UPDATE questions
SET translations = '{"en": "How do you feel about privacy in a relationship?", "da": "Hvordan har du det med privatliv i et forhold?", "de": "Kan du lide langsomme kys p\u00e5 din ryg og nakke?", "es": "H\u00e1 algo que gostarias que eu te chamasse quando fazemos sexo?", "pt": "H\u00e1 algo que gostarias que eu te chamasse quando fazemos sexo?", "ro": "Exist\u0103 ceva ce ai vrea s\u0103 te numesc c\u00e2nd facem dragoste?", "fr": "Y a-t-il quelque chose que tu aimerais que je t\u2019appelle quand on fait l\u2019amour ?", "it": "Come ti senti riguardo alla privacy in una relazione?", "fi": "Milt\u00e4 sinusta tuntuu yksityisyydest\u00e4 parisuhteessa?", "nl": "Hoe voel je je over privacy in een relatie?", "no": "Hvordan f\u00f8ler du om privatliv i et forhold?", "sv": "Hur k\u00e4nner du f\u00f6r integritet i en relation?", "pl": "Jak si\u0119 czujesz w kwestii prywatno\u015bci w zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about privacy in a relationship?';
UPDATE questions
SET translations = '{"en": "How do you feel when I post \u2014 or don\u2019t post \u2014 about us?", "da": "Hvordan har du det, n\u00e5r jeg poster \u2014 eller ikke poster \u2014 om os?", "de": "Hvad er \u00e9n ting ved vores sexliv, du gerne vil udforske dybere?", "es": "Exist\u0103 ceva ce ai vrea s\u0103 te numesc c\u00e2nd facem dragoste?", "pt": "Como te sentes quando eu publico \u2014 ou n\u00e3o publico \u2014 sobre n\u00f3s?", "ro": "Cum te sim\u021bi c\u00e2nd postez \u2014 sau nu postez \u2014 despre noi?", "fr": "Comment te sens-tu quand je publie \u2014 ou ne publie pas \u2014 sur nous ?", "it": "Come ti senti quando pubblico \u2014 o non pubblico \u2014 riguardo a noi?", "fi": "Milt\u00e4 sinusta tuntuu, kun julkaisen \u2014 tai en julkaise \u2014 meist\u00e4?", "nl": "Hoe voel je je als ik wel of niet over ons post?", "no": "Hvordan f\u00f8ler du n\u00e5r jeg legger ut \u2014 eller ikke legger ut \u2014 om oss?", "sv": "Hur k\u00e4nner du n\u00e4r jag postar \u2013 eller inte postar \u2013 om oss?", "pl": "Jak si\u0119 czujesz, gdy publikuj\u0119 \u2014 lub nie publikuj\u0119 \u2014 o nas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel when I post — or don’t post — about us?';
UPDATE questions
SET translations = '{"en": "Do you ever want to have children?", "da": "\u00d8nsker du nogensinde at f\u00e5 b\u00f8rn?", "de": "Hvilken form for tilbageholdenhed eller overgivelse synes du i hemmelighed er hot?", "es": "Y a-t-il quelque chose que tu aimerais que je t\u2019appelle quand on fait l\u2019amour ?", "pt": "Alguma vez quiseste ter filhos?", "ro": "\u021ai-ai dorit vreodat\u0103 s\u0103 ai copii?", "fr": "As-tu d\u00e9j\u00e0 voulu avoir des enfants ?", "it": "Vuoi mai avere dei figli?", "fi": "Haluatko joskus saada lapsia?", "nl": "Wil je ooit kinderen?", "no": "\u00d8nsker du noen gang \u00e5 f\u00e5 barn?", "sv": "Vill du n\u00e5gonsin ha barn?", "pl": "Czy kiedykolwiek chcesz mie\u0107 dzieci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you ever want to have children?';
UPDATE questions
SET translations = '{"en": "Do you from time to time check you ex social media out of curiosity?", "da": "Tjekker du nogensinde din eks\u2019 sociale medier af nysgerrighed?", "de": "Hvilken del af din krop ville du \u00f8nske, jeg ville v\u00e6re mere opm\u00e6rksom p\u00e5?", "es": "Welchen Teil deines K\u00f6rpers w\u00fcnschst du dir, dass ich mehr beachte?", "pt": "Espreitas \u00e0s vezes as redes sociais do teu ex por curiosidade?", "ro": "Verifici uneori re\u021belele de socializare ale fostului t\u0103u din curiozitate?", "fr": "Est-ce que tu regardes parfois les r\u00e9seaux sociaux de ton ex par curiosit\u00e9 ?", "it": "Controlli di tanto in tanto i social media del tuo ex per curiosit\u00e0?", "fi": "Tarkistatko joskus entisen kumppanisi sosiaalista mediaa uteliaisuudesta?", "nl": "Kijk je af en toe uit nieuwsgierigheid naar de sociale media van je ex?", "no": "Sjekker du av og til eksens sosiale medier av nysgjerrighet?", "sv": "Kollar du ibland p\u00e5 ditt ex:s sociala medier av nyfikenhet?", "pl": "Czy czasami sprawdzasz media spo\u0142eczno\u015bciowe swojego ex z ciekawo\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you from time to time check you ex social media out of curiosity?';
UPDATE questions
SET translations = '{"en": "How do you imagine our relationship evolving in the next few years?", "da": "Hvordan forestiller du dig, at vores forhold udvikler sig i de n\u00e6ste par \u00e5r?", "de": "Hvad synes du om at presse vores komfortzone med noget, der f\u00f8les en smule forbudt?", "es": "Wie findest du es, unsere Komfortzone mit etwas leicht Verbotenem zu erweitern?", "pt": "Como imaginas o nosso relacionamento a evoluir nos pr\u00f3ximos anos?", "ro": "Cum \u00ee\u021bi imaginezi c\u0103 se va dezvolta rela\u021bia noastr\u0103 \u00een urm\u0103torii ani?", "fr": "Comment imagines-tu notre relation dans les prochaines ann\u00e9es ?", "it": "Come immagini che la nostra relazione si evolver\u00e0 nei prossimi anni?", "fi": "Miten kuvittelet suhteemme kehittyv\u00e4n seuraavien vuosien aikana?", "nl": "Hoe stel je je voor dat onze relatie zich de komende jaren zal ontwikkelen?", "no": "Hvordan ser du for deg at forholdet v\u00e5rt vil utvikle seg de neste \u00e5rene?", "sv": "Hur f\u00f6rest\u00e4ller du dig att v\u00e5r relation utvecklas under de kommande \u00e5ren?", "pl": "Jak wyobra\u017casz sobie rozw\u00f3j naszej relacji w ci\u0105gu najbli\u017cszych kilku lat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you imagine our relationship evolving in the next few years?';
UPDATE questions
SET translations = '{"en": "Have you ever said \u201cI love you\u201d and not been sure you meant it? What did you learn from that?", "da": "Har du nogensinde sagt \u201cjeg elsker dig\u201d uden at v\u00e6re sikker p\u00e5, at du mente det? Hvad l\u00e6rte du af det?", "de": "Har du nogensinde holdt dig tilbage, fordi du ikke ville chokere mig?", "es": "Hast du dich jemals zur\u00fcckgehalten, weil du mich nicht schockieren wolltest?", "pt": "J\u00e1 disseste \u201camo-te\u201d sem ter a certeza de que o sentias? O que aprendeste com isso?", "ro": "Ai spus vreodat\u0103 \u201ete iubesc\u201d f\u0103r\u0103 s\u0103 fii sigur c\u0103 o sim\u021bi? Ce ai \u00eenv\u0103\u021bat din asta?", "fr": "As-tu d\u00e9j\u00e0 dit \u201cje t\u2019aime\u201d sans \u00eatre s\u00fbr de le penser ? Qu\u2019en as-tu appris ?", "it": "Hai mai detto \"ti amo\" senza essere sicuro di volerlo dire? Cosa hai imparato da questo?", "fi": "Oletko koskaan sanonut \"rakastan sinua\" etk\u00e4 ollut varma, ett\u00e4 tarkoitat sit\u00e4? Mit\u00e4 opit siit\u00e4?", "nl": "Heb je ooit \"Ik hou van je\" gezegd en niet zeker geweten of je het meende? Wat heb je daarvan geleerd?", "no": "Har du noen gang sagt \"jeg elsker deg\" og ikke v\u00e6rt sikker p\u00e5 om du mente det? Hva l\u00e6rte du av det?", "sv": "Har du n\u00e5gonsin sagt \"jag \u00e4lskar dig\" och inte varit s\u00e4ker p\u00e5 att du menade det? Vad l\u00e4rde du dig av det?", "pl": "Czy kiedykolwiek powiedzia\u0142e\u015b \u201ekocham ci\u0119\u201d i nie by\u0142e\u015b pewien, czy naprawd\u0119 to my\u015bla\u0142e\u015b? Czego si\u0119 z tego nauczy\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever said “I love you” and not been sure you meant it? What did you learn from that?';
UPDATE questions
SET translations = '{"en": "What\u2019s an opinion or belief you hold that most people wouldn\u2019t guess about you?", "da": "Hvilken holdning eller tro har du, som de fleste ikke ville g\u00e6tte om dig?", "de": "Hvad er noget legende, du ville \u00f8nske, vi gjorde oftere?", "es": "Was ist etwas Verspieltes, das du dir w\u00fcnschst, wir w\u00fcrden \u00f6fter tun?", "pt": "Que opini\u00e3o ou cren\u00e7a tens que a maioria n\u00e3o imaginaria sobre ti?", "ro": "Ce convingere ai pe care majoritatea nu ar ghici-o despre tine?", "fr": "Quelle opinion ou croyance as-tu que la plupart des gens ne devineraient pas \u00e0 ton sujet ?", "it": "Qual \u00e8 un''opinione o una convinzione che hai e che la maggior parte delle persone non indovinerebbe su di te?", "fi": "Mik\u00e4 on mielipide tai uskomus, jonka sinusta useimmat ihmiset eiv\u00e4t arvaisi?", "nl": "Wat is een mening of overtuiging die je hebt en waarvan de meeste mensen niet zouden raden dat je die hebt?", "no": "Hva er en mening eller tro du har som de fleste ikke ville gjettet om deg?", "sv": "Vilken \u00e5sikt eller tro har du som de flesta m\u00e4nniskor inte skulle gissa om dig?", "pl": "Jakie jest twoje zdanie lub przekonanie, kt\u00f3re wi\u0119kszo\u015b\u0107 ludzi by o tobie nie zgad\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s an opinion or belief you hold that most people wouldn’t guess about you?';
UPDATE questions
SET translations = '{"en": "Have you ever looked through someone\u2019s phone out of curiosity? Be honest.", "da": "Har du nogensinde kigget gennem nogens telefon af nysgerrighed? V\u00e6r \u00e6rlig.", "de": "Hvad er dit yndlingstidspunkt p\u00e5 dagen at blive intim?", "es": "Was ist deine Lieblingszeit am Tag, um intim zu werden?", "pt": "J\u00e1 espreitaste o telem\u00f3vel de algu\u00e9m por curiosidade? S\u00ea honesto.", "ro": "Ai verificat vreodat\u0103 telefonul cuiva din curiozitate? Fii sincer.", "fr": "As-tu d\u00e9j\u00e0 regard\u00e9 le t\u00e9l\u00e9phone de quelqu\u2019un par curiosit\u00e9 ? Sois honn\u00eate.", "it": "Hai mai guardato nel telefono di qualcuno per curiosit\u00e0? Sii onesto.", "fi": "Oletko koskaan katsellut jonkun puhelinta uteliaisuudesta? Ole rehellinen.", "nl": "Heb je ooit uit nieuwsgierigheid door iemands telefoon gekeken? Wees eerlijk.", "no": "Har du noen gang sett gjennom telefonen til noen av nysgjerrighet? V\u00e6r \u00e6rlig.", "sv": "Har du n\u00e5gonsin tittat igenom n\u00e5gons telefon av nyfikenhet? Var \u00e4rlig.", "pl": "Czy kiedykolwiek przeszuka\u0142e\u015b czyj\u015b telefon z ciekawo\u015bci? B\u0105d\u017a szczery."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever looked through someone’s phone out of curiosity? Be honest.';
UPDATE questions
SET translations = '{"en": "What was your first impression of me \u2014 be brutally honest.", "da": "Hvad var dit f\u00f8rste indtryk af mig \u2014 v\u00e6r brutalt \u00e6rlig.", "de": "Hvem af os er mest tilb\u00f8jelig til at starte noget og lade som om, det er uskyldigt?", "es": "Wer von uns f\u00e4ngt am ehesten etwas an und tut so, als w\u00e4re es unschuldig?", "pt": "Qual foi a tua primeira impress\u00e3o de mim \u2014 s\u00ea brutalmente honesto.", "ro": "Care a fost prima ta impresie despre mine \u2014 fii brutal de sincer.", "fr": "Quelle a \u00e9t\u00e9 ta premi\u00e8re impression de moi \u2014 sois brutalement honn\u00eate.", "it": "Qual \u00e8 stata la tua prima impressione di me \u2014 sii brutalmente onesto.", "fi": "Mik\u00e4 oli ensimm\u00e4inen vaikutelmasi minusta \u2014 ole t\u00e4ysin rehellinen.", "nl": "Wat was je eerste indruk van mij \u2014 wees eerlijk, ook al is het hard.", "no": "Hva var ditt f\u00f8rsteinntrykk av meg \u2014 v\u00e6r brutalt \u00e6rlig.", "sv": "Vad var ditt f\u00f6rsta intryck av mig \u2014 var brutalt \u00e4rlig.", "pl": "Jakie by\u0142o twoje pierwsze wra\u017cenie na m\u00f3j temat \u2014 b\u0105d\u017a brutalnie szczery."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What was your first impression of me — be brutally honest.';
UPDATE questions
SET translations = '{"en": "How do you feel about cancel culture or public shaming?", "da": "Hvordan har du det med cancel culture eller offentlig udskamning?", "de": "Hvem af os skjuler det v\u00e6rst, n\u00e5r vi er t\u00e6ndte?", "es": "Wer von uns kann seine Erregung am schlechtesten verbergen?", "pt": "O que pensas da \u201ccancel culture\u201d ou humilha\u00e7\u00e3o p\u00fablica?", "ro": "Ce p\u0103rere ai despre cultura anul\u0103rii sau ru\u0219inarea public\u0103?", "fr": "Que penses-tu de la \u201ccancel culture\u201d ou de la honte publique ?", "it": "Cosa ne pensi della cultura della cancellazione o della vergogna pubblica?", "fi": "Mit\u00e4 mielt\u00e4 olet peruutuskulttuurista tai julkisesta h\u00e4p\u00e4isyst\u00e4?", "nl": "Hoe voel je je over cancelcultuur of publieke beschaming?", "no": "Hva mener du om avbestillingskultur eller offentlig skam?", "sv": "Vad tycker du om avbokningskultur eller offentlig skam?", "pl": "Jak si\u0119 czujesz w kwestii kultury anulowania lub publicznego zawstydzania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about cancel culture or public shaming?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you like about my family, and one thing that\u2019s hard sometimes?", "da": "Hvad er \u00e9n ting, du kan lide ved min familie \u2014 og \u00e9n ting, der nogle gange er sv\u00e6r?", "de": "Hvem af os tror du mister fokus hurtigere, n\u00e5r flirten starter?", "es": "Wer von uns verliert schneller den Fokus, wenn das Flirten beginnt?", "pt": "O que gostas na minha fam\u00edlia \u2014 e o que \u00e0s vezes \u00e9 dif\u00edcil?", "ro": "Ce \u00ee\u021bi place la familia mea \u0219i ce e uneori dificil?", "fr": "Qu\u2019aimes-tu chez ma famille \u2014 et qu\u2019est-ce qui est parfois difficile ?", "it": "Qual \u00e8 una cosa che ti piace della mia famiglia e una cosa che a volte \u00e8 difficile?", "fi": "Mik\u00e4 on yksi asia, josta pid\u00e4t perheess\u00e4ni, ja yksi asia, joka on joskus vaikeaa?", "nl": "Wat is \u00e9\u00e9n ding dat je leuk vindt aan mijn familie, en \u00e9\u00e9n ding dat soms moeilijk is?", "no": "Hva er \u00e9n ting du liker med familien min, og \u00e9n ting som kan v\u00e6re vanskelig noen ganger?", "sv": "Vad \u00e4r en sak du gillar med min familj, och en sak som kan vara sv\u00e5r ibland?", "pl": "Co\u015b, co lubisz w mojej rodzinie, i co\u015b, co czasami bywa trudne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s one thing you like about my family, and one thing that’s hard sometimes?';
UPDATE questions
SET translations = '{"en": "Who from your past would make you a little nervous to bump into today \u2014 and why?", "da": "Hvem fra din fortid ville g\u00f8re dig lidt nerv\u00f8s, hvis du m\u00f8dte dem i dag \u2014 og hvorfor?", "de": "Hvem af os kan bedst lide at have kontrol?", "es": "Wer von uns mag es mehr, die Kontrolle zu haben?", "pt": "Quem do teu passado te deixaria nervoso se o encontrasses hoje \u2014 e porqu\u00ea?", "ro": "Cine din trecutul t\u0103u te-ar face pu\u021bin nervos dac\u0103 l-ai \u00eent\u00e2lni azi \u2014 \u0219i de ce?", "fr": "Qui de ton pass\u00e9 te rendrait un peu nerveux si tu le croisais aujourd\u2019hui \u2014 et pourquoi ?", "it": "Chi del tuo passato ti farebbe un po'' nervoso incontrare oggi \u2014 e perch\u00e9?", "fi": "Kuka menneisyydest\u00e4si saisi sinut tuntemaan itsesi hieman hermostuneeksi, jos kohtaisit h\u00e4net t\u00e4n\u00e4\u00e4n \u2014 ja miksi?", "nl": "Wie uit je verleden zou je een beetje nerveus maken om vandaag tegen te komen \u2014 en waarom?", "no": "Hvem fra fortiden din ville gjort deg litt nerv\u00f8s for \u00e5 m\u00f8te i dag \u2014 og hvorfor?", "sv": "Vem fr\u00e5n ditt f\u00f6rflutna skulle g\u00f6ra dig lite nerv\u00f6s att st\u00f6ta p\u00e5 idag \u2014 och varf\u00f6r?", "pl": "Kto z twojej przesz\u0142o\u015bci sprawi\u0142by, \u017ce poczu\u0142by\u015b si\u0119 troch\u0119 nerwowo, gdyby\u015b go dzisiaj spotka\u0142 \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who from your past would make you a little nervous to bump into today — and why?';
UPDATE questions
SET translations = '{"en": "How do you feel about how we each handle money?", "da": "Hvordan har du det med, hvordan vi hver is\u00e6r h\u00e5ndterer penge?", "de": "Hvem af os er mere tilb\u00f8jelig til at snige en flirtende besked i l\u00f8bet af dagen?", "es": "Wer von uns schickt eher eine flirtende Nachricht w\u00e4hrend des Tages?", "pt": "Como te sentes em rela\u00e7\u00e3o \u00e0 forma como cada um de n\u00f3s lida com o dinheiro?", "ro": "Cum te sim\u021bi legat de felul \u00een care fiecare dintre noi gestioneaz\u0103 banii?", "fr": "Que ressens-tu \u00e0 propos de notre mani\u00e8re respective de g\u00e9rer l\u2019argent ?", "it": "Come ti senti riguardo al modo in cui ciascuno di noi gestisce il denaro?", "fi": "Mit\u00e4 mielt\u00e4 olet siit\u00e4, miten me kumpikin k\u00e4sittelemme rahaa?", "nl": "Hoe voel je je over hoe wij elk met geld omgaan?", "no": "Hvordan f\u00f8ler du om hvordan vi hver for oss h\u00e5ndterer penger?", "sv": "Hur k\u00e4nner du f\u00f6r hur vi var och en hanterar pengar?", "pl": "Jak si\u0119 czujesz w kwestii tego, jak ka\u017cdy z nas radzi sobie z pieni\u0119dzmi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about how we each handle money?';
UPDATE questions
SET translations = '{"en": "What topic do you think couples should talk about before committing long-term?", "da": "Hvilket emne synes du, par b\u00f8r tale om, f\u00f8r de forpligter sig langsigtet?", "de": "Hvem af os ville starte et \"fem minutter\"-\u00f8jeblik, der bliver til en time?", "es": "Wer von uns w\u00fcrde ein \u201ef\u00fcnf Minuten\u201c-Moment beginnen, das zu einer Stunde wird?", "pt": "Que assunto achas que os casais deviam falar antes de se comprometerem a longo prazo?", "ro": "Despre ce subiect crezi c\u0103 ar trebui s\u0103 discute cuplurile \u00eenainte de a se angaja pe termen lung?", "fr": "Quel sujet les couples devraient-ils aborder avant de s\u2019engager \u00e0 long terme ?", "it": "Quale argomento pensi che le coppie dovrebbero discutere prima di impegnarsi a lungo termine?", "fi": "Mit\u00e4 aiheita luulet parien pit\u00e4isi k\u00e4sitell\u00e4 ennen pitk\u00e4n aikav\u00e4lin sitoutumista?", "nl": "Over welk onderwerp denk je dat stellen moeten praten voordat ze zich op de lange termijn binden?", "no": "Hvilket tema mener du at par b\u00f8r snakke om f\u00f8r de forplikter seg p\u00e5 lang sikt?", "sv": "Vilket \u00e4mne tycker du att par b\u00f6r prata om innan de f\u00f6rbinder sig p\u00e5 l\u00e5ng sikt?", "pl": "O jakim temacie uwa\u017casz, \u017ce pary powinny porozmawia\u0107 przed podj\u0119ciem d\u0142ugoterminowego zobowi\u0105zania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What topic do you think couples should talk about before committing long-term?';
UPDATE questions
SET translations = '{"en": "Have you ever loved two people at the same time?", "da": "Har du nogensinde elsket to personer p\u00e5 samme tid?", "de": "Hvad er din yndlingsm\u00e5de for mig at vise, at jeg higer efter dig?", "es": "Wie magst du es am liebsten, wenn ich dir zeige, dass ich dich begehre?", "pt": "J\u00e1 amaste duas pessoas ao mesmo tempo?", "ro": "Ai iubit vreodat\u0103 dou\u0103 persoane \u00een acela\u0219i timp?", "fr": "As-tu d\u00e9j\u00e0 aim\u00e9 deux personnes en m\u00eame temps ?", "it": "Hai mai amato due persone contemporaneamente?", "fi": "Oletko koskaan rakastanut kahta ihmist\u00e4 samaan aikaan?", "nl": "Heb je ooit twee mensen tegelijk liefgehad?", "no": "Har du noen gang elsket to personer samtidig?", "sv": "Har du n\u00e5gonsin \u00e4lskat tv\u00e5 personer samtidigt?", "pl": "Czy kiedykolwiek kocha\u0142e\u015b dwie osoby jednocze\u015bnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever loved two people at the same time?';
UPDATE questions
SET translations = '{"en": "What do you think makes conversations about politics or religion go wrong?", "da": "Hvad tror du g\u00f8r samtaler om politik eller religion s\u00e5 sv\u00e6re?", "de": "Hvor vigtig er \u00f8jenkontakt for dig, n\u00e5r vi er t\u00e6tte?", "es": "Wie wichtig ist dir Augenkontakt, wenn wir uns nah sind?", "pt": "Porque achas que conversas sobre pol\u00edtica ou religi\u00e3o correm mal?", "ro": "De ce crezi c\u0103 discu\u021biile despre politic\u0103 sau religie merg prost?", "fr": "Pourquoi penses-tu que les conversations sur la politique ou la religion tournent mal ?", "it": "Cosa pensi faccia andare male le conversazioni su politica o religione?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 saa keskustelut politiikasta tai uskonnosta menem\u00e4\u00e4n pieleen?", "nl": "Wat denk je dat gesprekken over politiek of religie verkeerd laten lopen?", "no": "Hva tror du gj\u00f8r at samtaler om politikk eller religion g\u00e5r galt?", "sv": "Vad tycker du g\u00f6r att samtal om politik eller religion g\u00e5r fel?", "pl": "Co twoim zdaniem sprawia, \u017ce rozmowy na temat polityki lub religii id\u0105 \u017ale?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you think makes conversations about politics or religion go wrong?';
UPDATE questions
SET translations = '{"en": "What\u2019s a fear or insecurity about the future that you rarely talk about?", "da": "Hvilken frygt eller usikkerhed om fremtiden taler du sj\u00e6ldent om?", "de": "Hvad er din yndlingsform for leg?", "es": "Was ist deine Lieblingsform des Spiels?", "pt": "Que medo ou inseguran\u00e7a sobre o futuro raramente falas?", "ro": "Ce fric\u0103 sau nesiguran\u021b\u0103 legat\u0103 de viitor discu\u021bi rar?", "fr": "Quelle peur ou ins\u00e9curit\u00e9 concernant l\u2019avenir \u00e9voques-tu rarement ?", "it": "Qual \u00e8 una paura o un''insicurezza riguardo al futuro di cui parli raramente?", "fi": "Mik\u00e4 on pelko tai ep\u00e4varmuus tulevaisuudesta, josta harvoin puhut?", "nl": "Wat is een angst of onzekerheid over de toekomst waar je zelden over praat?", "no": "Hva er en frykt eller usikkerhet om fremtiden som du sjelden snakker om?", "sv": "Vilken r\u00e4dsla eller os\u00e4kerhet om framtiden pratar du s\u00e4llan om?", "pl": "Jakie jest twoje l\u0119k lub niepewno\u015b\u0107 dotycz\u0105ca przysz\u0142o\u015bci, o kt\u00f3rym rzadko rozmawiasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s a fear or insecurity about the future that you rarely talk about?';
UPDATE questions
SET translations = '{"en": "What\u2019s the biggest trouble you ever got into \u2014 and what did it teach you?", "da": "Hvad er den st\u00f8rste ballade, du nogensinde har v\u00e6ret i \u2014 og hvad l\u00e6rte du af det?", "de": "Hvad betyder \"erfaring\" for dig i sengen \u2013 f\u00e6rdigheder, selvtillid, nysgerrighed?", "es": "Was bedeutet \u201eErfahrung\u201c f\u00fcr dich im Bett \u2013 K\u00f6nnen, Selbstvertrauen, Neugier?", "pt": "Qual foi o maior sarilho em que j\u00e1 te meteste \u2014 e o que aprendeste com isso?", "ro": "Care e cea mai mare belea \u00een care ai fost \u2014 \u0219i ce ai \u00eenv\u0103\u021bat din ea?", "fr": "Quelle est la plus grosse gal\u00e8re dans laquelle tu sois tomb\u00e9 \u2014 et qu\u2019en as-tu appris ?", "it": "Qual \u00e8 stato il problema pi\u00f9 grande in cui sei mai cacciato \u2014 e cosa ti ha insegnato?", "fi": "Mik\u00e4 on suurin ongelma, johon olet koskaan joutunut \u2014 ja mit\u00e4 se opetti sinulle?", "nl": "Wat is het grootste probleem waar je ooit in terecht bent gekomen \u2014 en wat heeft het je geleerd?", "no": "Hva er det st\u00f8rste problemet du noen gang har havnet i \u2013 og hva l\u00e6rte det deg?", "sv": "Vad \u00e4r det st\u00f6rsta problemet du n\u00e5gonsin hamnat i \u2014 och vad l\u00e4rde det dig?", "pl": "Jakie by\u0142o najwi\u0119ksze k\u0142opoty, w jakie kiedykolwiek si\u0119 wpakowa\u0142e\u015b \u2014 i czego ci\u0119 to nauczy\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s the biggest trouble you ever got into — and what did it teach you?';
UPDATE questions
SET translations = '{"en": "When you think about your past relationships, what stands out most \u2014 what you gave or what you lost?", "da": "N\u00e5r du t\u00e6nker p\u00e5 dine tidligere forhold, hvad st\u00e5r mest ud \u2014 det, du gav, eller det, du mistede?", "de": "Hvad er \u00e9n ting, du gerne vil lave med mig, som du aldrig har turdet n\u00e6vne f\u00f8r?", "es": "Was ist eine Sache, die du gerne mit mir tun w\u00fcrdest, dich aber nie getraut hast zu sagen?", "pt": "Quando pensas nas tuas rela\u00e7\u00f5es passadas, o que se destaca mais \u2014 o que deste ou o que perdeste?", "ro": "C\u00e2nd te g\u00e2nde\u0219ti la rela\u021biile tale anterioare, ce iese cel mai mult \u00een eviden\u021b\u0103 \u2014 ce ai oferit sau ce ai pierdut?", "fr": "Quand tu penses \u00e0 tes relations pass\u00e9es, qu\u2019est-ce qui te marque le plus \u2014 ce que tu as donn\u00e9 ou perdu ?", "it": "Quando pensi alle tue relazioni passate, cosa ti colpisce di pi\u00f9 \u2014 ci\u00f2 che hai dato o ci\u00f2 che hai perso?", "fi": "Kun ajattelet menneit\u00e4 suhteitasi, mik\u00e4 nousee eniten esiin \u2014 se, mit\u00e4 annoit vai se, mit\u00e4 menetit?", "nl": "Wanneer je aan je vorige relaties denkt, wat springt er dan het meest in het oog - wat je hebt gegeven of wat je hebt verloren?", "no": "N\u00e5r du tenker p\u00e5 dine tidligere forhold, hva st\u00e5r mest ut - hva du ga eller hva du mistet?", "sv": "N\u00e4r du t\u00e4nker p\u00e5 dina tidigare relationer, vad st\u00e5r ut mest \u2014 vad du gav eller vad du f\u00f6rlorade?", "pl": "Kiedy my\u015blisz o swoich przesz\u0142ych zwi\u0105zkach, co najbardziej si\u0119 wyr\u00f3\u017cnia \u2014 to, co da\u0142e\u015b, czy to, co straci\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When you think about your past relationships, what stands out most — what you gave or what you lost?';
UPDATE questions
SET translations = '{"en": "Do you think people today are too easily offended or not careful enough with words?", "da": "Synes du, folk i dag bliver for let forn\u00e6rmede eller ikke er forsigtige nok med ord?", "de": "Er der en side af dig, jeg stadig ikke har l\u00e5st op for endnu?", "es": "Gibt es eine Seite von dir, die ich noch nicht entdeckt habe?", "pt": "Achas que as pessoas hoje se ofendem com demasiada facilidade ou n\u00e3o t\u00eam cuidado com as palavras?", "ro": "Crezi c\u0103 oamenii ast\u0103zi se simt jigni\u021bi prea u\u0219or sau nu sunt suficient de aten\u021bi cu vorbele?", "fr": "Penses-tu que les gens aujourd\u2019hui sont trop facilement offens\u00e9s ou pas assez prudents avec leurs mots ?", "it": "Pensi che le persone di oggi si offendano troppo facilmente o che non siano abbastanza attente con le parole?", "fi": "Luuleeko, ett\u00e4 ihmiset t\u00e4n\u00e4 p\u00e4iv\u00e4n\u00e4 loukkaantuvat liian helposti vai eiv\u00e4t ole tarpeeksi varovaisia sanojensa kanssa?", "nl": "Denk je dat mensen vandaag de dag te snel beledigd zijn of niet voorzichtig genoeg met woorden omgaan?", "no": "Tror du folk i dag blir for lett forn\u00e6rmet, eller er de ikke forsiktige nok med ordene?", "sv": "Tycker du att folk idag \u00e4r f\u00f6r l\u00e4ttkr\u00e4nkta eller inte tillr\u00e4ckligt f\u00f6rsiktiga med sina ord?", "pl": "Czy uwa\u017casz, \u017ce ludzie dzisiaj s\u0105 zbyt \u0142atwo obra\u017cani, czy mo\u017ce nieostro\u017cni w doborze s\u0142\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you think people today are too easily offended or not careful enough with words?';
UPDATE questions
SET translations = '{"en": "How do you feel about earning more or less than your partner?", "da": "Hvordan har du det med at tjene mere eller mindre end din partner?", "de": "Hvilket af dine beg\u00e6r f\u00f8les stadig \"forbudt\", selvom det t\u00e6nder dig?", "es": "Welche deiner Begierden f\u00fchlt sich immer noch \u201everboten\u201c an, obwohl sie dich erregt?", "pt": "Como te sentes por ganhar mais ou menos do que o teu parceiro?", "ro": "Cum te sim\u021bi dac\u0103 c\u00e2\u0219tigi mai mult sau mai pu\u021bin dec\u00e2t partenerul t\u0103u?", "fr": "Que ressens-tu \u00e0 l\u2019id\u00e9e de gagner plus ou moins que ton partenaire ?", "it": "Come ti senti riguardo a guadagnare di pi\u00f9 o di meno rispetto al tuo partner?", "fi": "Milt\u00e4 sinusta tuntuu ansaita enemm\u00e4n tai v\u00e4hemm\u00e4n kuin kumppanisi?", "nl": "Hoe voel je je over het verdienen van meer of minder dan je partner?", "no": "Hvordan f\u00f8ler du om \u00e5 tjene mer eller mindre enn partneren din?", "sv": "Hur k\u00e4nner du f\u00f6r att tj\u00e4na mer eller mindre \u00e4n din partner?", "pl": "Jak si\u0119 czujesz w zwi\u0105zku z tym, \u017ce zarabiasz wi\u0119cej lub mniej ni\u017c tw\u00f3j partner?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about earning more or less than your partner?';
UPDATE questions
SET translations = '{"en": "What do you think your exes might say they learned from you?", "da": "Hvad tror du, dine eks\u2019er ville sige, de l\u00e6rte af dig?", "de": "Hvad f\u00e5r et \u00f8jeblik til at f\u00f8les dejligt forkert, men umuligt at modst\u00e5?", "es": "Was l\u00e4sst einen Moment sch\u00f6n falsch, aber unwiderstehlich f\u00fchlen?", "pt": "O que achas que os teus ex diriam que aprenderam contigo?", "ro": "Ce crezi c\u0103 ar spune fo\u0219tii t\u0103i c\u0103 au \u00eenv\u0103\u021bat de la tine?", "fr": "Que penses-tu que tes ex diraient avoir appris de toi ?", "it": "Cosa pensi che i tuoi ex possano dire di aver imparato da te?", "fi": "Mit\u00e4 luulet, mit\u00e4 entiset kumppanisi voisivat sanoa oppineensa sinulta?", "nl": "Wat denk je dat je exen zouden zeggen dat ze van jou hebben geleerd?", "no": "Hva tror du eksene dine ville sagt at de l\u00e6rte av deg?", "sv": "Vad tror du att dina ex kan s\u00e4ga att de har l\u00e4rt sig av dig?", "pl": "Co my\u015blisz, co twoje by\u0142e osoby mog\u0142yby powiedzie\u0107, \u017ce si\u0119 od ciebie nauczy\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you think your exes might say they learned from you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you sometimes judge others for \u2014 but also see a little of in yourself?", "da": "Hvad er noget, du nogle gange d\u00f8mmer andre for \u2014 men ogs\u00e5 ser lidt af i dig selv?", "de": "Hvilken slags hemmelighed mellem os ville du gerne beholde for evigt?", "es": "Welche Art von Geheimnis zwischen uns w\u00fcrdest du gerne f\u00fcr immer behalten?", "pt": "O que julgas \u00e0s vezes nos outros mas tamb\u00e9m v\u00eas em ti?", "ro": "Ce este ceva ce judeci la al\u021bii, dar recuno\u0219ti \u0219i \u00een tine?", "fr": "Quelle chose juges-tu parfois chez les autres mais reconnais-tu un peu chez toi ?", "it": "Qual \u00e8 qualcosa per cui a volte giudichi gli altri, ma che vedi anche un po'' in te stesso?", "fi": "Mik\u00e4 on jotain, jota joskus arvostelet muissa \u2014 mutta n\u00e4et my\u00f6s siit\u00e4 pienen osan itsess\u00e4si?", "nl": "Wat is iets waar je anderen soms op beoordeelt, maar waar je ook een beetje van in jezelf ziet?", "no": "Hva er noe du noen ganger d\u00f8mmer andre for \u2014 men ogs\u00e5 ser litt av i deg selv?", "sv": "Vad \u00e4r n\u00e5got du ibland d\u00f6mer andra f\u00f6r \u2014 men ocks\u00e5 ser lite av i dig sj\u00e4lv?", "pl": "Co\u015b, za co czasami oceniam innych \u2014 ale r\u00f3wnie\u017c dostrzegam to troch\u0119 w sobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you sometimes judge others for — but also see a little of in yourself?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you learned about yourself from your last relationship?", "da": "Hvad har du l\u00e6rt om dig selv fra dit sidste forhold?", "de": "Hvad er det f\u00f8rste, dine \u00f8jne g\u00e5r efter, n\u00e5r jeg begynder at kl\u00e6de mig af?", "es": "Wohin gehen deine Augen zuerst, wenn ich beginne, mich auszuziehen?", "pt": "O que aprendeste sobre ti mesmo com o teu \u00faltimo relacionamento?", "ro": "Ce ai \u00eenv\u0103\u021bat despre tine din ultima ta rela\u021bie?", "fr": "Qu\u2019as-tu appris sur toi-m\u00eame gr\u00e2ce \u00e0 ta derni\u00e8re relation ?", "it": "Qualcosa che hai imparato su te stesso dalla tua ultima relazione?", "fi": "Mit\u00e4 olet oppinut itsest\u00e4si edellisest\u00e4 suhteestasi?", "nl": "Wat is iets dat je over jezelf hebt geleerd van je laatste relatie?", "no": "Hva er noe du l\u00e6rte om deg selv fra ditt forrige forhold?", "sv": "Vad \u00e4r n\u00e5got du l\u00e4rde dig om dig sj\u00e4lv fr\u00e5n ditt senaste f\u00f6rh\u00e5llande?", "pl": "Co\u015b, czego si\u0119 nauczy\u0142e\u015b o sobie z ostatniego zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you learned about yourself from your last relationship?';
UPDATE questions
SET translations = '{"en": "When was a time jealousy actually taught you something about yourself?", "da": "Hvorn\u00e5r har jalousi faktisk l\u00e6rt dig noget om dig selv?", "de": "Hvilken smag ville du gerne smage p\u00e5 mine l\u00e6ber?", "es": "Welchen Geschmack w\u00fcrdest du gerne auf meinen Lippen schmecken?", "pt": "Quando \u00e9 que o ci\u00fame realmente te ensinou algo sobre ti pr\u00f3prio?", "ro": "C\u00e2nd te-a \u00eenv\u0103\u021bat gelozia ceva despre tine?", "fr": "Quand la jalousie t\u2019a-t-elle r\u00e9ellement appris quelque chose sur toi-m\u00eame ?", "it": "Quando \u00e8 stata una volta in cui la gelosia ti ha insegnato qualcosa su te stesso?", "fi": "Milloin kateus oikeasti opetti sinulle jotain itsest\u00e4si?", "nl": "Wanneer was een moment waarop jaloezie je daadwerkelijk iets over jezelf heeft geleerd?", "no": "N\u00e5r var det en gang sjalusi faktisk l\u00e6rte deg noe om deg selv?", "sv": "N\u00e4r var en tid d\u00e5 svartsjuka faktiskt l\u00e4rde dig n\u00e5got om dig sj\u00e4lv?", "pl": "Kiedy zazdro\u015b\u0107 nauczy\u0142a ci\u0119 czego\u015b o sobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When was a time jealousy actually taught you something about yourself?';
UPDATE questions
SET translations = '{"en": "What\u2019s something your best friend knows about you that I don\u2019t \u2014 yet?", "da": "Hvad ved din bedste ven om dig, som jeg ikke g\u00f8r \u2014 endnu?", "de": "Hvad ville du \u00f8nske, jeg gjorde oftere under forspil?", "es": "Was w\u00fcrdest du dir w\u00fcnschen, dass ich beim Vorspiel \u00f6fter tue?", "pt": "O que o teu melhor amigo sabe sobre ti que eu ainda n\u00e3o sei?", "ro": "Ce \u0219tie cel mai bun prieten al t\u0103u despre tine, dar eu nu?", "fr": "Qu\u2019est-ce que ton meilleur ami sait sur toi que je ne sais pas \u2014 encore ?", "it": "Qualcosa che il tuo migliore amico sa di te che io non so \u2014 ancora?", "fi": "Mik\u00e4 on jotain, mit\u00e4 paras yst\u00e4v\u00e4si tiet\u00e4\u00e4 sinusta, mutta min\u00e4 en \u2014 viel\u00e4?", "nl": "Wat is iets dat je beste vriend(in) over jou weet dat ik nog niet weet?", "no": "Hva er noe din beste venn vet om deg som jeg ikke vet \u2014 enn\u00e5?", "sv": "Vad \u00e4r det som din b\u00e4sta v\u00e4n vet om dig som jag inte vet \u2014 \u00e4n?", "pl": "Co\u015b, co tw\u00f3j najlepszy przyjaciel wie o tobie, a ja jeszcze nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something your best friend knows about you that I don’t — yet?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most impulsive or reckless thing you\u2019ve ever done just for the thrill?", "da": "Hvad er det mest impulsive eller hensynsl\u00f8se, du nogensinde har gjort bare for sp\u00e6ndingens skyld?", "de": "Hvilken slags belysning eller atmosf\u00e6re t\u00e6nder dig mest?", "es": "Welche Art von Licht oder Atmosph\u00e4re erregt dich am meisten?", "pt": "Qual foi a coisa mais impulsiva ou imprudente que j\u00e1 fizeste s\u00f3 pela emo\u00e7\u00e3o?", "ro": "Care este cel mai impulsiv sau nechibzuit lucru pe care l-ai f\u0103cut doar pentru adrenalin\u0103?", "fr": "Quelle est la chose la plus impulsive ou imprudente que tu aies faite juste pour le frisson ?", "it": "Qual \u00e8 la cosa pi\u00f9 impulsiva o avventata che hai mai fatto solo per il brivido?", "fi": "Mik\u00e4 on impulsiivisin tai holtittomin asia, jonka olet koskaan tehnyt vain j\u00e4nnityksen vuoksi?", "nl": "Wat is het meest impulsieve of roekeloze dat je ooit hebt gedaan, gewoon voor de spanning?", "no": "Hva er det mest impulsive eller hensynsl\u00f8se du noen gang har gjort bare for spenningen?", "sv": "Vad \u00e4r det mest impulsiva eller riskfyllda du n\u00e5gonsin har gjort bara f\u00f6r sp\u00e4nningens skull?", "pl": "Jak\u0105 najbardziej impulsywn\u0105 lub lekkomy\u015bln\u0105 rzecz kiedykolwiek zrobi\u0142e\u015b tylko dla dreszczyku emocji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s the most impulsive or reckless thing you’ve ever done just for the thrill?';
UPDATE questions
SET translations = '{"en": "What does financial independence mean to you in a relationship?", "da": "Hvad betyder \u00f8konomisk uafh\u00e6ngighed for dig i et forhold?", "de": "Hvordan kan du lide, at jeg viser dig, at jeg er i hum\u00f8r til det?", "es": "Wie magst du es, wenn ich dir zeige, dass ich in Stimmung bin?", "pt": "O que significa independ\u00eancia financeira para ti num relacionamento?", "ro": "Ce \u00eenseamn\u0103 independen\u021ba financiar\u0103 pentru tine \u00eentr-o rela\u021bie?", "fr": "Que signifie l\u2019ind\u00e9pendance financi\u00e8re pour toi dans une relation ?", "it": "Cosa significa per te l''indipendenza finanziaria in una relazione?", "fi": "Mit\u00e4 taloudellinen itsen\u00e4isyys merkitsee sinulle suhteessa?", "nl": "Wat betekent financi\u00eble onafhankelijkheid voor jou in een relatie?", "no": "Hva betyr \u00f8konomisk uavhengighet for deg i et forhold?", "sv": "Vad betyder ekonomisk oberoende f\u00f6r dig i en relation?", "pl": "Co dla Ciebie oznacza niezale\u017cno\u015b\u0107 finansowa w zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What does financial independence mean to you in a relationship?';
UPDATE questions
SET translations = '{"en": "How do you feel about your body right now?", "da": "Hvordan har du det med din krop lige nu?", "de": "Kan du lide, n\u00e5r jeg holder om dit ansigt eller dine hofter?", "es": "Magst du es, wenn ich dein Gesicht oder deine H\u00fcften halte?", "pt": "Como te sentes com o teu corpo neste momento?", "ro": "Cum te sim\u021bi \u00een leg\u0103tur\u0103 cu corpul t\u0103u acum?", "fr": "Comment te sens-tu par rapport \u00e0 ton corps en ce moment ?", "it": "Come ti senti riguardo al tuo corpo in questo momento?", "fi": "Milt\u00e4 sinusta tuntuu kehostasi juuri nyt?", "nl": "Hoe voel je je op dit moment over je lichaam?", "no": "Hvordan f\u00f8ler du deg om kroppen din akkurat n\u00e5?", "sv": "Hur k\u00e4nner du f\u00f6r din kropp just nu?", "pl": "Jak si\u0119 czujesz ze swoim cia\u0142em w tej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about your body right now?';
UPDATE questions
SET translations = '{"en": "Are you friends with your exes on social media? Why/why not?", "da": "Er du venner med dine ekser p\u00e5 sociale medier? Hvorfor/hvorfor ikke?", "de": "Hvad er din personlige definition af \"forf\u00f8rende\"?", "es": "Was ist deine pers\u00f6nliche Definition von \u201everf\u00fchrerisch\u201c?", "pt": "\u00c9s amigo dos teus ex nas redes sociais? Porqu\u00ea / porqu\u00ea n\u00e3o?", "ro": "E\u0219ti prieten cu fo\u0219tii t\u0103i pe re\u021belele sociale? De ce / de ce nu?", "fr": "Es-tu ami avec tes ex sur les r\u00e9seaux sociaux ? Pourquoi / pourquoi pas ?", "it": "Sei amico dei tuoi ex sui social media? Perch\u00e9 s\u00ec o perch\u00e9 no?", "fi": "Oletko yst\u00e4vi\u00e4 entisten kumppanien kanssa sosiaalisessa mediassa? Miksi/miksi ei?", "nl": "Ben je bevriend met je exen op sociale media? Waarom wel/niet?", "no": "Er du venn med eksene dine p\u00e5 sosiale medier? Hvorfor/hvorfor ikke?", "sv": "\u00c4r du v\u00e4nner med dina ex p\u00e5 sociala medier? Varf\u00f6r/varf\u00f6r inte?", "pl": "Czy jeste\u015b w przyja\u017ani z by\u0142ymi na mediach spo\u0142eczno\u015bciowych? Dlaczego/dlaczego nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Are you friends with your exes on social media? Why/why not?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the last person you looked up online just out of curiosity \u2014 and why?", "da": "Hvem er den sidste person, du slog op p\u00e5 online bare af nysgerrighed \u2014 og hvorfor?", "de": "Hvis nogen ville l\u00e6re pr\u00e6cis, hvordan de kunne behage dig, hvad er s\u00e5 det f\u00f8rste, de skulle v\u00e6re opm\u00e6rksomme p\u00e5?", "es": "Wenn jemand genau lernen wollte, wie man dich befriedigt \u2013 worauf sollte er als Erstes achten?", "pt": "Quem foi a \u00faltima pessoa que pesquisaste online por curiosidade \u2014 e porqu\u00ea?", "ro": "Cine e ultima persoan\u0103 pe care ai c\u0103utat-o online din curiozitate \u2014 \u0219i de ce?", "fr": "Quelle est la derni\u00e8re personne que tu as cherch\u00e9e en ligne par curiosit\u00e9 \u2014 et pourquoi ?", "it": "Chi \u00e8 stata l''ultima persona che hai cercato online per curiosit\u00e0 \u2014 e perch\u00e9?", "fi": "Kuka oli viimeinen henkil\u00f6, jota etsit verkosta uteliaisuudesta \u2014 ja miksi?", "nl": "Wie is de laatste persoon die je online hebt opgezocht uit nieuwsgierigheid \u2014 en waarom?", "no": "Hvem var den siste personen du s\u00f8kte opp p\u00e5 nettet bare av nysgjerrighet \u2014 og hvorfor?", "sv": "Vem var den senaste personen du s\u00f6kte p\u00e5 n\u00e4tet av ren nyfikenhet \u2014 och varf\u00f6r?", "pl": "Kto by\u0142 ostatni\u0105 osob\u0105, kt\u00f3r\u0105 wyszuka\u0142e\u015b w Internecie z ciekawo\u015bci \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who’s the last person you looked up online just out of curiosity — and why?';
UPDATE questions
SET translations = '{"en": "When\u2019s the last time you got caught in a small lie \u2014 and what did you learn from it?", "da": "Hvorn\u00e5r blev du sidst fanget i en lille l\u00f8gn \u2014 og hvad l\u00e6rte du af det?", "de": "Er der noget, du gerne vil have, at jeg kalder dig, n\u00e5r vi har sex?", "es": "Gibt es etwas, wie ich dich nennen soll, wenn wir Sex haben?", "pt": "Quando foi a \u00faltima vez que foste apanhado numa pequena mentira \u2014 e o que aprendeste?", "ro": "C\u00e2nd ai fost prins ultima dat\u0103 \u00eentr-o mic\u0103 minciun\u0103 \u2014 \u0219i ce ai \u00eenv\u0103\u021bat din asta?", "fr": "Quand t\u2019a-t-on pris pour la derni\u00e8re fois dans un petit mensonge \u2014 et qu\u2019en as-tu appris ?", "it": "Quando \u00e8 stata l''ultima volta che sei stato sorpreso in una piccola bugia \u2014 e cosa hai imparato da essa?", "fi": "Milloin viimeksi jouduit kiinni pienest\u00e4 valheesta \u2014 ja mit\u00e4 opit siit\u00e4?", "nl": "Wanneer was de laatste keer dat je betrapt werd op een klein leugentje \u2014 en wat heb je daaruit geleerd?", "no": "N\u00e5r var siste gang du ble tatt i en liten l\u00f8gn \u2014 og hva l\u00e6rte du av det?", "sv": "N\u00e4r var senaste g\u00e5ngen du blev tagen p\u00e5 en liten l\u00f6gn \u2014 och vad l\u00e4rde du dig av det?", "pl": "Kiedy ostatni raz wpad\u0142e\u015b w ma\u0142e k\u0142amstwo \u2014 i czego si\u0119 z tego nauczy\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When’s the last time you got caught in a small lie — and what did you learn from it?';
UPDATE questions
SET translations = '{"en": "Have you ever kept someone in your life longer than you should have?", "da": "Har du nogensinde beholdt nogen i dit liv l\u00e6ngere, end du burde have?", "de": "Hast du jemals jemanden l\u00e4nger in deinem Leben behalten, als du solltest?", "es": "\u00bfAlguna vez mantuviste a alguien en tu vida m\u00e1s tiempo del que deber\u00edas?", "pt": "J\u00e1 mantiveste algu\u00e9m na tua vida por mais tempo do que devias?", "ro": "Ai \u021binut vreodat\u0103 pe cineva \u00een via\u021ba ta mai mult dec\u00e2t trebuia?", "fr": "As-tu d\u00e9j\u00e0 gard\u00e9 quelqu\u2019un dans ta vie plus longtemps que tu n\u2019aurais d\u00fb ?", "it": "Hai mai tenuto qualcuno nella tua vita pi\u00f9 a lungo di quanto avresti dovuto?", "fi": "Oletko koskaan pit\u00e4nyt jotakuta el\u00e4m\u00e4ss\u00e4si pidemp\u00e4\u00e4n kuin olisi pit\u00e4nyt?", "nl": "Heb je ooit iemand langer in je leven gehouden dan je eigenlijk zou moeten?", "no": "Har du noen gang hatt noen i livet ditt lenger enn du burde?", "sv": "Har du n\u00e5gonsin haft n\u00e5gon i ditt liv l\u00e4ngre \u00e4n du borde?", "pl": "Czy kiedykolwiek trzyma\u0142e\u015b kogo\u015b w swoim \u017cyciu d\u0142u\u017cej, ni\u017c powiniene\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever kept someone in your life longer than you should have?';
UPDATE questions
SET translations = '{"en": "How do you handle it when you disagree deeply with someone you love?", "da": "Hvordan h\u00e5ndterer du det, n\u00e5r du er uenig med nogen, du elsker?", "de": "Wie gehst du damit um, wenn du mit jemandem, den du liebst, tief uneinig bist?", "es": "\u00bfC\u00f3mo manejas el estar en desacuerdo con alguien a quien amas?", "pt": "Como lidas quando discordas profundamente de algu\u00e9m que amas?", "ro": "Cum gestionezi o ne\u00een\u021belegere profund\u0103 cu cineva pe care \u00eel iube\u0219ti?", "fr": "Comment g\u00e8res-tu un d\u00e9saccord profond avec quelqu\u2019un que tu aimes ?", "it": "Come gestisci la situazione quando non sei d''accordo profondamente con qualcuno che ami?", "fi": "Miten toimit, kun olet syv\u00e4sti eri mielt\u00e4 jonkun rakastamasi kanssa?", "nl": "Hoe ga je ermee om als je diep van mening verschilt met iemand van wie je houdt?", "no": "Hvordan h\u00e5ndterer du det n\u00e5r du er dypt uenig med noen du elsker?", "sv": "Hur hanterar du det n\u00e4r du har djupa meningsskiljaktigheter med n\u00e5gon du \u00e4lskar?", "pl": "Jak radzisz sobie, gdy g\u0142\u0119boko si\u0119 z kim\u015b, kogo kochasz, nie zgadzasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you handle it when you disagree deeply with someone you love?';
UPDATE questions
SET translations = '{"en": "Is there a public figure whose ideas you secretly respect, even if most people around you don\u2019t?", "da": "Er der en offentlig person, hvis ideer du hemmeligt respekterer, selvom de fleste omkring dig ikke g\u00f8r?", "de": "Gibt es eine \u00f6ffentliche Person, deren Ideen du heimlich respektierst, auch wenn die meisten um dich herum es nicht tun?", "es": "\u00bfHay una figura p\u00fablica cuyas ideas respetas en secreto, aunque la mayor\u00eda a tu alrededor no?", "pt": "H\u00e1 uma figura p\u00fablica cujas ideias respeitas secretamente, mesmo que a maioria \u00e0 tua volta n\u00e3o?", "ro": "Exist\u0103 o persoan\u0103 public\u0103 ale c\u0103rei idei le respec\u021bi \u00een secret, chiar dac\u0103 majoritatea nu?", "fr": "Y a-t-il une personnalit\u00e9 publique dont tu respectes secr\u00e8tement les id\u00e9es, m\u00eame si la plupart ne le font pas ?", "it": "C''\u00e8 una figura pubblica le cui idee rispetti segretamente, anche se la maggior parte delle persone intorno a te non lo fa?", "fi": "Onko olemassa julkista henkil\u00f6\u00e4, jonka ajatuksia salaa kunnioitat, vaikka useimmat ymp\u00e4rill\u00e4si eiv\u00e4t?", "nl": "Is er een publieke figuur wiens idee\u00ebn je stiekem respecteert, ook al doen de meeste mensen om je heen dat niet?", "no": "Er det en offentlig person hvis ideer du hemmelig respekterer, selv om de fleste rundt deg ikke gj\u00f8r det?", "sv": "Finns det en offentlig person vars id\u00e9er du hemligt respekterar, \u00e4ven om de flesta omkring dig inte g\u00f6r det?", "pl": "Czy jest jaka\u015b posta\u0107 publiczna, kt\u00f3rej pomys\u0142y potajemnie szanujesz, nawet je\u015bli wi\u0119kszo\u015b\u0107 ludzi wok\u00f3\u0142 ciebie ich nie docenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Is there a public figure whose ideas you secretly respect, even if most people around you don’t?';
UPDATE questions
SET translations = '{"en": "Have you ever felt a little jealous of someone close to me? What made you feel that way?", "da": "Har du nogensinde v\u00e6ret lidt jaloux p\u00e5 nogen t\u00e6t p\u00e5 mig? Hvad fik dig til at f\u00f8le s\u00e5dan?", "de": "Warst du jemals ein bisschen eifers\u00fcchtig auf jemanden, der mir nahe steht? Was hat dich so f\u00fchlen lassen?", "es": "\u00bfAlguna vez te has sentido un poco celoso de alguien cercano a m\u00ed? \u00bfQu\u00e9 te hizo sentir as\u00ed?", "pt": "Alguma vez sentiste um pouco de ci\u00fames de algu\u00e9m pr\u00f3ximo de mim? O que te fez sentir assim?", "ro": "Te-ai sim\u021bit vreodat\u0103 pu\u021bin gelos pe cineva apropiat mie? Ce te-a f\u0103cut s\u0103 sim\u021bi asta?", "fr": "As-tu d\u00e9j\u00e0 \u00e9t\u00e9 un peu jaloux de quelqu\u2019un de proche de moi ? Qu\u2019est-ce qui t\u2019a fait ressentir \u00e7a ?", "it": "Hai mai provato un po'' di gelosia nei confronti di qualcuno a me vicino? Cosa ti ha fatto sentire in questo modo?", "fi": "Oletko koskaan tuntenut pient\u00e4 kateutta jotakuta l\u00e4heist\u00e4ni kohtaan? Mik\u00e4 sai sinut tuntemaan niin?", "nl": "Heb je ooit een beetje jaloers gevoeld op iemand die dicht bij me staat? Wat deed je zo voelen?", "no": "Har du noen gang f\u00f8lt deg litt sjalu p\u00e5 noen som st\u00e5r meg n\u00e6r? Hva fikk deg til \u00e5 f\u00f8le det slik?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig lite avundsjuk p\u00e5 n\u00e5gon som st\u00e5r mig n\u00e4ra? Vad fick dig att k\u00e4nna s\u00e5?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 troch\u0119 zazdrosny o kogo\u015b bliskiego mi? Co sprawi\u0142o, \u017ce tak si\u0119 poczu\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever felt a little jealous of someone close to me? What made you feel that way?';
UPDATE questions
SET translations = '{"en": "Who from your past do you still think about sometimes \u2014 and in what way?", "da": "Hvem fra din fortid t\u00e6nker du stadig p\u00e5 nogle gange \u2014 og hvordan?", "de": "An wen aus deiner Vergangenheit denkst du manchmal noch \u2013 und in welcher Weise?", "es": "\u00bfA qui\u00e9n de tu pasado sigues pensando a veces \u2014 y de qu\u00e9 manera?", "pt": "Em quem do teu passado ainda pensas \u00e0s vezes \u2014 e de que forma?", "ro": "La cine din trecut te mai g\u00e2nde\u0219ti uneori \u2014 \u0219i \u00een ce fel?", "fr": "\u00c0 qui de ton pass\u00e9 penses-tu encore parfois \u2014 et de quelle mani\u00e8re ?", "it": "Chi del tuo passato pensi ancora a volte \u2014 e in che modo?", "fi": "Kuka menneisyydest\u00e4si tulee joskus mieleesi \u2014 ja mill\u00e4 tavalla?", "nl": "Wie uit je verleden denk je soms nog aan \u2014 en op welke manier?", "no": "Hvem fra fortiden din tenker du fortsatt p\u00e5 noen ganger \u2014 og p\u00e5 hvilken m\u00e5te?", "sv": "Vem fr\u00e5n ditt f\u00f6rflutna t\u00e4nker du fortfarande p\u00e5 ibland \u2014 och p\u00e5 vilket s\u00e4tt?", "pl": "Kto z twojej przesz\u0142o\u015bci czasami przychodzi ci na my\u015bl \u2014 i w jaki spos\u00f3b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who from your past do you still think about sometimes — and in what way?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people often misunderstand about you?", "da": "Hvad misforst\u00e5r folk ofte om dig?", "de": "Was missverstehen die Leute oft an dir?", "es": "\u00bfQu\u00e9 es algo que la gente suele malinterpretar sobre ti?", "pt": "O que \u00e9 algo que as pessoas geralmente interpretam mal sobre ti?", "ro": "Ce crezi c\u0103 oamenii \u00een\u021beleg gre\u0219it despre tine?", "fr": "Qu\u2019est-ce que les gens comprennent souvent mal \u00e0 ton sujet ?", "it": "Qualcosa che le persone fraintendono spesso su di te?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset usein v\u00e4\u00e4rin ymm\u00e4rt\u00e4v\u00e4t sinusta?", "nl": "Wat is iets dat mensen vaak verkeerd begrijpen over jou?", "no": "Hva er noe folk ofte misforst\u00e5r om deg?", "sv": "Vad \u00e4r n\u00e5got som folk ofta missf\u00f6rst\u00e5r om dig?", "pl": "Co\u015b, co ludzie cz\u0119sto \u017ale rozumiej\u0105 na tw\u00f3j temat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something people often misunderstand about you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019d love for my parents to know about you someday?", "da": "Hvad er noget, du gerne vil have, mine for\u00e6ldre skal vide om dig en dag?", "de": "Was m\u00f6chtest du, dass meine Eltern eines Tages \u00fcber dich wissen?", "es": "\u00bfQu\u00e9 te gustar\u00eda que mis padres supieran sobre ti alg\u00fan d\u00eda?", "pt": "O que gostarias que os meus pais soubessem sobre ti um dia?", "ro": "Ce \u021bi-ar pl\u0103cea ca p\u0103rin\u021bii mei s\u0103 afle despre tine \u00eentr-o zi?", "fr": "Qu\u2019aimerais-tu que mes parents sachent de toi un jour ?", "it": "Qualcosa che ti piacerebbe che i miei genitori sapessero di te un giorno?", "fi": "Mik\u00e4 on jotain, jonka haluaisit vanhempieni tiet\u00e4v\u00e4n sinusta joskus?", "nl": "Wat is iets dat je zou willen dat mijn ouders ooit over jou weten?", "no": "Hva er noe du gjerne skulle \u00f8nsket at foreldrene mine visste om deg en dag?", "sv": "Vad \u00e4r det som du skulle vilja att mina f\u00f6r\u00e4ldrar fick veta om dig n\u00e5gon g\u00e5ng?", "pl": "Co\u015b, co chcia\u0142by\u015b, aby moi rodzice kiedy\u015b o tobie wiedzieli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you’d love for my parents to know about you someday?';
UPDATE questions
SET translations = '{"en": "Hand me your phone \u2014 I get to scroll through your photos for ten seconds.", "da": "Giv mig din telefon \u2014 jeg f\u00e5r lov til at rulle gennem dine billeder i ti sekunder.", "de": "Gib mir dein Handy \u2013 ich darf zehn Sekunden lang durch deine Fotos scrollen.", "es": "Dame tu tel\u00e9fono \u2014 puedo desplazarme por tus fotos durante diez segundos.", "pt": "D\u00e1-me o teu telem\u00f3vel \u2014 posso ver as tuas fotos por dez segundos.", "ro": "D\u0103-mi telefonul t\u0103u \u2014 pot derula prin fotografiile tale zece secunde.", "fr": "Passe-moi ton t\u00e9l\u00e9phone \u2014 j\u2019ai dix secondes pour faire d\u00e9filer tes photos.", "it": "Passami il tuo telefono \u2014 posso scorrere le tue foto per dieci secondi.", "fi": "Anna puhelimesi \u2014 saan selata valokuviasi kymmenen sekuntia.", "nl": "Geef me je telefoon \u2014 ik mag tien seconden door je foto''s scrollen.", "no": "Gi meg telefonen din \u2014 jeg f\u00e5r bla gjennom bildene dine i ti sekunder.", "sv": "Ge mig din telefon \u2014 jag f\u00e5r bl\u00e4ddra igenom dina bilder i tio sekunder.", "pl": "Podaj mi sw\u00f3j telefon \u2014 mog\u0119 przegl\u0105da\u0107 twoje zdj\u0119cia przez dziesi\u0119\u0107 sekund."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Hand me your phone — I get to scroll through your photos for ten seconds.';
UPDATE questions
SET translations = '{"en": "Have you ever felt judged for something you believe in?", "da": "Har du nogensinde f\u00f8lt dig d\u00f8mt for noget, du tror p\u00e5?", "de": "Hast du dich jemals f\u00fcr etwas, woran du glaubst, verurteilt gef\u00fchlt?", "es": "\u00bfAlguna vez te has sentido juzgado por algo en lo que crees?", "pt": "Alguma vez sentiste que foste julgado por algo em que acreditas?", "ro": "Te-ai sim\u021bit vreodat\u0103 judecat pentru ceva \u00een care crezi?", "fr": "T\u2019es-tu d\u00e9j\u00e0 senti jug\u00e9 pour quelque chose en quoi tu crois ?", "it": "Hai mai sentito di essere giudicato per qualcosa in cui credi?", "fi": "Oletko koskaan tuntenut, ett\u00e4 sinua on arvosteltu jostain, mihin uskot?", "nl": "Heb je ooit het gevoel gehad beoordeeld te worden om iets waar je in gelooft?", "no": "Har du noen gang f\u00f8lt deg d\u00f8mt for noe du tror p\u00e5?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig d\u00f6md f\u00f6r n\u00e5got du tror p\u00e5?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 oceniany za co\u015b, w co wierzysz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever felt judged for something you believe in?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think I don\u2019t give myself enough credit for?", "da": "Hvad tror du, jeg ikke giver mig selv nok ros for?", "de": "Was glaubst du, wof\u00fcr ich mir selbst nicht genug Anerkennung gebe?", "es": "\u00bfPor qu\u00e9 cosa crees que no me doy suficiente cr\u00e9dito?", "pt": "Pelo que achas que n\u00e3o me dou cr\u00e9dito suficiente?", "ro": "Pentru ce crezi c\u0103 nu \u00eemi dau suficient merit?", "fr": "Pour quoi penses-tu que je ne me donne pas assez de cr\u00e9dit ?", "it": "Qual \u00e8 una cosa per cui pensi che non mi dia abbastanza credito?", "fi": "Mik\u00e4 on jotain, mist\u00e4 luulet, etten anna itselleni tarpeeksi krediitti\u00e4?", "nl": "Wat is iets waarvan je denkt dat ik mezelf niet genoeg krediet geef?", "no": "Hva er noe du mener jeg ikke gir meg selv nok kreditt for?", "sv": "Vad \u00e4r n\u00e5got du tycker att jag inte ger mig sj\u00e4lv tillr\u00e4ckligt med ber\u00f6m f\u00f6r?", "pl": "Co\u015b, za co my\u015blisz, \u017ce nie doceniam siebie wystarczaj\u0105co?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you think I don’t give myself enough credit for?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019d love us to try together but haven\u2019t yet?", "da": "Hvad er noget, du gerne vil have, vi pr\u00f8ver sammen, men endnu ikke har gjort?", "de": "Was w\u00fcrdest du gerne mit mir ausprobieren, was wir noch nicht getan haben?", "es": "\u00bfQu\u00e9 te gustar\u00eda que prob\u00e1ramos juntos pero a\u00fan no hemos hecho?", "pt": "O que gostarias que tent\u00e1ssemos juntos mas ainda n\u00e3o fizemos?", "ro": "Ce ai vrea s\u0103 \u00eencerc\u0103m \u00eempreun\u0103, dar nu am f\u0103cut \u00eenc\u0103?", "fr": "Qu\u2019aimerais-tu que nous essayions ensemble mais que nous n\u2019avons pas encore fait ?", "it": "Qualcosa che ti piacerebbe provare insieme ma non abbiamo ancora fatto?", "fi": "Mik\u00e4 on jotain, mit\u00e4 haluaisit meid\u00e4n kokeilevan yhdess\u00e4, mutta emme ole viel\u00e4 tehneet?", "nl": "Wat is iets dat je graag samen met ons zou willen proberen, maar dat we nog niet hebben gedaan?", "no": "Hva er noe du gjerne vil at vi skal pr\u00f8ve sammen, men som vi ikke har gjort enn\u00e5?", "sv": "Vad \u00e4r n\u00e5got du skulle vilja att vi provar tillsammans men inte har gjort \u00e4n?", "pl": "Co\u015b, co chcieliby\u015bmy spr\u00f3bowa\u0107 razem, ale jeszcze tego nie zrobili\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you’d love us to try together but haven’t yet?';
UPDATE questions
SET translations = '{"en": "How do you think your exes would describe you as a partner?", "da": "Hvordan tror du, dine ekser ville beskrive dig som partner?", "de": "Wie w\u00fcrden dich deine Ex-Partner als Partner beschreiben?", "es": "\u00bfC\u00f3mo crees que tus ex te describir\u00edan como pareja?", "pt": "Como achas que os teus ex te descreveriam como parceiro?", "ro": "Cum crezi c\u0103 te-ar descrie fo\u0219tii t\u0103i ca partener?", "fr": "Comment penses-tu que tes ex te d\u00e9criraient comme partenaire ?", "it": "Come pensi che i tuoi ex ti descriverebbero come partner?", "fi": "Miten luulet, ett\u00e4 eks\u00e4si kuvailisivat sinua kumppanina?", "nl": "Hoe denk je dat je exen jou als partner zouden beschrijven?", "no": "Hvordan tror du eksene dine ville beskrevet deg som partner?", "sv": "Hur tror du att dina ex skulle beskriva dig som partner?", "pl": "Jak my\u015blisz, jak twoje by\u0142e partnerki/partnerzy opisaliby ci\u0119 jako partnera?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you think your exes would describe you as a partner?';
UPDATE questions
SET translations = '{"en": "How do you feel about getting older?", "da": "Hvordan har du det med at blive \u00e6ldre?", "de": "Wie f\u00fchlst du dich, wenn du \u00e4lter wirst?", "es": "\u00bfC\u00f3mo te sientes respecto a envejecer?", "pt": "Como te sentes em rela\u00e7\u00e3o a envelhecer?", "ro": "Cum te sim\u021bi \u00een leg\u0103tur\u0103 cu \u00eemb\u0103tr\u00e2nirea?", "fr": "Comment te sens-tu \u00e0 propos du fait de vieillir ?", "it": "Come ti senti riguardo all''invecchiare?", "fi": "Milt\u00e4 sinusta tuntuu vanhenemisesta?", "nl": "Hoe voel je je over ouder worden?", "no": "Hvordan f\u00f8ler du om \u00e5 bli eldre?", "sv": "Hur k\u00e4nner du inf\u00f6r att bli \u00e4ldre?", "pl": "Jak si\u0119 czujesz z powodu starzenia si\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about getting older?';
UPDATE questions
SET translations = '{"en": "Stare into my eyes for thirty seconds without laughing or looking away.", "da": "Stir mig i \u00f8jnene i tredive sekunder uden at grine eller kigge v\u00e6k.", "de": "Schau mir drei\u00dfig Sekunden lang in die Augen, ohne zu lachen oder wegzuschauen.", "es": "M\u00edrame a los ojos durante treinta segundos sin re\u00edrte ni mirar hacia otro lado.", "pt": "Olha-me nos olhos durante trinta segundos sem rir nem desviar o olhar.", "ro": "Prive\u0219te-m\u0103 \u00een ochi treizeci de secunde f\u0103r\u0103 s\u0103 r\u00e2zi sau s\u0103 te ui\u021bi \u00een alt\u0103 parte.", "fr": "Regarde-moi dans les yeux pendant trente secondes sans rire ni d\u00e9tourner le regard.", "it": "Guarda nei miei occhi per trenta secondi senza ridere o distogliere lo sguardo.", "fi": "Tuijota silmiini kolmekymment\u00e4 sekuntia nauramatta tai k\u00e4\u00e4nt\u00e4m\u00e4tt\u00e4 katsetta pois.", "nl": "Kijk dertig seconden in mijn ogen zonder te lachen of weg te kijken.", "no": "Se inn i \u00f8ynene mine i tretti sekunder uten \u00e5 le eller se bort.", "sv": "Stir in mina \u00f6gon i trettio sekunder utan att skratta eller titta bort.", "pl": "Patrz mi w oczy przez trzydzie\u015bci sekund, nie \u015bmiej\u0105c si\u0119 i nie odwracaj\u0105c wzroku."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Stare into my eyes for thirty seconds without laughing or looking away.';
UPDATE questions
SET translations = '{"en": "What\u2019s one little thing that makes you jealous?", "da": "Hvad er en lille ting, der g\u00f8r dig jaloux?", "de": "Was ist eine kleine Sache, die dich eifers\u00fcchtig macht?", "es": "\u00bfQu\u00e9 peque\u00f1a cosa te pone celoso?", "pt": "Que pequena coisa te deixa com ci\u00fames?", "ro": "Ce lucru mic te face gelos?", "fr": "Quelle petite chose te rend jaloux ?", "it": "Qual \u00e8 una piccola cosa che ti fa sentire geloso?", "fi": "Mik\u00e4 on yksi pieni asia, joka saa sinut kateelliseksi?", "nl": "Wat is \u00e9\u00e9n klein dingetje dat je jaloers maakt?", "no": "Hva er en liten ting som gj\u00f8r deg sjalu?", "sv": "Vad \u00e4r en liten sak som g\u00f6r dig avundsjuk?", "pl": "Co to za ma\u0142a rzecz, kt\u00f3ra ci\u0119 zazdro\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s one little thing that makes you jealous?';
UPDATE questions
SET translations = '{"en": "What\u2019s your guiltiest pleasure?", "da": "Hvad er din skyldigste forn\u00f8jelse?", "de": "Was ist dein heimlichstes Vergn\u00fcgen?", "es": "\u00bfCu\u00e1l es tu placer m\u00e1s culpable?", "pt": "Qual \u00e9 o teu prazer mais culpado?", "ro": "Care este pl\u0103cerea ta vinovat\u0103?", "fr": "Quel est ton plaisir coupable ?", "it": "Qual \u00e8 il tuo piacere pi\u00f9 colpevole?", "fi": "Mik\u00e4 on suurin syyllisyyden aiheuttava nautintosi?", "nl": "Wat is jouw grootste schuldgevoel genot?", "no": "Hva er din st\u00f8rste skyldf\u00f8lelse glede?", "sv": "Vad \u00e4r din st\u00f6rsta skuldfria njutning?", "pl": "Jakie jest twoje najwi\u0119ksze guilty pleasure?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s your guiltiest pleasure?';
UPDATE questions
SET translations = '{"en": "When did you realize you liked me more than just a friend?", "da": "Hvorn\u00e5r gik det op for dig, at du kunne lide mig mere end bare som ven?", "de": "Wann hast du gemerkt, dass du mich mehr magst als nur als Freund?", "es": "\u00bfCu\u00e1ndo te diste cuenta de que te gustaba m\u00e1s que solo como amigo?", "pt": "Quando percebeste que gostavas de mim mais do que apenas como amigo?", "ro": "C\u00e2nd \u021bi-ai dat seama c\u0103 m\u0103 placi mai mult dec\u00e2t ca prieten?", "fr": "Quand as-tu r\u00e9alis\u00e9 que tu m\u2019aimais plus que comme un ami ?", "it": "Quando hai capito che mi piacevi pi\u00f9 di un semplice amico?", "fi": "Milloin tajusit, ett\u00e4 pid\u00e4t minusta enemm\u00e4n kuin vain yst\u00e4v\u00e4n\u00e4?", "nl": "Wanneer besefte je dat je me meer leuk vond dan alleen een vriend?", "no": "N\u00e5r inns\u00e5 du at du likte meg mer enn bare som en venn?", "sv": "N\u00e4r ins\u00e5g du att du gillade mig mer \u00e4n bara som en v\u00e4n?", "pl": "Kiedy zda\u0142e\u015b sobie spraw\u0119, \u017ce lubisz mnie bardziej ni\u017c tylko jako przyjaciela?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When did you realize you liked me more than just a friend?';
UPDATE questions
SET translations = '{"en": "How do you feel when people talk about politics or religion at social gatherings?", "da": "Hvordan har du det, n\u00e5r folk taler om politik eller religion til sociale sammenkomster?", "de": "Wie f\u00fchlst du dich, wenn Menschen bei gesellschaftlichen Treffen \u00fcber Politik oder Religion sprechen?", "es": "\u00bfC\u00f3mo te sientes cuando la gente habla de pol\u00edtica o religi\u00f3n en reuniones sociales?", "pt": "Como te sentes quando as pessoas falam de pol\u00edtica ou religi\u00e3o em encontros sociais?", "ro": "Cum te sim\u021bi c\u00e2nd oamenii vorbesc despre politic\u0103 sau religie la \u00eent\u00e2lniri sociale?", "fr": "Que ressens-tu quand les gens parlent de politique ou de religion lors d\u2019\u00e9v\u00e9nements sociaux ?", "it": "Come ti senti quando le persone parlano di politica o religione durante gli incontri sociali?", "fi": "Milt\u00e4 sinusta tuntuu, kun ihmiset puhuvat politiikasta tai uskonnosta sosiaalisissa tilaisuuksissa?", "nl": "Hoe voel je je als mensen op sociale bijeenkomsten over politiek of religie praten?", "no": "Hvordan f\u00f8ler du deg n\u00e5r folk snakker om politikk eller religion p\u00e5 sosiale sammenkomster?", "sv": "Hur k\u00e4nner du n\u00e4r folk pratar om politik eller religion vid sociala tillst\u00e4llningar?", "pl": "Jak si\u0119 czujesz, gdy ludzie rozmawiaj\u0105 o polityce lub religii na spotkaniach towarzyskich?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel when people talk about politics or religion at social gatherings?';