UPDATE questions
SET translations = '{"en": "Who\u2019s the biggest overthinker before a night out?", "da": "Hvem overt\u00e6nker mest f\u00f8r en aften i byen?", "de": "Wer denkt vor einem Abend am meisten zu viel nach?", "es": "\u00bfQui\u00e9n es el que m\u00e1s piensa antes de salir de noche?", "pt": "Quem pensa demais antes de uma sa\u00edda \u00e0 noite?", "ro": "Cine g\u00e2nde\u0219te prea mult \u00eenainte de o ie\u0219ire \u00een ora\u0219?", "fr": "Qui r\u00e9fl\u00e9chit trop avant une soir\u00e9e ?", "it": "Chi \u00e8 il pi\u00f9 grande pensatore eccessivo prima di una serata fuori?", "fi": "Kuka on suurin liiallinen ajattelija ennen iltaa ulkona?", "nl": "Wie is de grootste piekeraar voor een avondje uit?", "no": "Hvem er den st\u00f8rste overtenkeren f\u00f8r en kveld ute?", "sv": "Vem \u00e4r den st\u00f6rsta \u00f6veranalyssaren innan en utekv\u00e4ll?", "pl": "Kto jest najwi\u0119kszym zamartwiaczem przed wyj\u015bciem na miasto?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the biggest overthinker before a night out?';
UPDATE questions
SET translations = '{"en": "What\u2019s one rule you\u2019d make for all parties if you could?", "da": "Hvilken regel ville du lave for alle fester, hvis du kunne?", "de": "Welche Regel w\u00fcrdest du f\u00fcr alle Partys aufstellen, wenn du k\u00f6nntest?", "es": "\u00bfQu\u00e9 regla pondr\u00edas para todas las fiestas si pudieras?", "pt": "Que regra farias para todas as festas se pudesses?", "ro": "Ce regul\u0103 ai impune pentru toate petrecerile dac\u0103 ai putea?", "fr": "Quelle r\u00e8gle instaurerais-tu pour toutes les soir\u00e9es si tu pouvais ?", "it": "Qual \u00e8 una regola che stabiliresti per tutti i partiti se potessi?", "fi": "Mik\u00e4 olisi yksi s\u00e4\u00e4nt\u00f6, jonka s\u00e4\u00e4t\u00e4isit kaikille juhliin, jos voisit?", "nl": "Wat is \u00e9\u00e9n regel die je zou maken voor alle feesten als je kon?", "no": "Hva er en regel du ville laget for alle fester hvis du kunne?", "sv": "Vilken regel skulle du inf\u00f6ra f\u00f6r alla fester om du kunde?", "pl": "Jak\u0105 jedn\u0105 zasad\u0119 wprowadzi\u0142by\u015b dla wszystkich imprez, gdyby\u015b m\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s one rule you’d make for all parties if you could?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the most photogenic when the night\u2019s getting blurry?", "da": "Hvem er mest fotogen, n\u00e5r natten begynder at blive sl\u00f8ret?", "de": "Wer ist am fotogensten, wenn die Nacht verschwimmt?", "es": "\u00bfQui\u00e9n es el m\u00e1s fotog\u00e9nico cuando la noche se vuelve borrosa?", "pt": "Quem \u00e9 o mais fotog\u00e9nico quando a noite come\u00e7a a ficar turva?", "ro": "Cine e cel mai fotogenic c\u00e2nd noaptea devine \u00eence\u021bo\u0219at\u0103?", "fr": "Qui est le plus photog\u00e9nique quand la nuit devient floue ?", "it": "Chi \u00e8 il pi\u00f9 fotogenico quando la notte diventa sfocata?", "fi": "Kuka on valokuvauksellisin, kun y\u00f6 alkaa h\u00e4m\u00e4rty\u00e4?", "nl": "Wie is het meest fotogeniek als de nacht vaag wordt?", "no": "Hvem er den mest fotogene n\u00e5r natten blir uklar?", "sv": "Vem \u00e4r mest fotogenisk n\u00e4r natten blir suddig?", "pl": "Kto jest najbardziej fotogeniczny, gdy noc staje si\u0119 nieostra?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the most photogenic when the night’s getting blurry?';
UPDATE questions
SET translations = '{"en": "What\u2019s a night out that still gets mentioned in this friend group?", "da": "Hvilken bytur bliver stadig n\u00e6vnt i denne vennegruppe?", "de": "Welche Partynacht wird in dieser Freundesgruppe immer noch erw\u00e4hnt?", "es": "\u00bfQu\u00e9 noche de fiesta todav\u00eda se menciona en este grupo de amigos?", "pt": "Que noite de festa ainda \u00e9 mencionada neste grupo de amigos?", "ro": "Ce noapte de ie\u0219it este \u00eenc\u0103 men\u021bionat\u0103 \u00een acest grup de prieteni?", "fr": "Quelle soir\u00e9e est encore mentionn\u00e9e dans ce groupe d\u2019amis ?", "it": "Qual \u00e8 una serata fuori che viene ancora menzionata in questo gruppo di amici?", "fi": "Mik\u00e4 on sellainen ilta, jota viel\u00e4kin mainitaan t\u00e4ss\u00e4 kaveriporukassa?", "nl": "Wat is een avondje uit dat nog steeds in deze vriendengroep wordt genoemd?", "no": "Hva er en kveld ute som fortsatt blir nevnt i denne vennegjengen?", "sv": "Vilken utekv\u00e4ll n\u00e4mns fortfarande i den h\u00e4r v\u00e4nskapsgruppen?", "pl": "Jaka noc na mie\u015bcie wci\u0105\u017c jest wspominana w tej grupie przyjaci\u00f3\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s a night out that still gets mentioned in this friend group?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to wake up with the weirdest story to tell?", "da": "Hvem v\u00e5gner mest sandsynligt op med den m\u00e6rkeligste historie at fort\u00e6lle?", "de": "Wer wacht am ehesten mit der seltsamsten Geschichte auf?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que despierte con la historia m\u00e1s rara que contar?", "pt": "Quem \u00e9 mais prov\u00e1vel acordar com a hist\u00f3ria mais estranha para contar?", "ro": "Cine e cel mai probabil s\u0103 se trezeasc\u0103 cu cea mai ciudat\u0103 poveste de spus?", "fr": "Qui est le plus susceptible de se r\u00e9veiller avec l\u2019histoire la plus \u00e9trange \u00e0 raconter ?", "it": "Chi \u00e8 pi\u00f9 probabile che si svegli con la storia pi\u00f9 strana da raccontare?", "fi": "Kuka todenn\u00e4k\u00f6isesti her\u00e4\u00e4 oudoimmalla tarinalla kerrottavanaan?", "nl": "Wie is het meest waarschijnlijk om wakker te worden met het vreemdste verhaal om te vertellen?", "no": "Hvem er mest sannsynlig \u00e5 v\u00e5kne opp med den merkeligste historien \u00e5 fortelle?", "sv": "Vem \u00e4r mest sannolikt att vakna upp med den konstigaste ber\u00e4ttelsen att ber\u00e4tta?", "pl": "Kto najprawdopodobniej obudzi si\u0119 z najdziwniejsz\u0105 histori\u0105 do opowiedzenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to wake up with the weirdest story to tell?';
UPDATE questions
SET translations = '{"en": "What\u2019s your personal definition of a 10/10 night?", "da": "Hvad er din personlige definition af en 10/10-aften?", "de": "Was ist deine pers\u00f6nliche Definition einer 10/10-Nacht?", "es": "\u00bfCu\u00e1l es tu definici\u00f3n personal de una noche 10/10?", "pt": "Qual \u00e9 a tua defini\u00e7\u00e3o pessoal de uma noite 10/10?", "ro": "Care este defini\u021bia ta personal\u0103 a unei nop\u021bi perfecte?", "fr": "Quelle est ta d\u00e9finition personnelle d\u2019une soir\u00e9e 10/10 ?", "it": "Qual \u00e8 la tua definizione personale di una notte da 10/10?", "fi": "Mik\u00e4 on sinun henkil\u00f6kohtainen m\u00e4\u00e4ritelm\u00e4si t\u00e4ydelliselle illalle?", "nl": "Wat is jouw persoonlijke definitie van een 10/10 avond?", "no": "Hva er din personlige definisjon av en 10/10 kveld?", "sv": "Vad \u00e4r din personliga definition av en 10/10-kv\u00e4ll?", "pl": "Jakie jest twoje osobiste zdefiniowanie idealnej nocy 10/10?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your personal definition of a 10/10 night?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to start flirting with the bartender?", "da": "Hvem begynder mest sandsynligt at flirte med bartenderen?", "de": "Wer f\u00e4ngt am ehesten an, mit dem Barkeeper zu flirten?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que empiece a coquetear con el camarero?", "pt": "Quem \u00e9 mais prov\u00e1vel come\u00e7ar a flertar com o barman?", "ro": "Cine e cel mai probabil s\u0103 flirteze cu barmanul?", "fr": "Qui est le plus susceptible de flirter avec le barman ?", "it": "Chi \u00e8 pi\u00f9 probabile che inizi a flirtare con il barista?", "fi": "Kuka todenn\u00e4k\u00f6isesti alkaa flirttailla baarimikon kanssa?", "nl": "Wie is het meest waarschijnlijk om te beginnen flirten met de barman?", "no": "Hvem er mest sannsynlig til \u00e5 begynne \u00e5 fl\u00f8rte med bartenderen?", "sv": "Vem \u00e4r mest ben\u00e4gen att b\u00f6rja flirta med bartendrarna?", "pl": "Kto najprawdopodobniej zacznie flirtowa\u0107 z barmanem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to start flirting with the bartender?';
UPDATE questions
SET translations = '{"en": "Who usually disappears mid-night and comes back with a story?", "da": "Hvem forsvinder normalt midt om natten og kommer tilbage med en historie?", "de": "Wer verschwindet normalerweise mitten in der Nacht und kommt mit einer Geschichte zur\u00fcck?", "es": "\u00bfQui\u00e9n suele desaparecer a mitad de la noche y vuelve con una historia?", "pt": "Quem normalmente desaparece a meio da noite e volta com uma hist\u00f3ria?", "ro": "Cine dispare de obicei \u00een toiul nop\u021bii \u0219i se \u00eentoarce cu o poveste?", "fr": "Qui dispara\u00eet d\u2019habitude au milieu de la nuit et revient avec une histoire ?", "it": "Chi di solito scompare a mezzanotte e torna con una storia?", "fi": "Kuka yleens\u00e4 katoaa keskiy\u00f6ll\u00e4 ja palaa tarinan kanssa?", "nl": "Wie verdwijnt meestal midden in de nacht en komt terug met een verhaal?", "no": "Hvem pleier vanligvis \u00e5 forsvinne ved midnatt og komme tilbake med en historie?", "sv": "Vem f\u00f6rsvinner vanligtvis vid midnatt och kommer tillbaka med en historia?", "pl": "Kto zazwyczaj znika o p\u00f3\u0142nocy i wraca z opowie\u015bci\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who usually disappears mid-night and comes back with a story?';
UPDATE questions
SET translations = '{"en": "Who in this group would win \u201cmost likely to start a conga line\u201d?", "da": "Hvem i gruppen ville vinde \u201cmest sandsynlig til at starte en conga-linje\u201d?", "de": "Wer in der Gruppe w\u00fcrde den Preis \u201eam ehesten eine Conga-Linie starten\u201c gewinnen?", "es": "\u00bfQui\u00e9n del grupo ganar\u00eda \u201cel m\u00e1s probable en empezar una conga\u201d?", "pt": "Quem no grupo ganharia \u201co mais prov\u00e1vel de come\u00e7ar uma conga\u201d?", "ro": "Cine din grup ar c\u00e2\u0219tiga titlul \u201ecel mai probabil s\u0103 \u00eenceap\u0103 o conga\u201d?", "fr": "Qui dans le groupe gagnerait le prix de \u201ccelui qui commence une conga\u201d ?", "it": "Chi in questo gruppo vincerebbe il premio per \"il pi\u00f9 probabile a iniziare una conga\"?", "fi": "Kuka t\u00e4ss\u00e4 porukassa voittaisi tittelin \"todenn\u00e4k\u00f6isin aloittamaan conga-linjan\"?", "nl": "Wie in deze groep zou \"het meest waarschijnlijk een conga lijn te starten\" winnen?", "no": "Hvem i denne gruppen ville vunnet \"mest sannsynlig til \u00e5 starte en conga-linje\"?", "sv": "Vem i den h\u00e4r gruppen skulle vinna \"mest troligt att starta en conga-linje\"?", "pl": "Kto w tej grupie wygra\u0142by tytu\u0142 \u201enajbardziej prawdopodobny do rozpocz\u0119cia konga\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who in this group would win “most likely to start a conga line”?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the biggest over-sharer after a few drinks?", "da": "Hvem deler for meget efter et par drinks?", "de": "Wer ist der gr\u00f6\u00dfte Oversharer nach ein paar Drinks?", "es": "\u00bfQui\u00e9n cuenta demasiado despu\u00e9s de unas copas?", "pt": "Quem partilha demais depois de algumas bebidas?", "ro": "Cine poveste\u0219te prea mult dup\u0103 c\u00e2teva pahare?", "fr": "Qui en dit trop apr\u00e8s quelques verres ?", "it": "Chi \u00e8 il pi\u00f9 grande chiacchierone dopo qualche drink?", "fi": "Kuka on suurin liiallinen jakaja muutaman juoman j\u00e4lkeen?", "nl": "Wie is de grootste over-sharer na een paar drankjes?", "no": "Hvem er den st\u00f8rste som deler for mye etter noen drinker?", "sv": "Vem \u00e4r den st\u00f6rsta \u00f6verdelaren efter n\u00e5gra drinkar?", "pl": "Kto jest najwi\u0119kszym nadmiernym dziel\u0105cym si\u0119 po kilku drinkach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the biggest over-sharer after a few drinks?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most surprising place you\u2019ve ended up after a party?", "da": "Hvad er det mest overraskende sted, du er endt efter en fest?", "de": "Was ist der \u00fcberraschendste Ort, an dem du nach einer Party gelandet bist?", "es": "\u00bfCu\u00e1l es el lugar m\u00e1s sorprendente donde has terminado despu\u00e9s de una fiesta?", "pt": "Qual \u00e9 o lugar mais surpreendente onde acabaste depois de uma festa?", "ro": "Care este cel mai nea\u0219teptat loc \u00een care ai ajuns dup\u0103 o petrecere?", "fr": "Quel est l\u2019endroit le plus surprenant o\u00f9 tu as fini apr\u00e8s une soir\u00e9e ?", "it": "Qual \u00e8 il posto pi\u00f9 sorprendente in cui ti sei ritrovato dopo una festa?", "fi": "Mik\u00e4 on yll\u00e4tt\u00e4vin paikka, johon olet p\u00e4\u00e4tynyt juhlan j\u00e4lkeen?", "nl": "Wat is de meest verrassende plek waar je bent beland na een feestje?", "no": "Hva er det mest overraskende stedet du har havnet etter en fest?", "sv": "Vilket \u00e4r det mest \u00f6verraskande st\u00e4llet du har hamnat p\u00e5 efter en fest?", "pl": "Jakie jest najbardziej zaskakuj\u0105ce miejsce, w kt\u00f3rym si\u0119 znalaz\u0142e\u015b po imprezie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s the most surprising place you’ve ended up after a party?';
UPDATE questions
SET translations = '{"en": "Who would you trust least to keep your secrets after three drinks?", "da": "Hvem ville du stole mindst p\u00e5 til at holde dine hemmeligheder efter tre drinks?", "de": "Wem w\u00fcrdest du am wenigsten vertrauen, deine Geheimnisse nach drei Drinks zu bewahren?", "es": "\u00bfEn qui\u00e9n confiar\u00edas menos para guardar tus secretos despu\u00e9s de tres copas?", "pt": "Em quem confiarias menos para guardar segredos depois de tr\u00eas bebidas?", "ro": "\u00cen cine ai avea cea mai pu\u021bin\u0103 \u00eencredere s\u0103-\u021bi p\u0103streze secretele dup\u0103 trei pahare?", "fr": "\u00c0 qui ferais-tu le moins confiance pour garder tes secrets apr\u00e8s trois verres ?", "it": "A chi faresti meno affidamento per mantenere i tuoi segreti dopo tre drink?", "fi": "Kenelle luottaisit v\u00e4hiten pit\u00e4m\u00e4\u00e4n salaisuutesi kolmen juoman j\u00e4lkeen?", "nl": "Wie zou je het minst vertrouwen om je geheimen te bewaren na drie drankjes?", "no": "Hvem ville du minst stole p\u00e5 til \u00e5 holde p\u00e5 hemmelighetene dine etter tre drinker?", "sv": "Vem skulle du lita minst p\u00e5 att h\u00e5lla dina hemligheter efter tre drinkar?", "pl": "Kogo by\u015b najmniej ufa\u0142 w przechowywaniu swoich sekret\u00f3w po trzech drinkach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who would you trust least to keep your secrets after three drinks?';
UPDATE questions
SET translations = '{"en": "What\u2019s your most unforgettable kiss story?", "da": "Hvad er din mest uforglemmelige kyssehistorie?", "de": "Was ist deine unvergesslichste Kussgeschichte?", "es": "\u00bfCu\u00e1l es tu historia de beso m\u00e1s inolvidable?", "pt": "Qual \u00e9 a tua hist\u00f3ria de beijo mais inesquec\u00edvel?", "ro": "Care este cea mai de neuitat poveste a ta despre un s\u0103rut?", "fr": "Quelle est ton histoire de baiser la plus inoubliable ?", "it": "Qual \u00e8 la tua storia di bacio pi\u00f9 indimenticabile?", "fi": "Mik\u00e4 on unohtumattomin suudelmasi tarina?", "nl": "Wat is jouw meest onvergetelijke kusverhaal?", "no": "Hva er din mest uforglemmelige kyss-historie?", "sv": "Vad \u00e4r din mest of\u00f6rgl\u00f6mliga kysshistoria?", "pl": "Jaka jest twoja najbardziej niezapomniana historia poca\u0142unku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your most unforgettable kiss story?';
UPDATE questions
SET translations = '{"en": "What\u2019s a red flag you\u2019d probably ignore if the person was hot enough?", "da": "Hvad er et r\u00f8dt flag, du sandsynligvis ville ignorere, hvis personen var varm nok?", "de": "Welche Red Flag w\u00fcrdest du wahrscheinlich ignorieren, wenn die Person hei\u00df genug w\u00e4re?", "es": "\u00bfQu\u00e9 bandera roja probablemente ignorar\u00edas si la persona fuera lo suficientemente atractiva?", "pt": "Que sinal de alerta provavelmente ignorarias se a pessoa fosse atraente o suficiente?", "ro": "Ce semnal ro\u0219u ai ignora probabil dac\u0103 persoana ar fi suficient de atr\u0103g\u0103toare?", "fr": "Quel drapeau rouge ignorerais-tu probablement si la personne \u00e9tait assez sexy ?", "it": "Qual \u00e8 un campanello d''allarme che probabilmente ignoreresti se la persona fosse abbastanza attraente?", "fi": "Mik\u00e4 on punainen lippu, jonka todenn\u00e4k\u00f6isesti sivuuttaisit, jos henkil\u00f6 olisi tarpeeksi kuuma?", "nl": "Wat is een rode vlag die je waarschijnlijk zou negeren als de persoon aantrekkelijk genoeg was?", "no": "Hva er et r\u00f8dt flagg du sannsynligvis ville ignorert hvis personen var attraktiv nok?", "sv": "Vilken r\u00f6d flagga skulle du troligtvis ignorera om personen var tillr\u00e4ckligt attraktiv?", "pl": "Jak\u0105 czerwon\u0105 flag\u0119 prawdopodobnie zignorowa\u0142by\u015b, gdyby ta osoba by\u0142a wystarczaj\u0105co atrakcyjna?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s a red flag you’d probably ignore if the person was hot enough?';
UPDATE questions
SET translations = '{"en": "What\u2019s a subtle way you flirt without meaning to?", "da": "Hvad er en subtil m\u00e5de, du flirter p\u00e5 uden at mene det?", "de": "Was ist eine subtile Art, wie du flirtest, ohne es zu merken?", "es": "\u00bfCu\u00e1l es una forma sutil en la que coqueteas sin darte cuenta?", "pt": "Qual \u00e9 uma maneira sutil de flertar sem perceberes?", "ro": "Care este o modalitate subtil\u0103 prin care flirtezi f\u0103r\u0103 s\u0103 vrei?", "fr": "Quelle est une fa\u00e7on subtile dont tu flirtes sans t\u2019en rendre compte ?", "it": "Qual \u00e8 un modo sottile in cui flirti senza volerlo?", "fi": "Mik\u00e4 on hienovarainen tapa, jolla flirttailet ilman, ett\u00e4 tarkoitat sit\u00e4?", "nl": "Wat is een subtiele manier waarop je flirt zonder het te bedoelen?", "no": "Hva er en subtil m\u00e5te du fl\u00f8rter p\u00e5 uten \u00e5 mene det?", "sv": "Vad \u00e4r ett subtilt s\u00e4tt du fl\u00f6rtar utan att mena det?", "pl": "Jaki jest subtelny spos\u00f3b, w jaki flirtujesz, nie maj\u0105c tego na my\u015bli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s a subtle way you flirt without meaning to?';
UPDATE questions
SET translations = '{"en": "Who in this group do you think would be the most fun to kiss under the disco lights?", "da": "Hvem i denne gruppe tror du ville v\u00e6re sjovest at kysse under diskolysene?", "de": "Wer in dieser Gruppe w\u00e4re deiner Meinung nach am lustigsten, unter den Discolichtern zu k\u00fcssen?", "es": "\u00bfQui\u00e9n en este grupo ser\u00eda el m\u00e1s divertido de besar bajo las luces del disco?", "pt": "Quem neste grupo seria o mais divertido de beijar sob as luzes da discoteca?", "ro": "Cine din acest grup crezi c\u0103 ar fi cel mai distractiv de s\u0103rutat sub luminile disco?", "fr": "Qui dans ce groupe serait le plus amusant \u00e0 embrasser sous les lumi\u00e8res disco ?", "it": "Chi pensi in questo gruppo sarebbe il pi\u00f9 divertente da baciarsi sotto le luci del disco?", "fi": "Kuka t\u00e4ss\u00e4 porukassa mielest\u00e4si olisi hauskin suudeltava diskovalojen alla?", "nl": "Wie in deze groep denk je dat het leukst zou zijn om onder de discolichten te kussen?", "no": "Hvem i denne gruppen tror du ville v\u00e6rt mest morsom \u00e5 kysse under diskolysene?", "sv": "Vem i den h\u00e4r gruppen tycker du skulle vara roligast att kyssa under discobelysningen?", "pl": "Kto w tej grupie, wed\u0142ug ciebie, by\u0142by najfajniejszy do poca\u0142owania pod dyskotekowymi \u015bwiat\u0142ami?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who in this group do you think would be the most fun to kiss under the disco lights?';
UPDATE questions
SET translations = '{"en": "What\u2019s a secret crush you once had that would shock everyone?", "da": "Hvad er en hemmelig forelskelse, du engang havde, der ville chokere alle?", "de": "Welcher geheime Schwarm von dir w\u00fcrde alle schockieren?", "es": "\u00bfQu\u00e9 amor secreto tuviste que sorprender\u00eda a todos?", "pt": "Que crush secreto j\u00e1 tiveste que chocaria toda a gente?", "ro": "Ce crush secret ai avut care i-ar \u0219oca pe to\u021bi?", "fr": "Quel crush secret as-tu eu qui choquerait tout le monde ?", "it": "Qual \u00e8 un amore segreto che hai avuto e che sorprenderebbe tutti?", "fi": "Mik\u00e4 on salainen ihastuksesi, joka yll\u00e4tt\u00e4isi kaikki?", "nl": "Wat is een geheime verliefdheid die je ooit had en die iedereen zou verbazen?", "no": "Hva er en hemmelig forelskelse du en gang hadde som ville sjokkere alle?", "sv": "Vilken hemlig f\u00f6r\u00e4lskelse hade du en g\u00e5ng som skulle chocka alla?", "pl": "Jaki by\u0142 tw\u00f3j tajny zauroczenie, kt\u00f3re zaskoczy\u0142oby wszystkich?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s a secret crush you once had that would shock everyone?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to get caught doing something they shouldn\u2019t?", "da": "Hvem bliver mest sandsynligt taget i at g\u00f8re noget, de ikke burde?", "de": "Wer wird am ehesten erwischt, wenn er etwas tut, das er nicht sollte?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que sea atrapado haciendo algo que no deber\u00eda?", "pt": "Quem \u00e9 mais prov\u00e1vel ser apanhado a fazer algo que n\u00e3o devia?", "ro": "Cine e cel mai probabil s\u0103 fie prins f\u0103c\u00e2nd ceva ce n-ar trebui?", "fr": "Qui est le plus susceptible de se faire attraper en train de faire quelque chose qu\u2019il ne devrait pas ?", "it": "Chi \u00e8 pi\u00f9 probabile che venga beccato a fare qualcosa che non dovrebbe?", "fi": "Kuka on todenn\u00e4k\u00f6isimmin kiinni tekem\u00e4ss\u00e4 jotain, mit\u00e4 heid\u00e4n ei pit\u00e4isi?", "nl": "Wie is het meest waarschijnlijk om betrapt te worden op iets wat ze niet zouden moeten doen?", "no": "Hvem er mest sannsynlig \u00e5 bli tatt for \u00e5 gj\u00f8re noe de ikke burde?", "sv": "Vem \u00e4r mest ben\u00e4gen att bli p\u00e5kommen med att g\u00f6ra n\u00e5got de inte borde?", "pl": "Kto najprawdopodobniej zostanie przy\u0142apany na robieniu czego\u015b, czego nie powinien?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to get caught doing something they shouldn’t?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you\u2019ve done for attention that totally worked?", "da": "Hvad er \u00e9n ting, du har gjort for opm\u00e6rksomhed, der faktisk virkede?", "de": "Was hast du getan, um Aufmerksamkeit zu bekommen, das tats\u00e4chlich funktioniert hat?", "es": "\u00bfQu\u00e9 has hecho por atenci\u00f3n que realmente funcion\u00f3?", "pt": "O que fizeste para chamar a aten\u00e7\u00e3o que realmente resultou?", "ro": "Ce ai f\u0103cut pentru aten\u021bie \u0219i chiar a func\u021bionat?", "fr": "Qu\u2019as-tu fait pour attirer l\u2019attention et qui a vraiment march\u00e9 ?", "it": "Qual \u00e8 una cosa che hai fatto per attirare l''attenzione e che ha funzionato alla grande?", "fi": "Mik\u00e4 on yksi asia, jonka olet tehnyt saadaksesi huomiota ja joka todella toimi?", "nl": "Wat is \u00e9\u00e9n ding dat je hebt gedaan voor aandacht dat echt werkte?", "no": "Hva er en ting du har gjort for oppmerksomhet som virkelig fungerte?", "sv": "Vad \u00e4r en sak du har gjort f\u00f6r uppm\u00e4rksamhet som verkligen fungerade?", "pl": "Co\u015b, co zrobi\u0142e\u015b dla uwagi, co naprawd\u0119 zadzia\u0142a\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s one thing you’ve done for attention that totally worked?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most spontaneous thing you\u2019ve said \u201cyes\u201d to after midnight?", "da": "Hvad er det mest spontane, du har sagt \u201cja\u201d til efter midnat?", "de": "Was ist das Spontanste, wozu du nach Mitternacht \u201eJa\u201c gesagt hast?", "es": "\u00bfQu\u00e9 es lo m\u00e1s espont\u00e1neo a lo que has dicho \u201cs\u00ed\u201d despu\u00e9s de medianoche?", "pt": "Qual foi a coisa mais espont\u00e2nea a que disseste \u201csim\u201d depois da meia-noite?", "ro": "Care este cel mai spontan lucru la care ai spus \u201eda\u201d dup\u0103 miezul nop\u021bii?", "fr": "Quelle est la chose la plus spontan\u00e9e \u00e0 laquelle tu as dit \u201coui\u201d apr\u00e8s minuit ?", "it": "Qual \u00e8 la cosa pi\u00f9 spontanea a cui hai detto \"s\u00ec\" dopo mezzanotte?", "fi": "Mik\u00e4 on spontaanin asia, johon olet sanonut \"kyll\u00e4\" keskiy\u00f6n j\u00e4lkeen?", "nl": "Wat is het meest spontane waar je na middernacht \"ja\" tegen hebt gezegd?", "no": "Hva er det mest spontane du har sagt \"ja\" til etter midnatt?", "sv": "Vad \u00e4r det mest spontana du har sagt \"ja\" till efter midnatt?", "pl": "Co by\u0142o najbardziej spontaniczne, na co powiedzia\u0142e\u015b \"tak\" po p\u00f3\u0142nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s the most spontaneous thing you’ve said “yes” to after midnight?';
UPDATE questions
SET translations = '{"en": "What\u2019s your most embarrassing autocorrect or drunk-text moment?", "da": "Hvad er din mest pinlige autokorrektur- eller fuld-sms-oplevelse?", "de": "Was ist dein peinlichster Autokorrektur- oder Betrunken-SMS-Moment?", "es": "\u00bfCu\u00e1l es tu momento m\u00e1s vergonzoso de autocorrecci\u00f3n o mensaje borracho?", "pt": "Qual \u00e9 o teu momento mais embara\u00e7oso de autocorre\u00e7\u00e3o ou mensagem b\u00eabeda?", "ro": "Care este cel mai jenant moment de autocorectare sau mesaj trimis beat?", "fr": "Quel est ton moment d\u2019autocorrect ou de texto ivre le plus embarrassant ?", "it": "Qual \u00e8 il tuo momento pi\u00f9 imbarazzante con l''autocorrezione o un messaggio inviato ubriaco?", "fi": "Mik\u00e4 on noloin automaattinen korjaus- tai humalatekstiviestisi?", "nl": "Wat is jouw meest g\u00eanante autocorrect- of dronken-bericht moment?", "no": "Hva er ditt mest pinlige autokorrektur- eller fyllest\u00f8tte-\u00f8yeblikk?", "sv": "Vad \u00e4r ditt mest pinsamma autokorrigering eller fylleri-meddelande \u00f6gonblick?", "pl": "Jaki jest tw\u00f3j najbardziej \u017cenuj\u0105cy moment zwi\u0105zany z automatycznym poprawianiem tekstu lub wiadomo\u015bci\u0105 wys\u0142an\u0105 po alkoholu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your most embarrassing autocorrect or drunk-text moment?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to win at karaoke without even trying?", "da": "Hvem vinder mest sandsynligt i karaoke uden engang at pr\u00f8ve?", "de": "Wer gewinnt am ehesten beim Karaoke, ohne es zu versuchen?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que gane en karaoke sin intentarlo?", "pt": "Quem \u00e9 mais prov\u00e1vel ganhar no karaoke sem sequer tentar?", "ro": "Cine e cel mai probabil s\u0103 c\u00e2\u0219tige la karaoke f\u0103r\u0103 s\u0103 \u00eencerce?", "fr": "Qui est le plus susceptible de gagner au karaok\u00e9 sans m\u00eame essayer ?", "it": "Chi \u00e8 pi\u00f9 probabile che vinca al karaoke senza nemmeno provarci?", "fi": "Kuka todenn\u00e4k\u00f6isesti voittaa karaokessa ilman, ett\u00e4 edes yritt\u00e4\u00e4?", "nl": "Wie heeft de grootste kans om te winnen met karaoke zonder er ook maar iets voor te doen?", "no": "Hvem er mest sannsynlig \u00e5 vinne p\u00e5 karaoke uten engang \u00e5 pr\u00f8ve?", "sv": "Vem \u00e4r mest troligt att vinna p\u00e5 karaoke utan att ens f\u00f6rs\u00f6ka?", "pl": "Kto ma najwi\u0119ksze szanse wygra\u0107 w karaoke bez nawet pr\u00f3by?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to win at karaoke without even trying?';
UPDATE questions
SET translations = '{"en": "What\u2019s your ideal night with friends \u2014 chaotic energy or chill conversations?", "da": "Hvordan ser din ideelle aften med venner ud \u2014 kaotisk energi eller afslappede samtaler?", "de": "Wie sieht dein idealer Abend mit Freunden aus \u2013 chaotische Energie oder entspannte Gespr\u00e4che?", "es": "\u00bfC\u00f3mo es tu noche ideal con amigos: energ\u00eda ca\u00f3tica o conversaciones tranquilas?", "pt": "Como \u00e9 a tua noite ideal com amigos \u2014 energia ca\u00f3tica ou conversas tranquilas?", "ro": "Cum arat\u0103 seara ta ideal\u0103 cu prietenii \u2014 energie haotic\u0103 sau discu\u021bii relaxate?", "fr": "Ta soir\u00e9e id\u00e9ale entre amis \u2014 \u00e9nergie chaotique ou conversations tranquilles ?", "it": "Qual \u00e8 la tua serata ideale con gli amici: energia caotica o conversazioni tranquille?", "fi": "Mik\u00e4 on ihanteellinen iltasi yst\u00e4vien kanssa \u2014 kaaosenergia vai rentouttavat keskustelut?", "nl": "Wat is jouw ideale avond met vrienden \u2014 chaotische energie of ontspannen gesprekken?", "no": "Hva er din ideelle kveld med venner \u2014 kaotisk energi eller avslappende samtaler?", "sv": "Vad \u00e4r din idealiska kv\u00e4ll med v\u00e4nner \u2014 kaotisk energi eller avslappnade samtal?", "pl": "Jaka jest twoja idealna noc z przyjaci\u00f3\u0142mi \u2014 chaotyczna energia czy spokojne rozmowy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your ideal night with friends — chaotic energy or chill conversations?';
UPDATE questions
SET translations = '{"en": "Who in this group would make the best game show host \u2014 and what would the show be about?", "da": "Hvem i denne gruppe ville v\u00e6re den bedste quizshow-v\u00e6rt \u2014 og hvad ville showet handle om?", "de": "Wer in dieser Gruppe w\u00e4re der beste Gameshow-Moderator \u2013 und worum w\u00fcrde es gehen?", "es": "\u00bfQui\u00e9n en este grupo ser\u00eda el mejor presentador de concurso y de qu\u00e9 tratar\u00eda el programa?", "pt": "Quem neste grupo seria o melhor apresentador de jogo \u2014 e sobre o que seria o programa?", "ro": "Cine din acest grup ar fi cel mai bun prezentator de show \u2014 \u0219i despre ce ar fi?", "fr": "Qui dans ce groupe ferait le meilleur animateur de jeu \u2014 et de quoi parlerait l\u2019\u00e9mission ?", "it": "Chi in questo gruppo sarebbe il miglior presentatore di un quiz \u2014 e di cosa tratterebbe lo show?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 olisi paras peliohjelman juontaja \u2014 ja mist\u00e4 ohjelma olisi?", "nl": "Wie in deze groep zou de beste spelshowhost zijn \u2014 en waar zou de show over gaan?", "no": "Hvem i denne gruppen ville v\u00e6rt den beste spillprogramverten \u2014 og hva ville programmet handlet om?", "sv": "Vem i den h\u00e4r gruppen skulle vara den b\u00e4sta programledaren f\u00f6r ett fr\u00e5gespel \u2014 och vad skulle programmet handla om?", "pl": "Kto w tej grupie by\u0142by najlepszym prowadz\u0105cym teleturniej \u2014 i o czym by\u0142by ten program?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who in this group would make the best game show host — and what would the show be about?';

-- Category: Plot Twists & Dilemmas  (75 questions)
UPDATE questions
SET translations = '{"en": "You\u2019re in love, but your friends hate your partner. Do you listen to them or follow your heart?", "da": "Du er forelsket, men dine venner hader din partner. Lytter du til dem eller f\u00f8lger dit hjerte?", "de": "Du bist verliebt, aber deine Freunde hassen deinen Partner. H\u00f6rst du auf sie oder folgst du deinem Herzen?", "es": "Est\u00e1s enamorado/a, pero tus amigos odian a tu pareja. \u00bfLes haces caso o sigues tu coraz\u00f3n?", "pt": "Est\u00e1s apaixonado(a), mas os teus amigos odeiam o teu parceiro. Ouves-os ou segues o teu cora\u00e7\u00e3o?", "ro": "E\u0219ti \u00eendr\u0103gostit(\u0103), dar prietenii t\u0103i \u00ee\u021bi ur\u0103sc partenerul. \u00cei ascul\u021bi sau \u00ee\u021bi urmezi inima?", "fr": "Tu es amoureux(se), mais tes amis d\u00e9testent ton partenaire. Tu les \u00e9coutes ou tu suis ton c\u0153ur ?", "it": "Sei innamorato, ma i tuoi amici odiano il tuo partner. Ascolti loro o segui il tuo cuore?", "fi": "Olet rakastunut, mutta yst\u00e4v\u00e4si vihaavat kumppaniasi. Kuunteletko heit\u00e4 vai seuraatko syd\u00e4nt\u00e4si?", "nl": "Je bent verliefd, maar je vrienden haten je partner. Luister je naar hen of volg je je hart?", "no": "Du er forelsket, men vennene dine hater partneren din. Lytter du til dem eller f\u00f8lger du hjertet ditt?", "sv": "Du \u00e4r k\u00e4r, men dina v\u00e4nner hatar din partner. Lyssnar du p\u00e5 dem eller f\u00f6ljer du ditt hj\u00e4rta?", "pl": "Jeste\u015b zakochany, ale twoi przyjaciele nienawidz\u0105 twojego partnera. S\u0142uchasz ich, czy pod\u0105\u017casz za swoim sercem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You’re in love, but your friends hate your partner. Do you listen to them or follow your heart?';
UPDATE questions
SET translations = '{"en": "If two of us called you crying at the same time, who would you answer first?", "da": "Hvis to af os ringede gr\u00e6dende p\u00e5 samme tid, hvem ville du svare f\u00f8rst?", "de": "Wenn zwei von uns dich gleichzeitig weinend anrufen w\u00fcrden, wem w\u00fcrdest du zuerst antworten?", "es": "Si dos de nosotros te llam\u00e1ramos llorando al mismo tiempo, \u00bfa qui\u00e9n responder\u00edas primero?", "pt": "Se dois de n\u00f3s te lig\u00e1ssemos a chorar ao mesmo tempo, a quem responderias primeiro?", "ro": "Dac\u0103 doi dintre noi te-ar suna pl\u00e2ng\u00e2nd \u00een acela\u0219i timp, cui i-ai r\u0103spunde primul?", "fr": "Si deux d\u2019entre nous t\u2019appelaient en pleurant en m\u00eame temps, \u00e0 qui r\u00e9pondrais-tu en premier ?", "it": "Se due di noi ti chiamassero piangendo contemporaneamente, chi risponderesti per primo?", "fi": "Jos kaksi meist\u00e4 soittaisi sinulle itkien samaan aikaan, kenelle vastaisit ensin?", "nl": "Als twee van ons je tegelijkertijd belden en huilend waren, wie zou je dan als eerste beantwoorden?", "no": "Hvis to av oss ringte deg gr\u00e5tende samtidig, hvem ville du svart f\u00f8rst?", "sv": "Om tv\u00e5 av oss ringde dig gr\u00e5tande samtidigt, vem skulle du svara f\u00f6rst?", "pl": "Je\u015bli dwoje z nas zadzwoni\u0142oby do ciebie p\u0142acz\u0105c w tym samym czasie, kogo by\u015b odebra\u0142 pierwszy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If two of us called you crying at the same time, who would you answer first?';
UPDATE questions
SET translations = '{"en": "If we all swapped phones for 5 minutes, whose would cause the biggest scandal?", "da": "Hvis vi alle byttede telefoner i 5 minutter, hvis ville skabe den st\u00f8rste skandale?", "de": "Wenn wir alle f\u00fcr 5 Minuten die Handys tauschen w\u00fcrden, welches w\u00fcrde den gr\u00f6\u00dften Skandal verursachen?", "es": "Si todos intercambi\u00e1ramos tel\u00e9fonos por 5 minutos, \u00bfcu\u00e1l causar\u00eda el mayor esc\u00e1ndalo?", "pt": "Se todos troc\u00e1ssemos de telem\u00f3vel por 5 minutos, qual causaria o maior esc\u00e2ndalo?", "ro": "Dac\u0103 ne-am schimba telefoanele timp de 5 minute, al cui ar provoca cel mai mare scandal?", "fr": "Si on \u00e9changeait tous nos t\u00e9l\u00e9phones pendant 5 minutes, lequel causerait le plus grand scandale ?", "it": "Se tutti noi scambiassimo i telefoni per 5 minuti, il quale causerebbe il maggior scandalo?", "fi": "Jos me kaikki vaihdettaisiin puhelimia viideksi minuutiksi, kenen puhelin aiheuttaisi suurimman skandaalin?", "nl": "Als we allemaal 5 minuten van telefoon zouden wisselen, wiens zou de grootste schandaal veroorzaken?", "no": "Hvis vi alle byttet telefoner i 5 minutter, hvis sin ville skape den st\u00f8rste skandalen?", "sv": "Om vi alla bytte telefoner i 5 minuter, vems skulle orsaka den st\u00f6rsta skandalen?", "pl": "Je\u015bli wszyscy zamieniliby\u015bmy si\u0119 telefonami na 5 minut, czyj telefon wywo\u0142a\u0142by najwi\u0119kszy skandal?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If we all swapped phones for 5 minutes, whose would cause the biggest scandal?';
UPDATE questions
SET translations = '{"en": "You win a free vacation \u2014 but you can only bring one friend from this room. Who\u2019s your pick and why?", "da": "Du vinder en gratis ferie \u2014 men du m\u00e5 kun tage \u00e9n ven fra dette rum. Hvem v\u00e6lger du og hvorfor?", "de": "Du gewinnst einen kostenlosen Urlaub \u2013 aber du darfst nur einen Freund aus diesem Raum mitnehmen. Wen w\u00e4hlst du und warum?", "es": "Ganas unas vacaciones gratis \u2014 pero solo puedes llevar a un amigo de esta sala. \u00bfA qui\u00e9n eliges y por qu\u00e9?", "pt": "Ganhas umas f\u00e9rias gr\u00e1tis \u2014 mas s\u00f3 podes levar um amigo desta sala. Quem escolhes e porqu\u00ea?", "ro": "C\u00e2\u0219tigi o vacan\u021b\u0103 gratuit\u0103 \u2014 dar po\u021bi lua doar un prieten din aceast\u0103 camer\u0103. Pe cine alegi \u0219i de ce?", "fr": "Tu gagnes des vacances gratuites \u2014 mais tu ne peux emmener qu\u2019un ami d\u2019ici. Qui choisis-tu et pourquoi ?", "it": "Vinci una vacanza gratis \u2014 ma puoi portare solo un amico di questa stanza. Chi scegli e perch\u00e9?", "fi": "Voitat ilmaisen loman \u2014 mutta voit tuoda vain yhden yst\u00e4v\u00e4n t\u00e4st\u00e4 huoneesta. Kuka on valintasi ja miksi?", "nl": "Je wint een gratis vakantie \u2014 maar je mag maar \u00e9\u00e9n vriend uit deze kamer meenemen. Wie kies je en waarom?", "no": "Du vinner en gratis ferie \u2014 men du kan bare ta med deg \u00e9n venn fra dette rommet. Hvem velger du og hvorfor?", "sv": "Du vinner en gratis semester \u2014 men du kan bara ta med en v\u00e4n fr\u00e5n det h\u00e4r rummet. Vem v\u00e4ljer du och varf\u00f6r?", "pl": "Wygrywasz darmowe wakacje \u2014 ale mo\u017cesz zabra\u0107 tylko jednego przyjaciela z tego pokoju. Kogo wybierasz i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You win a free vacation — but you can only bring one friend from this room. Who’s your pick and why?';
UPDATE questions
SET translations = '{"en": "Who in this group would survive a zombie apocalypse the longest?", "da": "Hvem i denne gruppe ville overleve l\u00e6ngst i en zombieapokalypse?", "de": "Wer in dieser Gruppe w\u00fcrde eine Zombie-Apokalypse am l\u00e4ngsten \u00fcberleben?", "es": "\u00bfQui\u00e9n de este grupo sobrevivir\u00eda m\u00e1s tiempo a un apocalipsis zombi?", "pt": "Quem deste grupo sobreviveria mais tempo a um apocalipse zombie?", "ro": "Cine din acest grup ar supravie\u021bui cel mai mult \u00eentr-o apocalips\u0103 cu zombi?", "fr": "Qui dans ce groupe survivrait le plus longtemps \u00e0 une apocalypse zombie ?", "it": "Chi in questo gruppo sopravviverebbe pi\u00f9 a lungo a un''apocalisse zombie?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 selviytyisi pisimp\u00e4\u00e4n zombi-apokalypsiss\u00e4?", "nl": "Wie in deze groep zou het langst overleven tijdens een zombie-apocalyps?", "no": "Hvem i denne gruppen ville overlevd en zombieapokalypse lengst?", "sv": "Vem i den h\u00e4r gruppen skulle \u00f6verleva en zombieapokalyps l\u00e4ngst?", "pl": "Kto w tej grupie przetrwa\u0142by najd\u0142u\u017cej podczas apokalipsy zombie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who in this group would survive a zombie apocalypse the longest?';
UPDATE questions
SET translations = '{"en": "If one of us became famous, who would handle it the best?", "da": "Hvis en af os blev ber\u00f8mt, hvem ville h\u00e5ndtere det bedst?", "de": "Wenn einer von uns ber\u00fchmt w\u00fcrde, wer k\u00e4me am besten damit zurecht?", "es": "Si uno de nosotros se hiciera famoso, \u00bfqui\u00e9n lo manejar\u00eda mejor?", "pt": "Se um de n\u00f3s se tornasse famoso, quem lidaria melhor com isso?", "ro": "Dac\u0103 unul dintre noi ar deveni faimos, cine s-ar descurca cel mai bine?", "fr": "Si l\u2019un de nous devenait c\u00e9l\u00e8bre, qui le g\u00e9rerait le mieux ?", "it": "Se uno di noi diventasse famoso, chi lo gestirebbe meglio?", "fi": "Jos joku meist\u00e4 tulisi kuuluisaksi, kuka k\u00e4sittelisi sit\u00e4 parhaiten?", "nl": "Als een van ons beroemd zou worden, wie zou daar het beste mee omgaan?", "no": "Hvis en av oss ble ber\u00f8mt, hvem ville taklet det best?", "sv": "Om en av oss blev ber\u00f6md, vem skulle hantera det b\u00e4st?", "pl": "Je\u015bli jedno z nas sta\u0142oby si\u0119 s\u0142awne, kto poradzi\u0142by sobie z tym najlepiej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If one of us became famous, who would handle it the best?';
UPDATE questions
SET translations = '{"en": "Who would you trust to delete your search history if you died suddenly?", "da": "Hvem ville du stole p\u00e5 til at slette din s\u00f8gehistorik, hvis du d\u00f8de pludseligt?", "de": "Wem w\u00fcrdest du vertrauen, deinen Suchverlauf zu l\u00f6schen, wenn du pl\u00f6tzlich sterben w\u00fcrdest?", "es": "\u00bfEn qui\u00e9n confiar\u00edas para borrar tu historial si murieras de repente?", "pt": "Em quem confiarias para apagar o teu hist\u00f3rico de pesquisa se morresses de repente?", "ro": "\u00cen cine ai avea \u00eencredere s\u0103-\u021bi \u0219tearg\u0103 istoricul de c\u0103utare dac\u0103 ai muri brusc?", "fr": "\u00c0 qui ferais-tu confiance pour effacer ton historique de recherche si tu mourais soudainement ?", "it": "A chi faresti fiducia per eliminare la tua cronologia di ricerca se dovessi morire all''improvviso?", "fi": "Kenelle luottaisit poistamaan hakuhistoriasi, jos kuolisit \u00e4killisesti?", "nl": "Wie zou je vertrouwen om je zoekgeschiedenis te verwijderen als je plotseling zou overlijden?", "no": "Hvem ville du stole p\u00e5 til \u00e5 slette s\u00f8kehistorikken din hvis du d\u00f8de plutselig?", "sv": "Vem skulle du lita p\u00e5 att radera din s\u00f6khistorik om du pl\u00f6tsligt dog?", "pl": "Kogo by\u015b zaufa\u0142, \u017ceby usun\u0105\u0142 twoj\u0105 histori\u0119 wyszukiwania, gdyby\u015b nagle umar\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would you trust to delete your search history if you died suddenly?';
UPDATE questions
SET translations = '{"en": "If someone here got arrested, who would you assume it was before even asking?", "da": "Hvis nogen her blev arresteret, hvem ville du antage, det var, uden at sp\u00f8rge?", "de": "Wenn jemand hier verhaftet w\u00fcrde, wen w\u00fcrdest du ohne zu fragen f\u00fcr schuldig halten?", "es": "Si arrestaran a alguien aqu\u00ed, \u00bfde qui\u00e9n sospechar\u00edas sin preguntar?", "pt": "Se algu\u00e9m aqui fosse preso, de quem suspeitarias sem perguntar?", "ro": "Dac\u0103 cineva de aici ar fi arestat, pe cine ai b\u0103nui f\u0103r\u0103 s\u0103 \u00eentrebi?", "fr": "Si quelqu\u2019un ici \u00e9tait arr\u00eat\u00e9, qui soup\u00e7onnerais-tu sans m\u00eame demander ?", "it": "Se qualcuno qui fosse stato arrestato, chi supporresti fosse prima ancora di chiedere?", "fi": "Jos joku t\u00e4\u00e4ll\u00e4 pid\u00e4tett\u00e4isiin, ket\u00e4 luulisit sen olevan ennen kuin edes kysyt?", "nl": "Als iemand hier gearresteerd zou worden, wie zou je dan aannemen dat het was voordat je het zelfs maar vraagt?", "no": "Hvis noen her ble arrestert, hvem ville du anta det var f\u00f8r du engang spurte?", "sv": "Om n\u00e5gon h\u00e4r blev arresterad, vem skulle du anta att det var innan du ens fr\u00e5gade?", "pl": "Gdyby kto\u015b tutaj zosta\u0142 aresztowany, kogo by\u015b podejrzewa\u0142, zanim jeszcze zapytasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If someone here got arrested, who would you assume it was before even asking?';
UPDATE questions
SET translations = '{"en": "You have to let one friend plan your wedding \u2014 who\u2019s in charge, and who\u2019s banned?", "da": "Du skal lade \u00e9n ven planl\u00e6gge dit bryllup \u2014 hvem er ansvarlig, og hvem er forbudt?", "de": "Du musst einem Freund erlauben, deine Hochzeit zu planen \u2013 wer ist verantwortlich und wer ist verboten?", "es": "Tienes que dejar que un amigo planifique tu boda \u2014 \u00bfqui\u00e9n est\u00e1 a cargo y qui\u00e9n est\u00e1 vetado?", "pt": "Tens de deixar um amigo planear o teu casamento \u2014 quem fica encarregado e quem \u00e9 proibido?", "ro": "Trebuie s\u0103 la\u0219i un prieten s\u0103-\u021bi planifice nunta \u2014 cine se ocup\u0103 \u0219i cine e interzis?", "fr": "Tu dois laisser un ami organiser ton mariage \u2014 qui est en charge et qui est banni ?", "it": "Devi lasciare che un amico organizzi il tuo matrimonio \u2014 chi \u00e8 in carica e chi \u00e8 bandito?", "fi": "Sinun t\u00e4ytyy antaa yhden yst\u00e4v\u00e4n suunnitella h\u00e4\u00e4t \u2014 kuka on vastuussa ja kuka on kielletty?", "nl": "Je moet \u00e9\u00e9n vriend de planning van je bruiloft laten doen \u2014 wie is de baas en wie is verbannen?", "no": "Du m\u00e5 la en venn planlegge bryllupet ditt - hvem har ansvaret, og hvem er utestengt?", "sv": "Du m\u00e5ste l\u00e5ta en v\u00e4n planera ditt br\u00f6llop \u2014 vem \u00e4r ansvarig, och vem \u00e4r bannlyst?", "pl": "Musisz pozwoli\u0107 jednemu przyjacielowi zaplanowa\u0107 twoje wesele \u2014 kto jest odpowiedzialny, a kto jest zakazany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You have to let one friend plan your wedding — who’s in charge, and who’s banned?';
UPDATE questions
SET translations = '{"en": "Who here would accidentally spoil your big secret within 24 hours?", "da": "Hvem her ville ved et uheld afsl\u00f8re din store hemmelighed inden for 24 timer?", "de": "Wer hier w\u00fcrde aus Versehen dein gro\u00dfes Geheimnis innerhalb von 24 Stunden verraten?", "es": "\u00bfQui\u00e9n aqu\u00ed revelar\u00eda accidentalmente tu gran secreto en 24 horas?", "pt": "Quem aqui revelaria acidentalmente o teu grande segredo em 24 horas?", "ro": "Cine de aici \u021bi-ar da din gre\u0219eal\u0103 marele secret \u00een 24 de ore?", "fr": "Qui ici r\u00e9v\u00e9lerait accidentellement ton grand secret en moins de 24 heures ?", "it": "Chi qui rovinerebbe accidentalmente il tuo grande segreto entro 24 ore?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 voisi vahingossa paljastaa suuren salaisuutesi 24 tunnin sis\u00e4ll\u00e4?", "nl": "Wie hier zou per ongeluk jouw grote geheim binnen 24 uur verklappen?", "no": "Hvem her ville ved et uhell avsl\u00f8rt din store hemmelighet innen 24 timer?", "sv": "Vem h\u00e4r skulle av misstag avsl\u00f6ja din stora hemlighet inom 24 timmar?", "pl": "Kto tutaj przypadkowo zdradzi\u0142by tw\u00f3j wielki sekret w ci\u0105gu 24 godzin?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who here would accidentally spoil your big secret within 24 hours?';
UPDATE questions
SET translations = '{"en": "Who do you think is the most likely to secretly stalk their ex online?", "da": "Hvem tror du er mest tilb\u00f8jelig til i hemmelighed at stalke deres eks online?", "de": "Wer ist deiner Meinung nach am ehesten heimlich dazu geneigt, seinen Ex online zu stalken?", "es": "\u00bfQui\u00e9n crees que es m\u00e1s propenso a espiar en secreto a su ex en l\u00ednea?", "pt": "Quem achas que seria mais propenso a seguir o ex online em segredo?", "ro": "Cine crezi c\u0103 e cel mai probabil s\u0103-\u0219i urm\u0103reasc\u0103 fostul pe ascuns online?", "fr": "Qui, selon toi, est le plus susceptible d\u2019espionner secr\u00e8tement son ex en ligne ?", "it": "Chi pensi sia il pi\u00f9 probabile a stalkerare segretamente il proprio ex online?", "fi": "Kuka mielest\u00e4si on todenn\u00e4k\u00f6isin salaa vakoilemaan entist\u00e4 kumppaniaan verkossa?", "nl": "Wie denk je dat het meest waarschijnlijk is om stiekem hun ex online te stalken?", "no": "Hvem tror du er mest sannsynlig til \u00e5 hemmelig overv\u00e5ke eksen sin p\u00e5 nettet?", "sv": "Vem tror du \u00e4r mest ben\u00e4gen att hemligt spionera p\u00e5 sitt ex online?", "pl": "Kto twoim zdaniem jest najbardziej sk\u0142onny do potajemnego \u015bledzenia swojego by\u0142ego w internecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who do you think is the most likely to secretly stalk their ex online?';
UPDATE questions
SET translations = '{"en": "Who would you nominate to lie for you if you were in trouble?", "da": "Hvem ville du nominere til at lyve for dig, hvis du var i problemer?", "de": "Wen w\u00fcrdest du nominieren, f\u00fcr dich zu l\u00fcgen, wenn du in Schwierigkeiten w\u00e4rst?", "es": "\u00bfA qui\u00e9n nominar\u00edas para mentir por ti si estuvieras en problemas?", "pt": "Quem nomearias para mentir por ti se estivesses em apuros?", "ro": "Pe cine ai nominaliza s\u0103 mint\u0103 pentru tine dac\u0103 ai fi \u00een probleme?", "fr": "Qui nominerais-tu pour mentir pour toi si tu \u00e9tais dans le p\u00e9trin ?", "it": "Chi nomineresti per mentire per te se fossi nei guai?", "fi": "Kenen sin\u00e4 nimitt\u00e4isit valehtelemaan puolestasi, jos olisit pulassa?", "nl": "Wie zou je nomineren om voor je te liegen als je in de problemen zat?", "no": "Hvem ville du nominere til \u00e5 lyve for deg hvis du var i tr\u00f8bbel?", "sv": "Vem skulle du nominera att ljuga f\u00f6r dig om du hamnade i trubbel?", "pl": "Kogo by\u015b nominowa\u0142, \u017ceby sk\u0142ama\u0142 w twoim imieniu, gdyby\u015b mia\u0142 k\u0142opoty?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would you nominate to lie for you if you were in trouble?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the most likely to ghost someone and then act confused about it?", "da": "Hvem er mest tilb\u00f8jelig til at ghoste nogen og s\u00e5 lade som ingenting bagefter?", "de": "Wer ist am ehesten dazu geneigt, jemanden zu ghosten und dann verwirrt zu tun?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que haga ghosting y luego se haga el confundido?", "pt": "Quem \u00e9 mais prov\u00e1vel de fazer ghosting e depois fingir que n\u00e3o percebeu?", "ro": "Cine e cel mai probabil s\u0103 ignore pe cineva \u0219i apoi s\u0103 se prefac\u0103 c\u0103 nu \u0219tie?", "fr": "Qui est le plus susceptible de ghoster quelqu\u2019un puis de faire semblant d\u2019\u00eatre confus ?", "it": "Chi \u00e8 pi\u00f9 probabile che sparisca da qualcuno e poi faccia finta di non sapere cosa sia successo?", "fi": "Kuka on todenn\u00e4k\u00f6isin j\u00e4tt\u00e4m\u00e4\u00e4n jonkun huomioimatta ja sitten k\u00e4ytt\u00e4ytym\u00e4\u00e4n h\u00e4mmentyneesti asiasta?", "nl": "Wie is het meest waarschijnlijk om iemand te ghosten en zich daar vervolgens over te verwonderen?", "no": "Hvem er mest sannsynlig til \u00e5 ghoste noen og s\u00e5 virke forvirret over det?", "sv": "Vem \u00e4r mest trolig att sp\u00f6ka n\u00e5gon och sedan agera f\u00f6rvirrad \u00f6ver det?", "pl": "Kto jest najbardziej sk\u0142onny do znikni\u0119cia i potem udawania, \u017ce nie wie, o co chodzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who’s the most likely to ghost someone and then act confused about it?';
UPDATE questions
SET translations = '{"en": "Two of your friends have events on the same night \u2014 one is a huge party, the other is a small dinner. Which do you pick, and why?", "da": "To af dine venner har events samme aften \u2014 en stor fest, en lille middag. Hvilken v\u00e6lger du, og hvorfor?", "de": "Zwei deiner Freunde haben am selben Abend Veranstaltungen \u2013 eine gro\u00dfe Party, ein kleines Abendessen. Welche w\u00e4hlst du und warum?", "es": "Dos de tus amigos tienen eventos la misma noche \u2014 una gran fiesta y una cena peque\u00f1a. \u00bfCu\u00e1l eliges y por qu\u00e9?", "pt": "Dois amigos teus t\u00eam eventos na mesma noite \u2014 uma grande festa e um jantar pequeno. Qual escolhes e porqu\u00ea?", "ro": "Doi dintre prietenii t\u0103i au evenimente \u00een aceea\u0219i sear\u0103 \u2014 o petrecere mare \u0219i o cin\u0103 mic\u0103. Pe care alegi \u0219i de ce?", "fr": "Deux de tes amis ont des \u00e9v\u00e9nements le m\u00eame soir \u2014 une grande f\u00eate et un petit d\u00eener. Lequel choisis-tu et pourquoi ?", "it": "Due dei tuoi amici hanno eventi nella stessa notte: uno \u00e8 una grande festa, l''altro \u00e8 una cena intima. Quale scegli e perch\u00e9?", "fi": "Kaksi yst\u00e4v\u00e4\u00e4si j\u00e4rjest\u00e4\u00e4 tapahtumia samana iltana \u2014 toinen on iso juhla, toinen pieni illallinen. Kumman valitset ja miksi?", "nl": "Twee van je vrienden hebben op dezelfde avond een evenement \u2014 de ene is een groot feest, de andere is een klein diner. Welke kies je, en waarom?", "no": "To venner har arrangementer samme kveld - en er en stor fest, den andre er en liten middag. Hvilken velger du, og hvorfor?", "sv": "Tv\u00e5 av dina v\u00e4nner har evenemang samma kv\u00e4ll \u2014 en \u00e4r en stor fest, den andra \u00e4r en liten middag. Vilken v\u00e4ljer du, och varf\u00f6r?", "pl": "Dw\u00f3ch twoich przyjaci\u00f3\u0142 ma wydarzenia w t\u0119 sam\u0105 noc \u2014 jedno to ogromna impreza, a drugie to ma\u0142a kolacja. Kt\u00f3re wybierasz i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Two of your friends have events on the same night — one is a huge party, the other is a small dinner. Which do you pick, and why?';
UPDATE questions
SET translations = '{"en": "You get one million dollars \u2014 but you have to ghost everyone in this room for a year. Would you do it?", "da": "Du f\u00e5r en million dollars \u2014 men du skal ignorere alle her i et \u00e5r. G\u00f8r du det?", "de": "Du bekommst eine Million Dollar \u2013 aber du musst alle hier ein Jahr lang ignorieren. W\u00fcrdest du es tun?", "es": "Obtienes un mill\u00f3n de d\u00f3lares \u2014 pero tienes que ignorar a todos aqu\u00ed por un a\u00f1o. \u00bfLo har\u00edas?", "pt": "Ganas um milh\u00e3o de d\u00f3lares \u2014 mas tens de ignorar toda a gente aqui durante um ano. Farias isso?", "ro": "Prime\u0219ti un milion de dolari \u2014 dar trebuie s\u0103 ignori pe toat\u0103 lumea de aici timp de un an. Ai face-o?", "fr": "Tu gagnes un million de dollars \u2014 mais tu dois ignorer tout le monde ici pendant un an. Le ferais-tu ?", "it": "Ricevi un milione di dollari \u2014 ma devi ignorare tutti in questa stanza per un anno. Lo faresti?", "fi": "Saat miljoona dollaria \u2014 mutta sinun t\u00e4ytyy kadota kaikilta t\u00e4ss\u00e4 huoneessa vuodeksi. Tekisitk\u00f6 niin?", "nl": "Je krijgt een miljoen dollar \u2014 maar je moet iedereen in deze kamer een jaar lang negeren. Zou je het doen?", "no": "Du f\u00e5r en million dollar \u2014 men du m\u00e5 kutte kontakten med alle i dette rommet i ett \u00e5r. Ville du gjort det?", "sv": "Du f\u00e5r en miljon dollar \u2014 men du m\u00e5ste sp\u00f6ka alla i det h\u00e4r rummet i ett \u00e5r. Skulle du g\u00f6ra det?", "pl": "Dostajesz milion dolar\u00f3w \u2014 ale musisz znikn\u0105\u0107 dla wszystkich w tym pokoju na rok. Czy by\u015b to zrobi\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You get one million dollars — but you have to ghost everyone in this room for a year. Would you do it?';
UPDATE questions
SET translations = '{"en": "One of your friends gets super rich and changes \u2014 do you call them out or stay quiet?", "da": "En af dine venner bliver superrig og forandrer sig \u2014 konfronterer du dem eller tier stille?", "de": "Einer deiner Freunde wird superreich und ver\u00e4ndert sich \u2013 sprichst du es an oder bleibst du still?", "es": "Uno de tus amigos se vuelve muy rico y cambia \u2014 \u00bflo enfrentas o te quedas callado?", "pt": "Um dos teus amigos fica muito rico e muda \u2014 chamas-lhe a aten\u00e7\u00e3o ou ficas calado?", "ro": "Unul dintre prietenii t\u0103i devine foarte bogat \u0219i se schimb\u0103 \u2014 \u00eel confrun\u021bi sau taci?", "fr": "L\u2019un de tes amis devient tr\u00e8s riche et change \u2014 tu le confrontes ou tu te tais ?", "it": "Uno dei tuoi amici diventa super ricco e cambia \u2014 li affronti o resti in silenzio?", "fi": "Yksi yst\u00e4vist\u00e4si rikastuu \u00e4kisti ja muuttuu \u2014 sanotko siit\u00e4 heille vai pysytk\u00f6 hiljaa?", "nl": "Een van je vrienden wordt superrijk en verandert \u2014 zeg je er iets van of blijf je stil?", "no": "En av vennene dine blir superrik og endrer seg \u2014 sier du ifra eller holder du kjeft?", "sv": "En av dina v\u00e4nner blir superrik och f\u00f6r\u00e4ndras \u2013 s\u00e4ger du till dem eller h\u00e5ller du tyst?", "pl": "Jeden z twoich przyjaci\u00f3\u0142 staje si\u0119 super bogaty i si\u0119 zmienia \u2014 czy zwr\u00f3cisz mu na to uwag\u0119, czy pozostaniesz cicho?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'One of your friends gets super rich and changes — do you call them out or stay quiet?';
UPDATE questions
SET translations = '{"en": "You find out a friend\u2019s partner is cheating \u2014 do you tell them or stay out of it?", "da": "Du finder ud af, at en vens partner er utro \u2014 fort\u00e6ller du det eller blander du dig udenom?", "de": "Du findest heraus, dass der Partner eines Freundes untreu ist \u2013 sagst du es oder h\u00e4ltst du dich raus?", "es": "Descubres que la pareja de un amigo enga\u00f1a \u2014 \u00bfse lo dices o te mantienes al margen?", "pt": "Descobres que o parceiro de um amigo \u00e9 infiel \u2014 dizes-lhe ou ficas de fora?", "ro": "Afli c\u0103 partenerul unui prieten \u00een\u0219al\u0103 \u2014 \u00eei spui sau te ab\u021bii?", "fr": "Tu d\u00e9couvres que le partenaire d\u2019un ami le trompe \u2014 tu le dis ou tu restes en dehors ?", "it": "Scopri che il partner di un amico ti tradisce \u2014 glielo dici o stai fuori da questa situazione?", "fi": "Saat tiet\u00e4\u00e4, ett\u00e4 yst\u00e4v\u00e4si kumppani pett\u00e4\u00e4 \u2014 kerrotko siit\u00e4 heille vai pysytk\u00f6 eristyksiss\u00e4?", "nl": "Je ontdekt dat de partner van een vriend bedriegt \u2014 vertel je het hen of blijf je er buiten?", "no": "Du finner ut at en venns partner er utro \u2014 sier du ifra eller holder du deg unna?", "sv": "Du f\u00e5r reda p\u00e5 att en v\u00e4ns partner \u00e4r otrogen \u2013 s\u00e4ger du det till dem eller h\u00e5ller du dig utanf\u00f6r?", "pl": "Dowiadujesz si\u0119, \u017ce partner przyjaciela ci\u0119 oszukuje \u2014 czy powiesz mu o tym, czy lepiej si\u0119 w to nie miesza\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You find out a friend’s partner is cheating — do you tell them or stay out of it?';
UPDATE questions
SET translations = '{"en": "You overhear your friend talking behind your back \u2014 do you confront them or slowly distance yourself?", "da": "Du overh\u00f8rer en ven tale bag din ryg \u2014 konfronterer du dem eller tr\u00e6kker dig langsomt v\u00e6k?", "de": "Du h\u00f6rst, wie ein Freund hinter deinem R\u00fccken redet \u2013 konfrontierst du ihn oder distanzierst du dich langsam?", "es": "Escuchas a un amigo hablando mal de ti \u2014 \u00bflo enfrentas o te alejas poco a poco?", "pt": "Ouves um amigo a falar de ti nas tuas costas \u2014 confrontas ou afastas-te aos poucos?", "ro": "\u00ce\u021bi auzi un prieten vorbind pe la spate \u2014 \u00eel confrun\u021bi sau te \u00eendep\u0103rtezi treptat?", "fr": "Tu entends un ami parler dans ton dos \u2014 tu le confrontes ou tu t\u2019\u00e9loignes doucement ?", "it": "Senti il tuo amico parlare alle tue spalle \u2014 lo affronti o ti allontani lentamente?", "fi": "Kuuntelet yst\u00e4v\u00e4si puhuvan selk\u00e4si takana \u2014 kohtaatko h\u00e4net vai et\u00e4nyt\u00e4tk\u00f6 itsesi v\u00e4hitellen?", "nl": "Je hoort je vriend achter je rug om praten \u2014 confronteer je ze of neem je langzaam afstand?", "no": "Du overh\u00f8rer vennen din snakke bak ryggen din \u2014 konfronterer du dem eller distanserer du deg sakte?", "sv": "Du h\u00f6r din v\u00e4n prata bakom din rygg \u2014 konfronterar du dem eller distanserar du dig l\u00e5ngsamt?", "pl": "S\u0142yszysz, jak tw\u00f3j przyjaciel rozmawia o tobie za twoimi plecami \u2014 czy skonfrontujesz si\u0119 z nim, czy powoli si\u0119 odsuniesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You overhear your friend talking behind your back — do you confront them or slowly distance yourself?';
UPDATE questions
SET translations = '{"en": "You can only tell one person in this room your biggest secret \u2014 who do you trust?", "da": "Du kan kun fort\u00e6lle \u00e9n person i dette rum din st\u00f8rste hemmelighed \u2014 hvem stoler du p\u00e5?", "de": "Du kannst nur einer Person in diesem Raum dein gr\u00f6\u00dftes Geheimnis anvertrauen \u2013 wem vertraust du?", "es": "Solo puedes contarle tu mayor secreto a una persona en esta sala \u2014 \u00bfen qui\u00e9n conf\u00edas?", "pt": "S\u00f3 podes contar o teu maior segredo a uma pessoa nesta sala \u2014 em quem confias?", "ro": "Po\u021bi spune cel mai mare secret al t\u0103u doar unei persoane din aceast\u0103 camer\u0103 \u2014 \u00een cine ai \u00eencredere?", "fr": "Tu ne peux confier ton plus grand secret qu\u2019\u00e0 une seule personne ici \u2014 \u00e0 qui fais-tu confiance ?", "it": "Puoi dire il tuo segreto pi\u00f9 grande solo a una persona in questa stanza \u2014 di chi ti fidi?", "fi": "Voit kertoa vain yhdelle henkil\u00f6lle t\u00e4ss\u00e4 huoneessa suurimman salaisuutesi \u2014 kenelle luotat?", "nl": "Je kunt maar \u00e9\u00e9n persoon in deze kamer je grootste geheim vertellen \u2014 wie vertrouw je?", "no": "Du kan bare fortelle \u00e9n person i dette rommet din st\u00f8rste hemmelighet \u2014 hvem stoler du p\u00e5?", "sv": "Du kan bara ber\u00e4tta f\u00f6r en person i det h\u00e4r rummet din st\u00f6rsta hemlighet \u2014 vem litar du p\u00e5?", "pl": "Mo\u017cesz powiedzie\u0107 tylko jednej osobie w tym pokoju sw\u00f3j najwi\u0119kszy sekret \u2014 komu ufasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You can only tell one person in this room your biggest secret — who do you trust?';
UPDATE questions
SET translations = '{"en": "You\u2019re offered your dream job, but you have to move away from everyone here. Do you go?", "da": "Du f\u00e5r dit dr\u00f8mmejob, men skal flytte v\u00e6k fra alle her. G\u00f8r du det?", "de": "Du bekommst deinen Traumjob, aber musst wegziehen von allen hier. Gehst du?", "es": "Te ofrecen tu trabajo so\u00f1ado, pero tienes que mudarte lejos de todos aqu\u00ed. \u00bfLo haces?", "pt": "Oferecem-te o teu trabalho de sonho, mas tens de te mudar para longe de todos. Vais?", "ro": "\u021ai se ofer\u0103 slujba visurilor tale, dar trebuie s\u0103 te mu\u021bi departe de to\u021bi de aici. O faci?", "fr": "On t\u2019offre ton job de r\u00eave, mais tu dois d\u00e9m\u00e9nager loin de tout le monde ici. Tu y vas ?", "it": "Ti offrono il lavoro dei tuoi sogni, ma devi trasferirti lontano da tutti qui. Vai?", "fi": "Sinulle tarjotaan unelmiesi ty\u00f6paikka, mutta sinun t\u00e4ytyy muuttaa pois kaikista t\u00e4\u00e4lt\u00e4. L\u00e4hdetk\u00f6?", "nl": "Je krijgt je droombaan aangeboden, maar je moet weg van iedereen hier. Ga je?", "no": "Du f\u00e5r tilbud om dr\u00f8mmejobben din, men du m\u00e5 flytte bort fra alle her. G\u00e5r du?", "sv": "Du f\u00e5r erbjudande om ditt dr\u00f6mjobb, men du m\u00e5ste flytta bort fr\u00e5n alla h\u00e4r. \u00c5ker du?", "pl": "Oferuj\u0105 ci prac\u0119 marze\u0144, ale musisz si\u0119 przeprowadzi\u0107 z dala od wszystkich tutaj. Czy si\u0119 decydujesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You’re offered your dream job, but you have to move away from everyone here. Do you go?';
UPDATE questions
SET translations = '{"en": "If two of your best friends started dating, would you be happy or secretly terrified?", "da": "Hvis to af dine bedste venner begyndte at date, ville du v\u00e6re glad eller hemmeligt skr\u00e6mt?", "de": "Wenn zwei deiner besten Freunde anfangen w\u00fcrden, sich zu daten, w\u00e4rst du gl\u00fccklich oder heimlich ver\u00e4ngstigt?", "es": "Si dos de tus mejores amigos empezaran a salir, \u00bfestar\u00edas feliz o secretamente aterrado?", "pt": "Se dois dos teus melhores amigos come\u00e7assem a namorar, ficarias feliz ou secretamente aterrorizado?", "ro": "Dac\u0103 doi dintre cei mai buni prieteni ai t\u0103i ar \u00eencepe s\u0103 se \u00eent\u00e2lneasc\u0103, ai fi fericit sau secret \u00eengrijorat?", "fr": "Si deux de tes meilleurs amis commen\u00e7aient \u00e0 sortir ensemble, serais-tu heureux ou secr\u00e8tement terrifi\u00e9 ?", "it": "Se due dei tuoi migliori amici iniziassero a uscire insieme, saresti felice o segretamente terrorizzato?", "fi": "Jos kaksi parasta yst\u00e4v\u00e4\u00e4si alkaisi seurustella, olisitko onnellinen vai salaa kauhuissasi?", "nl": "Als twee van je beste vrienden aan het daten gaan, zou je dan blij zijn of stiekem bang?", "no": "Hvis to av dine beste venner begynte \u00e5 date, ville du v\u00e6rt glad eller hemmelig redd?", "sv": "Om tv\u00e5 av dina b\u00e4sta v\u00e4nner b\u00f6rjade dejta, skulle du vara glad eller hemligt skr\u00e4md?", "pl": "Je\u015bli dw\u00f3jka twoich najlepszych przyjaci\u00f3\u0142 zacz\u0119\u0142aby si\u0119 spotyka\u0107, czy by\u0142by\u015b szcz\u0119\u015bliwy, czy mo\u017ce w tajemnicy przera\u017cony?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If two of your best friends started dating, would you be happy or secretly terrified?';
UPDATE questions
SET translations = '{"en": "You can only choose one: the friend who always makes you laugh or the friend who actually gives good advice.", "da": "Du kan kun v\u00e6lge \u00e9n: vennen der altid f\u00e5r dig til at grine, eller vennen der faktisk giver gode r\u00e5d.", "de": "Du kannst nur einen w\u00e4hlen: den Freund, der dich immer zum Lachen bringt, oder den, der wirklich gute Ratschl\u00e4ge gibt.", "es": "Solo puedes elegir uno: el amigo que siempre te hace re\u00edr o el que realmente da buenos consejos.", "pt": "S\u00f3 podes escolher um: o amigo que te faz rir ou o que d\u00e1 bons conselhos.", "ro": "Po\u021bi alege doar unul: prietenul care te face mereu s\u0103 r\u00e2zi sau cel care d\u0103 sfaturi bune.", "fr": "Tu ne peux en choisir qu\u2019un : celui qui te fait toujours rire ou celui qui donne de bons conseils.", "it": "Puoi scegliere solo uno: l''amico che ti fa sempre ridere o l''amico che d\u00e0 davvero buoni consigli.", "fi": "Voit valita vain yhden: yst\u00e4v\u00e4n, joka aina saa sinut nauramaan, tai yst\u00e4v\u00e4n, joka oikeasti antaa hyvi\u00e4 neuvoja.", "nl": "Je kunt maar \u00e9\u00e9n kiezen: de vriend die je altijd aan het lachen maakt of de vriend die echt goed advies geeft.", "no": "Du kan bare velge \u00e9n: vennen som alltid f\u00e5r deg til \u00e5 le, eller vennen som faktisk gir gode r\u00e5d.", "sv": "Du kan bara v\u00e4lja en: v\u00e4nnen som alltid f\u00e5r dig att skratta eller v\u00e4nnen som faktiskt ger bra r\u00e5d.", "pl": "Mo\u017cesz wybra\u0107 tylko jednego: przyjaciela, kt\u00f3ry zawsze ci\u0119 roz\u015bmiesza, czy przyjaciela, kt\u00f3ry naprawd\u0119 daje dobre rady?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You can only choose one: the friend who always makes you laugh or the friend who actually gives good advice.';
UPDATE questions
SET translations = '{"en": "If you could switch lives with one friend for a week, who would it be?", "da": "Hvis du kunne bytte liv med en ven i en uge, hvem ville det v\u00e6re?", "de": "Wenn du f\u00fcr eine Woche das Leben mit einem Freund tauschen k\u00f6nntest, wer w\u00e4re es?", "es": "Si pudieras cambiar de vida con un amigo por una semana, \u00bfqui\u00e9n ser\u00eda?", "pt": "Se pudesses trocar de vida com um amigo por uma semana, quem seria?", "ro": "Dac\u0103 ai putea schimba via\u021ba cu un prieten pentru o s\u0103pt\u0103m\u00e2n\u0103, cine ar fi?", "fr": "Si tu pouvais \u00e9changer ta vie avec un ami pendant une semaine, qui serait-ce ?", "it": "Se potessi scambiare la vita con un amico per una settimana, chi sarebbe?", "fi": "Jos voisit vaihtaa el\u00e4m\u00e4\u00e4 yhden yst\u00e4v\u00e4n kanssa viikoksi, kuka se olisi?", "nl": "Als je een week het leven van een vriend zou kunnen overnemen, wie zou dat dan zijn?", "no": "Hvis du kunne bytte liv med en venn i en uke, hvem ville det v\u00e6rt?", "sv": "Om du kunde byta liv med en v\u00e4n i en vecka, vem skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zamieni\u0107 si\u0119 \u017cyciem z jednym przyjacielem na tydzie\u0144, kto by to by\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If you could switch lives with one friend for a week, who would it be?';
UPDATE questions
SET translations = '{"en": "Who would you least trust with your love life?", "da": "Hvem ville du mindst stole p\u00e5 med dit k\u00e6rlighedsliv?", "de": "Wem w\u00fcrdest du am wenigsten dein Liebesleben anvertrauen?", "es": "\u00bfEn qui\u00e9n confiar\u00edas menos con tu vida amorosa?", "pt": "Em quem menos confiarias com a tua vida amorosa?", "ro": "\u00cen cine ai avea cea mai pu\u021bin\u0103 \u00eencredere c\u00e2nd vine vorba de via\u021ba ta amoroas\u0103?", "fr": "\u00c0 qui ferais-tu le moins confiance avec ta vie amoureuse ?", "it": "Chi faresti meno fiducia per la tua vita amorosa?", "fi": "Keneen luottaisit v\u00e4hiten rakkausel\u00e4m\u00e4\u00e4si?", "nl": "Wie zou je het minst vertrouwen met je liefdesleven?", "no": "Hvem ville du minst stole p\u00e5 med kj\u00e6rlighetslivet ditt?", "sv": "Vem skulle du minst lita p\u00e5 med ditt k\u00e4rleksliv?", "pl": "Kogo by\u015b najmniej ufa\u0142 w sprawach swojego \u017cycia mi\u0142osnego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would you least trust with your love life?';
UPDATE questions
SET translations = '{"en": "If your ex dated one of your friends \u2014 who could you actually forgive?", "da": "Hvis din eks datede en af dine venner \u2014 hvem kunne du faktisk tilgive?", "de": "Wenn dein Ex mit einem deiner Freunde ausgehen w\u00fcrde \u2013 wem k\u00f6nntest du wirklich verzeihen?", "es": "Si tu ex saliera con uno de tus amigos, \u00bfa qui\u00e9n podr\u00edas realmente perdonar?", "pt": "Se o teu ex namorasse com um dos teus amigos \u2014 quem realmente perdoarias?", "ro": "Dac\u0103 fostul t\u0103u ar \u00eencepe o rela\u021bie cu unul dintre prietenii t\u0103i \u2014 pe cine ai putea ierta cu adev\u0103rat?", "fr": "Si ton ex sortait avec un de tes amis \u2014 qui pourrais-tu vraiment pardonner ?", "it": "Se il tuo ex uscisse con uno dei tuoi amici \u2014 chi potresti realmente perdonare?", "fi": "Jos entinen kumppanisi seurusteli jonkun yst\u00e4v\u00e4si kanssa \u2014 ket\u00e4 voisit oikeasti antaa anteeksi?", "nl": "Als je ex met een van je vrienden zou daten \u2014 wie zou je eigenlijk kunnen vergeven?", "no": "Hvis eksen din datet en av vennene dine \u2014 hvem kunne du faktisk tilgi?", "sv": "Om din ex dejtade en av dina v\u00e4nner \u2014 vem skulle du faktiskt kunna f\u00f6rl\u00e5ta?", "pl": "Je\u015bli tw\u00f3j by\u0142y um\u00f3wi\u0142by si\u0119 z jednym z twoich przyjaci\u00f3\u0142 \u2014 kogo m\u00f3g\u0142by\u015b w\u0142a\u015bciwie wybaczy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If your ex dated one of your friends — who could you actually forgive?';
UPDATE questions
SET translations = '{"en": "One of us has to fake-date you for a year for money \u2014 who do you pick?", "da": "En af os skal lade som om vi dater dig i et \u00e5r for penge \u2014 hvem v\u00e6lger du?", "de": "Einer von uns muss f\u00fcr ein Jahr so tun, als w\u00fcrde er mit dir ausgehen \u2013 f\u00fcr Geld. Wen w\u00e4hlst du?", "es": "Uno de nosotros tiene que fingir salir contigo por un a\u00f1o por dinero \u2014 \u00bfa qui\u00e9n eliges?", "pt": "Um de n\u00f3s tem de fingir que namora contigo durante um ano por dinheiro \u2014 quem escolhes?", "ro": "Unul dintre noi trebuie s\u0103 se prefac\u0103 c\u0103 e \u00eentr-o rela\u021bie cu tine un an pentru bani \u2014 pe cine alegi?", "fr": "L\u2019un de nous doit faire semblant de sortir avec toi pendant un an pour de l\u2019argent \u2014 qui choisis-tu ?", "it": "Uno di noi deve fingere di uscire con te per un anno per soldi \u2014 chi scegli?", "fi": "Kenen valitset, jos jonkun meist\u00e4 t\u00e4ytyy teeskennell\u00e4 deittailua kanssasi vuoden ajan rahan takia?", "nl": "Een van ons moet jou een jaar lang voor geld faken, wie kies je?", "no": "En av oss m\u00e5 late som vi dater deg i et \u00e5r for penger \u2014 hvem velger du?", "sv": "En av oss m\u00e5ste l\u00e5tsasdejta dig i ett \u00e5r f\u00f6r pengar \u2014 vem v\u00e4ljer du?", "pl": "Jedna z nas musi udawa\u0107, \u017ce si\u0119 z tob\u0105 spotyka przez rok za pieni\u0105dze \u2014 kogo wybierasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'One of us has to fake-date you for a year for money — who do you pick?';