UPDATE questions
SET translations = '{"en": "Night drive: what sight on the road would make you turn around?", "da": "Nattur: Hvilket syn p\u00e5 vejen ville f\u00e5 dig til at vende om?", "de": "Nachtfahrt: Welcher Anblick auf der Stra\u00dfe w\u00fcrde dich umdrehen lassen?", "es": "Viaje nocturno: \u00bfqu\u00e9 ver\u00edas en la carretera que te har\u00eda dar la vuelta?", "pt": "Viagem noturna: que vis\u00e3o na estrada o faria voltar atr\u00e1s?", "ro": "Noapte pe drum: ce priveli\u0219te \u021bi-ar ap\u0103rea pe \u0219osea ca s\u0103 te \u00eentorci din drum?", "fr": "Trajet de nuit : quelle vision sur la route te ferait faire demi-tour ?", "it": "Guida notturna: quale cosa sulla strada ti farebbe fare inversione?", "fi": "Y\u00f6ajelu: millainen n\u00e4ky tiell\u00e4 saisi sinut k\u00e4\u00e4ntym\u00e4\u00e4n takaisin?", "nl": "Nachtelijke rit: welk beeld op de weg zou jou doen omkeren?", "no": "Nattkj\u00f8ring: hvilket syn p\u00e5 veien ville f\u00e5tt deg til \u00e5 snu?", "sv": "Nattk\u00f6rning: vilken syn p\u00e5 v\u00e4gen skulle f\u00e5 dig att v\u00e4nda?", "pl": "Nocna jazda: jaki widok na drodze sprawi\u0142by, \u017ce zawr\u00f3cisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Night drive: what sight on the road would make you turn around?';
UPDATE questions
SET translations = '{"en": "What\u2019s the eeriest place you\u2019ve ever been\u2014and what made it feel wrong?", "da": "Hvad er det mest uhyggelige sted, du nogensinde har v\u00e6ret \u2013 og hvorfor f\u00f8ltes det forkert?", "de": "Was ist der unheimlichste Ort, an dem du je warst \u2013 und warum f\u00fchlte er sich falsch an?", "es": "\u00bfCu\u00e1l es el lugar m\u00e1s inquietante en el que has estado, y qu\u00e9 lo hizo sentir mal?", "pt": "Qual \u00e9 o lugar mais assustador em que j\u00e1 esteve \u2013 e o que o fez parecer errado?", "ro": "Care este cel mai \u00eenfior\u0103tor loc \u00een care ai fost vreodat\u0103 \u2013 \u0219i ce l-a f\u0103cut s\u0103 se simt\u0103 \u201egre\u0219it\u201d?", "fr": "Quel est l\u2019endroit le plus \u00e9trange o\u00f9 tu sois all\u00e9 \u2013 et pourquoi semblait-il \u00ab mauvais \u00bb ?", "it": "Qual \u00e8 il posto pi\u00f9 inquietante in cui sei mai stato/a, e cosa lo rendeva cos\u00ec sbagliato?", "fi": "Mik\u00e4 on oudoinkin paikka, jossa olet ollut \u2013 ja mik\u00e4 teki siit\u00e4 niin karmivan?", "nl": "Wat is de griezeligste plek waar je ooit bent geweest, en wat maakte het zo fout aanvoelen?", "no": "Hva er det ekleste/merkeligste stedet du noen gang har v\u00e6rt \u2013 og hva gjorde at det f\u00f8ltes feil?", "sv": "Vilken \u00e4r den kusligaste plats du n\u00e5gonsin varit p\u00e5 \u2013 och vad gjorde att den k\u00e4ndes fel?", "pl": "Jakie jest najbardziej upiorne miejsce, w kt\u00f3rym kiedykolwiek by\u0142e\u015b/by\u0142a\u015b \u2013 i co sprawi\u0142o, \u017ce wydawa\u0142o si\u0119 takie z\u0142e?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the eeriest place you’ve ever been—and what made it feel wrong?';
UPDATE questions
SET translations = '{"en": "Tell a true coincidence that still gives you chills.", "da": "Fort\u00e6l om et sandt tilf\u00e6lde af sammenfald, der stadig giver dig kuldegysninger.", "de": "Erz\u00e4hl von einem wahren Zufall, der dir heute noch Schauer bereitet.", "es": "Cuenta una coincidencia real que a\u00fan te da escalofr\u00edos.", "pt": "Conte uma coincid\u00eancia verdadeira que ainda te arrepia.", "ro": "Poveste\u0219te o coinciden\u021b\u0103 adev\u0103rat\u0103 care \u00eenc\u0103 \u00ee\u021bi d\u0103 fiori.", "fr": "Raconte une co\u00efncidence r\u00e9elle qui te donne encore des frissons.", "it": "Racconta una vera coincidenza che ancora ti mette i brividi.", "fi": "Kerro oikea sattuma, joka kylm\u00e4\u00e4 viel\u00e4kin selk\u00e4piit\u00e4.", "nl": "Vertel een echte toevalligheid die je nog steeds kippenvel geeft.", "no": "Fortell om et ekte sammentreff som fortsatt gir deg frysninger.", "sv": "Ber\u00e4tta om en sann slump som fortfarande ger dig rysningar.", "pl": "Opowiedz o prawdziwym zbiegu okoliczno\u015bci, kt\u00f3ry nadal przyprawia ci\u0119 o dreszcze."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Tell a true coincidence that still gives you chills.';
UPDATE questions
SET translations = '{"en": "You notice a small red light behind a vent. Do you cover it or call staff?", "da": "Du ser et lille r\u00f8dt lys bag en ventilationsrist. D\u00e6kker du det eller ringer du til personalet?", "de": "Du bemerkst ein kleines rotes Licht hinter einem L\u00fcftungsschlitz. Deckst du es ab oder rufst du das Personal?", "es": "Ves una peque\u00f1a luz roja detr\u00e1s de una rejilla. \u00bfLa cubres o llamas al personal?", "pt": "V\u00eas uma pequena luz vermelha atr\u00e1s de uma ventila\u00e7\u00e3o. Cobres ou chamas os funcion\u00e1rios?", "ro": "Observi o mic\u0103 lumin\u0103 ro\u0219ie \u00een spatele unui orificiu de ventila\u021bie. O acoperi sau chemi personalul?", "fr": "Tu remarques une petite lumi\u00e8re rouge derri\u00e8re une grille d\u2019a\u00e9ration. Tu la couvres ou tu appelles le personnel ?", "it": "Noti una piccola luce rossa dietro una grata. La copri o chiami il personale?", "fi": "Huomaat pienen punaisen valon ritil\u00e4n takana. Peit\u00e4tk\u00f6 sen vai kutsutko henkil\u00f6kuntaa?", "nl": "Je ziet een klein rood lampje achter een rooster. Dek je het af of roep je personeel?", "no": "Du legger merke til et lite r\u00f8dt lys bak en ventil. Dekker du det til eller ringer du p\u00e5 personalet?", "sv": "Du ser ett litet r\u00f6tt ljus bakom ett ventilationsgaller. T\u00e4ckar du \u00f6ver det eller ringer du p\u00e5 personal?", "pl": "Zauwa\u017casz ma\u0142e czerwone \u015bwiate\u0142ko za kratk\u0105 wentylacyjn\u0105. Zas\u0142aniasz je czy wo\u0142asz obs\u0142ug\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You notice a small red light behind a vent. Do you cover it or call staff?';
UPDATE questions
SET translations = '{"en": "Worst way to die.", "da": "V\u00e6rste m\u00e5de at d\u00f8 p\u00e5.", "de": "Schlimmste Art zu sterben.", "es": "La peor forma de morir.", "pt": "Pior maneira de morrer.", "ro": "Cel mai groaznic mod de a muri.", "fr": "La pire fa\u00e7on de mourir.", "it": "Peggior modo di morire.", "fi": "Pahin tapa kuolla.", "nl": "Ergste manier om te sterven.", "no": "Verste m\u00e5te \u00e5 d\u00f8 p\u00e5.", "sv": "V\u00e4rsta s\u00e4ttet att d\u00f6.", "pl": "Najgorszy spos\u00f3b na \u015bmier\u0107."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Worst way to die.';
UPDATE questions
SET translations = '{"en": "Would cannibalism ever be an option?", "da": "Ville kannibalisme nogensinde v\u00e6re en mulighed?", "de": "W\u00e4re Kannibalismus jemals eine Option?", "es": "\u00bfSer\u00eda el canibalismo alguna vez una opci\u00f3n?", "pt": "O canibalismo seria alguma vez uma op\u00e7\u00e3o?", "ro": "Ar fi vreodat\u0103 canibalismul o op\u021biune?", "fr": "Le cannibalisme serait-il jamais une option ?", "it": "Il cannibalismo sarebbe mai un\u2019opzione?", "fi": "Voisiko kannibalismi ikin\u00e4 olla vaihtoehto?", "nl": "Zou kannibalisme ooit een optie zijn?", "no": "Kunne kannibalisme noen gang v\u00e6rt et alternativ?", "sv": "Skulle kannibalism n\u00e5gonsin kunna vara ett alternativ?", "pl": "Czy kanibalizm m\u00f3g\u0142by kiedykolwiek by\u0107 opcj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Would cannibalism ever be an option?';
UPDATE questions
SET translations = '{"en": "\u201cGlitch in the Matrix\u201d moment\u2014got one?", "da": "Har du nogensinde haft et \u201cGlitch in the Matrix\u201d-\u00f8jeblik?", "de": "Hattest du jemals einen \u201eGlitch in der Matrix\u201c-Moment?", "es": "\u00bfHas tenido alguna vez un momento de \u201cfallo en la Matrix\u201d?", "pt": "J\u00e1 tiveste algum momento de \u201cfalha na Matrix\u201d?", "ro": "Moment de tip \u201edefec\u021biune \u00een Matrix\u201d \u2013 ai avut vreunul?", "fr": "As-tu d\u00e9j\u00e0 v\u00e9cu un moment de \u00ab bug dans la Matrice \u00bb ?", "it": "Momento \"glitch nella Matrix\": ne hai uno?", "fi": "\"Glitch in the Matrix\" -hetki \u2013 onko sinulla sellaista?", "nl": "\"Glitch in the Matrix\"-moment \u2013 heb jij er \u00e9\u00e9n?", "no": "\"Glitch in the Matrix\"-\u00f8yeblikk \u2013 har du ett?", "sv": "\"Glitch in the Matrix\"-\u00f6gonblick \u2013 har du n\u00e5got?", "pl": "Moment \"glitch in the Matrix\" \u2013 masz taki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = '“Glitch in the Matrix” moment—got one?';
UPDATE questions
SET translations = '{"en": "Would you rather meet a man or a bear in the forest?", "da": "Ville du hellere m\u00f8de en mand eller en bj\u00f8rn i skoven?", "de": "W\u00fcrdest du lieber einem Mann oder einem B\u00e4ren im Wald begegnen?", "es": "\u00bfPreferir\u00edas encontrarte con un hombre o con un oso en el bosque?", "pt": "Preferias encontrar um homem ou um urso na floresta?", "ro": "Ai prefera s\u0103 \u00eent\u00e2lne\u0219ti un b\u0103rbat sau un urs \u00een p\u0103dure?", "fr": "Pr\u00e9f\u00e8rerais-tu croiser un homme ou un ours dans la for\u00eat ?", "it": "Preferiresti incontrare un uomo o un orso nel bosco?", "fi": "Haluaisitko mieluummin kohdata mets\u00e4ss\u00e4 miehen vai karhun?", "nl": "Kom je liever een man of een beer tegen in het bos?", "no": "Vil du helst m\u00f8te en mann eller en bj\u00f8rn i skogen?", "sv": "Skulle du hellre m\u00f6ta en man eller en bj\u00f6rn i skogen?", "pl": "Wolisz spotka\u0107 w lesie m\u0119\u017cczyzn\u0119 czy nied\u017awiedzia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Would you rather meet a man or a bear in the forest?';
UPDATE questions
SET translations = '{"en": "If our home were haunted, which room would it choose and why?", "da": "Hvis vores hjem var hjems\u00f8gt, hvilket rum ville det v\u00e6lge og hvorfor?", "de": "Wenn unser Haus heimgesucht w\u00e4re, welches Zimmer w\u00fcrde es w\u00e4hlen und warum?", "es": "Si nuestra casa estuviera encantada, \u00bfqu\u00e9 habitaci\u00f3n elegir\u00eda y por qu\u00e9?", "pt": "Se a nossa casa fosse assombrada, que quarto escolheria e porqu\u00ea?", "ro": "Dac\u0103 casa noastr\u0103 ar fi b\u00e2ntuit\u0103, ce camer\u0103 ar alege \u0219i de ce?", "fr": "Si notre maison \u00e9tait hant\u00e9e, quelle pi\u00e8ce choisirait-elle et pourquoi ?", "it": "Se la nostra casa fosse infestata, quale stanza sceglierebbe e perch\u00e9?", "fi": "Jos kotimme olisi kummitustalo, mink\u00e4 huoneen se valitsisi ja miksi?", "nl": "Als ons huis zou spoken, welke kamer zou het kiezen en waarom?", "no": "Hvis hjemmet v\u00e5rt var hjems\u00f8kt, hvilket rom ville det velge og hvorfor?", "sv": "Om v\u00e5rt hem var hems\u00f6kt, vilket rum skulle det v\u00e4lja och varf\u00f6r?", "pl": "Gdyby nasz dom by\u0142 nawiedzony, kt\u00f3ry pok\u00f3j by wybra\u0142 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If our home were haunted, which room would it choose and why?';
UPDATE questions
SET translations = '{"en": "What superstition do you follow \u201cjust in case\u201d?", "da": "Hvilken overtro f\u00f8lger du \u201cbare for en sikkerheds skyld\u201d?", "de": "Welchen Aberglauben befolgst du \u201enur f\u00fcr alle F\u00e4lle\u201c?", "es": "\u00bfQu\u00e9 superstici\u00f3n sigues \u201cpor si acaso\u201d?", "pt": "Que supersti\u00e7\u00e3o segues \u201cs\u00f3 por precau\u00e7\u00e3o\u201d?", "ro": "Ce supersti\u021bie urmezi \u201edoar ca s\u0103 fii sigur\u201d?", "fr": "Quelle superstition suis-tu \u00ab juste au cas o\u00f9 \u00bb ?", "it": "Quale superstizione segui \"per sicurezza\"?", "fi": "Mit\u00e4 taikauskoa noudatat varmuuden vuoksi \"ihan vain jos\"?", "nl": "Welke bijgeloof volg je, \"voor de zekerheid\"?", "no": "Hvilken overtro f\u00f8lger du \"bare for sikkerhets skyld\"?", "sv": "Vilken vidskepelse f\u00f6ljer du \"f\u00f6r s\u00e4kerhets skull\"?", "pl": "Jakiego przes\u0105du trzymasz si\u0119 \"na wszelki wypadek\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What superstition do you follow “just in case”?';
UPDATE questions
SET translations = '{"en": "Your pet stares at an empty corner for a full minute. What could it be?", "da": "Dit k\u00e6ledyr stirrer p\u00e5 et tomt hj\u00f8rne i et helt minut. Hvad kan det v\u00e6re?", "de": "Dein Haustier starrt eine leere Ecke eine Minute lang an. Was k\u00f6nnte es sein?", "es": "Tu mascota mira fijamente una esquina vac\u00eda durante un minuto. \u00bfQu\u00e9 podr\u00eda ser?", "pt": "O teu animal de estima\u00e7\u00e3o encara um canto vazio por um minuto. O que ser\u00e1?", "ro": "Animalul t\u0103u de companie se uit\u0103 fix \u00eentr-un col\u021b gol timp de un minut. Ce ar putea fi?", "fr": "Ton animal regarde un coin vide pendant une minute enti\u00e8re. Qu\u2019est-ce que \u00e7a pourrait \u00eatre ?", "it": "Il tuo animale domestico fissa un angolo vuoto per un minuto intero. Cosa potrebbe essere?", "fi": "Lemmikkisi tuijottaa tyhj\u00e4\u00e4 nurkkaa kokonaisen minuutin. Mit\u00e4 se voisi olla?", "nl": "Je huisdier staart een volle minuut naar een lege hoek. Wat zou het kunnen zijn?", "no": "Kj\u00e6ledyret ditt stirrer p\u00e5 et tomt hj\u00f8rne i et helt minutt. Hva kan det v\u00e6re?", "sv": "Ditt husdjur stirrar p\u00e5 ett tomt h\u00f6rn i en hel minut. Vad kan det vara?", "pl": "Tw\u00f3j pupil przez ca\u0142\u0105 minut\u0119 gapi si\u0119 w pusty k\u0105t. Co to mo\u017ce by\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your pet stares at an empty corner for a full minute. What could it be?';
UPDATE questions
SET translations = '{"en": "Pick one to witness: UFO, time traveler, or a ghost \u2013 which one do you choose?", "da": "Du m\u00e5 v\u00e6lge \u00e9n ting at se: UFO, tidsrejsende eller et sp\u00f8gelse \u2013 hvad v\u00e6lger du?", "de": "Du darfst eines sehen: UFO, Zeitreisenden oder Geist \u2013 was w\u00e4hlst du?", "es": "Puedes elegir presenciar uno: un OVNI, un viajero del tiempo o un fantasma. \u00bfCu\u00e1l eliges?", "pt": "Podes escolher ver um: OVNI, viajante no tempo ou fantasma \u2013 qual escolhes?", "ro": "Po\u021bi alege s\u0103 vezi un singur lucru: un OZN, un c\u0103l\u0103tor \u00een timp sau o fantom\u0103 \u2013 ce alegi?", "fr": "Tu peux en voir un seul : OVNI, voyageur du temps ou fant\u00f4me \u2013 lequel choisis-tu ?", "it": "Scegline uno da vedere: UFO, viaggiatore nel tempo o fantasma \u2013 quale scegli?", "fi": "Valitse yksi n\u00e4ht\u00e4v\u00e4ksi: UFO, aikamatkustaja vai kummitus \u2013 mink\u00e4 otat?", "nl": "Kies er \u00e9\u00e9n om mee te maken: UFO, tijdreiziger of geest \u2013 welke kies je?", "no": "Velg \u00e9n \u00e5 v\u00e6re vitne til: UFO, tidsreisende eller et sp\u00f8kelse \u2013 hvilken velger du?", "sv": "V\u00e4lj en att f\u00e5 bevittna: UFO, tidsresen\u00e4r eller ett sp\u00f6ke \u2013 vilken v\u00e4ljer du?", "pl": "Wybierz jedno, czego chcesz by\u0107 \u015bwiadkiem: UFO, podr\u00f3\u017cnik w czasie czy duch \u2013 co wybierasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Pick one to witness: UFO, time traveler, or a ghost – which one do you choose?';
UPDATE questions
SET translations = '{"en": "A date knows a private detail you never shared. Do you ask how, or end the date?", "da": "En date ved en privat detalje, du aldrig har delt. Sp\u00f8rger du hvordan, eller stopper du daten?", "de": "Ein Date kennt ein privates Detail, das du nie geteilt hast. Fragst du, wie er/sie das wei\u00df, oder beendest du das Date?", "es": "Una cita sabe un detalle privado que nunca compartiste. \u00bfPreguntas c\u00f3mo lo sabe o terminas la cita?", "pt": "Um encontro sabe um detalhe privado que nunca contaste. Perguntas como ou acabas o encontro?", "ro": "O persoan\u0103 cu care e\u0219ti la o \u00eent\u00e2lnire \u0219tie un detaliu privat pe care nu l-ai \u00eemp\u0103rt\u0103\u0219it niciodat\u0103. \u00centrebi cum \u0219tie sau \u00eenchei \u00eent\u00e2lnirea?", "fr": "Un rendez-vous conna\u00eet un d\u00e9tail priv\u00e9 que tu n\u2019as jamais partag\u00e9. Tu demandes comment ou tu mets fin au rendez-vous ?", "it": "Un appuntamento sa un dettaglio privato che non hai mai raccontato. Chiedi come fa a saperlo o chiudi l\u2019appuntamento?", "fi": "Treffi tiet\u00e4\u00e4 yksityiskohdan, jota et ole koskaan kertonut. Kysytk\u00f6 miten h\u00e4n sen tiet\u00e4\u00e4 vai lopetatko treffit?", "nl": "Een date weet een priv\u00e9-detail dat je nooit hebt verteld. Vraag je hoe hij/zij dat weet, of be\u00ebindig je de date?", "no": "En date vet en privat detalj du aldri har delt. Sp\u00f8r du hvordan, eller avslutter du daten?", "sv": "En dejt vet en privat detalj du aldrig ber\u00e4ttat. Fr\u00e5gar du hur hen vet det, eller avslutar du dejten?", "pl": "Osoba na randce zna prywatny szczeg\u00f3\u0142, kt\u00f3rego nigdy nie zdradzi\u0142e\u015b/-a\u015b. Pytasz, sk\u0105d wie, czy ko\u0144czysz randk\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A date knows a private detail you never shared. Do you ask how, or end the date?';
UPDATE questions
SET translations = '{"en": "If you could ask a ghost one question, what would it be?", "da": "Hvis du kunne stille et sp\u00f8gelse \u00e9t sp\u00f8rgsm\u00e5l, hvad ville det v\u00e6re?", "de": "Wenn du einem Geist eine Frage stellen k\u00f6nntest, welche w\u00e4re das?", "es": "Si pudieras hacerle una pregunta a un fantasma, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pudesses fazer uma pergunta a um fantasma, qual seria?", "ro": "Dac\u0103 ai putea pune o singur\u0103 \u00eentrebare unei fantome, care ar fi?", "fr": "Si tu pouvais poser une question \u00e0 un fant\u00f4me, laquelle serait-ce ?", "it": "Se potessi fare una domanda a un fantasma, quale sarebbe?", "fi": "Jos voisit kysy\u00e4 kummitukselta yhden kysymyksen, mik\u00e4 se olisi?", "nl": "Als je een geest \u00e9\u00e9n vraag kon stellen, welke zou dat zijn?", "no": "Hvis du kunne stille et sp\u00f8kelse ett sp\u00f8rsm\u00e5l, hva ville det v\u00e6rt?", "sv": "Om du kunde st\u00e4lla ett sp\u00f6ke en fr\u00e5ga, vad skulle du fr\u00e5ga?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a zada\u0107 duchowi jedno pytanie, jakie by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If you could ask a ghost one question, what would it be?';
UPDATE questions
SET translations = '{"en": "A rideshare driver locks the doors and says the route \u201cjust changed.\u201d What do you do next?", "da": "En chauff\u00f8r l\u00e5ser d\u00f8rene og siger, at ruten \u201clige har \u00e6ndret sig.\u201d Hvad g\u00f8r du?", "de": "Ein Fahrdienstfahrer verriegelt die T\u00fcren und sagt, die Route \u201ehat sich gerade ge\u00e4ndert.\u201c Was tust du?", "es": "Un conductor cierra las puertas y dice que la ruta \u201cacaba de cambiar\u201d. \u00bfQu\u00e9 haces?", "pt": "Um motorista tranca as portas e diz que a rota \u201cacabou de mudar\u201d. O que fazes?", "ro": "\u0218oferul de rideshare \u00eencuie u\u0219ile \u0219i spune c\u0103 ruta \u201etocmai s-a schimbat.\u201d Ce faci?", "fr": "Un chauffeur verrouille les portes et dit que l\u2019itin\u00e9raire \u00ab vient de changer \u00bb. Que fais-tu ?", "it": "Un autista di rideshare chiude le portiere e dice che il percorso \"\u00e8 appena cambiato\". Cosa fai dopo?", "fi": "Kyytipalvelun kuski lukitsee ovet ja sanoo reitin \"juuri muuttuneen\". Mit\u00e4 teet seuraavaksi?", "nl": "Een rideshare-chauffeur doet de deuren op slot en zegt dat de route \"net is veranderd\". Wat doe je daarna?", "no": "En samkj\u00f8ringssj\u00e5f\u00f8r l\u00e5ser d\u00f8rene og sier at ruta \"nettopp ble endret\". Hva gj\u00f8r du n\u00e5?", "sv": "En sam\u00e5kningschauff\u00f6r l\u00e5ser d\u00f6rrarna och s\u00e4ger att rutten \"just \u00e4ndrades\". Vad g\u00f6r du sedan?", "pl": "Kierowca przejazdu z aplikacji rygluje drzwi i m\u00f3wi, \u017ce trasa \"w\u0142a\u015bnie si\u0119 zmieni\u0142a\". Co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A rideshare driver locks the doors and says the route “just changed.” What do you do next?';
UPDATE questions
SET translations = '{"en": "What\u2019s your family\u2019s oddest good-luck ritual?", "da": "Hvad er din families m\u00e6rkeligste lykkebringende ritual?", "de": "Was ist das seltsamste Gl\u00fccksritual deiner Familie?", "es": "\u00bfCu\u00e1l es el ritual de buena suerte m\u00e1s extra\u00f1o de tu familia?", "pt": "Qual \u00e9 o ritual de sorte mais estranho da tua fam\u00edlia?", "ro": "Care este cel mai ciudat ritual de noroc al familiei tale?", "fr": "Quel est le rituel porte-bonheur le plus \u00e9trange de ta famille ?", "it": "Qual \u00e8 il rito portafortuna pi\u00f9 strano della tua famiglia?", "fi": "Mik\u00e4 on perheesi oudoin onnea tuova rituaali?", "nl": "Wat is het vreemdste geluksritueel van jouw familie?", "no": "Hva er familiens rareste lykkeritual?", "sv": "Vad \u00e4r din familjs konstigaste tur-ritual?", "pl": "Jaki jest najdziwniejszy rytua\u0142 na szcz\u0119\u015bcie w twojej rodzinie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s your family’s oddest good-luck ritual?';
UPDATE questions
SET translations = '{"en": "Share a dream you remember too clearly. Any meaning?", "da": "Del en dr\u00f8m, du husker alt for tydeligt. Nogen betydning?", "de": "Teile einen Traum, an den du dich zu gut erinnerst. Irgendeine Bedeutung?", "es": "Comparte un sue\u00f1o que recuerdes con demasiada claridad. \u00bfAlg\u00fan significado?", "pt": "Partilha um sonho que te lembras demasiado bem. Tem algum significado?", "ro": "Poveste\u0219te un vis pe care \u021bi-l aminte\u0219ti prea clar. Ce \u00een\u021beles are?", "fr": "Partage un r\u00eave dont tu te souviens trop bien. Une signification ?", "it": "Condividi un sogno che ricordi fin troppo bene. Che significato potrebbe avere?", "fi": "Kerro unesta, jonka muistat liian tarkasti. Onko sill\u00e4 mielest\u00e4si jokin merkitys?", "nl": "Deel een droom die je te goed herinnert. Zie je er een betekenis in?", "no": "Del en dr\u00f8m du husker altfor godt. Noen mening i den?", "sv": "Dela en dr\u00f6m du minns alldeles f\u00f6r tydligt. N\u00e5gon betydelse?", "pl": "Podziel si\u0119 snem, kt\u00f3ry pami\u0119tasz a\u017c za dobrze. Ma dla ciebie jakie\u015b znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Share a dream you remember too clearly. Any meaning?';
UPDATE questions
SET translations = '{"en": "A crime case you can\u2019t stop thinking about\u2014why this one?", "da": "En kriminalsag, du ikke kan glemme \u2013 hvorfor netop den?", "de": "Ein Kriminalfall, \u00fcber den du nicht aufh\u00f6ren kannst nachzudenken \u2013 warum dieser?", "es": "Un caso criminal que no puedes dejar de pensar \u2013 \u00bfpor qu\u00e9 ese?", "pt": "Um caso criminal que n\u00e3o consegues esquecer \u2013 porqu\u00ea esse?", "ro": "Un caz criminal de care nu te po\u021bi desprinde \u2013 de ce tocmai acesta?", "fr": "Une affaire criminelle \u00e0 laquelle tu penses encore \u2013 pourquoi celle-l\u00e0 ?", "it": "Un caso di cronaca nera a cui non riesci a smettere di pensare: perch\u00e9 proprio questo?", "fi": "Rikostapaus, jota et saa mielest\u00e4si \u2013 miksi juuri t\u00e4m\u00e4?", "nl": "Een strafzaak waar je maar aan blijft denken \u2013 waarom juist deze?", "no": "En kriminalsak du ikke klarer \u00e5 slutte \u00e5 tenke p\u00e5 \u2013 hvorfor akkurat denne?", "sv": "Ett kriminalfall du inte kan sluta t\u00e4nka p\u00e5 \u2013 varf\u00f6r just det?", "pl": "Sprawa kryminalna, o kt\u00f3rej nie mo\u017cesz przesta\u0107 my\u015ble\u0107 \u2013 dlaczego w\u0142a\u015bnie ta?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A crime case you can’t stop thinking about—why this one?';
UPDATE questions
SET translations = '{"en": "Footsteps outside your door, peephole blocked \u2013 what do you do?", "da": "Fodtrin udenfor din d\u00f8r, kighul blokeret \u2013 hvad g\u00f8r du?", "de": "Schritte vor deiner T\u00fcr, Spion blockiert \u2013 was tust du?", "es": "Pasos fuera de tu puerta, mirilla bloqueada \u2013 \u00bfqu\u00e9 haces?", "pt": "Passos fora da tua porta, olho m\u00e1gico bloqueado \u2013 o que fazes?", "ro": "Se aud pa\u0219i \u00een fa\u021ba u\u0219ii tale, vizorul este blocat \u2013 ce faci?", "fr": "Des pas devant ta porte, judas bloqu\u00e9 \u2013 que fais-tu ?", "it": "Passi fuori dalla porta, spioncino coperto \u2013 cosa fai?", "fi": "Askeleita oven ulkopuolella, ovisilm\u00e4 peitetty \u2013 mit\u00e4 teet?", "nl": "Voetstappen buiten je deur, deurspion afgeplakt \u2013 wat doe je?", "no": "Fottrinn utenfor d\u00f8ren din, d\u00f8rspionen er blokkert \u2013 hva gj\u00f8r du?", "sv": "Fotsteg utanf\u00f6r din d\u00f6rr, titth\u00e5let \u00e4r blockerat \u2013 vad g\u00f6r du?", "pl": "Kroki za drzwiami, wizjer zas\u0142oni\u0119ty \u2013 co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Footsteps outside your door, peephole blocked – what do you do?';
UPDATE questions
SET translations = '{"en": "Motion sensor lights turn on in the empty next room. How do you clear the space?", "da": "Bev\u00e6gelsessensorlys t\u00e6nder i det tomme rum ved siden af. Hvordan tjekker du det?", "de": "Bewegungsmelderlicht geht im leeren Nebenraum an. Wie pr\u00fcfst du den Raum?", "es": "Las luces con sensor se encienden en la habitaci\u00f3n vac\u00eda de al lado. \u00bfC\u00f3mo revisas el lugar?", "pt": "A luz do sensor de movimento acende-se no quarto ao lado. Como verificas?", "ro": "Lumina cu senzor de mi\u0219care se aprinde \u00een camera goal\u0103 de al\u0103turi. Cum verifici spa\u021biul?", "fr": "Les lumi\u00e8res \u00e0 capteur de mouvement s\u2019allument dans la pi\u00e8ce voisine vide. Comment v\u00e9rifies-tu ?", "it": "Le luci con sensore di movimento si accendono nella stanza vuota accanto. Come \"ripulisci\" lo spazio?", "fi": "Liiketunnistinvalot syttyv\u00e4t tyhj\u00e4\u00e4n viereiseen huoneeseen. Miten \"puhdistat\" tilan?", "nl": "Bewegingssensorlampen gaan aan in de lege kamer naast je. Hoe \"reinig\" je de ruimte?", "no": "Bevegelsessensorlysene sl\u00e5r seg p\u00e5 i det tomme rommet ved siden av. Hvordan \"renser\" du stedet?", "sv": "R\u00f6relsesensorlampor t\u00e4nds i det tomma rummet bredvid. Hur \"rensar\" du platsen?", "pl": "Czujniki ruchu zapalaj\u0105 \u015bwiat\u0142o w pustym pokoju obok. Jak \"oczyszczasz\" t\u0119 przestrze\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Motion sensor lights turn on in the empty next room. How do you clear the space?';
UPDATE questions
SET translations = '{"en": "You can ask a spirit one yes/no question. What do you ask?", "da": "Du kan stille en \u00e5nd \u00e9t ja/nej-sp\u00f8rgsm\u00e5l. Hvad sp\u00f8rger du om?", "de": "Du darfst einem Geist eine Ja/Nein-Frage stellen. Was fragst du?", "es": "Puedes hacerle una pregunta de s\u00ed/no a un esp\u00edritu. \u00bfQu\u00e9 preguntas?", "pt": "Podes fazer uma pergunta de sim/n\u00e3o a um esp\u00edrito. O que perguntas?", "ro": "Po\u021bi pune unei spirite o \u00eentrebare la care r\u0103spunde doar \u201eda\u201d sau \u201enu\u201d. Ce \u00eentrebi?", "fr": "Tu peux poser une question par oui/non \u00e0 un esprit. Que demandes-tu ?", "it": "Puoi fare a uno spirito una sola domanda a cui si risponde s\u00ec/no. Cosa chiedi?", "fi": "Voit kysy\u00e4 hengelt\u00e4 yhden kyll\u00e4/ei -kysymyksen. Mit\u00e4 kysyt?", "nl": "Je mag \u00e9\u00e9n ja/nee-vraag aan een geest stellen. Wat vraag je?", "no": "Du kan stille en \u00e5nd ett ja/nei-sp\u00f8rsm\u00e5l. Hva sp\u00f8r du om?", "sv": "Du f\u00e5r st\u00e4lla en ja/nej-fr\u00e5ga till en ande. Vad fr\u00e5gar du?", "pl": "Mo\u017cesz zada\u0107 duchowi jedno pytanie z odpowiedzi\u0105 tak/nie. O co pytasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You can ask a spirit one yes/no question. What do you ask?';
UPDATE questions
SET translations = '{"en": "You find an AirTag/tracker alert on your phone after a night out. What do you do?", "da": "Du f\u00e5r en AirTag/Tracker-advarsel p\u00e5 din telefon efter en aften ude. Hvad g\u00f8r du?", "de": "Du erh\u00e4ltst nach einer Nacht drau\u00dfen eine AirTag/Tracker-Warnung auf deinem Handy. Was tust du?", "es": "Recibes una alerta de AirTag/rastreador en tu tel\u00e9fono despu\u00e9s de una noche fuera. \u00bfQu\u00e9 haces?", "pt": "Recebes um alerta de AirTag/rastreador no teu telem\u00f3vel depois de uma noite fora. O que fazes?", "ro": "Prime\u0219ti o alert\u0103 pe telefon despre un AirTag/tracker dup\u0103 o noapte \u00een ora\u0219. Ce faci?", "fr": "Tu re\u00e7ois une alerte AirTag/suivi sur ton t\u00e9l\u00e9phone apr\u00e8s une soir\u00e9e dehors. Que fais-tu ?", "it": "Trovi una notifica di AirTag/tracker sul telefono dopo una serata fuori. Cosa fai?", "fi": "Saat AirTag-/seurantalaitteen h\u00e4lytyksen puhelimeesi illanvieton j\u00e4lkeen. Mit\u00e4 teet?", "nl": "Je krijgt na een avond uit een AirTag-/tracker-melding op je telefoon. Wat doe je?", "no": "Du f\u00e5r varsel om en AirTag/tracker p\u00e5 telefonen etter en kveld ute. Hva gj\u00f8r du?", "sv": "Du f\u00e5r en AirTag-/tracker-varning p\u00e5 mobilen efter en utekv\u00e4ll. Vad g\u00f6r du?", "pl": "Po wieczornym wyj\u015bciu dostajesz na telefon powiadomienie o AirTagu/trackerze. Co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You find an AirTag/tracker alert on your phone after a night out. What do you do?';
UPDATE questions
SET translations = '{"en": "Rate your belief in ghosts, 0\u201310, and defend it.", "da": "Bed\u00f8m din tro p\u00e5 sp\u00f8gelser fra 0\u201310, og forsvar den.", "de": "Bewerte deinen Glauben an Geister von 0 bis 10 und verteidige ihn.", "es": "Califica tu creencia en fantasmas del 0 al 10 y defi\u00e9ndela.", "pt": "Avalia a tua cren\u00e7a em fantasmas de 0 a 10 e defende-a.", "ro": "Evalueaz\u0103-\u021bi credin\u021ba \u00een fantome de la 0 la 10 \u0219i ap\u0103r\u0103-\u021bi r\u0103spunsul.", "fr": "\u00c9value ta croyance aux fant\u00f4mes de 0 \u00e0 10 et d\u00e9fends-la.", "it": "Valuta quanto credi ai fantasmi da 0 a 10 e difendi il tuo voto.", "fi": "Arvioi uskosi kummituksiin asteikolla 0\u201310 ja perustele se.", "nl": "Geef je geloof in geesten een cijfer van 0\u201310 en verdedig het.", "no": "Ranger troen din p\u00e5 sp\u00f8kelser fra 0\u201310, og forklar.", "sv": "Betygs\u00e4tt din tro p\u00e5 sp\u00f6ken, 0\u201310, och f\u00f6rsvara betyget.", "pl": "Oce\u0144 swoj\u0105 wiar\u0119 w duchy w skali 0\u201310 i j\u0105 uzasadnij."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Rate your belief in ghosts, 0–10, and defend it.';
UPDATE questions
SET translations = '{"en": "A child in a store waves behind you and says \u201cbye.\u201d There\u2019s no one there. How do you react?", "da": "Et barn i en butik vinker bag dig og siger \u201chej hej\u201d. Der er ingen der. Hvad g\u00f8r du?", "de": "Ein Kind im Laden winkt dir hinterher und sagt \u201eTsch\u00fcss\u201c. Niemand ist da. Wie reagierst du?", "es": "Un ni\u00f1o en una tienda te saluda y dice \u201cadi\u00f3s\u201d. No hay nadie all\u00ed. \u00bfC\u00f3mo reaccionas?", "pt": "Uma crian\u00e7a numa loja acena-te e diz \u201ctchau\u201d. N\u00e3o h\u00e1 ningu\u00e9m. Como reages?", "ro": "Un copil \u00eentr-un magazin \u00ee\u021bi face cu m\u00e2na \u0219i spune \u201epa.\u201d Nu e nimeni acolo. Cum reac\u021bionezi?", "fr": "Un enfant dans un magasin te fait signe et dit \u00ab au revoir \u00bb. Il n\u2019y a personne. Comment r\u00e9agis-tu ?", "it": "Un bambino in un negozio saluta dietro di te e dice \"ciao\". Non c\u2019\u00e8 nessuno. Come reagisci?", "fi": "Lapsi kaupassa vilkuttaa selk\u00e4si takana ja sanoo \"hei hei\". Ket\u00e4\u00e4n ei n\u00e4y. Miten reagoit?", "nl": "Een kind in een winkel zwaait achter je en zegt \"doei\". Er is niemand. Hoe reageer je?", "no": "Et barn i en butikk vinker bak deg og sier \"ha det\". Det er ingen der. Hvordan reagerer du?", "sv": "Ett barn i en butik vinkar bakom dig och s\u00e4ger \"hej d\u00e5\". Det finns ingen d\u00e4r. Hur reagerar du?", "pl": "Dziecko w sklepie macha za twoimi plecami i m\u00f3wi \"pa\". Nikogo tam nie ma. Jak reagujesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A child in a store waves behind you and says “bye.” There’s no one there. How do you react?';
UPDATE questions
SET translations = '{"en": "What childhood fear secretly still lives rent-free?", "da": "Hvilken barndomsfrygt bor stadig gratis i dit hoved?", "de": "Welche Kindheitsangst lebt immer noch mietfrei in deinem Kopf?", "es": "\u00bfQu\u00e9 miedo de la infancia sigue viviendo gratis en tu mente?", "pt": "Que medo de inf\u00e2ncia ainda vive de gra\u00e7a na tua mente?", "ro": "Ce fric\u0103 din copil\u0103rie \u00eenc\u0103 mai tr\u0103ie\u0219te \u00een tine \u201ecu chirie gratuit\u0103\u201d?", "fr": "Quelle peur d\u2019enfance vit encore gratuitement dans ta t\u00eate ?", "it": "Quale paura d\u2019infanzia vive ancora di nascosto nella tua testa?", "fi": "Mik\u00e4 lapsuuden pelko asuu salaa edelleen mieless\u00e4si?", "nl": "Welke kinderangst woont stiekem nog steeds in je hoofd?", "no": "Hvilken barndomsfrykt bor fortsatt i deg, i hemmelighet?", "sv": "Vilken barndomsr\u00e4dsla bor fortfarande gratis i ditt huvud?", "pl": "Kt\u00f3ry l\u0119k z dzieci\u0144stwa wci\u0105\u017c po cichu mieszka w twojej g\u0142owie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What childhood fear secretly still lives rent-free?';
UPDATE questions
SET translations = '{"en": "Create a spooky playlist title and its first three tracks.", "da": "Lav en uhyggelig playliste-titel og dens f\u00f8rste tre numre.", "de": "Erstelle einen gruseligen Playlist-Titel und die ersten drei Songs.", "es": "Crea un t\u00edtulo de lista espeluznante y sus tres primeras canciones.", "pt": "Cria um t\u00edtulo assustador de playlist e as suas tr\u00eas primeiras faixas.", "ro": "Creeaz\u0103 un titlu de playlist \u00eenfrico\u0219\u0103tor \u0219i primele trei melodii.", "fr": "Cr\u00e9e une playlist effrayante et donne-lui ses trois premiers morceaux.", "it": "Crea un titolo inquietante per una playlist e i suoi primi tre brani.", "fi": "Keksi karmiva soittolistan nimi ja sen kolme ensimm\u00e4ist\u00e4 kappaletta.", "nl": "Bedenk een griezelige playlist-titel en de eerste drie nummers.", "no": "Lag en skummel spilleliste-tittel og de tre f\u00f8rste l\u00e5tene.", "sv": "Hitta p\u00e5 en l\u00e4skig spellisttitel och dess tre f\u00f6rsta l\u00e5tar.", "pl": "Wymy\u015bl straszny tytu\u0142 playlisty i jej trzy pierwsze utwory."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Create a spooky playlist title and its first three tracks.';
UPDATE questions
SET translations = '{"en": "A neighbor says your lights flicker every night at the same minute. You weren\u2019t home. Thoughts?", "da": "En nabo siger, at dine lys blinker hver nat p\u00e5 samme tidspunkt. Du var ikke hjemme. Tanker?", "de": "Ein Nachbar sagt, deine Lichter flackern jede Nacht zur selben Minute. Du warst nicht zu Hause. Gedanken?", "es": "Un vecino dice que tus luces parpadean cada noche a la misma hora. No estabas en casa. \u00bfPensamientos?", "pt": "Um vizinho diz que as tuas luzes piscam todas as noites \u00e0 mesma hora. N\u00e3o estavas em casa. Pensamentos?", "ro": "Un vecin spune c\u0103 luminile tale p\u00e2lp\u00e2ie \u00een fiecare noapte la aceea\u0219i or\u0103. Tu nu erai acas\u0103. Ce crezi?", "fr": "Un voisin dit que tes lumi\u00e8res clignotent chaque nuit \u00e0 la m\u00eame heure. Tu n\u2019\u00e9tais pas chez toi. Des pens\u00e9es ?", "it": "Un vicino dice che le tue luci sfarfallano ogni notte alla stessa ora. Tu non eri a casa. Pensieri?", "fi": "Naapuri sanoo, ett\u00e4 valosi vilkkuvat joka ilta samaan aikaan. Et ollut kotona. Mit\u00e4 ajattelet?", "nl": "Een buur zegt dat je lampen elke nacht op hetzelfde moment flikkeren. Jij was niet thuis. Mening?", "no": "En nabo sier at lysene dine blinker hver natt p\u00e5 samme minutt. Du var ikke hjemme. Tanker?", "sv": "En granne s\u00e4ger att dina lampor blinkar varje natt p\u00e5 samma minut. Du var inte hemma. Tankar?", "pl": "S\u0105siad m\u00f3wi, \u017ce twoje \u015bwiat\u0142a migaj\u0105 co noc o tej samej minucie. Nie by\u0142o ci\u0119 w domu. Co o tym my\u015blisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A neighbor says your lights flicker every night at the same minute. You weren’t home. Thoughts?';
UPDATE questions
SET translations = '{"en": "Most unsettling piece of trivia you know?", "da": "Hvilken foruroligende fakta ved du?", "de": "Welches beunruhigende Wissen kennst du?", "es": "\u00bfQu\u00e9 dato inquietante conoces?", "pt": "Qual \u00e9 o facto mais perturbador que conheces?", "ro": "Care este cea mai tulbur\u0103toare informa\u021bie pe care o \u0219tii?", "fr": "Quelle information troublante connais-tu ?", "it": "Qual \u00e8 il fatto curioso pi\u00f9 inquietante che conosci?", "fi": "Mik\u00e4 on ahdistavin nippelitieto, jonka tied\u00e4t?", "nl": "Wat is het meest verontrustende weetje dat je kent?", "no": "Hva er den mest urovekkende fun facten du kjenner til?", "sv": "Vilken \u00e4r den mest obehagliga fakta du k\u00e4nner till?", "pl": "Jaka jest najbardziej niepokoj\u0105ca ciekawostka, jak\u0105 znasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Most unsettling piece of trivia you know?';
UPDATE questions
SET translations = '{"en": "If mirrors recorded one minute a day, which minute would you replay?", "da": "Hvis spejle optog \u00e9t minut om dagen, hvilket minut ville du gense?", "de": "Wenn Spiegel eine Minute pro Tag aufzeichnen w\u00fcrden, welche Minute w\u00fcrdest du wieder abspielen?", "es": "Si los espejos grabaran un minuto al d\u00eda, \u00bfqu\u00e9 minuto volver\u00edas a ver?", "pt": "Se os espelhos gravassem um minuto por dia, qual voltarias a ver?", "ro": "Dac\u0103 oglinzile ar \u00eenregistra un minut pe zi, ce minut ai revedea?", "fr": "Si les miroirs enregistraient une minute par jour, laquelle rejouerais-tu ?", "it": "Se gli specchi registrassero un minuto al giorno, quale minuto vorresti rivedere?", "fi": "Jos peilit tallentaisivat yhden minuutin p\u00e4iv\u00e4ss\u00e4, mink\u00e4 minuutin haluaisit katsoa uudelleen?", "nl": "Als spiegels \u00e9\u00e9n minuut per dag zouden opnemen, welke minuut zou jij terugkijken?", "no": "Hvis speil tok opp ett minutt om dagen, hvilket minutt ville du spolt tilbake til?", "sv": "Om speglar spelade in en minut om dagen, vilken minut skulle du spela upp igen?", "pl": "Gdyby lustra nagrywa\u0142y jedn\u0105 minut\u0119 dziennie, kt\u00f3r\u0105 minut\u0119 chcia\u0142(a)by\u015b odtworzy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If mirrors recorded one minute a day, which minute would you replay?';
UPDATE questions
SET translations = '{"en": "A stranger knows your name and favorite snack. Explain it rationally.", "da": "En fremmed kender dit navn og din yndlingssnack. Forklar det rationelt.", "de": "Ein Fremder kennt deinen Namen und deinen Lieblingssnack. Erkl\u00e4re es rational.", "es": "Un desconocido sabe tu nombre y tu aperitivo favorito. Expl\u00edcalo racionalmente.", "pt": "Um estranho sabe o teu nome e o teu lanche favorito. Explica racionalmente.", "ro": "Un str\u0103in \u00ee\u021bi \u0219tie numele \u0219i gustarea preferat\u0103. Explic\u0103 logic.", "fr": "Un inconnu conna\u00eet ton nom et ton encas pr\u00e9f\u00e9r\u00e9. Explique rationnellement.", "it": "Uno sconosciuto conosce il tuo nome e il tuo snack preferito. Spiegalo in modo razionale.", "fi": "Tuntematon tiet\u00e4\u00e4 nimesi ja lempiev\u00e4\u00e4si. Selit\u00e4 t\u00e4m\u00e4 j\u00e4rkev\u00e4sti.", "nl": "Een onbekende kent je naam en je favoriete snack. Verklaar het op een rationele manier.", "no": "En fremmed vet navnet ditt og favorittsnacken din. Forklar det p\u00e5 en rasjonell m\u00e5te.", "sv": "En fr\u00e4mling kan ditt namn och ditt favoritsnack. F\u00f6rklara det rationellt.", "pl": "Obca osoba zna twoje imi\u0119 i ulubion\u0105 przek\u0105sk\u0119. Wyja\u015bnij to racjonalnie."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A stranger knows your name and favorite snack. Explain it rationally.';
UPDATE questions
SET translations = '{"en": "You\u2019re walking home and all the streetlights go out at once. What\u2019s your next move?", "da": "Du g\u00e5r hjem, og alle gadelygter slukker p\u00e5 \u00e9n gang. Hvad g\u00f8r du?", "de": "Du gehst nach Hause, und alle Stra\u00dfenlaternen gehen gleichzeitig aus. Was tust du?", "es": "Caminas a casa y todas las farolas se apagan a la vez. \u00bfQu\u00e9 haces?", "pt": "Caminhas para casa e todos os candeeiros da rua apagam-se de uma vez. O que fazes?", "ro": "Mergi spre cas\u0103 \u0219i toate felinarele se sting deodat\u0103. Ce faci?", "fr": "Tu rentres chez toi et tous les lampadaires s\u2019\u00e9teignent d\u2019un coup. Que fais-tu ?", "it": "Stai tornando a casa a piedi e tutti i lampioni si spengono all\u2019improvviso. Qual \u00e8 la tua prossima mossa?", "fi": "K\u00e4velet kotiin ja kaikki katuvalot sammuvat yht\u00e4 aikaa. Mit\u00e4 teet seuraavaksi?", "nl": "Je loopt naar huis en alle lantaarnpalen gaan tegelijk uit. Wat is je volgende stap?", "no": "Du g\u00e5r hjem, og alle gatelysene slukker samtidig. Hva gj\u00f8r du da?", "sv": "Du g\u00e5r hem och alla gatlyktor slocknar samtidigt. Vad g\u00f6r du sen?", "pl": "Idziesz pieszo do domu i nagle wszystkie latarnie gasn\u0105. Jaki jest tw\u00f3j nast\u0119pny krok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You’re walking home and all the streetlights go out at once. What’s your next move?';
UPDATE questions
SET translations = '{"en": "What smell would make a place instantly haunted to you?", "da": "Hvilken lugt ville f\u00e5 et sted til straks at f\u00f8les hjems\u00f8gt?", "de": "Welcher Geruch w\u00fcrde einen Ort sofort spukhaft machen?", "es": "\u00bfQu\u00e9 olor har\u00eda que un lugar se sintiera inmediatamente encantado?", "pt": "Que cheiro faria um lugar parecer imediatamente assombrado?", "ro": "Ce miros ar face un loc s\u0103 par\u0103 instantaneu b\u00e2ntuit?", "fr": "Quelle odeur rendrait un endroit instantan\u00e9ment hant\u00e9 ?", "it": "Quale odore renderebbe un luogo istantaneamente infestato, per te?", "fi": "Mik\u00e4 haju saisi paikan tuntumaan heti kuin siell\u00e4 kummittelisi?", "nl": "Welke geur zou een plek voor jou meteen spookachtig maken?", "no": "Hvilken lukt ville f\u00e5tt et sted til \u00e5 f\u00f8les umiddelbart hjems\u00f8kt for deg?", "sv": "Vilken doft skulle f\u00e5 en plats att k\u00e4nnas direkt hems\u00f6kt f\u00f6r dig?", "pl": "Jaki zapach sprawi\u0142by, \u017ce miejsce od razu wyda\u0142oby ci si\u0119 nawiedzone?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What smell would make a place instantly haunted to you?';
UPDATE questions
SET translations = '{"en": "D\u00e9j\u00e0 vu hits hard\u2014but you know the next 10 seconds. Do you follow the script or try to break it?", "da": "D\u00e9j\u00e0 vu rammer h\u00e5rdt \u2013 men du kender de n\u00e6ste 10 sekunder. F\u00f8lger du scriptet eller bryder det?", "de": "D\u00e9j\u00e0-vu trifft dich hart \u2013 aber du kennst die n\u00e4chsten 10 Sekunden. Folgst du dem Ablauf oder brichst du ihn?", "es": "El d\u00e9j\u00e0 vu golpea fuerte, pero sabes los pr\u00f3ximos 10 segundos. \u00bfSigues el guion o lo rompes?", "pt": "O d\u00e9j\u00e0 vu atinge-te forte \u2013 mas sabes os pr\u00f3ximos 10 segundos. Segues o gui\u00e3o ou quebras?", "ro": "D\u00e9j\u00e0 vu te love\u0219te puternic \u2013 dar \u0219tii urm\u0103toarele 10 secunde. Urmezi scenariul sau \u00eel rupi?", "fr": "Le d\u00e9j\u00e0-vu te frappe fort \u2013 mais tu connais les dix prochaines secondes. Tu suis le script ou tu le brises ?", "it": "Il d\u00e9j\u00e0 vu \u00e8 fortissimo, ma tu conosci i prossimi 10 secondi. Segui il copione o provi a romperlo?", "fi": "D\u00e9j\u00e0-vu iskee kovaa \u2013 mutta tied\u00e4t seuraavat 10 sekuntia. Seuraatko k\u00e4sikirjoitusta vai yrit\u00e4tk\u00f6 rikkoa sen?", "nl": "Heftig d\u00e9j\u00e0 vu \u2013 maar je weet de komende 10 seconden. Volg je het script of probeer je het te doorbreken?", "no": "Deja vu treffer skikkelig, men du vet hva som skjer de neste 10 sekundene. F\u00f8lger du manus eller pr\u00f8ver du \u00e5 bryte det?", "sv": "Kraftig d\u00e9j\u00e0 vu \u2013 men du vet vad som h\u00e4nder de n\u00e4sta 10 sekunderna. F\u00f6ljer du manus eller f\u00f6rs\u00f6ker du bryta det?", "pl": "Mocne d\u00e9j\u00e0 vu \u2013 ale znasz nast\u0119pne 10 sekund. Trzymasz si\u0119 scenariusza czy pr\u00f3bujesz go przerwa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Déjà vu hits hard—but you know the next 10 seconds. Do you follow the script or try to break it?';
UPDATE questions
SET translations = '{"en": "Which ancient myth feels strangely plausible?", "da": "Hvilken gammel myte f\u00f8les m\u00e6rkeligt plausibel?", "de": "Welcher alte Mythos f\u00fchlt sich seltsam plausibel an?", "es": "\u00bfQu\u00e9 mito antiguo te parece extra\u00f1amente plausible?", "pt": "Que mito antigo te parece estranhamente plaus\u00edvel?", "ro": "Ce mit antic \u021bi se pare ciudat de plauzibil?", "fr": "Quel mythe ancien te semble \u00e9trangement plausible ?", "it": "Quale mito antico ti sembra stranamente plausibile?", "fi": "Mik\u00e4 muinainen myytti tuntuu oudon uskottavalta?", "nl": "Welke oude mythe voelt vreemd genoeg geloofwaardig?", "no": "Hvilken gammel myte f\u00f8les merkelig plausibel?", "sv": "Vilken antik myt k\u00e4nns m\u00e4rkligt trov\u00e4rdig?", "pl": "Kt\u00f3ry staro\u017cytny mit wydaje ci si\u0119 dziwnie wiarygodny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Which ancient myth feels strangely plausible?';
UPDATE questions
SET translations = '{"en": "Describe a time technology acted too smart.", "da": "Beskriv en tid, hvor teknologien virkede for smart.", "de": "Beschreibe einen Moment, in dem Technologie zu schlau wirkte.", "es": "Describe un momento en que la tecnolog\u00eda actu\u00f3 demasiado inteligente.", "pt": "Descreve um momento em que a tecnologia pareceu esperta demais.", "ro": "Descrie un moment c\u00e2nd tehnologia a p\u0103rut prea inteligent\u0103.", "fr": "D\u00e9cris un moment o\u00f9 la technologie a sembl\u00e9 trop intelligente.", "it": "Descrivi una volta in cui la tecnologia si \u00e8 comportata come se fosse troppo intelligente.", "fi": "Kuvaile kerta, jolloin teknologia toimi liian \u00e4lykk\u00e4\u00e4sti.", "nl": "Beschrijf een moment waarop technologie t\u00e9 slim leek te zijn.", "no": "Beskriv en gang teknologien oppf\u00f8rte seg altfor smart.", "sv": "Beskriv en g\u00e5ng n\u00e4r tekniken betedde sig alldeles f\u00f6r smart.", "pl": "Opisz sytuacj\u0119, kiedy technologia zachowa\u0142a si\u0119 zbyt \u201einteligentnie\u201d."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Describe a time technology acted too smart.';
UPDATE questions
SET translations = '{"en": "You can remove one fear forever\u2014what do you choose?", "da": "Du kan fjerne \u00e9n frygt for altid \u2013 hvilken v\u00e6lger du?", "de": "Du kannst eine Angst f\u00fcr immer beseitigen \u2013 welche w\u00e4hlst du?", "es": "Puedes eliminar un miedo para siempre \u2013 \u00bfcu\u00e1l eliges?", "pt": "Podes eliminar um medo para sempre \u2013 qual escolhes?", "ro": "Po\u021bi elimina o fric\u0103 pentru totdeauna \u2013 care ar fi?", "fr": "Tu peux supprimer une peur pour toujours \u2013 laquelle choisis-tu ?", "it": "Puoi eliminare per sempre una paura: quale scegli?", "fi": "Voit poistaa yhden pelon ikuisesti \u2013 mink\u00e4 valitset?", "nl": "Je mag \u00e9\u00e9n angst voor altijd wegnemen \u2013 welke kies je?", "no": "Du kan fjerne \u00e9n frykt for alltid \u2013 hvilken velger du?", "sv": "Du kan ta bort en r\u00e4dsla f\u00f6r alltid \u2013 vilken v\u00e4ljer du?", "pl": "Mo\u017cesz usun\u0105\u0107 jeden l\u0119k na zawsze \u2013 kt\u00f3ry wybierasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You can remove one fear forever—what do you choose?';
UPDATE questions
SET translations = '{"en": "A stranger insists they know you from a city you\u2019ve never visited\u2014and name a bar you \u201cliked.\u201d Next step?", "da": "En fremmed insisterer p\u00e5, at de kender dig fra en by, du aldrig har bes\u00f8gt \u2013 og n\u00e6vner en bar, du \u201ckunne lide.\u201d Hvad g\u00f8r du?", "de": "Ein Fremder besteht darauf, dich aus einer Stadt zu kennen, die du nie besucht hast \u2013 und nennt eine Bar, die du \u201emochtest\u201c. Was tust du?", "es": "Un extra\u00f1o insiste en que te conoce de una ciudad que nunca visitaste, y nombra un bar que \u201cte gustaba\u201d. \u00bfQu\u00e9 haces?", "pt": "Um estranho insiste que te conhece de uma cidade onde nunca estiveste \u2013 e menciona um bar de que \u201cgostavas\u201d. E agora?", "ro": "Un str\u0103in insist\u0103 c\u0103 te cunoa\u0219te dintr-un ora\u0219 \u00een care n-ai fost niciodat\u0103 \u2013 \u0219i men\u021bioneaz\u0103 un bar care \u201e\u021bi-a pl\u0103cut\u201d. Ce faci?", "fr": "Un inconnu insiste sur le fait qu\u2019il te conna\u00eet d\u2019une ville o\u00f9 tu n\u2019es jamais all\u00e9 \u2013 et nomme un bar que tu \u00ab aimais \u00bb. Que fais-tu ?", "it": "Uno sconosciuto insiste di conoscerti da una citt\u00e0 in cui non sei mai stato/a e nomina un bar che ti \u201cpiaceva\u201d. Prossima mossa?", "fi": "Tuntematon v\u00e4itt\u00e4\u00e4 tuntevansa sinut kaupungista, jossa et ole koskaan k\u00e4ynyt \u2013 ja mainitsee baarin, josta \u201cpidit\u201d. Mit\u00e4 teet seuraavaksi?", "nl": "Een onbekende beweert je te kennen uit een stad waar je nooit bent geweest \u2013 en noemt een bar die je zogenaamd \u201cleuk vond\u201d. Wat nu?", "no": "En fremmed insisterer p\u00e5 at de kjenner deg fra en by du aldri har v\u00e6rt i \u2013 og nevner en bar du visstnok \u201clikte\u201d. Hva gj\u00f8r du n\u00e5?", "sv": "En fr\u00e4mling p\u00e5st\u00e5r att hen k\u00e4nner dig fr\u00e5n en stad du aldrig varit i \u2013 och n\u00e4mner en bar du \u201dgillade\u201d. Vad g\u00f6r du sen?", "pl": "Obca osoba upiera si\u0119, \u017ce zna ci\u0119 z miasta, w kt\u00f3rym nigdy nie by\u0142e\u015b/by\u0142a\u015b \u2013 i wymienia bar, kt\u00f3ry rzekomo \u201elubi\u0142e\u015b/-a\u015b\u201d. Co dalej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A stranger insists they know you from a city you’ve never visited—and name a bar you “liked.” Next step?';
UPDATE questions
SET translations = '{"en": "What\u2019s the creepiest nice thing someone could do for you?", "da": "Hvad er den uhyggeligste venlige ting, nogen kunne g\u00f8re for dig?", "de": "Was ist das gruseligste nette Ding, das jemand f\u00fcr dich tun k\u00f6nnte?", "es": "\u00bfCu\u00e1l es la cosa amable m\u00e1s escalofriante que alguien podr\u00eda hacer por ti?", "pt": "Qual \u00e9 a coisa mais assustadoramente gentil que algu\u00e9m poderia fazer por ti?", "ro": "Care este cel mai \u00eenfior\u0103tor gest dr\u0103gu\u021b pe care cineva l-ar putea face pentru tine?", "fr": "Quelle est la chose gentille la plus effrayante que quelqu\u2019un pourrait faire pour toi ?", "it": "Qual \u00e8 la cosa pi\u00f9 inquietante ma gentile che qualcuno potrebbe fare per te?", "fi": "Mik\u00e4 olisi karmivin mutta silti \u201ckiltti\u201d teko, jonka joku voisi tehd\u00e4 puolestasi?", "nl": "Wat is het griezeligste aardige ding dat iemand voor je zou kunnen doen?", "no": "Hva er det skumleste, men egentlig snille, noen kunne gj\u00f8re for deg?", "sv": "Vad \u00e4r det l\u00e4skigaste sn\u00e4lla n\u00e5gon skulle kunna g\u00f6ra f\u00f6r dig?", "pl": "Jaka jest najbardziej creepowa, ale mi\u0142a rzecz, jak\u0105 kto\u015b m\u00f3g\u0142by dla ciebie zrobi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the creepiest nice thing someone could do for you?';
UPDATE questions
SET translations = '{"en": "You must spend the night in a museum. Which type would creep you out most (wax figures, medical curiosities, taxidermy, dolls, etc.)\u2014and why?", "da": "Du skal tilbringe natten p\u00e5 et museum. Hvilken type ville skr\u00e6mme dig mest (voksmennesker, medicinske kuriositeter, udstoppede dyr, dukker osv.) \u2013 og hvorfor?", "de": "Du musst die Nacht in einem Museum verbringen. Welche Art w\u00fcrde dich am meisten gruseln (Wachspuppen, medizinische Kuriosit\u00e4ten, Tierpr\u00e4parate, Puppen usw.) \u2013 und warum?", "es": "Debes pasar la noche en un museo. \u00bfQu\u00e9 tipo te asustar\u00eda m\u00e1s (figuras de cera, curiosidades m\u00e9dicas, taxidermia, mu\u00f1ecas, etc.) y por qu\u00e9?", "pt": "Tens de passar a noite num museu. Que tipo te assustaria mais (figuras de cera, curiosidades m\u00e9dicas, taxidermia, bonecas, etc.) \u2013 e porqu\u00ea?", "ro": "Trebuie s\u0103 petreci noaptea \u00eentr-un muzeu. Care tip te-ar speria cel mai tare (figuri de cear\u0103, curiozit\u0103\u021bi medicale, animale \u00eemp\u0103iate, p\u0103pu\u0219i etc.) \u2013 \u0219i de ce?", "fr": "Tu dois passer la nuit dans un mus\u00e9e. Quel type te ferait le plus peur (cire, curiosit\u00e9s m\u00e9dicales, animaux empaill\u00e9s, poup\u00e9es, etc.) \u2013 et pourquoi ?", "it": "Devi passare la notte in un museo. Quale tipo ti inquieterebbe di pi\u00f9 (figure di cera, curiosit\u00e0 mediche, tassidermia, bambole, ecc.) e perch\u00e9?", "fi": "Sinun on vietett\u00e4v\u00e4 y\u00f6 museossa. Millainen museo pelottaisi eniten (vahanuket, l\u00e4\u00e4ketieteelliset kuriositeetit, t\u00e4ytetyt el\u00e4imet, nuket jne.) \u2013 ja miksi?", "nl": "Je moet een nacht in een museum doorbrengen. Welk type zou je het meest laten griezelen (wasfiguren, medische curiosa, opgezette dieren, poppen, etc.) \u2013 en waarom?", "no": "Du m\u00e5 tilbringe natten p\u00e5 et museum. Hvilken type ville skremt deg mest (voksfigurer, medisinske kuriositeter, utstoppede dyr, dukker osv.) \u2013 og hvorfor?", "sv": "Du m\u00e5ste tillbringa natten p\u00e5 ett museum. Vilken typ skulle k\u00e4nnas mest obehaglig (vaxdockor, medicinska kuriositeter, uppstoppade djur, dockor osv.) \u2013 och varf\u00f6r?", "pl": "Musisz sp\u0119dzi\u0107 noc w muzeum. Jaki typ przerazi\u0142by ci\u0119 najbardziej (figury woskowe, ciekawostki medyczne, preparaty, lalki itp.) \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You must spend the night in a museum. Which type would creep you out most (wax figures, medical curiosities, taxidermy, dolls, etc.)—and why?';
UPDATE questions
SET translations = '{"en": "You find a duplicate of your house key in your drawer, newly cut. Do you change locks?", "da": "Du finder en kopi af din husn\u00f8gle i din skuffe, nyklippet. Skifter du l\u00e5s?", "de": "Du findest einen Duplikatschl\u00fcssel deines Hauses in deiner Schublade, frisch geschnitten. Wechselst du die Schl\u00f6sser?", "es": "Encuentras una copia de la llave de tu casa en tu caj\u00f3n, reci\u00e9n hecha. \u00bfCambias las cerraduras?", "pt": "Encontras uma c\u00f3pia da chave de tua casa na gaveta, rec\u00e9m cortada. Mudarias as fechaduras?", "ro": "G\u0103se\u0219ti o copie a cheii casei tale \u00een sertar, proasp\u0103t t\u0103iat\u0103. Schimbi yala?", "fr": "Tu trouves un double de ta cl\u00e9 de maison dans ton tiroir, fra\u00eechement taill\u00e9. Tu changes les serrures ?", "it": "Trovi un duplicato della chiave di casa nel cassetto, appena fatto. Cambi la serratura?", "fi": "L\u00f6yd\u00e4t laatikosta vastik\u00e4\u00e4n tehdyn vara-avaimen kotiisi. Vaihdatko lukot?", "nl": "Je vindt in je lade een nieuw bijgemaakte kopie van je huissleutel. Verwissel je de sloten?", "no": "Du finner en nykopiert husn\u00f8kkel i skuffen din. Skifter du l\u00e5ser?", "sv": "Du hittar en nygjord kopia av din husnyckel i en l\u00e5da. Byter du l\u00e5s?", "pl": "W szufladzie znajdujesz \u015bwie\u017co dorobiony duplikat klucza do domu. Wymieniasz zamki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You find a duplicate of your house key in your drawer, newly cut. Do you change locks?';
UPDATE questions
SET translations = '{"en": "Name a hilltop, tunnel, or alley that has \u2728bad vibes\u2728.", "da": "N\u00e6vn en bakketop, tunnel eller gyde med \u2728d\u00e5rlig energi\u2728.", "de": "Nenne einen H\u00fcgel, Tunnel oder eine Gasse mit \u2728schlechter Energie\u2728.", "es": "Nombra una colina, t\u00fanel o callej\u00f3n con \u2728malas vibras\u2728.", "pt": "Nomeia uma colina, t\u00fanel ou viela com \u2728m\u00e1s energias\u2728.", "ro": "Nume\u0219te un deal, tunel sau gang cu \u2728vibra\u021bii rele\u2728.", "fr": "Nomme une colline, un tunnel ou une ruelle avec \u2728de mauvaises ondes\u2728.", "it": "Nomina una cima, un tunnel o un vicolo che ha \u2728brutte vibrazioni\u2728.", "fi": "Nime\u00e4 m\u00e4enhuippu, tunneli tai kuja, josta tulee \u2728paha fiilis\u2728.", "nl": "Noem een heuveltop, tunnel of steeg die \u2728bad vibes\u2728 heeft.", "no": "Nevn en bakketopp, tunnel eller bakgate som har \u2728d\u00e5rlig vibber\u2728.", "sv": "N\u00e4mn en kulle, tunnel eller gr\u00e4nd som har \u2728d\u00e5lig vibbe\u2728.", "pl": "Podaj nazw\u0119 wzg\u00f3rza, tunelu lub zau\u0142ka, kt\u00f3ry ma \u2728z\u0142\u0105 energi\u0119\u2728."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Name a hilltop, tunnel, or alley that has ✨bad vibes✨.';
UPDATE questions
SET translations = '{"en": "Maps suggests a \u201cfaster route\u201d through a road that doesn\u2019t exist. Do you follow it?", "da": "Kort foresl\u00e5r en \u201churtigere rute\u201d gennem en vej, der ikke findes. F\u00f8lger du den?", "de": "Maps schl\u00e4gt eine \u201eschnellere Route\u201c \u00fcber eine Stra\u00dfe vor, die nicht existiert. Folgst du ihr?", "es": "El mapa sugiere una \u201cruta m\u00e1s r\u00e1pida\u201d por un camino que no existe. \u00bfLa sigues?", "pt": "O mapa sugere uma \u201crota mais r\u00e1pida\u201d por uma estrada que n\u00e3o existe. Segues?", "ro": "Harta \u00ee\u021bi sugereaz\u0103 o \u201erut\u0103 mai rapid\u0103\u201d printr-un drum care nu exist\u0103. O urmezi?", "fr": "Le GPS te propose un \u00ab itin\u00e9raire plus rapide \u00bb par une route qui n\u2019existe pas. Tu y vas ?", "it": "Maps ti suggerisce un \u201cpercorso pi\u00f9 veloce\u201d attraverso una strada che non esiste. Lo segui?", "fi": "Karttasovellus ehdottaa \u201cnopeampaa reitti\u00e4\u201d tiet\u00e4 pitkin, jota ei ole olemassa. L\u00e4hdetk\u00f6 mukaan?", "nl": "Maps stelt een \u201csnellere route\u201d voor via een weg die niet bestaat. Volg je die?", "no": "Kart-appen foresl\u00e5r en \u00abraskere rute\u00bb via en vei som ikke finnes. F\u00f8lger du den?", "sv": "Kartappen f\u00f6resl\u00e5r en \u201dsnabbare rutt\u201d via en v\u00e4g som inte finns. F\u00f6ljer du den?", "pl": "Mapy proponuj\u0105 \u201eszybsz\u0105 tras\u0119\u201d drog\u0105, kt\u00f3ra nie istnieje. Jedziesz ni\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Maps suggests a “faster route” through a road that doesn’t exist. Do you follow it?';
UPDATE questions
SET translations = '{"en": "Your shadow lags by two seconds. Now what?", "da": "Din skygge er to sekunder bagud. Hvad nu?", "de": "Dein Schatten hinkt zwei Sekunden hinterher. Was jetzt?", "es": "Tu sombra se retrasa dos segundos. \u00bfY ahora qu\u00e9?", "pt": "A tua sombra atrasa-se dois segundos. E agora?", "ro": "Umbra ta \u00eent\u00e2rzie dou\u0103 secunde. Ce faci?", "fr": "Ton ombre a deux secondes de retard. Et maintenant ?", "it": "La tua ombra \u00e8 in ritardo di due secondi. E adesso?", "fi": "Varjosi laahaa kaksi sekuntia per\u00e4ss\u00e4. Mit\u00e4 nyt?", "nl": "Je schaduw loopt twee seconden achter. Wat doe je?", "no": "Skyggen din henger to sekunder etter. Hva gj\u00f8r du?", "sv": "Din skugga ligger tv\u00e5 sekunder efter. Vad g\u00f6r du?", "pl": "Tw\u00f3j cie\u0144 sp\u00f3\u017ania si\u0119 o dwie sekundy. I co teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your shadow lags by two seconds. Now what?';
UPDATE questions
SET translations = '{"en": "Something keeps \u201cgoing wrong\u201d around one person. Do you believe in the evil eye or coincidence? Defend it.", "da": "Noget g\u00e5r altid galt omkring \u00e9n person. Tror du p\u00e5 det onde \u00f8je eller tilf\u00e6ldighed? Forklar.", "de": "Um eine Person geht immer etwas schief. Glaubst du an den b\u00f6sen Blick oder Zufall? Erkl\u00e4re.", "es": "Algo siempre sale mal alrededor de una persona. \u00bfCrees en el mal de ojo o en la coincidencia? Defi\u00e9ndelo.", "pt": "Algo d\u00e1 sempre errado \u00e0 volta de uma pessoa. Acreditas no mau-olhado ou em coincid\u00eancia? Defende.", "ro": "\u00cen jurul unei persoane totul merge prost. Crezi \u00een deochi sau \u00een coinciden\u021b\u0103? Ap\u0103r\u0103-\u021bi opinia.", "fr": "Quelque chose tourne toujours mal autour d\u2019une personne. Tu crois au mauvais \u0153il ou \u00e0 la co\u00efncidence ? D\u00e9fends ton point de vue.", "it": "Intorno a una certa persona va sempre tutto \u201cstorto\u201d. Credi nel malocchio o nelle coincidenze? Difendi la tua risposta.", "fi": "Jonkun ymp\u00e4rill\u00e4 jokin menee jatkuvasti \u201cpieleen\u201d. Uskotko pahaan silm\u00e4\u00e4n vai sattumaan? Perustele.", "nl": "Rond \u00e9\u00e9n persoon blijft er steeds iets \u201cmisgaan\u201d. Geloof je in het boze oog of in toeval? Verdedig je keuze.", "no": "Rundt \u00e9n person g\u00e5r ting stadig \u00abgalt\u00bb. Tror du p\u00e5 det onde \u00f8yet eller p\u00e5 tilfeldigheter? Begrunn.", "sv": "Runt en viss person verkar saker hela tiden g\u00e5 \u201dfel\u201d. Tror du p\u00e5 onda \u00f6gat eller p\u00e5 slumpen? F\u00f6rklara.", "pl": "Wok\u00f3\u0142 jednej osoby ci\u0105gle co\u015b \u201eidzie nie tak\u201d. Wierzysz w z\u0142e oko czy w przypadek? Uzasadnij."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Something keeps “going wrong” around one person. Do you believe in the evil eye or coincidence? Defend it.';
UPDATE questions
SET translations = '{"en": "Share a folk tale or saying from your culture that\u2019s a bit spooky.", "da": "Del et folkeeventyr eller ordsprog fra din kultur, der er lidt uhyggeligt.", "de": "Teile ein Volksm\u00e4rchen oder Sprichwort aus deiner Kultur, das etwas unheimlich ist.", "es": "Comparte un cuento popular o dicho de tu cultura que sea un poco espeluznante.", "pt": "Partilha um conto ou ditado da tua cultura que seja um pouco assustador.", "ro": "Spune o legend\u0103 sau un proverb din cultura ta care e pu\u021bin \u00eenfrico\u0219\u0103tor.", "fr": "Partage un conte ou un dicton de ta culture qui est un peu effrayant.", "it": "Condividi una fiaba popolare o un detto della tua cultura che sia un po\u2019 inquietante.", "fi": "Jaa kansansatu tai sanonta omasta kulttuuristasi, joka on hieman pelottava.", "nl": "Deel een volksverhaal of uitdrukking uit jouw cultuur die een beetje griezelig is.", "no": "Del et folkeeventyr eller et uttrykk fra kulturen din som er litt skummelt.", "sv": "Dela en folksaga eller ett uttryck fr\u00e5n din kultur som \u00e4r lite kusligt.", "pl": "Podziel si\u0119 ludow\u0105 opowie\u015bci\u0105 lub powiedzonkiem z twojej kultury, kt\u00f3re jest troch\u0119 straszne."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Share a folk tale or saying from your culture that’s a bit spooky.';
UPDATE questions
SET translations = '{"en": "What\u2019s your personal early-warning sign that a place isn\u2019t safe?", "da": "Hvad er dit personlige tidlige advarselstegn p\u00e5, at et sted ikke er sikkert?", "de": "Was ist dein pers\u00f6nliches Fr\u00fchwarnzeichen, dass ein Ort nicht sicher ist?", "es": "\u00bfCu\u00e1l es tu se\u00f1al de advertencia personal de que un lugar no es seguro?", "pt": "Qual \u00e9 o teu sinal pessoal de que um lugar n\u00e3o \u00e9 seguro?", "ro": "Care este semnul t\u0103u personal c\u0103 un loc nu e sigur?", "fr": "Quel est ton signe avant-coureur personnel qu\u2019un lieu n\u2019est pas s\u00fbr ?", "it": "Qual \u00e8 il tuo segnale personale d\u2019allarme che ti dice che un posto non \u00e8 sicuro?", "fi": "Mik\u00e4 on oma varoitusmerkkisi siit\u00e4, ett\u00e4 paikka ei ole turvallinen?", "nl": "Wat is voor jou het vroegste waarschuwingssignaal dat een plek niet veilig is?", "no": "Hva er ditt personlige tidlige varsel om at et sted ikke er trygt?", "sv": "Vad \u00e4r din personliga tidiga varningssignal p\u00e5 att en plats inte \u00e4r s\u00e4ker?", "pl": "Jaki jest tw\u00f3j osobisty wczesny sygna\u0142, \u017ce miejsce nie jest bezpieczne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s your personal early-warning sign that a place isn’t safe?';
UPDATE questions
SET translations = '{"en": "What do you think happens after we die\u2014one honest sentence.", "da": "Hvad tror du, der sker, n\u00e5r vi d\u00f8r \u2013 \u00e9n \u00e6rlig s\u00e6tning.", "de": "Was glaubst du, passiert, wenn wir sterben \u2013 ein ehrlicher Satz.", "es": "\u00bfQu\u00e9 crees que sucede cuando morimos? Una frase honesta.", "pt": "O que achas que acontece depois de morrermos \u2013 uma frase honesta.", "ro": "Ce crezi c\u0103 se \u00eent\u00e2mpl\u0103 dup\u0103 ce murim \u2013 o propozi\u021bie sincer\u0103.", "fr": "Que penses-tu qu\u2019il arrive apr\u00e8s la mort \u2013 une phrase honn\u00eate.", "it": "Cosa pensi che succeda dopo la morte? Una frase sincera.", "fi": "Mit\u00e4 luulet tapahtuvan kuoleman j\u00e4lkeen \u2013 yksi rehellinen lause.", "nl": "Wat denk je dat er gebeurt nadat we sterven \u2013 \u00e9\u00e9n eerlijke zin.", "no": "Hva tror du skjer etter at vi d\u00f8r \u2013 \u00e9n \u00e6rlig setning.", "sv": "Vad tror du h\u00e4nder efter att vi d\u00f6r \u2013 en \u00e4rlig mening.", "pl": "Jak my\u015blisz, co si\u0119 dzieje po \u015bmierci \u2013 jedno szczere zdanie."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What do you think happens after we die—one honest sentence.';
UPDATE questions
SET translations = '{"en": "You hear your name from an empty room. Investigate or nope?", "da": "Du h\u00f8rer dit navn fra et tomt rum. Unders\u00f8g eller g\u00e5 v\u00e6k?", "de": "Du h\u00f6rst deinen Namen aus einem leeren Raum. Untersuchen oder gehen?", "es": "Oyes tu nombre desde una habitaci\u00f3n vac\u00eda. \u00bfInvestigas o te vas?", "pt": "Ouves o teu nome vindo de uma sala vazia. Investigarias ou sa\u00edas?", "ro": "Auzi cum \u021bi se spune numele dintr-o camer\u0103 goal\u0103. Cercetezi sau pleci?", "fr": "Tu entends ton nom venir d\u2019une pi\u00e8ce vide. Tu enqu\u00eates ou tu pars ?", "it": "Senti il tuo nome provenire da una stanza vuota. Vai a vedere o lasci stare?", "fi": "Kuulet nimesi tyhj\u00e4st\u00e4 huoneesta. Tutkitko vai etk\u00f6 todellakaan?", "nl": "Je hoort je naam uit een lege kamer komen. Ga je kijken of echt niet?", "no": "Du h\u00f8rer navnet ditt bli ropt fra et tomt rom. G\u00e5r du for \u00e5 sjekke, eller nei takk?", "sv": "Du h\u00f6r ditt namn ropas fr\u00e5n ett tomt rum. G\u00e5r du och kollar eller nope?", "pl": "S\u0142yszysz swoje imi\u0119 z pustego pokoju. Idziesz sprawdzi\u0107 czy absolutnie nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You hear your name from an empty room. Investigate or nope?';
UPDATE questions
SET translations = '{"en": "Reincarnation is real: what skill or habit would you carry over?", "da": "Reinkarnation er virkelig: hvilken f\u00e6rdighed eller vane ville du tage med dig?", "de": "Reinkarnation ist real: Welche F\u00e4higkeit oder Gewohnheit w\u00fcrdest du mitnehmen?", "es": "La reencarnaci\u00f3n es real: \u00bfqu\u00e9 habilidad o h\u00e1bito llevar\u00edas contigo?", "pt": "A reencarna\u00e7\u00e3o \u00e9 real: que habilidade ou h\u00e1bito levarias contigo?", "ro": "Re\u00eencarnarea e real\u0103: ce abilitate sau obicei ai duce mai departe?", "fr": "La r\u00e9incarnation est r\u00e9elle : quelle comp\u00e9tence ou habitude emporterais-tu ?", "it": "La reincarnazione \u00e8 reale: quale abilit\u00e0 o abitudine vorresti portare con te?", "fi": "Reinkarnaatio on totta: mink\u00e4 taidon tai tavan ottaisit mukaasi seuraavaan el\u00e4m\u00e4\u00e4n?", "nl": "Re\u00efncarnatie is echt: welke vaardigheid of gewoonte zou je meenemen?", "no": "Reinkarnasjon er ekte: hvilken ferdighet eller vane ville du tatt med deg videre?", "sv": "Reinkarnation \u00e4r p\u00e5 riktigt: vilken f\u00e4rdighet eller vana skulle du ta med dig?", "pl": "Reinkarnacja jest prawdziwa: jak\u0105 umiej\u0119tno\u015b\u0107 lub jaki nawyk zabra\u0142(a)by\u015b ze sob\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Reincarnation is real: what skill or habit would you carry over?';
UPDATE questions
SET translations = '{"en": "What\u2019s the safest place on earth at midnight?", "da": "Hvad er det sikreste sted p\u00e5 jorden ved midnat?", "de": "Was ist der sicherste Ort auf der Erde um Mitternacht?", "es": "\u00bfCu\u00e1l es el lugar m\u00e1s seguro del mundo a medianoche?", "pt": "Qual \u00e9 o lugar mais seguro da Terra \u00e0 meia-noite?", "ro": "Care este cel mai sigur loc de pe P\u0103m\u00e2nt la miezul nop\u021bii?", "fr": "Quel est l\u2019endroit le plus s\u00fbr sur Terre \u00e0 minuit ?", "it": "Qual \u00e8 il posto pi\u00f9 sicuro sulla Terra a mezzanotte?", "fi": "Mik\u00e4 on maailman turvallisin paikka keskiy\u00f6ll\u00e4?", "nl": "Wat is de veiligste plek op aarde om middernacht?", "no": "Hva er det tryggeste stedet p\u00e5 jorden ved midnatt?", "sv": "Vilken \u00e4r den s\u00e4kraste platsen p\u00e5 jorden vid midnatt?", "pl": "Jakie miejsce na \u015bwiecie jest najbezpieczniejsze o p\u00f3\u0142nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the safest place on earth at midnight?';