UPDATE questions
SET translations = '{"en": "What\u2019s something people used to do that doesn\u2019t make sense today?", "da": "Hvad er noget, folk plejede at g\u00f8re, som ikke giver mening i dag?", "de": "Was haben die Leute fr\u00fcher gemacht, das heute keinen Sinn mehr ergibt?", "es": "\u00bfQu\u00e9 es algo que la gente sol\u00eda hacer que hoy no tiene sentido?", "pt": "O que \u00e9 algo que as pessoas costumavam fazer que hoje n\u00e3o faz sentido?", "ro": "Ce este ceva ce oamenii obi\u0219nuiau s\u0103 fac\u0103 \u0219i nu mai are sens azi?", "fr": "Quelle est une chose que les gens faisaient autrefois qui n\u2019a plus de sens aujourd\u2019hui ?", "it": "Qualcosa che le persone facevano in passato e che oggi non ha senso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen tekiv\u00e4t, mutta mik\u00e4 ei t\u00e4n\u00e4 p\u00e4iv\u00e4n\u00e4 en\u00e4\u00e4 tunnu j\u00e4rkev\u00e4lt\u00e4?", "nl": "Wat is iets dat mensen vroeger deden dat vandaag de dag geen zin meer heeft?", "no": "Hva er noe folk pleide \u00e5 gj\u00f8re som ikke gir mening i dag?", "sv": "Vad \u00e4r n\u00e5got som folk brukade g\u00f6ra som inte k\u00e4nns rimligt idag?", "pl": "Co\u015b, co ludzie kiedy\u015b robili, a dzisiaj nie ma sensu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to do that doesn’t make sense today?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing from the past you wish would come back?", "da": "Hvad er \u00e9n ting fra fortiden, du ville \u00f8nske kom tilbage?", "de": "Was ist eine Sache aus der Vergangenheit, die du dir zur\u00fcckw\u00fcnschst?", "es": "\u00bfQu\u00e9 cosa del pasado te gustar\u00eda que volviera?", "pt": "O que do passado gostarias que voltasse?", "ro": "Ce lucru din trecut ai vrea s\u0103 revin\u0103?", "fr": "Quelle chose du pass\u00e9 aimerais-tu revoir revenir ?", "it": "Qual \u00e8 una cosa del passato che vorresti tornasse?", "fi": "Mik\u00e4 on yksi asia menneisyydest\u00e4, jonka toivoisit palaavan?", "nl": "Wat is \u00e9\u00e9n ding uit het verleden dat je zou willen dat het terugkwam?", "no": "Hva er \u00e9n ting fra fortiden du skulle \u00f8nske kom tilbake?", "sv": "Vad \u00e4r en sak fr\u00e5n det f\u00f6rflutna som du \u00f6nskar skulle komma tillbaka?", "pl": "Co\u015b z przesz\u0142o\u015bci, co chcia\u0142by\u015b, aby wr\u00f3ci\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing from the past you wish would come back?';
UPDATE questions
SET translations = '{"en": "What\u2019s something from today you think is much better than before?", "da": "Hvad er noget fra i dag, som du synes er meget bedre end f\u00f8r?", "de": "Was ist etwas von heute, das du viel besser findest als fr\u00fcher?", "es": "\u00bfQu\u00e9 cosa de hoy crees que es mucho mejor que antes?", "pt": "O que de hoje achas muito melhor do que antes?", "ro": "Ce lucru din prezent crezi c\u0103 este mult mai bun dec\u00e2t \u00eenainte?", "fr": "Quelle chose d\u2019aujourd\u2019hui trouves-tu bien meilleure qu\u2019avant ?", "it": "Qualcosa di oggi che pensi sia molto meglio di prima?", "fi": "Mik\u00e4 on jotain t\u00e4n\u00e4\u00e4n, mik\u00e4 mielest\u00e4si on paljon parempaa kuin ennen?", "nl": "Wat is iets van vandaag dat je denkt dat het veel beter is dan vroeger?", "no": "Hva er noe fra i dag som du mener er mye bedre enn f\u00f8r?", "sv": "Vad \u00e4r n\u00e5got fr\u00e5n idag som du tycker \u00e4r mycket b\u00e4ttre \u00e4n tidigare?", "pl": "Co\u015b, co dzisiaj uwa\u017casz za znacznie lepsze ni\u017c wcze\u015bniej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something from today you think is much better than before?';
UPDATE questions
SET translations = '{"en": "What\u2019s a household chore that used to take forever?", "da": "Hvilken husopgave tog engang evigheder at lave?", "de": "Welche Hausarbeit hat fr\u00fcher ewig gedauert?", "es": "\u00bfQu\u00e9 tarea dom\u00e9stica sol\u00eda tardar una eternidad?", "pt": "Que tarefa dom\u00e9stica costumava demorar imenso tempo?", "ro": "Ce treab\u0103 casnic\u0103 obi\u0219nuia s\u0103 dureze o ve\u0219nicie?", "fr": "Quelle corv\u00e9e domestique prenait autrefois une \u00e9ternit\u00e9 ?", "it": "Quale faccenda domestica richiedeva un sacco di tempo?", "fi": "Mik\u00e4 kotity\u00f6 kesti ennen ikuisuuden?", "nl": "Wat is een huishoudelijke taak die vroeger eeuwig leek te duren?", "no": "Hva er en husarbeidoppgave som pleide \u00e5 ta en evighet?", "sv": "Vilket hush\u00e5llsarbete tog en evighet att g\u00f6ra tidigare?", "pl": "Jakie domowe obowi\u0105zki kiedy\u015b zajmowa\u0142y wieczno\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a household chore that used to take forever?';
UPDATE questions
SET translations = '{"en": "What\u2019s something kids today will never understand about your childhood?", "da": "Hvad er noget, b\u00f8rn i dag aldrig vil forst\u00e5 fra din barndom?", "de": "Was werden Kinder heute nie \u00fcber deine Kindheit verstehen?", "es": "\u00bfQu\u00e9 es algo de tu infancia que los ni\u00f1os de hoy nunca entender\u00e1n?", "pt": "O que \u00e9 algo da tua inf\u00e2ncia que as crian\u00e7as de hoje nunca compreender\u00e3o?", "ro": "Ce este ceva din copil\u0103ria ta pe care copiii de azi nu-l vor \u00een\u021belege niciodat\u0103?", "fr": "Quelle est une chose de ton enfance que les enfants d\u2019aujourd\u2019hui ne comprendront jamais ?", "it": "Qualcosa che i bambini di oggi non capiranno mai della tua infanzia?", "fi": "Mik\u00e4 on jotain, mit\u00e4 lapset t\u00e4n\u00e4 p\u00e4iv\u00e4n\u00e4 eiv\u00e4t koskaan ymm\u00e4rr\u00e4 lapsuudestasi?", "nl": "Wat is iets dat kinderen van vandaag de dag nooit zullen begrijpen over jouw kindertijd?", "no": "Hva er noe barn i dag aldri vil forst\u00e5 om barndommen din?", "sv": "Vad \u00e4r n\u00e5got som barn idag aldrig kommer att f\u00f6rst\u00e5 om din barndom?", "pl": "Co\u015b, czego dzieci dzisiaj nigdy nie zrozumiej\u0105 o twoim dzieci\u0144stwie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something kids today will never understand about your childhood?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people had to wait a long time for, that we barely have patience for today?", "da": "Hvad er noget, folk plejede at vente l\u00e6nge p\u00e5, som vi n\u00e6sten ikke har t\u00e5lmodighed til i dag?", "de": "Worauf mussten die Menschen fr\u00fcher lange warten, wof\u00fcr wir heute kaum Geduld haben?", "es": "\u00bfQu\u00e9 era algo por lo que la gente ten\u00eda que esperar mucho tiempo, pero hoy apenas tenemos paciencia?", "pt": "O que as pessoas antigamente tinham de esperar muito tempo e hoje quase n\u00e3o temos paci\u00eancia?", "ro": "Pentru ce trebuiau oamenii s\u0103 a\u0219tepte mult timp \u00eenainte, dar azi nu mai avem r\u0103bdare?", "fr": "Pour quoi les gens devaient-ils attendre longtemps autrefois et pour lequel nous n\u2019avons presque plus de patience aujourd\u2019hui ?", "it": "Qualcosa per cui le persone hanno dovuto aspettare a lungo, per cui noi oggi abbiamo a malapena pazienza?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset joutuivat odottamaan pitk\u00e4\u00e4n, mutta mit\u00e4 meill\u00e4 on nyky\u00e4\u00e4n tuskin k\u00e4rsiv\u00e4llisyytt\u00e4 odottaa?", "nl": "Wat is iets waar mensen vroeger lang op moesten wachten, waar we vandaag de dag nauwelijks geduld voor hebben?", "no": "Hva er noe folk m\u00e5tte vente lenge p\u00e5, som vi knapt har t\u00e5lmodighet til i dag?", "sv": "Vad \u00e4r n\u00e5got som folk fick v\u00e4nta l\u00e4nge p\u00e5, som vi knappt har t\u00e5lamod f\u00f6r idag?", "pl": "Co\u015b, na co ludzie musieli czeka\u0107 d\u0142ugo, a na co my ledwo mamy cierpliwo\u015b\u0107 dzisiaj?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people had to wait a long time for, that we barely have patience for today?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that\u2019s changed for the better in your lifetime?", "da": "Hvad er noget, der er blevet bedre i din levetid?", "de": "Was hat sich in deinem Leben zum Besseren ver\u00e4ndert?", "es": "\u00bfQu\u00e9 cosa ha cambiado para mejor en tu vida?", "pt": "O que mudou para melhor na tua vida?", "ro": "Ce s-a schimbat \u00een bine \u00een timpul vie\u021bii tale?", "fr": "Qu\u2019est-ce qui s\u2019est am\u00e9lior\u00e9 au cours de ta vie ?", "it": "Qualcosa che \u00e8 cambiato in meglio nella tua vita?", "fi": "Mik\u00e4 on jotain, mik\u00e4 on muuttunut paremmaksi el\u00e4m\u00e4si aikana?", "nl": "Wat is er in jouw leven veranderd ten goede?", "no": "Hva er noe som har endret seg til det bedre i l\u00f8pet av livet ditt?", "sv": "Vad \u00e4r n\u00e5got som har f\u00f6r\u00e4ndrats till det b\u00e4ttre under din livstid?", "pl": "Co\u015b, co zmieni\u0142o si\u0119 na lepsze w twoim \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that’s changed for the better in your lifetime?';
UPDATE questions
SET translations = '{"en": "What was your favorite way to spend a Saturday before phones or tablets?", "da": "Hvad var din yndlingsm\u00e5de at bruge en l\u00f8rdag p\u00e5 f\u00f8r telefoner og tablets?", "de": "Wie hast du samstags am liebsten Zeit verbracht, bevor es Handys und Tablets gab?", "es": "\u00bfC\u00f3mo te gustaba pasar los s\u00e1bados antes de los tel\u00e9fonos y tabletas?", "pt": "Como gostavas de passar os s\u00e1bados antes dos telem\u00f3veis e tablets?", "ro": "Cum \u00ee\u021bi pl\u0103cea s\u0103-\u021bi petreci s\u00e2mbetele \u00eenainte de telefoane \u0219i tablete?", "fr": "Quelle \u00e9tait ta fa\u00e7on pr\u00e9f\u00e9r\u00e9e de passer le samedi avant les t\u00e9l\u00e9phones et les tablettes ?", "it": "Qual era il tuo modo preferito di trascorrere un sabato prima dei telefoni o dei tablet?", "fi": "Mik\u00e4 oli lempitapasi viett\u00e4\u00e4 lauantaita ennen puhelimia tai tabletteja?", "nl": "Wat was jouw favoriete manier om een zaterdag door te brengen voordat er telefoons of tablets waren?", "no": "Hva var din favorittm\u00e5te \u00e5 tilbringe en l\u00f8rdag p\u00e5 f\u00f8r telefoner eller nettbrett?", "sv": "Vad var ditt favorit s\u00e4tt att spendera en l\u00f6rdag p\u00e5 innan telefoner eller surfplattor?", "pl": "Jaki by\u0142 tw\u00f3j ulubiony spos\u00f3b sp\u0119dzania soboty przed pojawieniem si\u0119 telefon\u00f3w kom\u00f3rkowych lub tablet\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your favorite way to spend a Saturday before phones or tablets?';
UPDATE questions
SET translations = '{"en": "Tell me about your first date or your first big crush.", "da": "Fort\u00e6l mig om din f\u00f8rste date eller din f\u00f8rste store forelskelse.", "de": "Erz\u00e4hl mir von deinem ersten Date oder deiner ersten gro\u00dfen Liebe.", "es": "Cu\u00e9ntame sobre tu primera cita o tu primer gran amor.", "pt": "Conta-me sobre o teu primeiro encontro ou a tua primeira grande paix\u00e3o.", "ro": "Poveste\u0219te-mi despre prima ta \u00eent\u00e2lnire sau prima ta mare iubire.", "fr": "Raconte-moi ton premier rendez-vous ou ton premier grand amour.", "it": "Parlami del tuo primo appuntamento o della tua prima grande cotta.", "fi": "Kerro minulle ensimm\u00e4isest\u00e4 treffeist\u00e4si tai ensimm\u00e4isest\u00e4 suuresta ihastuksestasi.", "nl": "Vertel me over je eerste date of je eerste grote verliefdheid.", "no": "Fortell meg om din f\u00f8rste date eller din f\u00f8rste store forelskelse.", "sv": "Ber\u00e4tta om din f\u00f6rsta dejt eller din f\u00f6rsta stora f\u00f6r\u00e4lskelse.", "pl": "Opowiedz mi o swojej pierwszej randce lub swojej pierwszej wielkiej mi\u0142o\u015bci."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about your first date or your first big crush.';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think was harder in \u201cthe good old days\u201d?", "da": "Hvad tror du var sv\u00e6rere i \u201cde gode gamle dage\u201d?", "de": "Was glaubst du, war schwieriger in den \u201eguten alten Zeiten\u201c?", "es": "\u00bfQu\u00e9 crees que era m\u00e1s dif\u00edcil en \u201clos viejos tiempos\u201d?", "pt": "O que achas que era mais dif\u00edcil nos \u201cbons velhos tempos\u201d?", "ro": "Ce crezi c\u0103 era mai greu \u00een \u201evremurile bune de alt\u0103dat\u0103\u201d?", "fr": "Qu\u2019est-ce qui \u00e9tait plus difficile selon toi dans \u201cle bon vieux temps\u201d ?", "it": "Qualcosa che pensi fosse pi\u00f9 difficile nei \"bei vecchi tempi\"?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ajattelet olleen vaikeampaa \"hyvin\u00e4 vanhoina aikoina\"?", "nl": "Wat is iets waarvan je denkt dat het moeilijker was in \"de goede oude tijd\"?", "no": "Hva er noe du mener var vanskeligere i \"de gode gamle dager\"?", "sv": "Vad \u00e4r n\u00e5got du tycker var sv\u00e5rare \"p\u00e5 den gamla goda tiden\"?", "pl": "Co my\u015blisz, \u017ce by\u0142o trudniejsze w \"dawnych dobrych czasach\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you think was harder in “the good old days”?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you miss about how people used to talk to each other?", "da": "Hvad savner du ved, hvordan folk plejede at tale med hinanden?", "de": "Was vermisst du daran, wie Menschen fr\u00fcher miteinander gesprochen haben?", "es": "\u00bfQu\u00e9 extra\u00f1as de c\u00f3mo la gente sol\u00eda hablar entre s\u00ed?", "pt": "O que sentes falta na forma como as pessoas costumavam conversar?", "ro": "Ce \u00ee\u021bi lipse\u0219te din felul \u00een care oamenii obi\u0219nuiau s\u0103 vorbeasc\u0103 unii cu al\u021bii?", "fr": "Qu\u2019est-ce qui te manque dans la fa\u00e7on dont les gens se parlaient autrefois ?", "it": "Qual \u00e8 una cosa che ti manca di come le persone parlavano tra di loro?", "fi": "Mik\u00e4 on jotain, mit\u00e4 kaipaat siit\u00e4, miten ihmiset puhuivat toisilleen ennen?", "nl": "Wat is iets dat je mist aan hoe mensen vroeger met elkaar praatten?", "no": "Hva er noe du savner med hvordan folk pleide \u00e5 snakke med hverandre?", "sv": "Vad \u00e4r det som du saknar med hur folk brukade prata med varandra?", "pl": "Co\u015b, co t\u0119sknisz za tym, jak ludzie kiedy\u015b rozmawiali ze sob\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you miss about how people used to talk to each other?';
UPDATE questions
SET translations = '{"en": "What was your favorite snack or drink growing up \u2014 does it still exist?", "da": "Hvad var din yndlingssnack eller drik, da du voksede op \u2014 findes den stadig?", "de": "Was war dein Lieblingssnack oder -getr\u00e4nk als Kind \u2013 gibt es das noch?", "es": "\u00bfCu\u00e1l era tu merienda o bebida favorita cuando eras ni\u00f1o \u2014 todav\u00eda existe?", "pt": "Qual era o teu lanche ou bebida favorita em crian\u00e7a \u2014 ainda existe?", "ro": "Care era gustarea sau b\u0103utura ta preferat\u0103 c\u00e2nd erai mic \u2014 mai exist\u0103?", "fr": "Quelle \u00e9tait ta collation ou boisson pr\u00e9f\u00e9r\u00e9e en grandissant \u2014 existe-t-elle encore ?", "it": "Qual era il tuo snack o drink preferito da bambino \u2014 esiste ancora?", "fi": "Mik\u00e4 oli lempiv\u00e4lipalas tai juomasi lapsena \u2014 onko se yh\u00e4 olemassa?", "nl": "Wat was je favoriete snack of drankje toen je opgroeide \u2014 bestaat het nog steeds?", "no": "Hva var din favorittsnack eller drikke da du vokste opp \u2014 finnes det fortsatt?", "sv": "Vad var ditt favorit-snack eller dryck n\u00e4r du v\u00e4xte upp \u2014 finns det fortfarande?", "pl": "Jakie by\u0142o twoje ulubione przek\u0105ski lub nap\u00f3j w dzieci\u0144stwie \u2014 czy nadal istnieje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your favorite snack or drink growing up — does it still exist?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that\u2019s gotten too complicated today?", "da": "Hvad er noget, der er blevet alt for kompliceret i dag?", "de": "Was ist heute viel zu kompliziert geworden?", "es": "\u00bfQu\u00e9 cosa se ha vuelto demasiado complicada hoy en d\u00eda?", "pt": "O que ficou demasiado complicado hoje em dia?", "ro": "Ce lucru a devenit prea complicat azi?", "fr": "Qu\u2019est-ce qui est devenu trop compliqu\u00e9 de nos jours ?", "it": "Qual \u00e8 qualcosa che \u00e8 diventato troppo complicato oggi?", "fi": "Mik\u00e4 on jotain, mik\u00e4 on t\u00e4n\u00e4\u00e4n mennyt liian monimutkaiseksi?", "nl": "Wat is iets dat vandaag te ingewikkeld is geworden?", "no": "Hva er noe som har blitt for komplisert i dag?", "sv": "Vad \u00e4r n\u00e5got som har blivit f\u00f6r komplicerat idag?", "pl": "Co\u015b, co sta\u0142o si\u0119 dzisiaj zbyt skomplikowane?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that’s gotten too complicated today?';
UPDATE questions
SET translations = '{"en": "What\u2019s something new that makes life easier now?", "da": "Hvad er noget nyt, der g\u00f8r livet lettere nu?", "de": "Was ist etwas Neues, das das Leben heute einfacher macht?", "es": "\u00bfQu\u00e9 cosa nueva hace la vida m\u00e1s f\u00e1cil ahora?", "pt": "O que h\u00e1 de novo que torna a vida mais f\u00e1cil agora?", "ro": "Ce lucru nou face via\u021ba mai u\u0219oar\u0103 acum?", "fr": "Quelle nouveaut\u00e9 rend la vie plus facile aujourd\u2019hui ?", "it": "Qualcosa di nuovo che rende la vita pi\u00f9 facile adesso?", "fi": "Mik\u00e4 on jotain uutta, mik\u00e4 tekee el\u00e4m\u00e4st\u00e4 helpompaa nyt?", "nl": "Wat is iets nieuws dat het leven nu gemakkelijker maakt?", "no": "Hva er noe nytt som gj\u00f8r livet enklere n\u00e5?", "sv": "Vad \u00e4r n\u00e5got nytt som g\u00f6r livet enklare nu?", "pl": "Co\u015b nowego, co u\u0142atwia \u017cycie teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something new that makes life easier now?';
UPDATE questions
SET translations = '{"en": "What was your first big purchase \u2014 and what did it cost?", "da": "Hvad var dit f\u00f8rste store k\u00f8b \u2014 og hvad kostede det?", "de": "Was war dein erster gro\u00dfer Kauf \u2013 und was hat er gekostet?", "es": "\u00bfCu\u00e1l fue tu primera gran compra \u2014 y cu\u00e1nto cost\u00f3?", "pt": "Qual foi a tua primeira grande compra \u2014 e quanto custou?", "ro": "Care a fost prima ta achizi\u021bie mare \u2014 \u0219i c\u00e2t a costat?", "fr": "Quel a \u00e9t\u00e9 ton premier grand achat \u2014 et combien cela a co\u00fbt\u00e9 ?", "it": "Qual \u00e8 stato il tuo primo grande acquisto \u2014 e quanto \u00e8 costato?", "fi": "Mik\u00e4 oli ensimm\u00e4inen iso ostoksesi \u2014 ja mit\u00e4 se maksoi?", "nl": "Wat was je eerste grote aankoop \u2014 en wat kostte het?", "no": "Hva var ditt f\u00f8rste store kj\u00f8p \u2014 og hva kostet det?", "sv": "Vad var ditt f\u00f6rsta stora k\u00f6p \u2014 och vad kostade det?", "pl": "Jakie by\u0142o twoje pierwsze du\u017ce zakupy \u2014 i ile to kosztowa\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your first big purchase — and what did it cost?';
UPDATE questions
SET translations = '{"en": "Tell me about a time when you had to be really brave.", "da": "Fort\u00e6l mig om en tid, hvor du m\u00e5tte v\u00e6re virkelig modig.", "de": "Erz\u00e4hl mir von einer Zeit, in der du sehr mutig sein musstest.", "es": "Cu\u00e9ntame de una vez que tuviste que ser muy valiente.", "pt": "Conta-me sobre uma vez em que tiveste de ser muito corajoso.", "ro": "Poveste\u0219te-mi despre o dat\u0103 c\u00e2nd a trebuit s\u0103 fii foarte curajos.", "fr": "Raconte-moi un moment o\u00f9 tu as d\u00fb \u00eatre vraiment courageux.", "it": "Raccontami di un momento in cui hai dovuto essere davvero coraggioso.", "fi": "Kerro minulle ajasta, jolloin sinun piti olla todella rohkea.", "nl": "Vertel me over een moment waarop je echt moedig moest zijn.", "no": "Fortell meg om en gang da du m\u00e5tte v\u00e6re virkelig modig.", "sv": "Ber\u00e4tta om en g\u00e5ng n\u00e4r du var tvungen att vara riktigt modig.", "pl": "Opowiedz mi o czasie, kiedy musia\u0142e\u015b by\u0107 naprawd\u0119 odwa\u017cny."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about a time when you had to be really brave.';
UPDATE questions
SET translations = '{"en": "What kind of toys or games were popular when you were little?", "da": "Hvilke leget\u00f8j eller spil var popul\u00e6re, da du var lille?", "de": "Welche Spielzeuge oder Spiele waren beliebt, als du klein warst?", "es": "\u00bfQu\u00e9 juguetes o juegos eran populares cuando eras peque\u00f1o?", "pt": "Que brinquedos ou jogos eram populares quando eras pequeno?", "ro": "Ce juc\u0103rii sau jocuri erau populare c\u00e2nd erai mic?", "fr": "Quels jouets ou jeux \u00e9taient populaires quand tu \u00e9tais petit ?", "it": "Quali tipi di giocattoli o giochi erano popolari quando eri piccolo?", "fi": "Mit\u00e4 leluja tai pelej\u00e4 oli suosittuja, kun olit pieni?", "nl": "Welke soorten speelgoed of spellen waren populair toen je klein was?", "no": "Hvilke typer leker eller spill var popul\u00e6re da du var liten?", "sv": "Vilka typer av leksaker eller spel var popul\u00e4ra n\u00e4r du var liten?", "pl": "Jakie zabawki lub gry by\u0142y popularne, gdy by\u0142e\u015b ma\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What kind of toys or games were popular when you were little?';
UPDATE questions
SET translations = '{"en": "What did \u201chaving fun\u201d look like before video games or TV?", "da": "Hvordan s\u00e5 \u201cat have det sjovt\u201d ud, f\u00f8r videospil eller tv fandtes?", "de": "Wie sah \u201eSpa\u00df haben\u201c aus, bevor es Videospiele oder Fernsehen gab?", "es": "\u00bfC\u00f3mo era \u201cdivertirse\u201d antes de los videojuegos o la televisi\u00f3n?", "pt": "Como era \u201cdivertir-se\u201d antes dos videojogos ou da televis\u00e3o?", "ro": "Cum ar\u0103ta \u201edistrac\u021bia\u201d \u00eenainte de jocurile video sau televiziune?", "fr": "\u00c0 quoi ressemblait \u201cs\u2019amuser\u201d avant les jeux vid\u00e9o ou la t\u00e9l\u00e9vision ?", "it": "Com''era \"divertirsi\" prima dei videogiochi o della TV?", "fi": "Milt\u00e4 \"hauskanpito\" n\u00e4ytti ennen videopelej\u00e4 tai televisiota?", "nl": "Hoe zag \"plezier hebben\" eruit voordat er videospellen of tv waren?", "no": "Hvordan s\u00e5 \"\u00e5 ha det moro\" ut f\u00f8r videospill eller TV?", "sv": "Hur s\u00e5g \"att ha roligt\" ut innan videospel eller TV?", "pl": "Jak wygl\u0105da\u0142a zabawa przed pojawieniem si\u0119 gier wideo lub telewizji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What did “having fun” look like before video games or TV?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you remember breaking and having to fix by hand?", "da": "Hvad er noget, du husker at have \u00f8delagt og m\u00e5tte reparere i h\u00e5nden?", "de": "Was erinnerst du dich, kaputt gemacht und von Hand repariert zu haben?", "es": "\u00bfQu\u00e9 recuerdas haber roto y tenido que arreglar a mano?", "pt": "O que te lembras de ter partido e consertado \u00e0 m\u00e3o?", "ro": "Ce \u00ee\u021bi aminte\u0219ti c\u0103 ai stricat \u0219i a trebuit s\u0103 repari cu m\u00e2na?", "fr": "De quoi te souviens-tu avoir cass\u00e9 et d\u00fb r\u00e9parer \u00e0 la main ?", "it": "Qualcosa che ricordi di aver rotto e di aver dovuto riparare a mano?", "fi": "Mik\u00e4 on jotain, jonka muistat rikkoneesi ja joutuneesi korjaamaan k\u00e4sin?", "nl": "Wat is iets dat je je herinnert dat je hebt gebroken en met de hand moest repareren?", "no": "Hva er noe du husker at du brakk og m\u00e5tte fikse for h\u00e5nd?", "sv": "Vad \u00e4r n\u00e5got du minns att du br\u00f6t och var tvungen att laga f\u00f6r hand?", "pl": "Co\u015b, co pami\u0119tasz, \u017ce zepsu\u0142e\u015b i musia\u0142e\u015b naprawi\u0107 r\u0119cznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you remember breaking and having to fix by hand?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you learned to live without back then that everyone has now?", "da": "Hvad er noget, du l\u00e6rte at leve uden dengang, som alle har nu?", "de": "Was hast du gelernt, fr\u00fcher ohne zu leben, was heute jeder hat?", "es": "\u00bfQu\u00e9 aprendiste a vivir sin tener antes, que ahora todos tienen?", "pt": "O que aprendeste a viver sem, que agora todos t\u00eam?", "ro": "Ce ai \u00eenv\u0103\u021bat s\u0103 tr\u0103ie\u0219ti f\u0103r\u0103 atunci, dar toat\u0103 lumea are acum?", "fr": "De quoi as-tu appris \u00e0 te passer autrefois que tout le monde a maintenant ?", "it": "Qualcosa che hai imparato a vivere senza all''epoca che tutti hanno adesso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 opit el\u00e4m\u00e4\u00e4n ilman silloin, mutta mit\u00e4 kaikilla on nyt?", "nl": "Wat is iets waar je toen leerde zonder te leven dat iedereen nu heeft?", "no": "Hva er noe du l\u00e6rte \u00e5 leve uten den gang som alle har n\u00e5?", "sv": "Vad \u00e4r n\u00e5got du l\u00e4rde dig att leva utan d\u00e5 som alla har nu?", "pl": "Co\u015b, czego nauczy\u0142e\u015b si\u0119 \u017cy\u0107 bez wtedy, co teraz ma ka\u017cdy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you learned to live without back then that everyone has now?';
UPDATE questions
SET translations = '{"en": "What was shopping like before online stores?", "da": "Hvordan var det at handle, f\u00f8r der fandtes onlinebutikker?", "de": "Wie war Einkaufen, bevor es Online-Shops gab?", "es": "\u00bfC\u00f3mo era ir de compras antes de las tiendas en l\u00ednea?", "pt": "Como era fazer compras antes das lojas online?", "ro": "Cum era cump\u0103r\u0103turile \u00eenainte de magazinele online?", "fr": "Comment faisait-on du shopping avant les magasins en ligne ?", "it": "Com''era fare shopping prima dei negozi online?", "fi": "Millainen ostaminen oli ennen verkkokauppoja?", "nl": "Hoe was winkelen voordat er online winkels waren?", "no": "Hvordan var shopping f\u00f8r nettbutikker?", "sv": "Hur var shopping innan n\u00e4tbutiker?", "pl": "Jak wygl\u0105da\u0142y zakupy przed pojawieniem si\u0119 sklep\u00f3w internetowych?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was shopping like before online stores?';
UPDATE questions
SET translations = '{"en": "Tell me about how you met the love of your life.", "da": "Fort\u00e6l mig, hvordan du m\u00f8dte k\u00e6rligheden i dit liv.", "de": "Erz\u00e4hl mir, wie du die Liebe deines Lebens getroffen hast.", "es": "Cu\u00e9ntame c\u00f3mo conociste al amor de tu vida.", "pt": "Conta-me como conheceste o amor da tua vida.", "ro": "Spune-mi cum \u021bi-ai \u00eent\u00e2lnit dragostea vie\u021bii tale.", "fr": "Raconte-moi comment tu as rencontr\u00e9 l\u2019amour de ta vie.", "it": "Raccontami di come hai incontrato l''amore della tua vita.", "fi": "Kerro minulle, miten tapasit el\u00e4m\u00e4si rakkauden.", "nl": "Vertel me hoe je de liefde van je leven hebt ontmoet.", "no": "Fortell meg om hvordan du m\u00f8tte kj\u00e6rligheten i livet ditt.", "sv": "Ber\u00e4tta om hur du tr\u00e4ffade k\u00e4rleken i ditt liv.", "pl": "Opowiedz mi, jak pozna\u0142e\u015b mi\u0142o\u015b\u0107 swojego \u017cycia."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about how you met the love of your life.';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think people appreciate less now than before?", "da": "Hvad er \u00e9n ting, du tror, folk v\u00e6rds\u00e6tter mindre nu end f\u00f8r?", "de": "Was ist eine Sache, die die Menschen heute weniger sch\u00e4tzen als fr\u00fcher?", "es": "\u00bfQu\u00e9 cosa crees que la gente aprecia menos ahora que antes?", "pt": "O que achas que as pessoas valorizam menos agora do que antes?", "ro": "Ce lucru crezi c\u0103 oamenii apreciaz\u0103 mai pu\u021bin acum dec\u00e2t \u00eenainte?", "fr": "Quelle chose penses-tu que les gens appr\u00e9cient moins aujourd\u2019hui qu\u2019avant ?", "it": "Qual \u00e8 una cosa che pensi le persone apprezzino meno adesso rispetto a prima?", "fi": "Mik\u00e4 on yksi asia, jota luulet ihmisten arvostavan v\u00e4hemm\u00e4n nyt kuin ennen?", "nl": "Wat is \u00e9\u00e9n ding dat je denkt dat mensen nu minder waarderen dan vroeger?", "no": "Hva er \u00e9n ting du tror folk setter mindre pris p\u00e5 n\u00e5 enn f\u00f8r?", "sv": "Vad \u00e4r en sak som du tror att folk uppskattar mindre nu \u00e4n tidigare?", "pl": "Co\u015b, co my\u015blisz, \u017ce ludzie mniej doceniaj\u0105 teraz ni\u017c wcze\u015bniej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you think people appreciate less now than before?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to make at home instead of buying?", "da": "Hvad er noget, folk plejede at lave derhjemme i stedet for at k\u00f8be?", "de": "Was haben die Leute fr\u00fcher zu Hause gemacht, anstatt es zu kaufen?", "es": "\u00bfQu\u00e9 sol\u00edan hacer las personas en casa en lugar de comprarlo?", "pt": "O que as pessoas costumavam fazer em casa em vez de comprar?", "ro": "Ce obi\u0219nuiau oamenii s\u0103 fac\u0103 acas\u0103 \u00een loc s\u0103 cumpere?", "fr": "Que faisaient les gens autrefois chez eux au lieu de l\u2019acheter ?", "it": "Qualcosa che le persone facevano in casa invece di comprare?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen tekiv\u00e4t kotona sen sijaan, ett\u00e4 ostaisivat sen?", "nl": "Wat is iets dat mensen vroeger thuis maakten in plaats van het te kopen?", "no": "Hva er noe folk pleide \u00e5 lage hjemme i stedet for \u00e5 kj\u00f8pe?", "sv": "Vad \u00e4r n\u00e5got som folk brukade g\u00f6ra hemma ist\u00e4llet f\u00f6r att k\u00f6pa?", "pl": "Co\u015b, co ludzie kiedy\u015b robili w domu zamiast kupowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to make at home instead of buying?';
UPDATE questions
SET translations = '{"en": "What was your first memory of seeing a computer, phone, or car?", "da": "Hvad er din f\u00f8rste erindring om at se en computer, telefon eller bil?", "de": "Was ist deine erste Erinnerung daran, einen Computer, ein Telefon oder ein Auto gesehen zu haben?", "es": "\u00bfCu\u00e1l es tu primer recuerdo de ver una computadora, un tel\u00e9fono o un coche?", "pt": "Qual \u00e9 a tua primeira lembran\u00e7a de ver um computador, um telefone ou um carro?", "ro": "Care este prima ta amintire de c\u00e2nd ai v\u0103zut un computer, un telefon sau o ma\u0219in\u0103?", "fr": "Quel est ton premier souvenir d\u2019avoir vu un ordinateur, un t\u00e9l\u00e9phone ou une voiture ?", "it": "Qual \u00e8 stato il tuo primo ricordo di aver visto un computer, un telefono o un''auto?", "fi": "Mik\u00e4 oli ensimm\u00e4inen muistosi tietokoneen, puhelimen tai auton n\u00e4kemisest\u00e4?", "nl": "Wat is je eerste herinnering aan het zien van een computer, telefoon of auto?", "no": "Hva var ditt f\u00f8rste minne om \u00e5 se en datamaskin, telefon eller bil?", "sv": "Vad \u00e4r ditt f\u00f6rsta minne av att se en dator, telefon eller bil?", "pl": "Jakie jest twoje pierwsze wspomnienie zwi\u0105zane z widzeniem komputera, telefonu lub samochodu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your first memory of seeing a computer, phone, or car?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that cost very little back then but is expensive now?", "da": "Hvad er noget, der kostede meget lidt dengang, men som er dyrt nu?", "de": "Was hat fr\u00fcher sehr wenig gekostet, ist aber heute teuer?", "es": "\u00bfQu\u00e9 cosa costaba muy poco antes pero ahora es cara?", "pt": "O que custava muito pouco antes, mas \u00e9 caro agora?", "ro": "Ce lucru costa foarte pu\u021bin atunci, dar e scump acum?", "fr": "Quelle chose co\u00fbtait tr\u00e8s peu autrefois mais est ch\u00e8re aujourd\u2019hui ?", "it": "Qualcosa che costava molto poco allora ma adesso \u00e8 costoso?", "fi": "Mik\u00e4 on jotain, mik\u00e4 maksoi ennen hyvin v\u00e4h\u00e4n, mutta on nyt kallista?", "nl": "Wat is iets dat vroeger heel weinig kostte maar nu duur is?", "no": "Hva er noe som kostet veldig lite den gangen, men som er dyrt n\u00e5?", "sv": "Vad \u00e4r n\u00e5got som kostade v\u00e4ldigt lite d\u00e5 men som \u00e4r dyrt nu?", "pl": "Co\u015b, co kiedy\u015b kosztowa\u0142o bardzo ma\u0142o, a teraz jest drogie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that cost very little back then but is expensive now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to do more slowly \u2014 and that was a good thing?", "da": "Hvad er noget, folk plejede at g\u00f8re langsommere \u2014 og det var godt?", "de": "Was haben die Leute fr\u00fcher langsamer gemacht \u2013 und das war gut so?", "es": "\u00bfQu\u00e9 hac\u00edan las personas m\u00e1s despacio antes \u2014 y era algo bueno?", "pt": "O que as pessoas faziam mais devagar antigamente \u2014 e era bom?", "ro": "Ce f\u0103ceau oamenii mai \u00eencet \u00eenainte \u2014 \u0219i era un lucru bun?", "fr": "Quelle chose les gens faisaient-ils plus lentement avant \u2014 et c\u2019\u00e9tait bien ainsi ?", "it": "Qualcosa che le persone facevano pi\u00f9 lentamente \u2014 e che era una cosa positiva?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen tekiv\u00e4t hitaammin \u2014 ja se oli hyv\u00e4 asia?", "nl": "Wat is iets dat mensen vroeger langzamer deden \u2014 en dat een goede zaak was?", "no": "Hva er noe folk pleide \u00e5 gj\u00f8re saktere \u2014 og som var en god ting?", "sv": "Vad \u00e4r n\u00e5got som folk brukade g\u00f6ra l\u00e5ngsammare \u2014 och som var en bra sak?", "pl": "Co\u015b, co ludzie robili kiedy\u015b wolniej \u2014 i to by\u0142o dobre?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to do more slowly — and that was a good thing?';
UPDATE questions
SET translations = '{"en": "What kind of music did you listen to, and how did you play it?", "da": "Hvilken slags musik lyttede du til, og hvordan spillede du den?", "de": "Welche Musik hast du geh\u00f6rt, und wie hast du sie gespielt?", "es": "\u00bfQu\u00e9 tipo de m\u00fasica escuchabas y c\u00f3mo la reproduc\u00edas?", "pt": "Que tipo de m\u00fasica ouvias e como a tocavas?", "ro": "Ce fel de muzic\u0103 ascultai \u0219i cum o redai?", "fr": "Quel genre de musique \u00e9coutais-tu et comment la jouais-tu ?", "it": "Che tipo di musica ascoltavi e come la suonavi?", "fi": "Millaista musiikkia kuuntelit ja miten soitit sit\u00e4?", "nl": "Welke soort muziek luisterde je naar, en hoe speelde je het?", "no": "Hvilken type musikk h\u00f8rte du p\u00e5, og hvordan spilte du den?", "sv": "Vilken typ av musik lyssnade du p\u00e5, och hur spelade du den?", "pl": "Jakiej muzyki s\u0142ucha\u0142e\u015b i jak j\u0105 odtwarza\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What kind of music did you listen to, and how did you play it?';
UPDATE questions
SET translations = '{"en": "Tell me about what people used to do for fun when you were young.", "da": "Fort\u00e6l mig, hvad folk plejede at g\u00f8re for sjov, da du var ung.", "de": "Erz\u00e4hl mir, was die Leute fr\u00fcher zum Spa\u00df gemacht haben, als du jung warst.", "es": "Cu\u00e9ntame qu\u00e9 hac\u00eda la gente para divertirse cuando eras joven.", "pt": "Conta-me o que as pessoas faziam para se divertir quando eras jovem.", "ro": "Spune-mi ce f\u0103ceau oamenii pentru distrac\u021bie c\u00e2nd erai t\u00e2n\u0103r.", "fr": "Raconte-moi ce que les gens faisaient pour s\u2019amuser quand tu \u00e9tais jeune.", "it": "Raccontami cosa facevano le persone per divertirsi quando eri giovane.", "fi": "Kerro minulle, mit\u00e4 ihmiset tekiv\u00e4t hauskaa nuoruudessasi.", "nl": "Vertel me wat mensen vroeger deden voor plezier toen je jong was.", "no": "Fortell meg om hva folk pleide \u00e5 gj\u00f8re for moro skyld da du var ung.", "sv": "Ber\u00e4tta om vad folk brukade g\u00f6ra f\u00f6r skoj n\u00e4r du var ung.", "pl": "Opowiedz mi, co ludzie robili dla zabawy, gdy by\u0142e\u015b m\u0142ody."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about what people used to do for fun when you were young.';
UPDATE questions
SET translations = '{"en": "What did \u201cstyle\u201d look like when you were growing up?", "da": "Hvordan s\u00e5 \u201cstil\u201d ud, da du voksede op?", "de": "Wie sah \u201eStil\u201c aus, als du aufgewachsen bist?", "es": "\u00bfC\u00f3mo era el \u201cestilo\u201d cuando crec\u00edas?", "pt": "Como era o \u201cestilo\u201d quando cresceste?", "ro": "Cum ar\u0103ta \u201estilul\u201d c\u00e2nd erai copil?", "fr": "\u00c0 quoi ressemblait le \u201cstyle\u201d quand tu grandissais ?", "it": "Com''era lo \"stile\" quando sei cresciuto?", "fi": "Millainen \"tyyli\" oli, kun kasvoit?", "nl": "Hoe zag \"stijl\" eruit toen je opgroeide?", "no": "Hvordan s\u00e5 \"stil\" ut da du vokste opp?", "sv": "Hur s\u00e5g \"stil\" ut n\u00e4r du v\u00e4xte upp?", "pl": "Jak wygl\u0105da\u0142 \u201estyl\u201d, gdy dorasta\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What did “style” look like when you were growing up?';
UPDATE questions
SET translations = '{"en": "What\u2019s something from the past you\u2019re glad didn\u2019t stick around?", "da": "Hvad er noget fra fortiden, du er glad for ikke h\u00e6nger ved?", "de": "Was aus der Vergangenheit bist du froh, dass es nicht geblieben ist?", "es": "\u00bfQu\u00e9 cosa del pasado te alegra que ya no exista?", "pt": "O que do passado te alegra que j\u00e1 n\u00e3o exista?", "ro": "Ce lucru din trecut te bucuri c\u0103 nu a r\u0103mas?", "fr": "Quelle chose du pass\u00e9 es-tu content(e) qu\u2019elle n\u2019existe plus ?", "it": "Qualcosa del passato di cui sei contento che non sia rimasto?", "fi": "Mik\u00e4 on jokin menneisyydest\u00e4, josta olet iloinen, ettei se j\u00e4\u00e4nyt pysyv\u00e4ksi?", "nl": "Wat is iets uit het verleden waar je blij mee bent dat het niet is gebleven?", "no": "Hva er noe fra fortiden du er glad for ikke ble v\u00e6rende?", "sv": "Vad \u00e4r n\u00e5got fr\u00e5n det f\u00f6rflutna som du \u00e4r glad att det inte stannade kvar?", "pl": "Co\u015b z przesz\u0142o\u015bci, z czego cieszysz si\u0119, \u017ce nie przetrwa\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something from the past you’re glad didn’t stick around?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think technology ruined?", "da": "Hvad er \u00e9n ting, du tror, teknologien \u00f8delagde?", "de": "Was ist eine Sache, von der du denkst, dass die Technologie sie ruiniert hat?", "es": "\u00bfQu\u00e9 es algo que crees que la tecnolog\u00eda arruin\u00f3?", "pt": "O que achas que a tecnologia arruinou?", "ro": "Ce crezi c\u0103 a stricat tehnologia?", "fr": "Quelle chose penses-tu que la technologie a g\u00e2ch\u00e9e ?", "it": "Qual \u00e8 una cosa che pensi la tecnologia abbia rovinato?", "fi": "Mik\u00e4 on yksi asia, jonka luulet teknologian pilanneen?", "nl": "Wat is \u00e9\u00e9n ding waarvan je denkt dat technologie het verpest heeft?", "no": "Hva er \u00e9n ting du mener teknologi har \u00f8delagt?", "sv": "Vad \u00e4r en sak som du tycker att teknologin har f\u00f6rst\u00f6rt?", "pl": "Co wed\u0142ug ciebie technologia zrujnowa\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you think technology ruined?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that made life simpler back then?", "da": "Hvad er noget, der gjorde livet enklere dengang?", "de": "Was hat das Leben fr\u00fcher einfacher gemacht?", "es": "\u00bfQu\u00e9 hac\u00eda la vida m\u00e1s simple antes?", "pt": "O que tornava a vida mais simples antigamente?", "ro": "Ce f\u0103cea via\u021ba mai simpl\u0103 atunci?", "fr": "Qu\u2019est-ce qui rendait la vie plus simple autrefois ?", "it": "Qualcosa che ha reso la vita pi\u00f9 semplice allora?", "fi": "Mik\u00e4 oli jotain, joka teki el\u00e4m\u00e4n yksinkertaisemmaksi silloin?", "nl": "Wat is iets dat het leven vroeger eenvoudiger maakte?", "no": "Hva er noe som gjorde livet enklere den gangen?", "sv": "Vad \u00e4r n\u00e5got som gjorde livet enklare d\u00e5?", "pl": "Co\u015b, co upraszcza\u0142o \u017cycie w tamtych czasach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that made life simpler back then?';
UPDATE questions
SET translations = '{"en": "What\u2019s something about today you wouldn\u2019t trade for anything?", "da": "Hvad er noget ved i dag, du ikke ville bytte for noget?", "de": "Was ist etwas an heute, das du f\u00fcr nichts eintauschen w\u00fcrdest?", "es": "\u00bfQu\u00e9 cosa de hoy no cambiar\u00edas por nada?", "pt": "O que de hoje n\u00e3o trocarias por nada?", "ro": "Ce este ceva din prezent pe care nu l-ai schimba pentru nimic?", "fr": "Quelle chose d\u2019aujourd\u2019hui ne changerais-tu pour rien au monde ?", "it": "Qualcosa di oggi che non scambieresti per nulla?", "fi": "Mik\u00e4 on jotain t\u00e4n\u00e4\u00e4n, jota et vaihtaisi mihink\u00e4\u00e4n?", "nl": "Wat is iets van vandaag dat je voor niets zou willen ruilen?", "no": "Hva er noe med i dag du ikke ville byttet bort for noe?", "sv": "Vad \u00e4r det som h\u00e4nde idag som du inte skulle byta mot n\u00e5got?", "pl": "Co\u015b, co dzisiaj masz, za nic by\u015b nie zamieni\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something about today you wouldn’t trade for anything?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that people were stricter about in your time?", "da": "Hvad var folk strengere med i din tid?", "de": "Womit waren die Leute in deiner Zeit strenger?", "es": "\u00bfCon qu\u00e9 eran m\u00e1s estrictas las personas en tu \u00e9poca?", "pt": "Com o que as pessoas eram mais rigorosas no teu tempo?", "ro": "Cu ce erau oamenii mai stric\u021bi \u00een vremea ta?", "fr": "Sur quoi les gens \u00e9taient-ils plus stricts \u00e0 ton \u00e9poque ?", "it": "Qualcosa di cui le persone erano pi\u00f9 severe ai tuoi tempi?", "fi": "Mik\u00e4 on jotain, mihin ihmiset olivat tiukempia sinun aikoinasi?", "nl": "Wat is iets waar mensen strenger over waren in jouw tijd?", "no": "Hva er noe folk var strengere p\u00e5 i din tid?", "sv": "Vad var n\u00e5got som folk var str\u00e4ngare med under din tid?", "pl": "Co\u015b, co ludzie byli surowsi w twoich czasach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that people were stricter about in your time?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that makes you think, \u201cWow, times have really changed\u201d?", "da": "Hvad er noget, der f\u00e5r dig til at t\u00e6nke: \u201cWow, tiderne har virkelig \u00e6ndret sig\u201d?", "de": "Was bringt dich dazu zu denken: \u201eWow, die Zeiten haben sich wirklich ver\u00e4ndert\u201c?", "es": "\u00bfQu\u00e9 te hace pensar: \u201cVaya, los tiempos realmente han cambiado\u201d?", "pt": "O que te faz pensar: \u201cUau, os tempos realmente mudaram\u201d?", "ro": "Ce te face s\u0103 spui: \u201eWow, vremurile chiar s-au schimbat\u201d?", "fr": "Qu\u2019est-ce qui te fait dire : \u00ab Wow, les temps ont vraiment chang\u00e9 \u00bb ?", "it": "Qualcosa che ti fa pensare: \"Wow, i tempi sono davvero cambiati\"?", "fi": "Mik\u00e4 on jotain, mik\u00e4 saa sinut ajattelemaan: \"Vau, ajat ovat todella muuttuneet\"?", "nl": "Wat is iets dat je doet denken: \"Wauw, de tijden zijn echt veranderd\"?", "no": "Hva er noe som f\u00e5r deg til \u00e5 tenke: \"Wow, tider har virkelig endret seg\"?", "sv": "Vad \u00e4r n\u00e5got som f\u00e5r dig att t\u00e4nka, \"Wow, tiderna har verkligen f\u00f6r\u00e4ndrats\"?", "pl": "Co\u015b, co sprawia, \u017ce my\u015blisz: \u201eWow, czasy naprawd\u0119 si\u0119 zmieni\u0142y\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that makes you think, “Wow, times have really changed”?';
UPDATE questions
SET translations = '{"en": "What was your favorite piece of \u201ccool\u201d tech when you were young?", "da": "Hvad var dit yndlingsstykke \u201csej\u201d teknologi, da du var ung?", "de": "Was war dein Lieblingsst\u00fcck \u201ecoole\u201c Technik, als du jung warst?", "es": "\u00bfCu\u00e1l era tu tecnolog\u00eda \u201cgenial\u201d favorita cuando eras joven?", "pt": "Qual era a tua tecnologia \u201cfixe\u201d favorita quando eras jovem?", "ro": "Care era tehnologia ta \u201ecool\u201d preferat\u0103 c\u00e2nd erai t\u00e2n\u0103r?", "fr": "Quel \u00e9tait ton gadget ou ta technologie \u00ab cool \u00bb pr\u00e9f\u00e9r\u00e9e quand tu \u00e9tais jeune ?", "it": "Qual era il tuo pezzo di tecnologia \"cool\" preferito quando eri giovane?", "fi": "Mik\u00e4 oli suosikkisi \"siistist\u00e4\" teknologiasta, kun olit nuori?", "nl": "Wat was jouw favoriete stuk \"coole\" technologie toen je jong was?", "no": "Hva var ditt favorittstykke av \"kult\" teknologi da du var ung?", "sv": "Vad var din favoritpryl av \"cool\" teknik n\u00e4r du var ung?", "pl": "Jaki by\u0142 tw\u00f3j ulubiony kawa\u0142ek \"fajnej\" technologii, gdy by\u0142e\u015b m\u0142ody?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your favorite piece of “cool” tech when you were young?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you hope never changes?", "da": "Hvad er \u00e9n ting, du h\u00e5ber aldrig \u00e6ndrer sig?", "de": "Was ist eine Sache, von der du hoffst, dass sie sich nie \u00e4ndert?", "es": "\u00bfQu\u00e9 cosa esperas que nunca cambie?", "pt": "O que esperas que nunca mude?", "ro": "Ce lucru speri s\u0103 nu se schimbe niciodat\u0103?", "fr": "Quelle chose esp\u00e8res-tu qu\u2019elle ne change jamais ?", "it": "Qual \u00e8 una cosa che speri non cambi mai?", "fi": "Mik\u00e4 on yksi asia, jonka toivot pysyv\u00e4n muuttumattomana?", "nl": "Wat is \u00e9\u00e9n ding waarvan je hoopt dat het nooit verandert?", "no": "Hva er \u00e9n ting du h\u00e5per aldri endrer seg?", "sv": "Vad \u00e4r en sak du hoppas aldrig f\u00f6r\u00e4ndras?", "pl": "Co jest jedn\u0105 rzecz\u0105, kt\u00f3ra, mam nadziej\u0119, nigdy si\u0119 nie zmieni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you hope never changes?';
UPDATE questions
SET translations = '{"en": "Tell me about a moment that changed the direction of your life.", "da": "Fort\u00e6l mig om et \u00f8jeblik, der \u00e6ndrede retningen i dit liv.", "de": "Erz\u00e4hl mir von einem Moment, der die Richtung deines Lebens ver\u00e4ndert hat.", "es": "Cu\u00e9ntame sobre un momento que cambi\u00f3 el rumbo de tu vida.", "pt": "Conta-me sobre um momento que mudou a dire\u00e7\u00e3o da tua vida.", "ro": "Spune-mi despre un moment care \u021bi-a schimbat direc\u021bia vie\u021bii.", "fr": "Raconte-moi un moment qui a chang\u00e9 la direction de ta vie.", "it": "Raccontami di un momento che ha cambiato la direzione della tua vita.", "fi": "Kerro minulle hetkest\u00e4, joka muutti el\u00e4m\u00e4si suuntaa.", "nl": "Vertel me over een moment dat de richting van je leven heeft veranderd.", "no": "Fortell meg om et \u00f8yeblikk som endret retningen i livet ditt.", "sv": "Ber\u00e4tta om ett \u00f6gonblick som f\u00f6r\u00e4ndrade riktningen i ditt liv.", "pl": "Opowiedz mi o momencie, kt\u00f3ry zmieni\u0142 kierunek twojego \u017cycia."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about a moment that changed the direction of your life.';
UPDATE questions
SET translations = '{"en": "What\u2019s a small decision that ended up changing a lot for you?", "da": "Hvad er en lille beslutning, der endte med at \u00e6ndre meget for dig?", "de": "Was ist eine kleine Entscheidung, die viel f\u00fcr dich ver\u00e4ndert hat?", "es": "\u00bfQu\u00e9 peque\u00f1a decisi\u00f3n termin\u00f3 cambiando mucho para ti?", "pt": "Que pequena decis\u00e3o acabou por mudar muito para ti?", "ro": "Ce mic\u0103 decizie a ajuns s\u0103-\u021bi schimbe mult via\u021ba?", "fr": "Quelle petite d\u00e9cision a fini par changer beaucoup pour toi ?", "it": "Qual \u00e8 una piccola decisione che alla fine ha cambiato molto per te?", "fi": "Mik\u00e4 on pieni p\u00e4\u00e4t\u00f6s, joka lopulta muutti paljon el\u00e4m\u00e4ss\u00e4si?", "nl": "Wat is een kleine beslissing die uiteindelijk veel voor jou heeft veranderd?", "no": "Hva er en liten beslutning som endte opp med \u00e5 forandre mye for deg?", "sv": "Vad \u00e4r ett litet beslut som slutade med att f\u00f6r\u00e4ndra mycket f\u00f6r dig?", "pl": "Jakie\u015b ma\u0142e postanowienie, kt\u00f3re ostatecznie zmieni\u0142o dla ciebie wiele?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a small decision that ended up changing a lot for you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to fix themselves that everyone replaces now?", "da": "Hvad plejede folk at reparere selv, som alle udskifter nu?", "de": "Was haben die Leute fr\u00fcher selbst repariert, was heute jeder ersetzt?", "es": "\u00bfQu\u00e9 sol\u00edan arreglar las personas antes que ahora todos reemplazan?", "pt": "O que as pessoas consertavam antes e agora todos substituem?", "ro": "Ce obi\u0219nuiau oamenii s\u0103 repare singuri, dar acum \u00eenlocuiesc?", "fr": "Que r\u00e9paraient autrefois les gens eux-m\u00eames que tout le monde remplace maintenant ?", "it": "Qualcosa che le persone si riparavano da sole e che ora tutti sostituiscono?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen korjasivat itse, mutta mik\u00e4 nyky\u00e4\u00e4n vaihdetaan?", "nl": "Wat is iets dat mensen vroeger zelf repareerden, maar wat nu iedereen vervangt?", "no": "Hva er noe folk pleide \u00e5 fikse selv, som alle n\u00e5 bytter ut?", "sv": "Vad \u00e4r n\u00e5got som folk brukade laga sj\u00e4lva men som alla nu byter ut?", "pl": "Co\u015b, co ludzie kiedy\u015b naprawiali sami, a teraz wszyscy wymieniaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to fix themselves that everyone replaces now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you had to wait for that\u2019s instant today?", "da": "Hvad ventede du p\u00e5 dengang, som er \u00f8jeblikkeligt i dag?", "de": "Worauf musstest du fr\u00fcher warten, das heute sofort da ist?", "es": "\u00bfQu\u00e9 ten\u00edas que esperar antes que ahora es instant\u00e1neo?", "pt": "O que tinhas de esperar antes e hoje \u00e9 instant\u00e2neo?", "ro": "Ce trebuia s\u0103 a\u0219tep\u021bi \u00eenainte \u0219i acum se \u00eent\u00e2mpl\u0103 instantaneu?", "fr": "Que devais-tu attendre autrefois et qui est instantan\u00e9 aujourd\u2019hui ?", "it": "Qualcosa per cui hai dovuto aspettare e che oggi \u00e8 istantaneo?", "fi": "Mik\u00e4 on jotain, jota jouduit odottamaan, mutta joka on t\u00e4n\u00e4\u00e4n v\u00e4lit\u00f6nt\u00e4?", "nl": "Wat is iets waar je op moest wachten dat vandaag de dag direct beschikbaar is?", "no": "Hva er noe du m\u00e5tte vente p\u00e5 som er \u00f8yeblikkelig i dag?", "sv": "Vad \u00e4r n\u00e5got du var tvungen att v\u00e4nta p\u00e5 som \u00e4r \u00f6gonblickligt idag?", "pl": "Co\u015b, na co musia\u0142e\u015b czeka\u0107, a co dzisiaj jest natychmiastowe?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you had to wait for that’s instant today?';
UPDATE questions
SET translations = '{"en": "What was your favorite thing to watch on TV \u2014 and when did it come on?", "da": "Hvad var dit yndlingsprogram i tv \u2014 og hvorn\u00e5r kom det p\u00e5?", "de": "Was war deine Lieblingssendung im Fernsehen \u2013 und wann lief sie?", "es": "\u00bfCu\u00e1l era tu programa favorito en la televisi\u00f3n \u2014 y cu\u00e1ndo se emit\u00eda?", "pt": "Qual era o teu programa favorito na TV \u2014 e quando dava?", "ro": "Care era emisiunea ta preferat\u0103 la TV \u2014 \u0219i c\u00e2nd era difuzat\u0103?", "fr": "Quelle \u00e9tait ton \u00e9mission pr\u00e9f\u00e9r\u00e9e \u00e0 la t\u00e9l\u00e9 \u2014 et quand passait-elle ?", "it": "Qual era la tua cosa preferita da guardare in TV \u2014 e quando andava in onda?", "fi": "Mik\u00e4 oli lempijuttusi, jota katsoit televisiosta \u2014 ja milloin se tuli?", "nl": "Wat was je favoriete programma om op tv te kijken \u2014 en wanneer kwam het op?", "no": "Hva var din favoritt \u00e5 se p\u00e5 TV \u2014 og n\u00e5r gikk det?", "sv": "Vad var din favoritgrej att titta p\u00e5 p\u00e5 TV \u2014 och n\u00e4r s\u00e4ndes den?", "pl": "Co by\u0142o twoj\u0105 ulubion\u0105 rzecz\u0105 do ogl\u0105dania w telewizji \u2014 i kiedy to lecia\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your favorite thing to watch on TV — and when did it come on?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think people had more patience for back then?", "da": "Hvad er \u00e9n ting, du tror, folk havde mere t\u00e5lmodighed med dengang?", "de": "Womit glaubst du, hatten die Menschen fr\u00fcher mehr Geduld?", "es": "\u00bfCon qu\u00e9 crees que la gente ten\u00eda m\u00e1s paciencia antes?", "pt": "Com o que achas que as pessoas tinham mais paci\u00eancia antigamente?", "ro": "Cu ce crezi c\u0103 aveau oamenii mai mult\u0103 r\u0103bdare \u00eenainte?", "fr": "Pour quoi penses-tu que les gens avaient plus de patience autrefois ?", "it": "Qual \u00e8 una cosa per cui pensi che le persone avessero pi\u00f9 pazienza ai tempi?", "fi": "Mik\u00e4 on yksi asia, johon luulet ihmisten olleen k\u00e4rsiv\u00e4llisempi\u00e4 ennen?", "nl": "Wat is \u00e9\u00e9n ding waar mensen vroeger meer geduld voor hadden, denk je?", "no": "Hva er \u00e9n ting du tror folk hadde mer t\u00e5lmodighet for den gang?", "sv": "Vad \u00e4r en sak som du tror att folk hade mer t\u00e5lamod f\u00f6r d\u00e5?", "pl": "Co\u015b, co my\u015blisz, \u017ce ludzie mieli wi\u0119cej cierpliwo\u015bci do tego kiedy\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you think people had more patience for back then?';
UPDATE questions
SET translations = '{"en": "What\u2019s a job that barely exists now but used to be common?", "da": "Hvilket job findes n\u00e6sten ikke mere, men var almindeligt f\u00f8r?", "de": "Welcher Beruf existiert heute kaum noch, war aber fr\u00fcher \u00fcblich?", "es": "\u00bfQu\u00e9 trabajo casi no existe ahora pero era com\u00fan antes?", "pt": "Que profiss\u00e3o quase n\u00e3o existe agora, mas era comum antes?", "ro": "Ce meserie abia mai exist\u0103 acum, dar era comun\u0103 \u00eenainte?", "fr": "Quel m\u00e9tier existe \u00e0 peine maintenant mais \u00e9tait courant autrefois ?", "it": "Qual \u00e8 un lavoro che esiste appena ora ma che era comune in passato?", "fi": "Mik\u00e4 on ty\u00f6, jota l\u00e4hes ei en\u00e4\u00e4 ole, mutta joka oli ennen yleinen?", "nl": "Wat is een baan die bijna niet meer bestaat, maar vroeger gebruikelijk was?", "no": "Hva er en jobb som knapt eksisterer n\u00e5, men som pleide \u00e5 v\u00e6re vanlig?", "sv": "Vilket jobb som knappt finns nu men som brukade vara vanligt?", "pl": "Jakie jest zaj\u0119cie, kt\u00f3re prawie nie istnieje teraz, ale kiedy\u015b by\u0142o powszechne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a job that barely exists now but used to be common?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that felt like luxury when you were growing up?", "da": "Hvad f\u00f8ltes som luksus, da du voksede op?", "de": "Was f\u00fchlte sich wie Luxus an, als du aufgewachsen bist?", "es": "\u00bfQu\u00e9 se sent\u00eda como un lujo cuando eras ni\u00f1o?", "pt": "O que parecia um luxo quando eras crian\u00e7a?", "ro": "Ce p\u0103rea un lux c\u00e2nd erai copil?", "fr": "Qu\u2019est-ce qui te semblait \u00eatre un luxe quand tu \u00e9tais enfant ?", "it": "Qualcosa che sembrava un lusso quando eri giovane?", "fi": "Mik\u00e4 oli jotain, mik\u00e4 tuntui ylellisyydelt\u00e4 lapsuudessasi?", "nl": "Wat was iets dat als luxe voelde toen je opgroeide?", "no": "Hva var noe som f\u00f8ltes som luksus da du vokste opp?", "sv": "Vad var n\u00e5got som k\u00e4ndes som lyx n\u00e4r du v\u00e4xte upp?", "pl": "Co\u015b, co wydawa\u0142o si\u0119 luksusem, gdy dorasta\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that felt like luxury when you were growing up?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think people took more pride in doing by hand?", "da": "Hvad er noget, du tror, folk var mere stolte af at lave i h\u00e5nden?", "de": "Worin glaubst du, waren die Menschen fr\u00fcher stolzer, wenn sie es von Hand gemacht haben?", "es": "\u00bfDe qu\u00e9 crees que la gente se sent\u00eda m\u00e1s orgullosa de hacer a mano antes?", "pt": "Do que achas que as pessoas tinham mais orgulho em fazer \u00e0 m\u00e3o?", "ro": "De ce crezi c\u0103 oamenii erau mai m\u00e2ndri s\u0103 fac\u0103 manual?", "fr": "De quoi penses-tu que les gens \u00e9taient plus fiers de faire \u00e0 la main ?", "it": "Qual \u00e8 qualcosa di cui pensi che le persone avessero pi\u00f9 orgoglio a fare a mano?", "fi": "Mik\u00e4 on jotain, mist\u00e4 luulet ihmisten olevan ylpe\u00e4mpi\u00e4, kun he tekev\u00e4t sen k\u00e4sin?", "nl": "Wat is iets waarvan je denkt dat mensen er meer trots op waren om het met de hand te doen?", "no": "Hva er noe du tror folk hadde mer stolthet i \u00e5 gj\u00f8re for h\u00e5nd?", "sv": "Vad \u00e4r n\u00e5got som du tror att folk tog mer stolthet i att g\u00f6ra f\u00f6r hand?", "pl": "Co\u015b, z czego my\u015blisz, \u017ce ludzie bardziej czerpali dum\u0119, robi\u0105c to r\u0119cznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you think people took more pride in doing by hand?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell that reminds you of \u201cthe old days\u201d?", "da": "Hvilken duft minder dig om \u201cde gode gamle dage\u201d?", "de": "Welcher Geruch erinnert dich an \u201edie guten alten Zeiten\u201c?", "es": "\u00bfQu\u00e9 olor te recuerda a \u201clos viejos tiempos\u201d?", "pt": "Que cheiro te lembra \u201cos bons velhos tempos\u201d?", "ro": "Ce miros \u00ee\u021bi aminte\u0219te de \u201evremurile bune de alt\u0103dat\u0103\u201d?", "fr": "Quelle odeur te rappelle \u201cle bon vieux temps\u201d ?", "it": "Qual \u00e8 un odore che ti ricorda \"i bei tempi\"?", "fi": "Mik\u00e4 tuoksu muistuttaa sinua \"vanhoista p\u00e4ivist\u00e4\"?", "nl": "Wat is een geur die je doet denken aan \"de oude tijden\"?", "no": "Hva er en lukt som minner deg om \"de gode gamle dager\"?", "sv": "Vilken doft p\u00e5minner dig om \"de gamla dagarna\"?", "pl": "Jaki zapach przypomina ci \"stare dobre czasy\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a smell that reminds you of “the old days”?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you used to do outside that kids rarely do now?", "da": "Hvad plejede du at lave udenfor, som b\u00f8rn sj\u00e6ldent g\u00f8r nu?", "de": "Was hast du fr\u00fcher drau\u00dfen gemacht, was Kinder heute selten tun?", "es": "\u00bfQu\u00e9 sol\u00edas hacer afuera que los ni\u00f1os rara vez hacen ahora?", "pt": "O que costumavas fazer ao ar livre que as crian\u00e7as raramente fazem agora?", "ro": "Ce f\u0103ceai afar\u0103 pe care copiii rar \u00eel mai fac acum?", "fr": "Que faisais-tu dehors que les enfants font rarement aujourd\u2019hui ?", "it": "Qualcosa che facevi all''aperto e che i bambini raramente fanno adesso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ennen teit ulkona, mutta mit\u00e4 lapset harvoin tekev\u00e4t nyt?", "nl": "Wat is iets dat je vroeger buiten deed wat kinderen nu zelden doen?", "no": "Hva er noe du pleide \u00e5 gj\u00f8re ute som barn sjelden gj\u00f8r n\u00e5?", "sv": "Vad \u00e4r n\u00e5got du brukade g\u00f6ra utomhus som barn s\u00e4llan g\u00f6r nu?", "pl": "Co\u015b, co kiedy\u015b robi\u0142e\u015b na zewn\u0105trz, a dzieci rzadko robi\u0105 teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you used to do outside that kids rarely do now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people collected before photos lived on phones?", "da": "Hvad samlede folk p\u00e5, f\u00f8r billeder levede p\u00e5 telefoner?", "de": "Was sammelten die Leute, bevor Fotos auf Handys gespeichert wurden?", "es": "\u00bfQu\u00e9 coleccionaba la gente antes de que las fotos vivieran en los tel\u00e9fonos?", "pt": "O que as pessoas colecionavam antes de as fotos viverem nos telem\u00f3veis?", "ro": "Ce colec\u021bionau oamenii \u00eenainte ca fotografiile s\u0103 fie pe telefoane?", "fr": "Que collectionnaient les gens avant que les photos vivent sur les t\u00e9l\u00e9phones ?", "it": "Qualcosa che le persone collezionavano prima che le foto vivessero sui telefoni?", "fi": "Mit\u00e4 asioita ihmiset ker\u00e4siv\u00e4t ennen kuin valokuvat olivat puhelimissa?", "nl": "Wat is iets dat mensen verzamelden voordat foto''s op telefoons stonden?", "no": "Hva er noe folk samlet p\u00e5 f\u00f8r bilder ble lagret p\u00e5 telefoner?", "sv": "Vad \u00e4r n\u00e5got som folk samlade p\u00e5 innan foton fanns p\u00e5 telefoner?", "pl": "Co\u015b, co ludzie zbierali, zanim zdj\u0119cia zacz\u0119\u0142y by\u0107 przechowywane w telefonach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people collected before photos lived on phones?';