UPDATE questions
SET translations = '{"en": "\u201cJournalists are too partisan nowadays to be trusted.\u201d", "da": "Journalister er for partiske i dag til at kunne stoles p\u00e5.", "de": "Journalisten sind heutzutage zu parteiisch, um ihnen zu vertrauen.", "es": "Los periodistas son demasiado parciales hoy en d\u00eda para ser confiables.", "pt": "Os jornalistas est\u00e3o demasiado tendenciosos hoje para serem confi\u00e1veis.", "ro": "Jurnali\u0219tii sunt prea p\u0103rtinitori \u00een zilele noastre pentru a fi de \u00eencredere.", "fr": "Les journalistes sont aujourd\u2019hui trop partisans pour \u00eatre dignes de confiance.", "it": "\"I giornalisti sono troppo faziosi al giorno d''oggi per essere fidati.\"", "fi": "\u201dToimittajat ovat nyky\u00e4\u00e4n liian puolueellisia, jotta heihin voisi luottaa.\u201d", "nl": "\"Journalisten zijn tegenwoordig te partijdig om te vertrouwen.\"", "no": "\"Journalister er for partiske i dag til \u00e5 v\u00e6re til \u00e5 stole p\u00e5.\"", "sv": "\"Journalister \u00e4r f\u00f6r partiska nuf\u00f6rtiden f\u00f6r att kunna litas p\u00e5.\"", "pl": "\u201eDziennikarze s\u0105 dzisiaj zbyt stronniczy, aby im ufa\u0107.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Journalists are too partisan nowadays to be trusted.”';
UPDATE questions
SET translations = '{"en": "\u201cTruth is subjective \u2014 objectivity is a myth.\u201d", "da": "Sandheden er subjektiv \u2013 objektivitet er en myte.", "de": "Wahrheit ist subjektiv \u2013 Objektivit\u00e4t ist ein Mythos.", "es": "La verdad es subjetiva \u2014 la objetividad es un mito.", "pt": "A verdade \u00e9 subjetiva \u2014 a objetividade \u00e9 um mito.", "ro": "Adev\u0103rul este subiectiv \u2014 obiectivitatea este un mit.", "fr": "La v\u00e9rit\u00e9 est subjective \u2014 l\u2019objectivit\u00e9 est un mythe.", "it": "\"La verit\u00e0 \u00e8 soggettiva \u2014 l''oggettivit\u00e0 \u00e8 un mito.\"", "fi": "\"Totuus on subjektiivista \u2014 objektiivisuus on myytti.\"", "nl": "\"Waarheid is subjectief \u2014 objectiviteit is een mythe.\"", "no": "\u201cSandhet er subjektiv \u2014 objektivitet er en myte.\u201d", "sv": "\"Sanningen \u00e4r subjektiv \u2014 objektivitet \u00e4r en myt.\"", "pl": "\u201ePrawda jest subiektywna \u2014 obiektywno\u015b\u0107 to mit.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Truth is subjective — objectivity is a myth.”';
UPDATE questions
SET translations = '{"en": "\u201cClimate change is a symptom, not the root problem.\u201d", "da": "Klimaforandringer er et symptom, ikke rodproblemet.", "de": "Der Klimawandel ist ein Symptom, nicht das eigentliche Problem.", "es": "El cambio clim\u00e1tico es un s\u00edntoma, no el problema ra\u00edz.", "pt": "As altera\u00e7\u00f5es clim\u00e1ticas s\u00e3o um sintoma, n\u00e3o o problema principal.", "ro": "Schimb\u0103rile climatice sunt un simptom, nu problema de baz\u0103.", "fr": "Le changement climatique est un sympt\u00f4me, pas le probl\u00e8me fondamental.", "it": "\"Il cambiamento climatico \u00e8 un sintomo, non il problema fondamentale.\"", "fi": "\"Ilmastonmuutos on oire, ei juurisyy.\"", "nl": "\"Klimaatverandering is een symptoom, niet het onderliggende probleem.\"", "no": "\u00abKlimaforandringer er et symptom, ikke roten til problemet.\u00bb", "sv": "\"Klimatf\u00f6r\u00e4ndringar \u00e4r ett symptom, inte det grundl\u00e4ggande problemet.\"", "pl": "\u201eZmiana klimatu jest objawem, a nie podstawowym problemem.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Climate change is a symptom, not the root problem.”';
UPDATE questions
SET translations = '{"en": "\u201cReligion is more harmful than helpful in modern society.\u201d", "da": "Religion g\u00f8r mere skade end gavn i det moderne samfund.", "de": "Religion richtet in der modernen Gesellschaft mehr Schaden als Nutzen an.", "es": "La religi\u00f3n hace m\u00e1s da\u00f1o que bien en la sociedad moderna.", "pt": "A religi\u00e3o faz mais mal do que bem na sociedade moderna.", "ro": "Religia face mai mult r\u0103u dec\u00e2t bine \u00een societatea modern\u0103.", "fr": "La religion fait plus de mal que de bien dans la soci\u00e9t\u00e9 moderne.", "it": "\"La religione \u00e8 pi\u00f9 dannosa che utile nella societ\u00e0 moderna.\"", "fi": "\"Uskonto on nykyaikaisessa yhteiskunnassa enemm\u00e4n haitallista kuin hy\u00f6dyllist\u00e4.\"", "nl": "\"Religie is schadelijker dan behulpzaam in de moderne samenleving.\"", "no": "\u201cReligion er mer skadelig enn nyttig i det moderne samfunnet.\u201d", "sv": "\"Religion \u00e4r mer skadlig \u00e4n hj\u00e4lpsam i det moderna samh\u00e4llet.\"", "pl": "\u201eReligia jest bardziej szkodliwa ni\u017c pomocna we wsp\u00f3\u0142czesnym spo\u0142ecze\u0144stwie.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Religion is more harmful than helpful in modern society.”';
UPDATE questions
SET translations = '{"en": "\u201cSpirituality without religion is just self-indulgence.\u201d", "da": "Spiritualitet uden religion er bare selvfork\u00e6lelse.", "de": "Spiritualit\u00e4t ohne Religion ist nur Selbstgef\u00e4lligkeit.", "es": "La espiritualidad sin religi\u00f3n es solo autoindulgencia.", "pt": "A espiritualidade sem religi\u00e3o \u00e9 apenas autoindulg\u00eancia.", "ro": "Spiritualitatea f\u0103r\u0103 religie este doar autoindulgen\u021b\u0103.", "fr": "La spiritualit\u00e9 sans religion n\u2019est qu\u2019une forme d\u2019auto-indulgence.", "it": "\"La spiritualit\u00e0 senza religione \u00e8 solo indulgenza personale.\"", "fi": "\"Spirituaalisuus ilman uskontoa on vain itsens\u00e4 hemmottelua.\"", "nl": "\"Spiritualiteit zonder religie is gewoon zelfzucht.\"", "no": "\"\u00c5ndelighet uten religion er bare selvtilfredsstillelse.\"", "sv": "\"Spiritualitet utan religion \u00e4r bara sj\u00e4lvf\u00f6rverkligande.\"", "pl": "\u201eDuchowo\u015b\u0107 bez religii to tylko samolubstwo.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Spirituality without religion is just self-indulgence.”';
UPDATE questions
SET translations = '{"en": "\u201cMarriage is an outdated institution.\u201d", "da": "\u00c6gteskab er en for\u00e6ldet institution.", "de": "Die Ehe ist eine veraltete Institution.", "es": "El matrimonio es una instituci\u00f3n obsoleta.", "pt": "O casamento \u00e9 uma institui\u00e7\u00e3o ultrapassada.", "ro": "C\u0103s\u0103toria este o institu\u021bie dep\u0103\u0219it\u0103.", "fr": "Le mariage est une institution d\u00e9pass\u00e9e.", "it": "\"Il matrimonio \u00e8 un''istituzione obsoleta.\"", "fi": "\"Avioituminen on vanhentunut instituutio.\"", "nl": "\"Het huwelijk is een verouderde instelling.\"", "no": "\"Ekteskap er en utdatert institusjon.\"", "sv": "\u201d\u00c4ktenskap \u00e4r en f\u00f6r\u00e5ldrad institution.\u201d", "pl": "\u201eMa\u0142\u017ce\u0144stwo to przestarza\u0142a instytucja.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Marriage is an outdated institution.”';
UPDATE questions
SET translations = '{"en": "\u201cChildren are too much responsibility in today\u2019s world \u2014 it\u2019s selfish to have them.\u201d", "da": "B\u00f8rn er for stort et ansvar i dag \u2013 det er egoistisk at f\u00e5 dem.", "de": "Kinder sind heutzutage zu viel Verantwortung \u2013 es ist egoistisch, sie zu haben.", "es": "Los ni\u00f1os son demasiada responsabilidad hoy en d\u00eda \u2014 es ego\u00edsta tenerlos.", "pt": "As crian\u00e7as s\u00e3o responsabilidade a mais hoje em dia \u2014 \u00e9 ego\u00edsta t\u00ea-las.", "ro": "Copiii sunt o responsabilitate prea mare azi \u2014 e egoist s\u0103-i ai.", "fr": "Les enfants repr\u00e9sentent trop de responsabilit\u00e9 aujourd\u2019hui \u2014 c\u2019est \u00e9go\u00efste d\u2019en avoir.", "it": "\"I bambini sono una responsabilit\u00e0 troppo grande nel mondo di oggi \u2014 \u00e8 egoistico averne.\"", "fi": "\"Lapset ovat nykymaailmassa liian suuri vastuu - on itsek\u00e4st\u00e4 hankkia niit\u00e4.\"", "nl": "\"Kinderen zijn te veel verantwoordelijkheid in de wereld van vandaag \u2014 het is ego\u00efstisch om ze te hebben.\"", "no": "\u00abBarn er for mye ansvar i dagens verden \u2014 det er egoistisk \u00e5 f\u00e5 dem.\u00bb", "sv": "\"Barn \u00e4r f\u00f6r mycket ansvar i dagens v\u00e4rld \u2014 det \u00e4r egoistiskt att skaffa dem.\"", "pl": "\u201eDzieci to zbyt du\u017ca odpowiedzialno\u015b\u0107 w dzisiejszym \u015bwiecie \u2014 to egoistyczne, \u017ceby je mie\u0107.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Children are too much responsibility in today’s world — it’s selfish to have them.”';
UPDATE questions
SET translations = '{"en": "\u201cPeople should live forever if we can fix aging.\u201d", "da": "Mennesker b\u00f8r leve evigt, hvis vi kan l\u00f8se aldring.", "de": "Menschen sollten ewig leben, wenn wir das Altern beheben k\u00f6nnen.", "es": "Las personas deber\u00edan vivir para siempre si podemos arreglar el envejecimiento.", "pt": "As pessoas deveriam viver para sempre se conseguirmos curar o envelhecimento.", "ro": "Oamenii ar trebui s\u0103 tr\u0103iasc\u0103 ve\u0219nic dac\u0103 putem repara \u00eemb\u0103tr\u00e2nirea.", "fr": "Les humains devraient vivre \u00e9ternellement si nous pouvons corriger le vieillissement.", "it": "\"Le persone dovrebbero vivere per sempre se possiamo risolvere l''invecchiamento.\"", "fi": "\"Ihmisten pit\u00e4isi el\u00e4\u00e4 ikuisesti, jos voimme korjata vanhenemisen.\"", "nl": "\"Mensen zouden voor altijd moeten leven als we veroudering kunnen verhelpen.\"", "no": "\"Folk b\u00f8r leve for alltid hvis vi kan fikse aldring.\"", "sv": "\"Folk borde leva f\u00f6r evigt om vi kan fixa \u00e5ldrandet.\"", "pl": "\u201eLudzie powinni \u017cy\u0107 wiecznie, je\u015bli mo\u017cemy naprawi\u0107 starzenie si\u0119.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“People should live forever if we can fix aging.”';
UPDATE questions
SET translations = '{"en": "\u201cHealth and wellness culture is often a new form of judgment.\u201d", "da": "Sundheds- og wellnesskulturen er ofte en ny form for d\u00f8mmende adf\u00e6rd.", "de": "Gesundheits- und Wellnesskultur ist oft eine neue Form des Urteilens.", "es": "La cultura del bienestar y la salud es a menudo una nueva forma de juicio.", "pt": "A cultura de sa\u00fade e bem-estar \u00e9 muitas vezes uma nova forma de julgamento.", "ro": "Cultura s\u0103n\u0103t\u0103\u021bii \u0219i a wellnessului este adesea o nou\u0103 form\u0103 de judecat\u0103.", "fr": "La culture du bien-\u00eatre et de la sant\u00e9 est souvent une nouvelle forme de jugement.", "it": "\"La cultura della salute e del benessere \u00e8 spesso una nuova forma di giudizio.\"", "fi": "\"Terveyden ja hyvinvoinnin kulttuuri on usein uusi tuomion muoto.\"", "nl": "\"De cultuur van gezondheid en welzijn is vaak een nieuwe vorm van oordeel.\"", "no": "\"Helse- og velv\u00e6re-kultur er ofte en ny form for d\u00f8mming.\"", "sv": "\"H\u00e4lsa och v\u00e4lbefinnande kultur \u00e4r ofta en ny form av d\u00f6mande.\"", "pl": "\u201eKultura zdrowia i wellness cz\u0119sto jest now\u0105 form\u0105 os\u0105du.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Health and wellness culture is often a new form of judgment.”';
UPDATE questions
SET translations = '{"en": "\u201cCanceling celebrities is easier than holding real power to account.\u201d", "da": "At aflyse kendisser er lettere end at holde reel magt ansvarlig.", "de": "Prominente zu canceln ist einfacher, als echte Macht zur Rechenschaft zu ziehen.", "es": "Cancelar a las celebridades es m\u00e1s f\u00e1cil que responsabilizar al verdadero poder.", "pt": "Cancelar celebridades \u00e9 mais f\u00e1cil do que responsabilizar o verdadeiro poder.", "ro": "Anularea celebrit\u0103\u021bilor e mai u\u0219oar\u0103 dec\u00e2t tragerea la r\u0103spundere a adev\u0103ratei puteri.", "fr": "Annuler des c\u00e9l\u00e9brit\u00e9s est plus facile que de tenir le vrai pouvoir responsable.", "it": "\"Cancellare le celebrit\u00e0 \u00e8 pi\u00f9 facile che rendere conto del vero potere.\"", "fi": "\"Julkkisten peruminen on helpompaa kuin todellisen vallan pit\u00e4mminen vastuussa.\"", "nl": "\"Het afschaffen van beroemdheden is makkelijker dan echte macht ter verantwoording roepen.\"", "no": "\"\u00c5 avlyse kjendiser er enklere enn \u00e5 holde ekte makt ansvarlig.\"", "sv": "\"Att avf\u00e4rda k\u00e4ndisar \u00e4r l\u00e4ttare \u00e4n att st\u00e4lla verklig makt till svars.\"", "pl": "\u201eAnulowanie celebryt\u00f3w jest \u0142atwiejsze ni\u017c poci\u0105ganie do odpowiedzialno\u015bci prawdziwej w\u0142adzy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Canceling celebrities is easier than holding real power to account.”';
UPDATE questions
SET translations = '{"en": "\u201cLuxury brands are just expensive uniforms for insecure people.\u201d", "da": "Luksusm\u00e6rker er bare dyre uniformer for usikre mennesker.", "de": "Luxusmarken sind nur teure Uniformen f\u00fcr unsichere Menschen.", "es": "Las marcas de lujo son solo uniformes caros para personas inseguras.", "pt": "As marcas de luxo s\u00e3o apenas uniformes caros para pessoas inseguras.", "ro": "M\u0103rcile de lux sunt doar uniforme scumpe pentru oameni nesiguri.", "fr": "Les marques de luxe ne sont que des uniformes co\u00fbteux pour les ins\u00e9cures.", "it": "\"Le marche di lusso sono solo uniformi costose per persone insicure.\"", "fi": "\"Ylelliset br\u00e4ndit ovat vain kalliita univormuja ep\u00e4varmoille ihmisille.\"", "nl": "\u201cLuxe merken zijn gewoon dure uniformen voor onzekere mensen.\u201d", "no": "\u00abLuksusmerker er bare dyre uniformer for usikre mennesker.\u00bb", "sv": "\"Lyxm\u00e4rken \u00e4r bara dyra uniformer f\u00f6r os\u00e4kra m\u00e4nniskor.\"", "pl": "\u201eMarki luksusowe to tylko drogie mundury dla niepewnych siebie ludzi.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Luxury brands are just expensive uniforms for insecure people.”';
UPDATE questions
SET translations = '{"en": "\u201cAuthenticity online is mostly performative.\u201d", "da": "Autenticitet online er for det meste performativ.", "de": "Online-Authentizit\u00e4t ist meist performativ.", "es": "La autenticidad en l\u00ednea es mayormente performativa.", "pt": "A autenticidade online \u00e9 maioritariamente performativa.", "ro": "Autenticitatea online este \u00een mare parte teatral\u0103.", "fr": "L\u2019authenticit\u00e9 en ligne est principalement performative.", "it": "\"L''autenticit\u00e0 online \u00e8 per lo pi\u00f9 performativa.\"", "fi": "\"Verkossa aitous on enimm\u00e4kseen esitt\u00e4v\u00e4\u00e4.\"", "nl": "\"Authenticiteit online is voornamelijk performatief.\"", "no": "\"Autentisitet p\u00e5 nettet er for det meste performativ.\"", "sv": "\"\u00c4kthet online \u00e4r mestadels performativ.\"", "pl": "\u201eAutentyczno\u015b\u0107 w internecie jest w wi\u0119kszo\u015bci performatywna.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Authenticity online is mostly performative.”';
UPDATE questions
SET translations = '{"en": "\u201cYou\u2019re obligated to call out injustice, even if it risks your social status.\u201d", "da": "Du er forpligtet til at p\u00e5tale uretf\u00e6rdighed, selv hvis det koster dig social status.", "de": "Du bist verpflichtet, Ungerechtigkeit anzusprechen, selbst wenn es dich sozialen Status kostet.", "es": "Est\u00e1s obligado a denunciar la injusticia, incluso si arriesgas tu estatus social.", "pt": "\u00c9s obrigado a denunciar a injusti\u00e7a, mesmo que arrisques o teu estatuto social.", "ro": "E\u0219ti obligat s\u0103 denun\u021bi nedreptatea, chiar dac\u0103 \u00ee\u021bi ri\u0219ti statutul social.", "fr": "Tu es oblig\u00e9 de d\u00e9noncer l\u2019injustice, m\u00eame si cela met en danger ton statut social.", "it": "\u201cSei obbligato a denunciare l''ingiustizia, anche se questo mette a rischio il tuo status sociale.\u201d", "fi": "\"Olet velvoitettu puuttumaan ep\u00e4oikeudenmukaisuuteen, vaikka se uhkaisi sosiaalista asemaasi.\"", "nl": "\"Je bent verplicht om onrecht aan te kaarten, ook al brengt het je sociale status in gevaar.\"", "no": "\"Du er forpliktet til \u00e5 p\u00e5peke urettferdighet, selv om det kan true din sosiale status.\"", "sv": "\"Du \u00e4r skyldig att p\u00e5peka or\u00e4ttvisor, \u00e4ven om det riskerar din sociala status.\"", "pl": "\u201eJeste\u015b zobowi\u0105zany do wytykania niesprawiedliwo\u015bci, nawet je\u015bli grozi to twojemu statusowi spo\u0142ecznemu.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You’re obligated to call out injustice, even if it risks your social status.”';
UPDATE questions
SET translations = '{"en": "\u201cYou shouldn\u2019t support a brand just because it\u2019s \u201cethical\u201d \u2014 ethics are marketing now.\u201d", "da": "Du b\u00f8r ikke st\u00f8tte et brand bare fordi det er \u201cetisk\u201d \u2013 etik er markedsf\u00f8ring nu.", "de": "Man sollte eine Marke nicht nur unterst\u00fctzen, weil sie \u201eethisch\u201c ist \u2013 Ethik ist jetzt Marketing.", "es": "No deber\u00edas apoyar una marca solo porque sea \u201c\u00e9tica\u201d \u2014 la \u00e9tica ahora es marketing.", "pt": "N\u00e3o deves apoiar uma marca apenas porque \u00e9 \u201c\u00e9tica\u201d \u2014 a \u00e9tica \u00e9 marketing agora.", "ro": "Nu ar trebui s\u0103 sprijini un brand doar pentru c\u0103 este \u201cetic\u201d \u2014 etica e marketing acum.", "fr": "Tu ne devrais pas soutenir une marque simplement parce qu\u2019elle est \u00ab \u00e9thique \u00bb \u2014 l\u2019\u00e9thique est devenue du marketing.", "it": "\"Non dovresti sostenere un marchio solo perch\u00e9 \u00e8 ''etico'' \u2014 l''etica \u00e8 diventata marketing ora.\"", "fi": "\"Et pit\u00e4isi tukea br\u00e4ndi\u00e4 vain sen vuoksi, ett\u00e4 se on ''eettinen'' \u2014 eettisyys on nyky\u00e4\u00e4n markkinointia.\"", "nl": "\"Je zou een merk niet moeten steunen alleen omdat het ''ethisch'' is \u2014 ethiek is nu marketing.\"", "no": "\"Du b\u00f8r ikke st\u00f8tte et merke bare fordi det er ''etisk'' \u2014 etikk er n\u00e5 markedsf\u00f8ring.\"", "sv": "\"Du borde inte st\u00f6dja ett m\u00e4rke bara f\u00f6r att det \u00e4r ''etiskt'' \u2014 etik \u00e4r nu marknadsf\u00f6ring.\"", "pl": "\u201eNie powiniene\u015b wspiera\u0107 marki tylko dlatego, \u017ce jest \u201eetyczna\u201d \u2014 etyka to teraz marketing.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You shouldn’t support a brand just because it’s “ethical” — ethics are marketing now.”';
UPDATE questions
SET translations = '{"en": "\u201cMinimalism should be imposed: everyone should live with < X possessions.\u201d", "da": "Minimalisme b\u00f8r p\u00e5l\u00e6gges: alle b\u00f8r leve med f\u00e6rre ejendele.", "de": "Minimalismus sollte vorgeschrieben werden: Jeder sollte mit weniger Besitz leben.", "es": "El minimalismo deber\u00eda imponerse: todos deber\u00edan vivir con menos posesiones.", "pt": "O minimalismo deveria ser imposto: todos deveriam viver com menos posses.", "ro": "Minimalismul ar trebui impus: to\u021bi ar trebui s\u0103 tr\u0103iasc\u0103 cu mai pu\u021bine lucruri.", "fr": "Le minimalisme devrait \u00eatre impos\u00e9 : tout le monde devrait vivre avec moins de possessions.", "it": "\"Il minimalismo dovrebbe essere imposto: tutti dovrebbero vivere con < X possedimenti.\"", "fi": "\"Minimalismia tulisi pakottaa: jokaisen tulisi el\u00e4\u00e4 alle < X omaisuuden kanssa.\"", "nl": "\"Minimalisme zou moeten worden opgelegd: iedereen zou met < X bezittingen moeten leven.\"", "no": "\u201cMinimalisme b\u00f8r p\u00e5legges: alle b\u00f8r leve med < X eiendeler.\u201d", "sv": "\"Minimalism b\u00f6r inf\u00f6ras: alla b\u00f6r leva med < X \u00e4godelar.\"", "pl": "\u201eMinimalizm powinien by\u0107 narzucony: ka\u017cdy powinien \u017cy\u0107 z < X przedmiotami.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Minimalism should be imposed: everyone should live with < X possessions.”';
UPDATE questions
SET translations = '{"en": "\u201cMoney is the most honest expression of value in relationships (time, gifts, wages).\u201d", "da": "Penge er det mest \u00e6rlige udtryk for v\u00e6rdi i forhold (tid, gaver, l\u00f8n).", "de": "Geld ist der ehrlichste Ausdruck von Wert in Beziehungen (Zeit, Geschenke, L\u00f6hne).", "es": "El dinero es la expresi\u00f3n m\u00e1s honesta de valor en las relaciones (tiempo, regalos, salarios).", "pt": "O dinheiro \u00e9 a express\u00e3o mais honesta de valor nas rela\u00e7\u00f5es (tempo, presentes, sal\u00e1rios).", "ro": "Banii sunt cea mai sincer\u0103 expresie a valorii \u00een rela\u021bii (timp, cadouri, salarii).", "fr": "L\u2019argent est la forme la plus honn\u00eate d\u2019expression de la valeur dans les relations (temps, cadeaux, salaires).", "it": "\u201cIl denaro \u00e8 l''espressione pi\u00f9 onesta del valore nelle relazioni (tempo, regali, salari).\u201d", "fi": "\"Raha on rehellisin arvon ilmaisu suhteissa (aika, lahjat, palkat).\"", "nl": "\"Geld is de meest eerlijke uitdrukking van waarde in relaties (tijd, cadeaus, lonen).\"", "no": "\u201cPenger er den mest \u00e6rlige uttrykk for verdi i relasjoner (tid, gaver, l\u00f8nn).\u201d", "sv": "\"Pengar \u00e4r det mest \u00e4rliga uttrycket f\u00f6r v\u00e4rde i relationer (tid, g\u00e5vor, l\u00f6ner).\"", "pl": "\u201ePieni\u0105dze s\u0105 najuczciwszym wyrazem warto\u015bci w relacjach (czas, prezenty, wynagrodzenia).\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Money is the most honest expression of value in relationships (time, gifts, wages).”';
UPDATE questions
SET translations = '{"en": "\u201cPrivacy is dead and we should stop pretending otherwise.\u201d", "da": "Privatliv er d\u00f8dt, og vi b\u00f8r stoppe med at lade som om det eksisterer.", "de": "Privatsph\u00e4re ist tot, und wir sollten aufh\u00f6ren, so zu tun, als g\u00e4be es sie.", "es": "La privacidad est\u00e1 muerta y deber\u00edamos dejar de fingir lo contrario.", "pt": "A privacidade est\u00e1 morta e devemos parar de fingir o contr\u00e1rio.", "ro": "Confiden\u021bialitatea este moart\u0103 \u0219i ar trebui s\u0103 \u00eencet\u0103m s\u0103 pretindem contrariul.", "fr": "La vie priv\u00e9e est morte et nous devrions cesser de pr\u00e9tendre le contraire.", "it": "\"La privacy \u00e8 morta e dovremmo smettere di fare finta del contrario.\"", "fi": "\"Yksityisyys on kuollut, ja meid\u00e4n pit\u00e4isi lopettaa teeskentely.\"", "nl": "\"Privacy is dood en we moeten stoppen met doen alsof dat niet zo is.\"", "no": "\"Personvernet er d\u00f8dt, og vi b\u00f8r slutte \u00e5 late som noe annet.\"", "sv": "\"Integriteten \u00e4r d\u00f6d och vi borde sluta l\u00e5tsas som n\u00e5got annat.\"", "pl": "\u201ePrywatno\u015b\u0107 umar\u0142a i powinni\u015bmy przesta\u0107 udawa\u0107, \u017ce jest inaczej.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Privacy is dead and we should stop pretending otherwise.”';
UPDATE questions
SET translations = '{"en": "\u201cVirtual reality will replace physical travel.\u201d", "da": "Virtuel virkelighed vil erstatte fysisk rejse.", "de": "Virtuelle Realit\u00e4t wird physisches Reisen ersetzen.", "es": "La realidad virtual reemplazar\u00e1 los viajes f\u00edsicos.", "pt": "A realidade virtual vai substituir as viagens f\u00edsicas.", "ro": "Realitatea virtual\u0103 va \u00eenlocui c\u0103l\u0103toriile fizice.", "fr": "La r\u00e9alit\u00e9 virtuelle remplacera les voyages physiques.", "it": "\"La realt\u00e0 virtuale sostituir\u00e0 i viaggi fisici.\"", "fi": "\"Virtuaalitodellisuus tulee korvaamaan fyysisen matkustamisen.\"", "nl": "\"Virtuele realiteit zal fysiek reizen vervangen.\"", "no": "\"Virtuell virkelighet vil erstatte fysisk reise.\"", "sv": "\"Virtuell verklighet kommer att ers\u00e4tta fysisk resa.\"", "pl": "\u201eWirtualna rzeczywisto\u015b\u0107 zast\u0105pi podr\u00f3\u017ce fizyczne.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Virtual reality will replace physical travel.”';
UPDATE questions
SET translations = '{"en": "\u201cSpace exploration is a waste while earth problems persist.\u201d", "da": "Rumforskning er spild, mens jordens problemer best\u00e5r.", "de": "Weltraumforschung ist eine Verschwendung, solange Probleme auf der Erde bestehen.", "es": "La exploraci\u00f3n espacial es un desperdicio mientras persistan los problemas terrestres.", "pt": "A explora\u00e7\u00e3o espacial \u00e9 um desperd\u00edcio enquanto persistirem os problemas na Terra.", "ro": "Explorarea spa\u021bial\u0103 este o risip\u0103 c\u00e2t timp problemele P\u0103m\u00e2ntului persist\u0103.", "fr": "L\u2019exploration spatiale est un gaspillage tant que les probl\u00e8mes terrestres persistent.", "it": "\"L''esplorazione spaziale \u00e8 uno spreco mentre i problemi sulla Terra persistono.\"", "fi": "\"Avaruustutkimus on hukkaa, kun maan ongelmat jatkuvat.\"", "nl": "\"Ruimteverkenning is een verspilling terwijl de problemen op aarde aanhouden.\"", "no": "\"Romforskning er bortkastet mens jordens problemer vedvarer.\"", "sv": "\"Rymdforskning \u00e4r sl\u00f6seri medan jordens problem kvarst\u00e5r.\"", "pl": "\u201eEksploracja kosmosu to marnotrawstwo, podczas gdy problemy na Ziemi wci\u0105\u017c istniej\u0105.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Space exploration is a waste while earth problems persist.”';
UPDATE questions
SET translations = '{"en": "\u201cWe should judge people\u2019s future actions more than past mistakes.\u201d", "da": "Vi b\u00f8r bed\u00f8mme folks fremtidige handlinger mere end deres tidligere fejl.", "de": "Wir sollten Menschen mehr nach ihren zuk\u00fcnftigen Handlungen als nach ihren fr\u00fcheren Fehlern beurteilen.", "es": "Deber\u00edamos juzgar a las personas por sus acciones futuras m\u00e1s que por sus errores pasados.", "pt": "Devemos julgar as pessoas mais pelas suas a\u00e7\u00f5es futuras do que pelos erros passados.", "ro": "Ar trebui s\u0103 judec\u0103m oamenii mai mult dup\u0103 ac\u021biunile viitoare dec\u00e2t dup\u0103 gre\u0219elile trecute.", "fr": "Nous devrions juger les gens davantage sur leurs actions futures que sur leurs erreurs pass\u00e9es.", "it": "\"Dovremmo giudicare le azioni future delle persone pi\u00f9 che gli errori passati.\"", "fi": "\"Meid\u00e4n pit\u00e4isi arvioida ihmisten tulevia tekoja enemm\u00e4n kuin menneit\u00e4 virheit\u00e4.\"", "nl": "\"We zouden de toekomstige acties van mensen meer moeten beoordelen dan hun verleden fouten.\"", "no": "\"Vi b\u00f8r vurdere folks fremtidige handlinger mer enn fortidige feil.\"", "sv": "\"Vi borde d\u00f6ma m\u00e4nniskors framtida handlingar mer \u00e4n deras f\u00f6rflutna misstag.\"", "pl": "\u201ePowinni\u015bmy ocenia\u0107 przysz\u0142e dzia\u0142ania ludzi bardziej ni\u017c ich przesz\u0142e b\u0142\u0119dy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“We should judge people’s future actions more than past mistakes.”';
UPDATE questions
SET translations = '{"en": "\u201cTherapy should be free, not a luxury service.\u201d", "da": "Terapi b\u00f8r v\u00e6re gratis, ikke en luksustjeneste.", "de": "Therapie sollte kostenlos sein, kein Luxusdienst.", "es": "La terapia deber\u00eda ser gratuita, no un servicio de lujo.", "pt": "A terapia devia ser gratuita, n\u00e3o um servi\u00e7o de luxo.", "ro": "Terapia ar trebui s\u0103 fie gratuit\u0103, nu un serviciu de lux.", "fr": "La th\u00e9rapie devrait \u00eatre gratuite, pas un service de luxe.", "it": "\"La terapia dovrebbe essere gratuita, non un servizio di lusso.\"", "fi": "\"Terapiapalveluiden tulisi olla ilmaisia, ei luksuspalveluja.\"", "nl": "\"Therapie zou gratis moeten zijn, geen luxe dienst.\"", "no": "\u00abTerapi b\u00f8r v\u00e6re gratis, ikke en luksustjeneste.\u00bb", "sv": "\"Terapi borde vara gratis, inte en lyxtj\u00e4nst.\"", "pl": "\u201eTerapia powinna by\u0107 darmowa, a nie luksusow\u0105 us\u0142ug\u0105.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Therapy should be free, not a luxury service.”';
UPDATE questions
SET translations = '{"en": "\u201cContent creators should be taxed like traditional workers.\u201d", "da": "Indholdsskabere b\u00f8r beskattes som traditionelle arbejdere.", "de": "Inhaltsersteller sollten wie traditionelle Arbeiter besteuert werden.", "es": "Los creadores de contenido deber\u00edan tributar como los trabajadores tradicionales.", "pt": "Os criadores de conte\u00fado deviam ser tributados como trabalhadores tradicionais.", "ro": "Creatorii de con\u021binut ar trebui impozita\u021bi ca lucr\u0103torii tradi\u021bionali.", "fr": "Les cr\u00e9ateurs de contenu devraient \u00eatre impos\u00e9s comme les travailleurs traditionnels.", "it": "\"I creatori di contenuti dovrebbero essere tassati come i lavoratori tradizionali.\"", "fi": "\"Sis\u00e4ll\u00f6ntuottajia tulisi verottaa kuten perinteisi\u00e4 ty\u00f6ntekij\u00f6it\u00e4.\"", "nl": "\"Contentmakers zouden belast moeten worden zoals traditionele werknemers.\"", "no": "\u00abInnholdsprodusenter b\u00f8r beskattes som tradisjonelle arbeidere.\u00bb", "sv": "\"Inneh\u00e5llsskapare b\u00f6r beskattas som traditionella arbetare.\"", "pl": "\u201eTw\u00f3rcy tre\u015bci powinni by\u0107 opodatkowani jak tradycyjni pracownicy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Content creators should be taxed like traditional workers.”';
UPDATE questions
SET translations = '{"en": "\u201cAI companionship (robots, chatbots) will be healthier relationships than many human ones.\u201d", "da": "AI-selskab (robotter, chatbots) vil v\u00e6re sundere relationer end mange menneskelige.", "de": "KI-Gesellschaft (Roboter, Chatbots) wird ges\u00fcndere Beziehungen haben als viele menschliche.", "es": "La compa\u00f1\u00eda de IA (robots, chatbots) ser\u00e1 m\u00e1s saludable que muchas relaciones humanas.", "pt": "A companhia da IA (rob\u00f4s, chatbots) ser\u00e1 mais saud\u00e1vel do que muitas rela\u00e7\u00f5es humanas.", "ro": "Compania oferit\u0103 de AI (robo\u021bi, chatbo\u021bi) va fi mai s\u0103n\u0103toas\u0103 dec\u00e2t multe rela\u021bii umane.", "fr": "La compagnie de", "it": "\"Le relazioni con i compagni AI (robot, chatbot) saranno pi\u00f9 sane di molte relazioni umane.\"", "fi": "\"AI-seurustelu (robotit, chatbotit) tulee olemaan terveempi\u00e4 suhteita kuin monet ihmisten v\u00e4liset.\"", "nl": "\"AI-vriendschap (robots, chatbots) zal gezondere relaties zijn dan veel menselijke.\"", "no": "\u00abAI-selskaper (roboter, chatboter) vil v\u00e6re sunnere relasjoner enn mange menneskelige.\u00bb", "sv": "\"AI-s\u00e4llskap (robotar, chattbotar) kommer att vara h\u00e4lsosammare relationer \u00e4n m\u00e5nga m\u00e4nskliga.\"", "pl": "\u201eTowarzystwo AI (roboty, chatboty) b\u0119dzie zdrowsze ni\u017c wiele relacji mi\u0119dzyludzkich.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“AI companionship (robots, chatbots) will be healthier relationships than many human ones.”';
UPDATE questions
SET translations = '{"en": "\u201cMemory is too flawed \u2014 we need to digitally archive lives.\u201d", "da": "Hukommelse er for fejlbeh\u00e6ftet \u2014 vi har brug for at arkivere liv digitalt.", "de": "Erinnerung ist zu fehlerhaft \u2013 wir m\u00fcssen Leben digital archivieren.", "es": "La memoria es demasiado defectuosa \u2014 necesitamos archivar las vidas digitalmente.", "pt": "A mem\u00f3ria \u00e9 demasiado fal\u00edvel \u2014 precisamos arquivar vidas digitalmente.", "ro": "Memoria este prea defectuoas\u0103 \u2014 trebuie s\u0103 arhiv\u0103m vie\u021bile digital.", "fr": "La m\u00e9moire est trop imparfaite \u2014 nous devons archiver les vies num\u00e9riquement.", "it": "\"La memoria \u00e8 troppo imperfetta \u2014 dobbiamo archiviare digitalmente le vite.\"", "fi": "\"Muisti on liian virheellinen \u2014 meid\u00e4n t\u00e4ytyy arkistoida el\u00e4m\u00e4t digitaalisesti.\"", "nl": "\"Geheugen is te gebrekkig \u2014 we moeten levens digitaal archiveren.\"", "no": "\"Minne er for feilaktig \u2014 vi m\u00e5 digitalt arkivere liv.\"", "sv": "\"Minne \u00e4r f\u00f6r bristf\u00e4lligt \u2014 vi beh\u00f6ver digitalt arkivera liv.\"", "pl": "\u201ePami\u0119\u0107 jest zbyt zawodna \u2014 musimy cyfrowo archiwizowa\u0107 \u017cycie.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Memory is too flawed — we need to digitally archive lives.”';
UPDATE questions
SET translations = '{"en": "\u201cHumans should stop having pets \u2014 it\u2019s an exploitative relationship.\u201d", "da": "Mennesker b\u00f8r stoppe med at have k\u00e6ledyr \u2014 det er et udnyttende forhold.", "de": "Menschen sollten aufh\u00f6ren, Haustiere zu halten \u2013 es ist eine ausbeuterische Beziehung.", "es": "Los humanos deber\u00edan dejar de tener mascotas \u2014 es una relaci\u00f3n de explotaci\u00f3n.", "pt": "Os humanos deviam deixar de ter animais de estima\u00e7\u00e3o \u2014 \u00e9 uma rela\u00e7\u00e3o explorat\u00f3ria.", "ro": "Oamenii ar trebui s\u0103 nu mai aib\u0103 animale de companie \u2014 este o rela\u021bie exploatatoare.", "fr": "Les humains devraient arr\u00eater d\u2019avoir des animaux de compagnie \u2014 c\u2019est une relation d\u2019exploitation.", "it": "\"Gli esseri umani dovrebbero smettere di avere animali domestici \u2014 \u00e8 una relazione sfruttatrice.\"", "fi": "\"Ihmisten pit\u00e4isi lopettaa lemmikkiel\u00e4inten pit\u00e4minen \u2014 se on hyv\u00e4ksik\u00e4ytt\u00f6suhde.\"", "nl": "\u201cMensen zouden moeten stoppen met het houden van huisdieren \u2014 het is een uitbuitende relatie.\u201d", "no": "\u201cMennesker b\u00f8r slutte \u00e5 ha kj\u00e6ledyr \u2014 det er et utnyttende forhold.\u201d", "sv": "\"M\u00e4nniskor borde sluta ha husdjur \u2014 det \u00e4r en utnyttjande relation.\"", "pl": "\u201eLudzie powinni przesta\u0107 mie\u0107 zwierz\u0119ta domowe \u2014 to jest relacja wyzyskuj\u0105ca.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Humans should stop having pets — it’s an exploitative relationship.”';

-- Category: Would You Rather Talks (75 questions)
UPDATE questions
SET translations = '{"en": "Would you rather have to tell your family every secret you have or hear all of theirs?", "da": "Ville du hellere fort\u00e6lle din familie alle dine hemmeligheder eller h\u00f8re alle deres?", "de": "W\u00fcrdest du lieber deiner Familie alle deine Geheimnisse erz\u00e4hlen oder alle ihre h\u00f6ren?", "es": "\u00bfPreferir\u00edas contarle a tu familia todos tus secretos o escuchar todos los suyos?", "pt": "Preferias contar \u00e0 tua fam\u00edlia todos os teus segredos ou ouvir todos os deles?", "ro": "Ai prefera s\u0103 le spui familiei toate secretele tale sau s\u0103 le auzi pe ale lor?", "fr": "Pr\u00e9f\u00e9rerais-tu dire \u00e0 ta famille tous tes secrets ou entendre tous les leurs ?", "it": "Preferiresti dover raccontare alla tua famiglia ogni segreto che hai o sentire tutti i loro?", "fi": "Haluaisitko mieluummin kertoa perheellesi kaikki salaisuutesi vai kuulla kaikki heid\u00e4n salaisuutensa?", "nl": "Zou je liever al je geheimen aan je familie moeten vertellen of al hun geheimen horen?", "no": "Ville du heller m\u00e5tte fortelle familien din hver hemmelighet du har, eller h\u00f8re alle deres?", "sv": "Skulle du hellre beh\u00f6va ber\u00e4tta f\u00f6r din familj alla hemligheter du har eller h\u00f6ra alla deras?", "pl": "Czy wola\u0142by\u015b powiedzie\u0107 swojej rodzinie wszystkie swoje sekrety, czy us\u0142ysze\u0107 wszystkie ich sekrety?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to tell your family every secret you have or hear all of theirs?';
UPDATE questions
SET translations = '{"en": "Would you rather have a pet dragon or a pet talking dog?", "da": "Ville du hellere have en k\u00e6ledragedrage eller en talende hund?", "de": "W\u00fcrdest du lieber einen Haustierdrachen oder einen sprechenden Hund haben?", "es": "\u00bfPreferir\u00edas tener un drag\u00f3n mascota o un perro que hable?", "pt": "Preferias ter um drag\u00e3o de estima\u00e7\u00e3o ou um c\u00e3o falante?", "ro": "Ai prefera s\u0103 ai un dragon de companie sau un c\u00e2ine vorbitor?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir un dragon de compagnie ou un chien qui parle ?", "it": "Preferiresti avere un drago domestico o un cane parlante?", "fi": "Haluaisitko mieluummin lemmikkilohik\u00e4\u00e4rmeen vai puhuvan koiran?", "nl": "Zou je liever een huisdraak hebben of een pratende hond?", "no": "Ville du heller hatt en kj\u00e6ledragon eller en kj\u00e6ledog som kan snakke?", "sv": "Skulle du hellre ha en husdjur-drake eller en pratande hund som husdjur?", "pl": "Czy wola\u0142by\u015b mie\u0107 smoka jako zwierz\u0119 domowe, czy gadaj\u0105cego psa?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have a pet dragon or a pet talking dog?';
UPDATE questions
SET translations = '{"en": "Would you rather be able to fly for one hour a day or be invisible for one hour a day?", "da": "Ville du hellere kunne flyve i en time om dagen eller v\u00e6re usynlig i en time om dagen?", "de": "W\u00fcrdest du lieber eine Stunde am Tag fliegen oder eine Stunde unsichtbar sein?", "es": "\u00bfPreferir\u00edas poder volar una hora al d\u00eda o ser invisible una hora al d\u00eda?", "pt": "Preferias poder voar uma hora por dia ou ser invis\u00edvel uma hora por dia?", "ro": "Ai prefera s\u0103 po\u021bi zbura o or\u0103 pe zi sau s\u0103 fii invizibil o or\u0103 pe zi?", "fr": "Pr\u00e9f\u00e9rerais-tu pouvoir voler une heure par jour ou \u00eatre invisible une heure par jour ?", "it": "Preferiresti poter volare per un''ora al giorno o essere invisibile per un''ora al giorno?", "fi": "Haluaisitko mieluummin pysty\u00e4 lent\u00e4m\u00e4\u00e4n tunnin p\u00e4iv\u00e4ss\u00e4 vai olla n\u00e4kym\u00e4t\u00f6n tunnin p\u00e4iv\u00e4ss\u00e4?", "nl": "Zou je liever \u00e9\u00e9n uur per dag kunnen vliegen of \u00e9\u00e9n uur per dag onzichtbaar zijn?", "no": "Ville du heller kunne fly i en time om dagen eller v\u00e6re usynlig i en time om dagen?", "sv": "Skulle du hellre kunna flyga i en timme om dagen eller vara osynlig i en timme om dagen?", "pl": "Czy wola\u0142by\u015b m\u00f3c lata\u0107 przez godzin\u0119 dziennie, czy by\u0107 niewidzialnym przez godzin\u0119 dziennie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be able to fly for one hour a day or be invisible for one hour a day?';
UPDATE questions
SET translations = '{"en": "Would you rather always wear pajamas or always wear fancy clothes?", "da": "Ville du hellere altid g\u00e5 i pyjamas eller altid g\u00e5 i fine t\u00f8j?", "de": "W\u00fcrdest du lieber immer im Pyjama oder immer in feiner Kleidung herumlaufen?", "es": "\u00bfPreferir\u00edas usar siempre pijama o siempre ropa elegante?", "pt": "Preferias usar sempre pijama ou sempre roupa elegante?", "ro": "Ai prefera s\u0103 por\u021bi mereu pijamale sau haine elegante?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours porter un pyjama ou toujours des v\u00eatements \u00e9l\u00e9gants ?", "it": "Preferiresti indossare sempre il pigiama o indossare sempre abiti eleganti?", "fi": "Haluaisitko mieluummin aina pukeutua pyjamiin vai aina hienoihin vaatteisiin?", "nl": "Zou je liever altijd pyjama''s dragen of altijd chique kleren?", "no": "Ville du heller alltid ha p\u00e5 deg pysjamas eller alltid ha p\u00e5 deg fine kl\u00e6r?", "sv": "Skulle du hellre alltid ha p\u00e5 dig pyjamas eller alltid ha p\u00e5 dig fina kl\u00e4der?", "pl": "Czy wola\u0142by\u015b zawsze nosi\u0107 pi\u017cam\u0119, czy zawsze nosi\u0107 eleganckie ubrania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always wear pajamas or always wear fancy clothes?';
UPDATE questions
SET translations = '{"en": "Would you rather spend a year saving for one big dream purchase or use that money for smaller fun things throughout the year?", "da": "Ville du hellere spare et \u00e5r til et stort dr\u00f8mmek\u00f8b eller bruge pengene p\u00e5 sm\u00e5 sjove ting hele \u00e5ret?", "de": "W\u00fcrdest du lieber ein Jahr lang f\u00fcr einen gro\u00dfen Traum sparen oder das Geld f\u00fcr kleine Dinge im Jahr ausgeben?", "es": "\u00bfPreferir\u00edas ahorrar durante un a\u00f1o para una gran compra o gastar ese dinero en cosas peque\u00f1as y divertidas durante el a\u00f1o?", "pt": "Preferias poupar um ano para uma grande compra ou gastar o dinheiro em pequenas divers\u00f5es durante o ano?", "ro": "Ai prefera s\u0103 economise\u0219ti un an pentru o mare dorin\u021b\u0103 sau s\u0103 cheltuie\u0219ti pe mici bucurii tot anul?", "fr": "Pr\u00e9f\u00e9rerais-tu \u00e9conomiser pendant un an pour un grand r\u00eave ou d\u00e9penser l\u2019argent pour de petits plaisirs toute l\u2019ann\u00e9e ?", "it": "Preferiresti passare un anno a risparmiare per un grande acquisto da sogno o usare quei soldi per piccole cose divertenti durante l''anno?", "fi": "Haluaisitko mieluummin s\u00e4\u00e4st\u00e4\u00e4 vuoden ajan yhden suuren unelmahankinnan vuoksi vai k\u00e4ytt\u00e4\u00e4 sen rahan pienempiin hauskoihin asioihin vuoden aikana?", "nl": "Zou je liever een jaar sparen voor \u00e9\u00e9n grote droomaankoop of dat geld gebruiken voor kleinere leuke dingen gedurende het jaar?", "no": "Ville du heller bruke et \u00e5r p\u00e5 \u00e5 spare til ett stort dr\u00f8mmekj\u00f8p, eller bruke de pengene p\u00e5 mindre morsomme ting gjennom \u00e5ret?", "sv": "Skulle du hellre spendera ett \u00e5r med att spara till ett stort dr\u00f6mink\u00f6p eller anv\u00e4nda de pengarna till mindre roliga saker under \u00e5ret?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 rok oszcz\u0119dzaj\u0105c na jeden du\u017cy wymarzony zakup, czy wyda\u0107 te pieni\u0105dze na mniejsze przyjemno\u015bci przez ca\u0142y rok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend a year saving for one big dream purchase or use that money for smaller fun things throughout the year?';
UPDATE questions
SET translations = '{"en": "Would you rather only eat breakfast food or only dinner food forever?", "da": "Ville du hellere kun spise morgenmadsmad eller kun aftensmad for evigt?", "de": "W\u00fcrdest du lieber nur Fr\u00fchst\u00fccksessen oder nur Abendessen f\u00fcr immer essen?", "es": "\u00bfPreferir\u00edas comer solo comida de desayuno o solo comida de cena para siempre?", "pt": "Preferias comer apenas comida de pequeno-almo\u00e7o ou apenas de jantar para sempre?", "ro": "Ai prefera s\u0103 m\u0103n\u00e2nci doar mic dejun sau doar cin\u0103 pentru totdeauna?", "fr": "Pr\u00e9f\u00e9rerais-tu ne manger que des plats de petit d\u00e9jeuner ou que des plats du d\u00eener pour toujours ?", "it": "Preferiresti mangiare solo cibo da colazione o solo cibo da cena per sempre?", "fi": "Haluaisitko sy\u00f6d\u00e4 vain aamiaisruokaa vai vain illallisruokaa ikuisesti?", "nl": "Zou je liever alleen ontbijtvoedsel of alleen diner voedsel voor altijd eten?", "no": "Ville du heller bare spise frokostmat eller bare middagmat for alltid?", "sv": "Skulle du hellre \u00e4ta frukostmat eller bara middagmat f\u00f6r alltid?", "pl": "Czy wola\u0142by\u015b je\u015b\u0107 tylko jedzenie na \u015bniadanie, czy tylko jedzenie na kolacj\u0119 na zawsze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather only eat breakfast food or only dinner food forever?';
UPDATE questions
SET translations = '{"en": "Would you rather time-travel to the past or to the future?", "da": "Ville du hellere rejse i tiden til fortiden eller til fremtiden?", "de": "W\u00fcrdest du lieber in die Vergangenheit oder in die Zukunft reisen?", "es": "\u00bfPreferir\u00edas viajar al pasado o al futuro?", "pt": "Preferias viajar no tempo para o passado ou para o futuro?", "ro": "Ai prefera s\u0103 c\u0103l\u0103tore\u0219ti \u00een trecut sau \u00een viitor?", "fr": "Pr\u00e9f\u00e9rerais-tu voyager dans le pass\u00e9 ou dans le futur ?", "it": "Preferiresti viaggiare nel tempo nel passato o nel futuro?", "fi": "Molempia vaihtoehtoja on vaikea valita, mutta haluaisitko mieluummin matkustaa ajassa menneisyyteen vai tulevaisuuteen?", "nl": "Zou je liever terug in de tijd reizen of naar de toekomst?", "no": "Ville du heller reise tilbake i tid eller til fremtiden?", "sv": "Skulle du hellre vilja resa tillbaka i tiden eller till framtiden?", "pl": "Czy wola\u0142by\u015b podr\u00f3\u017cowa\u0107 w czasie do przesz\u0142o\u015bci, czy do przysz\u0142o\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather time-travel to the past or to the future?';
UPDATE questions
SET translations = '{"en": "Would you rather have to tell jokes all day or listen to jokes all day?", "da": "Ville du hellere fort\u00e6lle vittigheder hele dagen eller h\u00f8re vittigheder hele dagen?", "de": "W\u00fcrdest du lieber den ganzen Tag Witze erz\u00e4hlen oder den ganzen Tag Witze h\u00f6ren?", "es": "\u00bfPreferir\u00edas contar chistes todo el d\u00eda o escuchar chistes todo el d\u00eda?", "pt": "Preferias contar piadas o dia todo ou ouvir piadas o dia todo?", "ro": "Ai prefera s\u0103 spui glume toat\u0103 ziua sau s\u0103 le ascul\u021bi toat\u0103 ziua?", "fr": "Pr\u00e9f\u00e9rerais-tu raconter des blagues toute la journ\u00e9e ou \u00e9couter des blagues toute la journ\u00e9e ?", "it": "Preferiresti dover raccontare barzellette tutto il giorno o ascoltare barzellette tutto il giorno?", "fi": "Kumpi olisi mieluummin: kertoa vitsej\u00e4 koko p\u00e4iv\u00e4n vai kuunnella vitsej\u00e4 koko p\u00e4iv\u00e4n?", "nl": "Zou je liever de hele dag grappen vertellen of de hele dag grappen luisteren?", "no": "Ville du heller m\u00e5tte fortelle vitser hele dagen eller h\u00f8re p\u00e5 vitser hele dagen?", "sv": "Skulle du hellre beh\u00f6va ber\u00e4tta sk\u00e4mt hela dagen eller lyssna p\u00e5 sk\u00e4mt hela dagen?", "pl": "Czy wola\u0142by\u015b opowiada\u0107 dowcipy przez ca\u0142y dzie\u0144, czy s\u0142ucha\u0107 dowcip\u00f3w przez ca\u0142y dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to tell jokes all day or listen to jokes all day?';
UPDATE questions
SET translations = '{"en": "Would you rather never run out of clean clothes or never run out of groceries?", "da": "Ville du hellere aldrig l\u00f8be t\u00f8r for rent t\u00f8j eller aldrig l\u00f8be t\u00f8r for madvarer?", "de": "W\u00fcrdest du lieber nie saubere Kleidung oder nie Lebensmittel ausgehen lassen?", "es": "\u00bfPreferir\u00edas no quedarte nunca sin ropa limpia o nunca sin comida?", "pt": "Preferias nunca ficar sem roupa limpa ou sem mantimentos?", "ro": "Ai prefera s\u0103 nu r\u0103m\u00e2i niciodat\u0103 f\u0103r\u0103 haine curate sau f\u0103r\u0103 provizii?", "fr": "Pr\u00e9f\u00e9rerais-tu ne jamais manquer de v\u00eatements propres ou ne jamais manquer de courses ?", "it": "Preferiresti non rimanere mai senza vestiti puliti o non rimanere mai senza generi alimentari?", "fi": "Haluaisitko mieluummin, ett\u00e4 puhtaat vaatteet eiv\u00e4t koskaan lopu vai ett\u00e4 ruoka ei koskaan lopu?", "nl": "Zou je liever nooit zonder schone kleren komen te zitten of nooit zonder boodschappen?", "no": "Ville du heller aldri g\u00e5 tom for rene kl\u00e6r eller aldri g\u00e5 tom for matvarer?", "sv": "Skulle du hellre aldrig f\u00e5 slut p\u00e5 rena kl\u00e4der eller aldrig f\u00e5 slut p\u00e5 matvaror?", "pl": "Czy wola\u0142by\u015b nigdy nie brakowa\u0107 czystych ubra\u0144, czy nigdy nie brakowa\u0107 jedzenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather never run out of clean clothes or never run out of groceries?';
UPDATE questions
SET translations = '{"en": "Would you rather never have to clean again or never have to do laundry again?", "da": "Ville du hellere aldrig g\u00f8re rent igen eller aldrig vaske t\u00f8j igen?", "de": "W\u00fcrdest du lieber nie wieder putzen oder nie wieder W\u00e4sche waschen?", "es": "\u00bfPreferir\u00edas no tener que limpiar nunca m\u00e1s o no tener que lavar la ropa nunca m\u00e1s?", "pt": "Preferias nunca mais limpar ou nunca mais lavar roupa?", "ro": "Ai prefera s\u0103 nu mai faci cur\u0103\u021benie niciodat\u0103 sau s\u0103 nu mai speli haine?", "fr": "Pr\u00e9f\u00e9rerais-tu ne plus jamais faire le m\u00e9nage ou ne plus jamais faire la lessive ?", "it": "Preferiresti non dover mai pi\u00f9 pulire o non dover mai pi\u00f9 fare il bucato?", "fi": "Haluaisitko mieluummin, ettet koskaan tarvitsisi siivota uudelleen vai ettet koskaan tarvitsisi pest\u00e4 pyykki\u00e4 uudelleen?", "nl": "Zou je liever nooit meer hoeven schoonmaken of nooit meer de was doen?", "no": "Ville du heller aldri m\u00e5tte rengj\u00f8re igjen eller aldri m\u00e5tte vaske kl\u00e6r igjen?", "sv": "Skulle du hellre slippa st\u00e4da helt eller slippa tv\u00e4tta kl\u00e4der helt?", "pl": "Czy wola\u0142by\u015b nigdy wi\u0119cej nie sprz\u0105ta\u0107, czy nigdy wi\u0119cej nie robi\u0107 prania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather never have to clean again or never have to do laundry again?';
UPDATE questions
SET translations = '{"en": "Would you rather be famouanos for cooking or famous for inventing something?", "da": "Ville du hellere v\u00e6re ber\u00f8mt for at lave mad eller for at opfinde noget?", "de": "W\u00e4rst du lieber ber\u00fchmt f\u00fcrs Kochen oder f\u00fcrs Erfinden?", "es": "\u00bfPreferir\u00edas ser famoso por cocinar o por inventar algo?", "pt": "Preferias ser famoso por cozinhar ou por inventar algo?", "ro": "Ai prefera s\u0103 fii faimos pentru g\u0103tit sau pentru inventat ceva?", "fr": "Pr\u00e9f\u00e9rerais-tu \u00eatre c\u00e9l\u00e8bre pour cuisiner ou pour inventer quelque chose ?", "it": "Preferiresti essere famoso per cucinare o famoso per aver inventato qualcosa?", "fi": "Haluaisitko olla kuuluisa ruoanlaitosta vai tunnettu keksij\u00e4n\u00e4?", "nl": "Zou je liever beroemd zijn om te koken of beroemd om iets uit te vinden?", "no": "Ville du heller v\u00e6rt kjent for \u00e5 lage mat eller kjent for \u00e5 oppfinne noe?", "sv": "Skulle du hellre vara k\u00e4nd f\u00f6r att laga mat eller k\u00e4nd f\u00f6r att uppfinna n\u00e5got?", "pl": "Czy wola\u0142by\u015b by\u0107 znany z gotowania, czy z wynalezienia czego\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be famouanos for cooking or famous for inventing something?';
UPDATE questions
SET translations = '{"en": "Would you rather live by the beach or in a cozy mountain cabin?", "da": "Ville du hellere bo ved stranden eller i en hyggelig bj\u00e6lkehytte i bjergene?", "de": "W\u00fcrdest du lieber am Strand oder in einer gem\u00fctlichen Bergh\u00fctte leben?", "es": "\u00bfPreferir\u00edas vivir en la playa o en una caba\u00f1a acogedora en la monta\u00f1a?", "pt": "Preferias viver na praia ou numa cabana acolhedora na montanha?", "ro": "Ai prefera s\u0103 tr\u0103ie\u0219ti la mare sau \u00eentr-o caban\u0103 de munte?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre \u00e0 la plage ou dans un chalet de montagne confortable ?", "it": "Preferiresti vivere vicino alla spiaggia o in una accogliente baita di montagna?", "fi": "El\u00e4isitk\u00f6 mieluummin rannalla vai mukavassa vuoristom\u00f6kiss\u00e4?", "nl": "Zou je liever aan het strand wonen of in een knusse berghut?", "no": "Ville du heller bodd ved stranden eller i en koselig hytte i fjellet?", "sv": "Skulle du hellre bo vid stranden eller i en mysig stuga i fj\u00e4llen?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 nad morzem, czy w przytulnej g\u00f3rskiej chatce?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live by the beach or in a cozy mountain cabin?';
UPDATE questions
SET translations = '{"en": "Would you rather have rainbow-colored hair or hair that glows in the dark?", "da": "Ville du hellere have regnbuefarvet h\u00e5r eller h\u00e5r, der lyser i m\u00f8rket?", "de": "H\u00e4ttest du lieber regenbogenfarbenes Haar oder Haar, das im Dunkeln leuchtet?", "es": "\u00bfPreferir\u00edas tener el cabello de colores del arco\u00edris o que brille en la oscuridad?", "pt": "Preferias ter cabelo com as cores do arco-\u00edris ou que brilhe no escuro?", "ro": "Ai prefera s\u0103 ai p\u0103r \u00een culorile curcubeului sau p\u0103r care lumineaz\u0103 \u00een \u00eentuneric?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir les cheveux arc-en-ciel ou les cheveux qui brillent dans le noir ?", "it": "Preferiresti avere i capelli color arcobaleno o capelli che brillano al buio?", "fi": "Haluaisitko mieluummin sateenkaaren v\u00e4riset hiukset vai hiukset, jotka hohtavat pime\u00e4ss\u00e4?", "nl": "Zou je liever regenboogkleurig haar hebben of haar dat in het donker gloeit?", "no": "Ville du heller ha regnbuefarget h\u00e5r eller h\u00e5r som lyser i m\u00f8rket?", "sv": "Skulle du hellre ha regnb\u00e5gsf\u00e4rgat h\u00e5r eller h\u00e5r som lyser i m\u00f6rkret?", "pl": "Czy wola\u0142by\u015b mie\u0107 w\u0142osy w kolorach t\u0119czy, czy w\u0142osy, kt\u00f3re \u015bwiec\u0105 w ciemno\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have rainbow-colored hair or hair that glows in the dark?';
UPDATE questions
SET translations = '{"en": "Would you rather spend a week with no internet or no TV?", "da": "Ville du hellere tilbringe en uge uden internet eller uden tv?", "de": "W\u00fcrdest du lieber eine Woche ohne Internet oder ohne Fernsehen verbringen?", "es": "\u00bfPreferir\u00edas pasar una semana sin internet o sin televisi\u00f3n?", "pt": "Preferias passar uma semana sem internet ou sem televis\u00e3o?", "ro": "Ai prefera s\u0103 petreci o s\u0103pt\u0103m\u00e2n\u0103 f\u0103r\u0103 internet sau f\u0103r\u0103 televizor?", "fr": "Pr\u00e9f\u00e9rerais-tu passer une semaine sans internet ou sans t\u00e9l\u00e9vision ?", "it": "Preferiresti trascorrere una settimana senza internet o senza TV?", "fi": "Olisitko mieluummin viikon ilman interneti\u00e4 vai ilman televisiota?", "nl": "Zou je liever een week zonder internet of zonder tv doorbrengen?", "no": "Ville du heller tilbringe en uke uten internett eller uten TV?", "sv": "Skulle du hellre spendera en vecka utan internet eller utan TV?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 tydzie\u0144 bez internetu czy bez telewizji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend a week with no internet or no TV?';
UPDATE questions
SET translations = '{"en": "Would you rather explore outer space or the deep ocean?", "da": "Ville du hellere udforske det ydre rum eller det dybe hav?", "de": "W\u00fcrdest du lieber das Weltall oder die Tiefsee erkunden?", "es": "\u00bfPreferir\u00edas explorar el espacio exterior o el oc\u00e9ano profundo?", "pt": "Preferias explorar o espa\u00e7o exterior ou o oceano profundo?", "ro": "Ai prefera s\u0103 explorezi spa\u021biul cosmic sau ad\u00e2ncurile oceanului?", "fr": "Pr\u00e9f\u00e9rerais-tu explorer l\u2019espace ou les profondeurs de l\u2019oc\u00e9an ?", "it": "Preferiresti esplorare lo spazio esterno o il profondo oceano?", "fi": "Haluaisitko mieluummin tutkia avaruuden syvyyksi\u00e4 vai syv\u00e4\u00e4 merta?", "nl": "Zou je liever de ruimte verkennen of de diepe oceaan?", "no": "Ville du heller utforske verdensrommet eller den dype havet?", "sv": "Skulle du hellre utforska yttre rymden eller den djupa oceanen?", "pl": "Czy wola\u0142by\u015b odkrywa\u0107 kosmos, czy g\u0142\u0119boki ocean?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather explore outer space or the deep ocean?';
UPDATE questions
SET translations = '{"en": "Would you rather eat ice cream every day or never eat dessert again?", "da": "Ville du hellere spise is hver dag eller aldrig spise dessert igen?", "de": "W\u00fcrdest du lieber jeden Tag Eis essen oder nie wieder Dessert essen?", "es": "\u00bfPreferir\u00edas comer helado todos los d\u00edas o no volver a comer postre nunca m\u00e1s?", "pt": "Preferias comer gelado todos os dias ou nunca mais comer sobremesa?", "ro": "Ai prefera s\u0103 m\u0103n\u00e2nci \u00eenghe\u021bat\u0103 zilnic sau s\u0103 nu mai m\u0103n\u00e2nci desert niciodat\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu manger de la glace tous les jours ou ne plus jamais manger de dessert ?", "it": "Preferiresti mangiare gelato ogni giorno o non mangiare mai pi\u00f9 dessert?", "fi": "Haluaisitko sy\u00f6d\u00e4 j\u00e4\u00e4tel\u00f6\u00e4 joka p\u00e4iv\u00e4 vai olla sy\u00f6m\u00e4tt\u00e4 j\u00e4lkiruokaa en\u00e4\u00e4 koskaan?", "nl": "Zou je liever elke dag ijs eten of nooit meer dessert eten?", "no": "Ville du heller spist iskrem hver dag eller aldri spist dessert igjen?", "sv": "Skulle du hellre \u00e4ta glass varje dag eller aldrig \u00e4ta efterr\u00e4tt igen?", "pl": "Czy wola\u0142by\u015b je\u015b\u0107 lody codziennie, czy nigdy wi\u0119cej nie je\u015b\u0107 deser\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather eat ice cream every day or never eat dessert again?';
UPDATE questions
SET translations = '{"en": "Would you rather be the world\u2019s funniest person or the world\u2019s best singer?", "da": "Ville du hellere v\u00e6re verdens sjoveste person eller verdens bedste sanger?", "de": "W\u00e4rst du lieber der lustigste Mensch der Welt oder der beste S\u00e4nger der Welt?", "es": "\u00bfPreferir\u00edas ser la persona m\u00e1s divertida del mundo o el mejor cantante del mundo?", "pt": "Preferias ser a pessoa mais engra\u00e7ada do mundo ou o melhor cantor do mundo?", "ro": "Ai prefera s\u0103 fii cel mai amuzant om din lume sau cel mai bun c\u00e2nt\u0103re\u021b?", "fr": "Pr\u00e9f\u00e9rerais-tu \u00eatre la personne la plus dr\u00f4le du monde ou le meilleur chanteur du monde ?", "it": "Preferiresti essere la persona pi\u00f9 divertente del mondo o il miglior cantante del mondo?", "fi": "Haluaisitko olla maailman hauskoin ihminen vai maailman paras laulaja?", "nl": "Zou je liever de grappigste persoon ter wereld zijn of de beste zanger ter wereld?", "no": "Ville du heller v\u00e6rt verdens morsomste person eller verdens beste sanger?", "sv": "Skulle du hellre vara v\u00e4rldens roligaste person eller v\u00e4rldens b\u00e4sta s\u00e5ngare?", "pl": "Czy wola\u0142by\u015b by\u0107 najs\u0142ynniejszym komikiem na \u015bwiecie, czy najlepszym piosenkarzem na \u015bwiecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be the world’s funniest person or the world’s best singer?';
UPDATE questions
SET translations = '{"en": "Would you rather have snow every day or sunshine every day?", "da": "Ville du hellere have sne hver dag eller solskin hver dag?", "de": "W\u00fcrdest du lieber jeden Tag Schnee oder jeden Tag Sonnenschein haben?", "es": "\u00bfPreferir\u00edas tener nieve todos los d\u00edas o sol todos los d\u00edas?", "pt": "Preferias ter neve todos os dias ou sol todos os dias?", "ro": "Ai prefera s\u0103 fie z\u0103pad\u0103 zilnic sau soare zilnic?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir de la neige tous les jours ou du soleil tous les jours ?", "it": "Preferiresti avere neve ogni giorno o sole ogni giorno?", "fi": "Haluaisitko mieluummin lunta joka p\u00e4iv\u00e4 vai auringonpaistetta joka p\u00e4iv\u00e4?", "nl": "Zou je liever elke dag sneeuw hebben of elke dag zonneschijn?", "no": "Vil du heller ha sn\u00f8 hver dag eller solskinn hver dag?", "sv": "Skulle du hellre vilja ha sn\u00f6 varje dag eller sol varje dag?", "pl": "Czy wola\u0142by\u015b mie\u0107 \u015bnieg ka\u017cdego dnia, czy s\u0142o\u0144ce ka\u017cdego dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have snow every day or sunshine every day?';
UPDATE questions
SET translations = '{"en": "Would you rather have your favorite meal on repeat forever or never repeat a meal again?", "da": "Ville du hellere spise din livret favorit hver dag eller aldrig spise det samme m\u00e5ltid to gange?", "de": "W\u00fcrdest du lieber dein Lieblingsessen immer wieder essen oder nie zweimal dasselbe?", "es": "\u00bfPreferir\u00edas comer tu comida favorita siempre o nunca repetir una comida?", "pt": "Preferias comer sempre a tua refei\u00e7\u00e3o favorita ou nunca repetir uma refei\u00e7\u00e3o?", "ro": "Ai prefera s\u0103 m\u0103n\u00e2nci mereu felul t\u0103u preferat sau s\u0103 nu repe\u021bi niciodat\u0103 o mas\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu manger ton plat pr\u00e9f\u00e9r\u00e9 en boucle ou ne jamais r\u00e9p\u00e9ter un repas ?", "it": "Preferiresti avere il tuo piatto preferito in ripetizione per sempre o non ripetere mai pi\u00f9 un pasto?", "fi": "Haluaisitko sy\u00f6d\u00e4 lempiruokaasi toistuvasti ikuisesti vai et koskaan toistaa ateriaa uudelleen?", "nl": "Zou je liever je favoriete maaltijd voor altijd herhalen of nooit meer een maaltijd herhalen?", "no": "Ville du heller hatt din favorittm\u00e5ltid i reprise for alltid, eller aldri gjentatt et m\u00e5ltid igjen?", "sv": "Skulle du hellre ha din favoritr\u00e4tt p\u00e5 repeat f\u00f6r alltid eller aldrig upprepa en m\u00e5ltid igen?", "pl": "Czy wola\u0142by\u015b je\u015b\u0107 swoje ulubione danie w k\u00f3\u0142ko przez wieczno\u015b\u0107, czy nigdy wi\u0119cej nie powt\u00f3rzy\u0107 \u017cadnego posi\u0142ku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have your favorite meal on repeat forever or never repeat a meal again?';
UPDATE questions
SET translations = '{"en": "Would you rather have to rhyme every sentence or start every sentence with \u201cYo!\u201d?", "da": "Ville du hellere rime i hver s\u00e6tning eller starte hver s\u00e6tning med \u201cYo!\u201d?", "de": "W\u00fcrdest du lieber in jedem Satz reimen oder jeden Satz mit \u201eYo!\u201c beginnen?", "es": "\u00bfPreferir\u00edas rimar en cada frase o empezar cada frase con \u201c\u00a1Yo!\u201d?", "pt": "Preferias rimar em todas as frases ou come\u00e7ar todas com \u201cYo!\u201d?", "ro": "Ai prefera s\u0103 rimezi \u00een fiecare propozi\u021bie sau s\u0103 \u00eencepi fiecare cu \u201cYo!\u201d?", "fr": "Pr\u00e9f\u00e9rerais-tu rimer dans chaque phrase ou commencer chaque phrase par \u00ab Yo! \u00bb ?", "it": "Preferiresti dover fare rima in ogni frase o iniziare ogni frase con \"Yo!\"?", "fi": "Haluaisitko mieluummin riimitell\u00e4 jokaisen lauseen vai aloittaa jokaisen lauseen sanalla \"Yo!\"?", "nl": "Zou je liever elke zin moeten rijmen of elke zin beginnen met \"Yo!\"?", "no": "Ville du heller m\u00e5tte rimme hver setning eller starte hver setning med \"Yo!\"?", "sv": "Skulle du hellre beh\u00f6va rimma varje mening eller b\u00f6rja varje mening med \"Yo!\"?", "pl": "Czy wola\u0142by\u015b rymowa\u0107 ka\u017cd\u0105 zdanie, czy zaczyna\u0107 ka\u017cde zdanie od \u201eYo!\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to rhyme every sentence or start every sentence with “Yo!”?';
UPDATE questions
SET translations = '{"en": "Would you rather live in a video game or in a storybook world?", "da": "Ville du hellere bo i et videospil eller i en eventyrbogsverden?", "de": "W\u00fcrdest du lieber in einem Videospiel oder in einer M\u00e4rchenwelt leben?", "es": "\u00bfPreferir\u00edas vivir en un videojuego o en un mundo de cuentos?", "pt": "Preferias viver num videojogo ou num mundo de contos de fadas?", "ro": "Ai prefera s\u0103 tr\u0103ie\u0219ti \u00eentr-un joc video sau \u00eentr-o lume de poveste?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre dans un jeu vid\u00e9o ou dans un monde de conte ?", "it": "Preferiresti vivere in un videogioco o in un mondo da libro di fiabe?", "fi": "Haluaisitko mieluummin el\u00e4\u00e4 videopeliss\u00e4 vai satukirjan maailmassa?", "nl": "Zou je liever in een videogame of in een verhaalwereld leven?", "no": "Ville du heller bo i et videospill eller i en eventyrverden?", "sv": "Skulle du hellre bo i ett videospel eller i en sagoboks v\u00e4rld?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 w grze wideo, czy w \u015bwiecie z ksi\u0105\u017cki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live in a video game or in a storybook world?';
UPDATE questions
SET translations = '{"en": "Would you rather teleport anywhere or pause time for ten minutes a day?", "da": "Ville du hellere kunne teleportere dig eller standse tiden i ti minutter om dagen?", "de": "W\u00fcrdest du lieber \u00fcberallhin teleportieren oder die Zeit jeden Tag zehn Minuten anhalten?", "es": "\u00bfPreferir\u00edas teletransportarte a cualquier lugar o pausar el tiempo diez minutos al d\u00eda?", "pt": "Preferias teletransportar-te para qualquer lugar ou parar o tempo por dez minutos por dia?", "ro": "Ai prefera s\u0103 te teleportezi oriunde sau s\u0103 opre\u0219ti timpul zece minute pe zi?", "fr": "Pr\u00e9f\u00e9rerais-tu pouvoir te t\u00e9l\u00e9porter ou arr\u00eater le temps dix minutes par jour ?", "it": "Preferiresti teletrasportarti ovunque o fermare il tempo per dieci minuti al giorno?", "fi": "Haluaisitko mieluummin teleportoida minne tahansa vai pys\u00e4ytt\u00e4\u00e4 ajan kymmeneksi minuutiksi p\u00e4iv\u00e4ss\u00e4?", "nl": "Zou je liever overal naartoe kunnen teleporteren of de tijd tien minuten per dag kunnen pauzeren?", "no": "Ville du heller teleportere hvor som helst eller pause tiden i ti minutter hver dag?", "sv": "Skulle du hellre kunna teleportera dig vart som helst eller pausa tiden i tio minuter om dagen?", "pl": "Czy wola\u0142by\u015b teleportowa\u0107 si\u0119 wsz\u0119dzie, czy zatrzyma\u0107 czas na dziesi\u0119\u0107 minut dziennie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather teleport anywhere or pause time for ten minutes a day?';
UPDATE questions
SET translations = '{"en": "Would you rather be able to talk to animals or control the weather?", "da": "Ville du hellere kunne tale med dyr eller styre vejret?", "de": "W\u00fcrdest du lieber mit Tieren sprechen oder das Wetter kontrollieren?", "es": "\u00bfPreferir\u00edas poder hablar con los animales o controlar el clima?", "pt": "Preferias falar com os animais ou controlar o clima?", "ro": "Ai prefera s\u0103 po\u021bi vorbi cu animalele sau s\u0103 controlezi vremea?", "fr": "Pr\u00e9f\u00e9rerais-tu parler aux animaux ou contr\u00f4ler la m\u00e9t\u00e9o ?", "it": "Preferiresti poter parlare con gli animali o controllare il tempo?", "fi": "Haluaisitko mieluummin pysty\u00e4 puhumaan el\u00e4imille vai hallitsemaan s\u00e4\u00e4t\u00e4?", "nl": "Zou je liever met dieren kunnen praten of het weer kunnen beheersen?", "no": "Ville du heller kunne snakke med dyr eller kontrollere v\u00e6ret?", "sv": "Skulle du hellre kunna prata med djur eller kontrollera v\u00e4dret?", "pl": "Czy wola\u0142by\u015b m\u00f3c rozmawia\u0107 ze zwierz\u0119tami, czy kontrolowa\u0107 pogod\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be able to talk to animals or control the weather?';
UPDATE questions
SET translations = '{"en": "Would you rather always wear mismatched shoes or wear your clothes backward for a year?", "da": "Ville du hellere altid have forskellige sko p\u00e5 eller have t\u00f8jet bagvendt i et \u00e5r?", "de": "W\u00fcrdest du lieber immer unterschiedliche Schuhe tragen oder deine Kleidung ein Jahr lang r\u00fcckw\u00e4rts?", "es": "\u00bfPreferir\u00edas usar zapatos diferentes siempre o la ropa al rev\u00e9s durante un a\u00f1o?", "pt": "Preferias usar sapatos trocados sempre ou a roupa ao contr\u00e1rio por um ano?", "ro": "Ai prefera s\u0103 por\u021bi mereu pantofi nepotrivi\u021bi sau hainele pe dos un an?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours porter des chaussures d\u00e9pareill\u00e9es ou tes v\u00eatements \u00e0 l\u2019envers pendant un an ?", "it": "Preferiresti indossare sempre scarpe non abbinate o portare i vestiti al contrario per un anno?", "fi": "Haluaisitko mieluummin aina k\u00e4ytt\u00e4\u00e4 eriparisia kenki\u00e4 vai pit\u00e4\u00e4 vaatteesi v\u00e4\u00e4rinp\u00e4in vuoden ajan?", "nl": "Zou je liever altijd mismatched schoenen dragen of je kleren een jaar lang achterstevoren dragen?", "no": "Ville du heller alltid ha p\u00e5 deg sko som ikke passer sammen, eller ha kl\u00e6rne dine bak frem i ett \u00e5r?", "sv": "Skulle du hellre alltid ha p\u00e5 dig olika skor eller ha dina kl\u00e4der bak och fram i ett \u00e5r?", "pl": "Czy wola\u0142by\u015b zawsze nosi\u0107 niedopasowane buty, czy nosi\u0107 ubrania na lew\u0105 stron\u0119 przez rok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always wear mismatched shoes or wear your clothes backward for a year?';
UPDATE questions
SET translations = '{"en": "Would you rather have to sing everything you say or dance everywhere you go?", "da": "Ville du hellere synge alt, hvad du siger, eller danse overalt, hvor du g\u00e5r?", "de": "W\u00fcrdest du lieber alles singen, was du sagst, oder \u00fcberall tanzen, wo du hingehst?", "es": "\u00bfPreferir\u00edas cantar todo lo que dices o bailar en todos lados a donde vayas?", "pt": "Preferias cantar tudo o que dizes ou dan\u00e7ar por onde fores?", "ro": "Ai prefera s\u0103 c\u00e2n\u021bi tot ce spui sau s\u0103 dansezi peste tot unde mergi?", "fr": "Pr\u00e9f\u00e9rerais-tu chanter tout ce que tu dis ou danser partout o\u00f9 tu vas ?", "it": "Preferiresti dover cantare tutto ci\u00f2 che dici o ballare ovunque tu vada?", "fi": "Haluaisitko laulaa kaiken, mit\u00e4 sanot, vai tanssia joka paikassa, mihin menet?", "nl": "Zou je liever alles wat je zegt moeten zingen of overal waar je gaat moeten dansen?", "no": "Ville du heller m\u00e5tte synge alt du sier eller danse overalt du g\u00e5r?", "sv": "Skulle du hellre beh\u00f6va sjunga allt du s\u00e4ger eller dansa \u00f6verallt du g\u00e5r?", "pl": "Czy wola\u0142by\u015b \u015bpiewa\u0107 wszystko, co m\u00f3wisz, czy ta\u0144czy\u0107 wsz\u0119dzie, gdzie idziesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to sing everything you say or dance everywhere you go?';