UPDATE questions
SET translations = '{"en": "What\u2019s a small token from me that would make you smile every time you saw it?", "da": "Hvilken lille ting fra mig ville f\u00e5 dig til at smile hver gang du s\u00e5 den?", "de": "Welches kleine Andenken von mir w\u00fcrde dich jedes Mal zum L\u00e4cheln bringen, wenn du es siehst?", "es": "\u00bfQu\u00e9 peque\u00f1o detalle m\u00edo te har\u00eda sonre\u00edr cada vez que lo vieras?", "pt": "Que pequeno gesto meu te faria sorrir sempre que o visses?", "ro": "Ce mic simbol de la mine te-ar face s\u0103 z\u00e2mbe\u0219ti de fiecare dat\u0103 c\u00e2nd l-ai vedea?", "fr": "Quel petit souvenir de moi te ferait sourire chaque fois que tu le verrais ?", "it": "Qual \u00e8 un piccolo regalo da parte mia che ti farebbe sorridere ogni volta che lo vedessi?", "fi": "Mik\u00e4 olisi pieni muistoesine minulta, joka saisi sinut hymyilem\u00e4\u00e4n joka kerta, kun n\u00e4kisit sen?", "nl": "Wat is een klein aandenken van mij dat je elke keer zou laten glimlachen als je het zag?", "no": "Hva er en liten gave fra meg som ville f\u00e5tt deg til \u00e5 smile hver gang du s\u00e5 den?", "sv": "Vad \u00e4r en liten g\u00e5va fr\u00e5n mig som skulle f\u00e5 dig att le varje g\u00e5ng du s\u00e5g den?", "pl": "Jaki ma\u0142y upominek ode mnie sprawi\u0142by, \u017ce za ka\u017cdym razem, gdy na niego spojrzysz, u\u015bmiechniesz si\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s a small token from me that would make you smile every time you saw it?';
UPDATE questions
SET translations = '{"en": "Do you think people misunderstand what it means to have \u201cgifts\u201d as a love language? What does it actually mean to you?", "da": "Tror du, folk misforst\u00e5r, hvad det betyder at have \u201cgaver\u201d som k\u00e6rlighedssprog? Hvad betyder det egentlig for dig?", "de": "Denkst du, dass Menschen missverstehen, was es bedeutet, \u201eGeschenke\u201c als Liebessprache zu haben? Was bedeutet es wirklich f\u00fcr dich?", "es": "\u00bfCrees que la gente malinterpreta lo que significa tener los \u201cregalos\u201d como lenguaje del amor? \u00bfQu\u00e9 significa realmente para ti?", "pt": "Achas que as pessoas interpretam mal o que significa ter \u201cpresentes\u201d como linguagem do amor? O que isso realmente significa para ti?", "ro": "Crezi c\u0103 oamenii \u00een\u021beleg gre\u0219it ce \u00eenseamn\u0103 s\u0103 ai \u201ecadouri\u201d ca limbaj al iubirii? Ce \u00eenseamn\u0103 asta cu adev\u0103rat pentru tine?", "fr": "Penses-tu que les gens comprennent mal ce que cela signifie d\u2019avoir les \u00ab cadeaux \u00bb comme langage de l\u2019amour ? Qu\u2019est-ce que cela signifie vraiment pour toi ?", "it": "Pensi che le persone fraintendano cosa significhi avere i \"regali\" come linguaggio dell''amore? Cosa significa realmente per te?", "fi": "Mietitk\u00f6, ett\u00e4 ihmiset ymm\u00e4rt\u00e4v\u00e4t v\u00e4\u00e4rin, mit\u00e4 tarkoittaa, ett\u00e4 \"lahjat\" ovat rakkauden kieli? Mit\u00e4 se oikeastaan tarkoittaa sinulle?", "nl": "Denk je dat mensen verkeerd begrijpen wat het betekent om \"gaven\" als liefdestaal te hebben? Wat betekent het eigenlijk voor jou?", "no": "Tror du folk misforst\u00e5r hva det betyr \u00e5 ha \"gaver\" som kj\u00e6rlighetsspr\u00e5k? Hva betyr det egentlig for deg?", "sv": "Tycker du att folk missf\u00f6rst\u00e5r vad det inneb\u00e4r att ha \"g\u00e5vor\" som k\u00e4rleksspr\u00e5k? Vad betyder det egentligen f\u00f6r dig?", "pl": "Czy uwa\u017casz, \u017ce ludzie \u017ale rozumiej\u0105, co oznacza posiadanie \u201edar\u00f3w\u201d jako j\u0119zyka mi\u0142o\u015bci? Co to dla Ciebie w\u0142a\u015bciwie oznacza?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you think people misunderstand what it means to have “gifts” as a love language? What does it actually mean to you?';
UPDATE questions
SET translations = '{"en": "What makes a gift feel shallow to you \u2014 and what makes it feel thoughtful and genuine?", "da": "Hvad f\u00e5r en gave til at f\u00f8les overfladisk for dig \u2013 og hvad f\u00e5r den til at f\u00f8les bet\u00e6nksom og \u00e6gte?", "de": "Was l\u00e4sst ein Geschenk f\u00fcr dich oberfl\u00e4chlich wirken \u2013 und was l\u00e4sst es durchdacht und echt erscheinen?", "es": "\u00bfQu\u00e9 hace que un regalo se sienta superficial para ti \u2014 y qu\u00e9 lo hace considerado y genuino?", "pt": "O que faz um presente parecer superficial para ti \u2014 e o que o torna atencioso e genu\u00edno?", "ro": "Ce face ca un cadou s\u0103 par\u0103 superficial pentru tine \u2014 \u0219i ce \u00eel face atent \u0219i sincer?", "fr": "Qu\u2019est-ce qui fait qu\u2019un cadeau te semble superficiel \u2014 et qu\u2019est-ce qui le rend attentionn\u00e9 et sinc\u00e8re ?", "it": "Cosa rende un regalo superficiale per te \u2014 e cosa lo rende invece pensato e genuino?", "fi": "Mik\u00e4 tekee lahjasta mielest\u00e4si pinnallisen \u2014 ja mik\u00e4 tekee siit\u00e4 ajatuksellisen ja aito?", "nl": "Wat maakt een cadeau voor jou oppervlakkig \u2014 en wat maakt het doordacht en oprecht?", "no": "Hva f\u00e5r en gave til \u00e5 f\u00f8les overfladisk for deg \u2014 og hva gj\u00f8r at den f\u00f8les gjennomtenkt og ekte?", "sv": "Vad f\u00e5r en g\u00e5va att k\u00e4nnas ytlig f\u00f6r dig \u2014 och vad f\u00e5r den att k\u00e4nnas omt\u00e4nksam och \u00e4kta?", "pl": "Co sprawia, \u017ce prezent wydaje si\u0119 p\u0142ytki, a co sprawia, \u017ce jest przemy\u015blany i szczery?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What makes a gift feel shallow to you — and what makes it feel thoughtful and genuine?';
UPDATE questions
SET translations = '{"en": "Do you prefer gifts that are practical or sentimental?", "da": "Foretr\u00e6kker du gaver, der er praktiske eller sentimentale?", "de": "Bevorzugst du Geschenke, die praktisch oder sentimental sind?", "es": "\u00bfPrefieres regalos que sean pr\u00e1cticos o sentimentales?", "pt": "Preferes presentes pr\u00e1ticos ou sentimentais?", "ro": "Preferi cadouri practice sau sentimentale?", "fr": "Pr\u00e9f\u00e8res-tu les cadeaux pratiques ou sentimentaux ?", "it": "Preferisci regali che siano pratici o sentimentali?", "fi": "Pid\u00e4tk\u00f6 enemm\u00e4n k\u00e4yt\u00e4nn\u00f6llisist\u00e4 vai tunteellisista lahjoista?", "nl": "Geef je de voorkeur aan praktische of sentimentele cadeaus?", "no": "Foretrekker du gaver som er praktiske eller sentimentale?", "sv": "F\u00f6redrar du presenter som \u00e4r praktiska eller sentimentala?", "pl": "Czy wolisz prezenty praktyczne czy sentymentalne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you prefer gifts that are practical or sentimental?';
UPDATE questions
SET translations = '{"en": "How do you feel when I remember small details about what you like?", "da": "Hvordan har du det, n\u00e5r jeg husker sm\u00e5 detaljer om, hvad du kan lide?", "de": "Wie f\u00fchlst du dich, wenn ich mich an kleine Details erinnere, die du magst?", "es": "\u00bfC\u00f3mo te sientes cuando recuerdo peque\u00f1os detalles sobre lo que te gusta?", "pt": "Como te sentes quando eu me lembro de pequenos detalhes sobre o que gostas?", "ro": "Cum te sim\u021bi c\u00e2nd \u00eemi amintesc mici detalii despre ce \u00ee\u021bi place?", "fr": "Que ressens-tu quand je me souviens des petits d\u00e9tails de ce que tu aimes ?", "it": "Come ti senti quando ricordo piccoli dettagli su ci\u00f2 che ti piace?", "fi": "Milt\u00e4 sinusta tuntuu, kun muistan pieni\u00e4 yksityiskohtia siit\u00e4, mist\u00e4 pid\u00e4t?", "nl": "Hoe voel je je als ik kleine details herinner over wat je leuk vindt?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg husker sm\u00e5 detaljer om hva du liker?", "sv": "Hur k\u00e4nner du dig n\u00e4r jag kommer ih\u00e5g sm\u00e5 detaljer om vad du gillar?", "pl": "Jak si\u0119 czujesz, gdy pami\u0119tam o ma\u0142ych szczeg\u00f3\u0142ach dotycz\u0105cych tego, co lubisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I remember small details about what you like?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing I could give you that has no price tag but huge meaning?", "da": "Hvad er \u00e9n ting, jeg kunne give dig, som ikke har en prisseddel, men enorm betydning?", "de": "Was ist eine Sache, die ich dir geben k\u00f6nnte, die keinen Preis hat, aber gro\u00dfe Bedeutung?", "es": "\u00bfQu\u00e9 podr\u00eda darte que no tenga precio pero signifique mucho?", "pt": "O que eu poderia dar-te que n\u00e3o tivesse pre\u00e7o mas tivesse um enorme significado?", "ro": "Ce \u021bi-a\u0219 putea oferi care nu are pre\u021b, dar are o mare \u00eensemn\u0103tate?", "fr": "Quelle chose pourrais-je t\u2019offrir qui n\u2019a pas de prix mais une grande signification ?", "it": "Qual \u00e8 una cosa che potrei darti che non ha un prezzo ma ha un grande significato?", "fi": "Mik\u00e4 on yksi asia, jonka voisin antaa sinulle, jolla ei ole hintalappua mutta valtava merkitys?", "nl": "Wat is \u00e9\u00e9n ding dat ik je zou kunnen geven dat geen prijs heeft, maar enorme betekenis heeft?", "no": "Hva er \u00e9n ting jeg kunne gi deg som ikke har prislapp, men stor betydning?", "sv": "Vad \u00e4r en sak jag skulle kunna ge dig som inte har n\u00e5got prislapp men stor betydelse?", "pl": "Co\u015b, co m\u00f3g\u0142bym ci da\u0107, co nie ma ceny, ale ma ogromne znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one thing I could give you that has no price tag but huge meaning?';
UPDATE questions
SET translations = '{"en": "What\u2019s something physical that instantly reminds you of our love?", "da": "Hvad er noget fysisk, der straks minder dig om vores k\u00e6rlighed?", "de": "Was ist etwas Physisches, das dich sofort an unsere Liebe erinnert?", "es": "\u00bfQu\u00e9 objeto f\u00edsico te recuerda instant\u00e1neamente a nuestro amor?", "pt": "Que objeto f\u00edsico te lembra instantaneamente do nosso amor?", "ro": "Ce obiect fizic \u00ee\u021bi aminte\u0219te imediat de dragostea noastr\u0103?", "fr": "Quel objet physique te rappelle instantan\u00e9ment notre amour ?", "it": "Qualcosa di fisico che ti ricorda immediatamente il nostro amore?", "fi": "Mik\u00e4 on jokin fyysinen asia, joka heti tuo mieleesi rakkautemme?", "nl": "Wat is iets fysieks dat je meteen aan onze liefde doet denken?", "no": "Hva er noe fysisk som umiddelbart minner deg om v\u00e5r kj\u00e6rlighet?", "sv": "Vad \u00e4r n\u00e5got fysiskt som genast p\u00e5minner dig om v\u00e5r k\u00e4rlek?", "pl": "Co\u015b fizycznego, co od razu przypomina ci o naszej mi\u0142o\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something physical that instantly reminds you of our love?';
UPDATE questions
SET translations = '{"en": "Do you think gifts should always be a surprise, or is it okay to say what you want and make it easy for each other?", "da": "Tror du, at gaver altid skal v\u00e6re en overraskelse, eller er det okay at sige, hvad man \u00f8nsker, og g\u00f8re det nemt for hinanden?", "de": "Denkst du, Geschenke sollten immer eine \u00dcberraschung sein, oder ist es in Ordnung zu sagen, was man will, um es einander leichter zu machen?", "es": "\u00bfCrees que los regalos siempre deben ser una sorpresa, o est\u00e1 bien decir lo que uno quiere y hacerlo f\u00e1cil para ambos?", "pt": "Achas que os presentes devem ser sempre uma surpresa, ou \u00e9 aceit\u00e1vel dizer o que se quer e facilitar um ao outro?", "ro": "Crezi c\u0103 darurile ar trebui s\u0103 fie mereu o surpriz\u0103, sau e \u00een regul\u0103 s\u0103 spui ce \u00ee\u021bi dore\u0219ti \u0219i s\u0103 fie mai simplu pentru am\u00e2ndoi?", "fr": "Penses-tu que les cadeaux devraient toujours \u00eatre une surprise, ou est-il acceptable de dire ce que l\u2019on veut pour se faciliter les choses ?", "it": "Pensi che i regali debbano sempre essere una sorpresa, o va bene dire cosa si desidera e facilitare le cose a vicenda?", "fi": "Mietitk\u00f6, ett\u00e4 lahjojen pit\u00e4isi aina olla yll\u00e4tyksi\u00e4, vai onko ihan ok sanoa, mit\u00e4 haluaa ja helpottaa toisten el\u00e4m\u00e4\u00e4?", "nl": "Denk je dat cadeaus altijd een verrassing moeten zijn, of is het ok\u00e9 om te zeggen wat je wilt en het elkaar gemakkelijk te maken?", "no": "Tror du gaver alltid b\u00f8r v\u00e6re en overraskelse, eller er det greit \u00e5 si hva man \u00f8nsker og gj\u00f8re det enklere for hverandre?", "sv": "Tycker du att presenter alltid ska vara en \u00f6verraskning, eller \u00e4r det okej att s\u00e4ga vad man vill ha och g\u00f6ra det l\u00e4ttare f\u00f6r varandra?", "pl": "Czy uwa\u017casz, \u017ce prezenty powinny zawsze by\u0107 niespodziank\u0105, czy mo\u017ce warto powiedzie\u0107, czego si\u0119 chce, aby u\u0142atwi\u0107 sobie nawzajem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you think gifts should always be a surprise, or is it okay to say what you want and make it easy for each other?';
UPDATE questions
SET translations = '{"en": "When\u2019s the last time you felt surprised \u2014 in a good way \u2014 by me?", "da": "Hvorn\u00e5r var sidste gang, du blev overrasket \u2013 p\u00e5 en god m\u00e5de \u2013 af mig?", "de": "Wann war das letzte Mal, dass du \u2013 auf gute Weise \u2013 von mir \u00fcberrascht wurdest?", "es": "\u00bfCu\u00e1ndo fue la \u00faltima vez que te sorprend\u00ed \u2014 de una buena manera?", "pt": "Quando foi a \u00faltima vez que te surpreendi \u2014 de uma forma boa?", "ro": "C\u00e2nd a fost ultima dat\u0103 c\u00e2nd te-am surprins \u2014 \u00eentr-un mod pl\u0103cut?", "fr": "Quand as-tu \u00e9t\u00e9 surpris(e) pour la derni\u00e8re fois \u2014 d\u2019une bonne mani\u00e8re \u2014 par moi ?", "it": "Quando \u00e8 stata l''ultima volta che ti sei sentito sorpreso \u2014 in modo positivo \u2014 da me?", "fi": "Milloin viimeksi tunsit itsesi yll\u00e4tetyksi \u2014 hyv\u00e4ll\u00e4 tavalla \u2014 minun ansiostani?", "nl": "Wanneer was de laatste keer dat je op een goede manier door mij verrast was?", "no": "N\u00e5r var siste gang du f\u00f8lte deg overrasket \u2014 p\u00e5 en god m\u00e5te \u2014 av meg?", "sv": "N\u00e4r var senaste g\u00e5ngen du k\u00e4nde dig \u00f6verraskad \u2014 p\u00e5 ett bra s\u00e4tt \u2014 av mig?", "pl": "Kiedy ostatni raz poczu\u0142e\u015b si\u0119 zaskoczony \u2014 w pozytywny spos\u00f3b \u2014 przeze mnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When’s the last time you felt surprised — in a good way — by me?';
UPDATE questions
SET translations = '{"en": "Do you see touch more as a way to show love, to feel loved, or both?", "da": "Ser du ber\u00f8ring mere som en m\u00e5de at vise k\u00e6rlighed p\u00e5, at f\u00f8le sig elsket \u2013 eller begge dele?", "de": "Siehst du Ber\u00fchrung eher als eine Art, Liebe zu zeigen, Liebe zu f\u00fchlen \u2013 oder beides?", "es": "\u00bfVes el contacto f\u00edsico m\u00e1s como una forma de mostrar amor, de sentirte amado/a, o ambas cosas?", "pt": "V\u00eas o toque mais como uma forma de mostrar amor, de te sentires amado(a), ou ambos?", "ro": "Vezi atingerea mai mult ca o modalitate de a ar\u0103ta iubire, de a te sim\u021bi iubit(\u0103) sau ambele?", "fr": "Vois-tu le contact physique plut\u00f4t comme une mani\u00e8re de montrer l\u2019amour, de te sentir aim\u00e9(e), ou les deux ?", "it": "Vedi il contatto fisico pi\u00f9 come un modo per mostrare amore, per sentirsi amati, o entrambi?", "fi": "N\u00e4etk\u00f6 kosketuksen enemm\u00e4n tapana osoittaa rakkautta, tuntea itsesi rakastetuksi vai molempina?", "nl": "Zie je aanraking meer als een manier om liefde te tonen, om je geliefd te voelen, of beide?", "no": "Ser du ber\u00f8ring mer som en m\u00e5te \u00e5 vise kj\u00e6rlighet p\u00e5, \u00e5 f\u00f8le seg elsket, eller begge deler?", "sv": "Ser du ber\u00f6ring mer som ett s\u00e4tt att visa k\u00e4rlek, att k\u00e4nna sig \u00e4lskad, eller b\u00e5da?", "pl": "Czy postrzegasz dotyk bardziej jako spos\u00f3b na okazanie mi\u0142o\u015bci, poczucie si\u0119 kochanym, czy mo\u017ce jedno i drugie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you see touch more as a way to show love, to feel loved, or both?';
UPDATE questions
SET translations = '{"en": "How important is physical closeness to you in everyday life?", "da": "Hvor vigtigt er fysisk n\u00e6rhed for dig i hverdagen?", "de": "Wie wichtig ist k\u00f6rperliche N\u00e4he f\u00fcr dich im Alltag?", "es": "\u00bfQu\u00e9 tan importante es la cercan\u00eda f\u00edsica para ti en la vida cotidiana?", "pt": "Qu\u00e3o importante \u00e9 a proximidade f\u00edsica para ti no dia a dia?", "ro": "C\u00e2t de important\u0103 este apropierea fizic\u0103 pentru tine \u00een via\u021ba de zi cu zi?", "fr": "Quelle importance a la proximit\u00e9 physique pour toi au quotidien ?", "it": "Quanto \u00e8 importante per te la vicinanza fisica nella vita quotidiana?", "fi": "Kuinka t\u00e4rke\u00e4\u00e4 fyysinen l\u00e4heisyys on sinulle arjessa?", "nl": "Hoe belangrijk is fysieke nabijheid voor jou in het dagelijks leven?", "no": "Hvor viktig er fysisk n\u00e6rhet for deg i hverdagen?", "sv": "Hur viktigt \u00e4r fysisk n\u00e4rhet f\u00f6r dig i vardagen?", "pl": "Jak wa\u017cna jest dla Ciebie blisko\u015b\u0107 fizyczna w codziennym \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How important is physical closeness to you in everyday life?';
UPDATE questions
SET translations = '{"en": "Did you grow up in a family that showed affection easily, or was touch more private or rare? How do you think that shaped you?", "da": "Voksede du op i en familie, der viste k\u00e6rlighed let, eller var ber\u00f8ring mere privat eller sj\u00e6lden? Hvordan tror du, det har formet dig?", "de": "Bist du in einer Familie aufgewachsen, die Zuneigung leicht zeigte, oder war Ber\u00fchrung privater oder seltener? Wie glaubst du, hat dich das gepr\u00e4gt?", "es": "\u00bfCreciste en una familia que mostraba afecto f\u00e1cilmente, o donde el contacto era m\u00e1s privado o raro? \u00bfC\u00f3mo crees que eso te form\u00f3?", "pt": "Cresceste numa fam\u00edlia que mostrava afeto facilmente, ou onde o toque era mais privado ou raro? Como achas que isso te moldou?", "ro": "Ai crescut \u00eentr-o familie care \u00ee\u0219i ar\u0103ta u\u0219or afec\u021biunea, sau atingerea era mai privat\u0103 ori rar\u0103? Cum crezi c\u0103 te-a influen\u021bat asta?", "fr": "As-tu grandi dans une famille qui montrait facilement de l\u2019affection, ou o\u00f9 le contact \u00e9tait plus priv\u00e9 ou rare ? Comment penses-tu que cela t\u2019a fa\u00e7onn\u00e9(e) ?", "it": "Sei cresciuto in una famiglia che mostrava affetto facilmente, o il contatto fisico era pi\u00f9 privato o raro? Come pensi che questo ti abbia influenzato?", "fi": "Kasvoitko perheess\u00e4, jossa osoitettiin hellyytt\u00e4 helposti, vai oliko kosketus enemm\u00e4n yksityist\u00e4 tai harvinaista? Miten luulet sen muovanneen sinua?", "nl": "Ben je opgegroeid in een gezin dat gemakkelijk genegenheid toonde, of was aanraking meer priv\u00e9 of zeldzaam? Hoe denk je dat dat jou gevormd heeft?", "no": "Vokste du opp i en familie som viste kj\u00e6rlighet lett, eller var ber\u00f8ring mer privat eller sjelden? Hvordan tror du det har formet deg?", "sv": "V\u00e4xte du upp i en familj som visade k\u00e4rlek l\u00e4tt, eller var ber\u00f6ring mer privat eller s\u00e4llsynt? Hur tror du att det formade dig?", "pl": "Czy dorasta\u0142e\u015b w rodzinie, kt\u00f3ra \u0142atwo okazywa\u0142a uczucia, czy mo\u017ce dotyk by\u0142 bardziej prywatny lub rzadki? Jak my\u015blisz, jak to wp\u0142yn\u0119\u0142o na Ciebie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Did you grow up in a family that showed affection easily, or was touch more private or rare? How do you think that shaped you?';
UPDATE questions
SET translations = '{"en": "How do you like to be comforted physically when you\u2019re upset?", "da": "Hvordan kan jeg bedst tr\u00f8ste dig fysisk, n\u00e5r du er ked af det?", "de": "Wie kann ich dich k\u00f6rperlich am besten tr\u00f6sten, wenn du traurig bist?", "es": "\u00bfC\u00f3mo te gusta que te consuele f\u00edsicamente cuando est\u00e1s triste?", "pt": "Como posso confortar-te fisicamente quando est\u00e1s triste?", "ro": "Cum pot s\u0103 te alin fizic c\u00e2nd e\u0219ti sup\u0103rat(\u0103)?", "fr": "Comment puis-je te r\u00e9conforter physiquement quand tu es triste ?", "it": "Come ti piace essere confortato fisicamente quando sei gi\u00f9 di morale?", "fi": "Miten tykk\u00e4\u00e4t, ett\u00e4 sinua lohdutetaan fyysisesti, kun olet surullinen?", "nl": "Hoe word je het liefst fysiek getroost als je van streek bent?", "no": "Hvordan liker du \u00e5 bli tr\u00f8stet fysisk n\u00e5r du er oppr\u00f8rt?", "sv": "Hur gillar du att bli tr\u00f6stad fysiskt n\u00e4r du \u00e4r uppr\u00f6rd?", "pl": "Jak lubisz by\u0107 pocieszany fizycznie, gdy jeste\u015b zdenerwowany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like to be comforted physically when you’re upset?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite way for me to hold or hug you?", "da": "Hvad er din yndlingsm\u00e5de for mig at holde eller kramme dig p\u00e5?", "de": "Was ist deine Lieblingsart, wie ich dich halte oder umarme?", "es": "\u00bfCu\u00e1l es tu forma favorita de que te abrace o te sostenga?", "pt": "Qual \u00e9 a tua maneira favorita de eu te abra\u00e7ar ou segurar?", "ro": "Care este modul t\u0103u preferat de a te \u021bine sau \u00eembr\u0103\u021bi\u0219a?", "fr": "Quelle est ta mani\u00e8re pr\u00e9f\u00e9r\u00e9e pour que je te tienne ou t\u2019embrasse ?", "it": "Qual \u00e8 il tuo modo preferito di abbracciarmi o tenermi?", "fi": "Mik\u00e4 on suosikkitapasi, miten haluaisit minun pit\u00e4v\u00e4n tai halivan sinua?", "nl": "Wat is jouw favoriete manier waarop ik je kan vasthouden of omarmen?", "no": "Hva er din favorittm\u00e5te for meg \u00e5 holde eller klemme deg p\u00e5?", "sv": "Vad \u00e4r ditt favorit s\u00e4tt f\u00f6r mig att h\u00e5lla om dig eller krama dig?", "pl": "Jaki jest tw\u00f3j ulubiony spos\u00f3b, w jaki mog\u0119 ci\u0119 przytuli\u0107 lub obj\u0105\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s your favorite way for me to hold or hug you?';
UPDATE questions
SET translations = '{"en": "How do you like me to show affection during the day \u2014 quick touches, hugs, kisses?", "da": "Hvordan vil du have, jeg viser hengivenhed i l\u00f8bet af dagen \u2013 hurtige ber\u00f8ringer, kram, kys?", "de": "Wie m\u00f6chtest du, dass ich tags\u00fcber Zuneigung zeige \u2013 kurze Ber\u00fchrungen, Umarmungen, K\u00fcsse?", "es": "\u00bfC\u00f3mo te gusta que te muestre cari\u00f1o durante el d\u00eda \u2014 toques r\u00e1pidos, abrazos, besos?", "pt": "Como queres que eu mostre carinho durante o dia \u2014 toques r\u00e1pidos, abra\u00e7os, beijos?", "ro": "Cum vrei s\u0103 \u00ee\u021bi ar\u0103t afec\u021biunea pe parcursul zilei \u2014 atingeri scurte, \u00eembr\u0103\u021bi\u0219\u0103ri, s\u0103ruturi?", "fr": "Comment veux-tu que je montre de l\u2019affection pendant la journ\u00e9e \u2014 gestes rapides, c\u00e2lins, baisers ?", "it": "Come ti piace che mostri affetto durante il giorno \u2014 tocchi veloci, abbracci, baci?", "fi": "Miten haluaisit, ett\u00e4 osoitan rakkautta p\u00e4iv\u00e4n aikana \u2014 nopeilla kosketuksilla, haleilla, suukkoilla?", "nl": "Hoe vind je het fijn dat ik genegenheid toon gedurende de dag \u2014 snelle aanrakingen, knuffels, kussen?", "no": "Hvordan liker du at jeg viser kj\u00e6rlighet i l\u00f8pet av dagen \u2014 raske ber\u00f8ringer, klemmer, kyss?", "sv": "Hur vill du att jag ska visa tillgivenhet under dagen \u2014 snabba ber\u00f6ringar, kramar, kyssar?", "pl": "Jak lubisz, \u017cebym okazywa\u0142 uczucia w ci\u0105gu dnia \u2014 szybkie dotkni\u0119cia, przytulenia, poca\u0142unki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to show affection during the day — quick touches, hugs, kisses?';
UPDATE questions
SET translations = '{"en": "What kind of physical affection helps you feel secure?", "da": "Hvilken form for fysisk hengivenhed f\u00e5r dig til at f\u00f8le dig tryg?", "de": "Welche Art von k\u00f6rperlicher Zuneigung l\u00e4sst dich sicher f\u00fchlen?", "es": "\u00bfQu\u00e9 tipo de afecto f\u00edsico te hace sentir seguro/a?", "pt": "Que tipo de afeto f\u00edsico te faz sentir seguro(a)?", "ro": "Ce fel de afec\u021biune fizic\u0103 te face s\u0103 te sim\u021bi \u00een siguran\u021b\u0103?", "fr": "Quel type d\u2019affection physique te fait te sentir en s\u00e9curit\u00e9 ?", "it": "Quale tipo di affetto fisico ti fa sentire sicuro?", "fi": "Mink\u00e4laista fyysist\u00e4 l\u00e4heisyytt\u00e4 tarvitset tunteaksesi itsesi turvalliseksi?", "nl": "Welke vorm van fysieke genegenheid helpt je je veilig te voelen?", "no": "Hvilken type fysisk n\u00e6rhet f\u00e5r deg til \u00e5 f\u00f8le deg trygg?", "sv": "Vilken typ av fysisk n\u00e4rhet f\u00e5r dig att k\u00e4nna dig trygg?", "pl": "Jakiego rodzaju fizyczna blisko\u015b\u0107 sprawia, \u017ce czujesz si\u0119 bezpiecznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of physical affection helps you feel secure?';
UPDATE questions
SET translations = '{"en": "When do you crave closeness with me the most?", "da": "Hvorn\u00e5r l\u00e6nges du mest efter at v\u00e6re t\u00e6t p\u00e5 mig?", "de": "Wann sehnst du dich am meisten danach, mir nahe zu sein?", "es": "\u00bfCu\u00e1ndo anhelas m\u00e1s estar cerca de m\u00ed?", "pt": "Quando \u00e9 que mais desejas estar perto de mim?", "ro": "C\u00e2nd \u00ee\u021bi dore\u0219ti cel mai mult s\u0103 fii aproape de mine?", "fr": "Quand d\u00e9sires-tu le plus \u00eatre proche de moi ?", "it": "Quando hai pi\u00f9 voglia di vicinanza con me?", "fi": "Milloin kaipaat l\u00e4heisyytt\u00e4 kanssani eniten?", "nl": "Wanneer heb je het meest behoefte aan nabijheid met mij?", "no": "N\u00e5r lengter du mest etter n\u00e6rhet med meg?", "sv": "N\u00e4r l\u00e4ngtar du mest efter n\u00e4rhet med mig?", "pl": "Kiedy najbardziej pragniesz blisko\u015bci ze mn\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When do you crave closeness with me the most?';
UPDATE questions
SET translations = '{"en": "How do you like me to initiate affection?", "da": "Hvordan vil du have, jeg tager initiativ til hengivenhed?", "de": "Wie m\u00f6chtest du, dass ich Zuneigung initiiere?", "es": "\u00bfC\u00f3mo te gusta que inicie el afecto contigo?", "pt": "Como gostas que eu inicie o carinho?", "ro": "Cum \u00ee\u021bi place s\u0103 ini\u021biez afec\u021biunea?", "fr": "Comment veux-tu que je prenne l\u2019initiative de l\u2019affection ?", "it": "Come ti piace che io inizi a mostrare affetto?", "fi": "Miten haluaisit, ett\u00e4 aloitan hellyyden?", "nl": "Hoe wil je dat ik genegenheid initieer?", "no": "Hvordan liker du at jeg viser omtanke?", "sv": "Hur vill du att jag ska visa min tillgivenhet?", "pl": "Jak lubisz, \u017cebym okazywa\u0142 uczucia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to initiate affection?';
UPDATE questions
SET translations = '{"en": "Do you think people misunderstand this love language \u2014 assuming it\u2019s only about sex, when it\u2019s really about comfort and connection?", "da": "Tror du, folk misforst\u00e5r dette k\u00e6rlighedssprog \u2013 og tror, det kun handler om sex, n\u00e5r det i virkeligheden handler om tr\u00f8st og forbindelse?", "de": "Denkst du, dass Menschen diese Liebessprache missverstehen \u2013 und denken, sie ginge nur um Sex, obwohl es in Wahrheit um Trost und Verbindung geht?", "es": "\u00bfCrees que la gente malinterpreta este lenguaje del amor \u2014 pensando que se trata solo de sexo, cuando realmente es de consuelo y conexi\u00f3n?", "pt": "Achas que as pessoas interpretam mal esta linguagem do amor \u2014 achando que \u00e9 s\u00f3 sobre sexo, quando na verdade \u00e9 sobre conforto e liga\u00e7\u00e3o?", "ro": "Crezi c\u0103 oamenii \u00een\u021beleg gre\u0219it acest limbaj al iubirii \u2014 crez\u00e2nd c\u0103 e doar despre sex, c\u00e2nd de fapt e despre confort \u0219i conexiune?", "fr": "Penses-tu que les gens comprennent mal ce langage de l\u2019amour \u2014 pensant qu\u2019il s\u2019agit seulement de sexe alors qu\u2019il s\u2019agit de r\u00e9confort et de connexion ?", "it": "Pensi che le persone fraintendano questo linguaggio dell''amore, assumendo che riguardi solo il sesso, quando in realt\u00e0 si tratta di conforto e connessione?", "fi": "Luuleeko, ett\u00e4 ihmiset ymm\u00e4rt\u00e4v\u00e4t t\u00e4m\u00e4n rakkauden kielen v\u00e4\u00e4rin \u2014 olettaen, ett\u00e4 se on vain seksi\u00e4, kun se oikeastaan liittyy mukavuuteen ja yhteyteen?", "nl": "Denk je dat mensen deze liefdestaal verkeerd begrijpen \u2014 ervan uitgaande dat het alleen om seks gaat, terwijl het eigenlijk om comfort en verbinding draait?", "no": "Tror du folk misforst\u00e5r dette kj\u00e6rlighetsspr\u00e5ket \u2014 og antar at det kun handler om sex, n\u00e5r det egentlig handler om komfort og forbindelse?", "sv": "Tror du att folk missf\u00f6rst\u00e5r detta k\u00e4rleksspr\u00e5k \u2014 och antar att det bara handlar om sex, n\u00e4r det egentligen handlar om komfort och koppling?", "pl": "Czy my\u015blisz, \u017ce ludzie \u017ale rozumiej\u0105 ten j\u0119zyk mi\u0142o\u015bci \u2014 zak\u0142adaj\u0105c, \u017ce chodzi tylko o seks, podczas gdy tak naprawd\u0119 chodzi o komfort i po\u0142\u0105czenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you think people misunderstand this love language — assuming it’s only about sex, when it’s really about comfort and connection?';
UPDATE questions
SET translations = '{"en": "How do you feel about affection in public?", "da": "Hvad synes du om hengivenhed i det offentlige rum?", "de": "Wie f\u00fchlst du dich bei Zuneigung in der \u00d6ffentlichkeit?", "es": "\u00bfQu\u00e9 piensas del afecto en p\u00fablico?", "pt": "O que achas de mostrar carinho em p\u00fablico?", "ro": "Ce p\u0103rere ai despre afec\u021biunea \u00een public?", "fr": "Que penses-tu de l\u2019affection en public ?", "it": "Cosa ne pensi dell''affetto in pubblico?", "fi": "Miten suhtaudut julkiseen hellyyteen?", "nl": "Hoe voel je je over genegenheid in het openbaar?", "no": "Hvordan f\u00f8ler du om kj\u00e6rlighet i offentligheten?", "sv": "Hur k\u00e4nner du f\u00f6r \u00f6mhet p\u00e5 offentliga platser?", "pl": "Jak si\u0119 czujesz w kwestii okazywania uczu\u0107 publicznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel about affection in public?';
UPDATE questions
SET translations = '{"en": "Do you ever feel pressure to be affectionate a certain way \u2014 like to hug, cuddle, or initiate \u2014 even when you\u2019re not in the mood?", "da": "F\u00f8ler du nogensinde pres for at vise hengivenhed p\u00e5 en bestemt m\u00e5de \u2013 som at kramme, nusse eller tage initiativ \u2013 selv n\u00e5r du ikke er i hum\u00f8r?", "de": "F\u00fchlst du dich jemals unter Druck, auf eine bestimmte Weise Zuneigung zu zeigen \u2013 zu umarmen, zu kuscheln oder den ersten Schritt zu machen \u2013 auch wenn du nicht in Stimmung bist?", "es": "\u00bfAlguna vez sientes presi\u00f3n para mostrar afecto de cierta manera \u2014 abrazar, acurrucarte o iniciar \u2014 incluso cuando no tienes ganas?", "pt": "Alguma vez sentes press\u00e3o para mostrar afeto de certa forma \u2014 abra\u00e7ar, aconchegar ou iniciar \u2014 mesmo quando n\u00e3o est\u00e1s com vontade?", "ro": "Sim\u021bi vreodat\u0103 presiune s\u0103 ar\u0103\u021bi afec\u021biune \u00eentr-un anumit fel \u2014 s\u0103 \u00eembr\u0103\u021bi\u0219ezi, s\u0103 te alint sau s\u0103 ini\u021biezi \u2014 chiar \u0219i c\u00e2nd nu ai chef?", "fr": "Ressens-tu parfois une pression pour montrer ton affection d\u2019une certaine fa\u00e7on \u2014 \u00e9treindre, c\u00e2liner ou initier \u2014 m\u00eame quand tu n\u2019en as pas envie ?", "it": "Ti capita mai di sentirti sotto pressione per essere affettuoso in un certo modo \u2014 come abbracciare, coccolare o iniziare \u2014 anche quando non sei dell''umore giusto?", "fi": "Tunnetko koskaan painetta olla affektiivinen tietyll\u00e4 tavalla \u2014 kuten halata, kietoutua tai aloittaa \u2014 vaikka et olisi siihen mielentilassa?", "nl": "Voel je ooit druk om op een bepaalde manier affectie te tonen \u2014 zoals knuffelen, omhelzen of het initiatief nemen \u2014 zelfs als je daar niet in de stemming voor bent?", "no": "F\u00f8ler du noen gang press for \u00e5 v\u00e6re kj\u00e6rlig p\u00e5 en bestemt m\u00e5te \u2014 som \u00e5 klemme, kose eller ta initiativ \u2014 selv n\u00e5r du ikke er i hum\u00f8r?", "sv": "K\u00e4nner du n\u00e5gonsin press att vara k\u00e4rleksfull p\u00e5 ett visst s\u00e4tt \u2014 som att kramas, mysa eller ta initiativ \u2014 \u00e4ven n\u00e4r du inte \u00e4r p\u00e5 hum\u00f6r?", "pl": "Czy kiedykolwiek czujesz presj\u0119, aby okazywa\u0107 uczucia w okre\u015blony spos\u00f3b \u2014 na przyk\u0142ad przytula\u0107, tuli\u0107 si\u0119 lub inicjowa\u0107 \u2014 nawet gdy nie masz na to ochoty?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you ever feel pressure to be affectionate a certain way — like to hug, cuddle, or initiate — even when you’re not in the mood?';
UPDATE questions
SET translations = '{"en": "How can we both ask for touch \u2014 or space \u2014 without anyone feeling rejected or guilty?", "da": "Hvordan kan vi begge bede om ber\u00f8ring \u2013 eller plads \u2013 uden at nogen f\u00f8ler sig afvist eller skyldig?", "de": "Wie k\u00f6nnen wir beide um Ber\u00fchrung \u2013 oder Raum \u2013 bitten, ohne dass sich jemand abgelehnt oder schuldig f\u00fchlt?", "es": "\u00bfC\u00f3mo podemos ambos pedir contacto \u2014 o espacio \u2014 sin que nadie se sienta rechazado o culpable?", "pt": "Como podemos ambos pedir toque \u2014 ou espa\u00e7o \u2014 sem que ningu\u00e9m se sinta rejeitado ou culpado?", "ro": "Cum putem cere am\u00e2ndoi atingere \u2014 sau spa\u021biu \u2014 f\u0103r\u0103 ca cineva s\u0103 se simt\u0103 respins sau vinovat?", "fr": "Comment pouvons-nous demander tous deux du contact \u2014 ou de l\u2019espace \u2014 sans que personne ne se sente rejet\u00e9 ou coupable ?", "it": "Come possiamo entrambi chiedere contatto \u2014 o spazio \u2014 senza che nessuno si senta rifiutato o in colpa?", "fi": "Miten voimme molemmat pyyt\u00e4\u00e4 kosketusta \u2014 tai tilaa \u2014 ilman, ett\u00e4 kukaan tuntee itse\u00e4\u00e4n hyl\u00e4tyksi tai syylliseksi?", "nl": "Hoe kunnen we allebei om aanraking \u2014 of ruimte \u2014 vragen zonder dat iemand zich afgewezen of schuldig voelt?", "no": "Hvordan kan vi begge be om ber\u00f8ring \u2014 eller plass \u2014 uten at noen f\u00f8ler seg avvist eller skyldig?", "sv": "Hur kan vi b\u00e5da be om ber\u00f6ring \u2014 eller utrymme \u2014 utan att n\u00e5gon k\u00e4nner sig avvisad eller skyldig?", "pl": "Jak mo\u017cemy oboje prosi\u0107 o dotyk \u2014 lub przestrze\u0144 \u2014 tak, aby nikt nie czu\u0142 si\u0119 odrzucony lub winny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How can we both ask for touch — or space — without anyone feeling rejected or guilty?';
UPDATE questions
SET translations = '{"en": "What\u2019s one small gesture I could do more often to say \u201cI love you\u201d without words?", "da": "Hvilken lille gestus kunne jeg g\u00f8re oftere for at sige \u201cjeg elsker dig\u201d uden ord?", "de": "Welche kleine Geste k\u00f6nnte ich \u00f6fter tun, um \u201eIch liebe dich\u201c ohne Worte zu sagen?", "es": "\u00bfQu\u00e9 peque\u00f1o gesto podr\u00eda hacer m\u00e1s a menudo para decir \u201cte amo\u201d sin palabras?", "pt": "Que pequeno gesto eu poderia fazer mais vezes para dizer \u201camo-te\u201d sem palavras?", "ro": "Ce mic gest a\u0219 putea face mai des pentru a spune \u201cte iubesc\u201d f\u0103r\u0103 cuvinte?", "fr": "Quel petit geste pourrais-je faire plus souvent pour dire \u00ab je t\u2019aime \u00bb sans mots ?", "it": "Qual \u00e8 un piccolo gesto che potrei fare pi\u00f9 spesso per dire \"ti amo\" senza parole?", "fi": "Mik\u00e4 on yksi pieni ele, jota voisin tehd\u00e4 useammin sanoakseni \"rakastan sinua\" ilman sanoja?", "nl": "Wat is \u00e9\u00e9n klein gebaar dat ik vaker zou kunnen doen om \"Ik hou van je\" zonder woorden te zeggen?", "no": "Hva er en liten gest jeg kunne gjort oftere for \u00e5 si \"jeg elsker deg\" uten ord?", "sv": "Vilken liten gest skulle jag kunna g\u00f6ra oftare f\u00f6r att s\u00e4ga \"jag \u00e4lskar dig\" utan ord?", "pl": "Jaki ma\u0142y gest m\u00f3g\u0142bym robi\u0107 cz\u0119\u015bciej, aby powiedzie\u0107 \u201ekocham ci\u0119\u201d bez s\u0142\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one small gesture I could do more often to say “I love you” without words?';
UPDATE questions
SET translations = '{"en": "How do you want me to show affection when words don\u2019t come easily?", "da": "Hvordan vil du have, jeg viser k\u00e6rlighed, n\u00e5r ordene ikke kommer let?", "de": "Wie m\u00f6chtest du, dass ich Liebe zeige, wenn mir die Worte nicht leichtfallen?", "es": "\u00bfC\u00f3mo quieres que te muestre amor cuando las palabras no salen f\u00e1cilmente?", "pt": "Como queres que eu mostre amor quando as palavras n\u00e3o v\u00eam facilmente?", "ro": "Cum vrei s\u0103-\u021bi ar\u0103t iubirea c\u00e2nd cuvintele nu vin u\u0219or?", "fr": "Comment veux-tu que je montre mon amour quand les mots ne viennent pas facilement ?", "it": "Come vuoi che ti mostri affetto quando le parole non vengono facilmente?", "fi": "Miten haluat, ett\u00e4 osoitan rakkautta, kun sanat eiv\u00e4t tule helposti?", "nl": "Hoe wil je dat ik genegenheid toon als woorden niet gemakkelijk komen?", "no": "Hvordan vil du at jeg skal vise kj\u00e6rlighet n\u00e5r ordene ikke kommer lett?", "sv": "Hur vill du att jag ska visa tillgivenhet n\u00e4r orden inte kommer l\u00e4tt?", "pl": "Jak chcesz, \u017cebym okazywa\u0142 uczucia, gdy s\u0142owa nie przychodz\u0105 \u0142atwo?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you want me to show affection when words don’t come easily?';

-- Category: Love Talks (75 questions)
UPDATE questions
SET translations = '{"en": "What''s something you don''t miss about being single?", "da": "Hvad savner du ikke ved at v\u00e6re single?", "de": "Was vermisst du nicht am Singleleben?", "es": "\u00bfQu\u00e9 es algo que no extra\u00f1as de estar soltero/a?", "pt": "O que \u00e9 algo que n\u00e3o sentes falta na vida de solteiro/a?", "ro": "Ce lucru nu \u00ee\u021bi lipse\u0219te din perioada c\u00e2nd erai singur(\u0103)?", "fr": "Qu\u2019est-ce qui ne te manque pas dans la vie de c\u00e9libataire ?", "it": "Qual \u00e8 una cosa che non ti manca di essere single?", "fi": "Mik\u00e4 on jotain, jota et kaipaakaan sinkkuudesta?", "nl": "Wat is iets dat je niet mist aan het vrijgezel zijn?", "no": "Hva er noe du ikke savner med \u00e5 v\u00e6re singel?", "sv": "Vad \u00e4r n\u00e5got du inte saknar med att vara singel?", "pl": "Co\u015b, czego nie t\u0119sknisz za byciem singlem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What''s something you don''t miss about being single?';
UPDATE questions
SET translations = '{"en": "What do you think is my biggest strength in our relationship?", "da": "Hvad mener du er min st\u00f8rste styrke i vores forhold?", "de": "Was ist deiner Meinung nach meine gr\u00f6\u00dfte St\u00e4rke in unserer Beziehung?", "es": "\u00bfQu\u00e9 crees que es mi mayor fortaleza en nuestra relaci\u00f3n?", "pt": "O que achas que \u00e9 a minha maior for\u00e7a na nossa rela\u00e7\u00e3o?", "ro": "Care crezi c\u0103 este cea mai mare calitate a mea \u00een rela\u021bia noastr\u0103?", "fr": "Selon toi, quelle est ma plus grande force dans notre relation ?", "it": "Quale pensi sia la mia forza pi\u00f9 grande nella nostra relazione?", "fi": "Mik\u00e4 mielest\u00e4si on suurin vahvuuteni suhteessamme?", "nl": "Wat denk je dat mijn grootste kracht is in onze relatie?", "no": "Hva tror du er min st\u00f8rste styrke i forholdet v\u00e5rt?", "sv": "Vad tycker du \u00e4r min st\u00f6rsta styrka i v\u00e5r relation?", "pl": "Jak\u0105 uwa\u017casz za moj\u0105 najwi\u0119ksz\u0105 si\u0142\u0119 w naszym zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What do you think is my biggest strength in our relationship?';
UPDATE questions
SET translations = '{"en": "How did you try to impress me at the beginning of our relationship?", "da": "Hvordan pr\u00f8vede du at imponere mig i begyndelsen af vores forhold?", "de": "Wie hast du am Anfang unserer Beziehung versucht, mich zu beeindrucken?", "es": "\u00bfC\u00f3mo intentaste impresionarme al principio de nuestra relaci\u00f3n?", "pt": "Como tentaste impressionar-me no in\u00edcio da nossa rela\u00e7\u00e3o?", "ro": "Cum ai \u00eencercat s\u0103 m\u0103 impresionezi la \u00eenceputul rela\u021biei noastre?", "fr": "Comment as-tu essay\u00e9 de m\u2019impressionner au d\u00e9but de notre relation ?", "it": "Come hai cercato di impressionarmi all''inizio della nostra relazione?", "fi": "Miten yritit vaikuttaa minuun suhteen alussa?", "nl": "Hoe heb je geprobeerd me te imponeren aan het begin van onze relatie?", "no": "Hvordan pr\u00f8vde du \u00e5 imponere meg i begynnelsen av forholdet v\u00e5rt?", "sv": "Hur f\u00f6rs\u00f6kte du imponera p\u00e5 mig i b\u00f6rjan av v\u00e5r relation?", "pl": "Jak pr\u00f3bowa\u0142e\u015b mnie zaimponowa\u0107 na pocz\u0105tku naszego zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How did you try to impress me at the beginning of our relationship?';
UPDATE questions
SET translations = '{"en": "How would you describe our chemistry?", "da": "Hvordan vil du beskrive vores kemi?", "de": "Wie w\u00fcrdest du unsere Chemie beschreiben?", "es": "\u00bfC\u00f3mo describir\u00edas nuestra qu\u00edmica?", "pt": "Como descreverias a nossa qu\u00edmica?", "ro": "Cum ai descrie chimia dintre noi?", "fr": "Comment d\u00e9crirais-tu notre alchimie ?", "it": "Come descriveresti la nostra chimica?", "fi": "Miten kuvailisit kemiaamme?", "nl": "Hoe zou je onze chemie beschrijven?", "no": "Hvordan ville du beskrive kjemien v\u00e5r?", "sv": "Hur skulle du beskriva v\u00e5r kemi?", "pl": "Jak by\u015b opisa\u0142 nasz\u0105 chemi\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How would you describe our chemistry?';
UPDATE questions
SET translations = '{"en": "What are some things I can do to help you feel more secure in our relationship?", "da": "Hvad kan jeg g\u00f8re for at f\u00e5 dig til at f\u00f8le dig mere tryg i vores forhold?", "de": "Was kann ich tun, damit du dich in unserer Beziehung sicherer f\u00fchlst?", "es": "\u00bfQu\u00e9 cosas puedo hacer para que te sientas m\u00e1s seguro/a en nuestra relaci\u00f3n?", "pt": "Que coisas posso fazer para te sentires mais seguro/a na nossa rela\u00e7\u00e3o?", "ro": "Ce a\u0219 putea face ca s\u0103 te sim\u021bi mai \u00een siguran\u021b\u0103 \u00een rela\u021bia noastr\u0103?", "fr": "Quelles choses puis-je faire pour que tu te sentes plus en s\u00e9curit\u00e9 dans notre relation ?", "it": "Quali sono alcune cose che posso fare per aiutarti a sentirti pi\u00f9 sicuro nella nostra relazione?", "fi": "Mit\u00e4 asioita voisin tehd\u00e4, jotta tuntisit itsesi turvallisemmaksi suhteessamme?", "nl": "Wat zijn enkele dingen die ik kan doen om je meer zekerheid te geven in onze relatie?", "no": "Hva er noen ting jeg kan gj\u00f8re for \u00e5 hjelpe deg med \u00e5 f\u00f8le deg mer trygg i forholdet v\u00e5rt?", "sv": "Vilka saker kan jag g\u00f6ra f\u00f6r att hj\u00e4lpa dig att k\u00e4nna dig mer trygg i v\u00e5r relation?", "pl": "Co mog\u0119 zrobi\u0107, aby\u015b czu\u0142 si\u0119 bardziej bezpiecznie w naszym zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What are some things I can do to help you feel more secure in our relationship?';
UPDATE questions
SET translations = '{"en": "When do you feel most loved by me?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest elsket af mig?", "de": "Wann f\u00fchlst du dich von mir am meisten geliebt?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s amado/a por m\u00ed?", "pt": "Quando te sentes mais amado/a por mim?", "ro": "C\u00e2nd te sim\u021bi cel mai iubit(\u0103) de mine?", "fr": "Quand te sens-tu le plus aim\u00e9(e) par moi ?", "it": "Quando ti senti pi\u00f9 amato da me?", "fi": "Milloin tunnet itsesi eniten rakastetuksi minun puolestani?", "nl": "Wanneer voel je je het meest geliefd door mij?", "no": "N\u00e5r f\u00f8ler du deg mest elsket av meg?", "sv": "N\u00e4r k\u00e4nner du dig mest \u00e4lskad av mig?", "pl": "Kiedy czujesz si\u0119 przeze mnie najbardziej kochany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When do you feel most loved by me?';
UPDATE questions
SET translations = '{"en": "What\u2019s the funniest \u201conly we get it\u201d moment we\u2019ve had so far?", "da": "Hvad er det sjoveste \u201ckun vi forst\u00e5r det\u201d-\u00f8jeblik, vi har haft indtil nu?", "de": "Was war bisher der lustigste \u201eNur wir verstehen das\u201c-Moment?", "es": "\u00bfCu\u00e1l ha sido hasta ahora el momento m\u00e1s gracioso de \u201csolo nosotros lo entendemos\u201d?", "pt": "Qual foi, at\u00e9 agora, o momento mais engra\u00e7ado do tipo \u201cs\u00f3 n\u00f3s percebemos\u201d?", "ro": "Care a fost p\u00e2n\u0103 acum momentul amuzant de tipul \u201edoar noi \u00eel \u00een\u021belegem\u201d?", "fr": "Quel a \u00e9t\u00e9 jusqu\u2019ici notre moment le plus dr\u00f4le du type \u00ab il n\u2019y a que nous qui comprenons \u00bb ?", "it": "Qual \u00e8 stato il momento pi\u00f9 divertente di \u201csolo noi lo capiamo\u201d che abbiamo avuto finora?", "fi": "Mik\u00e4 on hauskin \"vain me ymm\u00e4rr\u00e4mme\" hetki, jonka olemme kokeneet t\u00e4h\u00e4n menness\u00e4?", "nl": "Wat is het grappigste \"alleen wij begrijpen het\" moment dat we tot nu toe hebben gehad?", "no": "Hva er det morsomste \"bare vi forst\u00e5r det\"-\u00f8yeblikket vi har hatt s\u00e5 langt?", "sv": "Vad \u00e4r det roligaste \"bara vi f\u00f6rst\u00e5r\" \u00f6gonblicket vi har haft hittills?", "pl": "Jaki by\u0142 najzabawniejszy moment \u201etylko my to rozumiemy\u201d, kt\u00f3ry mieli\u015bmy do tej pory?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s the funniest “only we get it” moment we’ve had so far?';
UPDATE questions
SET translations = '{"en": "If our relationship were to end tomorrow what things would you miss the most?", "da": "Hvis vores forhold sluttede i morgen, hvilke ting ville du savne mest?", "de": "Wenn unsere Beziehung morgen enden w\u00fcrde, welche Dinge w\u00fcrdest du am meisten vermissen?", "es": "Si nuestra relaci\u00f3n terminara ma\u00f1ana, \u00bfqu\u00e9 cosas extra\u00f1ar\u00edas m\u00e1s?", "pt": "Se a nossa rela\u00e7\u00e3o acabasse amanh\u00e3, que coisas sentirias mais falta?", "ro": "Dac\u0103 rela\u021bia noastr\u0103 s-ar termina m\u00e2ine, ce lucruri \u021bi-ar lipsi cel mai mult?", "fr": "Si notre relation se terminait demain, quelles choses te manqueraient le plus ?", "it": "Se la nostra relazione dovesse finire domani, quali cose ti mancherebbero di pi\u00f9?", "fi": "Jos suhteemme p\u00e4\u00e4ttyisi huomenna, mit\u00e4 asioita kaipaisit eniten?", "nl": "Als onze relatie morgen zou eindigen, welke dingen zou je dan het meest missen?", "no": "Hvis forholdet v\u00e5rt skulle ta slutt i morgen, hva ville du savne mest?", "sv": "Om v\u00e5r relation skulle ta slut imorgon, vad skulle du sakna mest?", "pl": "Je\u015bli nasz zwi\u0105zek mia\u0142by si\u0119 zako\u0144czy\u0107 jutro, co najbardziej by\u015b t\u0119skni\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'If our relationship were to end tomorrow what things would you miss the most?';
UPDATE questions
SET translations = '{"en": "What about our relationship are you most grateful for?", "da": "Hvad ved vores forhold er du mest taknemmelig for?", "de": "Wof\u00fcr in unserer Beziehung bist du am dankbarsten?", "es": "\u00bfDe qu\u00e9 est\u00e1s m\u00e1s agradecido/a en nuestra relaci\u00f3n?", "pt": "Do que \u00e9 que est\u00e1s mais grato/a na nossa rela\u00e7\u00e3o?", "ro": "Pentru ce e\u0219ti cel mai recunosc\u0103tor/recunosc\u0103toare \u00een rela\u021bia noastr\u0103?", "fr": "De quoi es-tu le plus reconnaissant(e) dans notre relation ?", "it": "Di cosa nella nostra relazione sei pi\u00f9 grato?", "fi": "Mist\u00e4 suhteessamme olet eniten kiitollinen?", "nl": "Waar ben je het meest dankbaar voor in onze relatie?", "no": "Hva er du mest takknemlig for i v\u00e5rt forhold?", "sv": "Vad \u00e4r du mest tacksam f\u00f6r i v\u00e5r relation?", "pl": "Za co w naszej relacji jeste\u015b najbardziej wdzi\u0119czny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What about our relationship are you most grateful for?';
UPDATE questions
SET translations = '{"en": "What does a perfect day together look like for you?", "da": "Hvordan ser en perfekt dag sammen ud for dig?", "de": "Wie sieht f\u00fcr dich ein perfekter Tag zusammen aus?", "es": "\u00bfC\u00f3mo es para ti un d\u00eda perfecto juntos?", "pt": "Como \u00e9 para ti um dia perfeito juntos?", "ro": "Cum arat\u0103 pentru tine o zi perfect\u0103 petrecut\u0103 \u00eempreun\u0103?", "fr": "\u00c0 quoi ressemble pour toi une journ\u00e9e parfaite ensemble ?", "it": "Come sarebbe per te una giornata perfetta insieme?", "fi": "Millainen t\u00e4ydellinen p\u00e4iv\u00e4 yhdess\u00e4 n\u00e4ytt\u00e4\u00e4 sinun mielest\u00e4si?", "nl": "Hoe ziet een perfecte dag samen er voor jou uit?", "no": "Hvordan ser en perfekt dag sammen ut for deg?", "sv": "Hur ser en perfekt dag tillsammans ut f\u00f6r dig?", "pl": "Jak wygl\u0105da dla ciebie idealny dzie\u0144 razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What does a perfect day together look like for you?';
UPDATE questions
SET translations = '{"en": "How do you think we have both changed since we first met?", "da": "Hvordan synes du, at vi begge har \u00e6ndret os, siden vi m\u00f8dtes f\u00f8rste gang?", "de": "Wie glaubst du, haben wir uns beide ver\u00e4ndert, seit wir uns kennengelernt haben?", "es": "\u00bfC\u00f3mo crees que ambos hemos cambiado desde que nos conocimos?", "pt": "Como achas que ambos mud\u00e1mos desde que nos conhecemos?", "ro": "Cum crezi c\u0103 ne-am schimbat am\u00e2ndoi de c\u00e2nd ne-am cunoscut?", "fr": "Comment penses-tu que nous avons tous les deux chang\u00e9 depuis notre rencontre ?", "it": "Come pensi che siamo cambiati entrambi da quando ci siamo incontrati per la prima volta?", "fi": "Miten luulet, ett\u00e4 olemme molemmat muuttuneet siit\u00e4, kun tapasimme ensimm\u00e4isen kerran?", "nl": "Hoe denk je dat we allebei veranderd zijn sinds we elkaar voor het eerst ontmoetten?", "no": "Hvordan tror du vi begge har endret oss siden vi f\u00f8rst m\u00f8ttes?", "sv": "Hur tror du att vi b\u00e5da har f\u00f6r\u00e4ndrats sedan vi f\u00f6rst tr\u00e4ffades?", "pl": "Jak my\u015blisz, jak oboje si\u0119 zmienili\u015bmy od czasu, gdy si\u0119 po raz pierwszy spotkali\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How do you think we have both changed since we first met?';
UPDATE questions
SET translations = '{"en": "In what ways has our relationship changed you?", "da": "P\u00e5 hvilke m\u00e5der har vores forhold \u00e6ndret dig?", "de": "Inwiefern hat unsere Beziehung dich ver\u00e4ndert?", "es": "\u00bfDe qu\u00e9 maneras nuestra relaci\u00f3n te ha cambiado?", "pt": "De que maneiras a nossa rela\u00e7\u00e3o te mudou?", "ro": "\u00cen ce fel te-a schimbat rela\u021bia noastr\u0103?", "fr": "De quelles mani\u00e8res notre relation t\u2019a-t-elle chang\u00e9(e) ?", "it": "In che modo la nostra relazione ti ha cambiato?", "fi": "Miten suhteemme on muuttanut sinua?", "nl": "Op welke manieren heeft onze relatie jou veranderd?", "no": "P\u00e5 hvilke m\u00e5ter har forholdet v\u00e5rt endret deg?", "sv": "P\u00e5 vilka s\u00e4tt har v\u00e5r relation f\u00f6r\u00e4ndrat dig?", "pl": "W jaki spos\u00f3b nasza relacja ci\u0119 zmieni\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'In what ways has our relationship changed you?';
UPDATE questions
SET translations = '{"en": "What\u2019s a small surprise I could plan that would mean a lot to you?", "da": "Hvilken lille overraskelse kunne jeg planl\u00e6gge, som ville betyde meget for dig?", "de": "Welche kleine \u00dcberraschung k\u00f6nnte ich planen, die dir viel bedeuten w\u00fcrde?", "es": "\u00bfQu\u00e9 peque\u00f1a sorpresa podr\u00eda planear que signifique mucho para ti?", "pt": "Que pequena surpresa eu poderia preparar que significasse muito para ti?", "ro": "Ce mic\u0103 surpriz\u0103 a\u0219 putea s\u0103 planific care ar \u00eensemna mult pentru tine?", "fr": "Quelle petite surprise pourrais-je pr\u00e9parer qui compterait beaucoup pour toi ?", "it": "Qual \u00e8 una piccola sorpresa che potrei pianificare e che significherebbe molto per te?", "fi": "Mik\u00e4 olisi pieni yll\u00e4tys, jonka voisin suunnitella ja joka merkitsisi sinulle paljon?", "nl": "Wat is een kleine verrassing die ik zou kunnen plannen die veel voor je zou betekenen?", "no": "Hva er en liten overraskelse jeg kunne planlegge som ville bety mye for deg?", "sv": "Vad \u00e4r en liten \u00f6verraskning jag skulle kunna planera som skulle betyda mycket f\u00f6r dig?", "pl": "Jaka ma\u0142a niespodzianka, kt\u00f3r\u0105 m\u00f3g\u0142bym zaplanowa\u0107, mia\u0142aby dla Ciebie du\u017ce znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a small surprise I could plan that would mean a lot to you?';
UPDATE questions
SET translations = '{"en": "What''s a personal goal you have that you''d like more support with? ", "da": "Hvad er et personligt m\u00e5l, du har, hvor du gerne vil have mere st\u00f8tte?", "de": "Was ist ein pers\u00f6nliches Ziel von dir, bei dem du dir mehr Unterst\u00fctzung w\u00fcnschst?", "es": "\u00bfCu\u00e1l es una meta personal que tienes y con la que te gustar\u00eda recibir m\u00e1s apoyo?", "pt": "Qual \u00e9 um objetivo pessoal teu com o qual gostarias de ter mais apoio?", "ro": "Care este un obiectiv personal pentru care \u021bi-ai dori mai mult sprijin?", "fr": "Quel objectif personnel as-tu pour lequel tu aimerais davantage de soutien ?", "it": "Qual \u00e8 un obiettivo personale che hai e con cui vorresti avere pi\u00f9 supporto?", "fi": "Mik\u00e4 on henkil\u00f6kohtainen tavoitteesi, jossa toivoisit saavasi enemm\u00e4n tukea?", "nl": "Wat is een persoonlijk doel dat je hebt waar je graag meer ondersteuning bij zou willen?", "no": "Hva er et personlig m\u00e5l du har som du gjerne vil ha mer st\u00f8tte til?", "sv": "Vilket personligt m\u00e5l har du som du skulle vilja ha mer st\u00f6d med?", "pl": "Jakie osobiste cele masz, w kt\u00f3rych chcia\u0142by\u015b otrzyma\u0107 wi\u0119ksze wsparcie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What''s a personal goal you have that you''d like more support with? ';
UPDATE questions
SET translations = '{"en": "When do you feel most playful with me?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest legesyg sammen med mig?", "de": "Wann f\u00fchlst du dich mit mir am verspieltesten?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s juguet\u00f3n/a conmigo?", "pt": "Quando te sentes mais brincalh\u00e3o/brincalhona comigo?", "ro": "C\u00e2nd te sim\u021bi cel mai juc\u0103u\u0219/juc\u0103u\u0219\u0103 cu mine?", "fr": "Quand te sens-tu le/la plus joueur(se) avec moi ?", "it": "Quando ti senti pi\u00f9 giocoso con me?", "fi": "Milloin tunnet itsesi leikkisimm\u00e4ksi kanssani?", "nl": "Wanneer voel je je het meest speels met mij?", "no": "N\u00e5r f\u00f8ler du deg mest leken med meg?", "sv": "N\u00e4r k\u00e4nner du dig mest lekfull med mig?", "pl": "Kiedy czujesz si\u0119 ze mn\u0105 najbardziej zabawnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When do you feel most playful with me?';
UPDATE questions
SET translations = '{"en": "Which of us has the harder time hiding feelings?", "da": "Hvem af os har sv\u00e6rest ved at skjule f\u00f8lelser?", "de": "Wer von uns hat es am schwersten, Gef\u00fchle zu verbergen?", "es": "\u00bfQui\u00e9n de los dos tiene m\u00e1s dificultad para ocultar sus sentimientos?", "pt": "Qual de n\u00f3s tem mais dificuldade em esconder os sentimentos?", "ro": "Cine dintre noi are mai greu s\u0103-\u0219i ascund\u0103 sentimentele?", "fr": "Lequel de nous a le plus de mal \u00e0 cacher ses \u00e9motions ?", "it": "Chi di noi ha pi\u00f9 difficolt\u00e0 a nascondere i propri sentimenti?", "fi": "Kumpi meist\u00e4 on vaikeammassa asemassa tunteiden piilottamisessa?", "nl": "Wie van ons heeft het moeilijker om gevoelens te verbergen?", "no": "Hvem av oss har vanskeligere for \u00e5 skjule f\u00f8lelser?", "sv": "Vilken av oss har sv\u00e5rare att d\u00f6lja k\u00e4nslor?", "pl": "Kto z nas ma trudniej z ukrywaniem uczu\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Which of us has the harder time hiding feelings?';
UPDATE questions
SET translations = '{"en": "Which of us has a harder time saying no to the other?", "da": "Hvem af os har sv\u00e6rest ved at sige nej til den anden?", "de": "Wer von uns hat es schwerer, Nein zum anderen zu sagen?", "es": "\u00bfQui\u00e9n de los dos tiene m\u00e1s dificultad para decirle que no al otro?", "pt": "Qual de n\u00f3s tem mais dificuldade em dizer n\u00e3o ao outro?", "ro": "Cine dintre noi are mai greu s\u0103 \u00eei spun\u0103 nu celuilalt?", "fr": "Lequel de nous a le plus de mal \u00e0 dire non \u00e0 l\u2019autre ?", "it": "Chi di noi ha pi\u00f9 difficolt\u00e0 a dire di no all''altro?", "fi": "Kumpi meist\u00e4 on vaikeammassa asemassa sanoa ei toiselle?", "nl": "Wie van ons heeft het moeilijker om nee tegen de ander te zeggen?", "no": "Hvem av oss har vanskeligere for \u00e5 si nei til den andre?", "sv": "Vilken av oss har sv\u00e5rare att s\u00e4ga nej till den andra?", "pl": "Kto z nas ma trudniej powiedzie\u0107 \"nie\" drugiej osobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Which of us has a harder time saying no to the other?';
UPDATE questions
SET translations = '{"en": "Whats one of the best times you''ve had on vacation with me?", "da": "Hvem af os har brug for mest k\u00e6rlighed og omsorg for at f\u00f8le sig forbundet?", "de": "Wer von uns braucht mehr Zuneigung, um sich verbunden zu f\u00fchlen?", "es": "\u00bfQui\u00e9n de los dos necesita m\u00e1s cari\u00f1o para sentirse conectado/a?", "pt": "Qual de n\u00f3s precisa de mais carinho para se sentir conectado(a)?", "ro": "Cine dintre noi are nevoie de mai mult\u0103 afec\u021biune ca s\u0103 se simt\u0103 conectat(\u0103)?", "fr": "Lequel de nous a besoin de plus d\u2019affection pour se sentir connect\u00e9(e) ?", "it": "Qual \u00e8 uno dei migliori momenti che hai trascorso in vacanza con me?", "fi": "Mik\u00e4 on yksi parhaista hetkist\u00e4, jotka olet kokenut lomalla kanssani?", "nl": "Wat is een van de beste momenten die je met mij op vakantie hebt gehad?", "no": "Hva er et av de beste tidene du har hatt p\u00e5 ferie med meg?", "sv": "Vad \u00e4r en av de b\u00e4sta stunderna du har haft p\u00e5 semester med mig?", "pl": "Jaki by\u0142 jeden z najlepszych moment\u00f3w, kt\u00f3re sp\u0119dzili\u015bmy na wakacjach razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Whats one of the best times you''ve had on vacation with me?';
UPDATE questions
SET translations = '{"en": "Who sings better in the shower?", "da": "Hvem af os er mest tilb\u00f8jelig til at t\u00e6nde stearinlys og skabe stemning?", "de": "Wer von uns z\u00fcndet eher Kerzen an und sorgt f\u00fcr Stimmung?", "es": "\u00bfQui\u00e9n de los dos es m\u00e1s propenso/a a encender velas y crear ambiente?", "pt": "Qual de n\u00f3s \u00e9 mais prov\u00e1vel acender velas e criar clima?", "ro": "Cine dintre noi e mai probabil s\u0103 aprind\u0103 lum\u00e2n\u0103ri \u0219i s\u0103 creeze atmosfera?", "fr": "Lequel de nous est le plus susceptible d\u2019allumer des bougies et de mettre l\u2019ambiance ?", "it": "Chi canta meglio sotto la doccia?", "fi": "Kuka laulaa paremmin suihkussa?", "nl": "Wie zingt er beter onder de douche?", "no": "Hvem synger bedre i dusjen?", "sv": "Vem sjunger b\u00e4ttre i duschen?", "pl": "Kto lepiej \u015bpiewa pod prysznicem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Who sings better in the shower?';
UPDATE questions
SET translations = '{"en": "What\u2019s the funniest thing we\u2019ve experienced together?", "da": "Hvem af os er mest tilb\u00f8jelig til at t\u00e6nde stearinlys og skabe stemning?", "de": "Wer von uns z\u00fcndet eher Kerzen an und sorgt f\u00fcr Stimmung?", "es": "\u00bfQui\u00e9n de los dos es m\u00e1s propenso/a a encender velas y crear ambiente?", "pt": "Qual de n\u00f3s \u00e9 mais prov\u00e1vel acender velas e criar clima?", "ro": "Cine dintre noi e mai probabil s\u0103 aprind\u0103 lum\u00e2n\u0103ri \u0219i s\u0103 creeze atmosfera?", "fr": "Lequel de nous est le plus susceptible d\u2019allumer des bougies et de mettre l\u2019ambiance ?", "it": "Qual \u00e8 stata la cosa pi\u00f9 divertente che abbiamo vissuto insieme?", "fi": "Mik\u00e4 on hauskin asia, jonka olemme kokeneet yhdess\u00e4?", "nl": "Wat is het grappigste dat we samen hebben meegemaakt?", "no": "Hva er det morsomste vi har opplevd sammen?", "sv": "Vad \u00e4r det roligaste vi har upplevt tillsammans?", "pl": "Co by\u0142o naj\u015bmieszniejszego, co razem prze\u017cyli\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s the funniest thing we’ve experienced together?';
UPDATE questions
SET translations = '{"en": "Which of our differences makes us a better team?", "da": "Hvem af os siger f\u00f8rst undskyld efter et sk\u00e6nderi?", "de": "Wer von uns entschuldigt sich als Erstes nach einem Streit?", "es": "\u00bfQui\u00e9n de los dos pide perd\u00f3n primero despu\u00e9s de una pelea?", "pt": "Qual de n\u00f3s pede desculpa primeiro depois de uma discuss\u00e3o?", "ro": "Cine dintre noi \u00ee\u0219i cere primul scuze dup\u0103 o ceart\u0103?", "fr": "Lequel de nous s\u2019excuse en premier apr\u00e8s une dispute ?", "it": "Quale delle nostre differenze ci rende un team migliore?", "fi": "Mitk\u00e4 eromme tekev\u00e4t meist\u00e4 paremman tiimin?", "nl": "Welke van onze verschillen maakt ons een beter team?", "no": "Hvilke av v\u00e5re forskjeller gj\u00f8r oss til et bedre team?", "sv": "Vilka av v\u00e5ra olikheter g\u00f6r oss till ett b\u00e4ttre team?", "pl": "Kt\u00f3ra z naszych r\u00f3\u017cnic sprawia, \u017ce jeste\u015bmy lepszym zespo\u0142em?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Which of our differences makes us a better team?';
UPDATE questions
SET translations = '{"en": "What\u2019s a tiny habit of ours that you hope never fades?", "da": "Hvem af os er mest tilb\u00f8jelig til at foresl\u00e5 noget spontant?", "de": "Wer von uns schl\u00e4gt eher etwas Spontanes vor?", "es": "\u00bfQui\u00e9n de los dos es m\u00e1s propenso/a a sugerir algo espont\u00e1neo?", "pt": "Qual de n\u00f3s \u00e9 mais prov\u00e1vel sugerir algo espont\u00e2neo?", "ro": "Cine dintre noi e mai probabil s\u0103 propun\u0103 ceva spontan?", "fr": "Lequel de nous est le plus susceptible de proposer quelque chose de spontan\u00e9 ?", "it": "Qual \u00e8 una nostra piccola abitudine che speri non svanisca mai?", "fi": "Mik\u00e4 on pieni tapamme, jonka toivot, ettei se koskaan h\u00e4vi\u00e4?", "nl": "Wat is een klein gewoonte van ons waarvan je hoopt dat het nooit verdwijnt?", "no": "Hva er en liten vane vi har som du h\u00e5per aldri forsvinner?", "sv": "Vilken liten vana hos oss hoppas du aldrig f\u00f6rsvinner?", "pl": "Jaki\u015b ma\u0142y nawyk, kt\u00f3ry mamy, a kt\u00f3ry mam nadziej\u0119, \u017ce nigdy nie zniknie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a tiny habit of ours that you hope never fades?';
UPDATE questions
SET translations = '{"en": "When do you feel proud of who we are together?", "da": "Hvilken af dine kvaliteter tror du, jeg v\u00e6rds\u00e6tter mest?", "de": "Welche deiner Eigenschaften glaubst du, sch\u00e4tze ich am meisten?", "es": "\u00bfQu\u00e9 cualidad tuya crees que valoro m\u00e1s?", "pt": "Que qualidade sua voc\u00ea acha que eu mais valorizo?", "ro": "Care calitate a ta crezi c\u0103 o apreciez cel mai mult?", "fr": "Quelle qualit\u00e9 chez toi penses-tu que j\u2019appr\u00e9cie le plus ?", "it": "Quando ti senti orgoglioso di chi siamo insieme?", "fi": "Milloin tunnet ylpeytt\u00e4 siit\u00e4, keit\u00e4 me olemme yhdess\u00e4?", "nl": "Wanneer voel je je trots op wie we samen zijn?", "no": "N\u00e5r f\u00f8ler du deg stolt av hvem vi er sammen?", "sv": "N\u00e4r k\u00e4nner du dig stolt \u00f6ver vilka vi \u00e4r tillsammans?", "pl": "Kiedy czujesz dum\u0119 z tego, kim jeste\u015bmy razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When do you feel proud of who we are together?';
UPDATE questions
SET translations = '{"en": "Describe your ideal romantic vacation", "da": "Hvilket minde om os tror du stadig vil f\u00e5 dig til at smile, n\u00e5r du er 90?", "de": "Welche Erinnerung an uns wird dich deiner Meinung nach noch zum L\u00e4cheln bringen, wenn du 90 bist?", "es": "\u00bfQu\u00e9 recuerdo nuestro crees que todav\u00eda te har\u00e1 sonre\u00edr cuando tengas 90 a\u00f1os?", "pt": "Qual lembran\u00e7a nossa voc\u00ea acredita que ainda vai fazer voc\u00ea sorrir quando tiver 90 anos?", "ro": "Care este o amintire cu noi despre care crezi c\u0103 \u00eenc\u0103 te va face s\u0103 z\u00e2mbe\u0219ti c\u00e2nd vei avea 90 de ani?", "fr": "Quel souvenir de nous crois-tu te fera encore sourire quand tu auras 90 ans ?", "it": "Descrivi la tua vacanza romantica ideale.", "fi": "Kuvaile ihanteellista romanttista lomaa.", "nl": "Beschrijf je ideale romantische vakantie.", "no": "Beskriv din ideelle romantiske ferie.", "sv": "Beskriv din idealiska romantiska semester.", "pl": "Opisz swoje idealne romantyczne wakacje."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Describe your ideal romantic vacation';
UPDATE questions
SET translations = '{"en": "What do you think people say about us when we are not around?", "da": "Hvordan viser du k\u00e6rlighed, n\u00e5r ord ikke f\u00f8les nok?", "de": "Wie zeigst du Liebe, wenn Worte sich nicht genug anf\u00fchlen?", "es": "\u00bfC\u00f3mo demuestras amor cuando las palabras no parecen suficientes?", "pt": "Como voc\u00ea demonstra amor quando as palavras n\u00e3o parecem suficientes?", "ro": "Cum ar\u0103\u021bi iubire atunci c\u00e2nd cuvintele nu par suficiente?", "fr": "Comment montres-tu ton amour quand les mots ne suffisent pas ?", "it": "Cosa pensi che la gente dica di noi quando non ci siamo?", "fi": "Mit\u00e4 luulet, mit\u00e4 ihmiset sanovat meist\u00e4, kun emme ole l\u00e4sn\u00e4?", "nl": "Wat denk je dat mensen over ons zeggen als we er niet zijn?", "no": "Hva tror du folk sier om oss n\u00e5r vi ikke er til stede?", "sv": "Vad tror du att folk s\u00e4ger om oss n\u00e4r vi inte \u00e4r i n\u00e4rheten?", "pl": "Co my\u015blisz, co ludzie m\u00f3wi\u0105 o nas, gdy nas nie ma?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What do you think people say about us when we are not around?';
UPDATE questions
SET translations = '{"en": "Which of us needs more affection to feel connected?", "da": "Hvem af os har brug for mest k\u00e6rlighed og omsorg for at f\u00f8le sig forbundet?", "de": "Wer von uns braucht mehr Zuneigung, um sich verbunden zu f\u00fchlen?", "es": "\u00bfQui\u00e9n de los dos necesita m\u00e1s cari\u00f1o para sentirse conectado/a?", "pt": "Qual de n\u00f3s precisa de mais carinho para se sentir conectado(a)?", "ro": "Cine dintre noi are nevoie de mai mult\u0103 afec\u021biune ca s\u0103 se simt\u0103 conectat(\u0103)?", "fr": "Lequel de nous a besoin de plus d\u2019affection pour se sentir connect\u00e9(e) ?", "it": "Quale di noi ha bisogno di pi\u00f9 affetto per sentirsi connesso?", "fi": "Kumpi meist\u00e4 tarvitsee enemm\u00e4n rakkautta tunteakseen yhteytt\u00e4?", "nl": "Wie van ons heeft meer genegenheid nodig om zich verbonden te voelen?", "no": "Hvem av oss trenger mer kj\u00e6rlighet for \u00e5 f\u00f8le seg knyttet?", "sv": "Vilken av oss beh\u00f6ver mer k\u00e4rlek f\u00f6r att k\u00e4nna sig kopplad?", "pl": "Kt\u00f3ry z nas potrzebuje wi\u0119cej czu\u0142o\u015bci, aby poczu\u0107 si\u0119 po\u0142\u0105czonym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Which of us needs more affection to feel connected?';