UPDATE questions
SET translations = '{"en": "If we ran a tiny bed-and-breakfast, what would guests remember most?", "da": "Hvis vi drev et lille bed-and-breakfast, hvad ville g\u00e6sterne huske bedst?", "de": "Wenn wir ein kleines Bed-and-Breakfast h\u00e4tten, woran w\u00fcrden sich die G\u00e4ste am meisten erinnern?", "es": "Si dirigi\u00e9ramos un peque\u00f1o bed and breakfast, \u00bfqu\u00e9 recordar\u00edan m\u00e1s los hu\u00e9spedes?", "pt": "Se tiv\u00e9ssemos uma pousada, do que os h\u00f3spedes se lembrariam mais?", "ro": "Dac\u0103 am avea un mic bed-and-breakfast, ce ar \u021bine minte oaspe\u021bii?", "fr": "Si nous tenions une petite chambre d\u2019h\u00f4tes, de quoi les invit\u00e9s se souviendraient-ils le plus ?", "it": "Se gestissimo un piccolo bed & breakfast, che cosa ricorderebbero di pi\u00f9 gli ospiti?", "fi": "Jos pit\u00e4isimme pient\u00e4 bed & breakfastia, mink\u00e4 vieraat muistaisivat meist\u00e4 parhaiten?", "nl": "Als wij een klein bed & breakfast zouden runnen, wat zouden gasten zich dan het meest van ons herinneren?", "no": "Hvis vi drev et lite bed & breakfast, hva tror du gjestene ville husket best?", "sv": "Om vi drev ett litet bed and breakfast, vad skulle g\u00e4sterna minnas mest?", "pl": "Gdyby\u015bmy prowadzili ma\u0142y pensjonat typu bed & breakfast, co go\u015bcie zapami\u0119taliby najbardziej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we ran a tiny bed-and-breakfast, what would guests remember most?';
UPDATE questions
SET translations = '{"en": "If our car had a personality, what would its love language be?", "da": "Hvis vores bil havde en personlighed, hvad ville dens k\u00e6rlighedssprog v\u00e6re?", "de": "Wenn unser Auto eine Pers\u00f6nlichkeit h\u00e4tte, welche Liebessprache h\u00e4tte es?", "es": "Si nuestro coche tuviera personalidad, \u00bfcu\u00e1l ser\u00eda su lenguaje del amor?", "pt": "Se nosso carro tivesse personalidade, qual seria sua linguagem do amor?", "ro": "Dac\u0103 ma\u0219ina noastr\u0103 ar avea o personalitate, care ar fi limbajul ei al iubirii?", "fr": "Si notre voiture avait une personnalit\u00e9, quel serait son langage de l\u2019amour ?", "it": "Se la nostra macchina avesse una personalit\u00e0, quale sarebbe il suo linguaggio dell\u2019amore?", "fi": "Jos meid\u00e4n autolla olisi persoona, mik\u00e4 olisi sen rakkauden kieli?", "nl": "Als onze auto een persoonlijkheid had, wat zou zijn liefdestaal zijn?", "no": "Hvis bilen v\u00e5r hadde en personlighet, hva ville kj\u00e6rlighetsspr\u00e5ket dens v\u00e6rt?", "sv": "Om v\u00e5r bil hade en personlighet, vilket skulle dess k\u00e4rleksspr\u00e5k vara?", "pl": "Gdyby nasz samoch\u00f3d mia\u0142 osobowo\u015b\u0107, jakim \u201ej\u0119zykiem mi\u0142o\u015bci\u201d by si\u0119 pos\u0142ugiwa\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If our car had a personality, what would its love language be?';
UPDATE questions
SET translations = '{"en": "What three emojis summarize your travel style?", "da": "Hvilke tre emojis opsummerer din rejse-stil?", "de": "Welche drei Emojis beschreiben deinen Reisestil?", "es": "\u00bfQu\u00e9 tres emojis resumen tu estilo de viaje?", "pt": "Quais tr\u00eas emojis resumem seu estilo de viagem?", "ro": "Care trei emoji \u00ee\u021bi rezum\u0103 stilul de c\u0103l\u0103torie?", "fr": "Quels trois emojis r\u00e9sument ton style de voyage ?", "it": "Quali tre emoji riassumono il tuo stile di viaggio?", "fi": "Mitk\u00e4 kolme emojia kuvaavat parhaiten matkustustyyli\u00e4si?", "nl": "Welke drie emoji\u2019s vatten jouw reisstijl samen?", "no": "Hvilke tre emojier oppsummerer reisestilen din?", "sv": "Vilka tre emojis sammanfattar din resestil?", "pl": "Jakie trzy emoji podsumowuj\u0105 tw\u00f3j styl podr\u00f3\u017cowania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What three emojis summarize your travel style?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell that takes you straight back to childhood?", "da": "Hvilken duft sender dig direkte tilbage til barndommen?", "de": "Welcher Geruch versetzt dich sofort in deine Kindheit zur\u00fcck?", "es": "\u00bfQu\u00e9 olor te transporta directamente a tu infancia?", "pt": "Que cheiro te leva diretamente de volta \u00e0 inf\u00e2ncia?", "ro": "Ce miros te trimite direct \u00een copil\u0103rie?", "fr": "Quelle odeur te ram\u00e8ne directement \u00e0 ton enfance ?", "it": "Quale odore ti riporta immediatamente all\u2019infanzia?", "fi": "Mik\u00e4 tuoksu vie sinut suoraan takaisin lapsuuteen?", "nl": "Welke geur brengt je meteen terug naar je kindertijd?", "no": "Hvilken lukt sender deg rett tilbake til barndommen?", "sv": "Vilken doft tar dig direkt tillbaka till barndomen?", "pl": "Jaki zapach przenosi ci\u0119 prosto do dzieci\u0144stwa?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a smell that takes you straight back to childhood?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite \u201cdo nothing\u201d activity \u2014 the thing that totally recharges you?", "da": "Hvad er din yndlings \u201clav ingenting\u201d-aktivitet \u2014 den der virkelig lader dig op?", "de": "Was ist deine Lieblings-\u201eNichts-tun\u201c-Aktivit\u00e4t \u2013 die, die dich wirklich aufl\u00e4dt?", "es": "\u00bfCu\u00e1l es tu actividad favorita de \u201cno hacer nada\u201d, la que realmente te recarga?", "pt": "Qual \u00e9 a sua atividade favorita de \u201cn\u00e3o fazer nada\u201d \u2014 que te recarrega totalmente?", "ro": "Care este activitatea ta preferat\u0103 de \u201ea nu face nimic\u201d \u2014 cea care te re\u00eencarc\u0103 complet?", "fr": "Quelle est ton activit\u00e9 \u00ab ne rien faire \u00bb pr\u00e9f\u00e9r\u00e9e \u2014 celle qui te ressource compl\u00e8tement ?", "it": "Qual \u00e8 la tua attivit\u00e0 preferita da \u201cnon fare niente\u201d, quella che ti ricarica del tutto?", "fi": "Mik\u00e4 on lempisi \u201cen tee mit\u00e4\u00e4n\u201d -aktiviteetti \u2013 se, joka lataa akut t\u00e4ysin?", "nl": "Wat is je favoriete \u201cniks doen\u201d-activiteit \u2013 die ene die je helemaal oplaadt?", "no": "Hva er din favoritt-\u00abgj\u00f8re ingenting\u00bb-aktivitet \u2013 den som virkelig lader deg opp?", "sv": "Vad \u00e4r din favorit-\u201dg\u00f6ra ingenting\u201d-aktivitet \u2013 den som verkligen laddar dig?", "pl": "Jaka jest twoja ulubiona aktywno\u015b\u0107 \u201enicnierobienia\u201d \u2013 ta, kt\u00f3ra naprawd\u0119 ci\u0119 \u0142aduje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s your favorite “do nothing” activity — the thing that totally recharges you?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing that instantly puts you in a good mood, no matter what?", "da": "Hvad f\u00e5r dig straks i godt hum\u00f8r, uanset hvad?", "de": "Was bringt dich sofort in gute Laune, egal was passiert?", "es": "\u00bfQu\u00e9 cosa te pone instant\u00e1neamente de buen humor, sin importar qu\u00e9?", "pt": "O que te p\u00f5e imediatamente de bom humor, aconte\u00e7a o que acontecer?", "ro": "Ce te binedispune instantaneu, indiferent de situa\u021bie?", "fr": "Qu\u2019est-ce qui te met instantan\u00e9ment de bonne humeur, peu importe quoi ?", "it": "Qual \u00e8 una cosa che ti mette subito di buon umore, a prescindere da tutto?", "fi": "Mik\u00e4 yksi juttu tekee sinut heti hyv\u00e4lle tuulelle, tilanteesta riippumatta?", "nl": "Wat is \u00e9\u00e9n ding dat je meteen in een goed humeur brengt, wat er ook gebeurt?", "no": "Hva er \u00e9n ting som alltid f\u00e5r deg i godt hum\u00f8r, uansett?", "sv": "Vad \u00e4r en sak som direkt g\u00f6r dig p\u00e5 gott hum\u00f6r, oavsett vad?", "pl": "Co jest jedn\u0105 rzecz\u0105, kt\u00f3ra natychmiast poprawia ci humor, niezale\u017cnie od wszystkiego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s one thing that instantly puts you in a good mood, no matter what?';
UPDATE questions
SET translations = '{"en": "Ever forgotten something on a camping trip that you really needed?", "da": "Har du nogensinde glemt noget p\u00e5 en campingtur, som du virkelig havde brug for?", "de": "Hast du jemals etwas auf einem Campingausflug vergessen, das du wirklich gebraucht h\u00e4ttest?", "es": "\u00bfAlguna vez olvidaste algo en un campamento que realmente necesitabas?", "pt": "Voc\u00ea j\u00e1 esqueceu algo em um acampamento que realmente precisava?", "ro": "Ai uitat vreodat\u0103 ceva \u00eentr-o excursie cu cortul de care aveai mare nevoie?", "fr": "As-tu d\u00e9j\u00e0 oubli\u00e9 quelque chose d\u2019essentiel en camping ?", "it": "Ti \u00e8 mai capitato di dimenticare qualcosa in campeggio di cui avevi davvero bisogno?", "fi": "Oletko koskaan unohtanut jotain leirireissulle, mit\u00e4 oikeasti tarvitsit?", "nl": "Ben je ooit op kampeertrip iets vergeten dat je echt nodig had?", "no": "Har du noen gang glemt noe p\u00e5 campingtur som du virkelig trengte?", "sv": "Har du n\u00e5gonsin gl\u00f6mt n\u00e5got p\u00e5 en campingresa som du verkligen beh\u00f6vde?", "pl": "Zdarzy\u0142o ci si\u0119 kiedy\u015b zapomnie\u0107 na biwak czego\u015b, czego naprawd\u0119 potrzebowa\u0142e\u015b/potrzebowa\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Ever forgotten something on a camping trip that you really needed?';
UPDATE questions
SET translations = '{"en": "How do you balance plans vs. spontaneity on a trip?", "da": "Hvordan balancerer du planer vs. spontanitet p\u00e5 en rejse?", "de": "Wie balancierst du Planung und Spontaneit\u00e4t auf einer Reise?", "es": "\u00bfC\u00f3mo equilibras los planes y la espontaneidad en un viaje?", "pt": "Como equilibras planos e espontaneidade numa viagem?", "ro": "Cum echilibrezi planurile \u0219i spontaneitatea \u00eentr-o excursie?", "fr": "Comment \u00e9quilibres-tu les plans et la spontan\u00e9it\u00e9 lors d\u2019un voyage ?", "it": "Come bilanci i piani e la spontaneit\u00e0 in viaggio?", "fi": "Miten tasapainotat suunnitelmat ja spontaaniuden matkalla?", "nl": "Hoe balanceer jij plannen maken en spontaniteit op reis?", "no": "Hvordan balanserer du planer og spontanitet p\u00e5 tur?", "sv": "Hur balanserar du planering och spontanitet p\u00e5 en resa?", "pl": "Jak \u0142\u0105czysz planowanie ze spontaniczno\u015bci\u0105 w podr\u00f3\u017cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'How do you balance plans vs. spontaneity on a trip?';
UPDATE questions
SET translations = '{"en": "What\u2019s our optimal roles on a long drive (e.g. captain, DJ, snack provider, etc)?", "da": "Hvad er vores optimale roller p\u00e5 en lang k\u00f8retur (f.eks. kaptajn, DJ, snack-ansvarlig osv.)?", "de": "Was sind unsere optimalen Rollen auf einer langen Fahrt (z. B. Kapit\u00e4n, DJ, Snacklieferant usw.)?", "es": "\u00bfCu\u00e1les son nuestros roles ideales en un viaje largo (por ejemplo, capit\u00e1n, DJ, proveedor de snacks, etc.)?", "pt": "Quais s\u00e3o os nossos pap\u00e9is ideais numa longa viagem (por exemplo, capit\u00e3o, DJ, fornecedor de snacks, etc.)?", "ro": "Care sunt rolurile noastre ideale \u00eentr-o c\u0103l\u0103torie lung\u0103 (ex: c\u0103pitan, DJ, furnizor de gust\u0103ri etc.)?", "fr": "Quels sont nos r\u00f4les id\u00e9aux lors d\u2019un long trajet (ex : capitaine, DJ, fournisseur de snacks, etc.) ?", "it": "Quali sarebbero i nostri ruoli ideali in un lungo viaggio in auto (es. capitano, DJ, addetto agli snack, ecc.)?", "fi": "Mitk\u00e4 ovat meille parhaat roolit pitk\u00e4ll\u00e4 ajomatkalla (esim. kapteeni, DJ, v\u00e4lipalavastaava jne.)?", "nl": "Wat zijn onze ideale rollen tijdens een lange autorit (bijv. kapitein, DJ, snack-leverancier, etc.)?", "no": "Hva er v\u00e5re optimale roller p\u00e5 en lang biltur (f.eks. kaptein, DJ, snacksansvarlig osv.)?", "sv": "Vilka \u00e4r v\u00e5ra optimala roller p\u00e5 en l\u00e5ng bilresa (t.ex. kapten, DJ, snacksansvarig osv.)?", "pl": "Jakie s\u0105 dla nas idealne role podczas d\u0142ugiej jazdy autem (np. kapitan, DJ, dostawca przek\u0105sek itp.)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s our optimal roles on a long drive (e.g. captain, DJ, snack provider, etc)?';
UPDATE questions
SET translations = '{"en": "What\u2019s a moment when you felt totally fearless?", "da": "Hvorn\u00e5r f\u00f8lte du dig helt frygtl\u00f8s?", "de": "Wann hast du dich v\u00f6llig furchtlos gef\u00fchlt?", "es": "\u00bfCu\u00e1ndo te has sentido completamente sin miedo?", "pt": "Quando te sentiste totalmente destemido(a)?", "ro": "C\u00e2nd te-ai sim\u021bit complet ne\u00eenfricat(\u0103)?", "fr": "\u00c0 quel moment t\u2019es-tu senti(e) totalement sans peur ?", "it": "Racconta un momento in cui ti sei sentito/a totalmente senza paura.", "fi": "Kerro hetki, jolloin tunsit olosi t\u00e4ysin pelottomaksi.", "nl": "Noem een moment waarop je je totaal onbevreesd voelde.", "no": "Fortell om et \u00f8yeblikk der du f\u00f8lte deg helt fryktl\u00f8s.", "sv": "Ber\u00e4tta om ett tillf\u00e4lle d\u00e5 du k\u00e4nde dig helt or\u00e4dd.", "pl": "Opowiedz o chwili, kiedy czu\u0142e\u015b/czu\u0142a\u015b si\u0119 ca\u0142kowicie nieustraszony/a."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a moment when you felt totally fearless?';
UPDATE questions
SET translations = '{"en": "Describe your dream scenic route and what we\u2019d do there.", "da": "Beskriv din dr\u00f8mmesceniske rute og hvad vi ville g\u00f8re der.", "de": "Beschreibe deine Traumroute und was wir dort tun w\u00fcrden.", "es": "Describe tu ruta esc\u00e9nica de ensue\u00f1o y qu\u00e9 har\u00edamos all\u00ed.", "pt": "Descreve a tua rota panor\u00e2mica de sonho e o que far\u00edamos l\u00e1.", "ro": "Descrie traseul t\u0103u de vis \u0219i ce am face acolo.", "fr": "D\u00e9cris ton itin\u00e9raire de r\u00eave et ce qu\u2019on y ferait.", "it": "Descrivi il tuo percorso panoramico da sogno e cosa faremmo l\u00ec.", "fi": "Kuvaile unelmiesi maisemareitti ja mit\u00e4 tekisimme siell\u00e4.", "nl": "Beschrijf je droom-scenische route en wat we daar zouden doen.", "no": "Beskriv dr\u00f8mmeruten din med fin utsikt, og hva vi skulle gjort der.", "sv": "Beskriv din dr\u00f6mmiga natursk\u00f6na rutt och vad vi skulle g\u00f6ra d\u00e4r.", "pl": "Opisz swoj\u0105 wymarzon\u0105 widokow\u0105 tras\u0119 i to, co by\u015bmy tam robili."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Describe your dream scenic route and what we’d do there.';
UPDATE questions
SET translations = '{"en": "What\u2019s the strangest or funniest dream you\u2019ve ever had?", "da": "Hvad er den m\u00e6rkeligste eller sjoveste dr\u00f8m, du nogensinde har haft?", "de": "Was ist der seltsamste oder lustigste Traum, den du je hattest?", "es": "\u00bfCu\u00e1l es el sue\u00f1o m\u00e1s extra\u00f1o o divertido que has tenido?", "pt": "Qual foi o sonho mais estranho ou engra\u00e7ado que j\u00e1 tiveste?", "ro": "Care este cel mai ciudat sau amuzant vis pe care l-ai avut vreodat\u0103?", "fr": "Quel est le r\u00eave le plus \u00e9trange ou le plus dr\u00f4le que tu aies jamais fait ?", "it": "Qual \u00e8 il sogno pi\u00f9 strano o pi\u00f9 divertente che tu abbia mai fatto?", "fi": "Mik\u00e4 on oudoin tai hauskin uni, jonka olet koskaan n\u00e4hnyt?", "nl": "Wat is de vreemdste of grappigste droom die je ooit hebt gehad?", "no": "Hva er den rareste eller morsomste dr\u00f8mmen du har hatt?", "sv": "Vad \u00e4r den konstigaste eller roligaste dr\u00f6m du n\u00e5gonsin haft?", "pl": "Jaki jest najdziwniejszy albo najzabawniejszy sen, jaki kiedykolwiek mia\u0142e\u015b/mia\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s the strangest or funniest dream you’ve ever had?';
UPDATE questions
SET translations = '{"en": "Window or aisle? Why? ", "da": "Vindues- eller gangplads? Hvorfor?", "de": "Fenster- oder Gangplatz? Warum?", "es": "\u00bfVentana o pasillo? \u00bfPor qu\u00e9?", "pt": "Janela ou corredor? Por qu\u00ea?", "ro": "Loc la geam sau la culoar? De ce?", "fr": "Hublot ou couloir ? Pourquoi ?", "it": "Finestrino o corridoio? Perch\u00e9?", "fi": "Ikkunapaikka vai k\u00e4yt\u00e4v\u00e4paikka? Miksi?", "nl": "Raam of gangpad? Waarom?", "no": "Vindusplass eller midtgang? Hvorfor?", "sv": "F\u00f6nsterplats eller g\u00e5ngplats? Varf\u00f6r?", "pl": "Miejsce przy oknie czy przy przej\u015bciu? Dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Window or aisle? Why? ';
UPDATE questions
SET translations = '{"en": "If we detour two hours for an epic meal \u2013 would you think it\u2019s worth it? Why?", "da": "Hvis vi tager en omvej p\u00e5 to timer for et episk m\u00e5ltid \u2013 synes du, det er det v\u00e6rd? Hvorfor?", "de": "Wenn wir zwei Stunden Umweg f\u00fcr ein episches Essen machen \u2013 w\u00fcrdest du denken, es lohnt sich? Warum?", "es": "Si desviamos dos horas por una comida \u00e9pica, \u00bfcrees que valdr\u00eda la pena? \u00bfPor qu\u00e9?", "pt": "Se fizermos um desvio de duas horas por uma refei\u00e7\u00e3o \u00e9pica, achas que vale a pena? Porqu\u00ea?", "ro": "Dac\u0103 am face un ocol de dou\u0103 ore pentru o mas\u0103 epic\u0103, ai crede c\u0103 merit\u0103? De ce?", "fr": "Si on faisait un d\u00e9tour de deux heures pour un repas \u00e9pique \u2013 tu penserais que \u00e7a en vaut la peine ? Pourquoi ?", "it": "Se facessimo una deviazione di due ore per un pasto epico, penseresti che ne vale la pena? Perch\u00e9?", "fi": "Jos kiert\u00e4isimme kaksi tuntia paremman aterian takia, olisiko se sinusta sen arvoista? Miksi?", "nl": "Als we twee uur zouden omrijden voor een legendarische maaltijd \u2013 zou jij vinden dat het de moeite waard is? Waarom?", "no": "Hvis vi hadde kj\u00f8rt to timer ekstra for et episk m\u00e5ltid \u2013 hadde du syntes det var verdt det? Hvorfor?", "sv": "Om vi gjorde en tv\u00e5 timmar l\u00e5ng omv\u00e4g f\u00f6r en episk m\u00e5ltid \u2013 skulle du tycka att det var v\u00e4rt det? Varf\u00f6r?", "pl": "Gdyby\u015bmy nad\u0142o\u017cyli dwie godziny drogi dla epickiego posi\u0142ku \u2013 uzna\u0142(a)by\u015b, \u017ce by\u0142o warto? Dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we detour two hours for an epic meal – would you think it’s worth it? Why?';
UPDATE questions
SET translations = '{"en": "What was your most peaceful travel moment?", "da": "Hvad var dit mest fredfyldte rejse\u00f8jeblik?", "de": "Was war dein friedlichster Reisemoment?", "es": "\u00bfCu\u00e1l fue tu momento de viaje m\u00e1s tranquilo?", "pt": "Qual foi o teu momento de viagem mais pac\u00edfico?", "ro": "Care a fost cel mai lini\u0219tit moment al t\u0103u dintr-o c\u0103l\u0103torie?", "fr": "Quel a \u00e9t\u00e9 ton moment de voyage le plus paisible ?", "it": "Qual \u00e8 stato il tuo momento di viaggio pi\u00f9 pacifico?", "fi": "Mik\u00e4 on rauhallisin matkamuistosi?", "nl": "Wat was je meest vredige reis-moment?", "no": "Hva var ditt mest fredfulle reiseminne?", "sv": "Vad var ditt mest fridfulla rese\u00f6gonblick?", "pl": "Jaki by\u0142 tw\u00f3j najbardziej spokojny moment w podr\u00f3\u017cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What was your most peaceful travel moment?';
UPDATE questions
SET translations = '{"en": "What movie or book do you wish you could erase from memory just to experience again for the first time?", "da": "Hvilken film eller bog ville du \u00f8nske, du kunne slette fra hukommelsen bare for at opleve den igen for f\u00f8rste gang?", "de": "Welchen Film oder welches Buch w\u00fcrdest du gern aus deinem Ged\u00e4chtnis l\u00f6schen, um es zum ersten Mal wieder zu erleben?", "es": "\u00bfQu\u00e9 pel\u00edcula o libro desear\u00edas poder borrar de tu memoria para experimentarlo de nuevo por primera vez?", "pt": "Que filme ou livro gostarias de apagar da mem\u00f3ria para o viver novamente pela primeira vez?", "ro": "Ce film sau carte \u021bi-ai dori s\u0103 o \u0219tergi din memorie doar pentru a o retr\u0103i pentru prima dat\u0103?", "fr": "Quel film ou livre aimerais-tu effacer de ta m\u00e9moire pour le revivre comme la premi\u00e8re fois ?", "it": "Quale film o libro vorresti poter cancellare dalla memoria solo per riviverlo di nuovo per la prima volta?", "fi": "Mink\u00e4 elokuvan tai kirjan pyyhkisit mielest\u00e4si vain siksi, ett\u00e4 saisit kokea sen uudestaan ensimm\u00e4ist\u00e4 kertaa?", "nl": "Welke film of welk boek zou je uit je geheugen willen wissen, alleen maar om het nog \u00e9\u00e9n keer voor het eerst te ervaren?", "no": "Hvilken film eller bok skulle du \u00f8nske du kunne slette fra minnet bare for \u00e5 oppleve den p\u00e5 nytt for f\u00f8rste gang?", "sv": "Vilken film eller bok skulle du vilja radera ur minnet bara f\u00f6r att f\u00e5 uppleva den igen f\u00f6r f\u00f6rsta g\u00e5ngen?", "pl": "Jaki film albo jak\u0105 ksi\u0105\u017ck\u0119 chcia\u0142(a)by\u015b wymaza\u0107 z pami\u0119ci tylko po to, \u017ceby prze\u017cy\u0107 j\u0105 jeszcze raz po raz pierwszy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What movie or book do you wish you could erase from memory just to experience again for the first time?';
UPDATE questions
SET translations = '{"en": "If we had to stop and live in one of the towns we pass, what would convince you to stay?", "da": "Hvis vi skulle stoppe og bo i en af byerne, vi passerer, hvad ville overbevise dig om at blive?", "de": "Wenn wir in einer der St\u00e4dte, an denen wir vorbeifahren, leben m\u00fcssten \u2013 was w\u00fcrde dich \u00fcberzeugen zu bleiben?", "es": "Si tuvi\u00e9ramos que parar y vivir en una de las ciudades por las que pasamos, \u00bfqu\u00e9 te convencer\u00eda de quedarte?", "pt": "Se tiv\u00e9ssemos de parar e viver numa das cidades por onde passamos, o que te convenceria a ficar?", "ro": "Dac\u0103 ar trebui s\u0103 ne oprim \u0219i s\u0103 tr\u0103im \u00eentr-unul dintre ora\u0219ele prin care trecem, ce te-ar convinge s\u0103 r\u0103m\u00e2i?", "fr": "Si on devait s\u2019arr\u00eater et vivre dans une des villes qu\u2019on traverse, qu\u2019est-ce qui te convaincrait d\u2019y rester ?", "it": "Se dovessimo fermarci a vivere in una delle citt\u00e0 che attraversiamo, cosa ti convincerebbe a restare?", "fi": "Jos meid\u00e4n pit\u00e4isi pys\u00e4hty\u00e4 ja j\u00e4\u00e4d\u00e4 asumaan johonkin ohittamaamme kaupunkiin, mik\u00e4 saisi sinut j\u00e4\u00e4m\u00e4\u00e4n?", "nl": "Als we moesten stoppen en in \u00e9\u00e9n van de plaatsen gaan wonen waar we langs komen, wat zou jou overtuigen om te blijven?", "no": "Hvis vi m\u00e5tte stoppe og bo i en av byene vi kj\u00f8rer gjennom, hva skulle til for at du ble?", "sv": "Om vi var tvungna att stanna och bo i en av st\u00e4derna vi passerar, vad skulle f\u00e5 dig att vilja stanna kvar?", "pl": "Gdyby\u015bmy musieli zatrzyma\u0107 si\u0119 i zamieszka\u0107 w jednym z mijanych miasteczek, co przekona\u0142oby ci\u0119, \u017ceby zosta\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we had to stop and live in one of the towns we pass, what would convince you to stay?';
UPDATE questions
SET translations = '{"en": "What\u2019s a family tradition you actually really love?", "da": "Hvad er en familietradition, du faktisk virkelig elsker?", "de": "Welche Familientradition liebst du wirklich?", "es": "\u00bfQu\u00e9 tradici\u00f3n familiar realmente te encanta?", "pt": "Qual \u00e9 uma tradi\u00e7\u00e3o familiar que realmente adoras?", "ro": "Care este o tradi\u021bie de familie pe care chiar o iube\u0219ti?", "fr": "Quelle tradition familiale aimes-tu vraiment ?", "it": "Qual \u00e8 una tradizione di famiglia che in realt\u00e0 ami davvero?", "fi": "Mik\u00e4 on sellainen perinne, josta perheess\u00e4si oikeasti pid\u00e4t?", "nl": "Welke familietraditie vind je stiekem echt heel leuk?", "no": "Hvilken familietradisjon liker du faktisk veldig godt?", "sv": "Vilken familjetradition tycker du faktiskt riktigt mycket om?", "pl": "Jaka rodzinna tradycja naprawd\u0119 bardzo ci si\u0119 podoba?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a family tradition you actually really love?';
UPDATE questions
SET translations = '{"en": "If we created a tourist attraction in our neighborhood, what would it be?", "da": "Hvis vi lavede en turistattraktion i vores nabolag, hvad ville det v\u00e6re?", "de": "Wenn wir in unserer Nachbarschaft eine Touristenattraktion schaffen w\u00fcrden, was w\u00e4re das?", "es": "Si cre\u00e1ramos una atracci\u00f3n tur\u00edstica en nuestro vecindario, \u00bfqu\u00e9 ser\u00eda?", "pt": "Se cri\u00e1ssemos uma atra\u00e7\u00e3o tur\u00edstica no nosso bairro, o que seria?", "ro": "Dac\u0103 am crea o atrac\u021bie turistic\u0103 \u00een cartierul nostru, care ar fi aceasta?", "fr": "Si on cr\u00e9ait une attraction touristique dans notre quartier, ce serait quoi ?", "it": "Se creassimo un\u2019attrazione turistica nel nostro quartiere, che cosa sarebbe?", "fi": "Jos loisimme turistin\u00e4ht\u00e4vyyden omaan naapurustoomme, mik\u00e4 se olisi?", "nl": "Als we in onze buurt een toeristische attractie zouden cre\u00ebren, wat zou dat zijn?", "no": "Hvis vi lagde en turistattraksjon i nabolaget v\u00e5rt, hva ville den v\u00e6rt?", "sv": "Om vi skapade en turistattraktion i v\u00e5rt kvarter, vad skulle det vara?", "pl": "Gdyby\u015bmy stworzyli atrakcj\u0119 turystyczn\u0105 w naszej okolicy, czym by by\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we created a tourist attraction in our neighborhood, what would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s your \u201ccomfort smell\u201d and where does it take you?", "da": "Hvad er din \u201ckomfortduft\u201d, og hvor f\u00f8rer den dig hen?", "de": "Was ist dein \u201eKomfortgeruch\u201c und wohin bringt er dich?", "es": "\u00bfCu\u00e1l es tu \u201color de confort\u201d y a d\u00f3nde te lleva?", "pt": "Qual \u00e9 o teu \u201ccheiro de conforto\u201d e para onde te leva?", "ro": "Care este mirosul t\u0103u de confort \u0219i unde te poart\u0103 el?", "fr": "Quelle est ton \u201codeur de confort\u201d et o\u00f9 t\u2019emm\u00e8ne-t-elle ?", "it": "Qual \u00e8 il tuo \u201cprofumo di comfort\u201d e dove ti porta?", "fi": "Mik\u00e4 on sinun \u201clohtutuoksusi\u201d ja minne se sinut vie?", "nl": "Wat is jouw \u201ccomfort-geur\u201d en waar brengt die je naartoe?", "no": "Hva er din \u00abcomfort-lukt\u00bb, og hvor tar den deg?", "sv": "Vad \u00e4r din \u201dcomfort-doft\u201d och vart tar den dig?", "pl": "Jaki jest tw\u00f3j \u201ezapach komfortu\u201d i dok\u0105d ci\u0119 przenosi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s your “comfort smell” and where does it take you?';
UPDATE questions
SET translations = '{"en": "If you could time-travel to one specific meal in your life and eat it again, which one would it be ?", "da": "Hvis du kunne rejse tilbage i tiden til \u00e9t specifikt m\u00e5ltid i dit liv og spise det igen, hvilket ville det v\u00e6re?", "de": "Wenn du zu einem bestimmten Essen in deinem Leben zur\u00fcckreisen und es erneut essen k\u00f6nntest, welches w\u00e4re das?", "es": "Si pudieras viajar en el tiempo a una comida espec\u00edfica de tu vida y volver a comerla, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pudesses viajar no tempo at\u00e9 a uma refei\u00e7\u00e3o espec\u00edfica da tua vida e com\u00ea-la novamente, qual seria?", "ro": "Dac\u0103 ai putea c\u0103l\u0103tori \u00een timp la o anumit\u0103 mas\u0103 din via\u021ba ta \u0219i s\u0103 o m\u0103n\u00e2nci din nou, care ar fi?", "fr": "Si tu pouvais voyager dans le temps vers un repas pr\u00e9cis de ta vie et le manger \u00e0 nouveau, lequel serait-ce ?", "it": "Se potessi viaggiare nel tempo a un pasto specifico della tua vita per mangiarlo di nuovo, quale sceglieresti?", "fi": "Jos voisit aikamatkustaa yhteen tiettyyn ateriaan el\u00e4m\u00e4ss\u00e4si ja sy\u00f6d\u00e4 sen uudelleen, mik\u00e4 se olisi?", "nl": "Als je terug in de tijd kon gaan naar \u00e9\u00e9n specifieke maaltijd in je leven om die opnieuw te eten, welke zou dat zijn?", "no": "Hvis du kunne tidsreise til ett bestemt m\u00e5ltid i livet ditt og spise det igjen, hvilket ville du valgt?", "sv": "Om du kunde tidsresa till en specifik m\u00e5ltid i ditt liv och \u00e4ta den igen, vilken skulle du v\u00e4lja?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a cofn\u0105\u0107 si\u0119 w czasie do jednego konkretnego posi\u0142ku w swoim \u017cyciu i zje\u015b\u0107 go jeszcze raz, kt\u00f3ry by\u015b wybra\u0142(a)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could time-travel to one specific meal in your life and eat it again, which one would it be ?';
UPDATE questions
SET translations = '{"en": "What\u2019s a piece of advice you\u2019d give Future-Us before a big adventure?", "da": "Hvilket r\u00e5d ville du give os i fremtiden f\u00f8r et stort eventyr?", "de": "Welchen Rat w\u00fcrdest du unserem zuk\u00fcnftigen Ich vor einem gro\u00dfen Abenteuer geben?", "es": "\u00bfQu\u00e9 consejo le dar\u00edas a nuestro \u201cyo del futuro\u201d antes de una gran aventura?", "pt": "Que conselho darias ao nosso \u201cn\u00f3s do futuro\u201d antes de uma grande aventura?", "ro": "Ce sfat ai da versiunii noastre viitoare \u00eenainte de o mare aventur\u0103?", "fr": "Quel conseil donnerais-tu \u00e0 notre futur nous avant une grande aventure ?", "it": "Quale consiglio daresti al Noi-del-futuro prima di una grande avventura?", "fi": "Mink\u00e4 neuvon antaisit Tulevaisuuden-Meille ennen isoa seikkailua?", "nl": "Welk advies zou je geven aan Toekomst-Wij voordat we aan een groot avontuur beginnen?", "no": "Hvilket r\u00e5d ville du gitt Fremtid-oss f\u00f8r et stort eventyr?", "sv": "Vilket r\u00e5d skulle du ge Framtids-oss inf\u00f6r ett stort \u00e4ventyr?", "pl": "Jakiej rady udzieli\u0142(a)by\u015b Nam-z-Przysz\u0142o\u015bci przed wielk\u0105 przygod\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a piece of advice you’d give Future-Us before a big adventure?';
UPDATE questions
SET translations = '{"en": "What travel rule do you swear by that others ignore?", "da": "Hvilken rejse-regel sv\u00e6rger du til, som andre ignorerer?", "de": "An welche Reiseregel h\u00e4ltst du dich, die andere ignorieren?", "es": "\u00bfQu\u00e9 regla de viaje sigues que los dem\u00e1s ignoran?", "pt": "Que regra de viagem segues que os outros ignoram?", "ro": "Ce regul\u0103 de c\u0103l\u0103torie respec\u021bi tu, dar al\u021bii o ignor\u0103?", "fr": "Quelle r\u00e8gle de voyage suis-tu que les autres ignorent ?", "it": "Quale regola di viaggio segui alla lettera anche se gli altri la ignorano?", "fi": "Mink\u00e4 matkustuss\u00e4\u00e4nn\u00f6n noudattamista vannot, vaikka muut eiv\u00e4t?", "nl": "Op welke reisregel zweer jij, terwijl anderen die negeren?", "no": "Hvilken reiselov sverger du til som andre bare ignorerer?", "sv": "Vilken reseregel sv\u00e4r du vid som andra struntar i?", "pl": "Jakiej zasady podr\u00f3\u017cowania bezwzgl\u0119dnie si\u0119 trzymasz, cho\u0107 inni j\u0105 ignoruj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What travel rule do you swear by that others ignore?';
UPDATE questions
SET translations = '{"en": "If this drive had chapter titles, what\u2019s the title of this chapter?", "da": "Hvis denne k\u00f8retur havde kapiteltitler, hvad ville dette kapitel hedde?", "de": "Wenn diese Fahrt Kapitel h\u00e4tte, wie w\u00fcrde dieses hei\u00dfen?", "es": "Si este viaje tuviera t\u00edtulos de cap\u00edtulos, \u00bfc\u00f3mo se llamar\u00eda este?", "pt": "Se esta viagem tivesse t\u00edtulos de cap\u00edtulos, como se chamaria este?", "ro": "Dac\u0103 aceast\u0103 c\u0103l\u0103torie ar avea titluri de capitole, cum s-ar numi acesta?", "fr": "Si ce trajet avait des titres de chapitres, comment s\u2019intitulerait celui-ci ?", "it": "Se questo viaggio in auto avesse titoli di capitoli, quale sarebbe il titolo di questo capitolo?", "fi": "Jos t\u00e4ll\u00e4 ajomatkalla olisi luvun nimi, mik\u00e4 olisi t\u00e4m\u00e4n luvun otsikko?", "nl": "Als deze rit hoofdstuktitels had, hoe zou dit hoofdstuk heten?", "no": "Hvis denne bilturen hadde kapitteltitler, hva ville tittelen p\u00e5 dette kapittelet v\u00e6rt?", "sv": "Om den h\u00e4r bilresan hade kapitelrubriker, vad skulle rubriken p\u00e5 det h\u00e4r kapitlet vara?", "pl": "Gdyby ta podr\u00f3\u017c mia\u0142a tytu\u0142y rozdzia\u0142\u00f3w, jak brzmia\u0142by tytu\u0142 tego rozdzia\u0142u?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If this drive had chapter titles, what’s the title of this chapter?';
UPDATE questions
SET translations = '{"en": "If other drivers gave honest performance reviews, what feedback would we get?", "da": "Hvis andre bilister gav \u00e6rlige pr\u00e6stationsanmeldelser, hvilken feedback ville vi f\u00e5?", "de": "Wenn andere Fahrer ehrliche Leistungsbewertungen geben w\u00fcrden, welches Feedback w\u00fcrden wir bekommen?", "es": "Si otros conductores dieran evaluaciones honestas, \u00bfqu\u00e9 comentarios recibir\u00edamos?", "pt": "Se outros condutores dessem avalia\u00e7\u00f5es honestas, que feedback receber\u00edamos?", "ro": "Dac\u0103 al\u021bi \u0219oferi ar oferi recenzii sincere, ce feedback am primi?", "fr": "Si les autres conducteurs donnaient des \u00e9valuations honn\u00eates, quel retour aurions-nous ?", "it": "Se gli altri automobilisti potessero lasciarci recensioni sincere sulle nostre \u201cprestazioni\u201d, che feedback riceveremmo?", "fi": "Jos muut kuskit antaisivat meille rehellisi\u00e4 palautteita ajamisesta, millaisen arvion saisimme?", "nl": "Als andere bestuurders ons eerlijke prestatie-reviews zouden geven, welke feedback zouden we krijgen?", "no": "Hvis andre sj\u00e5f\u00f8rer ga oss \u00e6rlige tilbakemeldinger, hva slags vurdering hadde vi f\u00e5tt?", "sv": "Om andra bilister gav \u00e4rliga omd\u00f6men om oss, vilken feedback skulle vi f\u00e5?", "pl": "Gdyby inni kierowcy wystawiali nam szczere oceny, jak\u0105 opini\u0119 by\u015bmy dostali?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If other drivers gave honest performance reviews, what feedback would we get?';
UPDATE questions
SET translations = '{"en": "If we could bring one comfort from home on every trip, what would it be?", "da": "Hvis vi kunne tage \u00e9n ting med hjemmefra p\u00e5 hver tur, hvad ville det v\u00e6re?", "de": "Wenn wir auf jeder Reise einen Komfort von zu Hause mitnehmen k\u00f6nnten, was w\u00e4re das?", "es": "Si pudi\u00e9ramos llevar una comodidad de casa en cada viaje, \u00bfqu\u00e9 ser\u00eda?", "pt": "Se pud\u00e9ssemos levar um conforto de casa em cada viagem, qual seria?", "ro": "Dac\u0103 am putea lua un lucru confortabil de acas\u0103 \u00een fiecare c\u0103l\u0103torie, care ar fi?", "fr": "Si on pouvait emporter un confort de la maison \u00e0 chaque voyage, lequel serait-ce ?", "it": "Se potessimo portare da casa un solo \u201ccomfort\u201d in ogni viaggio, quale sarebbe?", "fi": "Jos voisimme ottaa jokaiselle matkalle yhden kotijutun mukaan, mik\u00e4 se olisi?", "nl": "Als we op elke reis \u00e9\u00e9n troostding van thuis konden meenemen, wat zou het zijn?", "no": "Hvis vi kunne ta med \u00e9n komfort-ting hjemmefra p\u00e5 hver tur, hva skulle det v\u00e6rt?", "sv": "Om vi kunde ta med en enda trygg grej hemifr\u00e5n p\u00e5 varje resa, vad skulle det vara?", "pl": "Gdyby\u015bmy mogli na ka\u017cd\u0105 podr\u00f3\u017c zabiera\u0107 jedn\u0105 rzecz daj\u0105c\u0105 domowy komfort, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we could bring one comfort from home on every trip, what would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s one destination that\u2019s still calling your name?", "da": "Hvilken destination kalder stadig p\u00e5 dit navn?", "de": "Welches Reiseziel ruft immer noch deinen Namen?", "es": "\u00bfQu\u00e9 destino a\u00fan te llama?", "pt": "Que destino ainda chama por ti?", "ro": "Ce destina\u021bie \u00eenc\u0103 \u00ee\u021bi strig\u0103 numele?", "fr": "Quelle destination t\u2019appelle encore ?", "it": "Qual \u00e8 una destinazione che continua ancora a chiamarti?", "fi": "Mik\u00e4 on sellainen kohde, joka kutsuu sinua yh\u00e4 uudestaan?", "nl": "Wat is \u00e9\u00e9n bestemming die jouw naam nog steeds roept?", "no": "Hva er ett reisem\u00e5l som fortsatt roper navnet ditt?", "sv": "Vilket resm\u00e5l k\u00e4nns fortfarande som att det ropar p\u00e5 dig?", "pl": "Jakie jedno miejsce na \u015bwiecie wci\u0105\u017c \u201ewo\u0142a ci\u0119\u201d po imieniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s one destination that’s still calling your name?';
UPDATE questions
SET translations = '{"en": "You\u2019re arrested for a ridiculous crime you totally committed. What would it be?", "da": "Du bliver arresteret for en latterlig forbrydelse, du helt sikkert har beg\u00e5et. Hvad er det?", "de": "Du wirst f\u00fcr ein l\u00e4cherliches Verbrechen verhaftet, das du definitiv begangen hast. Was w\u00e4re das?", "es": "Te arrestan por un crimen rid\u00edculo que definitivamente cometiste. \u00bfCu\u00e1l ser\u00eda?", "pt": "\u00c9s preso por um crime rid\u00edculo que claramente cometeste. Qual seria?", "ro": "E\u0219ti arestat pentru o crim\u0103 ridicol\u0103 pe care sigur ai comis-o. Care ar fi?", "fr": "Tu es arr\u00eat\u00e9 pour un crime ridicule que tu as clairement commis. Lequel est-ce ?", "it": "Ti arrestano per un crimine assurdo che hai davvero commesso. Quale sarebbe?", "fi": "Sinut pid\u00e4tet\u00e4\u00e4n naurettavasta rikoksesta, jonka ihan oikeasti teit. Mik\u00e4 rikos se olisi?", "nl": "Je wordt gearresteerd voor een belachelijke misdaad die je \u00e9cht hebt gepleegd. Wat is het?", "no": "Du blir arrestert for en tullete forbrytelse du faktisk har beg\u00e5tt. Hva er den?", "sv": "Du blir gripen f\u00f6r ett l\u00f6jligt brott du helt klart har beg\u00e5tt. Vad \u00e4r det?", "pl": "Zostajesz aresztowany/a za absurdalne przest\u0119pstwo, kt\u00f3rego naprawd\u0119 si\u0119 dopu\u015bci\u0142e\u015b/dopu\u015bci\u0142a\u015b. Co to takiego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'You’re arrested for a ridiculous crime you totally committed. What would it be?';
UPDATE questions
SET translations = '{"en": "Create a 10-second soap-opera scene set in\u2026 a gas station. Go.", "da": "Lav en 10-sekunders s\u00e6beopera-scene sat i... en tankstation. G\u00e5!", "de": "Erstelle eine 10-sek\u00fcndige Seifenopernszene, die in... einer Tankstelle spielt. Los!", "es": "Crea una escena de telenovela de 10 segundos ambientada en... una gasolinera. \u00a1Adelante!", "pt": "Cria uma cena de novela de 10 segundos passada num... posto de gasolina. Vai!", "ro": "Creeaz\u0103 o scen\u0103 de telenovel\u0103 de 10 secunde plasat\u0103 \u00eentr-o benzin\u0103rie. Start!", "fr": "Cr\u00e9e une sc\u00e8ne de feuilleton de 10 secondes se d\u00e9roulant dans... une station-service. Action !", "it": "Crea una scena da soap opera di 10 secondi ambientata in\u2026 una stazione di servizio. Vai.", "fi": "Keksi 10 sekunnin saippuasarjakohtaus, joka sijoittuu huoltoasemalle. Mene.", "nl": "Bedenk een soap-opera sc\u00e8ne van 10 seconden, spelend op\u2026 een benzinestation. Go.", "no": "Lag en 10 sekunders s\u00e5peserie-scene som foreg\u00e5r p\u00e5\u2026 en bensinstasjon. Kj\u00f8r.", "sv": "Skapa en 10 sekunder l\u00e5ng s\u00e5poperascen som utspelar sig p\u00e5\u2026 en bensinmack. K\u00f6r.", "pl": "Wymy\u015bl 10-sekundow\u0105 scen\u0119 telenoweli rozgrywaj\u0105c\u0105 si\u0119 na\u2026 stacji benzynowej. Start."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Create a 10-second soap-opera scene set in… a gas station. Go.';
UPDATE questions
SET translations = '{"en": "The car just hosted a talent show. Which seat wins and why?", "da": "Bilen har lige afholdt et talentshow. Hvilket s\u00e6de vandt og hvorfor?", "de": "Das Auto hat gerade eine Talentshow veranstaltet. Welcher Sitz gewinnt und warum?", "es": "El coche acaba de organizar un concurso de talentos. \u00bfQu\u00e9 asiento gana y por qu\u00e9?", "pt": "O carro acabou de organizar um show de talentos. Qual assento ganha e porqu\u00ea?", "ro": "Ma\u0219ina tocmai a g\u0103zduit un show de talente. Care loc c\u00e2\u0219tig\u0103 \u0219i de ce?", "fr": "La voiture vient d\u2019organiser un concours de talents. Quel si\u00e8ge gagne et pourquoi ?", "it": "L\u2019auto ha appena ospitato un talent show. Quale sedile vince e perch\u00e9?", "fi": "Auto j\u00e4rjesti juuri kykykilpailun. Mik\u00e4 penkki voittaa ja miksi?", "nl": "De auto heeft net een talentenshow gehouden. Welke stoel wint en waarom?", "no": "Bilen har nettopp hatt talentkonkurranse. Hvilket sete vinner, og hvorfor?", "sv": "Bilen har precis haft talangjakt. Vilken plats vinner och varf\u00f6r?", "pl": "Auto w\u0142a\u015bnie zorganizowa\u0142o pokaz talent\u00f3w. Kt\u00f3re siedzenie wygrywa i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'The car just hosted a talent show. Which seat wins and why?';
UPDATE questions
SET translations = '{"en": "If we ran a pop-up restaurant, what would our signature dish be?", "da": "Hvis vi drev en pop-up-restaurant, hvad ville vores signaturret v\u00e6re?", "de": "Wenn wir ein Pop-up-Restaurant betreiben w\u00fcrden, was w\u00e4re unser Signature-Gericht?", "es": "Si dirigi\u00e9ramos un restaurante temporal, \u00bfcu\u00e1l ser\u00eda nuestro plato insignia?", "pt": "Se tiv\u00e9ssemos um restaurante pop-up, qual seria o nosso prato de assinatura?", "ro": "Dac\u0103 am avea un restaurant temporar, care ar fi felul nostru de m\u00e2ncare semn\u0103tur\u0103?", "fr": "Si on tenait un restaurant \u00e9ph\u00e9m\u00e8re, quel serait notre plat signature ?", "it": "Se gestissimo un ristorante pop-up, quale sarebbe il nostro piatto simbolo?", "fi": "Jos pit\u00e4isimme pop up -ravintolaa, mik\u00e4 olisi meid\u00e4n nimikkoannos?", "nl": "Als we een pop-uprestaurant zouden runnen, wat zou ons signature gerecht zijn?", "no": "Hvis vi drev en pop up-restaurant, hva ville v\u00e5r signaturrett v\u00e6rt?", "sv": "Om vi drev en pop up-restaurang, vad skulle vara v\u00e5r signaturr\u00e4tt?", "pl": "Gdyby\u015bmy prowadzili restauracj\u0119 pop up, jakie danie by\u0142oby naszym popisowym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we ran a pop-up restaurant, what would our signature dish be?';
UPDATE questions
SET translations = '{"en": "What do you think our \u201ctravel personality\u201d is \u2014 adventurous, chill, foodie, etc.?", "da": "Hvad tror du, vores \u201crejsepersonlighed\u201d er \u2013 eventyrlystne, afslappede, madglade osv.?", "de": "Wie w\u00fcrdest du unsere \u201eReisepers\u00f6nlichkeit\u201c beschreiben \u2013 abenteuerlustig, entspannt, Feinschmecker usw.?", "es": "\u00bfC\u00f3mo describir\u00edas nuestra \u201cpersonalidad viajera\u201d: aventurera, relajada, foodie, etc.?", "pt": "Como achas que \u00e9 a nossa \u201cpersonalidade de viagem\u201d \u2014 aventureira, calma, gastron\u00f3mica, etc.?", "ro": "Cum crezi c\u0103 este \u201epersonalitatea noastr\u0103 de c\u0103l\u0103torie\u201d \u2014 aventuroas\u0103, relaxat\u0103, gurmand\u0103 etc.?", "fr": "Comment d\u00e9crirais-tu notre \u201cpersonnalit\u00e9 de voyage\u201d \u2014 aventuri\u00e8re, d\u00e9tendue, gourmande, etc. ?", "it": "Secondo te qual \u00e8 la nostra \u201cpersonalit\u00e0 di viaggio\u201d \u2013 avventurosa, rilassata, foodie, ecc.?", "fi": "Mik\u00e4 sinun mielest\u00e4si on meid\u00e4n \u201cmatkapersoonallisuus\u201d \u2013 seikkailija, rento, foodie jne.?", "nl": "Wat denk jij dat onze \u201creispersoonlijkheid\u201d is \u2013 avontuurlijk, chill, foodie, enz.?", "no": "Hva tror du er v\u00e5r \u201creise-personlighet\u201d \u2013 eventyrlysten, chill, foodie osv.?", "sv": "Vad tror du \u00e4r v\u00e5r \u201cresepersonlighet\u201d \u2013 \u00e4ventyrlig, chill, foodie osv.?", "pl": "Jak my\u015blisz, jaka jest nasza \u201epodr\u00f3\u017cnicza osobowo\u015b\u0107\u201d \u2013 przygodowa, na luzie, foodie itd.?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What do you think our “travel personality” is — adventurous, chill, foodie, etc.?';
UPDATE questions
SET translations = '{"en": "If we could relive one day together, which would it be?", "da": "Hvis vi kunne genleve en dag sammen, hvilken ville det v\u00e6re?", "de": "Wenn wir einen Tag zusammen noch einmal erleben k\u00f6nnten, welcher w\u00e4re das?", "es": "Si pudi\u00e9ramos revivir un d\u00eda juntos, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pud\u00e9ssemos reviver um dia juntos, qual seria?", "ro": "Dac\u0103 am putea retr\u0103i o zi \u00eempreun\u0103, care ar fi aceea?", "fr": "Si on pouvait revivre une journ\u00e9e ensemble, laquelle serait-ce ?", "it": "Se potessimo rivivere insieme una giornata, quale sarebbe?", "fi": "Jos voisimme el\u00e4\u00e4 yhdess\u00e4 yhden p\u00e4iv\u00e4n uudestaan, mik\u00e4 p\u00e4iv\u00e4 se olisi?", "nl": "Als we samen \u00e9\u00e9n dag opnieuw konden beleven, welke zou dat zijn?", "no": "Hvis vi kunne leve \u00e9n dag sammen p\u00e5 nytt, hvilken dag skulle det v\u00e6rt?", "sv": "Om vi kunde \u00e5teruppleva en dag tillsammans, vilken skulle det vara?", "pl": "Gdyby\u015bmy mogli prze\u017cy\u0107 razem jeszcze raz jeden dzie\u0144, kt\u00f3ry by\u015b wybra\u0142(a)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we could relive one day together, which would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s your most iconic travel fail or embarrassing moment?", "da": "Hvad er dit mest ikoniske rejsefiasko eller pinlige \u00f8jeblik?", "de": "Was ist dein ikonischster Reiseausrutscher oder peinlicher Moment?", "es": "\u00bfCu\u00e1l es tu fallo o momento embarazoso m\u00e1s ic\u00f3nico de viaje?", "pt": "Qual \u00e9 o teu maior fracasso ou momento embara\u00e7oso de viagem?", "ro": "Care este cel mai memorabil e\u0219ec sau moment jenant dintr-o c\u0103l\u0103torie?", "fr": "Quel est ton \u00e9chec ou moment de voyage le plus embl\u00e9matique ?", "it": "Qual \u00e8 il tuo fallimento di viaggio o momento imbarazzante pi\u00f9 iconico?", "fi": "Mik\u00e4 on ikonisin matkak\u00f6m\u00e4hdyksesi tai nolo hetki?", "nl": "Wat is je meest iconische reisblunder of g\u00eanante moment?", "no": "Hva er din mest legendariske reisetabbe eller pinlige \u00f8yeblikk?", "sv": "Vad \u00e4r ditt mest ikoniska resefiasko eller pinsamma \u00f6gonblick?", "pl": "Jaka jest twoja najbardziej ikoniczna wpadka z podr\u00f3\u017cy albo \u017cenuj\u0105cy moment?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s your most iconic travel fail or embarrassing moment?';
UPDATE questions
SET translations = '{"en": "Who would survive longest if we were in a zombie apocalypse \u2014 and why?", "da": "Hvem ville overleve l\u00e6ngst, hvis vi var i en zombieapokalypse \u2013 og hvorfor?", "de": "Wer w\u00fcrde am l\u00e4ngsten \u00fcberleben, wenn wir in einer Zombie-Apokalypse w\u00e4ren \u2013 und warum?", "es": "\u00bfQui\u00e9n sobrevivir\u00eda m\u00e1s tiempo si estuvi\u00e9ramos en un apocalipsis zombi y por qu\u00e9?", "pt": "Quem sobreviveria por mais tempo se estiv\u00e9ssemos num apocalipse zombie \u2014 e porqu\u00ea?", "ro": "Cine ar supravie\u021bui cel mai mult dac\u0103 am fi \u00eentr-o apocalips\u0103 zombie \u2014 \u0219i de ce?", "fr": "Qui survivrait le plus longtemps si nous \u00e9tions dans une apocalypse zombie \u2014 et pourquoi ?", "it": "Chi di noi sopravviverebbe pi\u00f9 a lungo in un\u2019apocalisse zombie \u2013 e perch\u00e9?", "fi": "Kuka meist\u00e4 selvi\u00e4isi pisimp\u00e4\u00e4n zombiapokalypsissa \u2013 ja miksi?", "nl": "Wie van ons zou het langst overleven in een zombie-apocalyps \u2013 en waarom?", "no": "Hvem av oss ville overlevd lengst i en zombieapokalypse \u2013 og hvorfor?", "sv": "Vem av oss skulle \u00f6verleva l\u00e4ngst i en zombieapokalyps \u2013 och varf\u00f6r?", "pl": "Kto z nas prze\u017cy\u0142by najd\u0142u\u017cej w apokalipsie zombie \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Who would survive longest if we were in a zombie apocalypse — and why?';
UPDATE questions
SET translations = '{"en": "Which landscape calms you the most on a drive?", "da": "Hvilket landskab beroliger dig mest under en k\u00f8retur?", "de": "Welche Landschaft beruhigt dich am meisten w\u00e4hrend einer Fahrt?", "es": "\u00bfQu\u00e9 paisaje te calma m\u00e1s durante un viaje?", "pt": "Que paisagem te acalma mais durante uma viagem?", "ro": "Ce peisaj te lini\u0219te\u0219te cel mai mult \u00een timpul unei c\u0103l\u0103torii?", "fr": "Quel paysage te calme le plus pendant un trajet ?", "it": "Quale paesaggio ti calma di pi\u00f9 quando sei in macchina?", "fi": "Millainen maisema rauhoittaa sinua eniten ajomatkalla?", "nl": "Welk landschap kalmeert je het meest tijdens het rijden?", "no": "Hvilket landskap roer deg mest n\u00e5r du er p\u00e5 kj\u00f8retur?", "sv": "Vilket landskap lugnar dig mest n\u00e4r du \u00e5ker bil?", "pl": "Jaki krajobraz najbardziej ci\u0119 uspokaja w czasie jazdy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Which landscape calms you the most on a drive?';
UPDATE questions
SET translations = '{"en": "Who in here tells the best stories?", "da": "Hvem her fort\u00e6ller de bedste historier?", "de": "Wer hier erz\u00e4hlt die besten Geschichten?", "es": "\u00bfQui\u00e9n de aqu\u00ed cuenta las mejores historias?", "pt": "Quem aqui conta as melhores hist\u00f3rias?", "ro": "Cine de aici spune cele mai bune pove\u0219ti?", "fr": "Qui ici raconte les meilleu", "it": "Chi qui dentro racconta le storie migliori?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 kertoo parhaat tarinat?", "nl": "Wie hier binnen vertelt de beste verhalen?", "no": "Hvem her inne forteller de beste historiene?", "sv": "Vem h\u00e4r inne ber\u00e4ttar de b\u00e4sta historierna?", "pl": "Kto tutaj opowiada najlepsze historie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Who in here tells the best stories?';
UPDATE questions
SET translations = '{"en": "If money didn\u2019t matter, what would your perfect week look like?", "da": "Hvis penge ikke bet\u00f8d noget, hvordan ville din perfekte uge se ud?", "de": "Wenn Geld keine Rolle spielen w\u00fcrde, wie w\u00fcrde deine perfekte Woche aussehen?", "es": "Si el dinero no importara, \u00bfc\u00f3mo ser\u00eda tu semana perfecta?", "pt": "Se o dinheiro n\u00e3o importasse, como seria a tua semana perfeita?", "ro": "Dac\u0103 banii nu ar conta, cum ar ar\u0103ta s\u0103pt\u0103m\u00e2na ta perfect\u0103?", "fr": "Si l\u2019argent n\u2019avait pas d\u2019importance, \u00e0 quoi ressemblerait ta semaine parfaite ?", "it": "Se i soldi non contassero, come sarebbe la tua settimana perfetta?", "fi": "Jos rahalla ei olisi v\u00e4li\u00e4, milt\u00e4 t\u00e4ydellinen viikkosi n\u00e4ytt\u00e4isi?", "nl": "Als geld geen rol speelde, hoe zou jouw perfecte week eruitzien?", "no": "Hvis penger ikke spilte noen rolle, hvordan ville din perfekte uke sett ut?", "sv": "Om pengar inte spelade n\u00e5gon roll, hur skulle din perfekta vecka se ut?", "pl": "Gdyby pieni\u0105dze nie mia\u0142y znaczenia, jak wygl\u0105da\u0142by tw\u00f3j idealny tydzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If money didn’t matter, what would your perfect week look like?';
UPDATE questions
SET translations = '{"en": "What\u2019s a random childhood memory that always makes you smile?", "da": "Hvad er et tilf\u00e6ldigt barndomsminde, der altid f\u00e5r dig til at smile?", "de": "Welche zuf\u00e4llige Kindheitserinnerung bringt dich immer zum L\u00e4cheln?", "es": "\u00bfQu\u00e9 recuerdo aleatorio de tu infancia siempre te hace sonre\u00edr?", "pt": "Qual \u00e9 uma lembran\u00e7a aleat\u00f3ria da inf\u00e2ncia que sempre te faz sorrir?", "ro": "Care este o amintire din copil\u0103rie care te face mereu s\u0103 z\u00e2mbe\u0219ti?", "fr": "Quel souvenir d\u2019enfance te fait toujours sourire ?", "it": "Qual \u00e8 un ricordo d\u2019infanzia casuale che ti fa sempre sorridere?", "fi": "Mik\u00e4 satunnainen lapsuusmuisto saa sinut aina hymyilem\u00e4\u00e4n?", "nl": "Wat is een willekeurige jeugdherinnering die je altijd laat glimlachen?", "no": "Hva er et tilfeldig barndomsminne som alltid f\u00e5r deg til \u00e5 smile?", "sv": "Vilket random barndomsminne f\u00e5r dig alltid att le?", "pl": "Jakie losowe wspomnienie z dzieci\u0144stwa zawsze wywo\u0142uje u\u015bmiech na twojej twarzy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a random childhood memory that always makes you smile?';
UPDATE questions
SET translations = '{"en": "If you could instantly become fluent in one language, which one \u2014 and where would you go to use it?", "da": "Hvis du \u00f8jeblikkeligt kunne blive flydende i \u00e9t sprog, hvilket ville det v\u00e6re \u2013 og hvor ville du bruge det?", "de": "Wenn du sofort flie\u00dfend in einer Sprache sprechen k\u00f6nntest, welche w\u00e4re das \u2013 und wo w\u00fcrdest du sie verwenden?", "es": "Si pudieras volverte fluido instant\u00e1neamente en un idioma, \u00bfcu\u00e1l ser\u00eda y d\u00f3nde lo usar\u00edas?", "pt": "Se pudesses falar fluentemente uma l\u00edngua instantaneamente, qual seria \u2014 e onde a usarias?", "ro": "Dac\u0103 ai putea deveni instantaneu fluent \u00eentr-o limb\u0103, care ar fi \u0219i unde ai folosi-o?", "fr": "Si tu pouvais devenir instantan\u00e9ment fluent dans une langue, laquelle serait-ce et o\u00f9 l\u2019utiliserais-tu ?", "it": "Se potessi diventare all\u2019istante fluente in una lingua, quale sarebbe \u2013 e dove andresti a usarla?", "fi": "Jos voisit saman tien oppia sujuvaksi yhdess\u00e4 kieless\u00e4, mik\u00e4 se olisi \u2013 ja minne menisit k\u00e4ytt\u00e4m\u00e4\u00e4n sit\u00e4?", "nl": "Als je in \u00e9\u00e9n taal meteen vloeiend kon worden, welke zou dat zijn \u2013 en waar zou je heen gaan om haar te gebruiken?", "no": "Hvis du umiddelbart kunne bli flytende i ett spr\u00e5k, hvilket \u2013 og hvor ville du reist for \u00e5 bruke det?", "sv": "Om du direkt kunde bli flytande i ett spr\u00e5k, vilket \u2013 och vart skulle du \u00e5ka f\u00f6r att anv\u00e4nda det?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a od razu biegle zna\u0107 jeden j\u0119zyk, kt\u00f3ry \u2013 i dok\u0105d pojecha\u0142(a)by\u015b, \u017ceby go u\u017cywa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could instantly become fluent in one language, which one — and where would you go to use it?';
UPDATE questions
SET translations = '{"en": "If you could rename yourself for a day, what name would you pick and why?", "da": "Hvis du kunne omd\u00f8be dig selv for en dag, hvilket navn ville du v\u00e6lge og hvorfor?", "de": "Wenn du dich f\u00fcr einen Tag umbenennen k\u00f6nntest, welchen Namen w\u00fcrdest du w\u00e4hlen und warum?", "es": "Si pudieras cambiarte el nombre por un d\u00eda, \u00bfcu\u00e1l elegir\u00edas y por qu\u00e9?", "pt": "Se pudesses mudar o teu nome por um dia, qual escolherias e porqu\u00ea?", "ro": "Dac\u0103 \u021bi-ai putea schimba numele pentru o zi, ce nume ai alege \u0219i de ce?", "fr": "Si tu pouvais te renommer pour une journ\u00e9e, quel pr\u00e9nom choisirais-tu et pourquoi ?", "it": "Se potessi cambiarti nome per un giorno, quale sceglieresti e perch\u00e9?", "fi": "Jos voisit nimet\u00e4 itsesi uudestaan yhdeksi p\u00e4iv\u00e4ksi, mink\u00e4 nimen valitsisit ja miksi?", "nl": "Als je jezelf \u00e9\u00e9n dag een andere naam kon geven, welke zou je kiezen en waarom?", "no": "Hvis du kunne gi deg selv et nytt navn for \u00e9n dag, hvilket navn ville du valgt og hvorfor?", "sv": "Om du kunde byta namn p\u00e5 dig sj\u00e4lv f\u00f6r en dag, vilket namn skulle du ta och varf\u00f6r?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a zmieni\u0107 sobie imi\u0119 na jeden dzie\u0144, jakie by\u015b wybra\u0142(a) i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could rename yourself for a day, what name would you pick and why?';
UPDATE questions
SET translations = '{"en": "If you could switch jobs with someone for one week, who would it be?", "da": "Hvis du kunne bytte job med en person i en uge, hvem skulle det s\u00e5 v\u00e6re?", "de": "Wenn du f\u00fcr eine Woche den Job mit jemandem tauschen k\u00f6nntest, wer w\u00e4re das?", "es": "Si pudieras intercambiar trabajos con alguien por una semana, \u00bfqui\u00e9n ser\u00eda?", "pt": "Se pudesses trocar de trabalho com algu\u00e9m por uma semana, quem seria?", "ro": "Dac\u0103 ai putea schimba locul de munc\u0103 cu cineva pentru o s\u0103pt\u0103m\u00e2n\u0103, cine ar fi?", "fr": "Si tu pouvais \u00e9changer ton travail avec quelqu\u2019un pendant une semaine, qui ce serait ?", "it": "Se potessi scambiare lavoro con qualcuno per una settimana, con chi sarebbe?", "fi": "Jos voisit vaihtaa viikoksi ty\u00f6paikkaa jonkun kanssa, kuka se olisi?", "nl": "Als je voor \u00e9\u00e9n week van baan kon ruilen met iemand, wie zou dat zijn?", "no": "Hvis du kunne bytte jobb med noen i \u00e9n uke, hvem ville det v\u00e6rt?", "sv": "Om du kunde byta jobb med n\u00e5gon i en vecka, vem skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a na tydzie\u0144 zamieni\u0107 si\u0119 z kim\u015b prac\u0105, kto by to by\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could switch jobs with someone for one week, who would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you wish people understood better about you?", "da": "Hvad er noget, du ville \u00f8nske, folk forstod bedre om dig?", "de": "Was ist etwas, das du dir w\u00fcnschst, dass die Leute besser \u00fcber dich verstehen w\u00fcrden?", "es": "\u00bfQu\u00e9 es algo que desear\u00edas que la gente entendiera mejor sobre ti?", "pt": "O que gostarias que as pessoas compreendessem melhor sobre ti?", "ro": "Ce \u021bi-ai dori ca oamenii s\u0103 \u00een\u021beleag\u0103 mai bine despre tine?", "fr": "Qu\u2019aimerais-tu que les gens comprennent mieux \u00e0 ton sujet ?", "it": "Qual \u00e8 una cosa che vorresti che gli altri capissero meglio di te?", "fi": "Mik\u00e4 on asia, jonka toivoisit muiden ymm\u00e4rt\u00e4v\u00e4n sinusta paremmin?", "nl": "Wat is iets waarvan je zou willen dat mensen het beter over jou begrepen?", "no": "Hva er noe du skulle \u00f8nske folk forsto bedre om deg?", "sv": "Vad \u00e4r n\u00e5got du \u00f6nskar att folk f\u00f6rstod b\u00e4ttre om dig?", "pl": "Co jest tak\u0105 rzecz\u0105, kt\u00f3r\u0105 bardzo chcia\u0142(a)by\u015b, \u017ceby ludzie lepiej o tobie rozumieli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s something you wish people understood better about you?';
UPDATE questions
SET translations = '{"en": "If you could have a billboard anywhere with any message, what would it say?", "da": "Hvis du kunne have et billboard hvor som helst med en hvilken som helst besked, hvad ville der st\u00e5?", "de": "Wenn du irgendwo ein Plakat mit einer beliebigen Botschaft haben k\u00f6nntest, was w\u00fcrde daraufstehen?", "es": "Si pudieras tener una cartelera en cualquier parte con cualquier mensaje, \u00bfqu\u00e9 dir\u00eda?", "pt": "Se pudesses ter um outdoor em qualquer lugar com qualquer mensagem, o que diria?", "ro": "Dac\u0103 ai putea avea un panou publicitar oriunde cu orice mesaj, ce ar scrie pe el?", "fr": "Si tu pouvais avoir un panneau publicitaire n\u2019importe o\u00f9 avec n\u2019importe quel message, que dirait-il ?", "it": "Se potessi avere un cartellone pubblicitario ovunque con qualsiasi messaggio, cosa direbbe?", "fi": "Jos voisit saada mainostaulun minne tahansa ja mill\u00e4 tahansa viestill\u00e4, mit\u00e4 siin\u00e4 lukisi?", "nl": "Als je ergens een billboard kon hebben met eender welke boodschap, wat zou erop staan?", "no": "Hvis du kunne ha en reklameplakat hvor som helst med hvilken som helst tekst, hva skulle det st\u00e5tt?", "sv": "Om du fick ha en reklamskylt var som helst i v\u00e4rlden med vilket budskap som helst, vad skulle det st\u00e5 p\u00e5 den?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a mie\u0107 billboard gdziekolwiek na \u015bwiecie z dowolnym has\u0142em, co by na nim by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could have a billboard anywhere with any message, what would it say?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019ve done once that you\u2019ll never do again \u2014 but you\u2019re glad you tried?", "da": "Hvad er noget, du kun har gjort \u00e9n gang, som du aldrig vil g\u00f8re igen \u2013 men er glad for, at du pr\u00f8vede?", "de": "Was hast du einmal getan, das du nie wieder tun w\u00fcrdest \u2013 aber froh bist, dass du es versucht hast?", "es": "\u00bfQu\u00e9 has hecho una vez que nunca volver\u00edas a hacer, pero te alegra haberlo intentado?", "pt": "O que fizeste uma vez que nunca mais farias \u2014 mas ficaste feliz por ter tentado?", "ro": "Ce ai f\u0103cut o dat\u0103 \u0219i nu ai mai face niciodat\u0103 \u2014 dar e\u0219ti bucuros c\u0103 ai \u00eencercat?", "fr": "Qu\u2019as-tu fait une fois que tu ne referais jamais \u2014 mais dont tu es content de l\u2019avoir tent\u00e9 ?", "it": "Qual \u00e8 qualcosa che hai fatto una volta e non farai mai pi\u00f9 \u2013 ma sei contento/a di averci provato?", "fi": "Mik\u00e4 on juttu, jonka teit kerran etk\u00e4 en\u00e4\u00e4 koskaan tekisi \u2013 mutta olet silti iloinen, ett\u00e4 kokeilit?", "nl": "Wat is iets dat je \u00e9\u00e9n keer hebt gedaan en nooit meer zult doen \u2013 maar waar je toch blij om bent dat je het hebt geprobeerd?", "no": "Hva er noe du har gjort \u00e9n gang som du aldri gj\u00f8r igjen \u2013 men du er glad du pr\u00f8vde?", "sv": "Vad \u00e4r n\u00e5got du gjort en g\u00e5ng och aldrig g\u00f6r igen \u2013 men du \u00e4r glad att du testade?", "pl": "Co takiego zrobi\u0142e\u015b/zrobi\u0142a\u015b raz i nigdy wi\u0119cej nie zrobisz \u2013 ale cieszysz si\u0119, \u017ce spr\u00f3bowa\u0142e\u015b/spr\u00f3bowa\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s something you’ve done once that you’ll never do again — but you’re glad you tried?';
UPDATE questions
SET translations = '{"en": "Mountains or beaches \u2014 and why?", "da": "Bjerge eller strande \u2013 og hvorfor?", "de": "Berge oder Str\u00e4nde \u2013 und warum?", "es": "\u00bfMonta\u00f1as o playas \u2014 y por qu\u00e9?", "pt": "Montanhas ou praias \u2014 e porqu\u00ea?", "ro": "Munte sau mare \u2014 \u0219i de ce?", "fr": "Montagnes ou plages \u2014 et pourquoi ?", "it": "Montagna o mare \u2013 e perch\u00e9?", "fi": "Vuoret vai rannat \u2013 ja miksi?", "nl": "Bergen of stranden \u2013 en waarom?", "no": "Fjell eller strender \u2013 og hvorfor?", "sv": "Berg eller str\u00e4nder \u2013 och varf\u00f6r?", "pl": "G\u00f3ry czy pla\u017ce \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Mountains or beaches — and why?';
UPDATE questions
SET translations = '{"en": "If you could watch one sunrise anywhere, where would it be?", "da": "Hvis du kunne se \u00e9n solopgang hvor som helst, hvor skulle det v\u00e6re?", "de": "Wenn du irgendwo einen Sonnenaufgang sehen k\u00f6nntest, wo w\u00e4re das?", "es": "Si pudieras ver un amanecer en cualquier lugar, \u00bfd\u00f3nde ser\u00eda?", "pt": "Se pudesses ver um nascer do sol em qualquer lugar, onde seria?", "ro": "Dac\u0103 ai putea privi un r\u0103s\u0103rit oriunde, unde ar fi?", "fr": "Si tu pouvais regarder un lever de soleil n\u2019importe o\u00f9, o\u00f9 serait-ce ?", "it": "Se potessi guardare un\u2019alba in qualsiasi posto, dove sarebbe?", "fi": "Jos voisit katsoa yhden auringonnousun miss\u00e4 tahansa, miss\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n zonsopgang ergens op aarde kon bekijken, waar zou dat zijn?", "no": "Hvis du kunne se \u00e9n soloppgang hvor som helst i verden, hvor skulle det v\u00e6re?", "sv": "Om du fick se en enda soluppg\u00e5ng var som helst, var skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a obejrze\u0107 jeden wsch\u00f3d s\u0142o\u0144ca w dowolnym miejscu, gdzie by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could watch one sunrise anywhere, where would it be?';
UPDATE questions
SET translations = '{"en": "Would you rather shave 30 minutes off the trip or discover a hidden gem?", "da": "Ville du hellere spare 30 minutter p\u00e5 turen eller opdage en skjult perle?", "de": "W\u00fcrdest du lieber 30 Minuten auf der Fahrt sparen oder ein verstecktes Juwel entdecken?", "es": "\u00bfPreferir\u00edas ahorrar 30 minutos de viaje o descubrir una joya escondida?", "pt": "Voc\u00ea preferiria economizar 30 minutos de viagem ou descobrir um lugar secreto?", "ro": "Ai prefera s\u0103 economise\u0219ti 30 de minute din drum sau s\u0103 descoperi o comoar\u0103 ascuns\u0103?", "fr": "Pr\u00e9f\u00e8rerais-tu gagner 30 minutes sur la route ou d\u00e9couvrir un joyau cach\u00e9 ?", "it": "Preferiresti togliere 30 minuti al viaggio o scoprire un posto segreto?", "fi": "Haluaisitko mieluummin lyhent\u00e4\u00e4 matkaa 30 minuutilla vai l\u00f6yt\u00e4\u00e4 salaisen helmen?", "nl": "Zou je liever 30 minuten van de reis afhalen of een verborgen parel ontdekken?", "no": "Ville du helst kutte 30 minutter av turen eller oppdage en skjult perle?", "sv": "Skulle du hellre korta resan med 30 minuter eller hitta en dold p\u00e4rla?", "pl": "Wola\u0142(a)by\u015b skr\u00f3ci\u0107 podr\u00f3\u017c o 30 minut czy odkry\u0107 ukryty skarb/miejsc\u00f3wk\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Would you rather shave 30 minutes off the trip or discover a hidden gem?';
UPDATE questions
SET translations = '{"en": "If you could teleport to any market in the world, where would you go first?", "da": "Hvis du kunne teleportere til et hvilket som helst marked i verden, hvor ville du tage hen f\u00f8rst?", "de": "Wenn du dich auf einen beliebigen Markt der Welt teleportieren k\u00f6nntest, wohin w\u00fcrdest du zuerst gehen?", "es": "Si pudieras teletransportarte a cualquier mercado del mundo, \u00bfa cu\u00e1l ir\u00edas primero?", "pt": "Se te pudesses teletransportar para qualquer mercado do mundo, para onde irias primeiro?", "ro": "Dac\u0103 te-ai putea teleporta \u00eentr-o pia\u021b\u0103 oriunde \u00een lume, unde ai merge mai \u00eent\u00e2i?", "fr": "Si tu pouvais te t\u00e9l\u00e9porter \u00e0 n\u2019importe quel march\u00e9 du monde, o\u00f9 irais-tu en premier ?", "it": "Se potessi teletrasportarti in qualsiasi mercato del mondo, dove andresti per primo/a?", "fi": "Jos voisit teleportata mille tahansa torille/markkinalle maailmassa, minne menisit ensin?", "nl": "Als je naar eender welke markt in de wereld kon teleporteren, waar zou je eerst heen gaan?", "no": "Hvis du kunne teleportere til hvilket som helst marked i verden, hvor ville du dratt f\u00f8rst?", "sv": "Om du kunde teleportera till vilken marknad som helst i v\u00e4rlden, vart skulle du \u00e5ka f\u00f6rst?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a teleportowa\u0107 si\u0119 na dowolny targ na \u015bwiecie, dok\u0105d poszed\u0142(a)by\u015b najpierw?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could teleport to any market in the world, where would you go first?';
UPDATE questions
SET translations = '{"en": "Airport edition: are you a \u201carrive super early\u201d or \u201ccutting it close\u201d traveler\u2014and why?", "da": "Lufthavns-udgave: Er du en \u201ckomme i rigtig god tid\u201d-rejsende eller en \u201ckommer i sidste \u00f8jeblik\u201d-type \u2013 og hvorfor?", "de": "Flughafen-Edition: Bist du eher der Typ \u201eviel zu fr\u00fch da\u201c oder \u201eknapp dran\u201c \u2013 und warum?", "es": "Edici\u00f3n aeropuerto: \u00bferes de llegar s\u00faper temprano o de ir apurando el tiempo hasta el final? \u00bfPor qu\u00e9?", "pt": "Edi\u00e7\u00e3o aeroporto: voc\u00ea \u00e9 do time \u201cchegar bem cedo\u201d ou \u201cdeixar para a \u00faltima hora\u201d \u2013 e por qu\u00ea?", "ro": "Edi\u021bia aeroport: e\u0219ti genul care ajunge super devreme sau cel care vine la limit\u0103 \u2013 \u0219i de ce?", "fr": "\u00c9dition a\u00e9roport : tu es plut\u00f4t du genre \u00e0 arriver tr\u00e8s en avance ou \u00e0 arriver tout juste \u00e0 temps \u2013 et pourquoi ?", "it": "Versione aeroporto: sei un viaggiatore da \u201carrivo super in anticipo\u201d o da \u201carrivo all\u2019ultimo minuto\u201d \u2013 e perch\u00e9?", "fi": "Lentokentt\u00e4versio: oletko \u201ctulen paikalle tosi ajoissa\u201d vai \u201cved\u00e4n melkein viime tipassa\u201d -matkailija \u2013 ja miksi?", "nl": "Luchthaven-editie: ben jij een \u201cheel vroeg aankomen\u201d of een \u201cnet op het nippertje\u201d reiziger \u2013 en waarom?", "no": "Flyplass-versjon: er du en \u201ckommer supertidlig\u201d eller \u201ckommer i siste liten\u201d-reisende \u2013 og hvorfor?", "sv": "Flygplats-version: \u00e4r du en \u201ckommer supertidigt\u201d- eller \u201ckommer i sista stund\u201d-resen\u00e4r \u2013 och varf\u00f6r?", "pl": "Wersja lotniskowa: jeste\u015b typem \u201eprzyje\u017cd\u017cam bardzo wcze\u015bnie\u201d czy \u201edocieram na styk\u201d \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Airport edition: are you a “arrive super early” or “cutting it close” traveler—and why?';

-- Category: Cozy Talks (75 questions)