UPDATE questions
SET translations = '{"en": "What kind of words mean the most to you when you\u2019ve had a rough day?", "da": "Hvilke slags ord betyder mest for dig, n\u00e5r du har haft en h\u00e5rd dag?", "de": "Welche Art von Worten bedeutet dir am meisten, wenn du einen harten Tag hattest?", "es": "\u00bfQu\u00e9 tipo de palabras significan m\u00e1s para ti cuando has tenido un mal d\u00eda?", "pt": "Que tipo de palavras significam mais para ti quando tiveste um dia dif\u00edcil?", "ro": "Ce fel de cuvinte \u00eenseamn\u0103 cel mai mult pentru tine c\u00e2nd ai avut o zi grea?", "fr": "Quels mots comptent le plus pour toi quand tu as pass\u00e9 une mauvaise journ\u00e9e ?", "it": "Che tipo di parole significano di pi\u00f9 per te quando hai avuto una giornata difficile?", "fi": "Mink\u00e4laiset sanat merkitsev\u00e4t sinulle eniten, kun olet ollut huonolla tuulella?", "nl": "Welke woorden betekenen het meest voor jou als je een zware dag hebt gehad?", "no": "Hvilke ord betyr mest for deg n\u00e5r du har hatt en t\u00f8ff dag?", "sv": "Vilka slags ord betyder mest f\u00f6r dig n\u00e4r du har haft en tuff dag?", "pl": "Jakie s\u0142owa maj\u0105 dla Ciebie najwi\u0119ksze znaczenie, gdy mia\u0142e\u015b trudny dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of words mean the most to you when you’ve had a rough day?';
UPDATE questions
SET translations = '{"en": "What do you wish I said to you more often?", "da": "Hvad ville du \u00f8nske, jeg sagde til dig oftere?", "de": "Was w\u00fcnschst du dir, dass ich dir \u00f6fter sage?", "es": "\u00bfQu\u00e9 te gustar\u00eda que te dijera m\u00e1s a menudo?", "pt": "O que gostarias que eu te dissesse mais vezes?", "ro": "Ce \u021bi-ai dori s\u0103-\u021bi spun mai des?", "fr": "Qu\u2019aimerais-tu que je te dise plus souvent ?", "it": "Cosa vorresti che ti dicessi pi\u00f9 spesso?", "fi": "Mit\u00e4 toivoisit, ett\u00e4 sanoisin sinulle useammin?", "nl": "Wat zou je willen dat ik vaker tegen je zei?", "no": "Hva \u00f8nsker du at jeg sa til deg oftere?", "sv": "Vad \u00f6nskar du att jag sa till dig oftare?", "pl": "Co chcia\u0142by\u015b, \u017cebym cz\u0119\u015bciej ci m\u00f3wi\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What do you wish I said to you more often?';
UPDATE questions
SET translations = '{"en": "When was the last time something I said really stuck with you \u2014 in a good way?", "da": "Hvorn\u00e5r var sidste gang, noget jeg sagde, virkelig blev hos dig \u2013 p\u00e5 en god m\u00e5de?", "de": "Wann war das letzte Mal, dass etwas, das ich sagte, dir im Ged\u00e4chtnis blieb \u2013 auf gute Weise?", "es": "\u00bfCu\u00e1ndo fue la \u00faltima vez que algo que dije realmente se te qued\u00f3 grabado, de buena manera?", "pt": "Quando foi a \u00faltima vez que algo que eu disse realmente ficou contigo \u2013 de uma forma boa?", "ro": "C\u00e2nd a fost ultima dat\u0103 c\u00e2nd ceva ce am spus \u021bi-a r\u0103mas \u00een minte \u2013 \u00eentr-un mod bun?", "fr": "Quand est-ce que quelque chose que j\u2019ai dit t\u2019est vraiment rest\u00e9 \u2013 d\u2019une bonne fa\u00e7on ?", "it": "Quando \u00e8 stata l''ultima volta che qualcosa che ho detto ti \u00e8 rimasto impresso \u2014 in un modo positivo?", "fi": "Milloin viimeksi jokin, mit\u00e4 sanoin, j\u00e4i sinulle todella mieleen \u2014 hyv\u00e4ll\u00e4 tavalla?", "nl": "Wanneer was de laatste keer dat iets wat ik zei echt bij je is gebleven \u2014 op een goede manier?", "no": "N\u00e5r var sist gang noe jeg sa virkelig festet seg hos deg \u2014 p\u00e5 en god m\u00e5te?", "sv": "N\u00e4r var senaste g\u00e5ngen n\u00e5got jag sa verkligen stannade kvar hos dig \u2014 p\u00e5 ett bra s\u00e4tt?", "pl": "Kiedy ostatni raz co\u015b, co powiedzia\u0142em, naprawd\u0119 zapad\u0142o ci w pami\u0119\u0107 \u2014 w dobry spos\u00f3b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When was the last time something I said really stuck with you — in a good way?';
UPDATE questions
SET translations = '{"en": "How do you like me to cheer you on when you\u2019re nervous or unsure?", "da": "Hvordan kan jeg bedst opmuntre dig, n\u00e5r du er nerv\u00f8s eller usikker?", "de": "Wie kann ich dich am besten aufmuntern, wenn du nerv\u00f6s oder unsicher bist?", "es": "\u00bfC\u00f3mo te gusta que te anime cuando est\u00e1s nervioso/a o inseguro/a?", "pt": "Como gostas que eu te anime quando est\u00e1s nervoso(a) ou inseguro(a)?", "ro": "Cum \u00ee\u021bi place s\u0103 te \u00eencurajez c\u00e2nd e\u0219ti nervos(\u0103) sau nesigur(\u0103)?", "fr": "Comment aimes-tu que je t\u2019encourage quand tu es nerveux(se) ou incertain(e) ?", "it": "Come ti piace che ti incoraggi quando sei nervoso o insicuro?", "fi": "Miten haluaisit, ett\u00e4 kannustan sinua, kun olet hermostunut tai ep\u00e4varma?", "nl": "Hoe vind je het fijn dat ik je aanmoedig als je nerveus of onzeker bent?", "no": "Hvordan liker du at jeg heier p\u00e5 deg n\u00e5r du er nerv\u00f8s eller usikker?", "sv": "Hur vill du att jag hejar p\u00e5 dig n\u00e4r du \u00e4r nerv\u00f6s eller os\u00e4ker?", "pl": "Jak lubisz, \u017ceby ci\u0119 dopingowa\u0107, gdy jeste\u015b zdenerwowany lub niepewny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to cheer you on when you’re nervous or unsure?';
UPDATE questions
SET translations = '{"en": "What kind of compliments feel most real to you?", "da": "Hvilke slags komplimenter f\u00f8les mest \u00e6gte for dig?", "de": "Welche Art von Komplimenten f\u00fchlt sich f\u00fcr dich am ehrlichsten an?", "es": "\u00bfQu\u00e9 tipo de cumplidos se sienten m\u00e1s reales para ti?", "pt": "Que tipo de elogios te parecem mais sinceros?", "ro": "Ce fel de complimente \u021bi se par cele mai autentice?", "fr": "Quels types de compliments te semblent les plus sinc\u00e8res ?", "it": "Quali tipi di complimenti ti sembrano pi\u00f9 autentici?", "fi": "Mink\u00e4laiset kohteliaisuudet tuntuvat sinusta kaikkein aidoimmilta?", "nl": "Welke soort complimenten voelen voor jou het meest oprecht?", "no": "Hvilke typer komplimenter f\u00f8les mest ekte for deg?", "sv": "Vilka typer av komplimanger k\u00e4nns mest \u00e4kta f\u00f6r dig?", "pl": "Jakie komplementy wydaj\u0105 ci si\u0119 najbardziej autentyczne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of compliments feel most real to you?';
UPDATE questions
SET translations = '{"en": "When you apologize, what do you need to hear from me to feel forgiven?", "da": "N\u00e5r du undskylder, hvad har du brug for at h\u00f8re fra mig for at f\u00f8le dig tilgivet?", "de": "Wenn du dich entschuldigst, was musst du von mir h\u00f6ren, um dich vergeben zu f\u00fchlen?", "es": "Cuando te disculpas, \u00bfqu\u00e9 necesitas o\u00edr de m\u00ed para sentirte perdonado/a?", "pt": "Quando pedes desculpa, o que precisas de ouvir de mim para te sentires perdoado(a)?", "ro": "C\u00e2nd \u00ee\u021bi ceri scuze, ce ai nevoie s\u0103 auzi de la mine ca s\u0103 te sim\u021bi iertat(\u0103)?", "fr": "Quand tu t\u2019excuses, qu\u2019as-tu besoin d\u2019entendre de ma part pour te sentir pardonn\u00e9(e) ?", "it": "Quando ti scuso, cosa hai bisogno di sentire da me per sentirti perdonato?", "fi": "Kun pyyd\u00e4t anteeksi, mit\u00e4 sinun tarvitsee kuulla minulta, jotta tuntisit itsesi anteeksiannetuksi?", "nl": "Wanneer je je verontschuldigt, wat heb je van mij nodig om je vergeven te voelen?", "no": "N\u00e5r du ber om unnskyldning, hva trenger du \u00e5 h\u00f8re fra meg for \u00e5 f\u00f8le deg tilgitt?", "sv": "N\u00e4r du ber om urs\u00e4kt, vad beh\u00f6ver du h\u00f6ra fr\u00e5n mig f\u00f6r att k\u00e4nna dig f\u00f6rl\u00e5ten?", "pl": "Kiedy przepraszasz, co musisz us\u0142ysze\u0107 ode mnie, aby poczu\u0107 si\u0119 wybaczonym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When you apologize, what do you need to hear from me to feel forgiven?';
UPDATE questions
SET translations = '{"en": "What\u2019s a sweet message or text from me that would make your whole day better?", "da": "Hvad er en s\u00f8d besked eller sms fra mig, der ville g\u00f8re hele din dag bedre?", "de": "Welche s\u00fc\u00dfe Nachricht oder SMS von mir w\u00fcrde deinen ganzen Tag besser machen?", "es": "\u00bfQu\u00e9 mensaje o texto dulce m\u00edo har\u00eda que tu d\u00eda fuera mejor?", "pt": "Que mensagem ou texto carinhoso meu tornaria o teu dia melhor?", "ro": "Care este un mesaj sau un text dr\u0103gu\u021b de la mine care \u021bi-ar face ziua mai bun\u0103?", "fr": "Quel message ou texto doux de ma part rendrait ta journ\u00e9e meilleure ?", "it": "Qual \u00e8 un messaggio dolce o un testo da parte mia che renderebbe la tua giornata migliore?", "fi": "Mik\u00e4 olisi suloinen viesti tai teksti minulta, joka tekisi koko p\u00e4iv\u00e4si paremmaksi?", "nl": "Wat is een lief bericht of tekst van mij die je hele dag beter zou maken?", "no": "Hva er en s\u00f8t melding eller tekst fra meg som ville gjort hele dagen din bedre?", "sv": "Vad \u00e4r ett s\u00f6tt meddelande eller sms fr\u00e5n mig som skulle g\u00f6ra hela din dag b\u00e4ttre?", "pl": "Jaka s\u0142odka wiadomo\u015b\u0107 lub tekst ode mnie poprawi\u0142by ci ca\u0142y dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s a sweet message or text from me that would make your whole day better?';
UPDATE questions
SET translations = '{"en": "How do you like me to express admiration for you?", "da": "Hvordan vil du have, jeg viser beundring for dig?", "de": "Wie m\u00f6chtest du, dass ich Bewunderung f\u00fcr dich ausdr\u00fccke?", "es": "\u00bfC\u00f3mo te gusta que exprese mi admiraci\u00f3n por ti?", "pt": "Como gostas que eu expresse a minha admira\u00e7\u00e3o por ti?", "ro": "Cum \u00ee\u021bi place s\u0103 \u00ee\u021bi ar\u0103t admira\u021bia mea?", "fr": "Comment aimes-tu que j\u2019exprime mon admiration pour toi ?", "it": "Come ti piace che esprima ammirazione per te?", "fi": "Miten haluaisit, ett\u00e4 ilmaisisin ihailuani sinua kohtaan?", "nl": "Hoe vind je het dat ik mijn bewondering voor jou uitdruk?", "no": "Hvordan liker du at jeg uttrykker beundring for deg?", "sv": "Hur vill du att jag ska uttrycka beundran f\u00f6r dig?", "pl": "Jak lubisz, \u017cebym wyra\u017ca\u0142 podziw dla ciebie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to express admiration for you?';
UPDATE questions
SET translations = '{"en": "When do my words matter the most to you \u2014 when you\u2019re celebrating or when you\u2019re hurting?", "da": "Hvorn\u00e5r betyder mine ord mest for dig \u2013 n\u00e5r du fejrer, eller n\u00e5r du har det sv\u00e6rt?", "de": "Wann bedeuten meine Worte dir am meisten \u2013 wenn du feierst oder wenn du leidest?", "es": "\u00bfCu\u00e1ndo mis palabras significan m\u00e1s para ti: cuando celebras o cuando sufres?", "pt": "Quando \u00e9 que as minhas palavras significam mais para ti \u2014 quando celebras ou quando sofres?", "ro": "C\u00e2nd cuvintele mele conteaz\u0103 cel mai mult pentru tine \u2014 c\u00e2nd te bucuri sau c\u00e2nd suferi?", "fr": "Quand mes mots comptent-ils le plus pour toi \u2014 quand tu c\u00e9l\u00e8bres ou quand tu souffres ?", "it": "Quando le mie parole contano di pi\u00f9 per te \u2014 quando stai festeggiando o quando stai soffrendo?", "fi": "Milloin sanani merkitsev\u00e4t sinulle eniten \u2014 kun juhlit vai kun k\u00e4rsit?", "nl": "Wanneer betekenen mijn woorden het meest voor jou - als je aan het vieren bent of als je pijn hebt?", "no": "N\u00e5r betyr ordene mine mest for deg \u2014 n\u00e5r du feirer eller n\u00e5r du har det vondt?", "sv": "N\u00e4r betyder mina ord mest f\u00f6r dig \u2013 n\u00e4r du firar eller n\u00e4r du har ont?", "pl": "Kiedy moje s\u0142owa maj\u0105 dla ciebie najwi\u0119ksze znaczenie \u2014 gdy \u015bwi\u0119tujesz, czy gdy cierpisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When do my words matter the most to you — when you’re celebrating or when you’re hurting?';
UPDATE questions
SET translations = '{"en": "What could I say that would make you feel truly seen right now?", "da": "Hvad kunne jeg sige lige nu, der ville f\u00e5 dig til at f\u00f8le dig virkelig set?", "de": "Was k\u00f6nnte ich jetzt sagen, damit du dich wirklich gesehen f\u00fchlst?", "es": "\u00bfQu\u00e9 podr\u00eda decir ahora que te har\u00eda sentir realmente visto/a?", "pt": "O que eu poderia dizer agora que te faria sentir-te verdadeiramente visto(a)?", "ro": "Ce a\u0219 putea spune acum ca s\u0103 te sim\u021bi cu adev\u0103rat v\u0103zut(\u0103)?", "fr": "Que pourrais-je dire maintenant pour que tu te sentes vraiment vu(e) ?", "it": "Cosa potrei dire che ti farebbe sentire veramente visto in questo momento?", "fi": "Mit\u00e4 voisin sanoa, jotta tuntisit itsesi todella n\u00e4hdyksi juuri nyt?", "nl": "Wat zou ik kunnen zeggen waardoor je je op dit moment echt gezien zou voelen?", "no": "Hva kunne jeg si som virkelig ville f\u00e5 deg til \u00e5 f\u00f8le deg sett akkurat n\u00e5?", "sv": "Vad skulle jag kunna s\u00e4ga som verkligen skulle f\u00e5 dig att k\u00e4nna dig sedd just nu?", "pl": "Co m\u00f3g\u0142bym powiedzie\u0107, \u017ceby\u015b poczu\u0142 si\u0119 naprawd\u0119 dostrzegany w tej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What could I say that would make you feel truly seen right now?';
UPDATE questions
SET translations = '{"en": "How do you feel when I tease or joke with you \u2014 do you take it as play or something else?", "da": "Hvordan har du det, n\u00e5r jeg driller eller laver sjov med dig \u2013 tager du det som leg eller noget andet?", "de": "Wie f\u00fchlst du dich, wenn ich dich necke oder mit dir scherze \u2013 nimmst du es als Spiel oder etwas anderes?", "es": "\u00bfC\u00f3mo te sientes cuando bromeo contigo, lo tomas como juego o como algo m\u00e1s?", "pt": "Como te sentes quando eu brinco contigo \u2014 levas como brincadeira ou outra coisa?", "ro": "Cum te sim\u021bi c\u00e2nd glumesc cu tine \u2014 o iei ca pe o joac\u0103 sau altceva?", "fr": "Comment te sens-tu quand je plaisante avec toi \u2014 tu le prends comme un jeu ou autrement ?", "it": "Come ti senti quando ti prendo in giro o scherzo con te \u2014 lo prendi come un gioco o qualcos''altro?", "fi": "Milt\u00e4 sinusta tuntuu, kun kiusoittelen tai vitsailen kanssasi \u2014 otatko sen leikkin\u00e4 vai jotain muuta?", "nl": "Hoe voel je je als ik je plaag of grappen met je maak \u2014 beschouw je het als spel of iets anders?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg tuller eller sp\u00f8ker med deg \u2014 tar du det som lek eller noe annet?", "sv": "Hur k\u00e4nner du dig n\u00e4r jag retas eller sk\u00e4mtar med dig \u2013 uppfattar du det som lek eller n\u00e5got annat?", "pl": "Jak si\u0119 czujesz, gdy \u017cartuj\u0119 lub drocz\u0119 si\u0119 z tob\u0105 \u2014 traktujesz to jako zabaw\u0119, czy mo\u017ce co\u015b innego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I tease or joke with you — do you take it as play or something else?';
UPDATE questions
SET translations = '{"en": "When you\u2019re upset, do you want me to listen quietly or say something reassuring right away?", "da": "N\u00e5r du er ked af det, vil du have mig til at lytte stille eller sige noget beroligende med det samme?", "de": "Wenn du traurig bist, soll ich still zuh\u00f6ren oder gleich etwas Beruhigendes sagen?", "es": "Cuando est\u00e1s molesto/a, \u00bfquieres que escuche en silencio o que diga algo reconfortante de inmediato?", "pt": "Quando est\u00e1s chateado(a), queres que eu ou\u00e7a em sil\u00eancio ou diga algo reconfortante logo?", "ro": "C\u00e2nd e\u0219ti sup\u0103rat(\u0103), vrei s\u0103 te ascult \u00een t\u0103cere sau s\u0103 spun ceva lini\u0219titor imediat?", "fr": "Quand tu es contrari\u00e9(e), veux-tu que j\u2019\u00e9coute en silence ou que je dise quelque chose de rassurant tout de suite ?", "it": "Quando sei turbato, preferisci che ti ascolti in silenzio o che dica subito qualcosa di rassicurante?", "fi": "Kun olet j\u00e4rkyttynyt, haluatko, ett\u00e4 kuuntelen hiljaa vai sanonko heti jotain lohduttavaa?", "nl": "Wanneer je van streek bent, wil je dan dat ik stil luister of meteen iets geruststellends zeg?", "no": "N\u00e5r du er oppr\u00f8rt, vil du at jeg skal lytte stille eller si noe beroligende med en gang?", "sv": "N\u00e4r du \u00e4r uppr\u00f6rd, vill du att jag ska lyssna tyst eller s\u00e4ga n\u00e5got lugnande direkt?", "pl": "Kiedy jeste\u015b zdenerwowany, wolisz, \u017cebym s\u0142ucha\u0142 cicho, czy od razu powiedzia\u0142 co\u015b pocieszaj\u0105cego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When you’re upset, do you want me to listen quietly or say something reassuring right away?';
UPDATE questions
SET translations = '{"en": "What\u2019s one compliment or kind word that always feels awkward to you \u2014 and why?", "da": "Hvilket kompliment eller venligt ord f\u00f8les altid akavet for dig \u2013 og hvorfor?", "de": "Welches Kompliment oder freundliche Wort f\u00fchlt sich f\u00fcr dich immer unangenehm an \u2013 und warum?", "es": "\u00bfQu\u00e9 cumplido o palabra amable siempre te resulta inc\u00f3modo, y por qu\u00e9?", "pt": "Que elogio ou palavra gentil te soa sempre estranho \u2014 e por qu\u00ea?", "ro": "Ce compliment sau cuv\u00e2nt amabil \u021bi se pare mereu ciudat \u2013 \u0219i de ce?", "fr": "Quel compliment ou mot gentil te met toujours mal \u00e0 l\u2019aise \u2014 et pourquoi ?", "it": "Qual \u00e8 un complimento o una parola gentile che ti fa sempre sentire a disagio \u2014 e perch\u00e9?", "fi": "Mik\u00e4 on yksi kehu tai yst\u00e4v\u00e4llinen sana, joka tuntuu aina vaivaannuttavalta \u2014 ja miksi?", "nl": "Wat is \u00e9\u00e9n compliment of vriendelijk woord dat je altijd ongemakkelijk vindt \u2014 en waarom?", "no": "Hva er et kompliment eller et vennlig ord som alltid f\u00f8les ubehagelig for deg \u2014 og hvorfor?", "sv": "Vilken komplimang eller sn\u00e4ll kommentar k\u00e4nns alltid awkward f\u00f6r dig \u2014 och varf\u00f6r?", "pl": "Jakie jest jedno komplement lub mi\u0142e s\u0142owo, kt\u00f3re zawsze wydaje ci si\u0119 niezr\u0119czne \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one compliment or kind word that always feels awkward to you — and why?';
UPDATE questions
SET translations = '{"en": "Do you like when you get comments on your appearance?", "da": "Kan du lide, n\u00e5r du f\u00e5r kommentarer om dit udseende?", "de": "Magst du es, wenn du Kommentare zu deinem Aussehen bekommst?", "es": "\u00bfTe gusta cuando recibes comentarios sobre tu apariencia?", "pt": "Gostas quando recebes coment\u00e1rios sobre a tua apar\u00eancia?", "ro": "\u00ce\u021bi place c\u00e2nd prime\u0219ti comentarii despre aspectul t\u0103u?", "fr": "Aimes-tu quand on commente ton apparence ?", "it": "Ti piace quando ricevi commenti sul tuo aspetto?", "fi": "Pid\u00e4tk\u00f6 siit\u00e4, kun saat kommentteja ulkon\u00e4\u00f6st\u00e4si?", "nl": "Vind je het leuk als je opmerkingen krijgt over je uiterlijk?", "no": "Liker du n\u00e5r du f\u00e5r kommentarer om utseendet ditt?", "sv": "Tycker du om n\u00e4r du f\u00e5r kommentarer om ditt utseende?", "pl": "Czy lubisz, gdy dostajesz komentarze na temat swojego wygl\u0105du?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you like when you get comments on your appearance?';
UPDATE questions
SET translations = '{"en": "When do you feel like you have my full attention?", "da": "Hvorn\u00e5r f\u00f8ler du, at du har min fulde opm\u00e6rksomhed?", "de": "Wann f\u00fchlst du, dass du meine volle Aufmerksamkeit hast?", "es": "\u00bfCu\u00e1ndo sientes que tienes toda mi atenci\u00f3n?", "pt": "Quando sentes que tens toda a minha aten\u00e7\u00e3o?", "ro": "C\u00e2nd sim\u021bi c\u0103 ai toat\u0103 aten\u021bia mea?", "fr": "Quand sens-tu que tu as toute mon attention ?", "it": "Quando senti di avere la mia piena attenzione?", "fi": "Milloin tunnet, ett\u00e4 minulla on t\u00e4ysi huomiosi?", "nl": "Wanneer voel je dat je mijn volledige aandacht hebt?", "no": "N\u00e5r f\u00f8ler du at du har min fulle oppmerksomhet?", "sv": "N\u00e4r k\u00e4nner du att du har min fulla uppm\u00e4rksamhet?", "pl": "Kiedy czujesz, \u017ce mam twoj\u0105 pe\u0142n\u0105 uwag\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When do you feel like you have my full attention?';
UPDATE questions
SET translations = '{"en": "What\u2019s one hobby or activity you\u2019d love for us to try as a couple?", "da": "Hvilken hobby eller aktivitet vil du gerne have, vi pr\u00f8ver som par?", "de": "Welches Hobby oder welche Aktivit\u00e4t w\u00fcrdest du gerne als Paar ausprobieren?", "es": "\u00bfQu\u00e9 afici\u00f3n o actividad te gustar\u00eda que prob\u00e1ramos como pareja?", "pt": "Que hobby ou atividade gostarias que experiment\u00e1ssemos como casal?", "ro": "Ce hobby sau activitate ai vrea s\u0103 \u00eencerc\u0103m ca cuplu?", "fr": "Quel passe-temps ou activit\u00e9 aimerais-tu que nous essayions en couple ?", "it": "Qual \u00e8 un hobby o un''attivit\u00e0 che ti piacerebbe provare insieme come coppia?", "fi": "Mik\u00e4 on yksi harrastus tai aktiviteetti, jonka haluaisit meid\u00e4n kokeilevan parina?", "nl": "Wat is een hobby of activiteit die je graag zou willen dat we samen als stel proberen?", "no": "Hva er en hobby eller aktivitet du gjerne vil at vi skal pr\u00f8ve som par?", "sv": "Vilken hobby eller aktivitet skulle du vilja att vi provar som ett par?", "pl": "Jakie jedno hobby lub aktywno\u015b\u0107 chcia\u0142by\u015b, \u017ceby\u015bmy spr\u00f3bowali jako para?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one hobby or activity you’d love for us to try as a couple?';
UPDATE questions
SET translations = '{"en": "What does \u201cquality time\u201d look like to you \u2014 what do we do, how does it feel?", "da": "Hvordan ser \u201ckvalitetstid\u201d ud for dig \u2013 hvad laver vi, hvordan f\u00f8les det?", "de": "Wie sieht \u201eQuality Time\u201c f\u00fcr dich aus \u2013 was machen wir, wie f\u00fchlt es sich an?", "es": "\u00bfC\u00f3mo se ve el \u201ctiempo de calidad\u201d para ti \u2014 qu\u00e9 hacemos, c\u00f3mo se siente?", "pt": "Como \u00e9 o \u201ctempo de qualidade\u201d para ti \u2014 o que fazemos, como se sente?", "ro": "Cum arat\u0103 pentru tine \u201ctimpul de calitate\u201d \u2014 ce facem, cum se simte?", "fr": "\u00c0 quoi ressemble pour toi un \u201cmoment de qualit\u00e9\u201d \u2014 que faisons-nous, comment cela se ressent-il ?", "it": "Cosa significa per te \"tempo di qualit\u00e0\" \u2014 cosa facciamo, come ci ci sentiamo?", "fi": "Milt\u00e4 \"laadukas aika\" n\u00e4ytt\u00e4\u00e4 sinulle - mit\u00e4 teemme, milt\u00e4 se tuntuu?", "nl": "Wat betekent \u201ckwaliteitstijd\u201d voor jou \u2014 wat doen we, hoe voelt het?", "no": "Hva ser \"kvalitetstid\" ut for deg \u2014 hva gj\u00f8r vi, hvordan f\u00f8les det?", "sv": "Vad inneb\u00e4r \"kvalitetstid\" f\u00f6r dig \u2014 vad g\u00f6r vi, hur k\u00e4nns det?", "pl": "Jak dla ciebie wygl\u0105da \u201ejako\u015bciowy czas\u201d \u2014 co robimy, jak si\u0119 czujemy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What does “quality time” look like to you — what do we do, how does it feel?';
UPDATE questions
SET translations = '{"en": "How can I make our time together feel more intentional?", "da": "Hvordan kan jeg f\u00e5 vores tid sammen til at f\u00f8les mere bevidst og meningsfuld?", "de": "Wie kann ich unsere gemeinsame Zeit bewusster und bedeutungsvoller gestalten?", "es": "\u00bfC\u00f3mo puedo hacer que nuestro tiempo juntos se sienta m\u00e1s intencional y significativo?", "pt": "Como posso tornar o nosso tempo juntos mais intencional e significativo?", "ro": "Cum pot face timpul nostru \u00eempreun\u0103 mai inten\u021bionat \u0219i semnificativ?", "fr": "Comment puis-je rendre notre temps ensemble plus intentionnel et significatif ?", "it": "Come posso fare in modo che il nostro tempo insieme si senta pi\u00f9 intenzionale?", "fi": "Miten voin tehd\u00e4 yhteisest\u00e4 ajastamme tarkoituksellisempaa?", "nl": "Hoe kan ik onze tijd samen meer doelbewust laten aanvoelen?", "no": "Hvordan kan jeg gj\u00f8re tiden v\u00e5r sammen mer meningsfull?", "sv": "Hur kan jag f\u00e5 v\u00e5r tid tillsammans att k\u00e4nnas mer avsiktlig?", "pl": "Jak mog\u0119 sprawi\u0107, aby nasz wsp\u00f3lny czas by\u0142 bardziej \u015bwiadomy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How can I make our time together feel more intentional?';
UPDATE questions
SET translations = '{"en": "How do you want us to handle distractions when we\u2019re together \u2014 phones, work, or people pulling us away?", "da": "Hvordan vil du have, at vi h\u00e5ndterer distraktioner, n\u00e5r vi er sammen \u2013 telefoner, arbejde eller folk, der tr\u00e6kker os v\u00e6k?", "de": "Wie m\u00f6chtest du, dass wir mit Ablenkungen umgehen, wenn wir zusammen sind \u2013 Telefonen, Arbeit oder Menschen, die uns ablenken?", "es": "\u00bfC\u00f3mo quieres que manejemos las distracciones cuando estamos juntos \u2014 tel\u00e9fonos, trabajo o gente que nos interrumpe?", "pt": "Como queres que lidemos com distra\u00e7\u00f5es quando estamos juntos \u2014 telem\u00f3veis, trabalho ou pessoas que nos afastam?", "ro": "Cum vrei s\u0103 gestion\u0103m distragerile c\u00e2nd suntem \u00eempreun\u0103 \u2014 telefoane, munc\u0103 sau oameni care ne \u00eentrerup?", "fr": "Comment veux-tu que nous g\u00e9rions les distractions quand nous sommes ensemble \u2014 t\u00e9l\u00e9phones, travail ou gens qui nous \u00e9loignent ?", "it": "Come vuoi che gestiamo le distrazioni quando siamo insieme \u2014 telefoni, lavoro o persone che ci allontanano?", "fi": "Miten haluat, ett\u00e4 k\u00e4sittelemme h\u00e4iri\u00f6tekij\u00f6it\u00e4, kun olemme yhdess\u00e4 \u2014 puhelimet, ty\u00f6 tai ihmiset, jotka vet\u00e4v\u00e4t meit\u00e4 pois?", "nl": "Hoe wil je dat we met afleidingen omgaan als we samen zijn \u2014 telefoons, werk of mensen die ons afleiden?", "no": "Hvordan \u00f8nsker du at vi skal h\u00e5ndtere distraksjoner n\u00e5r vi er sammen \u2014 telefoner, arbeid eller folk som trekker oss bort?", "sv": "Hur vill du att vi ska hantera distraktioner n\u00e4r vi \u00e4r tillsammans \u2014 telefoner, arbete eller m\u00e4nniskor som drar oss bort?", "pl": "Jak chcesz, \u017ceby\u015bmy radzili sobie z rozproszeniami, gdy jeste\u015bmy razem \u2014 telefonami, prac\u0105 czy lud\u017ami, kt\u00f3rzy nas odci\u0105gaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you want us to handle distractions when we’re together — phones, work, or people pulling us away?';
UPDATE questions
SET translations = '{"en": "How do you feel when we do chores or errands together \u2014 like teamwork or just getting stuff done?", "da": "Hvordan har du det, n\u00e5r vi laver husarbejde eller \u00e6rinder sammen \u2013 som teamwork eller bare for at f\u00e5 ting gjort?", "de": "Wie f\u00fchlst du dich, wenn wir Hausarbeit oder Besorgungen zusammen machen \u2013 wie Teamarbeit oder einfach, um Dinge zu erledigen?", "es": "\u00bfC\u00f3mo te sientes cuando hacemos tareas o mandados juntos \u2014 como trabajo en equipo o solo para hacer cosas?", "pt": "Como te sentes quando fazemos tarefas ou recados juntos \u2014 como trabalho de equipa ou s\u00f3 para tratar de coisas?", "ro": "Cum te sim\u021bi c\u00e2nd facem treburi sau comisioane \u00eempreun\u0103 \u2014 ca o echip\u0103 sau doar pentru a termina treaba?", "fr": "Comment te sens-tu quand nous faisons des t\u00e2ches ou des courses ensemble \u2014 comme une \u00e9quipe ou juste pour accomplir les choses ?", "it": "Come ti senti quando facciamo faccende o commissioni insieme \u2014 come un lavoro di squadra o semplicemente per portare a termine le cose?", "fi": "Milt\u00e4 sinusta tuntuu, kun teemme kotit\u00f6it\u00e4 tai asioita yhdess\u00e4 \u2013 onko se enemm\u00e4n tiimity\u00f6t\u00e4 vai vain asioiden hoitamista?", "nl": "Hoe voel je je als we samen klusjes of boodschappen doen \u2014 meer als teamwork of gewoon dingen afhandelen?", "no": "Hvordan f\u00f8ler du det n\u00e5r vi gj\u00f8r husarbeid eller \u00e6render sammen \u2014 som teamarbeid eller bare for \u00e5 f\u00e5 ting gjort?", "sv": "Hur k\u00e4nner du n\u00e4r vi g\u00f6r sysslor eller \u00e4renden tillsammans \u2013 som teamwork eller bara f\u00f6r att f\u00e5 saker gjorda?", "pl": "Jak si\u0119 czujesz, gdy robimy razem obowi\u0105zki domowe lub za\u0142atwiamy sprawy \u2014 jak zesp\u00f3\u0142 czy po prostu za\u0142atwiaj\u0105c sprawy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when we do chores or errands together — like teamwork or just getting stuff done?';
UPDATE questions
SET translations = '{"en": "How do you like me to check in with you during the day?", "da": "Hvordan vil du have, jeg tjekker ind hos dig i l\u00f8bet af dagen?", "de": "Wie m\u00f6chtest du, dass ich mich im Laufe des Tages bei dir melde?", "es": "\u00bfC\u00f3mo te gusta que te contacte durante el d\u00eda?", "pt": "Como gostas que eu fale contigo ao longo do dia?", "ro": "Cum ai vrea s\u0103 iau leg\u0103tura cu tine pe parcursul zilei?", "fr": "Comment aimes-tu que je prenne de tes nouvelles pendant la journ\u00e9e ?", "it": "Come preferisci che ti contatti durante il giorno?", "fi": "Miten haluaisit, ett\u00e4 tarkistan kuulumisesi p\u00e4iv\u00e4n aikana?", "nl": "Hoe wil je dat ik gedurende de dag contact met je opneem?", "no": "Hvordan vil du at jeg skal sjekke inn med deg i l\u00f8pet av dagen?", "sv": "Hur vill du att jag ska kolla in med dig under dagen?", "pl": "Jak wolisz, \u017cebym si\u0119 z tob\u0105 kontaktowa\u0142 w ci\u0105gu dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to check in with you during the day?';
UPDATE questions
SET translations = '{"en": "If we had a full day just for each other, what would you want to do?", "da": "Hvis vi havde en hel dag kun for hinanden, hvad ville du s\u00e5 gerne lave?", "de": "Wenn wir einen ganzen Tag nur f\u00fcr uns h\u00e4tten, was w\u00fcrdest du gerne tun?", "es": "Si tuvi\u00e9ramos un d\u00eda completo solo para nosotros, \u00bfqu\u00e9 te gustar\u00eda hacer?", "pt": "Se tiv\u00e9ssemos um dia inteiro s\u00f3 para n\u00f3s, o que gostarias de fazer?", "ro": "Dac\u0103 am avea o zi \u00eentreag\u0103 doar pentru noi, ce ai vrea s\u0103 facem?", "fr": "Si nous avions une journ\u00e9e enti\u00e8re juste pour nous, que voudrais-tu faire ?", "it": "Se avessimo un''intera giornata solo per noi, cosa ti piacerebbe fare?", "fi": "Jos meill\u00e4 olisi koko p\u00e4iv\u00e4 vain toisillemme, mit\u00e4 haluaisit tehd\u00e4?", "nl": "Als we een hele dag alleen voor elkaar hadden, wat zou je dan willen doen?", "no": "Hvis vi hadde en hel dag bare for hverandre, hva ville du \u00f8nsket \u00e5 gj\u00f8re?", "sv": "Om vi hade en hel dag bara f\u00f6r varandra, vad skulle du vilja g\u00f6ra?", "pl": "Je\u015bli mieliby\u015bmy ca\u0142y dzie\u0144 tylko dla siebie, co chcia\u0142by\u015b robi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'If we had a full day just for each other, what would you want to do?';
UPDATE questions
SET translations = '{"en": "What kind of conversation makes you feel closest to me?", "da": "Hvilken slags samtale f\u00e5r dig til at f\u00f8le dig t\u00e6ttest p\u00e5 mig?", "de": "Welche Art von Gespr\u00e4ch l\u00e4sst dich mir am n\u00e4chsten f\u00fchlen?", "es": "\u00bfQu\u00e9 tipo de conversaci\u00f3n te hace sentir m\u00e1s cerca de m\u00ed?", "pt": "Que tipo de conversa te faz sentir-te mais pr\u00f3ximo(a) de mim?", "ro": "Ce fel de conversa\u021bie te face s\u0103 te sim\u021bi cel mai aproape de mine?", "fr": "Quel type de conversation te fait te sentir le plus proche de moi ?", "it": "Che tipo di conversazione ti fa sentire pi\u00f9 vicino a me?", "fi": "Mink\u00e4lainen keskustelu saa sinut tuntemaan itsesi l\u00e4himm\u00e4ksi minua?", "nl": "Wat voor soort gesprek laat je je het dichtst bij mij voelen?", "no": "Hvilken type samtale f\u00e5r deg til \u00e5 f\u00f8le deg n\u00e6rmest meg?", "sv": "Vilken typ av samtal f\u00e5r dig att k\u00e4nna dig n\u00e4rmast mig?", "pl": "Jaki rodzaj rozmowy sprawia, \u017ce czujesz si\u0119 ze mn\u0105 najbli\u017cej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of conversation makes you feel closest to me?';
UPDATE questions
SET translations = '{"en": "How do you like to reconnect after we\u2019ve been apart or distracted?", "da": "Hvordan kan du bedst lide at genoprette forbindelsen efter, at vi har v\u00e6ret adskilt eller distraherede?", "de": "Wie verbindest du dich am liebsten wieder, nachdem wir getrennt oder abgelenkt waren?", "es": "\u00bfC\u00f3mo te gusta reconectar despu\u00e9s de que hemos estado separados o distra\u00eddos?", "pt": "Como gostas de reconectar depois de termos estado separados ou distra\u00eddos?", "ro": "Cum \u00ee\u021bi place s\u0103 te reconectezi dup\u0103 ce am fost desp\u0103r\u021bi\u021bi sau distra\u0219i?", "fr": "Comment aimes-tu te reconnecter apr\u00e8s que nous avons \u00e9t\u00e9 s\u00e9par\u00e9s ou distraits ?", "it": "Come ti piace riconnetterti dopo che siamo stati separati o distratti?", "fi": "Miten tykk\u00e4\u00e4t j\u00e4lleen yhdisty\u00e4, kun olemme olleet eristyksiss\u00e4 tai h\u00e4iriintyneit\u00e4?", "nl": "Hoe vind je het fijn om weer contact te maken nadat we een tijd apart zijn geweest of afgeleid zijn?", "no": "Hvordan liker du \u00e5 gjennopprette kontakten etter at vi har v\u00e6rt fra hverandre eller distrahert?", "sv": "Hur gillar du att \u00e5terknyta kontakten efter att vi har varit \u00e5tskilda eller distraherade?", "pl": "Jak lubisz si\u0119 ponownie po\u0142\u0105czy\u0107 po tym, jak byli\u015bmy oddaleni lub rozproszeni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like to reconnect after we’ve been apart or distracted?';
UPDATE questions
SET translations = '{"en": "What do I do that makes you feel like I\u2019m really there with you?", "da": "Hvad g\u00f8r jeg, der f\u00e5r dig til at f\u00f8le, at jeg virkelig er til stede sammen med dig?", "de": "Was mache ich, das dich f\u00fchlen l\u00e4sst, dass ich wirklich bei dir bin?", "es": "\u00bfQu\u00e9 hago que te hace sentir que realmente estoy contigo?", "pt": "O que eu fa\u00e7o que te faz sentir que estou mesmo presente contigo?", "ro": "Ce fac eu care te face s\u0103 sim\u021bi c\u0103 sunt cu adev\u0103rat al\u0103turi de tine?", "fr": "Qu\u2019est-ce que je fais qui te fait sentir que je suis vraiment avec toi ?", "it": "Cosa faccio che ti fa sentire come se fossi davvero l\u00ec con te?", "fi": "Mit\u00e4 teen, mik\u00e4 saa sinut tuntemaan, ett\u00e4 olen todella siell\u00e4 kanssasi?", "nl": "Wat doe ik waardoor je het gevoel hebt dat ik echt bij je ben?", "no": "Hva gj\u00f8r jeg som f\u00e5r deg til \u00e5 f\u00f8le at jeg virkelig er der med deg?", "sv": "Vad g\u00f6r jag som f\u00e5r dig att k\u00e4nna att jag verkligen \u00e4r d\u00e4r med dig?", "pl": "Co robi\u0119, co sprawia, \u017ce czujesz, \u017ce naprawd\u0119 jestem z tob\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What do I do that makes you feel like I’m really there with you?';
UPDATE questions
SET translations = '{"en": "What kind of date night feels most like \u201cus\u201d?", "da": "Hvilken slags dateaften f\u00f8les mest som \u201cos\u201d?", "de": "Welche Art von Date-Abend f\u00fchlt sich am meisten wie \u201ewir\u201c an?", "es": "\u00bfQu\u00e9 tipo de cita se siente m\u00e1s como \u201cnosotros\u201d?", "pt": "Que tipo de encontro se sente mais como \u201cn\u00f3s\u201d?", "ro": "Ce fel de \u00eent\u00e2lnire pare cel mai mult \u201enoi\u201d?", "fr": "Quel genre de soir\u00e9e en amoureux te semble le plus \u00ab nous \u00bb ?", "it": "Che tipo di serata romantica ci fa sentire pi\u00f9 \"noi\"?", "fi": "Mink\u00e4lainen treffi-ilta tuntuu eniten \"meilt\u00e4\"?", "nl": "Wat voor soort date night voelt het meest als \"wij\"?", "no": "Hva slags date night f\u00f8les mest som \"oss\"?", "sv": "Vilken typ av dejtkv\u00e4ll k\u00e4nns mest som \"vi\"?", "pl": "Jaki rodzaj randki najbardziej przypomina \u201enas\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of date night feels most like “us”?';
UPDATE questions
SET translations = '{"en": "How do I accidentally make you feel like I\u2019m not fully present \u2014 and how could I do better?", "da": "Hvordan f\u00e5r jeg dig ved en fejl til at f\u00f8le, at jeg ikke er helt til stede \u2013 og hvordan kunne jeg blive bedre?", "de": "Wie bringe ich dich aus Versehen dazu zu f\u00fchlen, dass ich nicht ganz pr\u00e4sent bin \u2013 und wie k\u00f6nnte ich es besser machen?", "es": "\u00bfC\u00f3mo hago que accidentalmente sientas que no estoy completamente presente, y c\u00f3mo podr\u00eda mejorar?", "pt": "Como \u00e9 que, sem querer, te fa\u00e7o sentir que n\u00e3o estou totalmente presente \u2014 e como posso melhorar?", "ro": "Cum te fac, f\u0103r\u0103 s\u0103 vreau, s\u0103 sim\u021bi c\u0103 nu sunt complet prezent \u2014 \u0219i cum a\u0219 putea fi mai bun(\u0103)?", "fr": "Comment est-ce que je te fais, sans le vouloir, sentir que je ne suis pas compl\u00e8tement pr\u00e9sent(e) \u2014 et comment pourrais-je faire mieux ?", "it": "Come faccio a farti sentire che non sono completamente presente \u2014 e come potrei fare meglio?", "fi": "Miten onnistun vahingossa saamaan sinut tuntemaan, ett\u00e4 en ole t\u00e4ysin l\u00e4sn\u00e4 \u2014 ja miten voisin parantaa?", "nl": "Hoe maak ik je per ongeluk het gevoel dat ik er niet helemaal ben \u2014 en hoe kan ik het beter doen?", "no": "Hvordan f\u00e5r jeg deg til \u00e5 f\u00f8le at jeg ikke er helt til stede \u2014 og hvordan kan jeg gj\u00f8re det bedre?", "sv": "Hur g\u00f6r jag s\u00e5 att du oavsiktligt k\u00e4nner att jag inte \u00e4r helt n\u00e4rvarande \u2014 och hur kan jag g\u00f6ra b\u00e4ttre?", "pl": "Jak mog\u0119 przypadkowo sprawi\u0107, \u017ce poczujesz, \u017ce nie jestem w pe\u0142ni obecny \u2014 i jak mog\u0119 to poprawi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do I accidentally make you feel like I’m not fully present — and how could I do better?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite memory of us just spending time together?", "da": "Hvad er dit yndlingsminde om os, bare n\u00e5r vi tilbringer tid sammen?", "de": "Was ist deine Lieblings\u00aderinnerung an uns, wenn wir einfach Zeit miteinander verbringen?", "es": "\u00bfCu\u00e1l es tu recuerdo favorito de nosotros pasando tiempo juntos?", "pt": "Qual \u00e9 a tua lembran\u00e7a favorita de n\u00f3s a passar tempo juntos?", "ro": "Care este amintirea ta preferat\u0103 cu noi petrec\u00e2nd timp \u00eempreun\u0103?", "fr": "Quel est ton souvenir pr\u00e9f\u00e9r\u00e9 de nous passant du temps ensemble ?", "it": "Qual \u00e8 il tuo ricordo preferito di noi che passiamo del tempo insieme?", "fi": "Mik\u00e4 on lempimuistosi siit\u00e4, kun vietimme aikaa yhdess\u00e4?", "nl": "Wat is je favoriete herinnering aan de tijd die we samen doorbrachten?", "no": "Hva er ditt favorittminne av oss n\u00e5r vi bare tilbringer tid sammen?", "sv": "Vad \u00e4r ditt favoritminne av oss n\u00e4r vi bara tillbringade tid tillsammans?", "pl": "Jakie jest twoje ulubione wspomnienie z czas\u00f3w, kiedy po prostu sp\u0119dzali\u015bmy razem czas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s your favorite memory of us just spending time together?';
UPDATE questions
SET translations = '{"en": "If we had 30 minutes right now, what would you want to do with me?", "da": "Hvis vi havde 30 minutter lige nu, hvad ville du gerne lave med mig?", "de": "Wenn wir jetzt 30 Minuten h\u00e4tten, was w\u00fcrdest du gerne mit mir machen?", "es": "Si tuvi\u00e9ramos 30 minutos ahora, \u00bfqu\u00e9 te gustar\u00eda hacer conmigo?", "pt": "Se tiv\u00e9ssemos 30 minutos agora, o que gostarias de fazer comigo?", "ro": "Dac\u0103 am avea 30 de minute acum, ce ai vrea s\u0103 facem \u00eempreun\u0103?", "fr": "Si nous avions 30 minutes maintenant, que voudrais-tu faire avec moi ?", "it": "Se avessimo 30 minuti in questo momento, cosa ti piacerebbe fare con me?", "fi": "Jos meill\u00e4 olisi nyt 30 minuuttia, mit\u00e4 haluaisit tehd\u00e4 kanssani?", "nl": "Als we nu 30 minuten hadden, wat zou je dan met mij willen doen?", "no": "Hvis vi hadde 30 minutter akkurat n\u00e5, hva ville du \u00f8nsket \u00e5 gj\u00f8re med meg?", "sv": "Om vi hade 30 minuter just nu, vad skulle du vilja g\u00f6ra med mig?", "pl": "Gdyby\u015bmy mieli teraz 30 minut, co chcia\u0142by\u015b ze mn\u0105 zrobi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'If we had 30 minutes right now, what would you want to do with me?';
UPDATE questions
SET translations = '{"en": "When it comes to chores or responsibilities, what do you naturally take on \u2014 and what do you secretly wish I\u2019d help with more?", "da": "N\u00e5r det g\u00e6lder pligter eller ansvar, hvad tager du naturligt p\u00e5 dig \u2013 og hvad ville du \u00f8nske, jeg hjalp mere med?", "de": "Wenn es um Pflichten oder Verantwortung geht, was \u00fcbernimmst du nat\u00fcrlich \u2013 und wobei w\u00fcnschst du dir, dass ich mehr helfe?", "es": "Cuando se trata de tareas o responsabilidades, \u00bfqu\u00e9 sueles asumir t\u00fa y con qu\u00e9 desear\u00edas que te ayudara m\u00e1s?", "pt": "Quando se trata de tarefas ou responsabilidades, o que assumes naturalmente \u2014 e com o que gostarias que eu ajudasse mais?", "ro": "C\u00e2nd vine vorba de treburi sau responsabilit\u0103\u021bi, ce preiei tu \u00een mod natural \u2014 \u0219i cu ce \u021bi-ai dori s\u0103 te ajut mai mult?", "fr": "Quand il s\u2019agit de t\u00e2ches ou de responsabilit\u00e9s, que prends-tu naturellement en charge \u2014 et avec quoi aimerais-tu que je t\u2019aide davantage ?", "it": "Quando si tratta di faccende o responsabilit\u00e0, cosa ti prendi naturalmente in carico \u2014 e con cosa desideri segretamente che io ti aiuti di pi\u00f9?", "fi": "Kun on kyse kotit\u00f6ist\u00e4 tai vastuista, mit\u00e4 otat luonnostaan hoitaaksesi \u2014 ja mihin toivoisit salaa, ett\u00e4 auttaisin enemm\u00e4n?", "nl": "Als het gaat om huishoudelijke taken of verantwoordelijkheden, wat neem je van nature op je \u2014 en waar zou je stiekem willen dat ik je meer mee help?", "no": "N\u00e5r det gjelder husarbeid eller ansvar, hva tar du naturlig p\u00e5 deg \u2014 og hva \u00f8nsker du hemmelig at jeg skulle hjelpe mer med?", "sv": "N\u00e4r det kommer till sysslor eller ansvar, vad tar du naturligt p\u00e5 dig \u2014 och vad \u00f6nskar du i hemlighet att jag skulle hj\u00e4lpa till med mer?", "pl": "Kiedy mowa o obowi\u0105zkach domowych lub odpowiedzialno\u015bciach, co zazwyczaj bierzesz na siebie \u2014 a co w tajemnicy chcia\u0142by\u015b, \u017cebym bardziej ci w tym pom\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When it comes to chores or responsibilities, what do you naturally take on — and what do you secretly wish I’d help with more?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing I could do this week that would make you feel loved?", "da": "Hvad er \u00e9n ting, jeg kunne g\u00f8re denne uge, som ville f\u00e5 dig til at f\u00f8le dig elsket?", "de": "Was ist eine Sache, die ich diese Woche tun k\u00f6nnte, damit du dich geliebt f\u00fchlst?", "es": "\u00bfQu\u00e9 podr\u00eda hacer esta semana que te har\u00eda sentir amado/a?", "pt": "O que eu poderia fazer esta semana que te fizesse sentir amado(a)?", "ro": "Care e un lucru pe care l-a\u0219 putea face s\u0103pt\u0103m\u00e2na asta ca s\u0103 te sim\u021bi iubit(\u0103)?", "fr": "Quelle est une chose que je pourrais faire cette semaine pour que tu te sentes aim\u00e9(e) ?", "it": "Qual \u00e8 una cosa che potrei fare questa settimana che ti farebbe sentire amato?", "fi": "Mik\u00e4 on yksi asia, jonka voisin tehd\u00e4 t\u00e4ll\u00e4 viikolla, jotta tuntisit itsesi rakastetuksi?", "nl": "Wat is \u00e9\u00e9n ding dat ik deze week kan doen waardoor je je geliefd voelt?", "no": "Hva er \u00e9n ting jeg kan gj\u00f8re denne uken som ville f\u00e5tt deg til \u00e5 f\u00f8le deg elsket?", "sv": "Vad \u00e4r en sak jag skulle kunna g\u00f6ra den h\u00e4r veckan som skulle f\u00e5 dig att k\u00e4nna dig \u00e4lskad?", "pl": "Co\u015b, co m\u00f3g\u0142by\u015b zrobi\u0107 w tym tygodniu, co sprawi\u0142oby, \u017ce poczu\u0142bym si\u0119 kochany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one thing I could do this week that would make you feel loved?';
UPDATE questions
SET translations = '{"en": "Did you grow up seeing one person do most of the housework or planning? How do you think that shaped what you expect in us?", "da": "S\u00e5 du som barn \u00e9n person tage sig af det meste husarbejde eller planl\u00e6gning? Hvordan tror du, det har formet dine forventninger til os?", "de": "Bist du aufgewachsen, indem du gesehen hast, dass eine Person den Gro\u00dfteil der Hausarbeit oder Planung gemacht hat? Wie hat das deiner Meinung nach beeinflusst, was du von uns erwartest?", "es": "\u00bfCreciste viendo a una persona hacer la mayor parte de las tareas o la planificaci\u00f3n? \u00bfC\u00f3mo crees que eso influy\u00f3 en lo que esperas de nosotros?", "pt": "Cresceste a ver uma pessoa fazer a maior parte das tarefas dom\u00e9sticas ou do planeamento? Como achas que isso moldou o que esperas de n\u00f3s?", "ro": "Ai crescut v\u0103z\u00e2nd o persoan\u0103 f\u0103c\u00e2nd cea mai mare parte din treburile casei sau planificare? Cum crezi c\u0103 asta \u021bi-a influen\u021bat a\u0219tept\u0103rile fa\u021b\u0103 de noi?", "fr": "As-tu grandi en voyant une seule personne faire la plupart des t\u00e2ches m\u00e9nag\u00e8res ou de la planification ? Comment penses-tu que cela a influenc\u00e9 ce que tu attends de nous ?", "it": "Sei cresciuto vedendo una persona fare la maggior parte dei lavori domestici o della pianificazione? Come pensi che questo abbia influenzato le tue aspettative nei nostri confronti?", "fi": "Kasvoitko niin, ett\u00e4 yksi henkil\u00f6 teki suurimman osan kotit\u00f6ist\u00e4 tai suunnittelusta? Miten luulet sen muovanneen odotuksiasi meist\u00e4?", "nl": "Ben je opgegroeid met het zien van \u00e9\u00e9n persoon die het meeste van het huishoudelijke werk of de planning deed? Hoe denk je dat dat heeft gevormd wat je van ons verwacht?", "no": "Vokste du opp med \u00e5 se \u00e9n person gj\u00f8re mesteparten av husarbeidet eller planleggingen? Hvordan tror du det har formet hva du forventer av oss?", "sv": "V\u00e4xte du upp med att se en person g\u00f6ra det mesta av hush\u00e5llsarbetet eller planeringen? Hur tror du att det har format vad du f\u00f6rv\u00e4ntar dig av oss?", "pl": "Czy dorasta\u0142e\u015b, widz\u0105c, \u017ce jedna osoba wykonuje wi\u0119kszo\u015b\u0107 prac domowych lub planowania? Jak my\u015blisz, jak to wp\u0142yn\u0119\u0142o na to, czego oczekujesz od nas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Did you grow up seeing one person do most of the housework or planning? How do you think that shaped what you expect in us?';
UPDATE questions
SET translations = '{"en": "How do you like me to show up when you\u2019re overwhelmed \u2014 jump in and help, or give you space first?", "da": "Hvordan vil du have, jeg reagerer, n\u00e5r du er overv\u00e6ldet \u2013 skal jeg springe ind og hj\u00e6lpe, eller give dig plads f\u00f8rst?", "de": "Wie m\u00f6chtest du, dass ich reagiere, wenn du \u00fcberfordert bist \u2013 soll ich einspringen und helfen oder dir zuerst Raum geben?", "es": "\u00bfC\u00f3mo te gusta que act\u00fae cuando est\u00e1s abrumado/a \u2014 que intervenga y ayude, o que te d\u00e9 espacio primero?", "pt": "Como queres que eu aja quando est\u00e1s sobrecarregado(a) \u2014 ajudar de imediato ou dar-te espa\u00e7o primeiro?", "ro": "Cum vrei s\u0103 reac\u021bionez c\u00e2nd e\u0219ti cople\u0219it(\u0103) \u2014 s\u0103 sar s\u0103 te ajut sau s\u0103-\u021bi dau spa\u021biu mai \u00eent\u00e2i?", "fr": "Comment veux-tu que j\u2019agisse quand tu es d\u00e9pass\u00e9(e) \u2014 que j\u2019intervienne pour aider ou que je te laisse d\u2019abord de l\u2019espace ?", "it": "Come preferisci che io mi comporti quando sei sopraffatto \u2014 intervenire e aiutarti, o darti prima dello spazio?", "fi": "Miten haluaisit, ett\u00e4 ilmestyn paikalle, kun olet ylivoimainen \u2014 hypp\u00e4\u00e4n mukaan auttamaan vai annan ensin tilaa?", "nl": "Hoe wil je dat ik reageer als je overweldigd bent \u2014 meteen helpen of eerst wat ruimte geven?", "no": "Hvordan vil du at jeg skal v\u00e6re der for deg n\u00e5r du f\u00f8ler deg overveldet \u2014 skal jeg hoppe inn og hjelpe, eller gi deg litt plass f\u00f8rst?", "sv": "Hur vill du att jag ska agera n\u00e4r du k\u00e4nner dig \u00f6verv\u00e4ldigad \u2014 hoppa in och hj\u00e4lpa till, eller ge dig utrymme f\u00f6rst?", "pl": "Jak wolisz, \u017cebym si\u0119 zachowa\u0142, gdy jeste\u015b przyt\u0142oczony \u2014 wskoczy\u0107 i pom\u00f3c, czy najpierw da\u0107 ci przestrze\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to show up when you’re overwhelmed — jump in and help, or give you space first?';
UPDATE questions
SET translations = '{"en": "What kind of help means the most when you\u2019re stressed?", "da": "Hvilken slags hj\u00e6lp betyder mest for dig, n\u00e5r du er stresset?", "de": "Welche Art von Hilfe bedeutet dir am meisten, wenn du gestresst bist?", "es": "\u00bfQu\u00e9 tipo de ayuda significa m\u00e1s para ti cuando est\u00e1s estresado/a?", "pt": "Que tipo de ajuda significa mais para ti quando est\u00e1s stressado(a)?", "ro": "Ce fel de ajutor conteaz\u0103 cel mai mult pentru tine c\u00e2nd e\u0219ti stresat(\u0103)?", "fr": "Quel type d\u2019aide compte le plus pour toi quand tu es stress\u00e9(e) ?", "it": "Che tipo di aiuto significa di pi\u00f9 quando sei stressato?", "fi": "Mink\u00e4laista apua arvostat eniten, kun olet stressaantunut?", "nl": "Welke soort hulp betekent het meest voor jou als je gestrest bent?", "no": "Hvilken type hjelp betyr mest n\u00e5r du er stresset?", "sv": "Vilken typ av hj\u00e4lp betyder mest n\u00e4r du \u00e4r stressad?", "pl": "Jaki rodzaj pomocy jest dla Ciebie najwa\u017cniejszy, gdy jeste\u015b zestresowany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of help means the most when you’re stressed?';
UPDATE questions
SET translations = '{"en": "What\u2019s one \u201cgender role\u201d or old habit we could unlearn together when it comes to helping each other?", "da": "Hvilken \u201ck\u00f8nsrolle\u201d eller gammel vane kunne vi afl\u00e6re sammen, n\u00e5r det g\u00e6lder at hj\u00e6lpe hinanden?", "de": "Welche \u201eGeschlechterrolle\u201c oder alte Gewohnheit k\u00f6nnten wir gemeinsam verlernen, wenn es darum geht, uns gegenseitig zu helfen?", "es": "\u00bfQu\u00e9 \u201crol de g\u00e9nero\u201d o viejo h\u00e1bito podr\u00edamos desaprender juntos cuando se trata de ayudarnos mutuamente?", "pt": "Que \u201cpapel de g\u00e9nero\u201d ou velho h\u00e1bito poder\u00edamos desaprender juntos quando se trata de ajudar um ao outro?", "ro": "Ce \u201erol de gen\u201d sau obicei vechi am putea dezv\u0103\u021ba \u00eempreun\u0103 c\u00e2nd vine vorba s\u0103 ne ajut\u0103m unul pe altul?", "fr": "Quel \u00ab r\u00f4le de genre \u00bb ou vieille habitude pourrions-nous d\u00e9sapprendre ensemble quand il s\u2019agit de s\u2019entraider ?", "it": "Qual \u00e8 un \"ruolo di genere\" o un''abitudine vecchia che potremmo disimparare insieme quando si tratta di aiutarci a vicenda?", "fi": "Mik\u00e4 on yksi \"sukupuolirooli\" tai vanha tapa, jonka voisimme unohtaa yhdess\u00e4 auttaessamme toisiamme?", "nl": "Wat is \u00e9\u00e9n \"genderrol\" of oude gewoonte die we samen zouden kunnen afleren als het gaat om elkaar helpen?", "no": "Hva er en \"kj\u00f8nnrolle\" eller gammel vane vi kan avl\u00e6re sammen n\u00e5r det gjelder \u00e5 hjelpe hverandre?", "sv": "Vilken \"k\u00f6nsroll\" eller gammal vana skulle vi kunna avl\u00e4ra oss tillsammans n\u00e4r det g\u00e4ller att hj\u00e4lpa varandra?", "pl": "Jak\u0105 jedn\u0105 \u201erol\u0119 p\u0142ci\u201d lub stary nawyk mogliby\u015bmy wsp\u00f3lnie oduczy\u0107 si\u0119, je\u015bli chodzi o wzajemn\u0105 pomoc?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one “gender role” or old habit we could unlearn together when it comes to helping each other?';
UPDATE questions
SET translations = '{"en": "What little thing do I do that makes your life easier?", "da": "Hvilken lille ting g\u00f8r jeg, der g\u00f8r dit liv lettere?", "de": "Welche kleine Sache mache ich, die dein Leben leichter macht?", "es": "\u00bfQu\u00e9 peque\u00f1a cosa hago que hace tu vida m\u00e1s f\u00e1cil?", "pt": "Que pequena coisa eu fa\u00e7o que torna a tua vida mais f\u00e1cil?", "ro": "Ce mic lucru fac eu care \u00ee\u021bi face via\u021ba mai u\u0219oar\u0103?", "fr": "Quelle petite chose est-ce que je fais qui rend ta vie plus facile ?", "it": "Quale piccola cosa faccio che rende la tua vita pi\u00f9 facile?", "fi": "Mik\u00e4 pieni asia, jonka teen, helpottaa el\u00e4m\u00e4\u00e4si?", "nl": "Wat is een klein ding dat ik doe dat jouw leven gemakkelijker maakt?", "no": "Hva er det lille jeg gj\u00f8r som gj\u00f8r livet ditt lettere?", "sv": "Vilken liten sak g\u00f6r jag som g\u00f6r ditt liv enklare?", "pl": "Jaka ma\u0142a rzecz, kt\u00f3r\u0105 robi\u0119, u\u0142atwia ci \u017cycie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What little thing do I do that makes your life easier?';
UPDATE questions
SET translations = '{"en": "How do you want me to show that I\u2019ve got your back?", "da": "Hvordan vil du have, jeg viser, at jeg st\u00f8tter dig?", "de": "Wie m\u00f6chtest du, dass ich zeige, dass ich hinter dir stehe?", "es": "\u00bfC\u00f3mo quieres que te demuestre que te apoyo?", "pt": "Como queres que eu mostre que estou do teu lado?", "ro": "Cum vrei s\u0103 \u00ee\u021bi ar\u0103t c\u0103 te sus\u021bin?", "fr": "Comment veux-tu que je montre que je suis l\u00e0 pour toi ?", "it": "Come vuoi che ti dimostri che ti sostengo?", "fi": "Miten haluat, ett\u00e4 n\u00e4yt\u00e4n, ett\u00e4 olen tukenasi?", "nl": "Hoe wil je dat ik laat zien dat ik je steun?", "no": "Hvordan vil du at jeg skal vise at jeg st\u00f8tter deg?", "sv": "Hur vill du att jag ska visa att jag st\u00f6ttar dig?", "pl": "Jak chcesz, \u017cebym pokaza\u0142, \u017ce ci\u0119 wspieram?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you want me to show that I’ve got your back?';
UPDATE questions
SET translations = '{"en": "What\u2019s a small gesture that always feels big to you?", "da": "Hvilken lille gestus f\u00f8les altid stor for dig?", "de": "Welche kleine Geste f\u00fchlt sich f\u00fcr dich immer gro\u00df an?", "es": "\u00bfQu\u00e9 peque\u00f1o gesto siempre se siente grande para ti?", "pt": "Que pequeno gesto te parece sempre importante?", "ro": "Ce mic gest \u021bi se pare mereu important?", "fr": "Quel petit geste te semble toujours grand ?", "it": "Qual \u00e8 un piccolo gesto che per te sembra sempre grande?", "fi": "Mik\u00e4 on pieni ele, joka tuntuu aina suurelta sinulle?", "nl": "Wat is een klein gebaar dat altijd groot voor je aanvoelt?", "no": "Hva er en liten gest som alltid f\u00f8les stor for deg?", "sv": "Vilken liten gest k\u00e4nns alltid stor f\u00f6r dig?", "pl": "Jaki ma\u0142y gest zawsze wydaje ci si\u0119 wielki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s a small gesture that always feels big to you?';
UPDATE questions
SET translations = '{"en": "When you\u2019re exhausted, how do you like me to step in?", "da": "N\u00e5r du er udmattet, hvordan vil du have, jeg tr\u00e6der til?", "de": "Wenn du ersch\u00f6pft bist, wie m\u00f6chtest du, dass ich einspringe?", "es": "Cuando est\u00e1s agotado/a, \u00bfc\u00f3mo te gusta que intervenga?", "pt": "Quando est\u00e1s exausto(a), como gostas que eu intervenha?", "ro": "C\u00e2nd e\u0219ti epuizat(\u0103), cum ai vrea s\u0103 intervin?", "fr": "Quand tu es \u00e9puis\u00e9(e), comment veux-tu que j\u2019intervienne ?", "it": "Quando sei esausto, come ti piace che io intervenga?", "fi": "Kun olet uupunut, miten haluaisit minun astuvan mukaan?", "nl": "Wanneer je uitgeput bent, hoe wil je dat ik inspring?", "no": "N\u00e5r du er utslitt, hvordan liker du at jeg tr\u00e5r til?", "sv": "N\u00e4r du \u00e4r utmattad, hur vill du att jag ska hj\u00e4lpa till?", "pl": "Kiedy jeste\u015b wyczerpany, jak chcia\u0142by\u015b, \u017cebym ci pom\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When you’re exhausted, how do you like me to step in?';
UPDATE questions
SET translations = '{"en": "What would make you feel more like a team with me?", "da": "Hvad ville f\u00e5 dig til at f\u00f8le dig mere som et team sammen med mig?", "de": "Was w\u00fcrde dich mehr wie ein Team mit mir f\u00fchlen lassen?", "es": "\u00bfQu\u00e9 te har\u00eda sentir m\u00e1s como un equipo conmigo?", "pt": "O que te faria sentir mais como uma equipa comigo?", "ro": "Ce te-ar face s\u0103 te sim\u021bi mai mult ca o echip\u0103 cu mine?", "fr": "Qu\u2019est-ce qui te ferait sentir davantage comme une \u00e9quipe avec moi ?", "it": "Cosa ti farebbe sentire pi\u00f9 parte di un team con me?", "fi": "Mik\u00e4 saisi sinut tuntemaan itsesi enemm\u00e4n tiimiksi kanssani?", "nl": "Wat zou je meer het gevoel geven dat we een team zijn?", "no": "Hva ville f\u00e5tt deg til \u00e5 f\u00f8le deg mer som et team med meg?", "sv": "Vad skulle f\u00e5 dig att k\u00e4nna dig mer som ett team med mig?", "pl": "Co sprawi\u0142oby, \u017ce poczu\u0142by\u015b si\u0119 bardziej cz\u0119\u015bci\u0105 zespo\u0142u ze mn\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What would make you feel more like a team with me?';
UPDATE questions
SET translations = '{"en": "How do you feel when I try to help but don\u2019t do it \u201cyour way\u201d?", "da": "Hvordan har du det, n\u00e5r jeg pr\u00f8ver at hj\u00e6lpe, men ikke g\u00f8r det \u201cp\u00e5 din m\u00e5de\u201d?", "de": "Wie f\u00fchlst du dich, wenn ich versuche zu helfen, es aber nicht \u201eauf deine Art\u201c mache?", "es": "\u00bfC\u00f3mo te sientes cuando intento ayudar pero no lo hago \u201ca tu manera\u201d?", "pt": "Como te sentes quando eu tento ajudar mas n\u00e3o o fa\u00e7o \u201c\u00e0 tua maneira\u201d?", "ro": "Cum te sim\u021bi c\u00e2nd \u00eencerc s\u0103 ajut dar nu o fac \u201c\u00een felul t\u0103u\u201d?", "fr": "Comment te sens-tu quand j\u2019essaie d\u2019aider mais que je ne le fais pas \u00ab \u00e0 ta fa\u00e7on \u00bb ?", "it": "Come ti senti quando cerco di aiutarti ma non lo faccio \"a modo tuo\"?", "fi": "Milt\u00e4 sinusta tuntuu, kun yrit\u00e4n auttaa, mutta en tee sit\u00e4 \"sinun tavallasi\"?", "nl": "Hoe voel je je als ik probeer te helpen maar het niet op \"jouw manier\" doe?", "no": "Hvordan f\u00f8ler du det n\u00e5r jeg pr\u00f8ver \u00e5 hjelpe, men ikke gj\u00f8r det \"din m\u00e5te\"?", "sv": "Hur k\u00e4nner du n\u00e4r jag f\u00f6rs\u00f6ker hj\u00e4lpa till men inte g\u00f6r det \"p\u00e5 ditt s\u00e4tt\"?", "pl": "Jak si\u0119 czujesz, gdy pr\u00f3buj\u0119 pom\u00f3c, ale nie robi\u0119 tego \u201epo twojemu\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I try to help but don’t do it “your way”?';
UPDATE questions
SET translations = '{"en": "What\u2019s something I do (or could do) that quietly says \u201cI care about you\u201d?", "da": "Hvad g\u00f8r jeg (eller kunne jeg g\u00f8re), der stille siger \u201cjeg holder af dig\u201d?", "de": "Was tue ich (oder k\u00f6nnte ich tun), das leise sagt \u201eIch k\u00fcmmere mich um dich\u201c?", "es": "\u00bfQu\u00e9 hago (o podr\u00eda hacer) que diga en silencio \u201cme importas\u201d?", "pt": "O que eu fa\u00e7o (ou poderia fazer) que diga silenciosamente \u201cimportas para mim\u201d?", "ro": "Ce fac (sau a\u0219 putea face) care spune \u00een t\u0103cere \u201e\u00eemi pas\u0103 de tine\u201d?", "fr": "Que fais-je (ou pourrais-je faire) qui dit silencieusement \u00ab je tiens \u00e0 toi \u00bb ?", "it": "Qualcosa che faccio (o potrei fare) che dice in silenzio \"mi importa di te\"?", "fi": "Mik\u00e4 on jokin asia, jonka teen (tai voisin tehd\u00e4), joka hiljaa sanoo \"v\u00e4lit\u00e4n sinusta\"?", "nl": "Wat is iets dat ik doe (of zou kunnen doen) dat stilletjes zegt \"ik geef om je\"?", "no": "Hva er noe jeg gj\u00f8r (eller kan gj\u00f8re) som stille sier \"jeg bryr meg om deg\"?", "sv": "Vad \u00e4r n\u00e5got jag g\u00f6r (eller skulle kunna g\u00f6ra) som tyst s\u00e4ger \"jag bryr mig om dig\"?", "pl": "Co\u015b, co robi\u0119 (lub m\u00f3g\u0142bym zrobi\u0107), co cicho m\u00f3wi \u201ezale\u017cy mi na tobie\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something I do (or could do) that quietly says “I care about you”?';
UPDATE questions
SET translations = '{"en": "How can I better notice when you need help \u2014 without you asking?", "da": "Hvordan kan jeg bedre l\u00e6gge m\u00e6rke til, n\u00e5r du har brug for hj\u00e6lp \u2013 uden at du sp\u00f8rger?", "de": "Wie kann ich besser erkennen, wenn du Hilfe brauchst \u2013 ohne dass du fragst?", "es": "\u00bfC\u00f3mo puedo notar mejor cu\u00e1ndo necesitas ayuda \u2014 sin que lo pidas?", "pt": "Como posso perceber melhor quando precisas de ajuda \u2014 sem pedires?", "ro": "Cum pot observa mai bine c\u00e2nd ai nevoie de ajutor \u2014 f\u0103r\u0103 s\u0103 ceri?", "fr": "Comment puis-je mieux remarquer quand tu as besoin d\u2019aide \u2014 sans que tu le demandes ?", "it": "Come posso accorgermi meglio quando hai bisogno di aiuto, senza che tu debba chiedere?", "fi": "Miten voisin paremmin huomata, kun tarvitset apua \u2014 ilman ett\u00e4 sinun tarvitsee pyyt\u00e4\u00e4?", "nl": "Hoe kan ik beter opmerken wanneer je hulp nodig hebt \u2014 zonder dat je het vraagt?", "no": "Hvordan kan jeg bedre legge merke til n\u00e5r du trenger hjelp \u2014 uten at du ber om det?", "sv": "Hur kan jag b\u00e4ttre m\u00e4rka n\u00e4r du beh\u00f6ver hj\u00e4lp \u2014 utan att du ber om det?", "pl": "Jak mog\u0119 lepiej zauwa\u017ca\u0107, kiedy potrzebujesz pomocy \u2014 bez pytania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How can I better notice when you need help — without you asking?';
UPDATE questions
SET translations = '{"en": "What\u2019s something I could do more often that would take weight off your shoulders?", "da": "Hvad kunne jeg g\u00f8re oftere, som ville lette noget af v\u00e6gten fra dine skuldre?", "de": "Was k\u00f6nnte ich \u00f6fter tun, um dir etwas Last von den Schultern zu nehmen?", "es": "\u00bfQu\u00e9 podr\u00eda hacer m\u00e1s a menudo que te quite peso de los hombros?", "pt": "O que eu poderia fazer mais vezes que te tirasse um peso dos ombros?", "ro": "Ce a\u0219 putea face mai des ca s\u0103-\u021bi iau o parte din greutate de pe umeri?", "fr": "Que pourrais-je faire plus souvent pour all\u00e9ger un peu le poids sur tes \u00e9paules ?", "it": "Cosa potrei fare pi\u00f9 spesso che allevierebbe un po'' il tuo peso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 voisin tehd\u00e4 useammin, mik\u00e4 kevent\u00e4isi taakkaasi?", "nl": "Wat is iets dat ik vaker zou kunnen doen om je ontlasten?", "no": "Hva er noe jeg kunne gjort oftere som ville lett byrden din?", "sv": "Vad \u00e4r n\u00e5got jag skulle kunna g\u00f6ra oftare som skulle l\u00e4tta p\u00e5 dina axlar?", "pl": "Co\u015b, co m\u00f3g\u0142bym robi\u0107 cz\u0119\u015bciej, co zdj\u0119\u0142oby ci ci\u0119\u017car z ramion?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something I could do more often that would take weight off your shoulders?';
UPDATE questions
SET translations = '{"en": "How do you usually react when someone gives you a gift \u2014 excited, shy, awkward, emotional? What do you wish people understood about that?", "da": "Hvordan reagerer du normalt, n\u00e5r nogen giver dig en gave \u2013 begejstret, genert, akavet, r\u00f8rt? Hvad ville du \u00f8nske, folk forstod om det?", "de": "Wie reagierst du normalerweise, wenn dir jemand ein Geschenk gibt \u2013 aufgeregt, sch\u00fcchtern, unbeholfen, emotional? Was w\u00fcnschst du dir, dass die Leute dar\u00fcber verstehen?", "es": "\u00bfC\u00f3mo sueles reaccionar cuando alguien te da un regalo \u2014 emocionado/a, t\u00edmido/a, inc\u00f3modo/a, emocionado/a? \u00bfQu\u00e9 te gustar\u00eda que la gente entendiera sobre eso?", "pt": "Como costumas reagir quando algu\u00e9m te oferece um presente \u2014 entusiasmado(a), t\u00edmido(a), atrapalhado(a), emocionado(a)? O que gostarias que as pessoas entendessem sobre isso?", "ro": "Cum reac\u021bionezi de obicei c\u00e2nd cineva \u00ee\u021bi ofer\u0103 un cadou \u2014 entuziasmat(\u0103), timid(\u0103), st\u00e2njenit(\u0103), emo\u021bionat(\u0103)? Ce \u021bi-ai dori s\u0103 \u00een\u021beleag\u0103 oamenii despre asta?", "fr": "Comment r\u00e9agis-tu d\u2019habitude quand quelqu\u2019un t\u2019offre un cadeau \u2014 excit\u00e9(e), timide, maladroit(e), \u00e9mu(e) ? Qu\u2019aimerais-tu que les gens comprennent \u00e0 ce sujet ?", "it": "Come reagisci di solito quando qualcuno ti fa un regalo \u2014 con entusiasmo, timidezza, imbarazzo, emozione? Cosa vorresti che le persone capissero riguardo a questo?", "fi": "Miten yleens\u00e4 reagoit, kun joku antaa sinulle lahjan \u2014 innokkaasti, ujoisesti, vaivaantuneesti, tunteellisesti? Mit\u00e4 toivot ihmisten ymm\u00e4rt\u00e4v\u00e4n siit\u00e4?", "nl": "Hoe reageer je meestal als iemand je een cadeau geeft \u2014 enthousiast, verlegen, ongemakkelijk, emotioneel? Wat zou je willen dat mensen daarover begrijpen?", "no": "Hvordan pleier du \u00e5 reagere n\u00e5r noen gir deg en gave \u2014 spent, sjenert, kl\u00f8nete, f\u00f8lelsesladet? Hva \u00f8nsker du at folk forsto om det?", "sv": "Hur brukar du reagera n\u00e4r n\u00e5gon ger dig en present \u2014 entusiastisk, blyg, klumpig, k\u00e4nslosam? Vad \u00f6nskar du att folk f\u00f6rstod om det?", "pl": "Jak zazwyczaj reagujesz, gdy kto\u015b daje ci prezent \u2014 z ekscytacj\u0105, nie\u015bmia\u0142o\u015bci\u0105, niezr\u0119cznie, emocjonalnie? Co chcia\u0142by\u015b, aby ludzie zrozumieli na ten temat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you usually react when someone gives you a gift — excited, shy, awkward, emotional? What do you wish people understood about that?';
UPDATE questions
SET translations = '{"en": "What makes a gift feel truly meaningful to you?", "da": "Hvad f\u00e5r en gave til virkelig at f\u00f8les meningsfuld for dig?", "de": "Was l\u00e4sst ein Geschenk f\u00fcr dich wirklich bedeutungsvoll f\u00fchlen?", "es": "\u00bfQu\u00e9 hace que un regalo se sienta verdaderamente significativo para ti?", "pt": "O que faz um presente parecer verdadeiramente significativo para ti?", "ro": "Ce face ca un cadou s\u0103 \u021bi se par\u0103 cu adev\u0103rat semnificativ?", "fr": "Qu\u2019est-ce qui rend un cadeau vraiment significatif pour toi ?", "it": "Cosa rende un regalo davvero significativo per te?", "fi": "Mik\u00e4 tekee lahjasta sinulle todella merkityksellisen?", "nl": "Wat maakt een cadeau voor jou echt betekenisvol?", "no": "Hva gj\u00f8r en gave virkelig meningsfull for deg?", "sv": "Vad g\u00f6r en g\u00e5va verkligen meningsfull f\u00f6r dig?", "pl": "Co sprawia, \u017ce prezent wydaje si\u0119 dla Ciebie naprawd\u0119 znacz\u0105cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What makes a gift feel truly meaningful to you?';
UPDATE questions
SET translations = '{"en": "Do you like surprises, or do you prefer to know something\u2019s coming?", "da": "Kan du lide overraskelser, eller foretr\u00e6kker du at vide, at noget er p\u00e5 vej?", "de": "Magst du \u00dcberraschungen oder wei\u00dft du lieber im Voraus, dass etwas kommt?", "es": "\u00bfTe gustan las sorpresas o prefieres saber que algo viene?", "pt": "Gostas de surpresas ou preferes saber que algo vem a\u00ed?", "ro": "\u00ce\u021bi plac surprizele sau preferi s\u0103 \u0219tii dinainte c\u0103 urmeaz\u0103 ceva?", "fr": "Aimes-tu les surprises ou pr\u00e9f\u00e8res-tu savoir \u00e0 l\u2019avance que quelque chose arrive ?", "it": "Ti piacciono le sorprese, o preferisci sapere che sta per arrivare qualcosa?", "fi": "Pid\u00e4tk\u00f6 yll\u00e4tyksist\u00e4, vai suositko tiet\u00e4\u00e4 etuk\u00e4teen, mit\u00e4 on tulossa?", "nl": "Hou je van verrassingen, of geef je er de voorkeur aan om te weten dat er iets aankomt?", "no": "Liker du overraskelser, eller foretrekker du \u00e5 vite at noe kommer?", "sv": "Tycker du om \u00f6verraskningar, eller f\u00f6redrar du att veta att n\u00e5got \u00e4r p\u00e5 v\u00e4g?", "pl": "Czy lubisz niespodzianki, czy wolisz wiedzie\u0107, \u017ce co\u015b nadchodzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you like surprises, or do you prefer to know something’s coming?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most thoughtful gift I\u2019ve ever given you \u2014 and why?", "da": "Hvad er den mest bet\u00e6nksomme gave, jeg nogensinde har givet dig \u2013 og hvorfor?", "de": "Was ist das aufmerksamste Geschenk, das ich dir je gemacht habe \u2013 und warum?", "es": "\u00bfCu\u00e1l es el regalo m\u00e1s considerado que te he dado \u2014 y por qu\u00e9?", "pt": "Qual foi o presente mais atencioso que j\u00e1 te dei \u2014 e por qu\u00ea?", "ro": "Care este cel mai atent cadou pe care \u021bi l-am oferit \u2014 \u0219i de ce?", "fr": "Quel est le cadeau le plus attentionn\u00e9 que je t\u2019aie jamais offert \u2014 et pourquoi ?", "it": "Qual \u00e8 il regalo pi\u00f9 premuroso che ti abbia mai fatto \u2014 e perch\u00e9?", "fi": "Mik\u00e4 on ajatuksellisin lahja, jonka olen koskaan antanut sinulle \u2014 ja miksi?", "nl": "Wat is het meest doordachte cadeau dat ik je ooit heb gegeven \u2014 en waarom?", "no": "Hva er den mest gjennomtenkte gaven jeg noen gang har gitt deg \u2014 og hvorfor?", "sv": "Vad \u00e4r den mest omt\u00e4nksamma presenten jag n\u00e5gonsin har gett dig \u2014 och varf\u00f6r?", "pl": "Jaki by\u0142 najbardziej przemy\u015blany prezent, jaki kiedykolwiek ci da\u0142em \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s the most thoughtful gift I’ve ever given you — and why?';
UPDATE questions
SET translations = '{"en": "How do you feel when I surprise you with something small?", "da": "Hvordan har du det, n\u00e5r jeg overrasker dig med noget lille?", "de": "Wie f\u00fchlst du dich, wenn ich dich mit etwas Kleinem \u00fcberrasche?", "es": "\u00bfC\u00f3mo te sientes cuando te sorprendo con algo peque\u00f1o?", "pt": "Como te sentes quando eu te surpreendo com algo pequeno?", "ro": "Cum te sim\u021bi c\u00e2nd te surprind cu ceva mic?", "fr": "Comment te sens-tu quand je te surprends avec quelque chose de petit ?", "it": "Come ti senti quando ti sorprendo con qualcosa di piccolo?", "fi": "Milt\u00e4 sinusta tuntuu, kun yll\u00e4t\u00e4n sinut jollakin pienell\u00e4?", "nl": "Hoe voel je je als ik je verras met iets kleins?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg overrasker deg med noe lite?", "sv": "Hur k\u00e4nner du dig n\u00e4r jag \u00f6verraskar dig med n\u00e5got litet?", "pl": "Jak si\u0119 czujesz, gdy zaskakuj\u0119 ci\u0119 czym\u015b ma\u0142ym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I surprise you with something small?';
UPDATE questions
SET translations = '{"en": "How important is it to you that a gift feels personal or symbolic?", "da": "Hvor vigtigt er det for dig, at en gave f\u00f8les personlig eller symbolsk?", "de": "Wie wichtig ist es dir, dass ein Geschenk pers\u00f6nlich oder symbolisch wirkt?", "es": "\u00bfQu\u00e9 tan importante es para ti que un regalo se sienta personal o simb\u00f3lico?", "pt": "Qu\u00e3o importante \u00e9 para ti que um presente pare\u00e7a pessoal ou simb\u00f3lico?", "ro": "C\u00e2t de important este pentru tine ca un cadou s\u0103 fie personal sau simbolic?", "fr": "Quelle importance accordes-tu au fait qu\u2019un cadeau soit personnel ou symbolique ?", "it": "Quanto \u00e8 importante per te che un regalo sembri personale o simbolico?", "fi": "Kuinka t\u00e4rke\u00e4\u00e4 sinulle on, ett\u00e4 lahja tuntuu henkil\u00f6kohtaiselta tai symboliselta?", "nl": "Hoe belangrijk is het voor jou dat een cadeau persoonlijk of symbolisch aanvoelt?", "no": "Hvor viktig er det for deg at en gave f\u00f8les personlig eller symbolsk?", "sv": "Hur viktigt \u00e4r det f\u00f6r dig att en present k\u00e4nns personlig eller symbolisk?", "pl": "Jak wa\u017cne jest dla Ciebie, aby prezent by\u0142 osobisty lub symboliczny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How important is it to you that a gift feels personal or symbolic?';