UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019ve done that took real courage?", "da": "Hvad har du gjort, der kr\u00e6vede \u00e6gte mod?", "de": "Was hast du getan, das echten Mut erforderte?", "es": "\u00bfQu\u00e9 has hecho que requiri\u00f3 verdadero valor?", "pt": "O que voc\u00ea fez que exigiu coragem de verdade?", "ro": "Ce ai f\u0103cut care a cerut curaj adev\u0103rat?", "fr": "Qu\u2019as-tu fait qui t\u2019a demand\u00e9 un vrai courage ?", "it": "Qualcosa che hai fatto che ha richiesto davvero coraggio?", "fi": "Mik\u00e4 on jotain, mit\u00e4 olet tehnyt, mik\u00e4 vaati todellista rohkeutta?", "nl": "Wat is iets dat je hebt gedaan dat echte moed vergde?", "no": "Hva er noe du har gjort som krevde ekte mot?", "sv": "Vad \u00e4r n\u00e5got du har gjort som kr\u00e4vde riktig mod?", "pl": "Co\u015b, co zrobi\u0142e\u015b, co wymaga\u0142o prawdziwej odwagi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you’ve done that took real courage?';
UPDATE questions
SET translations = '{"en": "What\u2019s a random skill you\u2019re oddly proud of?", "da": "Hvad er en tilf\u00e6ldig evne, du er m\u00e6rkeligt stolt af?", "de": "Welche zuf\u00e4llige F\u00e4higkeit macht dich seltsam stolz?", "es": "\u00bfQu\u00e9 habilidad aleatoria te enorgullece de forma extra\u00f1a?", "pt": "Qual habilidade aleat\u00f3ria te deixa estranhamente orgulhoso(a)?", "ro": "Care este o abilitate aleatoare de care e\u0219ti ciudat de m\u00e2ndru(\u0103)?", "fr": "Quelle comp\u00e9tence al\u00e9atoire te rend \u00e9trangement fier/fi\u00e8re ?", "it": "Qual \u00e8 una abilit\u00e0 casuale di cui sei stranamente orgoglioso?", "fi": "Mik\u00e4 on satunnainen taito, josta olet outoa ylpe\u00e4?", "nl": "Wat is een willekeurige vaardigheid waar je vreemd genoeg trots op bent?", "no": "Hva er en tilfeldig ferdighet du er merkelig stolt av?", "sv": "Vilken slumpm\u00e4ssig f\u00e4rdighet \u00e4r du konstigt stolt \u00f6ver?", "pl": "Jak\u0105\u015b przypadkow\u0105 umiej\u0119tno\u015bci\u0105, z kt\u00f3rej jeste\u015b dziwnie dumny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a random skill you’re oddly proud of?';
UPDATE questions
SET translations = '{"en": "If you could swap lives with someone for 24 hours, who would it be?", "da": "Hvis du kunne bytte liv med nogen i 24 timer, hvem skulle det v\u00e6re?", "de": "Wenn du f\u00fcr 24 Stunden mit jemandem das Leben tauschen k\u00f6nntest, wer w\u00e4re es?", "es": "Si pudieras intercambiar vidas con alguien por 24 horas, \u00bfqui\u00e9n ser\u00eda?", "pt": "Se voc\u00ea pudesse trocar de vida com algu\u00e9m por 24 horas, quem seria?", "ro": "Dac\u0103 ai putea face schimb de vie\u021bi cu cineva pentru 24 de ore, cine ar fi?", "fr": "Si tu pouvais \u00e9changer ta vie avec quelqu\u2019un pendant 24 heures, qui serait-ce ?", "it": "Se potessi scambiare la vita con qualcuno per 24 ore, chi sarebbe?", "fi": "Jos voisit vaihtaa el\u00e4m\u00e4\u00e4 jonkun kanssa 24 tunniksi, kuka se olisi?", "nl": "Als je 24 uur van leven zou kunnen ruilen met iemand, wie zou dat dan zijn?", "no": "Hvis du kunne bytte liv med noen i 24 timer, hvem ville det v\u00e6rt?", "sv": "Om du kunde byta liv med n\u00e5gon i 24 timmar, vem skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zamieni\u0107 si\u0119 \u017cyciem z kim\u015b na 24 godziny, z kim by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could swap lives with someone for 24 hours, who would it be?';
UPDATE questions
SET translations = '{"en": "If we all started a band, what would we be called?", "da": "Hvis vi alle startede et band, hvad skulle vi s\u00e5 hedde?", "de": "Wenn wir alle eine Band gr\u00fcnden w\u00fcrden, wie w\u00fcrden wir hei\u00dfen?", "es": "Si todos form\u00e1ramos una banda, \u00bfc\u00f3mo nos llamar\u00edamos?", "pt": "Se todos n\u00f3s form\u00e1ssemos uma banda, qual seria o nome?", "ro": "Dac\u0103 am forma cu to\u021bii o trup\u0103, cum s-ar numi?", "fr": "Si nous formions tous un groupe, comment s\u2019appellerait-il ?", "it": "Se tutti noi iniziassimo una band, come ci chiameremmo?", "fi": "Jos me kaikki perustaisimme b\u00e4ndin, mik\u00e4 sen nimi olisi?", "nl": "Als we allemaal een band zouden beginnen, hoe zouden we dan heten?", "no": "Hvis vi alle startet et band, hva ville vi hete?", "sv": "Om vi alla startade ett band, vad skulle vi heta?", "pl": "Je\u015bli wszyscy za\u0142o\u017cyliby\u015bmy zesp\u00f3\u0142, jak by\u015bmy si\u0119 nazywali?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If we all started a band, what would we be called?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most romantic thing someone\u2019s ever done for you?", "da": "Hvad er det mest romantiske, nogen nogensinde har gjort for dig?", "de": "Was ist das Romantischste, das jemand je f\u00fcr dich getan hat?", "es": "\u00bfQu\u00e9 es lo m\u00e1s rom\u00e1ntico que alguien ha hecho por ti?", "pt": "Qual foi a coisa mais rom\u00e2ntica que algu\u00e9m j\u00e1 fez por voc\u00ea?", "ro": "Care este cel mai romantic lucru pe care cineva l-a f\u0103cut pentru tine?", "fr": "Quelle est la chose la plus romantique qu\u2019on ait faite pour toi ?", "it": "Qual \u00e8 la cosa pi\u00f9 romantica che qualcuno abbia mai fatto per te?", "fi": "Mik\u00e4 on romanttisin asia, jonka joku on koskaan tehnyt puolestasi?", "nl": "Wat is het meest romantische dat iemand ooit voor je heeft gedaan?", "no": "Hva er det mest romantiske noen har gjort for deg?", "sv": "Vad \u00e4r det mest romantiska n\u00e5gon n\u00e5gonsin har gjort f\u00f6r dig?", "pl": "Co by\u0142o najbardziej romantycznym gestem, jaki kto\u015b dla ciebie zrobi\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s the most romantic thing someone’s ever done for you?';
UPDATE questions
SET translations = '{"en": "What\u2019s one lesson past relationships taught you?", "da": "Hvilken lektie har tidligere forhold l\u00e6rt dig?", "de": "Welche Lektion haben dir fr\u00fchere Beziehungen beigebracht?", "es": "\u00bfQu\u00e9 lecci\u00f3n te ense\u00f1aron las relaciones pasadas?", "pt": "Que li\u00e7\u00e3o os relacionamentos passados te ensinaram?", "ro": "Ce lec\u021bie te-au \u00eenv\u0103\u021bat rela\u021biile trecute?", "fr": "Quelle le\u00e7on tes relations pass\u00e9es t\u2019ont-elles apprise ?", "it": "Qual \u00e8 una lezione che le relazioni passate ti hanno insegnato?", "fi": "Mik\u00e4 on yksi oppi, jonka menneet suhteet ovat opettaneet sinulle?", "nl": "Wat is \u00e9\u00e9n les die je uit eerdere relaties hebt geleerd?", "no": "Hva er en l\u00e6rdom tidligere forhold har l\u00e6rt deg?", "sv": "Vilken l\u00e4rdom har tidigare relationer l\u00e4rt dig?", "pl": "Jak\u0105 jedn\u0105 lekcj\u0119 nauczy\u0142y ci\u0119 przesz\u0142e zwi\u0105zki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s one lesson past relationships taught you?';
UPDATE questions
SET translations = '{"en": "Do you believe in love at first sight \u2014 or slow burn?", "da": "Tror du p\u00e5 k\u00e6rlighed ved f\u00f8rste blik \u2014 eller langsomt voksende k\u00e6rlighed?", "de": "Glaubst du an Liebe auf den ersten Blick \u2013 oder an langsames Entflammen?", "es": "\u00bfCrees en el amor a primera vista o en el amor que crece lentamente?", "pt": "Voc\u00ea acredita em amor \u00e0 primeira vista \u2014 ou em amor que cresce com o tempo?", "ro": "Crezi \u00een dragoste la prima vedere sau \u00eentr-o dragoste care cre\u0219te lent?", "fr": "Crois-tu au coup de foudre \u2014 ou \u00e0 l\u2019amour qui grandit lentement ?", "it": "Credi nell''amore a prima vista o in un amore che si sviluppa lentamente?", "fi": "Uskotko rakkauteen ensisilm\u00e4yksell\u00e4 vai hitaaseen syttymiseen?", "nl": "Geloof je in liefde op het eerste gezicht \u2014 of in een langzame opbouw?", "no": "Tror du p\u00e5 kj\u00e6rlighet ved f\u00f8rste blikk \u2014 eller en langsom oppbygging?", "sv": "Tror du p\u00e5 k\u00e4rlek vid f\u00f6rsta \u00f6gonkastet \u2014 eller en l\u00e5ngsam brasa?", "pl": "Czy wierzysz w mi\u0142o\u015b\u0107 od pierwszego wejrzenia, czy raczej w powolne rozpalanie uczucia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Do you believe in love at first sight — or slow burn?';
UPDATE questions
SET translations = '{"en": "What\u2019s one relationship \u201cgreen flag\u201d you\u2019ve learned to appreciate more with age?", "da": "Hvilket \u201cgr\u00f8nt flag\u201d i et forhold har du l\u00e6rt at s\u00e6tte mere pris p\u00e5 med alderen?", "de": "Welches \u201egr\u00fcne Beziehungsflagge\u201c hast du mit dem Alter mehr zu sch\u00e4tzen gelernt?", "es": "\u00bfQu\u00e9 \u201cbandera verde\u201d en una relaci\u00f3n has aprendido a valorar con los a\u00f1os?", "pt": "Que \u201csinal verde\u201d em um relacionamento voc\u00ea aprendeu a valorizar com o tempo?", "ro": "Ce \u201esemn verde\u201d \u00eentr-o rela\u021bie ai \u00eenv\u0103\u021bat s\u0103 apreciezi mai mult odat\u0103 cu v\u00e2rsta?", "fr": "Quel \u00ab drapeau vert \u00bb relationnel as-tu appris \u00e0 mieux appr\u00e9cier avec l\u2019\u00e2ge ?", "it": "Qual \u00e8 un \"segnale verde\" in una relazione che hai imparato ad apprezzare di pi\u00f9 con l''et\u00e0?", "fi": "Mik\u00e4 on yksi suhteen \"vihre\u00e4 lippu\", jota olet oppinut arvostamaan enemm\u00e4n i\u00e4n my\u00f6t\u00e4?", "nl": "Wat is \u00e9\u00e9n relatie \"groene vlag\" die je met de jaren meer bent gaan waarderen?", "no": "Hva er en relasjons \"gr\u00f8nn flagg\" du har l\u00e6rt \u00e5 sette mer pris p\u00e5 med alderen?", "sv": "Vilken \"gr\u00f6n flagga\" i en relation har du l\u00e4rt dig att uppskatta mer med \u00e5ldern?", "pl": "Jak\u0105 jedn\u0105 \u201ezielon\u0105 flag\u0119\u201d w relacjach nauczy\u0142e\u015b si\u0119 bardziej docenia\u0107 z wiekiem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s one relationship “green flag” you’ve learned to appreciate more with age?';
UPDATE questions
SET translations = '{"en": "Do you believe people can fall in love more than once?", "da": "Tror du, folk kan blive forelskede mere end \u00e9n gang?", "de": "Glaubst du, dass Menschen sich mehr als einmal verlieben k\u00f6nnen?", "es": "\u00bfCrees que las personas pueden enamorarse m\u00e1s de una vez?", "pt": "Voc\u00ea acredita que as pessoas podem se apaixonar mais de uma vez?", "ro": "Crezi c\u0103 oamenii se pot \u00eendr\u0103gosti de mai multe ori?", "fr": "Penses-tu qu\u2019on puisse tomber amoureux plus d\u2019une fois ?", "it": "Credi che le persone possano innamorarsi pi\u00f9 di una volta?", "fi": "Uskotko, ett\u00e4 ihmiset voivat rakastua useammin kuin kerran?", "nl": "Geloof je dat mensen meer dan eens verliefd kunnen worden?", "no": "Tror du folk kan bli forelsket mer enn \u00e9n gang?", "sv": "Tror du att m\u00e4nniskor kan bli k\u00e4ra mer \u00e4n en g\u00e5ng?", "pl": "Czy wierzysz, \u017ce ludzie mog\u0105 zakochiwa\u0107 si\u0119 wi\u0119cej ni\u017c raz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Do you believe people can fall in love more than once?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019d tell your younger self about relationships?", "da": "Hvad ville du fort\u00e6lle dit yngre jeg om forhold?", "de": "Was w\u00fcrdest du deinem j\u00fcngeren Ich \u00fcber Beziehungen sagen?", "es": "\u00bfQu\u00e9 le dir\u00edas a tu yo m\u00e1s joven sobre las relaciones?", "pt": "O que voc\u00ea diria ao seu eu mais jovem sobre relacionamentos?", "ro": "Ce i-ai spune versiunii tale mai tinere despre rela\u021bii?", "fr": "Que dirais-tu \u00e0 ton toi plus jeune \u00e0 propos des relations ?", "it": "Cosa diresti al tuo io pi\u00f9 giovane riguardo alle relazioni?", "fi": "Mit\u00e4 kertoisit nuoremmalle itsellesi ihmissuhteista?", "nl": "Wat is iets dat je tegen je jongere zelf zou zeggen over relaties?", "no": "Hva er noe du ville sagt til ditt yngre jeg om forhold?", "sv": "Vad skulle du s\u00e4ga till ditt yngre jag om relationer?", "pl": "Co by\u015b powiedzia\u0142 swojemu m\u0142odszemu ja na temat zwi\u0105zk\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you’d tell your younger self about relationships?';
UPDATE questions
SET translations = '{"en": "Who\u2019s someone you''d like to call and catch up with? ", "da": "Hvem er en, du gerne vil ringe til og f\u00e5 snakket ordentligt med igen?", "de": "Mit wem w\u00fcrdest du gerne mal wieder telefonieren und richtig quatschen?", "es": "\u00bfA qui\u00e9n te gustar\u00eda llamar para ponerte al d\u00eda?", "pt": "Para quem voc\u00ea gostaria de ligar para colocar a conversa em dia?", "ro": "Pe cine \u021bi-ar pl\u0103cea s\u0103 suni ca s\u0103 mai sta\u021bi de vorb\u0103 \u0219i s\u0103 v\u0103 pune\u021bi la curent?", "fr": "Avec qui aimerais-tu passer un coup de fil pour prendre des nouvelles et papoter un peu ?", "it": "Chi \u00e8 qualcuno con cui ti piacerebbe telefonare e fare due chiacchiere?", "fi": "Kuka on joku, jota haluaisit soittaa ja vaihtaa kuulumisia?", "nl": "Wie is iemand met wie je graag zou willen bellen om bij te praten?", "no": "Hvem er det du gjerne vil ringe og ta en prat med?", "sv": "Vem \u00e4r n\u00e5gon du skulle vilja ringa och prata med?", "pl": "Kto jest osob\u0105, z kt\u00f3r\u0105 chcia\u0142by\u015b zadzwoni\u0107 i nadrobi\u0107 zaleg\u0142o\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who’s someone you''d like to call and catch up with? ';
UPDATE questions
SET translations = '{"en": "Concert edition: which artist or band would you drop everything to see live?", "da": "Koncert-udgave: Hvilken kunstner eller hvilket band ville du droppe alt for at se live?", "de": "Konzert-Edition: F\u00fcr welchen K\u00fcnstler oder welche Band w\u00fcrdest du alles stehen und liegen lassen, um sie live zu sehen?", "es": "Edici\u00f3n conciertos: \u00bfpor qu\u00e9 artista o banda dejar\u00edas todo para verlo/a en directo?", "pt": "Edi\u00e7\u00e3o show: por qual artista ou banda voc\u00ea largaria tudo para ver ao vivo?", "ro": "Edi\u021bia concert: pentru ce artist sau trup\u0103 ai l\u0103sa totul ca s\u0103-i vezi live?", "fr": "\u00c9dition concert : pour quel artiste ou groupe laisserais-tu tout tomber pour le voir en live ?", "it": "Edizione concerto: quale artista o band lasceresti tutto per vedere dal vivo?", "fi": "Konserttiin liittyen: mink\u00e4 artistin tai b\u00e4ndin esityksen vuoksi j\u00e4tt\u00e4isit kaiken muun?", "nl": "Concert editie: welke artiest of band zou je alles laten vallen om live te zien?", "no": "Konsertutgave: Hvilken artist eller band ville du gi opp alt for \u00e5 se live?", "sv": "Konsertutg\u00e5van: vilken artist eller band skulle du sl\u00e4ppa allt f\u00f6r att se live?", "pl": "Edycja koncertowa: kt\u00f3rego artyst\u0119 lub zesp\u00f3\u0142 by\u0142by\u015b got\u00f3w porzuci\u0107 wszystko, aby zobaczy\u0107 na \u017cywo?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Concert edition: which artist or band would you drop everything to see live?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people overhype way too much?", "da": "Hvad er noget, folk overvurderer alt for meget?", "de": "Was ist etwas, das die Leute total \u00fcberbewerten?", "es": "\u00bfQu\u00e9 es algo que la gente sobrevalora demasiado?", "pt": "O que as pessoas supervalorizam demais?", "ro": "Ce e ceva ce oamenii supraevalueaz\u0103 prea mult?", "fr": "Quelle chose les gens surestiment-ils beaucoup trop ?", "it": "Qual \u00e8 qualcosa che la gente esalta troppo?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ylikorostavat aivan liikaa?", "nl": "Wat is iets dat mensen veel te veel ophemelen?", "no": "Hva er noe folk overhypet altfor mye?", "sv": "Vad \u00e4r n\u00e5got som folk \u00f6verhypa alldeles f\u00f6r mycket?", "pl": "Co\u015b, co ludzie zdecydowanie za bardzo wyolbrzymiaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something people overhype way too much?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think should be normalized?", "da": "Hvad er \u00e9n ting, du synes b\u00f8r blive normaliseret?", "de": "Was ist eine Sache, die deiner Meinung nach normalisiert werden sollte?", "es": "\u00bfQu\u00e9 cosa crees que deber\u00eda normalizarse?", "pt": "O que voc\u00ea acha que deveria ser normalizado?", "ro": "Ce crezi c\u0103 ar trebui normalizat?", "fr": "Quelle chose penses-tu qu\u2019on devrait normaliser ?", "it": "Qual \u00e8 una cosa che pensi dovrebbe essere normalizzata?", "fi": "Mik\u00e4 on yksi asia, jonka ajattelet pit\u00e4isi normalisoida?", "nl": "Wat is \u00e9\u00e9n ding dat volgens jou genormaliseerd zou moeten worden?", "no": "Hva er \u00e9n ting du mener burde bli normalisert?", "sv": "Vad \u00e4r en sak som du tycker borde normaliseras?", "pl": "Co\u015b, co twoim zdaniem powinno by\u0107 znormalizowane?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s one thing you think should be normalized?';
UPDATE questions
SET translations = '{"en": "What\u2019s a fashion trend you\u2019ll never understand?", "da": "Hvilken modetrend vil du aldrig forst\u00e5?", "de": "Welchen Modetrend wirst du nie verstehen?", "es": "\u00bfQu\u00e9 tendencia de moda nunca entender\u00e1s?", "pt": "Qual tend\u00eancia de moda voc\u00ea nunca vai entender?", "ro": "Ce tendin\u021b\u0103 de mod\u0103 nu vei \u00een\u021belege niciodat\u0103?", "fr": "Quelle tendance mode ne comprendras-tu jamais ?", "it": "Qual \u00e8 una tendenza della moda che non capirai mai?", "fi": "Mik\u00e4 on muotitrendi, jota et koskaan tule ymm\u00e4rt\u00e4m\u00e4\u00e4n?", "nl": "Wat is een mode trend die je nooit zult begrijpen?", "no": "Hva er en motetrend du aldri vil forst\u00e5?", "sv": "Vilken modetrend kommer du aldrig att f\u00f6rst\u00e5?", "pl": "Jaki trend modowy, kt\u00f3rego nigdy nie zrozumiesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a fashion trend you’ll never understand?';
UPDATE questions
SET translations = '{"en": "What\u2019s your comfort show or book\u2014and why that one?", "da": "Hvad er dit \u201ccomfort show\u201d eller din yndlingsbog \u2014 og hvorfor netop den?", "de": "Was ist deine Komfortserie oder dein Lieblingsbuch \u2013 und warum genau das?", "es": "\u00bfCu\u00e1l es tu serie o libro de consuelo \u2014 y por qu\u00e9 ese?", "pt": "Qual \u00e9 sua s\u00e9rie ou livro de conforto \u2014 e por que esse?", "ro": "Care este serialul sau cartea ta de confort \u2014 \u0219i de ce aceea?", "fr": "Quelle est ta s\u00e9rie ou ton livre r\u00e9confortant \u2014 et pourquoi celui-l\u00e0 ?", "it": "Qual \u00e8 il tuo programma o libro di conforto\u2014e perch\u00e9 proprio quello?", "fi": "Mik\u00e4 on sinun mukavuusohjelmasi tai -kirjasi \u2013 ja miksi juuri se?", "nl": "Wat is jouw favoriete comfortshow of boek - en waarom die?", "no": "Hva er ditt komfortprogram eller bok \u2013 og hvorfor akkurat den?", "sv": "Vilken \u00e4r din trygghetsserie eller bok \u2013 och varf\u00f6r just den?", "pl": "Jaki jest tw\u00f3j ulubiony serial lub ksi\u0105\u017cka, kt\u00f3ra daje ci poczucie komfortu \u2013 i dlaczego akurat ten?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your comfort show or book—and why that one?';
UPDATE questions
SET translations = '{"en": "Who in this group would be the worst at keeping a secret?", "da": "Hvem i denne gruppe ville v\u00e6re d\u00e5rligst til at holde p\u00e5 en hemmelighed?", "de": "Wer in dieser Gruppe w\u00e4re am schlechtesten darin, ein Geheimnis zu bewahren?", "es": "\u00bfQui\u00e9n en este grupo ser\u00eda el peor guardando un secreto?", "pt": "Quem neste grupo seria o pior em guardar um segredo?", "ro": "Cine din acest grup ar fi cel mai prost la a p\u0103stra un secret?", "fr": "Qui dans ce groupe serait le pire pour garder un secret ?", "it": "Chi in questo gruppo sarebbe il peggiore a mantenere un segreto?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 olisi huonoin pit\u00e4m\u00e4\u00e4n salaisuutta?", "nl": "Wie in deze groep zou het slechtst zijn in het bewaren van een geheim?", "no": "Hvem i denne gruppen ville v\u00e6rt d\u00e5rligst til \u00e5 holde en hemmelighet?", "sv": "Vem i den h\u00e4r gruppen skulle vara s\u00e4mst p\u00e5 att h\u00e5lla en hemlighet?", "pl": "Kto w tej grupie by\u0142by najgorszy w utrzymywaniu tajemnicy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who in this group would be the worst at keeping a secret?';
UPDATE questions
SET translations = '{"en": "Is there anything embarrassing you once posted online?", "da": "Har du nogensinde lagt noget pinligt ud online?", "de": "Hast du jemals etwas Peinliches online gepostet?", "es": "\u00bfHas publicado alguna vez algo embarazoso en l\u00ednea?", "pt": "Voc\u00ea j\u00e1 postou algo constrangedor na internet?", "ro": "Ai postat vreodat\u0103 ceva jenant online?", "fr": "As-tu d\u00e9j\u00e0 post\u00e9 quelque chose d\u2019embarrassant en ligne ?", "it": "C''\u00e8 qualcosa di imbarazzante che hai postato online una volta?", "fi": "Onko jotain h\u00e4pe\u00e4llist\u00e4, mit\u00e4 olet joskus julkaissut verkossa?", "nl": "Is er iets beschamends dat je ooit online hebt gepost?", "no": "Er det noe pinlig du en gang la ut p\u00e5 nettet?", "sv": "\u00c4r det n\u00e5got pinsamt som du en g\u00e5ng postade online?", "pl": "Czy jest co\u015b kr\u0119puj\u0105cego, co kiedy\u015b opublikowa\u0142e\u015b w internecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Is there anything embarrassing you once posted online?';
UPDATE questions
SET translations = '{"en": "Who in this room would make the best celebrity?", "da": "Hvem i dette rum ville blive den bedste kendis?", "de": "Wer in diesem Raum w\u00e4re der beste Promi?", "es": "\u00bfQui\u00e9n en esta sala ser\u00eda la mejor celebridad?", "pt": "Quem nesta sala seria a melhor celebridade?", "ro": "Cine din aceast\u0103 camer\u0103 ar deveni cea mai bun\u0103 celebritate?", "fr": "Qui dans cette pi\u00e8ce ferait la meilleure c\u00e9l\u00e9brit\u00e9 ?", "it": "Chi in questa stanza diventerebbe la migliore celebrit\u00e0?", "fi": "Kuka t\u00e4ss\u00e4 huoneessa olisi paras julkkis?", "nl": "Wie in deze kamer zou de beste beroemdheid zijn?", "no": "Hvem i dette rommet ville blitt den beste kjendisen?", "sv": "Vem i det h\u00e4r rummet skulle bli den b\u00e4sta k\u00e4ndisen?", "pl": "Kto w tym pomieszczeniu by\u0142by najlepsz\u0105 gwiazd\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who in this room would make the best celebrity?';
UPDATE questions
SET translations = '{"en": "If you could change one thing about modern dating culture, what would it be?", "da": "Hvis du kunne \u00e6ndre \u00e9n ting ved moderne datingkultur, hvad skulle det v\u00e6re?", "de": "Wenn du eine Sache an der modernen Datingkultur \u00e4ndern k\u00f6nntest, was w\u00e4re das?", "es": "Si pudieras cambiar una cosa de la cultura moderna de citas, \u00bfqu\u00e9 ser\u00eda?", "pt": "Se voc\u00ea pudesse mudar uma coisa na cultura moderna de namoro, o que seria?", "ro": "Dac\u0103 ai putea schimba un lucru \u00een cultura modern\u0103 a \u00eent\u00e2lnirilor, care ar fi?", "fr": "Si tu pouvais changer une chose dans la culture moderne des rencontres, que serait-ce ?", "it": "Se potessi cambiare una cosa della cultura moderna degli appuntamenti, quale sarebbe?", "fi": "Jos voisit muuttaa yhden asian nykyp\u00e4iv\u00e4n deittailukulttuurissa, mik\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n ding aan de moderne datingcultuur zou kunnen veranderen, wat zou dat dan zijn?", "no": "Hvis du kunne endre \u00e9n ting med den moderne datingkulturen, hva ville det v\u00e6rt?", "sv": "Om du kunde f\u00f6r\u00e4ndra en sak med den moderna dejtingkulturen, vad skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zmieni\u0107 jedn\u0105 rzecz w nowoczesnej kulturze randkowania, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could change one thing about modern dating culture, what would it be?';
UPDATE questions
SET translations = '{"en": "If gossip were a sport, who here would win gold?", "da": "Hvis sladder var en sport, hvem her ville vinde guld?", "de": "Wenn Klatsch eine Sportart w\u00e4re, wer hier w\u00fcrde Gold gewinnen?", "es": "Si el chisme fuera un deporte, \u00bfqui\u00e9n aqu\u00ed ganar\u00eda el oro?", "pt": "Se fofoca fosse um esporte, quem aqui ganharia ouro?", "ro": "Dac\u0103 b\u00e2rfa ar fi un sport, cine de aici ar c\u00e2\u0219tiga aurul?", "fr": "Si les comm\u00e9rages \u00e9taient un sport, qui ici remporterait l\u2019or ?", "it": "Se il pettegolezzo fosse uno sport, chi qui vincerebbe l''oro?", "fi": "Jos juoruilu olisi urheilulaji, kuka t\u00e4\u00e4ll\u00e4 voittaisi kultamitalin?", "nl": "Als roddelen een sport was, wie hier zou dan goud winnen?", "no": "Hvis sladder var en sport, hvem her ville vinne gull?", "sv": "Om skvaller vore en sport, vem h\u00e4r skulle vinna guld?", "pl": "Gdyby plotki by\u0142y sportem, kto tutaj zdoby\u0142by z\u0142oty medal?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If gossip were a sport, who here would win gold?';
UPDATE questions
SET translations = '{"en": "If your high school classmates saw you now, what would surprise them most?", "da": "Hvis dine skolekammerater s\u00e5 dig nu, hvad ville overraske dem mest?", "de": "Wenn deine Schulfreunde dich jetzt sehen w\u00fcrden, was w\u00fcrde sie am meisten \u00fcberraschen?", "es": "Si tus compa\u00f1eros de escuela te vieran ahora, \u00bfqu\u00e9 los sorprender\u00eda m\u00e1s?", "pt": "Se seus colegas de escola te vissem agora, o que mais os surpreenderia?", "ro": "Dac\u0103 colegii t\u0103i de liceu te-ar vedea acum, ce i-ar surprinde cel mai mult?", "fr": "Si tes anciens camarades de classe te voyaient maintenant, qu\u2019est-ce qui les surprendrait le plus ?", "it": "Se i tuoi compagni di scuola superiore ti vedessero adesso, cosa li sorprenderebbe di pi\u00f9?", "fi": "Jos lukioaikaiset luokkatoverisi n\u00e4kiv\u00e4t sinut nyt, mik\u00e4 heit\u00e4 yll\u00e4tt\u00e4isi eniten?", "nl": "Als je middelbare schoolklasgenoten je nu zouden zien, wat zou hen dan het meest verbazen?", "no": "Hvis klassekameratene dine fra videreg\u00e5ende s\u00e5 deg n\u00e5, hva ville overrasket dem mest?", "sv": "Om dina gymnasieklasskamrater s\u00e5g dig nu, vad skulle \u00f6verraska dem mest?", "pl": "Gdyby twoi koledzy z liceum zobaczyli ci\u0119 teraz, co najbardziej by ich zaskoczy\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If your high school classmates saw you now, what would surprise them most?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you once pretended to understand but totally didn\u2019t?", "da": "Hvad har du engang ladet som om, du forstod, men faktisk ikke gjorde?", "de": "Was hast du einmal vorgegeben zu verstehen, obwohl du es nicht tatest?", "es": "\u00bfQu\u00e9 fingiste entender alguna vez pero realmente no entendiste?", "pt": "O que voc\u00ea fingiu entender, mas na verdade n\u00e3o entendeu?", "ro": "Ce ai pretins odat\u0103 c\u0103 \u00een\u021belegi, dar nu ai \u00een\u021beles de fapt?", "fr": "Qu\u2019as-tu d\u00e9j\u00e0 pr\u00e9tendu comprendre alors que tu ne comprenais pas du tout ?", "it": "Qualcosa che una volta hai fatto finta di capire ma in realt\u00e0 non capivi affatto?", "fi": "Mik\u00e4 on jotain, mit\u00e4 kerran teeskentelit ymm\u00e4rt\u00e4v\u00e4si, mutta et todellakaan ymm\u00e4rt\u00e4nyt?", "nl": "Wat is iets waarvan je ooit deed alsof je het begreep, maar dat totaal niet deed?", "no": "Hva er noe du en gang lot som du forsto, men som du absolutt ikke gjorde?", "sv": "Vad \u00e4r n\u00e5got du en g\u00e5ng l\u00e5tsades f\u00f6rst\u00e5 men verkligen inte gjorde?", "pl": "Co\u015b, co kiedy\u015b udawa\u0142e\u015b, \u017ce rozumiesz, ale tak naprawd\u0119 nie mia\u0142e\u015b poj\u0119cia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you once pretended to understand but totally didn’t?';
UPDATE questions
SET translations = '{"en": "Who here do you think flirts without even realizing it?", "da": "Hvem her tror du flirter uden at vide det?", "de": "Wer hier flirtet, ohne es zu merken?", "es": "\u00bfQui\u00e9n aqu\u00ed crees que coquetea sin darse cuenta?", "pt": "Quem aqui voc\u00ea acha que flerta sem perceber?", "ro": "Cine de aici flirteaz\u0103 f\u0103r\u0103 s\u0103-\u0219i dea seama?", "fr": "Qui ici flirte sans m\u00eame s\u2019en rendre compte ?", "it": "Chi pensi qui flirta senza nemmeno rendersene conto?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 mielest\u00e4si flirttailee ilman, ett\u00e4 edes huomaa sit\u00e4?", "nl": "Wie denk je dat hier flirt zonder het zelfs maar te beseffen?", "no": "Hvem her tror du fl\u00f8rter uten engang \u00e5 innse det?", "sv": "Vem h\u00e4r tror du fl\u00f6rtar utan att ens inse det?", "pl": "Kto tutaj, twoim zdaniem, flirtuje, nawet tego nie zauwa\u017caj\u0105c?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who here do you think flirts without even realizing it?';
UPDATE questions
SET translations = '{"en": "What\u2019s a tiny decision that ended up changing everything for you?", "da": "Hvad er en lille beslutning, der endte med at \u00e6ndre alt for dig?", "de": "Was ist eine kleine Entscheidung, die am Ende alles f\u00fcr dich ver\u00e4ndert hat?", "es": "\u00bfCu\u00e1l es una peque\u00f1a decisi\u00f3n que termin\u00f3 cambi\u00e1ndolo todo para ti?", "pt": "Qual foi uma pequena decis\u00e3o que acabou mudando tudo para voc\u00ea?", "ro": "Care este o mic\u0103 decizie care \u021bi-a schimbat totul?", "fr": "Quelle petite d\u00e9cision a fini par tout changer pour toi ?", "it": "Qual \u00e8 stata una piccola decisione che alla fine ha cambiato tutto per te?", "fi": "Mik\u00e4 on pieni p\u00e4\u00e4t\u00f6s, joka lopulta muutti kaiken sinulle?", "nl": "Wat is een kleine beslissing die uiteindelijk alles voor jou heeft veranderd?", "no": "Hva er en liten beslutning som endte opp med \u00e5 forandre alt for deg?", "sv": "Vilket litet beslut har slutat med att f\u00f6r\u00e4ndra allt f\u00f6r dig?", "pl": "Jakie ma\u0142e postanowienie zmieni\u0142o wszystko w twoim \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a tiny decision that ended up changing everything for you?';

-- Category: Deep Talks (75 questions)
UPDATE questions
SET translations = '{"en": "In what ways were we raised similarly and differently?", "da": "P\u00e5 hvilke m\u00e5der blev vi opdraget ens og forskelligt?", "de": "In welcher Hinsicht sind wir \u00e4hnlich und unterschiedlich aufgewachsen?", "es": "\u00bfEn qu\u00e9 aspectos fuimos criados de forma similar y diferente?", "pt": "De que maneiras fomos criados de forma parecida e diferente?", "ro": "\u00cen ce moduri am fost crescu\u021bi la fel \u0219i diferit?", "fr": "En quoi avons-nous \u00e9t\u00e9 \u00e9lev\u00e9s de mani\u00e8re similaire et diff\u00e9rente ?", "it": "In quali modi siamo stati cresciuti in modo simile e in modo diverso?", "fi": "Mill\u00e4 tavoin meid\u00e4t kasvatettiin samoin ja eri tavoin?", "nl": "Op welke manieren zijn we op vergelijkbare en verschillende manieren opgevoed?", "no": "P\u00e5 hvilke m\u00e5ter ble vi oppdratt likt og ulikt?", "sv": "P\u00e5 vilka s\u00e4tt blev vi uppfostrade p\u00e5 liknande och olika s\u00e4tt?", "pl": "W jakich aspektach byli\u015bmy wychowani podobnie, a w jakich r\u00f3\u017cnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'In what ways were we raised similarly and differently?';
UPDATE questions
SET translations = '{"en": "Which core value do you think holds a relationship together through hard times?", "da": "Hvilken kernev\u00e6rdi tror du holder et forhold sammen gennem sv\u00e6re tider?", "de": "Welcher Grundwert h\u00e4lt deiner Meinung nach eine Beziehung in schwierigen Zeiten zusammen?", "es": "\u00bfQu\u00e9 valor fundamental crees que mantiene una relaci\u00f3n unida en los momentos dif\u00edciles?", "pt": "Que valor fundamental achas que mant\u00e9m uma rela\u00e7\u00e3o unida em tempos dif\u00edceis?", "ro": "Ce valoare de baz\u0103 crezi c\u0103 men\u021bine o rela\u021bie unit\u0103 \u00een momentele grele?", "fr": "Quelle valeur essentielle, selon toi, maintient une relation unie dans les moments difficiles ?", "it": "Quale valore fondamentale pensi tenga un rapporto unito nei momenti difficili?", "fi": "Mik\u00e4 keskeinen arvo mielest\u00e4si pit\u00e4\u00e4 suhteen koossa vaikeina aikoina?", "nl": "Welke kernwaarde denk je dat een relatie bij elkaar houdt tijdens moeilijke tijden?", "no": "Hvilken kjerneverdi mener du holder et forhold sammen gjennom vanskelige tider?", "sv": "Vilken k\u00e4rnv\u00e4rde tycker du h\u00e5ller en relation samman genom sv\u00e5ra tider?", "pl": "Kt\u00f3ra z podstawowych warto\u015bci, twoim zdaniem, utrzymuje zwi\u0105zek razem w trudnych czasach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Which core value do you think holds a relationship together through hard times?';
UPDATE questions
SET translations = '{"en": "How do you think your parent''s relationship affected what you look for in a partner?", "da": "Hvordan tror du, dine for\u00e6ldres forhold har p\u00e5virket, hvad du leder efter i en partner?", "de": "Wie glaubst du, hat die Beziehung deiner Eltern beeinflusst, wonach du in einem Partner suchst?", "es": "\u00bfC\u00f3mo crees que la relaci\u00f3n de tus padres influy\u00f3 en lo que buscas en una pareja?", "pt": "Como voc\u00ea acha que o relacionamento dos seus pais influenciou o que voc\u00ea procura em um(a) parceiro(a)?", "ro": "Cum crezi c\u0103 rela\u021bia p\u0103rin\u021bilor t\u0103i a influen\u021bat ceea ce cau\u021bi la un partener?", "fr": "Comment penses-tu que la relation de tes parents a influenc\u00e9 ce que tu recherches chez un partenaire ?", "it": "Come pensi che la relazione dei tuoi genitori abbia influenzato ci\u00f2 che cerchi in un partner?", "fi": "Miten luulet vanhempiesi suhteen vaikuttaneen siihen, mit\u00e4 etsit kumppanilta?", "nl": "Hoe denk je dat de relatie van je ouders invloed heeft gehad op wat je zoekt in een partner?", "no": "Hvordan tror du forholdet til foreldrene dine har p\u00e5virket hva du ser etter i en partner?", "sv": "Hur tror du att dina f\u00f6r\u00e4ldrars relation har p\u00e5verkat vad du s\u00f6ker i en partner?", "pl": "Jak my\u015blisz, w jaki spos\u00f3b zwi\u0105zek twoich rodzic\u00f3w wp\u0142yn\u0105\u0142 na to, czego szukasz w partnerze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you think your parent''s relationship affected what you look for in a partner?';
UPDATE questions
SET translations = '{"en": "When do you feel most like your true self?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest som dit sande jeg?", "de": "Wann f\u00fchlst du dich am meisten wie dein wahres Selbst?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s como tu verdadero yo?", "pt": "Quando voc\u00ea se sente mais como seu verdadeiro eu?", "ro": "C\u00e2nd te sim\u021bi cel mai mult ca tine \u00eensu\u021bi(\u0103\u021bi)?", "fr": "Quand te sens-tu le plus comme ton vrai toi ?", "it": "Quando ti senti pi\u00f9 te stesso?", "fi": "Milloin tunnet itsesi eniten omaksi itseksesi?", "nl": "Wanneer voel je je het meest zoals je ware zelf?", "no": "N\u00e5r f\u00f8ler du deg mest som ditt sanne jeg?", "sv": "N\u00e4r k\u00e4nner du dig mest som ditt sanna jag?", "pl": "Kiedy czujesz si\u0119 najbardziej sob\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When do you feel most like your true self?';
UPDATE questions
SET translations = '{"en": "If you could go back in time ten years, what would you tell yourself?", "da": "Hvem af os har brug for mere k\u00e6rlighed for at f\u00f8le sig forbundet?", "de": "Wer von uns braucht mehr Zuneigung, um sich verbunden zu f\u00fchlen?", "es": "\u00bfQui\u00e9n de nosotros necesita m\u00e1s afecto para sentirse conectado?", "pt": "Quem de n\u00f3s precisa de mais afeto para se sentir conectado?", "ro": "Care dintre noi are nevoie de mai mult\u0103 afec\u021biune pentru a se sim\u021bi conectat?", "fr": "Lequel de nous a besoin de plus d\u2019affection pour se sentir connect\u00e9 ?", "it": "Se potessi tornare indietro nel tempo di dieci anni, cosa ti diresti?", "fi": "Jos voisit palata ajassa kymmenen vuotta taaksep\u00e4in, mit\u00e4 kertoisit itsellesi?", "nl": "Als je tien jaar terug in de tijd kon gaan, wat zou je tegen jezelf zeggen?", "no": "Hvis du kunne reise tilbake i tid ti \u00e5r, hva ville du sagt til deg selv?", "sv": "Om du kunde g\u00e5 tillbaka i tiden tio \u00e5r, vad skulle du s\u00e4ga till dig sj\u00e4lv?", "pl": "Gdyby\u015b m\u00f3g\u0142 cofn\u0105\u0107 si\u0119 w czasie o dziesi\u0119\u0107 lat, co by\u015b sobie powiedzia\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'If you could go back in time ten years, what would you tell yourself?';
UPDATE questions
SET translations = '{"en": "How can we both keep growing as individuals while still growing together?", "da": "Hvordan kan vi begge vokse som individer, mens vi stadig vokser sammen?", "de": "Wie k\u00f6nnen wir beide als Individuen wachsen, w\u00e4hrend wir zusammenwachsen?", "es": "\u00bfC\u00f3mo podemos seguir creciendo como individuos mientras crecemos juntos?", "pt": "Como podemos continuar crescendo como indiv\u00edduos enquanto crescemos juntos?", "ro": "Cum putem continua s\u0103 cre\u0219tem ca indivizi, \u00een timp ce cre\u0219tem \u00eempreun\u0103?", "fr": "Comment pouvons-nous continuer \u00e0 grandir individuellement tout en grandissant ensemble ?", "it": "Come possiamo entrambi continuare a crescere come individui mentre cresciamo insieme?", "fi": "Miten voimme molemmat kasvaa yksil\u00f6in\u00e4 samalla kun kasvamme yhdess\u00e4?", "nl": "Hoe kunnen we allebei blijven groeien als individuen terwijl we samen blijven groeien?", "no": "Hvordan kan vi begge fortsette \u00e5 vokse som individer samtidig som vi vokser sammen?", "sv": "Hur kan vi b\u00e5da forts\u00e4tta v\u00e4xa som individer samtidigt som vi v\u00e4xer tillsammans?", "pl": "Jak mo\u017cemy oboje nadal rozwija\u0107 si\u0119 jako jednostki, jednocze\u015bnie rozwijaj\u0105c si\u0119 razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How can we both keep growing as individuals while still growing together?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you miss about being on your own \u2014 and how can we make space for that within us?", "da": "Hvad savner du ved at v\u00e6re alene \u2014 og hvordan kan vi skabe plads til det i os?", "de": "Was vermisst du am Alleinsein \u2013 und wie k\u00f6nnen wir daf\u00fcr in uns Raum schaffen?", "es": "\u00bfQu\u00e9 extra\u00f1as de estar solo(a), y c\u00f3mo podemos hacer espacio para eso en nuestra relaci\u00f3n?", "pt": "O que voc\u00ea sente falta em estar sozinho(a) \u2014 e como podemos criar espa\u00e7o para isso entre n\u00f3s?", "ro": "Ce \u00ee\u021bi lipse\u0219te din a fi singur(\u0103) \u2014 \u0219i cum putem face loc pentru asta \u00eentre noi?", "fr": "Qu\u2019est-ce qui te manque dans le fait d\u2019\u00eatre seul(e), et comment pouvons-nous faire de la place pour cela dans notre relation ?", "it": "Cosa ti manca di pi\u00f9 del vivere da solo \u2014 e come possiamo fare spazio per questo dentro di noi?", "fi": "Mik\u00e4 on jotain, mit\u00e4 kaipaat omassa rauhassasi \u2014 ja miten voimme luoda tilaa sille meiss\u00e4?", "nl": "Wat mis je aan het alleen zijn \u2014 en hoe kunnen we ruimte maken voor dat binnen onszelf?", "no": "Hva er noe du savner med \u00e5 v\u00e6re alene \u2014 og hvordan kan vi gi plass til det i oss?", "sv": "Vad \u00e4r det som du saknar med att vara ensam \u2014 och hur kan vi skapa utrymme f\u00f6r det inom oss?", "pl": "Co\u015b, co t\u0119sknisz za byciem samodzielnym \u2014 i jak mo\u017cemy zrobi\u0107 miejsce na to w nas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s something you miss about being on your own — and how can we make space for that within us?';
UPDATE questions
SET translations = '{"en": "What does \u201cfreedom\u201d mean to you while being in a committed relationship?", "da": "Hvad betyder \u201cfrihed\u201d for dig i et forpligtende forhold?", "de": "Was bedeutet \u201eFreiheit\u201c f\u00fcr dich in einer festen Beziehung?", "es": "\u00bfQu\u00e9 significa \u201clibertad\u201d para ti dentro de una relaci\u00f3n comprometida?", "pt": "O que \u201cliberdade\u201d significa para voc\u00ea em um relacionamento comprometido?", "ro": "Ce \u00eenseamn\u0103 \u201elibertate\u201d pentru tine \u00eentr-o rela\u021bie serioas\u0103?", "fr": "Que signifie \u00ab libert\u00e9 \u00bb pour toi dans une relation engag\u00e9e ?", "it": "Cosa significa per te \"libert\u00e0\" mentre sei in una relazione impegnata?", "fi": "Mit\u00e4 \"vapaus\" merkitsee sinulle sitoutuneessa suhteessa ollessasi?", "nl": "Wat betekent \u201cvrijheid\u201d voor jou terwijl je in een toegewijde relatie bent?", "no": "Hva betyr \"frihet\" for deg n\u00e5r du er i et forpliktende forhold?", "sv": "Vad betyder \"frihet\" f\u00f6r dig n\u00e4r du \u00e4r i en seri\u00f6s relation?", "pl": "Co dla ciebie oznacza \u201ewolno\u015b\u0107\u201d b\u0119d\u0105c w zaanga\u017cowanym zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What does “freedom” mean to you while being in a committed relationship?';
UPDATE questions
SET translations = '{"en": "What are three qualities you''d want to instill in your children?", "da": "Hvilke tre kvaliteter vil du gerne give videre til dine b\u00f8rn?", "de": "Welche drei Eigenschaften w\u00fcrdest du deinen Kindern gerne mitgeben?", "es": "\u00bfCu\u00e1les son tres cualidades que te gustar\u00eda inculcarles a tus hijos?", "pt": "Quais s\u00e3o tr\u00eas qualidades que voc\u00ea gostaria de transmitir aos seus filhos?", "ro": "Care sunt trei calit\u0103\u021bi pe care ai vrea s\u0103 le insufli copiilor t\u0103i?", "fr": "Quelles sont trois qualit\u00e9s que tu aimerais transmettre \u00e0 tes enfants ?", "it": "Quali sono tre qualit\u00e0 che vorresti instillare nei tuoi figli?", "fi": "Mitk\u00e4 kolme ominaisuutta haluaisit opettaa lapsillesi?", "nl": "Welke drie kwaliteiten zou je in je kinderen willen bijbrengen?", "no": "Hvilke tre egenskaper ville du \u00f8nsket \u00e5 innpode i barna dine?", "sv": "Vilka tre egenskaper skulle du vilja f\u00f6rmedla till dina barn?", "pl": "Jakie trzy cechy chcia\u0142by\u015b wpoi\u0107 swoim dzieciom?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What are three qualities you''d want to instill in your children?';
UPDATE questions
SET translations = '{"en": "What do you think healthy compromise looks like for us?", "da": "Hvordan ser et sundt kompromis ud for os?", "de": "Wie sieht ein gesunder Kompromiss f\u00fcr uns aus?", "es": "\u00bfC\u00f3mo crees que se ve un compromiso saludable para nosotros?", "pt": "Como voc\u00ea acha que \u00e9 um compromisso saud\u00e1vel para n\u00f3s?", "ro": "Cum arat\u0103 un compromis s\u0103n\u0103tos pentru noi?", "fr": "\u00c0 quoi ressemble un compromis sain pour nous ?", "it": "Cosa pensi che sembri un compromesso sano per noi?", "fi": "Milt\u00e4 terve kompromissi n\u00e4ytt\u00e4\u00e4 mielest\u00e4si meille?", "nl": "Wat denk je dat een gezonde compromis voor ons eruitziet?", "no": "Hva tror du et sunt kompromiss ser ut for oss?", "sv": "Vad tycker du att en h\u00e4lsosam kompromiss ser ut f\u00f6r oss?", "pl": "Jak wed\u0142ug ciebie wygl\u0105da zdrowy kompromis dla nas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you think healthy compromise looks like for us?';
UPDATE questions
SET translations = '{"en": "What does forgiveness mean to you\u2014and what isn\u2019t it?", "da": "Hvad betyder tilgivelse for dig \u2014 og hvad g\u00f8r det ikke?", "de": "Was bedeutet Vergebung f\u00fcr dich \u2013 und was nicht?", "es": "\u00bfQu\u00e9 significa el perd\u00f3n para ti \u2014 y qu\u00e9 no lo es?", "pt": "O que o perd\u00e3o significa para voc\u00ea \u2014 e o que n\u00e3o \u00e9?", "ro": "Ce \u00eenseamn\u0103 iertarea pentru tine \u2014 \u0219i ce nu este ea?", "fr": "Que signifie le pardon pour toi \u2014 et qu\u2019est-ce qu\u2019il n\u2019est pas ?", "it": "Cosa significa per te il perdono\u2014e cosa non \u00e8?", "fi": "Mit\u00e4 anteeksianto merkitsee sinulle\u2014ja mit\u00e4 se ei ole?", "nl": "Wat betekent vergeving voor jou - en wat is het niet?", "no": "Hva betyr tilgivelse for deg \u2013 og hva er det ikke?", "sv": "Vad betyder f\u00f6rl\u00e5telse f\u00f6r dig \u2013 och vad \u00e4r det inte?", "pl": "Co dla ciebie oznacza przebaczenie \u2014 a czego nie oznacza?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What does forgiveness mean to you—and what isn’t it?';
UPDATE questions
SET translations = '{"en": "Which of us holds a grudge longer \u2014 and how do we fix it fast?", "da": "Hvem af os b\u00e6rer nag l\u00e6ngere \u2014 og hvordan l\u00f8ser vi det hurtigt?", "de": "Wer von uns hegt l\u00e4nger Groll \u2013 und wie l\u00f6sen wir das schnell?", "es": "\u00bfQui\u00e9n de nosotros guarda rencor por m\u00e1s tiempo \u2014 y c\u00f3mo lo solucionamos r\u00e1pido?", "pt": "Quem de n\u00f3s guarda rancor por mais tempo \u2014 e como resolvemos isso r\u00e1pido?", "ro": "Care dintre noi poart\u0103 pic\u0103 mai mult \u2014 \u0219i cum putem rezolva asta rapid?", "fr": "Lequel de nous garde rancune plus longtemps \u2014 et comment le r\u00e9glons-nous rapidement ?", "it": "Chi di noi tiene il rancore pi\u00f9 a lungo \u2014 e come possiamo risolverlo in fretta?", "fi": "Kumpi meist\u00e4 pit\u00e4\u00e4 kaunaa pidemp\u00e4\u00e4n \u2014 ja miten voimme korjata sen nopeasti?", "nl": "Wie van ons houdt het langst een wrok vast \u2014 en hoe kunnen we het snel oplossen?", "no": "Hvem av oss b\u00e6rer nag lenger \u2014 og hvordan kan vi fikse det raskt?", "sv": "Vilken av oss b\u00e4r p\u00e5 en l\u00e5ngvarig of\u00f6rr\u00e4tt \u2014 och hur kan vi snabbt \u00e5tg\u00e4rda det?", "pl": "Kto z nas trzyma uraz d\u0142u\u017cej \u2014 i jak szybko mo\u017cemy to naprawi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Which of us holds a grudge longer — and how do we fix it fast?';
UPDATE questions
SET translations = '{"en": "What\u2019s a boundary that protects your creativity or rest?", "da": "Hvilken gr\u00e6nse beskytter din kreativitet eller din hvile?", "de": "Welche Grenze sch\u00fctzt deine Kreativit\u00e4t oder deine Erholung?", "es": "\u00bfQu\u00e9 l\u00edmite protege tu creatividad o tu descanso?", "pt": "Que limite protege a sua criatividade ou o seu descanso?", "ro": "Care este o limit\u0103 care \u00ee\u021bi protejeaz\u0103 creativitatea sau odihna?", "fr": "Quelle limite prot\u00e8ge ta cr\u00e9ativit\u00e9 ou ton repos ?", "it": "Qual \u00e8 un confine che protegge la tua creativit\u00e0 o il tuo riposo?", "fi": "Mik\u00e4 on raja, joka suojaa luovuuttasi tai lepoasi?", "nl": "Wat is een grens die jouw creativiteit of rust beschermt?", "no": "Hva er en grense som beskytter din kreativitet eller hvile?", "sv": "Vilken gr\u00e4ns skyddar din kreativitet eller vila?", "pl": "Jaka granica chroni twoj\u0105 kreatywno\u015b\u0107 lub odpoczynek?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s a boundary that protects your creativity or rest?';
UPDATE questions
SET translations = '{"en": "What do you dream about accomplishing?", "da": "Hvad dr\u00f8mmer du om at opn\u00e5?", "de": "Wovon tr\u00e4umst du, etwas zu erreichen?", "es": "\u00bfCon qu\u00e9 sue\u00f1as lograr?", "pt": "O que voc\u00ea sonha em conquistar?", "ro": "Ce visezi s\u0103 realizezi?", "fr": "Que r\u00eaves-tu d\u2019accomplir ?", "it": "Di cosa sogni di realizzare?", "fi": "Mist\u00e4 unelmoit saavuttavasi?", "nl": "Waar droom je van om te bereiken?", "no": "Hva dr\u00f8mmer du om \u00e5 oppn\u00e5?", "sv": "Vad dr\u00f6mmer du om att uppn\u00e5?", "pl": "O czym marzysz, aby osi\u0105gn\u0105\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you dream about accomplishing?';
UPDATE questions
SET translations = '{"en": "When was the last time you felt awe?", "da": "Hvorn\u00e5r var sidste gang, du f\u00f8lte \u00e6refrygt?", "de": "Wann hast du das letzte Mal Ehrfurcht empfunden?", "es": "\u00bfCu\u00e1ndo fue la \u00faltima vez que sentiste asombro?", "pt": "Quando foi a \u00faltima vez que voc\u00ea sentiu admira\u00e7\u00e3o?", "ro": "C\u00e2nd ai sim\u021bit ultima dat\u0103 uimire?", "fr": "Quand as-tu ressenti de l\u2019\u00e9merveillement pour la derni\u00e8re fois ?", "it": "Quando \u00e8 stata l''ultima volta che ti sei sentito in soggezione?", "fi": "Milloin viimeksi tunsit ihmetyst\u00e4?", "nl": "Wanneer was de laatste keer dat je verwondering voelde?", "no": "N\u00e5r var siste gang du f\u00f8lte undring?", "sv": "N\u00e4r var senaste g\u00e5ngen du k\u00e4nde f\u00f6rundran?", "pl": "Kiedy ostatni raz poczu\u0142e\u015b zachwyt?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When was the last time you felt awe?';
UPDATE questions
SET translations = '{"en": "How do you feel when we disagree \u2014 and what helps you feel heard?", "da": "Hvordan har du det, n\u00e5r vi er uenige \u2014 og hvad hj\u00e6lper dig med at f\u00f8le dig h\u00f8rt?", "de": "Wie f\u00fchlst du dich, wenn wir uneinig sind \u2013 und was hilft dir, dich geh\u00f6rt zu f\u00fchlen?", "es": "\u00bfC\u00f3mo te sientes cuando no estamos de acuerdo \u2014 y qu\u00e9 te ayuda a sentirte escuchado(a)?", "pt": "Como voc\u00ea se sente quando discordamos \u2014 e o que te ajuda a se sentir ouvido(a)?", "ro": "Cum te sim\u021bi c\u00e2nd nu suntem de acord \u2014 \u0219i ce te ajut\u0103 s\u0103 te sim\u021bi ascultat(\u0103)?", "fr": "Comment te sens-tu quand nous ne sommes pas d\u2019accord \u2014 et qu\u2019est-ce qui t\u2019aide \u00e0 te sentir entendu(e) ?", "it": "Come ti senti quando non siamo d''accordo \u2014 e cosa ti aiuta a sentirti ascoltato?", "fi": "Milt\u00e4 sinusta tuntuu, kun olemme eri mielt\u00e4 \u2014 ja mik\u00e4 auttaa sinua tuntemaan itsesi kuulluksi?", "nl": "Hoe voel je je als we het oneens zijn \u2014 en wat helpt je om je gehoord te voelen?", "no": "Hvordan f\u00f8ler du deg n\u00e5r vi er uenige \u2014 og hva hjelper deg med \u00e5 f\u00f8le deg h\u00f8rt?", "sv": "Hur k\u00e4nner du n\u00e4r vi \u00e4r oense \u2014 och vad hj\u00e4lper dig att k\u00e4nna dig h\u00f6rd?", "pl": "Jak si\u0119 czujesz, gdy si\u0119 nie zgadzamy \u2014 i co pomaga ci czu\u0107 si\u0119 wys\u0142uchanym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you feel when we disagree — and what helps you feel heard?';
UPDATE questions
SET translations = '{"en": "Who in your life taught you the most about love?", "da": "Hvem i dit liv har l\u00e6rt dig mest om k\u00e6rlighed?", "de": "Wer in deinem Leben hat dir am meisten \u00fcber Liebe beigebracht?", "es": "\u00bfQui\u00e9n en tu vida te ha ense\u00f1ado m\u00e1s sobre el amor?", "pt": "Quem na sua vida te ensinou mais sobre o amor?", "ro": "Cine din via\u021ba ta te-a \u00eenv\u0103\u021bat cel mai mult despre dragoste?", "fr": "Qui dans ta vie t\u2019a le plus appris sur l\u2019amour ?", "it": "Chi nella tua vita ti ha insegnato di pi\u00f9 sull''amore?", "fi": "Kuka el\u00e4m\u00e4ss\u00e4si opetti sinulle eniten rakkaudesta?", "nl": "Wie in jouw leven heeft je het meest over liefde geleerd?", "no": "Hvem i livet ditt har l\u00e6rt deg mest om kj\u00e6rlighet?", "sv": "Vem i ditt liv l\u00e4rde dig mest om k\u00e4rlek?", "pl": "Kto w twoim \u017cyciu nauczy\u0142 ci\u0119 najwi\u0119cej o mi\u0142o\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Who in your life taught you the most about love?';
UPDATE questions
SET translations = '{"en": "When you look at me in quiet moments, what goes through your mind?", "da": "N\u00e5r du kigger p\u00e5 mig i stille \u00f8jeblikke, hvad g\u00e5r der s\u00e5 gennem dit hoved?", "de": "Wenn du mich in stillen Momenten ansiehst, was geht dir dann durch den Kopf?", "es": "Cuando me miras en momentos tranquilos, \u00bfqu\u00e9 pasa por tu mente?", "pt": "Quando voc\u00ea olha para mim em momentos de sil\u00eancio, o que passa pela sua cabe\u00e7a?", "ro": "C\u00e2nd te ui\u021bi la mine \u00een momentele lini\u0219tite, ce \u00ee\u021bi trece prin minte?", "fr": "Quand tu me regardes dans les moments de calme, qu\u2019est-ce qui te traverse l\u2019esprit ?", "it": "Quando mi guardi nei momenti di silenzio, cosa ti passa per la testa?", "fi": "Kun katsot minua hiljaisina hetkin\u00e4, mit\u00e4 ajattelet?", "nl": "Wanneer je me in stille momenten aankijkt, wat gaat er dan door je hoofd?", "no": "N\u00e5r du ser p\u00e5 meg i stille \u00f8yeblikk, hva tenker du p\u00e5?", "sv": "N\u00e4r du ser p\u00e5 mig i tysta stunder, vad t\u00e4nker du p\u00e5?", "pl": "Kiedy patrzysz na mnie w cichych chwilach, co przechodzi ci przez my\u015bl?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When you look at me in quiet moments, what goes through your mind?';
UPDATE questions
SET translations = '{"en": "Who in my life do you feel has a negative influence on me?", "da": "Hvem i mit liv f\u00f8ler du har en negativ indflydelse p\u00e5 mig?", "de": "Wer in meinem Leben hat deiner Meinung nach einen negativen Einfluss auf mich?", "es": "\u00bfQui\u00e9n en mi vida sientes que tiene una influencia negativa sobre m\u00ed?", "pt": "Quem na minha vida voc\u00ea sente que tem uma influ\u00eancia negativa sobre mim?", "ro": "Cine din via\u021ba mea sim\u021bi c\u0103 are o influen\u021b\u0103 negativ\u0103 asupra mea?", "fr": "Qui, dans ma vie, as-tu l\u2019impression a une influence n\u00e9gative sur moi ?", "it": "Chi nella mia vita pensi abbia un''influenza negativa su di me?", "fi": "Kuka el\u00e4m\u00e4ss\u00e4ni mielest\u00e4si vaikuttaa minuun negatiivisesti?", "nl": "Wie in mijn leven denk je dat een negatieve invloed op mij heeft?", "no": "Hvem i livet mitt f\u00f8ler du har en negativ innflytelse p\u00e5 meg?", "sv": "Vem i mitt liv tycker du har en negativ p\u00e5verkan p\u00e5 mig?", "pl": "Kto w moim \u017cyciu, twoim zdaniem, ma na mnie negatywny wp\u0142yw?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Who in my life do you feel has a negative influence on me?';
UPDATE questions
SET translations = '{"en": "What do you need from your partner when you\u2019ve had a tough day?", "da": "Hvad har du brug for fra din partner, n\u00e5r du har haft en h\u00e5rd dag?", "de": "Was brauchst du von deinem Partner, wenn du einen harten Tag hattest?", "es": "\u00bfQu\u00e9 necesitas de tu pareja cuando has tenido un d\u00eda dif\u00edcil?", "pt": "O que voc\u00ea precisa do seu parceiro quando teve um dia dif\u00edcil?", "ro": "De ce ai nevoie de la partenerul t\u0103u c\u00e2nd ai avut o zi grea?", "fr": "De quoi as-tu besoin de ton partenaire quand tu as eu une journ\u00e9e difficile ?", "it": "Cosa hai bisogno dal tuo partner quando hai avuto una giornata difficile?", "fi": "Mit\u00e4 tarvitset kumppaniltasi, kun sinulla on ollut vaikea p\u00e4iv\u00e4?", "nl": "Wat heb je van je partner nodig als je een zware dag hebt gehad?", "no": "Hva trenger du fra partneren din n\u00e5r du har hatt en t\u00f8ff dag?", "sv": "Vad beh\u00f6ver du fr\u00e5n din partner n\u00e4r du har haft en tuff dag?", "pl": "Czego potrzebujesz od swojego partnera, gdy mia\u0142e\u015b trudny dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you need from your partner when you’ve had a tough day?';
UPDATE questions
SET translations = '{"en": "What are you most grateful for in your life?", "da": "Hvad er du mest taknemmelig for i dit liv?", "de": "Wof\u00fcr bist du in deinem Leben am dankbarsten?", "es": "\u00bfPor qu\u00e9 est\u00e1s m\u00e1s agradecido(a) en tu vida?", "pt": "Pelo que voc\u00ea \u00e9 mais grato(a) na sua vida?", "ro": "Pentru ce e\u0219ti cel mai recunosc\u0103tor(are) \u00een via\u021ba ta?", "fr": "Pour quoi es-tu le plus reconnaissant(e) dans ta vie ?", "it": "Per cosa sei pi\u00f9 grato nella tua vita?", "fi": "Mist\u00e4 olet el\u00e4m\u00e4ss\u00e4si kiitollisin?", "nl": "Waar ben je het meest dankbaar voor in je leven?", "no": "Hva er du mest takknemlig for i livet ditt?", "sv": "Vad \u00e4r du mest tacksam f\u00f6r i ditt liv?", "pl": "Za co jeste\u015b najbardziej wdzi\u0119czny w swoim \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What are you most grateful for in your life?';
UPDATE questions
SET translations = '{"en": "How do you balance wanting to be right with wanting to be close?", "da": "Hvordan balancerer du \u00f8nsket om at have ret med \u00f8nsket om at v\u00e6re t\u00e6t?", "de": "Wie balancierst du den Wunsch, recht zu haben, mit dem Wunsch, nah zu sein?", "es": "\u00bfC\u00f3mo equilibras querer tener raz\u00f3n con querer estar cerca?", "pt": "Como voc\u00ea equilibra querer estar certo(a) com querer estar pr\u00f3ximo(a)?", "ro": "Cum echilibrezi dorin\u021ba de a avea dreptate cu dorin\u021ba de a fi apropiat(\u0103)?", "fr": "Comment \u00e9quilibres-tu le besoin d\u2019avoir raison et celui d\u2019\u00eatre proche ?", "it": "Come fai a bilanciare il desiderio di avere ragione con quello di essere vicino?", "fi": "Miten tasapainotat halun olla oikeassa ja halun olla l\u00e4hell\u00e4?", "nl": "Hoe balanceer je de wens om gelijk te hebben met de wens om dichtbij te zijn?", "no": "Hvordan balanserer du \u00f8nsket om \u00e5 ha rett med \u00f8nsket om \u00e5 v\u00e6re n\u00e6r?", "sv": "Hur balanserar du att vilja ha r\u00e4tt med att vilja vara n\u00e4ra?", "pl": "Jak r\u00f3wnowa\u017cysz ch\u0119\u0107 bycia w porz\u0105dku z ch\u0119ci\u0105 bycia blisko?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you balance wanting to be right with wanting to be close?';
UPDATE questions
SET translations = '{"en": "What do you think is the point of being alive?", "da": "Hvad tror du er meningen med at v\u00e6re i live?", "de": "Was glaubst du, ist der Sinn des Lebens?", "es": "\u00bfCu\u00e1l crees que es el prop\u00f3sito de estar vivo(a)?", "pt": "O que voc\u00ea acha que \u00e9 o prop\u00f3sito de estar vivo(a)?", "ro": "Care crezi c\u0103 este sensul de a fi \u00een via\u021b\u0103?", "fr": "Quel est, selon toi, le sens d\u2019\u00eatre en vie ?", "it": "Cosa pensi sia il senso di essere vivi?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 on el\u00e4m\u00e4n tarkoitus?", "nl": "Wat denk je dat het doel is van leven?", "no": "Hva tror du er meningen med \u00e5 v\u00e6re i live?", "sv": "Vad tycker du \u00e4r meningen med att leva?", "pl": "Co my\u015blisz, jaki jest sens \u017cycia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you think is the point of being alive?';
UPDATE questions
SET translations = '{"en": "What does a \u201cgood life\u201d look like to you in one sentence?", "da": "Hvordan ser et \u201cgodt liv\u201d ud for dig i \u00e9n s\u00e6tning?", "de": "Wie sieht ein \u201egutes Leben\u201c f\u00fcr dich in einem Satz aus?", "es": "\u00bfC\u00f3mo se ve una \u201cbuena vida\u201d para ti en una frase?", "pt": "Como \u00e9 uma \u201cboa vida\u201d para voc\u00ea em uma frase?", "ro": "Cum arat\u0103 o \u201evia\u021b\u0103 bun\u0103\u201d pentru tine \u00eentr-o singur\u0103 propozi\u021bie?", "fr": "\u00c0 quoi ressemble une \u00ab bonne vie \u00bb pour toi, en une phrase ?", "it": "Come descriveresti una \"buona vita\" in una sola frase?", "fi": "Milt\u00e4 \"hyv\u00e4 el\u00e4m\u00e4\" n\u00e4ytt\u00e4\u00e4 sinulle yhdell\u00e4 lauseella?", "nl": "Wat betekent een \u201cgoed leven\u201d voor jou in \u00e9\u00e9n zin?", "no": "Hvordan ser et \"godt liv\" ut for deg i \u00e9n setning?", "sv": "Vad inneb\u00e4r ett \"gott liv\" f\u00f6r dig i en mening?", "pl": "Jak wygl\u0105da dla Ciebie \u201edobre \u017cycie\u201d w jednym zdaniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What does a “good life” look like to you in one sentence?';
UPDATE questions
SET translations = '{"en": "In what way dos your current self differ from who you were five years ago?", "da": "Hvilket minde om os tror du stadig vil f\u00e5 dig til at smile, n\u00e5r du er 90?", "de": "Welche Erinnerung an uns wird dich deiner Meinung nach noch mit 90 zum L\u00e4cheln bringen?", "es": "\u00bfQu\u00e9 recuerdo nuestro crees que a\u00fan te har\u00e1 sonre\u00edr cuando tengas 90 a\u00f1os?", "pt": "Que lembran\u00e7a nossa voc\u00ea acredita que ainda vai te fazer sorrir aos 90 anos?", "ro": "Ce amintire despre noi crezi c\u0103 te va face s\u0103 z\u00e2mbe\u0219ti chiar \u0219i la 90 de ani?", "fr": "Quel souvenir de nous crois-tu te fera encore sourire \u00e0 90 ans ?", "it": "In che modo il tuo io attuale \u00e8 diverso da chi eri cinque anni fa?", "fi": "Miten nykyinen itsesi eroaa siit\u00e4, kuka olit viisi vuotta sitten?", "nl": "Op welke manier verschilt jouw huidige zelf van wie je vijf jaar geleden was?", "no": "P\u00e5 hvilken m\u00e5te skiller ditt n\u00e5v\u00e6rende jeg seg fra den du var for fem \u00e5r siden?", "sv": "P\u00e5 vilket s\u00e4tt skiljer sig ditt nuvarande jag fr\u00e5n den du var f\u00f6r fem \u00e5r sedan?", "pl": "W jaki spos\u00f3b twoje obecne ja r\u00f3\u017cni si\u0119 od tego, kim by\u0142e\u015b pi\u0119\u0107 lat temu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'In what way dos your current self differ from who you were five years ago?';