UPDATE questions
SET translations = '{"en": "\u201cMen suffer more from modern gender expectations than women do.\u201d", "da": "M\u00e6nd lider mere under moderne k\u00f8nsforventninger end kvinder.", "de": "M\u00e4nner leiden mehr unter modernen Geschlechtererwartungen als Frauen.", "es": "Los hombres sufren m\u00e1s por las expectativas de g\u00e9nero modernas que las mujeres.", "pt": "Os homens sofrem mais com as expectativas modernas de g\u00e9nero do que as mulheres.", "ro": "B\u0103rba\u021bii sufer\u0103 mai mult din cauza a\u0219tept\u0103rilor moderne legate de gen dec\u00e2t femeile.", "fr": "Les hommes souffrent davantage des attentes modernes li\u00e9es au genre que les femmes.", "it": "\"Gli uomini soffrono di pi\u00f9 delle aspettative di genere moderne rispetto alle donne.\"", "fi": "\"Miesten k\u00e4rsimys nykyaikaisista sukupuoliodotuksista on suurempaa kuin naisten.\"", "nl": "\"Mannen lijden meer onder moderne genderverwachtingen dan vrouwen.\"", "no": "\u00abMenn lider mer av moderne kj\u00f8nnsforventninger enn kvinner gj\u00f8r.\u00bb", "sv": "\"M\u00e4n lider mer av moderna k\u00f6nsf\u00f6rv\u00e4ntningar \u00e4n vad kvinnor g\u00f6r.\"", "pl": "\u201eM\u0119\u017cczy\u017ani bardziej cierpi\u0105 z powodu nowoczesnych oczekiwa\u0144 p\u0142ci ni\u017c kobiety.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Men suffer more from modern gender expectations than women do.”';
UPDATE questions
SET translations = '{"en": "\u201cFinancial freedom just means not caring what anyone else buys.\u201d", "da": "\u00d8konomisk frihed betyder bare ikke at g\u00e5 op i, hvad andre k\u00f8ber.", "de": "Finanzielle Freiheit bedeutet einfach, sich nicht darum zu k\u00fcmmern, was andere kaufen.", "es": "La libertad financiera solo significa no preocuparse por lo que compran los dem\u00e1s.", "pt": "Liberdade financeira significa apenas n\u00e3o se importar com o que os outros compram.", "ro": "Libertatea financiar\u0103 \u00eenseamn\u0103 doar s\u0103 nu-\u021bi pese de ce cump\u0103r\u0103 al\u021bii.", "fr": "La libert\u00e9 financi\u00e8re signifie simplement ne pas se soucier de ce que les autres ach\u00e8tent.", "it": "\"La libert\u00e0 finanziaria significa semplicemente non preoccuparsi di ci\u00f2 che comprano gli altri.\"", "fi": "\"Taloudellinen vapaus tarkoittaa vain sit\u00e4, ettei v\u00e4lit\u00e4 siit\u00e4, mit\u00e4 muut ostavat.\"", "nl": "\"Financi\u00eble vrijheid betekent gewoon dat je je niet druk maakt om wat anderen kopen.\"", "no": "\u201c\u00d8konomisk frihet betyr bare at man ikke bryr seg om hva andre kj\u00f8per.\u201d", "sv": "\"Ekonomisk frihet betyder bara att man inte bryr sig om vad andra k\u00f6per.\"", "pl": "\u201eWolno\u015b\u0107 finansowa oznacza po prostu, \u017ce nie obchodzi ci\u0119, co kupuj\u0105 inni.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Financial freedom just means not caring what anyone else buys.”';
UPDATE questions
SET translations = '{"en": "\u201cCancel culture does more harm than good.\u201d", "da": "Cancel culture g\u00f8r mere skade end gavn.", "de": "Cancel Culture richtet mehr Schaden als Nutzen an.", "es": "La cultura de la cancelaci\u00f3n hace m\u00e1s da\u00f1o que bien.", "pt": "A cultura do cancelamento faz mais mal do que bem.", "ro": "Cultura anul\u0103rii face mai mult r\u0103u dec\u00e2t bine.", "fr": "La culture de l\u2019annulation fait plus de mal que de bien.", "it": "\"La cultura della cancellazione fa pi\u00f9 male che bene.\"", "fi": "\"Peruutuskulttuuri tekee enemm\u00e4n haittaa kuin hy\u00f6ty\u00e4.\"", "nl": "\"Cancelcultuur doet meer kwaad dan goed.\"", "no": "\u201cAvbestillingskultur gj\u00f8r mer skade enn nytte.\u201d", "sv": "\"Cancelkultur g\u00f6r mer skada \u00e4n nytta.\"", "pl": "\u201eKultura anulowania przynosi wi\u0119cej szkody ni\u017c po\u017cytku.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Cancel culture does more harm than good.”';
UPDATE questions
SET translations = '{"en": "\"Dating apps make people feel more disposable, not more connected\"", "da": "Datingapps f\u00e5r folk til at f\u00f8le sig mere udskiftelige, ikke mere forbundet.", "de": "Dating-Apps lassen Menschen sich eher austauschbar f\u00fchlen, nicht verbundener.", "es": "Las apps de citas hacen que la gente se sienta m\u00e1s desechable, no m\u00e1s conectada.", "pt": "As apps de encontros fazem as pessoas sentirem-se mais descart\u00e1veis, n\u00e3o mais ligadas.", "ro": "Aplica\u021biile de dating \u00eei fac pe oameni s\u0103 se simt\u0103 mai de \u201earuncat\u201d, nu mai conecta\u021bi.", "fr": "Les applis de rencontre donnent aux gens l\u2019impression d\u2019\u00eatre plus jetables, pas plus connect\u00e9s.", "it": "\"Le app di incontri fanno sentire le persone pi\u00f9 usa e getta, non pi\u00f9 connesse.\"", "fi": "\"Deittisovellukset saavat ihmiset tuntemaan itsens\u00e4 enemm\u00e4n k\u00e4ytett\u00e4vilt\u00e4, eiv\u00e4tk\u00e4 he tunne itse\u00e4\u00e4n enemm\u00e4n yhteyteen.\"", "nl": "\"Datingapps zorgen ervoor dat mensen zich meer wegwerpbaar voelen, niet meer verbonden.\"", "no": "\"Datingapper f\u00e5r folk til \u00e5 f\u00f8le seg mer utbyttbare, ikke mer tilknyttede.\"", "sv": "\"Datingappar f\u00e5r m\u00e4nniskor att k\u00e4nna sig mer utbytbara, inte mer kopplade.\"", "pl": "\"Aplikacje randkowe sprawiaj\u0105, \u017ce ludzie czuj\u0105 si\u0119 bardziej jednorazowi, a nie bardziej po\u0142\u0105czeni.\""}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '"Dating apps make people feel more disposable, not more connected"';
UPDATE questions
SET translations = '{"en": "\u201cVacations are more stressful than staying home.\u201d", "da": "Ferier er mere stressende end at blive hjemme.", "de": "Urlaube sind stressiger als zu Hause zu bleiben.", "es": "Las vacaciones son m\u00e1s estresantes que quedarse en casa.", "pt": "As f\u00e9rias s\u00e3o mais stressantes do que ficar em casa.", "ro": "Vacan\u021bele sunt mai stresante dec\u00e2t s\u0103 stai acas\u0103.", "fr": "Les vacances sont plus stressantes que de rester chez soi.", "it": "\"Le vacanze sono pi\u00f9 stressanti che restare a casa.\"", "fi": "\"Lomat ovat stressaavampia kuin kotona oleminen.\"", "nl": "\"Vakanties zijn stressvoller dan thuisblijven.\"", "no": "\"Ferier er mer stressende enn \u00e5 v\u00e6re hjemme.\"", "sv": "\"Semestrar \u00e4r mer stressande \u00e4n att stanna hemma.\"", "pl": "\u201eWakacje s\u0105 bardziej stresuj\u0105ce ni\u017c zostanie w domu.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Vacations are more stressful than staying home.”';
UPDATE questions
SET translations = '{"en": "\u201cNatural beauty\u2019 is just a privilege when you can afford it.\u201d", "da": "\u201cNaturlig sk\u00f8nhed\u201d er bare et privilegium, n\u00e5r man har r\u00e5d til det.", "de": "\u201eNat\u00fcrliche Sch\u00f6nheit\u201c ist nur ein Privileg, wenn man es sich leisten kann.", "es": "La \u201cbelleza natural\u201d es solo un privilegio cuando puedes permit\u00edrtelo.", "pt": "\u201cBeleza natural\u201d \u00e9 apenas um privil\u00e9gio quando se pode pagar por isso.", "ro": "\u201eFrumuse\u021bea natural\u0103\u201d este doar un privilegiu atunci c\u00e2nd \u021bi-o permi\u021bi.", "fr": "La \u201cbeaut\u00e9 naturelle\u201d n\u2019est qu\u2019un privil\u00e8ge quand on peut se le permettre.", "it": "\"La ''bellezza naturale'' \u00e8 solo un privilegio quando te lo puoi permettere.\"", "fi": "\"Luonnonkauneus\" on vain etuoikeus, kun siihen on varaa.", "nl": "\"Natuurlijke schoonheid is gewoon een privilege als je het je kunt veroorloven.\"", "no": "\u201cNaturlig skj\u00f8nnhet er bare et privilegium n\u00e5r du har r\u00e5d til det.\u201d", "sv": "\"Naturlig sk\u00f6nhet \u00e4r bara en privilegium n\u00e4r man har r\u00e5d med det.\"", "pl": "\u201eNaturalne pi\u0119kno to tylko przywilej, gdy mo\u017cesz sobie na to pozwoli\u0107.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Natural beauty’ is just a privilege when you can afford it.”';
UPDATE questions
SET translations = '{"en": "\u201cFreedom of speech should have stronger limits when speech is harmful.\u201d", "da": "Ytringsfrihed b\u00f8r have st\u00e6rkere gr\u00e6nser, n\u00e5r talen er skadelig.", "de": "Meinungsfreiheit sollte st\u00e4rkere Grenzen haben, wenn die Rede sch\u00e4dlich ist.", "es": "La libertad de expresi\u00f3n deber\u00eda tener l\u00edmites m\u00e1s fuertes cuando el discurso es da\u00f1ino.", "pt": "A liberdade de express\u00e3o deve ter limites mais fortes quando o discurso \u00e9 prejudicial.", "ro": "Libertatea de exprimare ar trebui s\u0103 aib\u0103 limite mai stricte atunci c\u00e2nd vorbirea este d\u0103un\u0103toare.", "fr": "La libert\u00e9 d\u2019expression devrait avoir des limites plus strictes lorsque les propos sont nuisibles.", "it": "\"La libert\u00e0 di espressione dovrebbe avere limiti pi\u00f9 severi quando l''espressione \u00e8 dannosa.\"", "fi": "\"Vapaa sanaa tulisi rajoittaa voimakkaammin, kun puhe on vahingollista.\"", "nl": "\"Vrijheid van meningsuiting zou strengere grenzen moeten hebben wanneer de uiting schadelijk is.\"", "no": "\u00abYtringsfrihet b\u00f8r ha sterkere grenser n\u00e5r ytringer er skadelige.\u00bb", "sv": "\"Yttrandefrihet b\u00f6r ha starkare begr\u00e4nsningar n\u00e4r yttrandet \u00e4r skadligt.\"", "pl": "\u201eWolno\u015b\u0107 s\u0142owa powinna mie\u0107 silniejsze ograniczenia, gdy mowa jest szkodliwa.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Freedom of speech should have stronger limits when speech is harmful.”';
UPDATE questions
SET translations = '{"en": "\u201cTipping culture has gotten out of control.\u201d", "da": "Drikkepengekulturen er l\u00f8bet l\u00f8bsk.", "de": "Die Trinkgeldkultur ist au\u00dfer Kontrolle geraten.", "es": "La cultura de las propinas se ha salido de control.", "pt": "A cultura das gorjetas saiu do controlo.", "ro": "Cultura bac\u0219i\u0219urilor a sc\u0103pat de sub control.", "fr": "La culture du pourboire est devenue incontr\u00f4lable.", "it": "\"La cultura della mancia \u00e8 diventata incontrollabile.\"", "fi": "\"Juomaraha-kulttuuri on mennyt t\u00e4ysin hallitsemattomaksi.\"", "nl": "\"De foorkultuur is uit de hand gelopen.\"", "no": "\u201cTipskulturen har blitt ute av kontroll.\u201d", "sv": "\"Dricks-kulturen har blivit helt galen.\"", "pl": "\u201eKultura dawania napiwk\u00f3w wymkn\u0119\u0142a si\u0119 spod kontroli.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tipping culture has gotten out of control.”';
UPDATE questions
SET translations = '{"en": "\u201cInfluencers have too much cultural power for no accountability.\u201d", "da": "Influencere har for meget kulturel magt uden ansvar.", "de": "Influencer haben zu viel kulturelle Macht ohne Verantwortung.", "es": "Los influencers tienen demasiado poder cultural sin responsabilidad.", "pt": "Os influenciadores t\u00eam demasiado poder cultural sem responsabilidade.", "ro": "Influencerii au prea mult\u0103 putere cultural\u0103 f\u0103r\u0103 responsabilitate.", "fr": "Les influenceurs ont trop de pouvoir culturel sans responsabilit\u00e9.", "it": "\"Gli influencer hanno troppo potere culturale senza alcuna responsabilit\u00e0.\"", "fi": "\u201dVaikuttajilla on liian paljon kulttuurista valtaa ilman vastuuta.\u201d", "nl": "\"Invloeders hebben te veel culturele macht zonder enige verantwoording.\"", "no": "\u00abInfluensere har for mye kulturell makt uten ansvarlighet.\u00bb", "sv": "\"Influencers har f\u00f6r mycket kulturell makt utan ansvar.\"", "pl": "\u201eInfluencerzy maj\u0105 zbyt du\u017c\u0105 w\u0142adz\u0119 kulturow\u0105 bez \u017cadnej odpowiedzialno\u015bci.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Influencers have too much cultural power for no accountability.”';
UPDATE questions
SET translations = '{"en": "\u201cGood grades don\u2019t guarantee success, and bad grades don\u2019t guarantee failure.\u201d", "da": "Gode karakterer garanterer ikke succes, og d\u00e5rlige karakterer garanterer ikke fiasko.", "de": "Gute Noten garantieren keinen Erfolg, und schlechte Noten garantieren kein Scheitern.", "es": "Las buenas notas no garantizan el \u00e9xito, y las malas notas no garantizan el fracaso.", "pt": "Boas notas n\u00e3o garantem sucesso, e m\u00e1s notas n\u00e3o garantem fracasso.", "ro": "Notele bune nu garanteaz\u0103 succesul, iar notele proaste nu garanteaz\u0103 e\u0219ecul.", "fr": "Les bonnes notes ne garantissent pas la r\u00e9ussite, et les mauvaises notes ne garantissent pas l\u2019\u00e9chec.", "it": "\"Buoni voti non garantiscono il successo, e cattivi voti non garantiscono il fallimento.\"", "fi": "\u201dHyv\u00e4t arvosanat eiv\u00e4t takaa menestyst\u00e4, eik\u00e4 huonot arvosanat takaa ep\u00e4onnistumista.\u201d", "nl": "\"Goede cijfers garanderen geen succes, en slechte cijfers garanderen geen falen.\"", "no": "\"Gode karakterer garanterer ikke suksess, og d\u00e5rlige karakterer garanterer ikke fiasko.\"", "sv": "\"Bra betyg garanterar inte framg\u00e5ng, och d\u00e5liga betyg garanterar inte misslyckande.\"", "pl": "\u201eDobre oceny nie gwarantuj\u0105 sukcesu, a z\u0142e oceny nie gwarantuj\u0105 pora\u017cki.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Good grades don’t guarantee success, and bad grades don’t guarantee failure.”';
UPDATE questions
SET translations = '{"en": "\u201cAI-generated art and music should get royalty rights if they\u2019re based on human work.\u201d", "da": "AI-genereret kunst og musik b\u00f8r f\u00e5 royalties, hvis de er baseret p\u00e5 menneskeligt arbejde.", "de": "KI-generierte Kunst und Musik sollten Tantiemen erhalten, wenn sie auf menschlicher Arbeit basieren.", "es": "El arte y la m\u00fasica generados por IA deber\u00edan recibir regal\u00edas si se basan en trabajo humano.", "pt": "A arte e a m\u00fasica geradas por IA devem receber direitos autorais se forem baseadas em trabalho humano.", "ro": "Arta \u0219i muzica generate de AI ar trebui s\u0103 primeasc\u0103 drepturi de autor dac\u0103 se bazeaz\u0103 pe munc\u0103 uman\u0103.", "fr": "L\u2019art et la musique g\u00e9n\u00e9r\u00e9s par l\u2019IA devraient recevoir des droits d\u2019auteur s\u2019ils reposent sur un travail humain.", "it": "\u201cL''arte e la musica generate dall''IA dovrebbero avere diritti d''autore se si basano su opere umane.\u201d", "fi": "\"AI:n tuottamalle taiteelle ja musiikille tulisi my\u00f6nt\u00e4\u00e4 tekij\u00e4noikeudet, jos ne perustuvat ihmisty\u00f6h\u00f6n.\"", "nl": "\"AI-gegenereerde kunst en muziek zouden royaltyrechten moeten krijgen als ze gebaseerd zijn op menselijk werk.\"", "no": "\u00abAI-generert kunst og musikk b\u00f8r f\u00e5 royaltyrettigheter hvis de er basert p\u00e5 menneskelig arbeid.\u00bb", "sv": "\"AI-genererad konst och musik b\u00f6r f\u00e5 upphovsr\u00e4tt om de \u00e4r baserade p\u00e5 m\u00e4nskligt arbete.\"", "pl": "\u201eSztuka i muzyka generowane przez AI powinny mie\u0107 prawa autorskie, je\u015bli s\u0105 oparte na ludzkiej pracy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“AI-generated art and music should get royalty rights if they’re based on human work.”';
UPDATE questions
SET translations = '{"en": "\u201cBuying fancy coffee every day is self-care, not a bad financial habit.\u201d", "da": "At k\u00f8be dyr kaffe hver dag er egenomsorg, ikke en d\u00e5rlig vane.", "de": "Jeden Tag teuren Kaffee zu kaufen ist Selbstf\u00fcrsorge, keine schlechte Angewohnheit.", "es": "Comprar caf\u00e9 caro todos los d\u00edas es autocuidado, no un mal h\u00e1bito financiero.", "pt": "Comprar caf\u00e9 caro todos os dias \u00e9 autocuidado, n\u00e3o um mau h\u00e1bito financeiro.", "ro": "S\u0103 cumperi cafea scump\u0103 \u00een fiecare zi este grij\u0103 de sine, nu un obicei prost.", "fr": "Acheter un caf\u00e9 cher chaque jour, c\u2019est du self-care, pas une mauvaise habitude financi\u00e8re.", "it": "\"Comprare caff\u00e8 di alta qualit\u00e0 ogni giorno \u00e8 cura di s\u00e9, non una cattiva abitudine finanziaria.\"", "fi": "\"Joka p\u00e4iv\u00e4 hienon kahvin ostaminen on itsest\u00e4 huolehtimista, ei huono taloudellinen tapa.\"", "nl": "\"Elke dag dure koffie kopen is zelfzorg, geen slechte financi\u00eble gewoonte.\"", "no": "\"\u00c5 kj\u00f8pe fancy kaffe hver dag er egenpleie, ikke en d\u00e5rlig \u00f8konomisk vane.\"", "sv": "\"Att k\u00f6pa lyxigt kaffe varje dag \u00e4r egenv\u00e5rd, inte en d\u00e5lig ekonomisk vana.\"", "pl": "\u201eKupowanie drogiej kawy codziennie to dbanie o siebie, a nie z\u0142y nawyk finansowy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Buying fancy coffee every day is self-care, not a bad financial habit.”';
UPDATE questions
SET translations = '{"en": "\u201cCryptocurrencies are mostly a speculative bubble.\u201d", "da": "Kryptovalutaer er mest en spekulativ boble.", "de": "Kryptow\u00e4hrungen sind gr\u00f6\u00dftenteils eine spekulative Blase.", "es": "Las criptomonedas son en su mayor\u00eda una burbuja especulativa.", "pt": "As criptomoedas s\u00e3o, na sua maioria, uma bolha especulativa.", "ro": "Criptomonedele sunt \u00een mare parte o bul\u0103 speculativ\u0103.", "fr": "Les cryptomonnaies sont pour la plupart une bulle sp\u00e9culative.", "it": "\"Le criptovalute sono per lo pi\u00f9 una bolla speculativa.\"", "fi": "\"Kriptovaluutat ovat enimm\u00e4kseen spekulatiivinen kupla.\"", "nl": "\"Cryptovaluta''s zijn voornamelijk een speculatieve bubbel.\"", "no": "\"Cryptovalutaer er stort sett en spekulativ boble.\"", "sv": "\"Kryptovalutor \u00e4r mestadels en spekulativ bubbla.\"", "pl": "\u201eKryptowaluty to g\u0142\u00f3wnie spekulacyjna ba\u0144ka.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Cryptocurrencies are mostly a speculative bubble.”';
UPDATE questions
SET translations = '{"en": "\u201cElectric cars aren\u2019t a real climate solution yet.\u201d", "da": "Elbiler er endnu ikke en reel klimal\u00f8sning.", "de": "Elektroautos sind noch keine wirkliche Klimaschutzl\u00f6sung.", "es": "Los autos el\u00e9ctricos a\u00fan no son una verdadera soluci\u00f3n clim\u00e1tica.", "pt": "Os carros el\u00e9tricos ainda n\u00e3o s\u00e3o uma solu\u00e7\u00e3o real para o clima.", "ro": "Ma\u0219inile electrice nu sunt \u00eenc\u0103 o solu\u021bie real\u0103 pentru clim\u0103.", "fr": "Les voitures \u00e9lectriques ne sont pas encore une v\u00e9ritable solution climatique.", "it": "\"Le auto elettriche non sono ancora una vera soluzione per il clima.\"", "fi": "\"S\u00e4hk\u00f6autot eiv\u00e4t viel\u00e4 ole todellinen ilmastoratkaisu.\"", "nl": "\"Elektrische auto\u2019s zijn nog geen echte klimaatoplossing.\"", "no": "\"Elbiler er fortsatt ikke en reell klimak l\u00f8sning.\"", "sv": "\u201cElbilar \u00e4r \u00e4nnu inte en riktig l\u00f6sning f\u00f6r klimatet.\u201d", "pl": "\u201eSamochody elektryczne jeszcze nie s\u0105 prawdziwym rozwi\u0105zaniem dla klimatu.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Electric cars aren’t a real climate solution yet.”';
UPDATE questions
SET translations = '{"en": "\u201cWorking from home doesn\u2019t actually improve productivity in the long run.\u201d", "da": "At arbejde hjemmefra \u00f8ger ikke n\u00f8dvendigvis produktiviteten p\u00e5 lang sigt.", "de": "Homeoffice steigert langfristig nicht unbedingt die Produktivit\u00e4t.", "es": "Trabajar desde casa no mejora realmente la productividad a largo plazo.", "pt": "Trabalhar de casa n\u00e3o melhora necessariamente a produtividade a longo prazo.", "ro": "Munca de acas\u0103 nu \u00eembun\u0103t\u0103\u021be\u0219te neap\u0103rat productivitatea pe termen lung.", "fr": "Le t\u00e9l\u00e9travail n\u2019am\u00e9liore pas forc\u00e9ment la productivit\u00e9 \u00e0 long terme.", "it": "\"Lavorare da casa in realt\u00e0 non migliora la produttivit\u00e0 a lungo termine.\"", "fi": "\"Et\u00e4ty\u00f6 ei oikeastaan paranna tuottavuutta pitk\u00e4ll\u00e4 aikav\u00e4lill\u00e4.\"", "nl": "\"Thuiswerken verbetert de productiviteit op de lange termijn eigenlijk niet.\"", "no": "\"\u00c5 jobbe hjemmefra forbedrer faktisk ikke produktiviteten p\u00e5 lang sikt.\"", "sv": "\"Att arbeta hemifr\u00e5n f\u00f6rb\u00e4ttrar faktiskt inte produktiviteten p\u00e5 l\u00e5ng sikt.\"", "pl": "\u201ePraca zdalna wcale nie poprawia produktywno\u015bci na d\u0142u\u017csz\u0105 met\u0119.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Working from home doesn’t actually improve productivity in the long run.”';
UPDATE questions
SET translations = '{"en": "\u201cUniversal Basic Income is a bad idea \u2014 it disincentivizes work.\u201d", "da": "Borgerl\u00f8n er en d\u00e5rlig id\u00e9 \u2013 det fjerner incitamentet til at arbejde.", "de": "Das bedingungslose Grundeinkommen ist eine schlechte Idee \u2013 es entmutigt zur Arbeit.", "es": "La renta b\u00e1sica universal es una mala idea: desincentiva el trabajo.", "pt": "O rendimento b\u00e1sico universal \u00e9 uma m\u00e1 ideia \u2014 desincentiva o trabalho.", "ro": "Venitul de baz\u0103 universal este o idee proast\u0103 \u2014 descurajeaz\u0103 munca.", "fr": "Le revenu de base universel est une mauvaise id\u00e9e \u2014 il d\u00e9courage le travail.", "it": "\"Il Reddito di Base Universale \u00e8 una cattiva idea \u2014 disincentiva il lavoro.\"", "fi": "\"Yleinen perustulo on huono idea \u2014 se v\u00e4hent\u00e4\u00e4 ty\u00f6nteon kannustimia.\"", "nl": "\"Een Universeel Basisinkomen is een slecht idee - het ontmoedigt werk.\"", "no": "\"Universell grunninntekt er en d\u00e5rlig id\u00e9 \u2014 det demotiverer til arbeid.\"", "sv": "\"Universell grundinkomst \u00e4r en d\u00e5lig id\u00e9 \u2014 det minskar incitamenten att arbeta.\"", "pl": "\u201eUniwersalny doch\u00f3d podstawowy to z\u0142y pomys\u0142 \u2014 zniech\u0119ca do pracy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Universal Basic Income is a bad idea — it disincentivizes work.”';
UPDATE questions
SET translations = '{"en": "\u201cDo you think we overcomplicate gender \u2014 or are we finally just being honest about it?\u201d", "da": "Overkomplicerer vi k\u00f8n \u2013 eller er vi bare endelig \u00e6rlige om det?", "de": "Komplizieren wir Geschlecht zu sehr \u2013 oder sind wir endlich ehrlich damit?", "es": "\u00bfComplicamos demasiado el tema del g\u00e9nero o finalmente estamos siendo honestos al respecto?", "pt": "Complicamos demais o g\u00e9nero \u2014 ou finalmente estamos a ser honestos sobre isso?", "ro": "Complic\u0103m prea mult genul \u2014 sau \u00een sf\u00e2r\u0219it suntem sinceri \u00een leg\u0103tur\u0103 cu el?", "fr": "Est-ce qu\u2019on complique trop la question du genre \u2014 ou sommes-nous enfin honn\u00eates \u00e0 ce sujet ?", "it": "\"Pensi che stiamo complicando troppo il genere \u2014 o stiamo finalmente solo essendo onesti al riguardo?\"", "fi": "\"Luuleeko, ett\u00e4 monimutkaistamme sukupuolta \u2014 vai olemmeko vihdoin vain rehellisi\u00e4 siit\u00e4?\"", "nl": "\"Denk je dat we gender te ingewikkeld maken \u2014 of zijn we eindelijk gewoon eerlijk erover?\"", "no": "\u201cTror du vi overkompliserer kj\u00f8nn \u2014 eller er vi endelig bare \u00e6rlige om det?\u201d", "sv": "\"Tycker du att vi \u00f6verkomplicerar k\u00f6n \u2014 eller \u00e4r vi \u00e4ntligen bara \u00e4rliga om det?\"", "pl": "\u201eCzy my\u015blisz, \u017ce komplikujemy kwestie zwi\u0105zane z p\u0142ci\u0105 \u2014 czy mo\u017ce w ko\u0144cu po prostu jeste\u015bmy szczerzy na ten temat?\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Do you think we overcomplicate gender — or are we finally just being honest about it?”';
UPDATE questions
SET translations = '{"en": "\u201cShort videos have ruined our attention span \u2014 but we love it.\u201d", "da": "Korte videoer har \u00f8delagt vores koncentrationsevne \u2013 men vi elsker det.", "de": "Kurze Videos haben unsere Aufmerksamkeitsspanne ruiniert \u2013 aber wir lieben es.", "es": "Los videos cortos han arruinado nuestra capacidad de atenci\u00f3n \u2014 pero nos encantan.", "pt": "Os v\u00eddeos curtos arruinaram a nossa aten\u00e7\u00e3o \u2014 mas n\u00f3s adoramos.", "ro": "Videoclipurile scurte ne-au ruinat aten\u021bia \u2014 dar ne plac.", "fr": "Les vid\u00e9os courtes ont ruin\u00e9 notre capacit\u00e9 d\u2019attention \u2014 mais on adore \u00e7a.", "it": "\"I video brevi hanno rovinato la nostra capacit\u00e0 di concentrazione \u2014 ma ci piacciono.\"", "fi": "\"Lyhyet videot ovat pilanneet keskittymiskyky\u00e4mme \u2014 mutta rakastamme sit\u00e4.\"", "nl": "\"Korte video''s hebben onze aandachtsspanne verpest \u2014 maar we houden ervan.\"", "no": "\"Korte videoer har \u00f8delagt oppmerksomhetsspennet v\u00e5rt \u2014 men vi elsker det.\"", "sv": "\"Korta videor har f\u00f6rst\u00f6rt v\u00e5r uppm\u00e4rksamhetsspann \u2014 men vi \u00e4lskar det.\"", "pl": "\u201eKr\u00f3tkie filmy zrujnowa\u0142y nasz\u0105 zdolno\u015b\u0107 koncentracji \u2014 ale uwielbiamy to.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Short videos have ruined our attention span — but we love it.”';
UPDATE questions
SET translations = '{"en": "\u201cPronouns should never be enforced in casual conversation.\u201d", "da": "Pronominer b\u00f8r aldrig h\u00e5ndh\u00e6ves i uformel samtale.", "de": "Pronomen sollten in informellen Gespr\u00e4chen nie vorgeschrieben werden.", "es": "Los pronombres nunca deber\u00edan imponerse en conversaciones informales.", "pt": "Os pronomes nunca devem ser impostos em conversas informais.", "ro": "Pronumele nu ar trebui impuse niciodat\u0103 \u00een conversa\u021biile informale.", "fr": "Les pronoms ne devraient jamais \u00eatre impos\u00e9s dans une conversation informelle.", "it": "\"I pronomi non dovrebbero mai essere imposti nella conversazione informale.\"", "fi": "\"Pronomineja ei pit\u00e4isi koskaan pakottaa ep\u00e4virallisessa keskustelussa.\"", "nl": "\"Voornaamwoorden zouden nooit afgedwongen moeten worden in informele gesprekken.\"", "no": "\"Pronomen b\u00f8r aldri p\u00e5tvinges i uformell samtale.\"", "sv": "\"Pronomen b\u00f6r aldrig tvingas i avslappnad konversation.\"", "pl": "\u201eZaimki nigdy nie powinny by\u0107 narzucane w swobodnej rozmowie.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Pronouns should never be enforced in casual conversation.”';
UPDATE questions
SET translations = '{"en": "\u201cPeople judge plastic surgery until it\u2019s done really well.\u201d", "da": "Folk d\u00f8mmer plastikkirurgi, indtil det er gjort virkelig godt.", "de": "Menschen verurteilen Sch\u00f6nheitsoperationen, bis sie wirklich gut gemacht sind.", "es": "La gente juzga la cirug\u00eda pl\u00e1stica hasta que est\u00e1 realmente bien hecha.", "pt": "As pessoas julgam a cirurgia pl\u00e1stica at\u00e9 que seja realmente bem feita.", "ro": "Oamenii judec\u0103 chirurgia estetic\u0103 p\u00e2n\u0103 c\u00e2nd e f\u0103cut\u0103 foarte bine.", "fr": "Les gens jugent la chirurgie esth\u00e9tique jusqu\u2019\u00e0 ce qu\u2019elle soit vraiment r\u00e9ussie.", "it": "\"La gente giudica la chirurgia plastica finch\u00e9 non \u00e8 fatta davvero bene.\"", "fi": "\"Ihmiset tuomitsevat plastiikkakirurgian, kunnes se on tehty todella hyvin.\"", "nl": "\"Mensen oordelen over plastische chirurgie totdat het echt goed gedaan is.\"", "no": "\"Folk d\u00f8mmer plastisk kirurgi inntil det er gjort virkelig bra.\"", "sv": "\"Folk d\u00f6mer plastikkirurgi tills det g\u00f6rs riktigt bra.\"", "pl": "\u201eLudzie oceniaj\u0105 chirurgi\u0119 plastyczn\u0105, dop\u00f3ki nie zostanie wykonana naprawd\u0119 dobrze.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“People judge plastic surgery until it’s done really well.”';
UPDATE questions
SET translations = '{"en": "\u201cWe glorify being \u2018booked and busy\u2019 way too much.\u201d", "da": "Vi glorificerer at v\u00e6re \u2018booket og travl\u2019 alt for meget.", "de": "Wir glorifizieren es, \u201egebucht und besch\u00e4ftigt\u201c zu sein, viel zu sehr.", "es": "Glorificamos estar \u201cocupados y sin tiempo\u201d demasiado.", "pt": "Glorificamos estar \u201cocupados e cheios de trabalho\u201d em excesso.", "ro": "Glorific\u0103m prea mult ideea de a fi \u201cmereu ocupa\u021bi\u201d.", "fr": "On glorifie beaucoup trop le fait d\u2019\u00eatre \u00ab d\u00e9bord\u00e9 et occup\u00e9 \u00bb.", "it": "\"Glorifichiamo troppo il fatto di essere ''occupati e impegnati''.\"", "fi": "\"Ylist\u00e4mme \u2018varattuna ja kiireisen\u00e4\u2019 olemista aivan liian paljon.\"", "nl": "\"We verheerlijken het ''druk en bezig zijn'' veel te veel.\"", "no": "\"Vi glorifiserer det \u00e5 v\u00e6re ''booket og opptatt'' altfor mye.\"", "sv": "\"Vi glorifierar att vara ''bokad och upptagen'' alldeles f\u00f6r mycket.\"", "pl": "\u201eZbyt mocno gloryfikujemy bycie ''zaj\u0119tym i zapracowanym''.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“We glorify being ‘booked and busy’ way too much.”';
UPDATE questions
SET translations = '{"en": "\u201cMonogamy is overrated in modern relationships.\u201d", "da": "Monogami er overvurderet i moderne forhold.", "de": "Monogamie ist in modernen Beziehungen \u00fcberbewertet.", "es": "La monogamia est\u00e1 sobrevalorada en las relaciones modernas.", "pt": "A monogamia est\u00e1 sobrevalorizada nas rela\u00e7\u00f5es modernas.", "ro": "Monogamia este supraevaluat\u0103 \u00een rela\u021biile moderne.", "fr": "La monogamie est surestim\u00e9e dans les relations modernes.", "it": "\"La monogamia \u00e8 sopravvalutata nelle relazioni moderne.\"", "fi": "\"Monogamia on yliarvostettua nykyaikaisissa suhteissa.\"", "nl": "\"Monogamie is overschat in moderne relaties.\"", "no": "\"Monogami er overvurdert i moderne forhold.\"", "sv": "\"Monogami \u00e4r \u00f6verskattat i moderna relationer.\"", "pl": "\u201eMonogamia jest przereklamowana w nowoczesnych zwi\u0105zkach.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Monogamy is overrated in modern relationships.”';
UPDATE questions
SET translations = '{"en": "\u201cIt\u2019s okay to want a simple, quiet life instead of chasing \u2018main character energy.\u2019\u201d", "da": "Det er okay at \u00f8nske et simpelt, stille liv i stedet for at jagte \u201cmain character energy\u201d.", "de": "Es ist okay, ein einfaches, ruhiges Leben zu wollen, statt \u201eMain Character Energy\u201c zu jagen.", "es": "Est\u00e1 bien querer una vida simple y tranquila en lugar de perseguir la \u201cenerg\u00eda de protagonista\u201d.", "pt": "Est\u00e1 tudo bem querer uma vida simples e calma em vez de perseguir a \u201cenergia de protagonista\u201d.", "ro": "Este \u00een regul\u0103 s\u0103 vrei o via\u021b\u0103 simpl\u0103 \u0219i lini\u0219tit\u0103 \u00een loc s\u0103 alergi dup\u0103 \u201cenergia de personaj principal\u201d.", "fr": "C\u2019est bien de vouloir une vie simple et calme au lieu de courir apr\u00e8s l\u2019\u00ab \u00e9nergie de personnage principal \u00bb.", "it": "\"Va bene desiderare una vita semplice e tranquilla invece di inseguire l''energia del ''personaggio principale''.\"", "fi": "\"On ihan ok haluta yksinkertaista, rauhallista el\u00e4m\u00e4\u00e4 sen sijaan, ett\u00e4 jahtaa ''p\u00e4\u00e4henkil\u00f6energiaa''.\"", "nl": "\"Het is ok\u00e9 om een eenvoudig, rustig leven te willen in plaats van te jagen op ''hoofdpersonage-energie''.\"", "no": "\"Det er greit \u00e5 \u00f8nske seg et enkelt, stille liv i stedet for \u00e5 jage etter ''hovedkarakterenergi''.\"", "sv": "\"Det \u00e4r okej att vilja ha ett enkelt, lugnt liv ist\u00e4llet f\u00f6r att jaga ''huvudkarakt\u00e4rens energi.''\"", "pl": "\u201eTo w porz\u0105dku pragn\u0105\u0107 prostego, cichego \u017cycia zamiast goni\u0107 za ''energi\u0105 g\u0142\u00f3wnego bohatera''.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“It’s okay to want a simple, quiet life instead of chasing ‘main character energy.’”';
UPDATE questions
SET translations = '{"en": "\u201cLong-distance relationships are unrealistic in the digital age.\u201d", "da": "Langdistanceforhold er urealistiske i den digitale tidsalder.", "de": "Fernbeziehungen sind im digitalen Zeitalter unrealistisch.", "es": "Las relaciones a distancia son poco realistas en la era digital.", "pt": "Rela\u00e7\u00f5es \u00e0 dist\u00e2ncia s\u00e3o irrealistas na era digital.", "ro": "Rela\u021biile la distan\u021b\u0103 sunt nerealiste \u00een era digital\u0103.", "fr": "Les relations \u00e0 distance sont irr\u00e9alistes \u00e0 l\u2019\u00e8re du num\u00e9rique.", "it": "\"Le relazioni a distanza sono irrealistiche nell''era digitale.\"", "fi": "\"Pitk\u00e4matkan suhteet ovat ep\u00e4realistisia digitaalisella aikakaudella.\"", "nl": "\"Langdurige relaties zijn onrealistisch in het digitale tijdperk.\"", "no": "\"Langdistanseforhold er urealistiske i den digitale tidsalder.\"", "sv": "\"Distansf\u00f6rh\u00e5llanden \u00e4r orealistiska i den digitala tids\u00e5ldern.\"", "pl": "\u201eZwi\u0105zki na odleg\u0142o\u015b\u0107 s\u0105 nierealistyczne w erze cyfrowej.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Long-distance relationships are unrealistic in the digital age.”';
UPDATE questions
SET translations = '{"en": "\u201cTravelling too much is disrespectful to local cultures.\u201d", "da": "At rejse for meget er respektl\u00f8st over for lokale kulturer.", "de": "Zu viel Reisen ist respektlos gegen\u00fcber lokalen Kulturen.", "es": "Viajar demasiado es una falta de respeto hacia las culturas locales.", "pt": "Viajar demais \u00e9 desrespeitoso para com as culturas locais.", "ro": "A c\u0103l\u0103tori prea mult e lips\u0103 de respect fa\u021b\u0103 de culturile locale.", "fr": "Voyager trop est irrespectueux envers les cultures locales.", "it": "\"Viaggiare troppo \u00e8 irrispettoso verso le culture locali.\"", "fi": "\"Liian paljon matkustaminen on ep\u00e4kunnioittavaa paikallisia kulttuureja kohtaan.\"", "nl": "\"Te veel reizen is respectloos tegenover lokale culturen.\"", "no": "\"\u00c5 reise for mye er respektl\u00f8st overfor lokale kulturer.\"", "sv": "\"Att resa f\u00f6r mycket \u00e4r respektl\u00f6st mot lokala kulturer.\"", "pl": "\u201eZbyt cz\u0119ste podr\u00f3\u017cowanie jest brakiem szacunku dla lokalnych kultur.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Travelling too much is disrespectful to local cultures.”';
UPDATE questions
SET translations = '{"en": "\u201cTourism is a form of cultural appropriation.\u201d", "da": "Turisme er en form for kulturel tilegnelse.", "de": "Tourismus ist eine Form kultureller Aneignung.", "es": "El turismo es una forma de apropiaci\u00f3n cultural.", "pt": "O turismo \u00e9 uma forma de apropria\u00e7\u00e3o cultural.", "ro": "Turismul este o form\u0103 de \u00eensu\u0219ire cultural\u0103.", "fr": "Le tourisme est une forme d\u2019appropriation culturelle.", "it": "\"Il turismo \u00e8 una forma di appropriazione culturale.\"", "fi": "\u201dTurismi on er\u00e4\u00e4nlainen kulttuurinen omiminen.\u201d", "nl": "\u201cToerisme is een vorm van culturele toe-eigening.\u201d", "no": "\u00abTurisme er en form for kulturell appropriasjon.\u00bb", "sv": "\"Turism \u00e4r en form av kulturell appropriering.\"", "pl": "\u201eTurystyka jest form\u0105 przyw\u0142aszczenia kulturowego.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tourism is a form of cultural appropriation.”';
UPDATE questions
SET translations = '{"en": "\u201cLuxury brands are just branding \u2014 the products rarely justify the price premium.\u201d", "da": "Luksusm\u00e6rker handler kun om branding \u2013 produkterne retf\u00e6rdigg\u00f8r sj\u00e6ldent prispr\u00e6mien.", "de": "Luxusmarken sind nur Branding \u2013 die Produkte rechtfertigen selten den Preisaufschlag.", "es": "Las marcas de lujo son solo marca: los productos rara vez justifican su precio.", "pt": "As marcas de luxo s\u00e3o apenas branding \u2014 os produtos raramente justificam o pre\u00e7o.", "ro": "M\u0103rcile de lux sunt doar un brand \u2014 produsele rareori justific\u0103 pre\u021bul.", "fr": "Les marques de luxe ne sont que du branding \u2014 les produits justifient rarement leur prix.", "it": "\"Le marche di lusso sono solo branding \u2014 i prodotti raramente giustificano il prezzo elevato.\"", "fi": "\"Ylelliset br\u00e4ndit ovat vain br\u00e4nd\u00e4yst\u00e4 \u2014 tuotteet harvoin oikeuttavat hintalis\u00e4n.\"", "nl": "\u201cLuxe merken zijn gewoon branding \u2014 de producten rechtvaardigen zelden de prijsverhoging.\u201d", "no": "\u00abLuksusmerker er bare merkevarebygging \u2014 produktene rettferdiggj\u00f8r sjelden prisforskjellen.\u00bb", "sv": "\"Lyxm\u00e4rken \u00e4r bara varum\u00e4rken \u2014 produkterna r\u00e4ttf\u00e4rdigar s\u00e4llan prispremiumen.\"", "pl": "\u201eMarki luksusowe to tylko branding \u2014 produkty rzadko uzasadniaj\u0105 wy\u017csz\u0105 cen\u0119.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Luxury brands are just branding — the products rarely justify the price premium.”';
UPDATE questions
SET translations = '{"en": "\u201cMinimalism is just another consumer trend.\u201d", "da": "Minimalisme er bare en anden forbrugertrend.", "de": "Minimalismus ist nur ein weiterer Konsumtrend.", "es": "El minimalismo es solo otra tendencia de consumo.", "pt": "O minimalismo \u00e9 apenas mais uma tend\u00eancia de consumo.", "ro": "Minimalismul este doar o alt\u0103 tendin\u021b\u0103 de consum.", "fr": "Le minimalisme n\u2019est qu\u2019une autre tendance de consommation.", "it": "\"Il minimalismo \u00e8 solo un''altra tendenza di consumo.\"", "fi": "\"Minimalismi on vain toinen kulutustrendi.\"", "nl": "\"Minimalisme is gewoon weer een andere consumententrend.\"", "no": "\"Minimalisme er bare en annen forbrukertrend.\"", "sv": "\"Minimalism \u00e4r bara en annan konsumtionstrend.\"", "pl": "\u201eMinimalizm to tylko kolejny trend konsumpcyjny.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Minimalism is just another consumer trend.”';
UPDATE questions
SET translations = '{"en": "\u201cYou don\u2019t need a college degree to succeed anymore.\u201d", "da": "Du beh\u00f8ver ikke en universitetsgrad for at f\u00e5 succes l\u00e6ngere.", "de": "Man braucht keinen Hochschulabschluss mehr, um erfolgreich zu sein.", "es": "Ya no necesitas un t\u00edtulo universitario para tener \u00e9xito.", "pt": "J\u00e1 n\u00e3o precisas de um diploma universit\u00e1rio para ter sucesso.", "ro": "Nu mai ai nevoie de o diplom\u0103 universitar\u0103 ca s\u0103 reu\u0219e\u0219ti.", "fr": "On n\u2019a plus besoin d\u2019un dipl\u00f4me universitaire pour r\u00e9ussir.", "it": "\"Non hai pi\u00f9 bisogno di una laurea per avere successo.\"", "fi": "\"Sinun ei tarvitse en\u00e4\u00e4 korkeakoulututkintoa menesty\u00e4ksesi.\"", "nl": "\"Je hebt tegenwoordig geen universitaire diploma meer nodig om succesvol te zijn.\"", "no": "\"Du trenger ikke en h\u00f8yskoleutdanning for \u00e5 lykkes lenger.\"", "sv": "\"Du beh\u00f6ver inte en h\u00f6gskoleexamen f\u00f6r att lyckas l\u00e4ngre.\"", "pl": "\u201eNie potrzebujesz ju\u017c dyplomu uczelni, aby odnie\u015b\u0107 sukces.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You don’t need a college degree to succeed anymore.”';
UPDATE questions
SET translations = '{"en": "\u201cStandard schooling is outdated for the 21st century.\u201d", "da": "Standarduddannelse er for\u00e6ldet i det 21. \u00e5rhundrede.", "de": "Standardbildung ist im 21. Jahrhundert veraltet.", "es": "La educaci\u00f3n tradicional est\u00e1 obsoleta en el siglo XXI.", "pt": "O ensino padr\u00e3o est\u00e1 ultrapassado no s\u00e9culo XXI.", "ro": "Educa\u021bia standard este dep\u0103\u0219it\u0103 \u00een secolul XXI.", "fr": "L\u2019enseignement standard est d\u00e9pass\u00e9 au XXIe si\u00e8cle.", "it": "\"La scuola tradizionale \u00e8 obsoleta per il 21\u00b0 secolo.\"", "fi": "\"Perinteinen koulutus on vanhentunut 2000-luvulle.\"", "nl": "\"Standaardonderwijs is verouderd voor de 21ste eeuw.\"", "no": "\"Standard utdanning er utdatert for det 21. \u00e5rhundre.\"", "sv": "\"Standardutbildning \u00e4r f\u00f6r\u00e5ldrad f\u00f6r 2000-talet.\"", "pl": "\u201eStandardowe nauczanie jest przestarza\u0142e na XXI wiek.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Standard schooling is outdated for the 21st century.”';
UPDATE questions
SET translations = '{"en": "\u201cPhysical books are overrated in the age of e-readers.\u201d", "da": "Fysiske b\u00f8ger er overvurderede i e-l\u00e6sernes tidsalder.", "de": "Physische B\u00fccher sind im Zeitalter der E-Reader \u00fcberbewertet.", "es": "Los libros f\u00edsicos est\u00e1n sobrevalorados en la era de los e-readers.", "pt": "Os livros f\u00edsicos est\u00e3o sobrevalorizados na era dos e-readers.", "ro": "C\u0103r\u021bile fizice sunt supraevaluate \u00een epoca cititoarelor electronice.", "fr": "Les livres physiques sont surestim\u00e9s \u00e0 l\u2019\u00e8re des liseuses.", "it": "\"I libri fisici sono sopravvalutati nell''era degli e-reader.\"", "fi": "\"Fyysiset kirjat ovat yliarvostettuja e-lukijoiden aikakaudella.\"", "nl": "\"Fysieke boeken zijn overschat in het tijdperk van e-readers.\"", "no": "\"Fysiske b\u00f8ker er overvurderte i e-boklesernes tidsalder.\"", "sv": "\"Fysiska b\u00f6cker \u00e4r \u00f6verskattade i e-l\u00e4sarens tids\u00e5lder.\"", "pl": "\u201eFizyczne ksi\u0105\u017cki s\u0105 przereklamowane w erze czytnik\u00f3w e-book\u00f3w.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Physical books are overrated in the age of e-readers.”';
UPDATE questions
SET translations = '{"en": "\u201cAudiobooks count as reading \u2014 maybe even better than books.\u201d", "da": "Lydb\u00f8ger t\u00e6ller som l\u00e6sning \u2013 m\u00e5ske endda bedre end b\u00f8ger.", "de": "H\u00f6rb\u00fccher z\u00e4hlen als Lesen \u2013 vielleicht sogar besser als B\u00fccher.", "es": "Los audiolibros cuentan como lectura \u2014 quiz\u00e1s incluso mejor que los libros.", "pt": "Os audiolivros contam como leitura \u2014 talvez at\u00e9 melhor do que os livros.", "ro": "C\u0103r\u021bile audio se pun ca lectur\u0103 \u2014 poate chiar mai bune dec\u00e2t c\u0103r\u021bile.", "fr": "Les livres audio comptent comme de la lecture \u2014 voire mieux que les livres.", "it": "\u201cGli audiolibri contano come lettura \u2014 forse anche meglio dei libri.\u201d", "fi": "\"\u00c4\u00e4nikirjat lasketaan lukemiseksi \u2014 ehk\u00e4 jopa paremmiksi kuin kirjat.\"", "nl": "\"Luisterboeken tellen als lezen \u2014 misschien zelfs beter dan boeken.\"", "no": "\"Lydb\u00f8ker teller som lesing \u2014 kanskje til og med bedre enn b\u00f8ker.\"", "sv": "\"Lyssna p\u00e5 b\u00f6cker r\u00e4knas som l\u00e4sning \u2014 kanske till och med b\u00e4ttre \u00e4n b\u00f6cker.\"", "pl": "\u201eAudiobooki licz\u0105 si\u0119 jako czytanie \u2014 mo\u017ce nawet lepiej ni\u017c ksi\u0105\u017cki.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Audiobooks count as reading — maybe even better than books.”';
UPDATE questions
SET translations = '{"en": "\u201cYou should judge people by their digital footprint, not just appearance.\u201d", "da": "Du b\u00f8r bed\u00f8mme folk efter deres digitale fodaftryk, ikke kun udseende.", "de": "Man sollte Menschen nach ihrem digitalen Fu\u00dfabdruck beurteilen, nicht nur nach dem Aussehen.", "es": "Deber\u00edas juzgar a las personas por su huella digital, no solo por su apariencia.", "pt": "Devemos julgar as pessoas pela sua pegada digital, n\u00e3o apenas pela apar\u00eancia.", "ro": "Ar trebui s\u0103 judeci oamenii dup\u0103 amprenta lor digital\u0103, nu doar dup\u0103 aspect.", "fr": "On devrait juger les gens selon leur empreinte num\u00e9rique, pas seulement leur apparence.", "it": "\"Dovresti giudicare le persone in base alla loro impronta digitale, non solo all''aspetto.\"", "fi": "\"Sinun pit\u00e4isi arvioida ihmisi\u00e4 heid\u00e4n digitaalisen jalanj\u00e4lkens\u00e4 perusteella, ei vain ulkon\u00e4\u00f6n.\"", "nl": "\"Je zou mensen moeten beoordelen op hun digitale voetafdruk, niet alleen op hun uiterlijk.\"", "no": "\"Du b\u00f8r d\u00f8mme folk etter deres digitale fotavtrykk, ikke bare utseende.\"", "sv": "\"Du borde d\u00f6ma m\u00e4nniskor utifr\u00e5n deras digitala fotavtryck, inte bara utseende.\"", "pl": "\u201ePowiniene\u015b ocenia\u0107 ludzi po ich \u015bladzie cyfrowym, a nie tylko po wygl\u0105dzie.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You should judge people by their digital footprint, not just appearance.”';
UPDATE questions
SET translations = '{"en": "\u201cEveryone should be required to serve in some form (civil, military, ambiental) for a year.\u201d", "da": "Alle burde v\u00e6re forpligtet til at tjene et \u00e5r i en form for tjeneste (civil, milit\u00e6r, milj\u00f8).", "de": "Jeder sollte verpflichtet sein, ein Jahr in irgendeiner Form von Dienst (zivil, milit\u00e4risch, \u00f6kologisch) zu leisten.", "es": "Todos deber\u00edan estar obligados a servir durante un a\u00f1o en alguna forma (civil, militar, ambiental).", "pt": "Todos deveriam ser obrigados a servir durante um ano em alguma forma (civil, militar, ambiental).", "ro": "To\u021bi ar trebui s\u0103 fie obliga\u021bi s\u0103 serveasc\u0103 un an \u00eentr-o form\u0103 de serviciu (civil, militar, ecologic).", "fr": "Tout le monde devrait \u00eatre tenu de servir pendant un an sous une forme (civile, militaire, environnementale).", "it": "\u201cTutti dovrebbero essere obbligati a servire in qualche forma (civile, militare, ambientale) per un anno.\u201d", "fi": "\"Kaikkien tulisi olla velvollisia palvelemaan jollain tavalla (kansalais-, sotilas-, ymp\u00e4rist\u00f6hankkeissa) vuoden ajan.\"", "nl": "\" Iedereen zou verplicht moeten zijn om een jaar op de een of andere manier (civiel, militair, milieu) te dienen.\"", "no": "\"Alle b\u00f8r v\u00e6re p\u00e5lagt \u00e5 tjene i en eller annen form (sivil, milit\u00e6r, milj\u00f8messig) i ett \u00e5r.\"", "sv": "\"Alla borde vara skyldiga att tj\u00e4nstg\u00f6ra i n\u00e5gon form (civil, milit\u00e4r, milj\u00f6) i ett \u00e5r.\"", "pl": "\u201eKa\u017cdy powinien by\u0107 zobowi\u0105zany do s\u0142u\u017cby w jakiej\u015b formie (cywilnej, wojskowej, \u015brodowiskowej) przez rok.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Everyone should be required to serve in some form (civil, military, ambiental) for a year.”';
UPDATE questions
SET translations = '{"en": "\u201cMonuments to historical figures who were flawed should be destroyed, not contextualized.\u201d", "da": "Monumenter for historiske personer med fejl b\u00f8r \u00f8del\u00e6gges, ikke kontekstualiseres.", "de": "Denkm\u00e4ler f\u00fcr fehlerhafte historische Pers\u00f6nlichkeiten sollten zerst\u00f6rt, nicht kontextualisiert werden.", "es": "Los monumentos a figuras hist\u00f3ricas con defectos deber\u00edan ser destruidos, no contextualizados.", "pt": "Os monumentos a figuras hist\u00f3ricas com falhas deveriam ser destru\u00eddos, n\u00e3o contextualizados.", "ro": "Monumentele dedicate persoanelor istorice care au gre\u0219it ar trebui distruse, nu contextualizate.", "fr": "Les monuments d\u00e9di\u00e9s \u00e0 des figures historiques imparfaites devraient \u00eatre d\u00e9truits, pas contextualis\u00e9s.", "it": "\"I monumenti a figure storiche che avevano dei difetti dovrebbero essere distrutti, non contestualizzati.\"", "fi": "\"Historiallisten henkil\u00f6iden, joilla oli puutteita, muistomerkit tulisi tuhota, ei kontekstualisoida.\"", "nl": "\"Monumenten voor historische figuren die gebreken hadden, zouden vernietigd moeten worden, niet gecontextualiseerd.\"", "no": "\"Monumenter til historiske personer som hadde feil, b\u00f8r \u00f8delegges, ikke kontekstualiseres.\"", "sv": "\"Monument till historiska personer som hade brister b\u00f6r rivas, inte kontextualiseras.\"", "pl": "\u201ePomniki historycznych postaci, kt\u00f3re mia\u0142y wady, powinny zosta\u0107 zniszczone, a nie kontekstualizowane.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Monuments to historical figures who were flawed should be destroyed, not contextualized.”';
UPDATE questions
SET translations = '{"en": "\u201cNational borders are morally arbitrary.\u201d", "da": "Nationale gr\u00e6nser er moralsk vilk\u00e5rlige.", "de": "Nationale Grenzen sind moralisch willk\u00fcrlich.", "es": "Las fronteras nacionales son moralmente arbitrarias.", "pt": "As fronteiras nacionais s\u00e3o moralmente arbitr\u00e1rias.", "ro": "Grani\u021bele na\u021bionale sunt arbitrare din punct de vedere moral.", "fr": "Les fronti\u00e8res nationales sont moralement arbitraires.", "it": "\"Le frontiere nazionali sono moralmente arbitrarie.\"", "fi": "\"Kansalliset rajat ovat moraalisesti satunnaisia.\"", "nl": "\"Nationale grenzen zijn moreel willekeurig.\"", "no": "\"Nasjonsgrenser er moralsk vilk\u00e5rlige.\"", "sv": "\"Nationella gr\u00e4nser \u00e4r moraliskt godtyckliga.\"", "pl": "\u201eGranice narodowe s\u0105 moralnie arbitralne.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“National borders are morally arbitrary.”';
UPDATE questions
SET translations = '{"en": "\u201cImmigration is overwhelmingly beneficial to any country.\u201d", "da": "Immigration er overvejende gavnlig for ethvert land.", "de": "Einwanderung ist f\u00fcr jedes Land \u00fcberwiegend vorteilhaft.", "es": "La inmigraci\u00f3n es abrumadoramente beneficiosa para cualquier pa\u00eds.", "pt": "A imigra\u00e7\u00e3o \u00e9 esmagadoramente ben\u00e9fica para qualquer pa\u00eds.", "ro": "Imigra\u021bia este cov\u00e2r\u0219itor benefic\u0103 pentru orice \u021bar\u0103.", "fr": "L\u2019immigration est largement b\u00e9n\u00e9fique pour tout pays.", "it": "\"L''immigrazione \u00e8 straordinariamente vantaggiosa per qualsiasi paese.\"", "fi": "\"Maahanmuutto on ylivoimaisesti hy\u00f6dyllist\u00e4 mille tahansa maalle.\"", "nl": "\"Immigratie is overwegend voordelig voor elk land.\"", "no": "\"Immigrasjon er overveldende gunstig for ethvert land.\"", "sv": "\"Invandring \u00e4r \u00f6verv\u00e4ldigande f\u00f6rdelaktigt f\u00f6r vilket land som helst.\"", "pl": "\u201eImigracja jest w przewa\u017caj\u0105cej mierze korzystna dla ka\u017cdego kraju.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Immigration is overwhelmingly beneficial to any country.”';
UPDATE questions
SET translations = '{"en": "\u201cOpen borders is a better policy than strict immigration control.\u201d", "da": "\u00c5bne gr\u00e6nser er en bedre politik end streng immigrationskontrol.", "de": "Offene Grenzen sind eine bessere Politik als strenge Einwanderungskontrolle.", "es": "Las fronteras abiertas son una mejor pol\u00edtica que el control migratorio estricto.", "pt": "Fronteiras abertas s\u00e3o uma pol\u00edtica melhor do que o controlo rigoroso da imigra\u00e7\u00e3o.", "ro": "Grani\u021bele deschise sunt o politic\u0103 mai bun\u0103 dec\u00e2t controlul strict al imigra\u021biei.", "fr": "Les fronti\u00e8res ouvertes sont une meilleure politique qu\u2019un contr\u00f4le migratoire strict.", "it": "\"Le frontiere aperte sono una politica migliore rispetto a un controllo rigoroso dell''immigrazione.\"", "fi": "\"Avoimet rajat ovat parempi politiikka kuin tiukka maahanmuuttopolitiikka.\"", "nl": "\"Open grenzen is een betere beleidskeuze dan strikte immigratiecontrole.\"", "no": "\"\u00c5pne grenser er en bedre politikk enn streng innvandringskontroll.\"", "sv": "\"\u00d6ppna gr\u00e4nser \u00e4r en b\u00e4ttre politik \u00e4n strikt invandringskontroll.\"", "pl": "\u201eOtwarte granice to lepsza polityka ni\u017c surowa kontrola imigracyjna.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Open borders is a better policy than strict immigration control.”';
UPDATE questions
SET translations = '{"en": "\u201cUniversal healthcare should be global, not just national.\u201d", "da": "Universel sundhedspleje b\u00f8r v\u00e6re global, ikke kun national.", "de": "Universelle Gesundheitsversorgung sollte global, nicht nur national sein.", "es": "La atenci\u00f3n m\u00e9dica universal deber\u00eda ser global, no solo nacional.", "pt": "A sa\u00fade universal deveria ser global, n\u00e3o apenas nacional.", "ro": "Asisten\u021ba medical\u0103 universal\u0103 ar trebui s\u0103 fie global\u0103, nu doar na\u021bional\u0103.", "fr": "Les soins de sant\u00e9 universels devraient \u00eatre mondiaux, pas seulement nationaux.", "it": "\"La sanit\u00e0 universale dovrebbe essere globale, non solo nazionale.\"", "fi": "\"Yleinen terveydenhuolto pit\u00e4isi olla globaalia, ei vain kansallista.\"", "nl": "\"Universele gezondheidszorg zou wereldwijd moeten zijn, niet alleen nationaal.\"", "no": "\"Universell helseomsorg b\u00f8r v\u00e6re global, ikke bare nasjonal.\"", "sv": "\"Universell sjukv\u00e5rd b\u00f6r vara global, inte bara nationell.\"", "pl": "\u201eOpieka zdrowotna powinna by\u0107 globalna, a nie tylko krajowa.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Universal healthcare should be global, not just national.”';
UPDATE questions
SET translations = '{"en": "\u201cVaccination mandates violate bodily autonomy.\u201d", "da": "Vaccinetvang kr\u00e6nker kropslig autonomi.", "de": "Impfpflichten verletzen die k\u00f6rperliche Autonomie.", "es": "Los mandatos de vacunaci\u00f3n violan la autonom\u00eda corporal.", "pt": "As obrigatoriedades de vacina\u00e7\u00e3o violam a autonomia corporal.", "ro": "Obliga\u021biile de vaccinare \u00eencalc\u0103 autonomia corporal\u0103.", "fr": "Les obligations de vaccination violent l\u2019autonomie corporelle.", "it": "\"Le vaccinazioni obbligatorie violano l''autonomia corporea.\"", "fi": "\"Rokotusvelvoitteet rikkovat kehon itsem\u00e4\u00e4r\u00e4\u00e4misoikeutta.\"", "nl": "\"Vaccinatieverplichtingen schenden de lichamelijke autonomie.\"", "no": "\"Vaksinasjonsmandater krenker kroppslig autonomi.\"", "sv": "\"Vaccinationsmandat kr\u00e4nker kroppslig autonomi.\"", "pl": "\u201eObowi\u0105zkowe szczepienia naruszaj\u0105 autonomi\u0119 cia\u0142a.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Vaccination mandates violate bodily autonomy.”';
UPDATE questions
SET translations = '{"en": "\u201cOur phones are basically part of our personality now \u2014 and that\u2019s not always bad.\u201d", "da": "Vores telefoner er i bund og grund en del af vores personlighed nu \u2013 og det er ikke altid d\u00e5rligt.", "de": "Unsere Telefone sind im Grunde Teil unserer Pers\u00f6nlichkeit \u2013 und das ist nicht immer schlecht.", "es": "Nuestros tel\u00e9fonos son b\u00e1sicamente parte de nuestra personalidad \u2014 y eso no siempre es malo.", "pt": "Os nossos telem\u00f3veis s\u00e3o basicamente parte da nossa personalidade \u2014 e isso nem sempre \u00e9 mau.", "ro": "Telefoanele noastre sunt practic parte din personalitatea noastr\u0103 acum \u2014 \u0219i nu e \u00eentotdeauna r\u0103u.", "fr": "Nos t\u00e9l\u00e9phones font d\u00e9sormais partie de notre personnalit\u00e9 \u2014 et ce n\u2019est pas toujours mauvais.", "it": "\"I nostri telefoni sono praticamente parte della nostra personalit\u00e0 adesso \u2014 e non \u00e8 sempre una cosa negativa.\"", "fi": "\"Puhelimemme ovat k\u00e4yt\u00e4nn\u00f6ss\u00e4 osa persoonallisuuttamme nyt \u2014 eik\u00e4 se aina ole huono asia.\"", "nl": "\"Onze telefoons maken tegenwoordig eigenlijk deel uit van onze persoonlijkheid \u2014 en dat is niet altijd slecht.\"", "no": "\u00abTelefonene v\u00e5re er i bunn og grunn en del av personligheten v\u00e5r n\u00e5 \u2014 og det er ikke alltid d\u00e5rlig.\u00bb", "sv": "\"V\u00e5ra telefoner \u00e4r i princip en del av v\u00e5r personlighet nu \u2014 och det \u00e4r inte alltid d\u00e5ligt.\"", "pl": "\u201eNasze telefony s\u0105 teraz zasadniczo cz\u0119\u015bci\u0105 naszej osobowo\u015bci \u2014 i to nie zawsze jest z\u0142e.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Our phones are basically part of our personality now — and that’s not always bad.”';
UPDATE questions
SET translations = '{"en": "\u201cTech billionaires are the new rockstars \u2014 just with worse outfits.\u201d", "da": "Tech-milliard\u00e6rer er de nye rockstjerner \u2013 bare med d\u00e5rligere t\u00f8j.", "de": "Tech-Milliard\u00e4re sind die neuen Rockstars \u2013 nur mit schlechterer Kleidung.", "es": "Los multimillonarios tecnol\u00f3gicos son las nuevas estrellas de rock \u2014 solo con peor ropa.", "pt": "Os bilion\u00e1rios da tecnologia s\u00e3o as novas estrelas do rock \u2014 s\u00f3 com pior roupa.", "ro": "Miliardarii din tehnologie sunt noii rockstari \u2014 doar cu haine mai ur\u00e2te.", "fr": "Les milliardaires de la tech sont les nouvelles rockstars \u2014 juste avec de moins bons v\u00eatements.", "it": "\"I miliardari della tecnologia sono le nuove rockstar \u2014 solo con abiti peggiori.\"", "fi": "\"Teknologiabillion\u00e4\u00e4rit ovat uusia rockt\u00e4hti\u00e4 \u2014 vain huonommilla vaatteilla.\"", "nl": "\"Techmiljardairs zijn de nieuwe rocksterren \u2014 alleen met slechtere outfits.\"", "no": "\u201cTeknologi milliard\u00e6rer er de nye rockestjernene \u2014 bare med d\u00e5rligere antrekk.\u201d", "sv": "\"Techmiljard\u00e4rer \u00e4r de nya rockstj\u00e4rnorna \u2014 bara med s\u00e4mre kl\u00e4der.\"", "pl": "\u201eBillionerzy technologiczni to nowi rockmani \u2014 tylko w gorszych strojach.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tech billionaires are the new rockstars — just with worse outfits.”';
UPDATE questions
SET translations = '{"en": "\u201cLoyalty to a company is strange when a company can replace you in a week.\u201d", "da": "Loyalitet over for en virksomhed er m\u00e6rkeligt, n\u00e5r virksomheden kan erstatte dig p\u00e5 en uge.", "de": "Loyalit\u00e4t zu einer Firma ist seltsam, wenn dich das Unternehmen in einer Woche ersetzen kann.", "es": "Es raro ser leal a una empresa cuando esa empresa puede reemplazarte en una semana.", "pt": "\u00c9 estranho ser leal a uma empresa quando essa empresa te pode substituir em uma semana.", "ro": "Loialitatea fa\u021b\u0103 de o firm\u0103 este ciudat\u0103 c\u00e2nd compania te poate \u00eenlocui \u00eentr-o s\u0103pt\u0103m\u00e2n\u0103.", "fr": "La loyaut\u00e9 envers une entreprise est \u00e9trange quand cette entreprise peut te remplacer en une semaine.", "it": "\"La fedelt\u00e0 a un''azienda \u00e8 strana quando un''azienda pu\u00f2 sostituirti in una settimana.\"", "fi": "\"Uskollisuus yritykselle on outoa, kun yritys voi korvata sinut viikossa.\"", "nl": "\"Het is vreemd om loyaal te zijn aan een bedrijf als een bedrijf je binnen een week kan vervangen.\"", "no": "\u00abLojalitet til et selskap er merkelig n\u00e5r et selskap kan erstatte deg p\u00e5 en uke.\u00bb", "sv": "\"Lojalitet till ett f\u00f6retag \u00e4r konstigt n\u00e4r ett f\u00f6retag kan ers\u00e4tta dig p\u00e5 en vecka.\"", "pl": "\u201eLojalno\u015b\u0107 wobec firmy jest dziwna, gdy firma mo\u017ce ci\u0119 zast\u0105pi\u0107 w tydzie\u0144.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Loyalty to a company is strange when a company can replace you in a week.”';
UPDATE questions
SET translations = '{"en": "\u201cWorking for yourself is overrated \u2014 a steady paycheck is the real dream.\u201d", "da": "At arbejde for sig selv er overvurderet \u2013 en stabil l\u00f8n er den virkelige dr\u00f8m.", "de": "Selbstst\u00e4ndigkeit ist \u00fcberbewertet \u2013 ein sicheres Gehalt ist der wahre Traum.", "es": "Trabajar por cuenta propia est\u00e1 sobrevalorado \u2014 un sueldo fijo es el verdadero sue\u00f1o.", "pt": "Trabalhar por conta pr\u00f3pria \u00e9 sobrevalorizado \u2014 um sal\u00e1rio fixo \u00e9 o verdadeiro sonho.", "ro": "A lucra pe cont propriu este supraevaluat \u2014 un salariu stabil e visul adev\u0103rat.", "fr": "Travailler \u00e0 son compte est surestim\u00e9 \u2014 un salaire stable, c\u2019est le vrai r\u00eave.", "it": "\"Lavorare per conto proprio \u00e8 sopravvalutato \u2014 uno stipendio fisso \u00e8 il vero sogno.\"", "fi": "\"Ty\u00f6skentely itselleen on yliarvostettua \u2014 s\u00e4\u00e4nn\u00f6llinen palkka on todellinen unelma.\"", "nl": "\"Voor jezelf werken is overschat \u2014 een vast salaris is de echte droom.\"", "no": "\"\u00c5 jobbe for seg selv er overvurdert \u2014 en stabil l\u00f8nnsslipp er den virkelige dr\u00f8mmen.\"", "sv": "\"Att arbeta f\u00f6r sig sj\u00e4lv \u00e4r \u00f6verskattat \u2014 en stabil l\u00f6n \u00e4r den verkliga dr\u00f6mmen.\"", "pl": "\u201ePraca na w\u0142asny rachunek jest przereklamowana \u2014 sta\u0142a pensja to prawdziwy sen.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Working for yourself is overrated — a steady paycheck is the real dream.”';
UPDATE questions
SET translations = '{"en": "\u201cTech companies should have a \u2018karma score\u2019 for how good or bad they are for humanity.\u201d", "da": "Teknologivirksomheder burde have en \u201ckarma-score\u201d for, hvor gode eller d\u00e5rlige de er for menneskeheden.", "de": "Tech-Unternehmen sollten eine \u201eKarma-Bewertung\u201c haben, wie gut oder schlecht sie f\u00fcr die Menschheit sind.", "es": "Las empresas tecnol\u00f3gicas deber\u00edan tener una \u201cpuntuaci\u00f3n k\u00e1rmica\u201d seg\u00fan lo buenas o malas que sean para la humanidad.", "pt": "As empresas de tecnologia deveriam ter uma \u201cpontua\u00e7\u00e3o de karma\u201d pelo bem ou mal que fazem \u00e0 humanidade.", "ro": "Companiile tehnologice ar trebui s\u0103 aib\u0103 un \u201escor karmic\u201d pentru c\u00e2t de bune sau rele sunt pentru omenire.", "fr": "Les entreprises technologiques devraient avoir un \u00ab score de karma \u00bb selon leur impact sur l\u2019humanit\u00e9.", "it": "\"Le aziende tecnologiche dovrebbero avere un ''punteggio karma'' per quanto siano buone o cattive per l''umanit\u00e0.\"", "fi": "\"Teknologiayrityksill\u00e4 pit\u00e4isi olla ''karma-pisteet'' siit\u00e4, kuinka hyvi\u00e4 tai huonoja ne ovat ihmiskunnalle.\"", "nl": "\"Technologiebedrijven zouden een ''karma-score'' moeten hebben voor hoe goed of slecht ze zijn voor de mensheid.\"", "no": "\"Teknologiselskaper b\u00f8r ha en ''karma-score'' for hvor gode eller d\u00e5rlige de er for menneskeheten.\"", "sv": "\"Teknikf\u00f6retag borde ha en ''karma-po\u00e4ng'' f\u00f6r hur bra eller d\u00e5liga de \u00e4r f\u00f6r m\u00e4nskligheten.\"", "pl": "\u201eFirmy technologiczne powinny mie\u0107 ''wynik karmy'' oceniaj\u0105cy, jak dobre lub z\u0142e s\u0105 dla ludzko\u015bci.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tech companies should have a ‘karma score’ for how good or bad they are for humanity.”';
UPDATE questions
SET translations = '{"en": "\u201cData privacy is a luxury, not a right.\u201d", "da": "Dataprivatliv er en luksus, ikke en ret.", "de": "Datenschutz ist ein Luxus, kein Recht.", "es": "La privacidad de los datos es un lujo, no un derecho.", "pt": "A privacidade dos dados \u00e9 um luxo, n\u00e3o um direito.", "ro": "Confiden\u021bialitatea datelor este un lux, nu un drept.", "fr": "La vie priv\u00e9e des donn\u00e9es est un luxe, pas un droit.", "it": "\"La privacy dei dati \u00e8 un lusso, non un diritto.\"", "fi": "\"Tietosuoja on luksusta, ei oikeus.\"", "nl": "\"Gegevensprivacy is een luxe, geen recht.\"", "no": "\"Dataprivacy er en luksus, ikke en rettighet.\"", "sv": "\"Dataskydd \u00e4r en lyx, inte en r\u00e4ttighet.\"", "pl": "\u201ePrywatno\u015b\u0107 danych to luksus, a nie prawo.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Data privacy is a luxury, not a right.”';
UPDATE questions
SET translations = '{"en": "\u201cGovernment surveillance is inevitable and acceptable for security.\u201d", "da": "Regeringsoverv\u00e5gning er uundg\u00e5elig og acceptabel for sikkerheden.", "de": "Staatliche \u00dcberwachung ist unvermeidlich und akzeptabel f\u00fcr die Sicherheit.", "es": "La vigilancia gubernamental es inevitable y aceptable por seguridad.", "pt": "A vigil\u00e2ncia governamental \u00e9 inevit\u00e1vel e aceit\u00e1vel pela seguran\u00e7a.", "ro": "Supravegherea guvernamental\u0103 este inevitabil\u0103 \u0219i acceptabil\u0103 pentru siguran\u021b\u0103.", "fr": "La surveillance gouvernementale est in\u00e9vitable et acceptable pour la s\u00e9curit\u00e9.", "it": "\"La sorveglianza governativa \u00e8 inevitabile e accettabile per la sicurezza.\"", "fi": "\"Valtion valvonta on v\u00e4\u4e0d\u53ef\u907f\u514d\u4e14\u53ef\u63a5\u53d7 turvallisuuden vuoksi.\"", "nl": "\"Overheidsbewaking is onvermijdelijk en acceptabel voor de veiligheid.\"", "no": "\u201cRegjeringsoverv\u00e5kning er uunng\u00e5elig og akseptabelt for sikkerhet.\u201d", "sv": "\"Regeringens \u00f6vervakning \u00e4r oundviklig och acceptabel f\u00f6r s\u00e4kerhet.\"", "pl": "\u201eNadz\u00f3r rz\u0105dowy jest nieunikniony i akceptowalny dla bezpiecze\u0144stwa.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Government surveillance is inevitable and acceptable for security.”';
UPDATE questions
SET translations = '{"en": "\u201cIt\u2019s okay to be average \u2014 not everything needs to be about growth and optimization.\u201d", "da": "Det er okay bare at v\u00e6re gennemsnitlig \u2013 ikke alting beh\u00f8ver at handle om v\u00e6kst og optimering.", "de": "Es ist okay, durchschnittlich zu sein \u2013 nicht alles muss sich um Wachstum und Optimierung drehen.", "es": "Est\u00e1 bien ser una persona promedio; no todo tiene que tratarse de crecimiento y optimizaci\u00f3n.", "pt": "Est\u00e1 tudo bem em ser mediano \u2013 nem tudo tem de ser sobre crescimento e otimiza\u00e7\u00e3o.", "ro": "E \u00een regul\u0103 s\u0103 fii mediocru \u2013 nu totul trebuie s\u0103 fie despre cre\u0219tere \u0219i optimizare.", "fr": "C\u2019est OK d\u2019\u00eatre moyen \u2013 tout n\u2019a pas besoin de tourner autour de la croissance et de l\u2019optimisation.", "it": "\"Va bene essere nella media \u2014 non tutto deve riguardare la crescita e l''ottimizzazione.\"", "fi": "\"On ihan ok olla keskiverto \u2014 ei kaiken tarvitse liitty\u00e4 kasvuun ja optimointiin.\"", "nl": "\"Het is ok\u00e9 om gemiddeld te zijn \u2014 niet alles hoeft te draaien om groei en optimalisatie.\"", "no": "\"Det er greit \u00e5 v\u00e6re gjennomsnittlig \u2014 ikke alt trenger \u00e5 handle om vekst og optimalisering.\"", "sv": "\"Det \u00e4r okej att vara genomsnittlig \u2014 inte allt beh\u00f6ver handla om tillv\u00e4xt och optimering.\"", "pl": "\u201eW porz\u0105dku jest by\u0107 przeci\u0119tnym \u2014 nie wszystko musi dotyczy\u0107 wzrostu i optymalizacji.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“It’s okay to be average — not everything needs to be about growth and optimization.”';
UPDATE questions
SET translations = '{"en": "\u201cDeleting social media for \u2018mental health\u2019 is the new humblebrag.\u201d", "da": "At slette sociale medier for \u201cmental sundhed\u201d er den nye humblebrag.", "de": "Soziale Medien aus Gr\u00fcnden der \u201ementalen Gesundheit\u201c zu l\u00f6schen ist das neue Bescheidenheits-Branding.", "es": "Eliminar las redes sociales por \u201csalud mental\u201d es el nuevo humilde alarde.", "pt": "Apagar as redes sociais por \u201csa\u00fade mental\u201d \u00e9 o novo gesto humilde de vaidade.", "ro": "\u0218tergerea re\u021belelor sociale pentru \u201es\u0103n\u0103tatea mintal\u0103\u201d este noua form\u0103 de laud\u0103 modest\u0103.", "fr": "Supprimer les r\u00e9seaux sociaux pour sa \u00ab sant\u00e9 mentale \u00bb est le nouveau humblebrag.", "it": "\"Cancellare i social media per la ''salute mentale'' \u00e8 il nuovo modo di vantarsi con umilt\u00e0.\"", "fi": "\"Someiden poistaminen ''mielenterveyden'' vuoksi on uusi vaatimaton ylpeily.\"", "nl": "\"Sociale media verwijderen voor ''mentale gezondheid'' is de nieuwe bescheiden opschepperij.\"", "no": "\"\u00c5 slette sosiale medier for ''mental helse'' er den nye ydmyke skryten.\"", "sv": "\"Att radera sociala medier f\u00f6r ''mental h\u00e4lsa'' \u00e4r den nya blygsamma skryten.\"", "pl": "\u201eUsuni\u0119cie medi\u00f3w spo\u0142eczno\u015bciowych dla ''zdrowia psychicznego'' to nowy spos\u00f3b na chwalenie si\u0119.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Deleting social media for ‘mental health’ is the new humblebrag.”';
UPDATE questions
SET translations = '{"en": "\u201cAdult friendships shouldn\u2019t require a Google Calendar.\u201d", "da": "Venskaber for voksne burde ikke kr\u00e6ve en Google Kalender.", "de": "Freundschaften unter Erwachsenen sollten keinen Google Kalender erfordern.", "es": "Las amistades adultas no deber\u00edan requerir un Google Calendar.", "pt": "As amizades adultas n\u00e3o deviam precisar de um Google Calendar.", "ro": "Prieteniile \u00eentre adul\u021bi n-ar trebui s\u0103 necesite un Google Calendar.", "fr": "Les amiti\u00e9s d\u2019adultes ne devraient pas n\u00e9cessiter un agenda Google.", "it": "\"Le amicizie adulte non dovrebbero richiedere un Google Calendar.\"", "fi": "\"Aikuisyst\u00e4vyyksien ei pit\u00e4isi vaatia Google-kalenteria.\"", "nl": "\"Volwassen vriendschappen zouden geen Google Agenda moeten vereisen.\"", "no": "\"Vennskap blant voksne b\u00f8r ikke kreve en Google-kalender.\"", "sv": "\"Vuxna v\u00e4nskaper borde inte kr\u00e4va en Google-kalender.\"", "pl": "\u201ePrzyja\u017anie doros\u0142ych nie powinny wymaga\u0107 kalendarza Google.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Adult friendships shouldn’t require a Google Calendar.”';