UPDATE questions
SET translations = '{"en": "Is there anything you wish I\u2019d stop doing in bed?", "da": "Er der noget, du ville \u00f8nske, jeg ville holde op med at lave i sengen?", "de": "Gibt es etwas, das du dir w\u00fcnschst, ich w\u00fcrde im Bett nicht mehr tun?", "es": "\u00bfHay algo que quisieras que dejara de hacer en la cama?", "pt": "H\u00e1 algo que gostarias que eu deixasse de fazer na cama?", "ro": "Exist\u0103 ceva ce \u021bi-ai dori s\u0103 nu mai fac \u00een pat?", "fr": "Y a-t-il quelque chose que tu aimerais que j\u2019arr\u00eate de faire au lit ?", "it": "C''\u00e8 qualcosa che desideri che smetta di fare a letto?", "fi": "Onko jotain, mit\u00e4 toivoisit minun lopettavan s\u00e4ngyss\u00e4?", "nl": "Is er iets waarvan je zou willen dat ik ermee stop in bed?", "no": "Er det noe du \u00f8nsker jeg skulle slutte \u00e5 gj\u00f8re i sengen?", "sv": "Finns det n\u00e5got du \u00f6nskar att jag skulle sluta g\u00f6ra i s\u00e4ngen?", "pl": "Czy jest co\u015b, co chcia\u0142by\u015b, \u017cebym przesta\u0142 robi\u0107 w \u0142\u00f3\u017cku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is there anything you wish I’d stop doing in bed?';
UPDATE questions
SET translations = '{"en": "Is the anything new you\u2019d want us to try next time?", "da": "Er der noget nyt, du gerne vil have, vi skal pr\u00f8ve n\u00e6ste gang?", "de": "Gibt es etwas Neues, das du m\u00f6chtest, dass wir beim n\u00e4chsten Mal ausprobieren?", "es": "\u00bfHay algo nuevo que te gustar\u00eda que prob\u00e1ramos la pr\u00f3xima vez?", "pt": "H\u00e1 algo novo que gostarias que experiment\u00e1ssemos da pr\u00f3xima vez?", "ro": "Este ceva nou ce ai vrea s\u0103 \u00eencerc\u0103m data viitoare?", "fr": "Y a-t-il quelque chose de nouveau que tu voudrais qu\u2019on essaie la prochaine fois ?", "it": "C''\u00e8 qualcosa di nuovo che vorresti provare la prossima volta?", "fi": "Onko jotain uutta, mit\u00e4 haluaisit meid\u00e4n kokeilevan ensi kerralla?", "nl": "Is er iets nieuws dat je de volgende keer zou willen proberen?", "no": "Er det noe nytt du \u00f8nsker at vi skal pr\u00f8ve neste gang?", "sv": "\u00c4r det n\u00e5got nytt du skulle vilja att vi provar n\u00e4sta g\u00e5ng?", "pl": "Czy jest co\u015b nowego, co chcia\u0142by\u015b, \u017ceby\u015bmy spr\u00f3bowali nast\u0119pnym razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is the anything new you’d want us to try next time?';
UPDATE questions
SET translations = '{"en": "Do you prefer experimenting with different positions, or do you have favorites that always work?", "da": "Foretr\u00e6kker du at eksperimentere med forskellige stillinger, eller har du favoritter, der altid virker?", "de": "Probierst du gerne verschiedene Stellungen aus, oder hast du Favoriten, die immer funktionieren?", "es": "\u00bfPrefieres experimentar con distintas posiciones o tienes tus favoritas?", "pt": "Preferes experimentar v\u00e1rias posi\u00e7\u00f5es ou tens as tuas favoritas?", "ro": "\u00ce\u021bi place s\u0103 experimentezi pozi\u021bii diferite sau ai favoritele tale?", "fr": "Pr\u00e9f\u00e8res-tu exp\u00e9rimenter diff\u00e9rentes positions ou as-tu tes pr\u00e9f\u00e9r\u00e9es ?", "it": "Preferisci sperimentare con diverse posizioni, o hai delle preferite che funzionano sempre?", "fi": "Pid\u00e4tk\u00f6 enemm\u00e4n erilaisten asentojen kokeilemisesta, vai onko sinulla suosikkeja, jotka aina toimivat?", "nl": "Heb je liever om te experimenteren met verschillende posities, of heb je favorieten die altijd werken?", "no": "Foretrekker du \u00e5 eksperimentere med forskjellige stillinger, eller har du favoritter som alltid fungerer?", "sv": "F\u00f6redrar du att experimentera med olika st\u00e4llningar, eller har du favoriter som alltid fungerar?", "pl": "Czy wolisz eksperymentowa\u0107 z r\u00f3\u017cnymi pozycjami, czy masz ulubione, kt\u00f3re zawsze si\u0119 sprawdzaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you prefer experimenting with different positions, or do you have favorites that always work?';
UPDATE questions
SET translations = '{"en": "Have you ever been curious about using toys together?", "da": "Har du nogensinde v\u00e6ret nysgerrig efter at bruge leget\u00f8j sammen?", "de": "Warst du jemals neugierig, Sexspielzeug zusammen zu benutzen?", "es": "\u00bfAlguna vez has tenido curiosidad de usar juguetes juntos?", "pt": "J\u00e1 tiveste curiosidade de usar brinquedos juntos?", "ro": "Ai fost vreodat\u0103 curios(\u0103) s\u0103 folosim juc\u0103rii \u00eempreun\u0103?", "fr": "As-tu d\u00e9j\u00e0 eu envie d\u2019utiliser des jouets avec moi ?", "it": "Sei mai stato curioso di usare i giocattoli insieme?", "fi": "Oletko koskaan ollut utelias leikkim\u00e4\u00e4n leluilla yhdess\u00e4?", "nl": "Ben je ooit nieuwsgierig geweest naar het samen gebruiken van speelgoed?", "no": "Har du noen gang v\u00e6rt nysgjerrig p\u00e5 \u00e5 bruke leker sammen?", "sv": "Har du n\u00e5gonsin varit nyfiken p\u00e5 att anv\u00e4nda leksaker tillsammans?", "pl": "Czy kiedykolwiek zastanawia\u0142e\u015b si\u0119 nad wsp\u00f3lnym u\u017cywaniem zabawek?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever been curious about using toys together?';
UPDATE questions
SET translations = '{"en": "How do you feel about revisiting something we tried once but haven\u2019t in a while?", "da": "Hvad synes du om at pr\u00f8ve noget igen, vi har pr\u00f8vet engang, men ikke har gjort i et stykke tid?", "de": "Was h\u00e4ltst du davon, etwas wieder auszuprobieren, das wir schon einmal getan haben, aber lange nicht mehr?", "es": "\u00bfQu\u00e9 opinas de volver a probar algo que hicimos hace tiempo?", "pt": "O que achas de voltarmos a tentar algo que fizemos h\u00e1 algum tempo?", "ro": "Ce p\u0103rere ai despre a \u00eencerca din nou ceva ce am f\u0103cut c\u00e2ndva?", "fr": "Que penses-tu de refaire quelque chose que nous avons essay\u00e9 il y a longtemps ?", "it": "Come ti senti riguardo a riprovare qualcosa che abbiamo gi\u00e0 provato una volta ma che non facciamo da un po''?", "fi": "Mit\u00e4 mielt\u00e4 olet siit\u00e4, ett\u00e4 kokeilisimme uudelleen jotain, mit\u00e4 yritimme kerran mutta emme ole tehneet pitk\u00e4\u00e4n aikaan?", "nl": "Hoe voel je je over het opnieuw proberen van iets wat we eens hebben gedaan, maar al een tijdje niet meer?", "no": "Hvordan f\u00f8ler du om \u00e5 gjenta noe vi pr\u00f8vde en gang, men ikke har gjort p\u00e5 en stund?", "sv": "Hur k\u00e4nner du f\u00f6r att \u00e5terbes\u00f6ka n\u00e5got vi provade en g\u00e5ng men inte har gjort p\u00e5 ett tag?", "pl": "Co my\u015blisz o ponownym spr\u00f3bowaniu czego\u015b, co ju\u017c raz zrobili\u015bmy, ale od jakiego\u015b czasu tego nie robimy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about revisiting something we tried once but haven’t in a while?';
UPDATE questions
SET translations = '{"en": "Which of us is more likely to want another round?", "da": "Hvem af os er mest tilb\u00f8jelig til at have lyst til en omgang mere?", "de": "Wer von uns hat eher Lust auf eine zweite Runde?", "es": "\u00bfQui\u00e9n de nosotros es m\u00e1s propenso a querer una ronda m\u00e1s?", "pt": "Quem de n\u00f3s tem mais tend\u00eancia para querer uma segunda rodada?", "ro": "Cine dintre noi vrea mai des o a doua rund\u0103?", "fr": "Lequel de nous deux a le plus souvent envie d\u2019une deuxi\u00e8me fois ?", "it": "Quale di noi \u00e8 pi\u00f9 propenso a volere un altro giro?", "fi": "Kumpi meist\u00e4 todenn\u00e4k\u00f6isemmin haluaa viel\u00e4 yhden kierroksen?", "nl": "Wie van ons is waarschijnlijker om nog een ronde te willen?", "no": "Hvem av oss er mer sannsynlig \u00e5 \u00f8nske en runde til?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att vilja ha en runda till?", "pl": "Kt\u00f3ry z nas jest bardziej sk\u0142onny do ch\u0119ci na kolejna rund\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to want another round?';
UPDATE questions
SET translations = '{"en": "What\u2019s your opinion on toys that we can use while we\u2019re apart?", "da": "Hvad er din mening om leget\u00f8j, vi kan bruge, mens vi er fra hinanden? ", "de": "Was h\u00e4ltst du von Spielzeug, das wir benutzen k\u00f6nnten, wenn wir getrennt sind?", "es": "\u00bfQu\u00e9 piensas de los juguetes que podr\u00edamos usar cuando estamos separados?", "pt": "O que pensas sobre brinquedos que poder\u00edamos usar quando estamos separados?", "ro": "Ce p\u0103rere ai despre juc\u0103rii pe care le-am putea folosi c\u00e2nd suntem departe?", "fr": "Que penses-tu des jouets qu\u2019on pourrait utiliser quand on est s\u00e9par\u00e9s ?", "it": "Qual \u00e8 la tua opinione sui giocattoli che possiamo usare mentre siamo lontani?", "fi": "Mit\u00e4 mielt\u00e4 olet leluista, joita voimme k\u00e4ytt\u00e4\u00e4, kun olemme eristyksiss\u00e4?", "nl": "Wat is jouw mening over speelgoed dat we kunnen gebruiken terwijl we apart zijn?", "no": "Hva er din mening om leker vi kan bruke mens vi er fra hverandre?", "sv": "Vad tycker du om leksaker som vi kan anv\u00e4nda n\u00e4r vi \u00e4r \u00e5tskilda?", "pl": "Jakie jest twoje zdanie na temat zabawek, kt\u00f3re mo\u017cemy u\u017cywa\u0107, gdy jeste\u015bmy daleko od siebie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your opinion on toys that we can use while we’re apart?';
UPDATE questions
SET translations = '{"en": "What kind of place feels thrillingly off-limits for us?", "da": "Hvilken slags sted f\u00f8les sp\u00e6ndende og forbudt for os?", "de": "Welche Art von Ort f\u00fchlt sich f\u00fcr uns aufregend und verboten an?", "es": "\u00bfQu\u00e9 tipo de lugar te parece emocionante y prohibido para nosotros?", "pt": "Que tipo de lugar te parece excitante e proibido para n\u00f3s?", "ro": "Ce fel de loc \u021bi se pare incitant \u0219i interzis pentru noi?", "fr": "Quel genre d\u2019endroit te semble excitant et interdit pour nous ?", "it": "Che tipo di luogo ci sembra emozionantemente vietato?", "fi": "Mink\u00e4lainen paikka tuntuu j\u00e4nnitt\u00e4v\u00e4sti kielletylt\u00e4 meille?", "nl": "Wat voor soort plek voelt spannend verboden voor ons?", "no": "Hvilken type sted f\u00f8les spennende og utenfor rekkevidde for oss?", "sv": "Vilken typ av plats k\u00e4nns sp\u00e4nnande otillg\u00e4nglig f\u00f6r oss?", "pl": "Jakie miejsce wydaje si\u0119 nam ekscytuj\u0105co niedost\u0119pne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of place feels thrillingly off-limits for us?';
UPDATE questions
SET translations = '{"en": "Does the thought of almost being caught ever turn you on?", "da": "T\u00e6nder tanken om n\u00e6sten at blive opdaget dig nogensinde?", "de": "Macht dich der Gedanke an, fast erwischt zu werden, an?", "es": "\u00bfTe excita la idea de casi ser descubierto/a?", "pt": "Excita-te a ideia de quase seres apanhado/a?", "ro": "Te excit\u0103 g\u00e2ndul c\u0103 ai putea fi aproape descoperit(\u0103)?", "fr": "L\u2019id\u00e9e d\u2019\u00eatre presque surpris(e), t\u2019excite-t-elle ?", "it": "Il pensiero di essere quasi scoperto ti eccita mai?", "fi": "Kiehtooko ajatus siit\u00e4, ett\u00e4 melkein j\u00e4\u00e4 kiinni, koskaan sinua?", "nl": "Maakt de gedachte om bijna betrapt te worden je ooit opgewonden?", "no": "F\u00e5r tanken p\u00e5 \u00e5 nesten bli tatt deg noen gang til \u00e5 f\u00f8le deg tent?", "sv": "Blir du n\u00e5gonsin upphetsad av tanken p\u00e5 att n\u00e4stan bli p\u00e5kommen?", "pl": "Czy my\u015bl o prawie byciu przy\u0142apanym kiedykolwiek ci\u0119 podnieca?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Does the thought of almost being caught ever turn you on?';
UPDATE questions
SET translations = '{"en": "Would you enjoy a little risk \u2014 like a quiet, hidden spot only we know about?", "da": "Ville du nyde en lille risiko \u2013 som et stille, skjult sted, som kun vi kender til?", "de": "W\u00fcrdest du ein kleines Risiko genie\u00dfen \u2013 einen stillen, geheimen Ort, den nur wir kennen?", "es": "\u00bfDisfrutar\u00edas un poco de riesgo, como un lugar secreto solo nuestro?", "pt": "Gostarias de um pouco de risco \u2013 um lugar secreto s\u00f3 nosso?", "ro": "\u021ai-ar pl\u0103cea pu\u021bin risc \u2013 un loc ascuns doar al nostru?", "fr": "Aimerais-tu un peu de risque \u2013 un endroit secret que nous seuls connaissons ?", "it": "Ti piacerebbe un po'' di rischio \u2014 come un posto tranquillo e nascosto che conosciamo solo noi?", "fi": "Nauttisitko pienest\u00e4 riskist\u00e4 \u2014 kuten rauhallisesta, piilotetusta paikasta, jonka vain me tied\u00e4mme?", "nl": "Zou je genieten van een klein risico \u2014 zoals een rustige, verborgen plek die alleen wij kennen?", "no": "Ville du sette pris p\u00e5 litt risiko \u2014 som et stille, skjult sted bare vi vet om?", "sv": "Skulle du tycka om en liten risk \u2014 som en tyst, g\u00f6md plats som bara vi k\u00e4nner till?", "pl": "Czy cieszy\u0142by\u015b si\u0119 z odrobiny ryzyka \u2014 na przyk\u0142ad z cichego, ukrytego miejsca, o kt\u00f3rym wiemy tylko my?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Would you enjoy a little risk — like a quiet, hidden spot only we know about?';
UPDATE questions
SET translations = '{"en": "What\u2019s one fantasy of ours that you\u2019d actually want to make happen?", "da": "Hvilken fantasi ville du rent faktisk gerne f\u00f8re ud i livet?", "de": "Welche Fantasie w\u00fcrdest du wirklich gerne ausleben?", "es": "\u00bfQu\u00e9 fantas\u00eda te gustar\u00eda realmente hacer realidad?", "pt": "Que fantasia gostarias mesmo de realizar?", "ro": "Ce fantezie \u021bi-ar pl\u0103cea cu adev\u0103rat s\u0103 tr\u0103ie\u0219ti?", "fr": "Quelle fantaisie aimerais-tu vraiment r\u00e9aliser ?", "it": "Qual \u00e8 una nostra fantasia che vorresti davvero realizzare?", "fi": "Mik\u00e4 on yksi fantasiasi, jonka haluaisit todella toteuttaa?", "nl": "Wat is \u00e9\u00e9n fantasie van ons die je eigenlijk werkelijkheid zou willen laten worden?", "no": "Hva er en av v\u00e5re fantasier som du faktisk ville \u00f8nsket \u00e5 gj\u00f8re til virkelighet?", "sv": "Vilken av v\u00e5ra fantasier skulle du faktiskt vilja f\u00f6rverkliga?", "pl": "Jakie jedno nasze marzenie chcia\u0142by\u015b naprawd\u0119 zrealizowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one fantasy of ours that you’d actually want to make happen?';
UPDATE questions
SET translations = '{"en": "How do you feel about me being a bit more dominant \u2014 or would you rather take charge?", "da": "Hvad synes du om, at jeg er lidt mere dominerende \u2013 eller vil du hellere tage styringen?", "de": "Wie findest du es, wenn ich etwas dominanter bin \u2013 oder \u00fcbernimmst du lieber die Kontrolle?", "es": "\u00bfQu\u00e9 opinas si yo fuera un poco m\u00e1s dominante, o prefieres tomar el control?", "pt": "O que achas se eu fosse um pouco mais dominante, ou preferes tu o controlo?", "ro": "Ce p\u0103rere ai dac\u0103 a\u0219 fi pu\u021bin mai dominant(\u0103), sau preferi tu s\u0103 preiei controlul?", "fr": "Que penses-tu si j\u2019\u00e9tais un peu plus dominant(e) \u2013 ou pr\u00e9f\u00e8res-tu prendre le contr\u00f4le ?", "it": "Come ti senti riguardo al fatto che io sia un po'' pi\u00f9 dominante \u2014 o preferiresti prendere tu il comando?", "fi": "Milt\u00e4 sinusta tuntuu, ett\u00e4 olisin hieman dominoivampi \u2014 vai haluaisitko mieluummin ottaa ohjat itsellesi?", "nl": "Hoe voel je je over het idee dat ik wat dominanter ben \u2014 of heb je liever dat jij de leiding neemt?", "no": "Hvordan f\u00f8ler du om at jeg er litt mer dominerende \u2014 eller ville du heller ta kontrollen?", "sv": "Hur k\u00e4nner du f\u00f6r att jag \u00e4r lite mer dominant \u2014 eller skulle du hellre ta kommandot?", "pl": "Jak si\u0119 czujesz z tym, \u017ce by\u0142bym troch\u0119 bardziej dominuj\u0105cy \u2014 czy wola\u0142by\u015b przej\u0105\u0107 kontrol\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about me being a bit more dominant — or would you rather take charge?';
UPDATE questions
SET translations = '{"en": "How do you feel about us shopping for lingerie or underwear together?", "da": "Hvad synes du om, at vi shopper lingeri eller undert\u00f8j sammen?", "de": "Wie f\u00e4ndest du es, wenn wir gemeinsam Dessous einkaufen gehen?", "es": "\u00bfQu\u00e9 opinas de ir juntos a comprar lencer\u00eda o ropa interior?", "pt": "O que achas de irmos juntos comprar lingerie ou roupa interior?", "ro": "Ce p\u0103rere ai s\u0103 mergem \u00eempreun\u0103 s\u0103 cump\u0103r\u0103m lenjerie?", "fr": "Que penses-tu d\u2019aller acheter de la lingerie ensemble ?", "it": "Cosa ne pensi di andare a comprare insieme della lingerie o della biancheria intima?", "fi": "Milt\u00e4 sinusta tuntuu, jos menisimme yhdess\u00e4 ostamaan alusvaatteita tai alushousuja?", "nl": "Hoe voel je je over het samen winkelen voor lingerie of ondergoed?", "no": "Hvordan f\u00f8ler du om at vi handler undert\u00f8y sammen?", "sv": "Hur k\u00e4nner du f\u00f6r att vi handlar underkl\u00e4der tillsammans?", "pl": "Co my\u015blisz o tym, \u017ceby\u015bmy razem poszli na zakupy po bielizn\u0119 lub majtki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about us shopping for lingerie or underwear together?';
UPDATE questions
SET translations = '{"en": "What turns you on the most: making noise, or trying to stay quiet while we\u2019re doing it?", "da": "Hvad t\u00e6nder dig mest: At lave st\u00f8j eller at fors\u00f8ge at forblive stille, mens vi g\u00f8r det?", "de": "Was erregt dich mehr \u2013 laut zu sein oder zu versuchen, still zu bleiben, w\u00e4hrend wir es tun?", "es": "\u00bfQu\u00e9 te excita m\u00e1s: hacer ruido o intentar mantenerte en silencio mientras lo hacemos?", "pt": "O que te excita mais: fazer barulho ou tentar ficar em sil\u00eancio enquanto o fazemos?", "ro": "Ce te excit\u0103 mai mult: s\u0103 faci zgomot sau s\u0103 \u00eencerci s\u0103 r\u0103m\u00e2i t\u0103cut(\u0103) \u00een timp ce o facem?", "fr": "Qu\u2019est-ce qui t\u2019excite le plus : faire du bruit ou essayer de rester silencieux(se) pendant qu\u2019on le fait ?", "it": "Cosa ti eccita di pi\u00f9: fare rumore o cercare di rimanere in silenzio mentre lo facciamo?", "fi": "Mik\u00e4 saa sinut eniten innostumaan: melun tekeminen vai yritt\u00e4minen pysy\u00e4 hiljaa, kun teemme sit\u00e4?", "nl": "Wat opwindt je het meest: geluid maken, of proberen stil te blijven terwijl we het doen?", "no": "Hva tenner deg mest: \u00e5 lage lyd, eller \u00e5 pr\u00f8ve \u00e5 v\u00e6re stille mens vi gj\u00f8r det?", "sv": "Vad t\u00e4nder dig mest: att g\u00f6ra ljud, eller att f\u00f6rs\u00f6ka vara tyst medan vi g\u00f6r det?", "pl": "Co najbardziej ci\u0119 podnieca: robienie ha\u0142asu, czy pr\u00f3ba bycia cicho podczas tego, co robimy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What turns you on the most: making noise, or trying to stay quiet while we’re doing it?';
UPDATE questions
SET translations = '{"en": "What\u2019s the weirdest thing that unexpectedly turned you on about me?", "da": "Hvad var det m\u00e6rkeligste, der uventet t\u00e6ndte dig ved mig?", "de": "Was war das Seltsamste, das dich unerwartet an mir erregt hat?", "es": "\u00bfQu\u00e9 fue lo m\u00e1s extra\u00f1o que inesperadamente te excit\u00f3 de m\u00ed?", "pt": "O que foi o mais estranho que inesperadamente te excitou em mim?", "ro": "Care a fost cel mai ciudat lucru care te-a excitat la mine f\u0103r\u0103 s\u0103 te a\u0219tep\u021bi?", "fr": "Quelle est la chose la plus \u00e9trange qui t\u2019a excit\u00e9(e) chez moi ?", "it": "Qual \u00e8 la cosa pi\u00f9 strana che ti ha sorpreso e ti ha attratto di me?", "fi": "Mik\u00e4 on oudoin asia, joka yll\u00e4tt\u00e4en her\u00e4tti sinussa kiinnostusta minua kohtaan?", "nl": "Wat is het vreemdste dat je onverwacht aantrekkelijk vond aan mij?", "no": "Hva er det merkeligste som uventet tente deg p\u00e5 med meg?", "sv": "Vad \u00e4r det konstigaste som ov\u00e4ntat t\u00e4nde dig p\u00e5 mig?", "pl": "Co by\u0142o najdziwniejszym czym\u015b, co niespodziewanie ci\u0119 we mnie podnieci\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s the weirdest thing that unexpectedly turned you on about me?';
UPDATE questions
SET translations = '{"en": "Do you like slow kisses on your back and neck?", "da": "Kan du lide langsomme kys p\u00e5 din ryg og nakke?", "de": "Magst du langsame K\u00fcsse auf deinem R\u00fccken und Nacken?", "es": "\u00bfTe gustan los besos lentos en la espalda y el cuello?", "pt": "Gostas de beijos lentos nas costas e no pesco\u00e7o?", "ro": "\u00ce\u021bi plac s\u0103ruturile lente pe spate \u0219i pe g\u00e2t?", "fr": "Aimes-tu les baisers lents sur ton dos et ton cou ?", "it": "Ti piacciono i baci lenti sulla schiena e sul collo?", "fi": "Pid\u00e4tk\u00f6 hitaista suudelmista sel\u00e4ss\u00e4si ja kaulassasi?", "nl": "Hou je van langzame kussen op je rug en nek?", "no": "Liker du sakte kyss p\u00e5 ryggen og nakken?", "sv": "Tycker du om l\u00e5ngsamma kyssar p\u00e5 ryggen och nacken?", "pl": "Czy lubisz powolne poca\u0142unki na plecach i szyi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you like slow kisses on your back and neck?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing about our sex life you\u2019d love to explore more deeply?", "da": "Hvad er \u00e9n ting ved vores sexliv, du gerne vil udforske dybere?", "de": "Was ist eine Sache an unserem Sexleben, die du gerne tiefer erforschen w\u00fcrdest?", "es": "\u00bfQu\u00e9 es algo de nuestra vida sexual que te gustar\u00eda explorar m\u00e1s?", "pt": "O que \u00e9 algo da nossa vida sexual que gostarias de explorar mais?", "ro": "Ce este ceva din via\u021ba noastr\u0103 sexual\u0103 ce ai vrea s\u0103 explorezi mai mult?", "fr": "Qu\u2019aimerais-tu explorer davantage dans notre vie sexuelle ?", "it": "Qual \u00e8 una cosa della nostra vita sessuale che ti piacerebbe esplorare pi\u00f9 a fondo?", "fi": "Mik\u00e4 on yksi asia seksiel\u00e4m\u00e4st\u00e4mme, jota haluaisit tutkia syvemmin?", "nl": "Wat is \u00e9\u00e9n ding over ons seksleven dat je graag dieper zou willen verkennen?", "no": "Hva er \u00e9n ting ved v\u00e5rt sexliv du gjerne vil utforske dypere?", "sv": "Vad \u00e4r en sak om v\u00e5rt sexliv som du skulle vilja utforska djupare?", "pl": "Co\u015b, co chcia\u0142by\u015b zg\u0142\u0119bi\u0107 bardziej w naszym \u017cyciu seksualnym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one thing about our sex life you’d love to explore more deeply?';
UPDATE questions
SET translations = '{"en": "What kind of restraint or surrender do you secretly find hot?", "da": "Hvilken form for tilbageholdenhed eller overgivelse synes du i hemmelighed er hot?", "de": "Welche Art von Zur\u00fcckhaltung oder Hingabe findest du heimlich hei\u00df?", "es": "\u00bfQu\u00e9 tipo de control o rendici\u00f3n secreta te parece m\u00e1s excitante?", "pt": "Que tipo de controlo ou entrega secreta te parece mais excitante?", "ro": "Ce fel de control sau abandon \u021bi se pare secret \u0219i excitant?", "fr": "Quelle forme de contr\u00f4le ou de soumission trouves-tu secr\u00e8tement excitante ?", "it": "Che tipo di restrizione o resa trovi segretamente eccitante?", "fi": "Mink\u00e4laista pid\u00e4t salaa kuumana, kun on kyse pid\u00e4tyksest\u00e4 tai antautumisesta?", "nl": "Welke vorm van beperking of overgave vind je stiekem opwindend?", "no": "Hvilken type tilbakeholdenhet eller overgivelse synes du hemmelig er sexy?", "sv": "Vilken typ av begr\u00e4nsning eller \u00f6verl\u00e5telse tycker du hemligt \u00e4r sexig?", "pl": "Jakiego rodzaju pow\u015bci\u0105gni\u0119cie lub poddanie si\u0119 potajemnie uwa\u017casz za poci\u0105gaj\u0105ce?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of restraint or surrender do you secretly find hot?';
UPDATE questions
SET translations = '{"en": "What\u2019s a part of your body you wish I\u2019d pay more attention to?", "da": "Hvilken del af din krop ville du \u00f8nske, jeg ville v\u00e6re mere opm\u00e6rksom p\u00e5?", "de": "Welchen Teil deines K\u00f6rpers w\u00fcnschst du dir, dass ich mehr beachte?", "es": "\u00bfQu\u00e9 parte de tu cuerpo quisieras que yo prestara m\u00e1s atenci\u00f3n?", "pt": "Que parte do teu corpo gostarias que eu prestasse mais aten\u00e7\u00e3o?", "ro": "Ce parte a corpului t\u0103u \u021bi-ai dori s\u0103 o explorez mai mult?", "fr": "Quelle partie de ton corps aimerais-tu que je remarque davantage ?", "it": "Quale parte del tuo corpo vorresti che io prestassi pi\u00f9 attenzione?", "fi": "Mik\u00e4 osa kehostasi on sellainen, johon toivoisit minun kiinnitt\u00e4v\u00e4n enemm\u00e4n huomiota?", "nl": "Welke deel van je lichaam zou je willen dat ik meer aandacht aan besteed?", "no": "Hvilken del av kroppen din \u00f8nsker du at jeg skulle legge mer merke til?", "sv": "Vilken del av din kropp \u00f6nskar du att jag skulle l\u00e4gga mer m\u00e4rke till?", "pl": "Jak\u0105 cz\u0119\u015bci\u0105 swojego cia\u0142a chcia\u0142by\u015b, \u017cebym po\u015bwi\u0119ci\u0142 wi\u0119cej uwagi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s a part of your body you wish I’d pay more attention to?';
UPDATE questions
SET translations = '{"en": "How do you feel about pushing our comfort zone with something that feels slightly forbidden?", "da": "Hvad synes du om at presse vores komfortzone med noget, der f\u00f8les en smule forbudt?", "de": "Wie findest du es, unsere Komfortzone mit etwas leicht Verbotenem zu erweitern?", "es": "\u00bfQu\u00e9 opinas de empujar nuestros l\u00edmites con algo que se sienta un poco prohibido?", "pt": "O que achas de ultrapassarmos os nossos limites com algo que pare\u00e7a um pouco proibido?", "ro": "Ce p\u0103rere ai despre a dep\u0103\u0219i limitele cu ceva ce pare pu\u021bin interzis?", "fr": "Que penses-tu d\u2019explorer nos limites avec quelque chose d\u2019un peu interdit ?", "it": "Come ti senti riguardo a spingere il nostro comfort zone con qualcosa che sembra leggermente proibito?", "fi": "Milt\u00e4 sinusta tuntuu, ett\u00e4 ty\u00f6nt\u00e4isimme mukavuusaluettamme johonkin, mik\u00e4 tuntuu hieman kielletylt\u00e4?", "nl": "Hoe voel je je over het verleggen van onze comfortzone met iets dat een beetje verboden aanvoelt?", "no": "Hvordan f\u00f8ler du om \u00e5 presse komfortsonen v\u00e5r med noe som f\u00f8les litt forbudt?", "sv": "Hur k\u00e4nner du f\u00f6r att t\u00e4nja p\u00e5 v\u00e5ra gr\u00e4nser med n\u00e5got som k\u00e4nns lite f\u00f6rbjudet?", "pl": "Jak si\u0119 czujesz z pomys\u0142em na poszerzenie naszej strefy komfortu w czym\u015b, co wydaje si\u0119 lekko zakazane?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about pushing our comfort zone with something that feels slightly forbidden?';
UPDATE questions
SET translations = '{"en": "Have you ever held back because you didn\u2019t want to shock me?", "da": "Har du nogensinde holdt dig tilbage, fordi du ikke ville chokere mig?", "de": "Hast du dich jemals zur\u00fcckgehalten, weil du mich nicht schockieren wolltest?", "es": "\u00bfAlguna vez te has contenido por miedo a sorprenderme?", "pt": "J\u00e1 te contiveste por medo de me chocar?", "ro": "Te-ai re\u021binut vreodat\u0103 pentru c\u0103 nu ai vrut s\u0103 m\u0103 \u0219ochezi?", "fr": "T\u2019es-tu d\u00e9j\u00e0 retenu(e) par peur de me choquer ?", "it": "Hai mai trattenuto qualcosa perch\u00e9 non volevi scioccarmi?", "fi": "Oletko koskaan pid\u00e4tellyt itse\u00e4si, koska et halunnut j\u00e4rkytt\u00e4\u00e4 minua?", "nl": "Heb je ooit iets achtergehouden omdat je me niet wilde schokken?", "no": "Har du noen gang holdt tilbake fordi du ikke ville sjokkere meg?", "sv": "Har du n\u00e5gonsin h\u00e5llit tillbaka f\u00f6r att du inte ville chocka mig?", "pl": "Czy kiedykolwiek powstrzyma\u0142e\u015b si\u0119, poniewa\u017c nie chcia\u0142e\u015b mnie zszokowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever held back because you didn’t want to shock me?';
UPDATE questions
SET translations = '{"en": "What\u2019s something playful you wish we did more often?", "da": "Hvad er noget legende, du ville \u00f8nske, vi gjorde oftere?", "de": "Was ist etwas Verspieltes, das du dir w\u00fcnschst, wir w\u00fcrden \u00f6fter tun?", "es": "\u00bfQu\u00e9 cosa juguetona te gustar\u00eda que hici\u00e9ramos m\u00e1s a menudo?", "pt": "Que coisa divertida gostarias que fiz\u00e9ssemos mais vezes?", "ro": "Ce lucru juc\u0103u\u0219 ai vrea s\u0103 facem mai des?", "fr": "Quelle chose ludique aimerais-tu qu\u2019on fasse plus souvent ?", "it": "Qualcosa di giocoso che vorresti facessimo pi\u00f9 spesso?", "fi": "Mik\u00e4 on jokin leikkis\u00e4 asia, jota toivoisit tekev\u00e4mme useammin?", "nl": "Wat is iets speels dat je wenst dat we vaker deden?", "no": "Hva er noe lekent du skulle \u00f8nske vi gjorde oftere?", "sv": "Vad \u00e4r n\u00e5got lekfullt som du \u00f6nskar att vi gjorde oftare?", "pl": "Co\u015b zabawnego, co chcia\u0142by\u015b, \u017ceby\u015bmy robili cz\u0119\u015bciej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s something playful you wish we did more often?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite time of day to get intimate?", "da": "Hvad er dit yndlingstidspunkt p\u00e5 dagen at blive intim?", "de": "Was ist deine Lieblingszeit am Tag, um intim zu werden?", "es": "\u00bfCu\u00e1l es tu momento favorito del d\u00eda para ser \u00edntimos?", "pt": "Qual \u00e9 o teu momento favorito do dia para sermos \u00edntimos?", "ro": "Care este momentul t\u0103u preferat al zilei pentru a fi intimi?", "fr": "Quel est ton moment pr\u00e9f\u00e9r\u00e9 de la journ\u00e9e pour \u00eatre intime ?", "it": "Qual \u00e8 il tuo momento preferito della giornata per essere intimo?", "fi": "Mik\u00e4 on suosikkiaikasi p\u00e4iv\u00e4st\u00e4 intiimiyteen?", "nl": "Wat is jouw favoriete tijd van de dag om intiem te zijn?", "no": "Hva er ditt favorittidspunkt p\u00e5 dagen for \u00e5 bli intim?", "sv": "Vilken tid p\u00e5 dagen tycker du b\u00e4st om att vara intim?", "pl": "Jaka jest twoja ulubiona pora dnia na intymno\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite time of day to get intimate?';
UPDATE questions
SET translations = '{"en": "Which of us is more likely to start something and pretend it\u2019s innocent?", "da": "Hvem af os er mest tilb\u00f8jelig til at starte noget og lade som om, det er uskyldigt?", "de": "Wer von uns f\u00e4ngt am ehesten etwas an und tut so, als w\u00e4re es unschuldig?", "es": "\u00bfQui\u00e9n de los dos es m\u00e1s propenso a empezar algo y fingir que es inocente?", "pt": "Quem de n\u00f3s tem mais tend\u00eancia a come\u00e7ar algo fingindo ser inocente?", "ro": "Cine dintre noi \u00eencepe ceva pref\u0103c\u00e2ndu-se c\u0103 e nevinovat(\u0103)?", "fr": "Lequel de nous deux commence quelque chose en faisant semblant d\u2019\u00eatre innocent(e) ?", "it": "Quale di noi \u00e8 pi\u00f9 probabile che inizi qualcosa e faccia finta che sia innocente?", "fi": "Kumpi meist\u00e4 on todenn\u00e4k\u00f6isemmin se, joka aloittaa jotain ja esitt\u00e4\u00e4 sen viattomana?", "nl": "Wie van ons is waarschijnlijker om iets te beginnen en te doen alsof het onschuldig is?", "no": "Hvem av oss er mer sannsynlig til \u00e5 starte noe og late som om det er uskyldig?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att starta n\u00e5got och l\u00e5tsas att det \u00e4r oskyldigt?", "pl": "Kto z nas jest bardziej sk\u0142onny do rozpocz\u0119cia czego\u015b i udawania, \u017ce to niewinne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to start something and pretend it’s innocent?';
UPDATE questions
SET translations = '{"en": "Which of us hides it worse when we\u2019re turned on?", "da": "Hvem af os skjuler det v\u00e6rst, n\u00e5r vi er t\u00e6ndte? ", "de": "Wer von uns kann seine Erregung am schlechtesten verbergen?", "es": "\u00bfQui\u00e9n de los dos disimula peor cuando est\u00e1 excitado/a?", "pt": "Quem de n\u00f3s disfar\u00e7a pior quando est\u00e1 excitado/a?", "ro": "Cine dintre noi ascunde cel mai prost c\u00e2nd este excitat(\u0103)?", "fr": "Lequel de nous deux cache le moins bien quand il/elle est excit\u00e9(e) ?", "it": "Chi di noi lo nasconde peggio quando \u00e8 eccitato?", "fi": "Kumpi meist\u00e4 piilottaa sen huonommin, kun olemme kiihottuneita?", "nl": "Wie van ons verbergt het slechter als we opgewonden zijn?", "no": "Hvem av oss skjuler det d\u00e5rligere n\u00e5r vi er tent?", "sv": "Vilken av oss d\u00f6ljer det s\u00e4mst n\u00e4r vi \u00e4r upphetsade?", "pl": "Kto z nas gorzej to ukrywa, gdy jeste\u015bmy podnieceni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us hides it worse when we’re turned on?';
UPDATE questions
SET translations = '{"en": "Which of us do you think loses focus faster when the flirting starts?", "da": "Hvem af os tror du mister fokus hurtigere, n\u00e5r flirten starter?", "de": "Wer von uns verliert schneller den Fokus, wenn das Flirten beginnt?", "es": "\u00bfQui\u00e9n de los dos pierde la concentraci\u00f3n m\u00e1s r\u00e1pido cuando empieza el coqueteo?", "pt": "Quem de n\u00f3s perde a concentra\u00e7\u00e3o mais depressa quando a provoca\u00e7\u00e3o come\u00e7a?", "ro": "Cine dintre noi \u00ee\u0219i pierde mai repede concentrarea c\u00e2nd \u00eencepe flirtul?", "fr": "Lequel de nous deux perd sa concentration le plus vite quand la s\u00e9duction commence ?", "it": "Chi di noi pensi che perda pi\u00f9 rapidamente la concentrazione quando inizia il flirt?", "fi": "Kumpi meist\u00e4 luulet menett\u00e4v\u00e4n keskittymisen nopeammin, kun flirttailu alkaa?", "nl": "Wie van ons denk je dat sneller de focus verliest als het flirten begint?", "no": "Hvem av oss tror du mister fokus raskere n\u00e5r fl\u00f8rtingen begynner?", "sv": "Vilken av oss tror du tappar fokus snabbare n\u00e4r flirten b\u00f6rjar?", "pl": "Kt\u00f3ry z nas, twoim zdaniem, szybciej traci koncentracj\u0119, gdy zaczyna si\u0119 flirt?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us do you think loses focus faster when the flirting starts?';
UPDATE questions
SET translations = '{"en": "Which of us likes to be in control more?", "da": "Hvem af os kan bedst lide at have kontrol?", "de": "Wer von uns mag es mehr, die Kontrolle zu haben?", "es": "\u00bfQui\u00e9n de los dos disfruta m\u00e1s teniendo el control?", "pt": "Quem de n\u00f3s gosta mais de ter o controlo?", "ro": "Cine dintre noi iube\u0219te mai mult s\u0103 de\u021bin\u0103 controlul?", "fr": "Lequel de nous deux aime le plus avoir le contr\u00f4le ?", "it": "Chi di noi ama di pi\u00f9 avere il controllo?", "fi": "Kumpi meist\u00e4 pit\u00e4\u00e4 enemm\u00e4n siit\u00e4, ett\u00e4 on kontrollissa?", "nl": "Wie van ons houdt er meer van om de controle te hebben?", "no": "Hvem av oss liker \u00e5 ha kontroll mer?", "sv": "Vilken av oss gillar att ha kontroll mer?", "pl": "Kto z nas bardziej lubi mie\u0107 kontrol\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us likes to be in control more?';
UPDATE questions
SET translations = '{"en": "Which of us is more likely to sneak a flirty message during the day?", "da": "Hvem af os er mere tilb\u00f8jelig til at snige en flirtende besked i l\u00f8bet af dagen?", "de": "Wer von uns schickt eher eine flirtende Nachricht w\u00e4hrend des Tages?", "es": "\u00bfQui\u00e9n de los dos suele enviar m\u00e1s mensajes coquetos durante el d\u00eda?", "pt": "Quem de n\u00f3s costuma enviar mais mensagens provocantes durante o dia?", "ro": "Cine dintre noi trimite mai des mesaje cochete \u00een timpul zilei?", "fr": "Lequel de nous deux envoie le plus de messages coquins dans la journ\u00e9e ?", "it": "Quale di noi \u00e8 pi\u00f9 probabile che invii un messaggio flirtante durante il giorno?", "fi": "Kumpi meist\u00e4 on todenn\u00e4k\u00f6isemmin l\u00e4hett\u00e4m\u00e4ss\u00e4 flirttailevaa viesti\u00e4 p\u00e4iv\u00e4n aikana?", "nl": "Wie van ons is waarschijnlijker om overdag een flirterig berichtje te sturen?", "no": "Hvem av oss er mer sannsynlig \u00e5 sende en fl\u00f8rtete melding i l\u00f8pet av dagen?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att smyga iv\u00e4g ett fl\u00f6rtigt meddelande under dagen?", "pl": "Kto z nas jest bardziej sk\u0142onny do wys\u0142ania flirciarskiej wiadomo\u015bci w ci\u0105gu dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to sneak a flirty message during the day?';
UPDATE questions
SET translations = '{"en": "Which of us would start a \u201cfive minutes\u201d moment that turns into an hour?", "da": "Hvem af os ville starte et \"fem minutter\"-\u00f8jeblik, der bliver til en time?", "de": "Wer von uns w\u00fcrde ein \u201ef\u00fcnf Minuten\u201c-Moment beginnen, das zu einer Stunde wird?", "es": "\u00bfQui\u00e9n de los dos empezar\u00eda un \u201cmomento de cinco minutos\u201d que se convierte en una hora?", "pt": "Quem de n\u00f3s come\u00e7aria um \u201cmomento de cinco minutos\u201d que se torna numa hora?", "ro": "Cine dintre noi ar \u00eencepe un \u201emoment de cinci minute\u201d care devine o or\u0103?", "fr": "Lequel de nous deux commencerait un \u201cmoment de cinq minutes\u201d qui dure une heure ?", "it": "Quale di noi inizierebbe un momento di \"cinque minuti\" che si trasforma in un''ora?", "fi": "Kumpi meist\u00e4 aloittaisi \"viiden minuutin\" hetken, joka muuttuu tunniksi?", "nl": "Wie van ons zou een \"vijf minuten\" moment beginnen dat uitloopt op een uur?", "no": "Hvem av oss ville starte et \"fem minutter\" \u00f8yeblikk som blir til en time?", "sv": "Vilken av oss skulle starta ett \"fem minuter\"-\u00f6gonblick som blir en timme?", "pl": "Kto z nas rozpocz\u0105\u0142by \u201epi\u0119ciominutowy\u201d moment, kt\u00f3ry przerodzi\u0142by si\u0119 w godzin\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us would start a “five minutes” moment that turns into an hour?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite way for me to show that I\u2019m craving you?", "da": "Hvad er din yndlingsm\u00e5de for mig at vise, at jeg higer efter dig?", "de": "Wie magst du es am liebsten, wenn ich dir zeige, dass ich dich begehre?", "es": "\u00bfCu\u00e1l es tu forma favorita de mostrarme que me deseas?", "pt": "Qual \u00e9 a tua forma favorita de me mostrar que me desejas?", "ro": "Care este modul t\u0103u preferat de a-mi ar\u0103ta c\u0103 m\u0103 dore\u0219ti?", "fr": "Quelle est ta fa\u00e7on pr\u00e9f\u00e9r\u00e9e de me montrer que tu me d\u00e9sires ?", "it": "Qual \u00e8 il tuo modo preferito per farmi capire che hai voglia di me?", "fi": "Mik\u00e4 on suosikkitapasi, jolla voisin n\u00e4ytt\u00e4\u00e4, ett\u00e4 kaipaan sinua?", "nl": "Wat is jouw favoriete manier waarop ik kan laten zien dat ik naar je verlang?", "no": "Hva er din favorittm\u00e5te for meg \u00e5 vise at jeg lengter etter deg?", "sv": "Vad \u00e4r ditt favorit s\u00e4tt f\u00f6r mig att visa att jag l\u00e4ngtar efter dig?", "pl": "Jaki jest tw\u00f3j ulubiony spos\u00f3b, w jaki mog\u0119 pokaza\u0107, \u017ce ci\u0119 pragn\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite way for me to show that I’m craving you?';
UPDATE questions
SET translations = '{"en": "How important is eye contact for you when we\u2019re close?", "da": "Hvor vigtig er \u00f8jenkontakt for dig, n\u00e5r vi er t\u00e6tte?", "de": "Wie wichtig ist dir Augenkontakt, wenn wir uns nah sind?", "es": "\u00bfQu\u00e9 tan importante es el contacto visual para ti cuando estamos cerca?", "pt": "Qu\u00e3o importante \u00e9 o contacto visual para ti quando estamos juntos?", "ro": "C\u00e2t de important este contactul vizual pentru tine c\u00e2nd suntem aproape?", "fr": "Quelle importance a le contact visuel pour toi quand on est proches ?", "it": "Quanto \u00e8 importante per te il contatto visivo quando siamo vicini?", "fi": "Kuinka t\u00e4rke\u00e4\u00e4 silm\u00e4kontakti on sinulle, kun olemme l\u00e4hell\u00e4?", "nl": "Hoe belangrijk is oogcontact voor jou als we dichtbij zijn?", "no": "Hvor viktig er \u00f8yekontakt for deg n\u00e5r vi er n\u00e6re?", "sv": "Hur viktigt \u00e4r \u00f6gonkontakt f\u00f6r dig n\u00e4r vi \u00e4r n\u00e4ra?", "pl": "Jak wa\u017cny jest dla ciebie kontakt wzrokowy, gdy jeste\u015bmy blisko?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How important is eye contact for you when we’re close?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite type of forplay?", "da": "Hvad er din yndlingsform for leg?", "de": "Was ist deine Lieblingsform des Spiels?", "es": "\u00bfCu\u00e1l es tu tipo favorito de juego?", "pt": "Qual \u00e9 o teu tipo favorito de jogo?", "ro": "Care este tipul t\u0103u preferat de joc?", "fr": "Quel est ton type de jeu pr\u00e9f\u00e9r\u00e9 ?", "it": "Qual \u00e8 il tuo tipo di preliminari preferito?", "fi": "Mik\u00e4 on lempityyppisi esileikiss\u00e4?", "nl": "Wat is jouw favoriete soort voorspel?", "no": "Hva er din favoritt type forspill?", "sv": "Vad \u00e4r din favorittyp av f\u00f6rspel?", "pl": "Jaki jest tw\u00f3j ulubiony rodzaj gry wst\u0119pnej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite type of forplay?';
UPDATE questions
SET translations = '{"en": "What does \u201cexperience\u201d mean to you in bed \u2014 skill, confidence, curiosity?", "da": "Hvad betyder \"erfaring\" for dig i sengen \u2013 f\u00e6rdigheder, selvtillid, nysgerrighed?", "de": "Was bedeutet \u201eErfahrung\u201c f\u00fcr dich im Bett \u2013 K\u00f6nnen, Selbstvertrauen, Neugier?", "es": "\u00bfQu\u00e9 significa \u201cexperiencia\u201d para ti en la cama: habilidad, confianza o curiosidad?", "pt": "O que significa \u201cexperi\u00eancia\u201d para ti na cama \u2013 habilidade, confian\u00e7a ou curiosidade?", "ro": "Ce \u00eenseamn\u0103 \u201eexperien\u021b\u0103\u201d pentru tine \u00een pat \u2013 abilit\u0103\u021bi, \u00eencredere sau curiozitate?", "fr": "Que signifie \u00ab exp\u00e9rience \u00bb pour toi au lit \u2013 comp\u00e9tence, confiance ou curiosit\u00e9 ?", "it": "Cosa significa per te \"esperienza\" a letto \u2014 abilit\u00e0, fiducia, curiosit\u00e0?", "fi": "Mit\u00e4 \"kokemus\" merkitsee sinulle s\u00e4ngyss\u00e4 \u2014 taitoa, itseluottamusta, uteliaisuutta?", "nl": "Wat betekent \"ervaring\" voor jou in bed \u2014 vaardigheid, zelfvertrouwen, nieuwsgierigheid?", "no": "Hva betyr \"erfaring\" for deg i sengen \u2014 ferdigheter, selvtillit, nysgjerrighet?", "sv": "Vad betyder \"erfarenhet\" f\u00f6r dig i s\u00e4ngen \u2014 skicklighet, sj\u00e4lvf\u00f6rtroende, nyfikenhet?", "pl": "Co dla ciebie oznacza \u201edo\u015bwiadczenie\u201d w \u0142\u00f3\u017cku \u2014 umiej\u0119tno\u015b\u0107, pewno\u015b\u0107 siebie, ciekawo\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What does “experience” mean to you in bed — skill, confidence, curiosity?';
UPDATE questions
SET translations = '{"en": "Have you ever felt shy asking for what you want?", "da": "Har du nogensinde f\u00f8lt dig genert over at sp\u00f8rge om det, du vil have?", "de": "Hast du dich jemals gesch\u00e4mt, nach dem zu fragen, was du willst?", "es": "\u00bfAlguna vez te dio verg\u00fcenza pedir lo que quer\u00edas?", "pt": "Alguma vez tiveste vergonha de pedir o que querias?", "ro": "\u021ai-a fost vreodat\u0103 ru\u0219ine s\u0103 ceri ce vrei?", "fr": "As-tu d\u00e9j\u00e0 eu honte de demander ce que tu voulais ?", "it": "Hai mai provato timidezza nel chiedere ci\u00f2 che desideri?", "fi": "Oletko koskaan tuntenut ujoutta pyyt\u00e4ess\u00e4si sit\u00e4, mit\u00e4 haluat?", "nl": "Heb je ooit verlegen gevoeld om te vragen wat je wilt?", "no": "Har du noen gang f\u00f8lt deg sjenert n\u00e5r du skal be om det du \u00f8nsker?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig blyg f\u00f6r att be om det du vill ha?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 nie\u015bmia\u0142y, prosz\u0105c o to, czego chcesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever felt shy asking for what you want?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you\u2019d love to do with me that you\u2019ve never dared to mention before?", "da": "Hvad er \u00e9n ting, du gerne vil lave med mig, som du aldrig har turdet n\u00e6vne f\u00f8r?", "de": "Was ist eine Sache, die du gerne mit mir tun w\u00fcrdest, dich aber nie getraut hast zu sagen?", "es": "\u00bfQu\u00e9 cosa te gustar\u00eda hacer conmigo pero nunca te atreviste a decirlo?", "pt": "O que gostarias de fazer comigo mas nunca tiveste coragem de dizer?", "ro": "Ce \u021bi-ar pl\u0103cea s\u0103 faci cu mine, dar nu ai avut curajul s\u0103 spui?", "fr": "Qu\u2019aimerais-tu faire avec moi que tu n\u2019as jamais os\u00e9 mentionner ?", "it": "Qual \u00e8 una cosa che ti piacerebbe fare con me e che non hai mai osato menzionare prima?", "fi": "Mik\u00e4 on yksi asia, jonka haluaisit tehd\u00e4 kanssani, mutta et ole koskaan rohjennut mainita aiemmin?", "nl": "Wat is \u00e9\u00e9n ding dat je graag met mij zou willen doen, maar dat je nog nooit durfde te noemen?", "no": "Hva er \u00e9n ting du gjerne ville gjort med meg som du aldri har v\u00e5get \u00e5 nevne f\u00f8r?", "sv": "Vad \u00e4r en sak du skulle \u00e4lska att g\u00f6ra med mig som du aldrig v\u00e5gat n\u00e4mna f\u00f6rut?", "pl": "Co\u015b, co chcia\u0142by\u015b zrobi\u0107 ze mn\u0105, a nigdy wcze\u015bniej nie mia\u0142e\u015b odwagi o tym wspomnie\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one thing you’d love to do with me that you’ve never dared to mention before?';
UPDATE questions
SET translations = '{"en": "Is there a side of you, I still haven\u2019t unlocked yet?", "da": "Er der en side af dig, jeg stadig ikke har l\u00e5st op for endnu?", "de": "Gibt es eine Seite von dir, die ich noch nicht entdeckt habe?", "es": "\u00bfHay un lado tuyo que a\u00fan no he descubierto?", "pt": "H\u00e1 um lado teu que eu ainda n\u00e3o descobri?", "ro": "Exist\u0103 o parte din tine pe care nu am descoperit-o \u00eenc\u0103?", "fr": "Y a-t-il un c\u00f4t\u00e9 de toi que je n\u2019ai pas encore d\u00e9couvert ?", "it": "C''\u00e8 un lato di te che non ho ancora sbloccato?", "fi": "Onko sinussa viel\u00e4 puoli, jonka en ole viel\u00e4 avannut?", "nl": "Is er een kant van jou die ik nog niet heb ontdekt?", "no": "Er det en side av deg jeg fortsatt ikke har l\u00e5st opp?", "sv": "Finns det en sida av dig som jag fortfarande inte har l\u00e5st upp?", "pl": "Czy jest jaka\u015b strona ciebie, kt\u00f3rej jeszcze nie odkry\u0142em?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is there a side of you, I still haven’t unlocked yet?';
UPDATE questions
SET translations = '{"en": "Which desire of yours still feels \u201coff-limits,\u201d even though it turns you on?", "da": "Hvilket af dine beg\u00e6r f\u00f8les stadig \"forbudt\", selvom det t\u00e6nder dig?", "de": "Welche deiner Begierden f\u00fchlt sich immer noch \u201everboten\u201c an, obwohl sie dich erregt?", "es": "\u00bfCu\u00e1l de tus deseos a\u00fan se siente \u201cprohibido\u201d aunque te excite?", "pt": "Qual dos teus desejos ainda te parece \u201cproibido\u201d, mesmo que te excite?", "ro": "Care dintre dorin\u021bele tale \u00eenc\u0103 \u021bi se pare \u201einterzis\u0103\u201d, de\u0219i te excit\u0103?", "fr": "Lequel de tes d\u00e9sirs te semble encore \u00ab interdit \u00bb m\u00eame s\u2019il t\u2019excite ?", "it": "Quale tuo desiderio ti sembra ancora \"vietato\", anche se ti eccita?", "fi": "Mik\u00e4 halusi tuntuu edelleen \"kielletylt\u00e4\", vaikka se innostaa sinua?", "nl": "Welke wens van jou voelt nog steeds \"verboden,\" ook al maakt het je opgewonden?", "no": "Hvilket \u00f8nske har du som fortsatt f\u00f8les \"utenfor rekkevidde,\" selv om det tenner deg?", "sv": "Vilken \u00f6nskan har du som fortfarande k\u00e4nns \"utanf\u00f6r gr\u00e4nserna,\" \u00e4ven om den t\u00e4nder dig?", "pl": "Kt\u00f3re z twoich pragnie\u0144 wci\u0105\u017c wydaje si\u0119 \"niedost\u0119pne\", mimo \u017ce ci\u0119 podnieca?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which desire of yours still feels “off-limits,” even though it turns you on?';
UPDATE questions
SET translations = '{"en": "What makes a moment feel deliciously wrong but impossible to resist?", "da": "Hvad f\u00e5r et \u00f8jeblik til at f\u00f8les dejligt forkert, men umuligt at modst\u00e5?", "de": "Was l\u00e4sst einen Moment sch\u00f6n falsch, aber unwiderstehlich f\u00fchlen?", "es": "\u00bfQu\u00e9 hace que un momento se sienta deliciosamente incorrecto pero imposible de resistir?", "pt": "O que faz um momento parecer deliciosamente errado, mas imposs\u00edvel de resistir?", "ro": "Ce face un moment s\u0103 se simt\u0103 pl\u0103cut gre\u0219it, dar irezistibil?", "fr": "Qu\u2019est-ce qui rend un moment agr\u00e9ablement interdit mais impossible \u00e0 r\u00e9sister ?", "it": "Cosa rende un momento deliziosamente sbagliato ma impossibile da resistere?", "fi": "Mik\u00e4 tekee hetkest\u00e4 herkullisesti v\u00e4\u00e4r\u00e4n mutta mahdottoman vastustaa?", "nl": "Wat maakt een moment heerlijk verkeerd maar onmogelijk om te weerstaan?", "no": "Hva gj\u00f8r et \u00f8yeblikk deilig feil, men umulig \u00e5 motst\u00e5?", "sv": "Vad g\u00f6r att ett \u00f6gonblick k\u00e4nns h\u00e4rligt fel men om\u00f6jligt att motst\u00e5?", "pl": "Co sprawia, \u017ce chwila wydaje si\u0119 pysznie z\u0142a, ale niemo\u017cliwa do odrzucenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What makes a moment feel deliciously wrong but impossible to resist?';
UPDATE questions
SET translations = '{"en": "What kind of secret between us would you want to keep forever?", "da": "Hvilken slags hemmelighed mellem os ville du gerne beholde for evigt?", "de": "Welche Art von Geheimnis zwischen uns w\u00fcrdest du gerne f\u00fcr immer behalten?", "es": "\u00bfQu\u00e9 tipo de secreto entre nosotros te gustar\u00eda guardar para siempre?", "pt": "Que tipo de segredo entre n\u00f3s gostarias de guardar para sempre?", "ro": "Ce fel de secret \u00eentre noi ai vrea s\u0103 p\u0103strezi pentru totdeauna?", "fr": "Quel genre de secret entre nous aimerais-tu garder pour toujours ?", "it": "Che tipo di segreto tra di noi vorresti tenere per sempre?", "fi": "Mink\u00e4laista salaisuutta meid\u00e4n v\u00e4lill\u00e4mme haluaisit pit\u00e4\u00e4 ikuisesti?", "nl": "Welke soort geheim tussen ons zou je voor altijd willen bewaren?", "no": "Hvilken type hemmelighet mellom oss ville du \u00f8nsket \u00e5 beholde for alltid?", "sv": "Vilken sorts hemlighet mellan oss skulle du vilja beh\u00e5lla f\u00f6r alltid?", "pl": "Jak\u0105 tajemnic\u0119 mi\u0119dzy nami chcia\u0142by\u015b zachowa\u0107 na zawsze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of secret between us would you want to keep forever?';
UPDATE questions
SET translations = '{"en": "What\u2019s the first thing your eyes go to when I start undressing?", "da": "Hvad er det f\u00f8rste, dine \u00f8jne g\u00e5r efter, n\u00e5r jeg begynder at kl\u00e6de mig af?", "de": "Wohin gehen deine Augen zuerst, wenn ich beginne, mich auszuziehen?", "es": "\u00bfA d\u00f3nde van tus ojos primero cuando empiezo a desnudarme?", "pt": "Para onde v\u00e3o os teus olhos primeiro quando eu come\u00e7o a despir-me?", "ro": "Unde se uit\u0103 ochii t\u0103i prima dat\u0103 c\u00e2nd \u00eencep s\u0103 m\u0103 dezbrac?", "fr": "O\u00f9 vont tes yeux en premier quand je commence \u00e0 me d\u00e9shabiller ?", "it": "Qual \u00e8 la prima cosa su cui i tuoi occhi si posano quando inizio a spogliarmi?", "fi": "Mik\u00e4 on ensimm\u00e4inen asia, johon katseesi kiinnittyy, kun alan riisuutua?", "nl": "Wat is het eerste waar je ogen naartoe gaan als ik begin me uit te kleden?", "no": "Hva er det f\u00f8rste blikket ditt g\u00e5r til n\u00e5r jeg begynner \u00e5 kle av meg?", "sv": "Vad \u00e4r det f\u00f6rsta dina \u00f6gon g\u00e5r till n\u00e4r jag b\u00f6rjar kl\u00e4 av mig?", "pl": "Na co twoje oczy zwracaj\u0105 uwag\u0119, gdy zaczynam si\u0119 rozbiera\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s the first thing your eyes go to when I start undressing?';
UPDATE questions
SET translations = '{"en": "Which flavor would you want to taste on my lips?", "da": "Hvilken smag ville du gerne smage p\u00e5 mine l\u00e6ber?", "de": "Welchen Geschmack w\u00fcrdest du gerne auf meinen Lippen schmecken?", "es": "\u00bfA qu\u00e9 sabor te gustar\u00eda probar en mis labios?", "pt": "Que sabor gostarias de provar nos meus l\u00e1bios?", "ro": "Ce gust \u021bi-ar pl\u0103cea s\u0103 sim\u021bi pe buzele mele?", "fr": "Quelle saveur aimerais-tu go\u00fbter sur mes l\u00e8vres ?", "it": "Quale sapore vorresti assaporare sulle mie labbra?", "fi": "Mink\u00e4 maun haluaisit maistaa huuliltani?", "nl": "Welke smaak zou je willen proeven op mijn lippen?", "no": "Hvilken smak ville du \u00f8nsket \u00e5 smake p\u00e5 leppene mine?", "sv": "Vilken smak skulle du vilja smaka p\u00e5 mina l\u00e4ppar?", "pl": "Jakiego smaku chcia\u0142by\u015b spr\u00f3bowa\u0107 na moich ustach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which flavor would you want to taste on my lips?';
UPDATE questions
SET translations = '{"en": "What do you wish I\u2019d do more often during foreplay?", "da": "Hvad ville du \u00f8nske, jeg gjorde oftere under forspil?", "de": "Was w\u00fcrdest du dir w\u00fcnschen, dass ich beim Vorspiel \u00f6fter tue?", "es": "\u00bfQu\u00e9 te gustar\u00eda que hiciera m\u00e1s a menudo durante los juegos previos?", "pt": "O que gostarias que eu fizesse mais vezes durante as preliminares?", "ro": "Ce \u021bi-ai dori s\u0103 fac mai des \u00een timpul preludiului?", "fr": "Que voudrais-tu que je fasse plus souvent pendant les pr\u00e9liminaires ?", "it": "Cosa vorresti che facessi pi\u00f9 spesso durante il preliminare?", "fi": "Mit\u00e4 toivoisit minun tekev\u00e4n useammin esileikin aikana?", "nl": "Wat zou je willen dat ik vaker doe tijdens de voorspel?", "no": "Hva \u00f8nsker du at jeg skulle gj\u00f8re oftere under forspill?", "sv": "Vad \u00f6nskar du att jag gjorde oftare under f\u00f6rspelet?", "pl": "Co chcia\u0142by\u015b, \u017cebym robi\u0142 cz\u0119\u015bciej podczas wst\u0119pnej gry?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What do you wish I’d do more often during foreplay?';
UPDATE questions
SET translations = '{"en": "What kind of lighting or atmosphere turns you on the most?", "da": "Hvilken slags belysning eller atmosf\u00e6re t\u00e6nder dig mest?", "de": "Welche Art von Licht oder Atmosph\u00e4re erregt dich am meisten?", "es": "\u00bfQu\u00e9 tipo de iluminaci\u00f3n o ambiente te excita m\u00e1s?", "pt": "Que tipo de ilumina\u00e7\u00e3o ou ambiente mais te excita?", "ro": "Ce fel de lumin\u0103 sau atmosfer\u0103 te excit\u0103 cel mai mult?", "fr": "Quel type d\u2019\u00e9clairage ou d\u2019ambiance t\u2019excite le plus ?", "it": "Che tipo di illuminazione o atmosfera ti eccita di pi\u00f9?", "fi": "Mink\u00e4lainen valaistus tai tunnelma vieh\u00e4tt\u00e4\u00e4 sinua eniten?", "nl": "Wat voor soort verlichting of sfeer maakt je het meest opgewonden?", "no": "Hvilken type belysning eller atmosf\u00e6re tenner deg mest?", "sv": "Vilken typ av belysning eller atmosf\u00e4r t\u00e4nder dig mest?", "pl": "Jakiego rodzaju o\u015bwietlenie lub atmosfera najbardziej ci\u0119 podnieca?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of lighting or atmosphere turns you on the most?';
UPDATE questions
SET translations = '{"en": "How do you like me to show you that I\u2019m in the mood?", "da": "Hvordan kan du lide, at jeg viser dig, at jeg er i hum\u00f8r til det?", "de": "Wie magst du es, wenn ich dir zeige, dass ich in Stimmung bin?", "es": "\u00bfC\u00f3mo te gusta que te muestre que estoy de humor?", "pt": "Como gostas que eu te mostre que estou com vontade?", "ro": "Cum \u00ee\u021bi place s\u0103-\u021bi ar\u0103t c\u0103 sunt \u00een dispozi\u021bia potrivit\u0103?", "fr": "Comment aimes-tu que je te montre que j\u2019en ai envie ?", "it": "Come ti piace che ti faccia capire che sono dell''umore giusto?", "fi": "Miten haluaisit, ett\u00e4 n\u00e4yt\u00e4n sinulle, ett\u00e4 olen tunnelmassa?", "nl": "Hoe wil je dat ik je laat zien dat ik in de stemming ben?", "no": "Hvordan vil du at jeg skal vise deg at jeg er i hum\u00f8r?", "sv": "Hur vill du att jag ska visa dig att jag \u00e4r p\u00e5 hum\u00f6r?", "pl": "Jak chcia\u0142by\u015b, \u017cebym pokaza\u0142a ci, \u017ce mam nastr\u00f3j?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you like me to show you that I’m in the mood?';
UPDATE questions
SET translations = '{"en": "Do you like when I hold your face or your hips?", "da": "Kan du lide, n\u00e5r jeg holder om dit ansigt eller dine hofter?", "de": "Magst du es, wenn ich dein Gesicht oder deine H\u00fcften halte?", "es": "\u00bfTe gusta cuando te agarro la cara o las caderas?", "pt": "Gostas quando eu te agarro o rosto ou as ancas?", "ro": "\u00ce\u021bi place c\u00e2nd \u00ee\u021bi \u021bin fa\u021ba sau \u0219oldurile?", "fr": "Aimes-tu quand je tiens ton visage ou tes hanches ?", "it": "Ti piace quando ti tengo la faccia o i fianchi?", "fi": "Pid\u00e4tk\u00f6 siit\u00e4, kun pid\u00e4n kasvoistasi vai lanteistasi?", "nl": "Vind je het leuk als ik je gezicht of je heupen vasthoud?", "no": "Liker du at jeg holder ansiktet ditt eller hoftene dine?", "sv": "Tycker du om n\u00e4r jag h\u00e5ller ditt ansikte eller dina h\u00f6fter?", "pl": "Czy lubisz, gdy trzymam ci\u0119 za twarz czy za biodra?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you like when I hold your face or your hips?';
UPDATE questions
SET translations = '{"en": "What\u2019s your personal definition of \u201cseductive\u201d?", "da": "Hvad er din personlige definition af \"forf\u00f8rende\"?", "de": "Was ist deine pers\u00f6nliche Definition von \u201everf\u00fchrerisch\u201c?", "es": "\u00bfCu\u00e1l es tu definici\u00f3n personal de \u201cseductor/a\u201d?", "pt": "Qual \u00e9 a tua defini\u00e7\u00e3o pessoal de \u201csedutor/a\u201d?", "ro": "Care este defini\u021bia ta personal\u0103 a \u201eseduc\u021biei\u201d?", "fr": "Quelle est ta d\u00e9finition personnelle de \u00ab s\u00e9duisant(e) \u00bb ?", "it": "Qual \u00e8 la tua definizione personale di \"seducente\"?", "fi": "Mik\u00e4 on henkil\u00f6kohtainen m\u00e4\u00e4ritelm\u00e4si \"viettelev\u00e4lle\"?", "nl": "Wat is jouw persoonlijke definitie van \"verleidelijk\"?", "no": "Hva er din personlige definisjon av \"forf\u00f8rende\"?", "sv": "Vad \u00e4r din personliga definition av \"f\u00f6rf\u00f6risk\"?", "pl": "Jakie jest twoje osobiste zdefiniowanie \u201euwodzicielskiego\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your personal definition of “seductive”?';
UPDATE questions
SET translations = '{"en": "How do you feel about filming or photographing intimate moments purely for ourselves?", "da": "Hvad synes du om at filme eller fotografere intime \u00f8jeblikke udelukkende for os selv?", "de": "Was h\u00e4ltst du davon, intime Momente nur f\u00fcr uns zu filmen oder zu fotografieren?", "es": "\u00bfQu\u00e9 opinas de grabar o fotografiar momentos \u00edntimos solo para nosotros?", "pt": "O que achas de filmar ou fotografar momentos \u00edntimos apenas para n\u00f3s?", "ro": "Ce p\u0103rere ai despre a filma sau fotografia momente intime doar pentru noi?", "fr": "Que penses-tu de filmer ou photographier des moments intimes juste pour nous ?", "it": "Cosa ne pensi di filmare o fotografare momenti intimi solo per noi stessi?", "fi": "Milt\u00e4 sinusta tuntuu, kun kuvaamme tai valokuvaamme intiimej\u00e4 hetki\u00e4 vain itsellemme?", "nl": "Hoe voel je je over het filmen of fotograferen van intieme momenten puur voor onszelf?", "no": "Hvordan f\u00f8ler du om \u00e5 filme eller ta bilder av intime \u00f8yeblikk kun for oss selv?", "sv": "Hur k\u00e4nner du f\u00f6r att filma eller fotografera intima stunder enbart f\u00f6r oss sj\u00e4lva?", "pl": "Jak si\u0119 czujesz w kwestii filmowania lub fotografowania intymnych moment\u00f3w tylko dla nas samych?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about filming or photographing intimate moments purely for ourselves?';
UPDATE questions
SET translations = '{"en": "If someone wanted to learn exactly how to please you, what\u2019s the first thing they should pay attention to?", "da": "Hvis nogen ville l\u00e6re pr\u00e6cis, hvordan de kunne behage dig, hvad er s\u00e5 det f\u00f8rste, de skulle v\u00e6re opm\u00e6rksomme p\u00e5?", "de": "Wenn jemand genau lernen wollte, wie man dich befriedigt \u2013 worauf sollte er als Erstes achten?", "es": "Si alguien quisiera aprender exactamente c\u00f3mo complacerte, \u00bfen qu\u00e9 deber\u00eda fijarse primero?", "pt": "Se algu\u00e9m quisesse aprender exatamente como te agradar, em que deveria prestar aten\u00e7\u00e3o primeiro?", "ro": "Dac\u0103 cineva ar vrea s\u0103 \u00eenve\u021be exact cum s\u0103 te satisfac\u0103, la ce ar trebui s\u0103 fie atent(\u0103) mai \u00eent\u00e2i?", "fr": "Si quelqu\u2019un voulait apprendre exactement comment te plaire, \u00e0 quoi devrait-il pr\u00eater attention en premier ?", "it": "Se qualcuno volesse imparare esattamente come farti piacere, qual \u00e8 la prima cosa a cui dovrebbe prestare attenzione?", "fi": "Jos joku haluaisi oppia tarkalleen, miten miellytt\u00e4\u00e4 sinua, mik\u00e4 olisi ensimm\u00e4inen asia, johon heid\u00e4n tulisi kiinnitt\u00e4\u00e4 huomiota?", "nl": "Als iemand precies wilde leren hoe ze jou tevreden kunnen stellen, wat is dan het eerste waar ze op zouden moeten letten?", "no": "Hvis noen \u00f8nsket \u00e5 l\u00e6re n\u00f8yaktig hvordan de kan glede deg, hva er det f\u00f8rste de b\u00f8r legge merke til?", "sv": "Om n\u00e5gon ville l\u00e4ra sig exakt hur de kan behaga dig, vad \u00e4r det f\u00f6rsta de b\u00f6r l\u00e4gga m\u00e4rke till?", "pl": "Je\u015bli kto\u015b chcia\u0142by nauczy\u0107 si\u0119, jak ci\u0119 zadowoli\u0107, na co powinien zwr\u00f3ci\u0107 uwag\u0119 w pierwszej kolejno\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'If someone wanted to learn exactly how to please you, what’s the first thing they should pay attention to?';
UPDATE questions
SET translations = '{"en": "Is there anything you would want me to call you when we\u2019re having sex?", "da": "Er der noget, du gerne vil have, at jeg kalder dig, n\u00e5r vi har sex?", "de": "Gibt es etwas, wie ich dich nennen soll, wenn wir Sex haben?", "es": "\u00bfHay algo que te gustar\u00eda que te llame cuando tenemos sexo?", "pt": "H\u00e1 algo que gostarias que eu te chamasse quando fazemos sexo?", "ro": "Exist\u0103 ceva ce ai vrea s\u0103 te numesc c\u00e2nd facem dragoste?", "fr": "Y a-t-il quelque chose que tu aimerais que je t\u2019appelle quand on fait l\u2019amour ?", "it": "C''\u00e8 qualcosa con cui vorresti che ti chiamassi quando facciamo sesso?", "fi": "Onko jotain, mit\u00e4 haluaisit minun kutsuvan sinua, kun harrastamme seksi\u00e4?", "nl": "Is er iets wat je wilt dat ik je noem als we seks hebben?", "no": "Er det noe du vil at jeg skal kalle deg n\u00e5r vi har sex?", "sv": "Finns det n\u00e5got du skulle vilja att jag kallade dig n\u00e4r vi har sex?", "pl": "Czy jest co\u015b, co chcia\u0142by\u015b, \u017cebym nazywa\u0142 ci\u0119, gdy uprawiamy seks?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is there anything you would want me to call you when we’re having sex?';

-- Category: The Good Old Days Talks (75 questions)
UPDATE questions
SET translations = '{"en": "If we could swap ages for one day, what\u2019s the first thing you\u2019d do?", "da": "Hvis vi kunne bytte alder for en dag, hvad er det f\u00f8rste, du ville g\u00f8re?", "de": "Wenn wir f\u00fcr einen Tag das Alter tauschen k\u00f6nnten, was w\u00fcrdest du als Erstes tun?", "es": "Si pudi\u00e9ramos intercambiar edades por un d\u00eda, \u00bfqu\u00e9 ser\u00eda lo primero que har\u00edas?", "pt": "Se pud\u00e9ssemos trocar de idade por um dia, o que farias primeiro?", "ro": "Dac\u0103 am putea schimba v\u00e2rstele pentru o zi, care ar fi primul lucru pe care l-ai face?", "fr": "Si nous pouvions \u00e9changer nos \u00e2ges pour une journ\u00e9e, quelle serait la premi\u00e8re chose que tu ferais ?", "it": "Se potessimo scambiarci l''et\u00e0 per un giorno, qual \u00e8 la prima cosa che faresti?", "fi": "Jos voisimme vaihtaa ik\u00e4\u00e4mme p\u00e4iv\u00e4ksi, mik\u00e4 olisi ensimm\u00e4inen asia, jonka tekisit?", "nl": "Als we van leeftijd konden wisselen voor \u00e9\u00e9n dag, wat zou je dan als eerste doen?", "no": "Hvis vi kunne bytte alder i en dag, hva ville det f\u00f8rste du gjorde v\u00e6rt?", "sv": "Om vi kunde byta \u00e5lder f\u00f6r en dag, vad skulle du g\u00f6ra f\u00f6rst?", "pl": "Gdyby\u015bmy mogli zamieni\u0107 si\u0119 wiekiem na jeden dzie\u0144, co by\u015b zrobi\u0142 jako pierwsze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'If we could swap ages for one day, what’s the first thing you’d do?';