INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who had the weirdest haircut phase?", "da": "Hvem havde den mærkeligste frisurefase?", "de": "Wer hatte die seltsamste Frisurenphase?", "es": "¿Quién tuvo la fase de peinado más rara?", "pt": "Quem teve a fase de corte de cabelo mais estranha?", "ro": "Cine a avut cea mai ciudată fază de coafură?", "fr": "Qui a eu la phase de coiffure la plus étrange ?", "it": "Chi ha avuto la fase di taglio di capelli più strana?", "fi": "Kellä oli oudoimmat hiustyyli-vaiheet?", "nl": "Wie had de vreemdste kapselperiode?", "no": "Hvem hadde den rareste frisyrefasen?", "sv": "Vem hade den konstigaste frisyrfasen?", "pl": "Kto miał najdziwniejszą fazę fryzury?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to take <5000 photos on vacation?", "da": "Hvem tager sandsynligvis <5000 billeder på ferien?", "de": "Wer macht wahrscheinlich <5000 Fotos im Urlaub?", "es": "¿Quién es más probable que tome <5000 fotos en vacaciones?", "pt": "Quem é mais provável tirar <5000 fotos nas férias?", "ro": "Cine e cel mai probabil să facă <5000 de poze în vacanță?", "fr": "Qui est le plus susceptible de prendre <5000 photos en vacances ?", "it": "Chi è più probabile che scatti meno di 5000 foto in vacanza?", "fi": "Kuka todennäköisesti ottaa alle 5000 valokuvaa lomalla?", "nl": "Wie is het meest waarschijnlijk om <5000 foto''s op vakantie te maken?", "no": "Hvem er mest sannsynlig å ta <5000 bilder på ferie?", "sv": "Vem är mest benägen att ta <5000 bilder på semestern?", "pl": "Kto jest najbardziej prawdopodobny, aby zrobić mniej niż 5000 zdjęć na wakacjach?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to get sunburned first?", "da": "Hvem bliver først solskoldet?", "de": "Wer bekommt als Erster einen Sonnenbrand?", "es": "¿Quién es más probable que se queme con el sol primero?", "pt": "Quem é mais provável a ficar com queimadura de sol primeiro?", "ro": "Cine se arde primul de la soare?", "fr": "Qui est le plus susceptible d attraper un coup de soleil en premier ?", "it": "Chi è più probabile che si scotta per primo?", "fi": "Kuka todennäköisesti saa auringonpolttaman ensimmäisenä?", "nl": "Wie is het meest waarschijnlijk om als eerste verbrand te raken door de zon?", "no": "Hvem er mest sannsynlig til å bli solbrent først?", "sv": "Vem är mest sannolikt att bli solbränd först?", "pl": "Kto najprawdopodobniej pierwszy się poparzy?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the loudest when telling a story?", "da": "Hvem råber højest, når de fortæller en historie?", "de": "Wer ist am lautesten, wenn er eine Geschichte erzählt?", "es": "¿Quién es el más ruidoso al contar una historia?", "pt": "Quem fala mais alto quando conta uma história?", "ro": "Cine vorbește cel mai tare când spune o poveste?", "fr": "Qui parle le plus fort en racontant une histoire ?", "it": "Chi è il più rumoroso quando racconta una storia?", "fi": "Kuka on äänekkäin kertoessaan tarinaa?", "nl": "Wie is de luidste als hij of zij een verhaal vertelt?", "no": "Hvem er den høyeste når de forteller en historie?", "sv": "Vem är den högsta när de berättar en historia?", "pl": "Kto jest najgłośniejszy, opowiadając historię?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s a family tradition that’s been around the longest?", "da": "Hvad er den ældste familietradition?", "de": "Was ist die älteste Familientradition?", "es": "¿Cuál es la tradición familiar más antigua?", "pt": "Qual é a tradição familiar mais antiga?", "ro": "Care este cea mai veche tradiție de familie?", "fr": "Quelle est la plus ancienne tradition familiale ?", "it": "Qual è una tradizione familiare che esiste da più tempo?", "fi": "Mikä on perheenne vanhin perinne?", "nl": "Wat is een familietraditie die al het langst bestaat?", "no": "Hva er en familietradisjon som har vart lengst?", "sv": "Vilken familjetradition har funnits längst?", "pl": "Jaka tradycja rodzinna istnieje najdłużej?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who do we all take after the most — personality-wise?", "da": "Hvem ligner vi mest personlighedsmæssigt?", "de": "Wem ähneln wir alle am meisten – vom Charakter her?", "es": "¿A quién nos parecemos más en personalidad?", "pt": "A quem mais nos parecemos em personalidade?", "ro": "Pe cine semănăm cel mai mult ca personalitate?", "fr": "À qui ressemblons-nous le plus niveau personnalité ?", "it": "Chi di noi assomiglia di più agli altri — per quanto riguarda la personalità?", "fi": "Keneen meistä me kaikki muistutamme eniten — luonteenpiirteiltään?", "nl": "Van wie lijken we allemaal het meest — qua persoonlijkheid?", "no": "Hvem av oss ligner mest på hverandre — når det gjelder personlighet?", "sv": "Vem liknar vi alla mest — när det kommer till personlighet?", "pl": "Kogo najbardziej przypominamy, jeśli chodzi o osobowość?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s a family recipe everyone loves?", "da": "Hvad er en familieopskrift, som alle elsker?", "de": "Was ist ein Familienrezept, das jeder liebt?", "es": "¿Cuál es una receta familiar que todos aman?", "pt": "Qual é uma receita de família que todos amam?", "ro": "Care este o rețetă de familie iubită de toți?", "fr": "Quelle est une recette familiale que tout le monde aime ?", "it": "Qual è una ricetta di famiglia che tutti amano?", "fi": "Mikä on perheresepti, josta kaikki pitävät?", "nl": "Wat is een familierecept waar iedereen dol op is?", "no": "Hva er en familieresept som alle elsker?", "sv": "Vilket är ett familjerecept som alla älskar?", "pl": "Jaka jest rodzinna receptura, którą wszyscy uwielbiają?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who cries first at movies — every single time?", "da": "Hvem græder først til film — hver eneste gang?", "de": "Wer weint als Erster bei Filmen – jedes Mal?", "es": "¿Quién llora primero en las películas — cada vez?", "pt": "Quem chora primeiro nos filmes — todas as vezes?", "ro": "Cine plânge primul la filme — de fiecare dată?", "fr": "Qui pleure en premier devant les films — à chaque fois ?", "it": "Chi piange per primo ai film — ogni singola volta?", "fi": "Kuka itkee ensimmäisenä elokuvissa — joka kerta?", "nl": "Wie huilt er als eerste bij films — elke keer weer?", "no": "Hvem gråter først på filmer — hver eneste gang?", "sv": "Vem gråter först på filmer — varje gång?", "pl": "Kto zawsze płacze pierwszy na filmach?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Is there a dish only one person in the family can make perfectly?", "da": "Er der en ret, som kun én i familien kan lave perfekt?", "de": "Gibt es ein Gericht, das nur eine Person in der Familie perfekt kann?", "es": "¿Hay un plato que solo una persona de la familia pueda hacer perfectamente?", "pt": "Há um prato que só uma pessoa da família faz perfeitamente?", "ro": "Există un fel de mâncare pe care doar o persoană din familie îl face perfect?", "fr": "Y a-t-il un plat que seule une personne dans la famille sait faire parfaitement ?", "it": "C''è un piatto che solo una persona nella famiglia sa fare perfettamente?", "fi": "Onko perheessä ruoka, jota vain yksi henkilö osaa tehdä täydellisesti?", "nl": "Is er een gerecht dat maar één persoon in de familie perfect kan maken?", "no": "Er det en rett som bare én person i familien kan lage perfekt?", "sv": "Finns det en rätt som bara en person i familjen kan laga perfekt?", "pl": "Czy jest danie, które tylko jedna osoba w rodzinie potrafi przygotować idealnie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in our ancestry would you love to interview?", "da": "Hvem fra vores aner ville du elske at interviewe?", "de": "Wen aus unserer Ahnenreihe würdest du gern interviewen?", "es": "¿A quién de nuestros antepasados te gustaría entrevistar?", "pt": "Quem dos nossos antepassados gostarias de entrevistar?", "ro": "Pe cine din strămoșii noștri ai vrea să intervievezi?", "fr": "Quel ancêtre aimerais-tu interviewer ?", "it": "Chi nella nostra genealogia ti piacerebbe intervistare?", "fi": "Kuka esi-isistämme haluaisit haastatella?", "nl": "Wie in onze voorouders zou je graag willen interviewen?", "no": "Hvem i vår forfedre ville du elsket å intervjue?", "sv": "Vem i vår släkt skulle du vilja intervjua?", "pl": "Kogo z naszej przeszłości chciałbyś przesłuchać?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to bring home a random animal?", "da": "Hvem tager sandsynligvis et tilfældigt dyr med hjem?", "de": "Wer bringt wahrscheinlich ein zufälliges Tier mit nach Hause?", "es": "¿Quién es más probable que lleve un animal aleatorio a casa?", "pt": "Quem é mais provável de trazer um animal aleatório para casa?", "ro": "Cine e cel mai probabil să aducă un animal întâmplător acasă?", "fr": "Qui est le plus susceptible de ramener un animal au hasard à la maison ?", "it": "Chi è più probabile che porti a casa un animale casuale?", "fi": "Kuka todennäköisesti tuo kotiin satunnaisen eläimen?", "nl": "Wie is het meest waarschijnlijk om een random dier mee naar huis te nemen?", "no": "Hvem er mest sannsynlig til å ta med seg et tilfeldig dyr hjem?", "sv": "Vem är mest benägen att ta hem ett random djur?", "pl": "Kto najprawdopodobniej przyniesie do domu przypadkowe zwierzę?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s a song our family always sings or plays together?", "da": "Hvilken sang synger eller spiller vores familie altid sammen?", "de": "Welches Lied singt oder spielt unsere Familie immer zusammen?", "es": "¿Qué canción canta o toca siempre nuestra familia juntos?", "pt": "Qual música nossa família sempre canta ou toca junta?", "ro": "Ce melodie cântă mereu familia noastră împreună?", "fr": "Quelle chanson notre famille chante ou joue toujours ensemble ?", "it": "Qual è una canzone che la nostra famiglia canta o suona sempre insieme?", "fi": "Mikä on laulu, jota perheemme aina laulaa tai soittaa yhdessä?", "nl": "Wat is een lied dat onze familie altijd samen zingt of speelt?", "no": "Hvilken sang synger eller spiller familien vår alltid sammen?", "sv": "Vilken låt sjunger eller spelar vår familj alltid tillsammans?", "pl": "Jaka jest piosenka, którą nasza rodzina zawsze śpiewa lub gra razem?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in the family tells the best stories?", "da": "Hvem i familien fortæller de bedste historier?", "de": "Wer in der Familie erzählt die besten Geschichten?", "es": "¿Quién cuenta las mejores historias en la familia?", "pt": "Quem na família conta as melhores histórias?", "ro": "Cine din familie spune cele mai bune povești?", "fr": "Qui dans la famille raconte les meilleures histoires ?", "it": "Chi in famiglia racconta le storie migliori?", "fi": "Kuka perheessä kertoo parhaat tarinat?", "nl": "Wie in de familie vertelt de beste verhalen?", "no": "Hvem i familien forteller de beste historiene?", "sv": "Vem i familjen berättar de bästa historierna?", "pl": "Kto w rodzinie opowiada najlepsze historie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to forget where they put their phone — again?", "da": "Hvem glemmer oftest, hvor de lagde deres telefon — igen?", "de": "Wer vergisst am ehesten, wo er sein Handy hingelegt hat – schon wieder?", "es": "¿Quién es más probable que olvide dónde dejó su teléfono, otra vez?", "pt": "Quem é mais provável de esquecer onde deixou o telefone — de novo?", "ro": "Cine uită mereu unde și-a pus telefonul — din nou?", "fr": "Qui oublie le plus souvent où il a mis son téléphone — encore ?", "it": "Chi è più probabile che dimentichi dove ha messo il telefono — di nuovo?", "fi": "Kuka todennäköisesti unohtaa, mihin hän laittoi puhelimensa — taas?", "nl": "Wie is het meest waarschijnlijk om weer te vergeten waar ze hun telefoon hebben neergelegd?", "no": "Hvem er mest sannsynlig til å glemme hvor de la telefonen sin — igjen?", "sv": "Vem är mest benägen att glömma var de lagt sin telefon — igen?", "pl": "Kto najprawdopodobniej znowu zapomni, gdzie położył swój telefon?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s a family saying or phrase everyone knows?", "da": "Hvad er et familiebegreb, som alle kender?", "de": "Welcher Familienspruch ist bei allen bekannt?", "es": "¿Cuál es una frase o dicho familiar que todos conocen?", "pt": "Qual é uma frase ou ditado familiar que todos conhecem?", "ro": "Care este o expresie de familie pe care toți o știu?", "fr": "Quelle est une expression de famille que tout le monde connaît ?", "it": "Qual è un detto o una frase di famiglia che tutti conoscono?", "fi": "Mikä on perhesanonta tai lause, jonka kaikki tuntevat?", "nl": "Wat is een gezegde of uitdrukking binnen de familie die iedereen kent?", "no": "Hva er et familieuttrykk eller en frase som alle kjenner?", "sv": "Vad är ett familjespråk eller en fras som alla känner till?", "pl": "Jakie jest znane powiedzenie lub fraza rodzinne, które wszyscy znają?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s best known for taking way too many selfies?", "da": "Hvem er kendt for at tage alt for mange selfies?", "de": "Wer ist bekannt dafür, viel zu viele Selfies zu machen?", "es": "¿Quién es conocido por tomar demasiados selfies?", "pt": "Quem é conhecido por tirar selfies demais?", "ro": "Cine e cunoscut că face prea multe selfie-uri?", "fr": "Qui est connu pour prendre beaucoup trop de selfies ?", "it": "Chi è il più conosciuto per scattare un numero eccessivo di selfie?", "fi": "Kuka tunnetaan parhaiten siitä, että ottaa aivan liian monta selfie-kuvaa?", "nl": "Wie staat het meest bekend om veel te veel selfies te nemen?", "no": "Hvem er best kjent for å ta altfor mange selfies?", "sv": "Vem är mest känd för att ta alldeles för många selfies?", "pl": "Kto jest najlepiej znany z robienia zbyt wielu selfie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the most competitive person here?", "da": "Hvem er den mest konkurrencemindede her?", "de": "Wer ist hier am wettkampffreudigsten?", "es": "¿Quién es la persona más competitiva aquí?", "pt": "Quem é a pessoa mais competitiva aqui?", "ro": "Cine este cea mai competitivă persoană de aici?", "fr": "Qui est la personne la plus compétitive ici ?", "it": "Chi è la persona più competitiva qui?", "fi": "Kuka on täällä kilpailuhenkisin henkilö?", "nl": "Wie is de meest competitieve persoon hier?", "no": "Hvem er den mest konkurransedyktige personen her?", "sv": "Vem är den mest tävlingsinriktade personen här?", "pl": "Kto jest najbardziej konkurencyjną osobą tutaj?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to exaggerate every story just a little?", "da": "Hvem overdriver altid historierne lidt?", "de": "Wer übertreibt jede Geschichte ein kleines bisschen?", "es": "¿Quién es más probable que exagere cada historia un poco?", "pt": "Quem é mais provável de exagerar um pouco cada história?", "ro": "Cine e cel mai probabil să exagereze puțin fiecare poveste?", "fr": "Qui exagère toujours un peu chaque histoire ?", "it": "Chi è più probabile che esageri ogni storia solo un po''?", "fi": "Kuka todennäköisesti liioittelee jokaista tarinaa hieman?", "nl": "Wie is het meest waarschijnlijk om elk verhaal net iets te overdrijven?", "no": "Hvem er mest sannsynlig til å overdrive hver historie bare litt?", "sv": "Vem är mest benägen att överdriva varje historia lite grann?", "pl": "Kto jest najbardziej skłonny do nieco przesadzania w każdej historii?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s the weirdest family rule we’ve ever had?", "da": "Hvad er den mærkeligste familielov, vi nogensinde har haft?", "de": "Was ist die seltsamste Familienregel, die wir je hatten?", "es": "¿Cuál es la regla familiar más rara que hemos tenido?", "pt": "Qual é a regra familiar mais estranha que já tivemos?", "ro": "Care este cea mai ciudată regulă de familie pe care am avut-o?", "fr": "Quelle est la règle familiale la plus étrange que nous ayons eue ?", "it": "Qual è stata la regola familiare più strana che abbiamo mai avuto?", "fi": "Mikä on oudoin perhesääntö, jota olemme koskaan pitäneet?", "nl": "Wat is de vreemdste gezinsregel die we ooit hebben gehad?", "no": "Hva er den merkeligste familien regelen vi noen gang har hatt?", "sv": "Vad är den konstigaste familjeregeln vi någonsin har haft?", "pl": "Jakie jest najdziwniejsze zasada rodzinna, jaką kiedykolwiek mieliśmy?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s best known for burning dinner?", "da": "Hvem er bedst kendt for at brænde maden på?", "de": "Wer ist bekannt dafür, das Abendessen anzubrennen?", "es": "¿Quién es conocido por quemar la cena?", "pt": "Quem é conhecido por queimar o jantar?", "ro": "Cine e cunoscut că arde cina?", "fr": "Qui est connu pour brûler le dîner ?", "it": "Chi è il più noto per bruciare la cena?", "fi": "Kuka on parhaiten tunnettu illallisen polttamisesta?", "nl": "Wie staat het meest bekend om het verbranden van het avondeten?", "no": "Hvem er best kjent for å brenne middagen?", "sv": "Vem är mest känd för att bränna middagen?", "pl": "Kto jest najbardziej znany z przypalania kolacji?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who would make the best (or worst) reality TV star in our family?", "da": "Hvem ville være den bedste (eller værste) realitystjerne i familien?", "de": "Wer wäre der beste (oder schlechteste) Reality-TV-Star in unserer Familie?", "es": "¿Quién sería la mejor (o peor) estrella de reality show en nuestra familia?", "pt": "Quem seria a melhor (ou pior) estrela de reality show na nossa família?", "ro": "Cine ar fi cea mai bună (sau cea mai proastă) vedetă de reality show din familia noastră?", "fr": "Qui ferait la meilleure (ou la pire) star de télé-réalité dans notre famille ?", "it": "Chi sarebbe il migliore (o il peggiore) star della realtà nella nostra famiglia?", "fi": "Kuka perheessämme olisi paras (tai huonoin) tosi-tv-tähti?", "nl": "Wie zou de beste (of slechtste) reality-tv-ster in onze familie zijn?", "no": "Hvem ville vært den beste (eller dårligste) reality-TV-stjernen i familien vår?", "sv": "Vem skulle bli den bästa (eller sämsta) reality-TV-stjärnan i vår familj?", "pl": "Kto byłby najlepszą (lub najgorszą) gwiazdą reality show w naszej rodzinie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in our family gives the best hugs?", "da": "Hvem i familien giver de bedste kram?", "de": "Wer in unserer Familie gibt die besten Umarmungen?", "es": "¿Quién da los mejores abrazos en la familia?", "pt": "Quem na nossa família dá os melhores abraços?", "ro": "Cine din familia noastră dă cele mai bune îmbrățișări?", "fr": "Qui dans notre famille fait les meilleurs câlins ?", "it": "Chi nella nostra famiglia dà i migliori abbracci?", "fi": "Kuka perheessämme antaa parhaat halaukset?", "nl": "Wie in onze familie geeft de beste knuffels?", "no": "Hvem i familien vår gir de beste klemene?", "sv": "Vem i vår familj ger de bästa kramarna?", "pl": "Kto w naszej rodzinie daje najlepsze uściski?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Which of us is most likely to hide snacks from the others?", "da": "Hvem gemmer sandsynligvis snacks fra de andre?", "de": "Wer von uns versteckt wahrscheinlich Snacks vor den anderen?", "es": "¿Quién de nosotros es más probable que esconda los bocadillos de los demás?", "pt": "Quem de nós é mais provável esconder lanches dos outros?", "ro": "Cine dintre noi ascunde gustări de ceilalți?", "fr": "Qui parmi nous cache probablement des snacks aux autres ?", "it": "Quale di noi è più probabile che nasconda snack agli altri?", "fi": "Kumpi meistä todennäköisimmin piilottaa herkkuja muilta?", "nl": "Wie van ons is het meest waarschijnlijk om snacks voor de anderen te verstoppen?", "no": "Hvem av oss er mest sannsynlig til å skjule snacks for de andre?", "sv": "Vilken av oss är mest benägen att gömma snacks från de andra?", "pl": "Kto z nas jest najbardziej skłonny chować przekąski przed innymi?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who always forgets everyone’s birthdays until the last minute?", "da": "Hvem glemmer altid alles fødselsdage indtil sidste øjeblik?", "de": "Wer vergisst immer alle Geburtstage bis zur letzten Minute?", "es": "¿Quién siempre olvida los cumpleaños de todos hasta el último minuto?", "pt": "Quem sempre esquece os aniversários de todos até o último minuto?", "ro": "Cine uită mereu zilele de naștere ale tuturor până în ultimul moment?", "fr": "Qui oublie toujours les anniversaires de tout le monde jusqu’à la dernière minute ?", "it": "Chi dimentica sempre i compleanni di tutti fino all''ultimo minuto?", "fi": "Kuka unohtaa aina kaikkien syntymäpäivät viime hetkellä?", "nl": "Wie vergeet altijd ieders verjaardag tot het laatste moment?", "no": "Hvem glemmer alltid alles bursdager til siste liten?", "sv": "Vem glömmer alltid allas födelsedagar tills i sista minuten?", "pl": "Kto zawsze zapomina o urodzinach wszystkich do ostatniej chwili?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to start laughing when they shouldn’t?", "da": "Hvem begynder sandsynligvis at grine, når de ikke burde?", "de": "Wer fängt wahrscheinlich an zu lachen, wenn er nicht sollte?", "es": "¿Quién es más probable que empiece a reír cuando no debería?", "pt": "Quem é mais provável de começar a rir quando não devia?", "ro": "Cine e cel mai probabil să înceapă să râdă când nu ar trebui?", "fr": "Qui est le plus susceptible de rire quand il ne faut pas ?", "it": "Chi è più probabile che inizi a ridere quando non dovrebbe?", "fi": "Kuka todennäköisesti alkaa nauraa, kun ei pitäisi?", "nl": "Wie is het meest waarschijnlijk om te beginnen met lachen wanneer dat niet gepast is?", "no": "Hvem er mest sannsynlig til å begynne å le når de ikke burde?", "sv": "Vem är mest benägen att börja skratta när de inte borde?", "pl": "Kto najprawdopodobniej zacznie się śmiać, kiedy nie powinien?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s the funniest thing that’s ever happened during dinner?", "da": "Hvad er det sjoveste, der nogensinde er sket under middagen?", "de": "Was ist das Lustigste, das jemals beim Abendessen passiert ist?", "es": "¿Cuál es la cosa más divertida que ha pasado durante la cena?", "pt": "Qual é a coisa mais engraçada que já aconteceu durante o jantar?", "ro": "Care e cel mai amuzant lucru care s-a întâmplat vreodată la cină?", "fr": "Quelle est la chose la plus drôle qui soit arrivée pendant le dîner ?", "it": "Qual è la cosa più divertente che ti sia mai successa durante la cena?", "fi": "Mikä on hauskin asia, joka on koskaan tapahtunut illallisen aikana?", "nl": "Wat is het grappigste dat ooit tijdens het diner is gebeurd?", "no": "Hva er det morsomste som noen gang har skjedd under middagen?", "sv": "Vad är det roligaste som någonsin har hänt under middagen?", "pl": "Co było najśmieszniejszego, co kiedykolwiek się zdarzyło podczas kolacji?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s best at cheering people up?", "da": "Hvem er bedst til at opmuntre folk?", "de": "Wer kann am besten andere aufmuntern?", "es": "¿Quién es el mejor animando a los demás?", "pt": "Quem é o melhor a animar as pessoas?", "ro": "Cine e cel mai bun la a înveseli oamenii?", "fr": "Qui est le meilleur pour remonter le moral des gens ?", "it": "Chi è il migliore nel tirare su il morale alle persone?", "fi": "Kuka on paras piristämään ihmisiä?", "nl": "Wie is het beste in het opvrolijken van mensen?", "no": "Hvem er best til å muntre folk opp?", "sv": "Vem är bäst på att muntra upp folk?", "pl": "Kto jest najlepszy w pocieszaniu ludzi?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who takes the longest to get ready for family outings?", "da": "Hvem bruger længst tid på at gøre sig klar til familieudflugter?", "de": "Wer braucht am längsten, um sich für Familienausflüge fertigzumachen?", "es": "¿Quién tarda más en prepararse para las salidas familiares?", "pt": "Quem demora mais para se arrumar para os passeios em família?", "ro": "Cine se pregătește cel mai mult pentru ieșirile în familie?", "fr": "Qui met le plus de temps à se préparer pour les sorties en famille ?", "it": "Chi impiega più tempo a prepararsi per le uscite di famiglia?", "fi": "Kuka vie eniten aikaa valmistautuakseen perheretkiin?", "nl": "Wie heeft de meeste tijd nodig om zich klaar te maken voor gezinsuitstapjes?", "no": "Hvem bruker lengst tid på å gjøre seg klar til familieturer?", "sv": "Vem tar längst tid på sig att göra sig redo för familjeutflykter?", "pl": "Kto potrzebuje najwięcej czasu, żeby się przygotować na rodzinne wyjścia?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in our family has the biggest collection of random stuff?", "da": "Hvem i vores familie har den største samling af tilfældige ting?", "de": "Wer in unserer Familie hat die größte Sammlung zufälliger Sachen?", "es": "¿Quién en nuestra familia tiene la colección más grande de cosas al azar?", "pt": "Quem na nossa família tem a maior coleção de coisas aleatórias?", "ro": "Cine din familia noastră are cea mai mare colecție de lucruri întâmplătoare?", "fr": "Qui dans notre famille a la plus grande collection d’objets aléatoires ?", "it": "Chi nella nostra famiglia ha la collezione più grande di cose strane?", "fi": "Kellä perheessämme on suurin kokoelma satunnaisia tavaroita?", "nl": "Wie in onze familie heeft de grootste verzameling van willekeurige spullen?", "no": "Hvem i familien vår har den største samlingen av tilfeldige ting?", "sv": "Vem i vår familj har den största samlingen av slumpmässiga saker?", "pl": "Kto w naszej rodzinie ma największą kolekcję różnych rzeczy?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s best at keeping secrets from Mom or Dad?", "da": "Hvem er bedst til at holde hemmeligheder for mor eller far?", "de": "Wer kann am besten Geheimnisse vor Mama oder Papa bewahren?", "es": "¿Quién es el mejor guardando secretos de mamá o papá?", "pt": "Quem é o melhor a guardar segredos da mãe ou do pai?", "ro": "Cine e cel mai bun la a ține secrete față de mama sau tata?", "fr": "Qui est le meilleur pour garder des secrets à maman ou papa ?", "it": "Chi è il migliore a tenere segreti, mamma o papà?", "fi": "Kuka on paras pitämään salaisuuksia äidiltä tai isältä?", "nl": "Wie is het beste in het geheimhouden van geheimen voor Mama of Papa?", "no": "Hvem er best til å holde hemmeligheter for mamma eller pappa?", "sv": "Vem är bäst på att hålla hemligheter från mamma eller pappa?", "pl": "Kto lepiej potrafi trzymać sekrety przed mamą lub tatą?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in our family is the best at fixing things (even if it’s with duct tape)?", "da": "Hvem i vores familie er bedst til at fikse ting (selv med gaffatape)?", "de": "Wer in unserer Familie ist am besten im Reparieren (auch mit Klebeband)?", "es": "¿Quién en nuestra familia es el mejor arreglando cosas (aunque sea con cinta adhesiva)?", "pt": "Quem na nossa família é o melhor a consertar coisas (mesmo com fita adesiva)?", "ro": "Cine din familia noastră e cel mai bun la reparat lucruri (chiar și cu bandă adezivă)?", "fr": "Qui dans notre famille est le meilleur pour réparer les choses (même avec du ruban adhésif) ?", "it": "Chi nella nostra famiglia è il migliore a riparare le cose (anche se è con il nastro adesivo)?", "fi": "Kuka perheessämme on paras korjaamaan asioita (vaikka se olisi teipillä)?", "nl": "Wie in onze familie is het beste in het repareren van dingen (zelfs als het met ducttape is)?", "no": "Hvem i familien vår er best til å fikse ting (selv om det er med duct tape)?", "sv": "Vem i vår familj är bäst på att laga saker (även om det är med silvertejp)?", "pl": "Kto w naszej rodzinie jest najlepszy w naprawianiu rzeczy (nawet jeśli to za pomocą taśmy klejącej)?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to blink in every photo?", "da": "Hvem blinker mest på billeder?", "de": "Wer blinzelt auf jedem Foto?", "es": "¿Quién es más probable que parpadee en todas las fotos?", "pt": "Quem é mais provável piscar em todas as fotos?", "ro": "Cine clipește cel mai des în poze?", "fr": "Qui cligne toujours des yeux sur les photos ?", "it": "Chi è più probabile che sbatti le palpebre in ogni foto?", "fi": "Kuka todennäköisesti räpäyttää silmiään jokaisessa valokuvassa?", "nl": "Wie is het meest waarschijnlijk om in elke foto te knipperen?", "no": "Hvem er mest sannsynlig til å blunke på hvert bilde?", "sv": "Vem är mest sannolikt att blinka på varje foto?", "pl": "Kto najprawdopodobniej mruga na każdym zdjęciu?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who in our family starts playing Christmas music way too early?", "da": "Hvem i vores familie begynder at spille julemusik alt for tidligt?", "de": "Wer in unserer Familie spielt viel zu früh Weihnachtsmusik?", "es": "¿Quién en nuestra familia empieza a poner música navideña demasiado pronto?", "pt": "Quem na nossa família começa a tocar música de Natal cedo demais?", "ro": "Cine din familia noastră pune muzică de Crăciun prea devreme?", "fr": "Qui dans notre famille commence la musique de Noël beaucoup trop tôt ?", "it": "Chi nella nostra famiglia inizia a suonare la musica di Natale troppo presto?", "fi": "Kuka perheessämme alkaa soittaa joulumusiikkia liian aikaisin?", "nl": "Wie in onze familie begint er veel te vroeg met het afspelen van kerstmuziek?", "no": "Hvem i familien vår begynner å spille julesanger altfor tidlig?", "sv": "Vem i vår familj börjar spela julmusik alldeles för tidigt?", "pl": "Kto w naszej rodzinie zaczyna grać muzykę świąteczną zdecydowanie za wcześnie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to start a dance party in the kitchen?", "da": "Hvem starter sandsynligvis en dansefest i køkkenet?", "de": "Wer startet am ehesten eine Tanzparty in der Küche?", "es": "¿Quién es más probable que empiece una fiesta de baile en la cocina?", "pt": "Quem é mais provável de começar uma festa de dança na cozinha?", "ro": "Cine e cel mai probabil să înceapă o petrecere dansantă în bucătărie?", "fr": "Qui est le plus susceptible de lancer une fête dansante dans la cuisine ?", "it": "Chi è più probabile che inizi una festa da ballo in cucina?", "fi": "Kuka todennäköisesti aloittaa tanssijuhlat keittiössä?", "nl": "Wie is het meest waarschijnlijk om een dansfeestje in de keuken te beginnen?", "no": "Hvem er mest sannsynlig til å starte en dansefest på kjøkkenet?", "sv": "Vem är mest sannolikt att starta en dansfest i köket?", "pl": "Kto najprawdopodobniej zacznie imprezę taneczną w kuchni?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s our most unforgettable vacation moment?", "da": "Hvad er vores mest uforglemmelige ferieminde?", "de": "Was ist unser unvergesslichster Urlaubsmoment?", "es": "¿Cuál es nuestro momento de vacaciones más inolvidable?", "pt": "Qual é o nosso momento de férias mais inesquecível?", "ro": "Care este cel mai de neuitat moment al vacanței noastre?", "fr": "Quel est notre souvenir de vacances le plus inoubliable ?", "it": "Qual è il nostro momento di vacanza più indimenticabile?", "fi": "Mikä on meidän unohtumattomin lomamuistomme?", "nl": "Wat is ons meest onvergetelijke vakantie-moment?", "no": "Hva er vårt mest uforglemmelige ferieminne?", "sv": "Vilket är vårt mest oförglömliga semesterögonblick?", "pl": "Jaki jest nasz najbardziej niezapomniany moment z wakacji?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who always ends up getting lost on road trips?", "da": "Hvem farer altid vild på roadtrips?", "de": "Wer verirrt sich immer auf Roadtrips?", "es": "¿Quién siempre se pierde en los viajes por carretera?", "pt": "Quem sempre se perde nas viagens de carro?", "ro": "Cine se pierde mereu în excursiile cu mașina?", "fr": "Qui se perd toujours pendant les road trips ?", "it": "Chi si perde sempre durante i viaggi in auto?", "fi": "Kuka aina päätyy eksymään automatkoilla?", "nl": "Wie raakt er altijd verdwaald tijdens roadtrips?", "no": "Hvem ender alltid opp med å gå seg bort på bilturer?", "sv": "Vem brukar alltid gå vilse på roadtrips?", "pl": "Kto zawsze gubi się podczas podróży samochodowych?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the biggest over-packer in the family?", "da": "Hvem er den største over-packer i familien?", "de": "Wer ist der größte Überpacker in der Familie?", "es": "¿Quién es el que más empaca de más en la familia?", "pt": "Quem é o maior exagerado a fazer as malas na família?", "ro": "Cine împachetează mereu prea multe lucruri în familie?", "fr": "Qui est celui qui fait toujours trop de bagages dans la famille ?", "it": "Chi è il più grande esagerato nel fare le valigie della famiglia?", "fi": "Kuka on perheen suurin ylipakkaaja?", "nl": "Wie is de grootste overpakker in de familie?", "no": "Hvem er den største overpakker i familien?", "sv": "Vem är den största överpackaren i familjen?", "pl": "Kto jest największym pakowaczem w rodzinie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s a smell that instantly reminds us of home?", "da": "Hvilken duft minder os straks om hjemmet?", "de": "Welcher Geruch erinnert uns sofort an Zuhause?", "es": "¿Qué olor nos recuerda instantáneamente a casa?", "pt": "Qual cheiro nos lembra instantaneamente de casa?", "ro": "Ce miros ne amintește instant de acasă?", "fr": "Quelle odeur nous rappelle immédiatement la maison ?", "it": "Qual è un odore che ci ricorda immediatamente casa?", "fi": "Mikä tuoksu tuo heti mieleen kodin?", "nl": "Wat is een geur die ons meteen aan thuis herinnert?", "no": "Hva er en lukt som umiddelbart minner oss om hjemmet?", "sv": "Vilken doft påminner oss om hemmet direkt?", "pl": "Jaki zapach od razu przypomina nam o domu?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s usually in charge of music on long drives?", "da": "Hvem står normalt for musikken på lange køreture?", "de": "Wer ist normalerweise für die Musik bei langen Autofahrten zuständig?", "es": "¿Quién suele estar a cargo de la música en los viajes largos?", "pt": "Quem normalmente cuida da música nas viagens longas?", "ro": "Cine este de obicei responsabil cu muzica în drumurile lungi?", "fr": "Qui est généralement responsable de la musique lors des longs trajets ?", "it": "Chi di solito si occupa della musica durante i lunghi viaggi?", "fi": "Kuka yleensä vastaa musiikista pitkillä matkoilla?", "nl": "Wie is meestal verantwoordelijk voor de muziek tijdens lange ritten?", "no": "Hvem pleier vanligvis å ha ansvaret for musikken på lange bilturer?", "sv": "Vem brukar vanligtvis ha ansvaret för musiken på långresor?", "pl": "Kto zazwyczaj odpowiada za muzykę podczas długich podróży?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who insists on having a real Christmas tree, no matter the mess?", "da": "Hvem insisterer på at have et ægte juletræ, uanset rodet?", "de": "Wer besteht auf einem echten Weihnachtsbaum, egal wie chaotisch?", "es": "¿Quién insiste en tener un árbol de Navidad real, sin importar el desorden?", "pt": "Quem insiste em ter uma árvore de Natal de verdade, não importa a bagunça?", "ro": "Cine insistă să aibă un brad adevărat, indiferent de mizerie?", "fr": "Qui insiste pour avoir un vrai sapin de Noël, peu importe le bazar ?", "it": "Chi insiste per avere un vero albero di Natale, nonostante il disordine?", "fi": "Kuka vaatii oikeaa joulupuuta, huolimatta sotkusta?", "nl": "Wie staat erop een echte kerstboom te hebben, ongeacht de rommel?", "no": "Hvem insisterer på å ha et ekte juletre, uansett rotet?", "sv": "Vem insisterar på att ha en riktig julgran, oavsett röran?", "pl": "Kto upiera się przy prawdziwej choince, niezależnie od bałaganu?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "How did mom and dad meet - What’s the story?", "da": "Hvordan mødtes mor og far – hvad er historien?", "de": "Wie haben sich Mama und Papa kennengelernt – was ist die Geschichte?", "es": "¿Cómo se conocieron mamá y papá? ¿Cuál es la historia?", "pt": "Como mamãe e papai se conheceram – qual é a história?", "ro": "Cum s-au cunoscut mama și tata – care e povestea?", "fr": "Comment maman et papa se sont-ils rencontrés – quelle est l’histoire ?", "it": "Come si sono conosciuti mamma e papà - Qual è la storia?", "fi": "Miten äiti ja isä tapasivat - Mikä on tarina?", "nl": "Hoe hebben mama en papa elkaar ontmoet - Wat is het verhaal?", "no": "Hvordan møttes mamma og pappa - Hva er historien?", "sv": "Hur träffades mamma och pappa - Vad är historien?", "pl": "Jak mama i tata się poznali - Jaka jest historia?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who always falls asleep halfway through family movie night?", "da": "Hvem falder altid i søvn halvvejs gennem familiefilmaften?", "de": "Wer schläft immer mitten im Familienfilmabend ein?", "es": "¿Quién siempre se queda dormido a mitad de la noche de películas familiares?", "pt": "Quem sempre adormece no meio da noite de filme em família?", "ro": "Cine adoarme mereu la jumătatea serii de film în familie?", "fr": "Qui s’endort toujours à mi-chemin de la soirée cinéma en famille ?", "it": "Chi si addormenta sempre a metà della serata cinema in famiglia?", "fi": "Kuka aina nukahtaa puolivälissä perheen elokuvailtaa?", "nl": "Wie valt er altijd halverwege de familiefilmavond in slaap?", "no": "Hvem sovner alltid halvveis gjennom familiefilmen?", "sv": "Vem somnar alltid halvvägs genom familjefilmkvällen?", "pl": "Kto zawsze zasypia w połowie rodzinnego wieczoru filmowego?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s the funniest pet story we’ve ever told?", "da": "Hvad er den sjoveste kæledyrshistorie, vi nogensinde har fortalt?", "de": "Was ist die lustigste Haustiergeschichte, die wir je erzählt haben?", "es": "¿Cuál es la historia de mascota más divertida que hemos contado?", "pt": "Qual é a história de animal de estimação mais engraçada que já contamos?", "ro": "Care e cea mai amuzantă poveste cu un animal de companie pe care am spus-o vreodată?", "fr": "Quelle est l’histoire d’animal de compagnie la plus drôle que nous ayons racontée ?", "it": "Qual è la storia di animale domestico più divertente che abbiamo mai raccontato?", "fi": "Mikä on hauskin lemmikkitarina, jonka olemme koskaan kertoneet?", "nl": "Wat is het grappigste huisdierverhaal dat we ooit hebben verteld?", "no": "Hva er den morsomste dyrehistorien vi noen gang har fortalt?", "sv": "Vad är den roligaste husdjursberättelsen vi någonsin har berättat?", "pl": "Jaka jest najzabawniejsza historia o zwierzętach, jaką kiedykolwiek opowiedzieliśmy?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the best cook in our family?", "da": "Hvem er den bedste kok i vores familie?", "de": "Wer ist der beste Koch in unserer Familie?", "es": "¿Quién es el mejor cocinero de nuestra familia?", "pt": "Quem é o melhor cozinheiro da nossa família?", "ro": "Cine e cel mai bun bucătar din familia noastră?", "fr": "Qui est le meilleur cuisinier de notre famille ?", "it": "Chi è il miglior cuoco della nostra famiglia?", "fi": "Kuka on paras kokki perheessämme?", "nl": "Wie is de beste kok in onze familie?", "no": "Hvem er den beste kokken i familien vår?", "sv": "Vem är den bästa kocken i vår familj?", "pl": "Kto jest najlepszym kucharzem w naszej rodzinie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the worst — but still insists on cooking anyway?", "da": "Hvem er den værste — men insisterer stadig på at lave mad?", "de": "Wer ist der schlechteste – besteht aber trotzdem aufs Kochen?", "es": "¿Quién es el peor, pero aún insiste en cocinar?", "pt": "Quem é o pior — mas ainda insiste em cozinhar?", "ro": "Cine e cel mai prost, dar insistă totuși să gătească?", "fr": "Qui est le pire — mais insiste quand même pour cuisiner ?", "it": "Chi è il peggiore — ma insiste comunque a cucinare?", "fi": "Kuka on huonoin — mutta silti vaatii kokkaamista?", "nl": "Wie is de slechtste — maar blijft toch volhouden om te koken?", "no": "Hvem er den dårligste — men insisterer likevel på å lage mat?", "sv": "Vem är sämst — men insisterar ändå på att laga mat?", "pl": "Kto jest najgorszy — ale i tak upiera się, żeby gotować?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s the most famous “disaster meal” we’ve ever had?", "da": "Hvad er det mest berømte “katastrofemåltid”, vi nogensinde har haft?", "de": "Was war das berühmteste „Katastrophenessen“, das wir je hatten?", "es": "¿Cuál es la “comida desastre” más famosa que hemos tenido?", "pt": "Qual foi a refeição de “desastre” mais famosa que já tivemos?", "ro": "Care a fost cea mai „dezastruoasă masă” pe care am avut-o vreodată?", "fr": "Quel est le repas “catastrophe” le plus célèbre que nous ayons eu ?", "it": "Qual è il \"pasto disastroso\" più famoso che abbiamo mai avuto?", "fi": "Mikä on kuuluisin \"onnettomuusateria\", jonka olemme koskaan syöneet?", "nl": "Wat is de meest beroemde \"ramp maaltijd\" die we ooit hebben gehad?", "no": "Hva er det mest kjente \"katastrofemåltidet\" vi noen gang har hatt?", "sv": "Vad är den mest kända \"katastrofmåltiden\" vi någonsin har haft?", "pl": "Jakie jest najsłynniejsze \"katastrofalne danie\", jakie kiedykolwiek mieliśmy?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the best at starting traditions in our family?", "da": "Hvem er bedst til at starte traditioner i familien?", "de": "Wer ist am besten darin, Familientraditionen zu starten?", "es": "¿Quién es el mejor para iniciar tradiciones familiares?", "pt": "Quem é o melhor a começar tradições na família?", "ro": "Cine este cel mai bun la începutul tradițiilor în familie?", "fr": "Qui est le meilleur pour lancer des traditions dans notre famille ?", "it": "Chi è il migliore nel creare tradizioni nella nostra famiglia?", "fi": "Kuka on paras aloittamaan perinteitä meidän perheessämme?", "nl": "Wie is het beste in het starten van tradities in onze familie?", "no": "Hvem er best til å starte tradisjoner i familien vår?", "sv": "Vem är bäst på att starta traditioner i vår familj?", "pl": "Kto jest najlepszy w rozpoczynaniu tradycji w naszej rodzinie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s most likely to spill something on the couch?", "da": "Hvem spilder mest sandsynligt noget på sofaen?", "de": "Wer verschüttet am ehesten etwas auf dem Sofa?", "es": "¿Quién es más probable que derrame algo en el sofá?", "pt": "Quem é mais provável de derramar algo no sofá?", "ro": "Cine e cel mai probabil să verse ceva pe canapea?", "fr": "Qui est le plus susceptible de renverser quelque chose sur le canapé ?", "it": "Chi è più probabile che versi qualcosa sul divano?", "fi": "Kuka todennäköisimmin kaataa jotain sohvalle?", "nl": "Wie is het meest waarschijnlijk om iets op de bank te morsen?", "no": "Hvem er mest sannsynlig til å søle noe på sofaen?", "sv": "Vem är mest benägen att spilla något på soffan?", "pl": "Kto najprawdopodobniej rozleje coś na kanapie?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "What’s our go-to meal when no one feels like cooking?", "da": "Hvad er vores go-to-måltid, når ingen gider lave mad?", "de": "Was ist unser Standardessen, wenn niemand Lust zum Kochen hat?", "es": "¿Cuál es nuestra comida de emergencia cuando nadie quiere cocinar?", "pt": "Qual é a nossa refeição padrão quando ninguém quer cozinhar?", "ro": "Care e masa noastră de rezervă când nimeni nu vrea să gătească?", "fr": "Quel est notre repas de secours quand personne ne veut cuisiner ?", "it": "Qual è il nostro pasto preferito quando nessuno ha voglia di cucinare?", "fi": "Mikä on meidän varma ruoka, kun kukaan ei jaksa kokata?", "nl": "Wat is onze favoriete maaltijd als niemand zin heeft om te koken?", "no": "Hva er vår favorittmåltid når ingen har lyst til å lage mat?", "sv": "Vad är vår favoritmåltid när ingen känner för att laga mat?", "pl": "Jakie jest nasze ulubione danie, gdy nikt nie ma ochoty gotować?"}'::jsonb, false, true, true);
INSERT INTO questions (category_name, translations, is_couple, is_friends, is_family)
VALUES ('History Talks', '{"en": "Who’s the neat freak — and who’s the total mess?", "da": "Hvem er ordensmennesket — og hvem er totalt rodet?", "de": "Wer ist der Ordnungsfanatiker – und wer das totale Chaos?", "es": "¿Quién es el maniático del orden — y quién el desastre total?", "pt": "Quem é o arrumado — e quem é a bagunça total?", "ro": "Cine e obsedat de ordine — și cine e total dezordonat?", "fr": "Qui est le maniaque du rangement — et qui est le vrai bazar ?", "it": "Chi è l''ossessionato dell''ordine — e chi è il totale disordinato?", "fi": "Kuka on siisteysintoilija — ja kuka on totaalinen kaaos?", "nl": "Wie is de netheidfreak — en wie is de totale rommelmaker?", "no": "Hvem er den som er overdrevent ryddig — og hvem er rotet?", "sv": "Vem är pedanten — och vem är den totala röran?", "pl": "Kto jest pedantem, a kto totalnym bałaganiarzem?"}'::jsonb, false, true, true);
