UPDATE questions
SET translations = '{"en": "Night drive: what sight on the road would make you turn around?", "da": "Nattur: Hvilket syn p\u00e5 vejen ville f\u00e5 dig til at vende om?", "de": "Nachtfahrt: Welcher Anblick auf der Stra\u00dfe w\u00fcrde dich umdrehen lassen?", "es": "Viaje nocturno: \u00bfqu\u00e9 ver\u00edas en la carretera que te har\u00eda dar la vuelta?", "pt": "Viagem noturna: que vis\u00e3o na estrada o faria voltar atr\u00e1s?", "ro": "Noapte pe drum: ce priveli\u0219te \u021bi-ar ap\u0103rea pe \u0219osea ca s\u0103 te \u00eentorci din drum?", "fr": "Trajet de nuit : quelle vision sur la route te ferait faire demi-tour ?", "it": "Guida notturna: quale cosa sulla strada ti farebbe fare inversione?", "fi": "Y\u00f6ajelu: millainen n\u00e4ky tiell\u00e4 saisi sinut k\u00e4\u00e4ntym\u00e4\u00e4n takaisin?", "nl": "Nachtelijke rit: welk beeld op de weg zou jou doen omkeren?", "no": "Nattkj\u00f8ring: hvilket syn p\u00e5 veien ville f\u00e5tt deg til \u00e5 snu?", "sv": "Nattk\u00f6rning: vilken syn p\u00e5 v\u00e4gen skulle f\u00e5 dig att v\u00e4nda?", "pl": "Nocna jazda: jaki widok na drodze sprawi\u0142by, \u017ce zawr\u00f3cisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Night drive: what sight on the road would make you turn around?';
UPDATE questions
SET translations = '{"en": "What\u2019s the eeriest place you\u2019ve ever been\u2014and what made it feel wrong?", "da": "Hvad er det mest uhyggelige sted, du nogensinde har v\u00e6ret \u2013 og hvorfor f\u00f8ltes det forkert?", "de": "Was ist der unheimlichste Ort, an dem du je warst \u2013 und warum f\u00fchlte er sich falsch an?", "es": "\u00bfCu\u00e1l es el lugar m\u00e1s inquietante en el que has estado, y qu\u00e9 lo hizo sentir mal?", "pt": "Qual \u00e9 o lugar mais assustador em que j\u00e1 esteve \u2013 e o que o fez parecer errado?", "ro": "Care este cel mai \u00eenfior\u0103tor loc \u00een care ai fost vreodat\u0103 \u2013 \u0219i ce l-a f\u0103cut s\u0103 se simt\u0103 \u201egre\u0219it\u201d?", "fr": "Quel est l\u2019endroit le plus \u00e9trange o\u00f9 tu sois all\u00e9 \u2013 et pourquoi semblait-il \u00ab mauvais \u00bb ?", "it": "Qual \u00e8 il posto pi\u00f9 inquietante in cui sei mai stato/a, e cosa lo rendeva cos\u00ec sbagliato?", "fi": "Mik\u00e4 on oudoinkin paikka, jossa olet ollut \u2013 ja mik\u00e4 teki siit\u00e4 niin karmivan?", "nl": "Wat is de griezeligste plek waar je ooit bent geweest, en wat maakte het zo fout aanvoelen?", "no": "Hva er det ekleste/merkeligste stedet du noen gang har v\u00e6rt \u2013 og hva gjorde at det f\u00f8ltes feil?", "sv": "Vilken \u00e4r den kusligaste plats du n\u00e5gonsin varit p\u00e5 \u2013 och vad gjorde att den k\u00e4ndes fel?", "pl": "Jakie jest najbardziej upiorne miejsce, w kt\u00f3rym kiedykolwiek by\u0142e\u015b/by\u0142a\u015b \u2013 i co sprawi\u0142o, \u017ce wydawa\u0142o si\u0119 takie z\u0142e?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the eeriest place you’ve ever been—and what made it feel wrong?';
UPDATE questions
SET translations = '{"en": "Tell a true coincidence that still gives you chills.", "da": "Fort\u00e6l om et sandt tilf\u00e6lde af sammenfald, der stadig giver dig kuldegysninger.", "de": "Erz\u00e4hl von einem wahren Zufall, der dir heute noch Schauer bereitet.", "es": "Cuenta una coincidencia real que a\u00fan te da escalofr\u00edos.", "pt": "Conte uma coincid\u00eancia verdadeira que ainda te arrepia.", "ro": "Poveste\u0219te o coinciden\u021b\u0103 adev\u0103rat\u0103 care \u00eenc\u0103 \u00ee\u021bi d\u0103 fiori.", "fr": "Raconte une co\u00efncidence r\u00e9elle qui te donne encore des frissons.", "it": "Racconta una vera coincidenza che ancora ti mette i brividi.", "fi": "Kerro oikea sattuma, joka kylm\u00e4\u00e4 viel\u00e4kin selk\u00e4piit\u00e4.", "nl": "Vertel een echte toevalligheid die je nog steeds kippenvel geeft.", "no": "Fortell om et ekte sammentreff som fortsatt gir deg frysninger.", "sv": "Ber\u00e4tta om en sann slump som fortfarande ger dig rysningar.", "pl": "Opowiedz o prawdziwym zbiegu okoliczno\u015bci, kt\u00f3ry nadal przyprawia ci\u0119 o dreszcze."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Tell a true coincidence that still gives you chills.';
UPDATE questions
SET translations = '{"en": "You notice a small red light behind a vent. Do you cover it or call staff?", "da": "Du ser et lille r\u00f8dt lys bag en ventilationsrist. D\u00e6kker du det eller ringer du til personalet?", "de": "Du bemerkst ein kleines rotes Licht hinter einem L\u00fcftungsschlitz. Deckst du es ab oder rufst du das Personal?", "es": "Ves una peque\u00f1a luz roja detr\u00e1s de una rejilla. \u00bfLa cubres o llamas al personal?", "pt": "V\u00eas uma pequena luz vermelha atr\u00e1s de uma ventila\u00e7\u00e3o. Cobres ou chamas os funcion\u00e1rios?", "ro": "Observi o mic\u0103 lumin\u0103 ro\u0219ie \u00een spatele unui orificiu de ventila\u021bie. O acoperi sau chemi personalul?", "fr": "Tu remarques une petite lumi\u00e8re rouge derri\u00e8re une grille d\u2019a\u00e9ration. Tu la couvres ou tu appelles le personnel ?", "it": "Noti una piccola luce rossa dietro una grata. La copri o chiami il personale?", "fi": "Huomaat pienen punaisen valon ritil\u00e4n takana. Peit\u00e4tk\u00f6 sen vai kutsutko henkil\u00f6kuntaa?", "nl": "Je ziet een klein rood lampje achter een rooster. Dek je het af of roep je personeel?", "no": "Du legger merke til et lite r\u00f8dt lys bak en ventil. Dekker du det til eller ringer du p\u00e5 personalet?", "sv": "Du ser ett litet r\u00f6tt ljus bakom ett ventilationsgaller. T\u00e4ckar du \u00f6ver det eller ringer du p\u00e5 personal?", "pl": "Zauwa\u017casz ma\u0142e czerwone \u015bwiate\u0142ko za kratk\u0105 wentylacyjn\u0105. Zas\u0142aniasz je czy wo\u0142asz obs\u0142ug\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You notice a small red light behind a vent. Do you cover it or call staff?';
