UPDATE questions
SET translations = '{"en": "What\u2019s your funniest drunk confession story?", "da": "Hvad er din sjoveste fuld-tilst\u00e5elses-historie?", "de": "Was ist deine lustigste betrunkene Beichtgeschichte?", "es": "\u00bfCu\u00e1l es tu historia de confesi\u00f3n borracha m\u00e1s divertida?", "pt": "Qual \u00e9 a tua hist\u00f3ria de confiss\u00e3o b\u00eabeda mais engra\u00e7ada?", "ro": "Care este cea mai amuzant\u0103 poveste a ta spus\u0103 beat?", "fr": "Quelle est ton histoire d\u2019aveu d\u2019ivresse la plus dr\u00f4le ?", "it": "Qual \u00e8 la tua storia pi\u00f9 divertente di confessione da ubriaco?", "fi": "Mik\u00e4 on hauskin juopottelun tunnustustarinasi?", "nl": "Wat is jouw grappigste dronken bekentenisverhaal?", "no": "Hva er din morsomste fulle bekjennelseshistorie?", "sv": "Vad \u00e4r din roligaste berusade bek\u00e4nnelsehistoria?", "pl": "Jaka jest twoja najzabawniejsza historia z pijanego wyznania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your funniest drunk confession story?';
UPDATE questions
SET translations = '{"en": "What\u2019s your \u201cI\u2019m way too sober for this\u201d moment at a party?", "da": "Hvad er dit \u201cjeg er alt for \u00e6dru til det her\u201d-\u00f8jeblik til en fest?", "de": "Was ist dein \u201eIch bin viel zu n\u00fcchtern daf\u00fcr\u201c-Moment auf einer Party?", "es": "\u00bfCu\u00e1l es tu momento de \u201cestoy demasiado sobrio para esto\u201d en una fiesta?", "pt": "Qual \u00e9 o teu momento de \u201cestou s\u00f3brio demais para isto\u201d numa festa?", "ro": "Care este momentul t\u0103u de \u201esunt prea treaz pentru asta\u201d la o petrecere?", "fr": "Quel est ton moment \u201cje suis beaucoup trop sobre pour \u00e7a\u201d en soir\u00e9e ?", "it": "Qual \u00e8 il tuo momento \"sono troppo sobrio per questo\" a una festa?", "fi": "Mik\u00e4 on se hetki juhlissa, jolloin ajattelet \"olen aivan liian selv\u00e4 t\u00e4h\u00e4n\"?", "nl": "Wat is jouw \"ik ben veel te nuchter voor dit\" moment op een feestje?", "no": "Hva er ditt \"jeg er altfor edru for dette\"-\u00f8yeblikk p\u00e5 en fest?", "sv": "Vad \u00e4r ditt \"jag \u00e4r alldeles f\u00f6r nykter f\u00f6r det h\u00e4r\"-\u00f6gonblick p\u00e5 en fest?", "pl": "Jaki jest tw\u00f3j moment \u201ejestem zdecydowanie za trze\u017awy na to\u201d na imprezie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your “I’m way too sober for this” moment at a party?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the biggest \u201cI said I\u2019d stay for one drink\u201d liar?", "da": "Hvem er den st\u00f8rste \u201cjeg sagde, jeg bliver kun til \u00e9n drink\u201d l\u00f8gner?", "de": "Wer ist der gr\u00f6\u00dfte \u201eIch bleib nur f\u00fcr einen Drink\u201c-L\u00fcgner?", "es": "\u00bfQui\u00e9n es el mayor mentiroso de \u201csolo me quedo por una copa\u201d?", "pt": "Quem \u00e9 o maior mentiroso do \u201cs\u00f3 fico por uma bebida\u201d?", "ro": "Cine e cel mai mare mincinos cu \u201er\u0103m\u00e2n doar pentru o b\u0103utur\u0103\u201d?", "fr": "Qui est le plus grand menteur du \u201cje reste juste pour un verre\u201d ?", "it": "Chi \u00e8 il pi\u00f9 grande bugiardo del tipo \"ho detto che sarei rimasto per un drink\"?", "fi": "Kuka on suurin \"sanoin, ett\u00e4 j\u00e4isin vain yhteen juomaan\" valehtelija?", "nl": "Wie is de grootste \"ik zei dat ik voor \u00e9\u00e9n drankje zou blijven\" leugenaar?", "no": "Hvem er den st\u00f8rste \"jeg sa jeg skulle bli for \u00e9n drink\" l\u00f8gneren?", "sv": "Vem \u00e4r den st\u00f6rsta \"jag sa att jag skulle stanna f\u00f6r en drink\"-l\u00f6gnaren?", "pl": "Kto jest najwi\u0119kszym k\u0142amc\u0105, kt\u00f3ry m\u00f3wi \"m\u00f3wi\u0142em, \u017ce zostan\u0119 na jeden drink\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the biggest “I said I’d stay for one drink” liar?';
UPDATE questions
SET translations = '{"en": "What\u2019s your most chaotic Uber or taxi ride memory?", "da": "Hvad er din mest kaotiske Uber- eller taxatur-hukommelse?", "de": "Was ist deine chaotischste Uber- oder Taxifahrt-Erinnerung?", "es": "\u00bfCu\u00e1l es tu recuerdo m\u00e1s ca\u00f3tico de un Uber o taxi?", "pt": "Qual \u00e9 a tua mem\u00f3ria mais ca\u00f3tica de um Uber ou t\u00e1xi?", "ro": "Care e cea mai haotic\u0103 amintire a ta dintr-un Uber sau taxi?", "fr": "Quel est ton souvenir d\u2019Uber ou de taxi le plus chaotique ?", "it": "Qual \u00e8 il tuo ricordo pi\u00f9 caotico di un viaggio in Uber o in taxi?", "fi": "Mik\u00e4 on kaoottisin Uber- tai taksimatka-muistosi?", "nl": "Wat is je meest chaotische herinnering aan een Uber- of taxirit?", "no": "Hva er ditt mest kaotiske minne fra en Uber- eller taxitur?", "sv": "Vad \u00e4r ditt mest kaotiska minne fr\u00e5n en Uber- eller taxiresa?", "pl": "Jakie jest twoje najbardziej chaotyczne wspomnienie z przejazdu Uberem lub taks\u00f3wk\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your most chaotic Uber or taxi ride memory?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to lose their drink and just grab another?", "da": "Hvem mister mest sandsynligt deres drink og tager bare en anden?", "de": "Wer verliert am ehesten sein Getr\u00e4nk und nimmt einfach ein anderes?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que pierda su bebida y simplemente agarre otra?", "pt": "Quem \u00e9 mais prov\u00e1vel perder a bebida e simplesmente pegar outra?", "ro": "Cine e cel mai probabil s\u0103-\u0219i piard\u0103 b\u0103utura \u0219i s\u0103 ia pur \u0219i simplu alta?", "fr": "Qui est le plus susceptible de perdre son verre et d\u2019en prendre un autre ?", "it": "Chi \u00e8 pi\u00f9 probabile che perda la propria bevanda e ne prenda un''altra?", "fi": "Kuka todenn\u00e4k\u00f6isesti tiputtaa juomansa ja ottaa vain toisen?", "nl": "Wie is het meest waarschijnlijk om hun drankje te verliezen en gewoon een nieuwe te pakken?", "no": "Hvem er mest sannsynlig til \u00e5 miste drinken sin og bare ta en ny?", "sv": "Vem \u00e4r mest ben\u00e4gen att tappa sin drink och bara ta en ny?", "pl": "Kto najprawdopodobniej zgubi sw\u00f3j nap\u00f3j i po prostu we\u017amie inny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to lose their drink and just grab another?';
UPDATE questions
SET translations = '{"en": "What\u2019s the weirdest compliment you\u2019ve ever gotten while out?", "da": "Hvad er det m\u00e6rkeligste kompliment, du nogensinde har f\u00e5et, mens du var ude?", "de": "Was ist das seltsamste Kompliment, das du je bekommen hast, als du unterwegs warst?", "es": "\u00bfCu\u00e1l es el cumplido m\u00e1s raro que te han hecho mientras estabas fuera?", "pt": "Qual \u00e9 o elogio mais estranho que j\u00e1 recebeste quando estavas fora?", "ro": "Care este cel mai ciudat compliment pe care l-ai primit vreodat\u0103 \u00een ora\u0219?", "fr": "Quel est le compliment le plus \u00e9trange que tu aies jamais re\u00e7u en soir\u00e9e ?", "it": "Qual \u00e8 il complimento pi\u00f9 strano che hai mai ricevuto mentre eri fuori?", "fi": "Mik\u00e4 on outoimmasta kehu, jonka olet koskaan saanut ulkona ollessasi?", "nl": "Wat is de vreemdste compliment dat je ooit hebt gekregen terwijl je buiten was?", "no": "Hva er det merkeligste komplimentet du noen gang har f\u00e5tt mens du var ute?", "sv": "Vad \u00e4r det konstigaste komplimang du n\u00e5gonsin har f\u00e5tt n\u00e4r du varit ute?", "pl": "Jakie najdziwniejsze komplementy kiedykolwiek otrzyma\u0142e\u015b, b\u0119d\u0105c na zewn\u0105trz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s the weirdest compliment you’ve ever gotten while out?';
UPDATE questions
SET translations = '{"en": "What song instantly brings back a memory of a wild night?", "da": "Hvilken sang bringer straks minderne tilbage om en vild nat?", "de": "Welches Lied bringt sofort Erinnerungen an eine wilde Nacht zur\u00fcck?", "es": "\u00bfQu\u00e9 canci\u00f3n te trae instant\u00e1neamente recuerdos de una noche loca?", "pt": "Que m\u00fasica te traz instantaneamente mem\u00f3rias de uma noite louca?", "ro": "Ce melodie \u00ee\u021bi aduce instantaneu aminte de o noapte nebun\u0103?", "fr": "Quelle chanson te ram\u00e8ne instantan\u00e9ment \u00e0 une nuit folle ?", "it": "Quale canzone ti riporta immediatamente a un ricordo di una notte folle?", "fi": "Mik\u00e4 kappale tuo heti mieleen muiston villist\u00e4 y\u00f6st\u00e4?", "nl": "welk nummer brengt meteen een herinnering terug aan een wilde nacht?", "no": "Hvilken sang bringer umiddelbart tilbake minner fra en vill natt?", "sv": "Vilken l\u00e5t f\u00e5r dig genast att t\u00e4nka p\u00e5 en vild natt?", "pl": "Jaka piosenka od razu przywo\u0142uje wspomnienia szalonej nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What song instantly brings back a memory of a wild night?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the best at pretending they\u2019re sober when they\u2019re not?", "da": "Hvem er bedst til at lade som om, de er \u00e6dru, n\u00e5r de ikke er det?", "de": "Wer kann am besten so tun, als w\u00e4re er n\u00fcchtern, obwohl er es nicht ist?", "es": "\u00bfQui\u00e9n es el mejor fingiendo estar sobrio cuando no lo est\u00e1?", "pt": "Quem \u00e9 o melhor a fingir que est\u00e1 s\u00f3brio quando n\u00e3o est\u00e1?", "ro": "Cine e cel mai bun la a se preface c\u0103 e treaz c\u00e2nd nu e?", "fr": "Qui est le meilleur pour faire semblant d\u2019\u00eatre sobre quand il ne l\u2019est pas ?", "it": "Chi \u00e8 il migliore a fingere di essere sobrio quando non lo \u00e8?", "fi": "Kuka on paras teeskentelem\u00e4\u00e4n, ett\u00e4 on juomatta, vaikka ei ole?", "nl": "Wie is het beste in doen alsof ze nuchter zijn terwijl ze dat niet zijn?", "no": "Hvem er best til \u00e5 late som de er edru n\u00e5r de ikke er det?", "sv": "Vem \u00e4r b\u00e4st p\u00e5 att l\u00e5tsas vara nykter n\u00e4r de inte \u00e4r det?", "pl": "Kto jest najlepszy w udawaniu, \u017ce jest trze\u017awy, gdy wcale nie jest?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the best at pretending they’re sober when they’re not?';UPDATE questions
SET translations = '{"en": "Who\u2019s the biggest overthinker before a night out?", "da": "Hvem overt\u00e6nker mest f\u00f8r en aften i byen?", "de": "Wer denkt vor einem Abend am meisten zu viel nach?", "es": "\u00bfQui\u00e9n es el que m\u00e1s piensa antes de salir de noche?", "pt": "Quem pensa demais antes de uma sa\u00edda \u00e0 noite?", "ro": "Cine g\u00e2nde\u0219te prea mult \u00eenainte de o ie\u0219ire \u00een ora\u0219?", "fr": "Qui r\u00e9fl\u00e9chit trop avant une soir\u00e9e ?", "it": "Chi \u00e8 il pi\u00f9 grande pensatore eccessivo prima di una serata fuori?", "fi": "Kuka on suurin liiallinen ajattelija ennen iltaa ulkona?", "nl": "Wie is de grootste piekeraar voor een avondje uit?", "no": "Hvem er den st\u00f8rste overtenkeren f\u00f8r en kveld ute?", "sv": "Vem \u00e4r den st\u00f6rsta \u00f6veranalyssaren innan en utekv\u00e4ll?", "pl": "Kto jest najwi\u0119kszym zamartwiaczem przed wyj\u015bciem na miasto?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the biggest overthinker before a night out?';
UPDATE questions
SET translations = '{"en": "What\u2019s one rule you\u2019d make for all parties if you could?", "da": "Hvilken regel ville du lave for alle fester, hvis du kunne?", "de": "Welche Regel w\u00fcrdest du f\u00fcr alle Partys aufstellen, wenn du k\u00f6nntest?", "es": "\u00bfQu\u00e9 regla pondr\u00edas para todas las fiestas si pudieras?", "pt": "Que regra farias para todas as festas se pudesses?", "ro": "Ce regul\u0103 ai impune pentru toate petrecerile dac\u0103 ai putea?", "fr": "Quelle r\u00e8gle instaurerais-tu pour toutes les soir\u00e9es si tu pouvais ?", "it": "Qual \u00e8 una regola che stabiliresti per tutti i partiti se potessi?", "fi": "Mik\u00e4 olisi yksi s\u00e4\u00e4nt\u00f6, jonka s\u00e4\u00e4t\u00e4isit kaikille juhliin, jos voisit?", "nl": "Wat is \u00e9\u00e9n regel die je zou maken voor alle feesten als je kon?", "no": "Hva er en regel du ville laget for alle fester hvis du kunne?", "sv": "Vilken regel skulle du inf\u00f6ra f\u00f6r alla fester om du kunde?", "pl": "Jak\u0105 jedn\u0105 zasad\u0119 wprowadzi\u0142by\u015b dla wszystkich imprez, gdyby\u015b m\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s one rule you’d make for all parties if you could?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the most photogenic when the night\u2019s getting blurry?", "da": "Hvem er mest fotogen, n\u00e5r natten begynder at blive sl\u00f8ret?", "de": "Wer ist am fotogensten, wenn die Nacht verschwimmt?", "es": "\u00bfQui\u00e9n es el m\u00e1s fotog\u00e9nico cuando la noche se vuelve borrosa?", "pt": "Quem \u00e9 o mais fotog\u00e9nico quando a noite come\u00e7a a ficar turva?", "ro": "Cine e cel mai fotogenic c\u00e2nd noaptea devine \u00eence\u021bo\u0219at\u0103?", "fr": "Qui est le plus photog\u00e9nique quand la nuit devient floue ?", "it": "Chi \u00e8 il pi\u00f9 fotogenico quando la notte diventa sfocata?", "fi": "Kuka on valokuvauksellisin, kun y\u00f6 alkaa h\u00e4m\u00e4rty\u00e4?", "nl": "Wie is het meest fotogeniek als de nacht vaag wordt?", "no": "Hvem er den mest fotogene n\u00e5r natten blir uklar?", "sv": "Vem \u00e4r mest fotogenisk n\u00e4r natten blir suddig?", "pl": "Kto jest najbardziej fotogeniczny, gdy noc staje si\u0119 nieostra?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s the most photogenic when the night’s getting blurry?';