UPDATE questions
SET translations = '{"en": "You find your partner on a dating app \u201cjust to look.\u201d Is that cheating or harmless curiosity?", "da": "Du finder din partner p\u00e5 en datingapp \u201cbare for at kigge.\u201d Er det utroskab eller uskyldig nysgerrighed?", "de": "Du findest deinen Partner auf einer Dating-App \u201enur zum Schauen\u201c. Ist das Betrug oder harmlose Neugier?", "es": "Encuentras a tu pareja en una app de citas \u201csolo mirando\u201d. \u00bfEs enga\u00f1o o curiosidad inofensiva?", "pt": "Encontras o teu parceiro numa app de encontros \u201cs\u00f3 a ver\u201d. \u00c9 trai\u00e7\u00e3o ou curiosidade inofensiva?", "ro": "\u00ce\u021bi g\u0103se\u0219ti partenerul pe o aplica\u021bie de dating \u201edoar s\u0103 vad\u0103\u201d. E \u00een\u0219elat sau doar curiozitate nevinovat\u0103?", "fr": "Tu d\u00e9couvres ton partenaire sur une appli de rencontres \u00ab juste pour regarder \u00bb. C\u2019est de la tromperie ou de la curiosit\u00e9 ?", "it": "Trovi il tuo partner su un''app di incontri \"solo per curiosit\u00e0\". \u00c8 tradimento o semplice curiosit\u00e0?", "fi": "L\u00f6yd\u00e4t kumppanisi deittisovelluksesta \"vain katsomassa\". Onko se pett\u00e4mist\u00e4 vai harmitonta uteliaisuutta?", "nl": "Je vindt je partner op een datingapp \"gewoon om te kijken.\" Is dat bedrog of onschuldige nieuwsgierigheid?", "no": "Du finner partneren din p\u00e5 en datingapp \"bare for \u00e5 se.\" Er det utroskap eller harml\u00f8s nysgjerrighet?", "sv": "Du hittar din partner p\u00e5 en dejtingapp \"bara f\u00f6r att kolla.\" \u00c4r det otrohet eller harml\u00f6s nyfikenhet?", "pl": "Znalaz\u0142e\u015b swojego partnera na aplikacji randkowej \u201etylko do ogl\u0105dania\u201d. Czy to zdrada, czy nieszkodliwa ciekawo\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You find your partner on a dating app “just to look.” Is that cheating or harmless curiosity?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to win a fight\u2026 but for the dumbest reason?", "da": "Hvem er mest tilb\u00f8jelig til at vinde et slagsm\u00e5l \u2026 men for den dummeste grund?", "de": "Wer w\u00fcrde am ehesten einen Streit gewinnen \u2026 aber aus dem d\u00fcmmsten Grund?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que gane una pelea\u2026 pero por la raz\u00f3n m\u00e1s tonta?", "pt": "Quem \u00e9 mais prov\u00e1vel de ganhar uma briga\u2026 mas pela raz\u00e3o mais est\u00fapida?", "ro": "Cine e cel mai probabil s\u0103 c\u00e2\u0219tige o ceart\u0103\u2026 dar din cel mai prost motiv?", "fr": "Qui est le plus susceptible de gagner une dispute\u2026 mais pour la raison la plus stupide ?", "it": "Chi \u00e8 pi\u00f9 probabile che vinca una rissa... ma per il motivo pi\u00f9 stupido?", "fi": "Kuka todenn\u00e4k\u00f6isimmin voittaa taistelun... mutta typerimm\u00e4n syyn vuoksi?", "nl": "Wie is het meest waarschijnlijk om een gevecht te winnen... maar om de domste reden?", "no": "Hvem er mest sannsynlig \u00e5 vinne en kamp... men av den dummeste grunnen?", "sv": "Vem \u00e4r mest sannolikt att vinna en fight... men av den dummaste anledningen?", "pl": "Kto najprawdopodobniej wygra\u0142by walk\u0119... ale z najg\u0142upszego powodu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who’s most likely to win a fight… but for the dumbest reason?';
UPDATE questions
SET translations = '{"en": "Who in this room gives the best advice but never takes their own?", "da": "Hvem i dette rum giver de bedste r\u00e5d, men f\u00f8lger dem aldrig selv?", "de": "Wer in diesem Raum gibt die besten Ratschl\u00e4ge, befolgt sie aber nie selbst?", "es": "\u00bfQui\u00e9n en esta sala da los mejores consejos pero nunca los sigue?", "pt": "Quem nesta sala d\u00e1 os melhores conselhos mas nunca os segue?", "ro": "Cine din aceast\u0103 camer\u0103 d\u0103 cele mai bune sfaturi, dar nu le urmeaz\u0103 niciodat\u0103?", "fr": "Qui dans cette pi\u00e8ce donne les meilleurs conseils mais ne les suit jamais ?", "it": "Chi in questa stanza d\u00e0 i migliori consigli ma non segue mai i propri?", "fi": "Kuka t\u00e4ss\u00e4 huoneessa antaa parasta neuvoa, mutta ei koskaan seuraa omia neuvojaan?", "nl": "Wie in deze kamer geeft de beste adviezen maar volgt ze nooit zelf op?", "no": "Hvem i dette rommet gir de beste r\u00e5dene, men tar aldri sine egne?", "sv": "Vem i det h\u00e4r rummet ger de b\u00e4sta r\u00e5den men tar aldrig sina egna?", "pl": "Kto w tym pokoju daje najlepsze rady, ale nigdy ich nie stosuje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who in this room gives the best advice but never takes their own?';
UPDATE questions
SET translations = '{"en": "If one of your friends secretly won the lottery, who would tell everyone by accident?", "da": "Hvis en af dine venner hemmeligt vandt i lotto, hvem ville komme til at fort\u00e6lle det ved et uheld?", "de": "Wenn einer deiner Freunde heimlich im Lotto gewinnen w\u00fcrde, wer w\u00fcrde es aus Versehen verraten?", "es": "Si uno de tus amigos ganara la loter\u00eda en secreto, \u00bfqui\u00e9n lo contar\u00eda por accidente?", "pt": "Se um dos teus amigos ganhasse o Euromilh\u00f5es em segredo, quem contaria por acidente?", "ro": "Dac\u0103 unul dintre prietenii t\u0103i ar c\u00e2\u0219tiga la loterie \u00een secret, cine ar spune din gre\u0219eal\u0103?", "fr": "Si un de tes amis gagnait \u00e0 la loterie en secret, qui le r\u00e9v\u00e9lerait par accident ?", "it": "Se uno dei tuoi amici avesse vinto segretamente alla lotteria, chi lo direbbe a tutti per sbaglio?", "fi": "Jos yksi yst\u00e4vist\u00e4si voitti salaa lotossa, kuka kertoisi kaikille vahingossa?", "nl": "Als een van je vrienden stiekem de loterij heeft gewonnen, wie zou het dan per ongeluk aan iedereen vertellen?", "no": "Hvis en av vennene dine hemmelig vant i lotto, hvem ville fortalt alle ved et uhell?", "sv": "Om en av dina v\u00e4nner hemligt vann p\u00e5 lotteriet, vem skulle av misstag ber\u00e4tta f\u00f6r alla?", "pl": "Gdyby jeden z twoich przyjaci\u00f3\u0142 potajemnie wygra\u0142 na loterii, kto przypadkiem by o tym powiedzia\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If one of your friends secretly won the lottery, who would tell everyone by accident?';
UPDATE questions
SET translations = '{"en": "Who would most likely cry during an argument and win it?", "da": "Hvem ville sandsynligvis gr\u00e6de under et sk\u00e6nderi \u2014 og vinde det?", "de": "Wer w\u00fcrde wahrscheinlich w\u00e4hrend eines Streits weinen \u2013 und ihn gewinnen?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que llore durante una discusi\u00f3n\u2026 y la gane?", "pt": "Quem \u00e9 mais prov\u00e1vel de chorar durante uma discuss\u00e3o\u2026 e ganh\u00e1-la?", "ro": "Cine ar pl\u00e2nge \u00eentr-o ceart\u0103\u2026 \u0219i totu\u0219i ar c\u00e2\u0219tiga-o?", "fr": "Qui pleurerait probablement pendant une dispute\u2026 et la gagnerait ?", "it": "Chi piangerebbe pi\u00f9 probabilmente durante un litigio e lo vincerebbe?", "fi": "Kuka todenn\u00e4k\u00f6isesti itkee riidan aikana ja voittaa sen?", "nl": "Wie zou het meest waarschijnlijk tijdens een ruzie huilen en deze winnen?", "no": "Hvem ville mest sannsynlig gr\u00e5te under en krangel og vinne den?", "sv": "Vem skulle mest sannolikt gr\u00e5ta under en konflikt och vinna den?", "pl": "Kto najprawdopodobniej zap\u0142acze podczas k\u0142\u00f3tni i wygra j\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would most likely cry during an argument and win it?';
UPDATE questions
SET translations = '{"en": "Who here would secretly thrive in drama but pretend they hate it?", "da": "Hvem her ville i hemmelighed nyde drama, men lade som om de hader det?", "de": "Wer hier w\u00fcrde heimlich im Drama aufbl\u00fchen, aber so tun, als w\u00fcrde er es hassen?", "es": "\u00bfQui\u00e9n aqu\u00ed secretamente disfrutar\u00eda del drama pero fingir\u00eda odiarlo?", "pt": "Quem aqui secretamente adoraria o drama mas fingiria que o odeia?", "ro": "Cine de aici s-ar bucura \u00een secret de dram\u0103, dar ar pretinde c\u0103 o ur\u0103\u0219te?", "fr": "Qui ici adorerait secr\u00e8tement le drame mais ferait semblant de le d\u00e9tester ?", "it": "Chi qui prospererebbe segretamente nel dramma ma finge di odiarlo?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 salaa nauttisi draamasta, mutta teeskentelee vihaavansa sit\u00e4?", "nl": "Wie hier zou stiekem gedijen in drama maar doen alsof ze het haten?", "no": "Hvem her ville hemmelig blomstre i drama, men late som de hater det?", "sv": "Vem h\u00e4r skulle hemligt trivas i drama men l\u00e5tsas att de hatar det?", "pl": "Kto tutaj potajemnie odnajdywa\u0142by si\u0119 w dramacie, ale udaje, \u017ce go nienawidzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who here would secretly thrive in drama but pretend they hate it?';
UPDATE questions
SET translations = '{"en": "Your dating app matches you with your ex\u2019s best friend. Do you swipe right for revenge or pretend you never saw it?", "da": "Din datingapp matcher dig med din eks\u2019 bedste ven. Swiper du for h\u00e6vn eller lader som om du ikke s\u00e5 det?", "de": "Deine Dating-App matched dich mit dem besten Freund deines Ex. Wischst du aus Rache nach rechts oder tust du so, als h\u00e4ttest du es nie gesehen?", "es": "Tu app de citas te empareja con el mejor amigo de tu ex. \u00bfDeslizas por venganza o finges que no lo viste?", "pt": "A tua app de encontros faz-te match com o melhor amigo do teu ex. Deslizas por vingan\u00e7a ou finges que n\u00e3o viste?", "ro": "Aplica\u021bia ta de dating te potrive\u0219te cu cel mai bun prieten al fostului t\u0103u. Glisezi pentru r\u0103zbunare sau ignori?", "fr": "Ton appli de rencontres te met en match avec le meilleur ami de ton ex. Tu glisses par vengeance ou tu ignores ?", "it": "La tua app di incontri ti abbina con il migliore amico del tuo ex. Scorri a destra per vendetta o fai finta di non averlo mai visto?", "fi": "Sovelluksesi yhdist\u00e4\u00e4 sinut eks\u00e4si parhaan yst\u00e4v\u00e4n kanssa. Pyyhk\u00e4isetk\u00f6 oikealle koston vuoksi vai teetk\u00f6 kuin et olisi koskaan n\u00e4hnyt sit\u00e4?", "nl": "Je dating-app koppelt je aan de beste vriend van je ex. Swipe je naar rechts voor wraak of doe je alsof je het nooit hebt gezien?", "no": "Datingappen matcher deg med eksens beste venn. Svirer du til h\u00f8yre for hevn, eller later du som om du aldri s\u00e5 det?", "sv": "Din dejtingapp matchar dig med din exs b\u00e4sta v\u00e4n. Swipar du h\u00f6ger f\u00f6r h\u00e4mnd eller l\u00e5tsas du som om du aldrig s\u00e5g det?", "pl": "Twoja aplikacja randkowa \u0142\u0105czy ci\u0119 z najlepszym przyjacielem twojego by\u0142ego. Czy przesuniesz w prawo dla zemsty, czy udasz, \u017ce nigdy tego nie widzia\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Your dating app matches you with your ex’s best friend. Do you swipe right for revenge or pretend you never saw it?';
UPDATE questions
SET translations = '{"en": "Who would be voted \u201cmost likely to accidentally go viral\u201d?", "da": "Hvem ville blive stemt som \u201cmest sandsynlig til at g\u00e5 viralt ved et uheld\u201d?", "de": "Wer w\u00fcrde gew\u00e4hlt werden als \u201eam wahrscheinlichsten aus Versehen viral zu gehen\u201c?", "es": "\u00bfQui\u00e9n ser\u00eda votado como \u201cm\u00e1s probable de hacerse viral por accidente\u201d?", "pt": "Quem seria votado como \u201cmais prov\u00e1vel de se tornar viral por acidente\u201d?", "ro": "Cine ar fi votat \u201ccel mai probabil s\u0103 devin\u0103 viral din gre\u0219eal\u0103\u201d?", "fr": "Qui serait \u00e9lu \u00ab le plus susceptible de devenir viral par accident \u00bb ?", "it": "Chi verrebbe votato come \"il pi\u00f9 probabile a diventare virale per sbaglio\"?", "fi": "Kuka \u00e4\u00e4nestett\u00e4isiin \"todenn\u00e4k\u00f6isimmin vahingossa menem\u00e4\u00e4n viraaliksi\"?", "nl": "Wie zou er worden gekozen als \"meest waarschijnlijk om per ongeluk viraal te gaan\"?", "no": "Hvem ville blitt stemt som \"mest sannsynlig til \u00e5 bli viral ved en tilfeldighet\"?", "sv": "Vem skulle bli r\u00f6stad som \"mest sannolikt att av misstag bli viral\"?", "pl": "Kto by\u0142by g\u0142osowany na \u201enajbardziej prawdopodobnego do przypadkowego stania si\u0119 viralem\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would be voted “most likely to accidentally go viral”?';
UPDATE questions
SET translations = '{"en": "You find out one of your friends has been lying about their job for months \u2014 what\u2019s your move?", "da": "Du finder ud af, at en af dine venner har l\u00f8jet om deres job i flere m\u00e5neder \u2014 hvad g\u00f8r du?", "de": "Du erf\u00e4hrst, dass einer deiner Freunde seit Monaten \u00fcber seinen Job l\u00fcgt \u2013 was tust du?", "es": "Descubres que uno de tus amigos ha estado mintiendo sobre su trabajo durante meses \u2014 \u00bfqu\u00e9 haces?", "pt": "Descobres que um amigo teu mentiu sobre o trabalho durante meses \u2014 o que fazes?", "ro": "Afl\u0103 c\u0103 un prieten a min\u021bit luni de zile despre locul de munc\u0103 \u2014 ce faci?", "fr": "Tu d\u00e9couvres qu\u2019un ami ment sur son travail depuis des mois \u2014 que fais-tu ?", "it": "Scopri che uno dei tuoi amici ha mentito sul suo lavoro per mesi \u2014 quale sar\u00e0 la tua mossa?", "fi": "Saat tiet\u00e4\u00e4, ett\u00e4 yksi yst\u00e4vist\u00e4si on valehdellut ty\u00f6paikastaan kuukausia \u2014 mit\u00e4 teet?", "nl": "Je ontdekt dat een van je vrienden al maanden over zijn werk liegt \u2014 wat doe je?", "no": "Du finner ut at en av vennene dine har l\u00f8yet om jobben sin i flere m\u00e5neder \u2014 hva gj\u00f8r du?", "sv": "Du f\u00e5r reda p\u00e5 att en av dina v\u00e4nner har ljugit om sitt jobb i m\u00e5nader \u2014 vad g\u00f6r du?", "pl": "Dowiadujesz si\u0119, \u017ce jeden z twoich przyjaci\u00f3\u0142 k\u0142ama\u0142 o swojej pracy przez miesi\u0105ce \u2014 co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You find out one of your friends has been lying about their job for months — what’s your move?';
UPDATE questions
SET translations = '{"en": "Who here would start a fight at karaoke night?", "da": "Hvem her ville starte et slagsm\u00e5l til karaokeaften?", "de": "Wer hier w\u00fcrde bei einer Karaoke-Nacht einen Streit anfangen?", "es": "\u00bfQui\u00e9n aqu\u00ed empezar\u00eda una pelea en una noche de karaoke?", "pt": "Quem aqui come\u00e7aria uma briga numa noite de karaoke?", "ro": "Cine de aici ar \u00eencepe o ceart\u0103 la o sear\u0103 de karaoke?", "fr": "Qui ici commencerait une bagarre lors d\u2019une soir\u00e9e karaok\u00e9 ?", "it": "Chi qui inizierebbe una rissa durante la serata karaoke?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 aloittaisi riidan karaokey\u00f6n\u00e4?", "nl": "Wie hier zou een vechtpartij beginnen tijdens de karaoke-avond?", "no": "Hvem her ville startet en krangel p\u00e5 karaoke-kvelden?", "sv": "Vem h\u00e4r skulle starta ett br\u00e5k p\u00e5 karaoke-kv\u00e4llen?", "pl": "Kto tutaj zacz\u0105\u0142by b\u00f3jk\u0119 podczas karaoke?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who here would start a fight at karaoke night?';