UPDATE questions
SET translations = '{"en": "What\u2019s a fashion trend you\u2019ll never understand?", "da": "Hvilken modetrend vil du aldrig forst\u00e5?", "de": "Welchen Modetrend wirst du nie verstehen?", "es": "\u00bfQu\u00e9 tendencia de moda nunca entender\u00e1s?", "pt": "Qual tend\u00eancia de moda voc\u00ea nunca vai entender?", "ro": "Ce tendin\u021b\u0103 de mod\u0103 nu vei \u00een\u021belege niciodat\u0103?", "fr": "Quelle tendance mode ne comprendras-tu jamais ?", "it": "Qual \u00e8 una tendenza della moda che non capirai mai?", "fi": "Mik\u00e4 on muotitrendi, jota et koskaan tule ymm\u00e4rt\u00e4m\u00e4\u00e4n?", "nl": "Wat is een mode trend die je nooit zult begrijpen?", "no": "Hva er en motetrend du aldri vil forst\u00e5?", "sv": "Vilken modetrend kommer du aldrig att f\u00f6rst\u00e5?", "pl": "Jaki trend modowy, kt\u00f3rego nigdy nie zrozumiesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a fashion trend you’ll never understand?';
UPDATE questions
SET translations = '{"en": "What\u2019s your comfort show or book\u2014and why that one?", "da": "Hvad er dit \u201ccomfort show\u201d eller din yndlingsbog \u2014 og hvorfor netop den?", "de": "Was ist deine Komfortserie oder dein Lieblingsbuch \u2013 und warum genau das?", "es": "\u00bfCu\u00e1l es tu serie o libro de consuelo \u2014 y por qu\u00e9 ese?", "pt": "Qual \u00e9 sua s\u00e9rie ou livro de conforto \u2014 e por que esse?", "ro": "Care este serialul sau cartea ta de confort \u2014 \u0219i de ce aceea?", "fr": "Quelle est ta s\u00e9rie ou ton livre r\u00e9confortant \u2014 et pourquoi celui-l\u00e0 ?", "it": "Qual \u00e8 il tuo programma o libro di conforto\u2014e perch\u00e9 proprio quello?", "fi": "Mik\u00e4 on sinun mukavuusohjelmasi tai -kirjasi \u2013 ja miksi juuri se?", "nl": "Wat is jouw favoriete comfortshow of boek - en waarom die?", "no": "Hva er ditt komfortprogram eller bok \u2013 og hvorfor akkurat den?", "sv": "Vilken \u00e4r din trygghetsserie eller bok \u2013 och varf\u00f6r just den?", "pl": "Jaki jest tw\u00f3j ulubiony serial lub ksi\u0105\u017cka, kt\u00f3ra daje ci poczucie komfortu \u2013 i dlaczego akurat ten?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your comfort show or book—and why that one?';
UPDATE questions
SET translations = '{"en": "Who in this group would be the worst at keeping a secret?", "da": "Hvem i denne gruppe ville v\u00e6re d\u00e5rligst til at holde p\u00e5 en hemmelighed?", "de": "Wer in dieser Gruppe w\u00e4re am schlechtesten darin, ein Geheimnis zu bewahren?", "es": "\u00bfQui\u00e9n en este grupo ser\u00eda el peor guardando un secreto?", "pt": "Quem neste grupo seria o pior em guardar um segredo?", "ro": "Cine din acest grup ar fi cel mai prost la a p\u0103stra un secret?", "fr": "Qui dans ce groupe serait le pire pour garder un secret ?", "it": "Chi in questo gruppo sarebbe il peggiore a mantenere un segreto?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 olisi huonoin pit\u00e4m\u00e4\u00e4n salaisuutta?", "nl": "Wie in deze groep zou het slechtst zijn in het bewaren van een geheim?", "no": "Hvem i denne gruppen ville v\u00e6rt d\u00e5rligst til \u00e5 holde en hemmelighet?", "sv": "Vem i den h\u00e4r gruppen skulle vara s\u00e4mst p\u00e5 att h\u00e5lla en hemlighet?", "pl": "Kto w tej grupie by\u0142by najgorszy w utrzymywaniu tajemnicy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who in this group would be the worst at keeping a secret?';
UPDATE questions
SET translations = '{"en": "Is there anything embarrassing you once posted online?", "da": "Har du nogensinde lagt noget pinligt ud online?", "de": "Hast du jemals etwas Peinliches online gepostet?", "es": "\u00bfHas publicado alguna vez algo embarazoso en l\u00ednea?", "pt": "Voc\u00ea j\u00e1 postou algo constrangedor na internet?", "ro": "Ai postat vreodat\u0103 ceva jenant online?", "fr": "As-tu d\u00e9j\u00e0 post\u00e9 quelque chose d\u2019embarrassant en ligne ?", "it": "C''\u00e8 qualcosa di imbarazzante che hai postato online una volta?", "fi": "Onko jotain h\u00e4pe\u00e4llist\u00e4, mit\u00e4 olet joskus julkaissut verkossa?", "nl": "Is er iets beschamends dat je ooit online hebt gepost?", "no": "Er det noe pinlig du en gang la ut p\u00e5 nettet?", "sv": "\u00c4r det n\u00e5got pinsamt som du en g\u00e5ng postade online?", "pl": "Czy jest co\u015b kr\u0119puj\u0105cego, co kiedy\u015b opublikowa\u0142e\u015b w internecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Is there anything embarrassing you once posted online?';
UPDATE questions
SET translations = '{"en": "Who in this room would make the best celebrity?", "da": "Hvem i dette rum ville blive den bedste kendis?", "de": "Wer in diesem Raum w\u00e4re der beste Promi?", "es": "\u00bfQui\u00e9n en esta sala ser\u00eda la mejor celebridad?", "pt": "Quem nesta sala seria a melhor celebridade?", "ro": "Cine din aceast\u0103 camer\u0103 ar deveni cea mai bun\u0103 celebritate?", "fr": "Qui dans cette pi\u00e8ce ferait la meilleure c\u00e9l\u00e9brit\u00e9 ?", "it": "Chi in questa stanza diventerebbe la migliore celebrit\u00e0?", "fi": "Kuka t\u00e4ss\u00e4 huoneessa olisi paras julkkis?", "nl": "Wie in deze kamer zou de beste beroemdheid zijn?", "no": "Hvem i dette rommet ville blitt den beste kjendisen?", "sv": "Vem i det h\u00e4r rummet skulle bli den b\u00e4sta k\u00e4ndisen?", "pl": "Kto w tym pomieszczeniu by\u0142by najlepsz\u0105 gwiazd\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who in this room would make the best celebrity?';
UPDATE questions
SET translations = '{"en": "If you could change one thing about modern dating culture, what would it be?", "da": "Hvis du kunne \u00e6ndre \u00e9n ting ved moderne datingkultur, hvad skulle det v\u00e6re?", "de": "Wenn du eine Sache an der modernen Datingkultur \u00e4ndern k\u00f6nntest, was w\u00e4re das?", "es": "Si pudieras cambiar una cosa de la cultura moderna de citas, \u00bfqu\u00e9 ser\u00eda?", "pt": "Se voc\u00ea pudesse mudar uma coisa na cultura moderna de namoro, o que seria?", "ro": "Dac\u0103 ai putea schimba un lucru \u00een cultura modern\u0103 a \u00eent\u00e2lnirilor, care ar fi?", "fr": "Si tu pouvais changer une chose dans la culture moderne des rencontres, que serait-ce ?", "it": "Se potessi cambiare una cosa della cultura moderna degli appuntamenti, quale sarebbe?", "fi": "Jos voisit muuttaa yhden asian nykyp\u00e4iv\u00e4n deittailukulttuurissa, mik\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n ding aan de moderne datingcultuur zou kunnen veranderen, wat zou dat dan zijn?", "no": "Hvis du kunne endre \u00e9n ting med den moderne datingkulturen, hva ville det v\u00e6rt?", "sv": "Om du kunde f\u00f6r\u00e4ndra en sak med den moderna dejtingkulturen, vad skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zmieni\u0107 jedn\u0105 rzecz w nowoczesnej kulturze randkowania, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could change one thing about modern dating culture, what would it be?';
UPDATE questions
SET translations = '{"en": "If gossip were a sport, who here would win gold?", "da": "Hvis sladder var en sport, hvem her ville vinde guld?", "de": "Wenn Klatsch eine Sportart w\u00e4re, wer hier w\u00fcrde Gold gewinnen?", "es": "Si el chisme fuera un deporte, \u00bfqui\u00e9n aqu\u00ed ganar\u00eda el oro?", "pt": "Se fofoca fosse um esporte, quem aqui ganharia ouro?", "ro": "Dac\u0103 b\u00e2rfa ar fi un sport, cine de aici ar c\u00e2\u0219tiga aurul?", "fr": "Si les comm\u00e9rages \u00e9taient un sport, qui ici remporterait l\u2019or ?", "it": "Se il pettegolezzo fosse uno sport, chi qui vincerebbe l''oro?", "fi": "Jos juoruilu olisi urheilulaji, kuka t\u00e4\u00e4ll\u00e4 voittaisi kultamitalin?", "nl": "Als roddelen een sport was, wie hier zou dan goud winnen?", "no": "Hvis sladder var en sport, hvem her ville vinne gull?", "sv": "Om skvaller vore en sport, vem h\u00e4r skulle vinna guld?", "pl": "Gdyby plotki by\u0142y sportem, kto tutaj zdoby\u0142by z\u0142oty medal?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If gossip were a sport, who here would win gold?';
UPDATE questions
SET translations = '{"en": "If your high school classmates saw you now, what would surprise them most?", "da": "Hvis dine skolekammerater s\u00e5 dig nu, hvad ville overraske dem mest?", "de": "Wenn deine Schulfreunde dich jetzt sehen w\u00fcrden, was w\u00fcrde sie am meisten \u00fcberraschen?", "es": "Si tus compa\u00f1eros de escuela te vieran ahora, \u00bfqu\u00e9 los sorprender\u00eda m\u00e1s?", "pt": "Se seus colegas de escola te vissem agora, o que mais os surpreenderia?", "ro": "Dac\u0103 colegii t\u0103i de liceu te-ar vedea acum, ce i-ar surprinde cel mai mult?", "fr": "Si tes anciens camarades de classe te voyaient maintenant, qu\u2019est-ce qui les surprendrait le plus ?", "it": "Se i tuoi compagni di scuola superiore ti vedessero adesso, cosa li sorprenderebbe di pi\u00f9?", "fi": "Jos lukioaikaiset luokkatoverisi n\u00e4kiv\u00e4t sinut nyt, mik\u00e4 heit\u00e4 yll\u00e4tt\u00e4isi eniten?", "nl": "Als je middelbare schoolklasgenoten je nu zouden zien, wat zou hen dan het meest verbazen?", "no": "Hvis klassekameratene dine fra videreg\u00e5ende s\u00e5 deg n\u00e5, hva ville overrasket dem mest?", "sv": "Om dina gymnasieklasskamrater s\u00e5g dig nu, vad skulle \u00f6verraska dem mest?", "pl": "Gdyby twoi koledzy z liceum zobaczyli ci\u0119 teraz, co najbardziej by ich zaskoczy\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If your high school classmates saw you now, what would surprise them most?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you once pretended to understand but totally didn\u2019t?", "da": "Hvad har du engang ladet som om, du forstod, men faktisk ikke gjorde?", "de": "Was hast du einmal vorgegeben zu verstehen, obwohl du es nicht tatest?", "es": "\u00bfQu\u00e9 fingiste entender alguna vez pero realmente no entendiste?", "pt": "O que voc\u00ea fingiu entender, mas na verdade n\u00e3o entendeu?", "ro": "Ce ai pretins odat\u0103 c\u0103 \u00een\u021belegi, dar nu ai \u00een\u021beles de fapt?", "fr": "Qu\u2019as-tu d\u00e9j\u00e0 pr\u00e9tendu comprendre alors que tu ne comprenais pas du tout ?", "it": "Qualcosa che una volta hai fatto finta di capire ma in realt\u00e0 non capivi affatto?", "fi": "Mik\u00e4 on jotain, mit\u00e4 kerran teeskentelit ymm\u00e4rt\u00e4v\u00e4si, mutta et todellakaan ymm\u00e4rt\u00e4nyt?", "nl": "Wat is iets waarvan je ooit deed alsof je het begreep, maar dat totaal niet deed?", "no": "Hva er noe du en gang lot som du forsto, men som du absolutt ikke gjorde?", "sv": "Vad \u00e4r n\u00e5got du en g\u00e5ng l\u00e5tsades f\u00f6rst\u00e5 men verkligen inte gjorde?", "pl": "Co\u015b, co kiedy\u015b udawa\u0142e\u015b, \u017ce rozumiesz, ale tak naprawd\u0119 nie mia\u0142e\u015b poj\u0119cia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you once pretended to understand but totally didn’t?';
UPDATE questions
SET translations = '{"en": "Who here do you think flirts without even realizing it?", "da": "Hvem her tror du flirter uden at vide det?", "de": "Wer hier flirtet, ohne es zu merken?", "es": "\u00bfQui\u00e9n aqu\u00ed crees que coquetea sin darse cuenta?", "pt": "Quem aqui voc\u00ea acha que flerta sem perceber?", "ro": "Cine de aici flirteaz\u0103 f\u0103r\u0103 s\u0103-\u0219i dea seama?", "fr": "Qui ici flirte sans m\u00eame s\u2019en rendre compte ?", "it": "Chi pensi qui flirta senza nemmeno rendersene conto?", "fi": "Kuka t\u00e4\u00e4ll\u00e4 mielest\u00e4si flirttailee ilman, ett\u00e4 edes huomaa sit\u00e4?", "nl": "Wie denk je dat hier flirt zonder het zelfs maar te beseffen?", "no": "Hvem her tror du fl\u00f8rter uten engang \u00e5 innse det?", "sv": "Vem h\u00e4r tror du fl\u00f6rtar utan att ens inse det?", "pl": "Kto tutaj, twoim zdaniem, flirtuje, nawet tego nie zauwa\u017caj\u0105c?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who here do you think flirts without even realizing it?';