UPDATE questions
SET translations = '{"en": "Would you rather work from home forever or never work weekends again?", "da": "Ville du hellere arbejde hjemme for evigt eller aldrig arbejde i weekender igen?", "de": "W\u00fcrdest du lieber f\u00fcr immer von zu Hause arbeiten oder nie wieder an Wochenenden arbeiten?", "es": "\u00bfPreferir\u00edas trabajar desde casa para siempre o no trabajar nunca m\u00e1s los fines de semana?", "pt": "Preferias trabalhar em casa para sempre ou nunca mais trabalhar aos fins de semana?", "ro": "Ai prefera s\u0103 lucrezi mereu de acas\u0103 sau s\u0103 nu mai lucrezi niciodat\u0103 \u00een weekend?", "fr": "Pr\u00e9f\u00e9rerais-tu travailler \u00e0 domicile pour toujours ou ne plus jamais travailler le week-end ?", "it": "Preferiresti lavorare da casa per sempre o non lavorare mai pi\u00f9 nei fine settimana?", "fi": "Haluaisitko ty\u00f6skennell\u00e4 kotoa ikuisesti vai et koskaan en\u00e4\u00e4 tehd\u00e4 t\u00f6it\u00e4 viikonloppuisin?", "nl": "Zou je liever voor altijd thuiswerken of nooit meer in het weekend werken?", "no": "Ville du helst jobbe hjemmefra for alltid eller aldri jobbe helger igjen?", "sv": "Skulle du hellre arbeta hemifr\u00e5n f\u00f6r alltid eller aldrig mer arbeta p\u00e5 helger?", "pl": "Czy wola\u0142by\u015b pracowa\u0107 z domu na zawsze, czy nigdy wi\u0119cej nie pracowa\u0107 w weekendy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather work from home forever or never work weekends again?';
UPDATE questions
SET translations = '{"en": "Would you rather go camping or stay in a nice hotel?", "da": "Ville du hellere tage p\u00e5 camping eller bo p\u00e5 et flot hotel?", "de": "W\u00fcrdest du lieber campen gehen oder in einem sch\u00f6nen Hotel \u00fcbernachten?", "es": "\u00bfPreferir\u00edas ir de campamento o alojarte en un bonito hotel?", "pt": "Preferias acampar ou ficar num bom hotel?", "ro": "Ai prefera s\u0103 mergi cu cortul sau s\u0103 stai \u00eentr-un hotel frumos?", "fr": "Pr\u00e9f\u00e9rerais-tu faire du camping ou s\u00e9journer dans un bel h\u00f4tel ?", "it": "Preferiresti andare in campeggio o restare in un bel hotel?", "fi": "Haluaisitko mieluummin menn\u00e4 telttailemaan vai j\u00e4\u00e4d\u00e4 mukavaan hotelliin?", "nl": "Zou je liever gaan kamperen of in een mooi hotel blijven?", "no": "Ville du heller dra p\u00e5 camping eller bo p\u00e5 et fint hotell?", "sv": "Skulle du hellre campa eller bo p\u00e5 ett fint hotell?", "pl": "Czy wola\u0142by\u015b pojecha\u0107 na camping, czy zatrzyma\u0107 si\u0119 w \u0142adnym hotelu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather go camping or stay in a nice hotel?';
UPDATE questions
SET translations = '{"en": "Would you rather always be 10 minutes early or 10 minutes late?", "da": "Ville du hellere altid komme 10 minutter for tidligt eller 10 minutter for sent?", "de": "W\u00e4rst du lieber immer 10 Minuten zu fr\u00fch oder 10 Minuten zu sp\u00e4t?", "es": "\u00bfPreferir\u00edas llegar siempre 10 minutos antes o 10 minutos tarde?", "pt": "Preferias chegar sempre 10 minutos mais cedo ou 10 minutos mais tarde?", "ro": "Ai prefera s\u0103 ajungi mereu cu 10 minute mai devreme sau mai t\u00e2rziu?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours arriver 10 minutes en avance ou 10 minutes en retard ?", "it": "Preferiresti essere sempre 10 minuti in anticipo o 10 minuti in ritardo?", "fi": "Haluaisitko mieluummin olla aina 10 minuuttia etuajassa vai 10 minuuttia my\u00f6h\u00e4ss\u00e4?", "nl": "Zou je liever altijd 10 minuten te vroeg of 10 minuten te laat zijn?", "no": "Ville du heller alltid v\u00e6re 10 minutter tidlig eller 10 minutter sent?", "sv": "Skulle du hellre alltid vara 10 minuter tidig eller 10 minuter sen?", "pl": "Czy wola\u0142by\u015b zawsze by\u0107 10 minut wcze\u015bniej czy 10 minut sp\u00f3\u017aniony?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always be 10 minutes early or 10 minutes late?';
UPDATE questions
SET translations = '{"en": "Would you rather have an unlimited gift card to your favorite restaurant or your favorite clothing store?", "da": "Ville du hellere have et ubegr\u00e6nset gavekort til din yndlingsrestaurant eller yndlingsbutik?", "de": "W\u00fcrdest du lieber eine unbegrenzte Geschenkkarte f\u00fcr dein Lieblingsrestaurant oder dein Lieblingsgesch\u00e4ft haben?", "es": "\u00bfPreferir\u00edas tener una tarjeta de regalo ilimitada para tu restaurante favorito o para tu tienda de ropa favorita?", "pt": "Preferias ter um cart\u00e3o-presente ilimitado para o teu restaurante favorito ou loja de roupa favorita?", "ro": "Ai prefera un card cadou nelimitat la restaurantul preferat sau la magazinul preferat?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir une carte cadeau illimit\u00e9e pour ton restaurant pr\u00e9f\u00e9r\u00e9 ou ton magasin pr\u00e9f\u00e9r\u00e9 ?", "it": "Preferiresti avere una carta regalo illimitata per il tuo ristorante preferito o per il tuo negozio di abbigliamento preferito?", "fi": "Haluaisitko mieluummin rajattoman lahjakortin suosikkiravintolaasi vai suosikkivaateliikkeeseesi?", "nl": "Zou je liever een onbeperkte cadeaubon hebben voor je favoriete restaurant of voor je favoriete kledingwinkel?", "no": "Ville du heller hatt et ubegrenset gavekort til din favorittrestaurant eller din favorittkl\u00e6rbutikk?", "sv": "Skulle du hellre ha ett obegr\u00e4nsat presentkort till din favoritrestaurang eller din favoritkl\u00e4dbutik?", "pl": "Czy wola\u0142by\u015b mie\u0107 niesko\u0144czon\u0105 kart\u0119 podarunkow\u0105 do swojej ulubionej restauracji, czy do swojego ulubionego sklepu odzie\u017cowego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have an unlimited gift card to your favorite restaurant or your favorite clothing store?';
UPDATE questions
SET translations = '{"en": "Would you rather have dinner with your favorite celebrity or your favorite fictional character?", "da": "Ville du hellere spise middag med din yndlingsber\u00f8mthed eller din yndlingsfiktive karakter?", "de": "W\u00fcrdest du lieber mit deinem Lieblingspromi oder deiner Lieblingsfigur essen?", "es": "\u00bfPreferir\u00edas cenar con tu celebridad favorita o con tu personaje ficticio favorito?", "pt": "Preferias jantar com a tua celebridade favorita ou com a tua personagem fict\u00edcia favorita?", "ro": "Ai prefera s\u0103 iei cina cu vedeta preferat\u0103 sau cu personajul t\u0103u fictiv preferat?", "fr": "Pr\u00e9f\u00e9rerais-tu d\u00eener avec ta c\u00e9l\u00e9brit\u00e9 pr\u00e9f\u00e9r\u00e9e ou ton personnage fictif pr\u00e9f\u00e9r\u00e9 ?", "it": "Preferiresti cenare con il tuo celebre preferito o con il tuo personaggio di fantasia preferito?", "fi": "Haluaisitko mieluummin illallistaa lempijulkkiksesi kanssa vai lempihahmosi kanssa fiktiosta?", "nl": "Zou je liever dineren met je favoriete beroemdheid of je favoriete fictieve personage?", "no": "Ville du heller ha middag med din favorittkjendis eller din favorittfiktive karakter?", "sv": "Skulle du hellre \u00e4ta middag med din favoritber\u00f6mdhet eller din favoritfiktiva karakt\u00e4r?", "pl": "Czy wola\u0142by\u015b zje\u015b\u0107 kolacj\u0119 ze swoj\u0105 ulubion\u0105 gwiazd\u0105, czy z ulubion\u0105 postaci\u0105 fikcyjn\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have dinner with your favorite celebrity or your favorite fictional character?';
UPDATE questions
SET translations = '{"en": "Would you rather take a road trip across your country or travel abroad for a week?", "da": "Ville du hellere tage p\u00e5 roadtrip i dit eget land eller rejse til udlandet i en uge?", "de": "W\u00fcrdest du lieber eine Autoreise durch dein Land oder eine Auslandsreise f\u00fcr eine Woche machen?", "es": "\u00bfPreferir\u00edas hacer un viaje por carretera por tu pa\u00eds o viajar al extranjero por una semana?", "pt": "Preferias fazer uma viagem de carro pelo teu pa\u00eds ou viajar para o estrangeiro por uma semana?", "ro": "Ai prefera un roadtrip prin \u021bar\u0103 sau o s\u0103pt\u0103m\u00e2n\u0103 \u00een str\u0103in\u0103tate?", "fr": "Pr\u00e9f\u00e9rerais-tu faire un road trip dans ton pays ou voyager \u00e0 l\u2019\u00e9tranger pendant une semaine ?", "it": "Preferiresti fare un viaggio in auto attraverso il tuo paese o viaggiare all''estero per una settimana?", "fi": "Haluaisitko mieluummin tehd\u00e4 automatkan ymp\u00e4ri maata vai matkustaa ulkomaille viikoksi?", "nl": "Zou je liever een roadtrip door je eigen land maken of een week naar het buitenland reizen?", "no": "Ville du heller ta en biltur over landet ditt eller reise til utlandet i en uke?", "sv": "Skulle du hellre ta en bilresa genom ditt land eller resa utomlands i en vecka?", "pl": "Czy wola\u0142by\u015b pojecha\u0107 w podr\u00f3\u017c samochodow\u0105 po swoim kraju, czy wyjecha\u0107 za granic\u0119 na tydzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather take a road trip across your country or travel abroad for a week?';
UPDATE questions
SET translations = '{"en": "Would you rather always have clean sheets or always have your favorite meal ready?", "da": "Ville du hellere altid have rene lagner eller altid f\u00e5 din yndlingsret serveret?", "de": "W\u00fcrdest du lieber immer frische Bettw\u00e4sche oder immer dein Lieblingsgericht fertig haben?", "es": "\u00bfPreferir\u00edas tener siempre s\u00e1banas limpias o tu comida favorita lista?", "pt": "Preferias ter sempre len\u00e7\u00f3is limpos ou a tua refei\u00e7\u00e3o favorita pronta?", "ro": "Ai prefera s\u0103 ai mereu a\u0219ternuturi curate sau m\u00e2ncarea preferat\u0103 gata?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours avoir des draps propres ou ton plat pr\u00e9f\u00e9r\u00e9 pr\u00eat ?", "it": "Preferiresti avere sempre lenzuola pulite o avere sempre il tuo piatto preferito pronto?", "fi": "Haluaisitko mieluummin aina puhtaat lakanat vai ett\u00e4 lempiruokasi olisi aina valmiina?", "nl": "Zou je liever altijd schone lakens hebben of altijd je favoriete maaltijd klaar hebben?", "no": "Ville du heller alltid ha rene laken eller alltid ha favorittm\u00e5ltidet ditt klart?", "sv": "Skulle du hellre alltid ha rena lakan eller alltid ha din favoritr\u00e4tt redo?", "pl": "Czy wola\u0142by\u015b zawsze mie\u0107 czyste prze\u015bcierad\u0142a, czy zawsze mie\u0107 gotowe swoje ulubione danie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always have clean sheets or always have your favorite meal ready?';
UPDATE questions
SET translations = '{"en": "Would you rather win the lottery or have your dream job?", "da": "Ville du hellere vinde i lotto eller have dit dr\u00f8mmejob?", "de": "W\u00fcrdest du lieber im Lotto gewinnen oder deinen Traumjob haben?", "es": "\u00bfPreferir\u00edas ganar la loter\u00eda o tener tu trabajo so\u00f1ado?", "pt": "Preferias ganhar na lotaria ou ter o emprego dos teus sonhos?", "ro": "Ai prefera s\u0103 c\u00e2\u0219tigi la loto sau s\u0103 ai jobul visurilor tale?", "fr": "Pr\u00e9f\u00e9rerais-tu gagner \u00e0 la loterie ou avoir ton emploi de r\u00eave ?", "it": "Preferiresti vincere la lotteria o avere il lavoro dei tuoi sogni?", "fi": "Haluaisitko mieluummin voittaa lotossa vai saada unelmaty\u00f6si?", "nl": "Zou je liever de loterij winnen of je droombaan hebben?", "no": "Ville du heller vinne i lotto eller ha dr\u00f8mmejobben din?", "sv": "Skulle du hellre vinna p\u00e5 lotteriet eller ha ditt dr\u00f6mjobb?", "pl": "Czy wola\u0142by\u015b wygra\u0107 na loterii, czy mie\u0107 wymarzon\u0105 prac\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather win the lottery or have your dream job?';
UPDATE questions
SET translations = '{"en": "Would you rather spend your birthday doing something adventurous or relaxing?", "da": "Ville du hellere fejre din f\u00f8dselsdag med noget vildt eller afslappende?", "de": "W\u00fcrdest du lieber deinen Geburtstag abenteuerlich oder entspannt verbringen?", "es": "\u00bfPreferir\u00edas pasar tu cumplea\u00f1os haciendo algo aventurero o relajante?", "pt": "Preferias passar o teu anivers\u00e1rio a fazer algo aventureiro ou relaxante?", "ro": "Ai prefera s\u0103-\u021bi petreci ziua f\u0103c\u00e2nd ceva aventuros sau relaxant?", "fr": "Pr\u00e9f\u00e9rerais-tu passer ton anniversaire \u00e0 faire quelque chose d\u2019aventureux ou de relaxant ?", "it": "Preferiresti trascorrere il tuo compleanno facendo qualcosa di avventuroso o rilassante?", "fi": "Haluaisitko viett\u00e4\u00e4 syntym\u00e4p\u00e4iv\u00e4\u00e4si tekem\u00e4ll\u00e4 jotain seikkailullista vai rentoutumalla?", "nl": "Zou je liever je verjaardag doorbrengen met iets avontuurlijks of met ontspannen?", "no": "Ville du heller tilbringe bursdagen din med \u00e5 gj\u00f8re noe eventyrlig eller avslappende?", "sv": "Skulle du hellre spendera din f\u00f6delsedag med att g\u00f6ra n\u00e5got \u00e4ventyrligt eller avslappnande?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 swoje urodziny na czym\u015b przygodowym, czy raczej na relaksie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend your birthday doing something adventurous or relaxing?';
UPDATE questions
SET translations = '{"en": "Would you rather live in the city or the countryside?", "da": "Ville du hellere bo i byen eller p\u00e5 landet?", "de": "W\u00fcrdest du lieber in der Stadt oder auf dem Land leben?", "es": "\u00bfPreferir\u00edas vivir en la ciudad o en el campo?", "pt": "Preferias viver na cidade ou no campo?", "ro": "Ai prefera s\u0103 tr\u0103ie\u0219ti \u00een ora\u0219 sau la \u021bar\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre en ville ou \u00e0 la campagne ?", "it": "Preferiresti vivere in citt\u00e0 o in campagna?", "fi": "Haluaisitko mieluummin asua kaupungissa vai maalla?", "nl": "Zou je liever in de stad of op het platteland wonen?", "no": "Ville du heller bo i byen eller p\u00e5 landet?", "sv": "Skulle du hellre bo i staden eller p\u00e5 landsbygden?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 w mie\u015bcie, czy na wsi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live in the city or the countryside?';