UPDATE questions
SET translations = '{"en": "\u201cAudiobooks count as reading \u2014 maybe even better than books.\u201d", "da": "Lydb\u00f8ger t\u00e6ller som l\u00e6sning \u2013 m\u00e5ske endda bedre end b\u00f8ger.", "de": "H\u00f6rb\u00fccher z\u00e4hlen als Lesen \u2013 vielleicht sogar besser als B\u00fccher.", "es": "Los audiolibros cuentan como lectura \u2014 quiz\u00e1s incluso mejor que los libros.", "pt": "Os audiolivros contam como leitura \u2014 talvez at\u00e9 melhor do que os livros.", "ro": "C\u0103r\u021bile audio se pun ca lectur\u0103 \u2014 poate chiar mai bune dec\u00e2t c\u0103r\u021bile.", "fr": "Les livres audio comptent comme de la lecture \u2014 voire mieux que les livres.", "it": "\u201cGli audiolibri contano come lettura \u2014 forse anche meglio dei libri.\u201d", "fi": "\"\u00c4\u00e4nikirjat lasketaan lukemiseksi \u2014 ehk\u00e4 jopa paremmiksi kuin kirjat.\"", "nl": "\"Luisterboeken tellen als lezen \u2014 misschien zelfs beter dan boeken.\"", "no": "\"Lydb\u00f8ker teller som lesing \u2014 kanskje til og med bedre enn b\u00f8ker.\"", "sv": "\"Lyssna p\u00e5 b\u00f6cker r\u00e4knas som l\u00e4sning \u2014 kanske till och med b\u00e4ttre \u00e4n b\u00f6cker.\"", "pl": "\u201eAudiobooki licz\u0105 si\u0119 jako czytanie \u2014 mo\u017ce nawet lepiej ni\u017c ksi\u0105\u017cki.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Audiobooks count as reading — maybe even better than books.”';
UPDATE questions
SET translations = '{"en": "\u201cYou should judge people by their digital footprint, not just appearance.\u201d", "da": "Du b\u00f8r bed\u00f8mme folk efter deres digitale fodaftryk, ikke kun udseende.", "de": "Man sollte Menschen nach ihrem digitalen Fu\u00dfabdruck beurteilen, nicht nur nach dem Aussehen.", "es": "Deber\u00edas juzgar a las personas por su huella digital, no solo por su apariencia.", "pt": "Devemos julgar as pessoas pela sua pegada digital, n\u00e3o apenas pela apar\u00eancia.", "ro": "Ar trebui s\u0103 judeci oamenii dup\u0103 amprenta lor digital\u0103, nu doar dup\u0103 aspect.", "fr": "On devrait juger les gens selon leur empreinte num\u00e9rique, pas seulement leur apparence.", "it": "\"Dovresti giudicare le persone in base alla loro impronta digitale, non solo all''aspetto.\"", "fi": "\"Sinun pit\u00e4isi arvioida ihmisi\u00e4 heid\u00e4n digitaalisen jalanj\u00e4lkens\u00e4 perusteella, ei vain ulkon\u00e4\u00f6n.\"", "nl": "\"Je zou mensen moeten beoordelen op hun digitale voetafdruk, niet alleen op hun uiterlijk.\"", "no": "\"Du b\u00f8r d\u00f8mme folk etter deres digitale fotavtrykk, ikke bare utseende.\"", "sv": "\"Du borde d\u00f6ma m\u00e4nniskor utifr\u00e5n deras digitala fotavtryck, inte bara utseende.\"", "pl": "\u201ePowiniene\u015b ocenia\u0107 ludzi po ich \u015bladzie cyfrowym, a nie tylko po wygl\u0105dzie.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You should judge people by their digital footprint, not just appearance.”';
UPDATE questions
SET translations = '{"en": "\u201cEveryone should be required to serve in some form (civil, military, ambiental) for a year.\u201d", "da": "Alle burde v\u00e6re forpligtet til at tjene et \u00e5r i en form for tjeneste (civil, milit\u00e6r, milj\u00f8).", "de": "Jeder sollte verpflichtet sein, ein Jahr in irgendeiner Form von Dienst (zivil, milit\u00e4risch, \u00f6kologisch) zu leisten.", "es": "Todos deber\u00edan estar obligados a servir durante un a\u00f1o en alguna forma (civil, militar, ambiental).", "pt": "Todos deveriam ser obrigados a servir durante um ano em alguma forma (civil, militar, ambiental).", "ro": "To\u021bi ar trebui s\u0103 fie obliga\u021bi s\u0103 serveasc\u0103 un an \u00eentr-o form\u0103 de serviciu (civil, militar, ecologic).", "fr": "Tout le monde devrait \u00eatre tenu de servir pendant un an sous une forme (civile, militaire, environnementale).", "it": "\u201cTutti dovrebbero essere obbligati a servire in qualche forma (civile, militare, ambientale) per un anno.\u201d", "fi": "\"Kaikkien tulisi olla velvollisia palvelemaan jollain tavalla (kansalais-, sotilas-, ymp\u00e4rist\u00f6hankkeissa) vuoden ajan.\"", "nl": "\" Iedereen zou verplicht moeten zijn om een jaar op de een of andere manier (civiel, militair, milieu) te dienen.\"", "no": "\"Alle b\u00f8r v\u00e6re p\u00e5lagt \u00e5 tjene i en eller annen form (sivil, milit\u00e6r, milj\u00f8messig) i ett \u00e5r.\"", "sv": "\"Alla borde vara skyldiga att tj\u00e4nstg\u00f6ra i n\u00e5gon form (civil, milit\u00e4r, milj\u00f6) i ett \u00e5r.\"", "pl": "\u201eKa\u017cdy powinien by\u0107 zobowi\u0105zany do s\u0142u\u017cby w jakiej\u015b formie (cywilnej, wojskowej, \u015brodowiskowej) przez rok.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Everyone should be required to serve in some form (civil, military, ambiental) for a year.”';
UPDATE questions
SET translations = '{"en": "\u201cMonuments to historical figures who were flawed should be destroyed, not contextualized.\u201d", "da": "Monumenter for historiske personer med fejl b\u00f8r \u00f8del\u00e6gges, ikke kontekstualiseres.", "de": "Denkm\u00e4ler f\u00fcr fehlerhafte historische Pers\u00f6nlichkeiten sollten zerst\u00f6rt, nicht kontextualisiert werden.", "es": "Los monumentos a figuras hist\u00f3ricas con defectos deber\u00edan ser destruidos, no contextualizados.", "pt": "Os monumentos a figuras hist\u00f3ricas com falhas deveriam ser destru\u00eddos, n\u00e3o contextualizados.", "ro": "Monumentele dedicate persoanelor istorice care au gre\u0219it ar trebui distruse, nu contextualizate.", "fr": "Les monuments d\u00e9di\u00e9s \u00e0 des figures historiques imparfaites devraient \u00eatre d\u00e9truits, pas contextualis\u00e9s.", "it": "\"I monumenti a figure storiche che avevano dei difetti dovrebbero essere distrutti, non contestualizzati.\"", "fi": "\"Historiallisten henkil\u00f6iden, joilla oli puutteita, muistomerkit tulisi tuhota, ei kontekstualisoida.\"", "nl": "\"Monumenten voor historische figuren die gebreken hadden, zouden vernietigd moeten worden, niet gecontextualiseerd.\"", "no": "\"Monumenter til historiske personer som hadde feil, b\u00f8r \u00f8delegges, ikke kontekstualiseres.\"", "sv": "\"Monument till historiska personer som hade brister b\u00f6r rivas, inte kontextualiseras.\"", "pl": "\u201ePomniki historycznych postaci, kt\u00f3re mia\u0142y wady, powinny zosta\u0107 zniszczone, a nie kontekstualizowane.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Monuments to historical figures who were flawed should be destroyed, not contextualized.”';
UPDATE questions
SET translations = '{"en": "\u201cNational borders are morally arbitrary.\u201d", "da": "Nationale gr\u00e6nser er moralsk vilk\u00e5rlige.", "de": "Nationale Grenzen sind moralisch willk\u00fcrlich.", "es": "Las fronteras nacionales son moralmente arbitrarias.", "pt": "As fronteiras nacionais s\u00e3o moralmente arbitr\u00e1rias.", "ro": "Grani\u021bele na\u021bionale sunt arbitrare din punct de vedere moral.", "fr": "Les fronti\u00e8res nationales sont moralement arbitraires.", "it": "\"Le frontiere nazionali sono moralmente arbitrarie.\"", "fi": "\"Kansalliset rajat ovat moraalisesti satunnaisia.\"", "nl": "\"Nationale grenzen zijn moreel willekeurig.\"", "no": "\"Nasjonsgrenser er moralsk vilk\u00e5rlige.\"", "sv": "\"Nationella gr\u00e4nser \u00e4r moraliskt godtyckliga.\"", "pl": "\u201eGranice narodowe s\u0105 moralnie arbitralne.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“National borders are morally arbitrary.”';
UPDATE questions
SET translations = '{"en": "\u201cImmigration is overwhelmingly beneficial to any country.\u201d", "da": "Immigration er overvejende gavnlig for ethvert land.", "de": "Einwanderung ist f\u00fcr jedes Land \u00fcberwiegend vorteilhaft.", "es": "La inmigraci\u00f3n es abrumadoramente beneficiosa para cualquier pa\u00eds.", "pt": "A imigra\u00e7\u00e3o \u00e9 esmagadoramente ben\u00e9fica para qualquer pa\u00eds.", "ro": "Imigra\u021bia este cov\u00e2r\u0219itor benefic\u0103 pentru orice \u021bar\u0103.", "fr": "L\u2019immigration est largement b\u00e9n\u00e9fique pour tout pays.", "it": "\"L''immigrazione \u00e8 straordinariamente vantaggiosa per qualsiasi paese.\"", "fi": "\"Maahanmuutto on ylivoimaisesti hy\u00f6dyllist\u00e4 mille tahansa maalle.\"", "nl": "\"Immigratie is overwegend voordelig voor elk land.\"", "no": "\"Immigrasjon er overveldende gunstig for ethvert land.\"", "sv": "\"Invandring \u00e4r \u00f6verv\u00e4ldigande f\u00f6rdelaktigt f\u00f6r vilket land som helst.\"", "pl": "\u201eImigracja jest w przewa\u017caj\u0105cej mierze korzystna dla ka\u017cdego kraju.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Immigration is overwhelmingly beneficial to any country.”';
UPDATE questions
SET translations = '{"en": "\u201cOpen borders is a better policy than strict immigration control.\u201d", "da": "\u00c5bne gr\u00e6nser er en bedre politik end streng immigrationskontrol.", "de": "Offene Grenzen sind eine bessere Politik als strenge Einwanderungskontrolle.", "es": "Las fronteras abiertas son una mejor pol\u00edtica que el control migratorio estricto.", "pt": "Fronteiras abertas s\u00e3o uma pol\u00edtica melhor do que o controlo rigoroso da imigra\u00e7\u00e3o.", "ro": "Grani\u021bele deschise sunt o politic\u0103 mai bun\u0103 dec\u00e2t controlul strict al imigra\u021biei.", "fr": "Les fronti\u00e8res ouvertes sont une meilleure politique qu\u2019un contr\u00f4le migratoire strict.", "it": "\"Le frontiere aperte sono una politica migliore rispetto a un controllo rigoroso dell''immigrazione.\"", "fi": "\"Avoimet rajat ovat parempi politiikka kuin tiukka maahanmuuttopolitiikka.\"", "nl": "\"Open grenzen is een betere beleidskeuze dan strikte immigratiecontrole.\"", "no": "\"\u00c5pne grenser er en bedre politikk enn streng innvandringskontroll.\"", "sv": "\"\u00d6ppna gr\u00e4nser \u00e4r en b\u00e4ttre politik \u00e4n strikt invandringskontroll.\"", "pl": "\u201eOtwarte granice to lepsza polityka ni\u017c surowa kontrola imigracyjna.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Open borders is a better policy than strict immigration control.”';
UPDATE questions
SET translations = '{"en": "\u201cUniversal healthcare should be global, not just national.\u201d", "da": "Universel sundhedspleje b\u00f8r v\u00e6re global, ikke kun national.", "de": "Universelle Gesundheitsversorgung sollte global, nicht nur national sein.", "es": "La atenci\u00f3n m\u00e9dica universal deber\u00eda ser global, no solo nacional.", "pt": "A sa\u00fade universal deveria ser global, n\u00e3o apenas nacional.", "ro": "Asisten\u021ba medical\u0103 universal\u0103 ar trebui s\u0103 fie global\u0103, nu doar na\u021bional\u0103.", "fr": "Les soins de sant\u00e9 universels devraient \u00eatre mondiaux, pas seulement nationaux.", "it": "\"La sanit\u00e0 universale dovrebbe essere globale, non solo nazionale.\"", "fi": "\"Yleinen terveydenhuolto pit\u00e4isi olla globaalia, ei vain kansallista.\"", "nl": "\"Universele gezondheidszorg zou wereldwijd moeten zijn, niet alleen nationaal.\"", "no": "\"Universell helseomsorg b\u00f8r v\u00e6re global, ikke bare nasjonal.\"", "sv": "\"Universell sjukv\u00e5rd b\u00f6r vara global, inte bara nationell.\"", "pl": "\u201eOpieka zdrowotna powinna by\u0107 globalna, a nie tylko krajowa.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Universal healthcare should be global, not just national.”';
UPDATE questions
SET translations = '{"en": "\u201cVaccination mandates violate bodily autonomy.\u201d", "da": "Vaccinetvang kr\u00e6nker kropslig autonomi.", "de": "Impfpflichten verletzen die k\u00f6rperliche Autonomie.", "es": "Los mandatos de vacunaci\u00f3n violan la autonom\u00eda corporal.", "pt": "As obrigatoriedades de vacina\u00e7\u00e3o violam a autonomia corporal.", "ro": "Obliga\u021biile de vaccinare \u00eencalc\u0103 autonomia corporal\u0103.", "fr": "Les obligations de vaccination violent l\u2019autonomie corporelle.", "it": "\"Le vaccinazioni obbligatorie violano l''autonomia corporea.\"", "fi": "\"Rokotusvelvoitteet rikkovat kehon itsem\u00e4\u00e4r\u00e4\u00e4misoikeutta.\"", "nl": "\"Vaccinatieverplichtingen schenden de lichamelijke autonomie.\"", "no": "\"Vaksinasjonsmandater krenker kroppslig autonomi.\"", "sv": "\"Vaccinationsmandat kr\u00e4nker kroppslig autonomi.\"", "pl": "\u201eObowi\u0105zkowe szczepienia naruszaj\u0105 autonomi\u0119 cia\u0142a.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Vaccination mandates violate bodily autonomy.”';
UPDATE questions
SET translations = '{"en": "\u201cOur phones are basically part of our personality now \u2014 and that\u2019s not always bad.\u201d", "da": "Vores telefoner er i bund og grund en del af vores personlighed nu \u2013 og det er ikke altid d\u00e5rligt.", "de": "Unsere Telefone sind im Grunde Teil unserer Pers\u00f6nlichkeit \u2013 und das ist nicht immer schlecht.", "es": "Nuestros tel\u00e9fonos son b\u00e1sicamente parte de nuestra personalidad \u2014 y eso no siempre es malo.", "pt": "Os nossos telem\u00f3veis s\u00e3o basicamente parte da nossa personalidade \u2014 e isso nem sempre \u00e9 mau.", "ro": "Telefoanele noastre sunt practic parte din personalitatea noastr\u0103 acum \u2014 \u0219i nu e \u00eentotdeauna r\u0103u.", "fr": "Nos t\u00e9l\u00e9phones font d\u00e9sormais partie de notre personnalit\u00e9 \u2014 et ce n\u2019est pas toujours mauvais.", "it": "\"I nostri telefoni sono praticamente parte della nostra personalit\u00e0 adesso \u2014 e non \u00e8 sempre una cosa negativa.\"", "fi": "\"Puhelimemme ovat k\u00e4yt\u00e4nn\u00f6ss\u00e4 osa persoonallisuuttamme nyt \u2014 eik\u00e4 se aina ole huono asia.\"", "nl": "\"Onze telefoons maken tegenwoordig eigenlijk deel uit van onze persoonlijkheid \u2014 en dat is niet altijd slecht.\"", "no": "\u00abTelefonene v\u00e5re er i bunn og grunn en del av personligheten v\u00e5r n\u00e5 \u2014 og det er ikke alltid d\u00e5rlig.\u00bb", "sv": "\"V\u00e5ra telefoner \u00e4r i princip en del av v\u00e5r personlighet nu \u2014 och det \u00e4r inte alltid d\u00e5ligt.\"", "pl": "\u201eNasze telefony s\u0105 teraz zasadniczo cz\u0119\u015bci\u0105 naszej osobowo\u015bci \u2014 i to nie zawsze jest z\u0142e.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Our phones are basically part of our personality now — and that’s not always bad.”';