UPDATE questions
SET translations = '{"en": "What would you name a child if we had one together?", "da": "Hvad ville du kalde et barn, hvis vi fik et sammen?", "de": "Wie w\u00fcrdest du ein Kind nennen, wenn wir eins zusammen h\u00e4tten?", "es": "\u00bfQu\u00e9 nombre le pondr\u00edas a un hijo si tuvi\u00e9ramos uno juntos?", "pt": "Que nome darias a uma crian\u00e7a se tiv\u00e9ssemos uma juntos?", "ro": "Ce nume i-ai da unui copil dac\u0103 am avea unul \u00eempreun\u0103?", "fr": "Quel pr\u00e9nom donnerais-tu \u00e0 un enfant si nous en avions un ensemble ?", "it": "Come chiameresti un bambino se ne avessimo uno insieme?", "fi": "Mit\u00e4 nime\u00e4 antaisit lapselle, jos meill\u00e4 olisi yksi yhdess\u00e4?", "nl": "Hoe zou je een kind noemen als we er samen een zouden hebben?", "no": "Hva ville du kalt et barn hvis vi fikk ett sammen?", "sv": "Vad skulle du kalla ett barn om vi fick ett tillsammans?", "pl": "Jak by\u015b nazwa\u0142 dziecko, gdyby\u015bmy mieli je razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What would you name a child if we had one together?';
UPDATE questions
SET translations = '{"en": "What\u2019s a small white lie you\u2019ve told in the last couple days?", "da": "Hvilken lille hvid l\u00f8gn har du fortalt de sidste par dage?", "de": "Welche kleine Notl\u00fcge hast du in den letzten Tagen erz\u00e4hlt?", "es": "\u00bfQu\u00e9 peque\u00f1a mentira piadosa has dicho en los \u00faltimos d\u00edas?", "pt": "Que pequena mentira branca disseste nos \u00faltimos dias?", "ro": "Ce mic\u0103 minciun\u0103 nevinovat\u0103 ai spus \u00een ultimele zile?", "fr": "Quel petit mensonge blanc as-tu dit ces derniers jours ?", "it": "Qual \u00e8 una piccola bugia bianca che hai detto negli ultimi giorni?", "fi": "Mik\u00e4 on pieni valkoinen valhe, jonka olet kertonut viimeisten parin p\u00e4iv\u00e4n aikana?", "nl": "Wat is een klein leugentje dat je de afgelopen paar dagen hebt verteld?", "no": "Hva er en liten hvit l\u00f8gn du har fortalt de siste par dagene?", "sv": "Vad \u00e4r en liten vit l\u00f6gn du har sagt under de senaste dagarna?", "pl": "Jakie\u015b ma\u0142e bia\u0142e k\u0142amstwo, kt\u00f3re powiedzia\u0142e\u015b w ci\u0105gu ostatnich kilku dni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s a small white lie you’ve told in the last couple days?';
UPDATE questions
SET translations = '{"en": "What do you want our next chapter together to feel like?", "da": "Hvordan vil du have, at vores n\u00e6ste kapitel sammen skal f\u00f8les?", "de": "Wie m\u00f6chtest du, dass sich unser n\u00e4chstes Kapitel zusammen anf\u00fchlt?", "es": "\u00bfC\u00f3mo te gustar\u00eda que se sintiera nuestro pr\u00f3ximo cap\u00edtulo juntos?", "pt": "Como gostarias que fosse o nosso pr\u00f3ximo cap\u00edtulo juntos?", "ro": "Cum ai vrea s\u0103 fie urm\u0103torul nostru capitol \u00eempreun\u0103?", "fr": "Comment aimerais-tu que notre prochain chapitre ensemble se sente ?", "it": "Come vuoi che si senta il nostro prossimo capitolo insieme?", "fi": "Milt\u00e4 haluat, ett\u00e4 seuraava yhteinen luvumme tuntuu?", "nl": "Hoe wil je dat ons volgende hoofdstuk samen aanvoelt?", "no": "Hvordan vil du at v\u00e5rt neste kapittel sammen skal f\u00f8les?", "sv": "Hur vill du att v\u00e5rt n\u00e4sta kapitel tillsammans ska k\u00e4nnas?", "pl": "Jak chcesz, aby nasz nast\u0119pny rozdzia\u0142 razem si\u0119 czu\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you want our next chapter together to feel like?';
UPDATE questions
SET translations = '{"en": "What do you believe happens when we die \u2014 and does that belief comfort or challenge you?", "da": "Hvad tror du sker, n\u00e5r vi d\u00f8r \u2014 og tr\u00f8ster eller udfordrer den tro dig?", "de": "Was glaubst du, passiert, wenn wir sterben \u2013 und tr\u00f6stet oder fordert dich dieser Glaube heraus?", "es": "\u00bfQu\u00e9 crees que sucede cuando morimos \u2014 y esa creencia te consuela o te desaf\u00eda?", "pt": "O que acreditas que acontece quando morremos \u2014 e essa cren\u00e7a conforta-te ou desafia-te?", "ro": "Ce crezi c\u0103 se \u00eent\u00e2mpl\u0103 c\u00e2nd murim \u2014 \u0219i credin\u021ba asta te lini\u0219te\u0219te sau te provoac\u0103?", "fr": "Que penses-tu qu\u2019il se passe quand on meurt \u2014 et cette croyance te r\u00e9conforte-t-elle ou te met-elle au d\u00e9fi ?", "it": "Cosa credi che accada quando moriamo \u2014 e questa convinzione ti conforta o ti sfida?", "fi": "Mit\u00e4 uskot tapahtuvan, kun kuolemme \u2014 ja lohduttaako vai haastaa t\u00e4m\u00e4 uskomus sinua?", "nl": "Wat geloof je dat er gebeurt als we sterven \u2014 en biedt dat geloof je troost of daagt het je uit?", "no": "Hva tror du skjer n\u00e5r vi d\u00f8r \u2014 og gir den troen deg tr\u00f8st eller utfordrer den deg?", "sv": "Vad tror du h\u00e4nder n\u00e4r vi d\u00f6r \u2014 och ger den tron dig tr\u00f6st eller utmanar den dig?", "pl": "Co s\u0105dzisz, co si\u0119 dzieje, gdy umieramy \u2014 i czy ta wiara ci\u0119 pociesza, czy raczej wyzwala?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you believe happens when we die — and does that belief comfort or challenge you?';
UPDATE questions
SET translations = '{"en": "What moral value or principle matters most to you in a relationship?", "da": "Hvilken moralsk v\u00e6rdi eller princip betyder mest for dig i et forhold?", "de": "Welcher moralische Wert oder welches Prinzip ist dir in einer Beziehung am wichtigsten?", "es": "\u00bfQu\u00e9 valor moral o principio es m\u00e1s importante para ti en una relaci\u00f3n?", "pt": "Que valor moral ou princ\u00edpio \u00e9 mais importante para ti num relacionamento?", "ro": "Ce valoare moral\u0103 sau principiu conteaz\u0103 cel mai mult pentru tine \u00eentr-o rela\u021bie?", "fr": "Quelle valeur morale ou principe compte le plus pour toi dans une relation ?", "it": "Quale valore morale o principio \u00e8 pi\u00f9 importante per te in una relazione?", "fi": "Mik\u00e4 moraalinen arvo tai periaate on sinulle t\u00e4rkein suhteessa?", "nl": "Welke morele waarde of principe is voor jou het belangrijkst in een relatie?", "no": "Hvilken moralsk verdi eller prinsipp betyr mest for deg i et forhold?", "sv": "Vilken moralisk v\u00e4rdering eller princip betyder mest f\u00f6r dig i en relation?", "pl": "Jak\u0105 warto\u015b\u0107 moraln\u0105 lub zasad\u0119 uwa\u017casz za najwa\u017cniejsz\u0105 w zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What moral value or principle matters most to you in a relationship?';
UPDATE questions
SET translations = '{"en": "How do you decide what\u2019s forgivable and what\u2019s not?", "da": "Hvordan beslutter du, hvad der kan tilgives, og hvad der ikke kan?", "de": "Wie entscheidest du, was verzeihbar ist und was nicht?", "es": "\u00bfC\u00f3mo decides qu\u00e9 se puede perdonar y qu\u00e9 no?", "pt": "Como decides o que \u00e9 perdo\u00e1vel e o que n\u00e3o \u00e9?", "ro": "Cum decizi ce poate fi iertat \u0219i ce nu?", "fr": "Comment d\u00e9cides-tu ce qui est pardonnable et ce qui ne l\u2019est pas ?", "it": "Come decidi cosa \u00e8 perdonabile e cosa non lo \u00e8?", "fi": "Miten p\u00e4\u00e4t\u00e4t, mik\u00e4 on anteeksiannettavaa ja mik\u00e4 ei?", "nl": "Hoe beslis je wat vergeven kan worden en wat niet?", "no": "Hvordan bestemmer du hva som er tilgivelig og hva som ikke er det?", "sv": "Hur best\u00e4mmer du vad som \u00e4r f\u00f6rl\u00e5tligt och vad som inte \u00e4r det?", "pl": "Jak decydujesz, co jest do wybaczenia, a co nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you decide what’s forgivable and what’s not?';
UPDATE questions
SET translations = '{"en": "Have you ever struggled to understand someone\u2019s beliefs that were very different from your own?", "da": "Har du nogensinde haft sv\u00e6rt ved at forst\u00e5 nogen, hvis overbevisninger var meget forskellige fra dine egne?", "de": "Hattest du jemals Schwierigkeiten, den Glauben eines anderen zu verstehen, der sich stark von deinem unterschied?", "es": "\u00bfAlguna vez te cost\u00f3 entender las creencias de alguien muy diferentes a las tuyas?", "pt": "Alguma vez tiveste dificuldade em entender as cren\u00e7as de algu\u00e9m muito diferentes das tuas?", "ro": "\u021ai-a fost vreodat\u0103 greu s\u0103 \u00een\u021belegi credin\u021bele cuiva foarte diferite de ale tale?", "fr": "As-tu d\u00e9j\u00e0 eu du mal \u00e0 comprendre les croyances de quelqu\u2019un de tr\u00e8s diff\u00e9rent de toi ?", "it": "Hai mai avuto difficolt\u00e0 a comprendere le credenze di qualcuno che erano molto diverse dalle tue?", "fi": "Oletko koskaan kamppaillut ymm\u00e4rt\u00e4\u00e4ksesi jonkun uskomuksia, jotka olivat hyvin erilaisia kuin omasi?", "nl": "Heb je ooit moeite gehad om de overtuigingen van iemand te begrijpen die heel anders waren dan de jouwe?", "no": "Har du noen gang hatt problemer med \u00e5 forst\u00e5 noens tro som var veldig forskjellig fra din egen?", "sv": "Har du n\u00e5gonsin haft sv\u00e5rt att f\u00f6rst\u00e5 n\u00e5gon annans \u00f6vertygelser som var v\u00e4ldigt olika dina egna?", "pl": "Czy kiedykolwiek mia\u0142e\u015b trudno\u015bci ze zrozumieniem czyich\u015b przekona\u0144, kt\u00f3re by\u0142y bardzo r\u00f3\u017cne od twoich?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever struggled to understand someone’s beliefs that were very different from your own?';
UPDATE questions
SET translations = '{"en": "How do you feel when you hear someone talk openly about their past relationships or sexual history?", "da": "Hvordan har du det, n\u00e5r du h\u00f8rer nogen tale \u00e5bent om deres tidligere forhold eller seksuelle historie?", "de": "Wie f\u00fchlst du dich, wenn jemand offen \u00fcber seine fr\u00fcheren Beziehungen oder seine sexuelle Vergangenheit spricht?", "es": "\u00bfC\u00f3mo te sientes cuando alguien habla abiertamente de sus relaciones o historia sexual pasada?", "pt": "Como te sentes quando algu\u00e9m fala abertamente sobre as suas rela\u00e7\u00f5es ou passado sexual?", "ro": "Cum te sim\u021bi c\u00e2nd auzi pe cineva vorbind deschis despre rela\u021biile sau trecutul s\u0103u sexual?", "fr": "Que ressens-tu quand quelqu\u2019un parle ouvertement de ses anciennes relations ou de son pass\u00e9 sexuel ?", "it": "Come ti senti quando senti qualcuno parlare apertamente delle proprie relazioni passate o della propria storia sessuale?", "fi": "Milt\u00e4 sinusta tuntuu, kun kuulet jonkun puhuvan avoimesti menneist\u00e4 suhteistaan tai seksuaalisesta historiastaan?", "nl": "Hoe voel je je als je iemand openlijk hoort praten over hun vorige relaties of seksuele geschiedenis?", "no": "Hvordan f\u00f8ler du deg n\u00e5r du h\u00f8rer noen snakke \u00e5pent om sine tidligere forhold eller seksuelle erfaringer?", "sv": "Hur k\u00e4nner du n\u00e4r du h\u00f6r n\u00e5gon prata \u00f6ppet om sina tidigare relationer eller sin sexuella historia?", "pl": "Jak si\u0119 czujesz, gdy s\u0142yszysz, jak kto\u015b otwarcie m\u00f3wi o swoich przesz\u0142ych zwi\u0105zkach lub historii seksualnej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel when you hear someone talk openly about their past relationships or sexual history?';
UPDATE questions
SET translations = '{"en": "Do you think people are judged too harshly for the number of people they\u2019ve been with?", "da": "Synes du, folk bliver d\u00f8mt for h\u00e5rdt for antallet af personer, de har v\u00e6ret sammen med?", "de": "Denkst du, Menschen werden zu hart daf\u00fcr beurteilt, mit wie vielen sie zusammen waren?", "es": "\u00bfCrees que la gente es juzgada demasiado severamente por la cantidad de personas con las que ha estado?", "pt": "Achas que as pessoas s\u00e3o julgadas com demasiada dureza pelo n\u00famero de pessoas com quem estiveram?", "ro": "Crezi c\u0103 oamenii sunt judeca\u021bi prea aspru pentru num\u0103rul de persoane cu care au fost?", "fr": "Penses-tu que les gens sont trop jug\u00e9s pour le nombre de partenaires qu\u2019ils ont eus ?", "it": "Pensi che le persone vengano giudicate troppo severamente per il numero di persone con cui sono state?", "fi": "Mietitk\u00f6, ett\u00e4 ihmisi\u00e4 tuomitaan liian ankarasti sen perusteella, kuinka monen kanssa he ovat olleet?", "nl": "Denk je dat mensen te hard beoordeeld worden op het aantal mensen met wie ze geweest zijn?", "no": "Tror du folk blir d\u00f8mt for strengt for antallet de har v\u00e6rt sammen med?", "sv": "Tycker du att m\u00e4nniskor d\u00f6ms f\u00f6r h\u00e5rt f\u00f6r antalet personer de har varit med?", "pl": "Czy uwa\u017casz, \u017ce ludzie s\u0105 zbyt surowo oceniani za liczb\u0119 os\u00f3b, z kt\u00f3rymi byli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you think people are judged too harshly for the number of people they’ve been with?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019ve learned to be more tolerant or open-minded about?", "da": "Hvad har du l\u00e6rt at blive mere tolerant eller \u00e5ben overfor?", "de": "Was hast du gelernt, toleranter oder offener zu sein?", "es": "\u00bfQu\u00e9 has aprendido a tolerar o aceptar m\u00e1s abiertamente?", "pt": "O que aprendeste a tolerar ou a ser mais aberto?", "ro": "Ce ai \u00eenv\u0103\u021bat s\u0103 tolerezi mai u\u0219or sau s\u0103 accep\u021bi mai deschis?", "fr": "Qu\u2019as-tu appris \u00e0 \u00eatre plus tol\u00e9rant ou plus ouvert \u00e0 propos de ?", "it": "Qualcosa su cui hai imparato ad essere pi\u00f9 tollerante o aperto di mente?", "fi": "Mik\u00e4 on jotain, jonka olet oppinut olemaan suvaitsevaisempi tai avaramielisempi?", "nl": "Wat is iets waar je meer tolerant of open-minded over bent geworden?", "no": "Hva er noe du har l\u00e6rt \u00e5 v\u00e6re mer tolerant eller \u00e5pen for?", "sv": "Vad \u00e4r n\u00e5got du har l\u00e4rt dig att vara mer tolerant eller \u00f6ppen f\u00f6r?", "pl": "Czego nauczy\u0142e\u015b si\u0119, aby by\u0107 bardziej tolerancyjny lub otwarty?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you’ve learned to be more tolerant or open-minded about?';