UPDATE questions
SET translations = '{"en": "What piece of tech would you trust in a horror scenario?", "da": "Hvilken teknologi ville du stole p\u00e5 i et gyser-scenarie?", "de": "Welcher Technik w\u00fcrdest du in einem Horrorszenario vertrauen?", "es": "\u00bfQu\u00e9 tecnolog\u00eda confiar\u00edas en un escenario de terror?", "pt": "Em que tecnologia confiarias num cen\u00e1rio de terror?", "ro": "Pe ce tehnologie te-ai baza \u00eentr-un scenariu de groaz\u0103?", "fr": "Quelle technologie ferais-tu confiance dans un sc\u00e9nario d\u2019horreur ?", "it": "Quale dispositivo tecnologico ti fideresti di usare in uno scenario da film horror?", "fi": "Mihin tekniseen laitteeseen luottaisit kauhutilanteessa?", "nl": "Aan welk stukje technologie zou jij vertrouwen in een horrorscenario?", "no": "Hvilken teknodings ville du stolt p\u00e5 i et horrorscenario?", "sv": "Vilken teknikpryl skulle du lita p\u00e5 i ett skr\u00e4ckscenario?", "pl": "Kt\u00f3remu urz\u0105dzeniu lub technologii zaufa\u0142(a)by\u015b w scenariuszu grozy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What piece of tech would you trust in a horror scenario?';
UPDATE questions
SET translations = '{"en": "Which everyday job becomes scariest after midnight?", "da": "Hvilket almindeligt job bliver mest skr\u00e6mmende efter midnat?", "de": "Welcher Alltagsjob wird nach Mitternacht am gruseligsten?", "es": "\u00bfQu\u00e9 trabajo cotidiano se vuelve m\u00e1s aterrador despu\u00e9s de medianoche?", "pt": "Que trabalho comum se torna mais assustador depois da meia-noite?", "ro": "Ce slujb\u0103 obi\u0219nuit\u0103 devine cea mai \u00eenfrico\u0219\u0103toare dup\u0103 miezul nop\u021bii?", "fr": "Quel m\u00e9tier ordinaire devient le plus effrayant apr\u00e8s minuit ?", "it": "Quale lavoro quotidiano diventa il pi\u00f9 spaventoso dopo mezzanotte?", "fi": "Mik\u00e4 tavallinen ty\u00f6 muuttuu pelottavimmaksi keskiy\u00f6n j\u00e4lkeen?", "nl": "Welk alledaags beroep wordt het engst na middernacht?", "no": "Hvilken hverdagsjobb blir skumlest etter midnatt?", "sv": "Vilket vardagsjobb blir l\u00e4skigast efter midnatt?", "pl": "Kt\u00f3ry zwyk\u0142y zaw\u00f3d staje si\u0119 najstraszniejszy po p\u00f3\u0142nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Which everyday job becomes scariest after midnight?';
UPDATE questions
SET translations = '{"en": "Your date casually mention your street name before you told it. Confront or note it?", "da": "Din date n\u00e6vner tilf\u00e6ldigt dit vejnavn, f\u00f8r du har fortalt det. Konfronterer du eller noterer du det?", "de": "Dein Date erw\u00e4hnt beil\u00e4ufig deinen Stra\u00dfennamen, bevor du ihn gesagt hast. Konfrontierst du oder merkst du es dir?", "es": "Tu cita menciona tu calle antes de que lo digas. \u00bfLo enfrentas o lo anotas mentalmente?", "pt": "O teu encontro menciona o nome da tua rua antes de o dizeres. Confrontas ou registas?", "ro": "Persoana cu care e\u0219ti la \u00eent\u00e2lnire \u00ee\u021bi men\u021bioneaz\u0103 strada \u00eenainte s\u0103 o spui. O confrun\u021bi sau doar re\u021bii?", "fr": "Ton rendez-vous mentionne ton nom de rue avant que tu ne le dises. Tu confrontes ou tu notes ?", "it": "Il tuo appuntamento nomina con noncuranza il nome della tua via prima che tu glielo dica. Lo/la affronti o te lo segni soltanto?", "fi": "Deittisi mainitsee rennosti kotikatusi nimen ennen kuin kerroit sen. Otatko asian puheeksi vai vain merkitset muistiin?", "nl": "Je date noemt terloops jouw straatnaam voordat jij die hebt verteld. Spreek je het aan of onthoud je het alleen?", "no": "Date\u2019n din nevner nonchalant gaten du bor i f\u00f8r du har sagt det. Konfronterer du, eller bare noterer du det?", "sv": "Din dejt n\u00e4mner avslappnat ditt gatunamn innan du har sagt det. Konfronterar du eller bara noterar det?", "pl": "Osoba na randce mimochodem wymienia nazw\u0119 twojej ulicy, zanim jej powiesz. Konfrontujesz to czy tylko odnotowujesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your date casually mention your street name before you told it. Confront or note it?';
UPDATE questions
SET translations = '{"en": "Draft a rule for surviving the first 10 minutes of a scary movie.", "da": "Lav en regel for at overleve de f\u00f8rste 10 minutter af en gyserfilm.", "de": "Erstelle eine Regel, um die ersten 10 Minuten eines Horrorfilms zu \u00fcberleben.", "es": "Escribe una regla para sobrevivir los primeros 10 minutos de una pel\u00edcula de terror.", "pt": "Cria uma regra para sobreviver aos primeiros 10 minutos de um filme de terror.", "ro": "F\u0103 o regul\u0103 pentru a supravie\u021bui primelor 10 minute dintr-un film de groaz\u0103.", "fr": "\u00c9cris une r\u00e8gle pour survivre aux dix premi\u00e8res minutes d\u2019un film d\u2019horreur.", "it": "Scrivi una regola per sopravvivere ai primi 10 minuti di un film dell\u2019orrore.", "fi": "Laadi s\u00e4\u00e4nt\u00f6, jolla selvi\u00e4\u00e4 kauhuelokuvan ensimm\u00e4iset 10 minuuttia.", "nl": "Bedenk een regel om de eerste 10 minuten van een horrorfilm te overleven.", "no": "Lag en regel for \u00e5 overleve de f\u00f8rste 10 minuttene av en skrekkfilm.", "sv": "Formulera en regel f\u00f6r att \u00f6verleva de f\u00f6rsta 10 minuterna av en skr\u00e4ckfilm.", "pl": "U\u0142\u00f3\u017c zasad\u0119, kt\u00f3ra pozwala prze\u017cy\u0107 pierwsze 10 minut horroru."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Draft a rule for surviving the first 10 minutes of a scary movie.';
UPDATE questions
SET translations = '{"en": "If a friendly ghost could do one chore, which would you assign?", "da": "Hvis et venligt sp\u00f8gelse kunne lave \u00e9n husopgave, hvilken ville du v\u00e6lge?", "de": "Wenn ein freundlicher Geist eine Hausarbeit erledigen k\u00f6nnte, welche w\u00fcrdest du w\u00e4hlen?", "es": "Si un fantasma amable pudiera hacer una tarea dom\u00e9stica, \u00bfcu\u00e1l elegir\u00edas?", "pt": "Se um fantasma simp\u00e1tico pudesse fazer uma tarefa, qual escolherias?", "ro": "Dac\u0103 o fantom\u0103 prietenoas\u0103 ar putea face o treab\u0103 \u00een locul t\u0103u, ce i-ai da?", "fr": "Si un gentil fant\u00f4me pouvait faire une corv\u00e9e, laquelle lui confierais-tu ?", "it": "Se un fantasma amichevole potesse svolgere una faccenda domestica per te, quale gli affideresti?", "fi": "Jos yst\u00e4v\u00e4llinen kummitus voisi hoitaa yhden kotity\u00f6n, mink\u00e4 antaisit sen teht\u00e4v\u00e4ksi?", "nl": "Als een vriendelijke geest \u00e9\u00e9n klus voor je kon doen, welke zou je hem geven?", "no": "Hvis et vennlig sp\u00f8kelse kunne gj\u00f8re \u00e9n husoppgave for deg, hvilken ville du gitt det?", "sv": "Om ett v\u00e4nligt sp\u00f6ke kunde g\u00f6ra en syssla \u00e5t dig, vilken skulle du ge det?", "pl": "Gdyby przyjazny duch m\u00f3g\u0142 wykona\u0107 jedno domowe zadanie, kt\u00f3re by\u015b mu zleci\u0142(a)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If a friendly ghost could do one chore, which would you assign?';
UPDATE questions
SET translations = '{"en": "What would your personalized haunted house focus on to spook you?", "da": "Hvad ville dit personlige hjems\u00f8gte hus fokusere p\u00e5 for at skr\u00e6mme dig?", "de": "Worauf w\u00fcrde sich dein pers\u00f6nliches Spukhaus konzentrieren, um dich zu erschrecken?", "es": "\u00bfEn qu\u00e9 se centrar\u00eda tu casa encantada personalizada para asustarte?", "pt": "Em que se focaria a tua casa assombrada personalizada para te assustar?", "ro": "Pe ce s-ar concentra casa ta b\u00e2ntuit\u0103 personalizat\u0103 ca s\u0103 te sperie?", "fr": "Sur quoi se concentrerait ta maison hant\u00e9e personnalis\u00e9e pour te faire peur ?", "it": "Su cosa si concentrerebbe una casa infestata personalizzata per spaventarti davvero?", "fi": "Mihin asioihin sinun henkil\u00f6kohtainen kummitustalosi keskittyisi pelotellakseen sinua?", "nl": "Waar zou een gepersonaliseerd spookhuis zich op richten om jou echt bang te maken?", "no": "Hva ville et skreddersydd sp\u00f8kelseshus fokusert p\u00e5 for \u00e5 skremme akkurat deg?", "sv": "Vad skulle ett personligt hems\u00f6kt hus fokusera p\u00e5 f\u00f6r att skr\u00e4mma just dig?", "pl": "Na czym skupi\u0142by si\u0119 spersonalizowany nawiedzony dom, \u017ceby naprawd\u0119 ci\u0119 przestraszy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What would your personalized haunted house focus on to spook you?';
UPDATE questions
SET translations = '{"en": "A friend tracks your location \u201cfor safety\u201d\u2026 and comments on your stops. Is that care or control?", "da": "En ven sporer din placering \u201cfor sikkerhedens skyld\u201d\u2026 og kommenterer dine stop. Omsorg eller kontrol?", "de": "Ein Freund verfolgt deinen Standort \u201ezur Sicherheit\u201c\u2026 und kommentiert deine Stopps. Sorge oder Kontrolle?", "es": "Un amigo rastrea tu ubicaci\u00f3n \u201cpor seguridad\u201d\u2026 y comenta tus paradas. \u00bfCuidado o control?", "pt": "Um amigo rastreia a tua localiza\u00e7\u00e3o \u201cpor seguran\u00e7a\u201d\u2026 e comenta as tuas paragens. Cuidado ou controlo?", "ro": "Un prieten \u00ee\u021bi urm\u0103re\u0219te loca\u021bia \u201epentru siguran\u021b\u0103\u201d\u2026 \u0219i comenteaz\u0103 opririle tale. Grij\u0103 sau control?", "fr": "Un ami suit ta position \u00ab pour ta s\u00e9curit\u00e9 \u00bb\u2026 et commente tes arr\u00eats. Prendre soin ou contr\u00f4ler ?", "it": "Un amico traccia la tua posizione \u201cper sicurezza\u201d\u2026 e commenta tutte le tue soste. \u00c8 cura o controllo?", "fi": "Yst\u00e4v\u00e4 seuraa sijaintiasi \u201dturvallisuuden vuoksi\u201d\u2026 ja kommentoi pys\u00e4hdyksi\u00e4si. Onko se v\u00e4litt\u00e4mist\u00e4 vai kontrollia?", "nl": "Een vriend volgt je locatie \u201cvoor je veiligheid\u201d\u2026 en geeft commentaar op je stops. Is dat zorg of controle?", "no": "En venn sporer posisjonen din \u00abfor sikkerhets skyld\u00bb\u2026 og kommenterer stoppene dine. Er det omsorg eller kontroll?", "sv": "En v\u00e4n sp\u00e5rar din plats \u201df\u00f6r s\u00e4kerhetens skull\u201d\u2026 och kommenterar dina stopp. \u00c4r det omtanke eller kontroll?", "pl": "Przyjaciel \u015bledzi twoj\u0105 lokalizacj\u0119 \u201edla bezpiecze\u0144stwa\u201d\u2026 i komentuje twoje przystanki. To troska czy kontrola?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A friend tracks your location “for safety”… and comments on your stops. Is that care or control?';
UPDATE questions
SET translations = '{"en": "What\u2019s the eeriest kind of weather?", "da": "Hvad er den mest uhyggelige slags vejr?", "de": "Was ist die unheimlichste Art von Wetter?", "es": "\u00bfCu\u00e1l es el tipo de clima m\u00e1s inquietante?", "pt": "Qual \u00e9 o tipo de clima mais assustador?", "ro": "Care este cel mai \u00eenfior\u0103tor tip de vreme?", "fr": "Quel est le type de temps le plus inqui\u00e9tant ?", "it": "Che tipo di tempo atmosferico ti sembra pi\u00f9 inquietante?", "fi": "Millainen s\u00e4\u00e4 on mielest\u00e4si karmivin?", "nl": "Wat voor soort weer vind jij het meest spookachtig?", "no": "Hva er den mest uhyggelige typen v\u00e6r?", "sv": "Vilken sorts v\u00e4der \u00e4r ruggigast enligt dig?", "pl": "Jaki rodzaj pogody jest dla ciebie najbardziej upiorny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the eeriest kind of weather?';
UPDATE questions
SET translations = '{"en": "If the walls could talk, what rumor would they spread?", "da": "Hvis v\u00e6ggene kunne tale, hvilket rygte ville de sprede?", "de": "Wenn die W\u00e4nde sprechen k\u00f6nnten, welches Ger\u00fccht w\u00fcrden sie verbreiten?", "es": "Si las paredes pudieran hablar, \u00bfqu\u00e9 rumor propagar\u00edan?", "pt": "Se as paredes pudessem falar, que rumor espalhariam?", "ro": "Dac\u0103 pere\u021bii ar putea vorbi, ce zvon ar r\u0103sp\u00e2ndi?", "fr": "Si les murs pouvaient parler, quelle rumeur propageraient-ils ?", "it": "Se i muri potessero parlare, quale pettegolezzo diffonderebbero?", "fi": "Jos sein\u00e4t voisivat puhua, mit\u00e4 juorua ne levitt\u00e4isiv\u00e4t?", "nl": "Als de muren konden praten, welk gerucht zouden ze verspreiden?", "no": "Hvis veggene kunne snakke, hvilket rykte ville de spre?", "sv": "Om v\u00e4ggarna kunde prata, vilket rykte skulle de sprida?", "pl": "Gdyby \u015bciany mog\u0142y m\u00f3wi\u0107, jak\u0105 plotk\u0119 by rozpu\u015bci\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If the walls could talk, what rumor would they spread?';
UPDATE questions
SET translations = '{"en": "A neighbor moves in but never opens curtains. What\u2019s your theory?", "da": "En nabo flytter ind, men \u00e5bner aldrig gardinerne. Hvad er din teori?", "de": "Ein Nachbar zieht ein, aber \u00f6ffnet nie die Vorh\u00e4nge. Was ist deine Theorie?", "es": "Un vecino se muda pero nunca abre las cortinas. \u00bfCu\u00e1l es tu teor\u00eda?", "pt": "Um vizinho muda-se mas nunca abre as cortinas. Qual \u00e9 a tua teoria?", "ro": "Un vecin se mut\u0103, dar nu deschide niciodat\u0103 perdelele. Care e teoria ta?", "fr": "Un voisin emm\u00e9nage mais n\u2019ouvre jamais les rideaux. Quelle est ta th\u00e9orie ?", "it": "Un vicino si trasferisce ma non apre mai le tende. Qual \u00e8 la tua teoria?", "fi": "Naapuri muuttaa viereen, mutta ei koskaan avaa verhoja. Mik\u00e4 on teoriasi?", "nl": "Een nieuwe buur trekt in maar doet nooit de gordijnen open. Wat is jouw theorie?", "no": "En ny nabo flytter inn, men \u00e5pner aldri gardinene. Hva er teorien din?", "sv": "En granne flyttar in men \u00f6ppnar aldrig gardinerna. Vad \u00e4r din teori?", "pl": "Nowy s\u0105siad si\u0119 wprowadza, ale nigdy nie ods\u0142ania zas\u0142on. Jaka jest twoja teoria?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A neighbor moves in but never opens curtains. What’s your theory?';