UPDATE questions
SET translations = '{"en": "You\u2019re walking home and all the streetlights go out at once. What\u2019s your next move?", "da": "Du g\u00e5r hjem, og alle gadelygter slukker p\u00e5 \u00e9n gang. Hvad g\u00f8r du?", "de": "Du gehst nach Hause, und alle Stra\u00dfenlaternen gehen gleichzeitig aus. Was tust du?", "es": "Caminas a casa y todas las farolas se apagan a la vez. \u00bfQu\u00e9 haces?", "pt": "Caminhas para casa e todos os candeeiros da rua apagam-se de uma vez. O que fazes?", "ro": "Mergi spre cas\u0103 \u0219i toate felinarele se sting deodat\u0103. Ce faci?", "fr": "Tu rentres chez toi et tous les lampadaires s\u2019\u00e9teignent d\u2019un coup. Que fais-tu ?", "it": "Stai tornando a casa a piedi e tutti i lampioni si spengono all\u2019improvviso. Qual \u00e8 la tua prossima mossa?", "fi": "K\u00e4velet kotiin ja kaikki katuvalot sammuvat yht\u00e4 aikaa. Mit\u00e4 teet seuraavaksi?", "nl": "Je loopt naar huis en alle lantaarnpalen gaan tegelijk uit. Wat is je volgende stap?", "no": "Du g\u00e5r hjem, og alle gatelysene slukker samtidig. Hva gj\u00f8r du da?", "sv": "Du g\u00e5r hem och alla gatlyktor slocknar samtidigt. Vad g\u00f6r du sen?", "pl": "Idziesz pieszo do domu i nagle wszystkie latarnie gasn\u0105. Jaki jest tw\u00f3j nast\u0119pny krok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You’re walking home and all the streetlights go out at once. What’s your next move?';
UPDATE questions
SET translations = '{"en": "What smell would make a place instantly haunted to you?", "da": "Hvilken lugt ville f\u00e5 et sted til straks at f\u00f8les hjems\u00f8gt?", "de": "Welcher Geruch w\u00fcrde einen Ort sofort spukhaft machen?", "es": "\u00bfQu\u00e9 olor har\u00eda que un lugar se sintiera inmediatamente encantado?", "pt": "Que cheiro faria um lugar parecer imediatamente assombrado?", "ro": "Ce miros ar face un loc s\u0103 par\u0103 instantaneu b\u00e2ntuit?", "fr": "Quelle odeur rendrait un endroit instantan\u00e9ment hant\u00e9 ?", "it": "Quale odore renderebbe un luogo istantaneamente infestato, per te?", "fi": "Mik\u00e4 haju saisi paikan tuntumaan heti kuin siell\u00e4 kummittelisi?", "nl": "Welke geur zou een plek voor jou meteen spookachtig maken?", "no": "Hvilken lukt ville f\u00e5tt et sted til \u00e5 f\u00f8les umiddelbart hjems\u00f8kt for deg?", "sv": "Vilken doft skulle f\u00e5 en plats att k\u00e4nnas direkt hems\u00f6kt f\u00f6r dig?", "pl": "Jaki zapach sprawi\u0142by, \u017ce miejsce od razu wyda\u0142oby ci si\u0119 nawiedzone?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What smell would make a place instantly haunted to you?';
UPDATE questions
SET translations = '{"en": "D\u00e9j\u00e0 vu hits hard\u2014but you know the next 10 seconds. Do you follow the script or try to break it?", "da": "D\u00e9j\u00e0 vu rammer h\u00e5rdt \u2013 men du kender de n\u00e6ste 10 sekunder. F\u00f8lger du scriptet eller bryder det?", "de": "D\u00e9j\u00e0-vu trifft dich hart \u2013 aber du kennst die n\u00e4chsten 10 Sekunden. Folgst du dem Ablauf oder brichst du ihn?", "es": "El d\u00e9j\u00e0 vu golpea fuerte, pero sabes los pr\u00f3ximos 10 segundos. \u00bfSigues el guion o lo rompes?", "pt": "O d\u00e9j\u00e0 vu atinge-te forte \u2013 mas sabes os pr\u00f3ximos 10 segundos. Segues o gui\u00e3o ou quebras?", "ro": "D\u00e9j\u00e0 vu te love\u0219te puternic \u2013 dar \u0219tii urm\u0103toarele 10 secunde. Urmezi scenariul sau \u00eel rupi?", "fr": "Le d\u00e9j\u00e0-vu te frappe fort \u2013 mais tu connais les dix prochaines secondes. Tu suis le script ou tu le brises ?", "it": "Il d\u00e9j\u00e0 vu \u00e8 fortissimo, ma tu conosci i prossimi 10 secondi. Segui il copione o provi a romperlo?", "fi": "D\u00e9j\u00e0-vu iskee kovaa \u2013 mutta tied\u00e4t seuraavat 10 sekuntia. Seuraatko k\u00e4sikirjoitusta vai yrit\u00e4tk\u00f6 rikkoa sen?", "nl": "Heftig d\u00e9j\u00e0 vu \u2013 maar je weet de komende 10 seconden. Volg je het script of probeer je het te doorbreken?", "no": "Deja vu treffer skikkelig, men du vet hva som skjer de neste 10 sekundene. F\u00f8lger du manus eller pr\u00f8ver du \u00e5 bryte det?", "sv": "Kraftig d\u00e9j\u00e0 vu \u2013 men du vet vad som h\u00e4nder de n\u00e4sta 10 sekunderna. F\u00f6ljer du manus eller f\u00f6rs\u00f6ker du bryta det?", "pl": "Mocne d\u00e9j\u00e0 vu \u2013 ale znasz nast\u0119pne 10 sekund. Trzymasz si\u0119 scenariusza czy pr\u00f3bujesz go przerwa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Déjà vu hits hard—but you know the next 10 seconds. Do you follow the script or try to break it?';
UPDATE questions
SET translations = '{"en": "Which ancient myth feels strangely plausible?", "da": "Hvilken gammel myte f\u00f8les m\u00e6rkeligt plausibel?", "de": "Welcher alte Mythos f\u00fchlt sich seltsam plausibel an?", "es": "\u00bfQu\u00e9 mito antiguo te parece extra\u00f1amente plausible?", "pt": "Que mito antigo te parece estranhamente plaus\u00edvel?", "ro": "Ce mit antic \u021bi se pare ciudat de plauzibil?", "fr": "Quel mythe ancien te semble \u00e9trangement plausible ?", "it": "Quale mito antico ti sembra stranamente plausibile?", "fi": "Mik\u00e4 muinainen myytti tuntuu oudon uskottavalta?", "nl": "Welke oude mythe voelt vreemd genoeg geloofwaardig?", "no": "Hvilken gammel myte f\u00f8les merkelig plausibel?", "sv": "Vilken antik myt k\u00e4nns m\u00e4rkligt trov\u00e4rdig?", "pl": "Kt\u00f3ry staro\u017cytny mit wydaje ci si\u0119 dziwnie wiarygodny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Which ancient myth feels strangely plausible?';
UPDATE questions
SET translations = '{"en": "Describe a time technology acted too smart.", "da": "Beskriv en tid, hvor teknologien virkede for smart.", "de": "Beschreibe einen Moment, in dem Technologie zu schlau wirkte.", "es": "Describe un momento en que la tecnolog\u00eda actu\u00f3 demasiado inteligente.", "pt": "Descreve um momento em que a tecnologia pareceu esperta demais.", "ro": "Descrie un moment c\u00e2nd tehnologia a p\u0103rut prea inteligent\u0103.", "fr": "D\u00e9cris un moment o\u00f9 la technologie a sembl\u00e9 trop intelligente.", "it": "Descrivi una volta in cui la tecnologia si \u00e8 comportata come se fosse troppo intelligente.", "fi": "Kuvaile kerta, jolloin teknologia toimi liian \u00e4lykk\u00e4\u00e4sti.", "nl": "Beschrijf een moment waarop technologie t\u00e9 slim leek te zijn.", "no": "Beskriv en gang teknologien oppf\u00f8rte seg altfor smart.", "sv": "Beskriv en g\u00e5ng n\u00e4r tekniken betedde sig alldeles f\u00f6r smart.", "pl": "Opisz sytuacj\u0119, kiedy technologia zachowa\u0142a si\u0119 zbyt \u201einteligentnie\u201d."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Describe a time technology acted too smart.';
UPDATE questions
SET translations = '{"en": "You can remove one fear forever\u2014what do you choose?", "da": "Du kan fjerne \u00e9n frygt for altid \u2013 hvilken v\u00e6lger du?", "de": "Du kannst eine Angst f\u00fcr immer beseitigen \u2013 welche w\u00e4hlst du?", "es": "Puedes eliminar un miedo para siempre \u2013 \u00bfcu\u00e1l eliges?", "pt": "Podes eliminar um medo para sempre \u2013 qual escolhes?", "ro": "Po\u021bi elimina o fric\u0103 pentru totdeauna \u2013 care ar fi?", "fr": "Tu peux supprimer une peur pour toujours \u2013 laquelle choisis-tu ?", "it": "Puoi eliminare per sempre una paura: quale scegli?", "fi": "Voit poistaa yhden pelon ikuisesti \u2013 mink\u00e4 valitset?", "nl": "Je mag \u00e9\u00e9n angst voor altijd wegnemen \u2013 welke kies je?", "no": "Du kan fjerne \u00e9n frykt for alltid \u2013 hvilken velger du?", "sv": "Du kan ta bort en r\u00e4dsla f\u00f6r alltid \u2013 vilken v\u00e4ljer du?", "pl": "Mo\u017cesz usun\u0105\u0107 jeden l\u0119k na zawsze \u2013 kt\u00f3ry wybierasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You can remove one fear forever—what do you choose?';
UPDATE questions
SET translations = '{"en": "A stranger insists they know you from a city you\u2019ve never visited\u2014and name a bar you \u201cliked.\u201d Next step?", "da": "En fremmed insisterer p\u00e5, at de kender dig fra en by, du aldrig har bes\u00f8gt \u2013 og n\u00e6vner en bar, du \u201ckunne lide.\u201d Hvad g\u00f8r du?", "de": "Ein Fremder besteht darauf, dich aus einer Stadt zu kennen, die du nie besucht hast \u2013 und nennt eine Bar, die du \u201emochtest\u201c. Was tust du?", "es": "Un extra\u00f1o insiste en que te conoce de una ciudad que nunca visitaste, y nombra un bar que \u201cte gustaba\u201d. \u00bfQu\u00e9 haces?", "pt": "Um estranho insiste que te conhece de uma cidade onde nunca estiveste \u2013 e menciona um bar de que \u201cgostavas\u201d. E agora?", "ro": "Un str\u0103in insist\u0103 c\u0103 te cunoa\u0219te dintr-un ora\u0219 \u00een care n-ai fost niciodat\u0103 \u2013 \u0219i men\u021bioneaz\u0103 un bar care \u201e\u021bi-a pl\u0103cut\u201d. Ce faci?", "fr": "Un inconnu insiste sur le fait qu\u2019il te conna\u00eet d\u2019une ville o\u00f9 tu n\u2019es jamais all\u00e9 \u2013 et nomme un bar que tu \u00ab aimais \u00bb. Que fais-tu ?", "it": "Uno sconosciuto insiste di conoscerti da una citt\u00e0 in cui non sei mai stato/a e nomina un bar che ti \u201cpiaceva\u201d. Prossima mossa?", "fi": "Tuntematon v\u00e4itt\u00e4\u00e4 tuntevansa sinut kaupungista, jossa et ole koskaan k\u00e4ynyt \u2013 ja mainitsee baarin, josta \u201cpidit\u201d. Mit\u00e4 teet seuraavaksi?", "nl": "Een onbekende beweert je te kennen uit een stad waar je nooit bent geweest \u2013 en noemt een bar die je zogenaamd \u201cleuk vond\u201d. Wat nu?", "no": "En fremmed insisterer p\u00e5 at de kjenner deg fra en by du aldri har v\u00e6rt i \u2013 og nevner en bar du visstnok \u201clikte\u201d. Hva gj\u00f8r du n\u00e5?", "sv": "En fr\u00e4mling p\u00e5st\u00e5r att hen k\u00e4nner dig fr\u00e5n en stad du aldrig varit i \u2013 och n\u00e4mner en bar du \u201dgillade\u201d. Vad g\u00f6r du sen?", "pl": "Obca osoba upiera si\u0119, \u017ce zna ci\u0119 z miasta, w kt\u00f3rym nigdy nie by\u0142e\u015b/by\u0142a\u015b \u2013 i wymienia bar, kt\u00f3ry rzekomo \u201elubi\u0142e\u015b/-a\u015b\u201d. Co dalej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A stranger insists they know you from a city you’ve never visited—and name a bar you “liked.” Next step?';
UPDATE questions
SET translations = '{"en": "What\u2019s the creepiest nice thing someone could do for you?", "da": "Hvad er den uhyggeligste venlige ting, nogen kunne g\u00f8re for dig?", "de": "Was ist das gruseligste nette Ding, das jemand f\u00fcr dich tun k\u00f6nnte?", "es": "\u00bfCu\u00e1l es la cosa amable m\u00e1s escalofriante que alguien podr\u00eda hacer por ti?", "pt": "Qual \u00e9 a coisa mais assustadoramente gentil que algu\u00e9m poderia fazer por ti?", "ro": "Care este cel mai \u00eenfior\u0103tor gest dr\u0103gu\u021b pe care cineva l-ar putea face pentru tine?", "fr": "Quelle est la chose gentille la plus effrayante que quelqu\u2019un pourrait faire pour toi ?", "it": "Qual \u00e8 la cosa pi\u00f9 inquietante ma gentile che qualcuno potrebbe fare per te?", "fi": "Mik\u00e4 olisi karmivin mutta silti \u201ckiltti\u201d teko, jonka joku voisi tehd\u00e4 puolestasi?", "nl": "Wat is het griezeligste aardige ding dat iemand voor je zou kunnen doen?", "no": "Hva er det skumleste, men egentlig snille, noen kunne gj\u00f8re for deg?", "sv": "Vad \u00e4r det l\u00e4skigaste sn\u00e4lla n\u00e5gon skulle kunna g\u00f6ra f\u00f6r dig?", "pl": "Jaka jest najbardziej creepowa, ale mi\u0142a rzecz, jak\u0105 kto\u015b m\u00f3g\u0142by dla ciebie zrobi\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the creepiest nice thing someone could do for you?';
UPDATE questions
SET translations = '{"en": "You must spend the night in a museum. Which type would creep you out most (wax figures, medical curiosities, taxidermy, dolls, etc.)\u2014and why?", "da": "Du skal tilbringe natten p\u00e5 et museum. Hvilken type ville skr\u00e6mme dig mest (voksmennesker, medicinske kuriositeter, udstoppede dyr, dukker osv.) \u2013 og hvorfor?", "de": "Du musst die Nacht in einem Museum verbringen. Welche Art w\u00fcrde dich am meisten gruseln (Wachspuppen, medizinische Kuriosit\u00e4ten, Tierpr\u00e4parate, Puppen usw.) \u2013 und warum?", "es": "Debes pasar la noche en un museo. \u00bfQu\u00e9 tipo te asustar\u00eda m\u00e1s (figuras de cera, curiosidades m\u00e9dicas, taxidermia, mu\u00f1ecas, etc.) y por qu\u00e9?", "pt": "Tens de passar a noite num museu. Que tipo te assustaria mais (figuras de cera, curiosidades m\u00e9dicas, taxidermia, bonecas, etc.) \u2013 e porqu\u00ea?", "ro": "Trebuie s\u0103 petreci noaptea \u00eentr-un muzeu. Care tip te-ar speria cel mai tare (figuri de cear\u0103, curiozit\u0103\u021bi medicale, animale \u00eemp\u0103iate, p\u0103pu\u0219i etc.) \u2013 \u0219i de ce?", "fr": "Tu dois passer la nuit dans un mus\u00e9e. Quel type te ferait le plus peur (cire, curiosit\u00e9s m\u00e9dicales, animaux empaill\u00e9s, poup\u00e9es, etc.) \u2013 et pourquoi ?", "it": "Devi passare la notte in un museo. Quale tipo ti inquieterebbe di pi\u00f9 (figure di cera, curiosit\u00e0 mediche, tassidermia, bambole, ecc.) e perch\u00e9?", "fi": "Sinun on vietett\u00e4v\u00e4 y\u00f6 museossa. Millainen museo pelottaisi eniten (vahanuket, l\u00e4\u00e4ketieteelliset kuriositeetit, t\u00e4ytetyt el\u00e4imet, nuket jne.) \u2013 ja miksi?", "nl": "Je moet een nacht in een museum doorbrengen. Welk type zou je het meest laten griezelen (wasfiguren, medische curiosa, opgezette dieren, poppen, etc.) \u2013 en waarom?", "no": "Du m\u00e5 tilbringe natten p\u00e5 et museum. Hvilken type ville skremt deg mest (voksfigurer, medisinske kuriositeter, utstoppede dyr, dukker osv.) \u2013 og hvorfor?", "sv": "Du m\u00e5ste tillbringa natten p\u00e5 ett museum. Vilken typ skulle k\u00e4nnas mest obehaglig (vaxdockor, medicinska kuriositeter, uppstoppade djur, dockor osv.) \u2013 och varf\u00f6r?", "pl": "Musisz sp\u0119dzi\u0107 noc w muzeum. Jaki typ przerazi\u0142by ci\u0119 najbardziej (figury woskowe, ciekawostki medyczne, preparaty, lalki itp.) \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You must spend the night in a museum. Which type would creep you out most (wax figures, medical curiosities, taxidermy, dolls, etc.)—and why?';
UPDATE questions
SET translations = '{"en": "You find a duplicate of your house key in your drawer, newly cut. Do you change locks?", "da": "Du finder en kopi af din husn\u00f8gle i din skuffe, nyklippet. Skifter du l\u00e5s?", "de": "Du findest einen Duplikatschl\u00fcssel deines Hauses in deiner Schublade, frisch geschnitten. Wechselst du die Schl\u00f6sser?", "es": "Encuentras una copia de la llave de tu casa en tu caj\u00f3n, reci\u00e9n hecha. \u00bfCambias las cerraduras?", "pt": "Encontras uma c\u00f3pia da chave de tua casa na gaveta, rec\u00e9m cortada. Mudarias as fechaduras?", "ro": "G\u0103se\u0219ti o copie a cheii casei tale \u00een sertar, proasp\u0103t t\u0103iat\u0103. Schimbi yala?", "fr": "Tu trouves un double de ta cl\u00e9 de maison dans ton tiroir, fra\u00eechement taill\u00e9. Tu changes les serrures ?", "it": "Trovi un duplicato della chiave di casa nel cassetto, appena fatto. Cambi la serratura?", "fi": "L\u00f6yd\u00e4t laatikosta vastik\u00e4\u00e4n tehdyn vara-avaimen kotiisi. Vaihdatko lukot?", "nl": "Je vindt in je lade een nieuw bijgemaakte kopie van je huissleutel. Verwissel je de sloten?", "no": "Du finner en nykopiert husn\u00f8kkel i skuffen din. Skifter du l\u00e5ser?", "sv": "Du hittar en nygjord kopia av din husnyckel i en l\u00e5da. Byter du l\u00e5s?", "pl": "W szufladzie znajdujesz \u015bwie\u017co dorobiony duplikat klucza do domu. Wymieniasz zamki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You find a duplicate of your house key in your drawer, newly cut. Do you change locks?';