UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to retell the same story every time?", "da": "Hvem fort\u00e6ller den samme historie igen og igen?", "de": "Wer erz\u00e4hlt jedes Mal dieselbe Geschichte?", "es": "\u00bfQui\u00e9n siempre cuenta la misma historia?", "pt": "Quem sempre conta a mesma hist\u00f3ria?", "ro": "Cine spune mereu aceea\u0219i poveste?", "fr": "Qui raconte toujours la m\u00eame histoire ?", "it": "Chi \u00e8 pi\u00f9 probabile che racconti la stessa storia ogni volta?", "fi": "Kuka on kaikkein todenn\u00e4k\u00f6isin kertomaan saman tarinan joka kerta?", "nl": "Wie is het meest waarschijnlijk om steeds hetzelfde verhaal te vertellen?", "no": "Hvem er mest sannsynlig til \u00e5 gjenta den samme historien hver gang?", "sv": "Vem \u00e4r mest ben\u00e4gen att \u00e5terber\u00e4tta samma historia varje g\u00e5ng?", "pl": "Kto najprawdopodobniej opowiada t\u0119 sam\u0105 histori\u0119 za ka\u017cdym razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to retell the same story every time?';
UPDATE questions
SET translations = '{"en": "What\u2019s the funniest thing that ever happened on a road trip?", "da": "Hvad er det sjoveste, der nogensinde er sket p\u00e5 en roadtrip?", "de": "Was war das Lustigste, das je auf einem Roadtrip passiert ist?", "es": "\u00bfQu\u00e9 es lo m\u00e1s divertido que ha pasado en un viaje por carretera?", "pt": "Qual foi a coisa mais engra\u00e7ada que j\u00e1 aconteceu numa viagem de carro?", "ro": "Care e cel mai amuzant lucru care s-a \u00eent\u00e2mplat vreodat\u0103 \u00eentr-o excursie?", "fr": "Quelle est la chose la plus dr\u00f4le qui soit arriv\u00e9e lors d\u2019un road trip ?", "it": "Qual \u00e8 stata la cosa pi\u00f9 divertente che ti sia mai successa durante un viaggio in auto?", "fi": "Mik\u00e4 on hauskin asia, joka on koskaan tapahtunut automatkalla?", "nl": "Wat is het grappigste dat ooit is gebeurd tijdens een roadtrip?", "no": "Hva er det morsomste som noen gang har skjedd p\u00e5 en biltur?", "sv": "Vad \u00e4r det roligaste som n\u00e5gonsin har h\u00e4nt p\u00e5 en roadtrip?", "pl": "Co by\u0142o naj\u015bmieszniejszego, co kiedykolwiek wydarzy\u0142o si\u0119 podczas podr\u00f3\u017cy samochodowej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s the funniest thing that ever happened on a road trip?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to fall asleep five minutes into the drive?", "da": "Hvem falder mest sandsynligt i s\u00f8vn fem minutter inde i k\u00f8returen?", "de": "Wer schl\u00e4ft wahrscheinlich f\u00fcnf Minuten nach Fahrtbeginn ein?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que se duerma cinco minutos despu\u00e9s de salir?", "pt": "Quem \u00e9 mais prov\u00e1vel de adormecer cinco minutos depois de sair?", "ro": "Cine adoarme cel mai probabil la cinci minute dup\u0103 ce plec\u0103m?", "fr": "Qui s\u2019endort probablement cinq minutes apr\u00e8s le d\u00e9part ?", "it": "Chi \u00e8 pi\u00f9 probabile che si addormenti cinque minuti dopo essere partito?", "fi": "Kuka todenn\u00e4k\u00f6isesti nukkuu viisi minuuttia ajon alusta?", "nl": "Wie is het meest waarschijnlijk om vijf minuten na het rijden in slaap te vallen?", "no": "Hvem er mest sannsynlig \u00e5 sovne fem minutter etter at vi har begynt \u00e5 kj\u00f8re?", "sv": "Vem \u00e4r mest ben\u00e4gen att somna fem minuter in i k\u00f6rningen?", "pl": "Kto najprawdopodobniej za\u015bnie pi\u0119\u0107 minut po rozpocz\u0119ciu jazdy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to fall asleep five minutes into the drive?';
UPDATE questions
SET translations = '{"en": "Who always forgets their charger when we travel?", "da": "Hvem glemmer altid deres oplader, n\u00e5r vi rejser?", "de": "Wer vergisst immer sein Ladeger\u00e4t, wenn wir reisen?", "es": "\u00bfQui\u00e9n siempre olvida su cargador cuando viajamos?", "pt": "Quem sempre esquece o carregador quando viajamos?", "ro": "Cine uit\u0103 mereu \u00eenc\u0103rc\u0103torul c\u00e2nd c\u0103l\u0103torim?", "fr": "Qui oublie toujours son chargeur quand on voyage ?", "it": "Chi dimentica sempre il proprio caricabatterie quando viaggiamo?", "fi": "Kuka unohtaa aina laturinsa, kun matkustamme?", "nl": "Wie vergeet altijd zijn of haar oplader als we reizen?", "no": "Hvem glemmer alltid laderen sin n\u00e5r vi reiser?", "sv": "Vem gl\u00f6mmer alltid sin laddare n\u00e4r vi reser?", "pl": "Kto zawsze zapomina swojego \u0142adowarki, gdy podr\u00f3\u017cujemy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who always forgets their charger when we travel?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most chaotic morning we\u2019ve ever had before leaving for a trip?", "da": "Hvad er den mest kaotiske morgen, vi nogensinde har haft f\u00f8r en tur?", "de": "Was war der chaotischste Morgen vor einer Reise?", "es": "\u00bfCu\u00e1l ha sido la ma\u00f1ana m\u00e1s ca\u00f3tica antes de un viaje?", "pt": "Qual foi a manh\u00e3 mais ca\u00f3tica antes de uma viagem?", "ro": "Care a fost diminea\u021ba cea mai haotic\u0103 \u00eenainte de o excursie?", "fr": "Quel a \u00e9t\u00e9 le matin le plus chaotique avant un voyage ?", "it": "Qual \u00e8 stata la mattina pi\u00f9 caotica che abbiamo mai avuto prima di partire per un viaggio?", "fi": "Mik\u00e4 on ollut kaoottisin aamu, jonka olemme koskaan kokeneet ennen matkaan l\u00e4ht\u00f6\u00e4?", "nl": "Wat is de meest chaotische ochtend die we ooit hebben gehad voordat we op reis gingen?", "no": "Hva er den mest kaotiske morgenen vi noen gang har hatt f\u00f8r vi dro p\u00e5 tur?", "sv": "Vilken \u00e4r den mest kaotiska morgonen vi n\u00e5gonsin har haft innan vi \u00e5kte p\u00e5 en resa?", "pl": "Jaka by\u0142a najbardziej chaotyczna poranna chwila, jak\u0105 kiedykolwiek mieli\u015bmy przed wyjazdem w podr\u00f3\u017c?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s the most chaotic morning we’ve ever had before leaving for a trip?';
UPDATE questions
SET translations = '{"en": "What\u2019s a story about our grandparents everyone should know?", "da": "Hvad er en historie om bedstefor\u00e6ldre, som alle burde kende?", "de": "Welche Geschichte \u00fcber unsere Gro\u00dfeltern sollte jeder kennen?", "es": "\u00bfCu\u00e1l es una historia sobre nuestros abuelos que todos deber\u00edan conocer?", "pt": "Qual \u00e9 uma hist\u00f3ria sobre os nossos av\u00f3s que todos deveriam conhecer?", "ro": "Care e o poveste despre bunicii no\u0219tri pe care toat\u0103 lumea ar trebui s-o \u0219tie?", "fr": "Quelle histoire sur nos grands-parents tout le monde devrait conna\u00eetre ?", "it": "Qual \u00e8 una storia sui nostri nonni che tutti dovrebbero conoscere?", "fi": "Mik\u00e4 on tarina isoistamme, jonka kaikkien pit\u00e4isi tiet\u00e4\u00e4?", "nl": "Wat is een verhaal over onze grootouders dat iedereen zou moeten weten?", "no": "Hva er en historie om besteforeldrene v\u00e5re som alle burde vite?", "sv": "Vilken historia om v\u00e5ra mor- och farf\u00f6r\u00e4ldrar borde alla k\u00e4nna till?", "pl": "Jaka jest historia o naszych dziadkach, kt\u00f3r\u0105 ka\u017cdy powinien zna\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s a story about our grandparents everyone should know?';
UPDATE questions
SET translations = '{"en": "Who keeps the family photo albums or digital archives?", "da": "Hvem passer p\u00e5 familiealbummerne eller de digitale arkiver?", "de": "Wer pflegt die Familienalben oder digitalen Archive?", "es": "\u00bfQui\u00e9n cuida los \u00e1lbumes de fotos familiares o archivos digitales?", "pt": "Quem cuida dos \u00e1lbuns de fam\u00edlia ou arquivos digitais?", "ro": "Cine are grij\u0103 de albumele foto ale familiei sau arhivele digitale?", "fr": "Qui s\u2019occupe des albums photo ou des archives num\u00e9riques de la famille ?", "it": "Chi tiene gli album fotografici di famiglia o gli archivi digitali?", "fi": "Kuka pit\u00e4\u00e4 perheemme valokuva-albumeita tai digitaalisia arkistoja?", "nl": "Wie bewaart de familie fotoalbums of digitale archieven?", "no": "Hvem har familiealbumene eller de digitale arkivene?", "sv": "Vem h\u00e5ller i familjefotoalbumen eller de digitala arkiven?", "pl": "Kto przechowuje rodzinne albumy ze zdj\u0119ciami lub archiwa cyfrowe?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who keeps the family photo albums or digital archives?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that feels unique about our family?", "da": "Hvad f\u00f8les helt unikt ved vores familie?", "de": "Was f\u00fchlt sich an unserer Familie besonders einzigartig an?", "es": "\u00bfQu\u00e9 se siente \u00fanico acerca de nuestra familia?", "pt": "O que \u00e9 algo que faz a nossa fam\u00edlia ser \u00fanica?", "ro": "Ce e unic la familia noastr\u0103?", "fr": "Qu\u2019est-ce qui rend notre famille vraiment unique ?", "it": "Qual \u00e8 una cosa che ci sembra unica della nostra famiglia?", "fi": "Mik\u00e4 on jotain, mik\u00e4 tuntuu ainutlaatuiselta perheess\u00e4mme?", "nl": "Wat is iets dat uniek aan onze familie voelt?", "no": "Hva er noe som f\u00f8les unikt med familien v\u00e5r?", "sv": "Vad \u00e4r n\u00e5got som k\u00e4nns unikt med v\u00e5r familj?", "pl": "Co\u015b, co wydaje si\u0119 wyj\u0105tkowe w naszej rodzinie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s something that feels unique about our family?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to laugh so hard they can\u2019t breathe?", "da": "Hvem griner s\u00e5 meget, at de ikke kan tr\u00e6kke vejret?", "de": "Wer lacht so sehr, dass er keine Luft mehr bekommt?", "es": "\u00bfQui\u00e9n se r\u00ede tanto que no puede respirar?", "pt": "Quem ri tanto que mal consegue respirar?", "ro": "Cine r\u00e2de at\u00e2t de tare \u00eenc\u00e2t nu mai poate respira?", "fr": "Qui rit tellement qu\u2019il ne peut plus respirer ?", "it": "Chi \u00e8 pi\u00f9 probabile che rida cos\u00ec tanto da non riuscire a respirare?", "fi": "Kuka todenn\u00e4k\u00f6isesti nauraa niin paljon, etteiv\u00e4t he saa henke\u00e4?", "nl": "Wie is het meest waarschijnlijk om zo hard te lachen dat ze niet meer kunnen ademen?", "no": "Hvem er mest sannsynlig til \u00e5 le s\u00e5 mye at de ikke kan puste?", "sv": "Vem \u00e4r mest ben\u00e4gen att skratta s\u00e5 mycket att de inte kan andas?", "pl": "Kto najprawdopodobniej za\u015bmieje si\u0119 tak mocno, \u017ce nie b\u0119dzie m\u00f3g\u0142 oddycha\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to laugh so hard they can’t breathe?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the most dramatic when things go wrong?", "da": "Hvem er mest dramatisk, n\u00e5r ting g\u00e5r galt?", "de": "Wer ist am dramatischsten, wenn etwas schiefl\u00e4uft?", "es": "\u00bfQui\u00e9n es el m\u00e1s dram\u00e1tico cuando algo sale mal?", "pt": "Quem \u00e9 o mais dram\u00e1tico quando as coisas d\u00e3o errado?", "ro": "Cine e cel mai dramatic c\u00e2nd lucrurile merg prost?", "fr": "Qui est le plus dramatique quand les choses tournent mal ?", "it": "Chi \u00e8 il pi\u00f9 drammatico quando le cose vanno male?", "fi": "Kuka on kaikkein dramaattisin, kun asiat menev\u00e4t pieleen?", "nl": "Wie is het meest dramatisch als er iets misgaat?", "no": "Hvem er den mest dramatiske n\u00e5r ting g\u00e5r galt?", "sv": "Vem \u00e4r mest dramatisk n\u00e4r saker g\u00e5r fel?", "pl": "Kto jest najbardziej dramatyczny, gdy co\u015b idzie nie tak?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s the most dramatic when things go wrong?';