UPDATE questions
SET translations = '{"en": "Which of us is more likely to sneak a flirty message during the day?", "da": "Hvem af os er mere tilb\u00f8jelig til at snige en flirtende besked i l\u00f8bet af dagen?", "de": "Wer von uns schickt eher eine flirtende Nachricht w\u00e4hrend des Tages?", "es": "\u00bfQui\u00e9n de los dos suele enviar m\u00e1s mensajes coquetos durante el d\u00eda?", "pt": "Quem de n\u00f3s costuma enviar mais mensagens provocantes durante o dia?", "ro": "Cine dintre noi trimite mai des mesaje cochete \u00een timpul zilei?", "fr": "Lequel de nous deux envoie le plus de messages coquins dans la journ\u00e9e ?", "it": "Quale di noi \u00e8 pi\u00f9 probabile che invii un messaggio flirtante durante il giorno?", "fi": "Kumpi meist\u00e4 on todenn\u00e4k\u00f6isemmin l\u00e4hett\u00e4m\u00e4ss\u00e4 flirttailevaa viesti\u00e4 p\u00e4iv\u00e4n aikana?", "nl": "Wie van ons is waarschijnlijker om overdag een flirterig berichtje te sturen?", "no": "Hvem av oss er mer sannsynlig \u00e5 sende en fl\u00f8rtete melding i l\u00f8pet av dagen?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att smyga iv\u00e4g ett fl\u00f6rtigt meddelande under dagen?", "pl": "Kto z nas jest bardziej sk\u0142onny do wys\u0142ania flirciarskiej wiadomo\u015bci w ci\u0105gu dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to sneak a flirty message during the day?';
UPDATE questions
SET translations = '{"en": "Which of us would start a \u201cfive minutes\u201d moment that turns into an hour?", "da": "Hvem af os ville starte et \"fem minutter\"-\u00f8jeblik, der bliver til en time?", "de": "Wer von uns w\u00fcrde ein \u201ef\u00fcnf Minuten\u201c-Moment beginnen, das zu einer Stunde wird?", "es": "\u00bfQui\u00e9n de los dos empezar\u00eda un \u201cmomento de cinco minutos\u201d que se convierte en una hora?", "pt": "Quem de n\u00f3s come\u00e7aria um \u201cmomento de cinco minutos\u201d que se torna numa hora?", "ro": "Cine dintre noi ar \u00eencepe un \u201emoment de cinci minute\u201d care devine o or\u0103?", "fr": "Lequel de nous deux commencerait un \u201cmoment de cinq minutes\u201d qui dure une heure ?", "it": "Quale di noi inizierebbe un momento di \"cinque minuti\" che si trasforma in un''ora?", "fi": "Kumpi meist\u00e4 aloittaisi \"viiden minuutin\" hetken, joka muuttuu tunniksi?", "nl": "Wie van ons zou een \"vijf minuten\" moment beginnen dat uitloopt op een uur?", "no": "Hvem av oss ville starte et \"fem minutter\" \u00f8yeblikk som blir til en time?", "sv": "Vilken av oss skulle starta ett \"fem minuter\"-\u00f6gonblick som blir en timme?", "pl": "Kto z nas rozpocz\u0105\u0142by \u201epi\u0119ciominutowy\u201d moment, kt\u00f3ry przerodzi\u0142by si\u0119 w godzin\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us would start a “five minutes” moment that turns into an hour?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite way for me to show that I\u2019m craving you?", "da": "Hvad er din yndlingsm\u00e5de for mig at vise, at jeg higer efter dig?", "de": "Wie magst du es am liebsten, wenn ich dir zeige, dass ich dich begehre?", "es": "\u00bfCu\u00e1l es tu forma favorita de mostrarme que me deseas?", "pt": "Qual \u00e9 a tua forma favorita de me mostrar que me desejas?", "ro": "Care este modul t\u0103u preferat de a-mi ar\u0103ta c\u0103 m\u0103 dore\u0219ti?", "fr": "Quelle est ta fa\u00e7on pr\u00e9f\u00e9r\u00e9e de me montrer que tu me d\u00e9sires ?", "it": "Qual \u00e8 il tuo modo preferito per farmi capire che hai voglia di me?", "fi": "Mik\u00e4 on suosikkitapasi, jolla voisin n\u00e4ytt\u00e4\u00e4, ett\u00e4 kaipaan sinua?", "nl": "Wat is jouw favoriete manier waarop ik kan laten zien dat ik naar je verlang?", "no": "Hva er din favorittm\u00e5te for meg \u00e5 vise at jeg lengter etter deg?", "sv": "Vad \u00e4r ditt favorit s\u00e4tt f\u00f6r mig att visa att jag l\u00e4ngtar efter dig?", "pl": "Jaki jest tw\u00f3j ulubiony spos\u00f3b, w jaki mog\u0119 pokaza\u0107, \u017ce ci\u0119 pragn\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite way for me to show that I’m craving you?';
UPDATE questions
SET translations = '{"en": "How important is eye contact for you when we\u2019re close?", "da": "Hvor vigtig er \u00f8jenkontakt for dig, n\u00e5r vi er t\u00e6tte?", "de": "Wie wichtig ist dir Augenkontakt, wenn wir uns nah sind?", "es": "\u00bfQu\u00e9 tan importante es el contacto visual para ti cuando estamos cerca?", "pt": "Qu\u00e3o importante \u00e9 o contacto visual para ti quando estamos juntos?", "ro": "C\u00e2t de important este contactul vizual pentru tine c\u00e2nd suntem aproape?", "fr": "Quelle importance a le contact visuel pour toi quand on est proches ?", "it": "Quanto \u00e8 importante per te il contatto visivo quando siamo vicini?", "fi": "Kuinka t\u00e4rke\u00e4\u00e4 silm\u00e4kontakti on sinulle, kun olemme l\u00e4hell\u00e4?", "nl": "Hoe belangrijk is oogcontact voor jou als we dichtbij zijn?", "no": "Hvor viktig er \u00f8yekontakt for deg n\u00e5r vi er n\u00e6re?", "sv": "Hur viktigt \u00e4r \u00f6gonkontakt f\u00f6r dig n\u00e4r vi \u00e4r n\u00e4ra?", "pl": "Jak wa\u017cny jest dla ciebie kontakt wzrokowy, gdy jeste\u015bmy blisko?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How important is eye contact for you when we’re close?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite type of forplay?", "da": "Hvad er din yndlingsform for leg?", "de": "Was ist deine Lieblingsform des Spiels?", "es": "\u00bfCu\u00e1l es tu tipo favorito de juego?", "pt": "Qual \u00e9 o teu tipo favorito de jogo?", "ro": "Care este tipul t\u0103u preferat de joc?", "fr": "Quel est ton type de jeu pr\u00e9f\u00e9r\u00e9 ?", "it": "Qual \u00e8 il tuo tipo di preliminari preferito?", "fi": "Mik\u00e4 on lempityyppisi esileikiss\u00e4?", "nl": "Wat is jouw favoriete soort voorspel?", "no": "Hva er din favoritt type forspill?", "sv": "Vad \u00e4r din favorittyp av f\u00f6rspel?", "pl": "Jaki jest tw\u00f3j ulubiony rodzaj gry wst\u0119pnej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite type of forplay?';
UPDATE questions
SET translations = '{"en": "What does \u201cexperience\u201d mean to you in bed \u2014 skill, confidence, curiosity?", "da": "Hvad betyder \"erfaring\" for dig i sengen \u2013 f\u00e6rdigheder, selvtillid, nysgerrighed?", "de": "Was bedeutet \u201eErfahrung\u201c f\u00fcr dich im Bett \u2013 K\u00f6nnen, Selbstvertrauen, Neugier?", "es": "\u00bfQu\u00e9 significa \u201cexperiencia\u201d para ti en la cama: habilidad, confianza o curiosidad?", "pt": "O que significa \u201cexperi\u00eancia\u201d para ti na cama \u2013 habilidade, confian\u00e7a ou curiosidade?", "ro": "Ce \u00eenseamn\u0103 \u201eexperien\u021b\u0103\u201d pentru tine \u00een pat \u2013 abilit\u0103\u021bi, \u00eencredere sau curiozitate?", "fr": "Que signifie \u00ab exp\u00e9rience \u00bb pour toi au lit \u2013 comp\u00e9tence, confiance ou curiosit\u00e9 ?", "it": "Cosa significa per te \"esperienza\" a letto \u2014 abilit\u00e0, fiducia, curiosit\u00e0?", "fi": "Mit\u00e4 \"kokemus\" merkitsee sinulle s\u00e4ngyss\u00e4 \u2014 taitoa, itseluottamusta, uteliaisuutta?", "nl": "Wat betekent \"ervaring\" voor jou in bed \u2014 vaardigheid, zelfvertrouwen, nieuwsgierigheid?", "no": "Hva betyr \"erfaring\" for deg i sengen \u2014 ferdigheter, selvtillit, nysgjerrighet?", "sv": "Vad betyder \"erfarenhet\" f\u00f6r dig i s\u00e4ngen \u2014 skicklighet, sj\u00e4lvf\u00f6rtroende, nyfikenhet?", "pl": "Co dla ciebie oznacza \u201edo\u015bwiadczenie\u201d w \u0142\u00f3\u017cku \u2014 umiej\u0119tno\u015b\u0107, pewno\u015b\u0107 siebie, ciekawo\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What does “experience” mean to you in bed — skill, confidence, curiosity?';
UPDATE questions
SET translations = '{"en": "Have you ever felt shy asking for what you want?", "da": "Har du nogensinde f\u00f8lt dig genert over at sp\u00f8rge om det, du vil have?", "de": "Hast du dich jemals gesch\u00e4mt, nach dem zu fragen, was du willst?", "es": "\u00bfAlguna vez te dio verg\u00fcenza pedir lo que quer\u00edas?", "pt": "Alguma vez tiveste vergonha de pedir o que querias?", "ro": "\u021ai-a fost vreodat\u0103 ru\u0219ine s\u0103 ceri ce vrei?", "fr": "As-tu d\u00e9j\u00e0 eu honte de demander ce que tu voulais ?", "it": "Hai mai provato timidezza nel chiedere ci\u00f2 che desideri?", "fi": "Oletko koskaan tuntenut ujoutta pyyt\u00e4ess\u00e4si sit\u00e4, mit\u00e4 haluat?", "nl": "Heb je ooit verlegen gevoeld om te vragen wat je wilt?", "no": "Har du noen gang f\u00f8lt deg sjenert n\u00e5r du skal be om det du \u00f8nsker?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig blyg f\u00f6r att be om det du vill ha?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 nie\u015bmia\u0142y, prosz\u0105c o to, czego chcesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever felt shy asking for what you want?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you\u2019d love to do with me that you\u2019ve never dared to mention before?", "da": "Hvad er \u00e9n ting, du gerne vil lave med mig, som du aldrig har turdet n\u00e6vne f\u00f8r?", "de": "Was ist eine Sache, die du gerne mit mir tun w\u00fcrdest, dich aber nie getraut hast zu sagen?", "es": "\u00bfQu\u00e9 cosa te gustar\u00eda hacer conmigo pero nunca te atreviste a decirlo?", "pt": "O que gostarias de fazer comigo mas nunca tiveste coragem de dizer?", "ro": "Ce \u021bi-ar pl\u0103cea s\u0103 faci cu mine, dar nu ai avut curajul s\u0103 spui?", "fr": "Qu\u2019aimerais-tu faire avec moi que tu n\u2019as jamais os\u00e9 mentionner ?", "it": "Qual \u00e8 una cosa che ti piacerebbe fare con me e che non hai mai osato menzionare prima?", "fi": "Mik\u00e4 on yksi asia, jonka haluaisit tehd\u00e4 kanssani, mutta et ole koskaan rohjennut mainita aiemmin?", "nl": "Wat is \u00e9\u00e9n ding dat je graag met mij zou willen doen, maar dat je nog nooit durfde te noemen?", "no": "Hva er \u00e9n ting du gjerne ville gjort med meg som du aldri har v\u00e5get \u00e5 nevne f\u00f8r?", "sv": "Vad \u00e4r en sak du skulle \u00e4lska att g\u00f6ra med mig som du aldrig v\u00e5gat n\u00e4mna f\u00f6rut?", "pl": "Co\u015b, co chcia\u0142by\u015b zrobi\u0107 ze mn\u0105, a nigdy wcze\u015bniej nie mia\u0142e\u015b odwagi o tym wspomnie\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one thing you’d love to do with me that you’ve never dared to mention before?';
UPDATE questions
SET translations = '{"en": "Is there a side of you, I still haven\u2019t unlocked yet?", "da": "Er der en side af dig, jeg stadig ikke har l\u00e5st op for endnu?", "de": "Gibt es eine Seite von dir, die ich noch nicht entdeckt habe?", "es": "\u00bfHay un lado tuyo que a\u00fan no he descubierto?", "pt": "H\u00e1 um lado teu que eu ainda n\u00e3o descobri?", "ro": "Exist\u0103 o parte din tine pe care nu am descoperit-o \u00eenc\u0103?", "fr": "Y a-t-il un c\u00f4t\u00e9 de toi que je n\u2019ai pas encore d\u00e9couvert ?", "it": "C''\u00e8 un lato di te che non ho ancora sbloccato?", "fi": "Onko sinussa viel\u00e4 puoli, jonka en ole viel\u00e4 avannut?", "nl": "Is er een kant van jou die ik nog niet heb ontdekt?", "no": "Er det en side av deg jeg fortsatt ikke har l\u00e5st opp?", "sv": "Finns det en sida av dig som jag fortfarande inte har l\u00e5st upp?", "pl": "Czy jest jaka\u015b strona ciebie, kt\u00f3rej jeszcze nie odkry\u0142em?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is there a side of you, I still haven’t unlocked yet?';
UPDATE questions
SET translations = '{"en": "Which desire of yours still feels \u201coff-limits,\u201d even though it turns you on?", "da": "Hvilket af dine beg\u00e6r f\u00f8les stadig \"forbudt\", selvom det t\u00e6nder dig?", "de": "Welche deiner Begierden f\u00fchlt sich immer noch \u201everboten\u201c an, obwohl sie dich erregt?", "es": "\u00bfCu\u00e1l de tus deseos a\u00fan se siente \u201cprohibido\u201d aunque te excite?", "pt": "Qual dos teus desejos ainda te parece \u201cproibido\u201d, mesmo que te excite?", "ro": "Care dintre dorin\u021bele tale \u00eenc\u0103 \u021bi se pare \u201einterzis\u0103\u201d, de\u0219i te excit\u0103?", "fr": "Lequel de tes d\u00e9sirs te semble encore \u00ab interdit \u00bb m\u00eame s\u2019il t\u2019excite ?", "it": "Quale tuo desiderio ti sembra ancora \"vietato\", anche se ti eccita?", "fi": "Mik\u00e4 halusi tuntuu edelleen \"kielletylt\u00e4\", vaikka se innostaa sinua?", "nl": "Welke wens van jou voelt nog steeds \"verboden,\" ook al maakt het je opgewonden?", "no": "Hvilket \u00f8nske har du som fortsatt f\u00f8les \"utenfor rekkevidde,\" selv om det tenner deg?", "sv": "Vilken \u00f6nskan har du som fortfarande k\u00e4nns \"utanf\u00f6r gr\u00e4nserna,\" \u00e4ven om den t\u00e4nder dig?", "pl": "Kt\u00f3re z twoich pragnie\u0144 wci\u0105\u017c wydaje si\u0119 \"niedost\u0119pne\", mimo \u017ce ci\u0119 podnieca?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which desire of yours still feels “off-limits,” even though it turns you on?';