UPDATE questions
SET translations = '{"en": "What\u2019s one way we can protect our time from distractions?", "da": "Hvad er \u00e9n m\u00e5de, vi kan beskytte vores tid mod distraktioner p\u00e5?", "de": "Was ist eine M\u00f6glichkeit, unsere Zeit vor Ablenkungen zu sch\u00fctzen?", "es": "\u00bfCu\u00e1l es una forma en que podemos proteger nuestro tiempo de distracciones?", "pt": "Qual \u00e9 uma maneira de protegermos o nosso tempo das distra\u00e7\u00f5es?", "ro": "Care e o modalitate prin care ne putem proteja timpul de distrageri?", "fr": "Quelle est une fa\u00e7on de prot\u00e9ger notre temps des distractions ?", "it": "Qual \u00e8 un modo per proteggere il nostro tempo dalle distrazioni?", "fi": "Mik\u00e4 on yksi tapa suojata aikaamme h\u00e4iri\u00f6ilt\u00e4?", "nl": "Wat is een manier waarop we onze tijd kunnen beschermen tegen afleidingen?", "no": "Hva er en m\u00e5te vi kan beskytte tiden v\u00e5r mot distraksjoner?", "sv": "Vad \u00e4r ett s\u00e4tt vi kan skydda v\u00e5r tid fr\u00e5n distraktioner?", "pl": "Jaki jest jeden spos\u00f3b, w jaki mo\u017cemy chroni\u0107 nasz czas przed rozproszeniami?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s one way we can protect our time from distractions?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that always reminds you of me?", "da": "Hvad er noget, der altid f\u00e5r dig til at t\u00e6nke p\u00e5 mig?", "de": "Was erinnert dich immer an mich?", "es": "\u00bfQu\u00e9 cosa siempre te recuerda a m\u00ed?", "pt": "O que \u00e9 algo que sempre faz voc\u00ea lembrar de mim?", "ro": "Ce lucru te face \u00eentotdeauna s\u0103 te g\u00e2nde\u0219ti la mine?", "fr": "Qu\u2019est-ce qui te fait toujours penser \u00e0 moi ?", "it": "Qualcosa che ti ricorda sempre di me?", "fi": "Mik\u00e4 on jotain, mik\u00e4 aina muistuttaa sinua minusta?", "nl": "Wat is iets dat je altijd aan mij doet denken?", "no": "Hva er noe som alltid minner deg om meg?", "sv": "Vad \u00e4r n\u00e5got som alltid p\u00e5minner dig om mig?", "pl": "Co\u015b, co zawsze przypomina mi o tobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s something that always reminds you of me?';
UPDATE questions
SET translations = '{"en": "When did you last feel completely seen by me?", "da": "Hvorn\u00e5r te-ai sim\u021bit ultima dat\u0103 complet v\u0103zut(\u0103) de mine?", "de": "Wann hast du dich das letzte Mal von mir vollst\u00e4ndig gesehen gef\u00fchlt?", "es": "\u00bfCu\u00e1ndo fue la \u00faltima vez que te sentiste completamente visto/a por m\u00ed?", "pt": "Quando foi a \u00faltima vez que te sentiste totalmente visto/a por mim?", "ro": "C\u00e2nd te-ai sim\u021bit ultima dat\u0103 complet v\u0103zut(\u0103) de mine?", "fr": "Quand t\u2019es-tu senti(e) pleinement vu(e) par moi pour la derni\u00e8re fois ?", "it": "Quando ti sei sentito completamente visto da me l''ultima volta?", "fi": "Milloin tunsit viimeksi, ett\u00e4 olin t\u00e4ysin l\u00e4sn\u00e4 sinulle?", "nl": "Wanneer voelde je je voor het laatst helemaal gezien door mij?", "no": "N\u00e5r f\u00f8lte du deg sist helt sett av meg?", "sv": "N\u00e4r k\u00e4nde du senast att jag verkligen s\u00e5g dig?", "pl": "Kiedy ostatnio czu\u0142e\u015b si\u0119 ca\u0142kowicie dostrzegany przeze mnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When did you last feel completely seen by me?';
UPDATE questions
SET translations = '{"en": "How do you think we handle conflict?", "da": "Hvordan synes du, vi h\u00e5ndterer konflikter?", "de": "Wie, denkst du, gehen wir mit Konflikten um?", "es": "\u00bfC\u00f3mo crees que manejamos el conflicto?", "pt": "Como achas que lidamos com o conflito?", "ro": "Cum crezi c\u0103 gestion\u0103m conflictul?", "fr": "Comment penses-tu que nous g\u00e9rons le conflit ?", "it": "Come pensi che gestiamo i conflitti?", "fi": "Miten luulet, ett\u00e4 k\u00e4sittelemme konflikteja?", "nl": "Hoe denk je dat we met conflicten omgaan?", "no": "Hvordan tror du vi h\u00e5ndterer konflikt?", "sv": "Hur tycker du att vi hanterar konflikt?", "pl": "Jak my\u015blisz, jak radzimy sobie z konfliktami?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How do you think we handle conflict?';
UPDATE questions
SET translations = '{"en": "What do you want our mornings to feel like?", "da": "Hvordan vil du have, at vores morgener skal f\u00f8les?", "de": "Wie m\u00f6chtest du, dass sich unsere Morgen anf\u00fchlen?", "es": "\u00bfC\u00f3mo quieres que se sientan nuestras ma\u00f1anas?", "pt": "Como queres que sejam as nossas manh\u00e3s?", "ro": "Cum ai vrea s\u0103 fie dimine\u021bile noastre?", "fr": "Comment voudrais-tu que soient nos matins ?", "it": "Come vuoi che si sentano le nostre mattine?", "fi": "Milt\u00e4 haluat, ett\u00e4 aamuamme tuntuu?", "nl": "Hoe wil je dat onze ochtenden aanvoelen?", "no": "Hvordan vil du at morgenene v\u00e5re skal f\u00f8les?", "sv": "Hur vill du att v\u00e5ra morgnar ska k\u00e4nnas?", "pl": "Jak chcesz, \u017ceby nasze poranki wygl\u0105da\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What do you want our mornings to feel like?';
UPDATE questions
SET translations = '{"en": "What makes you feel the most energized?", "da": "Hvad f\u00e5r dig til at f\u00f8le dig mest energisk?", "de": "Was l\u00e4sst dich am meisten energiegeladen f\u00fchlen?", "es": "\u00bfQu\u00e9 te hace sentir con m\u00e1s energ\u00eda?", "pt": "O que te faz sentir mais energizado/a?", "ro": "Ce te face s\u0103 te sim\u021bi cel mai plin(\u0103) de energie?", "fr": "Qu\u2019est-ce qui te fait te sentir le plus \u00e9nergis\u00e9(e) ?", "it": "Cosa ti fa sentire pi\u00f9 energico?", "fi": "Mik\u00e4 saa sinut tuntemaan itsesi energisimm\u00e4ksi?", "nl": "Wat geeft jou de meeste energie?", "no": "Hva f\u00e5r deg til \u00e5 f\u00f8le deg mest energisk?", "sv": "Vad f\u00e5r dig att k\u00e4nna dig mest energisk?", "pl": "Co sprawia, \u017ce czujesz si\u0119 najbardziej na\u0142adowany energi\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What makes you feel the most energized?';
UPDATE questions
SET translations = '{"en": "Describe your feelings for me using only 3 words.", "da": "Beskriv dine f\u00f8lelser for mig med kun 3 ord.", "de": "Beschreibe deine Gef\u00fchle f\u00fcr mich in nur 3 W\u00f6rtern.", "es": "Describe tus sentimientos por m\u00ed usando solo 3 palabras.", "pt": "Descreve os teus sentimentos por mim usando apenas 3 palavras.", "ro": "Descrie-\u021bi sentimentele pentru mine \u00een doar 3 cuvinte.", "fr": "D\u00e9cris tes sentiments pour moi en seulement 3 mots.", "it": "Descrivi i tuoi sentimenti per me usando solo 3 parole.", "fi": "Kuvaile tunteitasi minua kohtaan k\u00e4ytt\u00e4en vain kolmea sanaa.", "nl": "Beschrijf je gevoelens voor mij met slechts 3 woorden.", "no": "Beskriv f\u00f8lelsene dine for meg med bare 3 ord.", "sv": "Beskriv dina k\u00e4nslor f\u00f6r mig med endast 3 ord.", "pl": "Opisz swoje uczucia do mnie u\u017cywaj\u0105c tylko 3 s\u0142\u00f3w."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Describe your feelings for me using only 3 words.';
UPDATE questions
SET translations = '{"en": "What memory of us would you put in a time capsule?", "da": "Ce amintire a noastr\u0103 ai pune \u00eentr-o capsul\u0103 a timpului?", "de": "Welche Erinnerung von uns w\u00fcrdest du in eine Zeitkapsel legen?", "es": "\u00bfQu\u00e9 recuerdo nuestro pondr\u00edas en una c\u00e1psula del tiempo?", "pt": "Que mem\u00f3ria nossa colocarias numa c\u00e1psula do tempo?", "ro": "Ce amintire a noastr\u0103 ai pune \u00eentr-o capsul\u0103 a timpului?", "fr": "Quel souvenir de nous mettrais-tu dans une capsule temporelle ?", "it": "Quale ricordo di noi metteresti in una capsula del tempo?", "fi": "Mik\u00e4 muisto meist\u00e4 laittaisit aikakapseliin?", "nl": "Welke herinnering aan ons zou je in een tijdcapsule stoppen?", "no": "Hvilket minne om oss ville du lagt i en tidskapsel?", "sv": "Vilket minne av oss skulle du l\u00e4gga i en tidskapsel?", "pl": "Jakie wspomnienie o nas umie\u015bci\u0142by\u015b w kapsule czasu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What memory of us would you put in a time capsule?';

-- Category: Party Night Talks (75 questions)
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to text their ex after a few drinks?", "da": "Hvem er mest tilb\u00f8jelig til at skrive til deres eks efter et par drinks?", "de": "Wer schreibt am ehesten seinem Ex nach ein paar Drinks?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que le escriba a su ex despu\u00e9s de unas copas?", "pt": "Quem \u00e9 mais prov\u00e1vel enviar mensagem ao ex depois de umas bebidas?", "ro": "Cine e cel mai probabil s\u0103-\u0219i scrie fostului dup\u0103 c\u00e2teva pahare?", "fr": "Qui est le plus susceptible d\u2019envoyer un message \u00e0 son ex apr\u00e8s quelques verres ?", "it": "Chi \u00e8 pi\u00f9 probabile che scriva un messaggio al proprio ex dopo qualche drink?", "fi": "Kuka todenn\u00e4k\u00f6isimmin l\u00e4hett\u00e4\u00e4 viestin eks\u00e4lleen muutaman juoman j\u00e4lkeen?", "nl": "Wie is het meest waarschijnlijk om hun ex te sms''en na een paar drankjes?", "no": "Hvem er mest sannsynlig til \u00e5 sende en melding til eksen etter noen drinker?", "sv": "Vem \u00e4r mest ben\u00e4gen att skicka ett sms till sitt ex efter n\u00e5gra drinkar?", "pl": "Kto najprawdopodobniej napisze do swojego by\u0142ego po kilku drinkach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to text their ex after a few drinks?';UPDATE questions
SET translations = '{"en": "What\u2019s your go-to party anthem?", "da": "Hvad er din go-to festhymne?", "de": "Was ist dein Go-to-Partyhit?", "es": "\u00bfCu\u00e1l es tu himno de fiesta favorito?", "pt": "Qual \u00e9 o teu hino de festa preferido?", "ro": "Care este imnul t\u0103u preferat de petrecere?", "fr": "Quelle est ta chanson de f\u00eate incontournable ?", "it": "Qual \u00e8 il tuo inno da festa preferito?", "fi": "Mik\u00e4 on sinun suosikkikappaleesi juhliin?", "nl": "Wat is jouw favoriete feestnummer?", "no": "Hva er din favoritt festl\u00e5t?", "sv": "Vad \u00e4r din favoritpartyl\u00e5t?", "pl": "Jaki jest tw\u00f3j ulubiony hymn imprezowy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your go-to party anthem?';
UPDATE questions
SET translations = '{"en": "What\u2019s your signature move on the dance floor?", "da": "Hvad er dit signaturmove p\u00e5 dansegulvet?", "de": "Was ist dein Signature-Move auf der Tanzfl\u00e4che?", "es": "\u00bfCu\u00e1l es tu movimiento caracter\u00edstico en la pista de baile?", "pt": "Qual \u00e9 o teu movimento de assinatura na pista de dan\u00e7a?", "ro": "Care este mi\u0219carea ta semn\u0103tur\u0103 pe ringul de dans?", "fr": "Quel est ton pas de danse signature ?", "it": "Qual \u00e8 la tua mossa distintiva sulla pista da ballo?", "fi": "Mik\u00e4 on sinun tavaramerkkiliike tanssilattialla?", "nl": "Wat is jouw kenmerkende beweging op de dansvloer?", "no": "Hva er ditt signaturtrekk p\u00e5 dansegulvet?", "sv": "Vad \u00e4r ditt signaturdrag p\u00e5 dansgolvet?", "pl": "Jaki jest tw\u00f3j znak rozpoznawczy na parkiecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your signature move on the dance floor?';