UPDATE questions
SET translations = '{"en": "What kind of place feels thrillingly off-limits for us?", "da": "Hvilken slags sted f\u00f8les sp\u00e6ndende og forbudt for os?", "de": "Welche Art von Ort f\u00fchlt sich f\u00fcr uns aufregend und verboten an?", "es": "\u00bfQu\u00e9 tipo de lugar te parece emocionante y prohibido para nosotros?", "pt": "Que tipo de lugar te parece excitante e proibido para n\u00f3s?", "ro": "Ce fel de loc \u021bi se pare incitant \u0219i interzis pentru noi?", "fr": "Quel genre d\u2019endroit te semble excitant et interdit pour nous ?", "it": "Che tipo di luogo ci sembra emozionantemente vietato?", "fi": "Mink\u00e4lainen paikka tuntuu j\u00e4nnitt\u00e4v\u00e4sti kielletylt\u00e4 meille?", "nl": "Wat voor soort plek voelt spannend verboden voor ons?", "no": "Hvilken type sted f\u00f8les spennende og utenfor rekkevidde for oss?", "sv": "Vilken typ av plats k\u00e4nns sp\u00e4nnande otillg\u00e4nglig f\u00f6r oss?", "pl": "Jakie miejsce wydaje si\u0119 nam ekscytuj\u0105co niedost\u0119pne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of place feels thrillingly off-limits for us?';
UPDATE questions
SET translations = '{"en": "Does the thought of almost being caught ever turn you on?", "da": "T\u00e6nder tanken om n\u00e6sten at blive opdaget dig nogensinde?", "de": "Macht dich der Gedanke an, fast erwischt zu werden, an?", "es": "\u00bfTe excita la idea de casi ser descubierto/a?", "pt": "Excita-te a ideia de quase seres apanhado/a?", "ro": "Te excit\u0103 g\u00e2ndul c\u0103 ai putea fi aproape descoperit(\u0103)?", "fr": "L\u2019id\u00e9e d\u2019\u00eatre presque surpris(e), t\u2019excite-t-elle ?", "it": "Il pensiero di essere quasi scoperto ti eccita mai?", "fi": "Kiehtooko ajatus siit\u00e4, ett\u00e4 melkein j\u00e4\u00e4 kiinni, koskaan sinua?", "nl": "Maakt de gedachte om bijna betrapt te worden je ooit opgewonden?", "no": "F\u00e5r tanken p\u00e5 \u00e5 nesten bli tatt deg noen gang til \u00e5 f\u00f8le deg tent?", "sv": "Blir du n\u00e5gonsin upphetsad av tanken p\u00e5 att n\u00e4stan bli p\u00e5kommen?", "pl": "Czy my\u015bl o prawie byciu przy\u0142apanym kiedykolwiek ci\u0119 podnieca?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Does the thought of almost being caught ever turn you on?';
UPDATE questions
SET translations = '{"en": "Would you enjoy a little risk \u2014 like a quiet, hidden spot only we know about?", "da": "Ville du nyde en lille risiko \u2013 som et stille, skjult sted, som kun vi kender til?", "de": "W\u00fcrdest du ein kleines Risiko genie\u00dfen \u2013 einen stillen, geheimen Ort, den nur wir kennen?", "es": "\u00bfDisfrutar\u00edas un poco de riesgo, como un lugar secreto solo nuestro?", "pt": "Gostarias de um pouco de risco \u2013 um lugar secreto s\u00f3 nosso?", "ro": "\u021ai-ar pl\u0103cea pu\u021bin risc \u2013 un loc ascuns doar al nostru?", "fr": "Aimerais-tu un peu de risque \u2013 un endroit secret que nous seuls connaissons ?", "it": "Ti piacerebbe un po'' di rischio \u2014 come un posto tranquillo e nascosto che conosciamo solo noi?", "fi": "Nauttisitko pienest\u00e4 riskist\u00e4 \u2014 kuten rauhallisesta, piilotetusta paikasta, jonka vain me tied\u00e4mme?", "nl": "Zou je genieten van een klein risico \u2014 zoals een rustige, verborgen plek die alleen wij kennen?", "no": "Ville du sette pris p\u00e5 litt risiko \u2014 som et stille, skjult sted bare vi vet om?", "sv": "Skulle du tycka om en liten risk \u2014 som en tyst, g\u00f6md plats som bara vi k\u00e4nner till?", "pl": "Czy cieszy\u0142by\u015b si\u0119 z odrobiny ryzyka \u2014 na przyk\u0142ad z cichego, ukrytego miejsca, o kt\u00f3rym wiemy tylko my?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Would you enjoy a little risk — like a quiet, hidden spot only we know about?';
UPDATE questions
SET translations = '{"en": "What\u2019s one fantasy of ours that you\u2019d actually want to make happen?", "da": "Hvilken fantasi ville du rent faktisk gerne f\u00f8re ud i livet?", "de": "Welche Fantasie w\u00fcrdest du wirklich gerne ausleben?", "es": "\u00bfQu\u00e9 fantas\u00eda te gustar\u00eda realmente hacer realidad?", "pt": "Que fantasia gostarias mesmo de realizar?", "ro": "Ce fantezie \u021bi-ar pl\u0103cea cu adev\u0103rat s\u0103 tr\u0103ie\u0219ti?", "fr": "Quelle fantaisie aimerais-tu vraiment r\u00e9aliser ?", "it": "Qual \u00e8 una nostra fantasia che vorresti davvero realizzare?", "fi": "Mik\u00e4 on yksi fantasiasi, jonka haluaisit todella toteuttaa?", "nl": "Wat is \u00e9\u00e9n fantasie van ons die je eigenlijk werkelijkheid zou willen laten worden?", "no": "Hva er en av v\u00e5re fantasier som du faktisk ville \u00f8nsket \u00e5 gj\u00f8re til virkelighet?", "sv": "Vilken av v\u00e5ra fantasier skulle du faktiskt vilja f\u00f6rverkliga?", "pl": "Jakie jedno nasze marzenie chcia\u0142by\u015b naprawd\u0119 zrealizowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one fantasy of ours that you’d actually want to make happen?';
UPDATE questions
SET translations = '{"en": "How do you feel about me being a bit more dominant \u2014 or would you rather take charge?", "da": "Hvad synes du om, at jeg er lidt mere dominerende \u2013 eller vil du hellere tage styringen?", "de": "Wie findest du es, wenn ich etwas dominanter bin \u2013 oder \u00fcbernimmst du lieber die Kontrolle?", "es": "\u00bfQu\u00e9 opinas si yo fuera un poco m\u00e1s dominante, o prefieres tomar el control?", "pt": "O que achas se eu fosse um pouco mais dominante, ou preferes tu o controlo?", "ro": "Ce p\u0103rere ai dac\u0103 a\u0219 fi pu\u021bin mai dominant(\u0103), sau preferi tu s\u0103 preiei controlul?", "fr": "Que penses-tu si j\u2019\u00e9tais un peu plus dominant(e) \u2013 ou pr\u00e9f\u00e8res-tu prendre le contr\u00f4le ?", "it": "Come ti senti riguardo al fatto che io sia un po'' pi\u00f9 dominante \u2014 o preferiresti prendere tu il comando?", "fi": "Milt\u00e4 sinusta tuntuu, ett\u00e4 olisin hieman dominoivampi \u2014 vai haluaisitko mieluummin ottaa ohjat itsellesi?", "nl": "Hoe voel je je over het idee dat ik wat dominanter ben \u2014 of heb je liever dat jij de leiding neemt?", "no": "Hvordan f\u00f8ler du om at jeg er litt mer dominerende \u2014 eller ville du heller ta kontrollen?", "sv": "Hur k\u00e4nner du f\u00f6r att jag \u00e4r lite mer dominant \u2014 eller skulle du hellre ta kommandot?", "pl": "Jak si\u0119 czujesz z tym, \u017ce by\u0142bym troch\u0119 bardziej dominuj\u0105cy \u2014 czy wola\u0142by\u015b przej\u0105\u0107 kontrol\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about me being a bit more dominant — or would you rather take charge?';
UPDATE questions
SET translations = '{"en": "How do you feel about us shopping for lingerie or underwear together?", "da": "Hvad synes du om, at vi shopper lingeri eller undert\u00f8j sammen?", "de": "Wie f\u00e4ndest du es, wenn wir gemeinsam Dessous einkaufen gehen?", "es": "\u00bfQu\u00e9 opinas de ir juntos a comprar lencer\u00eda o ropa interior?", "pt": "O que achas de irmos juntos comprar lingerie ou roupa interior?", "ro": "Ce p\u0103rere ai s\u0103 mergem \u00eempreun\u0103 s\u0103 cump\u0103r\u0103m lenjerie?", "fr": "Que penses-tu d\u2019aller acheter de la lingerie ensemble ?", "it": "Cosa ne pensi di andare a comprare insieme della lingerie o della biancheria intima?", "fi": "Milt\u00e4 sinusta tuntuu, jos menisimme yhdess\u00e4 ostamaan alusvaatteita tai alushousuja?", "nl": "Hoe voel je je over het samen winkelen voor lingerie of ondergoed?", "no": "Hvordan f\u00f8ler du om at vi handler undert\u00f8y sammen?", "sv": "Hur k\u00e4nner du f\u00f6r att vi handlar underkl\u00e4der tillsammans?", "pl": "Co my\u015blisz o tym, \u017ceby\u015bmy razem poszli na zakupy po bielizn\u0119 lub majtki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about us shopping for lingerie or underwear together?';
UPDATE questions
SET translations = '{"en": "What turns you on the most: making noise, or trying to stay quiet while we\u2019re doing it?", "da": "Hvad t\u00e6nder dig mest: At lave st\u00f8j eller at fors\u00f8ge at forblive stille, mens vi g\u00f8r det?", "de": "Was erregt dich mehr \u2013 laut zu sein oder zu versuchen, still zu bleiben, w\u00e4hrend wir es tun?", "es": "\u00bfQu\u00e9 te excita m\u00e1s: hacer ruido o intentar mantenerte en silencio mientras lo hacemos?", "pt": "O que te excita mais: fazer barulho ou tentar ficar em sil\u00eancio enquanto o fazemos?", "ro": "Ce te excit\u0103 mai mult: s\u0103 faci zgomot sau s\u0103 \u00eencerci s\u0103 r\u0103m\u00e2i t\u0103cut(\u0103) \u00een timp ce o facem?", "fr": "Qu\u2019est-ce qui t\u2019excite le plus : faire du bruit ou essayer de rester silencieux(se) pendant qu\u2019on le fait ?", "it": "Cosa ti eccita di pi\u00f9: fare rumore o cercare di rimanere in silenzio mentre lo facciamo?", "fi": "Mik\u00e4 saa sinut eniten innostumaan: melun tekeminen vai yritt\u00e4minen pysy\u00e4 hiljaa, kun teemme sit\u00e4?", "nl": "Wat opwindt je het meest: geluid maken, of proberen stil te blijven terwijl we het doen?", "no": "Hva tenner deg mest: \u00e5 lage lyd, eller \u00e5 pr\u00f8ve \u00e5 v\u00e6re stille mens vi gj\u00f8r det?", "sv": "Vad t\u00e4nder dig mest: att g\u00f6ra ljud, eller att f\u00f6rs\u00f6ka vara tyst medan vi g\u00f6r det?", "pl": "Co najbardziej ci\u0119 podnieca: robienie ha\u0142asu, czy pr\u00f3ba bycia cicho podczas tego, co robimy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What turns you on the most: making noise, or trying to stay quiet while we’re doing it?';
UPDATE questions
SET translations = '{"en": "What\u2019s the weirdest thing that unexpectedly turned you on about me?", "da": "Hvad var det m\u00e6rkeligste, der uventet t\u00e6ndte dig ved mig?", "de": "Was war das Seltsamste, das dich unerwartet an mir erregt hat?", "es": "\u00bfQu\u00e9 fue lo m\u00e1s extra\u00f1o que inesperadamente te excit\u00f3 de m\u00ed?", "pt": "O que foi o mais estranho que inesperadamente te excitou em mim?", "ro": "Care a fost cel mai ciudat lucru care te-a excitat la mine f\u0103r\u0103 s\u0103 te a\u0219tep\u021bi?", "fr": "Quelle est la chose la plus \u00e9trange qui t\u2019a excit\u00e9(e) chez moi ?", "it": "Qual \u00e8 la cosa pi\u00f9 strana che ti ha sorpreso e ti ha attratto di me?", "fi": "Mik\u00e4 on oudoin asia, joka yll\u00e4tt\u00e4en her\u00e4tti sinussa kiinnostusta minua kohtaan?", "nl": "Wat is het vreemdste dat je onverwacht aantrekkelijk vond aan mij?", "no": "Hva er det merkeligste som uventet tente deg p\u00e5 med meg?", "sv": "Vad \u00e4r det konstigaste som ov\u00e4ntat t\u00e4nde dig p\u00e5 mig?", "pl": "Co by\u0142o najdziwniejszym czym\u015b, co niespodziewanie ci\u0119 we mnie podnieci\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s the weirdest thing that unexpectedly turned you on about me?';
UPDATE questions
SET translations = '{"en": "Do you like slow kisses on your back and neck?", "da": "Kan du lide langsomme kys p\u00e5 din ryg og nakke?", "de": "Magst du langsame K\u00fcsse auf deinem R\u00fccken und Nacken?", "es": "\u00bfTe gustan los besos lentos en la espalda y el cuello?", "pt": "Gostas de beijos lentos nas costas e no pesco\u00e7o?", "ro": "\u00ce\u021bi plac s\u0103ruturile lente pe spate \u0219i pe g\u00e2t?", "fr": "Aimes-tu les baisers lents sur ton dos et ton cou ?", "it": "Ti piacciono i baci lenti sulla schiena e sul collo?", "fi": "Pid\u00e4tk\u00f6 hitaista suudelmista sel\u00e4ss\u00e4si ja kaulassasi?", "nl": "Hou je van langzame kussen op je rug en nek?", "no": "Liker du sakte kyss p\u00e5 ryggen og nakken?", "sv": "Tycker du om l\u00e5ngsamma kyssar p\u00e5 ryggen och nacken?", "pl": "Czy lubisz powolne poca\u0142unki na plecach i szyi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you like slow kisses on your back and neck?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing about our sex life you\u2019d love to explore more deeply?", "da": "Hvad er \u00e9n ting ved vores sexliv, du gerne vil udforske dybere?", "de": "Was ist eine Sache an unserem Sexleben, die du gerne tiefer erforschen w\u00fcrdest?", "es": "\u00bfQu\u00e9 es algo de nuestra vida sexual que te gustar\u00eda explorar m\u00e1s?", "pt": "O que \u00e9 algo da nossa vida sexual que gostarias de explorar mais?", "ro": "Ce este ceva din via\u021ba noastr\u0103 sexual\u0103 ce ai vrea s\u0103 explorezi mai mult?", "fr": "Qu\u2019aimerais-tu explorer davantage dans notre vie sexuelle ?", "it": "Qual \u00e8 una cosa della nostra vita sessuale che ti piacerebbe esplorare pi\u00f9 a fondo?", "fi": "Mik\u00e4 on yksi asia seksiel\u00e4m\u00e4st\u00e4mme, jota haluaisit tutkia syvemmin?", "nl": "Wat is \u00e9\u00e9n ding over ons seksleven dat je graag dieper zou willen verkennen?", "no": "Hva er \u00e9n ting ved v\u00e5rt sexliv du gjerne vil utforske dypere?", "sv": "Vad \u00e4r en sak om v\u00e5rt sexliv som du skulle vilja utforska djupare?", "pl": "Co\u015b, co chcia\u0142by\u015b zg\u0142\u0119bi\u0107 bardziej w naszym \u017cyciu seksualnym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s one thing about our sex life you’d love to explore more deeply?';