UPDATE questions
SET translations = '{"en": "Would you rather always have to talk in rhyme or always hum before speaking?", "da": "Ville du hellere altid skulle tale i rim eller nynne f\u00f8r du taler?", "de": "W\u00fcrdest du lieber immer in Reimen sprechen oder vor dem Sprechen summen?", "es": "\u00bfPreferir\u00edas hablar siempre en rimas o tararear antes de hablar?", "pt": "Preferias falar sempre em rimas ou cantarolar antes de falar?", "ro": "Ai prefera s\u0103 vorbe\u0219ti mereu \u00een rime sau s\u0103 fredonezi \u00eenainte s\u0103 vorbe\u0219ti?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours parler en rimes ou fredonner avant de parler ?", "it": "Preferiresti dover sempre parlare in rima o dover sempre fare un humm prima di parlare?", "fi": "Haluaisitko mieluummin puhua aina riimeiss\u00e4 vai aina humista ennen puhumista?", "nl": "Zou je liever altijd in rijm moeten praten of altijd moeten neuri\u00ebn voordat je spreekt?", "no": "Ville du heller alltid m\u00e5tte snakke p\u00e5 rim eller alltid nynne f\u00f8r du snakker?", "sv": "Skulle du hellre alltid beh\u00f6va prata p\u00e5 rim eller alltid nynna innan du pratar?", "pl": "Czy wola\u0142by\u015b zawsze m\u00f3wi\u0107 w rymach, czy zawsze humowa\u0107 przed m\u00f3wieniem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always have to talk in rhyme or always hum before speaking?';
UPDATE questions
SET translations = '{"en": "Would you rather be known for your great sense of humor or your great sense of style?", "da": "Ville du hellere v\u00e6re kendt for din humor eller din stil?", "de": "W\u00e4rst du lieber f\u00fcr deinen Humor oder deinen Stil bekannt?", "es": "\u00bfPreferir\u00edas ser conocido por tu gran sentido del humor o por tu gran estilo?", "pt": "Preferias ser conhecido pelo teu sentido de humor ou pelo teu estilo?", "ro": "Ai prefera s\u0103 fii cunoscut pentru sim\u021bul umorului sau pentru stilul t\u0103u?", "fr": "Pr\u00e9f\u00e9rerais-tu \u00eatre connu pour ton humour ou pour ton style ?", "it": "Preferiresti essere conosciuto per il tuo grande senso dell''umorismo o per il tuo grande senso dello stile?", "fi": "Haluaisitko olla tunnettu mahtavasta huumoristasi vai upeasta tyylist\u00e4si?", "nl": "Zou je liever bekend staan om je geweldige gevoel voor humor of om je geweldige gevoel voor stijl?", "no": "Ville du heller bli kjent for din gode sans for humor eller din gode sans for stil?", "sv": "Skulle du hellre vara k\u00e4nd f\u00f6r din fantastiska humor eller din fantastiska stil?", "pl": "Czy wola\u0142by\u015b by\u0107 znany ze swojego wspania\u0142ego poczucia humoru, czy z doskona\u0142ego wyczucia stylu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be known for your great sense of humor or your great sense of style?';
UPDATE questions
SET translations = '{"en": "Would you rather take a cold shower every day or never use air conditioning again?", "da": "Ville du hellere tage et koldt brusebad hver dag eller aldrig bruge aircondition igen?", "de": "W\u00fcrdest du lieber jeden Tag kalt duschen oder nie wieder Klimaanlage benutzen?", "es": "\u00bfPreferir\u00edas ducharte con agua fr\u00eda todos los d\u00edas o no usar nunca m\u00e1s aire acondicionado?", "pt": "Preferias tomar banho frio todos os dias ou nunca mais usar ar condicionado?", "ro": "Ai prefera s\u0103 faci du\u0219 rece zilnic sau s\u0103 nu mai folose\u0219ti aer condi\u021bionat?", "fr": "Pr\u00e9f\u00e9rerais-tu prendre une douche froide tous les jours ou ne plus jamais utiliser la climatisation ?", "it": "Preferiresti fare una doccia fredda ogni giorno o non usare mai pi\u00f9 l''aria condizionata?", "fi": "Haluaisitko mieluummin ottaa kylm\u00e4n suihkun joka p\u00e4iv\u00e4 vai olla k\u00e4ytt\u00e4m\u00e4tt\u00e4 ilmastointia en\u00e4\u00e4 koskaan?", "nl": "Zou je liever elke dag een koude douche nemen of nooit meer airconditioning gebruiken?", "no": "Ville du heller ta en kald dusj hver dag eller aldri bruke aircondition igjen?", "sv": "Skulle du hellre ta en kall dusch varje dag eller aldrig anv\u00e4nda luftkonditionering igen?", "pl": "Czy wola\u0142by\u015b bra\u0107 zimny prysznic codziennie, czy nigdy wi\u0119cej nie korzysta\u0107 z klimatyzacji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather take a cold shower every day or never use air conditioning again?';
UPDATE questions
SET translations = '{"en": "Would you rather only drink coffee or only drink tea for the rest of your life?", "da": "Ville du hellere kun drikke kaffe eller kun te resten af livet?", "de": "W\u00fcrdest du lieber nur Kaffee oder nur Tee f\u00fcr den Rest deines Lebens trinken?", "es": "\u00bfPreferir\u00edas beber solo caf\u00e9 o solo t\u00e9 por el resto de tu vida?", "pt": "Preferias beber apenas caf\u00e9 ou apenas ch\u00e1 para o resto da tua vida?", "ro": "Ai prefera s\u0103 bei doar cafea sau doar ceai pentru tot restul vie\u021bii?", "fr": "Pr\u00e9f\u00e9rerais-tu ne boire que du caf\u00e9 ou que du th\u00e9 pour le reste de ta vie ?", "it": "Preferiresti bere solo caff\u00e8 o solo t\u00e8 per il resto della tua vita?", "fi": "Kumpaa mieluummin joisit loppuel\u00e4m\u00e4si: vain kahvia vai vain teet\u00e4?", "nl": "Zou je liever de rest van je leven alleen koffie of alleen thee drinken?", "no": "Ville du heller bare drikke kaffe eller bare drikke te resten av livet?", "sv": "Skulle du hellre bara dricka kaffe eller bara dricka te resten av ditt liv?", "pl": "Czy wola\u0142by\u015b pi\u0107 tylko kaw\u0119, czy tylko herbat\u0119 przez reszt\u0119 swojego \u017cycia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather only drink coffee or only drink tea for the rest of your life?';
UPDATE questions
SET translations = '{"en": "Would you rather always wear the same outfit or never wear the same outfit twice?", "da": "Ville du hellere altid have det samme t\u00f8j p\u00e5 eller aldrig have det samme outfit to gange?", "de": "W\u00fcrdest du lieber immer dasselbe Outfit tragen oder nie zweimal dasselbe?", "es": "\u00bfPreferir\u00edas usar siempre el mismo atuendo o nunca repetir atuendo?", "pt": "Preferias usar sempre a mesma roupa ou nunca repetir a mesma?", "ro": "Ai prefera s\u0103 por\u021bi mereu acelea\u0219i haine sau niciodat\u0103 acelea\u0219i de dou\u0103 ori?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours porter la m\u00eame tenue ou ne jamais porter la m\u00eame deux fois ?", "it": "Preferiresti indossare sempre gli stessi vestiti o non indossare mai gli stessi vestiti due volte?", "fi": "Haluaisitko mieluummin aina pukeutua samaan asuun vai olla koskaan pukeutumatta samaan asuun kahdesti?", "nl": "Zou je liever altijd dezelfde outfit dragen of nooit dezelfde outfit twee keer?", "no": "Ville du heller alltid ha p\u00e5 deg det samme antrekket eller aldri bruke det samme antrekket to ganger?", "sv": "Skulle du hellre alltid ha p\u00e5 dig samma kl\u00e4der eller aldrig ha p\u00e5 dig samma kl\u00e4der tv\u00e5 g\u00e5nger?", "pl": "Czy wola\u0142by\u015b zawsze nosi\u0107 ten sam str\u00f3j, czy nigdy nie nosi\u0107 tego samego stroju dwa razy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always wear the same outfit or never wear the same outfit twice?';
UPDATE questions
SET translations = '{"en": "Would you rather host every family gathering or never host again?", "da": "Ville du hellere v\u00e6re v\u00e6rt for hver familiefest eller aldrig mere v\u00e6re v\u00e6rt?", "de": "W\u00fcrdest du lieber jedes Familientreffen ausrichten oder nie wieder eines ausrichten?", "es": "\u00bfPreferir\u00edas organizar todas las reuniones familiares o no volver a organizarlas nunca?", "pt": "Preferias organizar todas as reuni\u00f5es de fam\u00edlia ou nunca mais organizar nenhuma?", "ro": "Ai prefera s\u0103 g\u0103zduie\u0219ti toate reuniunile de familie sau s\u0103 nu mai g\u0103zduie\u0219ti niciuna?", "fr": "Pr\u00e9f\u00e9rerais-tu organiser chaque r\u00e9union de famille ou ne plus jamais en organiser ?", "it": "Preferiresti ospitare ogni riunione di famiglia o non ospitare mai pi\u00f9?", "fi": "Haluaisitko is\u00e4nn\u00f6id\u00e4 jokaisen perhejuhlan vai et koskaan is\u00e4nn\u00f6id\u00e4 en\u00e4\u00e4?", "nl": "Zou je liever elke familiebijeenkomst organiseren of nooit meer organiseren?", "no": "Ville du heller v\u00e6rt vert for hver familie sammenkomst eller aldri v\u00e6rt vert igjen?", "sv": "Skulle du hellre vara v\u00e4rd f\u00f6r varje familjesammankomst eller aldrig vara v\u00e4rd igen?", "pl": "Czy wola\u0142by\u015b organizowa\u0107 ka\u017cde spotkanie rodzinne, czy nigdy wi\u0119cej nie organizowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather host every family gathering or never host again?';
UPDATE questions
SET translations = '{"en": "Would you rather have a night out with friends or a cozy night in?", "da": "Ville du hellere tage ud med venner eller have en hyggelig aften hjemme?", "de": "W\u00fcrdest du lieber mit Freunden ausgehen oder einen gem\u00fctlichen Abend zu Hause haben?", "es": "\u00bfPreferir\u00edas salir con amigos o tener una noche acogedora en casa?", "pt": "Preferias sair com amigos ou ter uma noite acolhedora em casa?", "ro": "Ai prefera s\u0103 ie\u0219i cu prietenii sau s\u0103 ai o sear\u0103 lini\u0219tit\u0103 acas\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu sortir avec des amis ou passer une soir\u00e9e tranquille \u00e0 la maison ?", "it": "Preferiresti una serata fuori con gli amici o una serata accogliente a casa?", "fi": "Haluaisitko mieluummin viett\u00e4\u00e4 illan yst\u00e4vien kanssa ulkona vai nauttia mukavasta illasta kotona?", "nl": "Zou je liever een avondje uit met vrienden hebben of een gezellige avond thuis?", "no": "Vil du heller ha en kveld ute med venner eller en koselig kveld hjemme?", "sv": "Skulle du hellre ha en utekv\u00e4ll med v\u00e4nner eller en mysig kv\u00e4ll hemma?", "pl": "Czy wola\u0142by\u015b wyj\u015bcie na miasto z przyjaci\u00f3\u0142mi, czy przytulny wiecz\u00f3r w domu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have a night out with friends or a cozy night in?';
UPDATE questions
SET translations = '{"en": "Would you rather take a long scenic walk or a short brisk run?", "da": "Ville du hellere g\u00e5 en lang tur i naturen eller en kort hurtig l\u00f8betur?", "de": "W\u00fcrdest du lieber einen langen Spaziergang oder einen kurzen Lauf machen?", "es": "\u00bfPreferir\u00edas dar un paseo largo y tranquilo o una carrera corta y r\u00e1pida?", "pt": "Preferias fazer uma caminhada longa e tranquila ou uma corrida curta?", "ro": "Ai prefera o plimbare lung\u0103 \u0219i relaxat\u0103 sau o alergare scurt\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu faire une longue promenade ou un petit jogging rapide ?", "it": "Preferiresti fare una lunga passeggiata panoramica o una breve corsa veloce?", "fi": "Haluaisitko mieluummin tehd\u00e4 pitk\u00e4n maisemak\u00e4velyn vai lyhyen reippaan juoksun?", "nl": "Zou je liever een lange schilderachtige wandeling maken of een korte stevige run?", "no": "Ville du heller ta en lang naturskj\u00f8nn spasertur eller en kort rask l\u00f8petur?", "sv": "Skulle du hellre ta en l\u00e5ng natursk\u00f6n promenad eller en kort rask l\u00f6pning?", "pl": "Czy wola\u0142by\u015b d\u0142ugi, malowniczy spacer, czy kr\u00f3tk\u0105, energiczn\u0105 przebie\u017ck\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather take a long scenic walk or a short brisk run?';
UPDATE questions
SET translations = '{"en": "Would you rather be able to cook any recipe perfectly or play any instrument well?", "da": "Ville du hellere kunne lave enhver opskrift perfekt eller spille et instrument godt?", "de": "W\u00fcrdest du lieber jedes Rezept perfekt kochen oder jedes Instrument gut spielen k\u00f6nnen?", "es": "\u00bfPreferir\u00edas cocinar cualquier receta perfectamente o tocar bien cualquier instrumento?", "pt": "Preferias cozinhar qualquer receita perfeitamente ou tocar bem qualquer instrumento?", "ro": "Ai prefera s\u0103 g\u0103te\u0219ti orice re\u021bet\u0103 perfect sau s\u0103 c\u00e2n\u021bi bine la orice instrument?", "fr": "Pr\u00e9f\u00e9rerais-tu cuisiner parfaitement n\u2019importe quelle recette ou bien jouer de n\u2019importe quel instrument ?", "it": "Preferiresti essere in grado di cucinare perfettamente qualsiasi ricetta o suonare bene qualsiasi strumento?", "fi": "Haluaisitko mieluummin osata valmistaa mink\u00e4 tahansa reseptin t\u00e4ydellisesti vai soittaa mit\u00e4 tahansa instrumenttia hyvin?", "nl": "Zou je liever elk recept perfect kunnen koken of elk instrument goed kunnen bespelen?", "no": "Ville du heller kunne lage hvilken som helst oppskrift perfekt eller spille hvilket som helst instrument godt?", "sv": "Skulle du hellre kunna laga vilken recept som helst perfekt eller spela vilket instrument som helst bra?", "pl": "Czy wola\u0142by\u015b umie\u0107 gotowa\u0107 ka\u017cd\u0105 potraw\u0119 idealnie, czy gra\u0107 na ka\u017cdym instrumencie dobrze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be able to cook any recipe perfectly or play any instrument well?';
UPDATE questions
SET translations = '{"en": "Would you rather travel by plane or by train?", "da": "Ville du hellere rejse med fly eller tog?", "de": "W\u00fcrdest du lieber mit dem Flugzeug oder mit dem Zug reisen?", "es": "\u00bfPreferir\u00edas viajar en avi\u00f3n o en tren?", "pt": "Preferias viajar de avi\u00e3o ou de comboio?", "ro": "Ai prefera s\u0103 c\u0103l\u0103tore\u0219ti cu avionul sau cu trenul?", "fr": "Pr\u00e9f\u00e9rerais-tu voyager en avion ou en train ?", "it": "Preferiresti viaggiare in aereo o in treno?", "fi": "Matkustaisitko mieluummin lent\u00e4en vai junalla?", "nl": "Zou je liever met het vliegtuig of met de trein reizen?", "no": "Ville du heller reise med fly eller med tog?", "sv": "Skulle du hellre resa med flygplan eller med t\u00e5g?", "pl": "Czy wola\u0142by\u015b podr\u00f3\u017cowa\u0107 samolotem czy poci\u0105giem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather travel by plane or by train?';