UPDATE questions
SET translations = '{"en": "What travel rule do you swear by that others ignore?", "da": "Hvilken rejse-regel sv\u00e6rger du til, som andre ignorerer?", "de": "An welche Reiseregel h\u00e4ltst du dich, die andere ignorieren?", "es": "\u00bfQu\u00e9 regla de viaje sigues que los dem\u00e1s ignoran?", "pt": "Que regra de viagem segues que os outros ignoram?", "ro": "Ce regul\u0103 de c\u0103l\u0103torie respec\u021bi tu, dar al\u021bii o ignor\u0103?", "fr": "Quelle r\u00e8gle de voyage suis-tu que les autres ignorent ?", "it": "Quale regola di viaggio segui alla lettera anche se gli altri la ignorano?", "fi": "Mink\u00e4 matkustuss\u00e4\u00e4nn\u00f6n noudattamista vannot, vaikka muut eiv\u00e4t?", "nl": "Op welke reisregel zweer jij, terwijl anderen die negeren?", "no": "Hvilken reiselov sverger du til som andre bare ignorerer?", "sv": "Vilken reseregel sv\u00e4r du vid som andra struntar i?", "pl": "Jakiej zasady podr\u00f3\u017cowania bezwzgl\u0119dnie si\u0119 trzymasz, cho\u0107 inni j\u0105 ignoruj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What travel rule do you swear by that others ignore?';
UPDATE questions
SET translations = '{"en": "If this drive had chapter titles, what\u2019s the title of this chapter?", "da": "Hvis denne k\u00f8retur havde kapiteltitler, hvad ville dette kapitel hedde?", "de": "Wenn diese Fahrt Kapitel h\u00e4tte, wie w\u00fcrde dieses hei\u00dfen?", "es": "Si este viaje tuviera t\u00edtulos de cap\u00edtulos, \u00bfc\u00f3mo se llamar\u00eda este?", "pt": "Se esta viagem tivesse t\u00edtulos de cap\u00edtulos, como se chamaria este?", "ro": "Dac\u0103 aceast\u0103 c\u0103l\u0103torie ar avea titluri de capitole, cum s-ar numi acesta?", "fr": "Si ce trajet avait des titres de chapitres, comment s\u2019intitulerait celui-ci ?", "it": "Se questo viaggio in auto avesse titoli di capitoli, quale sarebbe il titolo di questo capitolo?", "fi": "Jos t\u00e4ll\u00e4 ajomatkalla olisi luvun nimi, mik\u00e4 olisi t\u00e4m\u00e4n luvun otsikko?", "nl": "Als deze rit hoofdstuktitels had, hoe zou dit hoofdstuk heten?", "no": "Hvis denne bilturen hadde kapitteltitler, hva ville tittelen p\u00e5 dette kapittelet v\u00e6rt?", "sv": "Om den h\u00e4r bilresan hade kapitelrubriker, vad skulle rubriken p\u00e5 det h\u00e4r kapitlet vara?", "pl": "Gdyby ta podr\u00f3\u017c mia\u0142a tytu\u0142y rozdzia\u0142\u00f3w, jak brzmia\u0142by tytu\u0142 tego rozdzia\u0142u?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If this drive had chapter titles, what’s the title of this chapter?';
UPDATE questions
SET translations = '{"en": "If other drivers gave honest performance reviews, what feedback would we get?", "da": "Hvis andre bilister gav \u00e6rlige pr\u00e6stationsanmeldelser, hvilken feedback ville vi f\u00e5?", "de": "Wenn andere Fahrer ehrliche Leistungsbewertungen geben w\u00fcrden, welches Feedback w\u00fcrden wir bekommen?", "es": "Si otros conductores dieran evaluaciones honestas, \u00bfqu\u00e9 comentarios recibir\u00edamos?", "pt": "Se outros condutores dessem avalia\u00e7\u00f5es honestas, que feedback receber\u00edamos?", "ro": "Dac\u0103 al\u021bi \u0219oferi ar oferi recenzii sincere, ce feedback am primi?", "fr": "Si les autres conducteurs donnaient des \u00e9valuations honn\u00eates, quel retour aurions-nous ?", "it": "Se gli altri automobilisti potessero lasciarci recensioni sincere sulle nostre \u201cprestazioni\u201d, che feedback riceveremmo?", "fi": "Jos muut kuskit antaisivat meille rehellisi\u00e4 palautteita ajamisesta, millaisen arvion saisimme?", "nl": "Als andere bestuurders ons eerlijke prestatie-reviews zouden geven, welke feedback zouden we krijgen?", "no": "Hvis andre sj\u00e5f\u00f8rer ga oss \u00e6rlige tilbakemeldinger, hva slags vurdering hadde vi f\u00e5tt?", "sv": "Om andra bilister gav \u00e4rliga omd\u00f6men om oss, vilken feedback skulle vi f\u00e5?", "pl": "Gdyby inni kierowcy wystawiali nam szczere oceny, jak\u0105 opini\u0119 by\u015bmy dostali?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If other drivers gave honest performance reviews, what feedback would we get?';
UPDATE questions
SET translations = '{"en": "If we could bring one comfort from home on every trip, what would it be?", "da": "Hvis vi kunne tage \u00e9n ting med hjemmefra p\u00e5 hver tur, hvad ville det v\u00e6re?", "de": "Wenn wir auf jeder Reise einen Komfort von zu Hause mitnehmen k\u00f6nnten, was w\u00e4re das?", "es": "Si pudi\u00e9ramos llevar una comodidad de casa en cada viaje, \u00bfqu\u00e9 ser\u00eda?", "pt": "Se pud\u00e9ssemos levar um conforto de casa em cada viagem, qual seria?", "ro": "Dac\u0103 am putea lua un lucru confortabil de acas\u0103 \u00een fiecare c\u0103l\u0103torie, care ar fi?", "fr": "Si on pouvait emporter un confort de la maison \u00e0 chaque voyage, lequel serait-ce ?", "it": "Se potessimo portare da casa un solo \u201ccomfort\u201d in ogni viaggio, quale sarebbe?", "fi": "Jos voisimme ottaa jokaiselle matkalle yhden kotijutun mukaan, mik\u00e4 se olisi?", "nl": "Als we op elke reis \u00e9\u00e9n troostding van thuis konden meenemen, wat zou het zijn?", "no": "Hvis vi kunne ta med \u00e9n komfort-ting hjemmefra p\u00e5 hver tur, hva skulle det v\u00e6rt?", "sv": "Om vi kunde ta med en enda trygg grej hemifr\u00e5n p\u00e5 varje resa, vad skulle det vara?", "pl": "Gdyby\u015bmy mogli na ka\u017cd\u0105 podr\u00f3\u017c zabiera\u0107 jedn\u0105 rzecz daj\u0105c\u0105 domowy komfort, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we could bring one comfort from home on every trip, what would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s one destination that\u2019s still calling your name?", "da": "Hvilken destination kalder stadig p\u00e5 dit navn?", "de": "Welches Reiseziel ruft immer noch deinen Namen?", "es": "\u00bfQu\u00e9 destino a\u00fan te llama?", "pt": "Que destino ainda chama por ti?", "ro": "Ce destina\u021bie \u00eenc\u0103 \u00ee\u021bi strig\u0103 numele?", "fr": "Quelle destination t\u2019appelle encore ?", "it": "Qual \u00e8 una destinazione che continua ancora a chiamarti?", "fi": "Mik\u00e4 on sellainen kohde, joka kutsuu sinua yh\u00e4 uudestaan?", "nl": "Wat is \u00e9\u00e9n bestemming die jouw naam nog steeds roept?", "no": "Hva er ett reisem\u00e5l som fortsatt roper navnet ditt?", "sv": "Vilket resm\u00e5l k\u00e4nns fortfarande som att det ropar p\u00e5 dig?", "pl": "Jakie jedno miejsce na \u015bwiecie wci\u0105\u017c \u201ewo\u0142a ci\u0119\u201d po imieniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s one destination that’s still calling your name?';
UPDATE questions
SET translations = '{"en": "You\u2019re arrested for a ridiculous crime you totally committed. What would it be?", "da": "Du bliver arresteret for en latterlig forbrydelse, du helt sikkert har beg\u00e5et. Hvad er det?", "de": "Du wirst f\u00fcr ein l\u00e4cherliches Verbrechen verhaftet, das du definitiv begangen hast. Was w\u00e4re das?", "es": "Te arrestan por un crimen rid\u00edculo que definitivamente cometiste. \u00bfCu\u00e1l ser\u00eda?", "pt": "\u00c9s preso por um crime rid\u00edculo que claramente cometeste. Qual seria?", "ro": "E\u0219ti arestat pentru o crim\u0103 ridicol\u0103 pe care sigur ai comis-o. Care ar fi?", "fr": "Tu es arr\u00eat\u00e9 pour un crime ridicule que tu as clairement commis. Lequel est-ce ?", "it": "Ti arrestano per un crimine assurdo che hai davvero commesso. Quale sarebbe?", "fi": "Sinut pid\u00e4tet\u00e4\u00e4n naurettavasta rikoksesta, jonka ihan oikeasti teit. Mik\u00e4 rikos se olisi?", "nl": "Je wordt gearresteerd voor een belachelijke misdaad die je \u00e9cht hebt gepleegd. Wat is het?", "no": "Du blir arrestert for en tullete forbrytelse du faktisk har beg\u00e5tt. Hva er den?", "sv": "Du blir gripen f\u00f6r ett l\u00f6jligt brott du helt klart har beg\u00e5tt. Vad \u00e4r det?", "pl": "Zostajesz aresztowany/a za absurdalne przest\u0119pstwo, kt\u00f3rego naprawd\u0119 si\u0119 dopu\u015bci\u0142e\u015b/dopu\u015bci\u0142a\u015b. Co to takiego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'You’re arrested for a ridiculous crime you totally committed. What would it be?';
UPDATE questions
SET translations = '{"en": "Create a 10-second soap-opera scene set in\u2026 a gas station. Go.", "da": "Lav en 10-sekunders s\u00e6beopera-scene sat i... en tankstation. G\u00e5!", "de": "Erstelle eine 10-sek\u00fcndige Seifenopernszene, die in... einer Tankstelle spielt. Los!", "es": "Crea una escena de telenovela de 10 segundos ambientada en... una gasolinera. \u00a1Adelante!", "pt": "Cria uma cena de novela de 10 segundos passada num... posto de gasolina. Vai!", "ro": "Creeaz\u0103 o scen\u0103 de telenovel\u0103 de 10 secunde plasat\u0103 \u00eentr-o benzin\u0103rie. Start!", "fr": "Cr\u00e9e une sc\u00e8ne de feuilleton de 10 secondes se d\u00e9roulant dans... une station-service. Action !", "it": "Crea una scena da soap opera di 10 secondi ambientata in\u2026 una stazione di servizio. Vai.", "fi": "Keksi 10 sekunnin saippuasarjakohtaus, joka sijoittuu huoltoasemalle. Mene.", "nl": "Bedenk een soap-opera sc\u00e8ne van 10 seconden, spelend op\u2026 een benzinestation. Go.", "no": "Lag en 10 sekunders s\u00e5peserie-scene som foreg\u00e5r p\u00e5\u2026 en bensinstasjon. Kj\u00f8r.", "sv": "Skapa en 10 sekunder l\u00e5ng s\u00e5poperascen som utspelar sig p\u00e5\u2026 en bensinmack. K\u00f6r.", "pl": "Wymy\u015bl 10-sekundow\u0105 scen\u0119 telenoweli rozgrywaj\u0105c\u0105 si\u0119 na\u2026 stacji benzynowej. Start."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Create a 10-second soap-opera scene set in… a gas station. Go.';
UPDATE questions
SET translations = '{"en": "The car just hosted a talent show. Which seat wins and why?", "da": "Bilen har lige afholdt et talentshow. Hvilket s\u00e6de vandt og hvorfor?", "de": "Das Auto hat gerade eine Talentshow veranstaltet. Welcher Sitz gewinnt und warum?", "es": "El coche acaba de organizar un concurso de talentos. \u00bfQu\u00e9 asiento gana y por qu\u00e9?", "pt": "O carro acabou de organizar um show de talentos. Qual assento ganha e porqu\u00ea?", "ro": "Ma\u0219ina tocmai a g\u0103zduit un show de talente. Care loc c\u00e2\u0219tig\u0103 \u0219i de ce?", "fr": "La voiture vient d\u2019organiser un concours de talents. Quel si\u00e8ge gagne et pourquoi ?", "it": "L\u2019auto ha appena ospitato un talent show. Quale sedile vince e perch\u00e9?", "fi": "Auto j\u00e4rjesti juuri kykykilpailun. Mik\u00e4 penkki voittaa ja miksi?", "nl": "De auto heeft net een talentenshow gehouden. Welke stoel wint en waarom?", "no": "Bilen har nettopp hatt talentkonkurranse. Hvilket sete vinner, og hvorfor?", "sv": "Bilen har precis haft talangjakt. Vilken plats vinner och varf\u00f6r?", "pl": "Auto w\u0142a\u015bnie zorganizowa\u0142o pokaz talent\u00f3w. Kt\u00f3re siedzenie wygrywa i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'The car just hosted a talent show. Which seat wins and why?';
UPDATE questions
SET translations = '{"en": "If we ran a pop-up restaurant, what would our signature dish be?", "da": "Hvis vi drev en pop-up-restaurant, hvad ville vores signaturret v\u00e6re?", "de": "Wenn wir ein Pop-up-Restaurant betreiben w\u00fcrden, was w\u00e4re unser Signature-Gericht?", "es": "Si dirigi\u00e9ramos un restaurante temporal, \u00bfcu\u00e1l ser\u00eda nuestro plato insignia?", "pt": "Se tiv\u00e9ssemos um restaurante pop-up, qual seria o nosso prato de assinatura?", "ro": "Dac\u0103 am avea un restaurant temporar, care ar fi felul nostru de m\u00e2ncare semn\u0103tur\u0103?", "fr": "Si on tenait un restaurant \u00e9ph\u00e9m\u00e8re, quel serait notre plat signature ?", "it": "Se gestissimo un ristorante pop-up, quale sarebbe il nostro piatto simbolo?", "fi": "Jos pit\u00e4isimme pop up -ravintolaa, mik\u00e4 olisi meid\u00e4n nimikkoannos?", "nl": "Als we een pop-uprestaurant zouden runnen, wat zou ons signature gerecht zijn?", "no": "Hvis vi drev en pop up-restaurant, hva ville v\u00e5r signaturrett v\u00e6rt?", "sv": "Om vi drev en pop up-restaurang, vad skulle vara v\u00e5r signaturr\u00e4tt?", "pl": "Gdyby\u015bmy prowadzili restauracj\u0119 pop up, jakie danie by\u0142oby naszym popisowym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we ran a pop-up restaurant, what would our signature dish be?';
UPDATE questions
SET translations = '{"en": "What do you think our \u201ctravel personality\u201d is \u2014 adventurous, chill, foodie, etc.?", "da": "Hvad tror du, vores \u201crejsepersonlighed\u201d er \u2013 eventyrlystne, afslappede, madglade osv.?", "de": "Wie w\u00fcrdest du unsere \u201eReisepers\u00f6nlichkeit\u201c beschreiben \u2013 abenteuerlustig, entspannt, Feinschmecker usw.?", "es": "\u00bfC\u00f3mo describir\u00edas nuestra \u201cpersonalidad viajera\u201d: aventurera, relajada, foodie, etc.?", "pt": "Como achas que \u00e9 a nossa \u201cpersonalidade de viagem\u201d \u2014 aventureira, calma, gastron\u00f3mica, etc.?", "ro": "Cum crezi c\u0103 este \u201epersonalitatea noastr\u0103 de c\u0103l\u0103torie\u201d \u2014 aventuroas\u0103, relaxat\u0103, gurmand\u0103 etc.?", "fr": "Comment d\u00e9crirais-tu notre \u201cpersonnalit\u00e9 de voyage\u201d \u2014 aventuri\u00e8re, d\u00e9tendue, gourmande, etc. ?", "it": "Secondo te qual \u00e8 la nostra \u201cpersonalit\u00e0 di viaggio\u201d \u2013 avventurosa, rilassata, foodie, ecc.?", "fi": "Mik\u00e4 sinun mielest\u00e4si on meid\u00e4n \u201cmatkapersoonallisuus\u201d \u2013 seikkailija, rento, foodie jne.?", "nl": "Wat denk jij dat onze \u201creispersoonlijkheid\u201d is \u2013 avontuurlijk, chill, foodie, enz.?", "no": "Hva tror du er v\u00e5r \u201creise-personlighet\u201d \u2013 eventyrlysten, chill, foodie osv.?", "sv": "Vad tror du \u00e4r v\u00e5r \u201cresepersonlighet\u201d \u2013 \u00e4ventyrlig, chill, foodie osv.?", "pl": "Jak my\u015blisz, jaka jest nasza \u201epodr\u00f3\u017cnicza osobowo\u015b\u0107\u201d \u2013 przygodowa, na luzie, foodie itd.?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What do you think our “travel personality” is — adventurous, chill, foodie, etc.?';