UPDATE questions
SET translations = '{"en": "What\u2019s my go-to \u201cI\u2019m fine\u201d behavior that proves I am not, in fact, fine?", "da": "Hvad er min klassiske \u201cjeg har det fint\u201d-adf\u00e6rd, der viser, at jeg faktisk ikke har det fint?", "de": "Was ist mein typisches \u201eMir geht\u2019s gut\u201c-Verhalten, das beweist, dass es mir eigentlich nicht gut geht?", "es": "\u00bfCu\u00e1l es mi comportamiento de \u201cestoy bien\u201d que demuestra que en realidad no lo estoy?", "pt": "Qual \u00e9 o meu comportamento de \u201cestou bem\u201d que prova que, na verdade, n\u00e3o estou bem?", "ro": "Care este comportamentul meu \u201esunt bine\u201d care arat\u0103 c\u0103, de fapt, nu sunt bine?", "fr": "Quel est mon comportement \u201c\u00e7a va\u201d qui prouve qu\u2019en r\u00e9alit\u00e9, \u00e7a ne va pas ?", "it": "Qual \u00e8 il mio comportamento abituale di \"sto bene\" che dimostra che in realt\u00e0 non sto affatto bene?", "fi": "Mik\u00e4 on se \"olen kunnossa\" -k\u00e4yt\u00f6kseni, joka todistaa, etten oikeasti ole kunnossa?", "nl": "Wat is mijn standaard \"het gaat goed met me\" gedrag dat bewijst dat ik in werkelijkheid niet goed ben?", "no": "Hva er min faste \"jeg har det bra\"-oppf\u00f8rsel som beviser at jeg faktisk ikke har det bra?", "sv": "Vad \u00e4r mitt standardbeteende f\u00f6r \"jag m\u00e5r bra\" som bevisar att jag faktiskt inte m\u00e5r bra?", "pl": "Jakie jest moje ulubione zachowanie \u201ejestem w porz\u0105dku\u201d, kt\u00f3re dowodzi, \u017ce tak naprawd\u0119 nie jestem w porz\u0105dku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s my go-to “I’m fine” behavior that proves I am not, in fact, fine?';
UPDATE questions
SET translations = '{"en": "What chore am I suspiciously good at avoiding?", "da": "Hvilken husopgave er jeg mist\u00e6nkeligt god til at undg\u00e5?", "de": "Welche Hausarbeit kann ich verd\u00e4chtig gut vermeiden?", "es": "\u00bfQu\u00e9 tarea dom\u00e9stica soy sospechosamente bueno evitando?", "pt": "Que tarefa dom\u00e9stica eu sou suspeitosamente bom a evitar?", "ro": "Ce treab\u0103 casnic\u0103 reu\u0219esc suspect de bine s\u0103 evit?", "fr": "Quelle corv\u00e9e domestique suis-je \u00e9trangement dou\u00e9 pour \u00e9viter ?", "it": "Quale faccenda riesco sospettosamente a evitare?", "fi": "Mik\u00e4 kotity\u00f6 on sellainen, jota olen ep\u00e4ilytt\u00e4v\u00e4n hyv\u00e4 v\u00e4ltt\u00e4m\u00e4\u00e4n?", "nl": "Welke klus ben ik verdacht goed in het vermijden?", "no": "Hvilken husarbeid er jeg mistenkelig flink til \u00e5 unng\u00e5?", "sv": "Vilken syssla \u00e4r jag misst\u00e4nkt bra p\u00e5 att undvika?", "pl": "Jak\u0105 prac\u0119 domow\u0105 podejrzanie dobrze omijam?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What chore am I suspiciously good at avoiding?';
UPDATE questions
SET translations = '{"en": "If my brain had browser tabs open, what three tabs are always there?", "da": "Hvis min hjerne havde browserfaner \u00e5bne, hvilke tre faner ville altid v\u00e6re der?", "de": "Wenn mein Gehirn Browser-Tabs offen h\u00e4tte, welche drei w\u00e4ren immer da?", "es": "Si mi cerebro tuviera pesta\u00f1as abiertas, \u00bfcu\u00e1les tres siempre estar\u00edan ah\u00ed?", "pt": "Se o meu c\u00e9rebro tivesse abas abertas, quais tr\u00eas estariam sempre l\u00e1?", "ro": "Dac\u0103 creierul meu ar avea file deschise, care trei ar fi mereu acolo?", "fr": "Si mon cerveau avait des onglets ouverts, lesquels trois seraient toujours l\u00e0 ?", "it": "Se il mio cervello avesse schede aperte nel browser, quali tre schede ci sarebbero sempre?", "fi": "Jos aivoni olisivat kuin selainikkunat, mitk\u00e4 kolme v\u00e4lilehte\u00e4 olisivat aina auki?", "nl": "Als mijn brein browser-tabbladen open had, welke drie tabbladen zouden er dan altijd zijn?", "no": "Hvis hjernen min hadde \u00e5pne nettleserfaner, hvilke tre faner ville alltid v\u00e6rt der?", "sv": "Om min hj\u00e4rna hade webbl\u00e4sartabbar \u00f6ppna, vilka tre flikar skulle alltid vara d\u00e4r?", "pl": "Gdyby m\u00f3j m\u00f3zg mia\u0142 otwarte zak\u0142adki w przegl\u0105darce, to jakie trzy zak\u0142adki by\u0142yby zawsze otwarte?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If my brain had browser tabs open, what three tabs are always there?';
UPDATE questions
SET translations = '{"en": "Which emoji sums me up a little too well?", "da": "Hvilken emoji opsummerer mig lidt for godt?", "de": "Welcher Emoji fasst mich ein bisschen zu gut zusammen?", "es": "\u00bfQu\u00e9 emoji me describe un poco demasiado bien?", "pt": "Que emoji me resume bem demais?", "ro": "Ce emoji m\u0103 descrie poate un pic prea bine?", "fr": "Quel emoji me r\u00e9sume un peu trop bien ?", "it": "Quale emoji mi rappresenta un po'' troppo bene?", "fi": "Mik\u00e4 emoji kuvaa minua ehk\u00e4 v\u00e4h\u00e4n liian hyvin?", "nl": "Welke emoji beschrijft mij misschien iets te goed?", "no": "Hvilken emoji oppsummerer meg litt for godt?", "sv": "Vilken emoji sammanfattar mig lite f\u00f6r bra?", "pl": "Kt\u00f3ry emoji najlepiej mnie opisuje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which emoji sums me up a little too well?';
UPDATE questions
SET translations = '{"en": "Which song would instantly expose me at karaoke?", "da": "Hvilken sang ville straks afsl\u00f8re mig ved karaoke?", "de": "Welches Lied w\u00fcrde mich beim Karaoke sofort entlarven?", "es": "\u00bfQu\u00e9 canci\u00f3n me delatar\u00eda instant\u00e1neamente en el karaoke?", "pt": "Que m\u00fasica me denunciaria imediatamente no karaoke?", "ro": "Ce melodie m-ar da de gol instant la karaoke?", "fr": "Quelle chanson m\u2019exposerait imm\u00e9diatement au karaok\u00e9 ?", "it": "Quale canzone mi esporrebbe immediatamente al karaoke?", "fi": "Mik\u00e4 laulu paljastaisi minut heti karaokessa?", "nl": "Welke song zou me meteen blootstellen tijdens karaoke?", "no": "Hvilken sang ville umiddelbart avsl\u00f8re meg p\u00e5 karaoke?", "sv": "Vilken l\u00e5t skulle omedelbart avsl\u00f6ja mig p\u00e5 karaoke?", "pl": "Kt\u00f3ra piosenka natychmiast by mnie zdemaskowa\u0142a na karaoke?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which song would instantly expose me at karaoke?';
UPDATE questions
SET translations = '{"en": "Which Disney movie would I fit best in and why?", "da": "Hvilken Disney-film ville jeg passe bedst ind i, og hvorfor?", "de": "In welchem Disney-Film w\u00fcrde ich am besten hineinpassen und warum?", "es": "\u00bfEn qu\u00e9 pel\u00edcula de Disney encajar\u00eda mejor y por qu\u00e9?", "pt": "Em que filme da Disney eu me encaixaria melhor e porqu\u00ea?", "ro": "\u00cen ce film Disney m-a\u0219 potrivi cel mai bine \u0219i de ce?", "fr": "Dans quel film Disney je m\u2019int\u00e9grerais le mieux et pourquoi ?", "it": "In quale film Disney pensi che mi adatterei meglio e perch\u00e9?", "fi": "Mihin Disney-elokuvaan sopisin parhaiten ja miksi?", "nl": "In welke Disney-film zou ik het beste passen en waarom?", "no": "Hvilken Disney-film ville jeg passe best inn i, og hvorfor?", "sv": "Vilken Disney-film skulle jag passa b\u00e4st in i och varf\u00f6r?", "pl": "W kt\u00f3rym filmie Disneya najlepiej bym pasowa\u0142 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which Disney movie would I fit best in and why?';
UPDATE questions
SET translations = '{"en": "If pets could text, what would yours send you at 2 a.m.?", "da": "Hvis k\u00e6ledyr kunne sende sms\u2019er, hvad ville dit sende dig kl. 2 om natten?", "de": "Wenn Haustiere SMS schreiben k\u00f6nnten, was w\u00fcrde deins dir um 2 Uhr morgens schicken?", "es": "Si las mascotas pudieran enviar mensajes, \u00bfqu\u00e9 te enviar\u00eda la tuya a las 2 a.m.?", "pt": "Se os animais de estima\u00e7\u00e3o pudessem enviar mensagens, o que o teu te mandaria \u00e0s 2h da manh\u00e3?", "ro": "Dac\u0103 animalele ar putea trimite mesaje, ce \u021bi-ar trimite al t\u0103u la ora 2 diminea\u021ba?", "fr": "Si les animaux pouvaient envoyer des textos, que t\u2019enverrait le tien \u00e0 2h du matin ?", "it": "Se gli animali domestici potessero inviare messaggi, cosa ti manderebbe il tuo alle due di notte?", "fi": "Jos lemmikkisi voisi l\u00e4hett\u00e4\u00e4 viestej\u00e4, mit\u00e4 se l\u00e4hett\u00e4isi sinulle kello 2 y\u00f6ll\u00e4?", "nl": "Als huisdieren konden sms''en, wat zou de jouwe je om 2 uur ''s nachts sturen?", "no": "Hvis kj\u00e6ledyr kunne sende tekstmeldinger, hva ville ditt sendt deg kl. 02.00?", "sv": "Om husdjur kunde skicka sms, vad skulle ditt skicka till dig klockan 2 p\u00e5 natten?", "pl": "Gdyby zwierz\u0119ta mog\u0142y wysy\u0142a\u0107 wiadomo\u015bci, co twoje by ci napisa\u0142o o 2 w nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If pets could text, what would yours send you at 2 a.m.?';
UPDATE questions
SET translations = '{"en": "What phrase do I say so often it should be on a T-shirt?", "da": "Hvilken s\u00e6tning siger jeg s\u00e5 tit, at den burde st\u00e5 p\u00e5 en T-shirt?", "de": "Welchen Satz sage ich so oft, dass er auf ein T-Shirt gedruckt werden sollte?", "es": "\u00bfQu\u00e9 frase digo tan a menudo que deber\u00eda estar en una camiseta?", "pt": "Que frase eu digo tantas vezes que devia estar numa t-shirt?", "ro": "Ce expresie o spun at\u00e2t de des \u00eenc\u00e2t ar trebui scris\u0103 pe un tricou?", "fr": "Quelle phrase je dis si souvent qu\u2019elle devrait \u00eatre sur un t-shirt ?", "it": "Quale frase dico cos\u00ec spesso che dovrebbe essere su una maglietta?", "fi": "Mik\u00e4 lause on sellainen, jota sanon niin usein, ett\u00e4 sen pit\u00e4isi olla t-paidassa?", "nl": "Welke zin zeg ik zo vaak dat hij op een T-shirt zou moeten staan?", "no": "Hvilken setning sier jeg s\u00e5 ofte at den burde st\u00e5 p\u00e5 en T-skjorte?", "sv": "Vilken fras s\u00e4ger jag s\u00e5 ofta att den borde st\u00e5 p\u00e5 en T-shirt?", "pl": "Jak\u0105 fraz\u0119 m\u00f3wi\u0119 tak cz\u0119sto, \u017ce powinna znale\u017a\u0107 si\u0119 na koszulce?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What phrase do I say so often it should be on a T-shirt?';

-- Category: Spicy Talks (75 questions)
UPDATE questions
SET translations = '{"en": "What\u2019s the best sex we\u2019ve ever had \u2014 and why does that one stand out?", "da": "Hvad er den bedste sex, vi nogensinde har haft \u2013 og hvorfor skiller netop den sig ud? ", "de": "Was war der beste Sex, den wir je hatten \u2013 und warum war er so besonders?", "es": "\u00bfCu\u00e1l ha sido el mejor sexo que hemos tenido y por qu\u00e9 fue tan especial?", "pt": "Qual foi o melhor sexo que j\u00e1 tivemos e por que foi t\u00e3o especial?", "ro": "Care a fost cel mai bun sex pe care l-am avut vreodat\u0103 \u0219i de ce a fost at\u00e2t de special?", "fr": "Quel a \u00e9t\u00e9 le meilleur sexe que nous ayons eu, et pourquoi \u00e9tait-il si sp\u00e9cial ?", "it": "Qual \u00e8 stato il miglior sesso che abbiamo mai avuto \u2014 e perch\u00e9 quello si distingue?", "fi": "Mik\u00e4 on paras seksi, jota olemme koskaan harrastaneet \u2014 ja miksi se erottuu muista?", "nl": "Wat is de beste seks die we ooit hebben gehad \u2014 en waarom springt die eruit?", "no": "Hva er det beste sex vi noen gang har hatt \u2014 og hvorfor skiller det seg ut?", "sv": "Vad \u00e4r den b\u00e4sta sex vi n\u00e5gonsin har haft \u2014 och varf\u00f6r st\u00e5r just den ut?", "pl": "Jaki by\u0142 najlepszy seks, jaki kiedykolwiek mieli\u015bmy \u2014 i dlaczego ten szczeg\u00f3lnie si\u0119 wyr\u00f3\u017cnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s the best sex we’ve ever had — and why does that one stand out?';
UPDATE questions
SET translations = '{"en": "Describe your favorite position and why you love it with me.", "da": "Beskriv din yndlingsstilling, og hvorfor du elsker den med mig. ", "de": "Beschreibe deine Lieblingsstellung und warum du sie mit mir so liebst.", "es": "Describe tu posici\u00f3n favorita y por qu\u00e9 la amas conmigo.", "pt": "Descreve a tua posi\u00e7\u00e3o favorita e por que a adoras comigo.", "ro": "Descrie pozi\u021bia ta preferat\u0103 \u0219i de ce o iube\u0219ti cu mine.", "fr": "D\u00e9cris ta position pr\u00e9f\u00e9r\u00e9e et pourquoi tu l\u2019aimes avec moi.", "it": "Descrivi la tua posizione preferita e perch\u00e9 la ami con me.", "fi": "Kuvaile lempiasentoasi ja miksi rakastat sit\u00e4 kanssani.", "nl": "Beschrijf je favoriete positie en waarom je die zo leuk vindt met mij.", "no": "Beskriv din favorittstilling og hvorfor du elsker den med meg.", "sv": "Beskriv din favoritposition och varf\u00f6r du \u00e4lskar den med mig.", "pl": "Opisz swoj\u0105 ulubion\u0105 pozycj\u0119 i powiedz, dlaczego j\u0105 z nami uwielbiasz."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Describe your favorite position and why you love it with me.';