UPDATE questions
SET translations = '{"en": "What do you wish we did less of\u2014and more of\u2014in a normal week?", "da": "Hvad ville du \u00f8nske, vi gjorde mindre af \u2014 og mere af \u2014 i en normal uge?", "de": "Wovon w\u00fcnschst du dir, dass wir in einer normalen Woche weniger \u2013 und mehr \u2013 machen?", "es": "\u00bfQu\u00e9 te gustar\u00eda que hici\u00e9ramos menos \u2014 y m\u00e1s \u2014 en una semana normal?", "pt": "O que gostarias que fiz\u00e9ssemos menos \u2014 e mais \u2014 numa semana normal?", "ro": "Ce \u021bi-ai dori s\u0103 facem mai pu\u021bin \u2014 \u0219i mai mult \u2014 \u00eentr-o s\u0103pt\u0103m\u00e2n\u0103 obi\u0219nuit\u0103?", "fr": "Qu\u2019aimerais-tu que nous fassions moins \u2014 et plus \u2014 au cours d\u2019une semaine normale ?", "it": "Cosa desideri che facessimo di meno e di pi\u00f9 in una settimana normale?", "fi": "Mit\u00e4 toivoisit, ett\u00e4 tekisimme v\u00e4hemm\u00e4n ja enemm\u00e4n normaalina viikkona?", "nl": "Waarvan zou je willen dat we het minder deden - en waarvan meer - in een normale week?", "no": "Hva \u00f8nsker du at vi gjorde mindre av \u2013 og mer av \u2013 i en vanlig uke?", "sv": "Vad \u00f6nskar du att vi gjorde mindre av \u2013 och mer av \u2013 under en vanlig vecka?", "pl": "Czego chcia\u0142by\u015b, \u017ceby\u015bmy robili mniej, a czego wi\u0119cej w normalnym tygodniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What do you wish we did less of—and more of—in a normal week?';
UPDATE questions
SET translations = '{"en": "What\u2019s a decision of ours you\u2019re proudest of?", "da": "Hvilken beslutning af vores er du mest stolt af?", "de": "Auf welche unserer Entscheidungen bist du am stolzesten?", "es": "\u00bfDe qu\u00e9 decisi\u00f3n nuestra est\u00e1s m\u00e1s orgulloso/a?", "pt": "De qual das nossas decis\u00f5es tens mais orgulho?", "ro": "De care dintre deciziile noastre e\u0219ti cel mai m\u00e2ndru/m\u00e2ndr\u0103?", "fr": "De quelle de nos d\u00e9cisions es-tu le plus fier/la plus fi\u00e8re ?", "it": "Qual \u00e8 una decisione di cui sei pi\u00f9 orgoglioso?", "fi": "Mik\u00e4 p\u00e4\u00e4t\u00f6s meilt\u00e4 on, josta olet ylpein?", "nl": "Wat is een beslissing van ons waar je het meest trots op bent?", "no": "Hva er en beslutning vi har tatt som du er mest stolt av?", "sv": "Vilket beslut \u00e4r du mest stolt \u00f6ver att vi har fattat?", "pl": "Jak\u0105 decyzj\u0119, kt\u00f3r\u0105 podj\u0119li\u015bmy, uwa\u017casz za najbardziej udan\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a decision of ours you’re proudest of?';
UPDATE questions
SET translations = '{"en": "What\u2019s something new you want to learn together?", "da": "Hvad er noget nyt, du gerne vil l\u00e6re sammen med mig?", "de": "Was ist etwas Neues, das du gerne gemeinsam lernen m\u00f6chtest?", "es": "\u00bfQu\u00e9 cosa nueva te gustar\u00eda que aprendi\u00e9ramos juntos?", "pt": "O que de novo gostarias que aprend\u00eassemos juntos?", "ro": "Ce lucru nou ai vrea s\u0103 \u00eenv\u0103\u021b\u0103m \u00eempreun\u0103?", "fr": "Quelle nouvelle chose voudrais-tu qu\u2019on apprenne ensemble ?", "it": "Qualcosa di nuovo che vuoi imparare insieme?", "fi": "Mik\u00e4 on jotain uutta, mit\u00e4 haluaisit oppia yhdess\u00e4?", "nl": "Wat is iets nieuws dat je samen wilt leren?", "no": "Hva er noe nytt du \u00f8nsker \u00e5 l\u00e6re sammen?", "sv": "Vad \u00e4r n\u00e5got nytt ni vill l\u00e4ra er tillsammans?", "pl": "Co\u015b nowego, czego chcesz si\u0119 nauczy\u0107 razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s something new you want to learn together?';
UPDATE questions
SET translations = '{"en": "Tell me about some of your highlights and lowlights from this past year.", "da": "Fort\u00e6l mig om nogle af dine h\u00f8jdepunkter og lavpunkter fra det sidste \u00e5r.", "de": "Erz\u00e4hl mir von einigen deiner Highlights und Tiefpunkte aus dem letzten Jahr.", "es": "Cu\u00e9ntame algunos de tus momentos altos y bajos de este \u00faltimo a\u00f1o.", "pt": "Fala-me de alguns dos teus altos e baixos do \u00faltimo ano.", "ro": "Poveste\u0219te-mi c\u00e2teva dintre momentele tale bune \u0219i rele din ultimul an.", "fr": "Parle-moi de quelques-uns de tes hauts et bas de l\u2019ann\u00e9e pass\u00e9e.", "it": "Raccontami alcuni dei tuoi momenti salienti e dei tuoi momenti difficili di quest''anno passato.", "fi": "Kerro minulle joitakin kohokohtia ja alhaisia hetki\u00e4 kuluneelta vuodelta.", "nl": "Vertel me over enkele van je hoogte- en dieptepunten van het afgelopen jaar.", "no": "Fortell meg om noen av h\u00f8ydepunktene og lavpunktene fra det siste \u00e5ret ditt.", "sv": "Ber\u00e4tta om n\u00e5gra av dina h\u00f6jdpunkter och l\u00e5gvattenm\u00e4rken fr\u00e5n det g\u00e5ngna \u00e5ret.", "pl": "Opowiedz mi o swoich najwa\u017cniejszych i najtrudniejszych momentach z minionego roku."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Tell me about some of your highlights and lowlights from this past year.';
UPDATE questions
SET translations = '{"en": "What\u2019s a memory of us, you believe will still make you smile when you\u2019re 90?", "da": "Hvilket minde om os tror du stadig vil f\u00e5 dig til at smile, n\u00e5r du er 90?", "de": "Welche Erinnerung an uns wird dich deiner Meinung nach noch zum L\u00e4cheln bringen, wenn du 90 bist?", "es": "\u00bfQu\u00e9 recuerdo nuestro crees que todav\u00eda te har\u00e1 sonre\u00edr cuando tengas 90 a\u00f1os?", "pt": "Qual lembran\u00e7a nossa voc\u00ea acredita que ainda vai fazer voc\u00ea sorrir quando tiver 90 anos?", "ro": "Care este o amintire cu noi despre care crezi c\u0103 \u00eenc\u0103 te va face s\u0103 z\u00e2mbe\u0219ti c\u00e2nd vei avea 90 de ani?", "fr": "Quel souvenir de nous crois-tu te fera encore sourire quand tu auras 90 ans ?", "it": "Qual \u00e8 un ricordo di noi che pensi ti far\u00e0 ancora sorridere quando avrai 90 anni?", "fi": "Mik\u00e4 muisto meist\u00e4 saa sinut edelleen hymyilem\u00e4\u00e4n, kun olet 90-vuotias?", "nl": "Wat is een herinnering aan ons waarvan je denkt dat die je nog steeds zal laten glimlachen als je 90 bent?", "no": "Hva er et minne om oss som du tror fortsatt vil f\u00e5 deg til \u00e5 smile n\u00e5r du er 90?", "sv": "Vilket minne av oss tror du fortfarande kommer f\u00e5 dig att le n\u00e4r du \u00e4r 90?", "pl": "Jakie wspomnienie o nas, twoim zdaniem, nadal sprawi, \u017ce si\u0119 u\u015bmiechniesz, gdy b\u0119dziesz mia\u0142 90 lat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a memory of us, you believe will still make you smile when you’re 90?';
UPDATE questions
SET translations = '{"en": "Aside from my current job, what''s an alternative carrier you think I would be amazing at?", "da": "Bortset fra mit nuv\u00e6rende job, hvilket alternativt karrierevalg tror du, jeg ville v\u00e6re fantastisk til?", "de": "Abgesehen von meinem jetzigen Job: Welcher alternative Beruf w\u00e4re deiner Meinung nach wie f\u00fcr mich gemacht?", "es": "Aparte de mi trabajo actual, \u00bfen qu\u00e9 otra carrera crees que ser\u00eda incre\u00edble?", "pt": "Al\u00e9m do meu trabalho atual, que carreira alternativa achas que eu faria maravilhas?", "ro": "\u00cen afar\u0103 de jobul meu actual, la ce alt\u0103 carier\u0103 crezi c\u0103 a\u0219 fi grozav(\u0103)?", "fr": "En dehors de mon travail actuel, quel autre m\u00e9tier penses-tu que je ferais \u00e0 merveille ?", "it": "A parte il mio attuale lavoro, quale carriera alternativa pensi che sarei straordinario?", "fi": "Mik\u00e4 olisi vaihtoehtoinen ura, jossa uskot, ett\u00e4 olisin mahtava nykyisen ty\u00f6ni lis\u00e4ksi?", "nl": "Afgezien van mijn huidige baan, wat is een alternatieve carri\u00e8re waarvan jij denkt dat ik er geweldig in zou zijn?", "no": "Bortsett fra min n\u00e5v\u00e6rende jobb, hva er en alternativ karriere du tror jeg ville v\u00e6rt fantastisk i?", "sv": "F\u00f6rutom mitt nuvarande jobb, vilken alternativ karri\u00e4r tror du att jag skulle vara fantastisk p\u00e5?", "pl": "Poza moj\u0105 obecn\u0105 prac\u0105, w jakiej alternatywnej karierze my\u015blisz, \u017ce by\u0142bym niesamowity?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Aside from my current job, what''s an alternative carrier you think I would be amazing at?';
UPDATE questions
SET translations = '{"en": "What helps you open up when you\u2019re feeling closed or isolated?", "da": "Hvad hj\u00e6lper dig med at \u00e5bne op, n\u00e5r du f\u00f8ler dig lukket eller isoleret?", "de": "Was hilft dir, dich zu \u00f6ffnen, wenn du dich verschlossen oder isoliert f\u00fchlst?", "es": "\u00bfQu\u00e9 te ayuda a abrirte cuando te sientes cerrado/a o aislado/a?", "pt": "O que te ajuda a abrir-te quando te sentes fechado/a ou isolado/a?", "ro": "Ce te ajut\u0103 s\u0103 te deschizi c\u00e2nd te sim\u021bi \u00eenchis(\u0103) sau izolat(\u0103)?", "fr": "Qu\u2019est-ce qui t\u2019aide \u00e0 t\u2019ouvrir quand tu te sens ferm\u00e9(e) ou isol\u00e9(e) ?", "it": "Cosa ti aiuta ad aprirti quando ti senti chiuso o isolato?", "fi": "Mik\u00e4 auttaa sinua avautumaan, kun tunnet itsesi sulkeutuneeksi tai eristyneeksi?", "nl": "Wat helpt jou om je open te stellen als je je gesloten of ge\u00efsoleerd voelt?", "no": "Hva hjelper deg med \u00e5 \u00e5pne deg n\u00e5r du f\u00f8ler deg lukket eller isolert?", "sv": "Vad hj\u00e4lper dig att \u00f6ppna upp n\u00e4r du k\u00e4nner dig st\u00e4ngd eller isolerad?", "pl": "Co pomaga ci si\u0119 otworzy\u0107, gdy czujesz si\u0119 zamkni\u0119ty lub odizolowany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What helps you open up when you’re feeling closed or isolated?';
UPDATE questions
SET translations = '{"en": "How do you show love when words don\u2019t feel enough?", "da": "Hvordan viser du k\u00e6rlighed, n\u00e5r ord ikke f\u00f8les nok?", "de": "Wie zeigst du Liebe, wenn Worte sich nicht genug anf\u00fchlen?", "es": "\u00bfC\u00f3mo demuestras amor cuando las palabras no parecen suficientes?", "pt": "Como voc\u00ea demonstra amor quando as palavras n\u00e3o parecem suficientes?", "ro": "Cum ar\u0103\u021bi iubire atunci c\u00e2nd cuvintele nu par suficiente?", "fr": "Comment montres-tu ton amour quand les mots ne suffisent pas ?", "it": "Come mostri amore quando le parole non sembrano sufficienti?", "fi": "Miten osoitat rakkautta, kun sanat eiv\u00e4t tunnu riitt\u00e4vilt\u00e4?", "nl": "Hoe laat je liefde zien als woorden niet genoeg lijken?", "no": "Hvordan viser du kj\u00e6rlighet n\u00e5r ord ikke f\u00f8les tilstrekkelige?", "sv": "Hur visar du k\u00e4rlek n\u00e4r orden inte k\u00e4nns tillr\u00e4ckliga?", "pl": "Jak okazujesz mi\u0142o\u015b\u0107, gdy s\u0142owa wydaj\u0105 si\u0119 niewystarczaj\u0105ce?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How do you show love when words don’t feel enough?';
UPDATE questions
SET translations = '{"en": "When do you feel most emotionally connected to me?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest f\u00f8lelsesm\u00e6ssigt forbundet med mig?", "de": "Wann f\u00fchlst du dich mir emotional am n\u00e4chsten?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s conectado/a emocionalmente conmigo?", "pt": "Quando voc\u00ea se sente mais ligado(a) a mim emocionalmente?", "ro": "C\u00e2nd te sim\u021bi cel mai conectat(\u0103) emo\u021bional cu mine?", "fr": "Quand te sens-tu le plus connect\u00e9(e) \u00e9motionnellement \u00e0 moi ?", "it": "Quando ti senti pi\u00f9 emotivamente connesso a me?", "fi": "Milloin tunnet itsesi eniten emotionaalisesti yhteyteen kanssani?", "nl": "Wanneer voel je je het meest emotioneel verbonden met mij?", "no": "N\u00e5r f\u00f8ler du deg mest f\u00f8lelsesmessig knyttet til meg?", "sv": "N\u00e4r k\u00e4nner du dig mest k\u00e4nslom\u00e4ssigt kopplad till mig?", "pl": "Kiedy czujesz si\u0119 ze mn\u0105 najbardziej emocjonalnie zwi\u0105zany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When do you feel most emotionally connected to me?';
UPDATE questions
SET translations = '{"en": "What\u2019s a guilty pleasure you\u2019re shy to admit?", "da": "Hvad er en guilty pleasure, du er lidt genert over at indr\u00f8mme?", "de": "Was ist ein heimliches Laster, das dir peinlich ist zuzugeben?", "es": "\u00bfCu\u00e1l es un placer culposo que te da verg\u00fcenza admitir?", "pt": "Qual \u00e9 um prazer culposo do qual voc\u00ea tem vergonha de admitir?", "ro": "Care este o \u201epl\u0103cere vinovat\u0103\u201d pe care \u00ee\u021bi e jen\u0103 s\u0103 o recuno\u0219ti?", "fr": "Quel est un plaisir coupable que tu es un peu timide d\u2019avouer ?", "it": "Qual \u00e8 un piacere colpevole di cui sei timido ad ammettere?", "fi": "Mik\u00e4 on syyllinen nautintosi, josta olet ujo my\u00f6nt\u00e4m\u00e4\u00e4n?", "nl": "Wat is een schuldige plezier waar je verlegen over bent om toe te geven?", "no": "Hva er en skyldf\u00f8lelse glede du er sjenert for \u00e5 innr\u00f8mme?", "sv": "Vilken skamlig njutning \u00e4r du blyg f\u00f6r att erk\u00e4nna?", "pl": "Jakie jest twoje poczucie winy przyjemno\u015b\u0107, kt\u00f3r\u0105 wstydzisz si\u0119 przyzna\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a guilty pleasure you’re shy to admit?';