UPDATE questions
SET translations = '{"en": "Who from your past do you still think about sometimes \u2014 and in what way?", "da": "Hvem fra din fortid t\u00e6nker du stadig p\u00e5 nogle gange \u2014 og hvordan?", "de": "An wen aus deiner Vergangenheit denkst du manchmal noch \u2013 und in welcher Weise?", "es": "\u00bfA qui\u00e9n de tu pasado sigues pensando a veces \u2014 y de qu\u00e9 manera?", "pt": "Em quem do teu passado ainda pensas \u00e0s vezes \u2014 e de que forma?", "ro": "La cine din trecut te mai g\u00e2nde\u0219ti uneori \u2014 \u0219i \u00een ce fel?", "fr": "\u00c0 qui de ton pass\u00e9 penses-tu encore parfois \u2014 et de quelle mani\u00e8re ?", "it": "Chi del tuo passato pensi ancora a volte \u2014 e in che modo?", "fi": "Kuka menneisyydest\u00e4si tulee joskus mieleesi \u2014 ja mill\u00e4 tavalla?", "nl": "Wie uit je verleden denk je soms nog aan \u2014 en op welke manier?", "no": "Hvem fra fortiden din tenker du fortsatt p\u00e5 noen ganger \u2014 og p\u00e5 hvilken m\u00e5te?", "sv": "Vem fr\u00e5n ditt f\u00f6rflutna t\u00e4nker du fortfarande p\u00e5 ibland \u2014 och p\u00e5 vilket s\u00e4tt?", "pl": "Kto z twojej przesz\u0142o\u015bci czasami przychodzi ci na my\u015bl \u2014 i w jaki spos\u00f3b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who from your past do you still think about sometimes — and in what way?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people often misunderstand about you?", "da": "Hvad misforst\u00e5r folk ofte om dig?", "de": "Was missverstehen die Leute oft an dir?", "es": "\u00bfQu\u00e9 es algo que la gente suele malinterpretar sobre ti?", "pt": "O que \u00e9 algo que as pessoas geralmente interpretam mal sobre ti?", "ro": "Ce crezi c\u0103 oamenii \u00een\u021beleg gre\u0219it despre tine?", "fr": "Qu\u2019est-ce que les gens comprennent souvent mal \u00e0 ton sujet ?", "it": "Qualcosa che le persone fraintendono spesso su di te?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset usein v\u00e4\u00e4rin ymm\u00e4rt\u00e4v\u00e4t sinusta?", "nl": "Wat is iets dat mensen vaak verkeerd begrijpen over jou?", "no": "Hva er noe folk ofte misforst\u00e5r om deg?", "sv": "Vad \u00e4r n\u00e5got som folk ofta missf\u00f6rst\u00e5r om dig?", "pl": "Co\u015b, co ludzie cz\u0119sto \u017ale rozumiej\u0105 na tw\u00f3j temat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something people often misunderstand about you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019d love for my parents to know about you someday?", "da": "Hvad er noget, du gerne vil have, mine for\u00e6ldre skal vide om dig en dag?", "de": "Was m\u00f6chtest du, dass meine Eltern eines Tages \u00fcber dich wissen?", "es": "\u00bfQu\u00e9 te gustar\u00eda que mis padres supieran sobre ti alg\u00fan d\u00eda?", "pt": "O que gostarias que os meus pais soubessem sobre ti um dia?", "ro": "Ce \u021bi-ar pl\u0103cea ca p\u0103rin\u021bii mei s\u0103 afle despre tine \u00eentr-o zi?", "fr": "Qu\u2019aimerais-tu que mes parents sachent de toi un jour ?", "it": "Qualcosa che ti piacerebbe che i miei genitori sapessero di te un giorno?", "fi": "Mik\u00e4 on jotain, jonka haluaisit vanhempieni tiet\u00e4v\u00e4n sinusta joskus?", "nl": "Wat is iets dat je zou willen dat mijn ouders ooit over jou weten?", "no": "Hva er noe du gjerne skulle \u00f8nsket at foreldrene mine visste om deg en dag?", "sv": "Vad \u00e4r det som du skulle vilja att mina f\u00f6r\u00e4ldrar fick veta om dig n\u00e5gon g\u00e5ng?", "pl": "Co\u015b, co chcia\u0142by\u015b, aby moi rodzice kiedy\u015b o tobie wiedzieli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you’d love for my parents to know about you someday?';
UPDATE questions
SET translations = '{"en": "Hand me your phone \u2014 I get to scroll through your photos for ten seconds.", "da": "Giv mig din telefon \u2014 jeg f\u00e5r lov til at rulle gennem dine billeder i ti sekunder.", "de": "Gib mir dein Handy \u2013 ich darf zehn Sekunden lang durch deine Fotos scrollen.", "es": "Dame tu tel\u00e9fono \u2014 puedo desplazarme por tus fotos durante diez segundos.", "pt": "D\u00e1-me o teu telem\u00f3vel \u2014 posso ver as tuas fotos por dez segundos.", "ro": "D\u0103-mi telefonul t\u0103u \u2014 pot derula prin fotografiile tale zece secunde.", "fr": "Passe-moi ton t\u00e9l\u00e9phone \u2014 j\u2019ai dix secondes pour faire d\u00e9filer tes photos.", "it": "Passami il tuo telefono \u2014 posso scorrere le tue foto per dieci secondi.", "fi": "Anna puhelimesi \u2014 saan selata valokuviasi kymmenen sekuntia.", "nl": "Geef me je telefoon \u2014 ik mag tien seconden door je foto''s scrollen.", "no": "Gi meg telefonen din \u2014 jeg f\u00e5r bla gjennom bildene dine i ti sekunder.", "sv": "Ge mig din telefon \u2014 jag f\u00e5r bl\u00e4ddra igenom dina bilder i tio sekunder.", "pl": "Podaj mi sw\u00f3j telefon \u2014 mog\u0119 przegl\u0105da\u0107 twoje zdj\u0119cia przez dziesi\u0119\u0107 sekund."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Hand me your phone — I get to scroll through your photos for ten seconds.';
UPDATE questions
SET translations = '{"en": "Have you ever felt judged for something you believe in?", "da": "Har du nogensinde f\u00f8lt dig d\u00f8mt for noget, du tror p\u00e5?", "de": "Hast du dich jemals f\u00fcr etwas, woran du glaubst, verurteilt gef\u00fchlt?", "es": "\u00bfAlguna vez te has sentido juzgado por algo en lo que crees?", "pt": "Alguma vez sentiste que foste julgado por algo em que acreditas?", "ro": "Te-ai sim\u021bit vreodat\u0103 judecat pentru ceva \u00een care crezi?", "fr": "T\u2019es-tu d\u00e9j\u00e0 senti jug\u00e9 pour quelque chose en quoi tu crois ?", "it": "Hai mai sentito di essere giudicato per qualcosa in cui credi?", "fi": "Oletko koskaan tuntenut, ett\u00e4 sinua on arvosteltu jostain, mihin uskot?", "nl": "Heb je ooit het gevoel gehad beoordeeld te worden om iets waar je in gelooft?", "no": "Har du noen gang f\u00f8lt deg d\u00f8mt for noe du tror p\u00e5?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig d\u00f6md f\u00f6r n\u00e5got du tror p\u00e5?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 oceniany za co\u015b, w co wierzysz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever felt judged for something you believe in?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think I don\u2019t give myself enough credit for?", "da": "Hvad tror du, jeg ikke giver mig selv nok ros for?", "de": "Was glaubst du, wof\u00fcr ich mir selbst nicht genug Anerkennung gebe?", "es": "\u00bfPor qu\u00e9 cosa crees que no me doy suficiente cr\u00e9dito?", "pt": "Pelo que achas que n\u00e3o me dou cr\u00e9dito suficiente?", "ro": "Pentru ce crezi c\u0103 nu \u00eemi dau suficient merit?", "fr": "Pour quoi penses-tu que je ne me donne pas assez de cr\u00e9dit ?", "it": "Qual \u00e8 una cosa per cui pensi che non mi dia abbastanza credito?", "fi": "Mik\u00e4 on jotain, mist\u00e4 luulet, etten anna itselleni tarpeeksi krediitti\u00e4?", "nl": "Wat is iets waarvan je denkt dat ik mezelf niet genoeg krediet geef?", "no": "Hva er noe du mener jeg ikke gir meg selv nok kreditt for?", "sv": "Vad \u00e4r n\u00e5got du tycker att jag inte ger mig sj\u00e4lv tillr\u00e4ckligt med ber\u00f6m f\u00f6r?", "pl": "Co\u015b, za co my\u015blisz, \u017ce nie doceniam siebie wystarczaj\u0105co?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you think I don’t give myself enough credit for?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019d love us to try together but haven\u2019t yet?", "da": "Hvad er noget, du gerne vil have, vi pr\u00f8ver sammen, men endnu ikke har gjort?", "de": "Was w\u00fcrdest du gerne mit mir ausprobieren, was wir noch nicht getan haben?", "es": "\u00bfQu\u00e9 te gustar\u00eda que prob\u00e1ramos juntos pero a\u00fan no hemos hecho?", "pt": "O que gostarias que tent\u00e1ssemos juntos mas ainda n\u00e3o fizemos?", "ro": "Ce ai vrea s\u0103 \u00eencerc\u0103m \u00eempreun\u0103, dar nu am f\u0103cut \u00eenc\u0103?", "fr": "Qu\u2019aimerais-tu que nous essayions ensemble mais que nous n\u2019avons pas encore fait ?", "it": "Qualcosa che ti piacerebbe provare insieme ma non abbiamo ancora fatto?", "fi": "Mik\u00e4 on jotain, mit\u00e4 haluaisit meid\u00e4n kokeilevan yhdess\u00e4, mutta emme ole viel\u00e4 tehneet?", "nl": "Wat is iets dat je graag samen met ons zou willen proberen, maar dat we nog niet hebben gedaan?", "no": "Hva er noe du gjerne vil at vi skal pr\u00f8ve sammen, men som vi ikke har gjort enn\u00e5?", "sv": "Vad \u00e4r n\u00e5got du skulle vilja att vi provar tillsammans men inte har gjort \u00e4n?", "pl": "Co\u015b, co chcieliby\u015bmy spr\u00f3bowa\u0107 razem, ale jeszcze tego nie zrobili\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you’d love us to try together but haven’t yet?';
UPDATE questions
SET translations = '{"en": "How do you think your exes would describe you as a partner?", "da": "Hvordan tror du, dine ekser ville beskrive dig som partner?", "de": "Wie w\u00fcrden dich deine Ex-Partner als Partner beschreiben?", "es": "\u00bfC\u00f3mo crees que tus ex te describir\u00edan como pareja?", "pt": "Como achas que os teus ex te descreveriam como parceiro?", "ro": "Cum crezi c\u0103 te-ar descrie fo\u0219tii t\u0103i ca partener?", "fr": "Comment penses-tu que tes ex te d\u00e9criraient comme partenaire ?", "it": "Come pensi che i tuoi ex ti descriverebbero come partner?", "fi": "Miten luulet, ett\u00e4 eks\u00e4si kuvailisivat sinua kumppanina?", "nl": "Hoe denk je dat je exen jou als partner zouden beschrijven?", "no": "Hvordan tror du eksene dine ville beskrevet deg som partner?", "sv": "Hur tror du att dina ex skulle beskriva dig som partner?", "pl": "Jak my\u015blisz, jak twoje by\u0142e partnerki/partnerzy opisaliby ci\u0119 jako partnera?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you think your exes would describe you as a partner?';
UPDATE questions
SET translations = '{"en": "How do you feel about getting older?", "da": "Hvordan har du det med at blive \u00e6ldre?", "de": "Wie f\u00fchlst du dich, wenn du \u00e4lter wirst?", "es": "\u00bfC\u00f3mo te sientes respecto a envejecer?", "pt": "Como te sentes em rela\u00e7\u00e3o a envelhecer?", "ro": "Cum te sim\u021bi \u00een leg\u0103tur\u0103 cu \u00eemb\u0103tr\u00e2nirea?", "fr": "Comment te sens-tu \u00e0 propos du fait de vieillir ?", "it": "Come ti senti riguardo all''invecchiare?", "fi": "Milt\u00e4 sinusta tuntuu vanhenemisesta?", "nl": "Hoe voel je je over ouder worden?", "no": "Hvordan f\u00f8ler du om \u00e5 bli eldre?", "sv": "Hur k\u00e4nner du inf\u00f6r att bli \u00e4ldre?", "pl": "Jak si\u0119 czujesz z powodu starzenia si\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about getting older?';
UPDATE questions
SET translations = '{"en": "Stare into my eyes for thirty seconds without laughing or looking away.", "da": "Stir mig i \u00f8jnene i tredive sekunder uden at grine eller kigge v\u00e6k.", "de": "Schau mir drei\u00dfig Sekunden lang in die Augen, ohne zu lachen oder wegzuschauen.", "es": "M\u00edrame a los ojos durante treinta segundos sin re\u00edrte ni mirar hacia otro lado.", "pt": "Olha-me nos olhos durante trinta segundos sem rir nem desviar o olhar.", "ro": "Prive\u0219te-m\u0103 \u00een ochi treizeci de secunde f\u0103r\u0103 s\u0103 r\u00e2zi sau s\u0103 te ui\u021bi \u00een alt\u0103 parte.", "fr": "Regarde-moi dans les yeux pendant trente secondes sans rire ni d\u00e9tourner le regard.", "it": "Guarda nei miei occhi per trenta secondi senza ridere o distogliere lo sguardo.", "fi": "Tuijota silmiini kolmekymment\u00e4 sekuntia nauramatta tai k\u00e4\u00e4nt\u00e4m\u00e4tt\u00e4 katsetta pois.", "nl": "Kijk dertig seconden in mijn ogen zonder te lachen of weg te kijken.", "no": "Se inn i \u00f8ynene mine i tretti sekunder uten \u00e5 le eller se bort.", "sv": "Stir in mina \u00f6gon i trettio sekunder utan att skratta eller titta bort.", "pl": "Patrz mi w oczy przez trzydzie\u015bci sekund, nie \u015bmiej\u0105c si\u0119 i nie odwracaj\u0105c wzroku."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Stare into my eyes for thirty seconds without laughing or looking away.';