UPDATE questions
SET translations = '{"en": "Who\u2019s more likely to accidentally spend $100 on something ridiculous?", "da": "Hvem har st\u00f8rst sandsynlighed for ved et uheld at bruge 100 $ p\u00e5 noget latterligt?", "de": "Wer w\u00fcrde mit gr\u00f6\u00dferer Wahrscheinlichkeit versehentlich 100 $ f\u00fcr etwas L\u00e4cherliches ausgeben?", "es": "\u00bfQui\u00e9n tiene m\u00e1s probabilidades de gastar accidentalmente 100 $ en algo rid\u00edculo?", "pt": "Quem tem maior probabilidade de gastar acidentalmente 100 US$ em algo rid\u00edculo?", "ro": "Cine este mai probabil s\u0103 cheltuiasc\u0103 din gre\u015feal\u0103 100 $ pe ceva ridicol?", "fr": "Qui est le plus susceptible de d\u00e9penser par accident 100 $ pour quelque chose de ridicule ?", "it": "Chi \u00e8 pi\u00f9 propenso a spendere accidentalmente 100 dollari per qualcosa di ridicolo?", "fi": "Kuka on todenn\u00e4k\u00f6isemmin vahingossa valmis k\u00e4ytt\u00e4m\u00e4\u00e4n 100 dollaria johonkin j\u00e4rjett\u00f6m\u00e4\u00e4n?", "nl": "Wie is er waarschijnlijker om per ongeluk $100 aan iets belachelijks uit te geven?", "no": "Hvem er mer sannsynlig \u00e5 ved en feiltakelse bruke 100 dollar p\u00e5 noe latterlig?", "sv": "Vem \u00e4r mer ben\u00e4gen att av misstag spendera 100 dollar p\u00e5 n\u00e5got l\u00f6jligt?", "pl": "Kto ma wi\u0119ksze szanse, \u017ceby przypadkowo wyda\u0107 100 dolar\u00f3w na co\u015b absurdalnego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Who’s more likely to accidentally spend $100 on something ridiculous?';
UPDATE questions
SET translations = '{"en": "Who\u2019s more likely to laugh in a serious moment?", "da": "Hvem har st\u00f8rst sandsynlighed for at grine i et seri\u00f8st \u00f8jeblik?", "de": "Wer w\u00fcrde in einem ernsten Moment eher lachen?", "es": "\u00bfQui\u00e9n tiene m\u00e1s probabilidades de re\u00edr en un momento serio?", "pt": "Quem \u00e9 mais prov\u00e1vel de rir num momento s\u00e9rio?", "ro": "Cine are cele mai mari \u015fanse s\u0103 r\u00e2d\u0103 \u00eentr-un moment serios?", "fr": "Qui est le plus susceptible de rire dans un moment s\u00e9rieux ?", "it": "Chi \u00e8 pi\u00f9 propenso a ridere in un momento serio?", "fi": "Kuka todenn\u00e4k\u00f6isesti nauraa vakavassa hetkess\u00e4?", "nl": "Wie is er waarschijnlijker om te lachen in een serieuze situatie?", "no": "Hvem er mer sannsynlig \u00e5 le i et alvorlig \u00f8yeblikk?", "sv": "Vem \u00e4r mer ben\u00e4gen att skratta i en allvarlig stund?", "pl": "Kto jest bardziej sk\u0142onny do \u015bmiechu w powa\u017cnej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Who’s more likely to laugh in a serious moment?';
UPDATE questions
SET translations = '{"en": "What everyday sound do I weirdly imitate too well?", "da": "Hvilken daglig lyd efterligner jeg m\u00e6rkeligt godt?", "de": "Welches Alltagsger\u00e4usch imitiere ich komischerweise viel zu gut?", "es": "\u00bfQu\u00e9 sonido cotidiano imito extra\u00f1amente demasiado bien?", "pt": "Que som cotidiano imito estranhamente demasiado bem?", "ro": "Ce sunet cotidian imi imit foarte ciudat \u015fi prea bine?", "fr": "Quel son quotidien j\u2019imite \u00e9trangement trop bien ?", "it": "Quale suono quotidiano imito in modo strano e troppo realistico?", "fi": "Mik\u00e4 arkinen \u00e4\u00e4ni minulta kummallisesti onnistuu imitoimaan liian hyvin?", "nl": "Welk alledaags geluid imiteer ik op een vreemde manier te goed?", "no": "Hvilken hverdagslyd imiterer jeg merkelig godt?", "sv": "Vilket vardagligt ljud imiterar jag konstigt nog f\u00f6r bra?", "pl": "Jaki codzienny d\u017awi\u0119k dziwnie na\u015bladuj\u0119 zbyt dobrze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What everyday sound do I weirdly imitate too well?';
UPDATE questions
SET translations = '{"en": "What\u2019s the funniest wrong lyric you sang for years?", "da": "Hvad er den sjoveste forkerte tekst, jeg sang i \u00e5revis?", "de": "Welcher ist der lustigste falsche Liedtext, den ich jahrelang gesungen habe?", "es": "\u00bfCu\u00e1l es la letra incorrecta m\u00e1s divertida que cant\u00e9 durante a\u00f1os?", "pt": "Qual \u00e9 a letra errada mais engra\u00e7ada que cantei durante anos?", "ro": "Care este versul gre\u015fit cel mai amuzant pe care l-am c\u00e2ntat ani de zile?", "fr": "Quelle est la fausse parole la plus dr\u00f4le que j\u2019ai chant\u00e9e pendant des ann\u00e9es ?", "it": "Qual \u00e8 stata la frase sbagliata pi\u00f9 divertente che hai cantato per anni?", "fi": "Mik\u00e4 on hauskin v\u00e4\u00e4r\u00e4 lyriikka, jonka lauloit vuosia?", "nl": "Wat is de grappigste foute tekst die je jarenlang hebt gezongen?", "no": "Hva er den morsomste feil teksten du har sunget i \u00e5revis?", "sv": "Vad \u00e4r den roligaste feltexten du sj\u00f6ng i flera \u00e5r?", "pl": "Jaka jest najzabawniejsza b\u0142\u0119dna linijka, kt\u00f3r\u0105 \u015bpiewa\u0142e\u015b przez lata?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s the funniest wrong lyric you sang for years?';
UPDATE questions
SET translations = '{"en": "If our fridge could talk, what would it roast us about?", "da": "Hvis vores k\u00f8leskab kunne tale, hvad ville det s\u00e5 slette os for?", "de": "Wenn unser K\u00fchlschrank sprechen k\u00f6nnte \u2013 wor\u00fcber w\u00fcrde er uns verspotten?", "es": "Si nuestra nevera pudiera hablar, \u00bfsobre qu\u00e9 se burlar\u00eda de nosotros?", "pt": "Se o nosso frigor\u00edfico pudesse falar, sobre o que nos gozaria?", "ro": "Dac\u0103 frigiderul nostru ar putea vorbi, despre ce ne-ar face mi\u015fto?", "fr": "Si notre frigo pouvait parler, de quoi se moquerait-il ?", "it": "Se il nostro frigorifero potesse parlare, di cosa ci prenderebbe in giro?", "fi": "Jos j\u00e4\u00e4kaappimme voisi puhua, mist\u00e4 se meit\u00e4 naljailisi?", "nl": "Als onze koelkast kon praten, waar zou hij ons dan over plagen?", "no": "Hvis kj\u00f8leskapet v\u00e5rt kunne snakke, hva ville det ertet oss om?", "sv": "Om v\u00e5rt kylsk\u00e5p kunde prata, vad skulle det sk\u00e4mta om oss?", "pl": "Gdyby nasza lod\u00f3wka mog\u0142a m\u00f3wi\u0107, z czego by nas wy\u015bmiewa\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If our fridge could talk, what would it roast us about?';
UPDATE questions
SET translations = '{"en": "If I ran a wildly specific niche store, what would I sell?", "da": "Hvis jeg drev en ekstremt niche-butik, hvad ville jeg s\u00e5 s\u00e6lge?", "de": "Wenn ich ein irre spezifisches Nischen-Gesch\u00e4ft f\u00fchren w\u00fcrde \u2013 was w\u00fcrde ich verkaufen?", "es": "Si yo dirigiera una tienda de nicho extremadamente espec\u00edfica, \u00bfqu\u00e9 vender\u00eda?", "pt": "Se eu dirigisse uma loja de nicho extremamente espec\u00edfica, o que venderia?", "ro": "Dac\u0103 a\u015f conduce un magazin extrem de specific de ni\u015f\u0103, ce a\u015f vinde?", "fr": "Si je tenais une boutique ultra-sp\u00e9cifique de niche, que vendrais-je ?", "it": "Se gestissi un negozio di nicchia estremamente specifico, cosa venderei?", "fi": "Jos py\u00f6ritt\u00e4isin hyvin erityist\u00e4 erikoisliikett\u00e4, mit\u00e4 myisin?", "nl": "Als ik een extreem specifieke nichewinkel zou runnen, wat zou ik dan verkopen?", "no": "Hvis jeg drev en veldig spesifikk nisjebutikk, hva ville jeg solgt?", "sv": "Om jag drev en extremt specifik nischbutik, vad skulle jag s\u00e4lja?", "pl": "Je\u015bli prowadzi\u0142bym bardzo specyficzny sklep niszowy, co bym sprzedawa\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If I ran a wildly specific niche store, what would I sell?';
UPDATE questions
SET translations = '{"en": "Do you have a chef\u2019s-kiss snack combo that horrifies others? What is it?", "da": "Har du en \u201cchef\u2019s-kiss\u201d snack-kombination, der skr\u00e6mmer andre? Hvad er den?", "de": "Hast du eine \u201eChef\u2019s-Kiss\u201c Snack-Kombi, die andere entsetzt? Was ist es?", "es": "\u00bfTienes una combinaci\u00f3n de snack estilo \u201echef\u2019s-kiss\u201d que horrorizara a otros? \u00bfCu\u00e1l es?", "pt": "Tens uma combina\u00e7\u00e3o de snack \u201cchef\u2019s-kiss\u201d que horroriza os outros? Qual \u00e9?", "ro": "Ai o combina\u0163ie de gustare \u201cchef\u2019s-kiss\u201d care sperie pe al\u0163ii? Care e?", "fr": "As-tu une combo grignotage \u00ab chef\u2019s-kiss \u00bb qui horrifie les autres ? Quelle est-elle ?", "it": "Hai una combinazione di snack da chef che orripila gli altri? Qual \u00e8?", "fi": "Onko sinulla joku kokin suudelman arvoinen v\u00e4lipala-yhdistelm\u00e4, joka kauhistuttaa muita? Mik\u00e4 se on?", "nl": "Heb je een snackcombinatie die een chef''s-kus waard is en anderen afschrikt? Wat is het?", "no": "Har du en snacks-kombinasjon som f\u00e5r andre til \u00e5 gr\u00f8sse? Hva er det?", "sv": "Har du en snacks-kombination som f\u00e5r andra att rysa av skr\u00e4ck? Vad \u00e4r det?", "pl": "Czy masz przek\u0105sk\u0119, kt\u00f3ra dla innych jest przera\u017caj\u0105ca, ale dla ciebie to po\u0142\u0105czenie idealne? Co to jest?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Do you have a chef’s-kiss snack combo that horrifies others? What is it?';
UPDATE questions
SET translations = '{"en": "What emoji do you overuse and what does it secretly mean?", "da": "Hvilken emoji overbruger du, og hvad betyder den hemmeligt?", "de": "Welchen Emoji \u00fcberverwendest du und was bedeutet er heimlich?", "es": "\u00bfQu\u00e9 emoji usas en exceso y qu\u00e9 significa en secreto?", "pt": "Que emoji usas em demasia e o que significa secretamente?", "ro": "Ce emoji folose\u015fti excesiv \u015fi ce \u00eenseamn\u0103 secret?", "fr": "Quel emoji utilises-tu \u00e0 outrance et que signifie-t-il secr\u00e8tement ?", "it": "Quale emoji usi troppo e cosa significa segretamente?", "fi": "Mik\u00e4 emoji on sinulla k\u00e4yt\u00f6ss\u00e4 liikaa ja mit\u00e4 se salaa tarkoittaa?", "nl": "Welke emoji gebruik je te vaak en wat betekent het stiekem?", "no": "Hvilket emoji bruker du for mye, og hva betyr det egentlig?", "sv": "Vilken emoji anv\u00e4nder du f\u00f6r mycket och vad betyder den egentligen?", "pl": "Jakiego emoji nadu\u017cywasz i co to tak naprawd\u0119 oznacza?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What emoji do you overuse and what does it secretly mean?';
UPDATE questions
SET translations = '{"en": "Which household task do I treat like an Olympic sport?", "da": "Hvilken husarbejde behandler jeg som en olympisk sport?", "de": "Welche Hausarbeit behandele ich wie eine olympische Sportart?", "es": "\u00bfQu\u00e9 tarea dom\u00e9stica trato como si fuera un deporte ol\u00edmpico?", "pt": "Qual tarefa dom\u00e9stica trato como se fosse um desporto ol\u00edmpico?", "ro": "Ce treab\u0103 casnic\u0103 tratez ca pe un sport olimpic?", "fr": "Quelle t\u00e2che m\u00e9nag\u00e8re je traite comme un sport olympique ?", "it": "Quale compito domestico tratto come se fosse uno sport olimpico?", "fi": "Mik\u00e4 kotity\u00f6 on minulle kuin olympialaji?", "nl": "Welke huishoudelijke taak beschouw ik als een Olympische sport?", "no": "Hvilket husarbeid behandler jeg som en olympisk sport?", "sv": "Vilken hush\u00e5llssyssla behandlar jag som en olympisk sport?", "pl": "Kt\u00f3r\u0105 domow\u0105 czynno\u015b\u0107 traktuj\u0119 jak sport olimpijski?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which household task do I treat like an Olympic sport?';
UPDATE questions
SET translations = '{"en": "What\u2019s my most dramatic reaction to a very small inconvenience?", "da": "Hvad er min mest dramatiske reaktion p\u00e5 en meget lille ulejlighed?", "de": "Was ist meine dramatischste Reaktion auf eine sehr kleine Unannehmlichkeit?", "es": "\u00bfCu\u00e1l es mi reacci\u00f3n m\u00e1s dram\u00e1tica ante una peque\u00f1a molestia?", "pt": "Qual \u00e9 a minha reac\u00e7\u00e3o mais dram\u00e1tica a um inc\u00f3modo muito pequeno?", "ro": "Care e cea mai dramatic\u0103 reac\u0163ie a mea la un inconvenient foarte mic?", "fr": "Quelle est ma r\u00e9action la plus dramatique \u00e0 une toute petite contrari\u00e9t\u00e9 ?", "it": "Qual \u00e8 stata la mia reazione pi\u00f9 drammatica a un piccolo inconveniente?", "fi": "Mik\u00e4 on dramaattisin reaktioni hyvin pieneen vaivaan?", "nl": "Wat is mijn meest dramatische reactie op een heel kleine tegenslag?", "no": "Hva er min mest dramatiske reaksjon p\u00e5 en veldig liten ulempe?", "sv": "Vad \u00e4r min mest dramatiska reaktion p\u00e5 en v\u00e4ldigt liten ol\u00e4genhet?", "pl": "Jaka by\u0142a moja najbardziej dramatyczna reakcja na bardzo ma\u0142\u0105 niedogodno\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s my most dramatic reaction to a very small inconvenience?';