UPDATE questions
SET translations = '{"en": "How do you define success for yourself now?", "da": "Hvordan definerer du succes for dig selv nu?", "de": "Wie definierst du heute Erfolg f\u00fcr dich selbst?", "es": "\u00bfC\u00f3mo defines el \u00e9xito para ti ahora?", "pt": "Como defines o sucesso para ti agora?", "ro": "Cum define\u0219ti succesul pentru tine acum?", "fr": "Comment d\u00e9finis-tu le succ\u00e8s pour toi aujourd\u2019hui ?", "it": "Come definisci il successo per te stesso adesso?", "fi": "Miten m\u00e4\u00e4rittelet menestyksen itsellesi nyt?", "nl": "Hoe definieer je nu succes voor jezelf?", "no": "Hvordan definerer du suksess for deg selv n\u00e5?", "sv": "Hur definierar du framg\u00e5ng f\u00f6r dig sj\u00e4lv nu?", "pl": "Jak definiujesz sukces dla siebie teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you define success for yourself now?';
UPDATE questions
SET translations = '{"en": "Do you think honesty can sometimes sound like judgment?", "da": "Tror du, \u00e6rlighed nogle gange kan lyde som d\u00f8mmende?", "de": "Denkst du, Ehrlichkeit kann manchmal wie ein Urteil klingen?", "es": "\u00bfCrees que la honestidad a veces puede sonar como un juicio?", "pt": "Acreditas que a honestidade \u00e0s vezes soa como julgamento?", "ro": "Crezi c\u0103 sinceritatea poate suna uneori ca o judecat\u0103?", "fr": "Penses-tu que l\u2019honn\u00eatet\u00e9 peut parfois ressembler \u00e0 un jugement ?", "it": "Pensi che l''onest\u00e0 a volte possa sembrare un giudizio?", "fi": "Luuleeko, ett\u00e4 rehellisyys voi joskus kuulostaa tuomiolta?", "nl": "Denk je dat eerlijkheid soms als oordeel kan klinken?", "no": "Tror du at \u00e6rlighet noen ganger kan h\u00f8res ut som d\u00f8mming?", "sv": "Tycker du att \u00e4rlighet ibland kan l\u00e5ta som d\u00f6mande?", "pl": "Czy my\u015blisz, \u017ce szczero\u015b\u0107 czasami mo\u017ce brzmie\u0107 jak os\u0105d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you think honesty can sometimes sound like judgment?';
UPDATE questions
SET translations = '{"en": "What\u2019s a political or social issue you feel strongly about but rarely talk about?", "da": "Hvilket politisk eller socialt emne f\u00f8ler du st\u00e6rkt for, men taler sj\u00e6ldent om?", "de": "Welches politische oder soziale Thema liegt dir am Herzen, \u00fcber das du selten sprichst?", "es": "\u00bfQu\u00e9 tema pol\u00edtico o social te importa mucho pero del que rara vez hablas?", "pt": "Que tema pol\u00edtico ou social te importa muito mas raramente falas sobre ele?", "ro": "Ce subiect politic sau social te preocup\u0103, dar rar vorbe\u0219ti despre el?", "fr": "Quel sujet politique ou social te tient \u00e0 c\u0153ur mais dont tu parles rarement ?", "it": "Qual \u00e8 un problema politico o sociale su cui hai forti opinioni ma di cui parli raramente?", "fi": "Mik\u00e4 on poliittinen tai sosiaalinen kysymys, josta tunnet voimakkaasti, mutta josta harvoin puhut?", "nl": "Wat is een politiek of sociaal probleem waar je sterk over denkt, maar zelden over praat?", "no": "Hva er et politisk eller sosialt sp\u00f8rsm\u00e5l du f\u00f8ler sterkt for, men sjelden snakker om?", "sv": "Vilket politiskt eller socialt \u00e4mne k\u00e4nner du starkt f\u00f6r men s\u00e4llan pratar om?", "pl": "Jaki jest problem polityczny lub spo\u0142eczny, na kt\u00f3rym ci zale\u017cy, ale rzadko o nim rozmawiasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s a political or social issue you feel strongly about but rarely talk about?';
UPDATE questions
SET translations = '{"en": "What do you think is harder today: being authentic or being private?", "da": "Hvad tror du er sv\u00e6rere i dag: at v\u00e6re autentisk eller at v\u00e6re privat?", "de": "Was glaubst du, ist heute schwieriger: authentisch oder privat zu sein?", "es": "\u00bfQu\u00e9 crees que es m\u00e1s dif\u00edcil hoy en d\u00eda: ser aut\u00e9ntico o ser reservado?", "pt": "O que achas que \u00e9 mais dif\u00edcil hoje: ser aut\u00eantico ou ser reservado?", "ro": "Ce crezi c\u0103 e mai greu azi: s\u0103 fii autentic sau s\u0103 fii discret?", "fr": "Que crois-tu qu\u2019il soit plus difficile aujourd\u2019hui : \u00eatre authentique ou \u00eatre r\u00e9serv\u00e9 ?", "it": "Cosa pensi sia pi\u00f9 difficile oggi: essere autentici o essere riservati?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 on t\u00e4n\u00e4 p\u00e4iv\u00e4n\u00e4 vaikeampaa: olla aito vai olla yksityinen?", "nl": "Wat denk je dat vandaag moeilijker is: authentiek zijn of priv\u00e9 zijn?", "no": "Hva tror du er vanskeligere i dag: \u00e5 v\u00e6re autentisk eller \u00e5 v\u00e6re privat?", "sv": "Vad tycker du \u00e4r sv\u00e5rare idag: att vara \u00e4kta eller att vara privat?", "pl": "Co my\u015blisz, co jest dzisiaj trudniejsze: bycie autentycznym czy bycie prywatnym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you think is harder today: being authentic or being private?';
UPDATE questions
SET translations = '{"en": "How do you feel about influencers or people who share every detail of their lives publicly?", "da": "Hvordan har du det med influencere eller folk, der deler alle detaljer af deres liv offentligt?", "de": "Wie stehst du zu Influencern oder Menschen, die jedes Detail ihres Lebens \u00f6ffentlich teilen?", "es": "\u00bfQu\u00e9 opinas de los influencers o de las personas que comparten cada detalle de su vida p\u00fablicamente?", "pt": "O que pensas dos influenciadores ou pessoas que partilham todos os detalhes da sua vida?", "ro": "Ce p\u0103rere ai despre influencerii sau persoanele care \u00ee\u0219i \u00eemp\u0103rt\u0103\u0219esc public fiecare detaliu al vie\u021bii?", "fr": "Que penses-tu des influenceurs ou des gens qui partagent chaque d\u00e9tail de leur vie publiquement ?", "it": "Cosa ne pensi degli influencer o delle persone che condividono ogni dettaglio della loro vita pubblicamente?", "fi": "Mit\u00e4 mielt\u00e4 olet vaikuttajista tai ihmisist\u00e4, jotka jakavat jokaisen yksityiskohdan el\u00e4m\u00e4st\u00e4\u00e4n julkisesti?", "nl": "Hoe voel je je over influencers of mensen die elk detail van hun leven openbaar delen?", "no": "Hva synes du om influensere eller folk som deler hver detalj av livene sine offentlig?", "sv": "Vad tycker du om influencers eller personer som delar varje detalj av sina liv offentligt?", "pl": "Jak si\u0119 czujesz w zwi\u0105zku z influencerami lub osobami, kt\u00f3re publicznie dziel\u0105 si\u0119 ka\u017cdym szczeg\u00f3\u0142em swojego \u017cycia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about influencers or people who share every detail of their lives publicly?';
UPDATE questions
SET translations = '{"en": "Have you ever taken something that wasn\u2019t yours? How did you feel afterward?", "da": "Har du nogensinde taget noget, der ikke var dit? Hvordan havde du det bagefter?", "de": "Har du nogensinde f\u00f8lt dig genert over at sp\u00f8rge om det, du vil have?", "es": "Hast du dich jemals gesch\u00e4mt, nach dem zu fragen, was du willst?", "pt": "J\u00e1 pegaste algo que n\u00e3o era teu? Como te sentiste depois?", "ro": "Ai luat vreodat\u0103 ceva ce nu era al t\u0103u? Cum te-ai sim\u021bit dup\u0103?", "fr": "As-tu d\u00e9j\u00e0 pris quelque chose qui ne t\u2019appartenait pas ? Comment t\u2019es-tu senti apr\u00e8s ?", "it": "Hai mai preso qualcosa che non era tuo? Come ti sei sentito dopo?", "fi": "Oletko koskaan ottanut jotain, mik\u00e4 ei ollut sinun? Milt\u00e4 sinusta tuntui sen j\u00e4lkeen?", "nl": "Heb je ooit iets genomen dat niet van jou was? Hoe voelde je je daarna?", "no": "Har du noen gang tatt noe som ikke var ditt? Hvordan f\u00f8lte du deg etterp\u00e5?", "sv": "Har du n\u00e5gonsin tagit n\u00e5got som inte var ditt? Hur k\u00e4nde du dig efter\u00e5t?", "pl": "Czy kiedykolwiek wzi\u0105\u0142e\u015b co\u015b, co nie by\u0142o twoje? Jak si\u0119 wtedy czu\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever taken something that wasn’t yours? How did you feel afterward?';
UPDATE questions
SET translations = '{"en": "What helps you feel free while still feeling loved?", "da": "Hvad hj\u00e6lper dig med at f\u00f8le dig fri, men stadig elsket?", "de": "Was hilft dir, dich frei zu f\u00fchlen und trotzdem geliebt zu werden?", "es": "\u00bfQu\u00e9 te ayuda a sentirte libre y al mismo tiempo amado?", "pt": "O que te ajuda a sentir-te livre e ainda assim amado?", "ro": "Ce te ajut\u0103 s\u0103 te sim\u021bi liber, dar totu\u0219i iubit?", "fr": "Qu\u2019est-ce qui t\u2019aide \u00e0 te sentir libre tout en te sentant aim\u00e9 ?", "it": "Cosa ti aiuta a sentirti libero pur continuando a sentirti amato?", "fi": "Mik\u00e4 auttaa sinua tuntemaan itsesi vapaaksi samalla kun tunnet itsesi rakastetuksi?", "nl": "Wat helpt jou om je vrij te voelen terwijl je je toch geliefd voelt?", "no": "Hva hjelper deg \u00e5 f\u00f8le deg fri samtidig som du f\u00f8ler deg elsket?", "sv": "Vad hj\u00e4lper dig att k\u00e4nna dig fri samtidigt som du k\u00e4nner dig \u00e4lskad?", "pl": "Co pomaga ci czu\u0107 si\u0119 wolnym, jednocze\u015bnie czuj\u0105c si\u0119 kochanym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What helps you feel free while still feeling loved?';
UPDATE questions
SET translations = '{"en": "What helps you feel confident and attractive in your own skin?", "da": "Hvad hj\u00e6lper dig med at f\u00f8le dig selvsikker og attraktiv i din egen hud?", "de": "Was hilft dir, dich selbstbewusst und attraktiv in deiner eigenen Haut zu f\u00fchlen?", "es": "\u00bfQu\u00e9 te ayuda a sentirte seguro y atractivo en tu propia piel?", "pt": "O que te ajuda a sentires-te confiante e atraente na tua pr\u00f3pria pele?", "ro": "Ce te ajut\u0103 s\u0103 te sim\u021bi \u00eencrez\u0103tor \u0219i atr\u0103g\u0103tor \u00een pielea ta?", "fr": "Qu\u2019est-ce qui t\u2019aide \u00e0 te sentir confiant et attirant dans ta propre peau ?", "it": "Cosa ti aiuta a sentirti sicuro e attraente nella tua pelle?", "fi": "Mik\u00e4 auttaa sinua tuntemaan itsesi itsevarmaksi ja vieh\u00e4tt\u00e4v\u00e4ksi omassa kehossasi?", "nl": "Wat helpt jou om je zelfverzekerd en aantrekkelijk te voelen in je eigen huid?", "no": "Hva hjelper deg med \u00e5 f\u00f8le deg selvsikker og attraktiv i din egen hud?", "sv": "Vad hj\u00e4lper dig att k\u00e4nna dig sj\u00e4lvs\u00e4ker och attraktiv i din egen hud?", "pl": "Co pomaga ci czu\u0107 si\u0119 pewnie i atrakcyjnie we w\u0142asnej sk\u00f3rze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What helps you feel confident and attractive in your own skin?';

-- Category: History Talks (74 questions)
UPDATE questions
SET translations = '{"en": "Who had the weirdest haircut phase?", "da": "Hvem havde den m\u00e6rkeligste frisurefase?", "de": "Wer hatte die seltsamste Frisurenphase?", "es": "\u00bfQui\u00e9n tuvo la fase de peinado m\u00e1s rara?", "pt": "Quem teve a fase de corte de cabelo mais estranha?", "ro": "Cine a avut cea mai ciudat\u0103 faz\u0103 de coafur\u0103?", "fr": "Qui a eu la phase de coiffure la plus \u00e9trange ?", "it": "Chi ha avuto la fase di taglio di capelli pi\u00f9 strana?", "fi": "Kell\u00e4 oli oudoimmat hiustyyli-vaiheet?", "nl": "Wie had de vreemdste kapselperiode?", "no": "Hvem hadde den rareste frisyrefasen?", "sv": "Vem hade den konstigaste frisyrfasen?", "pl": "Kto mia\u0142 najdziwniejsz\u0105 faz\u0119 fryzury?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who had the weirdest haircut phase?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to take <5000 photos on vacation?", "da": "Hvem tager sandsynligvis <5000 billeder p\u00e5 ferien?", "de": "Wer macht wahrscheinlich <5000 Fotos im Urlaub?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que tome <5000 fotos en vacaciones?", "pt": "Quem \u00e9 mais prov\u00e1vel tirar <5000 fotos nas f\u00e9rias?", "ro": "Cine e cel mai probabil s\u0103 fac\u0103 <5000 de poze \u00een vacan\u021b\u0103?", "fr": "Qui est le plus susceptible de prendre <5000 photos en vacances ?", "it": "Chi \u00e8 pi\u00f9 probabile che scatti meno di 5000 foto in vacanza?", "fi": "Kuka todenn\u00e4k\u00f6isesti ottaa alle 5000 valokuvaa lomalla?", "nl": "Wie is het meest waarschijnlijk om <5000 foto''s op vakantie te maken?", "no": "Hvem er mest sannsynlig \u00e5 ta <5000 bilder p\u00e5 ferie?", "sv": "Vem \u00e4r mest ben\u00e4gen att ta <5000 bilder p\u00e5 semestern?", "pl": "Kto jest najbardziej prawdopodobny, aby zrobi\u0107 mniej ni\u017c 5000 zdj\u0119\u0107 na wakacjach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to take <5000 photos on vacation?';