UPDATE questions
SET translations = '{"en": "What\u2019s something you used to do outside that kids rarely do now?", "da": "Hvad plejede du at lave udenfor, som b\u00f8rn sj\u00e6ldent g\u00f8r nu?", "de": "Was hast du fr\u00fcher drau\u00dfen gemacht, was Kinder heute selten tun?", "es": "\u00bfQu\u00e9 sol\u00edas hacer afuera que los ni\u00f1os rara vez hacen ahora?", "pt": "O que costumavas fazer ao ar livre que as crian\u00e7as raramente fazem agora?", "ro": "Ce f\u0103ceai afar\u0103 pe care copiii rar \u00eel mai fac acum?", "fr": "Que faisais-tu dehors que les enfants font rarement aujourd\u2019hui ?", "it": "Qualcosa che facevi all''aperto e che i bambini raramente fanno adesso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ennen teit ulkona, mutta mit\u00e4 lapset harvoin tekev\u00e4t nyt?", "nl": "Wat is iets dat je vroeger buiten deed wat kinderen nu zelden doen?", "no": "Hva er noe du pleide \u00e5 gj\u00f8re ute som barn sjelden gj\u00f8r n\u00e5?", "sv": "Vad \u00e4r n\u00e5got du brukade g\u00f6ra utomhus som barn s\u00e4llan g\u00f6r nu?", "pl": "Co\u015b, co kiedy\u015b robi\u0142e\u015b na zewn\u0105trz, a dzieci rzadko robi\u0105 teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you used to do outside that kids rarely do now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people collected before photos lived on phones?", "da": "Hvad samlede folk p\u00e5, f\u00f8r billeder levede p\u00e5 telefoner?", "de": "Was sammelten die Leute, bevor Fotos auf Handys gespeichert wurden?", "es": "\u00bfQu\u00e9 coleccionaba la gente antes de que las fotos vivieran en los tel\u00e9fonos?", "pt": "O que as pessoas colecionavam antes de as fotos viverem nos telem\u00f3veis?", "ro": "Ce colec\u021bionau oamenii \u00eenainte ca fotografiile s\u0103 fie pe telefoane?", "fr": "Que collectionnaient les gens avant que les photos vivent sur les t\u00e9l\u00e9phones ?", "it": "Qualcosa che le persone collezionavano prima che le foto vivessero sui telefoni?", "fi": "Mit\u00e4 asioita ihmiset ker\u00e4siv\u00e4t ennen kuin valokuvat olivat puhelimissa?", "nl": "Wat is iets dat mensen verzamelden voordat foto''s op telefoons stonden?", "no": "Hva er noe folk samlet p\u00e5 f\u00f8r bilder ble lagret p\u00e5 telefoner?", "sv": "Vad \u00e4r n\u00e5got som folk samlade p\u00e5 innan foton fanns p\u00e5 telefoner?", "pl": "Co\u015b, co ludzie zbierali, zanim zdj\u0119cia zacz\u0119\u0142y by\u0107 przechowywane w telefonach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people collected before photos lived on phones?';UPDATE questions
SET translations = '{"en": "What\u2019s something you remember hearing on the radio all the time?", "da": "Hvad kan du huske, du h\u00f8rte i radioen hele tiden?", "de": "Was erinnerst du dich, st\u00e4ndig im Radio geh\u00f6rt zu haben?", "es": "\u00bfQu\u00e9 recuerdas haber escuchado en la radio todo el tiempo?", "pt": "O que te lembras de ouvir na r\u00e1dio o tempo todo?", "ro": "Ce \u00ee\u021bi aminte\u0219ti c\u0103 auzeai mereu la radio?", "fr": "Que te souviens-tu d\u2019avoir entendu tout le temps \u00e0 la radio ?", "it": "Qualcosa che ricordi di aver sentito alla radio tutto il tempo?", "fi": "Mik\u00e4 on jotain, mit\u00e4 muistat kuulleesi radiosta koko ajan?", "nl": "Wat is iets dat je je herinnert dat je vaak op de radio hoorde?", "no": "Hva er noe du husker \u00e5 ha h\u00f8rt p\u00e5 radioen hele tiden?", "sv": "Vad \u00e4r n\u00e5got du minns att du h\u00f6rde p\u00e5 radion hela tiden?", "pl": "Co\u015b, co pami\u0119tasz, \u017ce s\u0142ysza\u0142e\u015b w radiu ca\u0142y czas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you remember hearing on the radio all the time?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you had to memorize because you couldn\u2019t just look it up?", "da": "Hvad skulle du l\u00e6re udenad, fordi du ikke bare kunne sl\u00e5 det op?", "de": "Was musstest du auswendig lernen, weil du es nicht einfach nachschlagen konntest?", "es": "\u00bfQu\u00e9 ten\u00edas que memorizar porque no pod\u00edas simplemente buscarlo?", "pt": "O que tinhas de memorizar porque n\u00e3o podias simplesmente procurar?", "ro": "Ce trebuia s\u0103 memorezi pentru c\u0103 nu puteai doar s\u0103 cau\u021bi?", "fr": "Qu\u2019est-ce que tu devais m\u00e9moriser parce que tu ne pouvais pas simplement le chercher ?", "it": "Qualcosa che hai dovuto memorizzare perch\u00e9 non potevi semplicemente cercarlo?", "fi": "Mik\u00e4 on jotain, jonka jouduit muistamaan, koska et voinut vain etsi\u00e4 sit\u00e4?", "nl": "Wat is iets dat je moest onthouden omdat je het niet gewoon kon opzoeken?", "no": "Hva er noe du m\u00e5tte l\u00e6re deg utenat fordi du ikke kunne bare sl\u00e5 det opp?", "sv": "Vad \u00e4r n\u00e5got du var tvungen att memorera eftersom du inte bara kunde sl\u00e5 upp det?", "pl": "Co\u015b, co musia\u0142e\u015b zapami\u0119ta\u0107, poniewa\u017c nie mog\u0142e\u015b po prostu tego znale\u017a\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you had to memorize because you couldn’t just look it up?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think technology has made less personal?", "da": "Hvad tror du, teknologien har gjort mindre personlig?", "de": "Was hat die Technologie deiner Meinung nach unpers\u00f6nlicher gemacht?", "es": "\u00bfQu\u00e9 crees que la tecnolog\u00eda ha hecho menos personal?", "pt": "O que achas que a tecnologia tornou menos pessoal?", "ro": "Ce crezi c\u0103 a f\u0103cut tehnologia mai pu\u021bin personal?", "fr": "Qu\u2019est-ce que la technologie a rendu moins personnel selon toi ?", "it": "Qualcosa che pensi la tecnologia abbia reso meno personale?", "fi": "Mik\u00e4 on jotain, jonka ajattelet teknologian tehneen v\u00e4hemm\u00e4n henkil\u00f6kohtaiseksi?", "nl": "Wat is iets waarvan je denkt dat technologie het minder persoonlijk heeft gemaakt?", "no": "Hva er noe du mener at teknologi har gjort mindre personlig?", "sv": "Vad \u00e4r n\u00e5got som du tycker att teknologin har gjort mindre personligt?", "pl": "Co\u015b, co my\u015blisz, \u017ce technologia uczyni\u0142a mniej osobistym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you think technology has made less personal?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing from today you wish had existed long ago?", "da": "Hvad er \u00e9n ting fra i dag, du ville \u00f8nske havde eksisteret for l\u00e6nge siden?", "de": "Was ist eine Sache von heute, die du dir schon lange gew\u00fcnscht h\u00e4ttest?", "es": "\u00bfQu\u00e9 cosa de hoy desear\u00edas que hubiera existido hace mucho tiempo?", "pt": "O que de hoje gostarias que tivesse existido h\u00e1 muito tempo?", "ro": "Ce lucru din prezent \u021bi-ai fi dorit s\u0103 existe de mult?", "fr": "Quelle chose d\u2019aujourd\u2019hui aurais-tu aim\u00e9 qu\u2019elle existe il y a longtemps ?", "it": "Qual \u00e8 una cosa di oggi che avresti voluto esistesse tanto tempo fa?", "fi": "Mik\u00e4 on yksi asia t\u00e4n\u00e4\u00e4n, jonka toivoisit olevan olemassa jo kauan sitten?", "nl": "Wat is \u00e9\u00e9n ding van vandaag dat je had gewild dat het lang geleden al bestond?", "no": "Hva er \u00e9n ting fra i dag du skulle \u00f8nske hadde eksistert for lenge siden?", "sv": "Vad \u00e4r en sak fr\u00e5n idag som du \u00f6nskar hade funnits f\u00f6r l\u00e4nge sedan?", "pl": "Co\u015b, co dzisiaj istnieje, co chcia\u0142by\u015b, \u017ceby istnia\u0142o ju\u017c dawno temu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing from today you wish had existed long ago?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that cost only a few coins when you were young?", "da": "Hvad kostede kun f\u00e5 m\u00f8nter, da du var ung?", "de": "Was hat nur ein paar M\u00fcnzen gekostet, als du jung warst?", "es": "\u00bfQu\u00e9 costaba solo unas pocas monedas cuando eras joven?", "pt": "O que custava apenas umas moedas quando eras jovem?", "ro": "Ce costa doar c\u00e2teva monede c\u00e2nd erai t\u00e2n\u0103r?", "fr": "Qu\u2019est-ce qui ne co\u00fbtait que quelques pi\u00e8ces quand tu \u00e9tais jeune ?", "it": "Qualcosa che costava solo qualche moneta quando eri giovane?", "fi": "Mik\u00e4 on jotain, joka maksoi vain muutaman kolikon, kun olit nuori?", "nl": "Wat is iets dat maar een paar muntjes kostte toen je jong was?", "no": "Hva er noe som kostet bare noen f\u00e5 mynter da du var ung?", "sv": "Vad var n\u00e5got som kostade bara n\u00e5gra mynt n\u00e4r du var ung?", "pl": "Co\u015b, co kosztowa\u0142o tylko kilka monet, kiedy by\u0142e\u015b m\u0142ody?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that cost only a few coins when you were young?';
UPDATE questions
SET translations = '{"en": "What\u2019s something about \u201cthe good old days\u201d that actually wasn\u2019t so good?", "da": "Hvad ved \u201cde gode gamle dage\u201d var faktisk ikke s\u00e5 godt?", "de": "Was an den \u201eguten alten Zeiten\u201c war eigentlich nicht so gut?", "es": "\u00bfQu\u00e9 de \u201clos viejos tiempos\u201d en realidad no era tan bueno?", "pt": "O que dos \u201cbons velhos tempos\u201d afinal n\u00e3o era assim t\u00e3o bom?", "ro": "Ce era \u00een \u201evremurile bune de alt\u0103dat\u0103\u201d care de fapt nu era a\u0219a grozav?", "fr": "Qu\u2019est-ce qui, dans \u201cle bon vieux temps\u201d, n\u2019\u00e9tait pas si bien que \u00e7a ?", "it": "Qualcosa dei \"bei tempi andati\" che in realt\u00e0 non era poi cos\u00ec buono?", "fi": "Mik\u00e4 on jotain \"hyvist\u00e4 vanhoista p\u00e4ivist\u00e4\", joka ei oikeastaan ollut niin hyv\u00e4\u00e4?", "nl": "Wat is iets aan \"de goede oude tijd\" dat eigenlijk niet zo goed was?", "no": "Hva er noe med \"de gode gamle dager\" som faktisk ikke var s\u00e5 bra?", "sv": "Vad \u00e4r n\u00e5got om \"de goda gamla dagarna\" som faktiskt inte var s\u00e5 bra?", "pl": "Co\u015b, co w \"dawnych dobrych czasach\" nie by\u0142o a\u017c tak dobre?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something about “the good old days” that actually wasn’t so good?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people worried about back then that seems funny now?", "da": "Hvad bekymrede folk sig om dengang, som virker sjovt nu?", "de": "Worum haben sich die Leute damals Sorgen gemacht, was heute lustig erscheint?", "es": "\u00bfDe qu\u00e9 se preocupaba la gente antes que ahora parece gracioso?", "pt": "Com o que as pessoas se preocupavam antes e que agora parece engra\u00e7ado?", "ro": "De ce \u00ee\u0219i f\u0103ceau griji oamenii atunci, dar acum pare amuzant?", "fr": "De quoi les gens s\u2019inqui\u00e9taient-ils autrefois et qui para\u00eet dr\u00f4le aujourd\u2019hui ?", "it": "Qual \u00e8 qualcosa di cui le persone si preoccupavano all''epoca che ora sembra divertente?", "fi": "Mik\u00e4 on jotain, mist\u00e4 ihmiset olivat huolissaan silloin, mik\u00e4 tuntuu nyt hassulta?", "nl": "Wat is iets waar mensen zich toen zorgen over maakten dat nu grappig lijkt?", "no": "Hva er noe folk bekymret seg for den gang som virker morsomt n\u00e5?", "sv": "Vad \u00e4r n\u00e5got som folk oroade sig f\u00f6r d\u00e5 som verkar lustigt nu?", "pl": "Co\u015b, co ludzie si\u0119 wtedy martwili, a teraz wydaje si\u0119 zabawne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people worried about back then that seems funny now?';
UPDATE questions
SET translations = '{"en": "What\u2019s a rule your parents had that nobody follows anymore?", "da": "Hvad var en regel, dine for\u00e6ldre havde, som ingen f\u00f8lger mere?", "de": "Welche Regel hatten deine Eltern, die heute niemand mehr befolgt?", "es": "\u00bfQu\u00e9 regla ten\u00edan tus padres que ya nadie sigue?", "pt": "Que regra tinham os teus pais que j\u00e1 ningu\u00e9m segue?", "ro": "Ce regul\u0103 aveau p\u0103rin\u021bii t\u0103i pe care nimeni nu o mai respect\u0103 azi?", "fr": "Quelle r\u00e8gle tes parents avaient-ils que plus personne ne suit maintenant ?", "it": "Qual \u00e8 una regola che i tuoi genitori avevano e che nessuno segue pi\u00f9?", "fi": "Mik\u00e4 on s\u00e4\u00e4nt\u00f6, jonka vanhempasi asettivat, mutta jota kukaan ei en\u00e4\u00e4 noudata?", "nl": "Wat is een regel die je ouders hadden die niemand meer volgt?", "no": "Hva er en regel foreldrene dine hadde som ingen f\u00f8lger lenger?", "sv": "Vilken regel hade dina f\u00f6r\u00e4ldrar som ingen f\u00f6ljer l\u00e4ngre?", "pl": "Jakie zasady mieli twoi rodzice, kt\u00f3rych nikt ju\u017c nie przestrzega?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a rule your parents had that nobody follows anymore?';
UPDATE questions
SET translations = '{"en": "What\u2019s a piece of advice people said all the time when you were growing up?", "da": "Hvad var et r\u00e5d, folk altid sagde, da du voksede op?", "de": "Welchen Ratschlag haben die Leute st\u00e4ndig gegeben, als du aufgewachsen bist?", "es": "\u00bfQu\u00e9 consejo dec\u00eda la gente todo el tiempo cuando crec\u00edas?", "pt": "Que conselho as pessoas diziam sempre quando cresceste?", "ro": "Ce sfat spuneau oamenii mereu c\u00e2nd erai copil?", "fr": "Quel conseil les gens donnaient-ils tout le temps quand tu grandissais ?", "it": "Qual \u00e8 un consiglio che le persone dicevano sempre quando eri giovane?", "fi": "Mik\u00e4 on neuvo, jota ihmiset sanoivat koko ajan, kun kasvoit?", "nl": "Wat is een advies dat mensen vaak zeiden toen je opgroeide?", "no": "Hva er et r\u00e5d folk sa hele tiden da du vokste opp?", "sv": "Vilket r\u00e5d sa folk hela tiden n\u00e4r du v\u00e4xte upp?", "pl": "Jak\u0105 rad\u0119 ludzie cz\u0119sto powtarzali, gdy dorasta\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a piece of advice people said all the time when you were growing up?';