UPDATE questions
SET translations = '{"en": "\u201cFinancial freedom just means not caring what anyone else buys.\u201d", "da": "\u00d8konomisk frihed betyder bare ikke at g\u00e5 op i, hvad andre k\u00f8ber.", "de": "Finanzielle Freiheit bedeutet einfach, sich nicht darum zu k\u00fcmmern, was andere kaufen.", "es": "La libertad financiera solo significa no preocuparse por lo que compran los dem\u00e1s.", "pt": "Liberdade financeira significa apenas n\u00e3o se importar com o que os outros compram.", "ro": "Libertatea financiar\u0103 \u00eenseamn\u0103 doar s\u0103 nu-\u021bi pese de ce cump\u0103r\u0103 al\u021bii.", "fr": "La libert\u00e9 financi\u00e8re signifie simplement ne pas se soucier de ce que les autres ach\u00e8tent.", "it": "\"La libert\u00e0 finanziaria significa semplicemente non preoccuparsi di ci\u00f2 che comprano gli altri.\"", "fi": "\"Taloudellinen vapaus tarkoittaa vain sit\u00e4, ettei v\u00e4lit\u00e4 siit\u00e4, mit\u00e4 muut ostavat.\"", "nl": "\"Financi\u00eble vrijheid betekent gewoon dat je je niet druk maakt om wat anderen kopen.\"", "no": "\u201c\u00d8konomisk frihet betyr bare at man ikke bryr seg om hva andre kj\u00f8per.\u201d", "sv": "\"Ekonomisk frihet betyder bara att man inte bryr sig om vad andra k\u00f6per.\"", "pl": "\u201eWolno\u015b\u0107 finansowa oznacza po prostu, \u017ce nie obchodzi ci\u0119, co kupuj\u0105 inni.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Financial freedom just means not caring what anyone else buys.”';
UPDATE questions
SET translations = '{"en": "\u201cCancel culture does more harm than good.\u201d", "da": "Cancel culture g\u00f8r mere skade end gavn.", "de": "Cancel Culture richtet mehr Schaden als Nutzen an.", "es": "La cultura de la cancelaci\u00f3n hace m\u00e1s da\u00f1o que bien.", "pt": "A cultura do cancelamento faz mais mal do que bem.", "ro": "Cultura anul\u0103rii face mai mult r\u0103u dec\u00e2t bine.", "fr": "La culture de l\u2019annulation fait plus de mal que de bien.", "it": "\"La cultura della cancellazione fa pi\u00f9 male che bene.\"", "fi": "\"Peruutuskulttuuri tekee enemm\u00e4n haittaa kuin hy\u00f6ty\u00e4.\"", "nl": "\"Cancelcultuur doet meer kwaad dan goed.\"", "no": "\u201cAvbestillingskultur gj\u00f8r mer skade enn nytte.\u201d", "sv": "\"Cancelkultur g\u00f6r mer skada \u00e4n nytta.\"", "pl": "\u201eKultura anulowania przynosi wi\u0119cej szkody ni\u017c po\u017cytku.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Cancel culture does more harm than good.”';
UPDATE questions
SET translations = '{"en": "\"Dating apps make people feel more disposable, not more connected\"", "da": "Datingapps f\u00e5r folk til at f\u00f8le sig mere udskiftelige, ikke mere forbundet.", "de": "Dating-Apps lassen Menschen sich eher austauschbar f\u00fchlen, nicht verbundener.", "es": "Las apps de citas hacen que la gente se sienta m\u00e1s desechable, no m\u00e1s conectada.", "pt": "As apps de encontros fazem as pessoas sentirem-se mais descart\u00e1veis, n\u00e3o mais ligadas.", "ro": "Aplica\u021biile de dating \u00eei fac pe oameni s\u0103 se simt\u0103 mai de \u201earuncat\u201d, nu mai conecta\u021bi.", "fr": "Les applis de rencontre donnent aux gens l\u2019impression d\u2019\u00eatre plus jetables, pas plus connect\u00e9s.", "it": "\"Le app di incontri fanno sentire le persone pi\u00f9 usa e getta, non pi\u00f9 connesse.\"", "fi": "\"Deittisovellukset saavat ihmiset tuntemaan itsens\u00e4 enemm\u00e4n k\u00e4ytett\u00e4vilt\u00e4, eiv\u00e4tk\u00e4 he tunne itse\u00e4\u00e4n enemm\u00e4n yhteyteen.\"", "nl": "\"Datingapps zorgen ervoor dat mensen zich meer wegwerpbaar voelen, niet meer verbonden.\"", "no": "\"Datingapper f\u00e5r folk til \u00e5 f\u00f8le seg mer utbyttbare, ikke mer tilknyttede.\"", "sv": "\"Datingappar f\u00e5r m\u00e4nniskor att k\u00e4nna sig mer utbytbara, inte mer kopplade.\"", "pl": "\"Aplikacje randkowe sprawiaj\u0105, \u017ce ludzie czuj\u0105 si\u0119 bardziej jednorazowi, a nie bardziej po\u0142\u0105czeni.\""}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '"Dating apps make people feel more disposable, not more connected"';
UPDATE questions
SET translations = '{"en": "\u201cVacations are more stressful than staying home.\u201d", "da": "Ferier er mere stressende end at blive hjemme.", "de": "Urlaube sind stressiger als zu Hause zu bleiben.", "es": "Las vacaciones son m\u00e1s estresantes que quedarse en casa.", "pt": "As f\u00e9rias s\u00e3o mais stressantes do que ficar em casa.", "ro": "Vacan\u021bele sunt mai stresante dec\u00e2t s\u0103 stai acas\u0103.", "fr": "Les vacances sont plus stressantes que de rester chez soi.", "it": "\"Le vacanze sono pi\u00f9 stressanti che restare a casa.\"", "fi": "\"Lomat ovat stressaavampia kuin kotona oleminen.\"", "nl": "\"Vakanties zijn stressvoller dan thuisblijven.\"", "no": "\"Ferier er mer stressende enn \u00e5 v\u00e6re hjemme.\"", "sv": "\"Semestrar \u00e4r mer stressande \u00e4n att stanna hemma.\"", "pl": "\u201eWakacje s\u0105 bardziej stresuj\u0105ce ni\u017c zostanie w domu.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Vacations are more stressful than staying home.”';
UPDATE questions
SET translations = '{"en": "\u201cNatural beauty\u2019 is just a privilege when you can afford it.\u201d", "da": "\u201cNaturlig sk\u00f8nhed\u201d er bare et privilegium, n\u00e5r man har r\u00e5d til det.", "de": "\u201eNat\u00fcrliche Sch\u00f6nheit\u201c ist nur ein Privileg, wenn man es sich leisten kann.", "es": "La \u201cbelleza natural\u201d es solo un privilegio cuando puedes permit\u00edrtelo.", "pt": "\u201cBeleza natural\u201d \u00e9 apenas um privil\u00e9gio quando se pode pagar por isso.", "ro": "\u201eFrumuse\u021bea natural\u0103\u201d este doar un privilegiu atunci c\u00e2nd \u021bi-o permi\u021bi.", "fr": "La \u201cbeaut\u00e9 naturelle\u201d n\u2019est qu\u2019un privil\u00e8ge quand on peut se le permettre.", "it": "\"La ''bellezza naturale'' \u00e8 solo un privilegio quando te lo puoi permettere.\"", "fi": "\"Luonnonkauneus\" on vain etuoikeus, kun siihen on varaa.", "nl": "\"Natuurlijke schoonheid is gewoon een privilege als je het je kunt veroorloven.\"", "no": "\u201cNaturlig skj\u00f8nnhet er bare et privilegium n\u00e5r du har r\u00e5d til det.\u201d", "sv": "\"Naturlig sk\u00f6nhet \u00e4r bara en privilegium n\u00e4r man har r\u00e5d med det.\"", "pl": "\u201eNaturalne pi\u0119kno to tylko przywilej, gdy mo\u017cesz sobie na to pozwoli\u0107.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Natural beauty’ is just a privilege when you can afford it.”';
UPDATE questions
SET translations = '{"en": "\u201cFreedom of speech should have stronger limits when speech is harmful.\u201d", "da": "Ytringsfrihed b\u00f8r have st\u00e6rkere gr\u00e6nser, n\u00e5r talen er skadelig.", "de": "Meinungsfreiheit sollte st\u00e4rkere Grenzen haben, wenn die Rede sch\u00e4dlich ist.", "es": "La libertad de expresi\u00f3n deber\u00eda tener l\u00edmites m\u00e1s fuertes cuando el discurso es da\u00f1ino.", "pt": "A liberdade de express\u00e3o deve ter limites mais fortes quando o discurso \u00e9 prejudicial.", "ro": "Libertatea de exprimare ar trebui s\u0103 aib\u0103 limite mai stricte atunci c\u00e2nd vorbirea este d\u0103un\u0103toare.", "fr": "La libert\u00e9 d\u2019expression devrait avoir des limites plus strictes lorsque les propos sont nuisibles.", "it": "\"La libert\u00e0 di espressione dovrebbe avere limiti pi\u00f9 severi quando l''espressione \u00e8 dannosa.\"", "fi": "\"Vapaa sanaa tulisi rajoittaa voimakkaammin, kun puhe on vahingollista.\"", "nl": "\"Vrijheid van meningsuiting zou strengere grenzen moeten hebben wanneer de uiting schadelijk is.\"", "no": "\u00abYtringsfrihet b\u00f8r ha sterkere grenser n\u00e5r ytringer er skadelige.\u00bb", "sv": "\"Yttrandefrihet b\u00f6r ha starkare begr\u00e4nsningar n\u00e4r yttrandet \u00e4r skadligt.\"", "pl": "\u201eWolno\u015b\u0107 s\u0142owa powinna mie\u0107 silniejsze ograniczenia, gdy mowa jest szkodliwa.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Freedom of speech should have stronger limits when speech is harmful.”';
UPDATE questions
SET translations = '{"en": "\u201cTipping culture has gotten out of control.\u201d", "da": "Drikkepengekulturen er l\u00f8bet l\u00f8bsk.", "de": "Die Trinkgeldkultur ist au\u00dfer Kontrolle geraten.", "es": "La cultura de las propinas se ha salido de control.", "pt": "A cultura das gorjetas saiu do controlo.", "ro": "Cultura bac\u0219i\u0219urilor a sc\u0103pat de sub control.", "fr": "La culture du pourboire est devenue incontr\u00f4lable.", "it": "\"La cultura della mancia \u00e8 diventata incontrollabile.\"", "fi": "\"Juomaraha-kulttuuri on mennyt t\u00e4ysin hallitsemattomaksi.\"", "nl": "\"De foorkultuur is uit de hand gelopen.\"", "no": "\u201cTipskulturen har blitt ute av kontroll.\u201d", "sv": "\"Dricks-kulturen har blivit helt galen.\"", "pl": "\u201eKultura dawania napiwk\u00f3w wymkn\u0119\u0142a si\u0119 spod kontroli.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tipping culture has gotten out of control.”';
UPDATE questions
SET translations = '{"en": "\u201cInfluencers have too much cultural power for no accountability.\u201d", "da": "Influencere har for meget kulturel magt uden ansvar.", "de": "Influencer haben zu viel kulturelle Macht ohne Verantwortung.", "es": "Los influencers tienen demasiado poder cultural sin responsabilidad.", "pt": "Os influenciadores t\u00eam demasiado poder cultural sem responsabilidade.", "ro": "Influencerii au prea mult\u0103 putere cultural\u0103 f\u0103r\u0103 responsabilitate.", "fr": "Les influenceurs ont trop de pouvoir culturel sans responsabilit\u00e9.", "it": "\"Gli influencer hanno troppo potere culturale senza alcuna responsabilit\u00e0.\"", "fi": "\u201dVaikuttajilla on liian paljon kulttuurista valtaa ilman vastuuta.\u201d", "nl": "\"Invloeders hebben te veel culturele macht zonder enige verantwoording.\"", "no": "\u00abInfluensere har for mye kulturell makt uten ansvarlighet.\u00bb", "sv": "\"Influencers har f\u00f6r mycket kulturell makt utan ansvar.\"", "pl": "\u201eInfluencerzy maj\u0105 zbyt du\u017c\u0105 w\u0142adz\u0119 kulturow\u0105 bez \u017cadnej odpowiedzialno\u015bci.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Influencers have too much cultural power for no accountability.”';
UPDATE questions
SET translations = '{"en": "\u201cGood grades don\u2019t guarantee success, and bad grades don\u2019t guarantee failure.\u201d", "da": "Gode karakterer garanterer ikke succes, og d\u00e5rlige karakterer garanterer ikke fiasko.", "de": "Gute Noten garantieren keinen Erfolg, und schlechte Noten garantieren kein Scheitern.", "es": "Las buenas notas no garantizan el \u00e9xito, y las malas notas no garantizan el fracaso.", "pt": "Boas notas n\u00e3o garantem sucesso, e m\u00e1s notas n\u00e3o garantem fracasso.", "ro": "Notele bune nu garanteaz\u0103 succesul, iar notele proaste nu garanteaz\u0103 e\u0219ecul.", "fr": "Les bonnes notes ne garantissent pas la r\u00e9ussite, et les mauvaises notes ne garantissent pas l\u2019\u00e9chec.", "it": "\"Buoni voti non garantiscono il successo, e cattivi voti non garantiscono il fallimento.\"", "fi": "\u201dHyv\u00e4t arvosanat eiv\u00e4t takaa menestyst\u00e4, eik\u00e4 huonot arvosanat takaa ep\u00e4onnistumista.\u201d", "nl": "\"Goede cijfers garanderen geen succes, en slechte cijfers garanderen geen falen.\"", "no": "\"Gode karakterer garanterer ikke suksess, og d\u00e5rlige karakterer garanterer ikke fiasko.\"", "sv": "\"Bra betyg garanterar inte framg\u00e5ng, och d\u00e5liga betyg garanterar inte misslyckande.\"", "pl": "\u201eDobre oceny nie gwarantuj\u0105 sukcesu, a z\u0142e oceny nie gwarantuj\u0105 pora\u017cki.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Good grades don’t guarantee success, and bad grades don’t guarantee failure.”';
UPDATE questions
SET translations = '{"en": "\u201cAI-generated art and music should get royalty rights if they\u2019re based on human work.\u201d", "da": "AI-genereret kunst og musik b\u00f8r f\u00e5 royalties, hvis de er baseret p\u00e5 menneskeligt arbejde.", "de": "KI-generierte Kunst und Musik sollten Tantiemen erhalten, wenn sie auf menschlicher Arbeit basieren.", "es": "El arte y la m\u00fasica generados por IA deber\u00edan recibir regal\u00edas si se basan en trabajo humano.", "pt": "A arte e a m\u00fasica geradas por IA devem receber direitos autorais se forem baseadas em trabalho humano.", "ro": "Arta \u0219i muzica generate de AI ar trebui s\u0103 primeasc\u0103 drepturi de autor dac\u0103 se bazeaz\u0103 pe munc\u0103 uman\u0103.", "fr": "L\u2019art et la musique g\u00e9n\u00e9r\u00e9s par l\u2019IA devraient recevoir des droits d\u2019auteur s\u2019ils reposent sur un travail humain.", "it": "\u201cL''arte e la musica generate dall''IA dovrebbero avere diritti d''autore se si basano su opere umane.\u201d", "fi": "\"AI:n tuottamalle taiteelle ja musiikille tulisi my\u00f6nt\u00e4\u00e4 tekij\u00e4noikeudet, jos ne perustuvat ihmisty\u00f6h\u00f6n.\"", "nl": "\"AI-gegenereerde kunst en muziek zouden royaltyrechten moeten krijgen als ze gebaseerd zijn op menselijk werk.\"", "no": "\u00abAI-generert kunst og musikk b\u00f8r f\u00e5 royaltyrettigheter hvis de er basert p\u00e5 menneskelig arbeid.\u00bb", "sv": "\"AI-genererad konst och musik b\u00f6r f\u00e5 upphovsr\u00e4tt om de \u00e4r baserade p\u00e5 m\u00e4nskligt arbete.\"", "pl": "\u201eSztuka i muzyka generowane przez AI powinny mie\u0107 prawa autorskie, je\u015bli s\u0105 oparte na ludzkiej pracy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“AI-generated art and music should get royalty rights if they’re based on human work.”';