UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to accidentally text the wrong person something dramatic?", "da": "Hvem er mest tilb\u00f8jelig til ved et uheld at sende en dramatisk besked til den forkerte person?", "de": "Wer wird am ehesten versehentlich eine dramatische Nachricht an die falsche Person senden?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que env\u00ede por error un mensaje dram\u00e1tico a la persona equivocada?", "pt": "Quem \u00e9 mais prov\u00e1vel de enviar por engano uma mensagem dram\u00e1tica \u00e0 pessoa errada?", "ro": "Cine e cel mai probabil s\u0103 trimit\u0103 din gre\u0219eal\u0103 un mesaj dramatic persoanei gre\u0219ite?", "fr": "Qui est le plus susceptible d\u2019envoyer par erreur un message dramatique \u00e0 la mauvaise personne ?", "it": "Chi \u00e8 pi\u00f9 probabile che invii per sbaglio un messaggio drammatico alla persona sbagliata?", "fi": "Kuka todenn\u00e4k\u00f6isimmin l\u00e4hett\u00e4\u00e4 vahingossa dramaattisen viestin v\u00e4\u00e4r\u00e4lle henkil\u00f6lle?", "nl": "Wie is het meest waarschijnlijk om per ongeluk iets dramatisch naar de verkeerde persoon te sms''en?", "no": "Hvem er mest sannsynlig til \u00e5 sende en dramatisk melding til feil person ved et uhell?", "sv": "Vem \u00e4r mest ben\u00e4gen att av misstag skicka ett dramatiskt meddelande till fel person?", "pl": "Kto najprawdopodobniej przypadkowo wy\u015ble co\u015b dramatycznego do niew\u0142a\u015bciwej osoby?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who’s most likely to accidentally text the wrong person something dramatic?';
UPDATE questions
SET translations = '{"en": "Who would you call if you needed to hide something \u2014 and who would absolutely snitch?", "da": "Hvem ville du ringe til, hvis du havde brug for at skjule noget \u2014 og hvem ville helt sikkert sladre?", "de": "Wen w\u00fcrdest du anrufen, wenn du etwas verstecken m\u00fcsstest \u2013 und wer w\u00fcrde auf jeden Fall petzen?", "es": "\u00bfA qui\u00e9n llamar\u00edas si necesitaras esconder algo \u2014 y qui\u00e9n absolutamente delatar\u00eda?", "pt": "A quem ligarias se precisasses esconder algo \u2014 e quem contaria tudo?", "ro": "Pe cine ai suna dac\u0103 ai avea nevoie s\u0103 ascunzi ceva \u2014 \u0219i cine ar spune sigur?", "fr": "Qui appellerais-tu si tu devais cacher quelque chose \u2014 et qui trahirait s\u00fbrement ?", "it": "Chi chiameresti se avessi bisogno di nascondere qualcosa \u2014 e chi sicuramente farebbe la spia?", "fi": "Kene\u00e4 soittaisit, jos sinun pit\u00e4isi piilottaa jotain \u2014 ja kuka varmasti kertoisi siit\u00e4 eteenp\u00e4in?", "nl": "Wie zou je bellen als je iets moest verbergen \u2014 en wie zou absoluut verklikken?", "no": "Hvem ville du ringe til hvis du trengte \u00e5 skjule noe \u2014 og hvem ville absolutt sladre?", "sv": "Vem skulle du ringa om du beh\u00f6vde g\u00f6mma n\u00e5got \u2014 och vem skulle absolut skvallra?", "pl": "Kogo by\u015b zadzwoni\u0142, gdyby\u015b musia\u0142 co\u015b ukry\u0107 \u2014 a kto na pewno by doni\u00f3s\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would you call if you needed to hide something — and who would absolutely snitch?';
UPDATE questions
SET translations = '{"en": "You have to give one of us your phone for an hour. Who\u2019s least likely to ruin your life?", "da": "Du skal give en af os din telefon i en time. Hvem er mindst tilb\u00f8jelig til at \u00f8del\u00e6gge dit liv?", "de": "Du musst einem von uns dein Handy f\u00fcr eine Stunde geben. Wer w\u00fcrde dein Leben am wenigsten ruinieren?", "es": "Tienes que darle tu tel\u00e9fono a uno de nosotros por una hora. \u00bfQui\u00e9n es menos probable que arruine tu vida?", "pt": "Tens de dar o teu telem\u00f3vel a um de n\u00f3s por uma hora. Quem \u00e9 menos prov\u00e1vel de arruinar a tua vida?", "ro": "Trebuie s\u0103-i dai telefonul t\u0103u unuia dintre noi pentru o or\u0103. Cine are cele mai mici \u0219anse s\u0103-\u021bi strice via\u021ba?", "fr": "Tu dois donner ton t\u00e9l\u00e9phone \u00e0 l\u2019un de nous pour une heure. Qui est le moins susceptible de ruiner ta vie ?", "it": "Devi dare il tuo telefono a uno di noi per un''ora. Chi \u00e8 il meno probabile che rovini la tua vita?", "fi": "Kenen teist\u00e4 pit\u00e4isi saada puhelimensa k\u00e4ytt\u00f6\u00f6n tunniksi? Kuka on v\u00e4hiten todenn\u00e4k\u00f6inen pilaamaan el\u00e4m\u00e4\u00e4si?", "nl": "Je moet een van ons je telefoon voor een uur geven. Wie is het minst waarschijnlijk om je leven te verwoesten?", "no": "Du m\u00e5 gi en av oss telefonen din i en time. Hvem er minst sannsynlig til \u00e5 \u00f8delegge livet ditt?", "sv": "Du m\u00e5ste ge en av oss din telefon i en timme. Vem \u00e4r minst sannolikt att f\u00f6rst\u00f6ra ditt liv?", "pl": "Musisz da\u0107 jednemu z nas sw\u00f3j telefon na godzin\u0119. Kto jest najmniej prawdopodobny, \u017ceby zrujnowa\u0107 ci \u017cycie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You have to give one of us your phone for an hour. Who’s least likely to ruin your life?';
UPDATE questions
SET translations = '{"en": "You find out two of your close friends were hanging out without inviting you \u2014 what\u2019s your honest reaction?", "da": "Du finder ud af, at to af dine t\u00e6tte venner hang ud uden dig \u2014 hvad er din \u00e6rlige reaktion?", "de": "Du findest heraus, dass zwei deiner engen Freunde ohne dich abgehangen haben \u2013 was ist deine ehrliche Reaktion?", "es": "Descubres que dos de tus amigos cercanos salieron sin ti \u2014 \u00bfcu\u00e1l es tu reacci\u00f3n honesta?", "pt": "Descobres que dois dos teus amigos pr\u00f3ximos sa\u00edram sem ti \u2014 qual \u00e9 a tua rea\u00e7\u00e3o honesta?", "ro": "Afl\u0103 c\u0103 doi dintre prietenii t\u0103i apropia\u021bi s-au \u00eent\u00e2lnit f\u0103r\u0103 tine \u2014 care e reac\u021bia ta sincer\u0103?", "fr": "Tu d\u00e9couvres que deux de tes amis proches sont sortis sans toi \u2014 quelle est ta r\u00e9action honn\u00eate ?", "it": "Scopri che due dei tuoi amici pi\u00f9 stretti si sono incontrati senza invitarti \u2014 qual \u00e8 la tua reazione onesta?", "fi": "Saat tiet\u00e4\u00e4, ett\u00e4 kaksi l\u00e4heist\u00e4 yst\u00e4v\u00e4\u00e4si vietti aikaa yhdess\u00e4 ilman, ett\u00e4 kutsuivat sinua \u2014 mik\u00e4 on rehellinen reaktiosi?", "nl": "Je ontdekt dat twee van je goede vrienden samen waren zonder jou uit te nodigen \u2014 wat is je eerlijke reactie?", "no": "Du finner ut at to av dine n\u00e6re venner hang ut uten \u00e5 invitere deg \u2014 hva er din \u00e6rlige reaksjon?", "sv": "Du f\u00e5r reda p\u00e5 att tv\u00e5 av dina n\u00e4ra v\u00e4nner h\u00e4ngde med varandra utan att bjuda in dig \u2014 vad \u00e4r din \u00e4rliga reaktion?", "pl": "Dowiadujesz si\u0119, \u017ce dw\u00f3ch twoich bliskich przyjaci\u00f3\u0142 sp\u0119dza\u0142o czas razem, nie zapraszaj\u0105c ci\u0119 \u2014 jaka jest twoja szczera reakcja?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You find out two of your close friends were hanging out without inviting you — what’s your honest reaction?';
UPDATE questions
SET translations = '{"en": "Who in this room would handle a breakup the most dramatically?", "da": "Hvem her ville h\u00e5ndtere et brud mest dramatisk?", "de": "Wer hier w\u00fcrde eine Trennung am dramatischsten verarbeiten?", "es": "\u00bfQui\u00e9n aqu\u00ed manejar\u00eda una ruptura de la forma m\u00e1s dram\u00e1tica?", "pt": "Quem aqui lidaria com uma separa\u00e7\u00e3o da forma mais dram\u00e1tica?", "ro": "Cine de aici ar reac\u021biona cel mai dramatic la o desp\u0103r\u021bire?", "fr": "Qui ici vivrait une rupture de la mani\u00e8re la plus dramatique ?", "it": "Chi in questa stanza gestirebbe una rottura in modo pi\u00f9 drammatico?", "fi": "Kuka t\u00e4ss\u00e4 huoneessa k\u00e4sittelisi eron kaikkein dramaattisimmin?", "nl": "Wie in deze kamer zou een breakup het meest dramatisch verwerken?", "no": "Hvem i dette rommet ville h\u00e5ndtert et brudd mest dramatisk?", "sv": "Vem i det h\u00e4r rummet skulle hantera en breakup mest dramatiskt?", "pl": "Kto w tym pomieszczeniu najdramaturgiczniej poradzi\u0142by sobie z rozstaniem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who in this room would handle a breakup the most dramatically?';
UPDATE questions
SET translations = '{"en": "Who do you think has the most secrets no one knows about?", "da": "Hvem tror du har flest hemmeligheder, som ingen kender til?", "de": "Wer, glaubst du, hat die meisten Geheimnisse, von denen niemand wei\u00df?", "es": "\u00bfQui\u00e9n crees que tiene m\u00e1s secretos que nadie conoce?", "pt": "Quem achas que tem mais segredos que ningu\u00e9m sabe?", "ro": "Cine crezi c\u0103 are cele mai multe secrete pe care nimeni nu le \u0219tie?", "fr": "Qui, selon toi, a le plus de secrets que personne ne conna\u00eet ?", "it": "Chi pensi abbia i pi\u00f9 segreti che nessuno conosce?", "fi": "Kuka mielest\u00e4si on se, jolla on eniten salaisuuksia, joista kukaan ei tied\u00e4?", "nl": "Wie denk je dat de meeste geheimen heeft die niemand weet?", "no": "Hvem tror du har de fleste hemmelighetene ingen vet om?", "sv": "Vem tror du har flest hemligheter som ingen k\u00e4nner till?", "pl": "Kto twoim zdaniem ma najwi\u0119cej sekret\u00f3w, o kt\u00f3rych nikt nie wie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who do you think has the most secrets no one knows about?';
UPDATE questions
SET translations = '{"en": "If you could upgrade one friend\u2019s personality trait and downgrade another, who and what would it be?", "da": "Hvis du kunne opgradere \u00e9n vens personlighedstr\u00e6k og nedgradere en anden, hvem og hvad ville det v\u00e6re?", "de": "Wenn du ein Pers\u00f6nlichkeitsmerkmal eines Freundes verbessern und ein anderes verschlechtern k\u00f6nntest, wer und was w\u00e4re das?", "es": "Si pudieras mejorar un rasgo de personalidad de un amigo y empeorar otro, \u00bfqui\u00e9n y cu\u00e1l ser\u00eda?", "pt": "Se pudesses melhorar um tra\u00e7o de personalidade de um amigo e piorar outro, quem e qual seria?", "ro": "Dac\u0103 ai putea \u00eembun\u0103t\u0103\u021bi un atribut al unui prieten \u0219i \u00eenr\u0103ut\u0103\u021bi altul, cine \u0219i care ar fi?", "fr": "Si tu pouvais am\u00e9liorer un trait de personnalit\u00e9 d\u2019un ami et en affaiblir un autre, qui et lequel choisirais-tu ?", "it": "Se potessi migliorare un tratto della personalit\u00e0 di un amico e peggiorarne un altro, chi e quale sarebbe?", "fi": "Jos voisit parantaa yhden yst\u00e4v\u00e4si luonteenpiirteen ja heikent\u00e4\u00e4 toisen, kuka ja mik\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n persoonlijkheidskenmerk van een vriend zou kunnen verbeteren en dat van een ander zou kunnen verslechteren, wie en wat zou het zijn?", "no": "Hvis du kunne oppgradere en venns personlighetstrekk og nedgradere et annet, hvem ville det v\u00e6rt og hva ville det v\u00e6rt?", "sv": "Om du kunde uppgradera en v\u00e4ns personlighetsegenskap och nedgradera en annan, vem skulle det vara och vad skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 poprawi\u0107 jedn\u0105 cech\u0119 osobowo\u015bci przyjaciela, a obni\u017cy\u0107 inn\u0105 u innego, kogo by\u015b wybra\u0142 i co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If you could upgrade one friend’s personality trait and downgrade another, who and what would it be?';
UPDATE questions
SET translations = '{"en": "You\u2019re given the power to erase one embarrassing moment for a friend \u2014 whose would you erase?", "da": "Du f\u00e5r magten til at slette \u00e9t pinligt \u00f8jeblik for en ven \u2014 hvis ville du slette?", "de": "Du hast die Macht, einen peinlichen Moment eines Freundes zu l\u00f6schen \u2013 wessen w\u00fcrdest du l\u00f6schen?", "es": "Tienes el poder de borrar un momento vergonzoso de un amigo \u2014 \u00bfcu\u00e1l borrar\u00edas?", "pt": "Tens o poder de apagar um momento embara\u00e7oso de um amigo \u2014 qual apagarias?", "ro": "Ai puterea s\u0103 \u0219tergi un moment jenant al unui prieten \u2014 pe al cui l-ai \u0219terge?", "fr": "Tu as le pouvoir d\u2019effacer un moment embarrassant d\u2019un ami \u2014 lequel effacerais-tu ?", "it": "Ti \u00e8 data la possibilit\u00e0 di cancellare un momento imbarazzante per un amico \u2014 quale cancelleresti?", "fi": "Sinulle annetaan valta pyyhki\u00e4 yksi nolostuttava hetki yst\u00e4v\u00e4lt\u00e4si \u2014 mink\u00e4 hetken pyyhkisit?", "nl": "Je krijgt de macht om \u00e9\u00e9n g\u00eanant moment voor een vriend te wissen \u2014 wiens zou je wissen?", "no": "Du f\u00e5r makten til \u00e5 slette ett pinlig \u00f8yeblikk for en venn \u2014 hvilket ville du slette?", "sv": "Du f\u00e5r makten att radera ett pinsamt \u00f6gonblick f\u00f6r en v\u00e4n \u2014 vilket skulle du radera?", "pl": "Dostajesz moc, aby wymaza\u0107 jeden wstydliwy moment dla przyjaciela \u2014 kt\u00f3ry by\u015b wymaza\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You’re given the power to erase one embarrassing moment for a friend — whose would you erase?';
UPDATE questions
SET translations = '{"en": "You can only keep one: the friend who always shows up late, or the one who always cancels last minute?", "da": "Du kan kun beholde \u00e9n: vennen der altid kommer for sent, eller den der altid aflyser i sidste \u00f8jeblik?", "de": "Du kannst nur einen behalten: den Freund, der immer zu sp\u00e4t kommt, oder den, der immer im letzten Moment absagt?", "es": "Solo puedes quedarte con uno: \u00bfel amigo que siempre llega tarde o el que siempre cancela a \u00faltimo momento?", "pt": "S\u00f3 podes ficar com um: o amigo que est\u00e1 sempre atrasado ou o que cancela \u00e0 \u00faltima hora?", "ro": "Po\u021bi p\u0103stra doar unul: prietenul care \u00eent\u00e2rzie mereu sau cel care anuleaz\u0103 \u00een ultimul moment?", "fr": "Tu ne peux en garder qu\u2019un : celui qui est toujours en retard ou celui qui annule toujours \u00e0 la derni\u00e8re minute ?", "it": "Puoi tenere solo uno: l''amico che arriva sempre in ritardo, o quello che cancella sempre all''ultimo minuto?", "fi": "Voit pit\u00e4\u00e4 vain yhden: yst\u00e4v\u00e4n, joka aina saapuu my\u00f6h\u00e4ss\u00e4, vai sen, joka aina peruu viime hetkell\u00e4?", "nl": "Je mag er maar \u00e9\u00e9n houden: de vriend die altijd te laat komt, of degene die altijd op het laatste moment afzegt?", "no": "Du kan bare beholde \u00e9n: vennen som alltid kommer for sent, eller den som alltid avlyser i siste liten?", "sv": "Du kan bara beh\u00e5lla en: v\u00e4nnen som alltid kommer f\u00f6r sent, eller den som alltid avbokar i sista minuten?", "pl": "Mo\u017cesz zatrzyma\u0107 tylko jednego: przyjaciela, kt\u00f3ry zawsze si\u0119 sp\u00f3\u017ania, czy tego, kt\u00f3ry zawsze odwo\u0142uje w ostatniej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You can only keep one: the friend who always shows up late, or the one who always cancels last minute?';
UPDATE questions
SET translations = '{"en": "You find out your friend has been lying about something small for years \u2014 what do you do?", "da": "Du finder ud af, at din ven har l\u00f8jet om noget sm\u00e5t i \u00e5revis \u2014 hvad g\u00f8r du?", "de": "Du erf\u00e4hrst, dass dein Freund jahrelang \u00fcber etwas Kleines gelogen hat \u2013 was tust du?", "es": "Descubres que tu amigo ha estado mintiendo sobre algo peque\u00f1o durante a\u00f1os \u2014 \u00bfqu\u00e9 haces?", "pt": "Descobres que o teu amigo mentiu sobre algo pequeno durante anos \u2014 o que fazes?", "ro": "Afl\u0103 c\u0103 prietenul t\u0103u a min\u021bit ani de zile despre ceva mic \u2014 ce faci?", "fr": "Tu d\u00e9couvres que ton ami ment depuis des ann\u00e9es sur un petit d\u00e9tail \u2014 que fais-tu ?", "it": "Scopri che il tuo amico ha mentito su qualcosa di piccolo per anni \u2014 cosa fai?", "fi": "Saat tiet\u00e4\u00e4, ett\u00e4 yst\u00e4v\u00e4si on valehdellut jostain pienest\u00e4 jo vuosia \u2014 mit\u00e4 teet?", "nl": "Je ontdekt dat je vriend al jaren over iets kleins liegt \u2014 wat doe je?", "no": "Du finner ut at vennen din har l\u00f8yet om noe lite i flere \u00e5r \u2014 hva gj\u00f8r du?", "sv": "Du f\u00e5r reda p\u00e5 att din v\u00e4n har ljugit om n\u00e5got litet i flera \u00e5r \u2013 vad g\u00f6r du?", "pl": "Dowiadujesz si\u0119, \u017ce tw\u00f3j przyjaciel k\u0142ama\u0142 o czym\u015b ma\u0142ym przez lata \u2014 co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You find out your friend has been lying about something small for years — what do you do?';