UPDATE questions
SET translations = '{"en": "How important is it to you that a gift feels personal or symbolic?", "da": "Hvor vigtigt er det for dig, at en gave f\u00f8les personlig eller symbolsk?", "de": "Wie wichtig ist es dir, dass ein Geschenk pers\u00f6nlich oder symbolisch wirkt?", "es": "\u00bfQu\u00e9 tan importante es para ti que un regalo se sienta personal o simb\u00f3lico?", "pt": "Qu\u00e3o importante \u00e9 para ti que um presente pare\u00e7a pessoal ou simb\u00f3lico?", "ro": "C\u00e2t de important este pentru tine ca un cadou s\u0103 fie personal sau simbolic?", "fr": "Quelle importance accordes-tu au fait qu\u2019un cadeau soit personnel ou symbolique ?", "it": "Quanto \u00e8 importante per te che un regalo sembri personale o simbolico?", "fi": "Kuinka t\u00e4rke\u00e4\u00e4 sinulle on, ett\u00e4 lahja tuntuu henkil\u00f6kohtaiselta tai symboliselta?", "nl": "Hoe belangrijk is het voor jou dat een cadeau persoonlijk of symbolisch aanvoelt?", "no": "Hvor viktig er det for deg at en gave f\u00f8les personlig eller symbolsk?", "sv": "Hur viktigt \u00e4r det f\u00f6r dig att en present k\u00e4nns personlig eller symbolisk?", "pl": "Jak wa\u017cne jest dla Ciebie, aby prezent by\u0142 osobisty lub symboliczny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How important is it to you that a gift feels personal or symbolic?';UPDATE questions
SET translations = '{"en": "What\u2019s a small token from me that would make you smile every time you saw it?", "da": "Hvilken lille ting fra mig ville f\u00e5 dig til at smile hver gang du s\u00e5 den?", "de": "Welches kleine Andenken von mir w\u00fcrde dich jedes Mal zum L\u00e4cheln bringen, wenn du es siehst?", "es": "\u00bfQu\u00e9 peque\u00f1o detalle m\u00edo te har\u00eda sonre\u00edr cada vez que lo vieras?", "pt": "Que pequeno gesto meu te faria sorrir sempre que o visses?", "ro": "Ce mic simbol de la mine te-ar face s\u0103 z\u00e2mbe\u0219ti de fiecare dat\u0103 c\u00e2nd l-ai vedea?", "fr": "Quel petit souvenir de moi te ferait sourire chaque fois que tu le verrais ?", "it": "Qual \u00e8 un piccolo regalo da parte mia che ti farebbe sorridere ogni volta che lo vedessi?", "fi": "Mik\u00e4 olisi pieni muistoesine minulta, joka saisi sinut hymyilem\u00e4\u00e4n joka kerta, kun n\u00e4kisit sen?", "nl": "Wat is een klein aandenken van mij dat je elke keer zou laten glimlachen als je het zag?", "no": "Hva er en liten gave fra meg som ville f\u00e5tt deg til \u00e5 smile hver gang du s\u00e5 den?", "sv": "Vad \u00e4r en liten g\u00e5va fr\u00e5n mig som skulle f\u00e5 dig att le varje g\u00e5ng du s\u00e5g den?", "pl": "Jaki ma\u0142y upominek ode mnie sprawi\u0142by, \u017ce za ka\u017cdym razem, gdy na niego spojrzysz, u\u015bmiechniesz si\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s a small token from me that would make you smile every time you saw it?';
UPDATE questions
SET translations = '{"en": "Do you think people misunderstand what it means to have \u201cgifts\u201d as a love language? What does it actually mean to you?", "da": "Tror du, folk misforst\u00e5r, hvad det betyder at have \u201cgaver\u201d som k\u00e6rlighedssprog? Hvad betyder det egentlig for dig?", "de": "Denkst du, dass Menschen missverstehen, was es bedeutet, \u201eGeschenke\u201c als Liebessprache zu haben? Was bedeutet es wirklich f\u00fcr dich?", "es": "\u00bfCrees que la gente malinterpreta lo que significa tener los \u201cregalos\u201d como lenguaje del amor? \u00bfQu\u00e9 significa realmente para ti?", "pt": "Achas que as pessoas interpretam mal o que significa ter \u201cpresentes\u201d como linguagem do amor? O que isso realmente significa para ti?", "ro": "Crezi c\u0103 oamenii \u00een\u021beleg gre\u0219it ce \u00eenseamn\u0103 s\u0103 ai \u201ecadouri\u201d ca limbaj al iubirii? Ce \u00eenseamn\u0103 asta cu adev\u0103rat pentru tine?", "fr": "Penses-tu que les gens comprennent mal ce que cela signifie d\u2019avoir les \u00ab cadeaux \u00bb comme langage de l\u2019amour ? Qu\u2019est-ce que cela signifie vraiment pour toi ?", "it": "Pensi che le persone fraintendano cosa significhi avere i \"regali\" come linguaggio dell''amore? Cosa significa realmente per te?", "fi": "Mietitk\u00f6, ett\u00e4 ihmiset ymm\u00e4rt\u00e4v\u00e4t v\u00e4\u00e4rin, mit\u00e4 tarkoittaa, ett\u00e4 \"lahjat\" ovat rakkauden kieli? Mit\u00e4 se oikeastaan tarkoittaa sinulle?", "nl": "Denk je dat mensen verkeerd begrijpen wat het betekent om \"gaven\" als liefdestaal te hebben? Wat betekent het eigenlijk voor jou?", "no": "Tror du folk misforst\u00e5r hva det betyr \u00e5 ha \"gaver\" som kj\u00e6rlighetsspr\u00e5k? Hva betyr det egentlig for deg?", "sv": "Tycker du att folk missf\u00f6rst\u00e5r vad det inneb\u00e4r att ha \"g\u00e5vor\" som k\u00e4rleksspr\u00e5k? Vad betyder det egentligen f\u00f6r dig?", "pl": "Czy uwa\u017casz, \u017ce ludzie \u017ale rozumiej\u0105, co oznacza posiadanie \u201edar\u00f3w\u201d jako j\u0119zyka mi\u0142o\u015bci? Co to dla Ciebie w\u0142a\u015bciwie oznacza?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you think people misunderstand what it means to have “gifts” as a love language? What does it actually mean to you?';
UPDATE questions
SET translations = '{"en": "What makes a gift feel shallow to you \u2014 and what makes it feel thoughtful and genuine?", "da": "Hvad f\u00e5r en gave til at f\u00f8les overfladisk for dig \u2013 og hvad f\u00e5r den til at f\u00f8les bet\u00e6nksom og \u00e6gte?", "de": "Was l\u00e4sst ein Geschenk f\u00fcr dich oberfl\u00e4chlich wirken \u2013 und was l\u00e4sst es durchdacht und echt erscheinen?", "es": "\u00bfQu\u00e9 hace que un regalo se sienta superficial para ti \u2014 y qu\u00e9 lo hace considerado y genuino?", "pt": "O que faz um presente parecer superficial para ti \u2014 e o que o torna atencioso e genu\u00edno?", "ro": "Ce face ca un cadou s\u0103 par\u0103 superficial pentru tine \u2014 \u0219i ce \u00eel face atent \u0219i sincer?", "fr": "Qu\u2019est-ce qui fait qu\u2019un cadeau te semble superficiel \u2014 et qu\u2019est-ce qui le rend attentionn\u00e9 et sinc\u00e8re ?", "it": "Cosa rende un regalo superficiale per te \u2014 e cosa lo rende invece pensato e genuino?", "fi": "Mik\u00e4 tekee lahjasta mielest\u00e4si pinnallisen \u2014 ja mik\u00e4 tekee siit\u00e4 ajatuksellisen ja aito?", "nl": "Wat maakt een cadeau voor jou oppervlakkig \u2014 en wat maakt het doordacht en oprecht?", "no": "Hva f\u00e5r en gave til \u00e5 f\u00f8les overfladisk for deg \u2014 og hva gj\u00f8r at den f\u00f8les gjennomtenkt og ekte?", "sv": "Vad f\u00e5r en g\u00e5va att k\u00e4nnas ytlig f\u00f6r dig \u2014 och vad f\u00e5r den att k\u00e4nnas omt\u00e4nksam och \u00e4kta?", "pl": "Co sprawia, \u017ce prezent wydaje si\u0119 p\u0142ytki, a co sprawia, \u017ce jest przemy\u015blany i szczery?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What makes a gift feel shallow to you — and what makes it feel thoughtful and genuine?';
UPDATE questions
SET translations = '{"en": "Do you prefer gifts that are practical or sentimental?", "da": "Foretr\u00e6kker du gaver, der er praktiske eller sentimentale?", "de": "Bevorzugst du Geschenke, die praktisch oder sentimental sind?", "es": "\u00bfPrefieres regalos que sean pr\u00e1cticos o sentimentales?", "pt": "Preferes presentes pr\u00e1ticos ou sentimentais?", "ro": "Preferi cadouri practice sau sentimentale?", "fr": "Pr\u00e9f\u00e8res-tu les cadeaux pratiques ou sentimentaux ?", "it": "Preferisci regali che siano pratici o sentimentali?", "fi": "Pid\u00e4tk\u00f6 enemm\u00e4n k\u00e4yt\u00e4nn\u00f6llisist\u00e4 vai tunteellisista lahjoista?", "nl": "Geef je de voorkeur aan praktische of sentimentele cadeaus?", "no": "Foretrekker du gaver som er praktiske eller sentimentale?", "sv": "F\u00f6redrar du presenter som \u00e4r praktiska eller sentimentala?", "pl": "Czy wolisz prezenty praktyczne czy sentymentalne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you prefer gifts that are practical or sentimental?';
UPDATE questions
SET translations = '{"en": "How do you feel when I remember small details about what you like?", "da": "Hvordan har du det, n\u00e5r jeg husker sm\u00e5 detaljer om, hvad du kan lide?", "de": "Wie f\u00fchlst du dich, wenn ich mich an kleine Details erinnere, die du magst?", "es": "\u00bfC\u00f3mo te sientes cuando recuerdo peque\u00f1os detalles sobre lo que te gusta?", "pt": "Como te sentes quando eu me lembro de pequenos detalhes sobre o que gostas?", "ro": "Cum te sim\u021bi c\u00e2nd \u00eemi amintesc mici detalii despre ce \u00ee\u021bi place?", "fr": "Que ressens-tu quand je me souviens des petits d\u00e9tails de ce que tu aimes ?", "it": "Come ti senti quando ricordo piccoli dettagli su ci\u00f2 che ti piace?", "fi": "Milt\u00e4 sinusta tuntuu, kun muistan pieni\u00e4 yksityiskohtia siit\u00e4, mist\u00e4 pid\u00e4t?", "nl": "Hoe voel je je als ik kleine details herinner over wat je leuk vindt?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg husker sm\u00e5 detaljer om hva du liker?", "sv": "Hur k\u00e4nner du dig n\u00e4r jag kommer ih\u00e5g sm\u00e5 detaljer om vad du gillar?", "pl": "Jak si\u0119 czujesz, gdy pami\u0119tam o ma\u0142ych szczeg\u00f3\u0142ach dotycz\u0105cych tego, co lubisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I remember small details about what you like?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing I could give you that has no price tag but huge meaning?", "da": "Hvad er \u00e9n ting, jeg kunne give dig, som ikke har en prisseddel, men enorm betydning?", "de": "Was ist eine Sache, die ich dir geben k\u00f6nnte, die keinen Preis hat, aber gro\u00dfe Bedeutung?", "es": "\u00bfQu\u00e9 podr\u00eda darte que no tenga precio pero signifique mucho?", "pt": "O que eu poderia dar-te que n\u00e3o tivesse pre\u00e7o mas tivesse um enorme significado?", "ro": "Ce \u021bi-a\u0219 putea oferi care nu are pre\u021b, dar are o mare \u00eensemn\u0103tate?", "fr": "Quelle chose pourrais-je t\u2019offrir qui n\u2019a pas de prix mais une grande signification ?", "it": "Qual \u00e8 una cosa che potrei darti che non ha un prezzo ma ha un grande significato?", "fi": "Mik\u00e4 on yksi asia, jonka voisin antaa sinulle, jolla ei ole hintalappua mutta valtava merkitys?", "nl": "Wat is \u00e9\u00e9n ding dat ik je zou kunnen geven dat geen prijs heeft, maar enorme betekenis heeft?", "no": "Hva er \u00e9n ting jeg kunne gi deg som ikke har prislapp, men stor betydning?", "sv": "Vad \u00e4r en sak jag skulle kunna ge dig som inte har n\u00e5got prislapp men stor betydelse?", "pl": "Co\u015b, co m\u00f3g\u0142bym ci da\u0107, co nie ma ceny, ale ma ogromne znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one thing I could give you that has no price tag but huge meaning?';
UPDATE questions
SET translations = '{"en": "What\u2019s something physical that instantly reminds you of our love?", "da": "Hvad er noget fysisk, der straks minder dig om vores k\u00e6rlighed?", "de": "Was ist etwas Physisches, das dich sofort an unsere Liebe erinnert?", "es": "\u00bfQu\u00e9 objeto f\u00edsico te recuerda instant\u00e1neamente a nuestro amor?", "pt": "Que objeto f\u00edsico te lembra instantaneamente do nosso amor?", "ro": "Ce obiect fizic \u00ee\u021bi aminte\u0219te imediat de dragostea noastr\u0103?", "fr": "Quel objet physique te rappelle instantan\u00e9ment notre amour ?", "it": "Qualcosa di fisico che ti ricorda immediatamente il nostro amore?", "fi": "Mik\u00e4 on jokin fyysinen asia, joka heti tuo mieleesi rakkautemme?", "nl": "Wat is iets fysieks dat je meteen aan onze liefde doet denken?", "no": "Hva er noe fysisk som umiddelbart minner deg om v\u00e5r kj\u00e6rlighet?", "sv": "Vad \u00e4r n\u00e5got fysiskt som genast p\u00e5minner dig om v\u00e5r k\u00e4rlek?", "pl": "Co\u015b fizycznego, co od razu przypomina ci o naszej mi\u0142o\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something physical that instantly reminds you of our love?';
UPDATE questions
SET translations = '{"en": "Do you think gifts should always be a surprise, or is it okay to say what you want and make it easy for each other?", "da": "Tror du, at gaver altid skal v\u00e6re en overraskelse, eller er det okay at sige, hvad man \u00f8nsker, og g\u00f8re det nemt for hinanden?", "de": "Denkst du, Geschenke sollten immer eine \u00dcberraschung sein, oder ist es in Ordnung zu sagen, was man will, um es einander leichter zu machen?", "es": "\u00bfCrees que los regalos siempre deben ser una sorpresa, o est\u00e1 bien decir lo que uno quiere y hacerlo f\u00e1cil para ambos?", "pt": "Achas que os presentes devem ser sempre uma surpresa, ou \u00e9 aceit\u00e1vel dizer o que se quer e facilitar um ao outro?", "ro": "Crezi c\u0103 darurile ar trebui s\u0103 fie mereu o surpriz\u0103, sau e \u00een regul\u0103 s\u0103 spui ce \u00ee\u021bi dore\u0219ti \u0219i s\u0103 fie mai simplu pentru am\u00e2ndoi?", "fr": "Penses-tu que les cadeaux devraient toujours \u00eatre une surprise, ou est-il acceptable de dire ce que l\u2019on veut pour se faciliter les choses ?", "it": "Pensi che i regali debbano sempre essere una sorpresa, o va bene dire cosa si desidera e facilitare le cose a vicenda?", "fi": "Mietitk\u00f6, ett\u00e4 lahjojen pit\u00e4isi aina olla yll\u00e4tyksi\u00e4, vai onko ihan ok sanoa, mit\u00e4 haluaa ja helpottaa toisten el\u00e4m\u00e4\u00e4?", "nl": "Denk je dat cadeaus altijd een verrassing moeten zijn, of is het ok\u00e9 om te zeggen wat je wilt en het elkaar gemakkelijk te maken?", "no": "Tror du gaver alltid b\u00f8r v\u00e6re en overraskelse, eller er det greit \u00e5 si hva man \u00f8nsker og gj\u00f8re det enklere for hverandre?", "sv": "Tycker du att presenter alltid ska vara en \u00f6verraskning, eller \u00e4r det okej att s\u00e4ga vad man vill ha och g\u00f6ra det l\u00e4ttare f\u00f6r varandra?", "pl": "Czy uwa\u017casz, \u017ce prezenty powinny zawsze by\u0107 niespodziank\u0105, czy mo\u017ce warto powiedzie\u0107, czego si\u0119 chce, aby u\u0142atwi\u0107 sobie nawzajem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you think gifts should always be a surprise, or is it okay to say what you want and make it easy for each other?';
UPDATE questions
SET translations = '{"en": "When\u2019s the last time you felt surprised \u2014 in a good way \u2014 by me?", "da": "Hvorn\u00e5r var sidste gang, du blev overrasket \u2013 p\u00e5 en god m\u00e5de \u2013 af mig?", "de": "Wann war das letzte Mal, dass du \u2013 auf gute Weise \u2013 von mir \u00fcberrascht wurdest?", "es": "\u00bfCu\u00e1ndo fue la \u00faltima vez que te sorprend\u00ed \u2014 de una buena manera?", "pt": "Quando foi a \u00faltima vez que te surpreendi \u2014 de uma forma boa?", "ro": "C\u00e2nd a fost ultima dat\u0103 c\u00e2nd te-am surprins \u2014 \u00eentr-un mod pl\u0103cut?", "fr": "Quand as-tu \u00e9t\u00e9 surpris(e) pour la derni\u00e8re fois \u2014 d\u2019une bonne mani\u00e8re \u2014 par moi ?", "it": "Quando \u00e8 stata l''ultima volta che ti sei sentito sorpreso \u2014 in modo positivo \u2014 da me?", "fi": "Milloin viimeksi tunsit itsesi yll\u00e4tetyksi \u2014 hyv\u00e4ll\u00e4 tavalla \u2014 minun ansiostani?", "nl": "Wanneer was de laatste keer dat je op een goede manier door mij verrast was?", "no": "N\u00e5r var siste gang du f\u00f8lte deg overrasket \u2014 p\u00e5 en god m\u00e5te \u2014 av meg?", "sv": "N\u00e4r var senaste g\u00e5ngen du k\u00e4nde dig \u00f6verraskad \u2014 p\u00e5 ett bra s\u00e4tt \u2014 av mig?", "pl": "Kiedy ostatni raz poczu\u0142e\u015b si\u0119 zaskoczony \u2014 w pozytywny spos\u00f3b \u2014 przeze mnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When’s the last time you felt surprised — in a good way — by me?';
UPDATE questions
SET translations = '{"en": "Do you see touch more as a way to show love, to feel loved, or both?", "da": "Ser du ber\u00f8ring mere som en m\u00e5de at vise k\u00e6rlighed p\u00e5, at f\u00f8le sig elsket \u2013 eller begge dele?", "de": "Siehst du Ber\u00fchrung eher als eine Art, Liebe zu zeigen, Liebe zu f\u00fchlen \u2013 oder beides?", "es": "\u00bfVes el contacto f\u00edsico m\u00e1s como una forma de mostrar amor, de sentirte amado/a, o ambas cosas?", "pt": "V\u00eas o toque mais como uma forma de mostrar amor, de te sentires amado(a), ou ambos?", "ro": "Vezi atingerea mai mult ca o modalitate de a ar\u0103ta iubire, de a te sim\u021bi iubit(\u0103) sau ambele?", "fr": "Vois-tu le contact physique plut\u00f4t comme une mani\u00e8re de montrer l\u2019amour, de te sentir aim\u00e9(e), ou les deux ?", "it": "Vedi il contatto fisico pi\u00f9 come un modo per mostrare amore, per sentirsi amati, o entrambi?", "fi": "N\u00e4etk\u00f6 kosketuksen enemm\u00e4n tapana osoittaa rakkautta, tuntea itsesi rakastetuksi vai molempina?", "nl": "Zie je aanraking meer als een manier om liefde te tonen, om je geliefd te voelen, of beide?", "no": "Ser du ber\u00f8ring mer som en m\u00e5te \u00e5 vise kj\u00e6rlighet p\u00e5, \u00e5 f\u00f8le seg elsket, eller begge deler?", "sv": "Ser du ber\u00f6ring mer som ett s\u00e4tt att visa k\u00e4rlek, att k\u00e4nna sig \u00e4lskad, eller b\u00e5da?", "pl": "Czy postrzegasz dotyk bardziej jako spos\u00f3b na okazanie mi\u0142o\u015bci, poczucie si\u0119 kochanym, czy mo\u017ce jedno i drugie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you see touch more as a way to show love, to feel loved, or both?';