UPDATE questions
SET translations = '{"en": "How do you feel when I talk dirty?", "da": "Hvordan har du det, n\u00e5r jeg taler beskidt?", "de": "Wie f\u00fchlst du dich, wenn ich schmutzig mit dir rede?", "es": "\u00bfC\u00f3mo te sientes cuando te hablo de forma atrevida?", "pt": "Como te sentes quando eu falo contigo de forma atrevida?", "ro": "Cum te sim\u021bi c\u00e2nd \u00ee\u021bi vorbesc murdar?", "fr": "Comment te sens-tu quand je te parle de fa\u00e7on coquine ?", "it": "Come ti senti quando parlo in modo provocante?", "fi": "Milt\u00e4 sinusta tuntuu, kun puhun rivoja?", "nl": "Hoe voel je je als ik vies praat?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg snakker dirty?", "sv": "Hur k\u00e4nner du n\u00e4r jag pratar snuskigt?", "pl": "Jak si\u0119 czujesz, gdy m\u00f3wi\u0119 spro\u015bno\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel when I talk dirty?';
UPDATE questions
SET translations = '{"en": "Would you like to see me wear something sheer, lacy, silky, or revealing?", "da": "Kunne du t\u00e6nke dig at se mig have noget transparent, blondeagtigt, silkeagtigt eller afsl\u00f8rende p\u00e5?", "de": "W\u00fcrdest du es m\u00f6gen, mich in etwas Transparentem, Spitzen-, Seidigem oder Offenherzigem zu sehen?", "es": "\u00bfTe gustar\u00eda verme con algo transparente, de encaje, seda o revelador?", "pt": "Gostarias de me ver com algo transparente, rendado, sedoso ou revelador?", "ro": "\u021ai-ar pl\u0103cea s\u0103 m\u0103 vezi purt\u00e2nd ceva transparent, din dantel\u0103, m\u0103tase sau provocator?", "fr": "Aimerais-tu me voir porter quelque chose de transparent, dentelle, soie ou r\u00e9v\u00e9lateur ?", "it": "Ti piacerebbe vedermi indossare qualcosa di trasparente, pizzo, setoso o rivelatore?", "fi": "Haluaisitko n\u00e4hd\u00e4 minun pukeutuvan johonkin l\u00e4pin\u00e4kyv\u00e4\u00e4n, pitsiseen, silkkiseen tai paljastavaan?", "nl": "Zou je het leuk vinden als ik iets doorschijnends, kantachtig, zijdezacht of onthullend draag?", "no": "Vil du se meg ha p\u00e5 noe gjennomsiktig, blonder, silkeaktig eller avsl\u00f8rende?", "sv": "Skulle du vilja se mig ha p\u00e5 mig n\u00e5got genomskinligt, spetsigt, silkeslent eller avsl\u00f6jande?", "pl": "Czy chcia\u0142by\u015b zobaczy\u0107 mnie w czym\u015b przezroczystym, koronkowym, jedwabnym lub odkrywaj\u0105cym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Would you like to see me wear something sheer, lacy, silky, or revealing?';
UPDATE questions
SET translations = '{"en": "What kind of role-play between us sounds the most exciting?", "da": "Hvilken slags rollespil mellem os lyder mest sp\u00e6ndende?", "de": "Welche Art von Rollenspiel zwischen uns klingt f\u00fcr dich am aufregendsten?", "es": "\u00bfQu\u00e9 tipo de juego de roles entre nosotros te parece m\u00e1s emocionante?", "pt": "Que tipo de roleplay entre n\u00f3s te parece mais excitante?", "ro": "Ce tip de joc de rol \u00eentre noi \u021bi se pare cel mai interesant?", "fr": "Quel type de jeu de r\u00f4le entre nous te semble le plus excitant ?", "it": "Quale tipo di gioco di ruolo tra noi ti sembra pi\u00f9 eccitante?", "fi": "Mink\u00e4lainen roolileikki meid\u00e4n v\u00e4lill\u00e4mme kuulostaa j\u00e4nnitt\u00e4vimm\u00e4lt\u00e4?", "nl": "Welke soort rollenspel tussen ons klinkt het meest spannend?", "no": "Hvilken type rollespill mellom oss h\u00f8res mest spennende ut?", "sv": "Vilken typ av rollspel mellan oss l\u00e5ter mest sp\u00e4nnande?", "pl": "Jaki rodzaj odgrywania r\u00f3l mi\u0119dzy nami brzmi najbardziej ekscytuj\u0105co?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of role-play between us sounds the most exciting?';
UPDATE questions
SET translations = '{"en": "Do you prefer spontaneous sex or something you\u2019ve been anticipating all day?", "da": "Foretr\u00e6kker du spontan sex eller noget, du har ventet p\u00e5 hele dagen?", "de": "Magst du spontanen Sex oder lieber etwas, auf das du den ganzen Tag gewartet hast?", "es": "\u00bfPrefieres el sexo espont\u00e1neo o algo que hayas esperado todo el d\u00eda?", "pt": "Preferes sexo espont\u00e2neo ou algo pelo qual esperaste o dia inteiro?", "ro": "Preferi sexul spontan sau ceva ce ai a\u0219teptat toat\u0103 ziua?", "fr": "Pr\u00e9f\u00e8res-tu le sexe spontan\u00e9 ou quelque chose que tu attends toute la journ\u00e9e ?", "it": "Preferisci il sesso spontaneo o qualcosa che hai anticipato per tutto il giorno?", "fi": "Pid\u00e4tk\u00f6 enemm\u00e4n spontaaneista seksist\u00e4 vai sellaisesta, jota olet odottanut koko p\u00e4iv\u00e4n?", "nl": "Geef je de voorkeur aan spontane seks of iets waar je de hele dag naar hebt uitgekeken?", "no": "Foretrekker du spontan sex eller noe du har sett frem til hele dagen?", "sv": "F\u00f6redrar du spontan sex eller n\u00e5got som du har sett fram emot hela dagen?", "pl": "Czy wolisz spontaniczny seks, czy raczej taki, na kt\u00f3ry czeka\u0142e\u015b przez ca\u0142y dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you prefer spontaneous sex or something you’ve been anticipating all day?';UPDATE questions
SET translations = '{"en": "Is there anything you wish I\u2019d stop doing in bed?", "da": "Er der noget, du ville \u00f8nske, jeg ville holde op med at lave i sengen?", "de": "Gibt es etwas, das du dir w\u00fcnschst, ich w\u00fcrde im Bett nicht mehr tun?", "es": "\u00bfHay algo que quisieras que dejara de hacer en la cama?", "pt": "H\u00e1 algo que gostarias que eu deixasse de fazer na cama?", "ro": "Exist\u0103 ceva ce \u021bi-ai dori s\u0103 nu mai fac \u00een pat?", "fr": "Y a-t-il quelque chose que tu aimerais que j\u2019arr\u00eate de faire au lit ?", "it": "C''\u00e8 qualcosa che desideri che smetta di fare a letto?", "fi": "Onko jotain, mit\u00e4 toivoisit minun lopettavan s\u00e4ngyss\u00e4?", "nl": "Is er iets waarvan je zou willen dat ik ermee stop in bed?", "no": "Er det noe du \u00f8nsker jeg skulle slutte \u00e5 gj\u00f8re i sengen?", "sv": "Finns det n\u00e5got du \u00f6nskar att jag skulle sluta g\u00f6ra i s\u00e4ngen?", "pl": "Czy jest co\u015b, co chcia\u0142by\u015b, \u017cebym przesta\u0142 robi\u0107 w \u0142\u00f3\u017cku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is there anything you wish I’d stop doing in bed?';
UPDATE questions
SET translations = '{"en": "Is the anything new you\u2019d want us to try next time?", "da": "Er der noget nyt, du gerne vil have, vi skal pr\u00f8ve n\u00e6ste gang?", "de": "Gibt es etwas Neues, das du m\u00f6chtest, dass wir beim n\u00e4chsten Mal ausprobieren?", "es": "\u00bfHay algo nuevo que te gustar\u00eda que prob\u00e1ramos la pr\u00f3xima vez?", "pt": "H\u00e1 algo novo que gostarias que experiment\u00e1ssemos da pr\u00f3xima vez?", "ro": "Este ceva nou ce ai vrea s\u0103 \u00eencerc\u0103m data viitoare?", "fr": "Y a-t-il quelque chose de nouveau que tu voudrais qu\u2019on essaie la prochaine fois ?", "it": "C''\u00e8 qualcosa di nuovo che vorresti provare la prossima volta?", "fi": "Onko jotain uutta, mit\u00e4 haluaisit meid\u00e4n kokeilevan ensi kerralla?", "nl": "Is er iets nieuws dat je de volgende keer zou willen proberen?", "no": "Er det noe nytt du \u00f8nsker at vi skal pr\u00f8ve neste gang?", "sv": "\u00c4r det n\u00e5got nytt du skulle vilja att vi provar n\u00e4sta g\u00e5ng?", "pl": "Czy jest co\u015b nowego, co chcia\u0142by\u015b, \u017ceby\u015bmy spr\u00f3bowali nast\u0119pnym razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Is the anything new you’d want us to try next time?';
UPDATE questions
SET translations = '{"en": "Do you prefer experimenting with different positions, or do you have favorites that always work?", "da": "Foretr\u00e6kker du at eksperimentere med forskellige stillinger, eller har du favoritter, der altid virker?", "de": "Probierst du gerne verschiedene Stellungen aus, oder hast du Favoriten, die immer funktionieren?", "es": "\u00bfPrefieres experimentar con distintas posiciones o tienes tus favoritas?", "pt": "Preferes experimentar v\u00e1rias posi\u00e7\u00f5es ou tens as tuas favoritas?", "ro": "\u00ce\u021bi place s\u0103 experimentezi pozi\u021bii diferite sau ai favoritele tale?", "fr": "Pr\u00e9f\u00e8res-tu exp\u00e9rimenter diff\u00e9rentes positions ou as-tu tes pr\u00e9f\u00e9r\u00e9es ?", "it": "Preferisci sperimentare con diverse posizioni, o hai delle preferite che funzionano sempre?", "fi": "Pid\u00e4tk\u00f6 enemm\u00e4n erilaisten asentojen kokeilemisesta, vai onko sinulla suosikkeja, jotka aina toimivat?", "nl": "Heb je liever om te experimenteren met verschillende posities, of heb je favorieten die altijd werken?", "no": "Foretrekker du \u00e5 eksperimentere med forskjellige stillinger, eller har du favoritter som alltid fungerer?", "sv": "F\u00f6redrar du att experimentera med olika st\u00e4llningar, eller har du favoriter som alltid fungerar?", "pl": "Czy wolisz eksperymentowa\u0107 z r\u00f3\u017cnymi pozycjami, czy masz ulubione, kt\u00f3re zawsze si\u0119 sprawdzaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Do you prefer experimenting with different positions, or do you have favorites that always work?';
UPDATE questions
SET translations = '{"en": "Have you ever been curious about using toys together?", "da": "Har du nogensinde v\u00e6ret nysgerrig efter at bruge leget\u00f8j sammen?", "de": "Warst du jemals neugierig, Sexspielzeug zusammen zu benutzen?", "es": "\u00bfAlguna vez has tenido curiosidad de usar juguetes juntos?", "pt": "J\u00e1 tiveste curiosidade de usar brinquedos juntos?", "ro": "Ai fost vreodat\u0103 curios(\u0103) s\u0103 folosim juc\u0103rii \u00eempreun\u0103?", "fr": "As-tu d\u00e9j\u00e0 eu envie d\u2019utiliser des jouets avec moi ?", "it": "Sei mai stato curioso di usare i giocattoli insieme?", "fi": "Oletko koskaan ollut utelias leikkim\u00e4\u00e4n leluilla yhdess\u00e4?", "nl": "Ben je ooit nieuwsgierig geweest naar het samen gebruiken van speelgoed?", "no": "Har du noen gang v\u00e6rt nysgjerrig p\u00e5 \u00e5 bruke leker sammen?", "sv": "Har du n\u00e5gonsin varit nyfiken p\u00e5 att anv\u00e4nda leksaker tillsammans?", "pl": "Czy kiedykolwiek zastanawia\u0142e\u015b si\u0119 nad wsp\u00f3lnym u\u017cywaniem zabawek?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever been curious about using toys together?';
UPDATE questions
SET translations = '{"en": "How do you feel about revisiting something we tried once but haven\u2019t in a while?", "da": "Hvad synes du om at pr\u00f8ve noget igen, vi har pr\u00f8vet engang, men ikke har gjort i et stykke tid?", "de": "Was h\u00e4ltst du davon, etwas wieder auszuprobieren, das wir schon einmal getan haben, aber lange nicht mehr?", "es": "\u00bfQu\u00e9 opinas de volver a probar algo que hicimos hace tiempo?", "pt": "O que achas de voltarmos a tentar algo que fizemos h\u00e1 algum tempo?", "ro": "Ce p\u0103rere ai despre a \u00eencerca din nou ceva ce am f\u0103cut c\u00e2ndva?", "fr": "Que penses-tu de refaire quelque chose que nous avons essay\u00e9 il y a longtemps ?", "it": "Come ti senti riguardo a riprovare qualcosa che abbiamo gi\u00e0 provato una volta ma che non facciamo da un po''?", "fi": "Mit\u00e4 mielt\u00e4 olet siit\u00e4, ett\u00e4 kokeilisimme uudelleen jotain, mit\u00e4 yritimme kerran mutta emme ole tehneet pitk\u00e4\u00e4n aikaan?", "nl": "Hoe voel je je over het opnieuw proberen van iets wat we eens hebben gedaan, maar al een tijdje niet meer?", "no": "Hvordan f\u00f8ler du om \u00e5 gjenta noe vi pr\u00f8vde en gang, men ikke har gjort p\u00e5 en stund?", "sv": "Hur k\u00e4nner du f\u00f6r att \u00e5terbes\u00f6ka n\u00e5got vi provade en g\u00e5ng men inte har gjort p\u00e5 ett tag?", "pl": "Co my\u015blisz o ponownym spr\u00f3bowaniu czego\u015b, co ju\u017c raz zrobili\u015bmy, ale od jakiego\u015b czasu tego nie robimy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about revisiting something we tried once but haven’t in a while?';
UPDATE questions
SET translations = '{"en": "Which of us is more likely to want another round?", "da": "Hvem af os er mest tilb\u00f8jelig til at have lyst til en omgang mere?", "de": "Wer von uns hat eher Lust auf eine zweite Runde?", "es": "\u00bfQui\u00e9n de nosotros es m\u00e1s propenso a querer una ronda m\u00e1s?", "pt": "Quem de n\u00f3s tem mais tend\u00eancia para querer uma segunda rodada?", "ro": "Cine dintre noi vrea mai des o a doua rund\u0103?", "fr": "Lequel de nous deux a le plus souvent envie d\u2019une deuxi\u00e8me fois ?", "it": "Quale di noi \u00e8 pi\u00f9 propenso a volere un altro giro?", "fi": "Kumpi meist\u00e4 todenn\u00e4k\u00f6isemmin haluaa viel\u00e4 yhden kierroksen?", "nl": "Wie van ons is waarschijnlijker om nog een ronde te willen?", "no": "Hvem av oss er mer sannsynlig \u00e5 \u00f8nske en runde til?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att vilja ha en runda till?", "pl": "Kt\u00f3ry z nas jest bardziej sk\u0142onny do ch\u0119ci na kolejna rund\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to want another round?';
UPDATE questions
SET translations = '{"en": "What\u2019s your opinion on toys that we can use while we\u2019re apart?", "da": "Hvad er din mening om leget\u00f8j, vi kan bruge, mens vi er fra hinanden? ", "de": "Was h\u00e4ltst du von Spielzeug, das wir benutzen k\u00f6nnten, wenn wir getrennt sind?", "es": "\u00bfQu\u00e9 piensas de los juguetes que podr\u00edamos usar cuando estamos separados?", "pt": "O que pensas sobre brinquedos que poder\u00edamos usar quando estamos separados?", "ro": "Ce p\u0103rere ai despre juc\u0103rii pe care le-am putea folosi c\u00e2nd suntem departe?", "fr": "Que penses-tu des jouets qu\u2019on pourrait utiliser quand on est s\u00e9par\u00e9s ?", "it": "Qual \u00e8 la tua opinione sui giocattoli che possiamo usare mentre siamo lontani?", "fi": "Mit\u00e4 mielt\u00e4 olet leluista, joita voimme k\u00e4ytt\u00e4\u00e4, kun olemme eristyksiss\u00e4?", "nl": "Wat is jouw mening over speelgoed dat we kunnen gebruiken terwijl we apart zijn?", "no": "Hva er din mening om leker vi kan bruke mens vi er fra hverandre?", "sv": "Vad tycker du om leksaker som vi kan anv\u00e4nda n\u00e4r vi \u00e4r \u00e5tskilda?", "pl": "Jakie jest twoje zdanie na temat zabawek, kt\u00f3re mo\u017cemy u\u017cywa\u0107, gdy jeste\u015bmy daleko od siebie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your opinion on toys that we can use while we’re apart?';