UPDATE questions
SET translations = '{"en": "What phrase do I say so often it should be on a T-shirt?", "da": "Hvilken s\u00e6tning siger jeg s\u00e5 ofte, at den burde st\u00e5 p\u00e5 en T-shirt?", "de": "Welchen Satz sage ich so oft, dass er auf ein T-Shirt geh\u00f6rt?", "es": "\u00bfQu\u00e9 frase digo tan seguido que deber\u00eda estar en una camiseta?", "pt": "Que frase eu digo tanto que deveria estar em uma camiseta?", "ro": "Ce expresie spun at\u00e2t de des \u00eenc\u00e2t ar trebui pus\u0103 pe un tricou?", "fr": "Quelle phrase dis-je si souvent qu\u2019elle devrait \u00eatre sur un t-shirt ?", "it": "Quale frase dico cos\u00ec spesso che dovrebbe stare su una maglietta?", "fi": "Mink\u00e4 lauseen sanon niin usein, ett\u00e4 sen pit\u00e4isi olla T-paidassa?", "nl": "Welke zin zeg ik zo vaak dat hij op een T-shirt zou moeten staan?", "no": "Hvilken setning sier jeg s\u00e5 ofte at den burde st\u00e5 p\u00e5 en T-skjorte?", "sv": "Vilken fras s\u00e4ger jag s\u00e5 ofta att den borde st\u00e5 p\u00e5 en T-shirt?", "pl": "Jakie zdanie m\u00f3wi\u0119 tak cz\u0119sto, \u017ce powinno trafi\u0107 na koszulk\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What phrase do I say so often it should be on a T-shirt?';
UPDATE questions
SET translations = '{"en": "If we started a pyramid scheme, what ridiculous thing would we sell and why would it work?", "da": "Hvis vi startede et pyramidespil, hvad for en sk\u00f8r ting ville vi s\u00e6lge \u2014 og hvorfor ville det virke?", "de": "Wenn wir ein Pyramidensystem starten w\u00fcrden, was Verr\u00fccktes w\u00fcrden wir verkaufen \u2013 und warum w\u00fcrde es funktionieren?", "es": "Si empez\u00e1ramos una estafa piramidal, \u00bfqu\u00e9 cosa rid\u00edcula vender\u00edamos y por qu\u00e9 funcionar\u00eda?", "pt": "Se come\u00e7\u00e1ssemos um esquema de pir\u00e2mide, que coisa rid\u00edcula vender\u00edamos e por que daria certo?", "ro": "Dac\u0103 am \u00eencepe o schem\u0103 piramidal\u0103, ce lucru absurd am vinde \u0219i de ce ar func\u021biona?", "fr": "Si on lan\u00e7ait une pyramide de Ponzi, quelle chose ridicule vendrions-nous et pourquoi \u00e7a marcherait ?", "it": "Se mettessimo in piedi uno schema piramidale, quale cosa assurda venderemmo e perch\u00e9 funzionerebbe?", "fi": "Jos perustaisimme pyramidihuijauksen, mit\u00e4 naurettavaa myisimme ja miksi se muka toimisi?", "nl": "Als wij een piramidespel zouden starten, welk belachelijk product zouden we verkopen en waarom zou dat werken?", "no": "Hvis vi startet et pyramidespill, hvilken latterlig ting skulle vi solgt \u2013 og hvorfor ville det funket?", "sv": "Om vi startade ett pyramidspel, vilken l\u00f6jlig grej skulle vi s\u00e4lja och varf\u00f6r skulle det funka?", "pl": "Gdyby\u015bmy za\u0142o\u017cyli piramid\u0119 finansow\u0105, jaki absurdalny produkt by\u015bmy sprzedawali i dlaczego by to dzia\u0142a\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we started a pyramid scheme, what ridiculous thing would we sell and why would it work?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell, sound, or taste that instantly says \u201cvacation\u201d to you?", "da": "Hvilken duft, lyd eller smag siger straks \u201cferie\u201d for dig?", "de": "Welcher Geruch, Klang oder Geschmack bedeutet f\u00fcr dich sofort \u201eUrlaub\u201c?", "es": "\u00bfQu\u00e9 olor, sonido o sabor te dice instant\u00e1neamente \u201cvacaciones\u201d?", "pt": "Que cheiro, som ou sabor imediatamente diz \u201cf\u00e9rias\u201d para voc\u00ea?", "ro": "Ce miros, sunet sau gust spune instantaneu \u201evacan\u021b\u0103\u201d pentru tine?", "fr": "Quelle odeur, son ou saveur te dit instantan\u00e9ment \u00ab vacances \u00bb ?", "it": "Quale odore, suono o sapore ti dice immediatamente \u201cvacanza\u201d?", "fi": "Mik\u00e4 tuoksu, \u00e4\u00e4ni tai maku tarkoittaa sinulle heti \u201cloma\u201d?", "nl": "Welke geur, welk geluid of welke smaak zegt voor jou meteen \u201cvakantie\u201d?", "no": "Hvilken lukt, lyd eller smak sier umiddelbart \u00abferie\u00bb for deg?", "sv": "Vilken doft, vilket ljud eller vilken smak betyder direkt \u201dsemester\u201d f\u00f6r dig?", "pl": "Jaki zapach, d\u017awi\u0119k lub smak od razu kojarzy ci si\u0119 z \u201ewakacjami\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a smell, sound, or taste that instantly says “vacation” to you?';
UPDATE questions
SET translations = '{"en": "Ever slept somewhere totally unusual? Where?", "da": "Har du nogensinde sovet et helt us\u00e6dvanligt sted? Hvor?", "de": "Hast du jemals an einem v\u00f6llig ungew\u00f6hnlichen Ort geschlafen? Wo?", "es": "\u00bfAlguna vez dormiste en un lugar totalmente inusual? \u00bfD\u00f3nde?", "pt": "Voc\u00ea j\u00e1 dormiu em um lugar totalmente incomum? Onde?", "ro": "Ai dormit vreodat\u0103 \u00eentr-un loc complet neobi\u0219nuit? Unde?", "fr": "As-tu d\u00e9j\u00e0 dormi dans un endroit compl\u00e8tement insolite ? O\u00f9 ?", "it": "Hai mai dormito in un posto davvero insolito? Dove?", "fi": "Oletko koskaan nukkunut ihan oudossa paikassa? Miss\u00e4?", "nl": "Heb je ooit op een totaal ongebruikelijke plek geslapen? Waar?", "no": "Har du noen gang sovet et helt uvanlig sted? Hvor?", "sv": "Har du n\u00e5gonsin sovit p\u00e5 ett helt ovanligt st\u00e4lle? Var?", "pl": "Czy kiedykolwiek spa\u0142e\u015b/spa\u0142a\u015b w zupe\u0142nie nietypowym miejscu? Gdzie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Ever slept somewhere totally unusual? Where?';
UPDATE questions
SET translations = '{"en": "What\u2019s your gas-station snack hall-of-fame pick?", "da": "Hvad er din \u201ctankstation-snack\u201d favorit gennem tiderne?", "de": "Was ist dein ultimativer Tankstellen-Snack-Favorit?", "es": "\u00bfCu\u00e1l es tu snack favorito de gasolinera de todos los tiempos?", "pt": "Qual \u00e9 o seu lanche de posto de gasolina preferido de todos os tempos?", "ro": "Care este gustarea ta preferat\u0103 de benzin\u0103rie din toate timpurile?", "fr": "Quelle est ta collation d\u2019autoroute pr\u00e9f\u00e9r\u00e9e de tous les temps ?", "it": "Qual \u00e8 lo snack da autogrill che entra nella tua personale \u201cHall of Fame\u201d?", "fi": "Mik\u00e4 on huoltoaseman ev\u00e4iden Hall of Fame -valintasi?", "nl": "Wat is jouw tankstation-snack voor in de Hall of Fame?", "no": "Hva er din bensinstasjons-snack i Hall of Fame?", "sv": "Vilket mack-snack hamnar i din egen Hall of Fame?", "pl": "Jaka przek\u0105ska ze stacji benzynowej trafia do twojej \u201egalerii s\u0142aw\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s your gas-station snack hall-of-fame pick?';
UPDATE questions
SET translations = '{"en": "What\u2019s the longest journey you\u2019ve ever taken?", "da": "Hvad er den l\u00e6ngste rejse, du nogensinde har taget?", "de": "Was ist die l\u00e4ngste Reise, die du je gemacht hast?", "es": "\u00bfCu\u00e1l es el viaje m\u00e1s largo que has hecho?", "pt": "Qual \u00e9 a viagem mais longa que voc\u00ea j\u00e1 fez?", "ro": "Care este cea mai lung\u0103 c\u0103l\u0103torie pe care ai f\u0103cut-o?", "fr": "Quel est le plus long voyage que tu aies jamais fait ?", "it": "Qual \u00e8 il viaggio pi\u00f9 lungo che tu abbia mai fatto?", "fi": "Mik\u00e4 on pisin matka, jonka olet koskaan tehnyt?", "nl": "Wat is de langste reis die je ooit hebt gemaakt?", "no": "Hva er den lengste reisen du noen gang har tatt?", "sv": "Vilken \u00e4r den l\u00e4ngsta resa du n\u00e5gonsin har gjort?", "pl": "Jaka jest najd\u0142u\u017csza podr\u00f3\u017c, jak\u0105 kiedykolwiek odby\u0142e\u015b/odby\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s the longest journey you’ve ever taken?';
UPDATE questions
SET translations = '{"en": "If pets could text, what would yours send you at 2 a.m.?", "da": "Hvis k\u00e6ledyr kunne skrive beskeder, hvad ville dit sende dig kl. 2 om natten?", "de": "Wenn Haustiere schreiben k\u00f6nnten, was w\u00fcrde dir deins um 2 Uhr nachts schicken?", "es": "Si las mascotas pudieran mandar mensajes, \u00bfqu\u00e9 te enviar\u00eda la tuya a las 2 a.m.?", "pt": "Se os pets pudessem mandar mensagens, o que o seu te mandaria \u00e0s 2 da manh\u00e3?", "ro": "Dac\u0103 animalele de companie ar putea trimite mesaje, ce \u021bi-ar trimite al t\u0103u la 2 diminea\u021ba?", "fr": "Si les animaux pouvaient envoyer des textos, que t\u2019enverrait le tien \u00e0 2 h du matin ?", "it": "Se gli animali domestici potessero mandare messaggi, cosa ti scriverebbe il tuo alle 2 di notte?", "fi": "Jos lemmikit voisivat l\u00e4hett\u00e4\u00e4 viestej\u00e4, mit\u00e4 omasi l\u00e4hett\u00e4isi sinulle klo 2 y\u00f6ll\u00e4?", "nl": "Als huisdieren konden appen, wat zou die van jou je om 2 uur \u2019s nachts sturen?", "no": "Hvis kj\u00e6ledyr kunne sende meldinger, hva ville ditt sendt deg klokka 2 om natta?", "sv": "Om husdjur kunde sms:a, vad skulle ditt skicka till dig kl. 2 p\u00e5 natten?", "pl": "Gdyby zwierzaki mog\u0142y pisa\u0107 wiadomo\u015bci, co twoje wys\u0142a\u0142oby ci o 2 w nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If pets could text, what would yours send you at 2 a.m.?';
UPDATE questions
SET translations = '{"en": "Which city would you move to for one year \u2013 and why?", "da": "Hvilken by ville du flytte til i et \u00e5r \u2013 og hvorfor?", "de": "In welche Stadt w\u00fcrdest du f\u00fcr ein Jahr ziehen \u2013 und warum?", "es": "\u00bfA qu\u00e9 ciudad te mudar\u00edas por un a\u00f1o \u2013 y por qu\u00e9?", "pt": "Para qual cidade voc\u00ea se mudaria por um ano \u2013 e por qu\u00ea?", "ro": "\u00cen ce ora\u0219 te-ai muta pentru un an \u2013 \u0219i de ce?", "fr": "Dans quelle ville irais-tu vivre pendant un an \u2013 et pourquoi ?", "it": "In quale citt\u00e0 ti trasferiresti per un anno, e perch\u00e9?", "fi": "Mihin kaupunkiin muuttaisit vuodeksi \u2013 ja miksi?", "nl": "Naar welke stad zou je voor \u00e9\u00e9n jaar verhuizen \u2013 en waarom?", "no": "Hvilken by ville du flyttet til for ett \u00e5r \u2013 og hvorfor?", "sv": "Till vilken stad skulle du flytta i ett \u00e5r \u2013 och varf\u00f6r?", "pl": "Do jakiego miasta przeprowadzi\u0142(a)by\u015b si\u0119 na rok \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Which city would you move to for one year – and why?';
UPDATE questions
SET translations = '{"en": "Have you ever had a \u201cthis is not what I expected\u201d travel moment \u2014 good or bad?", "da": "Har du nogensinde haft en \u201cdet var ikke som forventet\u201d-rejseoplevelse \u2014 god eller d\u00e5rlig?", "de": "Hattest du jemals einen \u201edas habe ich nicht erwartet\u201c-Reisemoment \u2013 gut oder schlecht?", "es": "\u00bfAlguna vez tuviste un momento de viaje de \u201cesto no era lo que esperaba\u201d, bueno o malo?", "pt": "Voc\u00ea j\u00e1 teve um momento de viagem \u201cn\u00e3o era o que eu esperava\u201d \u2014 bom ou ruim?", "ro": "Ai avut vreodat\u0103 un moment de c\u0103l\u0103torie \u201enu era ce credeam\u201d \u2014 bun sau r\u0103u?", "fr": "As-tu d\u00e9j\u00e0 eu un moment de voyage du type \u00ab ce n\u2019\u00e9tait pas ce \u00e0 quoi je m\u2019attendais \u00bb \u2014 bon ou mauvais ?", "it": "Hai mai avuto in viaggio un momento del tipo \u201cnon \u00e8 come me lo aspettavo\u201d, in bene o in male?", "fi": "Onko sinulle matkalla tullut hetke\u00e4, jolloin ajattelit: \u201ct\u00e4t\u00e4 en odottanut\u201d \u2013 hyv\u00e4ss\u00e4 tai pahassa?", "nl": "Heb je ooit op reis zo\u2019n \u201cdit is niet wat ik verwachtte\u201d-moment gehad \u2013 positief of negatief?", "no": "Har du noen gang hatt et \u00abdette var ikke som jeg hadde forventet\u00bb-\u00f8yeblikk p\u00e5 reise \u2013 p\u00e5 godt eller vondt?", "sv": "Har du n\u00e5gonsin haft ett \u201ddet h\u00e4r var inte vad jag v\u00e4ntade mig\u201d-\u00f6gonblick p\u00e5 resa \u2013 bra eller d\u00e5ligt?", "pl": "Czy mia\u0142e\u015b/mia\u0142a\u015b kiedy\u015b w podr\u00f3\u017cy moment \u201etego si\u0119 nie spodziewa\u0142em/am\u201d \u2013 na plus lub na minus?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Have you ever had a “this is not what I expected” travel moment — good or bad?';
UPDATE questions
SET translations = '{"en": "Have you ever been scared of a sound in the wild \u2014 and did you ever find out what it was?", "da": "Har du nogensinde v\u00e6ret bange for en lyd i naturen \u2014 og fandt du ud af, hvad det var?", "de": "Hattest du jemals Angst vor einem Ger\u00e4usch in der Wildnis \u2013 und hast du herausgefunden, was es war?", "es": "\u00bfAlguna vez te asust\u00f3 un sonido en la naturaleza \u2014 y descubriste qu\u00e9 era?", "pt": "Voc\u00ea j\u00e1 se assustou com um som na natureza \u2014 e descobriu o que era?", "ro": "\u021ai s-a \u00eent\u00e2mplat vreodat\u0103 s\u0103 te sperii de un sunet \u00een natur\u0103 \u2014 \u0219i s\u0103 afli ce era?", "fr": "T\u2019es-tu d\u00e9j\u00e0 fait peur avec un bruit dans la nature \u2014 et as-tu d\u00e9couvert ce que c\u2019\u00e9tait ?", "it": "Ti sei mai spaventato/a per un rumore in natura \u2013 e hai poi scoperto cos\u2019era?", "fi": "Oletko koskaan pel\u00e4stynyt \u00e4\u00e4nt\u00e4 luonnossa \u2013 ja saitko koskaan selville, mit\u00e4 se oli?", "nl": "Ben je ooit bang geweest voor een geluid in de natuur \u2013 en kwam je er ooit achter wat het was?", "no": "Har du noen gang blitt redd av en lyd ute i naturen \u2013 og fant du noen gang ut hva det var?", "sv": "Har du n\u00e5gonsin blivit r\u00e4dd f\u00f6r ett ljud ute i naturen \u2013 och tog du n\u00e5gonsin reda p\u00e5 vad det var?", "pl": "Czy kiedykolwiek przestraszy\u0142(a) ci\u0119 jaki\u015b d\u017awi\u0119k na \u0142onie natury \u2013 i czy dowiedzia\u0142e\u015b/dowiedzia\u0142a\u015b si\u0119, co to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Have you ever been scared of a sound in the wild — and did you ever find out what it was?';