UPDATE questions
SET translations = '{"en": "What\u2019s a TV show or movie you\u2019d love to watch for the first time again?", "da": "Hvilket tv-program eller hvilken film ville du elske at se for f\u00f8rste gang igen?", "de": "Welche Serie oder welchen Film w\u00fcrdest du gerne noch einmal zum ersten Mal sehen?", "es": "\u00bfQu\u00e9 programa o pel\u00edcula te gustar\u00eda volver a ver por primera vez?", "pt": "Que programa de TV ou filme voc\u00ea gostaria de assistir pela primeira vez novamente?", "ro": "Ce emisiune TV sau film \u021bi-ar pl\u0103cea s\u0103 vezi din nou ca prima dat\u0103?", "fr": "Quelle s\u00e9rie ou film aimerais-tu revoir comme si c\u2019\u00e9tait la premi\u00e8re fois ?", "it": "Qual \u00e8 un programma TV o un film che ti piacerebbe rivedere per la prima volta?", "fi": "Mik\u00e4 on TV-ohjelma tai elokuva, jonka haluaisit katsoa ensimm\u00e4ist\u00e4 kertaa uudelleen?", "nl": "Wat is een tv-show of film die je graag opnieuw voor de eerste keer zou willen zien?", "no": "Hvilken TV-serie eller film ville du elsket \u00e5 se for f\u00f8rste gang igjen?", "sv": "Vilken TV-show eller film skulle du \u00e4lska att se f\u00f6r f\u00f6rsta g\u00e5ngen igen?", "pl": "Jaki program telewizyjny lub film chcia\u0142by\u015b obejrze\u0107 po raz pierwszy jeszcze raz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a TV show or movie you’d love to watch for the first time again?';
UPDATE questions
SET translations = '{"en": "What does your ideal \u201cno plans\u201d night look like?", "da": "Hvordan ser din ideelle \u201cingen planer\u201d-aften ud?", "de": "Wie sieht dein idealer \u201eKeine-Pl\u00e4ne\u201c-Abend aus?", "es": "\u00bfC\u00f3mo es tu noche ideal de \u201csin planes\u201d?", "pt": "Como \u00e9 a sua noite ideal de \u201csem planos\u201d?", "ro": "Cum arat\u0103 seara ta ideal\u0103 \u201ef\u0103r\u0103 planuri\u201d?", "fr": "\u00c0 quoi ressemble ta soir\u00e9e id\u00e9ale \u00ab sans plans \u00bb ?", "it": "Come sarebbe la tua serata ideale \"senza piani\"?", "fi": "Millainen on sinun ihanteellinen \"ilman suunnitelmia\" ilta?", "nl": "Hoe ziet jouw ideale \"geen plannen\" avond eruit?", "no": "Hvordan ser din ideelle \"ingen planer\" kveld ut?", "sv": "Hur ser din ideala \"inga planer\" kv\u00e4ll ut?", "pl": "Jak wygl\u0105da tw\u00f3j idealny wiecz\u00f3r bez plan\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What does your ideal “no plans” night look like?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite cozy season activity \u2014 baking, reading, movie marathons, crafts?", "da": "Hvad er din yndlingsaktivitet i den hyggelige \u00e5rstid \u2014 bagning, l\u00e6sning, film-maraton, h\u00e5ndv\u00e6rk?", "de": "Was ist deine Lieblingsaktivit\u00e4t in der gem\u00fctlichen Jahreszeit \u2013 Backen, Lesen, Film-Marathon, Basteln?", "es": "\u00bfCu\u00e1l es tu actividad favorita de la temporada acogedora \u2014 hornear, leer, ver pel\u00edculas, manualidades?", "pt": "Qual \u00e9 a sua atividade favorita na esta\u00e7\u00e3o aconchegante \u2014 assar, ler, maratonar filmes, artesanato?", "ro": "Care este activitatea ta preferat\u0103 \u00een sezonul confortabil \u2014 copt, citit, filme, me\u0219te\u0219uguri?", "fr": "Quelle est ton activit\u00e9 cocooning pr\u00e9f\u00e9r\u00e9e \u2014 p\u00e2tisserie, lecture, films, bricolage ?", "it": "Qual \u00e8 la tua attivit\u00e0 preferita per la stagione accogliente \u2014 cucinare, leggere, maratone di film, fare lavoretti?", "fi": "Mik\u00e4 on suosikkisi mukavassa sesongissa \u2014 leipominen, lukeminen, elokuvamaratonit, k\u00e4sity\u00f6t?", "nl": "Wat is jouw favoriete knusse seizoensactiviteit \u2014 bakken, lezen, film marathons, knutselen?", "no": "Hva er din favorittkoselige sesongaktivitet \u2014 baking, lesing, film-maraton, h\u00e5ndverk?", "sv": "Vilken \u00e4r din favoritaktivitet f\u00f6r den mysiga s\u00e4songen \u2014 baka, l\u00e4sa, film-maraton, hantverk?", "pl": "Jakie jest twoje ulubione przytulne zaj\u0119cie w sezonie \u2014 pieczenie, czytanie, maratony filmowe, czy rob\u00f3tki r\u0119czne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your favorite cozy season activity — baking, reading, movie marathons, crafts?';
UPDATE questions
SET translations = '{"en": "What kind of home do you dream of living in one day?", "da": "Hvilken slags hjem dr\u00f8mmer du om at bo i en dag?", "de": "Von welchem Zuhause tr\u00e4umst du, eines Tages zu leben?", "es": "\u00bfEn qu\u00e9 tipo de casa sue\u00f1as vivir alg\u00fan d\u00eda?", "pt": "Em que tipo de casa voc\u00ea sonha em morar um dia?", "ro": "\u00cen ce fel de cas\u0103 visezi s\u0103 tr\u0103ie\u0219ti \u00eentr-o zi?", "fr": "Dans quel type de maison r\u00eaves-tu de vivre un jour ?", "it": "Che tipo di casa sogni di vivere un giorno?", "fi": "Millaisessa kodissa unelmoit asuvasi jonain p\u00e4iv\u00e4n\u00e4?", "nl": "In wat voor soort huis droom je ervan om op een dag te wonen?", "no": "Hvilken type hjem dr\u00f8mmer du om \u00e5 bo i en dag?", "sv": "Vilken typ av hem dr\u00f6mmer du om att bo i en dag?", "pl": "W jakim domu marzysz o tym, aby mieszka\u0107 pewnego dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What kind of home do you dream of living in one day?';
UPDATE questions
SET translations = '{"en": "What\u2019s the best compliment you\u2019ve ever received?", "da": "Hvad er det bedste kompliment, du nogensinde har f\u00e5et?", "de": "Was ist das beste Kompliment, das du je bekommen hast?", "es": "\u00bfCu\u00e1l es el mejor cumplido que has recibido?", "pt": "Qual \u00e9 o melhor elogio que voc\u00ea j\u00e1 recebeu?", "ro": "Care este cel mai frumos compliment pe care l-ai primit vreodat\u0103?", "fr": "Quel est le plus beau compliment que tu aies jamais re\u00e7u ?", "it": "Qual \u00e8 il miglior complimento che tu abbia mai ricevuto?", "fi": "Mik\u00e4 on paras kehu, jonka olet koskaan saanut?", "nl": "Wat is het beste compliment dat je ooit hebt gekregen?", "no": "Hva er det beste komplimentet du noen gang har f\u00e5tt?", "sv": "Vad \u00e4r den b\u00e4sta komplimang du n\u00e5gonsin har f\u00e5tt?", "pl": "Jakie jest najlepsze komplement, jaki kiedykolwiek otrzyma\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s the best compliment you’ve ever received?';
UPDATE questions
SET translations = '{"en": "What\u2019s one song that will always get you dancing, no matter where you are?", "da": "Hvilken sang f\u00e5r dig altid til at danse, uanset hvor du er?", "de": "Welches Lied bringt dich immer zum Tanzen, egal wo du bist?", "es": "\u00bfQu\u00e9 canci\u00f3n siempre te hace bailar, sin importar d\u00f3nde est\u00e9s?", "pt": "Que m\u00fasica sempre te faz dan\u00e7ar, n\u00e3o importa onde esteja?", "ro": "Ce melodie te face mereu s\u0103 dansezi, indiferent unde e\u0219ti?", "fr": "Quelle chanson te fait toujours danser, peu importe o\u00f9 tu es ?", "it": "Qual \u00e8 una canzone che ti fa sempre ballare, ovunque tu sia?", "fi": "Mik\u00e4 on yksi laulu, joka saa sinut aina tanssimaan, riippumatta siit\u00e4, miss\u00e4 olet?", "nl": "Wat is \u00e9\u00e9n nummer dat je altijd aan het dansen krijgt, waar je ook bent?", "no": "Hva er en sang som alltid f\u00e5r deg til \u00e5 danse, uansett hvor du er?", "sv": "Vilken l\u00e5t f\u00e5r dig alltid att dansa, oavsett var du \u00e4r?", "pl": "Jaka jest jedna piosenka, kt\u00f3ra zawsze sprawi, \u017ce zaczniesz ta\u0144czy\u0107, bez wzgl\u0119du na to, gdzie jeste\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s one song that will always get you dancing, no matter where you are?';
UPDATE questions
SET translations = '{"en": "Who\u2019s your favorite person to low-key stalk online?", "da": "Hvem er din yndlingsperson at \u201csnige-stalke\u201d online?", "de": "Wer ist deine Lieblingsperson, die du heimlich online verfolgst?", "es": "\u00bfQui\u00e9n es tu persona favorita para \u201cstalkear\u201d discretamente en l\u00ednea?", "pt": "Quem \u00e9 a sua pessoa favorita para \u201cseguir de leve\u201d online?", "ro": "Cine este persoana ta preferat\u0103 pe care o urm\u0103re\u0219ti discret online?", "fr": "Quelle est la personne que tu aimes secr\u00e8tement suivre en ligne ?", "it": "Chi \u00e8 la tua persona preferita da seguire in modo discreto online?", "fi": "Kuka on suosikkihenkil\u00f6si, jota seuraat salaa netiss\u00e4?", "nl": "Wie is jouw favoriete persoon om online stiekem te volgen?", "no": "Hvem er din favorittperson \u00e5 f\u00f8lge med p\u00e5 diskret p\u00e5 nettet?", "sv": "Vem \u00e4r din favoritperson att smyga p\u00e5 online?", "pl": "Kto jest twoj\u0105 ulubion\u0105 osob\u0105, kt\u00f3r\u0105 potajemnie obserwujesz w internecie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who’s your favorite person to low-key stalk online?';UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019ve done that took real courage?", "da": "Hvad har du gjort, der kr\u00e6vede \u00e6gte mod?", "de": "Was hast du getan, das echten Mut erforderte?", "es": "\u00bfQu\u00e9 has hecho que requiri\u00f3 verdadero valor?", "pt": "O que voc\u00ea fez que exigiu coragem de verdade?", "ro": "Ce ai f\u0103cut care a cerut curaj adev\u0103rat?", "fr": "Qu\u2019as-tu fait qui t\u2019a demand\u00e9 un vrai courage ?", "it": "Qualcosa che hai fatto che ha richiesto davvero coraggio?", "fi": "Mik\u00e4 on jotain, mit\u00e4 olet tehnyt, mik\u00e4 vaati todellista rohkeutta?", "nl": "Wat is iets dat je hebt gedaan dat echte moed vergde?", "no": "Hva er noe du har gjort som krevde ekte mot?", "sv": "Vad \u00e4r n\u00e5got du har gjort som kr\u00e4vde riktig mod?", "pl": "Co\u015b, co zrobi\u0142e\u015b, co wymaga\u0142o prawdziwej odwagi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you’ve done that took real courage?';
UPDATE questions
SET translations = '{"en": "What\u2019s a random skill you\u2019re oddly proud of?", "da": "Hvad er en tilf\u00e6ldig evne, du er m\u00e6rkeligt stolt af?", "de": "Welche zuf\u00e4llige F\u00e4higkeit macht dich seltsam stolz?", "es": "\u00bfQu\u00e9 habilidad aleatoria te enorgullece de forma extra\u00f1a?", "pt": "Qual habilidade aleat\u00f3ria te deixa estranhamente orgulhoso(a)?", "ro": "Care este o abilitate aleatoare de care e\u0219ti ciudat de m\u00e2ndru(\u0103)?", "fr": "Quelle comp\u00e9tence al\u00e9atoire te rend \u00e9trangement fier/fi\u00e8re ?", "it": "Qual \u00e8 una abilit\u00e0 casuale di cui sei stranamente orgoglioso?", "fi": "Mik\u00e4 on satunnainen taito, josta olet outoa ylpe\u00e4?", "nl": "Wat is een willekeurige vaardigheid waar je vreemd genoeg trots op bent?", "no": "Hva er en tilfeldig ferdighet du er merkelig stolt av?", "sv": "Vilken slumpm\u00e4ssig f\u00e4rdighet \u00e4r du konstigt stolt \u00f6ver?", "pl": "Jak\u0105\u015b przypadkow\u0105 umiej\u0119tno\u015bci\u0105, z kt\u00f3rej jeste\u015b dziwnie dumny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a random skill you’re oddly proud of?';
UPDATE questions
SET translations = '{"en": "If you could swap lives with someone for 24 hours, who would it be?", "da": "Hvis du kunne bytte liv med nogen i 24 timer, hvem skulle det v\u00e6re?", "de": "Wenn du f\u00fcr 24 Stunden mit jemandem das Leben tauschen k\u00f6nntest, wer w\u00e4re es?", "es": "Si pudieras intercambiar vidas con alguien por 24 horas, \u00bfqui\u00e9n ser\u00eda?", "pt": "Se voc\u00ea pudesse trocar de vida com algu\u00e9m por 24 horas, quem seria?", "ro": "Dac\u0103 ai putea face schimb de vie\u021bi cu cineva pentru 24 de ore, cine ar fi?", "fr": "Si tu pouvais \u00e9changer ta vie avec quelqu\u2019un pendant 24 heures, qui serait-ce ?", "it": "Se potessi scambiare la vita con qualcuno per 24 ore, chi sarebbe?", "fi": "Jos voisit vaihtaa el\u00e4m\u00e4\u00e4 jonkun kanssa 24 tunniksi, kuka se olisi?", "nl": "Als je 24 uur van leven zou kunnen ruilen met iemand, wie zou dat dan zijn?", "no": "Hvis du kunne bytte liv med noen i 24 timer, hvem ville det v\u00e6rt?", "sv": "Om du kunde byta liv med n\u00e5gon i 24 timmar, vem skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zamieni\u0107 si\u0119 \u017cyciem z kim\u015b na 24 godziny, z kim by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could swap lives with someone for 24 hours, who would it be?';
UPDATE questions
SET translations = '{"en": "If we all started a band, what would we be called?", "da": "Hvis vi alle startede et band, hvad skulle vi s\u00e5 hedde?", "de": "Wenn wir alle eine Band gr\u00fcnden w\u00fcrden, wie w\u00fcrden wir hei\u00dfen?", "es": "Si todos form\u00e1ramos una banda, \u00bfc\u00f3mo nos llamar\u00edamos?", "pt": "Se todos n\u00f3s form\u00e1ssemos uma banda, qual seria o nome?", "ro": "Dac\u0103 am forma cu to\u021bii o trup\u0103, cum s-ar numi?", "fr": "Si nous formions tous un groupe, comment s\u2019appellerait-il ?", "it": "Se tutti noi iniziassimo una band, come ci chiameremmo?", "fi": "Jos me kaikki perustaisimme b\u00e4ndin, mik\u00e4 sen nimi olisi?", "nl": "Als we allemaal een band zouden beginnen, hoe zouden we dan heten?", "no": "Hvis vi alle startet et band, hva ville vi hete?", "sv": "Om vi alla startade ett band, vad skulle vi heta?", "pl": "Je\u015bli wszyscy za\u0142o\u017cyliby\u015bmy zesp\u00f3\u0142, jak by\u015bmy si\u0119 nazywali?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If we all started a band, what would we be called?';