UPDATE questions
SET translations = '{"en": "What\u2019s one green flag you always notice right away?", "da": "Hvilket \u201cgr\u00f8nt flag\u201d l\u00e6gger du altid m\u00e6rke til med det samme?", "de": "Welche \u201egr\u00fcne Flagge\u201c bemerkst du immer sofort?", "es": "\u00bfQu\u00e9 \u201cbandera verde\u201d notas de inmediato en alguien?", "pt": "Qual \u201csinal verde\u201d voc\u00ea percebe imediatamente em algu\u00e9m?", "ro": "Ce \u201esemn verde\u201d observi imediat la cineva?", "fr": "Quel \u00ab drapeau vert \u00bb remarques-tu tout de suite chez quelqu\u2019un ?", "it": "Qual \u00e8 una bandiera verde che noti sempre subito?", "fi": "Mik\u00e4 on yksi vihre\u00e4 lippu, jonka huomaat aina heti?", "nl": "Wat is \u00e9\u00e9n groene vlag die je altijd meteen opmerkt?", "no": "Hva er en gr\u00f8nn flagg du alltid legger merke til med en gang?", "sv": "Vilken gr\u00f6n flagga l\u00e4gger du alltid m\u00e4rke till direkt?", "pl": "Jaka jest jedna pozytywna cecha, kt\u00f3r\u0105 zawsze zauwa\u017casz od razu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s one green flag you always notice right away?';
UPDATE questions
SET translations = '{"en": "If you could hear what people say about you when you\u2019re not around, would you want to?", "da": "Hvis du kunne h\u00f8re, hvad folk siger om dig, n\u00e5r du ikke er der, ville du s\u00e5 have lyst til det?", "de": "Wenn du h\u00f6ren k\u00f6nntest, was die Leute \u00fcber dich sagen, wenn du nicht da bist \u2013 w\u00fcrdest du das wollen?", "es": "Si pudieras escuchar lo que la gente dice de ti cuando no est\u00e1s, \u00bfquerr\u00edas hacerlo?", "pt": "Se voc\u00ea pudesse ouvir o que as pessoas dizem sobre voc\u00ea quando n\u00e3o est\u00e1 por perto, voc\u00ea gostaria?", "ro": "Dac\u0103 ai putea auzi ce spun oamenii despre tine c\u00e2nd nu e\u0219ti de fa\u021b\u0103, ai vrea?", "fr": "Si tu pouvais entendre ce que les gens disent de toi en ton absence, le voudrais-tu ?", "it": "Se potessi sentire cosa dicono le persone di te quando non ci sei, lo vorresti?", "fi": "Jos voisit kuulla, mit\u00e4 ihmiset sanovat sinusta, kun et ole paikalla, haluaisitko?", "nl": "Als je zou kunnen horen wat mensen over je zeggen als je er niet bent, zou je dat dan willen?", "no": "Hvis du kunne h\u00f8re hva folk sier om deg n\u00e5r du ikke er til stede, ville du \u00f8nsket det?", "sv": "Om du kunde h\u00f6ra vad folk s\u00e4ger om dig n\u00e4r du inte \u00e4r d\u00e4r, skulle du vilja det?", "pl": "Gdyby\u015b m\u00f3g\u0142 us\u0142ysze\u0107, co ludzie m\u00f3wi\u0105 o tobie, gdy ci\u0119 nie ma, czy chcia\u0142by\u015b to wiedzie\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could hear what people say about you when you’re not around, would you want to?';
UPDATE questions
SET translations = '{"en": "Who\u2019s someone that always makes you feel grounded?", "da": "Hvem f\u00e5r dig altid til at f\u00f8le dig rolig og jordn\u00e6r?", "de": "Wer bringt dich immer wieder auf den Boden der Tatsachen?", "es": "\u00bfQui\u00e9n siempre te hace sentir en calma y con los pies en la tierra?", "pt": "Quem sempre te faz se sentir calmo(a) e com os p\u00e9s no ch\u00e3o?", "ro": "Cine te face \u00eentotdeauna s\u0103 te sim\u021bi ancorat(\u0103) \u0219i lini\u0219tit(\u0103)?", "fr": "Qui te ram\u00e8ne toujours les pieds sur terre ?", "it": "Chi \u00e8 qualcuno che ti fa sempre sentire radicato?", "fi": "Kuka on joku, joka aina saa sinut tuntemaan olosi rauhalliseksi?", "nl": "Wie is iemand die je altijd een gevoel van stabiliteit geeft?", "no": "Hvem er det som alltid f\u00e5r deg til \u00e5 f\u00f8le deg forankret?", "sv": "Vem \u00e4r n\u00e5gon som alltid f\u00e5r dig att k\u00e4nna dig jordad?", "pl": "Kto\u015b, kto zawsze sprawia, \u017ce czujesz si\u0119 ugruntowany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who’s someone that always makes you feel grounded?';
UPDATE questions
SET translations = '{"en": "If you could relive one weekend with friends, which would it be?", "da": "Hvis du kunne genleve en weekend med venner, hvilken skulle det v\u00e6re?", "de": "Wenn du ein Wochenende mit Freunden noch einmal erleben k\u00f6nntest, welches w\u00e4re das?", "es": "Si pudieras revivir un fin de semana con amigos, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se voc\u00ea pudesse reviver um fim de semana com amigos, qual seria?", "ro": "Dac\u0103 ai putea retr\u0103i un weekend cu prietenii, care ar fi?", "fr": "Si tu pouvais revivre un week-end avec des amis, lequel serait-ce ?", "it": "Se potessi rivivere un weekend con gli amici, quale sarebbe?", "fi": "Jos voisit el\u00e4\u00e4 uudelleen yhden viikonlopun yst\u00e4vien kanssa, mik\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n weekend met vrienden opnieuw zou kunnen beleven, welk weekend zou dat dan zijn?", "no": "Hvis du kunne gjenoppleve en helg med venner, hvilken ville det v\u00e6rt?", "sv": "Om du kunde \u00e5teruppleva en helg med v\u00e4nner, vilken skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 prze\u017cy\u0107 jeden weekend z przyjaci\u00f3\u0142mi na nowo, kt\u00f3ry by to by\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could relive one weekend with friends, which would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite form of self-care?", "da": "Hvad er din yndlingsform for egenomsorg?", "de": "Was ist deine Lieblingsform der Selbstf\u00fcrsorge?", "es": "\u00bfCu\u00e1l es tu forma favorita de autocuidado?", "pt": "Qual \u00e9 a sua forma favorita de autocuidado?", "ro": "Care este forma ta preferat\u0103 de \u00eengrijire de sine?", "fr": "Quelle est ta forme pr\u00e9f\u00e9r\u00e9e de soin de soi ?", "it": "Qual \u00e8 la tua forma di cura di te stesso preferita?", "fi": "Mik\u00e4 on suosikkimuotosi itsest\u00e4 huolehtimiseen?", "nl": "Wat is jouw favoriete manier van zelfzorg?", "no": "Hva er din favorittform for egenpleie?", "sv": "Vad \u00e4r din favoritform av sj\u00e4lvv\u00e5rd?", "pl": "Jaka jest twoja ulubiona forma dbania o siebie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your favorite form of self-care?';
UPDATE questions
SET translations = '{"en": "Is there a hobby you do just for the joy of it? Tell us about it", "da": "Har du en hobby, du laver bare for gl\u00e6den ved det? Fort\u00e6l om det.", "de": "Hast du ein Hobby, das du nur aus Freude machst? Erz\u00e4hl davon.", "es": "\u00bfTienes un pasatiempo que haces solo por placer? Cu\u00e9ntanos.", "pt": "Voc\u00ea tem um hobby que faz apenas por prazer? Conte-nos.", "ro": "Ai un hobby pe care \u00eel faci doar din pl\u0103cere? Poveste\u0219te-ne.", "fr": "As-tu un passe-temps que tu fais juste pour le plaisir ? Parle-nous-en.", "it": "C''\u00e8 un hobby che fai solo per il piacere di farlo? Raccontaci di questo.", "fi": "Onko sinulla harrastus, jota teet vain ilon vuoksi? Kerro siit\u00e4 meille.", "nl": "Is er een hobby die je alleen voor de lol doet? Vertel ons erover.", "no": "Er det en hobby du driver med bare for glede? Fortell oss om det.", "sv": "Finns det en hobby som du g\u00f6r bara f\u00f6r n\u00f6jes skull? Ber\u00e4tta om den.", "pl": "Czy jest jakie\u015b hobby, kt\u00f3re robisz tylko dla przyjemno\u015bci? Opowiedz nam o tym."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Is there a hobby you do just for the joy of it? Tell us about it';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite comfort food?", "da": "Hvad er din yndlingskomfortmad?", "de": "Was ist dein Lieblings-Komfortessen?", "es": "\u00bfCu\u00e1l es tu comida reconfortante favorita?", "pt": "Qual \u00e9 a sua comida de conforto favorita?", "ro": "Care este m\u00e2ncarea ta preferat\u0103 de confort?", "fr": "Quel est ton plat r\u00e9confortant pr\u00e9f\u00e9r\u00e9 ?", "it": "Qual \u00e8 il tuo cibo confortito preferito?", "fi": "Mik\u00e4 on lempiruokasi, joka tuo lohtua?", "nl": "Wat is jouw favoriete troosteten?", "no": "Hva er din favoritt komfortmat?", "sv": "Vad \u00e4r din favorittr\u00f6stmat?", "pl": "Jakie jest twoje ulubione jedzenie na pocieszenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your favorite comfort food?';
UPDATE questions
SET translations = '{"en": "What\u2019s something small that you\u2019ve been grateful for lately?", "da": "Hvad er en lille ting, du har v\u00e6ret taknemmelig for for nylig?", "de": "Wof\u00fcr warst du in letzter Zeit dankbar, auch wenn es klein war?", "es": "\u00bfQu\u00e9 cosa peque\u00f1a has agradecido \u00faltimamente?", "pt": "Por qual coisa pequena voc\u00ea tem sido grato(a) ultimamente?", "ro": "Pentru ce lucru mic ai fost recunosc\u0103tor(are) \u00een ultima vreme?", "fr": "Quelle petite chose as-tu r\u00e9cemment appr\u00e9ci\u00e9e ?", "it": "Qualcosa di piccolo per cui sei stato grato ultimamente?", "fi": "Mik\u00e4 on jokin pieni asia, josta olet ollut kiitollinen viime aikoina?", "nl": "Wat is iets kleins waar je de laatste tijd dankbaar voor bent geweest?", "no": "Hva er noe lite du har v\u00e6rt takknemlig for i det siste?", "sv": "Vad \u00e4r n\u00e5got litet som du har varit tacksam f\u00f6r p\u00e5 sistone?", "pl": "Co\u015b ma\u0142ego, za co ostatnio by\u0142e\u015b wdzi\u0119czny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something small that you’ve been grateful for lately?';
UPDATE questions
SET translations = '{"en": "What do you miss most about being young?", "da": "Hvad savner du mest ved at v\u00e6re ung?", "de": "Was vermisst du am meisten daran, jung zu sein?", "es": "\u00bfQu\u00e9 extra\u00f1as m\u00e1s de ser joven?", "pt": "Do que voc\u00ea mais sente falta em ser jovem?", "ro": "Ce \u00ee\u021bi lipse\u0219te cel mai mult din tinere\u021be?", "fr": "Qu\u2019est-ce qui te manque le plus dans ta jeunesse ?", "it": "Cosa ti manca di pi\u00f9 dell''essere giovane?", "fi": "Mit\u00e4 kaipaat eniten nuoruudesta?", "nl": "Wat mis je het meest aan jong zijn?", "no": "Hva savner du mest med \u00e5 v\u00e6re ung?", "sv": "Vad saknar du mest med att vara ung?", "pl": "Czego najbardziej brakuje ci w byciu m\u0142odym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What do you miss most about being young?';
UPDATE questions
SET translations = '{"en": "Takeout edition: if we\u2019re ordering food for a cozy hang, what\u2019s your go-to choice?", "da": "Takeaway-udgave: hvis vi bestiller mad til en hyggelig aften, hvad er s\u00e5 dit go-to valg?", "de": "Take-out-Edition: Wenn wir f\u00fcr einen gem\u00fctlichen Abend Essen bestellen, was ist deine Standardwahl?", "es": "Edici\u00f3n comida para llevar: si pedimos algo para una noche tranquila, \u00bfcu\u00e1l es tu opci\u00f3n de confianza?", "pt": "Edi\u00e7\u00e3o delivery: se a gente for pedir comida para uma noite aconchegante, qual \u00e9 a sua escolha n\u00famero um?", "ro": "Edi\u021bia m\u00e2ncare la pachet: dac\u0103 comand\u0103m ceva pentru o sear\u0103 cozy, care este alegerea ta preferat\u0103?", "fr": "\u00c9dition take-out : si on commande \u00e0 manger pour une soir\u00e9e cosy, quel est ton choix num\u00e9ro un ?", "it": "Edizione da asporto: se ordiniamo cibo per una serata accogliente, qual \u00e8 la tua scelta preferita?", "fi": "Nouto-tyylill\u00e4: jos tilataan ruokaa mukavaan illanviettoon, mik\u00e4 on sinun suosikkivalintasi?", "nl": "Afhaal editie: als we eten bestellen voor een gezellige bijeenkomst, wat is jouw favoriete keuze?", "no": "Takeout-utgave: hvis vi bestiller mat for en koselig samling, hva er ditt favorittvalg?", "sv": "Takeout-utg\u00e5van: om vi best\u00e4ller mat f\u00f6r en mysig samling, vad \u00e4r ditt favoritval?", "pl": "Edycja na wynos: je\u015bli zamawiamy jedzenie na przytulne spotkanie, co jest twoim ulubionym wyborem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Takeout edition: if we’re ordering food for a cozy hang, what’s your go-to choice?';