UPDATE questions
SET translations = '{"en": "What\u2019s something people used to plan weeks ahead that we do last-minute now?", "da": "Hvad plejede folk at planl\u00e6gge uger i forvejen, som vi nu g\u00f8r i sidste \u00f8jeblik?", "de": "Was haben die Leute fr\u00fcher wochenlang im Voraus geplant, das wir jetzt in letzter Minute machen?", "es": "\u00bfQu\u00e9 planificaban las personas con semanas de anticipaci\u00f3n que ahora hacemos a \u00faltimo momento?", "pt": "O que as pessoas costumavam planear semanas antes e agora fazemos em cima da hora?", "ro": "Ce planificau oamenii cu s\u0103pt\u0103m\u00e2ni \u00eenainte, dar acum facem pe ultima sut\u0103 de metri?", "fr": "Que planifiaient autrefois les gens des semaines \u00e0 l\u2019avance et que nous faisons \u00e0 la derni\u00e8re minute maintenant ?", "it": "Qualcosa che le persone pianificavano settimane in anticipo e che ora facciamo all''ultimo minuto?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen suunnittelivat viikkoja etuk\u00e4teen, mutta teemme nyt viime hetkell\u00e4?", "nl": "Wat is iets waar mensen vroeger weken van tevoren plannen voor maakten, maar wat we nu op het laatste moment doen?", "no": "Hva er noe folk pleide \u00e5 planlegge uker i forveien, som vi n\u00e5 gj\u00f8r i siste liten?", "sv": "Vad \u00e4r n\u00e5got som folk brukade planera veckor i f\u00f6rv\u00e4g som vi g\u00f6r i sista minuten nu?", "pl": "Co\u015b, co ludzie kiedy\u015b planowali z wyprzedzeniem, a teraz robimy na ostatni\u0105 chwil\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to plan weeks ahead that we do last-minute now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that used to last longer back then, compared to nowadays?", "da": "Hvad plejede at holde l\u00e6ngere dengang, sammenlignet med nu?", "de": "Was hat fr\u00fcher l\u00e4nger gehalten als heute?", "es": "\u00bfQu\u00e9 duraba m\u00e1s antes comparado con ahora?", "pt": "O que durava mais antes comparado com agora?", "ro": "Ce \u021binea mai mult \u00eenainte, comparativ cu acum?", "fr": "Qu\u2019est-ce qui durait plus longtemps autrefois compar\u00e9 \u00e0 aujourd\u2019hui ?", "it": "Qual \u00e8 qualcosa che durava di pi\u00f9 una volta, rispetto ai giorni nostri?", "fi": "Mik\u00e4 on jotain, mik\u00e4 kesti aikaisemmin pidemp\u00e4\u00e4n verrattuna nykyp\u00e4iv\u00e4\u00e4n?", "nl": "Wat is iets dat vroeger langer meeging dan tegenwoordig?", "no": "Hva er noe som pleide \u00e5 vare lenger f\u00f8r, sammenlignet med i dag?", "sv": "Vad \u00e4r n\u00e5got som brukade h\u00e5lla l\u00e4ngre f\u00f6rr i tiden, j\u00e4mf\u00f6rt med idag?", "pl": "Co\u015b, co kiedy\u015b trwa\u0142o d\u0142u\u017cej w por\u00f3wnaniu do dzisiaj?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that used to last longer back then, compared to nowadays?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing from the \u201cgood old days\u201d you\u2019d want the next generation to experience?", "da": "Hvad er \u00e9n ting fra \u201cde gode gamle dage\u201d, du gerne vil have, at n\u00e6ste generation oplever?", "de": "Was aus den \u201eguten alten Zeiten\u201c w\u00fcrdest du der n\u00e4chsten Generation w\u00fcnschen zu erleben?", "es": "\u00bfQu\u00e9 cosa de \u201clos viejos tiempos\u201d quisieras que experimentara la pr\u00f3xima generaci\u00f3n?", "pt": "O que dos \u201cbons velhos tempos\u201d gostarias que a pr\u00f3xima gera\u00e7\u00e3o experimentasse?", "ro": "Ce lucru din \u201evremurile bune\u201d ai vrea s\u0103-l tr\u0103iasc\u0103 \u0219i urm\u0103toarea genera\u021bie?", "fr": "Quelle chose du \u201cbon vieux temps\u201d aimerais-tu que la prochaine g\u00e9n\u00e9ration connaisse ?", "it": "Qual \u00e8 una cosa dei \"bei tempi andati\" che vorresti che la prossima generazione sperimentasse?", "fi": "Mik\u00e4 on yksi asia \"hyvilt\u00e4 vanhoilta ajoilta\", jonka haluaisit seuraavan sukupolven kokevan?", "nl": "Wat is \u00e9\u00e9n ding uit de \"goede oude tijd\" dat je de volgende generatie zou willen laten ervaren?", "no": "Hva er \u00e9n ting fra \"de gode gamle dager\" du ville \u00f8nsket at neste generasjon skulle oppleve?", "sv": "Vad \u00e4r en sak fr\u00e5n de \"gamla goda dagarna\" som du skulle vilja att n\u00e4sta generation f\u00e5r uppleva?", "pl": "Co\u015b, co z \"dobrych starych czas\u00f3w\" chcia\u0142by\u015b, aby nast\u0119pne pokolenie do\u015bwiadczy\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing from the “good old days” you’d want the next generation to experience?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to argue about that no one cares about today?", "da": "Hvad plejede folk at sk\u00e6ndes om, som ingen bekymrer sig om nu?", "de": "Wor\u00fcber haben sich die Leute fr\u00fcher gestritten, was heute niemanden mehr interessiert?", "es": "\u00bfDe qu\u00e9 discut\u00eda la gente antes que hoy a nadie le importa?", "pt": "Sobre o que as pessoas discutiam antes que hoje ningu\u00e9m se importa?", "ro": "Despre ce se certau oamenii \u00eenainte \u0219i acum nu mai pas\u0103 nim\u0103nui?", "fr": "De quoi les gens se disputaient-ils autrefois et dont tout le monde se fiche aujourd\u2019hui ?", "it": "Qualcosa su cui le persone litigavano un tempo e di cui oggi a nessuno importa?", "fi": "Mik\u00e4 on jotain, mist\u00e4 ihmiset aiemmin riiteliv\u00e4t, mutta josta kukaan ei v\u00e4lit\u00e4 t\u00e4n\u00e4\u00e4n?", "nl": "Wat is iets waar mensen vroeger over discussieerden, maar waar tegenwoordig niemand zich meer druk om maakt?", "no": "Hva er noe folk pleide \u00e5 krangle om som ingen bryr seg om i dag?", "sv": "Vad \u00e4r n\u00e5got som folk brukade br\u00e5ka om men som ingen bryr sig om idag?", "pl": "O co ludzie kiedy\u015b si\u0119 k\u0142\u00f3cili, a dzi\u015b nikogo to nie obchodzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to argue about that no one cares about today?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you\u2019d show your younger self if you could time travel?", "da": "Hvad er \u00e9n ting, du ville vise dit yngre jeg, hvis du kunne rejse i tiden?", "de": "Was w\u00fcrdest du deinem j\u00fcngeren Ich zeigen, wenn du in der Zeit reisen k\u00f6nntest?", "es": "\u00bfQu\u00e9 cosa le mostrar\u00edas a tu yo m\u00e1s joven si pudieras viajar en el tiempo?", "pt": "O que mostrarias ao teu eu mais jovem se pudesses viajar no tempo?", "ro": "Ce i-ai ar\u0103ta sinelui t\u0103u mai t\u00e2n\u0103r dac\u0103 ai putea c\u0103l\u0103tori \u00een timp?", "fr": "Quelle chose montrerais-tu \u00e0 ton moi plus jeune si tu pouvais voyager dans le temps ?", "it": "Qual \u00e8 una cosa che mostreresti al tuo io pi\u00f9 giovane se potessi viaggiare nel tempo?", "fi": "Mik\u00e4 on yksi asia, jonka n\u00e4ytt\u00e4isit nuoremmalle itsellesi, jos voisit matkustaa ajassa taaksep\u00e4in?", "nl": "Wat is \u00e9\u00e9n ding dat je je jongere zelf zou laten zien als je zou kunnen tijdreizen?", "no": "Hva er \u00e9n ting du ville vist ditt yngre jeg hvis du kunne reise i tid?", "sv": "Vad \u00e4r en sak du skulle visa ditt yngre jag om du kunde resa i tiden?", "pl": "Co\u015b, co by\u015b pokaza\u0142 swojemu m\u0142odszemu ja, gdyby\u015b m\u00f3g\u0142 podr\u00f3\u017cowa\u0107 w czasie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you’d show your younger self if you could time travel?';

-- Category: Tiny Talks (75 questions)
UPDATE questions
SET translations = '{"en": "If Mom and Dad had superhero powers, what would their powers be?", "da": "Hvis mor og far havde superkr\u00e6fter, hvilke kr\u00e6fter ville de s\u00e5 have?", "de": "Wenn Mama und Papa Superkr\u00e4fte h\u00e4tten, welche Kr\u00e4fte h\u00e4tten sie dann?", "es": "Si mam\u00e1 y pap\u00e1 tuvieran superpoderes, \u00bfcu\u00e1les ser\u00edan sus poderes?", "pt": "Se a mam\u00e3e e o papai tivessem superpoderes, quais seriam seus poderes?", "ro": "Dac\u0103 mama \u0219i tata ar avea superputeri, care ar fi puterile lor?", "fr": "Si maman et papa avaient des superpouvoirs, quels seraient leurs pouvoirs ?", "it": "L\u2019app della serratura smart mostra che qualcuno ha provato quattro PIN alle 2:41 di notte. Cosa fai?", "fi": "\u00c4lylukkosovellus n\u00e4ytt\u00e4\u00e4, ett\u00e4 joku kokeili nelj\u00e4\u00e4 PIN-koodia klo 2.41 y\u00f6ll\u00e4. Mit\u00e4 teet?", "nl": "Je slimme-deurslot-app laat zien dat iemand om 2.41 uur vier pincodes heeft geprobeerd. Wat doe je?", "no": "Appen til smartl\u00e5sen viser at noen pr\u00f8vde fire PIN-koder kl. 02.41. Hva gj\u00f8r du?", "sv": "Din smartl\u00e5s-app visar att n\u00e5gon provade fyra koder kl. 2.41 p\u00e5 natten. Vad g\u00f6r du?", "pl": "Aplikacja od twojego smart-zamka pokazuje, \u017ce kto\u015b o 2:41 w nocy pr\u00f3bowa\u0142 czterech PIN-\u00f3w. Co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If Mom and Dad had superhero powers, what would their powers be?';
UPDATE questions
SET translations = '{"en": "Would you rather have wings or a tail? Why?", "da": "Ville du helst have vinger eller en hale? Hvorfor?", "de": "W\u00fcrdest du lieber Fl\u00fcgel oder einen Schwanz haben? Warum?", "es": "\u00bfPreferir\u00edas tener alas o una cola? \u00bfPor qu\u00e9?", "pt": "Preferias ter asas ou uma cauda? Por qu\u00ea?", "ro": "Ai prefera s\u0103 ai aripi sau o coad\u0103? De ce?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir des ailes ou une queue ? Pourquoi ?", "it": "Preferiresti avere ali o una coda? Perch\u00e9?", "fi": "Haluaisitko mieluummin siivet vai h\u00e4nn\u00e4n? Miksi?", "nl": "Zou je liever vleugels of een staart hebben? Waarom?", "no": "Ville du heller hatt vinger eller en hale? Hvorfor?", "sv": "Skulle du hellre ha vingar eller en svans? Varf\u00f6r?", "pl": "Czy wola\u0142by\u015b mie\u0107 skrzyd\u0142a czy ogon? Dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Would you rather have wings or a tail? Why?';
UPDATE questions
SET translations = '{"en": "What\u2019s you super snack?", "da": "A tua app da fechadura mostra que algu\u00e9m tentou quatro PINs \u00e0s 2:41. O que fazes?", "de": "Was ist dein Supersnack?", "es": "\u00bfCu\u00e1l es tu s\u00faper merienda?", "pt": "Qual \u00e9 o teu super lanche?", "ro": "Care este snack-ul tau preferat?", "fr": "Quel est ton super go\u00fbter ?", "it": "Qual \u00e8 il tuo super snack?", "fi": "Mik\u00e4 on sinun superv\u00e4lipala?", "nl": "Wat is jouw super snack?", "no": "Hva er din super-snack?", "sv": "Vad \u00e4r din super-snack?", "pl": "Jaka jest twoja ulubiona przek\u0105ska?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What’s you super snack?';
UPDATE questions
SET translations = '{"en": "If a cloud had a taste, what flavor would it have? Why?", "da": "Aplica\u021bia ta de \u00eencuietoare arat\u0103 c\u0103 cineva a \u00eencercat patru coduri la 2:41 diminea\u021ba. Ce faci?", "de": "Wenn eine Wolke einen Geschmack h\u00e4tte, welchen h\u00e4tte sie? Warum?", "es": "Si una nube tuviera sabor, \u00bfa qu\u00e9 sabr\u00eda? \u00bfPor qu\u00e9?", "pt": "Se uma nuvem tivesse sabor, qual seria? Por qu\u00ea?", "ro": "Dac\u0103 un nor ar avea gust, ce gust ar avea? De ce?", "fr": "Si un nuage avait un go\u00fbt, quel serait-il ? Pourquoi ?", "it": "Se una nuvola avesse un sapore, quale sarebbe? Perch\u00e9?", "fi": "Jos pilvell\u00e4 olisi maku, mik\u00e4 se olisi? Miksi?", "nl": "Als een wolk een smaak had, welke smaak zou het dan hebben? Waarom?", "no": "Hvis en sky hadde en smak, hvilken smak ville den hatt? Hvorfor?", "sv": "Om ett moln hade en smak, vilken smak skulle det ha? Varf\u00f6r?", "pl": "Gdyby chmura mia\u0142a smak, jaki by mia\u0142a? Dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If a cloud had a taste, what flavor would it have? Why?';
UPDATE questions
SET translations = '{"en": "If your backpack could talk, what story would it tell?", "da": "Ton application de serrure connect\u00e9e montre que quelqu\u2019un a essay\u00e9 quatre codes \u00e0 2h41. Que fais-tu ?", "de": "Wenn dein Rucksack sprechen k\u00f6nnte, welche Geschichte w\u00fcrde er erz\u00e4hlen?", "es": "Si tu mochila pudiera hablar, \u00bfqu\u00e9 historia contar\u00eda?", "pt": "Se a tua mochila pudesse falar, que hist\u00f3ria contaria?", "ro": "Dac\u0103 ghiozdanul t\u0103u ar putea vorbi, ce poveste ar spune?", "fr": "Si ton sac \u00e0 dos pouvait parler, quelle histoire raconterait-il ?", "it": "Se il tuo zaino potesse parlare, quale storia racconterebbe?", "fi": "Jos repussasi olisi \u00e4\u00e4ni, mit\u00e4 tarinaa se kertoisi?", "nl": "Als je rugzak kon praten, welk verhaal zou hij vertellen?", "no": "Hvis sekken din kunne snakke, hvilken historie ville den fortelle?", "sv": "Om din ryggs\u00e4ck kunde prata, vilken historia skulle den ber\u00e4tta?", "pl": "Gdyby tw\u00f3j plecak m\u00f3g\u0142 m\u00f3wi\u0107, jak\u0105 histori\u0119 by opowiedzia\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If your backpack could talk, what story would it tell?';