UPDATE questions
SET translations = '{"en": "What happens to ice if you leave it in the sun?", "da": "Hvad sker der med is, hvis du lader det st\u00e5 i solen?", "de": "Was passiert mit Eis, wenn du es in die Sonne legst?", "es": "\u00bfQu\u00e9 pasa con el hielo si lo dejas al sol?", "pt": "O que acontece ao gelo se o deixares ao sol?", "ro": "Ce se \u00eent\u00e2mpl\u0103 cu ghea\u021ba dac\u0103 o la\u0219i la soare?", "fr": "Que se passe-t-il avec la glace si tu la laisses au soleil ?", "it": "Cosa succede al ghiaccio se lo lasci al sole?", "fi": "Mit\u00e4 tapahtuu j\u00e4\u00e4lle, jos j\u00e4t\u00e4t sen auringonpaisteeseen?", "nl": "Wat gebeurt er met ijs als je het in de zon laat liggen?", "no": "Hva skjer med is hvis du lar det st\u00e5 i solen?", "sv": "Vad h\u00e4nder med is om du l\u00e4mnar den i solen?", "pl": "Co si\u0119 stanie z lodem, je\u015bli zostawisz go na s\u0142o\u0144cu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What happens to ice if you leave it in the sun?';
UPDATE questions
SET translations = '{"en": "What is something kind you can say to yourself?", "da": "Hvad er noget venligt, du kan sige til dig selv?", "de": "Was ist etwas Nettes, das du zu dir selbst sagen kannst?", "es": "\u00bfQu\u00e9 es algo amable que puedes decirte a ti mismo?", "pt": "O que \u00e9 algo gentil que podes dizer a ti mesmo?", "ro": "Ceva dr\u0103gu\u021b ce po\u021bi spune despre tine \u00eensu\u021bi?", "fr": "Quelle est une chose gentille que tu peux te dire \u00e0 toi-m\u00eame ?", "it": "Qualcosa di gentile che puoi dire a te stesso?", "fi": "Mik\u00e4 on jokin yst\u00e4v\u00e4llinen asia, jonka voit sanoa itsellesi?", "nl": "Wat is iets vriendelijks dat je tegen jezelf kunt zeggen?", "no": "Hva er noe snilt du kan si til deg selv?", "sv": "Vad \u00e4r n\u00e5got sn\u00e4llt du kan s\u00e4ga till dig sj\u00e4lv?", "pl": "Co\u015b mi\u0142ego, co mo\u017cesz powiedzie\u0107 sobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What is something kind you can say to yourself?';
UPDATE questions
SET translations = '{"en": "What\u2019s something funny Mom or Dad always say?", "da": "Hvad er noget sjovt, mor eller far altid siger?", "de": "Was ist etwas Lustiges, das Mama oder Papa immer sagen?", "es": "\u00bfQu\u00e9 es algo gracioso que mam\u00e1 o pap\u00e1 siempre dicen?", "pt": "O que \u00e9 algo engra\u00e7ado que a mam\u00e3e ou o papai sempre dizem?", "ro": "Ce este ceva amuzant pe care mama sau tata \u00eel spun mereu?", "fr": "Quelle est une chose dr\u00f4le que maman ou papa disent toujours ?", "it": "Qualcosa di divertente che mamma o pap\u00e0 dicono sempre?", "fi": "Mik\u00e4 on jotain hauskaa, mit\u00e4 \u00e4iti tai is\u00e4 aina sanoo?", "nl": "Wat is iets grappigs dat Mama of Papa altijd zegt?", "no": "Hva er noe morsomt som mamma eller pappa alltid sier?", "sv": "Vad \u00e4r n\u00e5got roligt som mamma eller pappa alltid s\u00e4ger?", "pl": "Co\u015b zabawnego, co zawsze m\u00f3wi Mama lub Tata?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What’s something funny Mom or Dad always say?';
UPDATE questions
SET translations = '{"en": "If you could invite an animal to dinner, which one\u2014and what would you serve?", "da": "Hvis du kunne invitere et dyr til middag, hvilket \u2014 og hvad ville du servere?", "de": "Wenn du ein Tier zum Abendessen einladen k\u00f6nntest \u2013 welches und was w\u00fcrdest du servieren?", "es": "Si pudieras invitar a un animal a cenar, \u00bfcu\u00e1l ser\u00eda y qu\u00e9 servir\u00edas?", "pt": "Se pudesses convidar um animal para jantar, qual seria \u2014 e o que servirias?", "ro": "Dac\u0103 ai putea invita un animal la cin\u0103, care ar fi \u0219i ce i-ai servi?", "fr": "Si tu pouvais inviter un animal \u00e0 d\u00eener, lequel serait-ce et que lui servirais-tu ?", "it": "Se potessi invitare un animale a cena, quale sarebbe\u2014e cosa gli serviresti?", "fi": "Jos voisit kutsua el\u00e4imen illalliselle, mink\u00e4 el\u00e4imen kutsuisit - ja mit\u00e4 tarjoaisit?", "nl": "Als je een dier zou kunnen uitnodigen voor het diner, welk dier zou dat zijn - en wat zou je serveren?", "no": "Hvis du kunne invitere et dyr til middag, hvilket ville det v\u00e6rt - og hva ville du servert?", "sv": "Om du kunde bjuda in ett djur till middag, vilket skulle det vara \u2013 och vad skulle du servera?", "pl": "Gdyby\u015b m\u00f3g\u0142 zaprosi\u0107 jakie\u015b zwierz\u0119 na kolacj\u0119, kt\u00f3re by to by\u0142o \u2013 i co by\u015b mu poda\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could invite an animal to dinner, which one—and what would you serve?';
UPDATE questions
SET translations = '{"en": "If you could help Santa for one night, what job would you do?", "da": "Hvis du kunne hj\u00e6lpe julemanden en nat, hvilket job ville du tage?", "de": "Wenn du dem Weihnachtsmann f\u00fcr eine Nacht helfen k\u00f6nntest, welchen Job w\u00fcrdest du machen?", "es": "Si pudieras ayudar a Santa por una noche, \u00bfqu\u00e9 trabajo har\u00edas?", "pt": "Se pudesses ajudar o Pai Natal por uma noite, que trabalho farias?", "ro": "Dac\u0103 l-ai putea ajuta pe Mo\u0219 Cr\u0103ciun pentru o noapte, ce slujb\u0103 ai face?", "fr": "Si tu pouvais aider le P\u00e8re No\u00ebl pendant une nuit, quel travail ferais-tu ?", "it": "Se potessi aiutare Babbo Natale per una notte, quale lavoro faresti?", "fi": "Jos voisit auttaa joulupukkia yhden y\u00f6n, mit\u00e4 ty\u00f6t\u00e4 tekisit?", "nl": "Als je \u00e9\u00e9n nacht Santa zou kunnen helpen, welke taak zou je dan doen?", "no": "Hvis du kunne hjelpe julenissen en natt, hvilken jobb ville du gjort?", "sv": "Om du kunde hj\u00e4lpa jultomten en natt, vilket jobb skulle du g\u00f6ra?", "pl": "Gdyby\u015b m\u00f3g\u0142 pom\u00f3c \u015awi\u0119temu Miko\u0142ajowi przez jedn\u0105 noc, jak\u0105 prac\u0119 by\u015b wybra\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could help Santa for one night, what job would you do?';
UPDATE questions
SET translations = '{"en": "What do you think is hard about being a grown-up?", "da": "Hvad synes du er sv\u00e6rt ved at v\u00e6re voksen?", "de": "Was findest du schwierig daran, erwachsen zu sein?", "es": "\u00bfQu\u00e9 crees que es dif\u00edcil de ser adulto?", "pt": "O que achas que \u00e9 dif\u00edcil em ser adulto?", "ro": "Ce crezi c\u0103 este greu \u00een a fi adult?", "fr": "Qu\u2019est-ce qui est difficile selon toi dans le fait d\u2019\u00eatre adulte ?", "it": "Cosa pensi sia difficile nell''essere adulti?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 aikuisena olemisessa on vaikeaa?", "nl": "Wat denk je dat moeilijk is aan volwassen zijn?", "no": "Hva synes du er vanskelig med \u00e5 v\u00e6re voksen?", "sv": "Vad tycker du \u00e4r sv\u00e5rt med att vara vuxen?", "pl": "Co my\u015blisz, \u017ce jest trudne w byciu doros\u0142ym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What do you think is hard about being a grown-up?';
UPDATE questions
SET translations = '{"en": "What do you think is awesome about being a grown-up?", "da": "Hvad synes du er sejt ved at v\u00e6re voksen?", "de": "Was findest du toll daran, erwachsen zu sein?", "es": "\u00bfQu\u00e9 crees que es genial de ser adulto?", "pt": "O que achas que \u00e9 incr\u00edvel em ser adulto?", "ro": "Ce crezi c\u0103 este grozav \u00een a fi adult?", "fr": "Qu\u2019est-ce qui est g\u00e9nial selon toi dans le fait d\u2019\u00eatre adulte ?", "it": "Cosa pensi sia fantastico nell''essere adulti?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 aikuisuudessa on mahtavaa?", "nl": "Wat vind je geweldig aan volwassen zijn?", "no": "Hva synes du er fantastisk med \u00e5 v\u00e6re voksen?", "sv": "Vad tycker du \u00e4r fantastiskt med att vara vuxen?", "pl": "Co uwa\u017casz za niesamowite w byciu doros\u0142ym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What do you think is awesome about being a grown-up?';
UPDATE questions
SET translations = '{"en": "If you had a tiny garden, what would you plant first?", "da": "Hvis du havde en lille have, hvad ville du plante f\u00f8rst?", "de": "Wenn du einen kleinen Garten h\u00e4ttest, was w\u00fcrdest du zuerst pflanzen?", "es": "Si tuvieras un jard\u00edn peque\u00f1o, \u00bfqu\u00e9 plantar\u00edas primero?", "pt": "Se tivesses um pequeno jardim, o que plantarias primeiro?", "ro": "Dac\u0103 ai avea o gr\u0103din\u0103 mic\u0103, ce ai planta mai \u00eent\u00e2i?", "fr": "Si tu avais un petit jardin, que planterais-tu en premier ?", "it": "Se avessi un piccolo giardino, cosa pianteresti per primo?", "fi": "Jos sinulla olisi pieni puutarha, mit\u00e4 istuttaisit ensin?", "nl": "Als je een kleine tuin had, wat zou je dan als eerste planten?", "no": "Hvis du hadde en liten hage, hva ville du plantet f\u00f8rst?", "sv": "Om du hade en liten tr\u00e4dg\u00e5rd, vad skulle du plantera f\u00f6rst?", "pl": "Gdyby\u015b mia\u0142 ma\u0142y ogr\u00f3dek, co by\u015b posadzi\u0142 jako pierwsze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you had a tiny garden, what would you plant first?';
UPDATE questions
SET translations = '{"en": "What would your pet ask for if it could write to Santa?", "da": "Hvad ville dit k\u00e6ledyr bede om, hvis det kunne skrive til julemanden?", "de": "Was w\u00fcrde dein Haustier sich w\u00fcnschen, wenn es dem Weihnachtsmann schreiben k\u00f6nnte?", "es": "\u00bfQu\u00e9 pedir\u00eda tu mascota si pudiera escribirle a Santa?", "pt": "O que o teu animal de estima\u00e7\u00e3o pediria se pudesse escrever ao Pai Natal?", "ro": "Ce ar cere animalul t\u0103u de companie dac\u0103 i-ar putea scrie lui Mo\u0219 Cr\u0103ciun?", "fr": "Que demanderait ton animal de compagnie s\u2019il pouvait \u00e9crire au P\u00e8re No\u00ebl ?", "it": "Cosa chiederebbe il tuo animale domestico se potesse scrivere a Babbo Natale?", "fi": "Mit\u00e4 lemmikkisi pyyt\u00e4isi, jos se voisi kirjoittaa Joulupukille?", "nl": "Wat zou jouw huisdier vragen als het een brief aan de kerstman kon schrijven?", "no": "Hva ville kj\u00e6ledyret ditt be om hvis det kunne skrive til julenissen?", "sv": "Vad skulle ditt husdjur be om om det kunde skriva till Tomten?", "pl": "Co by twoje zwierz\u0119 poprosi\u0142o, gdyby mog\u0142o napisa\u0107 do \u015awi\u0119tego Miko\u0142aja?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What would your pet ask for if it could write to Santa?';
UPDATE questions
SET translations = '{"en": "Show us how you brush your teeth. What comes first?", "da": "Vis os, hvordan du b\u00f8rster t\u00e6nder. Hvad g\u00f8r du f\u00f8rst?", "de": "Zeig uns, wie du deine Z\u00e4hne putzt. Was machst du zuerst?", "es": "Mu\u00e9stranos c\u00f3mo te cepillas los dientes. \u00bfQu\u00e9 haces primero?", "pt": "Mostra-nos como escovas os dentes. O que fazes primeiro?", "ro": "Arat\u0103-ne cum te speli pe din\u021bi. Ce faci mai \u00eent\u00e2i?", "fr": "Montre-nous comment tu te brosses les dents. Que fais-tu d\u2019abord ?", "it": "Mostraci come ti lavi i denti. Cosa fai prima?", "fi": "N\u00e4yt\u00e4 meille, miten harjaat hampaasi. Mik\u00e4 tulee ensin?", "nl": "Laat ons zien hoe je je tanden poetst. Wat komt er eerst?", "no": "Vis oss hvordan du pusser tennene. Hva kommer f\u00f8rst?", "sv": "Visa oss hur du borstar t\u00e4nderna. Vad kommer f\u00f6rst?", "pl": "Poka\u017c nam, jak myjesz z\u0119by. Co robisz najpierw?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Show us how you brush your teeth. What comes first?';