UPDATE questions
SET translations = '{"en": "What\u2019s the weirdest compliment you\u2019ve ever received?", "da": "Hvad er det m\u00e6rkeligste kompliment, du nogensinde har f\u00e5et?", "de": "Was ist das seltsamste Kompliment, das du je bekommen hast?", "es": "\u00bfCu\u00e1l es el cumplido m\u00e1s raro que has recibido?", "pt": "Qual foi o elogio mais estranho que voc\u00ea j\u00e1 recebeu?", "ro": "Care este cel mai ciudat compliment pe care l-ai primit vreodat\u0103?", "fr": "Quel est le compliment le plus \u00e9trange que tu aies re\u00e7u ?", "it": "Qual \u00e8 il complimento pi\u00f9 strano che tu abbia mai ricevuto?", "fi": "Mik\u00e4 on oudoin kohteliaisuus, jonka olet koskaan saanut?", "nl": "Wat is het vreemdste compliment dat je ooit hebt gekregen?", "no": "Hva er det rareste komplimentet du noen gang har f\u00e5tt?", "sv": "Vad \u00e4r den konstigaste komplimang du n\u00e5gonsin f\u00e5tt?", "pl": "Jaki jest najdziwniejszy komplement, jaki kiedykolwiek dosta\u0142e\u015b/dosta\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s the weirdest compliment you’ve ever received?';
UPDATE questions
SET translations = '{"en": "What skill instantly makes traveling with someone easier?", "da": "Hvilken evne g\u00f8r det \u00f8jeblikkeligt lettere at rejse med nogen?", "de": "Welche F\u00e4higkeit macht das Reisen mit jemandem sofort einfacher?", "es": "\u00bfQu\u00e9 habilidad hace que viajar con alguien sea m\u00e1s f\u00e1cil?", "pt": "Que habilidade torna viajar com algu\u00e9m instantaneamente mais f\u00e1cil?", "ro": "Ce abilitate face c\u0103l\u0103toria cu cineva imediat mai u\u0219oar\u0103?", "fr": "Quelle comp\u00e9tence rend instantan\u00e9ment un voyage \u00e0 deux plus facile ?", "it": "Quale abilit\u00e0 rende immediatamente pi\u00f9 facile viaggiare con qualcuno?", "fi": "Mik\u00e4 taito tekee matkustamisesta jonkun kanssa heti helpompaa?", "nl": "Welke vaardigheid maakt het meteen makkelijker om met iemand te reizen?", "no": "Hvilken ferdighet gj\u00f8r det med en gang lettere \u00e5 reise sammen med noen?", "sv": "Vilken f\u00f6rm\u00e5ga g\u00f6r det direkt l\u00e4ttare att resa med n\u00e5gon?", "pl": "Jaka umiej\u0119tno\u015b\u0107 od razu u\u0142atwia podr\u00f3\u017cowanie z kim\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What skill instantly makes traveling with someone easier?';
UPDATE questions
SET translations = '{"en": "Which friend or relative would make this drive hilarious\u2014and why?", "da": "Hvilken ven eller sl\u00e6gtning ville g\u00f8re denne k\u00f8retur hylende morsom \u2014 og hvorfor?", "de": "Welcher Freund oder Verwandte w\u00fcrde diese Fahrt urkomisch machen \u2013 und warum?", "es": "\u00bfQu\u00e9 amigo o familiar har\u00eda este viaje divertid\u00edsimo \u2014 y por qu\u00e9?", "pt": "Que amigo ou parente tornaria essa viagem hil\u00e1ria \u2014 e por qu\u00ea?", "ro": "Ce prieten sau rud\u0103 ar face aceast\u0103 c\u0103l\u0103torie amuzant\u0103 \u2014 \u0219i de ce?", "fr": "Quel ami ou membre de la famille rendrait ce trajet hilarant \u2014 et pourquoi ?", "it": "Quale amico o parente renderebbe questo viaggio in auto esilarante, e perch\u00e9?", "fi": "Mik\u00e4 yst\u00e4v\u00e4 tai sukulainen tekisi t\u00e4st\u00e4 ajomatkasta hulvattoman \u2013 ja miksi?", "nl": "Welke vriend of welk familielid zou deze rit hysterisch grappig maken \u2013 en waarom?", "no": "Hvilken venn eller slektning ville gjort denne bilturen hysterisk morsom \u2013 og hvorfor?", "sv": "Vilken v\u00e4n eller sl\u00e4kting skulle g\u00f6ra den h\u00e4r bilresan hysteriskt rolig \u2013 och varf\u00f6r?", "pl": "Kt\u00f3ry przyjaciel albo krewny sprawi\u0142by, \u017ce ta przeja\u017cd\u017cka by\u0142aby przezabawna \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Which friend or relative would make this drive hilarious—and why?';
UPDATE questions
SET translations = '{"en": "If you could time-capsule one everyday moment, which would you save from today?", "da": "Hvis du kunne tidskapsle \u00e9t hverdags\u00f8jeblik, hvilket ville du gemme fra i dag?", "de": "Wenn du einen Alltagsmoment in einer Zeitkapsel bewahren k\u00f6nntest, welchen w\u00fcrdest du heute speichern?", "es": "Si pudieras guardar un momento cotidiano en una c\u00e1psula del tiempo, \u00bfcu\u00e1l elegir\u00edas hoy?", "pt": "Se voc\u00ea pudesse guardar um momento comum de hoje em uma c\u00e1psula do tempo, qual seria?", "ro": "Dac\u0103 ai putea p\u0103stra un moment obi\u0219nuit de azi \u00eentr-o capsul\u0103 a timpului, care ar fi?", "fr": "Si tu pouvais mettre un moment ordinaire d\u2019aujourd\u2019hui dans une capsule temporelle, lequel choisirais-tu ?", "it": "Se potessi mettere in una capsula del tempo un momento qualsiasi di oggi, quale salveresti?", "fi": "Jos voisit laittaa aikakapseliin yhden arkisen hetken, mink\u00e4 t\u00e4m\u00e4n p\u00e4iv\u00e4n hetken valitsisit?", "nl": "Als je \u00e9\u00e9n alledaags moment in een tijdcapsule kon stoppen, welk moment van vandaag zou je kiezen?", "no": "Hvis du kunne legge ett hverdags\u00f8yeblikk i en tidskapsel, hvilket fra i dag ville du valgt?", "sv": "Om du kunde tidskapsla ett vardags\u00f6gonblick, vilket fr\u00e5n just idag skulle du spara?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a zamkn\u0105\u0107 w kapsule czasu jeden zwyk\u0142y moment, kt\u00f3ry z dzisiejszego dnia by\u015b wybra\u0142(a)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you could time-capsule one everyday moment, which would you save from today?';
UPDATE questions
SET translations = '{"en": "What\u2019s one item you always pack, even if you never end up using it?", "da": "Hvilken ting pakker du altid, selvom du aldrig ender med at bruge den?", "de": "Welchen Gegenstand packst du immer ein, auch wenn du ihn nie benutzt?", "es": "\u00bfQu\u00e9 objeto siempre empacas, aunque nunca lo uses?", "pt": "Que item voc\u00ea sempre leva, mesmo sem nunca usar?", "ro": "Ce obiect iei mereu cu tine, chiar dac\u0103 nu-l folose\u0219ti niciodat\u0103?", "fr": "Quel objet emportes-tu toujours, m\u00eame si tu ne l\u2019utilises jamais ?", "it": "Qual \u00e8 l\u2019oggetto che metti sempre in valigia, anche se poi non lo usi mai?", "fi": "Mik\u00e4 on yksi tavara, jonka pakkaat aina, vaikka et ikin\u00e4 p\u00e4\u00e4tyisi k\u00e4ytt\u00e4m\u00e4\u00e4n sit\u00e4?", "nl": "Welk item neem je altijd mee, ook al gebruik je het uiteindelijk nooit?", "no": "Hvilken ting pakker du alltid, selv om du nesten aldri ender opp med \u00e5 bruke den?", "sv": "Vilken sak packar du alltid, \u00e4ven om du aldrig anv\u00e4nder den?", "pl": "Jaki przedmiot zawsze pakujesz, nawet je\u015bli i tak go nie u\u017cywasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s one item you always pack, even if you never end up using it?';
UPDATE questions
SET translations = '{"en": "If you caught a shooting star, what wish would you send with it?", "da": "Hvis du s\u00e5 et stjerneskud, hvilket \u00f8nske ville du sende med det?", "de": "Wenn du eine Sternschnuppe siehst, welchen Wunsch w\u00fcrdest du damit senden?", "es": "Si vieras una estrella fugaz, \u00bfqu\u00e9 deseo pedir\u00edas?", "pt": "Se voc\u00ea visse uma estrela cadente, que desejo faria?", "ro": "Dac\u0103 ai vedea o stea c\u0103z\u0103toare, ce dorin\u021b\u0103 \u021bi-ai pune?", "fr": "Si tu voyais une \u00e9toile filante, quel v\u0153u ferais-tu ?", "it": "Se potessi \u201cacchiappare\u201d una stella cadente, quale desiderio le affideresti?", "fi": "Jos saisit kiinni t\u00e4hdenlennon, mink\u00e4 toiveen l\u00e4hett\u00e4isit sen mukana?", "nl": "Als je een vallende ster kon vangen, welke wens zou je ermee meesturen?", "no": "Hvis du kunne fange et stjerneskudd, hvilket \u00f8nske ville du sendt med det?", "sv": "Om du kunde f\u00e5nga ett stj\u00e4rnfall, vilken \u00f6nskan skulle du skicka med det?", "pl": "Gdyby uda\u0142o ci si\u0119 z\u0142apa\u0107 spadaj\u0105c\u0105 gwiazd\u0119, jakie \u017cyczenie by\u015b z ni\u0105 wys\u0142a\u0142(a)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If you caught a shooting star, what wish would you send with it?';
UPDATE questions
SET translations = '{"en": "Where were you the first time you saw the ocean?", "da": "Hvor var du f\u00f8rste gang, du s\u00e5 havet?", "de": "Wo warst du, als du das Meer zum ersten Mal gesehen hast?", "es": "\u00bfD\u00f3nde estabas la primera vez que viste el mar?", "pt": "Onde voc\u00ea estava quando viu o mar pela primeira vez?", "ro": "Unde erai prima dat\u0103 c\u00e2nd ai v\u0103zut marea?", "fr": "O\u00f9 \u00e9tais-tu la premi\u00e8re fois que tu as vu la mer ?", "it": "Dove eri la prima volta che hai visto l\u2019oceano?", "fi": "Miss\u00e4 olit, kun n\u00e4it meren ensimm\u00e4isen kerran?", "nl": "Waar was je de eerste keer dat je de oceaan zag?", "no": "Hvor var du f\u00f8rste gang du s\u00e5 havet?", "sv": "Var befann du dig f\u00f6rsta g\u00e5ngen du s\u00e5g havet?", "pl": "Gdzie by\u0142e\u015b/by\u0142a\u015b, gdy po raz pierwszy zobaczy\u0142e\u015b/zobaczy\u0142a\u015b ocean?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Where were you the first time you saw the ocean?';
UPDATE questions
SET translations = '{"en": "Tell a travel mishap you can laugh about now.", "da": "Fort\u00e6l om en rejsefejl, du nu kan grine af.", "de": "Erz\u00e4hl von einem Reisepatzer, \u00fcber den du jetzt lachen kannst.", "es": "Cu\u00e9ntanos un error de viaje del que ahora puedas re\u00edrte.", "pt": "Conte um erro de viagem do qual voc\u00ea ri hoje.", "ro": "Poveste\u0219te o gre\u0219eal\u0103 de c\u0103l\u0103torie de care po\u021bi r\u00e2de acum.", "fr": "Raconte une m\u00e9saventure de voyage dont tu peux rire maintenant.", "it": "Racconta un imprevisto di viaggio su cui ora riesci a ridere.", "fi": "Kerro matkak\u00f6mm\u00e4hdys, jolle voit nyky\u00e4\u00e4n jo nauraa.", "nl": "Vertel over een reisblunder waar je nu om kunt lachen.", "no": "Fortell om en reisetabbe du kan le av n\u00e5.", "sv": "Ber\u00e4tta om ett rese-misstag som du kan skratta \u00e5t nu.", "pl": "Opowiedz o wpadce z podr\u00f3\u017cy, z kt\u00f3rej dzi\u015b mo\u017cesz si\u0119 \u015bmia\u0107."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Tell a travel mishap you can laugh about now.';
UPDATE questions
SET translations = '{"en": "What\u2019s a tiny detour you\u2019ll always take\u2014view, bakery, weird statue?", "da": "Hvilken lille omvej vil du altid tage \u2014 udsigt, bageri, m\u00e6rkelig statue?", "de": "Welchen kleinen Umweg nimmst du immer \u2013 Aussicht, B\u00e4ckerei, seltsame Statue?", "es": "\u00bfQu\u00e9 peque\u00f1o desv\u00edo siempre tomas \u2014 una vista, panader\u00eda o estatua rara?", "pt": "Que pequeno desvio voc\u00ea sempre faz \u2014 vista, padaria, est\u00e1tua estranha?", "ro": "Ce mic ocol faci mereu \u2014 o priveli\u0219te, o brut\u0103rie, o statuie ciudat\u0103?", "fr": "Quel petit d\u00e9tour fais-tu toujours \u2014 vue, boulangerie, statue \u00e9trange ?", "it": "Quale piccola deviazione farai sempre volentieri \u2013 per un bel panorama, una panetteria, una statua strana\u2026?", "fi": "Mink\u00e4 pienen ylim\u00e4\u00e4r\u00e4isen koukkauksen teet aina \u2013 n\u00e4k\u00f6alapaikan, leipomon vai jonkin oudon patsaan takia?", "nl": "Wat is een kleine omweg die je altijd maakt \u2013 voor uitzicht, bakkerij, of een raar standbeeld?", "no": "Hvilken liten omvei tar du alltid \u2013 for utsikten, et bakeri, en rar statue?", "sv": "Vilken liten omv\u00e4g tar du alltid \u2013 f\u00f6r utsikten, ett bageri, en konstig staty?", "pl": "Jak\u0105 ma\u0142\u0105 nadk\u0142adk\u0119 drogi zawsze zrobisz \u2013 dla widoku, piekarni, dziwnego pomnika?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a tiny detour you’ll always take—view, bakery, weird statue?';UPDATE questions
SET translations = '{"en": "If we ran a tiny bed-and-breakfast, what would guests remember most?", "da": "Hvis vi drev et lille bed-and-breakfast, hvad ville g\u00e6sterne huske bedst?", "de": "Wenn wir ein kleines Bed-and-Breakfast h\u00e4tten, woran w\u00fcrden sich die G\u00e4ste am meisten erinnern?", "es": "Si dirigi\u00e9ramos un peque\u00f1o bed and breakfast, \u00bfqu\u00e9 recordar\u00edan m\u00e1s los hu\u00e9spedes?", "pt": "Se tiv\u00e9ssemos uma pousada, do que os h\u00f3spedes se lembrariam mais?", "ro": "Dac\u0103 am avea un mic bed-and-breakfast, ce ar \u021bine minte oaspe\u021bii?", "fr": "Si nous tenions une petite chambre d\u2019h\u00f4tes, de quoi les invit\u00e9s se souviendraient-ils le plus ?", "it": "Se gestissimo un piccolo bed & breakfast, che cosa ricorderebbero di pi\u00f9 gli ospiti?", "fi": "Jos pit\u00e4isimme pient\u00e4 bed & breakfastia, mink\u00e4 vieraat muistaisivat meist\u00e4 parhaiten?", "nl": "Als wij een klein bed & breakfast zouden runnen, wat zouden gasten zich dan het meest van ons herinneren?", "no": "Hvis vi drev et lite bed & breakfast, hva tror du gjestene ville husket best?", "sv": "Om vi drev ett litet bed and breakfast, vad skulle g\u00e4sterna minnas mest?", "pl": "Gdyby\u015bmy prowadzili ma\u0142y pensjonat typu bed & breakfast, co go\u015bcie zapami\u0119taliby najbardziej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If we ran a tiny bed-and-breakfast, what would guests remember most?';
UPDATE questions
SET translations = '{"en": "If our car had a personality, what would its love language be?", "da": "Hvis vores bil havde en personlighed, hvad ville dens k\u00e6rlighedssprog v\u00e6re?", "de": "Wenn unser Auto eine Pers\u00f6nlichkeit h\u00e4tte, welche Liebessprache h\u00e4tte es?", "es": "Si nuestro coche tuviera personalidad, \u00bfcu\u00e1l ser\u00eda su lenguaje del amor?", "pt": "Se nosso carro tivesse personalidade, qual seria sua linguagem do amor?", "ro": "Dac\u0103 ma\u0219ina noastr\u0103 ar avea o personalitate, care ar fi limbajul ei al iubirii?", "fr": "Si notre voiture avait une personnalit\u00e9, quel serait son langage de l\u2019amour ?", "it": "Se la nostra macchina avesse una personalit\u00e0, quale sarebbe il suo linguaggio dell\u2019amore?", "fi": "Jos meid\u00e4n autolla olisi persoona, mik\u00e4 olisi sen rakkauden kieli?", "nl": "Als onze auto een persoonlijkheid had, wat zou zijn liefdestaal zijn?", "no": "Hvis bilen v\u00e5r hadde en personlighet, hva ville kj\u00e6rlighetsspr\u00e5ket dens v\u00e6rt?", "sv": "Om v\u00e5r bil hade en personlighet, vilket skulle dess k\u00e4rleksspr\u00e5k vara?", "pl": "Gdyby nasz samoch\u00f3d mia\u0142 osobowo\u015b\u0107, jakim \u201ej\u0119zykiem mi\u0142o\u015bci\u201d by si\u0119 pos\u0142ugiwa\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'If our car had a personality, what would its love language be?';