UPDATE questions
SET translations = '{"en": "What\u2019s a piece of advice you\u2019re glad you ignored?", "da": "Hvilket r\u00e5d er du glad for, at du ignorerede?", "de": "Welchen Rat bist du froh, ignoriert zu haben?", "es": "\u00bfQu\u00e9 consejo te alegra haber ignorado?", "pt": "Que conselho voc\u00ea est\u00e1 feliz por ter ignorado?", "ro": "Ce sfat te bucuri c\u0103 ai ignorat?", "fr": "Quel conseil es-tu heureux(se) d\u2019avoir ignor\u00e9 ?", "it": "Qual \u00e8 un consiglio che sei contento di aver ignorato?", "fi": "Mik\u00e4 on neuvo, josta olet iloinen, ett\u00e4 ignoroit sen?", "nl": "Wat is een advies dat je blij bent dat je hebt genegeerd?", "no": "Hva er et r\u00e5d du er glad for at du ignorerte?", "sv": "Vilket r\u00e5d \u00e4r du glad att du ignorerade?", "pl": "Jak\u0105 rad\u0119 cieszysz si\u0119, \u017ce zignorowa\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s a piece of advice you’re glad you ignored?';
UPDATE questions
SET translations = '{"en": "What part of getting older are you looking forward to?", "da": "Hvilken del af at blive \u00e6ldre ser du mest frem til?", "de": "Auf welchen Teil des \u00c4lterwerdens freust du dich am meisten?", "es": "\u00bfQu\u00e9 parte de envejecer esperas con m\u00e1s ilusi\u00f3n?", "pt": "De qual parte de envelhecer voc\u00ea mais espera?", "ro": "La ce parte a \u00eemb\u0103tr\u00e2nirii a\u0219tep\u021bi cu bucurie?", "fr": "Quelle partie du fait de vieillir attends-tu avec le plus d\u2019impatience ?", "it": "Quale aspetto dell''invecchiare non vedi l''ora di affrontare?", "fi": "Mist\u00e4 vanhenemisessa odotat eniten?", "nl": "Waar kijk je naar uit als het gaat om ouder worden?", "no": "Hvilken del av \u00e5 bli eldre ser du frem til?", "sv": "Vilken del av att bli \u00e4ldre ser du fram emot?", "pl": "Na kt\u00f3r\u0105 cz\u0119\u015b\u0107 starzenia si\u0119 czekasz z niecierpliwo\u015bci\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What part of getting older are you looking forward to?';
UPDATE questions
SET translations = '{"en": "How can I better show that I\u2019m in your corner, no matter what?", "da": "Hvordan kan jeg bedre vise, at jeg altid er p\u00e5 din side?", "de": "Wie kann ich besser zeigen, dass ich immer auf deiner Seite bin?", "es": "\u00bfC\u00f3mo puedo mostrarte mejor que siempre estoy de tu lado?", "pt": "Como posso mostrar melhor que estou sempre ao seu lado?", "ro": "Cum pot ar\u0103ta mai bine c\u0103 sunt mereu de partea ta?", "fr": "Comment puis-je mieux te montrer que je suis toujours de ton c\u00f4t\u00e9 ?", "it": "Come posso dimostrare meglio che sono dalla tua parte, qualunque cosa accada?", "fi": "Miten voisin paremmin osoittaa, ett\u00e4 olen tukenasi, riippumatta siit\u00e4, mit\u00e4 tapahtuu?", "nl": "Hoe kan ik beter laten zien dat ik aan jouw kant sta, wat er ook gebeurt?", "no": "Hvordan kan jeg bedre vise at jeg st\u00e5r p\u00e5 din side, uansett hva?", "sv": "Hur kan jag b\u00e4ttre visa att jag st\u00e5r p\u00e5 din sida, oavsett vad?", "pl": "Jak mog\u0119 lepiej pokaza\u0107, \u017ce zawsze stoj\u0119 po twojej stronie, bez wzgl\u0119du na wszystko?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How can I better show that I’m in your corner, no matter what?';
UPDATE questions
SET translations = '{"en": "Which memory reminds you that you\u2019re resilient?", "da": "Hvilket minde minder dig om, at du er modstandsdygtig?", "de": "Welche Erinnerung erinnert dich daran, dass du widerstandsf\u00e4hig bist?", "es": "\u00bfQu\u00e9 recuerdo te recuerda que eres resiliente?", "pt": "Que lembran\u00e7a te lembra que voc\u00ea \u00e9 resiliente?", "ro": "Ce amintire \u00ee\u021bi aminte\u0219te c\u0103 e\u0219ti rezistent(\u0103)?", "fr": "Quel souvenir te rappelle que tu es r\u00e9silient(e) ?", "it": "Quale ricordo ti ricorda che sei resiliente?", "fi": "Mik\u00e4 muisto muistuttaa sinua siit\u00e4, ett\u00e4 olet kest\u00e4v\u00e4?", "nl": "Welke herinnering herinnert je eraan dat je veerkrachtig bent?", "no": "Hvilket minne minner deg om at du er motstandsdyktig?", "sv": "Vilket minne p\u00e5minner dig om att du \u00e4r motst\u00e5ndskraftig?", "pl": "Kt\u00f3ra pami\u0119\u0107 przypomina ci, \u017ce jeste\u015b odporny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Which memory reminds you that you’re resilient?';
UPDATE questions
SET translations = '{"en": "What would Past-You thank Present-You for?", "da": "Hvad ville Fortids-Dig takke Nutids-Dig for?", "de": "Wof\u00fcr w\u00fcrde dein Vergangenheits-Ich deinem Gegenwarts-Ich danken?", "es": "\u00bfPor qu\u00e9 te agradecer\u00eda tu Yo del pasado?", "pt": "Pelo que o Seu Eu do Passado agradeceria ao Seu Eu do Presente?", "ro": "Pentru ce \u021bi-ar mul\u021bumi Sinele t\u0103u din trecut?", "fr": "Pour quoi ton Toi du pass\u00e9 remercierait-il ton Toi du pr\u00e9sent ?", "it": "Per cosa ringrazierebbe il Passato-Te il Presente-Te?", "fi": "Mit\u00e4 menneisyydess\u00e4 oleva sin\u00e4 kiitt\u00e4isi nykyisyydess\u00e4 olevaa sinua?", "nl": "Waarvoor zou het verleden-Jij het heden-Jij bedanken?", "no": "Hva ville Fortid-Du takket N\u00e5tid-Du for?", "sv": "Vad skulle det f\u00f6rflutna du tacka nuvarande du f\u00f6r?", "pl": "Za co przesz\u0142e \"Ty\" podzi\u0119kowa\u0142by tera\u017aniejszemu \"Ty\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What would Past-You thank Present-You for?';
UPDATE questions
SET translations = '{"en": "Name one thing worth being patient for?", "da": "N\u00e6vn \u00e9n ting, der er v\u00e6rd at v\u00e6re t\u00e5lmodig for.", "de": "Nenne eine Sache, f\u00fcr die es sich lohnt, geduldig zu sein.", "es": "Nombra una cosa por la que valga la pena ser paciente.", "pt": "Diga uma coisa pela qual vale a pena ser paciente.", "ro": "Nume\u0219te un lucru pentru care merit\u0103 s\u0103 fii r\u0103bd\u0103tor(are).", "fr": "Nomme une chose qui vaut la peine d\u2019\u00eatre patient(e).", "it": "Nomina una cosa per cui valga la pena avere pazienza?", "fi": "Nime\u00e4 yksi asia, jota kannattaa odottaa k\u00e4rsiv\u00e4llisesti?", "nl": "Noem \u00e9\u00e9n ding waar het de moeite waard is om geduldig voor te zijn?", "no": "Nevn \u00e9n ting som er verdt \u00e5 v\u00e6re t\u00e5lmodig for?", "sv": "N\u00e4mn en sak som \u00e4r v\u00e4rd att vara t\u00e5lmodig f\u00f6r?", "pl": "Wymie\u0144 jedn\u0105 rzecz, na kt\u00f3r\u0105 warto czeka\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Name one thing worth being patient for?';
UPDATE questions
SET translations = '{"en": "What kind of intimacy makes you feel closest to me?", "da": "Hvilken form for intimitet f\u00e5r dig til at f\u00f8le dig t\u00e6ttest p\u00e5 mig?", "de": "Welche Art von Intimit\u00e4t l\u00e4sst dich mir am n\u00e4chsten f\u00fchlen?", "es": "\u00bfQu\u00e9 tipo de intimidad te hace sentir m\u00e1s cerca de m\u00ed?", "pt": "Que tipo de intimidade faz voc\u00ea se sentir mais pr\u00f3ximo(a) de mim?", "ro": "Ce tip de intimitate te face s\u0103 te sim\u021bi cel mai aproape de mine?", "fr": "Quel type d\u2019intimit\u00e9 te fait te sentir le plus proche de moi ?", "it": "Che tipo di intimit\u00e0 ti fa sentire pi\u00f9 vicino a me?", "fi": "Mink\u00e4laista l\u00e4heisyytt\u00e4 tunnet, ett\u00e4 se tuo meid\u00e4t l\u00e4himm\u00e4ksi toisiamme?", "nl": "Welke vorm van intimiteit laat je je het dichtst bij mij voelen?", "no": "Hvilken type intimitet f\u00e5r deg til \u00e5 f\u00f8le deg n\u00e6rmest meg?", "sv": "Vilken typ av intimitet f\u00e5r dig att k\u00e4nna dig n\u00e4rmast mig?", "pl": "Jakiego rodzaju intymno\u015b\u0107 sprawia, \u017ce czujesz si\u0119 ze mn\u0105 najbli\u017cej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What kind of intimacy makes you feel closest to me?';
UPDATE questions
SET translations = '{"en": "What\u2019s a tiny practice that improves your mental health?", "da": "Hvilken lille vane forbedrer dit mentale helbred?", "de": "Welche kleine Gewohnheit verbessert deine psychische Gesundheit?", "es": "\u00bfQu\u00e9 peque\u00f1a pr\u00e1ctica mejora tu salud mental?", "pt": "Que pequeno h\u00e1bito melhora sua sa\u00fade mental?", "ro": "Ce mic obicei \u00ee\u021bi \u00eembun\u0103t\u0103\u021be\u0219te s\u0103n\u0103tatea mental\u0103?", "fr": "Quelle petite habitude am\u00e9liore ta sant\u00e9 mentale ?", "it": "Qual \u00e8 una piccola pratica che migliora la tua salute mentale?", "fi": "Mik\u00e4 on pieni k\u00e4yt\u00e4nt\u00f6, joka parantaa mielenterveytt\u00e4si?", "nl": "Wat is een kleine gewoonte die je mentale gezondheid verbetert?", "no": "Hva er en liten praksis som forbedrer din mentale helse?", "sv": "Vilken liten vana f\u00f6rb\u00e4ttrar din mentala h\u00e4lsa?", "pl": "Jaka ma\u0142a praktyka poprawia twoje zdrowie psychiczne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s a tiny practice that improves your mental health?';
UPDATE questions
SET translations = '{"en": "What is your relationship to jealousy \u2013 and why do you think it is so?", "da": "Hvilket forhold har du til jalousi \u2014 og hvorfor tror du, det er s\u00e5dan?", "de": "Welche Beziehung hast du zur Eifersucht \u2013 und warum glaubst du, ist das so?", "es": "\u00bfCu\u00e1l es tu relaci\u00f3n con los celos \u2014 y por qu\u00e9 crees que es as\u00ed?", "pt": "Qual \u00e9 a sua rela\u00e7\u00e3o com o ci\u00fame \u2014 e por que acha que \u00e9 assim?", "ro": "Care este rela\u021bia ta cu gelozia \u2014 \u0219i de ce crezi c\u0103 este a\u0219a?", "fr": "Quelle est ta relation \u00e0 la jalousie \u2014 et pourquoi penses-tu qu\u2019elle est ainsi ?", "it": "Qual \u00e8 il tuo rapporto con la gelosia \u2013 e perch\u00e9 pensi che sia cos\u00ec?", "fi": "Mik\u00e4 on suhteesi mustasukkaisuuteen \u2013 ja miksi luulet niin olevan?", "nl": "Wat is jouw relatie tot jaloezie \u2013 en waarom denk je dat het zo is?", "no": "Hva er ditt forhold til sjalusi \u2013 og hvorfor tror du det er slik?", "sv": "Vad \u00e4r din relation till svartsjuka \u2013 och varf\u00f6r tror du att det \u00e4r s\u00e5?", "pl": "Jaki jest tw\u00f3j zwi\u0105zek z zazdro\u015bci\u0105 \u2013 i dlaczego tak my\u015blisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What is your relationship to jealousy – and why do you think it is so?';
UPDATE questions
SET translations = '{"en": "When do you feel time slow down?", "da": "Hvorn\u00e5r f\u00f8ler du, at tiden g\u00e5r langsommere?", "de": "Wann hast du das Gef\u00fchl, dass die Zeit langsamer vergeht?", "es": "\u00bfCu\u00e1ndo sientes que el tiempo se desacelera?", "pt": "Quando voc\u00ea sente que o tempo desacelera?", "ro": "C\u00e2nd sim\u021bi c\u0103 timpul \u00eencetine\u0219te?", "fr": "Quand as-tu l\u2019impression que le temps ralentit ?", "it": "Quando senti che il tempo rallenta?", "fi": "Milloin tunnet ajan hidastuvan?", "nl": "Wanneer voel je dat de tijd langzamer gaat?", "no": "N\u00e5r f\u00f8ler du at tiden g\u00e5r saktere?", "sv": "N\u00e4r k\u00e4nner du att tiden saktar ner?", "pl": "Kiedy czujesz, \u017ce czas zwalnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When do you feel time slow down?';