UPDATE questions
SET translations = '{"en": "If your name had to be something else, what would you pick?", "da": "Hvis dit navn skulle v\u00e6re noget andet, hvad ville du v\u00e6lge?", "de": "Wenn dein Name etwas anderes sein m\u00fcsste, was w\u00fcrdest du w\u00e4hlen?", "es": "Si tu nombre tuviera que ser otro, \u00bfcu\u00e1l elegir\u00edas?", "pt": "Se o teu nome tivesse de ser outro, qual escolherias?", "ro": "Dac\u0103 numele t\u0103u ar trebui s\u0103 fie altul, ce ai alege?", "fr": "Si ton pr\u00e9nom devait \u00eatre autre, lequel choisirais-tu ?", "it": "Se il tuo nome dovesse essere un altro, quale sceglieresti?", "fi": "Jos nimesi pit\u00e4isi olla jotain muuta, mit\u00e4 valitsisit?", "nl": "Als je naam iets anders moest zijn, wat zou je dan kiezen?", "no": "Hvis navnet ditt m\u00e5tte v\u00e6re noe annet, hva ville du valgt?", "sv": "Om ditt namn skulle vara n\u00e5got annat, vad skulle du v\u00e4lja?", "pl": "Gdyby\u015b musia\u0142 mie\u0107 inne imi\u0119, jakie by\u015b wybra\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'If your name had to be something else, what would you pick?';
UPDATE questions
SET translations = '{"en": "What\u2019s a drink that gives you instant flashbacks?", "da": "Hvilken drink giver dig \u00f8jeblikkelige flashbacks?", "de": "Welches Getr\u00e4nk l\u00f6st bei dir sofort Flashbacks aus?", "es": "\u00bfQu\u00e9 bebida te da flashbacks instant\u00e1neos?", "pt": "Que bebida te d\u00e1 flashbacks instant\u00e2neos?", "ro": "Ce b\u0103utur\u0103 \u00ee\u021bi provoac\u0103 instantaneu amintiri intense?", "fr": "Quelle boisson te donne instantan\u00e9ment des flashbacks ?", "it": "Qual \u00e8 una bevanda che ti fa avere flashback istantanei?", "fi": "Mik\u00e4 juoma tuo sinulle heti mieleen muistoja?", "nl": "Wat is een drankje dat je directe flashbacks geeft?", "no": "Hva er en drink som gir deg umiddelbare tilbakeblikk?", "sv": "Vilken dryck ger dig omedelbara flashbacks?", "pl": "Jaki nap\u00f3j wywo\u0142uje u ciebie natychmiastowe wspomnienia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s a drink that gives you instant flashbacks?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to start something crazy and convince everyone to join?", "da": "Hvem er mest sandsynligt til at starte noget vildt og overbevise alle om at deltage?", "de": "Wer startet am ehesten etwas Verr\u00fccktes und \u00fcberzeugt alle mitzumachen?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que empiece algo loco y convenza a todos de unirse?", "pt": "Quem \u00e9 mais prov\u00e1vel come\u00e7ar algo louco e convencer todos a participar?", "ro": "Cine e cel mai probabil s\u0103 \u00eenceap\u0103 ceva nebunesc \u0219i s\u0103 conving\u0103 pe toat\u0103 lumea s\u0103 se al\u0103ture?", "fr": "Qui est le plus susceptible de lancer quelque chose de fou et de convaincre tout le monde de le suivre ?", "it": "Chi \u00e8 pi\u00f9 probabile che inizi qualcosa di folle e convinca tutti a unirsi?", "fi": "Kuka todenn\u00e4k\u00f6isesti aloittaa jotain hullua ja saa kaikki mukaan?", "nl": "Wie is het meest waarschijnlijk om iets gek te beginnen en iedereen te overtuigen om mee te doen?", "no": "Hvem er mest sannsynlig til \u00e5 starte noe spr\u00f8tt og overbevise alle om \u00e5 bli med?", "sv": "Vem \u00e4r mest ben\u00e4gen att starta n\u00e5got galet och \u00f6vertyga alla att h\u00e4nga p\u00e5?", "pl": "Kto najprawdopodobniej zacznie co\u015b szalonego i przekona wszystkich do do\u0142\u0105czenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to start something crazy and convince everyone to join?';
UPDATE questions
SET translations = '{"en": "What\u2019s your most unexplainable fear or superstition?", "da": "Hvad er din mest uforklarlige frygt eller overtro?", "de": "Was ist deine unerkl\u00e4rlichste Angst oder Aberglaube?", "es": "\u00bfCu\u00e1l es tu miedo o superstici\u00f3n m\u00e1s inexplicable?", "pt": "Qual \u00e9 o teu medo ou supersti\u00e7\u00e3o mais inexplic\u00e1vel?", "ro": "Care este frica sau supersti\u021bia ta cea mai de neexplicat?", "fr": "Quelle est ta peur ou superstition la plus inexplicable ?", "it": "Qual \u00e8 la tua paura o superstizione pi\u00f9 inspiegabile?", "fi": "Mik\u00e4 on sinun selitt\u00e4m\u00e4tt\u00f6min pelkosi tai taikausko?", "nl": "Wat is jouw meest onverklaarbare angst of bijgeloof?", "no": "Hva er din mest uforst\u00e5elige frykt eller overtro?", "sv": "Vad \u00e4r din mest of\u00f6rklarliga r\u00e4dsla eller superstition?", "pl": "Jakie jest twoje najbardziej niewyt\u0142umaczalne l\u0119ki lub przes\u0105dy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your most unexplainable fear or superstition?';
UPDATE questions
SET translations = '{"en": "What\u2019s your usual catchphrase? Does it work?", "da": "Hvad er dit s\u00e6dvanlige catchphrase? Virker det?", "de": "Was ist dein typischer Spruch? Funktioniert er?", "es": "\u00bfCu\u00e1l es tu frase t\u00edpica? \u00bfFunciona?", "pt": "Qual \u00e9 a tua frase t\u00edpica? Funciona?", "ro": "Care este expresia ta obi\u0219nuit\u0103? Func\u021bioneaz\u0103?", "fr": "Quelle est ta phrase f\u00e9tiche ? Est-ce qu\u2019elle marche ?", "it": "Qual \u00e8 il tuo solito motto? Funziona?", "fi": "Mik\u00e4 on tavallinen iskulauseesi? Toimiiko se?", "nl": "Wat is jouw gebruikelijke catchphrase? Werkt het?", "no": "Hva er ditt vanlige slagord? Fungerer det?", "sv": "Vad \u00e4r ditt vanliga motto? Fungerar det?", "pl": "Jakie jest twoje zwyk\u0142e powiedzenie? Dzia\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s your usual catchphrase? Does it work?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you always overthink that doesn\u2019t matter at all?", "da": "Hvad er noget, du altid overt\u00e6nker, som slet ikke betyder noget?", "de": "Was ist etwas, das du immer \u00fcberdenkst, obwohl es \u00fcberhaupt keine Rolle spielt?", "es": "\u00bfQu\u00e9 cosa sobrepiensas siempre que en realidad no importa?", "pt": "O que \u00e9 algo que pensas demais mas n\u00e3o tem import\u00e2ncia nenhuma?", "ro": "Ce este ceva ce analizezi prea mult, de\u0219i nu conteaz\u0103 deloc?", "fr": "Quelle est la chose que tu ressasses toujours alors qu\u2019elle n\u2019a aucune importance ?", "it": "Qual \u00e8 una cosa su cui pensi sempre troppo e che in realt\u00e0 non ha importanza?", "fi": "Mik\u00e4 on jotain, mit\u00e4 aina murehdit liikaa, vaikka sill\u00e4 ei ole mit\u00e4\u00e4n merkityst\u00e4?", "nl": "Wat is iets waar je altijd te veel over nadenkt dat helemaal niet belangrijk is?", "no": "Hva er noe du alltid overtenker som ikke betyr noe i det hele tatt?", "sv": "Vad \u00e4r n\u00e5got du alltid \u00f6veranalyserar som egentligen inte spelar n\u00e5gon roll?", "pl": "Co\u015b, co zawsze za bardzo analizujesz, a tak naprawd\u0119 nie ma znaczenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s something you always overthink that doesn’t matter at all?';
UPDATE questions
SET translations = '{"en": "What\u2019s one rule your parents had that you\u2019ll never understand?", "da": "Hvad er \u00e9n regel, dine for\u00e6ldre havde, som du aldrig har forst\u00e5et?", "de": "Welche Regel deiner Eltern hast du nie verstanden?", "es": "\u00bfQu\u00e9 regla de tus padres nunca entendiste?", "pt": "Que regra dos teus pais nunca compreendeste?", "ro": "Ce regul\u0103 a p\u0103rin\u021bilor t\u0103i nu ai \u00een\u021beles niciodat\u0103?", "fr": "Quelle r\u00e8gle de tes parents n\u2019as-tu jamais comprise ?", "it": "Qual \u00e8 una regola che i tuoi genitori avevano e che non capirai mai?", "fi": "Mik\u00e4 on yksi s\u00e4\u00e4nt\u00f6, jonka vanhempasi asettivat, jota et koskaan tule ymm\u00e4rt\u00e4m\u00e4\u00e4n?", "nl": "Wat is \u00e9\u00e9n regel die je ouders hadden die je nooit zult begrijpen?", "no": "Hva er en regel foreldrene dine hadde som du aldri vil forst\u00e5?", "sv": "Vilken regel hade dina f\u00f6r\u00e4ldrar som du aldrig kommer att f\u00f6rst\u00e5?", "pl": "Jakie jest jedno zasada, kt\u00f3r\u0105 twoi rodzice mieli, a kt\u00f3rej nigdy nie zrozumiesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s one rule your parents had that you’ll never understand?';
UPDATE questions
SET translations = '{"en": "What\u2019s you favorite drinking game (or alt\u2011game)?", "da": "Hvad er dit yndlingsdrikkespil (eller alternativt spil)?", "de": "Was ist dein Lieblings-Trinkspiel (oder Alternativspiel)?", "es": "\u00bfCu\u00e1l es tu juego de beber favorito (o juego alternativo)?", "pt": "Qual \u00e9 o teu jogo de beber favorito (ou jogo alternativo)?", "ro": "Care este jocul t\u0103u preferat de b\u0103ut (sau alternativ)?", "fr": "Quel est ton jeu \u00e0 boire pr\u00e9f\u00e9r\u00e9 (ou jeu alternatif) ?", "it": "Qual \u00e8 il tuo gioco da bere (o gioco alternativo) preferito?", "fi": "Mik\u00e4 on suosikkijuomapeli (tai vaihtoehtopeli)si?", "nl": "Wat is je favoriete drinkspel (of alternatief spel)?", "no": "Hva er ditt favorittdrikkelek (eller alternativspill)?", "sv": "Vilket \u00e4r ditt favoritdryckespel (eller alternativspel)?", "pl": "Jaka jest twoja ulubiona gra pijacka (lub alternatywna gra)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'What’s you favorite drinking game (or alt‑game)?';
UPDATE questions
SET translations = '{"en": "If you could time-travel 10 years into the future, what would you hope to see?", "da": "Hvis du kunne rejse 10 \u00e5r frem i tiden, hvad ville du h\u00e5be at se?", "de": "Wenn du 10 Jahre in die Zukunft reisen k\u00f6nntest, was w\u00fcrdest du hoffen zu sehen?", "es": "Si pudieras viajar 10 a\u00f1os al futuro, \u00bfqu\u00e9 esperar\u00edas ver?", "pt": "Se pudesses viajar 10 anos no futuro, o que esperarias ver?", "ro": "Dac\u0103 ai putea c\u0103l\u0103tori 10 ani \u00een viitor, ce ai spera s\u0103 vezi?", "fr": "Si tu pouvais voyager 10 ans dans le futur, qu\u2019esp\u00e9rerais-tu voir ?", "it": "Se potessi viaggiare nel tempo di dieci anni nel futuro, cosa spereresti di vedere?", "fi": "Jos voisit matkustaa ajassa 10 vuotta tulevaisuuteen, mit\u00e4 toivoisit n\u00e4kev\u00e4si?", "nl": "Als je 10 jaar in de toekomst zou kunnen tijdreizen, wat hoop je dan te zien?", "no": "Hvis du kunne reise ti \u00e5r frem i tid, hva h\u00e5per du \u00e5 se?", "sv": "Om du kunde resa i tiden 10 \u00e5r in i framtiden, vad skulle du hoppas f\u00e5 se?", "pl": "Gdyby\u015b m\u00f3g\u0142 podr\u00f3\u017cowa\u0107 w czasie o 10 lat do przodu, co by\u015b chcia\u0142 zobaczy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'If you could time-travel 10 years into the future, what would you hope to see?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to end up on stage or dancing on furniture?", "da": "Hvem ender mest sandsynligt p\u00e5 scenen eller dansende p\u00e5 m\u00f8bler?", "de": "Wer landet am ehesten auf der B\u00fchne oder tanzt auf M\u00f6beln?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que termine en el escenario o bailando sobre los muebles?", "pt": "Quem \u00e9 mais prov\u00e1vel acabar em cima do palco ou a dan\u00e7ar nos m\u00f3veis?", "ro": "Cine e cel mai probabil s\u0103 ajung\u0103 pe scen\u0103 sau s\u0103 danseze pe mobil\u0103?", "fr": "Qui est le plus susceptible de finir sur sc\u00e8ne ou \u00e0 danser sur les meubles ?", "it": "Chi \u00e8 pi\u00f9 probabile che finisca sul palco o a ballare sui mobili?", "fi": "Kuka todenn\u00e4k\u00f6isesti p\u00e4\u00e4tyy lavalle tai tanssimaan huonekalujen p\u00e4\u00e4ll\u00e4?", "nl": "Wie is het meest waarschijnlijk om op het podium te eindigen of op meubels te dansen?", "no": "Hvem er mest sannsynlig \u00e5 ende opp p\u00e5 scenen eller danse p\u00e5 m\u00f8blene?", "sv": "Vem \u00e4r mest trolig att hamna p\u00e5 scen eller dansa p\u00e5 m\u00f6bler?", "pl": "Kto najprawdopodobniej sko\u0144czy na scenie lub ta\u0144cz\u0105c na meblach?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who’s most likely to end up on stage or dancing on furniture?';