UPDATE questions
SET translations = '{"en": "What\u2019s the funniest \u201conly we get it\u201d moment we\u2019ve had so far?", "da": "Hvad er det sjoveste \u201ckun vi forst\u00e5r det\u201d-\u00f8jeblik, vi har haft indtil nu?", "de": "Was war bisher der lustigste \u201eNur wir verstehen das\u201c-Moment?", "es": "\u00bfCu\u00e1l ha sido hasta ahora el momento m\u00e1s gracioso de \u201csolo nosotros lo entendemos\u201d?", "pt": "Qual foi, at\u00e9 agora, o momento mais engra\u00e7ado do tipo \u201cs\u00f3 n\u00f3s percebemos\u201d?", "ro": "Care a fost p\u00e2n\u0103 acum momentul amuzant de tipul \u201edoar noi \u00eel \u00een\u021belegem\u201d?", "fr": "Quel a \u00e9t\u00e9 jusqu\u2019ici notre moment le plus dr\u00f4le du type \u00ab il n\u2019y a que nous qui comprenons \u00bb ?", "it": "Qual \u00e8 stato il momento pi\u00f9 divertente di \u201csolo noi lo capiamo\u201d che abbiamo avuto finora?", "fi": "Mik\u00e4 on hauskin \"vain me ymm\u00e4rr\u00e4mme\" hetki, jonka olemme kokeneet t\u00e4h\u00e4n menness\u00e4?", "nl": "Wat is het grappigste \"alleen wij begrijpen het\" moment dat we tot nu toe hebben gehad?", "no": "Hva er det morsomste \"bare vi forst\u00e5r det\"-\u00f8yeblikket vi har hatt s\u00e5 langt?", "sv": "Vad \u00e4r det roligaste \"bara vi f\u00f6rst\u00e5r\" \u00f6gonblicket vi har haft hittills?", "pl": "Jaki by\u0142 najzabawniejszy moment \u201etylko my to rozumiemy\u201d, kt\u00f3ry mieli\u015bmy do tej pory?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s the funniest “only we get it” moment we’ve had so far?';
UPDATE questions
SET translations = '{"en": "If our relationship were to end tomorrow what things would you miss the most?", "da": "Hvis vores forhold sluttede i morgen, hvilke ting ville du savne mest?", "de": "Wenn unsere Beziehung morgen enden w\u00fcrde, welche Dinge w\u00fcrdest du am meisten vermissen?", "es": "Si nuestra relaci\u00f3n terminara ma\u00f1ana, \u00bfqu\u00e9 cosas extra\u00f1ar\u00edas m\u00e1s?", "pt": "Se a nossa rela\u00e7\u00e3o acabasse amanh\u00e3, que coisas sentirias mais falta?", "ro": "Dac\u0103 rela\u021bia noastr\u0103 s-ar termina m\u00e2ine, ce lucruri \u021bi-ar lipsi cel mai mult?", "fr": "Si notre relation se terminait demain, quelles choses te manqueraient le plus ?", "it": "Se la nostra relazione dovesse finire domani, quali cose ti mancherebbero di pi\u00f9?", "fi": "Jos suhteemme p\u00e4\u00e4ttyisi huomenna, mit\u00e4 asioita kaipaisit eniten?", "nl": "Als onze relatie morgen zou eindigen, welke dingen zou je dan het meest missen?", "no": "Hvis forholdet v\u00e5rt skulle ta slutt i morgen, hva ville du savne mest?", "sv": "Om v\u00e5r relation skulle ta slut imorgon, vad skulle du sakna mest?", "pl": "Je\u015bli nasz zwi\u0105zek mia\u0142by si\u0119 zako\u0144czy\u0107 jutro, co najbardziej by\u015b t\u0119skni\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'If our relationship were to end tomorrow what things would you miss the most?';
UPDATE questions
SET translations = '{"en": "What about our relationship are you most grateful for?", "da": "Hvad ved vores forhold er du mest taknemmelig for?", "de": "Wof\u00fcr in unserer Beziehung bist du am dankbarsten?", "es": "\u00bfDe qu\u00e9 est\u00e1s m\u00e1s agradecido/a en nuestra relaci\u00f3n?", "pt": "Do que \u00e9 que est\u00e1s mais grato/a na nossa rela\u00e7\u00e3o?", "ro": "Pentru ce e\u0219ti cel mai recunosc\u0103tor/recunosc\u0103toare \u00een rela\u021bia noastr\u0103?", "fr": "De quoi es-tu le plus reconnaissant(e) dans notre relation ?", "it": "Di cosa nella nostra relazione sei pi\u00f9 grato?", "fi": "Mist\u00e4 suhteessamme olet eniten kiitollinen?", "nl": "Waar ben je het meest dankbaar voor in onze relatie?", "no": "Hva er du mest takknemlig for i v\u00e5rt forhold?", "sv": "Vad \u00e4r du mest tacksam f\u00f6r i v\u00e5r relation?", "pl": "Za co w naszej relacji jeste\u015b najbardziej wdzi\u0119czny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What about our relationship are you most grateful for?';
UPDATE questions
SET translations = '{"en": "What does a perfect day together look like for you?", "da": "Hvordan ser en perfekt dag sammen ud for dig?", "de": "Wie sieht f\u00fcr dich ein perfekter Tag zusammen aus?", "es": "\u00bfC\u00f3mo es para ti un d\u00eda perfecto juntos?", "pt": "Como \u00e9 para ti um dia perfeito juntos?", "ro": "Cum arat\u0103 pentru tine o zi perfect\u0103 petrecut\u0103 \u00eempreun\u0103?", "fr": "\u00c0 quoi ressemble pour toi une journ\u00e9e parfaite ensemble ?", "it": "Come sarebbe per te una giornata perfetta insieme?", "fi": "Millainen t\u00e4ydellinen p\u00e4iv\u00e4 yhdess\u00e4 n\u00e4ytt\u00e4\u00e4 sinun mielest\u00e4si?", "nl": "Hoe ziet een perfecte dag samen er voor jou uit?", "no": "Hvordan ser en perfekt dag sammen ut for deg?", "sv": "Hur ser en perfekt dag tillsammans ut f\u00f6r dig?", "pl": "Jak wygl\u0105da dla ciebie idealny dzie\u0144 razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What does a perfect day together look like for you?';
UPDATE questions
SET translations = '{"en": "How do you think we have both changed since we first met?", "da": "Hvordan synes du, at vi begge har \u00e6ndret os, siden vi m\u00f8dtes f\u00f8rste gang?", "de": "Wie glaubst du, haben wir uns beide ver\u00e4ndert, seit wir uns kennengelernt haben?", "es": "\u00bfC\u00f3mo crees que ambos hemos cambiado desde que nos conocimos?", "pt": "Como achas que ambos mud\u00e1mos desde que nos conhecemos?", "ro": "Cum crezi c\u0103 ne-am schimbat am\u00e2ndoi de c\u00e2nd ne-am cunoscut?", "fr": "Comment penses-tu que nous avons tous les deux chang\u00e9 depuis notre rencontre ?", "it": "Come pensi che siamo cambiati entrambi da quando ci siamo incontrati per la prima volta?", "fi": "Miten luulet, ett\u00e4 olemme molemmat muuttuneet siit\u00e4, kun tapasimme ensimm\u00e4isen kerran?", "nl": "Hoe denk je dat we allebei veranderd zijn sinds we elkaar voor het eerst ontmoetten?", "no": "Hvordan tror du vi begge har endret oss siden vi f\u00f8rst m\u00f8ttes?", "sv": "Hur tror du att vi b\u00e5da har f\u00f6r\u00e4ndrats sedan vi f\u00f6rst tr\u00e4ffades?", "pl": "Jak my\u015blisz, jak oboje si\u0119 zmienili\u015bmy od czasu, gdy si\u0119 po raz pierwszy spotkali\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'How do you think we have both changed since we first met?';
UPDATE questions
SET translations = '{"en": "In what ways has our relationship changed you?", "da": "P\u00e5 hvilke m\u00e5der har vores forhold \u00e6ndret dig?", "de": "Inwiefern hat unsere Beziehung dich ver\u00e4ndert?", "es": "\u00bfDe qu\u00e9 maneras nuestra relaci\u00f3n te ha cambiado?", "pt": "De que maneiras a nossa rela\u00e7\u00e3o te mudou?", "ro": "\u00cen ce fel te-a schimbat rela\u021bia noastr\u0103?", "fr": "De quelles mani\u00e8res notre relation t\u2019a-t-elle chang\u00e9(e) ?", "it": "In che modo la nostra relazione ti ha cambiato?", "fi": "Miten suhteemme on muuttanut sinua?", "nl": "Op welke manieren heeft onze relatie jou veranderd?", "no": "P\u00e5 hvilke m\u00e5ter har forholdet v\u00e5rt endret deg?", "sv": "P\u00e5 vilka s\u00e4tt har v\u00e5r relation f\u00f6r\u00e4ndrat dig?", "pl": "W jaki spos\u00f3b nasza relacja ci\u0119 zmieni\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'In what ways has our relationship changed you?';
UPDATE questions
SET translations = '{"en": "What\u2019s a small surprise I could plan that would mean a lot to you?", "da": "Hvilken lille overraskelse kunne jeg planl\u00e6gge, som ville betyde meget for dig?", "de": "Welche kleine \u00dcberraschung k\u00f6nnte ich planen, die dir viel bedeuten w\u00fcrde?", "es": "\u00bfQu\u00e9 peque\u00f1a sorpresa podr\u00eda planear que signifique mucho para ti?", "pt": "Que pequena surpresa eu poderia preparar que significasse muito para ti?", "ro": "Ce mic\u0103 surpriz\u0103 a\u0219 putea s\u0103 planific care ar \u00eensemna mult pentru tine?", "fr": "Quelle petite surprise pourrais-je pr\u00e9parer qui compterait beaucoup pour toi ?", "it": "Qual \u00e8 una piccola sorpresa che potrei pianificare e che significherebbe molto per te?", "fi": "Mik\u00e4 olisi pieni yll\u00e4tys, jonka voisin suunnitella ja joka merkitsisi sinulle paljon?", "nl": "Wat is een kleine verrassing die ik zou kunnen plannen die veel voor je zou betekenen?", "no": "Hva er en liten overraskelse jeg kunne planlegge som ville bety mye for deg?", "sv": "Vad \u00e4r en liten \u00f6verraskning jag skulle kunna planera som skulle betyda mycket f\u00f6r dig?", "pl": "Jaka ma\u0142a niespodzianka, kt\u00f3r\u0105 m\u00f3g\u0142bym zaplanowa\u0107, mia\u0142aby dla Ciebie du\u017ce znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What’s a small surprise I could plan that would mean a lot to you?';
UPDATE questions
SET translations = '{"en": "What''s a personal goal you have that you''d like more support with? ", "da": "Hvad er et personligt m\u00e5l, du har, hvor du gerne vil have mere st\u00f8tte?", "de": "Was ist ein pers\u00f6nliches Ziel von dir, bei dem du dir mehr Unterst\u00fctzung w\u00fcnschst?", "es": "\u00bfCu\u00e1l es una meta personal que tienes y con la que te gustar\u00eda recibir m\u00e1s apoyo?", "pt": "Qual \u00e9 um objetivo pessoal teu com o qual gostarias de ter mais apoio?", "ro": "Care este un obiectiv personal pentru care \u021bi-ai dori mai mult sprijin?", "fr": "Quel objectif personnel as-tu pour lequel tu aimerais davantage de soutien ?", "it": "Qual \u00e8 un obiettivo personale che hai e con cui vorresti avere pi\u00f9 supporto?", "fi": "Mik\u00e4 on henkil\u00f6kohtainen tavoitteesi, jossa toivoisit saavasi enemm\u00e4n tukea?", "nl": "Wat is een persoonlijk doel dat je hebt waar je graag meer ondersteuning bij zou willen?", "no": "Hva er et personlig m\u00e5l du har som du gjerne vil ha mer st\u00f8tte til?", "sv": "Vilket personligt m\u00e5l har du som du skulle vilja ha mer st\u00f6d med?", "pl": "Jakie osobiste cele masz, w kt\u00f3rych chcia\u0142by\u015b otrzyma\u0107 wi\u0119ksze wsparcie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'What''s a personal goal you have that you''d like more support with? ';
UPDATE questions
SET translations = '{"en": "When do you feel most playful with me?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest legesyg sammen med mig?", "de": "Wann f\u00fchlst du dich mit mir am verspieltesten?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s juguet\u00f3n/a conmigo?", "pt": "Quando te sentes mais brincalh\u00e3o/brincalhona comigo?", "ro": "C\u00e2nd te sim\u021bi cel mai juc\u0103u\u0219/juc\u0103u\u0219\u0103 cu mine?", "fr": "Quand te sens-tu le/la plus joueur(se) avec moi ?", "it": "Quando ti senti pi\u00f9 giocoso con me?", "fi": "Milloin tunnet itsesi leikkisimm\u00e4ksi kanssani?", "nl": "Wanneer voel je je het meest speels met mij?", "no": "N\u00e5r f\u00f8ler du deg mest leken med meg?", "sv": "N\u00e4r k\u00e4nner du dig mest lekfull med mig?", "pl": "Kiedy czujesz si\u0119 ze mn\u0105 najbardziej zabawnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'When do you feel most playful with me?';
UPDATE questions
SET translations = '{"en": "Which of us has the harder time hiding feelings?", "da": "Hvem af os har sv\u00e6rest ved at skjule f\u00f8lelser?", "de": "Wer von uns hat es am schwersten, Gef\u00fchle zu verbergen?", "es": "\u00bfQui\u00e9n de los dos tiene m\u00e1s dificultad para ocultar sus sentimientos?", "pt": "Qual de n\u00f3s tem mais dificuldade em esconder os sentimentos?", "ro": "Cine dintre noi are mai greu s\u0103-\u0219i ascund\u0103 sentimentele?", "fr": "Lequel de nous a le plus de mal \u00e0 cacher ses \u00e9motions ?", "it": "Chi di noi ha pi\u00f9 difficolt\u00e0 a nascondere i propri sentimenti?", "fi": "Kumpi meist\u00e4 on vaikeammassa asemassa tunteiden piilottamisessa?", "nl": "Wie van ons heeft het moeilijker om gevoelens te verbergen?", "no": "Hvem av oss har vanskeligere for \u00e5 skjule f\u00f8lelser?", "sv": "Vilken av oss har sv\u00e5rare att d\u00f6lja k\u00e4nslor?", "pl": "Kto z nas ma trudniej z ukrywaniem uczu\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Talks'
  AND translations->>'en' = 'Which of us has the harder time hiding feelings?';