UPDATE questions
SET translations = '{"en": "Photo gallery edition: what kind of picture do you have way too many of on your phone?", "da": "Billedgalleri-udgave: Hvilken slags billeder har du alt for mange af p\u00e5 din telefon?", "de": "Fotogalerie-Edition: Von welcher Art Fotos hast du viel zu viele auf deinem Handy?", "es": "Edici\u00f3n galer\u00eda de fotos: \u00bfde qu\u00e9 tipo de fotos tienes demasiadas en tu m\u00f3vil?", "pt": "Edi\u00e7\u00e3o galeria de fotos: de que tipo de foto voc\u00ea tem em quantidade absurda no seu celular?", "ro": "Edi\u021bia galerie foto: ce fel de poze ai mult prea multe pe telefon?", "fr": "\u00c9dition galerie photo : quel type de photos as-tu beaucoup trop en nombre sur ton t\u00e9l\u00e9phone ?", "it": "Edizione della galleria fotografica: che tipo di foto hai decisamente troppe sul tuo telefono?", "fi": "Valokuvagalleria: mink\u00e4laista kuvaa sinulla on puhelimessasi aivan liian paljon?", "nl": "Fotogalerij editie: welk soort foto heb je veel te veel van op je telefoon?", "no": "Fotogalleriutgave: hvilken type bilder har du altfor mange av p\u00e5 telefonen din?", "sv": "Fotogalleriutg\u00e5van: vilken typ av bilder har du alldeles f\u00f6r m\u00e5nga av p\u00e5 din telefon?", "pl": "Edycja galerii zdj\u0119\u0107: jakiego rodzaju zdj\u0119\u0107 masz zdecydowanie za du\u017co na swoim telefonie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Photo gallery edition: what kind of picture do you have way too many of on your phone?';
UPDATE questions
SET translations = '{"en": "If your laugh were a ringtone, who would set it and embarrass you with it?", "da": "Hvis dit grin var en ringetone, hvem ville indstille det og g\u00f8re dig flov med det?", "de": "Wenn dein Lachen ein Klingelton w\u00e4re, wer w\u00fcrde ihn einstellen und dich damit blamieren?", "es": "Si tu risa fuera un tono de llamada, \u00bfqui\u00e9n lo pondr\u00eda y te avergonzar\u00eda con \u00e9l?", "pt": "Se a tua risada fosse um toque de telem\u00f3vel, quem a definiria e te envergonharia com isso?", "ro": "Dac\u0103 r\u00e2sul t\u0103u ar fi un ton de apel, cine l-ar seta \u0219i te-ar face de r\u00e2s cu el?", "fr": "Si ton rire \u00e9tait une sonnerie, qui la mettrait et t\u2019embarrasserait avec ?", "it": "Se la tua risata fosse una suoneria, chi la imposterebbe e ti metterebbe in imbarazzo con essa?", "fi": "Jos naurusi olisi soitto\u00e4\u00e4ni, kuka sen asettaisi ja h\u00e4p\u00e4isisi sinua sill\u00e4?", "nl": "Als je lach een beltoon zou zijn, wie zou die dan instellen en je ermee in verlegenheid brengen?", "no": "Hvis latteren din var en ringetone, hvem ville satt den og gjort deg flau med den?", "sv": "Om ditt skratt vore en ringsignal, vem skulle s\u00e4tta den och sk\u00e4mma ut dig med den?", "pl": "Gdyby tw\u00f3j \u015bmiech by\u0142 dzwonkiem, kto by go ustawi\u0142 i zawstydzi\u0142 ci\u0119 tym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If your laugh were a ringtone, who would set it and embarrass you with it?';
UPDATE questions
SET translations = '{"en": "If your reflection gave unfiltered feedback, what would it roast first?", "da": "Hvis dit spejlbillede gav ufiltreret feedback, hvad ville det g\u00f8re grin med f\u00f8rst?", "de": "Wenn dein Spiegelbild ungefiltertes Feedback g\u00e4be, was w\u00fcrde es zuerst verspotten?", "es": "Si tu reflejo diera una opini\u00f3n sin filtro, \u00bfqu\u00e9 ser\u00eda lo primero que criticar\u00eda?", "pt": "Se o teu reflexo desse feedback sem filtros, o que zombaria primeiro?", "ro": "Dac\u0103 reflexia ta \u021bi-ar da un feedback sincer, ce ar critica prima dat\u0103?", "fr": "Si ton reflet te donnait un retour sans filtre, que se moquerait-il en premier ?", "it": "Se il tuo riflesso desse un feedback senza filtri, cosa criticerebbe per prima cosa?", "fi": "Jos peilikuvaasi antaisi suoraa palautetta, mik\u00e4 se ensin kritisoisi?", "nl": "Als je reflectie ongefilterde feedback zou geven, wat zou het dan als eerste bekritiseren?", "no": "Hvis refleksjonen din ga ufiltrert tilbakemelding, hva ville den kritisert f\u00f8rst?", "sv": "Om din spegelbild gav ofiltrerat feedback, vad skulle den f\u00f6rst kritisera?", "pl": "Gdyby twoje odbicie dawa\u0142o nieprzefiltrowane opinie, co by skrytykowa\u0142o w pierwszej kolejno\u015bci?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If your reflection gave unfiltered feedback, what would it roast first?';
UPDATE questions
SET translations = '{"en": "If all pets suddenly spoke perfect human, which would be the worst gossip?", "da": "Hvis alle k\u00e6ledyr pludselig kunne tale perfekt menneskesprog, hvilket ville sladre mest?", "de": "Wenn alle Haustiere pl\u00f6tzlich perfektes Menschendeutsch sprechen k\u00f6nnten, welches w\u00e4re der schlimmste Klatsch?", "es": "Si todas las mascotas hablaran perfectamente humano, \u00bfcu\u00e1l ser\u00eda el peor chismoso?", "pt": "Se todos os animais de estima\u00e7\u00e3o falassem humano perfeito, qual seria o pior fofoqueiro?", "ro": "Dac\u0103 toate animalele de companie ar vorbi perfect omene\u0219te, care ar fi cel mai b\u00e2rfitor?", "fr": "Si tous les animaux de compagnie parlaient parfaitement humain, lequel serait le pire comm\u00e8re ?", "it": "Se tutti gli animali domestici all''improvviso parlassero perfettamente l''umano, quale sarebbe il pettegolezzo peggiore?", "fi": "Jos kaikki lemmikit yht\u00e4kki\u00e4 puhuisivat t\u00e4ydellist\u00e4 ihmiskielt\u00e4, mik\u00e4 olisi pahin juoru?", "nl": "Als alle huisdieren plotseling perfect menselijk konden praten, welk gerucht zou dan het ergste zijn?", "no": "Hvis alle kj\u00e6ledyr plutselig kunne snakke perfekt menneskespr\u00e5k, hvilket ville v\u00e6rt det verste sladderet?", "sv": "Om alla husdjur pl\u00f6tsligt kunde prata perfekt m\u00e4nskligt, vilket skulle vara det v\u00e4rsta skvaller?", "pl": "Gdyby wszystkie zwierz\u0119ta domowe nagle zacz\u0119\u0142y m\u00f3wi\u0107 perfekcyjnym ludzkim j\u0119zykiem, kt\u00f3re z nich by\u0142oby najgorszym plotkarzem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If all pets suddenly spoke perfect human, which would be the worst gossip?';
UPDATE questions
SET translations = '{"en": "If you had a theme sound effect every time you entered a room, what would it be?", "da": "Hvis du havde en temasoundeffekt, hver gang du tr\u00e5dte ind i et rum, hvad ville det v\u00e6re?", "de": "Wenn du jedes Mal, wenn du einen Raum betrittst, einen Themensoundeffekt h\u00e4ttest \u2013 welcher w\u00e4re das?", "es": "Si tuvieras un efecto de sonido tem\u00e1tico cada vez que entras a una habitaci\u00f3n, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se tivesses um efeito sonoro tem\u00e1tico sempre que entrasse numa sala, qual seria?", "ro": "Dac\u0103 ai avea un efect sonor tematic de fiecare dat\u0103 c\u00e2nd intri \u00eentr-o camer\u0103, care ar fi?", "fr": "Si tu avais un effet sonore chaque fois que tu entres dans une pi\u00e8ce, lequel serait-ce ?", "it": "Se avessi un effetto sonoro tematico ogni volta che entrassi in una stanza, quale sarebbe?", "fi": "Jos sinulla olisi teema\u00e4\u00e4nitehoste joka kerta, kun astut huoneeseen, mik\u00e4 se olisi?", "nl": "Als je een them geluids effect zou hebben elke keer dat je een kamer binnenkomt, wat zou het dan zijn?", "no": "Hvis du hadde en temalydeffekt hver gang du gikk inn i et rom, hva ville det v\u00e6rt?", "sv": "Om du hade ett temaljud varje g\u00e5ng du gick in i ett rum, vad skulle det vara?", "pl": "Gdyby\u015b mia\u0142 efekt d\u017awi\u0119kowy tematyczny za ka\u017cdym razem, gdy wchodzi\u0142e\u015b do pokoju, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If you had a theme sound effect every time you entered a room, what would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s the silliest rule you\u2019d enforce if you were in charge for one hour?", "da": "Hvad er den mest fjollede regel, du ville h\u00e5ndh\u00e6ve, hvis du havde magten i en time?", "de": "Welche alberne Regel w\u00fcrdest du durchsetzen, wenn du f\u00fcr eine Stunde das Sagen h\u00e4ttest?", "es": "\u00bfCu\u00e1l ser\u00eda la regla m\u00e1s tonta que har\u00edas cumplir si estuvieras a cargo por una hora?", "pt": "Qual seria a regra mais tola que imporias se estivesses no comando por uma hora?", "ro": "Care ar fi cea mai tr\u0103znit\u0103 regul\u0103 pe care ai impune-o dac\u0103 ai fi la conducere timp de o or\u0103?", "fr": "Quelle serait la r\u00e8gle la plus stupide que tu ferais appliquer si tu \u00e9tais en charge pendant une heure ?", "it": "Qual \u00e8 la regola pi\u00f9 stupida che faresti rispettare se fossi al comando per un''ora?", "fi": "Mik\u00e4 olisi typerin s\u00e4\u00e4nt\u00f6, jonka s\u00e4\u00e4t\u00e4isit, jos olisit vastuussa tunnin ajan?", "nl": "Wat is de gekste regel die je zou handhaven als je \u00e9\u00e9n uur de baas was?", "no": "Hva er den mest tullete regelen du ville innf\u00f8rt hvis du hadde ansvaret i \u00e9n time?", "sv": "Vilken knasig regel skulle du inf\u00f6ra om du hade makten i en timme?", "pl": "Jak\u0105 najg\u0142upsz\u0105 zasad\u0119 wprowadzi\u0142by\u015b, gdyby\u015b by\u0142 odpowiedzialny przez jedn\u0105 godzin\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s the silliest rule you’d enforce if you were in charge for one hour?';
UPDATE questions
SET translations = '{"en": "Weekend edition: what\u2019s your most realistic definition of \u201cI\u2019m not doing much this weekend\u201d?", "da": "Weekend-udgave: Hvad er din mest realistiske definition af \u201cjeg skal ikke lave s\u00e5 meget i weekenden\u201d?", "de": "Wochenend-Edition: Was ist deine realistischste Definition von \u201eIch mache nicht viel dieses Wochenende\u201c?", "es": "Edici\u00f3n fin de semana: \u00bfcu\u00e1l es tu definici\u00f3n m\u00e1s realista de \u201cno voy a hacer mucho este finde\u201d?", "pt": "Edi\u00e7\u00e3o fim de semana: qual \u00e9 a sua defini\u00e7\u00e3o mais realista de \u201cn\u00e3o vou fazer muita coisa neste fim de semana\u201d?", "ro": "Edi\u021bia weekend: care este cea mai realist\u0103 defini\u021bie a ta pentru \u201enu fac mare lucru weekendul \u0103sta\u201d?", "fr": "\u00c9dition week-end : quelle est ta d\u00e9finition la plus r\u00e9aliste de \u00ab je ne fais pas grand-chose ce week-end \u00bb ?", "it": "Edizione del weekend: qual \u00e8 la tua definizione pi\u00f9 realistica di \"non far\u00f2 molto questo weekend\"?", "fi": "Viikonlopun erikoisnumero: mik\u00e4 on realistisin m\u00e4\u00e4ritelm\u00e4si \"En tee paljoa t\u00e4n\u00e4 viikonloppuna\"?", "nl": "Weekend editie: wat is jouw meest realistische definitie van \"ik doe dit weekend niet veel\"?", "no": "Helgeutgave: hva er din mest realistiske definisjon av \"jeg skal ikke gj\u00f8re s\u00e5 mye i helgen\"?", "sv": "Helgupplaga: vad \u00e4r din mest realistiska definition av \"jag g\u00f6r inte mycket i helgen\"?", "pl": "Weekendowa edycja: jaka jest twoja najbardziej realistyczna definicja \u201eNie robi\u0119 nic w ten weekend\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Weekend edition: what’s your most realistic definition of “I’m not doing much this weekend”?';
UPDATE questions
SET translations = '{"en": "What completely unnecessary item would I smuggle onto a deserted island?", "da": "Hvilken fuldst\u00e6ndig un\u00f8dvendig genstand ville jeg smugle med til en \u00f8de \u00f8?", "de": "Welchen v\u00f6llig unn\u00f6tigen Gegenstand w\u00fcrde ich auf eine einsame Insel schmuggeln?", "es": "\u00bfQu\u00e9 objeto completamente innecesario me llevar\u00eda a una isla desierta?", "pt": "Que objeto completamente desnecess\u00e1rio eu contrabandearia para uma ilha deserta?", "ro": "Ce obiect complet inutil a\u0219 ascunde pe o insul\u0103 pustie?", "fr": "Quel objet totalement inutile je ferais passer en contrebande sur une \u00eele d\u00e9serte ?", "it": "Quale oggetto completamente superfluo porterei di nascosto su un''isola deserta?", "fi": "Mik\u00e4 t\u00e4ysin tarpeeton esine min\u00e4 salakuljettaisin autiolle saarelle?", "nl": "Wat zou ik volledig onnodig meenemen naar een onbewoond eiland?", "no": "Hvilken helt un\u00f8dvendig gjenstand ville jeg smugle med meg til en \u00f8de \u00f8y?", "sv": "Vilken helt on\u00f6dig sak skulle jag smuggla med mig till en \u00f6de \u00f6?", "pl": "Jaki ca\u0142kowicie zb\u0119dny przedmiot przemyci\u0142bym na bezludn\u0105 wysp\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What completely unnecessary item would I smuggle onto a deserted island?';
UPDATE questions
SET translations = '{"en": "What\u2019s my signature \u201cI\u2019m innocent\u201d face\u2014and when do I use it?", "da": "Hvad er mit signatur \u201cjeg er uskyldig\u201d-ansigt \u2013 og hvorn\u00e5r bruger jeg det?", "de": "Was ist mein typisches \u201eIch bin unschuldig\u201c-Gesicht \u2013 und wann benutze ich es?", "es": "\u00bfCu\u00e1l es mi cara de \u201csoy inocente\u201d y cu\u00e1ndo la uso?", "pt": "Qual \u00e9 a minha cara de \u201csou inocente\u201d \u2014 e quando a uso?", "ro": "Care este expresia mea \u201esunt nevinovat\u201d \u2013 \u0219i c\u00e2nd o folosesc?", "fr": "Quelle est ma t\u00eate \u201cje suis innocent\u201d \u2013 et quand est-ce que je l\u2019utilise ?", "it": "Qual \u00e8 la mia espressione \"sono innocente\" e quando la uso?", "fi": "Mik\u00e4 on minun allekirjoitukseni \"Olen viaton\" -ilme, ja milloin k\u00e4yt\u00e4n sit\u00e4?", "nl": "Wat is mijn handtekening \"Ik ben onschuldig\" gezicht - en wanneer gebruik ik het?", "no": "Hva er mitt signatur \"jeg er uskyldig\" ansikt\u2014og n\u00e5r bruker jeg det?", "sv": "Vad \u00e4r mitt signaturansikte f\u00f6r \"jag \u00e4r oskyldig\"\u2014och n\u00e4r anv\u00e4nder jag det?", "pl": "Jaka jest moja charakterystyczna mina \u201eJestem niewinny\u201d \u2013 i kiedy jej u\u017cywam?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s my signature “I’m innocent” face—and when do I use it?';
UPDATE questions
SET translations = '{"en": "Job interview edition: what\u2019s your go-to fake \u201cprofessional\u201d phrase when you actually mean \u201cI have no idea\u201d?", "da": "Jobinterview-udgave: Hvad er din standard falske \u201cprofessionelle\u201d s\u00e6tning, n\u00e5r du egentlig mener \u201cjeg har ingen id\u00e9\u201d?", "de": "Bewerbungsgespr\u00e4ch-Edition: Was ist dein Standard-\u201eprofessioneller\u201c Spruch, wenn du eigentlich meinst \u201eIch habe keine Ahnung\u201c?", "es": "Edici\u00f3n entrevista de trabajo: \u00bfcu\u00e1l es tu frase \u201cprofesional\u201d de emergencia cuando en realidad quieres decir \u201cno tengo ni idea\u201d?", "pt": "Edi\u00e7\u00e3o entrevista de emprego: qual \u00e9 a sua frase \u201cprofissional\u201d padr\u00e3o quando, na verdade, voc\u00ea quer dizer \u201cn\u00e3o fa\u00e7o a menor ideia\u201d?", "ro": "Edi\u021bia interviu de angajare: care este fraza ta \u201eprofesional\u0103\u201d de rezerv\u0103 c\u00e2nd, de fapt, vrei s\u0103 spui \u201enu am nici cea mai vag\u0103 idee\u201d?", "fr": "\u00c9dition entretien d\u2019embauche : quelle est ta phrase \u00ab professionnelle \u00bb de secours quand tu veux en r\u00e9alit\u00e9 dire \u00ab je n\u2019en ai aucune id\u00e9e \u00bb ?", "it": "Qual \u00e8 la tua frase \"professionale\" di riserva quando in realt\u00e0 intendi dire \"non ne ho idea\"?", "fi": "Ty\u00f6haastatteluversio: mik\u00e4 on se suosikkikeksim\u00e4si \"ammattimainen\" fraasi, kun oikeasti tarkoitat \"minulla ei ole aavistustakaan\"?", "nl": "Wat is jouw favoriete nep \"professionele\" uitdrukking wanneer je eigenlijk bedoelt \"ik heb geen idee\"?", "no": "Jobbintervju-utgave: hva er din favoritt \"profesjonelle\" frase n\u00e5r du egentlig mener \"jeg har ingen anelse\"?", "sv": "Jobbintervjuutg\u00e5van: vad \u00e4r din favoritfalska \"professionella\" fras n\u00e4r du egentligen menar \"jag har ingen aning\"?", "pl": "Jakie jest twoje ulubione \u201eprofesjonalne\u201d sformu\u0142owanie, kt\u00f3re u\u017cywasz, gdy tak naprawd\u0119 masz na my\u015bli \u201enie mam poj\u0119cia\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Job interview edition: what’s your go-to fake “professional” phrase when you actually mean “I have no idea”?';