UPDATE questions
SET translations = '{"en": "Tell the steps for making a simple sandwich.", "da": "Fort\u00e6l trinnene til at lave en simpel sandwich.", "de": "Erkl\u00e4re die Schritte, um ein einfaches Sandwich zu machen.", "es": "Explica los pasos para hacer un s\u00e1ndwich simple.", "pt": "Diz os passos para fazer uma sandu\u00edche simples.", "ro": "Spune pa\u0219ii pentru a face un sandvi\u0219 simplu.", "fr": "Dis les \u00e9tapes pour faire un sandwich simple.", "it": "Raccontami i passaggi per fare un semplice panino.", "fi": "Kerro vaiheet yksinkertaisen voileiv\u00e4n tekemiseen.", "nl": "Vertel de stappen voor het maken van een simpele sandwich.", "no": "Fortell trinnene for \u00e5 lage et enkelt sm\u00f8rbr\u00f8d.", "sv": "Ber\u00e4tta stegen f\u00f6r att g\u00f6ra en enkel sm\u00f6rg\u00e5s.", "pl": "Podaj kroki do zrobienia prostego kanapki."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Tell the steps for making a simple sandwich.';UPDATE questions
SET translations = '{"en": "What is something you used today that uses electricity?", "da": "Hvad har du brugt i dag, der bruger elektricitet?", "de": "Was hast du heute benutzt, das Strom verbraucht?", "es": "\u00bfQu\u00e9 usaste hoy que usa electricidad?", "pt": "O que usaste hoje que utiliza eletricidade?", "ro": "Ce ai folosit ast\u0103zi care folose\u0219te electricitate?", "fr": "Qu\u2019as-tu utilis\u00e9 aujourd\u2019hui qui utilise de l\u2019\u00e9lectricit\u00e9 ?", "it": "Qualcosa che hai usato oggi che utilizza elettricit\u00e0?", "fi": "Mik\u00e4 on jotain, mit\u00e4 k\u00e4ytit t\u00e4n\u00e4\u00e4n, joka k\u00e4ytt\u00e4\u00e4 s\u00e4hk\u00f6\u00e4?", "nl": "Wat is iets dat je vandaag hebt gebruikt dat elektriciteit verbruikt?", "no": "Hva er noe du brukte i dag som bruker elektrisitet?", "sv": "Vad \u00e4r n\u00e5got du anv\u00e4nde idag som anv\u00e4nder elektricitet?", "pl": "Co\u015b, z czego dzisiaj korzysta\u0142e\u015b, co u\u017cywa energii elektrycznej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What is something you used today that uses electricity?';
UPDATE questions
SET translations = '{"en": "If your bed could fly anywhere tonight, where would it take you?", "da": "Hvis din seng kunne flyve hvor som helst i nat, hvor ville den tage dig hen?", "de": "Wenn dein Bett heute Nacht \u00fcberall hinfliegen k\u00f6nnte, wohin w\u00fcrde es dich bringen?", "es": "Si tu cama pudiera volar a cualquier lugar esta noche, \u00bfa d\u00f3nde te llevar\u00eda?", "pt": "Se a tua cama pudesse voar para qualquer lugar esta noite, para onde te levaria?", "ro": "Dac\u0103 patul t\u0103u ar putea zbura oriunde \u00een seara asta, unde te-ar duce?", "fr": "Si ton lit pouvait voler n\u2019importe o\u00f9 ce soir, o\u00f9 t\u2019emm\u00e8nerait-il ?", "it": "Se il tuo letto potesse volare ovunque stasera, dove ti porterebbe?", "fi": "Jos s\u00e4nkysi voisi lent\u00e4\u00e4 minne tahansa t\u00e4n\u00e4 y\u00f6n\u00e4, minne se veisi sinut?", "nl": "Als je bed vanavond overal naartoe kon vliegen, waar zou het je naartoe brengen?", "no": "Hvis sengen din kunne fly hvor som helst i natt, hvor ville den tatt deg?", "sv": "Om din s\u00e4ng kunde flyga vart som helst i natt, vart skulle den ta dig?", "pl": "Gdyby twoje \u0142\u00f3\u017cko mog\u0142o polecie\u0107 gdziekolwiek dzisiaj w nocy, dok\u0105d by ci\u0119 zabra\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If your bed could fly anywhere tonight, where would it take you?';
UPDATE questions
SET translations = '{"en": "If rainbows were slides, where would they land?", "da": "Hvis regnbuer var rutsjebaner, hvor ville de lande?", "de": "Wenn Regenb\u00f6gen Rutschen w\u00e4ren, wo w\u00fcrden sie landen?", "es": "Si los arco\u00edris fueran toboganes, \u00bfd\u00f3nde terminar\u00edan?", "pt": "Se os arco-\u00edris fossem escorregas, onde iriam parar?", "ro": "Dac\u0103 curcubeiele ar fi tobogane, unde ar ajunge?", "fr": "Si les arcs-en-ciel \u00e9taient des toboggans, o\u00f9 atterriraient-ils ?", "it": "Se gli arcobaleni fossero scivoli, dove atterrebbero?", "fi": "Jos sateenkaaret olisivat liukum\u00e4ki\u00e4, mihin ne laskeutuisivat?", "nl": "Als regenbogen glijbanen waren, waar zouden ze dan landen?", "no": "Hvis regnbuer var sklier, hvor ville de lande?", "sv": "Om regnb\u00e5gar var rutschkanor, var skulle de landa?", "pl": "Je\u015bli t\u0119cze by\u0142yby zje\u017cd\u017calniami, gdzie by l\u0105dowa\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If rainbows were slides, where would they land?';
UPDATE questions
SET translations = '{"en": "Name three things that are rough or bumpy.", "da": "N\u00e6vn tre ting, der er ru eller uj\u00e6vne.", "de": "Nenne drei Dinge, die rau oder uneben sind.", "es": "Nombra tres cosas que sean \u00e1speras o rugosas.", "pt": "Nomeia tr\u00eas coisas que sejam \u00e1speras ou irregulares.", "ro": "Nume\u0219te trei lucruri care sunt aspre sau denivelate.", "fr": "Nomme trois choses qui sont rugueuses ou bossel\u00e9es.", "it": "Nomina tre cose che sono ruvide o irregolari.", "fi": "Nime\u00e4 kolme asiaa, jotka ovat karheita tai ep\u00e4tasaisia.", "nl": "Noem drie dingen die ruw of hobbelig zijn.", "no": "Nevn tre ting som er grove eller ujevne.", "sv": "N\u00e4mn tre saker som \u00e4r grova eller oj\u00e4mna.", "pl": "Wymie\u0144 trzy rzeczy, kt\u00f3re s\u0105 szorstkie lub wyboiste."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Name three things that are rough or bumpy.';
UPDATE questions
SET translations = '{"en": "If you could make a new ice-cream flavor, what\u2019s in it?", "da": "Hvis du kunne lave en ny is-smag, hvad skulle der s\u00e5 v\u00e6re i den?", "de": "Wenn du eine neue Eissorte erfinden k\u00f6nntest, was w\u00e4re darin?", "es": "Si pudieras crear un nuevo sabor de helado, \u00bfqu\u00e9 tendr\u00eda?", "pt": "Se pudesses criar um novo sabor de gelado, o que teria?", "ro": "Dac\u0103 ai putea face o nou\u0103 arom\u0103 de \u00eenghe\u021bat\u0103, ce ar con\u021bine?", "fr": "Si tu pouvais inventer une nouvelle saveur de glace, qu\u2019y mettrais-tu ?", "it": "Se potessi creare un nuovo gusto di gelato, cosa ci metteresti dentro?", "fi": "Jos voisit tehd\u00e4 uuden j\u00e4\u00e4tel\u00f6maun, mit\u00e4 siin\u00e4 olisi?", "nl": "Als je een nieuwe ijsmaak zou kunnen maken, wat zit er dan in?", "no": "Hvis du kunne lage en ny iskrem-smak, hva ville v\u00e6rt i den?", "sv": "Om du kunde skapa en ny glassmak, vad skulle den inneh\u00e5lla?", "pl": "Gdyby\u015b m\u00f3g\u0142 stworzy\u0107 nowy smak lod\u00f3w, co by w nim by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could make a new ice-cream flavor, what’s in it?';
UPDATE questions
SET translations = '{"en": "What would you cook for Mom or Dad if it was their birthday?", "da": "Hvad ville du lave til mor eller far, hvis det var deres f\u00f8dselsdag?", "de": "Was w\u00fcrdest du f\u00fcr Mama oder Papa kochen, wenn sie Geburtstag h\u00e4tten?", "es": "\u00bfQu\u00e9 cocinar\u00edas para mam\u00e1 o pap\u00e1 si fuera su cumplea\u00f1os?", "pt": "O que cozinharias para a mam\u00e3e ou o papai se fosse o anivers\u00e1rio deles?", "ro": "Ce ai g\u0103ti pentru mama sau tata dac\u0103 ar fi ziua lor?", "fr": "Que cuisinerais-tu pour maman ou papa si c\u2019\u00e9tait leur anniversaire ?", "it": "Cosa cucineresti per la mamma o il pap\u00e0 se fosse il loro compleanno?", "fi": "Mit\u00e4 kokkaisit \u00e4idille tai is\u00e4lle, jos olisi heid\u00e4n syntym\u00e4p\u00e4iv\u00e4ns\u00e4?", "nl": "Wat zou je koken voor je moeder of vader als het hun verjaardag was?", "no": "Hva ville du laget til mamma eller pappa hvis det var bursdagen deres?", "sv": "Vad skulle du laga till mamma eller pappa om det var deras f\u00f6delsedag?", "pl": "Co by\u015b ugotowa\u0142 dla Mamy lub Taty, gdyby mieli urodziny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What would you cook for Mom or Dad if it was their birthday?';
UPDATE questions
SET translations = '{"en": "If you were a teacher for one hour, what would you teach?", "da": "Hvis du var l\u00e6rer i en time, hvad ville du undervise i?", "de": "Wenn du eine Stunde lang Lehrer w\u00e4rst, was w\u00fcrdest du unterrichten?", "es": "Si fueras maestro por una hora, \u00bfqu\u00e9 ense\u00f1ar\u00edas?", "pt": "Se fosses professor por uma hora, o que ensinarias?", "ro": "Dac\u0103 ai fi profesor pentru o or\u0103, ce ai preda?", "fr": "Si tu \u00e9tais enseignant pendant une heure, qu\u2019enseignerais-tu ?", "it": "Se fossi un insegnante per un''ora, cosa insegneresti?", "fi": "Jos olisit opettaja yhden tunnin ajan, mit\u00e4 opettaisit?", "nl": "Als je een uur lang leraar zou zijn, wat zou je dan onderwijzen?", "no": "Hvis du var l\u00e6rer i en time, hva ville du undervist i?", "sv": "Om du var l\u00e4rare i en timme, vad skulle du undervisa om?", "pl": "Gdyby\u015b by\u0142 nauczycielem przez jedn\u0105 godzin\u0119, co by\u015b naucza\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you were a teacher for one hour, what would you teach?';
UPDATE questions
SET translations = '{"en": "If you could change your name for a day, what would it be?", "da": "Hvis du kunne \u00e6ndre dit navn for en dag, hvad ville det v\u00e6re?", "de": "Wenn du deinen Namen f\u00fcr einen Tag \u00e4ndern k\u00f6nntest, wie w\u00fcrdest du hei\u00dfen?", "es": "Si pudieras cambiar tu nombre por un d\u00eda, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pudesses mudar o teu nome por um dia, qual seria?", "ro": "Dac\u0103 \u021bi-ai putea schimba numele pentru o zi, care ar fi?", "fr": "Si tu pouvais changer ton pr\u00e9nom pour une journ\u00e9e, lequel choisirais-tu ?", "it": "Se potessi cambiare il tuo nome per un giorno, quale sarebbe?", "fi": "Jos voisit vaihtaa nimesi yhdeksi p\u00e4iv\u00e4ksi, mik\u00e4 se olisi?", "nl": "Als je je naam voor een dag zou kunnen veranderen, wat zou het dan zijn?", "no": "Hvis du kunne endre navnet ditt for en dag, hva ville det v\u00e6rt?", "sv": "Om du kunde byta namn f\u00f6r en dag, vad skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 zmieni\u0107 swoje imi\u0119 na jeden dzie\u0144, jakie by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could change your name for a day, what would it be?';
UPDATE questions
SET translations = '{"en": "What would you do if your birthday lasted a whole week?", "da": "Hvad ville du g\u00f8re, hvis din f\u00f8dselsdag varede en hel uge?", "de": "Was w\u00fcrdest du tun, wenn dein Geburtstag eine ganze Woche dauern w\u00fcrde?", "es": "\u00bfQu\u00e9 har\u00edas si tu cumplea\u00f1os durara toda una semana?", "pt": "O que farias se o teu anivers\u00e1rio durasse uma semana inteira?", "ro": "Ce ai face dac\u0103 ziua ta de na\u0219tere ar dura o s\u0103pt\u0103m\u00e2n\u0103 \u00eentreag\u0103?", "fr": "Que ferais-tu si ton anniversaire durait toute une semaine ?", "it": "Cosa faresti se il tuo compleanno durasse un''intera settimana?", "fi": "Mit\u00e4 tekisit, jos syntym\u00e4p\u00e4iv\u00e4si kest\u00e4isi koko viikon?", "nl": "Wat zou je doen als je verjaardag een hele week duurde?", "no": "Hva ville du gjort hvis bursdagen din varte en hel uke?", "sv": "Vad skulle du g\u00f6ra om din f\u00f6delsedag varade en hel vecka?", "pl": "Co by\u015b zrobi\u0142, gdyby twoje urodziny trwa\u0142y ca\u0142y tydzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What would you do if your birthday lasted a whole week?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite part of having friends over?", "da": "Hvad er din yndlingsdel ved at have venner p\u00e5 bes\u00f8g?", "de": "Was ist dein Lieblingsteil daran, Freunde zu Besuch zu haben?", "es": "\u00bfCu\u00e1l es tu parte favorita de tener amigos en casa?", "pt": "Qual \u00e9 a tua parte favorita de ter amigos em casa?", "ro": "Care este partea ta preferat\u0103 c\u00e2nd vin prietenii \u00een vizit\u0103?", "fr": "Quelle est ta partie pr\u00e9f\u00e9r\u00e9e quand tes amis viennent \u00e0 la maison ?", "it": "Qual \u00e8 la tua parte preferita nell''avere amici a casa?", "fi": "Mik\u00e4 on lempiosasi siit\u00e4, ett\u00e4 yst\u00e4v\u00e4t tulevat kyl\u00e4\u00e4n?", "nl": "Wat is jouw favoriete onderdeel van vrienden over de vloer hebben?", "no": "Hva er din favorittdel ved \u00e5 ha venner p\u00e5 bes\u00f8k?", "sv": "Vad \u00e4r din favoritdel med att ha v\u00e4nner \u00f6ver?", "pl": "Jaka jest twoja ulubiona cz\u0119\u015b\u0107 zapraszania przyjaci\u00f3\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What’s your favorite part of having friends over?';