UPDATE questions
SET translations = '{"en": "Your pet stares at an empty corner for a full minute. What could it be?", "da": "Dit k\u00e6ledyr stirrer p\u00e5 et tomt hj\u00f8rne i et helt minut. Hvad kan det v\u00e6re?", "de": "Dein Haustier starrt eine leere Ecke eine Minute lang an. Was k\u00f6nnte es sein?", "es": "Tu mascota mira fijamente una esquina vac\u00eda durante un minuto. \u00bfQu\u00e9 podr\u00eda ser?", "pt": "O teu animal de estima\u00e7\u00e3o encara um canto vazio por um minuto. O que ser\u00e1?", "ro": "Animalul t\u0103u de companie se uit\u0103 fix \u00eentr-un col\u021b gol timp de un minut. Ce ar putea fi?", "fr": "Ton animal regarde un coin vide pendant une minute enti\u00e8re. Qu\u2019est-ce que \u00e7a pourrait \u00eatre ?", "it": "Il tuo animale domestico fissa un angolo vuoto per un minuto intero. Cosa potrebbe essere?", "fi": "Lemmikkisi tuijottaa tyhj\u00e4\u00e4 nurkkaa kokonaisen minuutin. Mit\u00e4 se voisi olla?", "nl": "Je huisdier staart een volle minuut naar een lege hoek. Wat zou het kunnen zijn?", "no": "Kj\u00e6ledyret ditt stirrer p\u00e5 et tomt hj\u00f8rne i et helt minutt. Hva kan det v\u00e6re?", "sv": "Ditt husdjur stirrar p\u00e5 ett tomt h\u00f6rn i en hel minut. Vad kan det vara?", "pl": "Tw\u00f3j pupil przez ca\u0142\u0105 minut\u0119 gapi si\u0119 w pusty k\u0105t. Co to mo\u017ce by\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your pet stares at an empty corner for a full minute. What could it be?';
UPDATE questions
SET translations = '{"en": "Pick one to witness: UFO, time traveler, or a ghost \u2013 which one do you choose?", "da": "Du m\u00e5 v\u00e6lge \u00e9n ting at se: UFO, tidsrejsende eller et sp\u00f8gelse \u2013 hvad v\u00e6lger du?", "de": "Du darfst eines sehen: UFO, Zeitreisenden oder Geist \u2013 was w\u00e4hlst du?", "es": "Puedes elegir presenciar uno: un OVNI, un viajero del tiempo o un fantasma. \u00bfCu\u00e1l eliges?", "pt": "Podes escolher ver um: OVNI, viajante no tempo ou fantasma \u2013 qual escolhes?", "ro": "Po\u021bi alege s\u0103 vezi un singur lucru: un OZN, un c\u0103l\u0103tor \u00een timp sau o fantom\u0103 \u2013 ce alegi?", "fr": "Tu peux en voir un seul : OVNI, voyageur du temps ou fant\u00f4me \u2013 lequel choisis-tu ?", "it": "Scegline uno da vedere: UFO, viaggiatore nel tempo o fantasma \u2013 quale scegli?", "fi": "Valitse yksi n\u00e4ht\u00e4v\u00e4ksi: UFO, aikamatkustaja vai kummitus \u2013 mink\u00e4 otat?", "nl": "Kies er \u00e9\u00e9n om mee te maken: UFO, tijdreiziger of geest \u2013 welke kies je?", "no": "Velg \u00e9n \u00e5 v\u00e6re vitne til: UFO, tidsreisende eller et sp\u00f8kelse \u2013 hvilken velger du?", "sv": "V\u00e4lj en att f\u00e5 bevittna: UFO, tidsresen\u00e4r eller ett sp\u00f6ke \u2013 vilken v\u00e4ljer du?", "pl": "Wybierz jedno, czego chcesz by\u0107 \u015bwiadkiem: UFO, podr\u00f3\u017cnik w czasie czy duch \u2013 co wybierasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Pick one to witness: UFO, time traveler, or a ghost – which one do you choose?';
UPDATE questions
SET translations = '{"en": "A date knows a private detail you never shared. Do you ask how, or end the date?", "da": "En date ved en privat detalje, du aldrig har delt. Sp\u00f8rger du hvordan, eller stopper du daten?", "de": "Ein Date kennt ein privates Detail, das du nie geteilt hast. Fragst du, wie er/sie das wei\u00df, oder beendest du das Date?", "es": "Una cita sabe un detalle privado que nunca compartiste. \u00bfPreguntas c\u00f3mo lo sabe o terminas la cita?", "pt": "Um encontro sabe um detalhe privado que nunca contaste. Perguntas como ou acabas o encontro?", "ro": "O persoan\u0103 cu care e\u0219ti la o \u00eent\u00e2lnire \u0219tie un detaliu privat pe care nu l-ai \u00eemp\u0103rt\u0103\u0219it niciodat\u0103. \u00centrebi cum \u0219tie sau \u00eenchei \u00eent\u00e2lnirea?", "fr": "Un rendez-vous conna\u00eet un d\u00e9tail priv\u00e9 que tu n\u2019as jamais partag\u00e9. Tu demandes comment ou tu mets fin au rendez-vous ?", "it": "Un appuntamento sa un dettaglio privato che non hai mai raccontato. Chiedi come fa a saperlo o chiudi l\u2019appuntamento?", "fi": "Treffi tiet\u00e4\u00e4 yksityiskohdan, jota et ole koskaan kertonut. Kysytk\u00f6 miten h\u00e4n sen tiet\u00e4\u00e4 vai lopetatko treffit?", "nl": "Een date weet een priv\u00e9-detail dat je nooit hebt verteld. Vraag je hoe hij/zij dat weet, of be\u00ebindig je de date?", "no": "En date vet en privat detalj du aldri har delt. Sp\u00f8r du hvordan, eller avslutter du daten?", "sv": "En dejt vet en privat detalj du aldrig ber\u00e4ttat. Fr\u00e5gar du hur hen vet det, eller avslutar du dejten?", "pl": "Osoba na randce zna prywatny szczeg\u00f3\u0142, kt\u00f3rego nigdy nie zdradzi\u0142e\u015b/-a\u015b. Pytasz, sk\u0105d wie, czy ko\u0144czysz randk\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A date knows a private detail you never shared. Do you ask how, or end the date?';
UPDATE questions
SET translations = '{"en": "If you could ask a ghost one question, what would it be?", "da": "Hvis du kunne stille et sp\u00f8gelse \u00e9t sp\u00f8rgsm\u00e5l, hvad ville det v\u00e6re?", "de": "Wenn du einem Geist eine Frage stellen k\u00f6nntest, welche w\u00e4re das?", "es": "Si pudieras hacerle una pregunta a un fantasma, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pudesses fazer uma pergunta a um fantasma, qual seria?", "ro": "Dac\u0103 ai putea pune o singur\u0103 \u00eentrebare unei fantome, care ar fi?", "fr": "Si tu pouvais poser une question \u00e0 un fant\u00f4me, laquelle serait-ce ?", "it": "Se potessi fare una domanda a un fantasma, quale sarebbe?", "fi": "Jos voisit kysy\u00e4 kummitukselta yhden kysymyksen, mik\u00e4 se olisi?", "nl": "Als je een geest \u00e9\u00e9n vraag kon stellen, welke zou dat zijn?", "no": "Hvis du kunne stille et sp\u00f8kelse ett sp\u00f8rsm\u00e5l, hva ville det v\u00e6rt?", "sv": "Om du kunde st\u00e4lla ett sp\u00f6ke en fr\u00e5ga, vad skulle du fr\u00e5ga?", "pl": "Gdyby\u015b m\u00f3g\u0142/mog\u0142a zada\u0107 duchowi jedno pytanie, jakie by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If you could ask a ghost one question, what would it be?';
UPDATE questions
SET translations = '{"en": "A rideshare driver locks the doors and says the route \u201cjust changed.\u201d What do you do next?", "da": "En chauff\u00f8r l\u00e5ser d\u00f8rene og siger, at ruten \u201clige har \u00e6ndret sig.\u201d Hvad g\u00f8r du?", "de": "Ein Fahrdienstfahrer verriegelt die T\u00fcren und sagt, die Route \u201ehat sich gerade ge\u00e4ndert.\u201c Was tust du?", "es": "Un conductor cierra las puertas y dice que la ruta \u201cacaba de cambiar\u201d. \u00bfQu\u00e9 haces?", "pt": "Um motorista tranca as portas e diz que a rota \u201cacabou de mudar\u201d. O que fazes?", "ro": "\u0218oferul de rideshare \u00eencuie u\u0219ile \u0219i spune c\u0103 ruta \u201etocmai s-a schimbat.\u201d Ce faci?", "fr": "Un chauffeur verrouille les portes et dit que l\u2019itin\u00e9raire \u00ab vient de changer \u00bb. Que fais-tu ?", "it": "Un autista di rideshare chiude le portiere e dice che il percorso \"\u00e8 appena cambiato\". Cosa fai dopo?", "fi": "Kyytipalvelun kuski lukitsee ovet ja sanoo reitin \"juuri muuttuneen\". Mit\u00e4 teet seuraavaksi?", "nl": "Een rideshare-chauffeur doet de deuren op slot en zegt dat de route \"net is veranderd\". Wat doe je daarna?", "no": "En samkj\u00f8ringssj\u00e5f\u00f8r l\u00e5ser d\u00f8rene og sier at ruta \"nettopp ble endret\". Hva gj\u00f8r du n\u00e5?", "sv": "En sam\u00e5kningschauff\u00f6r l\u00e5ser d\u00f6rrarna och s\u00e4ger att rutten \"just \u00e4ndrades\". Vad g\u00f6r du sedan?", "pl": "Kierowca przejazdu z aplikacji rygluje drzwi i m\u00f3wi, \u017ce trasa \"w\u0142a\u015bnie si\u0119 zmieni\u0142a\". Co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A rideshare driver locks the doors and says the route “just changed.” What do you do next?';
UPDATE questions
SET translations = '{"en": "What\u2019s your family\u2019s oddest good-luck ritual?", "da": "Hvad er din families m\u00e6rkeligste lykkebringende ritual?", "de": "Was ist das seltsamste Gl\u00fccksritual deiner Familie?", "es": "\u00bfCu\u00e1l es el ritual de buena suerte m\u00e1s extra\u00f1o de tu familia?", "pt": "Qual \u00e9 o ritual de sorte mais estranho da tua fam\u00edlia?", "ro": "Care este cel mai ciudat ritual de noroc al familiei tale?", "fr": "Quel est le rituel porte-bonheur le plus \u00e9trange de ta famille ?", "it": "Qual \u00e8 il rito portafortuna pi\u00f9 strano della tua famiglia?", "fi": "Mik\u00e4 on perheesi oudoin onnea tuova rituaali?", "nl": "Wat is het vreemdste geluksritueel van jouw familie?", "no": "Hva er familiens rareste lykkeritual?", "sv": "Vad \u00e4r din familjs konstigaste tur-ritual?", "pl": "Jaki jest najdziwniejszy rytua\u0142 na szcz\u0119\u015bcie w twojej rodzinie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s your family’s oddest good-luck ritual?';
UPDATE questions
SET translations = '{"en": "Share a dream you remember too clearly. Any meaning?", "da": "Del en dr\u00f8m, du husker alt for tydeligt. Nogen betydning?", "de": "Teile einen Traum, an den du dich zu gut erinnerst. Irgendeine Bedeutung?", "es": "Comparte un sue\u00f1o que recuerdes con demasiada claridad. \u00bfAlg\u00fan significado?", "pt": "Partilha um sonho que te lembras demasiado bem. Tem algum significado?", "ro": "Poveste\u0219te un vis pe care \u021bi-l aminte\u0219ti prea clar. Ce \u00een\u021beles are?", "fr": "Partage un r\u00eave dont tu te souviens trop bien. Une signification ?", "it": "Condividi un sogno che ricordi fin troppo bene. Che significato potrebbe avere?", "fi": "Kerro unesta, jonka muistat liian tarkasti. Onko sill\u00e4 mielest\u00e4si jokin merkitys?", "nl": "Deel een droom die je te goed herinnert. Zie je er een betekenis in?", "no": "Del en dr\u00f8m du husker altfor godt. Noen mening i den?", "sv": "Dela en dr\u00f6m du minns alldeles f\u00f6r tydligt. N\u00e5gon betydelse?", "pl": "Podziel si\u0119 snem, kt\u00f3ry pami\u0119tasz a\u017c za dobrze. Ma dla ciebie jakie\u015b znaczenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Share a dream you remember too clearly. Any meaning?';
UPDATE questions
SET translations = '{"en": "A crime case you can\u2019t stop thinking about\u2014why this one?", "da": "En kriminalsag, du ikke kan glemme \u2013 hvorfor netop den?", "de": "Ein Kriminalfall, \u00fcber den du nicht aufh\u00f6ren kannst nachzudenken \u2013 warum dieser?", "es": "Un caso criminal que no puedes dejar de pensar \u2013 \u00bfpor qu\u00e9 ese?", "pt": "Um caso criminal que n\u00e3o consegues esquecer \u2013 porqu\u00ea esse?", "ro": "Un caz criminal de care nu te po\u021bi desprinde \u2013 de ce tocmai acesta?", "fr": "Une affaire criminelle \u00e0 laquelle tu penses encore \u2013 pourquoi celle-l\u00e0 ?", "it": "Un caso di cronaca nera a cui non riesci a smettere di pensare: perch\u00e9 proprio questo?", "fi": "Rikostapaus, jota et saa mielest\u00e4si \u2013 miksi juuri t\u00e4m\u00e4?", "nl": "Een strafzaak waar je maar aan blijft denken \u2013 waarom juist deze?", "no": "En kriminalsak du ikke klarer \u00e5 slutte \u00e5 tenke p\u00e5 \u2013 hvorfor akkurat denne?", "sv": "Ett kriminalfall du inte kan sluta t\u00e4nka p\u00e5 \u2013 varf\u00f6r just det?", "pl": "Sprawa kryminalna, o kt\u00f3rej nie mo\u017cesz przesta\u0107 my\u015ble\u0107 \u2013 dlaczego w\u0142a\u015bnie ta?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A crime case you can’t stop thinking about—why this one?';
UPDATE questions
SET translations = '{"en": "Footsteps outside your door, peephole blocked \u2013 what do you do?", "da": "Fodtrin udenfor din d\u00f8r, kighul blokeret \u2013 hvad g\u00f8r du?", "de": "Schritte vor deiner T\u00fcr, Spion blockiert \u2013 was tust du?", "es": "Pasos fuera de tu puerta, mirilla bloqueada \u2013 \u00bfqu\u00e9 haces?", "pt": "Passos fora da tua porta, olho m\u00e1gico bloqueado \u2013 o que fazes?", "ro": "Se aud pa\u0219i \u00een fa\u021ba u\u0219ii tale, vizorul este blocat \u2013 ce faci?", "fr": "Des pas devant ta porte, judas bloqu\u00e9 \u2013 que fais-tu ?", "it": "Passi fuori dalla porta, spioncino coperto \u2013 cosa fai?", "fi": "Askeleita oven ulkopuolella, ovisilm\u00e4 peitetty \u2013 mit\u00e4 teet?", "nl": "Voetstappen buiten je deur, deurspion afgeplakt \u2013 wat doe je?", "no": "Fottrinn utenfor d\u00f8ren din, d\u00f8rspionen er blokkert \u2013 hva gj\u00f8r du?", "sv": "Fotsteg utanf\u00f6r din d\u00f6rr, titth\u00e5let \u00e4r blockerat \u2013 vad g\u00f6r du?", "pl": "Kroki za drzwiami, wizjer zas\u0142oni\u0119ty \u2013 co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Footsteps outside your door, peephole blocked – what do you do?';
UPDATE questions
SET translations = '{"en": "Motion sensor lights turn on in the empty next room. How do you clear the space?", "da": "Bev\u00e6gelsessensorlys t\u00e6nder i det tomme rum ved siden af. Hvordan tjekker du det?", "de": "Bewegungsmelderlicht geht im leeren Nebenraum an. Wie pr\u00fcfst du den Raum?", "es": "Las luces con sensor se encienden en la habitaci\u00f3n vac\u00eda de al lado. \u00bfC\u00f3mo revisas el lugar?", "pt": "A luz do sensor de movimento acende-se no quarto ao lado. Como verificas?", "ro": "Lumina cu senzor de mi\u0219care se aprinde \u00een camera goal\u0103 de al\u0103turi. Cum verifici spa\u021biul?", "fr": "Les lumi\u00e8res \u00e0 capteur de mouvement s\u2019allument dans la pi\u00e8ce voisine vide. Comment v\u00e9rifies-tu ?", "it": "Le luci con sensore di movimento si accendono nella stanza vuota accanto. Come \"ripulisci\" lo spazio?", "fi": "Liiketunnistinvalot syttyv\u00e4t tyhj\u00e4\u00e4n viereiseen huoneeseen. Miten \"puhdistat\" tilan?", "nl": "Bewegingssensorlampen gaan aan in de lege kamer naast je. Hoe \"reinig\" je de ruimte?", "no": "Bevegelsessensorlysene sl\u00e5r seg p\u00e5 i det tomme rommet ved siden av. Hvordan \"renser\" du stedet?", "sv": "R\u00f6relsesensorlampor t\u00e4nds i det tomma rummet bredvid. Hur \"rensar\" du platsen?", "pl": "Czujniki ruchu zapalaj\u0105 \u015bwiat\u0142o w pustym pokoju obok. Jak \"oczyszczasz\" t\u0119 przestrze\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Motion sensor lights turn on in the empty next room. How do you clear the space?';