UPDATE questions
SET translations = '{"en": "What\u2019s the most impulsive or reckless thing you\u2019ve ever done just for the thrill?", "da": "Hvad er det mest impulsive eller hensynsl\u00f8se, du nogensinde har gjort bare for sp\u00e6ndingens skyld?", "de": "Hvilken slags belysning eller atmosf\u00e6re t\u00e6nder dig mest?", "es": "Welche Art von Licht oder Atmosph\u00e4re erregt dich am meisten?", "pt": "Qual foi a coisa mais impulsiva ou imprudente que j\u00e1 fizeste s\u00f3 pela emo\u00e7\u00e3o?", "ro": "Care este cel mai impulsiv sau nechibzuit lucru pe care l-ai f\u0103cut doar pentru adrenalin\u0103?", "fr": "Quelle est la chose la plus impulsive ou imprudente que tu aies faite juste pour le frisson ?", "it": "Qual \u00e8 la cosa pi\u00f9 impulsiva o avventata che hai mai fatto solo per il brivido?", "fi": "Mik\u00e4 on impulsiivisin tai holtittomin asia, jonka olet koskaan tehnyt vain j\u00e4nnityksen vuoksi?", "nl": "Wat is het meest impulsieve of roekeloze dat je ooit hebt gedaan, gewoon voor de spanning?", "no": "Hva er det mest impulsive eller hensynsl\u00f8se du noen gang har gjort bare for spenningen?", "sv": "Vad \u00e4r det mest impulsiva eller riskfyllda du n\u00e5gonsin har gjort bara f\u00f6r sp\u00e4nningens skull?", "pl": "Jak\u0105 najbardziej impulsywn\u0105 lub lekkomy\u015bln\u0105 rzecz kiedykolwiek zrobi\u0142e\u015b tylko dla dreszczyku emocji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s the most impulsive or reckless thing you’ve ever done just for the thrill?';
UPDATE questions
SET translations = '{"en": "What does financial independence mean to you in a relationship?", "da": "Hvad betyder \u00f8konomisk uafh\u00e6ngighed for dig i et forhold?", "de": "Hvordan kan du lide, at jeg viser dig, at jeg er i hum\u00f8r til det?", "es": "Wie magst du es, wenn ich dir zeige, dass ich in Stimmung bin?", "pt": "O que significa independ\u00eancia financeira para ti num relacionamento?", "ro": "Ce \u00eenseamn\u0103 independen\u021ba financiar\u0103 pentru tine \u00eentr-o rela\u021bie?", "fr": "Que signifie l\u2019ind\u00e9pendance financi\u00e8re pour toi dans une relation ?", "it": "Cosa significa per te l''indipendenza finanziaria in una relazione?", "fi": "Mit\u00e4 taloudellinen itsen\u00e4isyys merkitsee sinulle suhteessa?", "nl": "Wat betekent financi\u00eble onafhankelijkheid voor jou in een relatie?", "no": "Hva betyr \u00f8konomisk uavhengighet for deg i et forhold?", "sv": "Vad betyder ekonomisk oberoende f\u00f6r dig i en relation?", "pl": "Co dla Ciebie oznacza niezale\u017cno\u015b\u0107 finansowa w zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What does financial independence mean to you in a relationship?';
UPDATE questions
SET translations = '{"en": "How do you feel about your body right now?", "da": "Hvordan har du det med din krop lige nu?", "de": "Kan du lide, n\u00e5r jeg holder om dit ansigt eller dine hofter?", "es": "Magst du es, wenn ich dein Gesicht oder deine H\u00fcften halte?", "pt": "Como te sentes com o teu corpo neste momento?", "ro": "Cum te sim\u021bi \u00een leg\u0103tur\u0103 cu corpul t\u0103u acum?", "fr": "Comment te sens-tu par rapport \u00e0 ton corps en ce moment ?", "it": "Come ti senti riguardo al tuo corpo in questo momento?", "fi": "Milt\u00e4 sinusta tuntuu kehostasi juuri nyt?", "nl": "Hoe voel je je op dit moment over je lichaam?", "no": "Hvordan f\u00f8ler du deg om kroppen din akkurat n\u00e5?", "sv": "Hur k\u00e4nner du f\u00f6r din kropp just nu?", "pl": "Jak si\u0119 czujesz ze swoim cia\u0142em w tej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about your body right now?';
UPDATE questions
SET translations = '{"en": "Are you friends with your exes on social media? Why/why not?", "da": "Er du venner med dine ekser p\u00e5 sociale medier? Hvorfor/hvorfor ikke?", "de": "Hvad er din personlige definition af \"forf\u00f8rende\"?", "es": "Was ist deine pers\u00f6nliche Definition von \u201everf\u00fchrerisch\u201c?", "pt": "\u00c9s amigo dos teus ex nas redes sociais? Porqu\u00ea / porqu\u00ea n\u00e3o?", "ro": "E\u0219ti prieten cu fo\u0219tii t\u0103i pe re\u021belele sociale? De ce / de ce nu?", "fr": "Es-tu ami avec tes ex sur les r\u00e9seaux sociaux ? Pourquoi / pourquoi pas ?", "it": "Sei amico dei tuoi ex sui social media? Perch\u00e9 s\u00ec o perch\u00e9 no?", "fi": "Oletko yst\u00e4vi\u00e4 entisten kumppanien kanssa sosiaalisessa mediassa? Miksi/miksi ei?", "nl": "Ben je bevriend met je exen op sociale media? Waarom wel/niet?", "no": "Er du venn med eksene dine p\u00e5 sosiale medier? Hvorfor/hvorfor ikke?", "sv": "\u00c4r du v\u00e4nner med dina ex p\u00e5 sociala medier? Varf\u00f6r/varf\u00f6r inte?", "pl": "Czy jeste\u015b w przyja\u017ani z by\u0142ymi na mediach spo\u0142eczno\u015bciowych? Dlaczego/dlaczego nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Are you friends with your exes on social media? Why/why not?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the last person you looked up online just out of curiosity \u2014 and why?", "da": "Hvem er den sidste person, du slog op p\u00e5 online bare af nysgerrighed \u2014 og hvorfor?", "de": "Hvis nogen ville l\u00e6re pr\u00e6cis, hvordan de kunne behage dig, hvad er s\u00e5 det f\u00f8rste, de skulle v\u00e6re opm\u00e6rksomme p\u00e5?", "es": "Wenn jemand genau lernen wollte, wie man dich befriedigt \u2013 worauf sollte er als Erstes achten?", "pt": "Quem foi a \u00faltima pessoa que pesquisaste online por curiosidade \u2014 e porqu\u00ea?", "ro": "Cine e ultima persoan\u0103 pe care ai c\u0103utat-o online din curiozitate \u2014 \u0219i de ce?", "fr": "Quelle est la derni\u00e8re personne que tu as cherch\u00e9e en ligne par curiosit\u00e9 \u2014 et pourquoi ?", "it": "Chi \u00e8 stata l''ultima persona che hai cercato online per curiosit\u00e0 \u2014 e perch\u00e9?", "fi": "Kuka oli viimeinen henkil\u00f6, jota etsit verkosta uteliaisuudesta \u2014 ja miksi?", "nl": "Wie is de laatste persoon die je online hebt opgezocht uit nieuwsgierigheid \u2014 en waarom?", "no": "Hvem var den siste personen du s\u00f8kte opp p\u00e5 nettet bare av nysgjerrighet \u2014 og hvorfor?", "sv": "Vem var den senaste personen du s\u00f6kte p\u00e5 n\u00e4tet av ren nyfikenhet \u2014 och varf\u00f6r?", "pl": "Kto by\u0142 ostatni\u0105 osob\u0105, kt\u00f3r\u0105 wyszuka\u0142e\u015b w Internecie z ciekawo\u015bci \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who’s the last person you looked up online just out of curiosity — and why?';
UPDATE questions
SET translations = '{"en": "When\u2019s the last time you got caught in a small lie \u2014 and what did you learn from it?", "da": "Hvorn\u00e5r blev du sidst fanget i en lille l\u00f8gn \u2014 og hvad l\u00e6rte du af det?", "de": "Er der noget, du gerne vil have, at jeg kalder dig, n\u00e5r vi har sex?", "es": "Gibt es etwas, wie ich dich nennen soll, wenn wir Sex haben?", "pt": "Quando foi a \u00faltima vez que foste apanhado numa pequena mentira \u2014 e o que aprendeste?", "ro": "C\u00e2nd ai fost prins ultima dat\u0103 \u00eentr-o mic\u0103 minciun\u0103 \u2014 \u0219i ce ai \u00eenv\u0103\u021bat din asta?", "fr": "Quand t\u2019a-t-on pris pour la derni\u00e8re fois dans un petit mensonge \u2014 et qu\u2019en as-tu appris ?", "it": "Quando \u00e8 stata l''ultima volta che sei stato sorpreso in una piccola bugia \u2014 e cosa hai imparato da essa?", "fi": "Milloin viimeksi jouduit kiinni pienest\u00e4 valheesta \u2014 ja mit\u00e4 opit siit\u00e4?", "nl": "Wanneer was de laatste keer dat je betrapt werd op een klein leugentje \u2014 en wat heb je daaruit geleerd?", "no": "N\u00e5r var siste gang du ble tatt i en liten l\u00f8gn \u2014 og hva l\u00e6rte du av det?", "sv": "N\u00e4r var senaste g\u00e5ngen du blev tagen p\u00e5 en liten l\u00f6gn \u2014 och vad l\u00e4rde du dig av det?", "pl": "Kiedy ostatni raz wpad\u0142e\u015b w ma\u0142e k\u0142amstwo \u2014 i czego si\u0119 z tego nauczy\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When’s the last time you got caught in a small lie — and what did you learn from it?';
UPDATE questions
SET translations = '{"en": "Have you ever kept someone in your life longer than you should have?", "da": "Har du nogensinde beholdt nogen i dit liv l\u00e6ngere, end du burde have?", "de": "Hast du jemals jemanden l\u00e4nger in deinem Leben behalten, als du solltest?", "es": "\u00bfAlguna vez mantuviste a alguien en tu vida m\u00e1s tiempo del que deber\u00edas?", "pt": "J\u00e1 mantiveste algu\u00e9m na tua vida por mais tempo do que devias?", "ro": "Ai \u021binut vreodat\u0103 pe cineva \u00een via\u021ba ta mai mult dec\u00e2t trebuia?", "fr": "As-tu d\u00e9j\u00e0 gard\u00e9 quelqu\u2019un dans ta vie plus longtemps que tu n\u2019aurais d\u00fb ?", "it": "Hai mai tenuto qualcuno nella tua vita pi\u00f9 a lungo di quanto avresti dovuto?", "fi": "Oletko koskaan pit\u00e4nyt jotakuta el\u00e4m\u00e4ss\u00e4si pidemp\u00e4\u00e4n kuin olisi pit\u00e4nyt?", "nl": "Heb je ooit iemand langer in je leven gehouden dan je eigenlijk zou moeten?", "no": "Har du noen gang hatt noen i livet ditt lenger enn du burde?", "sv": "Har du n\u00e5gonsin haft n\u00e5gon i ditt liv l\u00e4ngre \u00e4n du borde?", "pl": "Czy kiedykolwiek trzyma\u0142e\u015b kogo\u015b w swoim \u017cyciu d\u0142u\u017cej, ni\u017c powiniene\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever kept someone in your life longer than you should have?';
UPDATE questions
SET translations = '{"en": "How do you handle it when you disagree deeply with someone you love?", "da": "Hvordan h\u00e5ndterer du det, n\u00e5r du er uenig med nogen, du elsker?", "de": "Wie gehst du damit um, wenn du mit jemandem, den du liebst, tief uneinig bist?", "es": "\u00bfC\u00f3mo manejas el estar en desacuerdo con alguien a quien amas?", "pt": "Como lidas quando discordas profundamente de algu\u00e9m que amas?", "ro": "Cum gestionezi o ne\u00een\u021belegere profund\u0103 cu cineva pe care \u00eel iube\u0219ti?", "fr": "Comment g\u00e8res-tu un d\u00e9saccord profond avec quelqu\u2019un que tu aimes ?", "it": "Come gestisci la situazione quando non sei d''accordo profondamente con qualcuno che ami?", "fi": "Miten toimit, kun olet syv\u00e4sti eri mielt\u00e4 jonkun rakastamasi kanssa?", "nl": "Hoe ga je ermee om als je diep van mening verschilt met iemand van wie je houdt?", "no": "Hvordan h\u00e5ndterer du det n\u00e5r du er dypt uenig med noen du elsker?", "sv": "Hur hanterar du det n\u00e4r du har djupa meningsskiljaktigheter med n\u00e5gon du \u00e4lskar?", "pl": "Jak radzisz sobie, gdy g\u0142\u0119boko si\u0119 z kim\u015b, kogo kochasz, nie zgadzasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you handle it when you disagree deeply with someone you love?';
UPDATE questions
SET translations = '{"en": "Is there a public figure whose ideas you secretly respect, even if most people around you don\u2019t?", "da": "Er der en offentlig person, hvis ideer du hemmeligt respekterer, selvom de fleste omkring dig ikke g\u00f8r?", "de": "Gibt es eine \u00f6ffentliche Person, deren Ideen du heimlich respektierst, auch wenn die meisten um dich herum es nicht tun?", "es": "\u00bfHay una figura p\u00fablica cuyas ideas respetas en secreto, aunque la mayor\u00eda a tu alrededor no?", "pt": "H\u00e1 uma figura p\u00fablica cujas ideias respeitas secretamente, mesmo que a maioria \u00e0 tua volta n\u00e3o?", "ro": "Exist\u0103 o persoan\u0103 public\u0103 ale c\u0103rei idei le respec\u021bi \u00een secret, chiar dac\u0103 majoritatea nu?", "fr": "Y a-t-il une personnalit\u00e9 publique dont tu respectes secr\u00e8tement les id\u00e9es, m\u00eame si la plupart ne le font pas ?", "it": "C''\u00e8 una figura pubblica le cui idee rispetti segretamente, anche se la maggior parte delle persone intorno a te non lo fa?", "fi": "Onko olemassa julkista henkil\u00f6\u00e4, jonka ajatuksia salaa kunnioitat, vaikka useimmat ymp\u00e4rill\u00e4si eiv\u00e4t?", "nl": "Is er een publieke figuur wiens idee\u00ebn je stiekem respecteert, ook al doen de meeste mensen om je heen dat niet?", "no": "Er det en offentlig person hvis ideer du hemmelig respekterer, selv om de fleste rundt deg ikke gj\u00f8r det?", "sv": "Finns det en offentlig person vars id\u00e9er du hemligt respekterar, \u00e4ven om de flesta omkring dig inte g\u00f6r det?", "pl": "Czy jest jaka\u015b posta\u0107 publiczna, kt\u00f3rej pomys\u0142y potajemnie szanujesz, nawet je\u015bli wi\u0119kszo\u015b\u0107 ludzi wok\u00f3\u0142 ciebie ich nie docenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Is there a public figure whose ideas you secretly respect, even if most people around you don’t?';
UPDATE questions
SET translations = '{"en": "Have you ever felt a little jealous of someone close to me? What made you feel that way?", "da": "Har du nogensinde v\u00e6ret lidt jaloux p\u00e5 nogen t\u00e6t p\u00e5 mig? Hvad fik dig til at f\u00f8le s\u00e5dan?", "de": "Warst du jemals ein bisschen eifers\u00fcchtig auf jemanden, der mir nahe steht? Was hat dich so f\u00fchlen lassen?", "es": "\u00bfAlguna vez te has sentido un poco celoso de alguien cercano a m\u00ed? \u00bfQu\u00e9 te hizo sentir as\u00ed?", "pt": "Alguma vez sentiste um pouco de ci\u00fames de algu\u00e9m pr\u00f3ximo de mim? O que te fez sentir assim?", "ro": "Te-ai sim\u021bit vreodat\u0103 pu\u021bin gelos pe cineva apropiat mie? Ce te-a f\u0103cut s\u0103 sim\u021bi asta?", "fr": "As-tu d\u00e9j\u00e0 \u00e9t\u00e9 un peu jaloux de quelqu\u2019un de proche de moi ? Qu\u2019est-ce qui t\u2019a fait ressentir \u00e7a ?", "it": "Hai mai provato un po'' di gelosia nei confronti di qualcuno a me vicino? Cosa ti ha fatto sentire in questo modo?", "fi": "Oletko koskaan tuntenut pient\u00e4 kateutta jotakuta l\u00e4heist\u00e4ni kohtaan? Mik\u00e4 sai sinut tuntemaan niin?", "nl": "Heb je ooit een beetje jaloers gevoeld op iemand die dicht bij me staat? Wat deed je zo voelen?", "no": "Har du noen gang f\u00f8lt deg litt sjalu p\u00e5 noen som st\u00e5r meg n\u00e6r? Hva fikk deg til \u00e5 f\u00f8le det slik?", "sv": "Har du n\u00e5gonsin k\u00e4nt dig lite avundsjuk p\u00e5 n\u00e5gon som st\u00e5r mig n\u00e4ra? Vad fick dig att k\u00e4nna s\u00e5?", "pl": "Czy kiedykolwiek czu\u0142e\u015b si\u0119 troch\u0119 zazdrosny o kogo\u015b bliskiego mi? Co sprawi\u0142o, \u017ce tak si\u0119 poczu\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever felt a little jealous of someone close to me? What made you feel that way?';