UPDATE questions
SET translations = '{"en": "What\u2019s an opinion or belief you hold that most people wouldn\u2019t guess about you?", "da": "Hvilken holdning eller tro har du, som de fleste ikke ville g\u00e6tte om dig?", "de": "Hvad er noget legende, du ville \u00f8nske, vi gjorde oftere?", "es": "Was ist etwas Verspieltes, das du dir w\u00fcnschst, wir w\u00fcrden \u00f6fter tun?", "pt": "Que opini\u00e3o ou cren\u00e7a tens que a maioria n\u00e3o imaginaria sobre ti?", "ro": "Ce convingere ai pe care majoritatea nu ar ghici-o despre tine?", "fr": "Quelle opinion ou croyance as-tu que la plupart des gens ne devineraient pas \u00e0 ton sujet ?", "it": "Qual \u00e8 un''opinione o una convinzione che hai e che la maggior parte delle persone non indovinerebbe su di te?", "fi": "Mik\u00e4 on mielipide tai uskomus, jonka sinusta useimmat ihmiset eiv\u00e4t arvaisi?", "nl": "Wat is een mening of overtuiging die je hebt en waarvan de meeste mensen niet zouden raden dat je die hebt?", "no": "Hva er en mening eller tro du har som de fleste ikke ville gjettet om deg?", "sv": "Vilken \u00e5sikt eller tro har du som de flesta m\u00e4nniskor inte skulle gissa om dig?", "pl": "Jakie jest twoje zdanie lub przekonanie, kt\u00f3re wi\u0119kszo\u015b\u0107 ludzi by o tobie nie zgad\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s an opinion or belief you hold that most people wouldn’t guess about you?';
UPDATE questions
SET translations = '{"en": "Have you ever looked through someone\u2019s phone out of curiosity? Be honest.", "da": "Har du nogensinde kigget gennem nogens telefon af nysgerrighed? V\u00e6r \u00e6rlig.", "de": "Hvad er dit yndlingstidspunkt p\u00e5 dagen at blive intim?", "es": "Was ist deine Lieblingszeit am Tag, um intim zu werden?", "pt": "J\u00e1 espreitaste o telem\u00f3vel de algu\u00e9m por curiosidade? S\u00ea honesto.", "ro": "Ai verificat vreodat\u0103 telefonul cuiva din curiozitate? Fii sincer.", "fr": "As-tu d\u00e9j\u00e0 regard\u00e9 le t\u00e9l\u00e9phone de quelqu\u2019un par curiosit\u00e9 ? Sois honn\u00eate.", "it": "Hai mai guardato nel telefono di qualcuno per curiosit\u00e0? Sii onesto.", "fi": "Oletko koskaan katsellut jonkun puhelinta uteliaisuudesta? Ole rehellinen.", "nl": "Heb je ooit uit nieuwsgierigheid door iemands telefoon gekeken? Wees eerlijk.", "no": "Har du noen gang sett gjennom telefonen til noen av nysgjerrighet? V\u00e6r \u00e6rlig.", "sv": "Har du n\u00e5gonsin tittat igenom n\u00e5gons telefon av nyfikenhet? Var \u00e4rlig.", "pl": "Czy kiedykolwiek przeszuka\u0142e\u015b czyj\u015b telefon z ciekawo\u015bci? B\u0105d\u017a szczery."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever looked through someone’s phone out of curiosity? Be honest.';
UPDATE questions
SET translations = '{"en": "What was your first impression of me \u2014 be brutally honest.", "da": "Hvad var dit f\u00f8rste indtryk af mig \u2014 v\u00e6r brutalt \u00e6rlig.", "de": "Hvem af os er mest tilb\u00f8jelig til at starte noget og lade som om, det er uskyldigt?", "es": "Wer von uns f\u00e4ngt am ehesten etwas an und tut so, als w\u00e4re es unschuldig?", "pt": "Qual foi a tua primeira impress\u00e3o de mim \u2014 s\u00ea brutalmente honesto.", "ro": "Care a fost prima ta impresie despre mine \u2014 fii brutal de sincer.", "fr": "Quelle a \u00e9t\u00e9 ta premi\u00e8re impression de moi \u2014 sois brutalement honn\u00eate.", "it": "Qual \u00e8 stata la tua prima impressione di me \u2014 sii brutalmente onesto.", "fi": "Mik\u00e4 oli ensimm\u00e4inen vaikutelmasi minusta \u2014 ole t\u00e4ysin rehellinen.", "nl": "Wat was je eerste indruk van mij \u2014 wees eerlijk, ook al is het hard.", "no": "Hva var ditt f\u00f8rsteinntrykk av meg \u2014 v\u00e6r brutalt \u00e6rlig.", "sv": "Vad var ditt f\u00f6rsta intryck av mig \u2014 var brutalt \u00e4rlig.", "pl": "Jakie by\u0142o twoje pierwsze wra\u017cenie na m\u00f3j temat \u2014 b\u0105d\u017a brutalnie szczery."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What was your first impression of me — be brutally honest.';
UPDATE questions
SET translations = '{"en": "How do you feel about cancel culture or public shaming?", "da": "Hvordan har du det med cancel culture eller offentlig udskamning?", "de": "Hvem af os skjuler det v\u00e6rst, n\u00e5r vi er t\u00e6ndte?", "es": "Wer von uns kann seine Erregung am schlechtesten verbergen?", "pt": "O que pensas da \u201ccancel culture\u201d ou humilha\u00e7\u00e3o p\u00fablica?", "ro": "Ce p\u0103rere ai despre cultura anul\u0103rii sau ru\u0219inarea public\u0103?", "fr": "Que penses-tu de la \u201ccancel culture\u201d ou de la honte publique ?", "it": "Cosa ne pensi della cultura della cancellazione o della vergogna pubblica?", "fi": "Mit\u00e4 mielt\u00e4 olet peruutuskulttuurista tai julkisesta h\u00e4p\u00e4isyst\u00e4?", "nl": "Hoe voel je je over cancelcultuur of publieke beschaming?", "no": "Hva mener du om avbestillingskultur eller offentlig skam?", "sv": "Vad tycker du om avbokningskultur eller offentlig skam?", "pl": "Jak si\u0119 czujesz w kwestii kultury anulowania lub publicznego zawstydzania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about cancel culture or public shaming?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you like about my family, and one thing that\u2019s hard sometimes?", "da": "Hvad er \u00e9n ting, du kan lide ved min familie \u2014 og \u00e9n ting, der nogle gange er sv\u00e6r?", "de": "Hvem af os tror du mister fokus hurtigere, n\u00e5r flirten starter?", "es": "Wer von uns verliert schneller den Fokus, wenn das Flirten beginnt?", "pt": "O que gostas na minha fam\u00edlia \u2014 e o que \u00e0s vezes \u00e9 dif\u00edcil?", "ro": "Ce \u00ee\u021bi place la familia mea \u0219i ce e uneori dificil?", "fr": "Qu\u2019aimes-tu chez ma famille \u2014 et qu\u2019est-ce qui est parfois difficile ?", "it": "Qual \u00e8 una cosa che ti piace della mia famiglia e una cosa che a volte \u00e8 difficile?", "fi": "Mik\u00e4 on yksi asia, josta pid\u00e4t perheess\u00e4ni, ja yksi asia, joka on joskus vaikeaa?", "nl": "Wat is \u00e9\u00e9n ding dat je leuk vindt aan mijn familie, en \u00e9\u00e9n ding dat soms moeilijk is?", "no": "Hva er \u00e9n ting du liker med familien min, og \u00e9n ting som kan v\u00e6re vanskelig noen ganger?", "sv": "Vad \u00e4r en sak du gillar med min familj, och en sak som kan vara sv\u00e5r ibland?", "pl": "Co\u015b, co lubisz w mojej rodzinie, i co\u015b, co czasami bywa trudne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s one thing you like about my family, and one thing that’s hard sometimes?';
UPDATE questions
SET translations = '{"en": "Who from your past would make you a little nervous to bump into today \u2014 and why?", "da": "Hvem fra din fortid ville g\u00f8re dig lidt nerv\u00f8s, hvis du m\u00f8dte dem i dag \u2014 og hvorfor?", "de": "Hvem af os kan bedst lide at have kontrol?", "es": "Wer von uns mag es mehr, die Kontrolle zu haben?", "pt": "Quem do teu passado te deixaria nervoso se o encontrasses hoje \u2014 e porqu\u00ea?", "ro": "Cine din trecutul t\u0103u te-ar face pu\u021bin nervos dac\u0103 l-ai \u00eent\u00e2lni azi \u2014 \u0219i de ce?", "fr": "Qui de ton pass\u00e9 te rendrait un peu nerveux si tu le croisais aujourd\u2019hui \u2014 et pourquoi ?", "it": "Chi del tuo passato ti farebbe un po'' nervoso incontrare oggi \u2014 e perch\u00e9?", "fi": "Kuka menneisyydest\u00e4si saisi sinut tuntemaan itsesi hieman hermostuneeksi, jos kohtaisit h\u00e4net t\u00e4n\u00e4\u00e4n \u2014 ja miksi?", "nl": "Wie uit je verleden zou je een beetje nerveus maken om vandaag tegen te komen \u2014 en waarom?", "no": "Hvem fra fortiden din ville gjort deg litt nerv\u00f8s for \u00e5 m\u00f8te i dag \u2014 og hvorfor?", "sv": "Vem fr\u00e5n ditt f\u00f6rflutna skulle g\u00f6ra dig lite nerv\u00f6s att st\u00f6ta p\u00e5 idag \u2014 och varf\u00f6r?", "pl": "Kto z twojej przesz\u0142o\u015bci sprawi\u0142by, \u017ce poczu\u0142by\u015b si\u0119 troch\u0119 nerwowo, gdyby\u015b go dzisiaj spotka\u0142 \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Who from your past would make you a little nervous to bump into today — and why?';
UPDATE questions
SET translations = '{"en": "How do you feel about how we each handle money?", "da": "Hvordan har du det med, hvordan vi hver is\u00e6r h\u00e5ndterer penge?", "de": "Hvem af os er mere tilb\u00f8jelig til at snige en flirtende besked i l\u00f8bet af dagen?", "es": "Wer von uns schickt eher eine flirtende Nachricht w\u00e4hrend des Tages?", "pt": "Como te sentes em rela\u00e7\u00e3o \u00e0 forma como cada um de n\u00f3s lida com o dinheiro?", "ro": "Cum te sim\u021bi legat de felul \u00een care fiecare dintre noi gestioneaz\u0103 banii?", "fr": "Que ressens-tu \u00e0 propos de notre mani\u00e8re respective de g\u00e9rer l\u2019argent ?", "it": "Come ti senti riguardo al modo in cui ciascuno di noi gestisce il denaro?", "fi": "Mit\u00e4 mielt\u00e4 olet siit\u00e4, miten me kumpikin k\u00e4sittelemme rahaa?", "nl": "Hoe voel je je over hoe wij elk met geld omgaan?", "no": "Hvordan f\u00f8ler du om hvordan vi hver for oss h\u00e5ndterer penger?", "sv": "Hur k\u00e4nner du f\u00f6r hur vi var och en hanterar pengar?", "pl": "Jak si\u0119 czujesz w kwestii tego, jak ka\u017cdy z nas radzi sobie z pieni\u0119dzmi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about how we each handle money?';
UPDATE questions
SET translations = '{"en": "What topic do you think couples should talk about before committing long-term?", "da": "Hvilket emne synes du, par b\u00f8r tale om, f\u00f8r de forpligter sig langsigtet?", "de": "Hvem af os ville starte et \"fem minutter\"-\u00f8jeblik, der bliver til en time?", "es": "Wer von uns w\u00fcrde ein \u201ef\u00fcnf Minuten\u201c-Moment beginnen, das zu einer Stunde wird?", "pt": "Que assunto achas que os casais deviam falar antes de se comprometerem a longo prazo?", "ro": "Despre ce subiect crezi c\u0103 ar trebui s\u0103 discute cuplurile \u00eenainte de a se angaja pe termen lung?", "fr": "Quel sujet les couples devraient-ils aborder avant de s\u2019engager \u00e0 long terme ?", "it": "Quale argomento pensi che le coppie dovrebbero discutere prima di impegnarsi a lungo termine?", "fi": "Mit\u00e4 aiheita luulet parien pit\u00e4isi k\u00e4sitell\u00e4 ennen pitk\u00e4n aikav\u00e4lin sitoutumista?", "nl": "Over welk onderwerp denk je dat stellen moeten praten voordat ze zich op de lange termijn binden?", "no": "Hvilket tema mener du at par b\u00f8r snakke om f\u00f8r de forplikter seg p\u00e5 lang sikt?", "sv": "Vilket \u00e4mne tycker du att par b\u00f6r prata om innan de f\u00f6rbinder sig p\u00e5 l\u00e5ng sikt?", "pl": "O jakim temacie uwa\u017casz, \u017ce pary powinny porozmawia\u0107 przed podj\u0119ciem d\u0142ugoterminowego zobowi\u0105zania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What topic do you think couples should talk about before committing long-term?';
UPDATE questions
SET translations = '{"en": "Have you ever loved two people at the same time?", "da": "Har du nogensinde elsket to personer p\u00e5 samme tid?", "de": "Hvad er din yndlingsm\u00e5de for mig at vise, at jeg higer efter dig?", "es": "Wie magst du es am liebsten, wenn ich dir zeige, dass ich dich begehre?", "pt": "J\u00e1 amaste duas pessoas ao mesmo tempo?", "ro": "Ai iubit vreodat\u0103 dou\u0103 persoane \u00een acela\u0219i timp?", "fr": "As-tu d\u00e9j\u00e0 aim\u00e9 deux personnes en m\u00eame temps ?", "it": "Hai mai amato due persone contemporaneamente?", "fi": "Oletko koskaan rakastanut kahta ihmist\u00e4 samaan aikaan?", "nl": "Heb je ooit twee mensen tegelijk liefgehad?", "no": "Har du noen gang elsket to personer samtidig?", "sv": "Har du n\u00e5gonsin \u00e4lskat tv\u00e5 personer samtidigt?", "pl": "Czy kiedykolwiek kocha\u0142e\u015b dwie osoby jednocze\u015bnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Have you ever loved two people at the same time?';
UPDATE questions
SET translations = '{"en": "What do you think makes conversations about politics or religion go wrong?", "da": "Hvad tror du g\u00f8r samtaler om politik eller religion s\u00e5 sv\u00e6re?", "de": "Hvor vigtig er \u00f8jenkontakt for dig, n\u00e5r vi er t\u00e6tte?", "es": "Wie wichtig ist dir Augenkontakt, wenn wir uns nah sind?", "pt": "Porque achas que conversas sobre pol\u00edtica ou religi\u00e3o correm mal?", "ro": "De ce crezi c\u0103 discu\u021biile despre politic\u0103 sau religie merg prost?", "fr": "Pourquoi penses-tu que les conversations sur la politique ou la religion tournent mal ?", "it": "Cosa pensi faccia andare male le conversazioni su politica o religione?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 saa keskustelut politiikasta tai uskonnosta menem\u00e4\u00e4n pieleen?", "nl": "Wat denk je dat gesprekken over politiek of religie verkeerd laten lopen?", "no": "Hva tror du gj\u00f8r at samtaler om politikk eller religion g\u00e5r galt?", "sv": "Vad tycker du g\u00f6r att samtal om politik eller religion g\u00e5r fel?", "pl": "Co twoim zdaniem sprawia, \u017ce rozmowy na temat polityki lub religii id\u0105 \u017ale?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you think makes conversations about politics or religion go wrong?';