UPDATE questions
SET translations = '{"en": "Give a dramatic trailer voice-over for today\u2019s errands.", "da": "Giv en dramatisk trailer-voice-over for dagens \u00e6rinder.", "de": "Gib einen dramatischen Trailer-Voice-over f\u00fcr die heutigen Erledigungen.", "es": "Haz un voice-over dram\u00e1tico de tr\u00e1iler para las compras de hoy.", "pt": "Faz uma narra\u00e7\u00e3o estilo trailer dram\u00e1tica para as tarefas de hoje.", "ro": "D\u0103 o voce-over dramatic pentru trailer-ul de azi al cump\u0103r\u0103turilor \u015fi \u0103rilor.", "fr": "Fais une voix off dramatique fa\u00e7on bande-annonce pour les courses d\u2019aujourd\u2019hui.", "it": "Dai un''interpretazione drammatica per il voice-over delle commissioni di oggi.", "fi": "Esittele dramaattinen traileri\u00e4\u00e4ni t\u00e4n\u00e4\u00e4n teht\u00e4ville asioille.", "nl": "Geef een dramatische trailer stem-over voor de boodschappen van vandaag.", "no": "Gi en dramatisk trailer stemme-over for dagens \u00e6render.", "sv": "Ge en dramatisk trailer-r\u00f6st f\u00f6r dagens \u00e4renden.", "pl": "Przygotuj si\u0119 na emocjonuj\u0105c\u0105 podr\u00f3\u017c przez codzienne obowi\u0105zki! Dzi\u015b, w \u015bwiecie zakup\u00f3w i zada\u0144 do wykonania, stawisz czo\u0142a wyzwaniom, kt\u00f3re zmieni\u0105 twoje \u017cycie! Zmierz si\u0119 z nieprzewidywalnymi przeszkodami, odkrywaj tajemnice ukryte w alejkach supermarket\u00f3w i podejmuj decyzje, kt\u00f3re wp\u0142yn\u0105 na twoje jutro. Czy zd\u0105\u017cysz na czas? Czy pokonasz wszystkie przeszkody? To nie jest zwyk\u0142y dzie\u0144 \u2013 to misja, kt\u00f3ra zdefiniuje twoj\u0105 determinacj\u0119!"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Give a dramatic trailer voice-over for today’s errands.';
UPDATE questions
SET translations = '{"en": "Which inanimate object would be the worst roommate?", "da": "Hvilket livl\u00f8st objekt ville v\u00e6re den v\u00e6rste v\u00e6relseskammerat?", "de": "Welcher lebloser Gegenstand w\u00e4re der schlechteste Mitbewohner?", "es": "\u00bfQu\u00e9 objeto inanimado ser\u00eda el peor compa\u00f1ero de cuarto?", "pt": "Qual objeto inanimado seria o pior colega de quarto?", "ro": "Ce obiect ne\u00eensufle\u0163it ar fi cel mai r\u0103u coleg de camer\u0103?", "fr": "Quel objet inanim\u00e9 serait le pire colocataire ?", "it": "Quale oggetto inanimato sarebbe il peggior coinquilino?", "fi": "Mik\u00e4 eloton esine olisi huonoin k\u00e4mpp\u00e4kaveri?", "nl": "Welk levenloos object zou de slechtste huisgenoot zijn?", "no": "Hvilket livl\u00f8st objekt ville v\u00e6rt den d\u00e5rligste romkameraten?", "sv": "Vilken livl\u00f6s sak skulle vara den s\u00e4msta rumskamraten?", "pl": "Kt\u00f3ry martwy przedmiot by\u0142by najgorszym wsp\u00f3\u0142lokatorem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which inanimate object would be the worst roommate?';
UPDATE questions
SET translations = '{"en": "What\u2019s the tiny thing I do that makes you laugh every time\u2014even when you try not to?", "da": "Hvad er den lille ting, jeg g\u00f8r, som f\u00e5r dig til at grine hver gang \u2013 selv n\u00e5r du pr\u00f8ver ikke at?", "de": "Was ist die kleine Sache, die ich tue und die dich jedes Mal zum Lachen bringt \u2013 selbst wenn du es versuchst nicht zu?", "es": "\u00bfCu\u00e1l es la cosita que hago y que te hace re\u00edr cada vez \u2013 incluso cuando tratas de no hacerlo?", "pt": "Qual \u00e9 a pequena coisa que eu fa\u00e7o que te faz rir sempre, mesmo quando tentas n\u00e3o rir?", "ro": "Care e chestia mic\u0103 pe care o fac \u015fi care te face s\u0103 r\u00e2zi de fiecare dat\u0103 \u2013 chiar \u015fi c\u00e2nd \u00eencerci s\u0103 nu?", "fr": "Quelle est la petite chose que je fais qui te fait rire \u00e0 chaque fois \u2014 m\u00eame quand tu essaies de ne pas rire ?", "it": "Qual \u00e8 quella piccola cosa che faccio che ti fa ridere ogni volta, anche quando cerchi di non farlo?", "fi": "Mik\u00e4 on se pieni asia, jonka teen, joka saa sinut nauramaan joka kerta - jopa silloin, kun yrit\u00e4t olla nauramatta?", "nl": "Wat is het kleine ding dat ik doe waardoor je elke keer moet lachen, zelfs als je probeert het niet te doen?", "no": "Hva er den lille tingen jeg gj\u00f8r som f\u00e5r deg til \u00e5 le hver gang \u2013 selv n\u00e5r du pr\u00f8ver \u00e5 la v\u00e6re?", "sv": "Vad \u00e4r den lilla saken jag g\u00f6r som f\u00e5r dig att skratta varje g\u00e5ng \u2013 \u00e4ven n\u00e4r du f\u00f6rs\u00f6ker l\u00e5ta bli?", "pl": "Co to za ma\u0142a rzecz, kt\u00f3r\u0105 robi\u0119, \u017ce zawsze ci\u0119 roz\u015bmiesza, nawet gdy pr\u00f3bujesz si\u0119 powstrzyma\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What’s the tiny thing I do that makes you laugh every time—even when you try not to?';
UPDATE questions
SET translations = '{"en": "What conspiracy theory would you start, strictly for laughs?", "da": "Hvilken konspirationsteori ville du starte, udelukkende for grin?", "de": "Welche Verschw\u00f6rungstheorie w\u00fcrdest du starten, rein zum Spa\u00df?", "es": "\u00bfQu\u00e9 teor\u00eda conspirativa iniciar\u00edas, estrictamente para re\u00edr?", "pt": "Que teoria da conspira\u00e7\u00e3o come\u00e7arias, estritamente para rir?", "ro": "Ce teorie a conspira\u0163iei ai porni, strict pentru r\u00e2s?", "fr": "Quelle th\u00e9orie du complot lancerais-tu, strictement pour rire ?", "it": "Quale teoria del complotto avresti voglia di inventare, solo per ridere?", "fi": "Mink\u00e4 salaliittoteorian aloittaisit, pelk\u00e4st\u00e4\u00e4n huumorin vuoksi?", "nl": "Welke samenzweringstheorie zou je beginnen, puur voor de lol?", "no": "Hvilken konspirasjonsteori ville du startet, kun for moro skyld?", "sv": "Vilken konspirationsteori skulle du starta, enbart f\u00f6r skratt?", "pl": "Jak\u0105 teori\u0119 spiskow\u0105 by\u015b wymy\u015bli\u0142, czysto dla zabawy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What conspiracy theory would you start, strictly for laughs?';
UPDATE questions
SET translations = '{"en": "What do I do in photos every single time, even by accident?", "da": "Hvad g\u00f8r jeg p\u00e5 fotos hver gang, selv ved et uheld?", "de": "Was tue ich auf Fotos jedes Mal, selbst aus Versehen?", "es": "\u00bfQu\u00e9 hago en fotos cada vez, incluso por accidente?", "pt": "O que fa\u00e7o em fotos todas as vezes, mesmo sem querer?", "ro": "Ce fac eu \u00een poze de fiecare dat\u0103, chiar \u015fi din gre\u015feal\u0103?", "fr": "Que fais-je sur les photos \u00e0 chaque fois, m\u00eame par accident ?", "it": "Cosa faccio in foto ogni singola volta, anche per sbaglio?", "fi": "Mit\u00e4 teen valokuvissa joka kerta, jopa vahingossa?", "nl": "Wat doe ik elke keer weer op foto''s, zelfs per ongeluk?", "no": "Hva gj\u00f8r jeg p\u00e5 bilder hver eneste gang, selv ved et uhell?", "sv": "Vad g\u00f6r jag p\u00e5 bilder varje g\u00e5ng, \u00e4ven av misstag?", "pl": "Co robi\u0119 na zdj\u0119ciach za ka\u017cdym razem, nawet przypadkiem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What do I do in photos every single time, even by accident?';
UPDATE questions
SET translations = '{"en": "You get three mundane wishes. What would those wishes be?", "da": "Du f\u00e5r tre dagligdags \u00f8nsker. Hvad ville de v\u00e6re?", "de": "Du bekommst drei allt\u00e4gliche W\u00fcnsche. Was w\u00e4ren diese W\u00fcnsche?", "es": "Te conceden tres deseos mundanos. \u00bfCu\u00e1les ser\u00edan?", "pt": "Tens tr\u00eas desejos mundanos. Quais seriam?", "ro": "Prime\u015fti trei dorin\u0163e banale. Care ar fi ele?", "fr": "Tu obtiens trois souhaits banals. Quels seraient-ils ?", "it": "Hai tre desideri banali. Quali sarebbero?", "fi": "Saat kolme arkista toivetta. Mitk\u00e4 ne olisivat?", "nl": "Je krijgt drie alledaagse wensen. Wat zouden die wensen zijn?", "no": "Du f\u00e5r tre hverdagslige \u00f8nsker. Hva ville de \u00f8nskene v\u00e6rt?", "sv": "Du f\u00e5r tre vardagliga \u00f6nskningar. Vad skulle de \u00f6nskningarna vara?", "pl": "Dostajesz trzy zwyczajne \u017cyczenia. Jakie to b\u0119d\u0105 \u017cyczenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'You get three mundane wishes. What would those wishes be?';
UPDATE questions
SET translations = '{"en": "Pitch a children\u2019s book based on our inside joke.", "da": "Pr\u00e6senter en b\u00f8rnebog baseret p\u00e5 vores interne joke.", "de": "Verfasse ein Kinderbuch basierend auf unserem Insider-Witz.", "es": "Prop\u00f3n un libro para ni\u00f1os basado en nuestra broma interna.", "pt": "Apresenta um livro infantil baseado na nossa piada privada.", "ro": "Propune-o pe o carte de copii bazat\u0103 pe gluma noastr\u0103 intern\u0103.", "fr": "Propose un livre pour enfants bas\u00e9 sur notre blague int\u00e9rieure.", "it": "Proponi un libro per bambini basato sulla nostra battuta interna.", "fi": "Esittele lastenkirja, joka perustuu meid\u00e4n sis\u00e4iseen vitsiin.", "nl": "Pitch een kinderboek gebaseerd op onze inside joke.", "no": "Lag en barnebok basert p\u00e5 v\u00e5r interne vits.", "sv": "Pitcha en barnbok baserad p\u00e5 v\u00e5rt interna sk\u00e4mt.", "pl": "Zaproponuj ksi\u0105\u017ck\u0119 dla dzieci opart\u0105 na naszym wewn\u0119trznym \u017carcie."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Pitch a children’s book based on our inside joke.';
UPDATE questions
SET translations = '{"en": "Supermarket edition: what\u2019s your classic \u201cI definitely didn\u2019t need this\u201d purchase?", "da": "Supermarked-udgave: Hvad er dit klassiske \u201cdet her havde jeg da ikke brug for\u201d-k\u00f8b?", "de": "Supermarkt-Edition: Was ist dein klassischer \u201eDas brauchte ich eigentlich gar nicht\u201c-Kauf?", "es": "Edici\u00f3n supermercado: \u00bfcu\u00e1l es tu compra cl\u00e1sica de \u201crealmente no necesitaba esto\u201d?", "pt": "Edi\u00e7\u00e3o supermercado: qual \u00e9 a sua compra cl\u00e1ssica de \u201ceu com certeza n\u00e3o precisava disso\u201d?", "ro": "Edi\u021bia supermarket: care este cump\u0103r\u0103tura ta clasic\u0103 de \u201easta chiar nu-mi trebuia\u201d?", "fr": "Version supermarch\u00e9 : quel est ton achat classique \u00ab je n\u2019en avais vraiment pas besoin \u00bb ?", "it": "Edizione supermercato: qual \u00e8 il tuo acquisto classico \"non ne avevo sicuramente bisogno\"?", "fi": "Supermarket-versio: mik\u00e4 on klassinen \"en todellakaan tarvinnut t\u00e4t\u00e4\" ostoksesi?", "nl": "Supermarkt editie: wat is jouw klassieke \"dit had ik absoluut niet nodig\" aankoop?", "no": "Supermarkedutgave: hva er ditt klassiske \"jeg trengte absolutt ikke dette\"-kj\u00f8p?", "sv": "Supermarknadsutg\u00e5van: vad \u00e4r ditt klassiska \"det h\u00e4r beh\u00f6vde jag definitivt inte\" k\u00f6p?", "pl": "Edycja supermarketowa: jaki jest tw\u00f3j klasyczny zakup \u201ena pewno tego nie potrzebowa\u0142em\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Supermarket edition: what’s your classic “I definitely didn’t need this” purchase?';
UPDATE questions
SET translations = '{"en": "Kitchen edition: what snack do you always buy \u201cfor guests\u201d but end up eating yourself?", "da": "K\u00f8kken-udgave: Hvilken snack k\u00f8ber du altid \u201ctil g\u00e6ster\u201d, men ender med selv at spise?", "de": "K\u00fcchen-Edition: Welchen Snack kaufst du immer \u201ef\u00fcr G\u00e4ste\u201c, isst ihn aber am Ende selbst?", "es": "Versi\u00f3n cocina: \u00bfqu\u00e9 snack compras siempre \u201cpara las visitas\u201d, pero acabas comi\u00e9ndotelo t\u00fa?", "pt": "Edi\u00e7\u00e3o cozinha: qual petisco voc\u00ea sempre compra \u201cpara as visitas\u201d, mas acaba comendo voc\u00ea mesmo(a)?", "ro": "Edi\u021bia buc\u0103t\u0103rie: ce gustare cumperi mereu \u201epentru musafiri\u201d, dar ajungi s\u0103 o m\u0103n\u00e2nci tu?", "fr": "\u00c9dition cuisine : quel snack ach\u00e8tes-tu toujours \u00ab pour les invit\u00e9s \u00bb mais que tu finis par manger toi-m\u00eame ?", "it": "Edizione cucina: quale snack compri sempre \"per gli ospiti\" ma finisci per mangiare tu stesso?", "fi": "Keitti\u00f6versio: mik\u00e4 v\u00e4lipala on sellainen, jonka ostat aina \"vieraille\", mutta sy\u00f6t lopulta itse?", "nl": "Keuken editie: welke snack koop je altijd \u201cvoor gasten\u201d maar eet je uiteindelijk zelf op?", "no": "Kj\u00f8kkenutgave: hvilken snack kj\u00f8per du alltid \"til gjestene\", men ender opp med \u00e5 spise selv?", "sv": "K\u00f6ksutg\u00e5van: vilken snacks k\u00f6per du alltid \"till g\u00e4ster\" men slutar med att \u00e4ta sj\u00e4lv?", "pl": "W wersji kuchennej: jaki przek\u0105sk\u0119 zawsze kupujesz \"dla go\u015bci\", ale ko\u0144czysz jedz\u0105c sam?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Kitchen edition: what snack do you always buy “for guests” but end up eating yourself?';
UPDATE questions
SET translations = '{"en": "Which of us would be the worst undercover spy \u2013 and why?", "da": "Hvem af os ville v\u00e6re den v\u00e6rste undercover-spion \u2013 og hvorfor?", "de": "Wer von uns w\u00e4re der schlechteste Undercover-Spion \u2013 und warum?", "es": "\u00bfCu\u00e1l de nosotros ser\u00eda el peor esp\u00eda encubierto \u2013 y por qu\u00e9?", "pt": "Qual de n\u00f3s seria o pior espi\u00e3o disfar\u00e7ado \u2013 e por qu\u00ea?", "ro": "Care dintre noi ar fi cel mai r\u0103u spion sub acoperire \u2013 \u015fi de ce?", "fr": "Lequel d\u2019entre nous serait le pire espion infiltr\u00e9 \u2013 et pourquoi ?", "it": "Quale di noi sarebbe il peggior spia sotto copertura \u2013 e perch\u00e9?", "fi": "Kumpi meist\u00e4 olisi huonoin salainen agentti \u2013 ja miksi?", "nl": "Wie van ons zou de slechtste undercover spion zijn \u2013 en waarom?", "no": "Hvem av oss ville v\u00e6rt den d\u00e5rligste undercover-spionen \u2013 og hvorfor?", "sv": "Vilken av oss skulle vara den s\u00e4msta undercover-spionen \u2013 och varf\u00f6r?", "pl": "Kto z nas by\u0142by najgorszym tajnym agentem \u2013 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which of us would be the worst undercover spy – and why?';