UPDATE questions
SET translations = '{"en": "What\u2019s our biggest inside joke that no one else would understand?", "da": "Hvad er vores st\u00f8rste interne joke, som ingen andre ville forst\u00e5?", "de": "Was ist unser gr\u00f6\u00dfter Insiderwitz, den sonst niemand verstehen w\u00fcrde?", "es": "\u00bfCu\u00e1l es nuestra broma interna m\u00e1s grande que nadie m\u00e1s entender\u00eda?", "pt": "Qual \u00e9 a nossa piada interna que ningu\u00e9m mais entenderia?", "ro": "Care este gluma noastr\u0103 intern\u0103 pe care nimeni altcineva n-ar \u00een\u021belege-o?", "fr": "Quelle est notre blague interne que personne d\u2019autre ne comprendrait ?", "it": "Qual \u00e8 la nostra pi\u00f9 grande battuta interna che nessun altro capirebbe?", "fi": "Mik\u00e4 on meid\u00e4n suurin sis\u00e4inen vitsimme, jota kukaan muu ei ymm\u00e4rt\u00e4isi?", "nl": "Wat is onze grootste inside joke die niemand anders zou begrijpen?", "no": "Hva er v\u00e5r st\u00f8rste interne vits som ingen andre ville forst\u00e5?", "sv": "Vad \u00e4r v\u00e5rt st\u00f6rsta interna sk\u00e4mt som ingen annan skulle f\u00f6rst\u00e5?", "pl": "Jaki jest nasz najwi\u0119kszy wewn\u0119trzny \u017cart, kt\u00f3rego nikt inny by nie zrozumia\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s our biggest inside joke that no one else would understand?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to win a family game night?", "da": "Hvem vinder oftest familiens spilaften?", "de": "Wer gewinnt am h\u00e4ufigsten den Familien-Spieleabend?", "es": "\u00bfQui\u00e9n suele ganar las noches de juegos familiares?", "pt": "Quem costuma ganhar nas noites de jogos em fam\u00edlia?", "ro": "Cine c\u00e2\u0219tig\u0103 cel mai des seara de jocuri \u00een familie?", "fr": "Qui gagne le plus souvent lors des soir\u00e9es jeux de famille ?", "it": "Chi \u00e8 pi\u00f9 probabile che vinca una serata di giochi in famiglia?", "fi": "Kuka todenn\u00e4k\u00f6isesti voittaa perhepeliy\u00f6n?", "nl": "Wie is het meest waarschijnlijk om een familie spelletjesavond te winnen?", "no": "Hvem er mest sannsynlig \u00e5 vinne en familiekveld med spill?", "sv": "Vem \u00e4r mest sannolikt att vinna en familjespelkv\u00e4ll?", "pl": "Kto ma najwi\u0119ksze szanse na wygran\u0105 podczas rodzinnej gry?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to win a family game night?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to accuse everyone else of cheating?", "da": "Hvem beskylder oftest alle andre for at snyde?", "de": "Wer beschuldigt am ehesten alle anderen des Schummelns?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que acuse a los dem\u00e1s de hacer trampa?", "pt": "Quem \u00e9 mais prov\u00e1vel de acusar os outros de trapacear?", "ro": "Cine e cel mai probabil s\u0103-i acuze pe to\u021bi ceilal\u021bi c\u0103 tri\u0219eaz\u0103?", "fr": "Qui est le plus susceptible d\u2019accuser tout le monde de tricher ?", "it": "Chi \u00e8 pi\u00f9 probabile che accusi gli altri di barare?", "fi": "Kuka on todenn\u00e4k\u00f6isimmin syytt\u00e4m\u00e4ss\u00e4 kaikkia muita huijaamisesta?", "nl": "Wie is het meest waarschijnlijk om iedereen ervan te beschuldigen te vals te spelen?", "no": "Hvem er mest sannsynlig til \u00e5 anklage alle andre for \u00e5 jukse?", "sv": "Vem \u00e4r mest ben\u00e4gen att anklaga alla andra f\u00f6r fusk?", "pl": "Kto najprawdopodobniej oskar\u017cy wszystkich innych o oszustwo?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to accuse everyone else of cheating?';
UPDATE questions
SET translations = '{"en": "Who\u2019s best at making up songs or silly jingles?", "da": "Hvem er bedst til at finde p\u00e5 sange eller fjollede rim?", "de": "Wer ist am besten darin, Lieder oder alberne Reime zu erfinden?", "es": "\u00bfQui\u00e9n es el mejor inventando canciones o tonter\u00edas?", "pt": "Quem \u00e9 o melhor a inventar can\u00e7\u00f5es ou rimas engra\u00e7adas?", "ro": "Cine e cel mai bun la inventat c\u00e2ntece sau rime haioase?", "fr": "Qui est le meilleur pour inventer des chansons ou des jingles amusants ?", "it": "Chi \u00e8 il migliore a inventare canzoni o jingle divertenti?", "fi": "Kuka on paras keksim\u00e4\u00e4n lauluja tai hassuja jingleseit\u00e4?", "nl": "Wie is het beste in het maken van liedjes of grappige jingles?", "no": "Hvem er best til \u00e5 lage sanger eller morsomme jingler?", "sv": "Vem \u00e4r b\u00e4st p\u00e5 att hitta p\u00e5 s\u00e5nger eller roliga jinglar?", "pl": "Kto jest najlepszy w wymy\u015blaniu piosenek lub zabawnych d\u017cingli?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s best at making up songs or silly jingles?';
UPDATE questions
SET translations = '{"en": "Who got in the most trouble as a kid?", "da": "Hvem kom mest i problemer som barn?", "de": "Wer hatte als Kind am meisten \u00c4rger?", "es": "\u00bfQui\u00e9n se met\u00eda m\u00e1s en problemas de ni\u00f1o?", "pt": "Quem mais se metia em encrenca quando era crian\u00e7a?", "ro": "Cine se b\u0103ga cel mai des \u00een belele c\u00e2nd era copil?", "fr": "Qui avait le plus d\u2019ennuis quand il \u00e9tait enfant ?", "it": "Chi ha combinato pi\u00f9 guai da bambino?", "fi": "Kuka sai lapsena eniten ongelmia?", "nl": "Wie kreeg er als kind de meeste problemen?", "no": "Hvem kom i mest tr\u00f8bbel som barn?", "sv": "Vem hamnade i mest trubbel som barn?", "pl": "Kto mia\u0142 najwi\u0119cej k\u0142opot\u00f3w jako dziecko?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who got in the most trouble as a kid?';
UPDATE questions
SET translations = '{"en": "Who has the funniest school stories?", "da": "Hvem har de sjoveste skolehistorier?", "de": "Wer hat die lustigsten Schulgeschichten?", "es": "\u00bfQui\u00e9n tiene las historias escolares m\u00e1s graciosas?", "pt": "Quem tem as hist\u00f3rias escolares mais engra\u00e7adas?", "ro": "Cine are cele mai amuzante pove\u0219ti din \u0219coal\u0103?", "fr": "Qui a les histoires d\u2019\u00e9cole les plus dr\u00f4les ?", "it": "Chi ha le storie scolastiche pi\u00f9 divertenti?", "fi": "Kell\u00e4 on hauskimmat koulutarinat?", "nl": "Wie heeft de grappigste schoolverhalen?", "no": "Hvem har de morsomste skolehistoriene?", "sv": "Vem har de roligaste skolhistorierna?", "pl": "Kto ma naj\u015bmieszniejsze historie ze szko\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who has the funniest school stories?';
UPDATE questions
SET translations = '{"en": "Who always took forever to finish homework?", "da": "Hvem brugte evigheder p\u00e5 at lave lektier?", "de": "Wer brauchte ewig, um Hausaufgaben zu machen?", "es": "\u00bfQui\u00e9n tardaba una eternidad en hacer la tarea?", "pt": "Quem demorava uma eternidade para fazer o dever de casa?", "ro": "Cine terminaa cel mai greu temele?", "fr": "Qui mettait toujours une \u00e9ternit\u00e9 \u00e0 faire ses devoirs ?", "it": "Chi impiegava sempre un''eternit\u00e0 per finire i compiti?", "fi": "Kuka aina k\u00e4ytti ikuisuuden kotiteht\u00e4vien tekemiseen?", "nl": "Wie deed er altijd eeuwig over het maken van huiswerk?", "no": "Hvem brukte alltid evigheter p\u00e5 \u00e5 bli ferdig med leksene?", "sv": "Vem tog alltid en evighet p\u00e5 sig att bli klar med l\u00e4xorna?", "pl": "Kto zawsze potrzebowa\u0142 wieczno\u015bci, \u017ceby sko\u0144czy\u0107 prac\u0119 domow\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who always took forever to finish homework?';
UPDATE questions
SET translations = '{"en": "What\u2019s something Mom or Dad always said that still makes us laugh?", "da": "Hvad er noget, mor eller far altid sagde, som stadig f\u00e5r os til at grine?", "de": "Was haben Mama oder Papa immer gesagt, wor\u00fcber wir noch heute lachen?", "es": "\u00bfQu\u00e9 es algo que mam\u00e1 o pap\u00e1 siempre dec\u00edan y que a\u00fan nos hace re\u00edr?", "pt": "O que mam\u00e3e ou papai sempre diziam e ainda nos faz rir?", "ro": "Ce spuneau mama sau tata mereu \u0219i ne face \u00eenc\u0103 s\u0103 r\u00e2dem?", "fr": "Qu\u2019est-ce que maman ou papa disaient toujours et qui nous fait encore rire ?", "it": "Qualcosa che mamma o pap\u00e0 dicevano sempre e che ci fa ancora ridere?", "fi": "Mik\u00e4 on jotain, mit\u00e4 \u00e4iti tai is\u00e4 aina sanoi, mik\u00e4 saa meid\u00e4t yh\u00e4 nauramaan?", "nl": "Wat is iets dat Mam of Pap altijd zei dat ons nog steeds aan het lachen maakt?", "no": "Hva er noe mamma eller pappa alltid sa som fortsatt f\u00e5r oss til \u00e5 le?", "sv": "Vad \u00e4r n\u00e5got som mamma eller pappa alltid sa som fortfarande f\u00e5r oss att skratta?", "pl": "Co\u015b, co Mama lub Tata zawsze m\u00f3wili, co wci\u0105\u017c nas roz\u015bmiesza?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s something Mom or Dad always said that still makes us laugh?';
UPDATE questions
SET translations = '{"en": "What\u2019s a TV show or song that reminds us of growing up?", "da": "Hvilket tv-show eller sang minder os om vores barndom?", "de": "Welche TV-Show oder welches Lied erinnert uns an unsere Kindheit?", "es": "\u00bfQu\u00e9 programa o canci\u00f3n nos recuerda a nuestra infancia?", "pt": "Que programa de TV ou m\u00fasica nos lembra da nossa inf\u00e2ncia?", "ro": "Ce emisiune sau c\u00e2ntec ne aminte\u0219te de copil\u0103rie?", "fr": "Quelle \u00e9mission ou chanson nous rappelle notre enfance ?", "it": "Qual \u00e8 un programma TV o una canzone che ci ricorda di crescere?", "fi": "Mik\u00e4 on televisio-ohjelma tai laulu, joka muistuttaa meit\u00e4 lapsuudesta?", "nl": "Wat is een tv-show of lied dat ons herinnert aan opgroeien?", "no": "Hva er et TV-program eller en sang som minner oss om \u00e5 vokse opp?", "sv": "Vilken TV-show eller l\u00e5t p\u00e5minner oss om att v\u00e4xa upp?", "pl": "Jaki program telewizyjny lub piosenka przypomina nam o dorastaniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s a TV show or song that reminds us of growing up?';
UPDATE questions
SET translations = '{"en": "What\u2019s a memory that instantly makes everyone laugh?", "da": "Hvilken erindring f\u00e5r straks alle til at grine?", "de": "Welche Erinnerung bringt sofort alle zum Lachen?", "es": "\u00bfQu\u00e9 recuerdo hace que todos se r\u00edan al instante?", "pt": "Que lembran\u00e7a faz todos rirem instantaneamente?", "ro": "Ce amintire \u00eei face pe to\u021bi s\u0103 r\u00e2d\u0103 instantaneu?", "fr": "Quel souvenir fait rire tout le monde instantan\u00e9ment ?", "it": "Qual \u00e8 un ricordo che fa ridere tutti all''istante?", "fi": "Mik\u00e4 on muisto, joka saa kaikki nauramaan heti?", "nl": "Wat is een herinnering die iedereen meteen aan het lachen maakt?", "no": "Hva er et minne som umiddelbart f\u00e5r alle til \u00e5 le?", "sv": "Vilket minne f\u00e5r alltid alla att skratta?", "pl": "Jakie wspomnienie od razu sprawia, \u017ce wszyscy si\u0119 \u015bmiej\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s a memory that instantly makes everyone laugh?';