UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to start a dance party in the kitchen?", "da": "Hvem starter sandsynligvis en dansefest i k\u00f8kkenet?", "de": "Wer startet am ehesten eine Tanzparty in der K\u00fcche?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que empiece una fiesta de baile en la cocina?", "pt": "Quem \u00e9 mais prov\u00e1vel de come\u00e7ar uma festa de dan\u00e7a na cozinha?", "ro": "Cine e cel mai probabil s\u0103 \u00eenceap\u0103 o petrecere dansant\u0103 \u00een buc\u0103t\u0103rie?", "fr": "Qui est le plus susceptible de lancer une f\u00eate dansante dans la cuisine ?", "it": "Chi \u00e8 pi\u00f9 probabile che inizi una festa da ballo in cucina?", "fi": "Kuka todenn\u00e4k\u00f6isesti aloittaa tanssijuhlat keitti\u00f6ss\u00e4?", "nl": "Wie is het meest waarschijnlijk om een dansfeestje in de keuken te beginnen?", "no": "Hvem er mest sannsynlig til \u00e5 starte en dansefest p\u00e5 kj\u00f8kkenet?", "sv": "Vem \u00e4r mest sannolikt att starta en dansfest i k\u00f6ket?", "pl": "Kto najprawdopodobniej zacznie imprez\u0119 taneczn\u0105 w kuchni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to start a dance party in the kitchen?';
UPDATE questions
SET translations = '{"en": "What\u2019s our most unforgettable vacation moment?", "da": "Hvad er vores mest uforglemmelige ferieminde?", "de": "Was ist unser unvergesslichster Urlaubsmoment?", "es": "\u00bfCu\u00e1l es nuestro momento de vacaciones m\u00e1s inolvidable?", "pt": "Qual \u00e9 o nosso momento de f\u00e9rias mais inesquec\u00edvel?", "ro": "Care este cel mai de neuitat moment al vacan\u021bei noastre?", "fr": "Quel est notre souvenir de vacances le plus inoubliable ?", "it": "Qual \u00e8 il nostro momento di vacanza pi\u00f9 indimenticabile?", "fi": "Mik\u00e4 on meid\u00e4n unohtumattomin lomamuistomme?", "nl": "Wat is ons meest onvergetelijke vakantie-moment?", "no": "Hva er v\u00e5rt mest uforglemmelige ferieminne?", "sv": "Vilket \u00e4r v\u00e5rt mest of\u00f6rgl\u00f6mliga semester\u00f6gonblick?", "pl": "Jaki jest nasz najbardziej niezapomniany moment z wakacji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s our most unforgettable vacation moment?';
UPDATE questions
SET translations = '{"en": "Who always ends up getting lost on road trips?", "da": "Hvem farer altid vild p\u00e5 roadtrips?", "de": "Wer verirrt sich immer auf Roadtrips?", "es": "\u00bfQui\u00e9n siempre se pierde en los viajes por carretera?", "pt": "Quem sempre se perde nas viagens de carro?", "ro": "Cine se pierde mereu \u00een excursiile cu ma\u0219ina?", "fr": "Qui se perd toujours pendant les road trips ?", "it": "Chi si perde sempre durante i viaggi in auto?", "fi": "Kuka aina p\u00e4\u00e4tyy eksym\u00e4\u00e4n automatkoilla?", "nl": "Wie raakt er altijd verdwaald tijdens roadtrips?", "no": "Hvem ender alltid opp med \u00e5 g\u00e5 seg bort p\u00e5 bilturer?", "sv": "Vem brukar alltid g\u00e5 vilse p\u00e5 roadtrips?", "pl": "Kto zawsze gubi si\u0119 podczas podr\u00f3\u017cy samochodowych?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who always ends up getting lost on road trips?';
UPDATE questions
SET translations = '{"en": "Who\u2019s the biggest over-packer in the family?", "da": "Hvem er den st\u00f8rste over-packer i familien?", "de": "Wer ist der gr\u00f6\u00dfte \u00dcberpacker in der Familie?", "es": "\u00bfQui\u00e9n es el que m\u00e1s empaca de m\u00e1s en la familia?", "pt": "Quem \u00e9 o maior exagerado a fazer as malas na fam\u00edlia?", "ro": "Cine \u00eempacheteaz\u0103 mereu prea multe lucruri \u00een familie?", "fr": "Qui est celui qui fait toujours trop de bagages dans la famille ?", "it": "Chi \u00e8 il pi\u00f9 grande esagerato nel fare le valigie della famiglia?", "fi": "Kuka on perheen suurin ylipakkaaja?", "nl": "Wie is de grootste overpakker in de familie?", "no": "Hvem er den st\u00f8rste overpakker i familien?", "sv": "Vem \u00e4r den st\u00f6rsta \u00f6verpackaren i familjen?", "pl": "Kto jest najwi\u0119kszym pakowaczem w rodzinie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s the biggest over-packer in the family?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell that instantly reminds us of home?", "da": "Hvilken duft minder os straks om hjemmet?", "de": "Welcher Geruch erinnert uns sofort an Zuhause?", "es": "\u00bfQu\u00e9 olor nos recuerda instant\u00e1neamente a casa?", "pt": "Qual cheiro nos lembra instantaneamente de casa?", "ro": "Ce miros ne aminte\u0219te instant de acas\u0103?", "fr": "Quelle odeur nous rappelle imm\u00e9diatement la maison ?", "it": "Qual \u00e8 un odore che ci ricorda immediatamente casa?", "fi": "Mik\u00e4 tuoksu tuo heti mieleen kodin?", "nl": "Wat is een geur die ons meteen aan thuis herinnert?", "no": "Hva er en lukt som umiddelbart minner oss om hjemmet?", "sv": "Vilken doft p\u00e5minner oss om hemmet direkt?", "pl": "Jaki zapach od razu przypomina nam o domu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s a smell that instantly reminds us of home?';
UPDATE questions
SET translations = '{"en": "Who\u2019s usually in charge of music on long drives?", "da": "Hvem st\u00e5r normalt for musikken p\u00e5 lange k\u00f8reture?", "de": "Wer ist normalerweise f\u00fcr die Musik bei langen Autofahrten zust\u00e4ndig?", "es": "\u00bfQui\u00e9n suele estar a cargo de la m\u00fasica en los viajes largos?", "pt": "Quem normalmente cuida da m\u00fasica nas viagens longas?", "ro": "Cine este de obicei responsabil cu muzica \u00een drumurile lungi?", "fr": "Qui est g\u00e9n\u00e9ralement responsable de la musique lors des longs trajets ?", "it": "Chi di solito si occupa della musica durante i lunghi viaggi?", "fi": "Kuka yleens\u00e4 vastaa musiikista pitkill\u00e4 matkoilla?", "nl": "Wie is meestal verantwoordelijk voor de muziek tijdens lange ritten?", "no": "Hvem pleier vanligvis \u00e5 ha ansvaret for musikken p\u00e5 lange bilturer?", "sv": "Vem brukar vanligtvis ha ansvaret f\u00f6r musiken p\u00e5 l\u00e5ngresor?", "pl": "Kto zazwyczaj odpowiada za muzyk\u0119 podczas d\u0142ugich podr\u00f3\u017cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s usually in charge of music on long drives?';
UPDATE questions
SET translations = '{"en": "Who insists on having a real Christmas tree, no matter the mess?", "da": "Hvem insisterer p\u00e5 at have et \u00e6gte juletr\u00e6, uanset rodet?", "de": "Wer besteht auf einem echten Weihnachtsbaum, egal wie chaotisch?", "es": "\u00bfQui\u00e9n insiste en tener un \u00e1rbol de Navidad real, sin importar el desorden?", "pt": "Quem insiste em ter uma \u00e1rvore de Natal de verdade, n\u00e3o importa a bagun\u00e7a?", "ro": "Cine insist\u0103 s\u0103 aib\u0103 un brad adev\u0103rat, indiferent de mizerie?", "fr": "Qui insiste pour avoir un vrai sapin de No\u00ebl, peu importe le bazar ?", "it": "Chi insiste per avere un vero albero di Natale, nonostante il disordine?", "fi": "Kuka vaatii oikeaa joulupuuta, huolimatta sotkusta?", "nl": "Wie staat erop een echte kerstboom te hebben, ongeacht de rommel?", "no": "Hvem insisterer p\u00e5 \u00e5 ha et ekte juletre, uansett rotet?", "sv": "Vem insisterar p\u00e5 att ha en riktig julgran, oavsett r\u00f6ran?", "pl": "Kto upiera si\u0119 przy prawdziwej choince, niezale\u017cnie od ba\u0142aganu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who insists on having a real Christmas tree, no matter the mess?';
UPDATE questions
SET translations = '{"en": "How did mom and dad meet - What\u2019s the story?", "da": "Hvordan m\u00f8dtes mor og far \u2013 hvad er historien?", "de": "Wie haben sich Mama und Papa kennengelernt \u2013 was ist die Geschichte?", "es": "\u00bfC\u00f3mo se conocieron mam\u00e1 y pap\u00e1? \u00bfCu\u00e1l es la historia?", "pt": "Como mam\u00e3e e papai se conheceram \u2013 qual \u00e9 a hist\u00f3ria?", "ro": "Cum s-au cunoscut mama \u0219i tata \u2013 care e povestea?", "fr": "Comment maman et papa se sont-ils rencontr\u00e9s \u2013 quelle est l\u2019histoire ?", "it": "Come si sono conosciuti mamma e pap\u00e0 - Qual \u00e8 la storia?", "fi": "Miten \u00e4iti ja is\u00e4 tapasivat - Mik\u00e4 on tarina?", "nl": "Hoe hebben mama en papa elkaar ontmoet - Wat is het verhaal?", "no": "Hvordan m\u00f8ttes mamma og pappa - Hva er historien?", "sv": "Hur tr\u00e4ffades mamma och pappa - Vad \u00e4r historien?", "pl": "Jak mama i tata si\u0119 poznali - Jaka jest historia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'How did mom and dad meet - What’s the story?';
UPDATE questions
SET translations = '{"en": "Who always falls asleep halfway through family movie night?", "da": "Hvem falder altid i s\u00f8vn halvvejs gennem familiefilmaften?", "de": "Wer schl\u00e4ft immer mitten im Familienfilmabend ein?", "es": "\u00bfQui\u00e9n siempre se queda dormido a mitad de la noche de pel\u00edculas familiares?", "pt": "Quem sempre adormece no meio da noite de filme em fam\u00edlia?", "ro": "Cine adoarme mereu la jum\u0103tatea serii de film \u00een familie?", "fr": "Qui s\u2019endort toujours \u00e0 mi-chemin de la soir\u00e9e cin\u00e9ma en famille ?", "it": "Chi si addormenta sempre a met\u00e0 della serata cinema in famiglia?", "fi": "Kuka aina nukahtaa puoliv\u00e4liss\u00e4 perheen elokuvailtaa?", "nl": "Wie valt er altijd halverwege de familiefilmavond in slaap?", "no": "Hvem sovner alltid halvveis gjennom familiefilmen?", "sv": "Vem somnar alltid halvv\u00e4gs genom familjefilmkv\u00e4llen?", "pl": "Kto zawsze zasypia w po\u0142owie rodzinnego wieczoru filmowego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who always falls asleep halfway through family movie night?';
UPDATE questions
SET translations = '{"en": "What\u2019s the funniest pet story we\u2019ve ever told?", "da": "Hvad er den sjoveste k\u00e6ledyrshistorie, vi nogensinde har fortalt?", "de": "Was ist die lustigste Haustiergeschichte, die wir je erz\u00e4hlt haben?", "es": "\u00bfCu\u00e1l es la historia de mascota m\u00e1s divertida que hemos contado?", "pt": "Qual \u00e9 a hist\u00f3ria de animal de estima\u00e7\u00e3o mais engra\u00e7ada que j\u00e1 contamos?", "ro": "Care e cea mai amuzant\u0103 poveste cu un animal de companie pe care am spus-o vreodat\u0103?", "fr": "Quelle est l\u2019histoire d\u2019animal de compagnie la plus dr\u00f4le que nous ayons racont\u00e9e ?", "it": "Qual \u00e8 la storia di animale domestico pi\u00f9 divertente che abbiamo mai raccontato?", "fi": "Mik\u00e4 on hauskin lemmikkitarina, jonka olemme koskaan kertoneet?", "nl": "Wat is het grappigste huisdierverhaal dat we ooit hebben verteld?", "no": "Hva er den morsomste dyrehistorien vi noen gang har fortalt?", "sv": "Vad \u00e4r den roligaste husdjursber\u00e4ttelsen vi n\u00e5gonsin har ber\u00e4ttat?", "pl": "Jaka jest najzabawniejsza historia o zwierz\u0119tach, jak\u0105 kiedykolwiek opowiedzieli\u015bmy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s the funniest pet story we’ve ever told?';