UPDATE questions
SET translations = '{"en": "What are your favorite kind of compliments \u2014and why?", "da": "Hvilken slags komplimenter kan du bedst lide \u2014 og hvorfor?", "de": "Welche Art von Komplimenten magst du am liebsten \u2013 und warum?", "es": "\u00bfQu\u00e9 tipo de cumplidos te gustan m\u00e1s, y por qu\u00e9?", "pt": "Que tipo de elogios voc\u00ea mais gosta \u2014 e por qu\u00ea?", "ro": "Ce fel de complimente \u00ee\u021bi plac cel mai mult \u2014 \u0219i de ce?", "fr": "Quel type de compliments pr\u00e9f\u00e8res-tu \u2014 et pourquoi ?", "it": "Quali sono i tuoi complimenti preferiti \u2014 e perch\u00e9?", "fi": "Mitk\u00e4 ovat suosikkisi kehuja \u2014 ja miksi?", "nl": "Wat zijn jouw favoriete soorten complimenten \u2014 en waarom?", "no": "Hva er dine favorittkomplimenter \u2014 og hvorfor?", "sv": "Vilka \u00e4r dina favoritkommentarer \u2014 och varf\u00f6r?", "pl": "Jakie s\u0105 twoje ulubione rodzaje komplement\u00f3w \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What are your favorite kind of compliments —and why?';
UPDATE questions
SET translations = '{"en": "What makes you feel like we\u2019re a real team?", "da": "Hvad f\u00e5r dig til at f\u00f8le, at vi er et rigtigt team?", "de": "Was l\u00e4sst dich f\u00fchlen, dass wir ein echtes Team sind?", "es": "\u00bfQu\u00e9 te hace sentir que somos un verdadero equipo?", "pt": "O que faz voc\u00ea sentir que somos uma verdadeira equipe?", "ro": "Ce te face s\u0103 sim\u021bi c\u0103 suntem o adev\u0103rat\u0103 echip\u0103?", "fr": "Qu\u2019est-ce qui te fait sentir que nous formons une vraie \u00e9quipe ?", "it": "Cosa ti fa sentire che siamo una vera squadra?", "fi": "Mik\u00e4 saa sinut tuntemaan, ett\u00e4 olemme oikea tiimi?", "nl": "Wat zorgt ervoor dat je het gevoel hebt dat we een echt team zijn?", "no": "Hva f\u00e5r deg til \u00e5 f\u00f8le at vi er et ekte team?", "sv": "Vad f\u00e5r dig att k\u00e4nna att vi verkligen \u00e4r ett team?", "pl": "Co sprawia, \u017ce czujesz, \u017ce jeste\u015bmy prawdziwym zespo\u0142em?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What makes you feel like we’re a real team?';
UPDATE questions
SET translations = '{"en": "What would you keep if you had to halve your possessions?", "da": "Hvad ville du beholde, hvis du skulle halvere dine ejendele?", "de": "Was w\u00fcrdest du behalten, wenn du deinen Besitz halbieren m\u00fcsstest?", "es": "\u00bfQu\u00e9 conservar\u00edas si tuvieras que reducir tus posesiones a la mitad?", "pt": "O que voc\u00ea manteria se tivesse que reduzir seus pertences pela metade?", "ro": "Ce ai p\u0103stra dac\u0103 ar trebui s\u0103 \u00ee\u021bi \u00eenjum\u0103t\u0103\u021be\u0219ti lucrurile?", "fr": "Que garderais-tu si tu devais r\u00e9duire tes possessions de moiti\u00e9 ?", "it": "Cosa terresti se dovessi dimezzare i tuoi possedimenti?", "fi": "Mit\u00e4 pit\u00e4isit, jos sinun pit\u00e4isi puolittaa omaisuutesi?", "nl": "Wat zou je behouden als je je bezittingen moest halveren?", "no": "Hva ville du beholdt hvis du m\u00e5tte halvere eiendelene dine?", "sv": "Vad skulle du beh\u00e5lla om du var tvungen att halvera dina \u00e4godelar?", "pl": "Co by\u015b zatrzyma\u0142, gdyby\u015b musia\u0142 po\u0142ow\u0119 swoich rzeczy odda\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What would you keep if you had to halve your possessions?';
UPDATE questions
SET translations = '{"en": "Which memory reminds you that choosing each other is always worth it?", "da": "Hvilket minde minder dig om, at det altid er det v\u00e6rd at v\u00e6lge hinanden?", "de": "Welche Erinnerung erinnert dich daran, dass es sich immer lohnt, einander zu w\u00e4hlen?", "es": "\u00bfQu\u00e9 recuerdo te recuerda que siempre vale la pena elegirnos el uno al otro?", "pt": "Que lembran\u00e7a te faz lembrar que vale sempre a pena escolher um ao outro?", "ro": "Ce amintire \u00ee\u021bi aminte\u0219te c\u0103 merit\u0103 mereu s\u0103 ne alegem unul pe cel\u0103lalt?", "fr": "Quel souvenir te rappelle que se choisir l\u2019un l\u2019autre en vaut toujours la peine ?", "it": "Quale ricordo ti ricorda che scegliere l''uno l''altro ne vale sempre la pena?", "fi": "Mik\u00e4 muisto muistuttaa sinua siit\u00e4, ett\u00e4 toisten valitseminen on aina sen arvoista?", "nl": "Welke herinnering herinnert je eraan dat het altijd de moeite waard is om voor elkaar te kiezen?", "no": "Hvilket minne minner deg om at det alltid er verdt \u00e5 velge hverandre?", "sv": "Vilket minne p\u00e5minner dig om att det alltid \u00e4r v\u00e4rt att v\u00e4lja varandra?", "pl": "Kt\u00f3ra pami\u0119\u0107 przypomina ci, \u017ce wybieranie siebie nawzajem zawsze jest tego warte?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Which memory reminds you that choosing each other is always worth it?';
UPDATE questions
SET translations = '{"en": "When do you feel most emotionally safe with me\u2014and what helps create that?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest f\u00f8lelsesm\u00e6ssigt tryg med mig \u2014 og hvad hj\u00e6lper med at skabe det?", "de": "Wann f\u00fchlst du dich bei mir am emotional sichersten \u2013 und was tr\u00e4gt dazu bei?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s emocionalmente seguro(a) conmigo, y qu\u00e9 ayuda a crear eso?", "pt": "Quando voc\u00ea se sente mais emocionalmente seguro(a) comigo \u2014 e o que ajuda a criar isso?", "ro": "C\u00e2nd te sim\u021bi cel mai \u00een siguran\u021b\u0103 emo\u021bional cu mine \u2014 \u0219i ce ajut\u0103 la asta?", "fr": "Quand te sens-tu le plus en s\u00e9curit\u00e9 \u00e9motionnellement avec moi \u2014 et qu\u2019est-ce qui y contribue ?", "it": "Quando ti senti pi\u00f9 emotivamente al sicuro con me\u2014e cosa aiuta a creare quella sensazione?", "fi": "Milloin tunnet itsesi emotionaalisesti turvallisimmaksi kanssani\u2014ja mik\u00e4 auttaa luomaan sen?", "nl": "Wanneer voel je je het meest emotioneel veilig bij mij - en wat helpt om dat te cre\u00ebren?", "no": "N\u00e5r f\u00f8ler du deg mest f\u00f8lelsesmessig trygg med meg\u2014og hva bidrar til \u00e5 skape det?", "sv": "N\u00e4r k\u00e4nner du dig mest k\u00e4nslom\u00e4ssigt trygg med mig \u2013 och vad hj\u00e4lper till att skapa det?", "pl": "Kiedy czujesz si\u0119 ze mn\u0105 najbardziej emocjonalnie bezpiecznie - i co pomaga to stworzy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When do you feel most emotionally safe with me—and what helps create that?';
UPDATE questions
SET translations = '{"en": "What makes you feel desired without words?", "da": "Hvad f\u00e5r dig til at f\u00f8le dig \u00f8nsket uden ord?", "de": "Was l\u00e4sst dich dich begehrt f\u00fchlen, ohne Worte?", "es": "\u00bfQu\u00e9 te hace sentir deseado(a) sin palabras?", "pt": "O que faz voc\u00ea se sentir desejado(a) sem palavras?", "ro": "Ce te face s\u0103 te sim\u021bi dorit(\u0103) f\u0103r\u0103 cuvinte?", "fr": "Qu\u2019est-ce qui te fait te sentir d\u00e9sir\u00e9(e) sans mots ?", "it": "Cosa ti fa sentire desiderato senza parole?", "fi": "Mik\u00e4 saa sinut tuntemaan itsesi halutuksi ilman sanoja?", "nl": "Wat laat je je gewenst voelen zonder woorden?", "no": "Hva f\u00e5r deg til \u00e5 f\u00f8le deg \u00f8nsket uten ord?", "sv": "Vad f\u00e5r dig att k\u00e4nna dig \u00e5tr\u00e5dd utan ord?", "pl": "Co sprawia, \u017ce czujesz si\u0119 po\u017c\u0105dany bez s\u0142\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What makes you feel desired without words?';
UPDATE questions
SET translations = '{"en": "What kind of fun do you want more of together?", "da": "Hvilken slags sjov vil du gerne have mere af sammen?", "de": "Welche Art von Spa\u00df m\u00f6chtest du gerne mehr mit mir haben?", "es": "\u00bfQu\u00e9 tipo de diversi\u00f3n te gustar\u00eda tener m\u00e1s juntos?", "pt": "Que tipo de divers\u00e3o voc\u00ea gostaria de ter mais comigo?", "ro": "Ce fel de distrac\u021bie ai vrea s\u0103 avem mai des \u00eempreun\u0103?", "fr": "Quel type d\u2019amusement aimerais-tu que nous ayons plus souvent ensemble ?", "it": "Che tipo di divertimento vuoi di pi\u00f9 insieme?", "fi": "Millaista hauskuutta haluaisit lis\u00e4\u00e4 yhdess\u00e4?", "nl": "Wat voor soort plezier wil je meer samen hebben?", "no": "Hva slags moro \u00f8nsker du mer av sammen?", "sv": "Vilken typ av roligheter vill du ha mer av tillsammans?", "pl": "Jakiego rodzaju zabawy chcia\u0142by\u015b mie\u0107 wi\u0119cej razem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What kind of fun do you want more of together?';
UPDATE questions
SET translations = '{"en": "Which friend or couple around us brings out our best?", "da": "Hvilken ven eller hvilket par omkring os bringer det bedste frem i os?", "de": "Welcher Freund oder welches Paar um uns herum bringt das Beste in uns hervor?", "es": "\u00bfQu\u00e9 amigo o pareja a nuestro alrededor saca lo mejor de nosotros?", "pt": "Que amigo ou casal ao nosso redor traz o melhor de n\u00f3s?", "ro": "Ce prieten sau cuplu din jurul nostru scoate ce e mai bun din noi?", "fr": "Quel ami ou couple autour de nous fait ressortir le meilleur de nous ?", "it": "Quale amico o coppia intorno a noi tira fuori il meglio di noi?", "fi": "Mik\u00e4 yst\u00e4v\u00e4 tai pari ymp\u00e4rill\u00e4mme saa meid\u00e4t loistamaan parhaimmillamme?", "nl": "Welke vriend of welk stel om ons heen haalt het beste in ons naar boven?", "no": "Hvilken venn eller hvilket par rundt oss f\u00e5r frem det beste i oss?", "sv": "Vilken v\u00e4n eller vilket par omkring oss f\u00e5r fram det b\u00e4sta i oss?", "pl": "Kt\u00f3ry przyjaciel lub para w naszym otoczeniu wydobywa z nas to, co najlepsze?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Which friend or couple around us brings out our best?';
UPDATE questions
SET translations = '{"en": "Who have you looked up to in your life?", "da": "Hvem har du set mest op til i dit liv?", "de": "Zu wem hast du in deinem Leben am meisten aufgesehen?", "es": "\u00bfA qui\u00e9n has admirado m\u00e1s en tu vida?", "pt": "A quem voc\u00ea mais admirou na sua vida?", "ro": "Pe cine ai admirat cel mai mult \u00een via\u021ba ta?", "fr": "Qui as-tu le plus admir\u00e9 dans ta vie ?", "it": "Chi hai ammirato nella tua vita?", "fi": "Ket\u00e4 olet ihaillut el\u00e4m\u00e4ss\u00e4si?", "nl": "Wie heb je in je leven als voorbeeld gezien?", "no": "Hvem har du sett opp til i livet ditt?", "sv": "Vem har du sett upp till i ditt liv?", "pl": "Kogo podziwia\u0142e\u015b w swoim \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Who have you looked up to in your life?';
UPDATE questions
SET translations = '{"en": "What do you think would truly make you a happy person?", "da": "Hvad tror du, der virkelig ville g\u00f8re dig til et lykkeligt menneske?", "de": "Was glaubst du, w\u00fcrde dich wirklich zu einem gl\u00fccklichen Menschen machen?", "es": "\u00bfQu\u00e9 crees que realmente te har\u00eda una persona feliz?", "pt": "O que voc\u00ea acha que realmente te tornaria uma pessoa feliz?", "ro": "Ce crezi c\u0103 te-ar face cu adev\u0103rat o persoan\u0103 fericit\u0103?", "fr": "Que penses-tu qui te rendrait vraiment heureux(se) ?", "it": "Cosa pensi che ti renderebbe davvero una persona felice?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 todella tekisi sinusta onnellisen ihmisen?", "nl": "Wat denk je dat je echt een gelukkig persoon zou maken?", "no": "Hva tror du virkelig ville gjort deg til en lykkelig person?", "sv": "Vad tror du verkligen skulle g\u00f6ra dig till en lycklig person?", "pl": "Co my\u015blisz, co naprawd\u0119 uczyni\u0142oby ci\u0119 szcz\u0119\u015bliwym cz\u0142owiekiem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you think would truly make you a happy person?';