UPDATE questions
SET translations = '{"en": "Laundry edition: how many times can you wear something before it really has to meet the washing machine?", "da": "Vasket\u00f8js-udgave: Hvor mange gange kan du have noget p\u00e5, f\u00f8r det virkelig m\u00e5 m\u00f8de vaskemaskinen?", "de": "W\u00e4sche-Edition: Wie oft kannst du etwas tragen, bevor es wirklich in die Waschmaschine muss?", "es": "Edici\u00f3n colada: \u00bfcu\u00e1ntas veces puedes ponerte algo antes de que de verdad tenga que conocer la lavadora?", "pt": "Edi\u00e7\u00e3o lavanderia: quantas vezes voc\u00ea pode usar uma pe\u00e7a antes de ela realmente precisar conhecer a m\u00e1quina de lavar?", "ro": "Edi\u021bia rufe: de c\u00e2te ori po\u021bi purta ceva \u00eenainte s\u0103 trebuiasc\u0103 cu adev\u0103rat s\u0103 ajung\u0103 \u00een ma\u0219ina de sp\u0103lat?", "fr": "\u00c9dition linge : combien de fois peux-tu porter quelque chose avant qu\u2019il doive vraiment rencontrer la machine \u00e0 laver ?", "it": "Edizione lavanderia: quante volte puoi indossare qualcosa prima che debba davvero incontrare la lavatrice?", "fi": "Pyykkiversio: kuinka monta kertaa voit k\u00e4ytt\u00e4\u00e4 jotain ennen kuin se todella tarvitsee tavata pesukone?", "nl": "Was editie: hoe vaak kun je iets dragen voordat het echt in de wasmachine moet?", "no": "Vaskemaskinens utgave: hvor mange ganger kan du bruke noe f\u00f8r det virkelig m\u00e5 i vaskemaskinen?", "sv": "Tv\u00e4ttutg\u00e5van: hur m\u00e5nga g\u00e5nger kan du anv\u00e4nda n\u00e5got innan det verkligen m\u00e5ste tr\u00e4ffa tv\u00e4ttmaskinen?", "pl": "Edycja prania: ile razy mo\u017cesz nosi\u0107 co\u015b, zanim naprawd\u0119 b\u0119dzie musia\u0142o trafi\u0107 do pralki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Laundry edition: how many times can you wear something before it really has to meet the washing machine?';
UPDATE questions
SET translations = '{"en": "How many times do you hit snooze before you\u2019re actually awake?", "da": "Hvor mange gange trykker du p\u00e5 snooze, f\u00f8r du rent faktisk er v\u00e5gen?", "de": "Wie oft dr\u00fcckst du auf Snooze, bevor du wirklich wach bist?", "es": "\u00bfCu\u00e1ntas veces pulsas el bot\u00f3n de posponer antes de estar realmente despierto/a?", "pt": "Quantas vezes voc\u00ea aperta o soneca antes de estar realmente acordado(a)?", "ro": "De c\u00e2te ori ape\u0219i pe \u201esnooze\u201d \u00eenainte s\u0103 fii cu adev\u0103rat treaz/treaz\u0103?", "fr": "Combien de fois appuies-tu sur \u00ab snooze \u00bb avant d\u2019\u00eatre vraiment r\u00e9veill\u00e9(e) ?", "it": "Quante volte premi il tasto snooze prima di essere davvero sveglio?", "fi": "Kuinka monta kertaa snooze-nappia painat ennen kuin olet oikeasti hereill\u00e4?", "nl": "Hoeveel keer druk je op de sluimerknop voordat je echt wakker bent?", "no": "Hvor mange ganger trykker du p\u00e5 slumreknappen f\u00f8r du faktisk er v\u00e5ken?", "sv": "Hur m\u00e5nga g\u00e5nger trycker du p\u00e5 snooze innan du faktiskt \u00e4r vaken?", "pl": "Ile razy naciskasz drzemk\u0119, zanim naprawd\u0119 wstaniesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'How many times do you hit snooze before you’re actually awake?';
UPDATE questions
SET translations = '{"en": "Group chat edition: what kind of messages do you quietly ignore the most?", "da": "Gruppechat-udgave: Hvilken slags beskeder ignorerer du oftest i stilhed?", "de": "Gruppenchat-Edition: Welche Art von Nachrichten ignorierst du am h\u00e4ufigsten heimlich?", "es": "Edici\u00f3n grupo de chat: \u00bfqu\u00e9 tipo de mensajes ignoras en silencio con m\u00e1s frecuencia?", "pt": "Edi\u00e7\u00e3o grupo de conversa: que tipo de mensagem voc\u00ea ignora em sil\u00eancio com mais frequ\u00eancia?", "ro": "Edi\u021bia grup de chat: ce fel de mesaje ignori cel mai des \u00een t\u0103cere?", "fr": "\u00c9dition conversation de groupe : quel type de message ignores-tu le plus silencieusement ?", "it": "Edizione chat di gruppo: quali tipi di messaggi ignori pi\u00f9 spesso in silenzio?", "fi": "Ryhm\u00e4keskustelu: mink\u00e4laisia viestej\u00e4 j\u00e4t\u00e4t eniten huomiotta?", "nl": "Groepschat editie: welke soort berichten negeer je het vaakst stilletjes?", "no": "Gruppechat-utgave: hvilke typer meldinger ignorerer du mest stille?", "sv": "Gruppchattversion: vilka typer av meddelanden ignorerar du tyst mest?", "pl": "W edycji czatu grupowego: jakie rodzaje wiadomo\u015bci najcz\u0119\u015bciej ignorujesz w milczeniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Group chat edition: what kind of messages do you quietly ignore the most?';
UPDATE questions
SET translations = '{"en": "You can add one ridiculous rule to society\u2014what is it?", "da": "Du kan tilf\u00f8je \u00e9n latterlig regel til samfundet \u2013 hvad er den?", "de": "Du darfst eine absurde Regel zur Gesellschaft hinzuf\u00fcgen \u2013 was w\u00e4re sie?", "es": "Puedes a\u00f1adir una regla rid\u00edcula a la sociedad \u2014 \u00bfcu\u00e1l ser\u00eda?", "pt": "Podes adicionar uma regra rid\u00edcula \u00e0 sociedade \u2014 qual seria?", "ro": "Po\u0163i ad\u0103uga o regul\u0103 ridicol\u0103 la societate \u2014 care ar fi?", "fr": "Tu peux ajouter une r\u00e8gle ridicule \u00e0 la soci\u00e9t\u00e9 \u2014 laquelle serait-elle ?", "it": "Puoi aggiungere una regola ridicola alla societ\u00e0\u2014qual \u00e8?", "fi": "Voit lis\u00e4t\u00e4 yhden j\u00e4rjett\u00f6m\u00e4n s\u00e4\u00e4nn\u00f6n yhteiskuntaan\u2014mik\u00e4 se olisi?", "nl": "Je mag \u00e9\u00e9n belachelijke regel aan de samenleving toevoegen\u2014wat zou het zijn?", "no": "Du kan legge til en latterlig regel i samfunnet - hva ville det v\u00e6rt?", "sv": "Du kan l\u00e4gga till en l\u00f6jlig regel i samh\u00e4llet \u2013 vad skulle det vara?", "pl": "Mo\u017cesz doda\u0107 jedn\u0105 absurdaln\u0105 zasad\u0119 do spo\u0142ecze\u0144stwa\u2014jaka by to by\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'You can add one ridiculous rule to society—what is it?';
UPDATE questions
SET translations = '{"en": "Fridge edition: what item has been in there so long it should be paying rent?", "da": "K\u00f8leskabs-udgave: Hvilken ting har st\u00e5et derinde s\u00e5 l\u00e6nge, at den burde betale husleje?", "de": "K\u00fchlschrank-Edition: Welches Teil steht schon so lange dort, dass es eigentlich Miete zahlen m\u00fcsste?", "es": "Edici\u00f3n nevera: \u00bfqu\u00e9 cosa lleva ah\u00ed tanto tiempo que ya deber\u00eda pagar alquiler?", "pt": "Edi\u00e7\u00e3o geladeira: qual item est\u00e1 l\u00e1 h\u00e1 tanto tempo que j\u00e1 deveria pagar aluguel?", "ro": "Edi\u021bia frigider: ce lucru st\u0103 acolo de at\u00e2t de mult timp \u00eenc\u00e2t ar trebui deja s\u0103 pl\u0103teasc\u0103 chirie?", "fr": "\u00c9dition frigo : quel objet est l\u00e0 depuis si longtemps qu\u2019il devrait d\u00e9j\u00e0 payer un loyer ?", "it": "Edizione frigorifero: quale oggetto \u00e8 rimasto l\u00ec dentro cos\u00ec a lungo che dovrebbe pagare l''affitto?", "fi": "J\u00e4\u00e4kaappiversio: mik\u00e4 esine on ollut siell\u00e4 niin kauan, ett\u00e4 sen pit\u00e4isi maksaa vuokraa?", "nl": "Koelkast editie: welk item is daar zo lang dat het huur zou moeten betalen?", "no": "Kj\u00f8leskapsutgave: hvilket item har v\u00e6rt der s\u00e5 lenge at det burde betale husleie?", "sv": "Kylsk\u00e5psutg\u00e5van: vilken sak har varit d\u00e4r s\u00e5 l\u00e4nge att den borde betala hyra?", "pl": "Edycja lod\u00f3wki: jaki przedmiot jest tam tak d\u0142ugo, \u017ce powinien p\u0142aci\u0107 czynsz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Fridge edition: what item has been in there so long it should be paying rent?';
UPDATE questions
SET translations = '{"en": "Which of us would be banned from a fancy library first\u2014and why?", "da": "Hvem af os ville blive udelukket fra et fint bibliotek f\u00f8rst \u2013 og hvorfor?", "de": "Wer von uns w\u00fcrde zuerst aus einer feinen Bibliothek verwiesen \u2013 und warum?", "es": "\u00bfQui\u00e9n de nosotros ser\u00eda expulsado primero de una biblioteca elegante \u2014 y por qu\u00e9?", "pt": "Qual de n\u00f3s seria banido primeiro de uma biblioteca chique \u2014 e por qu\u00ea?", "ro": "Care dintre noi ar fi exclus primul dintr-o bibliotec\u0103 select\u0103 \u2014 \u015fi de ce?", "fr": "Lequel d\u2019entre nous serait expuls\u00e9 d\u2019une biblioth\u00e8que chic en premier \u2014 et pourquoi ?", "it": "Quale di noi verrebbe espulso da una biblioteca elegante per primo\u2014e perch\u00e9?", "fi": "Kumpi meist\u00e4 saisi ensimm\u00e4isen\u00e4 porttikiellon hienoon kirjastoon - ja miksi?", "nl": "Wie van ons zou als eerste verbannen worden uit een chique bibliotheek - en waarom?", "no": "Hvem av oss ville blitt utestengt fra et fint bibliotek f\u00f8rst\u2014og hvorfor?", "sv": "Vilken av oss skulle bli utkastad fr\u00e5n ett fint bibliotek f\u00f6rst\u2014och varf\u00f6r?", "pl": "Kto z nas zosta\u0142by pierwszym zakazanym go\u015bciem w eleganckiej bibliotece - i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Which of us would be banned from a fancy library first—and why?';
UPDATE questions
SET translations = '{"en": "Choose a useless talent to become world-famous for. What\u2019s your claim to fame?", "da": "V\u00e6lg et ubrugeligt talent at blive verdenskendt for. Hvad er dit krav til ber\u00f8mmelse?", "de": "W\u00e4hle ein nutzloses Talent, um weltweit ber\u00fchmt zu werden. Was ist dein Ruhmesanspruch?", "es": "Elige un talento in\u00fatil para llegar a ser famoso mundialmente. \u00bfCu\u00e1l es tu reivindicaci\u00f3n para la fama?", "pt": "Escolhe um talento in\u00fatil para seres famoso mundialmente. Qual \u00e9 a tua reivindica\u00e7\u00e3o de fama?", "ro": "Alege un talent inutil pentru a deveni celebru la nivel mondial. Care este preten\u0163ia ta de faim\u0103?", "fr": "Choisis un talent inutile pour devenir c\u00e9l\u00e8bre dans le monde entier. Quelle est ta revendication de gloire ?", "it": "Scegli un talento inutile per diventare famoso in tutto il mondo. Qual \u00e8 il tuo motivo di celebrit\u00e0?", "fi": "Valitse hy\u00f6dytt\u00f6m\u00e4ksi katsottava taito, josta haluaisit tulla maailman kuuluisaksi. Mik\u00e4 on sinun kuuluisuutesi syy?", "nl": "Kies een nutteloos talent om wereldberoemd om te worden. Wat is jouw claim to fame?", "no": "Velg et unyttig talent \u00e5 bli verdensber\u00f8mt for. Hva er din ber\u00f8mmelse?", "sv": "V\u00e4lj en v\u00e4rdel\u00f6s talang att bli v\u00e4rldsber\u00f6md f\u00f6r. Vad \u00e4r din ber\u00f6mmelse?", "pl": "Wybierz bezu\u017cyteczny talent, za kt\u00f3ry chcia\u0142by\u015b sta\u0107 si\u0119 s\u0142awny na ca\u0142ym \u015bwiecie. Jaki jest tw\u00f3j pow\u00f3d do s\u0142awy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Choose a useless talent to become world-famous for. What’s your claim to fame?';
UPDATE questions
SET translations = '{"en": "What item has been \u201cwaiting to be folded\u201d for the longest time?", "da": "Hvilken ting har \u201cventet p\u00e5 at blive lagt sammen\u201d i l\u00e6ngst tid?", "de": "Welches Teil wartet schon am l\u00e4ngsten darauf, endlich zusammengelegt zu werden?", "es": "\u00bfQu\u00e9 prenda lleva m\u00e1s tiempo \u201cesperando a ser doblada\u201d?", "pt": "Qual pe\u00e7a est\u00e1 \u201cesperando para ser dobrada\u201d h\u00e1 mais tempo?", "ro": "Care obiect a \u201ea\u0219teptat s\u0103 fie \u00eemp\u0103turit\u201d cel mai mult timp?", "fr": "Quel v\u00eatement \u00ab attend d\u2019\u00eatre pli\u00e9 \u00bb depuis le plus longtemps ?", "it": "Quale oggetto \u00e8 stato \"in attesa di essere piegato\" per il periodo pi\u00f9 lungo?", "fi": "Mik\u00e4 esine on \"odottanut taittamista\" pisimp\u00e4\u00e4n?", "nl": "welk item wacht al het langst om gevouwen te worden?", "no": "Hvilket plagg har \"ventet p\u00e5 \u00e5 bli brettet\" lengst?", "sv": "Vilken sak har \"v\u00e4ntat p\u00e5 att bli vikt\" l\u00e4ngst tid?", "pl": "Jaki przedmiot czeka\u0142 najd\u0142u\u017cej na z\u0142o\u017cenie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'What item has been “waiting to be folded” for the longest time?';
UPDATE questions
SET translations = '{"en": "Bedtime edition: what\u2019s the last thing you usually see on your phone before you actually sleep?", "da": "Godnat-udgave: Hvad er det sidste, du normalt ser p\u00e5 din telefon, f\u00f8r du faktisk sover?", "de": "Schlafenszeit-Edition: Was ist das Letzte, was du normalerweise auf deinem Handy siehst, bevor du wirklich einschl\u00e4fst?", "es": "Edici\u00f3n hora de dormir: \u00bfqu\u00e9 es lo \u00faltimo que sueles ver en tu tel\u00e9fono antes de dormirte de verdad?", "pt": "Edi\u00e7\u00e3o hora de dormir: qual \u00e9 a \u00faltima coisa que voc\u00ea geralmente v\u00ea no telefone antes de realmente dormir?", "ro": "Edi\u021bia ora de culcare: care este ultimul lucru pe care \u00eel vezi de obicei pe telefon \u00eenainte s\u0103 adormi cu adev\u0103rat?", "fr": "\u00c9dition coucher : quelle est la derni\u00e8re chose que tu regardes g\u00e9n\u00e9ralement sur ton t\u00e9l\u00e9phone avant de t\u2019endormir vraiment ?", "it": "Edizione prima di dormire: qual \u00e8 l''ultima cosa che di solito vedi sul tuo telefono prima di addormentarti?", "fi": "Nukkumaanmenoaika: mik\u00e4 on viimeinen asia, jonka yleens\u00e4 n\u00e4et puhelimessasi ennen kuin oikeasti nukahdat?", "nl": "Bedtijd editie: wat is het laatste dat je meestal op je telefoon ziet voordat je daadwerkelijk gaat slapen?", "no": "Sengeklokke-utgave: hva er det siste du vanligvis ser p\u00e5 telefonen din f\u00f8r du faktisk sovner?", "sv": "S\u00e4ngg\u00e5endet: vad \u00e4r det sista du vanligtvis ser p\u00e5 din telefon innan du faktiskt somnar?", "pl": "Edycja na dobranoc: co zazwyczaj ostatnio widzisz na swoim telefonie przed snem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'Bedtime edition: what’s the last thing you usually see on your phone before you actually sleep?';
UPDATE questions
SET translations = '{"en": "If your phone\u2019s autocorrect had a personality, how would it describe you?", "da": "Hvilken fane har v\u00e6ret \u00e5ben s\u00e5 l\u00e6nge, at den i praksis bor der nu?", "de": "Welcher Tab ist schon so lange ge\u00f6ffnet, dass er dort praktisch wohnt?", "es": "\u00bfQu\u00e9 pesta\u00f1a lleva abierta tanto tiempo que b\u00e1sicamente ya vive ah\u00ed?", "pt": "Qual aba est\u00e1 aberta h\u00e1 tanto tempo que basicamente j\u00e1 mora ali?", "ro": "Ce fil\u0103 este deschis\u0103 de at\u00e2t de mult timp \u00eenc\u00e2t practic locuie\u0219te acolo acum?", "fr": "Quel onglet est ouvert depuis si longtemps qu\u2019il habite pratiquement l\u00e0 maintenant ?", "it": "Se il correttore automatico del tuo telefono avesse una personalit\u00e0, come ti descriverebbe?", "fi": "Jos puhelimesi automaattinen korjaus olisi persoonallisuus, millaisena se kuvailisi sinua?", "nl": "Als de autocorrectie van je telefoon een persoonlijkheid had, hoe zou het jou dan beschrijven?", "no": "Hvis telefonens autokorrektur hadde en personlighet, hvordan ville den beskrevet deg?", "sv": "Om din telefons autokorrigering hade en personlighet, hur skulle den beskriva dig?", "pl": "Gdyby autokorekta w twoim telefonie mia\u0142a osobowo\u015b\u0107, jak by ci\u0119 opisa\u0142a?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Silly Talks'
  AND translations->>'en' = 'If your phone’s autocorrect had a personality, how would it describe you?';