UPDATE questions
SET translations = '{"en": "Would you rather have snow every day or sunshine every day?", "da": "Ville du hellere have sne hver dag eller solskin hver dag?", "de": "W\u00fcrdest du lieber jeden Tag Schnee oder jeden Tag Sonnenschein haben?", "es": "\u00bfPreferir\u00edas tener nieve todos los d\u00edas o sol todos los d\u00edas?", "pt": "Preferias ter neve todos os dias ou sol todos os dias?", "ro": "Ai prefera s\u0103 fie z\u0103pad\u0103 zilnic sau soare zilnic?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir de la neige tous les jours ou du soleil tous les jours ?", "it": "Preferiresti avere neve ogni giorno o sole ogni giorno?", "fi": "Haluaisitko mieluummin lunta joka p\u00e4iv\u00e4 vai auringonpaistetta joka p\u00e4iv\u00e4?", "nl": "Zou je liever elke dag sneeuw hebben of elke dag zonneschijn?", "no": "Vil du heller ha sn\u00f8 hver dag eller solskinn hver dag?", "sv": "Skulle du hellre vilja ha sn\u00f6 varje dag eller sol varje dag?", "pl": "Czy wola\u0142by\u015b mie\u0107 \u015bnieg ka\u017cdego dnia, czy s\u0142o\u0144ce ka\u017cdego dnia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have snow every day or sunshine every day?';
UPDATE questions
SET translations = '{"en": "Would you rather have your favorite meal on repeat forever or never repeat a meal again?", "da": "Ville du hellere spise din livret favorit hver dag eller aldrig spise det samme m\u00e5ltid to gange?", "de": "W\u00fcrdest du lieber dein Lieblingsessen immer wieder essen oder nie zweimal dasselbe?", "es": "\u00bfPreferir\u00edas comer tu comida favorita siempre o nunca repetir una comida?", "pt": "Preferias comer sempre a tua refei\u00e7\u00e3o favorita ou nunca repetir uma refei\u00e7\u00e3o?", "ro": "Ai prefera s\u0103 m\u0103n\u00e2nci mereu felul t\u0103u preferat sau s\u0103 nu repe\u021bi niciodat\u0103 o mas\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu manger ton plat pr\u00e9f\u00e9r\u00e9 en boucle ou ne jamais r\u00e9p\u00e9ter un repas ?", "it": "Preferiresti avere il tuo piatto preferito in ripetizione per sempre o non ripetere mai pi\u00f9 un pasto?", "fi": "Haluaisitko sy\u00f6d\u00e4 lempiruokaasi toistuvasti ikuisesti vai et koskaan toistaa ateriaa uudelleen?", "nl": "Zou je liever je favoriete maaltijd voor altijd herhalen of nooit meer een maaltijd herhalen?", "no": "Ville du heller hatt din favorittm\u00e5ltid i reprise for alltid, eller aldri gjentatt et m\u00e5ltid igjen?", "sv": "Skulle du hellre ha din favoritr\u00e4tt p\u00e5 repeat f\u00f6r alltid eller aldrig upprepa en m\u00e5ltid igen?", "pl": "Czy wola\u0142by\u015b je\u015b\u0107 swoje ulubione danie w k\u00f3\u0142ko przez wieczno\u015b\u0107, czy nigdy wi\u0119cej nie powt\u00f3rzy\u0107 \u017cadnego posi\u0142ku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have your favorite meal on repeat forever or never repeat a meal again?';
UPDATE questions
SET translations = '{"en": "Would you rather have to rhyme every sentence or start every sentence with \u201cYo!\u201d?", "da": "Ville du hellere rime i hver s\u00e6tning eller starte hver s\u00e6tning med \u201cYo!\u201d?", "de": "W\u00fcrdest du lieber in jedem Satz reimen oder jeden Satz mit \u201eYo!\u201c beginnen?", "es": "\u00bfPreferir\u00edas rimar en cada frase o empezar cada frase con \u201c\u00a1Yo!\u201d?", "pt": "Preferias rimar em todas as frases ou come\u00e7ar todas com \u201cYo!\u201d?", "ro": "Ai prefera s\u0103 rimezi \u00een fiecare propozi\u021bie sau s\u0103 \u00eencepi fiecare cu \u201cYo!\u201d?", "fr": "Pr\u00e9f\u00e9rerais-tu rimer dans chaque phrase ou commencer chaque phrase par \u00ab Yo! \u00bb ?", "it": "Preferiresti dover fare rima in ogni frase o iniziare ogni frase con \"Yo!\"?", "fi": "Haluaisitko mieluummin riimitell\u00e4 jokaisen lauseen vai aloittaa jokaisen lauseen sanalla \"Yo!\"?", "nl": "Zou je liever elke zin moeten rijmen of elke zin beginnen met \"Yo!\"?", "no": "Ville du heller m\u00e5tte rimme hver setning eller starte hver setning med \"Yo!\"?", "sv": "Skulle du hellre beh\u00f6va rimma varje mening eller b\u00f6rja varje mening med \"Yo!\"?", "pl": "Czy wola\u0142by\u015b rymowa\u0107 ka\u017cd\u0105 zdanie, czy zaczyna\u0107 ka\u017cde zdanie od \u201eYo!\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to rhyme every sentence or start every sentence with “Yo!”?';
UPDATE questions
SET translations = '{"en": "Would you rather live in a video game or in a storybook world?", "da": "Ville du hellere bo i et videospil eller i en eventyrbogsverden?", "de": "W\u00fcrdest du lieber in einem Videospiel oder in einer M\u00e4rchenwelt leben?", "es": "\u00bfPreferir\u00edas vivir en un videojuego o en un mundo de cuentos?", "pt": "Preferias viver num videojogo ou num mundo de contos de fadas?", "ro": "Ai prefera s\u0103 tr\u0103ie\u0219ti \u00eentr-un joc video sau \u00eentr-o lume de poveste?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre dans un jeu vid\u00e9o ou dans un monde de conte ?", "it": "Preferiresti vivere in un videogioco o in un mondo da libro di fiabe?", "fi": "Haluaisitko mieluummin el\u00e4\u00e4 videopeliss\u00e4 vai satukirjan maailmassa?", "nl": "Zou je liever in een videogame of in een verhaalwereld leven?", "no": "Ville du heller bo i et videospill eller i en eventyrverden?", "sv": "Skulle du hellre bo i ett videospel eller i en sagoboks v\u00e4rld?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 w grze wideo, czy w \u015bwiecie z ksi\u0105\u017cki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live in a video game or in a storybook world?';
UPDATE questions
SET translations = '{"en": "Would you rather teleport anywhere or pause time for ten minutes a day?", "da": "Ville du hellere kunne teleportere dig eller standse tiden i ti minutter om dagen?", "de": "W\u00fcrdest du lieber \u00fcberallhin teleportieren oder die Zeit jeden Tag zehn Minuten anhalten?", "es": "\u00bfPreferir\u00edas teletransportarte a cualquier lugar o pausar el tiempo diez minutos al d\u00eda?", "pt": "Preferias teletransportar-te para qualquer lugar ou parar o tempo por dez minutos por dia?", "ro": "Ai prefera s\u0103 te teleportezi oriunde sau s\u0103 opre\u0219ti timpul zece minute pe zi?", "fr": "Pr\u00e9f\u00e9rerais-tu pouvoir te t\u00e9l\u00e9porter ou arr\u00eater le temps dix minutes par jour ?", "it": "Preferiresti teletrasportarti ovunque o fermare il tempo per dieci minuti al giorno?", "fi": "Haluaisitko mieluummin teleportoida minne tahansa vai pys\u00e4ytt\u00e4\u00e4 ajan kymmeneksi minuutiksi p\u00e4iv\u00e4ss\u00e4?", "nl": "Zou je liever overal naartoe kunnen teleporteren of de tijd tien minuten per dag kunnen pauzeren?", "no": "Ville du heller teleportere hvor som helst eller pause tiden i ti minutter hver dag?", "sv": "Skulle du hellre kunna teleportera dig vart som helst eller pausa tiden i tio minuter om dagen?", "pl": "Czy wola\u0142by\u015b teleportowa\u0107 si\u0119 wsz\u0119dzie, czy zatrzyma\u0107 czas na dziesi\u0119\u0107 minut dziennie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather teleport anywhere or pause time for ten minutes a day?';
UPDATE questions
SET translations = '{"en": "Would you rather be able to talk to animals or control the weather?", "da": "Ville du hellere kunne tale med dyr eller styre vejret?", "de": "W\u00fcrdest du lieber mit Tieren sprechen oder das Wetter kontrollieren?", "es": "\u00bfPreferir\u00edas poder hablar con los animales o controlar el clima?", "pt": "Preferias falar com os animais ou controlar o clima?", "ro": "Ai prefera s\u0103 po\u021bi vorbi cu animalele sau s\u0103 controlezi vremea?", "fr": "Pr\u00e9f\u00e9rerais-tu parler aux animaux ou contr\u00f4ler la m\u00e9t\u00e9o ?", "it": "Preferiresti poter parlare con gli animali o controllare il tempo?", "fi": "Haluaisitko mieluummin pysty\u00e4 puhumaan el\u00e4imille vai hallitsemaan s\u00e4\u00e4t\u00e4?", "nl": "Zou je liever met dieren kunnen praten of het weer kunnen beheersen?", "no": "Ville du heller kunne snakke med dyr eller kontrollere v\u00e6ret?", "sv": "Skulle du hellre kunna prata med djur eller kontrollera v\u00e4dret?", "pl": "Czy wola\u0142by\u015b m\u00f3c rozmawia\u0107 ze zwierz\u0119tami, czy kontrolowa\u0107 pogod\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather be able to talk to animals or control the weather?';
UPDATE questions
SET translations = '{"en": "Would you rather always wear mismatched shoes or wear your clothes backward for a year?", "da": "Ville du hellere altid have forskellige sko p\u00e5 eller have t\u00f8jet bagvendt i et \u00e5r?", "de": "W\u00fcrdest du lieber immer unterschiedliche Schuhe tragen oder deine Kleidung ein Jahr lang r\u00fcckw\u00e4rts?", "es": "\u00bfPreferir\u00edas usar zapatos diferentes siempre o la ropa al rev\u00e9s durante un a\u00f1o?", "pt": "Preferias usar sapatos trocados sempre ou a roupa ao contr\u00e1rio por um ano?", "ro": "Ai prefera s\u0103 por\u021bi mereu pantofi nepotrivi\u021bi sau hainele pe dos un an?", "fr": "Pr\u00e9f\u00e9rerais-tu toujours porter des chaussures d\u00e9pareill\u00e9es ou tes v\u00eatements \u00e0 l\u2019envers pendant un an ?", "it": "Preferiresti indossare sempre scarpe non abbinate o portare i vestiti al contrario per un anno?", "fi": "Haluaisitko mieluummin aina k\u00e4ytt\u00e4\u00e4 eriparisia kenki\u00e4 vai pit\u00e4\u00e4 vaatteesi v\u00e4\u00e4rinp\u00e4in vuoden ajan?", "nl": "Zou je liever altijd mismatched schoenen dragen of je kleren een jaar lang achterstevoren dragen?", "no": "Ville du heller alltid ha p\u00e5 deg sko som ikke passer sammen, eller ha kl\u00e6rne dine bak frem i ett \u00e5r?", "sv": "Skulle du hellre alltid ha p\u00e5 dig olika skor eller ha dina kl\u00e4der bak och fram i ett \u00e5r?", "pl": "Czy wola\u0142by\u015b zawsze nosi\u0107 niedopasowane buty, czy nosi\u0107 ubrania na lew\u0105 stron\u0119 przez rok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always wear mismatched shoes or wear your clothes backward for a year?';
UPDATE questions
SET translations = '{"en": "Would you rather have to sing everything you say or dance everywhere you go?", "da": "Ville du hellere synge alt, hvad du siger, eller danse overalt, hvor du g\u00e5r?", "de": "W\u00fcrdest du lieber alles singen, was du sagst, oder \u00fcberall tanzen, wo du hingehst?", "es": "\u00bfPreferir\u00edas cantar todo lo que dices o bailar en todos lados a donde vayas?", "pt": "Preferias cantar tudo o que dizes ou dan\u00e7ar por onde fores?", "ro": "Ai prefera s\u0103 c\u00e2n\u021bi tot ce spui sau s\u0103 dansezi peste tot unde mergi?", "fr": "Pr\u00e9f\u00e9rerais-tu chanter tout ce que tu dis ou danser partout o\u00f9 tu vas ?", "it": "Preferiresti dover cantare tutto ci\u00f2 che dici o ballare ovunque tu vada?", "fi": "Haluaisitko laulaa kaiken, mit\u00e4 sanot, vai tanssia joka paikassa, mihin menet?", "nl": "Zou je liever alles wat je zegt moeten zingen of overal waar je gaat moeten dansen?", "no": "Ville du heller m\u00e5tte synge alt du sier eller danse overalt du g\u00e5r?", "sv": "Skulle du hellre beh\u00f6va sjunga allt du s\u00e4ger eller dansa \u00f6verallt du g\u00e5r?", "pl": "Czy wola\u0142by\u015b \u015bpiewa\u0107 wszystko, co m\u00f3wisz, czy ta\u0144czy\u0107 wsz\u0119dzie, gdzie idziesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to sing everything you say or dance everywhere you go?';UPDATE questions
SET translations = '{"en": "Would you rather live in a house made of candy or a house made of pillows?", "da": "Ville du hellere bo i et hus lavet af slik eller et hus lavet af puder?", "de": "W\u00fcrdest du lieber in einem Haus aus S\u00fc\u00dfigkeiten oder in einem Haus aus Kissen leben?", "es": "\u00bfPreferir\u00edas vivir en una casa hecha de dulces o en una casa hecha de almohadas?", "pt": "Preferias viver numa casa feita de doces ou numa casa feita de almofadas?", "ro": "Ai prefera s\u0103 locuie\u0219ti \u00eentr-o cas\u0103 f\u0103cut\u0103 din dulciuri sau din perne?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre dans une maison faite de bonbons ou une maison faite d\u2019oreillers ?", "it": "Preferiresti vivere in una casa fatta di caramelle o in una casa fatta di cuscini?", "fi": "Haluaisitko mieluummin asua karkkitalossa vai tyynyjen talossa?", "nl": "Zou je liever in een huis van snoep wonen of in een huis van kussens?", "no": "Ville du heller bo i et hus laget av godteri eller et hus laget av puter?", "sv": "Skulle du hellre bo i ett hus gjort av godis eller ett hus gjort av kuddar?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 w domu zrobionym z cukierk\u00f3w, czy w domu zrobionym z poduszek?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live in a house made of candy or a house made of pillows?';
UPDATE questions
SET translations = '{"en": "Would you rather spend a whole weekend without screens or without snacks?", "da": "Ville du hellere tilbringe en hel weekend uden sk\u00e6rme eller uden snacks?", "de": "W\u00fcrdest du lieber ein ganzes Wochenende ohne Bildschirme oder ohne Snacks verbringen?", "es": "\u00bfPreferir\u00edas pasar un fin de semana entero sin pantallas o sin aperitivos?", "pt": "Preferias passar um fim de semana inteiro sem ecr\u00e3s ou sem snacks?", "ro": "Ai prefera s\u0103 petreci un weekend \u00eentreg f\u0103r\u0103 ecrane sau f\u0103r\u0103 gust\u0103ri?", "fr": "Pr\u00e9f\u00e9rerais-tu passer tout un week-end sans \u00e9crans ou sans collations ?", "it": "Preferiresti passare un intero fine settimana senza schermi o senza snack?", "fi": "Kumpi olisi sinulle mieluisampaa: viett\u00e4\u00e4 koko viikonloppu ilman n\u00e4ytt\u00f6j\u00e4 vai ilman v\u00e4lipaloja?", "nl": "Zou je liever een heel weekend zonder schermen doorbrengen of zonder snacks?", "no": "Ville du heller tilbringe en hel helg uten skjermer eller uten snacks?", "sv": "Skulle du hellre tillbringa en hel helg utan sk\u00e4rmar eller utan snacks?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 ca\u0142y weekend bez ekran\u00f3w czy bez przek\u0105sek?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend a whole weekend without screens or without snacks?';
UPDATE questions
SET translations = '{"en": "Would you rather only eat homemade meals or only restaurant food for a year?", "da": "Ville du hellere kun spise hjemmelavet mad eller kun restaurantmad i et \u00e5r?", "de": "W\u00fcrdest du lieber ein Jahr lang nur Hausmannskost oder nur Restaurantessen essen?", "es": "\u00bfPreferir\u00edas comer solo comida casera o solo comida de restaurante durante un a\u00f1o?", "pt": "Preferias comer apenas comida caseira ou apenas comida de restaurante durante um ano?", "ro": "Ai prefera s\u0103 m\u0103n\u00e2nci doar m\u00e2ncare g\u0103tit\u0103 acas\u0103 sau doar de la restaurant timp de un an?", "fr": "Pr\u00e9f\u00e9rerais-tu ne manger que des plats faits maison ou que des plats de restaurant pendant un an ?", "it": "Preferiresti mangiare solo pasti fatti in casa o solo cibo da ristorante per un anno?", "fi": "Haluaisitko sy\u00f6d\u00e4 vain kotitekoisia aterioita vai vain ravintolaruokaa vuoden ajan?", "nl": "Zou je liever een jaar lang alleen zelfgemaakte maaltijden eten of alleen restauranteten?", "no": "Ville du heller bare spise hjemmelagde m\u00e5ltider eller bare restaurantmat i ett \u00e5r?", "sv": "Skulle du hellre \u00e4ta endast hemlagade m\u00e5ltider eller endast restaurangmat i ett \u00e5r?", "pl": "Czy wola\u0142by\u015b je\u015b\u0107 tylko domowe posi\u0142ki, czy tylko jedzenie z restauracji przez rok?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather only eat homemade meals or only restaurant food for a year?';