UPDATE questions
SET translations = '{"en": "You can ask a spirit one yes/no question. What do you ask?", "da": "Du kan stille en \u00e5nd \u00e9t ja/nej-sp\u00f8rgsm\u00e5l. Hvad sp\u00f8rger du om?", "de": "Du darfst einem Geist eine Ja/Nein-Frage stellen. Was fragst du?", "es": "Puedes hacerle una pregunta de s\u00ed/no a un esp\u00edritu. \u00bfQu\u00e9 preguntas?", "pt": "Podes fazer uma pergunta de sim/n\u00e3o a um esp\u00edrito. O que perguntas?", "ro": "Po\u021bi pune unei spirite o \u00eentrebare la care r\u0103spunde doar \u201eda\u201d sau \u201enu\u201d. Ce \u00eentrebi?", "fr": "Tu peux poser une question par oui/non \u00e0 un esprit. Que demandes-tu ?", "it": "Puoi fare a uno spirito una sola domanda a cui si risponde s\u00ec/no. Cosa chiedi?", "fi": "Voit kysy\u00e4 hengelt\u00e4 yhden kyll\u00e4/ei -kysymyksen. Mit\u00e4 kysyt?", "nl": "Je mag \u00e9\u00e9n ja/nee-vraag aan een geest stellen. Wat vraag je?", "no": "Du kan stille en \u00e5nd ett ja/nei-sp\u00f8rsm\u00e5l. Hva sp\u00f8r du om?", "sv": "Du f\u00e5r st\u00e4lla en ja/nej-fr\u00e5ga till en ande. Vad fr\u00e5gar du?", "pl": "Mo\u017cesz zada\u0107 duchowi jedno pytanie z odpowiedzi\u0105 tak/nie. O co pytasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You can ask a spirit one yes/no question. What do you ask?';
UPDATE questions
SET translations = '{"en": "You find an AirTag/tracker alert on your phone after a night out. What do you do?", "da": "Du f\u00e5r en AirTag/Tracker-advarsel p\u00e5 din telefon efter en aften ude. Hvad g\u00f8r du?", "de": "Du erh\u00e4ltst nach einer Nacht drau\u00dfen eine AirTag/Tracker-Warnung auf deinem Handy. Was tust du?", "es": "Recibes una alerta de AirTag/rastreador en tu tel\u00e9fono despu\u00e9s de una noche fuera. \u00bfQu\u00e9 haces?", "pt": "Recebes um alerta de AirTag/rastreador no teu telem\u00f3vel depois de uma noite fora. O que fazes?", "ro": "Prime\u0219ti o alert\u0103 pe telefon despre un AirTag/tracker dup\u0103 o noapte \u00een ora\u0219. Ce faci?", "fr": "Tu re\u00e7ois une alerte AirTag/suivi sur ton t\u00e9l\u00e9phone apr\u00e8s une soir\u00e9e dehors. Que fais-tu ?", "it": "Trovi una notifica di AirTag/tracker sul telefono dopo una serata fuori. Cosa fai?", "fi": "Saat AirTag-/seurantalaitteen h\u00e4lytyksen puhelimeesi illanvieton j\u00e4lkeen. Mit\u00e4 teet?", "nl": "Je krijgt na een avond uit een AirTag-/tracker-melding op je telefoon. Wat doe je?", "no": "Du f\u00e5r varsel om en AirTag/tracker p\u00e5 telefonen etter en kveld ute. Hva gj\u00f8r du?", "sv": "Du f\u00e5r en AirTag-/tracker-varning p\u00e5 mobilen efter en utekv\u00e4ll. Vad g\u00f6r du?", "pl": "Po wieczornym wyj\u015bciu dostajesz na telefon powiadomienie o AirTagu/trackerze. Co robisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You find an AirTag/tracker alert on your phone after a night out. What do you do?';
UPDATE questions
SET translations = '{"en": "Rate your belief in ghosts, 0\u201310, and defend it.", "da": "Bed\u00f8m din tro p\u00e5 sp\u00f8gelser fra 0\u201310, og forsvar den.", "de": "Bewerte deinen Glauben an Geister von 0 bis 10 und verteidige ihn.", "es": "Califica tu creencia en fantasmas del 0 al 10 y defi\u00e9ndela.", "pt": "Avalia a tua cren\u00e7a em fantasmas de 0 a 10 e defende-a.", "ro": "Evalueaz\u0103-\u021bi credin\u021ba \u00een fantome de la 0 la 10 \u0219i ap\u0103r\u0103-\u021bi r\u0103spunsul.", "fr": "\u00c9value ta croyance aux fant\u00f4mes de 0 \u00e0 10 et d\u00e9fends-la.", "it": "Valuta quanto credi ai fantasmi da 0 a 10 e difendi il tuo voto.", "fi": "Arvioi uskosi kummituksiin asteikolla 0\u201310 ja perustele se.", "nl": "Geef je geloof in geesten een cijfer van 0\u201310 en verdedig het.", "no": "Ranger troen din p\u00e5 sp\u00f8kelser fra 0\u201310, og forklar.", "sv": "Betygs\u00e4tt din tro p\u00e5 sp\u00f6ken, 0\u201310, och f\u00f6rsvara betyget.", "pl": "Oce\u0144 swoj\u0105 wiar\u0119 w duchy w skali 0\u201310 i j\u0105 uzasadnij."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Rate your belief in ghosts, 0–10, and defend it.';
UPDATE questions
SET translations = '{"en": "A child in a store waves behind you and says \u201cbye.\u201d There\u2019s no one there. How do you react?", "da": "Et barn i en butik vinker bag dig og siger \u201chej hej\u201d. Der er ingen der. Hvad g\u00f8r du?", "de": "Ein Kind im Laden winkt dir hinterher und sagt \u201eTsch\u00fcss\u201c. Niemand ist da. Wie reagierst du?", "es": "Un ni\u00f1o en una tienda te saluda y dice \u201cadi\u00f3s\u201d. No hay nadie all\u00ed. \u00bfC\u00f3mo reaccionas?", "pt": "Uma crian\u00e7a numa loja acena-te e diz \u201ctchau\u201d. N\u00e3o h\u00e1 ningu\u00e9m. Como reages?", "ro": "Un copil \u00eentr-un magazin \u00ee\u021bi face cu m\u00e2na \u0219i spune \u201epa.\u201d Nu e nimeni acolo. Cum reac\u021bionezi?", "fr": "Un enfant dans un magasin te fait signe et dit \u00ab au revoir \u00bb. Il n\u2019y a personne. Comment r\u00e9agis-tu ?", "it": "Un bambino in un negozio saluta dietro di te e dice \"ciao\". Non c\u2019\u00e8 nessuno. Come reagisci?", "fi": "Lapsi kaupassa vilkuttaa selk\u00e4si takana ja sanoo \"hei hei\". Ket\u00e4\u00e4n ei n\u00e4y. Miten reagoit?", "nl": "Een kind in een winkel zwaait achter je en zegt \"doei\". Er is niemand. Hoe reageer je?", "no": "Et barn i en butikk vinker bak deg og sier \"ha det\". Det er ingen der. Hvordan reagerer du?", "sv": "Ett barn i en butik vinkar bakom dig och s\u00e4ger \"hej d\u00e5\". Det finns ingen d\u00e4r. Hur reagerar du?", "pl": "Dziecko w sklepie macha za twoimi plecami i m\u00f3wi \"pa\". Nikogo tam nie ma. Jak reagujesz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A child in a store waves behind you and says “bye.” There’s no one there. How do you react?';
UPDATE questions
SET translations = '{"en": "What childhood fear secretly still lives rent-free?", "da": "Hvilken barndomsfrygt bor stadig gratis i dit hoved?", "de": "Welche Kindheitsangst lebt immer noch mietfrei in deinem Kopf?", "es": "\u00bfQu\u00e9 miedo de la infancia sigue viviendo gratis en tu mente?", "pt": "Que medo de inf\u00e2ncia ainda vive de gra\u00e7a na tua mente?", "ro": "Ce fric\u0103 din copil\u0103rie \u00eenc\u0103 mai tr\u0103ie\u0219te \u00een tine \u201ecu chirie gratuit\u0103\u201d?", "fr": "Quelle peur d\u2019enfance vit encore gratuitement dans ta t\u00eate ?", "it": "Quale paura d\u2019infanzia vive ancora di nascosto nella tua testa?", "fi": "Mik\u00e4 lapsuuden pelko asuu salaa edelleen mieless\u00e4si?", "nl": "Welke kinderangst woont stiekem nog steeds in je hoofd?", "no": "Hvilken barndomsfrykt bor fortsatt i deg, i hemmelighet?", "sv": "Vilken barndomsr\u00e4dsla bor fortfarande gratis i ditt huvud?", "pl": "Kt\u00f3ry l\u0119k z dzieci\u0144stwa wci\u0105\u017c po cichu mieszka w twojej g\u0142owie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What childhood fear secretly still lives rent-free?';
UPDATE questions
SET translations = '{"en": "Create a spooky playlist title and its first three tracks.", "da": "Lav en uhyggelig playliste-titel og dens f\u00f8rste tre numre.", "de": "Erstelle einen gruseligen Playlist-Titel und die ersten drei Songs.", "es": "Crea un t\u00edtulo de lista espeluznante y sus tres primeras canciones.", "pt": "Cria um t\u00edtulo assustador de playlist e as suas tr\u00eas primeiras faixas.", "ro": "Creeaz\u0103 un titlu de playlist \u00eenfrico\u0219\u0103tor \u0219i primele trei melodii.", "fr": "Cr\u00e9e une playlist effrayante et donne-lui ses trois premiers morceaux.", "it": "Crea un titolo inquietante per una playlist e i suoi primi tre brani.", "fi": "Keksi karmiva soittolistan nimi ja sen kolme ensimm\u00e4ist\u00e4 kappaletta.", "nl": "Bedenk een griezelige playlist-titel en de eerste drie nummers.", "no": "Lag en skummel spilleliste-tittel og de tre f\u00f8rste l\u00e5tene.", "sv": "Hitta p\u00e5 en l\u00e4skig spellisttitel och dess tre f\u00f6rsta l\u00e5tar.", "pl": "Wymy\u015bl straszny tytu\u0142 playlisty i jej trzy pierwsze utwory."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Create a spooky playlist title and its first three tracks.';
UPDATE questions
SET translations = '{"en": "A neighbor says your lights flicker every night at the same minute. You weren\u2019t home. Thoughts?", "da": "En nabo siger, at dine lys blinker hver nat p\u00e5 samme tidspunkt. Du var ikke hjemme. Tanker?", "de": "Ein Nachbar sagt, deine Lichter flackern jede Nacht zur selben Minute. Du warst nicht zu Hause. Gedanken?", "es": "Un vecino dice que tus luces parpadean cada noche a la misma hora. No estabas en casa. \u00bfPensamientos?", "pt": "Um vizinho diz que as tuas luzes piscam todas as noites \u00e0 mesma hora. N\u00e3o estavas em casa. Pensamentos?", "ro": "Un vecin spune c\u0103 luminile tale p\u00e2lp\u00e2ie \u00een fiecare noapte la aceea\u0219i or\u0103. Tu nu erai acas\u0103. Ce crezi?", "fr": "Un voisin dit que tes lumi\u00e8res clignotent chaque nuit \u00e0 la m\u00eame heure. Tu n\u2019\u00e9tais pas chez toi. Des pens\u00e9es ?", "it": "Un vicino dice che le tue luci sfarfallano ogni notte alla stessa ora. Tu non eri a casa. Pensieri?", "fi": "Naapuri sanoo, ett\u00e4 valosi vilkkuvat joka ilta samaan aikaan. Et ollut kotona. Mit\u00e4 ajattelet?", "nl": "Een buur zegt dat je lampen elke nacht op hetzelfde moment flikkeren. Jij was niet thuis. Mening?", "no": "En nabo sier at lysene dine blinker hver natt p\u00e5 samme minutt. Du var ikke hjemme. Tanker?", "sv": "En granne s\u00e4ger att dina lampor blinkar varje natt p\u00e5 samma minut. Du var inte hemma. Tankar?", "pl": "S\u0105siad m\u00f3wi, \u017ce twoje \u015bwiat\u0142a migaj\u0105 co noc o tej samej minucie. Nie by\u0142o ci\u0119 w domu. Co o tym my\u015blisz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A neighbor says your lights flicker every night at the same minute. You weren’t home. Thoughts?';
UPDATE questions
SET translations = '{"en": "Most unsettling piece of trivia you know?", "da": "Hvilken foruroligende fakta ved du?", "de": "Welches beunruhigende Wissen kennst du?", "es": "\u00bfQu\u00e9 dato inquietante conoces?", "pt": "Qual \u00e9 o facto mais perturbador que conheces?", "ro": "Care este cea mai tulbur\u0103toare informa\u021bie pe care o \u0219tii?", "fr": "Quelle information troublante connais-tu ?", "it": "Qual \u00e8 il fatto curioso pi\u00f9 inquietante che conosci?", "fi": "Mik\u00e4 on ahdistavin nippelitieto, jonka tied\u00e4t?", "nl": "Wat is het meest verontrustende weetje dat je kent?", "no": "Hva er den mest urovekkende fun facten du kjenner til?", "sv": "Vilken \u00e4r den mest obehagliga fakta du k\u00e4nner till?", "pl": "Jaka jest najbardziej niepokoj\u0105ca ciekawostka, jak\u0105 znasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Most unsettling piece of trivia you know?';
UPDATE questions
SET translations = '{"en": "If mirrors recorded one minute a day, which minute would you replay?", "da": "Hvis spejle optog \u00e9t minut om dagen, hvilket minut ville du gense?", "de": "Wenn Spiegel eine Minute pro Tag aufzeichnen w\u00fcrden, welche Minute w\u00fcrdest du wieder abspielen?", "es": "Si los espejos grabaran un minuto al d\u00eda, \u00bfqu\u00e9 minuto volver\u00edas a ver?", "pt": "Se os espelhos gravassem um minuto por dia, qual voltarias a ver?", "ro": "Dac\u0103 oglinzile ar \u00eenregistra un minut pe zi, ce minut ai revedea?", "fr": "Si les miroirs enregistraient une minute par jour, laquelle rejouerais-tu ?", "it": "Se gli specchi registrassero un minuto al giorno, quale minuto vorresti rivedere?", "fi": "Jos peilit tallentaisivat yhden minuutin p\u00e4iv\u00e4ss\u00e4, mink\u00e4 minuutin haluaisit katsoa uudelleen?", "nl": "Als spiegels \u00e9\u00e9n minuut per dag zouden opnemen, welke minuut zou jij terugkijken?", "no": "Hvis speil tok opp ett minutt om dagen, hvilket minutt ville du spolt tilbake til?", "sv": "Om speglar spelade in en minut om dagen, vilken minut skulle du spela upp igen?", "pl": "Gdyby lustra nagrywa\u0142y jedn\u0105 minut\u0119 dziennie, kt\u00f3r\u0105 minut\u0119 chcia\u0142(a)by\u015b odtworzy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'If mirrors recorded one minute a day, which minute would you replay?';
UPDATE questions
SET translations = '{"en": "A stranger knows your name and favorite snack. Explain it rationally.", "da": "En fremmed kender dit navn og din yndlingssnack. Forklar det rationelt.", "de": "Ein Fremder kennt deinen Namen und deinen Lieblingssnack. Erkl\u00e4re es rational.", "es": "Un desconocido sabe tu nombre y tu aperitivo favorito. Expl\u00edcalo racionalmente.", "pt": "Um estranho sabe o teu nome e o teu lanche favorito. Explica racionalmente.", "ro": "Un str\u0103in \u00ee\u021bi \u0219tie numele \u0219i gustarea preferat\u0103. Explic\u0103 logic.", "fr": "Un inconnu conna\u00eet ton nom et ton encas pr\u00e9f\u00e9r\u00e9. Explique rationnellement.", "it": "Uno sconosciuto conosce il tuo nome e il tuo snack preferito. Spiegalo in modo razionale.", "fi": "Tuntematon tiet\u00e4\u00e4 nimesi ja lempiev\u00e4\u00e4si. Selit\u00e4 t\u00e4m\u00e4 j\u00e4rkev\u00e4sti.", "nl": "Een onbekende kent je naam en je favoriete snack. Verklaar het op een rationele manier.", "no": "En fremmed vet navnet ditt og favorittsnacken din. Forklar det p\u00e5 en rasjonell m\u00e5te.", "sv": "En fr\u00e4mling kan ditt namn och ditt favoritsnack. F\u00f6rklara det rationellt.", "pl": "Obca osoba zna twoje imi\u0119 i ulubion\u0105 przek\u0105sk\u0119. Wyja\u015bnij to racjonalnie."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A stranger knows your name and favorite snack. Explain it rationally.';