UPDATE questions
SET translations = '{"en": "Would you rather live without music or live without TV?", "da": "Ville du hellere leve uden musik eller uden tv?", "de": "W\u00fcrdest du lieber ohne Musik oder ohne Fernsehen leben?", "es": "\u00bfPreferir\u00edas vivir sin m\u00fasica o sin televisi\u00f3n?", "pt": "Preferias viver sem m\u00fasica ou sem televis\u00e3o?", "ro": "Ai prefera s\u0103 tr\u0103ie\u0219ti f\u0103r\u0103 muzic\u0103 sau f\u0103r\u0103 televizor?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre sans musique ou sans t\u00e9l\u00e9vision ?", "it": "Preferiresti vivere senza musica o vivere senza televisione?", "fi": "Elisitk\u00f6 mieluummin ilman musiikkia vai ilman televisiota?", "nl": "Zou je liever zonder muziek leven of zonder tv?", "no": "Ville du heller levd uten musikk eller uten TV?", "sv": "Skulle du hellre leva utan musik eller leva utan TV?", "pl": "Czy wola\u0142by\u015b \u017cy\u0107 bez muzyki, czy bez telewizji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live without music or live without TV?';
UPDATE questions
SET translations = '{"en": "Would you rather spend a year without coffee or a year without chocolate?", "da": "Ville du hellere undv\u00e6re kaffe i et \u00e5r eller chokolade i et \u00e5r?", "de": "W\u00fcrdest du lieber ein Jahr ohne Kaffee oder ein Jahr ohne Schokolade leben?", "es": "\u00bfPreferir\u00edas pasar un a\u00f1o sin caf\u00e9 o un a\u00f1o sin chocolate?", "pt": "Preferias passar um ano sem caf\u00e9 ou um ano sem chocolate?", "ro": "Ai prefera un an f\u0103r\u0103 cafea sau un an f\u0103r\u0103 ciocolat\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu passer un an sans caf\u00e9 ou un an sans chocolat ?", "it": "Preferiresti passare un anno senza caff\u00e8 o un anno senza cioccolato?", "fi": "Valitsisitko mieluummin viett\u00e4\u00e4 vuoden ilman kahvia vai vuoden ilman suklaata?", "nl": "Zou je liever een jaar zonder koffie of een jaar zonder chocolade doorbrengen?", "no": "Ville du heller tilbringe et \u00e5r uten kaffe eller et \u00e5r uten sjokolade?", "sv": "Skulle du hellre spendera ett \u00e5r utan kaffe eller ett \u00e5r utan choklad?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 rok bez kawy czy rok bez czekolady?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend a year without coffee or a year without chocolate?';
UPDATE questions
SET translations = '{"en": "Would you rather always hit every green light or never have to fold laundry again?", "da": "Ville du hellere altid ramme gr\u00f8nt lys eller aldrig folde vasket\u00f8j igen?", "de": "W\u00fcrdest du lieber immer jede gr\u00fcne Ampel erwischen oder nie wieder W\u00e4sche falten?", "es": "\u00bfPreferir\u00edas atrapar siempre el sem\u00e1foro en verde o no volver a doblar la ropa nunca m\u00e1s?", "pt": "Preferias apanhar sempre todos os sinais verdes ou nunca mais dobrar roupa?", "ro": "Ai prefera s\u0103 prinzi mereu verde la semafor sau s\u0103 nu mai \u00eemp\u0103ture\u0219ti rufe niciodat\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu attraper tous les feux verts ou ne plus jamais plier le linge ?", "it": "Preferiresti colpire sempre ogni semaforo verde o non dover mai pi\u00f9 piegare il bucato?", "fi": "Haluaisitko mieluummin aina osua jokaiseen vihre\u00e4\u00e4n valoon vai ettei sinun koskaan en\u00e4\u00e4 tarvitsisi taittaa pyykki\u00e4?", "nl": "Zou je liever altijd elke groene licht krijgen of nooit meer de was hoeven op te vouwen?", "no": "Ville du heller alltid treffe p\u00e5 gr\u00f8nt lys eller aldri m\u00e5tte brette kl\u00e6r igjen?", "sv": "Skulle du hellre alltid f\u00e5 gr\u00f6nt ljus eller aldrig beh\u00f6va vika tv\u00e4tt igen?", "pl": "Czy wola\u0142by\u015b zawsze trafia\u0107 na zielone \u015bwiat\u0142a, czy nigdy wi\u0119cej nie musie\u0107 sk\u0142ada\u0107 prania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always hit every green light or never have to fold laundry again?';
UPDATE questions
SET translations = '{"en": "Would you rather have to cook every meal or do all the cleaning?", "da": "Ville du hellere lave al maden eller al reng\u00f8ringen?", "de": "W\u00fcrdest du lieber jedes Essen kochen oder die ganze Reinigung machen?", "es": "\u00bfPreferir\u00edas cocinar todas las comidas o hacer toda la limpieza?", "pt": "Preferias cozinhar todas as refei\u00e7\u00f5es ou fazer toda a limpeza?", "ro": "Ai prefera s\u0103 g\u0103te\u0219ti toate mesele sau s\u0103 faci toat\u0103 cur\u0103\u021benia?", "fr": "Pr\u00e9f\u00e9rerais-tu cuisiner tous les repas ou faire tout le m\u00e9nage ?", "it": "Preferiresti dover cucinare ogni pasto o fare tutte le pulizie?", "fi": "Haluaisitko mieluummin kokata jokaisen aterian vai tehd\u00e4 kaikki siivoukset?", "nl": "Zou je liever elke maaltijd moeten koken of al het schoonmaken doen?", "no": "Ville du heller m\u00e5tte lage hver eneste m\u00e5ltid eller gj\u00f8re all rengj\u00f8ringen?", "sv": "Skulle du hellre laga varje m\u00e5ltid eller g\u00f6ra all st\u00e4dning?", "pl": "Czy wola\u0142by\u015b gotowa\u0107 ka\u017cde posi\u0142ek, czy zajmowa\u0107 si\u0119 ca\u0142ym sprz\u0105taniem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have to cook every meal or do all the cleaning?';
UPDATE questions
SET translations = '{"en": "Would you rather spend your money on experiences or on nice things?", "da": "Ville du hellere bruge dine penge p\u00e5 oplevelser eller p\u00e5 p\u00e6ne ting?", "de": "W\u00fcrdest du lieber dein Geld f\u00fcr Erlebnisse oder f\u00fcr sch\u00f6ne Dinge ausgeben?", "es": "\u00bfPreferir\u00edas gastar tu dinero en experiencias o en cosas bonitas?", "pt": "Preferias gastar o teu dinheiro em experi\u00eancias ou em coisas bonitas?", "ro": "Ai prefera s\u0103-\u021bi cheltuie\u0219ti banii pe experien\u021be sau pe lucruri frumoase?", "fr": "Pr\u00e9f\u00e9rerais-tu d\u00e9penser ton argent pour des exp\u00e9riences ou pour de belles choses ?", "it": "Preferiresti spendere i tuoi soldi per esperienze o per cose belle?", "fi": "Haluaisitko k\u00e4ytt\u00e4\u00e4 rahasi el\u00e4myksiin vai kauniisiin asioihin?", "nl": "Zou je liever je geld uitgeven aan ervaringen of aan mooie spullen?", "no": "Ville du heller bruke pengene dine p\u00e5 opplevelser eller p\u00e5 fine ting?", "sv": "Skulle du hellre spendera dina pengar p\u00e5 upplevelser eller p\u00e5 fina saker?", "pl": "Czy wola\u0142by\u015b wydawa\u0107 pieni\u0105dze na do\u015bwiadczenia, czy na \u0142adne rzeczy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend your money on experiences or on nice things?';
UPDATE questions
SET translations = '{"en": "Would you rather live somewhere it\u2019s always warm or where there are all four seasons?", "da": "Ville du hellere bo et sted, hvor der altid er varmt, eller hvor der er fire \u00e5rstider?", "de": "W\u00fcrdest du lieber dort leben, wo es immer warm ist, oder wo es vier Jahreszeiten gibt?", "es": "\u00bfPreferir\u00edas vivir en un lugar donde siempre haga calor o donde haya cuatro estaciones?", "pt": "Preferias viver onde est\u00e1 sempre calor ou onde h\u00e1 quatro esta\u00e7\u00f5es?", "ro": "Ai prefera s\u0103 locuie\u0219ti unde e mereu cald sau unde sunt toate cele patru anotimpuri?", "fr": "Pr\u00e9f\u00e9rerais-tu vivre l\u00e0 o\u00f9 il fait toujours chaud ou l\u00e0 o\u00f9 il y a les quatre saisons ?", "it": "Preferiresti vivere in un posto dove fa sempre caldo o in un luogo con tutte e quattro le stagioni?", "fi": "Haluaisitko mieluummin asua paikassa, jossa on aina l\u00e4mmin, vai sellaisessa, jossa on kaikki nelj\u00e4 vuodenaikaa?", "nl": "Zou je liever ergens wonen waar het altijd warm is of waar alle vier seizoenen zijn?", "no": "Ville du heller bo et sted hvor det alltid er varmt, eller et sted med alle fire \u00e5rstider?", "sv": "Skulle du hellre bo n\u00e5gonstans d\u00e4r det alltid \u00e4r varmt eller d\u00e4r det finns alla fyra \u00e5rstider?", "pl": "Czy wola\u0142by\u015b mieszka\u0107 w miejscu, gdzie jest zawsze ciep\u0142o, czy tam, gdzie s\u0105 wszystkie cztery pory roku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather live somewhere it’s always warm or where there are all four seasons?';
UPDATE questions
SET translations = '{"en": "Would you rather go one month without internet or one month without your favorite food?", "da": "Ville du hellere undv\u00e6re internettet i en m\u00e5ned eller din livret mad i en m\u00e5ned?", "de": "W\u00fcrdest du lieber einen Monat ohne Internet oder einen Monat ohne dein Lieblingsessen leben?", "es": "\u00bfPreferir\u00edas pasar un mes sin internet o un mes sin tu comida favorita?", "pt": "Preferias passar um m\u00eas sem internet ou sem a tua comida favorita?", "ro": "Ai prefera o lun\u0103 f\u0103r\u0103 internet sau f\u0103r\u0103 m\u00e2ncarea ta preferat\u0103?", "fr": "Pr\u00e9f\u00e9rerais-tu passer un mois sans internet ou un mois sans ton plat pr\u00e9f\u00e9r\u00e9 ?", "it": "Preferiresti trascorrere un mese senza internet o un mese senza il tuo cibo preferito?", "fi": "Kumpi olisi sinulle helpompaa: olla kuukausi ilman internetti\u00e4 vai kuukausi ilman lempiruokaasi?", "nl": "Zou je liever een maand zonder internet gaan of een maand zonder je favoriete eten?", "no": "Ville du heller g\u00e5tt en m\u00e5ned uten internett eller en m\u00e5ned uten din favorittmat?", "sv": "Skulle du hellre vara utan internet i en m\u00e5nad eller utan din favoritmat i en m\u00e5nad?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 miesi\u0105c bez internetu czy miesi\u0105c bez swojego ulubionego jedzenia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather go one month without internet or one month without your favorite food?';
UPDATE questions
SET translations = '{"en": "Would you rather always have to sing \u201cHappy Birthday\u201d when you enter a room or always wear a party hat?", "da": "Ville du hellere altid synge \u201cHappy Birthday\u201d, n\u00e5r du g\u00e5r ind i et rum, eller altid b\u00e6re en festhat?", "de": "W\u00fcrdest du lieber jedes Mal \u201eHappy Birthday\u201c singen, wenn du einen Raum betrittst, oder immer eine Partyhut tragen?", "es": "\u00bfPreferir\u00edas tener que cantar \u201cFeliz cumplea\u00f1os\u201d cada vez que entras a una habitaci\u00f3n o usar siempre un gorro de fiesta?", "pt": "Preferias cantar \u201cParab\u00e9ns a Voc\u00ea\u201d sempre que entras numa sala ou usar sempre um chap\u00e9u de festa?", "ro": "Ai prefera s\u0103 c\u00e2n\u021bi \u201cLa mul\u021bi ani\u201d ori de c\u00e2te ori intri \u00eentr-o camer\u0103 sau s\u0103 por\u021bi mereu o p\u0103l\u0103rie de petrecere?", "fr": "Pr\u00e9f\u00e9rerais-tu devoir chanter \u201cJoyeux anniversaire\u201d chaque fois que tu entres dans une pi\u00e8ce ou toujours porter un chapeau de f\u00eate ?", "it": "Preferiresti dover sempre cantare \"Tanti Auguri\" quando entri in una stanza o dover sempre indossare un cappello da festa?", "fi": "Haluaisitko mieluummin laulaa aina \"Paljon onnea vaan\" astuessasi huoneeseen vai pit\u00e4\u00e4 aina juhlap\u00e4\u00e4hinett\u00e4?", "nl": "Zou je liever altijd \"Happy Birthday\" moeten zingen wanneer je een kamer binnenkomt of altijd een feesthoed dragen?", "no": "Ville du heller alltid m\u00e5tte synge \"Gratulerer med dagen\" n\u00e5r du g\u00e5r inn i et rom, eller alltid ha p\u00e5 deg en festhatt?", "sv": "Skulle du hellre alltid beh\u00f6va sjunga \"Ja m\u00e5 han leva\" n\u00e4r du g\u00e5r in i ett rum eller alltid b\u00e4ra en partyhatt?", "pl": "Czy wola\u0142by\u015b zawsze \u015bpiewa\u0107 \"Sto lat\", gdy wchodzisz do pokoju, czy zawsze nosi\u0107 czapk\u0119 urodzinow\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather always have to sing “Happy Birthday” when you enter a room or always wear a party hat?';
UPDATE questions
SET translations = '{"en": "Would you rather have a personal chef or a personal driver?", "da": "Ville du hellere have en personlig kok eller en personlig chauff\u00f8r?", "de": "W\u00e4rst du lieber mit einem pers\u00f6nlichen Koch oder einem pers\u00f6nlichen Fahrer ausgestattet?", "es": "\u00bfPreferir\u00edas tener un chef personal o un chofer personal?", "pt": "Preferias ter um chef pessoal ou um motorista pessoal?", "ro": "Ai prefera s\u0103 ai un buc\u0103tar personal sau un \u0219ofer personal?", "fr": "Pr\u00e9f\u00e9rerais-tu avoir un chef personnel ou un chauffeur personnel ?", "it": "Preferiresti avere un cuoco personale o un autista personale?", "fi": "Haluaisitko mieluummin henkil\u00f6kohtaisen kokin vai henkil\u00f6kohtaisen kuljettajan?", "nl": "Zou je liever een persoonlijke chef hebben of een persoonlijke chauffeur?", "no": "Ville du heller hatt en personlig kokk eller en personlig sj\u00e5f\u00f8r?", "sv": "Skulle du hellre ha en personlig kock eller en personlig chauff\u00f6r?", "pl": "Czy wola\u0142by\u015b mie\u0107 osobistego kucharza czy osobistego kierowc\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather have a personal chef or a personal driver?';
UPDATE questions
SET translations = '{"en": "Would you rather spend a day with no responsibilities or get an extra $200?", "da": "Ville du hellere have en dag uden ansvar eller f\u00e5 200 dollars ekstra?", "de": "W\u00fcrdest du lieber einen Tag ohne Verantwortung oder 200 Dollar extra haben?", "es": "\u00bfPreferir\u00edas tener un d\u00eda sin responsabilidades o ganar 200 d\u00f3lares extra?", "pt": "Preferias ter um dia sem responsabilidades ou ganhar 200 d\u00f3lares extra?", "ro": "Ai prefera o zi f\u0103r\u0103 responsabilit\u0103\u021bi sau 200 de dolari \u00een plus?", "fr": "Pr\u00e9f\u00e9rerais-tu passer une journ\u00e9e sans responsabilit\u00e9s ou gagner 200 \u20ac de plus ?", "it": "Preferiresti trascorrere una giornata senza responsabilit\u00e0 o ricevere 200 dollari in pi\u00f9?", "fi": "Haluaisitko mieluummin viett\u00e4\u00e4 p\u00e4iv\u00e4n ilman vastuuta vai saada ylim\u00e4\u00e4r\u00e4iset 200 dollaria?", "nl": "Zou je liever een dag zonder verantwoordelijkheden doorbrengen of een extra $200 krijgen?", "no": "Ville du heller tilbringe en dag uten ansvar eller f\u00e5 200 dollar ekstra?", "sv": "Skulle du hellre spendera en dag utan ansvar eller f\u00e5 200 dollar extra?", "pl": "Czy wola\u0142by\u015b sp\u0119dzi\u0107 dzie\u0144 bez \u017cadnych obowi\u0105zk\u00f3w, czy dosta\u0107 dodatkowe 200 dolar\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Would You Rather Talks'
  AND translations->>'en' = 'Would you rather spend a day with no responsibilities or get an extra $200?';