UPDATE questions
SET translations = '{"en": "When it comes to chores or responsibilities, what do you naturally take on \u2014 and what do you secretly wish I\u2019d help with more?", "da": "N\u00e5r det g\u00e6lder pligter eller ansvar, hvad tager du naturligt p\u00e5 dig \u2013 og hvad ville du \u00f8nske, jeg hjalp mere med?", "de": "Wenn es um Pflichten oder Verantwortung geht, was \u00fcbernimmst du nat\u00fcrlich \u2013 und wobei w\u00fcnschst du dir, dass ich mehr helfe?", "es": "Cuando se trata de tareas o responsabilidades, \u00bfqu\u00e9 sueles asumir t\u00fa y con qu\u00e9 desear\u00edas que te ayudara m\u00e1s?", "pt": "Quando se trata de tarefas ou responsabilidades, o que assumes naturalmente \u2014 e com o que gostarias que eu ajudasse mais?", "ro": "C\u00e2nd vine vorba de treburi sau responsabilit\u0103\u021bi, ce preiei tu \u00een mod natural \u2014 \u0219i cu ce \u021bi-ai dori s\u0103 te ajut mai mult?", "fr": "Quand il s\u2019agit de t\u00e2ches ou de responsabilit\u00e9s, que prends-tu naturellement en charge \u2014 et avec quoi aimerais-tu que je t\u2019aide davantage ?", "it": "Quando si tratta di faccende o responsabilit\u00e0, cosa ti prendi naturalmente in carico \u2014 e con cosa desideri segretamente che io ti aiuti di pi\u00f9?", "fi": "Kun on kyse kotit\u00f6ist\u00e4 tai vastuista, mit\u00e4 otat luonnostaan hoitaaksesi \u2014 ja mihin toivoisit salaa, ett\u00e4 auttaisin enemm\u00e4n?", "nl": "Als het gaat om huishoudelijke taken of verantwoordelijkheden, wat neem je van nature op je \u2014 en waar zou je stiekem willen dat ik je meer mee help?", "no": "N\u00e5r det gjelder husarbeid eller ansvar, hva tar du naturlig p\u00e5 deg \u2014 og hva \u00f8nsker du hemmelig at jeg skulle hjelpe mer med?", "sv": "N\u00e4r det kommer till sysslor eller ansvar, vad tar du naturligt p\u00e5 dig \u2014 och vad \u00f6nskar du i hemlighet att jag skulle hj\u00e4lpa till med mer?", "pl": "Kiedy mowa o obowi\u0105zkach domowych lub odpowiedzialno\u015bciach, co zazwyczaj bierzesz na siebie \u2014 a co w tajemnicy chcia\u0142by\u015b, \u017cebym bardziej ci w tym pom\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When it comes to chores or responsibilities, what do you naturally take on — and what do you secretly wish I’d help with more?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing I could do this week that would make you feel loved?", "da": "Hvad er \u00e9n ting, jeg kunne g\u00f8re denne uge, som ville f\u00e5 dig til at f\u00f8le dig elsket?", "de": "Was ist eine Sache, die ich diese Woche tun k\u00f6nnte, damit du dich geliebt f\u00fchlst?", "es": "\u00bfQu\u00e9 podr\u00eda hacer esta semana que te har\u00eda sentir amado/a?", "pt": "O que eu poderia fazer esta semana que te fizesse sentir amado(a)?", "ro": "Care e un lucru pe care l-a\u0219 putea face s\u0103pt\u0103m\u00e2na asta ca s\u0103 te sim\u021bi iubit(\u0103)?", "fr": "Quelle est une chose que je pourrais faire cette semaine pour que tu te sentes aim\u00e9(e) ?", "it": "Qual \u00e8 una cosa che potrei fare questa settimana che ti farebbe sentire amato?", "fi": "Mik\u00e4 on yksi asia, jonka voisin tehd\u00e4 t\u00e4ll\u00e4 viikolla, jotta tuntisit itsesi rakastetuksi?", "nl": "Wat is \u00e9\u00e9n ding dat ik deze week kan doen waardoor je je geliefd voelt?", "no": "Hva er \u00e9n ting jeg kan gj\u00f8re denne uken som ville f\u00e5tt deg til \u00e5 f\u00f8le deg elsket?", "sv": "Vad \u00e4r en sak jag skulle kunna g\u00f6ra den h\u00e4r veckan som skulle f\u00e5 dig att k\u00e4nna dig \u00e4lskad?", "pl": "Co\u015b, co m\u00f3g\u0142by\u015b zrobi\u0107 w tym tygodniu, co sprawi\u0142oby, \u017ce poczu\u0142bym si\u0119 kochany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one thing I could do this week that would make you feel loved?';
UPDATE questions
SET translations = '{"en": "Did you grow up seeing one person do most of the housework or planning? How do you think that shaped what you expect in us?", "da": "S\u00e5 du som barn \u00e9n person tage sig af det meste husarbejde eller planl\u00e6gning? Hvordan tror du, det har formet dine forventninger til os?", "de": "Bist du aufgewachsen, indem du gesehen hast, dass eine Person den Gro\u00dfteil der Hausarbeit oder Planung gemacht hat? Wie hat das deiner Meinung nach beeinflusst, was du von uns erwartest?", "es": "\u00bfCreciste viendo a una persona hacer la mayor parte de las tareas o la planificaci\u00f3n? \u00bfC\u00f3mo crees que eso influy\u00f3 en lo que esperas de nosotros?", "pt": "Cresceste a ver uma pessoa fazer a maior parte das tarefas dom\u00e9sticas ou do planeamento? Como achas que isso moldou o que esperas de n\u00f3s?", "ro": "Ai crescut v\u0103z\u00e2nd o persoan\u0103 f\u0103c\u00e2nd cea mai mare parte din treburile casei sau planificare? Cum crezi c\u0103 asta \u021bi-a influen\u021bat a\u0219tept\u0103rile fa\u021b\u0103 de noi?", "fr": "As-tu grandi en voyant une seule personne faire la plupart des t\u00e2ches m\u00e9nag\u00e8res ou de la planification ? Comment penses-tu que cela a influenc\u00e9 ce que tu attends de nous ?", "it": "Sei cresciuto vedendo una persona fare la maggior parte dei lavori domestici o della pianificazione? Come pensi che questo abbia influenzato le tue aspettative nei nostri confronti?", "fi": "Kasvoitko niin, ett\u00e4 yksi henkil\u00f6 teki suurimman osan kotit\u00f6ist\u00e4 tai suunnittelusta? Miten luulet sen muovanneen odotuksiasi meist\u00e4?", "nl": "Ben je opgegroeid met het zien van \u00e9\u00e9n persoon die het meeste van het huishoudelijke werk of de planning deed? Hoe denk je dat dat heeft gevormd wat je van ons verwacht?", "no": "Vokste du opp med \u00e5 se \u00e9n person gj\u00f8re mesteparten av husarbeidet eller planleggingen? Hvordan tror du det har formet hva du forventer av oss?", "sv": "V\u00e4xte du upp med att se en person g\u00f6ra det mesta av hush\u00e5llsarbetet eller planeringen? Hur tror du att det har format vad du f\u00f6rv\u00e4ntar dig av oss?", "pl": "Czy dorasta\u0142e\u015b, widz\u0105c, \u017ce jedna osoba wykonuje wi\u0119kszo\u015b\u0107 prac domowych lub planowania? Jak my\u015blisz, jak to wp\u0142yn\u0119\u0142o na to, czego oczekujesz od nas?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Did you grow up seeing one person do most of the housework or planning? How do you think that shaped what you expect in us?';
UPDATE questions
SET translations = '{"en": "How do you like me to show up when you\u2019re overwhelmed \u2014 jump in and help, or give you space first?", "da": "Hvordan vil du have, jeg reagerer, n\u00e5r du er overv\u00e6ldet \u2013 skal jeg springe ind og hj\u00e6lpe, eller give dig plads f\u00f8rst?", "de": "Wie m\u00f6chtest du, dass ich reagiere, wenn du \u00fcberfordert bist \u2013 soll ich einspringen und helfen oder dir zuerst Raum geben?", "es": "\u00bfC\u00f3mo te gusta que act\u00fae cuando est\u00e1s abrumado/a \u2014 que intervenga y ayude, o que te d\u00e9 espacio primero?", "pt": "Como queres que eu aja quando est\u00e1s sobrecarregado(a) \u2014 ajudar de imediato ou dar-te espa\u00e7o primeiro?", "ro": "Cum vrei s\u0103 reac\u021bionez c\u00e2nd e\u0219ti cople\u0219it(\u0103) \u2014 s\u0103 sar s\u0103 te ajut sau s\u0103-\u021bi dau spa\u021biu mai \u00eent\u00e2i?", "fr": "Comment veux-tu que j\u2019agisse quand tu es d\u00e9pass\u00e9(e) \u2014 que j\u2019intervienne pour aider ou que je te laisse d\u2019abord de l\u2019espace ?", "it": "Come preferisci che io mi comporti quando sei sopraffatto \u2014 intervenire e aiutarti, o darti prima dello spazio?", "fi": "Miten haluaisit, ett\u00e4 ilmestyn paikalle, kun olet ylivoimainen \u2014 hypp\u00e4\u00e4n mukaan auttamaan vai annan ensin tilaa?", "nl": "Hoe wil je dat ik reageer als je overweldigd bent \u2014 meteen helpen of eerst wat ruimte geven?", "no": "Hvordan vil du at jeg skal v\u00e6re der for deg n\u00e5r du f\u00f8ler deg overveldet \u2014 skal jeg hoppe inn og hjelpe, eller gi deg litt plass f\u00f8rst?", "sv": "Hur vill du att jag ska agera n\u00e4r du k\u00e4nner dig \u00f6verv\u00e4ldigad \u2014 hoppa in och hj\u00e4lpa till, eller ge dig utrymme f\u00f6rst?", "pl": "Jak wolisz, \u017cebym si\u0119 zachowa\u0142, gdy jeste\u015b przyt\u0142oczony \u2014 wskoczy\u0107 i pom\u00f3c, czy najpierw da\u0107 ci przestrze\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you like me to show up when you’re overwhelmed — jump in and help, or give you space first?';
UPDATE questions
SET translations = '{"en": "What kind of help means the most when you\u2019re stressed?", "da": "Hvilken slags hj\u00e6lp betyder mest for dig, n\u00e5r du er stresset?", "de": "Welche Art von Hilfe bedeutet dir am meisten, wenn du gestresst bist?", "es": "\u00bfQu\u00e9 tipo de ayuda significa m\u00e1s para ti cuando est\u00e1s estresado/a?", "pt": "Que tipo de ajuda significa mais para ti quando est\u00e1s stressado(a)?", "ro": "Ce fel de ajutor conteaz\u0103 cel mai mult pentru tine c\u00e2nd e\u0219ti stresat(\u0103)?", "fr": "Quel type d\u2019aide compte le plus pour toi quand tu es stress\u00e9(e) ?", "it": "Che tipo di aiuto significa di pi\u00f9 quando sei stressato?", "fi": "Mink\u00e4laista apua arvostat eniten, kun olet stressaantunut?", "nl": "Welke soort hulp betekent het meest voor jou als je gestrest bent?", "no": "Hvilken type hjelp betyr mest n\u00e5r du er stresset?", "sv": "Vilken typ av hj\u00e4lp betyder mest n\u00e4r du \u00e4r stressad?", "pl": "Jaki rodzaj pomocy jest dla Ciebie najwa\u017cniejszy, gdy jeste\u015b zestresowany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What kind of help means the most when you’re stressed?';
UPDATE questions
SET translations = '{"en": "What\u2019s one \u201cgender role\u201d or old habit we could unlearn together when it comes to helping each other?", "da": "Hvilken \u201ck\u00f8nsrolle\u201d eller gammel vane kunne vi afl\u00e6re sammen, n\u00e5r det g\u00e6lder at hj\u00e6lpe hinanden?", "de": "Welche \u201eGeschlechterrolle\u201c oder alte Gewohnheit k\u00f6nnten wir gemeinsam verlernen, wenn es darum geht, uns gegenseitig zu helfen?", "es": "\u00bfQu\u00e9 \u201crol de g\u00e9nero\u201d o viejo h\u00e1bito podr\u00edamos desaprender juntos cuando se trata de ayudarnos mutuamente?", "pt": "Que \u201cpapel de g\u00e9nero\u201d ou velho h\u00e1bito poder\u00edamos desaprender juntos quando se trata de ajudar um ao outro?", "ro": "Ce \u201erol de gen\u201d sau obicei vechi am putea dezv\u0103\u021ba \u00eempreun\u0103 c\u00e2nd vine vorba s\u0103 ne ajut\u0103m unul pe altul?", "fr": "Quel \u00ab r\u00f4le de genre \u00bb ou vieille habitude pourrions-nous d\u00e9sapprendre ensemble quand il s\u2019agit de s\u2019entraider ?", "it": "Qual \u00e8 un \"ruolo di genere\" o un''abitudine vecchia che potremmo disimparare insieme quando si tratta di aiutarci a vicenda?", "fi": "Mik\u00e4 on yksi \"sukupuolirooli\" tai vanha tapa, jonka voisimme unohtaa yhdess\u00e4 auttaessamme toisiamme?", "nl": "Wat is \u00e9\u00e9n \"genderrol\" of oude gewoonte die we samen zouden kunnen afleren als het gaat om elkaar helpen?", "no": "Hva er en \"kj\u00f8nnrolle\" eller gammel vane vi kan avl\u00e6re sammen n\u00e5r det gjelder \u00e5 hjelpe hverandre?", "sv": "Vilken \"k\u00f6nsroll\" eller gammal vana skulle vi kunna avl\u00e4ra oss tillsammans n\u00e4r det g\u00e4ller att hj\u00e4lpa varandra?", "pl": "Jak\u0105 jedn\u0105 \u201erol\u0119 p\u0142ci\u201d lub stary nawyk mogliby\u015bmy wsp\u00f3lnie oduczy\u0107 si\u0119, je\u015bli chodzi o wzajemn\u0105 pomoc?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s one “gender role” or old habit we could unlearn together when it comes to helping each other?';
UPDATE questions
SET translations = '{"en": "What little thing do I do that makes your life easier?", "da": "Hvilken lille ting g\u00f8r jeg, der g\u00f8r dit liv lettere?", "de": "Welche kleine Sache mache ich, die dein Leben leichter macht?", "es": "\u00bfQu\u00e9 peque\u00f1a cosa hago que hace tu vida m\u00e1s f\u00e1cil?", "pt": "Que pequena coisa eu fa\u00e7o que torna a tua vida mais f\u00e1cil?", "ro": "Ce mic lucru fac eu care \u00ee\u021bi face via\u021ba mai u\u0219oar\u0103?", "fr": "Quelle petite chose est-ce que je fais qui rend ta vie plus facile ?", "it": "Quale piccola cosa faccio che rende la tua vita pi\u00f9 facile?", "fi": "Mik\u00e4 pieni asia, jonka teen, helpottaa el\u00e4m\u00e4\u00e4si?", "nl": "Wat is een klein ding dat ik doe dat jouw leven gemakkelijker maakt?", "no": "Hva er det lille jeg gj\u00f8r som gj\u00f8r livet ditt lettere?", "sv": "Vilken liten sak g\u00f6r jag som g\u00f6r ditt liv enklare?", "pl": "Jaka ma\u0142a rzecz, kt\u00f3r\u0105 robi\u0119, u\u0142atwia ci \u017cycie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What little thing do I do that makes your life easier?';
UPDATE questions
SET translations = '{"en": "How do you want me to show that I\u2019ve got your back?", "da": "Hvordan vil du have, jeg viser, at jeg st\u00f8tter dig?", "de": "Wie m\u00f6chtest du, dass ich zeige, dass ich hinter dir stehe?", "es": "\u00bfC\u00f3mo quieres que te demuestre que te apoyo?", "pt": "Como queres que eu mostre que estou do teu lado?", "ro": "Cum vrei s\u0103 \u00ee\u021bi ar\u0103t c\u0103 te sus\u021bin?", "fr": "Comment veux-tu que je montre que je suis l\u00e0 pour toi ?", "it": "Come vuoi che ti dimostri che ti sostengo?", "fi": "Miten haluat, ett\u00e4 n\u00e4yt\u00e4n, ett\u00e4 olen tukenasi?", "nl": "Hoe wil je dat ik laat zien dat ik je steun?", "no": "Hvordan vil du at jeg skal vise at jeg st\u00f8tter deg?", "sv": "Hur vill du att jag ska visa att jag st\u00f6ttar dig?", "pl": "Jak chcesz, \u017cebym pokaza\u0142, \u017ce ci\u0119 wspieram?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you want me to show that I’ve got your back?';
UPDATE questions
SET translations = '{"en": "What\u2019s a small gesture that always feels big to you?", "da": "Hvilken lille gestus f\u00f8les altid stor for dig?", "de": "Welche kleine Geste f\u00fchlt sich f\u00fcr dich immer gro\u00df an?", "es": "\u00bfQu\u00e9 peque\u00f1o gesto siempre se siente grande para ti?", "pt": "Que pequeno gesto te parece sempre importante?", "ro": "Ce mic gest \u021bi se pare mereu important?", "fr": "Quel petit geste te semble toujours grand ?", "it": "Qual \u00e8 un piccolo gesto che per te sembra sempre grande?", "fi": "Mik\u00e4 on pieni ele, joka tuntuu aina suurelta sinulle?", "nl": "Wat is een klein gebaar dat altijd groot voor je aanvoelt?", "no": "Hva er en liten gest som alltid f\u00f8les stor for deg?", "sv": "Vilken liten gest k\u00e4nns alltid stor f\u00f6r dig?", "pl": "Jaki ma\u0142y gest zawsze wydaje ci si\u0119 wielki?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s a small gesture that always feels big to you?';
UPDATE questions
SET translations = '{"en": "When you\u2019re exhausted, how do you like me to step in?", "da": "N\u00e5r du er udmattet, hvordan vil du have, jeg tr\u00e6der til?", "de": "Wenn du ersch\u00f6pft bist, wie m\u00f6chtest du, dass ich einspringe?", "es": "Cuando est\u00e1s agotado/a, \u00bfc\u00f3mo te gusta que intervenga?", "pt": "Quando est\u00e1s exausto(a), como gostas que eu intervenha?", "ro": "C\u00e2nd e\u0219ti epuizat(\u0103), cum ai vrea s\u0103 intervin?", "fr": "Quand tu es \u00e9puis\u00e9(e), comment veux-tu que j\u2019intervienne ?", "it": "Quando sei esausto, come ti piace che io intervenga?", "fi": "Kun olet uupunut, miten haluaisit minun astuvan mukaan?", "nl": "Wanneer je uitgeput bent, hoe wil je dat ik inspring?", "no": "N\u00e5r du er utslitt, hvordan liker du at jeg tr\u00e5r til?", "sv": "N\u00e4r du \u00e4r utmattad, hur vill du att jag ska hj\u00e4lpa till?", "pl": "Kiedy jeste\u015b wyczerpany, jak chcia\u0142by\u015b, \u017cebym ci pom\u00f3g\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'When you’re exhausted, how do you like me to step in?';