UPDATE questions
SET translations = '{"en": "What\u2019s something you think I\u2019m really good at? What\u2019s something you think you are really good at?", "da": "Hvad synes du, jeg er rigtig god til? Hvad synes du, du selv er god til?", "de": "Was glaubst du, worin ich richtig gut bin? Worin bist du richtig gut?", "es": "\u00bfEn qu\u00e9 crees que soy muy bueno? \u00bfEn qu\u00e9 crees que t\u00fa eres bueno?", "pt": "Em que achas que eu sou muito bom? Em que achas que tu \u00e9s bom?", "ro": "La ce crezi c\u0103 sunt foarte bun? La ce crezi c\u0103 e\u0219ti tu bun?", "fr": "En quoi penses-tu que je suis tr\u00e8s bon ? Et toi, en quoi es-tu bon ?", "it": "Qual \u00e8 una cosa in cui pensi che io sia davvero bravo? E qual \u00e8 una cosa in cui pensi di essere davvero bravo?", "fi": "Mik\u00e4 on jotain, miss\u00e4 luulet minun olevan todella hyv\u00e4? Mik\u00e4 on jotain, miss\u00e4 luulet olevasi todella hyv\u00e4?", "nl": "Wat is iets waarvan je denkt dat ik er echt goed in ben? Wat is iets waarvan je denkt dat jij er echt goed in bent?", "no": "Hva er noe du mener jeg er veldig god til? Hva er noe du mener du er veldig god til?", "sv": "Vad \u00e4r n\u00e5got som du tycker att jag \u00e4r riktigt bra p\u00e5? Vad \u00e4r n\u00e5got som du tycker att du \u00e4r riktigt bra p\u00e5?", "pl": "Co my\u015blisz, w czym jestem naprawd\u0119 dobry? A co my\u015blisz, w czym ty jeste\u015b naprawd\u0119 dobry?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What’s something you think I’m really good at? What’s something you think you are really good at?';
UPDATE questions
SET translations = '{"en": "Who do you like to sit next to, and why?", "da": "Hvem kan du bedst lide at sidde ved siden af, og hvorfor?", "de": "Neben wem sitzt du gern, und warum?", "es": "\u00bfAl lado de qui\u00e9n te gusta sentarte y por qu\u00e9?", "pt": "Ao lado de quem gostas de te sentar e por qu\u00ea?", "ro": "L\u00e2ng\u0103 cine \u00ee\u021bi place s\u0103 stai la \u0219coal\u0103 \u0219i de ce?", "fr": "\u00c0 c\u00f4t\u00e9 de qui aimes-tu t\u2019asseoir et pourquoi ?", "it": "Chi ti piace avere accanto e perch\u00e9?", "fi": "Kenen vieress\u00e4 tykk\u00e4\u00e4t istua, ja miksi?", "nl": "Wie zit je het liefst naast, en waarom?", "no": "Hvem liker du \u00e5 sitte ved siden av, og hvorfor?", "sv": "Vem gillar du att sitta bredvid, och varf\u00f6r?", "pl": "Kogo lubisz siedzie\u0107 obok i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Who do you like to sit next to, and why?';
UPDATE questions
SET translations = '{"en": "Show a face for excited, then tell us what makes you feel that way.", "da": "Vis et ansigt for begejstret, og fort\u00e6l os derefter, hvad der f\u00e5r dig til at f\u00f8le s\u00e5dan.", "de": "Zeig ein Gesicht f\u00fcr Aufregung und erz\u00e4hle uns, was dich so f\u00fchlen l\u00e4sst.", "es": "Muestra una cara de emoci\u00f3n, y dinos qu\u00e9 te hace sentir as\u00ed.", "pt": "Mostra uma cara de empolgado e diz-nos o que te faz sentir assim.", "ro": "Arat\u0103 o fa\u021b\u0103 de entuziasm \u0219i spune-ne ce te face s\u0103 te sim\u021bi a\u0219a.", "fr": "Montre un visage excit\u00e9, puis dis-nous ce te fait te sentir ainsi.", "it": "Mostra un volto entusiasta, poi raccontaci cosa ti fa sentire in quel modo.", "fi": "N\u00e4yt\u00e4 innostunut ilme ja kerro meille, mik\u00e4 saa sinut tuntemaan niin.", "nl": "Toon een gezicht voor opwinding en vertel ons wat je zo voelt.", "no": "Vis et ansikt for begeistring, og fortell oss hva som f\u00e5r deg til \u00e5 f\u00f8le det slik.", "sv": "Visa ett ansikte f\u00f6r upphetsning, och ber\u00e4tta sedan vad som f\u00e5r dig att k\u00e4nna s\u00e5.", "pl": "Poka\u017c twarz wyra\u017caj\u0105c\u0105 ekscytacj\u0119, a nast\u0119pnie powiedz nam, co sprawia, \u017ce tak si\u0119 czujesz."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'Show a face for excited, then tell us what makes you feel that way.';
UPDATE questions
SET translations = '{"en": "If you could change the sky\u2019s color for one day, what would you pick?", "da": "Hvis du kunne \u00e6ndre himlens farve for en dag, hvilken ville du v\u00e6lge?", "de": "Wenn du die Farbe des Himmels f\u00fcr einen Tag \u00e4ndern k\u00f6nntest, welche w\u00fcrdest du w\u00e4hlen?", "es": "Si pudieras cambiar el color del cielo por un d\u00eda, \u00bfcu\u00e1l elegir\u00edas?", "pt": "Se pudesses mudar a cor do c\u00e9u por um dia, qual escolherias?", "ro": "Dac\u0103 ai putea schimba culoarea cerului pentru o zi, ce culoare ai alege?", "fr": "Si tu pouvais changer la couleur du ciel pour une journ\u00e9e, laquelle choisirais-tu ?", "it": "Se potessi cambiare il colore del cielo per un giorno, quale sceglieresti?", "fi": "Jos voisit muuttaa taivaan v\u00e4ri\u00e4 yhden p\u00e4iv\u00e4n ajaksi, mik\u00e4 v\u00e4ri olisi valintasi?", "nl": "Als je de kleur van de lucht voor \u00e9\u00e9n dag zou kunnen veranderen, welke zou je dan kiezen?", "no": "Hvis du kunne endre fargen p\u00e5 himmelen for en dag, hva ville du valgt?", "sv": "Om du kunde \u00e4ndra himlens f\u00e4rg f\u00f6r en dag, vilken skulle du v\u00e4lja?", "pl": "Gdyby\u015b m\u00f3g\u0142 zmieni\u0107 kolor nieba na jeden dzie\u0144, jaki by\u015b wybra\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could change the sky’s color for one day, what would you pick?';
UPDATE questions
SET translations = '{"en": "What is something you can do all by yourself now?", "da": "Hvad er noget, du nu kan g\u00f8re helt selv?", "de": "Was kannst du jetzt ganz allein tun?", "es": "\u00bfQu\u00e9 puedes hacer t\u00fa solo ahora?", "pt": "O que j\u00e1 consegues fazer sozinho agora?", "ro": "Ce po\u021bi face singur acum?", "fr": "Qu\u2019est-ce que tu peux faire tout seul maintenant ?", "it": "Qualcosa che puoi fare tutto da solo adesso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 voit tehd\u00e4 t\u00e4ysin itse nyt?", "nl": "Wat is iets dat je nu helemaal alleen kunt doen?", "no": "Hva er noe du kan gj\u00f8re helt alene n\u00e5?", "sv": "Vad \u00e4r n\u00e5got du kan g\u00f6ra helt sj\u00e4lv nu?", "pl": "Co\u015b, co mo\u017cesz teraz zrobi\u0107 ca\u0142kowicie samodzielnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What is something you can do all by yourself now?';
UPDATE questions
SET translations = '{"en": "If you had a pocket robot, what job would you give it?", "da": "Hvis du havde en lomme-robot, hvilket job ville du give den?", "de": "Wenn du einen Taschenroboter h\u00e4ttest, welche Aufgabe w\u00fcrdest du ihm geben?", "es": "Si tuvieras un robot de bolsillo, \u00bfqu\u00e9 trabajo le dar\u00edas?", "pt": "Se tivesses um rob\u00f4 de bolso, que trabalho lhe darias?", "ro": "Dac\u0103 ai avea un robot de buzunar, ce sarcin\u0103 i-ai da?", "fr": "Si tu avais un robot de poche, quel travail lui confierais-tu ?", "it": "Se avessi un robot tascabile, quale lavoro gli affideresti?", "fi": "Jos sinulla olisi taskurobotti, mink\u00e4 ty\u00f6n antaisit sille?", "nl": "Als je een zakrobot had, welke taak zou je hem dan geven?", "no": "Hvis du hadde en lomme-robot, hvilken jobb ville du gitt den?", "sv": "Om du hade en fickrobot, vilket jobb skulle du ge den?", "pl": "Gdyby\u015b mia\u0142 robota kieszonkowego, jak\u0105 prac\u0119 by\u015b mu da\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you had a pocket robot, what job would you give it?';
UPDATE questions
SET translations = '{"en": "If you could plant a magic seed, what would you like to grow?", "da": "Hvis du kunne plante et magisk fr\u00f8, hvad ville du gerne have, at det voksede til?", "de": "Wenn du einen magischen Samen pflanzen k\u00f6nntest, was w\u00fcrdest du gerne wachsen lassen?", "es": "Si pudieras plantar una semilla m\u00e1gica, \u00bfqu\u00e9 te gustar\u00eda que creciera?", "pt": "Se pudesses plantar uma semente m\u00e1gica, o que gostarias que crescesse?", "ro": "Dac\u0103 ai putea planta o s\u0103m\u00e2n\u021b\u0103 magic\u0103, ce ai vrea s\u0103 creasc\u0103 din ea?", "fr": "Si tu pouvais planter une graine magique, que voudrais-tu qu\u2019elle fasse pousser ?", "it": "Se potessi piantare un seme magico, cosa ti piacerebbe far crescere?", "fi": "Jos voisit istuttaa taikasiemenen, mit\u00e4 haluaisit kasvattaa?", "nl": "Als je een magisch zaadje zou kunnen planten, wat zou je dan graag willen laten groeien?", "no": "Hvis du kunne plante et magisk fr\u00f8, hva ville du likt \u00e5 dyrke?", "sv": "Om du kunde plantera ett magiskt fr\u00f6, vad skulle du vilja att det v\u00e4xte?", "pl": "Gdyby\u015b m\u00f3g\u0142 zasadzi\u0107 magiczne ziarno, co chcia\u0142by\u015b, aby wyros\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could plant a magic seed, what would you like to grow?';
UPDATE questions
SET translations = '{"en": "What do you think the Tooth Fairy does with all the teeth she collects?", "da": "Hvad tror du, Tandfeen g\u00f8r med alle t\u00e6nderne, hun samler?", "de": "Was glaubst du, was die Zahnfee mit all den Z\u00e4hnen macht, die sie sammelt?", "es": "\u00bfQu\u00e9 crees que hace el Hada de los Dientes con todos los dientes que recoge?", "pt": "O que achas que a Fada dos Dentes faz com todos os dentes que recolhe?", "ro": "Ce crezi c\u0103 face Z\u00e2na M\u0103selu\u021b\u0103 cu to\u021bi din\u021bii pe care \u00eei colecteaz\u0103?", "fr": "Que penses-tu que fait la Petite Souris avec toutes les dents qu\u2019elle ramasse ?", "it": "Cosa pensi che faccia la Fatina dei Denti con tutti i denti che colleziona?", "fi": "Mit\u00e4 mielt\u00e4 olet, mit\u00e4 Hammaskeiju tekee kaikilla ker\u00e4\u00e4mill\u00e4\u00e4n hampailla?", "nl": "Wat denk je dat de Tandfee doet met al die tanden die ze verzamelt?", "no": "Hva tror du Tandfeen gj\u00f8r med alle tennene hun samler inn?", "sv": "Vad tror du tandfen g\u00f6r med alla t\u00e4nder hon samlar in?", "pl": "Co my\u015blisz, co wr\u00f3\u017cka z\u0119buszka robi ze wszystkimi z\u0119bami, kt\u00f3re zbiera?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What do you think the Tooth Fairy does with all the teeth she collects?';
UPDATE questions
SET translations = '{"en": "If you could give Mom or Dad a new job, what would it be?", "da": "Hvis du kunne give mor eller far et nyt job, hvad ville det v\u00e6re?", "de": "Wenn du Mama oder Papa einen neuen Job geben k\u00f6nntest, welcher w\u00e4re das?", "es": "Si pudieras darle a mam\u00e1 o pap\u00e1 un nuevo trabajo, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se pudesses dar \u00e0 mam\u00e3e ou ao papai um novo emprego, qual seria?", "ro": "Dac\u0103 ai putea s\u0103-i dai mamei sau tat\u0103lui un nou loc de munc\u0103, care ar fi acela?", "fr": "Si tu pouvais donner un nouveau travail \u00e0 maman ou papa, lequel serait-ce ?", "it": "Se potessi dare a mamma o pap\u00e0 un nuovo lavoro, quale sarebbe?", "fi": "Jos voisit antaa \u00e4idille tai is\u00e4lle uuden ty\u00f6n, mik\u00e4 se olisi?", "nl": "Als je Mama of Papa een nieuwe baan zou kunnen geven, wat zou dat dan zijn?", "no": "Hvis du kunne gi mamma eller pappa en ny jobb, hva ville det v\u00e6rt?", "sv": "Om du kunde ge mamma eller pappa ett nytt jobb, vad skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 da\u0107 Mamie lub Tacie now\u0105 prac\u0119, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'If you could give Mom or Dad a new job, what would it be?';
UPDATE questions
SET translations = '{"en": "What do you think is harder \u2014 being a kid or being a parent? Why?", "da": "Hvad tror du er sv\u00e6rere \u2014 at v\u00e6re barn eller at v\u00e6re for\u00e6lder? Hvorfor?", "de": "Was ist deiner Meinung nach schwieriger \u2013 ein Kind oder ein Elternteil zu sein? Warum?", "es": "\u00bfQu\u00e9 crees que es m\u00e1s dif\u00edcil: ser ni\u00f1o o ser padre? \u00bfPor qu\u00e9?", "pt": "O que achas que \u00e9 mais dif\u00edcil \u2014 ser crian\u00e7a ou ser pai/m\u00e3e? Por qu\u00ea?", "ro": "Ce crezi c\u0103 este mai greu \u2014 s\u0103 fii copil sau p\u0103rinte? De ce?", "fr": "Qu\u2019est-ce qui est plus difficile \u00e0 ton avis \u2014 \u00eatre enfant ou \u00eatre parent ? Pourquoi ?", "it": "Cosa pensi sia pi\u00f9 difficile \u2014 essere un bambino o essere un genitore? Perch\u00e9?", "fi": "Mit\u00e4 mielt\u00e4 olet, mik\u00e4 on vaikeampaa \u2014 olla lapsi vai olla vanhempi? Miksi?", "nl": "Wat denk je dat moeilijker is \u2014 een kind zijn of een ouder zijn? Waarom?", "no": "Hva tror du er vanskeligere \u2014 \u00e5 v\u00e6re barn eller \u00e5 v\u00e6re forelder? Hvorfor?", "sv": "Vad tycker du \u00e4r sv\u00e5rare \u2014 att vara barn eller att vara f\u00f6r\u00e4lder? Varf\u00f6r?", "pl": "Co my\u015blisz, co jest trudniejsze \u2014 by\u0107 dzieckiem czy by\u0107 rodzicem? Dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Tiny Talks'
  AND translations->>'en' = 'What do you think is harder — being a kid or being a parent? Why?';