UPDATE questions
SET translations = '{"en": "\u201cYou\u2019re obligated to call out injustice, even if it risks your social status.\u201d", "da": "Du er forpligtet til at p\u00e5tale uretf\u00e6rdighed, selv hvis det koster dig social status.", "de": "Du bist verpflichtet, Ungerechtigkeit anzusprechen, selbst wenn es dich sozialen Status kostet.", "es": "Est\u00e1s obligado a denunciar la injusticia, incluso si arriesgas tu estatus social.", "pt": "\u00c9s obrigado a denunciar a injusti\u00e7a, mesmo que arrisques o teu estatuto social.", "ro": "E\u0219ti obligat s\u0103 denun\u021bi nedreptatea, chiar dac\u0103 \u00ee\u021bi ri\u0219ti statutul social.", "fr": "Tu es oblig\u00e9 de d\u00e9noncer l\u2019injustice, m\u00eame si cela met en danger ton statut social.", "it": "\u201cSei obbligato a denunciare l''ingiustizia, anche se questo mette a rischio il tuo status sociale.\u201d", "fi": "\"Olet velvoitettu puuttumaan ep\u00e4oikeudenmukaisuuteen, vaikka se uhkaisi sosiaalista asemaasi.\"", "nl": "\"Je bent verplicht om onrecht aan te kaarten, ook al brengt het je sociale status in gevaar.\"", "no": "\"Du er forpliktet til \u00e5 p\u00e5peke urettferdighet, selv om det kan true din sosiale status.\"", "sv": "\"Du \u00e4r skyldig att p\u00e5peka or\u00e4ttvisor, \u00e4ven om det riskerar din sociala status.\"", "pl": "\u201eJeste\u015b zobowi\u0105zany do wytykania niesprawiedliwo\u015bci, nawet je\u015bli grozi to twojemu statusowi spo\u0142ecznemu.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You’re obligated to call out injustice, even if it risks your social status.”';
UPDATE questions
SET translations = '{"en": "\u201cYou shouldn\u2019t support a brand just because it\u2019s \u201cethical\u201d \u2014 ethics are marketing now.\u201d", "da": "Du b\u00f8r ikke st\u00f8tte et brand bare fordi det er \u201cetisk\u201d \u2013 etik er markedsf\u00f8ring nu.", "de": "Man sollte eine Marke nicht nur unterst\u00fctzen, weil sie \u201eethisch\u201c ist \u2013 Ethik ist jetzt Marketing.", "es": "No deber\u00edas apoyar una marca solo porque sea \u201c\u00e9tica\u201d \u2014 la \u00e9tica ahora es marketing.", "pt": "N\u00e3o deves apoiar uma marca apenas porque \u00e9 \u201c\u00e9tica\u201d \u2014 a \u00e9tica \u00e9 marketing agora.", "ro": "Nu ar trebui s\u0103 sprijini un brand doar pentru c\u0103 este \u201cetic\u201d \u2014 etica e marketing acum.", "fr": "Tu ne devrais pas soutenir une marque simplement parce qu\u2019elle est \u00ab \u00e9thique \u00bb \u2014 l\u2019\u00e9thique est devenue du marketing.", "it": "\"Non dovresti sostenere un marchio solo perch\u00e9 \u00e8 ''etico'' \u2014 l''etica \u00e8 diventata marketing ora.\"", "fi": "\"Et pit\u00e4isi tukea br\u00e4ndi\u00e4 vain sen vuoksi, ett\u00e4 se on ''eettinen'' \u2014 eettisyys on nyky\u00e4\u00e4n markkinointia.\"", "nl": "\"Je zou een merk niet moeten steunen alleen omdat het ''ethisch'' is \u2014 ethiek is nu marketing.\"", "no": "\"Du b\u00f8r ikke st\u00f8tte et merke bare fordi det er ''etisk'' \u2014 etikk er n\u00e5 markedsf\u00f8ring.\"", "sv": "\"Du borde inte st\u00f6dja ett m\u00e4rke bara f\u00f6r att det \u00e4r ''etiskt'' \u2014 etik \u00e4r nu marknadsf\u00f6ring.\"", "pl": "\u201eNie powiniene\u015b wspiera\u0107 marki tylko dlatego, \u017ce jest \u201eetyczna\u201d \u2014 etyka to teraz marketing.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You shouldn’t support a brand just because it’s “ethical” — ethics are marketing now.”';
UPDATE questions
SET translations = '{"en": "\u201cMinimalism should be imposed: everyone should live with < X possessions.\u201d", "da": "Minimalisme b\u00f8r p\u00e5l\u00e6gges: alle b\u00f8r leve med f\u00e6rre ejendele.", "de": "Minimalismus sollte vorgeschrieben werden: Jeder sollte mit weniger Besitz leben.", "es": "El minimalismo deber\u00eda imponerse: todos deber\u00edan vivir con menos posesiones.", "pt": "O minimalismo deveria ser imposto: todos deveriam viver com menos posses.", "ro": "Minimalismul ar trebui impus: to\u021bi ar trebui s\u0103 tr\u0103iasc\u0103 cu mai pu\u021bine lucruri.", "fr": "Le minimalisme devrait \u00eatre impos\u00e9 : tout le monde devrait vivre avec moins de possessions.", "it": "\"Il minimalismo dovrebbe essere imposto: tutti dovrebbero vivere con < X possedimenti.\"", "fi": "\"Minimalismia tulisi pakottaa: jokaisen tulisi el\u00e4\u00e4 alle < X omaisuuden kanssa.\"", "nl": "\"Minimalisme zou moeten worden opgelegd: iedereen zou met < X bezittingen moeten leven.\"", "no": "\u201cMinimalisme b\u00f8r p\u00e5legges: alle b\u00f8r leve med < X eiendeler.\u201d", "sv": "\"Minimalism b\u00f6r inf\u00f6ras: alla b\u00f6r leva med < X \u00e4godelar.\"", "pl": "\u201eMinimalizm powinien by\u0107 narzucony: ka\u017cdy powinien \u017cy\u0107 z < X przedmiotami.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Minimalism should be imposed: everyone should live with < X possessions.”';
UPDATE questions
SET translations = '{"en": "\u201cMoney is the most honest expression of value in relationships (time, gifts, wages).\u201d", "da": "Penge er det mest \u00e6rlige udtryk for v\u00e6rdi i forhold (tid, gaver, l\u00f8n).", "de": "Geld ist der ehrlichste Ausdruck von Wert in Beziehungen (Zeit, Geschenke, L\u00f6hne).", "es": "El dinero es la expresi\u00f3n m\u00e1s honesta de valor en las relaciones (tiempo, regalos, salarios).", "pt": "O dinheiro \u00e9 a express\u00e3o mais honesta de valor nas rela\u00e7\u00f5es (tempo, presentes, sal\u00e1rios).", "ro": "Banii sunt cea mai sincer\u0103 expresie a valorii \u00een rela\u021bii (timp, cadouri, salarii).", "fr": "L\u2019argent est la forme la plus honn\u00eate d\u2019expression de la valeur dans les relations (temps, cadeaux, salaires).", "it": "\u201cIl denaro \u00e8 l''espressione pi\u00f9 onesta del valore nelle relazioni (tempo, regali, salari).\u201d", "fi": "\"Raha on rehellisin arvon ilmaisu suhteissa (aika, lahjat, palkat).\"", "nl": "\"Geld is de meest eerlijke uitdrukking van waarde in relaties (tijd, cadeaus, lonen).\"", "no": "\u201cPenger er den mest \u00e6rlige uttrykk for verdi i relasjoner (tid, gaver, l\u00f8nn).\u201d", "sv": "\"Pengar \u00e4r det mest \u00e4rliga uttrycket f\u00f6r v\u00e4rde i relationer (tid, g\u00e5vor, l\u00f6ner).\"", "pl": "\u201ePieni\u0105dze s\u0105 najuczciwszym wyrazem warto\u015bci w relacjach (czas, prezenty, wynagrodzenia).\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Money is the most honest expression of value in relationships (time, gifts, wages).”';
UPDATE questions
SET translations = '{"en": "\u201cPrivacy is dead and we should stop pretending otherwise.\u201d", "da": "Privatliv er d\u00f8dt, og vi b\u00f8r stoppe med at lade som om det eksisterer.", "de": "Privatsph\u00e4re ist tot, und wir sollten aufh\u00f6ren, so zu tun, als g\u00e4be es sie.", "es": "La privacidad est\u00e1 muerta y deber\u00edamos dejar de fingir lo contrario.", "pt": "A privacidade est\u00e1 morta e devemos parar de fingir o contr\u00e1rio.", "ro": "Confiden\u021bialitatea este moart\u0103 \u0219i ar trebui s\u0103 \u00eencet\u0103m s\u0103 pretindem contrariul.", "fr": "La vie priv\u00e9e est morte et nous devrions cesser de pr\u00e9tendre le contraire.", "it": "\"La privacy \u00e8 morta e dovremmo smettere di fare finta del contrario.\"", "fi": "\"Yksityisyys on kuollut, ja meid\u00e4n pit\u00e4isi lopettaa teeskentely.\"", "nl": "\"Privacy is dood en we moeten stoppen met doen alsof dat niet zo is.\"", "no": "\"Personvernet er d\u00f8dt, og vi b\u00f8r slutte \u00e5 late som noe annet.\"", "sv": "\"Integriteten \u00e4r d\u00f6d och vi borde sluta l\u00e5tsas som n\u00e5got annat.\"", "pl": "\u201ePrywatno\u015b\u0107 umar\u0142a i powinni\u015bmy przesta\u0107 udawa\u0107, \u017ce jest inaczej.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Privacy is dead and we should stop pretending otherwise.”';
UPDATE questions
SET translations = '{"en": "\u201cVirtual reality will replace physical travel.\u201d", "da": "Virtuel virkelighed vil erstatte fysisk rejse.", "de": "Virtuelle Realit\u00e4t wird physisches Reisen ersetzen.", "es": "La realidad virtual reemplazar\u00e1 los viajes f\u00edsicos.", "pt": "A realidade virtual vai substituir as viagens f\u00edsicas.", "ro": "Realitatea virtual\u0103 va \u00eenlocui c\u0103l\u0103toriile fizice.", "fr": "La r\u00e9alit\u00e9 virtuelle remplacera les voyages physiques.", "it": "\"La realt\u00e0 virtuale sostituir\u00e0 i viaggi fisici.\"", "fi": "\"Virtuaalitodellisuus tulee korvaamaan fyysisen matkustamisen.\"", "nl": "\"Virtuele realiteit zal fysiek reizen vervangen.\"", "no": "\"Virtuell virkelighet vil erstatte fysisk reise.\"", "sv": "\"Virtuell verklighet kommer att ers\u00e4tta fysisk resa.\"", "pl": "\u201eWirtualna rzeczywisto\u015b\u0107 zast\u0105pi podr\u00f3\u017ce fizyczne.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Virtual reality will replace physical travel.”';
UPDATE questions
SET translations = '{"en": "\u201cSpace exploration is a waste while earth problems persist.\u201d", "da": "Rumforskning er spild, mens jordens problemer best\u00e5r.", "de": "Weltraumforschung ist eine Verschwendung, solange Probleme auf der Erde bestehen.", "es": "La exploraci\u00f3n espacial es un desperdicio mientras persistan los problemas terrestres.", "pt": "A explora\u00e7\u00e3o espacial \u00e9 um desperd\u00edcio enquanto persistirem os problemas na Terra.", "ro": "Explorarea spa\u021bial\u0103 este o risip\u0103 c\u00e2t timp problemele P\u0103m\u00e2ntului persist\u0103.", "fr": "L\u2019exploration spatiale est un gaspillage tant que les probl\u00e8mes terrestres persistent.", "it": "\"L''esplorazione spaziale \u00e8 uno spreco mentre i problemi sulla Terra persistono.\"", "fi": "\"Avaruustutkimus on hukkaa, kun maan ongelmat jatkuvat.\"", "nl": "\"Ruimteverkenning is een verspilling terwijl de problemen op aarde aanhouden.\"", "no": "\"Romforskning er bortkastet mens jordens problemer vedvarer.\"", "sv": "\"Rymdforskning \u00e4r sl\u00f6seri medan jordens problem kvarst\u00e5r.\"", "pl": "\u201eEksploracja kosmosu to marnotrawstwo, podczas gdy problemy na Ziemi wci\u0105\u017c istniej\u0105.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Space exploration is a waste while earth problems persist.”';
UPDATE questions
SET translations = '{"en": "\u201cWe should judge people\u2019s future actions more than past mistakes.\u201d", "da": "Vi b\u00f8r bed\u00f8mme folks fremtidige handlinger mere end deres tidligere fejl.", "de": "Wir sollten Menschen mehr nach ihren zuk\u00fcnftigen Handlungen als nach ihren fr\u00fcheren Fehlern beurteilen.", "es": "Deber\u00edamos juzgar a las personas por sus acciones futuras m\u00e1s que por sus errores pasados.", "pt": "Devemos julgar as pessoas mais pelas suas a\u00e7\u00f5es futuras do que pelos erros passados.", "ro": "Ar trebui s\u0103 judec\u0103m oamenii mai mult dup\u0103 ac\u021biunile viitoare dec\u00e2t dup\u0103 gre\u0219elile trecute.", "fr": "Nous devrions juger les gens davantage sur leurs actions futures que sur leurs erreurs pass\u00e9es.", "it": "\"Dovremmo giudicare le azioni future delle persone pi\u00f9 che gli errori passati.\"", "fi": "\"Meid\u00e4n pit\u00e4isi arvioida ihmisten tulevia tekoja enemm\u00e4n kuin menneit\u00e4 virheit\u00e4.\"", "nl": "\"We zouden de toekomstige acties van mensen meer moeten beoordelen dan hun verleden fouten.\"", "no": "\"Vi b\u00f8r vurdere folks fremtidige handlinger mer enn fortidige feil.\"", "sv": "\"Vi borde d\u00f6ma m\u00e4nniskors framtida handlingar mer \u00e4n deras f\u00f6rflutna misstag.\"", "pl": "\u201ePowinni\u015bmy ocenia\u0107 przysz\u0142e dzia\u0142ania ludzi bardziej ni\u017c ich przesz\u0142e b\u0142\u0119dy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“We should judge people’s future actions more than past mistakes.”';
UPDATE questions
SET translations = '{"en": "\u201cTherapy should be free, not a luxury service.\u201d", "da": "Terapi b\u00f8r v\u00e6re gratis, ikke en luksustjeneste.", "de": "Therapie sollte kostenlos sein, kein Luxusdienst.", "es": "La terapia deber\u00eda ser gratuita, no un servicio de lujo.", "pt": "A terapia devia ser gratuita, n\u00e3o um servi\u00e7o de luxo.", "ro": "Terapia ar trebui s\u0103 fie gratuit\u0103, nu un serviciu de lux.", "fr": "La th\u00e9rapie devrait \u00eatre gratuite, pas un service de luxe.", "it": "\"La terapia dovrebbe essere gratuita, non un servizio di lusso.\"", "fi": "\"Terapiapalveluiden tulisi olla ilmaisia, ei luksuspalveluja.\"", "nl": "\"Therapie zou gratis moeten zijn, geen luxe dienst.\"", "no": "\u00abTerapi b\u00f8r v\u00e6re gratis, ikke en luksustjeneste.\u00bb", "sv": "\"Terapi borde vara gratis, inte en lyxtj\u00e4nst.\"", "pl": "\u201eTerapia powinna by\u0107 darmowa, a nie luksusow\u0105 us\u0142ug\u0105.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Therapy should be free, not a luxury service.”';
UPDATE questions
SET translations = '{"en": "\u201cContent creators should be taxed like traditional workers.\u201d", "da": "Indholdsskabere b\u00f8r beskattes som traditionelle arbejdere.", "de": "Inhaltsersteller sollten wie traditionelle Arbeiter besteuert werden.", "es": "Los creadores de contenido deber\u00edan tributar como los trabajadores tradicionales.", "pt": "Os criadores de conte\u00fado deviam ser tributados como trabalhadores tradicionais.", "ro": "Creatorii de con\u021binut ar trebui impozita\u021bi ca lucr\u0103torii tradi\u021bionali.", "fr": "Les cr\u00e9ateurs de contenu devraient \u00eatre impos\u00e9s comme les travailleurs traditionnels.", "it": "\"I creatori di contenuti dovrebbero essere tassati come i lavoratori tradizionali.\"", "fi": "\"Sis\u00e4ll\u00f6ntuottajia tulisi verottaa kuten perinteisi\u00e4 ty\u00f6ntekij\u00f6it\u00e4.\"", "nl": "\"Contentmakers zouden belast moeten worden zoals traditionele werknemers.\"", "no": "\u00abInnholdsprodusenter b\u00f8r beskattes som tradisjonelle arbeidere.\u00bb", "sv": "\"Inneh\u00e5llsskapare b\u00f6r beskattas som traditionella arbetare.\"", "pl": "\u201eTw\u00f3rcy tre\u015bci powinni by\u0107 opodatkowani jak tradycyjni pracownicy.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Content creators should be taxed like traditional workers.”';