UPDATE questions
SET translations = '{"en": "Who in this group would make the best game show host \u2014 and what would the show be about?", "da": "Hvem i denne gruppe ville v\u00e6re den bedste quizshow-v\u00e6rt \u2014 og hvad ville showet handle om?", "de": "Wer in dieser Gruppe w\u00e4re der beste Gameshow-Moderator \u2013 und worum w\u00fcrde es gehen?", "es": "\u00bfQui\u00e9n en este grupo ser\u00eda el mejor presentador de concurso y de qu\u00e9 tratar\u00eda el programa?", "pt": "Quem neste grupo seria o melhor apresentador de jogo \u2014 e sobre o que seria o programa?", "ro": "Cine din acest grup ar fi cel mai bun prezentator de show \u2014 \u0219i despre ce ar fi?", "fr": "Qui dans ce groupe ferait le meilleur animateur de jeu \u2014 et de quoi parlerait l\u2019\u00e9mission ?", "it": "Chi in questo gruppo sarebbe il miglior presentatore di un quiz \u2014 e di cosa tratterebbe lo show?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 olisi paras peliohjelman juontaja \u2014 ja mist\u00e4 ohjelma olisi?", "nl": "Wie in deze groep zou de beste spelshowhost zijn \u2014 en waar zou de show over gaan?", "no": "Hvem i denne gruppen ville v\u00e6rt den beste spillprogramverten \u2014 og hva ville programmet handlet om?", "sv": "Vem i den h\u00e4r gruppen skulle vara den b\u00e4sta programledaren f\u00f6r ett fr\u00e5gespel \u2014 och vad skulle programmet handla om?", "pl": "Kto w tej grupie by\u0142by najlepszym prowadz\u0105cym teleturniej \u2014 i o czym by\u0142by ten program?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Party Night Talks'
  AND translations->>'en' = 'Who in this group would make the best game show host — and what would the show be about?';

-- Category: Plot Twists & Dilemmas  (75 questions)
UPDATE questions
SET translations = '{"en": "You\u2019re in love, but your friends hate your partner. Do you listen to them or follow your heart?", "da": "Du er forelsket, men dine venner hader din partner. Lytter du til dem eller f\u00f8lger dit hjerte?", "de": "Du bist verliebt, aber deine Freunde hassen deinen Partner. H\u00f6rst du auf sie oder folgst du deinem Herzen?", "es": "Est\u00e1s enamorado/a, pero tus amigos odian a tu pareja. \u00bfLes haces caso o sigues tu coraz\u00f3n?", "pt": "Est\u00e1s apaixonado(a), mas os teus amigos odeiam o teu parceiro. Ouves-os ou segues o teu cora\u00e7\u00e3o?", "ro": "E\u0219ti \u00eendr\u0103gostit(\u0103), dar prietenii t\u0103i \u00ee\u021bi ur\u0103sc partenerul. \u00cei ascul\u021bi sau \u00ee\u021bi urmezi inima?", "fr": "Tu es amoureux(se), mais tes amis d\u00e9testent ton partenaire. Tu les \u00e9coutes ou tu suis ton c\u0153ur ?", "it": "Sei innamorato, ma i tuoi amici odiano il tuo partner. Ascolti loro o segui il tuo cuore?", "fi": "Olet rakastunut, mutta yst\u00e4v\u00e4si vihaavat kumppaniasi. Kuunteletko heit\u00e4 vai seuraatko syd\u00e4nt\u00e4si?", "nl": "Je bent verliefd, maar je vrienden haten je partner. Luister je naar hen of volg je je hart?", "no": "Du er forelsket, men vennene dine hater partneren din. Lytter du til dem eller f\u00f8lger du hjertet ditt?", "sv": "Du \u00e4r k\u00e4r, men dina v\u00e4nner hatar din partner. Lyssnar du p\u00e5 dem eller f\u00f6ljer du ditt hj\u00e4rta?", "pl": "Jeste\u015b zakochany, ale twoi przyjaciele nienawidz\u0105 twojego partnera. S\u0142uchasz ich, czy pod\u0105\u017casz za swoim sercem?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You’re in love, but your friends hate your partner. Do you listen to them or follow your heart?';
UPDATE questions
SET translations = '{"en": "If two of us called you crying at the same time, who would you answer first?", "da": "Hvis to af os ringede gr\u00e6dende p\u00e5 samme tid, hvem ville du svare f\u00f8rst?", "de": "Wenn zwei von uns dich gleichzeitig weinend anrufen w\u00fcrden, wem w\u00fcrdest du zuerst antworten?", "es": "Si dos de nosotros te llam\u00e1ramos llorando al mismo tiempo, \u00bfa qui\u00e9n responder\u00edas primero?", "pt": "Se dois de n\u00f3s te lig\u00e1ssemos a chorar ao mesmo tempo, a quem responderias primeiro?", "ro": "Dac\u0103 doi dintre noi te-ar suna pl\u00e2ng\u00e2nd \u00een acela\u0219i timp, cui i-ai r\u0103spunde primul?", "fr": "Si deux d\u2019entre nous t\u2019appelaient en pleurant en m\u00eame temps, \u00e0 qui r\u00e9pondrais-tu en premier ?", "it": "Se due di noi ti chiamassero piangendo contemporaneamente, chi risponderesti per primo?", "fi": "Jos kaksi meist\u00e4 soittaisi sinulle itkien samaan aikaan, kenelle vastaisit ensin?", "nl": "Als twee van ons je tegelijkertijd belden en huilend waren, wie zou je dan als eerste beantwoorden?", "no": "Hvis to av oss ringte deg gr\u00e5tende samtidig, hvem ville du svart f\u00f8rst?", "sv": "Om tv\u00e5 av oss ringde dig gr\u00e5tande samtidigt, vem skulle du svara f\u00f6rst?", "pl": "Je\u015bli dwoje z nas zadzwoni\u0142oby do ciebie p\u0142acz\u0105c w tym samym czasie, kogo by\u015b odebra\u0142 pierwszy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If two of us called you crying at the same time, who would you answer first?';
UPDATE questions
SET translations = '{"en": "If we all swapped phones for 5 minutes, whose would cause the biggest scandal?", "da": "Hvis vi alle byttede telefoner i 5 minutter, hvis ville skabe den st\u00f8rste skandale?", "de": "Wenn wir alle f\u00fcr 5 Minuten die Handys tauschen w\u00fcrden, welches w\u00fcrde den gr\u00f6\u00dften Skandal verursachen?", "es": "Si todos intercambi\u00e1ramos tel\u00e9fonos por 5 minutos, \u00bfcu\u00e1l causar\u00eda el mayor esc\u00e1ndalo?", "pt": "Se todos troc\u00e1ssemos de telem\u00f3vel por 5 minutos, qual causaria o maior esc\u00e2ndalo?", "ro": "Dac\u0103 ne-am schimba telefoanele timp de 5 minute, al cui ar provoca cel mai mare scandal?", "fr": "Si on \u00e9changeait tous nos t\u00e9l\u00e9phones pendant 5 minutes, lequel causerait le plus grand scandale ?", "it": "Se tutti noi scambiassimo i telefoni per 5 minuti, il quale causerebbe il maggior scandalo?", "fi": "Jos me kaikki vaihdettaisiin puhelimia viideksi minuutiksi, kenen puhelin aiheuttaisi suurimman skandaalin?", "nl": "Als we allemaal 5 minuten van telefoon zouden wisselen, wiens zou de grootste schandaal veroorzaken?", "no": "Hvis vi alle byttet telefoner i 5 minutter, hvis sin ville skape den st\u00f8rste skandalen?", "sv": "Om vi alla bytte telefoner i 5 minuter, vems skulle orsaka den st\u00f6rsta skandalen?", "pl": "Je\u015bli wszyscy zamieniliby\u015bmy si\u0119 telefonami na 5 minut, czyj telefon wywo\u0142a\u0142by najwi\u0119kszy skandal?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If we all swapped phones for 5 minutes, whose would cause the biggest scandal?';
UPDATE questions
SET translations = '{"en": "You win a free vacation \u2014 but you can only bring one friend from this room. Who\u2019s your pick and why?", "da": "Du vinder en gratis ferie \u2014 men du m\u00e5 kun tage \u00e9n ven fra dette rum. Hvem v\u00e6lger du og hvorfor?", "de": "Du gewinnst einen kostenlosen Urlaub \u2013 aber du darfst nur einen Freund aus diesem Raum mitnehmen. Wen w\u00e4hlst du und warum?", "es": "Ganas unas vacaciones gratis \u2014 pero solo puedes llevar a un amigo de esta sala. \u00bfA qui\u00e9n eliges y por qu\u00e9?", "pt": "Ganhas umas f\u00e9rias gr\u00e1tis \u2014 mas s\u00f3 podes levar um amigo desta sala. Quem escolhes e porqu\u00ea?", "ro": "C\u00e2\u0219tigi o vacan\u021b\u0103 gratuit\u0103 \u2014 dar po\u021bi lua doar un prieten din aceast\u0103 camer\u0103. Pe cine alegi \u0219i de ce?", "fr": "Tu gagnes des vacances gratuites \u2014 mais tu ne peux emmener qu\u2019un ami d\u2019ici. Qui choisis-tu et pourquoi ?", "it": "Vinci una vacanza gratis \u2014 ma puoi portare solo un amico di questa stanza. Chi scegli e perch\u00e9?", "fi": "Voitat ilmaisen loman \u2014 mutta voit tuoda vain yhden yst\u00e4v\u00e4n t\u00e4st\u00e4 huoneesta. Kuka on valintasi ja miksi?", "nl": "Je wint een gratis vakantie \u2014 maar je mag maar \u00e9\u00e9n vriend uit deze kamer meenemen. Wie kies je en waarom?", "no": "Du vinner en gratis ferie \u2014 men du kan bare ta med deg \u00e9n venn fra dette rommet. Hvem velger du og hvorfor?", "sv": "Du vinner en gratis semester \u2014 men du kan bara ta med en v\u00e4n fr\u00e5n det h\u00e4r rummet. Vem v\u00e4ljer du och varf\u00f6r?", "pl": "Wygrywasz darmowe wakacje \u2014 ale mo\u017cesz zabra\u0107 tylko jednego przyjaciela z tego pokoju. Kogo wybierasz i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You win a free vacation — but you can only bring one friend from this room. Who’s your pick and why?';
UPDATE questions
SET translations = '{"en": "Who in this group would survive a zombie apocalypse the longest?", "da": "Hvem i denne gruppe ville overleve l\u00e6ngst i en zombieapokalypse?", "de": "Wer in dieser Gruppe w\u00fcrde eine Zombie-Apokalypse am l\u00e4ngsten \u00fcberleben?", "es": "\u00bfQui\u00e9n de este grupo sobrevivir\u00eda m\u00e1s tiempo a un apocalipsis zombi?", "pt": "Quem deste grupo sobreviveria mais tempo a um apocalipse zombie?", "ro": "Cine din acest grup ar supravie\u021bui cel mai mult \u00eentr-o apocalips\u0103 cu zombi?", "fr": "Qui dans ce groupe survivrait le plus longtemps \u00e0 une apocalypse zombie ?", "it": "Chi in questo gruppo sopravviverebbe pi\u00f9 a lungo a un''apocalisse zombie?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 selviytyisi pisimp\u00e4\u00e4n zombi-apokalypsiss\u00e4?", "nl": "Wie in deze groep zou het langst overleven tijdens een zombie-apocalyps?", "no": "Hvem i denne gruppen ville overlevd en zombieapokalypse lengst?", "sv": "Vem i den h\u00e4r gruppen skulle \u00f6verleva en zombieapokalyps l\u00e4ngst?", "pl": "Kto w tej grupie przetrwa\u0142by najd\u0142u\u017cej podczas apokalipsy zombie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who in this group would survive a zombie apocalypse the longest?';
UPDATE questions
SET translations = '{"en": "If one of us became famous, who would handle it the best?", "da": "Hvis en af os blev ber\u00f8mt, hvem ville h\u00e5ndtere det bedst?", "de": "Wenn einer von uns ber\u00fchmt w\u00fcrde, wer k\u00e4me am besten damit zurecht?", "es": "Si uno de nosotros se hiciera famoso, \u00bfqui\u00e9n lo manejar\u00eda mejor?", "pt": "Se um de n\u00f3s se tornasse famoso, quem lidaria melhor com isso?", "ro": "Dac\u0103 unul dintre noi ar deveni faimos, cine s-ar descurca cel mai bine?", "fr": "Si l\u2019un de nous devenait c\u00e9l\u00e8bre, qui le g\u00e9rerait le mieux ?", "it": "Se uno di noi diventasse famoso, chi lo gestirebbe meglio?", "fi": "Jos joku meist\u00e4 tulisi kuuluisaksi, kuka k\u00e4sittelisi sit\u00e4 parhaiten?", "nl": "Als een van ons beroemd zou worden, wie zou daar het beste mee omgaan?", "no": "Hvis en av oss ble ber\u00f8mt, hvem ville taklet det best?", "sv": "Om en av oss blev ber\u00f6md, vem skulle hantera det b\u00e4st?", "pl": "Je\u015bli jedno z nas sta\u0142oby si\u0119 s\u0142awne, kto poradzi\u0142by sobie z tym najlepiej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If one of us became famous, who would handle it the best?';
UPDATE questions
SET translations = '{"en": "Who would you trust to delete your search history if you died suddenly?", "da": "Hvem ville du stole p\u00e5 til at slette din s\u00f8gehistorik, hvis du d\u00f8de pludseligt?", "de": "Wem w\u00fcrdest du vertrauen, deinen Suchverlauf zu l\u00f6schen, wenn du pl\u00f6tzlich sterben w\u00fcrdest?", "es": "\u00bfEn qui\u00e9n confiar\u00edas para borrar tu historial si murieras de repente?", "pt": "Em quem confiarias para apagar o teu hist\u00f3rico de pesquisa se morresses de repente?", "ro": "\u00cen cine ai avea \u00eencredere s\u0103-\u021bi \u0219tearg\u0103 istoricul de c\u0103utare dac\u0103 ai muri brusc?", "fr": "\u00c0 qui ferais-tu confiance pour effacer ton historique de recherche si tu mourais soudainement ?", "it": "A chi faresti fiducia per eliminare la tua cronologia di ricerca se dovessi morire all''improvviso?", "fi": "Kenelle luottaisit poistamaan hakuhistoriasi, jos kuolisit \u00e4killisesti?", "nl": "Wie zou je vertrouwen om je zoekgeschiedenis te verwijderen als je plotseling zou overlijden?", "no": "Hvem ville du stole p\u00e5 til \u00e5 slette s\u00f8kehistorikken din hvis du d\u00f8de plutselig?", "sv": "Vem skulle du lita p\u00e5 att radera din s\u00f6khistorik om du pl\u00f6tsligt dog?", "pl": "Kogo by\u015b zaufa\u0142, \u017ceby usun\u0105\u0142 twoj\u0105 histori\u0119 wyszukiwania, gdyby\u015b nagle umar\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'Who would you trust to delete your search history if you died suddenly?';
UPDATE questions
SET translations = '{"en": "If someone here got arrested, who would you assume it was before even asking?", "da": "Hvis nogen her blev arresteret, hvem ville du antage, det var, uden at sp\u00f8rge?", "de": "Wenn jemand hier verhaftet w\u00fcrde, wen w\u00fcrdest du ohne zu fragen f\u00fcr schuldig halten?", "es": "Si arrestaran a alguien aqu\u00ed, \u00bfde qui\u00e9n sospechar\u00edas sin preguntar?", "pt": "Se algu\u00e9m aqui fosse preso, de quem suspeitarias sem perguntar?", "ro": "Dac\u0103 cineva de aici ar fi arestat, pe cine ai b\u0103nui f\u0103r\u0103 s\u0103 \u00eentrebi?", "fr": "Si quelqu\u2019un ici \u00e9tait arr\u00eat\u00e9, qui soup\u00e7onnerais-tu sans m\u00eame demander ?", "it": "Se qualcuno qui fosse stato arrestato, chi supporresti fosse prima ancora di chiedere?", "fi": "Jos joku t\u00e4\u00e4ll\u00e4 pid\u00e4tett\u00e4isiin, ket\u00e4 luulisit sen olevan ennen kuin edes kysyt?", "nl": "Als iemand hier gearresteerd zou worden, wie zou je dan aannemen dat het was voordat je het zelfs maar vraagt?", "no": "Hvis noen her ble arrestert, hvem ville du anta det var f\u00f8r du engang spurte?", "sv": "Om n\u00e5gon h\u00e4r blev arresterad, vem skulle du anta att det var innan du ens fr\u00e5gade?", "pl": "Gdyby kto\u015b tutaj zosta\u0142 aresztowany, kogo by\u015b podejrzewa\u0142, zanim jeszcze zapytasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'If someone here got arrested, who would you assume it was before even asking?';
UPDATE questions
SET translations = '{"en": "You have to let one friend plan your wedding \u2014 who\u2019s in charge, and who\u2019s banned?", "da": "Du skal lade \u00e9n ven planl\u00e6gge dit bryllup \u2014 hvem er ansvarlig, og hvem er forbudt?", "de": "Du musst einem Freund erlauben, deine Hochzeit zu planen \u2013 wer ist verantwortlich und wer ist verboten?", "es": "Tienes que dejar que un amigo planifique tu boda \u2014 \u00bfqui\u00e9n est\u00e1 a cargo y qui\u00e9n est\u00e1 vetado?", "pt": "Tens de deixar um amigo planear o teu casamento \u2014 quem fica encarregado e quem \u00e9 proibido?", "ro": "Trebuie s\u0103 la\u0219i un prieten s\u0103-\u021bi planifice nunta \u2014 cine se ocup\u0103 \u0219i cine e interzis?", "fr": "Tu dois laisser un ami organiser ton mariage \u2014 qui est en charge et qui est banni ?", "it": "Devi lasciare che un amico organizzi il tuo matrimonio \u2014 chi \u00e8 in carica e chi \u00e8 bandito?", "fi": "Sinun t\u00e4ytyy antaa yhden yst\u00e4v\u00e4n suunnitella h\u00e4\u00e4t \u2014 kuka on vastuussa ja kuka on kielletty?", "nl": "Je moet \u00e9\u00e9n vriend de planning van je bruiloft laten doen \u2014 wie is de baas en wie is verbannen?", "no": "Du m\u00e5 la en venn planlegge bryllupet ditt - hvem har ansvaret, og hvem er utestengt?", "sv": "Du m\u00e5ste l\u00e5ta en v\u00e4n planera ditt br\u00f6llop \u2014 vem \u00e4r ansvarig, och vem \u00e4r bannlyst?", "pl": "Musisz pozwoli\u0107 jednemu przyjacielowi zaplanowa\u0107 twoje wesele \u2014 kto jest odpowiedzialny, a kto jest zakazany?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Plot Twists & Dilemmas '
  AND translations->>'en' = 'You have to let one friend plan your wedding — who’s in charge, and who’s banned?';