UPDATE questions
SET translations = '{"en": "What three emojis summarize your travel style?", "da": "Hvilke tre emojis opsummerer din rejse-stil?", "de": "Welche drei Emojis beschreiben deinen Reisestil?", "es": "\u00bfQu\u00e9 tres emojis resumen tu estilo de viaje?", "pt": "Quais tr\u00eas emojis resumem seu estilo de viagem?", "ro": "Care trei emoji \u00ee\u021bi rezum\u0103 stilul de c\u0103l\u0103torie?", "fr": "Quels trois emojis r\u00e9sument ton style de voyage ?", "it": "Quali tre emoji riassumono il tuo stile di viaggio?", "fi": "Mitk\u00e4 kolme emojia kuvaavat parhaiten matkustustyyli\u00e4si?", "nl": "Welke drie emoji\u2019s vatten jouw reisstijl samen?", "no": "Hvilke tre emojier oppsummerer reisestilen din?", "sv": "Vilka tre emojis sammanfattar din resestil?", "pl": "Jakie trzy emoji podsumowuj\u0105 tw\u00f3j styl podr\u00f3\u017cowania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What three emojis summarize your travel style?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell that takes you straight back to childhood?", "da": "Hvilken duft sender dig direkte tilbage til barndommen?", "de": "Welcher Geruch versetzt dich sofort in deine Kindheit zur\u00fcck?", "es": "\u00bfQu\u00e9 olor te transporta directamente a tu infancia?", "pt": "Que cheiro te leva diretamente de volta \u00e0 inf\u00e2ncia?", "ro": "Ce miros te trimite direct \u00een copil\u0103rie?", "fr": "Quelle odeur te ram\u00e8ne directement \u00e0 ton enfance ?", "it": "Quale odore ti riporta immediatamente all\u2019infanzia?", "fi": "Mik\u00e4 tuoksu vie sinut suoraan takaisin lapsuuteen?", "nl": "Welke geur brengt je meteen terug naar je kindertijd?", "no": "Hvilken lukt sender deg rett tilbake til barndommen?", "sv": "Vilken doft tar dig direkt tillbaka till barndomen?", "pl": "Jaki zapach przenosi ci\u0119 prosto do dzieci\u0144stwa?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a smell that takes you straight back to childhood?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite \u201cdo nothing\u201d activity \u2014 the thing that totally recharges you?", "da": "Hvad er din yndlings \u201clav ingenting\u201d-aktivitet \u2014 den der virkelig lader dig op?", "de": "Was ist deine Lieblings-\u201eNichts-tun\u201c-Aktivit\u00e4t \u2013 die, die dich wirklich aufl\u00e4dt?", "es": "\u00bfCu\u00e1l es tu actividad favorita de \u201cno hacer nada\u201d, la que realmente te recarga?", "pt": "Qual \u00e9 a sua atividade favorita de \u201cn\u00e3o fazer nada\u201d \u2014 que te recarrega totalmente?", "ro": "Care este activitatea ta preferat\u0103 de \u201ea nu face nimic\u201d \u2014 cea care te re\u00eencarc\u0103 complet?", "fr": "Quelle est ton activit\u00e9 \u00ab ne rien faire \u00bb pr\u00e9f\u00e9r\u00e9e \u2014 celle qui te ressource compl\u00e8tement ?", "it": "Qual \u00e8 la tua attivit\u00e0 preferita da \u201cnon fare niente\u201d, quella che ti ricarica del tutto?", "fi": "Mik\u00e4 on lempisi \u201cen tee mit\u00e4\u00e4n\u201d -aktiviteetti \u2013 se, joka lataa akut t\u00e4ysin?", "nl": "Wat is je favoriete \u201cniks doen\u201d-activiteit \u2013 die ene die je helemaal oplaadt?", "no": "Hva er din favoritt-\u00abgj\u00f8re ingenting\u00bb-aktivitet \u2013 den som virkelig lader deg opp?", "sv": "Vad \u00e4r din favorit-\u201dg\u00f6ra ingenting\u201d-aktivitet \u2013 den som verkligen laddar dig?", "pl": "Jaka jest twoja ulubiona aktywno\u015b\u0107 \u201enicnierobienia\u201d \u2013 ta, kt\u00f3ra naprawd\u0119 ci\u0119 \u0142aduje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s your favorite “do nothing” activity — the thing that totally recharges you?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing that instantly puts you in a good mood, no matter what?", "da": "Hvad f\u00e5r dig straks i godt hum\u00f8r, uanset hvad?", "de": "Was bringt dich sofort in gute Laune, egal was passiert?", "es": "\u00bfQu\u00e9 cosa te pone instant\u00e1neamente de buen humor, sin importar qu\u00e9?", "pt": "O que te p\u00f5e imediatamente de bom humor, aconte\u00e7a o que acontecer?", "ro": "Ce te binedispune instantaneu, indiferent de situa\u021bie?", "fr": "Qu\u2019est-ce qui te met instantan\u00e9ment de bonne humeur, peu importe quoi ?", "it": "Qual \u00e8 una cosa che ti mette subito di buon umore, a prescindere da tutto?", "fi": "Mik\u00e4 yksi juttu tekee sinut heti hyv\u00e4lle tuulelle, tilanteesta riippumatta?", "nl": "Wat is \u00e9\u00e9n ding dat je meteen in een goed humeur brengt, wat er ook gebeurt?", "no": "Hva er \u00e9n ting som alltid f\u00e5r deg i godt hum\u00f8r, uansett?", "sv": "Vad \u00e4r en sak som direkt g\u00f6r dig p\u00e5 gott hum\u00f6r, oavsett vad?", "pl": "Co jest jedn\u0105 rzecz\u0105, kt\u00f3ra natychmiast poprawia ci humor, niezale\u017cnie od wszystkiego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s one thing that instantly puts you in a good mood, no matter what?';
UPDATE questions
SET translations = '{"en": "Ever forgotten something on a camping trip that you really needed?", "da": "Har du nogensinde glemt noget p\u00e5 en campingtur, som du virkelig havde brug for?", "de": "Hast du jemals etwas auf einem Campingausflug vergessen, das du wirklich gebraucht h\u00e4ttest?", "es": "\u00bfAlguna vez olvidaste algo en un campamento que realmente necesitabas?", "pt": "Voc\u00ea j\u00e1 esqueceu algo em um acampamento que realmente precisava?", "ro": "Ai uitat vreodat\u0103 ceva \u00eentr-o excursie cu cortul de care aveai mare nevoie?", "fr": "As-tu d\u00e9j\u00e0 oubli\u00e9 quelque chose d\u2019essentiel en camping ?", "it": "Ti \u00e8 mai capitato di dimenticare qualcosa in campeggio di cui avevi davvero bisogno?", "fi": "Oletko koskaan unohtanut jotain leirireissulle, mit\u00e4 oikeasti tarvitsit?", "nl": "Ben je ooit op kampeertrip iets vergeten dat je echt nodig had?", "no": "Har du noen gang glemt noe p\u00e5 campingtur som du virkelig trengte?", "sv": "Har du n\u00e5gonsin gl\u00f6mt n\u00e5got p\u00e5 en campingresa som du verkligen beh\u00f6vde?", "pl": "Zdarzy\u0142o ci si\u0119 kiedy\u015b zapomnie\u0107 na biwak czego\u015b, czego naprawd\u0119 potrzebowa\u0142e\u015b/potrzebowa\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Ever forgotten something on a camping trip that you really needed?';
UPDATE questions
SET translations = '{"en": "How do you balance plans vs. spontaneity on a trip?", "da": "Hvordan balancerer du planer vs. spontanitet p\u00e5 en rejse?", "de": "Wie balancierst du Planung und Spontaneit\u00e4t auf einer Reise?", "es": "\u00bfC\u00f3mo equilibras los planes y la espontaneidad en un viaje?", "pt": "Como equilibras planos e espontaneidade numa viagem?", "ro": "Cum echilibrezi planurile \u0219i spontaneitatea \u00eentr-o excursie?", "fr": "Comment \u00e9quilibres-tu les plans et la spontan\u00e9it\u00e9 lors d\u2019un voyage ?", "it": "Come bilanci i piani e la spontaneit\u00e0 in viaggio?", "fi": "Miten tasapainotat suunnitelmat ja spontaaniuden matkalla?", "nl": "Hoe balanceer jij plannen maken en spontaniteit op reis?", "no": "Hvordan balanserer du planer og spontanitet p\u00e5 tur?", "sv": "Hur balanserar du planering och spontanitet p\u00e5 en resa?", "pl": "Jak \u0142\u0105czysz planowanie ze spontaniczno\u015bci\u0105 w podr\u00f3\u017cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'How do you balance plans vs. spontaneity on a trip?';
UPDATE questions
SET translations = '{"en": "What\u2019s our optimal roles on a long drive (e.g. captain, DJ, snack provider, etc)?", "da": "Hvad er vores optimale roller p\u00e5 en lang k\u00f8retur (f.eks. kaptajn, DJ, snack-ansvarlig osv.)?", "de": "Was sind unsere optimalen Rollen auf einer langen Fahrt (z. B. Kapit\u00e4n, DJ, Snacklieferant usw.)?", "es": "\u00bfCu\u00e1les son nuestros roles ideales en un viaje largo (por ejemplo, capit\u00e1n, DJ, proveedor de snacks, etc.)?", "pt": "Quais s\u00e3o os nossos pap\u00e9is ideais numa longa viagem (por exemplo, capit\u00e3o, DJ, fornecedor de snacks, etc.)?", "ro": "Care sunt rolurile noastre ideale \u00eentr-o c\u0103l\u0103torie lung\u0103 (ex: c\u0103pitan, DJ, furnizor de gust\u0103ri etc.)?", "fr": "Quels sont nos r\u00f4les id\u00e9aux lors d\u2019un long trajet (ex : capitaine, DJ, fournisseur de snacks, etc.) ?", "it": "Quali sarebbero i nostri ruoli ideali in un lungo viaggio in auto (es. capitano, DJ, addetto agli snack, ecc.)?", "fi": "Mitk\u00e4 ovat meille parhaat roolit pitk\u00e4ll\u00e4 ajomatkalla (esim. kapteeni, DJ, v\u00e4lipalavastaava jne.)?", "nl": "Wat zijn onze ideale rollen tijdens een lange autorit (bijv. kapitein, DJ, snack-leverancier, etc.)?", "no": "Hva er v\u00e5re optimale roller p\u00e5 en lang biltur (f.eks. kaptein, DJ, snacksansvarlig osv.)?", "sv": "Vilka \u00e4r v\u00e5ra optimala roller p\u00e5 en l\u00e5ng bilresa (t.ex. kapten, DJ, snacksansvarig osv.)?", "pl": "Jakie s\u0105 dla nas idealne role podczas d\u0142ugiej jazdy autem (np. kapitan, DJ, dostawca przek\u0105sek itp.)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s our optimal roles on a long drive (e.g. captain, DJ, snack provider, etc)?';
UPDATE questions
SET translations = '{"en": "What\u2019s a moment when you felt totally fearless?", "da": "Hvorn\u00e5r f\u00f8lte du dig helt frygtl\u00f8s?", "de": "Wann hast du dich v\u00f6llig furchtlos gef\u00fchlt?", "es": "\u00bfCu\u00e1ndo te has sentido completamente sin miedo?", "pt": "Quando te sentiste totalmente destemido(a)?", "ro": "C\u00e2nd te-ai sim\u021bit complet ne\u00eenfricat(\u0103)?", "fr": "\u00c0 quel moment t\u2019es-tu senti(e) totalement sans peur ?", "it": "Racconta un momento in cui ti sei sentito/a totalmente senza paura.", "fi": "Kerro hetki, jolloin tunsit olosi t\u00e4ysin pelottomaksi.", "nl": "Noem een moment waarop je je totaal onbevreesd voelde.", "no": "Fortell om et \u00f8yeblikk der du f\u00f8lte deg helt fryktl\u00f8s.", "sv": "Ber\u00e4tta om ett tillf\u00e4lle d\u00e5 du k\u00e4nde dig helt or\u00e4dd.", "pl": "Opowiedz o chwili, kiedy czu\u0142e\u015b/czu\u0142a\u015b si\u0119 ca\u0142kowicie nieustraszony/a."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s a moment when you felt totally fearless?';
UPDATE questions
SET translations = '{"en": "Describe your dream scenic route and what we\u2019d do there.", "da": "Beskriv din dr\u00f8mmesceniske rute og hvad vi ville g\u00f8re der.", "de": "Beschreibe deine Traumroute und was wir dort tun w\u00fcrden.", "es": "Describe tu ruta esc\u00e9nica de ensue\u00f1o y qu\u00e9 har\u00edamos all\u00ed.", "pt": "Descreve a tua rota panor\u00e2mica de sonho e o que far\u00edamos l\u00e1.", "ro": "Descrie traseul t\u0103u de vis \u0219i ce am face acolo.", "fr": "D\u00e9cris ton itin\u00e9raire de r\u00eave et ce qu\u2019on y ferait.", "it": "Descrivi il tuo percorso panoramico da sogno e cosa faremmo l\u00ec.", "fi": "Kuvaile unelmiesi maisemareitti ja mit\u00e4 tekisimme siell\u00e4.", "nl": "Beschrijf je droom-scenische route en wat we daar zouden doen.", "no": "Beskriv dr\u00f8mmeruten din med fin utsikt, og hva vi skulle gjort der.", "sv": "Beskriv din dr\u00f6mmiga natursk\u00f6na rutt och vad vi skulle g\u00f6ra d\u00e4r.", "pl": "Opisz swoj\u0105 wymarzon\u0105 widokow\u0105 tras\u0119 i to, co by\u015bmy tam robili."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'Describe your dream scenic route and what we’d do there.';
UPDATE questions
SET translations = '{"en": "What\u2019s the strangest or funniest dream you\u2019ve ever had?", "da": "Hvad er den m\u00e6rkeligste eller sjoveste dr\u00f8m, du nogensinde har haft?", "de": "Was ist der seltsamste oder lustigste Traum, den du je hattest?", "es": "\u00bfCu\u00e1l es el sue\u00f1o m\u00e1s extra\u00f1o o divertido que has tenido?", "pt": "Qual foi o sonho mais estranho ou engra\u00e7ado que j\u00e1 tiveste?", "ro": "Care este cel mai ciudat sau amuzant vis pe care l-ai avut vreodat\u0103?", "fr": "Quel est le r\u00eave le plus \u00e9trange ou le plus dr\u00f4le que tu aies jamais fait ?", "it": "Qual \u00e8 il sogno pi\u00f9 strano o pi\u00f9 divertente che tu abbia mai fatto?", "fi": "Mik\u00e4 on oudoin tai hauskin uni, jonka olet koskaan n\u00e4hnyt?", "nl": "Wat is de vreemdste of grappigste droom die je ooit hebt gehad?", "no": "Hva er den rareste eller morsomste dr\u00f8mmen du har hatt?", "sv": "Vad \u00e4r den konstigaste eller roligaste dr\u00f6m du n\u00e5gonsin haft?", "pl": "Jaki jest najdziwniejszy albo najzabawniejszy sen, jaki kiedykolwiek mia\u0142e\u015b/mia\u0142a\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Car Talks'
  AND translations->>'en' = 'What’s the strangest or funniest dream you’ve ever had?';