UPDATE questions
SET translations = '{"en": "What kind of restraint or surrender do you secretly find hot?", "da": "Hvilken form for tilbageholdenhed eller overgivelse synes du i hemmelighed er hot?", "de": "Welche Art von Zur\u00fcckhaltung oder Hingabe findest du heimlich hei\u00df?", "es": "\u00bfQu\u00e9 tipo de control o rendici\u00f3n secreta te parece m\u00e1s excitante?", "pt": "Que tipo de controlo ou entrega secreta te parece mais excitante?", "ro": "Ce fel de control sau abandon \u021bi se pare secret \u0219i excitant?", "fr": "Quelle forme de contr\u00f4le ou de soumission trouves-tu secr\u00e8tement excitante ?", "it": "Che tipo di restrizione o resa trovi segretamente eccitante?", "fi": "Mink\u00e4laista pid\u00e4t salaa kuumana, kun on kyse pid\u00e4tyksest\u00e4 tai antautumisesta?", "nl": "Welke vorm van beperking of overgave vind je stiekem opwindend?", "no": "Hvilken type tilbakeholdenhet eller overgivelse synes du hemmelig er sexy?", "sv": "Vilken typ av begr\u00e4nsning eller \u00f6verl\u00e5telse tycker du hemligt \u00e4r sexig?", "pl": "Jakiego rodzaju pow\u015bci\u0105gni\u0119cie lub poddanie si\u0119 potajemnie uwa\u017casz za poci\u0105gaj\u0105ce?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What kind of restraint or surrender do you secretly find hot?';
UPDATE questions
SET translations = '{"en": "What\u2019s a part of your body you wish I\u2019d pay more attention to?", "da": "Hvilken del af din krop ville du \u00f8nske, jeg ville v\u00e6re mere opm\u00e6rksom p\u00e5?", "de": "Welchen Teil deines K\u00f6rpers w\u00fcnschst du dir, dass ich mehr beachte?", "es": "\u00bfQu\u00e9 parte de tu cuerpo quisieras que yo prestara m\u00e1s atenci\u00f3n?", "pt": "Que parte do teu corpo gostarias que eu prestasse mais aten\u00e7\u00e3o?", "ro": "Ce parte a corpului t\u0103u \u021bi-ai dori s\u0103 o explorez mai mult?", "fr": "Quelle partie de ton corps aimerais-tu que je remarque davantage ?", "it": "Quale parte del tuo corpo vorresti che io prestassi pi\u00f9 attenzione?", "fi": "Mik\u00e4 osa kehostasi on sellainen, johon toivoisit minun kiinnitt\u00e4v\u00e4n enemm\u00e4n huomiota?", "nl": "Welke deel van je lichaam zou je willen dat ik meer aandacht aan besteed?", "no": "Hvilken del av kroppen din \u00f8nsker du at jeg skulle legge mer merke til?", "sv": "Vilken del av din kropp \u00f6nskar du att jag skulle l\u00e4gga mer m\u00e4rke till?", "pl": "Jak\u0105 cz\u0119\u015bci\u0105 swojego cia\u0142a chcia\u0142by\u015b, \u017cebym po\u015bwi\u0119ci\u0142 wi\u0119cej uwagi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s a part of your body you wish I’d pay more attention to?';
UPDATE questions
SET translations = '{"en": "How do you feel about pushing our comfort zone with something that feels slightly forbidden?", "da": "Hvad synes du om at presse vores komfortzone med noget, der f\u00f8les en smule forbudt?", "de": "Wie findest du es, unsere Komfortzone mit etwas leicht Verbotenem zu erweitern?", "es": "\u00bfQu\u00e9 opinas de empujar nuestros l\u00edmites con algo que se sienta un poco prohibido?", "pt": "O que achas de ultrapassarmos os nossos limites com algo que pare\u00e7a um pouco proibido?", "ro": "Ce p\u0103rere ai despre a dep\u0103\u0219i limitele cu ceva ce pare pu\u021bin interzis?", "fr": "Que penses-tu d\u2019explorer nos limites avec quelque chose d\u2019un peu interdit ?", "it": "Come ti senti riguardo a spingere il nostro comfort zone con qualcosa che sembra leggermente proibito?", "fi": "Milt\u00e4 sinusta tuntuu, ett\u00e4 ty\u00f6nt\u00e4isimme mukavuusaluettamme johonkin, mik\u00e4 tuntuu hieman kielletylt\u00e4?", "nl": "Hoe voel je je over het verleggen van onze comfortzone met iets dat een beetje verboden aanvoelt?", "no": "Hvordan f\u00f8ler du om \u00e5 presse komfortsonen v\u00e5r med noe som f\u00f8les litt forbudt?", "sv": "Hur k\u00e4nner du f\u00f6r att t\u00e4nja p\u00e5 v\u00e5ra gr\u00e4nser med n\u00e5got som k\u00e4nns lite f\u00f6rbjudet?", "pl": "Jak si\u0119 czujesz z pomys\u0142em na poszerzenie naszej strefy komfortu w czym\u015b, co wydaje si\u0119 lekko zakazane?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'How do you feel about pushing our comfort zone with something that feels slightly forbidden?';
UPDATE questions
SET translations = '{"en": "Have you ever held back because you didn\u2019t want to shock me?", "da": "Har du nogensinde holdt dig tilbage, fordi du ikke ville chokere mig?", "de": "Hast du dich jemals zur\u00fcckgehalten, weil du mich nicht schockieren wolltest?", "es": "\u00bfAlguna vez te has contenido por miedo a sorprenderme?", "pt": "J\u00e1 te contiveste por medo de me chocar?", "ro": "Te-ai re\u021binut vreodat\u0103 pentru c\u0103 nu ai vrut s\u0103 m\u0103 \u0219ochezi?", "fr": "T\u2019es-tu d\u00e9j\u00e0 retenu(e) par peur de me choquer ?", "it": "Hai mai trattenuto qualcosa perch\u00e9 non volevi scioccarmi?", "fi": "Oletko koskaan pid\u00e4tellyt itse\u00e4si, koska et halunnut j\u00e4rkytt\u00e4\u00e4 minua?", "nl": "Heb je ooit iets achtergehouden omdat je me niet wilde schokken?", "no": "Har du noen gang holdt tilbake fordi du ikke ville sjokkere meg?", "sv": "Har du n\u00e5gonsin h\u00e5llit tillbaka f\u00f6r att du inte ville chocka mig?", "pl": "Czy kiedykolwiek powstrzyma\u0142e\u015b si\u0119, poniewa\u017c nie chcia\u0142e\u015b mnie zszokowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Have you ever held back because you didn’t want to shock me?';
UPDATE questions
SET translations = '{"en": "What\u2019s something playful you wish we did more often?", "da": "Hvad er noget legende, du ville \u00f8nske, vi gjorde oftere?", "de": "Was ist etwas Verspieltes, das du dir w\u00fcnschst, wir w\u00fcrden \u00f6fter tun?", "es": "\u00bfQu\u00e9 cosa juguetona te gustar\u00eda que hici\u00e9ramos m\u00e1s a menudo?", "pt": "Que coisa divertida gostarias que fiz\u00e9ssemos mais vezes?", "ro": "Ce lucru juc\u0103u\u0219 ai vrea s\u0103 facem mai des?", "fr": "Quelle chose ludique aimerais-tu qu\u2019on fasse plus souvent ?", "it": "Qualcosa di giocoso che vorresti facessimo pi\u00f9 spesso?", "fi": "Mik\u00e4 on jokin leikkis\u00e4 asia, jota toivoisit tekev\u00e4mme useammin?", "nl": "Wat is iets speels dat je wenst dat we vaker deden?", "no": "Hva er noe lekent du skulle \u00f8nske vi gjorde oftere?", "sv": "Vad \u00e4r n\u00e5got lekfullt som du \u00f6nskar att vi gjorde oftare?", "pl": "Co\u015b zabawnego, co chcia\u0142by\u015b, \u017ceby\u015bmy robili cz\u0119\u015bciej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s something playful you wish we did more often?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite time of day to get intimate?", "da": "Hvad er dit yndlingstidspunkt p\u00e5 dagen at blive intim?", "de": "Was ist deine Lieblingszeit am Tag, um intim zu werden?", "es": "\u00bfCu\u00e1l es tu momento favorito del d\u00eda para ser \u00edntimos?", "pt": "Qual \u00e9 o teu momento favorito do dia para sermos \u00edntimos?", "ro": "Care este momentul t\u0103u preferat al zilei pentru a fi intimi?", "fr": "Quel est ton moment pr\u00e9f\u00e9r\u00e9 de la journ\u00e9e pour \u00eatre intime ?", "it": "Qual \u00e8 il tuo momento preferito della giornata per essere intimo?", "fi": "Mik\u00e4 on suosikkiaikasi p\u00e4iv\u00e4st\u00e4 intiimiyteen?", "nl": "Wat is jouw favoriete tijd van de dag om intiem te zijn?", "no": "Hva er ditt favorittidspunkt p\u00e5 dagen for \u00e5 bli intim?", "sv": "Vilken tid p\u00e5 dagen tycker du b\u00e4st om att vara intim?", "pl": "Jaka jest twoja ulubiona pora dnia na intymno\u015b\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'What’s your favorite time of day to get intimate?';
UPDATE questions
SET translations = '{"en": "Which of us is more likely to start something and pretend it\u2019s innocent?", "da": "Hvem af os er mest tilb\u00f8jelig til at starte noget og lade som om, det er uskyldigt?", "de": "Wer von uns f\u00e4ngt am ehesten etwas an und tut so, als w\u00e4re es unschuldig?", "es": "\u00bfQui\u00e9n de los dos es m\u00e1s propenso a empezar algo y fingir que es inocente?", "pt": "Quem de n\u00f3s tem mais tend\u00eancia a come\u00e7ar algo fingindo ser inocente?", "ro": "Cine dintre noi \u00eencepe ceva pref\u0103c\u00e2ndu-se c\u0103 e nevinovat(\u0103)?", "fr": "Lequel de nous deux commence quelque chose en faisant semblant d\u2019\u00eatre innocent(e) ?", "it": "Quale di noi \u00e8 pi\u00f9 probabile che inizi qualcosa e faccia finta che sia innocente?", "fi": "Kumpi meist\u00e4 on todenn\u00e4k\u00f6isemmin se, joka aloittaa jotain ja esitt\u00e4\u00e4 sen viattomana?", "nl": "Wie van ons is waarschijnlijker om iets te beginnen en te doen alsof het onschuldig is?", "no": "Hvem av oss er mer sannsynlig til \u00e5 starte noe og late som om det er uskyldig?", "sv": "Vilken av oss \u00e4r mer ben\u00e4gen att starta n\u00e5got och l\u00e5tsas att det \u00e4r oskyldigt?", "pl": "Kto z nas jest bardziej sk\u0142onny do rozpocz\u0119cia czego\u015b i udawania, \u017ce to niewinne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us is more likely to start something and pretend it’s innocent?';
UPDATE questions
SET translations = '{"en": "Which of us hides it worse when we\u2019re turned on?", "da": "Hvem af os skjuler det v\u00e6rst, n\u00e5r vi er t\u00e6ndte? ", "de": "Wer von uns kann seine Erregung am schlechtesten verbergen?", "es": "\u00bfQui\u00e9n de los dos disimula peor cuando est\u00e1 excitado/a?", "pt": "Quem de n\u00f3s disfar\u00e7a pior quando est\u00e1 excitado/a?", "ro": "Cine dintre noi ascunde cel mai prost c\u00e2nd este excitat(\u0103)?", "fr": "Lequel de nous deux cache le moins bien quand il/elle est excit\u00e9(e) ?", "it": "Chi di noi lo nasconde peggio quando \u00e8 eccitato?", "fi": "Kumpi meist\u00e4 piilottaa sen huonommin, kun olemme kiihottuneita?", "nl": "Wie van ons verbergt het slechter als we opgewonden zijn?", "no": "Hvem av oss skjuler det d\u00e5rligere n\u00e5r vi er tent?", "sv": "Vilken av oss d\u00f6ljer det s\u00e4mst n\u00e4r vi \u00e4r upphetsade?", "pl": "Kto z nas gorzej to ukrywa, gdy jeste\u015bmy podnieceni?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us hides it worse when we’re turned on?';
UPDATE questions
SET translations = '{"en": "Which of us do you think loses focus faster when the flirting starts?", "da": "Hvem af os tror du mister fokus hurtigere, n\u00e5r flirten starter?", "de": "Wer von uns verliert schneller den Fokus, wenn das Flirten beginnt?", "es": "\u00bfQui\u00e9n de los dos pierde la concentraci\u00f3n m\u00e1s r\u00e1pido cuando empieza el coqueteo?", "pt": "Quem de n\u00f3s perde a concentra\u00e7\u00e3o mais depressa quando a provoca\u00e7\u00e3o come\u00e7a?", "ro": "Cine dintre noi \u00ee\u0219i pierde mai repede concentrarea c\u00e2nd \u00eencepe flirtul?", "fr": "Lequel de nous deux perd sa concentration le plus vite quand la s\u00e9duction commence ?", "it": "Chi di noi pensi che perda pi\u00f9 rapidamente la concentrazione quando inizia il flirt?", "fi": "Kumpi meist\u00e4 luulet menett\u00e4v\u00e4n keskittymisen nopeammin, kun flirttailu alkaa?", "nl": "Wie van ons denk je dat sneller de focus verliest als het flirten begint?", "no": "Hvem av oss tror du mister fokus raskere n\u00e5r fl\u00f8rtingen begynner?", "sv": "Vilken av oss tror du tappar fokus snabbare n\u00e4r flirten b\u00f6rjar?", "pl": "Kt\u00f3ry z nas, twoim zdaniem, szybciej traci koncentracj\u0119, gdy zaczyna si\u0119 flirt?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us do you think loses focus faster when the flirting starts?';
UPDATE questions
SET translations = '{"en": "Which of us likes to be in control more?", "da": "Hvem af os kan bedst lide at have kontrol?", "de": "Wer von uns mag es mehr, die Kontrolle zu haben?", "es": "\u00bfQui\u00e9n de los dos disfruta m\u00e1s teniendo el control?", "pt": "Quem de n\u00f3s gosta mais de ter o controlo?", "ro": "Cine dintre noi iube\u0219te mai mult s\u0103 de\u021bin\u0103 controlul?", "fr": "Lequel de nous deux aime le plus avoir le contr\u00f4le ?", "it": "Chi di noi ama di pi\u00f9 avere il controllo?", "fi": "Kumpi meist\u00e4 pit\u00e4\u00e4 enemm\u00e4n siit\u00e4, ett\u00e4 on kontrollissa?", "nl": "Wie van ons houdt er meer van om de controle te hebben?", "no": "Hvem av oss liker \u00e5 ha kontroll mer?", "sv": "Vilken av oss gillar att ha kontroll mer?", "pl": "Kto z nas bardziej lubi mie\u0107 kontrol\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Spicy Talks'
  AND translations->>'en' = 'Which of us likes to be in control more?';