UPDATE questions
SET translations = '{"en": "Name a hilltop, tunnel, or alley that has \u2728bad vibes\u2728.", "da": "N\u00e6vn en bakketop, tunnel eller gyde med \u2728d\u00e5rlig energi\u2728.", "de": "Nenne einen H\u00fcgel, Tunnel oder eine Gasse mit \u2728schlechter Energie\u2728.", "es": "Nombra una colina, t\u00fanel o callej\u00f3n con \u2728malas vibras\u2728.", "pt": "Nomeia uma colina, t\u00fanel ou viela com \u2728m\u00e1s energias\u2728.", "ro": "Nume\u0219te un deal, tunel sau gang cu \u2728vibra\u021bii rele\u2728.", "fr": "Nomme une colline, un tunnel ou une ruelle avec \u2728de mauvaises ondes\u2728.", "it": "Nomina una cima, un tunnel o un vicolo che ha \u2728brutte vibrazioni\u2728.", "fi": "Nime\u00e4 m\u00e4enhuippu, tunneli tai kuja, josta tulee \u2728paha fiilis\u2728.", "nl": "Noem een heuveltop, tunnel of steeg die \u2728bad vibes\u2728 heeft.", "no": "Nevn en bakketopp, tunnel eller bakgate som har \u2728d\u00e5rlig vibber\u2728.", "sv": "N\u00e4mn en kulle, tunnel eller gr\u00e4nd som har \u2728d\u00e5lig vibbe\u2728.", "pl": "Podaj nazw\u0119 wzg\u00f3rza, tunelu lub zau\u0142ka, kt\u00f3ry ma \u2728z\u0142\u0105 energi\u0119\u2728."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Name a hilltop, tunnel, or alley that has ✨bad vibes✨.';
UPDATE questions
SET translations = '{"en": "Maps suggests a \u201cfaster route\u201d through a road that doesn\u2019t exist. Do you follow it?", "da": "Kort foresl\u00e5r en \u201churtigere rute\u201d gennem en vej, der ikke findes. F\u00f8lger du den?", "de": "Maps schl\u00e4gt eine \u201eschnellere Route\u201c \u00fcber eine Stra\u00dfe vor, die nicht existiert. Folgst du ihr?", "es": "El mapa sugiere una \u201cruta m\u00e1s r\u00e1pida\u201d por un camino que no existe. \u00bfLa sigues?", "pt": "O mapa sugere uma \u201crota mais r\u00e1pida\u201d por uma estrada que n\u00e3o existe. Segues?", "ro": "Harta \u00ee\u021bi sugereaz\u0103 o \u201erut\u0103 mai rapid\u0103\u201d printr-un drum care nu exist\u0103. O urmezi?", "fr": "Le GPS te propose un \u00ab itin\u00e9raire plus rapide \u00bb par une route qui n\u2019existe pas. Tu y vas ?", "it": "Maps ti suggerisce un \u201cpercorso pi\u00f9 veloce\u201d attraverso una strada che non esiste. Lo segui?", "fi": "Karttasovellus ehdottaa \u201cnopeampaa reitti\u00e4\u201d tiet\u00e4 pitkin, jota ei ole olemassa. L\u00e4hdetk\u00f6 mukaan?", "nl": "Maps stelt een \u201csnellere route\u201d voor via een weg die niet bestaat. Volg je die?", "no": "Kart-appen foresl\u00e5r en \u00abraskere rute\u00bb via en vei som ikke finnes. F\u00f8lger du den?", "sv": "Kartappen f\u00f6resl\u00e5r en \u201dsnabbare rutt\u201d via en v\u00e4g som inte finns. F\u00f6ljer du den?", "pl": "Mapy proponuj\u0105 \u201eszybsz\u0105 tras\u0119\u201d drog\u0105, kt\u00f3ra nie istnieje. Jedziesz ni\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Maps suggests a “faster route” through a road that doesn’t exist. Do you follow it?';
UPDATE questions
SET translations = '{"en": "Your shadow lags by two seconds. Now what?", "da": "Din skygge er to sekunder bagud. Hvad nu?", "de": "Dein Schatten hinkt zwei Sekunden hinterher. Was jetzt?", "es": "Tu sombra se retrasa dos segundos. \u00bfY ahora qu\u00e9?", "pt": "A tua sombra atrasa-se dois segundos. E agora?", "ro": "Umbra ta \u00eent\u00e2rzie dou\u0103 secunde. Ce faci?", "fr": "Ton ombre a deux secondes de retard. Et maintenant ?", "it": "La tua ombra \u00e8 in ritardo di due secondi. E adesso?", "fi": "Varjosi laahaa kaksi sekuntia per\u00e4ss\u00e4. Mit\u00e4 nyt?", "nl": "Je schaduw loopt twee seconden achter. Wat doe je?", "no": "Skyggen din henger to sekunder etter. Hva gj\u00f8r du?", "sv": "Din skugga ligger tv\u00e5 sekunder efter. Vad g\u00f6r du?", "pl": "Tw\u00f3j cie\u0144 sp\u00f3\u017ania si\u0119 o dwie sekundy. I co teraz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your shadow lags by two seconds. Now what?';
UPDATE questions
SET translations = '{"en": "Something keeps \u201cgoing wrong\u201d around one person. Do you believe in the evil eye or coincidence? Defend it.", "da": "Noget g\u00e5r altid galt omkring \u00e9n person. Tror du p\u00e5 det onde \u00f8je eller tilf\u00e6ldighed? Forklar.", "de": "Um eine Person geht immer etwas schief. Glaubst du an den b\u00f6sen Blick oder Zufall? Erkl\u00e4re.", "es": "Algo siempre sale mal alrededor de una persona. \u00bfCrees en el mal de ojo o en la coincidencia? Defi\u00e9ndelo.", "pt": "Algo d\u00e1 sempre errado \u00e0 volta de uma pessoa. Acreditas no mau-olhado ou em coincid\u00eancia? Defende.", "ro": "\u00cen jurul unei persoane totul merge prost. Crezi \u00een deochi sau \u00een coinciden\u021b\u0103? Ap\u0103r\u0103-\u021bi opinia.", "fr": "Quelque chose tourne toujours mal autour d\u2019une personne. Tu crois au mauvais \u0153il ou \u00e0 la co\u00efncidence ? D\u00e9fends ton point de vue.", "it": "Intorno a una certa persona va sempre tutto \u201cstorto\u201d. Credi nel malocchio o nelle coincidenze? Difendi la tua risposta.", "fi": "Jonkun ymp\u00e4rill\u00e4 jokin menee jatkuvasti \u201cpieleen\u201d. Uskotko pahaan silm\u00e4\u00e4n vai sattumaan? Perustele.", "nl": "Rond \u00e9\u00e9n persoon blijft er steeds iets \u201cmisgaan\u201d. Geloof je in het boze oog of in toeval? Verdedig je keuze.", "no": "Rundt \u00e9n person g\u00e5r ting stadig \u00abgalt\u00bb. Tror du p\u00e5 det onde \u00f8yet eller p\u00e5 tilfeldigheter? Begrunn.", "sv": "Runt en viss person verkar saker hela tiden g\u00e5 \u201dfel\u201d. Tror du p\u00e5 onda \u00f6gat eller p\u00e5 slumpen? F\u00f6rklara.", "pl": "Wok\u00f3\u0142 jednej osoby ci\u0105gle co\u015b \u201eidzie nie tak\u201d. Wierzysz w z\u0142e oko czy w przypadek? Uzasadnij."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Something keeps “going wrong” around one person. Do you believe in the evil eye or coincidence? Defend it.';
UPDATE questions
SET translations = '{"en": "Share a folk tale or saying from your culture that\u2019s a bit spooky.", "da": "Del et folkeeventyr eller ordsprog fra din kultur, der er lidt uhyggeligt.", "de": "Teile ein Volksm\u00e4rchen oder Sprichwort aus deiner Kultur, das etwas unheimlich ist.", "es": "Comparte un cuento popular o dicho de tu cultura que sea un poco espeluznante.", "pt": "Partilha um conto ou ditado da tua cultura que seja um pouco assustador.", "ro": "Spune o legend\u0103 sau un proverb din cultura ta care e pu\u021bin \u00eenfrico\u0219\u0103tor.", "fr": "Partage un conte ou un dicton de ta culture qui est un peu effrayant.", "it": "Condividi una fiaba popolare o un detto della tua cultura che sia un po\u2019 inquietante.", "fi": "Jaa kansansatu tai sanonta omasta kulttuuristasi, joka on hieman pelottava.", "nl": "Deel een volksverhaal of uitdrukking uit jouw cultuur die een beetje griezelig is.", "no": "Del et folkeeventyr eller et uttrykk fra kulturen din som er litt skummelt.", "sv": "Dela en folksaga eller ett uttryck fr\u00e5n din kultur som \u00e4r lite kusligt.", "pl": "Podziel si\u0119 ludow\u0105 opowie\u015bci\u0105 lub powiedzonkiem z twojej kultury, kt\u00f3re jest troch\u0119 straszne."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Share a folk tale or saying from your culture that’s a bit spooky.';
UPDATE questions
SET translations = '{"en": "What\u2019s your personal early-warning sign that a place isn\u2019t safe?", "da": "Hvad er dit personlige tidlige advarselstegn p\u00e5, at et sted ikke er sikkert?", "de": "Was ist dein pers\u00f6nliches Fr\u00fchwarnzeichen, dass ein Ort nicht sicher ist?", "es": "\u00bfCu\u00e1l es tu se\u00f1al de advertencia personal de que un lugar no es seguro?", "pt": "Qual \u00e9 o teu sinal pessoal de que um lugar n\u00e3o \u00e9 seguro?", "ro": "Care este semnul t\u0103u personal c\u0103 un loc nu e sigur?", "fr": "Quel est ton signe avant-coureur personnel qu\u2019un lieu n\u2019est pas s\u00fbr ?", "it": "Qual \u00e8 il tuo segnale personale d\u2019allarme che ti dice che un posto non \u00e8 sicuro?", "fi": "Mik\u00e4 on oma varoitusmerkkisi siit\u00e4, ett\u00e4 paikka ei ole turvallinen?", "nl": "Wat is voor jou het vroegste waarschuwingssignaal dat een plek niet veilig is?", "no": "Hva er ditt personlige tidlige varsel om at et sted ikke er trygt?", "sv": "Vad \u00e4r din personliga tidiga varningssignal p\u00e5 att en plats inte \u00e4r s\u00e4ker?", "pl": "Jaki jest tw\u00f3j osobisty wczesny sygna\u0142, \u017ce miejsce nie jest bezpieczne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s your personal early-warning sign that a place isn’t safe?';
UPDATE questions
SET translations = '{"en": "What do you think happens after we die\u2014one honest sentence.", "da": "Hvad tror du, der sker, n\u00e5r vi d\u00f8r \u2013 \u00e9n \u00e6rlig s\u00e6tning.", "de": "Was glaubst du, passiert, wenn wir sterben \u2013 ein ehrlicher Satz.", "es": "\u00bfQu\u00e9 crees que sucede cuando morimos? Una frase honesta.", "pt": "O que achas que acontece depois de morrermos \u2013 uma frase honesta.", "ro": "Ce crezi c\u0103 se \u00eent\u00e2mpl\u0103 dup\u0103 ce murim \u2013 o propozi\u021bie sincer\u0103.", "fr": "Que penses-tu qu\u2019il arrive apr\u00e8s la mort \u2013 une phrase honn\u00eate.", "it": "Cosa pensi che succeda dopo la morte? Una frase sincera.", "fi": "Mit\u00e4 luulet tapahtuvan kuoleman j\u00e4lkeen \u2013 yksi rehellinen lause.", "nl": "Wat denk je dat er gebeurt nadat we sterven \u2013 \u00e9\u00e9n eerlijke zin.", "no": "Hva tror du skjer etter at vi d\u00f8r \u2013 \u00e9n \u00e6rlig setning.", "sv": "Vad tror du h\u00e4nder efter att vi d\u00f6r \u2013 en \u00e4rlig mening.", "pl": "Jak my\u015blisz, co si\u0119 dzieje po \u015bmierci \u2013 jedno szczere zdanie."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What do you think happens after we die—one honest sentence.';
UPDATE questions
SET translations = '{"en": "You hear your name from an empty room. Investigate or nope?", "da": "Du h\u00f8rer dit navn fra et tomt rum. Unders\u00f8g eller g\u00e5 v\u00e6k?", "de": "Du h\u00f6rst deinen Namen aus einem leeren Raum. Untersuchen oder gehen?", "es": "Oyes tu nombre desde una habitaci\u00f3n vac\u00eda. \u00bfInvestigas o te vas?", "pt": "Ouves o teu nome vindo de uma sala vazia. Investigarias ou sa\u00edas?", "ro": "Auzi cum \u021bi se spune numele dintr-o camer\u0103 goal\u0103. Cercetezi sau pleci?", "fr": "Tu entends ton nom venir d\u2019une pi\u00e8ce vide. Tu enqu\u00eates ou tu pars ?", "it": "Senti il tuo nome provenire da una stanza vuota. Vai a vedere o lasci stare?", "fi": "Kuulet nimesi tyhj\u00e4st\u00e4 huoneesta. Tutkitko vai etk\u00f6 todellakaan?", "nl": "Je hoort je naam uit een lege kamer komen. Ga je kijken of echt niet?", "no": "Du h\u00f8rer navnet ditt bli ropt fra et tomt rom. G\u00e5r du for \u00e5 sjekke, eller nei takk?", "sv": "Du h\u00f6r ditt namn ropas fr\u00e5n ett tomt rum. G\u00e5r du och kollar eller nope?", "pl": "S\u0142yszysz swoje imi\u0119 z pustego pokoju. Idziesz sprawdzi\u0107 czy absolutnie nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You hear your name from an empty room. Investigate or nope?';
UPDATE questions
SET translations = '{"en": "Reincarnation is real: what skill or habit would you carry over?", "da": "Reinkarnation er virkelig: hvilken f\u00e6rdighed eller vane ville du tage med dig?", "de": "Reinkarnation ist real: Welche F\u00e4higkeit oder Gewohnheit w\u00fcrdest du mitnehmen?", "es": "La reencarnaci\u00f3n es real: \u00bfqu\u00e9 habilidad o h\u00e1bito llevar\u00edas contigo?", "pt": "A reencarna\u00e7\u00e3o \u00e9 real: que habilidade ou h\u00e1bito levarias contigo?", "ro": "Re\u00eencarnarea e real\u0103: ce abilitate sau obicei ai duce mai departe?", "fr": "La r\u00e9incarnation est r\u00e9elle : quelle comp\u00e9tence ou habitude emporterais-tu ?", "it": "La reincarnazione \u00e8 reale: quale abilit\u00e0 o abitudine vorresti portare con te?", "fi": "Reinkarnaatio on totta: mink\u00e4 taidon tai tavan ottaisit mukaasi seuraavaan el\u00e4m\u00e4\u00e4n?", "nl": "Re\u00efncarnatie is echt: welke vaardigheid of gewoonte zou je meenemen?", "no": "Reinkarnasjon er ekte: hvilken ferdighet eller vane ville du tatt med deg videre?", "sv": "Reinkarnation \u00e4r p\u00e5 riktigt: vilken f\u00e4rdighet eller vana skulle du ta med dig?", "pl": "Reinkarnacja jest prawdziwa: jak\u0105 umiej\u0119tno\u015b\u0107 lub jaki nawyk zabra\u0142(a)by\u015b ze sob\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Reincarnation is real: what skill or habit would you carry over?';
UPDATE questions
SET translations = '{"en": "What\u2019s the safest place on earth at midnight?", "da": "Hvad er det sikreste sted p\u00e5 jorden ved midnat?", "de": "Was ist der sicherste Ort auf der Erde um Mitternacht?", "es": "\u00bfCu\u00e1l es el lugar m\u00e1s seguro del mundo a medianoche?", "pt": "Qual \u00e9 o lugar mais seguro da Terra \u00e0 meia-noite?", "ro": "Care este cel mai sigur loc de pe P\u0103m\u00e2nt la miezul nop\u021bii?", "fr": "Quel est l\u2019endroit le plus s\u00fbr sur Terre \u00e0 minuit ?", "it": "Qual \u00e8 il posto pi\u00f9 sicuro sulla Terra a mezzanotte?", "fi": "Mik\u00e4 on maailman turvallisin paikka keskiy\u00f6ll\u00e4?", "nl": "Wat is de veiligste plek op aarde om middernacht?", "no": "Hva er det tryggeste stedet p\u00e5 jorden ved midnatt?", "sv": "Vilken \u00e4r den s\u00e4kraste platsen p\u00e5 jorden vid midnatt?", "pl": "Jakie miejsce na \u015bwiecie jest najbezpieczniejsze o p\u00f3\u0142nocy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s the safest place on earth at midnight?';UPDATE questions
SET translations = '{"en": "Name a spot in our city you\u2019d avoid after midnight\u2014and why.", "da": "N\u00e6vn et sted i vores by, du ville undg\u00e5 efter midnat \u2013 og hvorfor.", "de": "Nenne einen Ort in unserer Stadt, den du nach Mitternacht meiden w\u00fcrdest \u2013 und warum.", "es": "Nombra un lugar de nuestra ciudad que evitar\u00edas despu\u00e9s de medianoche, y por qu\u00e9.", "pt": "Nomeia um local na nossa cidade que evitarias depois da meia-noite \u2013 e porqu\u00ea.", "ro": "Nume\u0219te un loc din ora\u0219 pe care l-ai evita dup\u0103 miezul nop\u021bii \u2013 \u0219i de ce.", "fr": "Nomme un endroit dans notre ville que tu \u00e9viterais apr\u00e8s minuit \u2013 et pourquoi.", "it": "Indica un posto della nostra citt\u00e0 che eviteresti dopo mezzanotte, e perch\u00e9.", "fi": "Nime\u00e4 paikka kaupungissamme, jota v\u00e4lttelisit keskiy\u00f6n j\u00e4lkeen \u2013 ja miksi.", "nl": "Noem een plek in onze stad die je na middernacht zou vermijden \u2013 en waarom.", "no": "Nevn et sted i byen v\u00e5r du ville unng\u00e5 etter midnatt \u2013 og hvorfor.", "sv": "N\u00e4mn en plats i v\u00e5r stad som du skulle undvika efter midnatt \u2013 och varf\u00f6r.", "pl": "Wska\u017c miejsce w naszym mie\u015bcie, kt\u00f3rego unika\u0142(a)by\u015b po p\u00f3\u0142nocy \u2013 i dlaczego."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Name a spot in our city you’d avoid after midnight—and why.';