UPDATE questions
SET translations = '{"en": "What would convince you that a place is truly haunted?", "da": "Hvad ville overbevise dig om, at et sted virkelig er hjems\u00f8gt?", "de": "Was w\u00fcrde dich davon \u00fcberzeugen, dass ein Ort wirklich spukt?", "es": "\u00bfQu\u00e9 te convencer\u00eda de que un lugar est\u00e1 realmente encantado?", "pt": "O que te convenceria de que um lugar \u00e9 realmente assombrado?", "ro": "Ce te-ar convinge c\u0103 un loc este cu adev\u0103rat b\u00e2ntuit?", "fr": "Qu\u2019est-ce qui te convaincrait qu\u2019un lieu est vraiment hant\u00e9 ?", "it": "Cosa ti convincerebbe che un luogo \u00e8 davvero infestato?", "fi": "Mik\u00e4 vakuuttaisi sinut siit\u00e4, ett\u00e4 paikka on oikeasti kummitusten valtaama?", "nl": "Wat zou jou ervan overtuigen dat een plek echt spookt?", "no": "Hva ville overbevist deg om at et sted virkelig er hjems\u00f8kt?", "sv": "Vad skulle \u00f6vertyga dig om att en plats verkligen \u00e4r hems\u00f6kt?", "pl": "Co przekona\u0142oby ci\u0119, \u017ce miejsce jest naprawd\u0119 nawiedzone?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What would convince you that a place is truly haunted?';
UPDATE questions
SET translations = '{"en": "A single shoe sits in the middle of the lane\u2014stop or keep moving?", "da": "En enkelt sko st\u00e5r midt p\u00e5 vejen \u2013 stopper du eller k\u00f8rer videre?", "de": "Ein einzelner Schuh liegt mitten auf der Stra\u00dfe \u2013 bleibst du stehen oder f\u00e4hrst du weiter?", "es": "Un solo zapato est\u00e1 en medio del camino \u2013 \u00bfte detienes o sigues?", "pt": "Um \u00fanico sapato est\u00e1 no meio da estrada \u2013 paras ou continuas?", "ro": "Un singur pantof st\u0103 \u00een mijlocul drumului \u2013 te opre\u0219ti sau mergi mai departe?", "fr": "Une seule chaussure est au milieu de la route \u2013 tu t\u2019arr\u00eates ou tu continues ?", "it": "C\u2019\u00e8 una sola scarpa in mezzo alla corsia: ti fermi o continui ad andare?", "fi": "Yksitt\u00e4inen kenk\u00e4 makaa kaistan keskell\u00e4 \u2013 pys\u00e4hdytk\u00f6 vai jatkatko matkaa?", "nl": "Er ligt \u00e9\u00e9n losse schoen midden op de rijbaan \u2013 stop je of rijd je door?", "no": "En enslig sko ligger midt i kj\u00f8refeltet \u2013 stopper du eller fortsetter du?", "sv": "En ensam sko ligger mitt i k\u00f6rf\u00e4ltet \u2013 stannar du eller forts\u00e4tter?", "pl": "Na \u015brodku pasa le\u017cy pojedynczy but \u2013 zatrzymujesz si\u0119 czy jedziesz dalej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'A single shoe sits in the middle of the lane—stop or keep moving?';
UPDATE questions
SET translations = '{"en": "Have you ever felt watched? Set the scene.", "da": "Har du nogensinde f\u00f8lt dig overv\u00e5get? S\u00e6t scenen.", "de": "Hast du dich jemals beobachtet gef\u00fchlt? Beschreib die Szene.", "es": "\u00bfAlguna vez te has sentido observado? Describe la escena.", "pt": "J\u00e1 te sentiste observado? Descreve a cena.", "ro": "Te-ai sim\u021bit vreodat\u0103 privit? Descrie scena.", "fr": "T\u2019es-tu d\u00e9j\u00e0 senti observ\u00e9 ? D\u00e9cris la sc\u00e8ne.", "it": "Ti sei mai sentito/a osservato/a? Descrivi la scena.", "fi": "Oletko koskaan tuntenut, ett\u00e4 sinua tarkkaillaan? Kuvaa tilanne.", "nl": "Heb je je ooit bekeken gevoeld? Beschrijf de situatie.", "no": "Har du noen gang f\u00f8lt deg overv\u00e5ket? Beskriv situasjonen.", "sv": "Har du n\u00e5gonsin k\u00e4nt dig iakttagen? Beskriv scenen.", "pl": "Czy kiedykolwiek czu\u0142e\u015b/czu\u0142a\u015b si\u0119 obserwowany/a? Opisz t\u0119 sytuacj\u0119."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Have you ever felt watched? Set the scene.';
UPDATE questions
SET translations = '{"en": "You smell cigarette smoke in your apartment; no one smokes. Vent or investigate first?", "da": "Du lugter cigaretr\u00f8g i din lejlighed; ingen ryger. Luft ud eller unders\u00f8g f\u00f8rst?", "de": "Du riechst Zigarettenrauch in deiner Wohnung; niemand raucht. L\u00fcften oder nachsehen?", "es": "Hueles humo de cigarrillo en tu apartamento; nadie fuma. \u00bfVentilar o investigar primero?", "pt": "Sentes cheiro a fumo no teu apartamento; ningu\u00e9m fuma. Ares ou investigas?", "ro": "Sim\u021bi miros de fum de \u021bigar\u0103 \u00een apartament, dar nimeni nu fumeaz\u0103. Aerise\u0219ti sau investighezi?", "fr": "Tu sens la fum\u00e9e de cigarette chez toi ; personne ne fume. Tu a\u00e8res ou tu enqu\u00eates ?", "it": "Senti odore di fumo di sigaretta in casa; nessuno fuma. Arieggi o indaghi per prima cosa?", "fi": "Haistat tupakansavua asunnossasi, vaikka kukaan ei tupakoi. Tuuletatko vai alatko ensin selvitt\u00e4\u00e4 syyt\u00e4?", "nl": "Je ruikt sigarettenrook in je appartement; niemand rookt. Eerst luchten of eerst onderzoeken?", "no": "Du lukter sigarettr\u00f8yk i leiligheten, men ingen r\u00f8yker. Lufter du ut eller unders\u00f8ker du f\u00f8rst?", "sv": "Du k\u00e4nner cigarettr\u00f6k i l\u00e4genheten, men ingen r\u00f6ker. V\u00e4drar du eller unders\u00f6ker du f\u00f6rst?", "pl": "Czujesz dym papierosowy w mieszkaniu, a nikt nie pali. Najpierw wietrzysz czy najpierw sprawdzasz, sk\u0105d to?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You smell cigarette smoke in your apartment; no one smokes. Vent or investigate first?';
UPDATE questions
SET translations = '{"en": "You see someone place a bag under a bench and walk away fast. Do you follow, report, or wait?", "da": "Du ser nogen l\u00e6gge en taske under en b\u00e6nk og g\u00e5 hurtigt v\u00e6k. F\u00f8lger du efter, anmelder du, eller venter du?", "de": "Du siehst jemanden eine Tasche unter eine Bank legen und schnell weggehen. Folgst du, meldest du es oder wartest du?", "es": "Ves a alguien dejar una bolsa bajo un banco y alejarse r\u00e1pido. \u00bfSigues, reportas o esperas?", "pt": "V\u00eas algu\u00e9m deixar uma mala debaixo de um banco e sair depressa. Segues, denuncias ou esperas?", "ro": "Vezi pe cineva pun\u00e2nd o geant\u0103 sub o banc\u0103 \u0219i plec\u00e2nd repede. Urm\u0103re\u0219ti, anun\u021bi sau a\u0219tep\u021bi?", "fr": "Tu vois quelqu\u2019un poser un sac sous un banc et partir vite. Tu suis, tu signales ou tu attends ?", "it": "Vedi qualcuno mettere una borsa sotto una panchina e allontanarsi in fretta. Lo segui, lo segnali o aspetti?", "fi": "N\u00e4et jonkun laittavan laukun penkin alle ja k\u00e4velev\u00e4n nopeasti pois. Seuraatko, ilmoitatko vai odotatko?", "nl": "Je ziet iemand een tas onder een bank neerzetten en snel weglopen. Volg je, meld je het, of wacht je af?", "no": "Du ser noen legge en veske under en benk og g\u00e5 raskt bort. F\u00f8lger du etter, varsler du, eller venter du?", "sv": "Du ser n\u00e5gon l\u00e4gga en v\u00e4ska under en b\u00e4nk och g\u00e5 d\u00e4rifr\u00e5n snabbt. F\u00f6ljer du efter, larmar du eller v\u00e4ntar du?", "pl": "Widzisz, jak kto\u015b chowa torb\u0119 pod \u0142awk\u0105 i szybko odchodzi. Idziesz za nim, zg\u0142aszasz to czy czekasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'You see someone place a bag under a bench and walk away fast. Do you follow, report, or wait?';
UPDATE questions
SET translations = '{"en": "Pick a historical mystery you wish solved.", "da": "V\u00e6lg et historisk mysterium, du gerne ville have l\u00f8st.", "de": "W\u00e4hle ein historisches Mysterium, das du gerne gel\u00f6st h\u00e4ttest.", "es": "Elige un misterio hist\u00f3rico que te gustar\u00eda resolver.", "pt": "Escolhe um mist\u00e9rio hist\u00f3rico que gostarias de ver resolvido.", "ro": "Alege un mister istoric pe care \u021bi-ai dori s\u0103 fie rezolvat.", "fr": "Choisis un myst\u00e8re historique que tu aimerais voir r\u00e9solu.", "it": "Scegli un mistero storico che vorresti vedere risolto.", "fi": "Valitse historiallinen mysteeri, jonka toivoisit ratkeavan.", "nl": "Kies een historisch mysterie waarvan je zou willen dat het wordt opgelost.", "no": "Velg et historisk mysterium du skulle \u00f8nske ble l\u00f8st.", "sv": "V\u00e4lj ett historiskt mysterium som du \u00f6nskar fick en l\u00f6sning.", "pl": "Wybierz historyczn\u0105 zagadk\u0119, kt\u00f3r\u0105 chcia\u0142(a)by\u015b, \u017ceby rozwi\u0105zano."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Pick a historical mystery you wish solved.';
UPDATE questions
SET translations = '{"en": "What\u2019s your plan if the power goes out\u2026 and the neighbors\u2019 lights stay on?", "da": "Hvad er din plan, hvis str\u00f8mmen g\u00e5r\u2026 men naboernes lys bliver t\u00e6ndt?", "de": "Was ist dein Plan, wenn der Strom ausf\u00e4llt\u2026 aber die Nachbarn noch Licht haben?", "es": "\u00bfCu\u00e1l es tu plan si se va la luz\u2026 pero las luces de los vecinos siguen encendidas?", "pt": "Qual \u00e9 o teu plano se faltar a luz\u2026 mas as luzes dos vizinhos ficarem acesas?", "ro": "Care e planul t\u0103u dac\u0103 se ia curentul\u2026 dar luminile vecinilor r\u0103m\u00e2n aprinse?", "fr": "Quel est ton plan si le courant saute\u2026 mais que les lumi\u00e8res des voisins restent allum\u00e9es ?", "it": "Qual \u00e8 il tuo piano se salta la corrente\u2026 ma le luci dei vicini restano accese?", "fi": "Mik\u00e4 on suunnitelmasi, jos s\u00e4hk\u00f6t katkeavat\u2026 mutta naapureilla valot pysyv\u00e4t p\u00e4\u00e4ll\u00e4?", "nl": "Wat is je plan als bij jou de stroom uitvalt\u2026 maar bij de buren het licht blijft branden?", "no": "Hva er planen din hvis str\u00f8mmen g\u00e5r hos deg\u2026 men naboenes lys fortsatt er p\u00e5?", "sv": "Vad \u00e4r din plan om str\u00f6mmen g\u00e5r hos dig\u2026 men grannarnas lampor \u00e4r fortfarande t\u00e4nda?", "pl": "Jaki masz plan, je\u015bli u ciebie zga\u015bnie pr\u0105d\u2026 a u s\u0105siad\u00f3w \u015bwiat\u0142a nadal b\u0119d\u0105 si\u0119 \u015bwieci\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What’s your plan if the power goes out… and the neighbors’ lights stay on?';
UPDATE questions
SET translations = '{"en": "Your laptop webcam light flickers on for a second. What do you check first?", "da": "Din b\u00e6rbare webcams lys blinker et sekund. Hvad tjekker du f\u00f8rst?", "de": "Dein Laptop-Webcam-Licht flackert kurz auf. Was \u00fcberpr\u00fcfst du zuerst?", "es": "La luz de tu webcam parpadea un segundo. \u00bfQu\u00e9 revisas primero?", "pt": "A luz da tua webcam pisca por um segundo. O que verificas primeiro?", "ro": "Lumina camerei laptopului p\u00e2lp\u00e2ie o secund\u0103. Ce verifici mai \u00eent\u00e2i?", "fr": "La lumi\u00e8re de ta webcam clignote une seconde. Que v\u00e9rifies-tu d\u2019abord ?", "it": "La spia della webcam del portatile si accende per un secondo. Cosa controlli per prima cosa?", "fi": "Kannettavasi verkkokameran valo v\u00e4l\u00e4ht\u00e4\u00e4 hetkeksi p\u00e4\u00e4lle. Mit\u00e4 tarkistat ensin?", "nl": "Het lampje van je laptopwebcam springt \u00e9\u00e9n seconde aan. Wat controleer je als eerste?", "no": "Webkameralyset p\u00e5 laptopen blinker p\u00e5 i et sekund. Hva sjekker du f\u00f8rst?", "sv": "Webbkamerans lampa p\u00e5 din laptop blinkar till en sekund. Vad kollar du f\u00f6rst?", "pl": "Lampka kamerki w laptopie na chwil\u0119 si\u0119 zapala. Co sprawdzasz najpierw?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Your laptop webcam light flickers on for a second. What do you check first?';
UPDATE questions
SET translations = '{"en": "What location in a video game would be terrifying in real life?", "da": "Hvilket sted i et videospil ville v\u00e6re skr\u00e6mmende i virkeligheden?", "de": "Welcher Ort aus einem Videospiel w\u00e4re im echten Leben furchterregend?", "es": "\u00bfQu\u00e9 lugar de un videojuego ser\u00eda aterrador en la vida real?", "pt": "Que local de um videojogo seria aterrador na vida real?", "ro": "Ce loc dintr-un joc video ar fi \u00eenfrico\u0219\u0103tor \u00een realitate?", "fr": "Quel lieu d\u2019un jeu vid\u00e9o serait terrifiant dans la vraie vie ?", "it": "Quale ambientazione di un videogioco sarebbe terrificante nella vita reale?", "fi": "Mik\u00e4 videopelien paikka olisi kauhein oikeassa el\u00e4m\u00e4ss\u00e4?", "nl": "Welke locatie in een videogame zou in het echt doodeng zijn?", "no": "Hvilket sted i et videospill ville v\u00e6rt skrekkelig i virkeligheten?", "sv": "Vilken plats i ett tv-spel skulle vara fruktansv\u00e4rd i verkliga livet?", "pl": "Jaka lokalizacja z gry wideo by\u0142aby przera\u017caj\u0105ca w prawdziwym \u017cyciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'What location in a video game would be terrifying in real life?';
UPDATE questions
SET translations = '{"en": "Someone at a party calls Dahmer their \u201cfavorite case.\u201d Do you engage or distance\u2014why?", "da": "Nogen til en fest kalder Dahmer deres \u201cfavoritsag\u201d. Deltager du eller holder afstand \u2013 hvorfor?", "de": "Jemand auf einer Party nennt Dahmer seinen \u201eLieblingsfall\u201c. Gehst du ins Gespr\u00e4ch oder h\u00e4ltst du Abstand \u2013 warum?", "es": "Alguien en una fiesta llama a Dahmer su \u201ccaso favorito\u201d. \u00bfParticipas o te alejas, y por qu\u00e9?", "pt": "Algu\u00e9m numa festa chama Dahmer de o seu \u201ccaso favorito\u201d. Interages ou afastas-te \u2013 porqu\u00ea?", "ro": "Cineva la o petrecere \u00eel nume\u0219te pe Dahmer \u201ecazul lor preferat\u201d. Te implici sau te distan\u021bezi \u2013 de ce?", "fr": "Quelqu\u2019un \u00e0 une f\u00eate dit que Dahmer est son \u00ab affaire pr\u00e9f\u00e9r\u00e9e \u00bb. Tu engages ou tu t\u2019\u00e9loignes \u2013 pourquoi ?", "it": "A una festa qualcuno dice che Dahmer \u00e8 il suo \u201ccaso preferito\u201d. Ci parli o ti allontani? Perch\u00e9?", "fi": "Juhlissa joku sanoo, ett\u00e4 Dahmer on h\u00e4nen \u201csuosikkitapauksensa\u201d. Jaatko keskusteluun vai otatko et\u00e4isyytt\u00e4 \u2013 miksi?", "nl": "Op een feestje noemt iemand Dahmer zijn/haar \u201cfavoriete zaak\u201d. Ga je het gesprek aan of neem je afstand \u2013 waarom?", "no": "P\u00e5 en fest sier noen at Dahmer er deres \u00abfavorittsak\u00bb. Tar du praten, eller trekker du deg unna \u2013 hvorfor?", "sv": "P\u00e5 en fest s\u00e4ger n\u00e5gon att Dahmer \u00e4r deras \u201dfavoritfall\u201d. G\u00e5r du in i samtalet eller tar du avst\u00e5nd \u2013 varf\u00f6r?", "pl": "Na imprezie kto\u015b nazywa Dahmera swoim \u201eulubionym przypadkiem\u201d. W\u0142\u0105czasz si\u0119 w rozmow\u0119 czy trzymasz dystans \u2013 dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'After Dark Talks'
  AND translations->>'en' = 'Someone at a party calls Dahmer their “favorite case.” Do you engage or distance—why?';