UPDATE questions
SET translations = '{"en": "What would make you feel more like a team with me?", "da": "Hvad ville f\u00e5 dig til at f\u00f8le dig mere som et team sammen med mig?", "de": "Was w\u00fcrde dich mehr wie ein Team mit mir f\u00fchlen lassen?", "es": "\u00bfQu\u00e9 te har\u00eda sentir m\u00e1s como un equipo conmigo?", "pt": "O que te faria sentir mais como uma equipa comigo?", "ro": "Ce te-ar face s\u0103 te sim\u021bi mai mult ca o echip\u0103 cu mine?", "fr": "Qu\u2019est-ce qui te ferait sentir davantage comme une \u00e9quipe avec moi ?", "it": "Cosa ti farebbe sentire pi\u00f9 parte di un team con me?", "fi": "Mik\u00e4 saisi sinut tuntemaan itsesi enemm\u00e4n tiimiksi kanssani?", "nl": "Wat zou je meer het gevoel geven dat we een team zijn?", "no": "Hva ville f\u00e5tt deg til \u00e5 f\u00f8le deg mer som et team med meg?", "sv": "Vad skulle f\u00e5 dig att k\u00e4nna dig mer som ett team med mig?", "pl": "Co sprawi\u0142oby, \u017ce poczu\u0142by\u015b si\u0119 bardziej cz\u0119\u015bci\u0105 zespo\u0142u ze mn\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What would make you feel more like a team with me?';
UPDATE questions
SET translations = '{"en": "How do you feel when I try to help but don\u2019t do it \u201cyour way\u201d?", "da": "Hvordan har du det, n\u00e5r jeg pr\u00f8ver at hj\u00e6lpe, men ikke g\u00f8r det \u201cp\u00e5 din m\u00e5de\u201d?", "de": "Wie f\u00fchlst du dich, wenn ich versuche zu helfen, es aber nicht \u201eauf deine Art\u201c mache?", "es": "\u00bfC\u00f3mo te sientes cuando intento ayudar pero no lo hago \u201ca tu manera\u201d?", "pt": "Como te sentes quando eu tento ajudar mas n\u00e3o o fa\u00e7o \u201c\u00e0 tua maneira\u201d?", "ro": "Cum te sim\u021bi c\u00e2nd \u00eencerc s\u0103 ajut dar nu o fac \u201c\u00een felul t\u0103u\u201d?", "fr": "Comment te sens-tu quand j\u2019essaie d\u2019aider mais que je ne le fais pas \u00ab \u00e0 ta fa\u00e7on \u00bb ?", "it": "Come ti senti quando cerco di aiutarti ma non lo faccio \"a modo tuo\"?", "fi": "Milt\u00e4 sinusta tuntuu, kun yrit\u00e4n auttaa, mutta en tee sit\u00e4 \"sinun tavallasi\"?", "nl": "Hoe voel je je als ik probeer te helpen maar het niet op \"jouw manier\" doe?", "no": "Hvordan f\u00f8ler du det n\u00e5r jeg pr\u00f8ver \u00e5 hjelpe, men ikke gj\u00f8r det \"din m\u00e5te\"?", "sv": "Hur k\u00e4nner du n\u00e4r jag f\u00f6rs\u00f6ker hj\u00e4lpa till men inte g\u00f6r det \"p\u00e5 ditt s\u00e4tt\"?", "pl": "Jak si\u0119 czujesz, gdy pr\u00f3buj\u0119 pom\u00f3c, ale nie robi\u0119 tego \u201epo twojemu\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I try to help but don’t do it “your way”?';
UPDATE questions
SET translations = '{"en": "What\u2019s something I do (or could do) that quietly says \u201cI care about you\u201d?", "da": "Hvad g\u00f8r jeg (eller kunne jeg g\u00f8re), der stille siger \u201cjeg holder af dig\u201d?", "de": "Was tue ich (oder k\u00f6nnte ich tun), das leise sagt \u201eIch k\u00fcmmere mich um dich\u201c?", "es": "\u00bfQu\u00e9 hago (o podr\u00eda hacer) que diga en silencio \u201cme importas\u201d?", "pt": "O que eu fa\u00e7o (ou poderia fazer) que diga silenciosamente \u201cimportas para mim\u201d?", "ro": "Ce fac (sau a\u0219 putea face) care spune \u00een t\u0103cere \u201e\u00eemi pas\u0103 de tine\u201d?", "fr": "Que fais-je (ou pourrais-je faire) qui dit silencieusement \u00ab je tiens \u00e0 toi \u00bb ?", "it": "Qualcosa che faccio (o potrei fare) che dice in silenzio \"mi importa di te\"?", "fi": "Mik\u00e4 on jokin asia, jonka teen (tai voisin tehd\u00e4), joka hiljaa sanoo \"v\u00e4lit\u00e4n sinusta\"?", "nl": "Wat is iets dat ik doe (of zou kunnen doen) dat stilletjes zegt \"ik geef om je\"?", "no": "Hva er noe jeg gj\u00f8r (eller kan gj\u00f8re) som stille sier \"jeg bryr meg om deg\"?", "sv": "Vad \u00e4r n\u00e5got jag g\u00f6r (eller skulle kunna g\u00f6ra) som tyst s\u00e4ger \"jag bryr mig om dig\"?", "pl": "Co\u015b, co robi\u0119 (lub m\u00f3g\u0142bym zrobi\u0107), co cicho m\u00f3wi \u201ezale\u017cy mi na tobie\u201d?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something I do (or could do) that quietly says “I care about you”?';
UPDATE questions
SET translations = '{"en": "How can I better notice when you need help \u2014 without you asking?", "da": "Hvordan kan jeg bedre l\u00e6gge m\u00e6rke til, n\u00e5r du har brug for hj\u00e6lp \u2013 uden at du sp\u00f8rger?", "de": "Wie kann ich besser erkennen, wenn du Hilfe brauchst \u2013 ohne dass du fragst?", "es": "\u00bfC\u00f3mo puedo notar mejor cu\u00e1ndo necesitas ayuda \u2014 sin que lo pidas?", "pt": "Como posso perceber melhor quando precisas de ajuda \u2014 sem pedires?", "ro": "Cum pot observa mai bine c\u00e2nd ai nevoie de ajutor \u2014 f\u0103r\u0103 s\u0103 ceri?", "fr": "Comment puis-je mieux remarquer quand tu as besoin d\u2019aide \u2014 sans que tu le demandes ?", "it": "Come posso accorgermi meglio quando hai bisogno di aiuto, senza che tu debba chiedere?", "fi": "Miten voisin paremmin huomata, kun tarvitset apua \u2014 ilman ett\u00e4 sinun tarvitsee pyyt\u00e4\u00e4?", "nl": "Hoe kan ik beter opmerken wanneer je hulp nodig hebt \u2014 zonder dat je het vraagt?", "no": "Hvordan kan jeg bedre legge merke til n\u00e5r du trenger hjelp \u2014 uten at du ber om det?", "sv": "Hur kan jag b\u00e4ttre m\u00e4rka n\u00e4r du beh\u00f6ver hj\u00e4lp \u2014 utan att du ber om det?", "pl": "Jak mog\u0119 lepiej zauwa\u017ca\u0107, kiedy potrzebujesz pomocy \u2014 bez pytania?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How can I better notice when you need help — without you asking?';
UPDATE questions
SET translations = '{"en": "What\u2019s something I could do more often that would take weight off your shoulders?", "da": "Hvad kunne jeg g\u00f8re oftere, som ville lette noget af v\u00e6gten fra dine skuldre?", "de": "Was k\u00f6nnte ich \u00f6fter tun, um dir etwas Last von den Schultern zu nehmen?", "es": "\u00bfQu\u00e9 podr\u00eda hacer m\u00e1s a menudo que te quite peso de los hombros?", "pt": "O que eu poderia fazer mais vezes que te tirasse um peso dos ombros?", "ro": "Ce a\u0219 putea face mai des ca s\u0103-\u021bi iau o parte din greutate de pe umeri?", "fr": "Que pourrais-je faire plus souvent pour all\u00e9ger un peu le poids sur tes \u00e9paules ?", "it": "Cosa potrei fare pi\u00f9 spesso che allevierebbe un po'' il tuo peso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 voisin tehd\u00e4 useammin, mik\u00e4 kevent\u00e4isi taakkaasi?", "nl": "Wat is iets dat ik vaker zou kunnen doen om je ontlasten?", "no": "Hva er noe jeg kunne gjort oftere som ville lett byrden din?", "sv": "Vad \u00e4r n\u00e5got jag skulle kunna g\u00f6ra oftare som skulle l\u00e4tta p\u00e5 dina axlar?", "pl": "Co\u015b, co m\u00f3g\u0142bym robi\u0107 cz\u0119\u015bciej, co zdj\u0119\u0142oby ci ci\u0119\u017car z ramion?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s something I could do more often that would take weight off your shoulders?';
UPDATE questions
SET translations = '{"en": "How do you usually react when someone gives you a gift \u2014 excited, shy, awkward, emotional? What do you wish people understood about that?", "da": "Hvordan reagerer du normalt, n\u00e5r nogen giver dig en gave \u2013 begejstret, genert, akavet, r\u00f8rt? Hvad ville du \u00f8nske, folk forstod om det?", "de": "Wie reagierst du normalerweise, wenn dir jemand ein Geschenk gibt \u2013 aufgeregt, sch\u00fcchtern, unbeholfen, emotional? Was w\u00fcnschst du dir, dass die Leute dar\u00fcber verstehen?", "es": "\u00bfC\u00f3mo sueles reaccionar cuando alguien te da un regalo \u2014 emocionado/a, t\u00edmido/a, inc\u00f3modo/a, emocionado/a? \u00bfQu\u00e9 te gustar\u00eda que la gente entendiera sobre eso?", "pt": "Como costumas reagir quando algu\u00e9m te oferece um presente \u2014 entusiasmado(a), t\u00edmido(a), atrapalhado(a), emocionado(a)? O que gostarias que as pessoas entendessem sobre isso?", "ro": "Cum reac\u021bionezi de obicei c\u00e2nd cineva \u00ee\u021bi ofer\u0103 un cadou \u2014 entuziasmat(\u0103), timid(\u0103), st\u00e2njenit(\u0103), emo\u021bionat(\u0103)? Ce \u021bi-ai dori s\u0103 \u00een\u021beleag\u0103 oamenii despre asta?", "fr": "Comment r\u00e9agis-tu d\u2019habitude quand quelqu\u2019un t\u2019offre un cadeau \u2014 excit\u00e9(e), timide, maladroit(e), \u00e9mu(e) ? Qu\u2019aimerais-tu que les gens comprennent \u00e0 ce sujet ?", "it": "Come reagisci di solito quando qualcuno ti fa un regalo \u2014 con entusiasmo, timidezza, imbarazzo, emozione? Cosa vorresti che le persone capissero riguardo a questo?", "fi": "Miten yleens\u00e4 reagoit, kun joku antaa sinulle lahjan \u2014 innokkaasti, ujoisesti, vaivaantuneesti, tunteellisesti? Mit\u00e4 toivot ihmisten ymm\u00e4rt\u00e4v\u00e4n siit\u00e4?", "nl": "Hoe reageer je meestal als iemand je een cadeau geeft \u2014 enthousiast, verlegen, ongemakkelijk, emotioneel? Wat zou je willen dat mensen daarover begrijpen?", "no": "Hvordan pleier du \u00e5 reagere n\u00e5r noen gir deg en gave \u2014 spent, sjenert, kl\u00f8nete, f\u00f8lelsesladet? Hva \u00f8nsker du at folk forsto om det?", "sv": "Hur brukar du reagera n\u00e4r n\u00e5gon ger dig en present \u2014 entusiastisk, blyg, klumpig, k\u00e4nslosam? Vad \u00f6nskar du att folk f\u00f6rstod om det?", "pl": "Jak zazwyczaj reagujesz, gdy kto\u015b daje ci prezent \u2014 z ekscytacj\u0105, nie\u015bmia\u0142o\u015bci\u0105, niezr\u0119cznie, emocjonalnie? Co chcia\u0142by\u015b, aby ludzie zrozumieli na ten temat?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you usually react when someone gives you a gift — excited, shy, awkward, emotional? What do you wish people understood about that?';
UPDATE questions
SET translations = '{"en": "What makes a gift feel truly meaningful to you?", "da": "Hvad f\u00e5r en gave til virkelig at f\u00f8les meningsfuld for dig?", "de": "Was l\u00e4sst ein Geschenk f\u00fcr dich wirklich bedeutungsvoll f\u00fchlen?", "es": "\u00bfQu\u00e9 hace que un regalo se sienta verdaderamente significativo para ti?", "pt": "O que faz um presente parecer verdadeiramente significativo para ti?", "ro": "Ce face ca un cadou s\u0103 \u021bi se par\u0103 cu adev\u0103rat semnificativ?", "fr": "Qu\u2019est-ce qui rend un cadeau vraiment significatif pour toi ?", "it": "Cosa rende un regalo davvero significativo per te?", "fi": "Mik\u00e4 tekee lahjasta sinulle todella merkityksellisen?", "nl": "Wat maakt een cadeau voor jou echt betekenisvol?", "no": "Hva gj\u00f8r en gave virkelig meningsfull for deg?", "sv": "Vad g\u00f6r en g\u00e5va verkligen meningsfull f\u00f6r dig?", "pl": "Co sprawia, \u017ce prezent wydaje si\u0119 dla Ciebie naprawd\u0119 znacz\u0105cy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What makes a gift feel truly meaningful to you?';
UPDATE questions
SET translations = '{"en": "Do you like surprises, or do you prefer to know something\u2019s coming?", "da": "Kan du lide overraskelser, eller foretr\u00e6kker du at vide, at noget er p\u00e5 vej?", "de": "Magst du \u00dcberraschungen oder wei\u00dft du lieber im Voraus, dass etwas kommt?", "es": "\u00bfTe gustan las sorpresas o prefieres saber que algo viene?", "pt": "Gostas de surpresas ou preferes saber que algo vem a\u00ed?", "ro": "\u00ce\u021bi plac surprizele sau preferi s\u0103 \u0219tii dinainte c\u0103 urmeaz\u0103 ceva?", "fr": "Aimes-tu les surprises ou pr\u00e9f\u00e8res-tu savoir \u00e0 l\u2019avance que quelque chose arrive ?", "it": "Ti piacciono le sorprese, o preferisci sapere che sta per arrivare qualcosa?", "fi": "Pid\u00e4tk\u00f6 yll\u00e4tyksist\u00e4, vai suositko tiet\u00e4\u00e4 etuk\u00e4teen, mit\u00e4 on tulossa?", "nl": "Hou je van verrassingen, of geef je er de voorkeur aan om te weten dat er iets aankomt?", "no": "Liker du overraskelser, eller foretrekker du \u00e5 vite at noe kommer?", "sv": "Tycker du om \u00f6verraskningar, eller f\u00f6redrar du att veta att n\u00e5got \u00e4r p\u00e5 v\u00e4g?", "pl": "Czy lubisz niespodzianki, czy wolisz wiedzie\u0107, \u017ce co\u015b nadchodzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'Do you like surprises, or do you prefer to know something’s coming?';
UPDATE questions
SET translations = '{"en": "What\u2019s the most thoughtful gift I\u2019ve ever given you \u2014 and why?", "da": "Hvad er den mest bet\u00e6nksomme gave, jeg nogensinde har givet dig \u2013 og hvorfor?", "de": "Was ist das aufmerksamste Geschenk, das ich dir je gemacht habe \u2013 und warum?", "es": "\u00bfCu\u00e1l es el regalo m\u00e1s considerado que te he dado \u2014 y por qu\u00e9?", "pt": "Qual foi o presente mais atencioso que j\u00e1 te dei \u2014 e por qu\u00ea?", "ro": "Care este cel mai atent cadou pe care \u021bi l-am oferit \u2014 \u0219i de ce?", "fr": "Quel est le cadeau le plus attentionn\u00e9 que je t\u2019aie jamais offert \u2014 et pourquoi ?", "it": "Qual \u00e8 il regalo pi\u00f9 premuroso che ti abbia mai fatto \u2014 e perch\u00e9?", "fi": "Mik\u00e4 on ajatuksellisin lahja, jonka olen koskaan antanut sinulle \u2014 ja miksi?", "nl": "Wat is het meest doordachte cadeau dat ik je ooit heb gegeven \u2014 en waarom?", "no": "Hva er den mest gjennomtenkte gaven jeg noen gang har gitt deg \u2014 og hvorfor?", "sv": "Vad \u00e4r den mest omt\u00e4nksamma presenten jag n\u00e5gonsin har gett dig \u2014 och varf\u00f6r?", "pl": "Jaki by\u0142 najbardziej przemy\u015blany prezent, jaki kiedykolwiek ci da\u0142em \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'What’s the most thoughtful gift I’ve ever given you — and why?';
UPDATE questions
SET translations = '{"en": "How do you feel when I surprise you with something small?", "da": "Hvordan har du det, n\u00e5r jeg overrasker dig med noget lille?", "de": "Wie f\u00fchlst du dich, wenn ich dich mit etwas Kleinem \u00fcberrasche?", "es": "\u00bfC\u00f3mo te sientes cuando te sorprendo con algo peque\u00f1o?", "pt": "Como te sentes quando eu te surpreendo com algo pequeno?", "ro": "Cum te sim\u021bi c\u00e2nd te surprind cu ceva mic?", "fr": "Comment te sens-tu quand je te surprends avec quelque chose de petit ?", "it": "Come ti senti quando ti sorprendo con qualcosa di piccolo?", "fi": "Milt\u00e4 sinusta tuntuu, kun yll\u00e4t\u00e4n sinut jollakin pienell\u00e4?", "nl": "Hoe voel je je als ik je verras met iets kleins?", "no": "Hvordan f\u00f8ler du deg n\u00e5r jeg overrasker deg med noe lite?", "sv": "Hur k\u00e4nner du dig n\u00e4r jag \u00f6verraskar dig med n\u00e5got litet?", "pl": "Jak si\u0119 czujesz, gdy zaskakuj\u0119 ci\u0119 czym\u015b ma\u0142ym?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Love Languages Remix Talks'
  AND translations->>'en' = 'How do you feel when I surprise you with something small?';