UPDATE questions
SET translations = '{"en": "Tell me about a moment that changed the direction of your life.", "da": "Fort\u00e6l mig om et \u00f8jeblik, der \u00e6ndrede retningen i dit liv.", "de": "Erz\u00e4hl mir von einem Moment, der die Richtung deines Lebens ver\u00e4ndert hat.", "es": "Cu\u00e9ntame sobre un momento que cambi\u00f3 el rumbo de tu vida.", "pt": "Conta-me sobre um momento que mudou a dire\u00e7\u00e3o da tua vida.", "ro": "Spune-mi despre un moment care \u021bi-a schimbat direc\u021bia vie\u021bii.", "fr": "Raconte-moi un moment qui a chang\u00e9 la direction de ta vie.", "it": "Raccontami di un momento che ha cambiato la direzione della tua vita.", "fi": "Kerro minulle hetkest\u00e4, joka muutti el\u00e4m\u00e4si suuntaa.", "nl": "Vertel me over een moment dat de richting van je leven heeft veranderd.", "no": "Fortell meg om et \u00f8yeblikk som endret retningen i livet ditt.", "sv": "Ber\u00e4tta om ett \u00f6gonblick som f\u00f6r\u00e4ndrade riktningen i ditt liv.", "pl": "Opowiedz mi o momencie, kt\u00f3ry zmieni\u0142 kierunek twojego \u017cycia."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about a moment that changed the direction of your life.';
UPDATE questions
SET translations = '{"en": "What\u2019s a small decision that ended up changing a lot for you?", "da": "Hvad er en lille beslutning, der endte med at \u00e6ndre meget for dig?", "de": "Was ist eine kleine Entscheidung, die viel f\u00fcr dich ver\u00e4ndert hat?", "es": "\u00bfQu\u00e9 peque\u00f1a decisi\u00f3n termin\u00f3 cambiando mucho para ti?", "pt": "Que pequena decis\u00e3o acabou por mudar muito para ti?", "ro": "Ce mic\u0103 decizie a ajuns s\u0103-\u021bi schimbe mult via\u021ba?", "fr": "Quelle petite d\u00e9cision a fini par changer beaucoup pour toi ?", "it": "Qual \u00e8 una piccola decisione che alla fine ha cambiato molto per te?", "fi": "Mik\u00e4 on pieni p\u00e4\u00e4t\u00f6s, joka lopulta muutti paljon el\u00e4m\u00e4ss\u00e4si?", "nl": "Wat is een kleine beslissing die uiteindelijk veel voor jou heeft veranderd?", "no": "Hva er en liten beslutning som endte opp med \u00e5 forandre mye for deg?", "sv": "Vad \u00e4r ett litet beslut som slutade med att f\u00f6r\u00e4ndra mycket f\u00f6r dig?", "pl": "Jakie\u015b ma\u0142e postanowienie, kt\u00f3re ostatecznie zmieni\u0142o dla ciebie wiele?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a small decision that ended up changing a lot for you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to fix themselves that everyone replaces now?", "da": "Hvad plejede folk at reparere selv, som alle udskifter nu?", "de": "Was haben die Leute fr\u00fcher selbst repariert, was heute jeder ersetzt?", "es": "\u00bfQu\u00e9 sol\u00edan arreglar las personas antes que ahora todos reemplazan?", "pt": "O que as pessoas consertavam antes e agora todos substituem?", "ro": "Ce obi\u0219nuiau oamenii s\u0103 repare singuri, dar acum \u00eenlocuiesc?", "fr": "Que r\u00e9paraient autrefois les gens eux-m\u00eames que tout le monde remplace maintenant ?", "it": "Qualcosa che le persone si riparavano da sole e che ora tutti sostituiscono?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen korjasivat itse, mutta mik\u00e4 nyky\u00e4\u00e4n vaihdetaan?", "nl": "Wat is iets dat mensen vroeger zelf repareerden, maar wat nu iedereen vervangt?", "no": "Hva er noe folk pleide \u00e5 fikse selv, som alle n\u00e5 bytter ut?", "sv": "Vad \u00e4r n\u00e5got som folk brukade laga sj\u00e4lva men som alla nu byter ut?", "pl": "Co\u015b, co ludzie kiedy\u015b naprawiali sami, a teraz wszyscy wymieniaj\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to fix themselves that everyone replaces now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you had to wait for that\u2019s instant today?", "da": "Hvad ventede du p\u00e5 dengang, som er \u00f8jeblikkeligt i dag?", "de": "Worauf musstest du fr\u00fcher warten, das heute sofort da ist?", "es": "\u00bfQu\u00e9 ten\u00edas que esperar antes que ahora es instant\u00e1neo?", "pt": "O que tinhas de esperar antes e hoje \u00e9 instant\u00e2neo?", "ro": "Ce trebuia s\u0103 a\u0219tep\u021bi \u00eenainte \u0219i acum se \u00eent\u00e2mpl\u0103 instantaneu?", "fr": "Que devais-tu attendre autrefois et qui est instantan\u00e9 aujourd\u2019hui ?", "it": "Qualcosa per cui hai dovuto aspettare e che oggi \u00e8 istantaneo?", "fi": "Mik\u00e4 on jotain, jota jouduit odottamaan, mutta joka on t\u00e4n\u00e4\u00e4n v\u00e4lit\u00f6nt\u00e4?", "nl": "Wat is iets waar je op moest wachten dat vandaag de dag direct beschikbaar is?", "no": "Hva er noe du m\u00e5tte vente p\u00e5 som er \u00f8yeblikkelig i dag?", "sv": "Vad \u00e4r n\u00e5got du var tvungen att v\u00e4nta p\u00e5 som \u00e4r \u00f6gonblickligt idag?", "pl": "Co\u015b, na co musia\u0142e\u015b czeka\u0107, a co dzisiaj jest natychmiastowe?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you had to wait for that’s instant today?';
UPDATE questions
SET translations = '{"en": "What was your favorite thing to watch on TV \u2014 and when did it come on?", "da": "Hvad var dit yndlingsprogram i tv \u2014 og hvorn\u00e5r kom det p\u00e5?", "de": "Was war deine Lieblingssendung im Fernsehen \u2013 und wann lief sie?", "es": "\u00bfCu\u00e1l era tu programa favorito en la televisi\u00f3n \u2014 y cu\u00e1ndo se emit\u00eda?", "pt": "Qual era o teu programa favorito na TV \u2014 e quando dava?", "ro": "Care era emisiunea ta preferat\u0103 la TV \u2014 \u0219i c\u00e2nd era difuzat\u0103?", "fr": "Quelle \u00e9tait ton \u00e9mission pr\u00e9f\u00e9r\u00e9e \u00e0 la t\u00e9l\u00e9 \u2014 et quand passait-elle ?", "it": "Qual era la tua cosa preferita da guardare in TV \u2014 e quando andava in onda?", "fi": "Mik\u00e4 oli lempijuttusi, jota katsoit televisiosta \u2014 ja milloin se tuli?", "nl": "Wat was je favoriete programma om op tv te kijken \u2014 en wanneer kwam het op?", "no": "Hva var din favoritt \u00e5 se p\u00e5 TV \u2014 og n\u00e5r gikk det?", "sv": "Vad var din favoritgrej att titta p\u00e5 p\u00e5 TV \u2014 och n\u00e4r s\u00e4ndes den?", "pl": "Co by\u0142o twoj\u0105 ulubion\u0105 rzecz\u0105 do ogl\u0105dania w telewizji \u2014 i kiedy to lecia\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your favorite thing to watch on TV — and when did it come on?';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think people had more patience for back then?", "da": "Hvad er \u00e9n ting, du tror, folk havde mere t\u00e5lmodighed med dengang?", "de": "Womit glaubst du, hatten die Menschen fr\u00fcher mehr Geduld?", "es": "\u00bfCon qu\u00e9 crees que la gente ten\u00eda m\u00e1s paciencia antes?", "pt": "Com o que achas que as pessoas tinham mais paci\u00eancia antigamente?", "ro": "Cu ce crezi c\u0103 aveau oamenii mai mult\u0103 r\u0103bdare \u00eenainte?", "fr": "Pour quoi penses-tu que les gens avaient plus de patience autrefois ?", "it": "Qual \u00e8 una cosa per cui pensi che le persone avessero pi\u00f9 pazienza ai tempi?", "fi": "Mik\u00e4 on yksi asia, johon luulet ihmisten olleen k\u00e4rsiv\u00e4llisempi\u00e4 ennen?", "nl": "Wat is \u00e9\u00e9n ding waar mensen vroeger meer geduld voor hadden, denk je?", "no": "Hva er \u00e9n ting du tror folk hadde mer t\u00e5lmodighet for den gang?", "sv": "Vad \u00e4r en sak som du tror att folk hade mer t\u00e5lamod f\u00f6r d\u00e5?", "pl": "Co\u015b, co my\u015blisz, \u017ce ludzie mieli wi\u0119cej cierpliwo\u015bci do tego kiedy\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you think people had more patience for back then?';
UPDATE questions
SET translations = '{"en": "What\u2019s a job that barely exists now but used to be common?", "da": "Hvilket job findes n\u00e6sten ikke mere, men var almindeligt f\u00f8r?", "de": "Welcher Beruf existiert heute kaum noch, war aber fr\u00fcher \u00fcblich?", "es": "\u00bfQu\u00e9 trabajo casi no existe ahora pero era com\u00fan antes?", "pt": "Que profiss\u00e3o quase n\u00e3o existe agora, mas era comum antes?", "ro": "Ce meserie abia mai exist\u0103 acum, dar era comun\u0103 \u00eenainte?", "fr": "Quel m\u00e9tier existe \u00e0 peine maintenant mais \u00e9tait courant autrefois ?", "it": "Qual \u00e8 un lavoro che esiste appena ora ma che era comune in passato?", "fi": "Mik\u00e4 on ty\u00f6, jota l\u00e4hes ei en\u00e4\u00e4 ole, mutta joka oli ennen yleinen?", "nl": "Wat is een baan die bijna niet meer bestaat, maar vroeger gebruikelijk was?", "no": "Hva er en jobb som knapt eksisterer n\u00e5, men som pleide \u00e5 v\u00e6re vanlig?", "sv": "Vilket jobb som knappt finns nu men som brukade vara vanligt?", "pl": "Jakie jest zaj\u0119cie, kt\u00f3re prawie nie istnieje teraz, ale kiedy\u015b by\u0142o powszechne?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a job that barely exists now but used to be common?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that felt like luxury when you were growing up?", "da": "Hvad f\u00f8ltes som luksus, da du voksede op?", "de": "Was f\u00fchlte sich wie Luxus an, als du aufgewachsen bist?", "es": "\u00bfQu\u00e9 se sent\u00eda como un lujo cuando eras ni\u00f1o?", "pt": "O que parecia um luxo quando eras crian\u00e7a?", "ro": "Ce p\u0103rea un lux c\u00e2nd erai copil?", "fr": "Qu\u2019est-ce qui te semblait \u00eatre un luxe quand tu \u00e9tais enfant ?", "it": "Qualcosa che sembrava un lusso quando eri giovane?", "fi": "Mik\u00e4 oli jotain, mik\u00e4 tuntui ylellisyydelt\u00e4 lapsuudessasi?", "nl": "Wat was iets dat als luxe voelde toen je opgroeide?", "no": "Hva var noe som f\u00f8ltes som luksus da du vokste opp?", "sv": "Vad var n\u00e5got som k\u00e4ndes som lyx n\u00e4r du v\u00e4xte upp?", "pl": "Co\u015b, co wydawa\u0142o si\u0119 luksusem, gdy dorasta\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that felt like luxury when you were growing up?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you think people took more pride in doing by hand?", "da": "Hvad er noget, du tror, folk var mere stolte af at lave i h\u00e5nden?", "de": "Worin glaubst du, waren die Menschen fr\u00fcher stolzer, wenn sie es von Hand gemacht haben?", "es": "\u00bfDe qu\u00e9 crees que la gente se sent\u00eda m\u00e1s orgullosa de hacer a mano antes?", "pt": "Do que achas que as pessoas tinham mais orgulho em fazer \u00e0 m\u00e3o?", "ro": "De ce crezi c\u0103 oamenii erau mai m\u00e2ndri s\u0103 fac\u0103 manual?", "fr": "De quoi penses-tu que les gens \u00e9taient plus fiers de faire \u00e0 la main ?", "it": "Qual \u00e8 qualcosa di cui pensi che le persone avessero pi\u00f9 orgoglio a fare a mano?", "fi": "Mik\u00e4 on jotain, mist\u00e4 luulet ihmisten olevan ylpe\u00e4mpi\u00e4, kun he tekev\u00e4t sen k\u00e4sin?", "nl": "Wat is iets waarvan je denkt dat mensen er meer trots op waren om het met de hand te doen?", "no": "Hva er noe du tror folk hadde mer stolthet i \u00e5 gj\u00f8re for h\u00e5nd?", "sv": "Vad \u00e4r n\u00e5got som du tror att folk tog mer stolthet i att g\u00f6ra f\u00f6r hand?", "pl": "Co\u015b, z czego my\u015blisz, \u017ce ludzie bardziej czerpali dum\u0119, robi\u0105c to r\u0119cznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you think people took more pride in doing by hand?';
UPDATE questions
SET translations = '{"en": "What\u2019s a smell that reminds you of \u201cthe old days\u201d?", "da": "Hvilken duft minder dig om \u201cde gode gamle dage\u201d?", "de": "Welcher Geruch erinnert dich an \u201edie guten alten Zeiten\u201c?", "es": "\u00bfQu\u00e9 olor te recuerda a \u201clos viejos tiempos\u201d?", "pt": "Que cheiro te lembra \u201cos bons velhos tempos\u201d?", "ro": "Ce miros \u00ee\u021bi aminte\u0219te de \u201evremurile bune de alt\u0103dat\u0103\u201d?", "fr": "Quelle odeur te rappelle \u201cle bon vieux temps\u201d ?", "it": "Qual \u00e8 un odore che ti ricorda \"i bei tempi\"?", "fi": "Mik\u00e4 tuoksu muistuttaa sinua \"vanhoista p\u00e4ivist\u00e4\"?", "nl": "Wat is een geur die je doet denken aan \"de oude tijden\"?", "no": "Hva er en lukt som minner deg om \"de gode gamle dager\"?", "sv": "Vilken doft p\u00e5minner dig om \"de gamla dagarna\"?", "pl": "Jaki zapach przypomina ci \"stare dobre czasy\"?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s a smell that reminds you of “the old days”?';