UPDATE questions
SET translations = '{"en": "What\u2019s a fear or insecurity about the future that you rarely talk about?", "da": "Hvilken frygt eller usikkerhed om fremtiden taler du sj\u00e6ldent om?", "de": "Hvad er din yndlingsform for leg?", "es": "Was ist deine Lieblingsform des Spiels?", "pt": "Que medo ou inseguran\u00e7a sobre o futuro raramente falas?", "ro": "Ce fric\u0103 sau nesiguran\u021b\u0103 legat\u0103 de viitor discu\u021bi rar?", "fr": "Quelle peur ou ins\u00e9curit\u00e9 concernant l\u2019avenir \u00e9voques-tu rarement ?", "it": "Qual \u00e8 una paura o un''insicurezza riguardo al futuro di cui parli raramente?", "fi": "Mik\u00e4 on pelko tai ep\u00e4varmuus tulevaisuudesta, josta harvoin puhut?", "nl": "Wat is een angst of onzekerheid over de toekomst waar je zelden over praat?", "no": "Hva er en frykt eller usikkerhet om fremtiden som du sjelden snakker om?", "sv": "Vilken r\u00e4dsla eller os\u00e4kerhet om framtiden pratar du s\u00e4llan om?", "pl": "Jakie jest twoje l\u0119k lub niepewno\u015b\u0107 dotycz\u0105ca przysz\u0142o\u015bci, o kt\u00f3rym rzadko rozmawiasz?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s a fear or insecurity about the future that you rarely talk about?';
UPDATE questions
SET translations = '{"en": "What\u2019s the biggest trouble you ever got into \u2014 and what did it teach you?", "da": "Hvad er den st\u00f8rste ballade, du nogensinde har v\u00e6ret i \u2014 og hvad l\u00e6rte du af det?", "de": "Hvad betyder \"erfaring\" for dig i sengen \u2013 f\u00e6rdigheder, selvtillid, nysgerrighed?", "es": "Was bedeutet \u201eErfahrung\u201c f\u00fcr dich im Bett \u2013 K\u00f6nnen, Selbstvertrauen, Neugier?", "pt": "Qual foi o maior sarilho em que j\u00e1 te meteste \u2014 e o que aprendeste com isso?", "ro": "Care e cea mai mare belea \u00een care ai fost \u2014 \u0219i ce ai \u00eenv\u0103\u021bat din ea?", "fr": "Quelle est la plus grosse gal\u00e8re dans laquelle tu sois tomb\u00e9 \u2014 et qu\u2019en as-tu appris ?", "it": "Qual \u00e8 stato il problema pi\u00f9 grande in cui sei mai cacciato \u2014 e cosa ti ha insegnato?", "fi": "Mik\u00e4 on suurin ongelma, johon olet koskaan joutunut \u2014 ja mit\u00e4 se opetti sinulle?", "nl": "Wat is het grootste probleem waar je ooit in terecht bent gekomen \u2014 en wat heeft het je geleerd?", "no": "Hva er det st\u00f8rste problemet du noen gang har havnet i \u2013 og hva l\u00e6rte det deg?", "sv": "Vad \u00e4r det st\u00f6rsta problemet du n\u00e5gonsin hamnat i \u2014 och vad l\u00e4rde det dig?", "pl": "Jakie by\u0142o najwi\u0119ksze k\u0142opoty, w jakie kiedykolwiek si\u0119 wpakowa\u0142e\u015b \u2014 i czego ci\u0119 to nauczy\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s the biggest trouble you ever got into — and what did it teach you?';
UPDATE questions
SET translations = '{"en": "When you think about your past relationships, what stands out most \u2014 what you gave or what you lost?", "da": "N\u00e5r du t\u00e6nker p\u00e5 dine tidligere forhold, hvad st\u00e5r mest ud \u2014 det, du gav, eller det, du mistede?", "de": "Hvad er \u00e9n ting, du gerne vil lave med mig, som du aldrig har turdet n\u00e6vne f\u00f8r?", "es": "Was ist eine Sache, die du gerne mit mir tun w\u00fcrdest, dich aber nie getraut hast zu sagen?", "pt": "Quando pensas nas tuas rela\u00e7\u00f5es passadas, o que se destaca mais \u2014 o que deste ou o que perdeste?", "ro": "C\u00e2nd te g\u00e2nde\u0219ti la rela\u021biile tale anterioare, ce iese cel mai mult \u00een eviden\u021b\u0103 \u2014 ce ai oferit sau ce ai pierdut?", "fr": "Quand tu penses \u00e0 tes relations pass\u00e9es, qu\u2019est-ce qui te marque le plus \u2014 ce que tu as donn\u00e9 ou perdu ?", "it": "Quando pensi alle tue relazioni passate, cosa ti colpisce di pi\u00f9 \u2014 ci\u00f2 che hai dato o ci\u00f2 che hai perso?", "fi": "Kun ajattelet menneit\u00e4 suhteitasi, mik\u00e4 nousee eniten esiin \u2014 se, mit\u00e4 annoit vai se, mit\u00e4 menetit?", "nl": "Wanneer je aan je vorige relaties denkt, wat springt er dan het meest in het oog - wat je hebt gegeven of wat je hebt verloren?", "no": "N\u00e5r du tenker p\u00e5 dine tidligere forhold, hva st\u00e5r mest ut - hva du ga eller hva du mistet?", "sv": "N\u00e4r du t\u00e4nker p\u00e5 dina tidigare relationer, vad st\u00e5r ut mest \u2014 vad du gav eller vad du f\u00f6rlorade?", "pl": "Kiedy my\u015blisz o swoich przesz\u0142ych zwi\u0105zkach, co najbardziej si\u0119 wyr\u00f3\u017cnia \u2014 to, co da\u0142e\u015b, czy to, co straci\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When you think about your past relationships, what stands out most — what you gave or what you lost?';
UPDATE questions
SET translations = '{"en": "Do you think people today are too easily offended or not careful enough with words?", "da": "Synes du, folk i dag bliver for let forn\u00e6rmede eller ikke er forsigtige nok med ord?", "de": "Er der en side af dig, jeg stadig ikke har l\u00e5st op for endnu?", "es": "Gibt es eine Seite von dir, die ich noch nicht entdeckt habe?", "pt": "Achas que as pessoas hoje se ofendem com demasiada facilidade ou n\u00e3o t\u00eam cuidado com as palavras?", "ro": "Crezi c\u0103 oamenii ast\u0103zi se simt jigni\u021bi prea u\u0219or sau nu sunt suficient de aten\u021bi cu vorbele?", "fr": "Penses-tu que les gens aujourd\u2019hui sont trop facilement offens\u00e9s ou pas assez prudents avec leurs mots ?", "it": "Pensi che le persone di oggi si offendano troppo facilmente o che non siano abbastanza attente con le parole?", "fi": "Luuleeko, ett\u00e4 ihmiset t\u00e4n\u00e4 p\u00e4iv\u00e4n\u00e4 loukkaantuvat liian helposti vai eiv\u00e4t ole tarpeeksi varovaisia sanojensa kanssa?", "nl": "Denk je dat mensen vandaag de dag te snel beledigd zijn of niet voorzichtig genoeg met woorden omgaan?", "no": "Tror du folk i dag blir for lett forn\u00e6rmet, eller er de ikke forsiktige nok med ordene?", "sv": "Tycker du att folk idag \u00e4r f\u00f6r l\u00e4ttkr\u00e4nkta eller inte tillr\u00e4ckligt f\u00f6rsiktiga med sina ord?", "pl": "Czy uwa\u017casz, \u017ce ludzie dzisiaj s\u0105 zbyt \u0142atwo obra\u017cani, czy mo\u017ce nieostro\u017cni w doborze s\u0142\u00f3w?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'Do you think people today are too easily offended or not careful enough with words?';
UPDATE questions
SET translations = '{"en": "How do you feel about earning more or less than your partner?", "da": "Hvordan har du det med at tjene mere eller mindre end din partner?", "de": "Hvilket af dine beg\u00e6r f\u00f8les stadig \"forbudt\", selvom det t\u00e6nder dig?", "es": "Welche deiner Begierden f\u00fchlt sich immer noch \u201everboten\u201c an, obwohl sie dich erregt?", "pt": "Como te sentes por ganhar mais ou menos do que o teu parceiro?", "ro": "Cum te sim\u021bi dac\u0103 c\u00e2\u0219tigi mai mult sau mai pu\u021bin dec\u00e2t partenerul t\u0103u?", "fr": "Que ressens-tu \u00e0 l\u2019id\u00e9e de gagner plus ou moins que ton partenaire ?", "it": "Come ti senti riguardo a guadagnare di pi\u00f9 o di meno rispetto al tuo partner?", "fi": "Milt\u00e4 sinusta tuntuu ansaita enemm\u00e4n tai v\u00e4hemm\u00e4n kuin kumppanisi?", "nl": "Hoe voel je je over het verdienen van meer of minder dan je partner?", "no": "Hvordan f\u00f8ler du om \u00e5 tjene mer eller mindre enn partneren din?", "sv": "Hur k\u00e4nner du f\u00f6r att tj\u00e4na mer eller mindre \u00e4n din partner?", "pl": "Jak si\u0119 czujesz w zwi\u0105zku z tym, \u017ce zarabiasz wi\u0119cej lub mniej ni\u017c tw\u00f3j partner?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'How do you feel about earning more or less than your partner?';
UPDATE questions
SET translations = '{"en": "What do you think your exes might say they learned from you?", "da": "Hvad tror du, dine eks\u2019er ville sige, de l\u00e6rte af dig?", "de": "Hvad f\u00e5r et \u00f8jeblik til at f\u00f8les dejligt forkert, men umuligt at modst\u00e5?", "es": "Was l\u00e4sst einen Moment sch\u00f6n falsch, aber unwiderstehlich f\u00fchlen?", "pt": "O que achas que os teus ex diriam que aprenderam contigo?", "ro": "Ce crezi c\u0103 ar spune fo\u0219tii t\u0103i c\u0103 au \u00eenv\u0103\u021bat de la tine?", "fr": "Que penses-tu que tes ex diraient avoir appris de toi ?", "it": "Cosa pensi che i tuoi ex possano dire di aver imparato da te?", "fi": "Mit\u00e4 luulet, mit\u00e4 entiset kumppanisi voisivat sanoa oppineensa sinulta?", "nl": "Wat denk je dat je exen zouden zeggen dat ze van jou hebben geleerd?", "no": "Hva tror du eksene dine ville sagt at de l\u00e6rte av deg?", "sv": "Vad tror du att dina ex kan s\u00e4ga att de har l\u00e4rt sig av dig?", "pl": "Co my\u015blisz, co twoje by\u0142e osoby mog\u0142yby powiedzie\u0107, \u017ce si\u0119 od ciebie nauczy\u0142y?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What do you think your exes might say they learned from you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you sometimes judge others for \u2014 but also see a little of in yourself?", "da": "Hvad er noget, du nogle gange d\u00f8mmer andre for \u2014 men ogs\u00e5 ser lidt af i dig selv?", "de": "Hvilken slags hemmelighed mellem os ville du gerne beholde for evigt?", "es": "Welche Art von Geheimnis zwischen uns w\u00fcrdest du gerne f\u00fcr immer behalten?", "pt": "O que julgas \u00e0s vezes nos outros mas tamb\u00e9m v\u00eas em ti?", "ro": "Ce este ceva ce judeci la al\u021bii, dar recuno\u0219ti \u0219i \u00een tine?", "fr": "Quelle chose juges-tu parfois chez les autres mais reconnais-tu un peu chez toi ?", "it": "Qual \u00e8 qualcosa per cui a volte giudichi gli altri, ma che vedi anche un po'' in te stesso?", "fi": "Mik\u00e4 on jotain, jota joskus arvostelet muissa \u2014 mutta n\u00e4et my\u00f6s siit\u00e4 pienen osan itsess\u00e4si?", "nl": "Wat is iets waar je anderen soms op beoordeelt, maar waar je ook een beetje van in jezelf ziet?", "no": "Hva er noe du noen ganger d\u00f8mmer andre for \u2014 men ogs\u00e5 ser litt av i deg selv?", "sv": "Vad \u00e4r n\u00e5got du ibland d\u00f6mer andra f\u00f6r \u2014 men ocks\u00e5 ser lite av i dig sj\u00e4lv?", "pl": "Co\u015b, za co czasami oceniam innych \u2014 ale r\u00f3wnie\u017c dostrzegam to troch\u0119 w sobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you sometimes judge others for — but also see a little of in yourself?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you learned about yourself from your last relationship?", "da": "Hvad har du l\u00e6rt om dig selv fra dit sidste forhold?", "de": "Hvad er det f\u00f8rste, dine \u00f8jne g\u00e5r efter, n\u00e5r jeg begynder at kl\u00e6de mig af?", "es": "Wohin gehen deine Augen zuerst, wenn ich beginne, mich auszuziehen?", "pt": "O que aprendeste sobre ti mesmo com o teu \u00faltimo relacionamento?", "ro": "Ce ai \u00eenv\u0103\u021bat despre tine din ultima ta rela\u021bie?", "fr": "Qu\u2019as-tu appris sur toi-m\u00eame gr\u00e2ce \u00e0 ta derni\u00e8re relation ?", "it": "Qualcosa che hai imparato su te stesso dalla tua ultima relazione?", "fi": "Mit\u00e4 olet oppinut itsest\u00e4si edellisest\u00e4 suhteestasi?", "nl": "Wat is iets dat je over jezelf hebt geleerd van je laatste relatie?", "no": "Hva er noe du l\u00e6rte om deg selv fra ditt forrige forhold?", "sv": "Vad \u00e4r n\u00e5got du l\u00e4rde dig om dig sj\u00e4lv fr\u00e5n ditt senaste f\u00f6rh\u00e5llande?", "pl": "Co\u015b, czego si\u0119 nauczy\u0142e\u015b o sobie z ostatniego zwi\u0105zku?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something you learned about yourself from your last relationship?';
UPDATE questions
SET translations = '{"en": "When was a time jealousy actually taught you something about yourself?", "da": "Hvorn\u00e5r har jalousi faktisk l\u00e6rt dig noget om dig selv?", "de": "Hvilken smag ville du gerne smage p\u00e5 mine l\u00e6ber?", "es": "Welchen Geschmack w\u00fcrdest du gerne auf meinen Lippen schmecken?", "pt": "Quando \u00e9 que o ci\u00fame realmente te ensinou algo sobre ti pr\u00f3prio?", "ro": "C\u00e2nd te-a \u00eenv\u0103\u021bat gelozia ceva despre tine?", "fr": "Quand la jalousie t\u2019a-t-elle r\u00e9ellement appris quelque chose sur toi-m\u00eame ?", "it": "Quando \u00e8 stata una volta in cui la gelosia ti ha insegnato qualcosa su te stesso?", "fi": "Milloin kateus oikeasti opetti sinulle jotain itsest\u00e4si?", "nl": "Wanneer was een moment waarop jaloezie je daadwerkelijk iets over jezelf heeft geleerd?", "no": "N\u00e5r var det en gang sjalusi faktisk l\u00e6rte deg noe om deg selv?", "sv": "N\u00e4r var en tid d\u00e5 svartsjuka faktiskt l\u00e4rde dig n\u00e5got om dig sj\u00e4lv?", "pl": "Kiedy zazdro\u015b\u0107 nauczy\u0142a ci\u0119 czego\u015b o sobie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'When was a time jealousy actually taught you something about yourself?';
UPDATE questions
SET translations = '{"en": "What\u2019s something your best friend knows about you that I don\u2019t \u2014 yet?", "da": "Hvad ved din bedste ven om dig, som jeg ikke g\u00f8r \u2014 endnu?", "de": "Hvad ville du \u00f8nske, jeg gjorde oftere under forspil?", "es": "Was w\u00fcrdest du dir w\u00fcnschen, dass ich beim Vorspiel \u00f6fter tue?", "pt": "O que o teu melhor amigo sabe sobre ti que eu ainda n\u00e3o sei?", "ro": "Ce \u0219tie cel mai bun prieten al t\u0103u despre tine, dar eu nu?", "fr": "Qu\u2019est-ce que ton meilleur ami sait sur toi que je ne sais pas \u2014 encore ?", "it": "Qualcosa che il tuo migliore amico sa di te che io non so \u2014 ancora?", "fi": "Mik\u00e4 on jotain, mit\u00e4 paras yst\u00e4v\u00e4si tiet\u00e4\u00e4 sinusta, mutta min\u00e4 en \u2014 viel\u00e4?", "nl": "Wat is iets dat je beste vriend(in) over jou weet dat ik nog niet weet?", "no": "Hva er noe din beste venn vet om deg som jeg ikke vet \u2014 enn\u00e5?", "sv": "Vad \u00e4r det som din b\u00e4sta v\u00e4n vet om dig som jag inte vet \u2014 \u00e4n?", "pl": "Co\u015b, co tw\u00f3j najlepszy przyjaciel wie o tobie, a ja jeszcze nie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Do-you-dare Talks'
  AND translations->>'en' = 'What’s something your best friend knows about you that I don’t — yet?';