UPDATE questions
SET translations = '{"en": "\u201cMonogamy is overrated in modern relationships.\u201d", "da": "Monogami er overvurderet i moderne forhold.", "de": "Monogamie ist in modernen Beziehungen \u00fcberbewertet.", "es": "La monogamia est\u00e1 sobrevalorada en las relaciones modernas.", "pt": "A monogamia est\u00e1 sobrevalorizada nas rela\u00e7\u00f5es modernas.", "ro": "Monogamia este supraevaluat\u0103 \u00een rela\u021biile moderne.", "fr": "La monogamie est surestim\u00e9e dans les relations modernes.", "it": "\"La monogamia \u00e8 sopravvalutata nelle relazioni moderne.\"", "fi": "\"Monogamia on yliarvostettua nykyaikaisissa suhteissa.\"", "nl": "\"Monogamie is overschat in moderne relaties.\"", "no": "\"Monogami er overvurdert i moderne forhold.\"", "sv": "\"Monogami \u00e4r \u00f6verskattat i moderna relationer.\"", "pl": "\u201eMonogamia jest przereklamowana w nowoczesnych zwi\u0105zkach.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Monogamy is overrated in modern relationships.”';
UPDATE questions
SET translations = '{"en": "\u201cIt\u2019s okay to want a simple, quiet life instead of chasing \u2018main character energy.\u2019\u201d", "da": "Det er okay at \u00f8nske et simpelt, stille liv i stedet for at jagte \u201cmain character energy\u201d.", "de": "Es ist okay, ein einfaches, ruhiges Leben zu wollen, statt \u201eMain Character Energy\u201c zu jagen.", "es": "Est\u00e1 bien querer una vida simple y tranquila en lugar de perseguir la \u201cenerg\u00eda de protagonista\u201d.", "pt": "Est\u00e1 tudo bem querer uma vida simples e calma em vez de perseguir a \u201cenergia de protagonista\u201d.", "ro": "Este \u00een regul\u0103 s\u0103 vrei o via\u021b\u0103 simpl\u0103 \u0219i lini\u0219tit\u0103 \u00een loc s\u0103 alergi dup\u0103 \u201cenergia de personaj principal\u201d.", "fr": "C\u2019est bien de vouloir une vie simple et calme au lieu de courir apr\u00e8s l\u2019\u00ab \u00e9nergie de personnage principal \u00bb.", "it": "\"Va bene desiderare una vita semplice e tranquilla invece di inseguire l''energia del ''personaggio principale''.\"", "fi": "\"On ihan ok haluta yksinkertaista, rauhallista el\u00e4m\u00e4\u00e4 sen sijaan, ett\u00e4 jahtaa ''p\u00e4\u00e4henkil\u00f6energiaa''.\"", "nl": "\"Het is ok\u00e9 om een eenvoudig, rustig leven te willen in plaats van te jagen op ''hoofdpersonage-energie''.\"", "no": "\"Det er greit \u00e5 \u00f8nske seg et enkelt, stille liv i stedet for \u00e5 jage etter ''hovedkarakterenergi''.\"", "sv": "\"Det \u00e4r okej att vilja ha ett enkelt, lugnt liv ist\u00e4llet f\u00f6r att jaga ''huvudkarakt\u00e4rens energi.''\"", "pl": "\u201eTo w porz\u0105dku pragn\u0105\u0107 prostego, cichego \u017cycia zamiast goni\u0107 za ''energi\u0105 g\u0142\u00f3wnego bohatera''.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“It’s okay to want a simple, quiet life instead of chasing ‘main character energy.’”';
UPDATE questions
SET translations = '{"en": "\u201cLong-distance relationships are unrealistic in the digital age.\u201d", "da": "Langdistanceforhold er urealistiske i den digitale tidsalder.", "de": "Fernbeziehungen sind im digitalen Zeitalter unrealistisch.", "es": "Las relaciones a distancia son poco realistas en la era digital.", "pt": "Rela\u00e7\u00f5es \u00e0 dist\u00e2ncia s\u00e3o irrealistas na era digital.", "ro": "Rela\u021biile la distan\u021b\u0103 sunt nerealiste \u00een era digital\u0103.", "fr": "Les relations \u00e0 distance sont irr\u00e9alistes \u00e0 l\u2019\u00e8re du num\u00e9rique.", "it": "\"Le relazioni a distanza sono irrealistiche nell''era digitale.\"", "fi": "\"Pitk\u00e4matkan suhteet ovat ep\u00e4realistisia digitaalisella aikakaudella.\"", "nl": "\"Langdurige relaties zijn onrealistisch in het digitale tijdperk.\"", "no": "\"Langdistanseforhold er urealistiske i den digitale tidsalder.\"", "sv": "\"Distansf\u00f6rh\u00e5llanden \u00e4r orealistiska i den digitala tids\u00e5ldern.\"", "pl": "\u201eZwi\u0105zki na odleg\u0142o\u015b\u0107 s\u0105 nierealistyczne w erze cyfrowej.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Long-distance relationships are unrealistic in the digital age.”';
UPDATE questions
SET translations = '{"en": "\u201cTravelling too much is disrespectful to local cultures.\u201d", "da": "At rejse for meget er respektl\u00f8st over for lokale kulturer.", "de": "Zu viel Reisen ist respektlos gegen\u00fcber lokalen Kulturen.", "es": "Viajar demasiado es una falta de respeto hacia las culturas locales.", "pt": "Viajar demais \u00e9 desrespeitoso para com as culturas locais.", "ro": "A c\u0103l\u0103tori prea mult e lips\u0103 de respect fa\u021b\u0103 de culturile locale.", "fr": "Voyager trop est irrespectueux envers les cultures locales.", "it": "\"Viaggiare troppo \u00e8 irrispettoso verso le culture locali.\"", "fi": "\"Liian paljon matkustaminen on ep\u00e4kunnioittavaa paikallisia kulttuureja kohtaan.\"", "nl": "\"Te veel reizen is respectloos tegenover lokale culturen.\"", "no": "\"\u00c5 reise for mye er respektl\u00f8st overfor lokale kulturer.\"", "sv": "\"Att resa f\u00f6r mycket \u00e4r respektl\u00f6st mot lokala kulturer.\"", "pl": "\u201eZbyt cz\u0119ste podr\u00f3\u017cowanie jest brakiem szacunku dla lokalnych kultur.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Travelling too much is disrespectful to local cultures.”';
UPDATE questions
SET translations = '{"en": "\u201cTourism is a form of cultural appropriation.\u201d", "da": "Turisme er en form for kulturel tilegnelse.", "de": "Tourismus ist eine Form kultureller Aneignung.", "es": "El turismo es una forma de apropiaci\u00f3n cultural.", "pt": "O turismo \u00e9 uma forma de apropria\u00e7\u00e3o cultural.", "ro": "Turismul este o form\u0103 de \u00eensu\u0219ire cultural\u0103.", "fr": "Le tourisme est une forme d\u2019appropriation culturelle.", "it": "\"Il turismo \u00e8 una forma di appropriazione culturale.\"", "fi": "\u201dTurismi on er\u00e4\u00e4nlainen kulttuurinen omiminen.\u201d", "nl": "\u201cToerisme is een vorm van culturele toe-eigening.\u201d", "no": "\u00abTurisme er en form for kulturell appropriasjon.\u00bb", "sv": "\"Turism \u00e4r en form av kulturell appropriering.\"", "pl": "\u201eTurystyka jest form\u0105 przyw\u0142aszczenia kulturowego.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Tourism is a form of cultural appropriation.”';
UPDATE questions
SET translations = '{"en": "\u201cLuxury brands are just branding \u2014 the products rarely justify the price premium.\u201d", "da": "Luksusm\u00e6rker handler kun om branding \u2013 produkterne retf\u00e6rdigg\u00f8r sj\u00e6ldent prispr\u00e6mien.", "de": "Luxusmarken sind nur Branding \u2013 die Produkte rechtfertigen selten den Preisaufschlag.", "es": "Las marcas de lujo son solo marca: los productos rara vez justifican su precio.", "pt": "As marcas de luxo s\u00e3o apenas branding \u2014 os produtos raramente justificam o pre\u00e7o.", "ro": "M\u0103rcile de lux sunt doar un brand \u2014 produsele rareori justific\u0103 pre\u021bul.", "fr": "Les marques de luxe ne sont que du branding \u2014 les produits justifient rarement leur prix.", "it": "\"Le marche di lusso sono solo branding \u2014 i prodotti raramente giustificano il prezzo elevato.\"", "fi": "\"Ylelliset br\u00e4ndit ovat vain br\u00e4nd\u00e4yst\u00e4 \u2014 tuotteet harvoin oikeuttavat hintalis\u00e4n.\"", "nl": "\u201cLuxe merken zijn gewoon branding \u2014 de producten rechtvaardigen zelden de prijsverhoging.\u201d", "no": "\u00abLuksusmerker er bare merkevarebygging \u2014 produktene rettferdiggj\u00f8r sjelden prisforskjellen.\u00bb", "sv": "\"Lyxm\u00e4rken \u00e4r bara varum\u00e4rken \u2014 produkterna r\u00e4ttf\u00e4rdigar s\u00e4llan prispremiumen.\"", "pl": "\u201eMarki luksusowe to tylko branding \u2014 produkty rzadko uzasadniaj\u0105 wy\u017csz\u0105 cen\u0119.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Luxury brands are just branding — the products rarely justify the price premium.”';
UPDATE questions
SET translations = '{"en": "\u201cMinimalism is just another consumer trend.\u201d", "da": "Minimalisme er bare en anden forbrugertrend.", "de": "Minimalismus ist nur ein weiterer Konsumtrend.", "es": "El minimalismo es solo otra tendencia de consumo.", "pt": "O minimalismo \u00e9 apenas mais uma tend\u00eancia de consumo.", "ro": "Minimalismul este doar o alt\u0103 tendin\u021b\u0103 de consum.", "fr": "Le minimalisme n\u2019est qu\u2019une autre tendance de consommation.", "it": "\"Il minimalismo \u00e8 solo un''altra tendenza di consumo.\"", "fi": "\"Minimalismi on vain toinen kulutustrendi.\"", "nl": "\"Minimalisme is gewoon weer een andere consumententrend.\"", "no": "\"Minimalisme er bare en annen forbrukertrend.\"", "sv": "\"Minimalism \u00e4r bara en annan konsumtionstrend.\"", "pl": "\u201eMinimalizm to tylko kolejny trend konsumpcyjny.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Minimalism is just another consumer trend.”';
UPDATE questions
SET translations = '{"en": "\u201cYou don\u2019t need a college degree to succeed anymore.\u201d", "da": "Du beh\u00f8ver ikke en universitetsgrad for at f\u00e5 succes l\u00e6ngere.", "de": "Man braucht keinen Hochschulabschluss mehr, um erfolgreich zu sein.", "es": "Ya no necesitas un t\u00edtulo universitario para tener \u00e9xito.", "pt": "J\u00e1 n\u00e3o precisas de um diploma universit\u00e1rio para ter sucesso.", "ro": "Nu mai ai nevoie de o diplom\u0103 universitar\u0103 ca s\u0103 reu\u0219e\u0219ti.", "fr": "On n\u2019a plus besoin d\u2019un dipl\u00f4me universitaire pour r\u00e9ussir.", "it": "\"Non hai pi\u00f9 bisogno di una laurea per avere successo.\"", "fi": "\"Sinun ei tarvitse en\u00e4\u00e4 korkeakoulututkintoa menesty\u00e4ksesi.\"", "nl": "\"Je hebt tegenwoordig geen universitaire diploma meer nodig om succesvol te zijn.\"", "no": "\"Du trenger ikke en h\u00f8yskoleutdanning for \u00e5 lykkes lenger.\"", "sv": "\"Du beh\u00f6ver inte en h\u00f6gskoleexamen f\u00f6r att lyckas l\u00e4ngre.\"", "pl": "\u201eNie potrzebujesz ju\u017c dyplomu uczelni, aby odnie\u015b\u0107 sukces.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“You don’t need a college degree to succeed anymore.”';
UPDATE questions
SET translations = '{"en": "\u201cStandard schooling is outdated for the 21st century.\u201d", "da": "Standarduddannelse er for\u00e6ldet i det 21. \u00e5rhundrede.", "de": "Standardbildung ist im 21. Jahrhundert veraltet.", "es": "La educaci\u00f3n tradicional est\u00e1 obsoleta en el siglo XXI.", "pt": "O ensino padr\u00e3o est\u00e1 ultrapassado no s\u00e9culo XXI.", "ro": "Educa\u021bia standard este dep\u0103\u0219it\u0103 \u00een secolul XXI.", "fr": "L\u2019enseignement standard est d\u00e9pass\u00e9 au XXIe si\u00e8cle.", "it": "\"La scuola tradizionale \u00e8 obsoleta per il 21\u00b0 secolo.\"", "fi": "\"Perinteinen koulutus on vanhentunut 2000-luvulle.\"", "nl": "\"Standaardonderwijs is verouderd voor de 21ste eeuw.\"", "no": "\"Standard utdanning er utdatert for det 21. \u00e5rhundre.\"", "sv": "\"Standardutbildning \u00e4r f\u00f6r\u00e5ldrad f\u00f6r 2000-talet.\"", "pl": "\u201eStandardowe nauczanie jest przestarza\u0142e na XXI wiek.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Standard schooling is outdated for the 21st century.”';
UPDATE questions
SET translations = '{"en": "\u201cPhysical books are overrated in the age of e-readers.\u201d", "da": "Fysiske b\u00f8ger er overvurderede i e-l\u00e6sernes tidsalder.", "de": "Physische B\u00fccher sind im Zeitalter der E-Reader \u00fcberbewertet.", "es": "Los libros f\u00edsicos est\u00e1n sobrevalorados en la era de los e-readers.", "pt": "Os livros f\u00edsicos est\u00e3o sobrevalorizados na era dos e-readers.", "ro": "C\u0103r\u021bile fizice sunt supraevaluate \u00een epoca cititoarelor electronice.", "fr": "Les livres physiques sont surestim\u00e9s \u00e0 l\u2019\u00e8re des liseuses.", "it": "\"I libri fisici sono sopravvalutati nell''era degli e-reader.\"", "fi": "\"Fyysiset kirjat ovat yliarvostettuja e-lukijoiden aikakaudella.\"", "nl": "\"Fysieke boeken zijn overschat in het tijdperk van e-readers.\"", "no": "\"Fysiske b\u00f8ker er overvurderte i e-boklesernes tidsalder.\"", "sv": "\"Fysiska b\u00f6cker \u00e4r \u00f6verskattade i e-l\u00e4sarens tids\u00e5lder.\"", "pl": "\u201eFizyczne ksi\u0105\u017cki s\u0105 przereklamowane w erze czytnik\u00f3w e-book\u00f3w.\u201d"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Unpopular Opinions XL '
  AND translations->>'en' = '“Physical books are overrated in the age of e-readers.”';