UPDATE questions
SET translations = '{"en": "Who in this group would survive longest in a zombie apocalypse \u2014 and why?", "da": "Hvem i denne gruppe ville overleve l\u00e6ngst i en zombieapokalypse \u2014 og hvorfor?", "de": "Wer in dieser Gruppe w\u00fcrde am l\u00e4ngsten in einer Zombie-Apokalypse \u00fcberleben \u2013 und warum?", "es": "\u00bfQui\u00e9n en este grupo sobrevivir\u00eda m\u00e1s tiempo en un apocalipsis zombi \u2014 y por qu\u00e9?", "pt": "Quem neste grupo sobreviveria mais tempo em um apocalipse zumbi \u2014 e por qu\u00ea?", "ro": "Cine din acest grup ar supravie\u021bui cel mai mult \u00eentr-o apocalips\u0103 zombie \u2014 \u0219i de ce?", "fr": "Qui dans ce groupe survivrait le plus longtemps \u00e0 une apocalypse zombie \u2014 et pourquoi ?", "it": "Chi in questo gruppo sopravviverebbe pi\u00f9 a lungo a un''apocalisse zombie \u2014 e perch\u00e9?", "fi": "Kuka t\u00e4ss\u00e4 ryhm\u00e4ss\u00e4 selviytyisi pisimp\u00e4\u00e4n zombiapokalypsiss\u00e4 \u2014 ja miksi?", "nl": "Wie in deze groep zou het langst overleven in een zombie-apocalyps \u2014 en waarom?", "no": "Hvem i denne gruppen ville overlevd lengst i en zombie-apokalypse \u2014 og hvorfor?", "sv": "Vem i den h\u00e4r gruppen skulle \u00f6verleva l\u00e4ngst i en zombieapokalyps \u2014 och varf\u00f6r?", "pl": "Kto w tej grupie przetrwa\u0142by najd\u0142u\u017cej w apokalipsie zombie \u2014 i dlaczego?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'Who in this group would survive longest in a zombie apocalypse — and why?';
UPDATE questions
SET translations = '{"en": "What\u2019s a \u201cpopular\u201d song that drives you crazy?", "da": "Hvilken \u201cpopul\u00e6r\u201d sang driver dig til vanvid?", "de": "Welcher \u201epopul\u00e4re\u201c Song macht dich wahnsinnig?", "es": "\u00bfQu\u00e9 canci\u00f3n \u201cpopular\u201d te vuelve loco(a)?", "pt": "Que m\u00fasica \u201cpopular\u201d te enlouquece?", "ro": "Ce c\u00e2ntec \u201epopular\u201d te scoate din min\u021bi?", "fr": "Quelle chanson \u00ab populaire \u00bb te rend fou/folle ?", "it": "Qual \u00e8 una canzone \"popolare\" che ti fa impazzire?", "fi": "Mik\u00e4 on \"suosittu\" kappale, joka saa sinut hulluksi?", "nl": "Wat is een \"populaire\" song die je gek maakt?", "no": "Hva er en \"popul\u00e6r\" sang som gj\u00f8r deg gal?", "sv": "Vilken \"popul\u00e4r\" l\u00e5t g\u00f6r dig galen?", "pl": "Jaka \"popularna\" piosenka doprowadza ci\u0119 do sza\u0142u?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s a “popular” song that drives you crazy?';
UPDATE questions
SET translations = '{"en": "When do you feel most cared for by friends/family?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest passet p\u00e5 af venner/familie?", "de": "Wann f\u00fchlst du dich am meisten von Freunden/Familie umsorgt?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s cuidado(a) por tus amigos/familia?", "pt": "Quando voc\u00ea se sente mais cuidado(a) por amigos/fam\u00edlia?", "ro": "C\u00e2nd te sim\u021bi cel mai \u00eengrijit(\u0103) de prieteni/familie?", "fr": "Quand te sens-tu le plus pris(e) en charge par tes amis/ta famille ?", "it": "Quando ti senti pi\u00f9 coccolato dagli amici/dalla famiglia?", "fi": "Milloin tunnet itsesi eniten v\u00e4litetyksi yst\u00e4vien/perheen toimesta?", "nl": "Wanneer voel je je het meest verzorgd door vrienden/familie?", "no": "N\u00e5r f\u00f8ler du deg mest ivaretatt av venner/familie?", "sv": "N\u00e4r k\u00e4nner du dig mest omh\u00e4ndertagen av v\u00e4nner/familj?", "pl": "Kiedy czujesz si\u0119 najbardziej kochany przez przyjaci\u00f3\u0142/rodzin\u0119?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'When do you feel most cared for by friends/family?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite way to unwind after a long day?", "da": "Hvad er din yndlingsm\u00e5de at slappe af p\u00e5 efter en lang dag?", "de": "Was ist deine Lieblingsmethode, um nach einem langen Tag zu entspannen?", "es": "\u00bfCu\u00e1l es tu forma favorita de relajarte despu\u00e9s de un largo d\u00eda?", "pt": "Qual \u00e9 a sua maneira favorita de relaxar depois de um longo dia?", "ro": "Care este modul t\u0103u preferat de a te relaxa dup\u0103 o zi lung\u0103?", "fr": "Quelle est ta fa\u00e7on pr\u00e9f\u00e9r\u00e9e de te d\u00e9tendre apr\u00e8s une longue journ\u00e9e ?", "it": "Qual \u00e8 il tuo modo preferito di rilassarti dopo una lunga giornata?", "fi": "Mik\u00e4 on suosikkitapasi rentoutua pitk\u00e4n p\u00e4iv\u00e4n j\u00e4lkeen?", "nl": "Wat is jouw favoriete manier om te ontspannen na een lange dag?", "no": "Hva er din favorittm\u00e5te \u00e5 slappe av p\u00e5 etter en lang dag?", "sv": "Vad \u00e4r ditt favorit s\u00e4tt att koppla av efter en l\u00e5ng dag?", "pl": "Jaki jest tw\u00f3j ulubiony spos\u00f3b na relaks po d\u0142ugim dniu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your favorite way to unwind after a long day?';
UPDATE questions
SET translations = '{"en": "If we could teleport anywhere for a cozy weekend getaway, where would we go?", "da": "Hvis vi kunne teleportere hvor som helst til en hyggelig weekend, hvor skulle vi tage hen?", "de": "Wenn wir uns f\u00fcr ein gem\u00fctliches Wochenende irgendwohin teleportieren k\u00f6nnten, wohin w\u00fcrden wir gehen?", "es": "Si pudi\u00e9ramos teletransportarnos a cualquier lugar para un fin de semana acogedor, \u00bfa d\u00f3nde ir\u00edamos?", "pt": "Se pud\u00e9ssemos nos teletransportar para um fim de semana aconchegante, para onde ir\u00edamos?", "ro": "Dac\u0103 ne-am putea teleporta oriunde pentru un weekend relaxant, unde am merge?", "fr": "Si nous pouvions nous t\u00e9l\u00e9porter pour un week-end cocooning, o\u00f9 irions-nous ?", "it": "Se potessimo teletrasportarci ovunque per un weekend di fuga accogliente, dove andremmo?", "fi": "Jos voisimme teleportoida minne tahansa mukavalle viikonloppumatkalle, minne menisimme?", "nl": "Als we overal naartoe konden teleporteren voor een gezellig weekendje weg, waar zouden we dan naartoe gaan?", "no": "Hvis vi kunne teleportere hvor som helst for en koselig helgetur, hvor ville vi dra?", "sv": "Om vi kunde teleportera oss vart som helst f\u00f6r en mysig weekendresa, vart skulle vi \u00e5ka?", "pl": "Gdyby\u015bmy mogli teleportowa\u0107 si\u0119 gdziekolwiek na przytulny weekendowy wypad, dok\u0105d by\u015bmy pojechali?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If we could teleport anywhere for a cozy weekend getaway, where would we go?';
UPDATE questions
SET translations = '{"en": "What\u2019s your favorite candle scent or smell to have at home?", "da": "Hvilken duft af stearinlys eller lugt elsker du at have derhjemme?", "de": "Welcher Kerzenduft oder Geruch gef\u00e4llt dir zu Hause am besten?", "es": "\u00bfCu\u00e1l es tu aroma de vela o fragancia favorita para tener en casa?", "pt": "Qual \u00e9 o seu cheiro ou aroma de vela favorito para ter em casa?", "ro": "Care este mirosul sau parfumul de lum\u00e2nare preferat pentru acas\u0103?", "fr": "Quelle senteur de bougie ou parfum aimes-tu avoir \u00e0 la maison ?", "it": "Qual \u00e8 la tua fragranza di candela preferita o odore da avere in casa?", "fi": "Mik\u00e4 on suosikkikynttil\u00e4tuoksusi tai -hajusi, jonka haluaisit kotiisi?", "nl": "Wat is jouw favoriete kaarsgeur of geur om thuis te hebben?", "no": "Hva er din favorittlysduft eller lukt \u00e5 ha hjemme?", "sv": "Vilken \u00e4r din favoritdoft av ljus eller doft som du gillar att ha hemma?", "pl": "Jaki jest tw\u00f3j ulubiony zapach \u015bwiecy lub aromat, kt\u00f3ry lubisz mie\u0107 w domu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your favorite candle scent or smell to have at home?';
UPDATE questions
SET translations = '{"en": "If you could recreate one cozy memory from childhood, what would it be?", "da": "Hvis du kunne genskabe et hyggeligt barndomsminde, hvilket ville det v\u00e6re?", "de": "Wenn du eine gem\u00fctliche Kindheitserinnerung wiedererleben k\u00f6nntest, welche w\u00e4re das?", "es": "Si pudieras recrear un recuerdo acogedor de tu infancia, \u00bfcu\u00e1l ser\u00eda?", "pt": "Se voc\u00ea pudesse recriar uma lembran\u00e7a aconchegante da inf\u00e2ncia, qual seria?", "ro": "Dac\u0103 ai putea recrea o amintire cald\u0103 din copil\u0103rie, care ar fi?", "fr": "Si tu pouvais recr\u00e9er un souvenir d\u2019enfance chaleureux, lequel serait-ce ?", "it": "Se potessi ricreare un ricordo accogliente dell''infanzia, quale sarebbe?", "fi": "Jos voisit el\u00e4\u00e4 uudelleen yhden lapsuuden mukavan muiston, mik\u00e4 se olisi?", "nl": "Als je \u00e9\u00e9n gezellige herinnering uit je kindertijd opnieuw zou kunnen cre\u00ebren, welke zou dat dan zijn?", "no": "Hvis du kunne gjenskape ett koselig minne fra barndommen, hva ville det v\u00e6rt?", "sv": "Om du kunde \u00e5terskapa ett mysigt minne fr\u00e5n barndomen, vilket skulle det vara?", "pl": "Gdyby\u015b m\u00f3g\u0142 odtworzy\u0107 jedno przytulne wspomnienie z dzieci\u0144stwa, co by to by\u0142o?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'If you could recreate one cozy memory from childhood, what would it be?';
UPDATE questions
SET translations = '{"en": "What\u2019s your ideal lazy Sunday?", "da": "Hvordan ser din ideelle dovne s\u00f8ndag ud?", "de": "Wie sieht dein idealer fauler Sonntag aus?", "es": "\u00bfC\u00f3mo es tu domingo perezoso ideal?", "pt": "Como \u00e9 o seu domingo pregui\u00e7oso ideal?", "ro": "Cum arat\u0103 duminica ta lene\u0219\u0103 ideal\u0103?", "fr": "\u00c0 quoi ressemble ton dimanche paresseux id\u00e9al ?", "it": "Qual \u00e8 il tuo ideale domenica pigra?", "fi": "Mik\u00e4 on sinun ihanteellinen laiskottelusunnuntai?", "nl": "Wat is jouw ideale luie zondag?", "no": "Hva er din ideelle late s\u00f8ndag?", "sv": "Vad \u00e4r din perfekta lata s\u00f6ndag?", "pl": "Jaki jest tw\u00f3j idealny leniwy niedzielny dzie\u0144?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s your ideal lazy Sunday?';
UPDATE questions
SET translations = '{"en": "What kind of weather makes you happiest?", "da": "Hvilket vejr g\u00f8r dig mest glad?", "de": "Welches Wetter macht dich am gl\u00fccklichsten?", "es": "\u00bfQu\u00e9 tipo de clima te hace m\u00e1s feliz?", "pt": "Que tipo de clima te deixa mais feliz?", "ro": "Ce tip de vreme te face cel mai fericit(\u0103)?", "fr": "Quel type de m\u00e9t\u00e9o te rend le plus heureux(se) ?", "it": "Che tipo di tempo ti rende pi\u00f9 felice?", "fi": "Mink\u00e4lainen s\u00e4\u00e4 tekee sinut onnelliseksi?", "nl": "Wat voor soort weer maakt jou het gelukkigst?", "no": "Hvilken type v\u00e6r gj\u00f8r deg lykkeligst?", "sv": "Vilken typ av v\u00e4der g\u00f6r dig lyckligast?", "pl": "Jaka pogoda sprawia, \u017ce jeste\u015b najszcz\u0119\u015bliwszy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What kind of weather makes you happiest?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you\u2019ve recently learned to appreciate?", "da": "Hvad er noget, du for nylig har l\u00e6rt at s\u00e6tte pris p\u00e5?", "de": "Was hast du in letzter Zeit sch\u00e4tzen gelernt?", "es": "\u00bfQu\u00e9 es algo que has aprendido a apreciar recientemente?", "pt": "O que voc\u00ea aprendeu a valorizar recentemente?", "ro": "Ce ai \u00eenv\u0103\u021bat recent s\u0103 apreciezi?", "fr": "Qu\u2019as-tu appris \u00e0 appr\u00e9cier r\u00e9cemment ?", "it": "Qualcosa che hai recentemente imparato ad apprezzare?", "fi": "Mik\u00e4 on jotain, mit\u00e4 olet \u00e4skett\u00e4in oppinut arvostamaan?", "nl": "Wat is iets dat je recentelijk hebt leren waarderen?", "no": "Hva er noe du nylig har l\u00e6rt \u00e5 sette pris p\u00e5?", "sv": "Vad \u00e4r n\u00e5got du nyligen har l\u00e4rt dig att uppskatta?", "pl": "Co\u015b, co ostatnio nauczy\u0142e\u015b si\u0119 docenia\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Cozy Talks'
  AND translations->>'en' = 'What’s something you’ve recently learned to appreciate?';