UPDATE questions
SET translations = '{"en": "What\u2019s something you remember breaking and having to fix by hand?", "da": "Hvad er noget, du husker at have \u00f8delagt og m\u00e5tte reparere i h\u00e5nden?", "de": "Was erinnerst du dich, kaputt gemacht und von Hand repariert zu haben?", "es": "\u00bfQu\u00e9 recuerdas haber roto y tenido que arreglar a mano?", "pt": "O que te lembras de ter partido e consertado \u00e0 m\u00e3o?", "ro": "Ce \u00ee\u021bi aminte\u0219ti c\u0103 ai stricat \u0219i a trebuit s\u0103 repari cu m\u00e2na?", "fr": "De quoi te souviens-tu avoir cass\u00e9 et d\u00fb r\u00e9parer \u00e0 la main ?", "it": "Qualcosa che ricordi di aver rotto e di aver dovuto riparare a mano?", "fi": "Mik\u00e4 on jotain, jonka muistat rikkoneesi ja joutuneesi korjaamaan k\u00e4sin?", "nl": "Wat is iets dat je je herinnert dat je hebt gebroken en met de hand moest repareren?", "no": "Hva er noe du husker at du brakk og m\u00e5tte fikse for h\u00e5nd?", "sv": "Vad \u00e4r n\u00e5got du minns att du br\u00f6t och var tvungen att laga f\u00f6r hand?", "pl": "Co\u015b, co pami\u0119tasz, \u017ce zepsu\u0142e\u015b i musia\u0142e\u015b naprawi\u0107 r\u0119cznie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you remember breaking and having to fix by hand?';
UPDATE questions
SET translations = '{"en": "What\u2019s something you learned to live without back then that everyone has now?", "da": "Hvad er noget, du l\u00e6rte at leve uden dengang, som alle har nu?", "de": "Was hast du gelernt, fr\u00fcher ohne zu leben, was heute jeder hat?", "es": "\u00bfQu\u00e9 aprendiste a vivir sin tener antes, que ahora todos tienen?", "pt": "O que aprendeste a viver sem, que agora todos t\u00eam?", "ro": "Ce ai \u00eenv\u0103\u021bat s\u0103 tr\u0103ie\u0219ti f\u0103r\u0103 atunci, dar toat\u0103 lumea are acum?", "fr": "De quoi as-tu appris \u00e0 te passer autrefois que tout le monde a maintenant ?", "it": "Qualcosa che hai imparato a vivere senza all''epoca che tutti hanno adesso?", "fi": "Mik\u00e4 on jotain, mit\u00e4 opit el\u00e4m\u00e4\u00e4n ilman silloin, mutta mit\u00e4 kaikilla on nyt?", "nl": "Wat is iets waar je toen leerde zonder te leven dat iedereen nu heeft?", "no": "Hva er noe du l\u00e6rte \u00e5 leve uten den gang som alle har n\u00e5?", "sv": "Vad \u00e4r n\u00e5got du l\u00e4rde dig att leva utan d\u00e5 som alla har nu?", "pl": "Co\u015b, czego nauczy\u0142e\u015b si\u0119 \u017cy\u0107 bez wtedy, co teraz ma ka\u017cdy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something you learned to live without back then that everyone has now?';
UPDATE questions
SET translations = '{"en": "What was shopping like before online stores?", "da": "Hvordan var det at handle, f\u00f8r der fandtes onlinebutikker?", "de": "Wie war Einkaufen, bevor es Online-Shops gab?", "es": "\u00bfC\u00f3mo era ir de compras antes de las tiendas en l\u00ednea?", "pt": "Como era fazer compras antes das lojas online?", "ro": "Cum era cump\u0103r\u0103turile \u00eenainte de magazinele online?", "fr": "Comment faisait-on du shopping avant les magasins en ligne ?", "it": "Com''era fare shopping prima dei negozi online?", "fi": "Millainen ostaminen oli ennen verkkokauppoja?", "nl": "Hoe was winkelen voordat er online winkels waren?", "no": "Hvordan var shopping f\u00f8r nettbutikker?", "sv": "Hur var shopping innan n\u00e4tbutiker?", "pl": "Jak wygl\u0105da\u0142y zakupy przed pojawieniem si\u0119 sklep\u00f3w internetowych?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was shopping like before online stores?';
UPDATE questions
SET translations = '{"en": "Tell me about how you met the love of your life.", "da": "Fort\u00e6l mig, hvordan du m\u00f8dte k\u00e6rligheden i dit liv.", "de": "Erz\u00e4hl mir, wie du die Liebe deines Lebens getroffen hast.", "es": "Cu\u00e9ntame c\u00f3mo conociste al amor de tu vida.", "pt": "Conta-me como conheceste o amor da tua vida.", "ro": "Spune-mi cum \u021bi-ai \u00eent\u00e2lnit dragostea vie\u021bii tale.", "fr": "Raconte-moi comment tu as rencontr\u00e9 l\u2019amour de ta vie.", "it": "Raccontami di come hai incontrato l''amore della tua vita.", "fi": "Kerro minulle, miten tapasit el\u00e4m\u00e4si rakkauden.", "nl": "Vertel me hoe je de liefde van je leven hebt ontmoet.", "no": "Fortell meg om hvordan du m\u00f8tte kj\u00e6rligheten i livet ditt.", "sv": "Ber\u00e4tta om hur du tr\u00e4ffade k\u00e4rleken i ditt liv.", "pl": "Opowiedz mi, jak pozna\u0142e\u015b mi\u0142o\u015b\u0107 swojego \u017cycia."}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'Tell me about how you met the love of your life.';
UPDATE questions
SET translations = '{"en": "What\u2019s one thing you think people appreciate less now than before?", "da": "Hvad er \u00e9n ting, du tror, folk v\u00e6rds\u00e6tter mindre nu end f\u00f8r?", "de": "Was ist eine Sache, die die Menschen heute weniger sch\u00e4tzen als fr\u00fcher?", "es": "\u00bfQu\u00e9 cosa crees que la gente aprecia menos ahora que antes?", "pt": "O que achas que as pessoas valorizam menos agora do que antes?", "ro": "Ce lucru crezi c\u0103 oamenii apreciaz\u0103 mai pu\u021bin acum dec\u00e2t \u00eenainte?", "fr": "Quelle chose penses-tu que les gens appr\u00e9cient moins aujourd\u2019hui qu\u2019avant ?", "it": "Qual \u00e8 una cosa che pensi le persone apprezzino meno adesso rispetto a prima?", "fi": "Mik\u00e4 on yksi asia, jota luulet ihmisten arvostavan v\u00e4hemm\u00e4n nyt kuin ennen?", "nl": "Wat is \u00e9\u00e9n ding dat je denkt dat mensen nu minder waarderen dan vroeger?", "no": "Hva er \u00e9n ting du tror folk setter mindre pris p\u00e5 n\u00e5 enn f\u00f8r?", "sv": "Vad \u00e4r en sak som du tror att folk uppskattar mindre nu \u00e4n tidigare?", "pl": "Co\u015b, co my\u015blisz, \u017ce ludzie mniej doceniaj\u0105 teraz ni\u017c wcze\u015bniej?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s one thing you think people appreciate less now than before?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to make at home instead of buying?", "da": "Hvad er noget, folk plejede at lave derhjemme i stedet for at k\u00f8be?", "de": "Was haben die Leute fr\u00fcher zu Hause gemacht, anstatt es zu kaufen?", "es": "\u00bfQu\u00e9 sol\u00edan hacer las personas en casa en lugar de comprarlo?", "pt": "O que as pessoas costumavam fazer em casa em vez de comprar?", "ro": "Ce obi\u0219nuiau oamenii s\u0103 fac\u0103 acas\u0103 \u00een loc s\u0103 cumpere?", "fr": "Que faisaient les gens autrefois chez eux au lieu de l\u2019acheter ?", "it": "Qualcosa che le persone facevano in casa invece di comprare?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen tekiv\u00e4t kotona sen sijaan, ett\u00e4 ostaisivat sen?", "nl": "Wat is iets dat mensen vroeger thuis maakten in plaats van het te kopen?", "no": "Hva er noe folk pleide \u00e5 lage hjemme i stedet for \u00e5 kj\u00f8pe?", "sv": "Vad \u00e4r n\u00e5got som folk brukade g\u00f6ra hemma ist\u00e4llet f\u00f6r att k\u00f6pa?", "pl": "Co\u015b, co ludzie kiedy\u015b robili w domu zamiast kupowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to make at home instead of buying?';
UPDATE questions
SET translations = '{"en": "What was your first memory of seeing a computer, phone, or car?", "da": "Hvad er din f\u00f8rste erindring om at se en computer, telefon eller bil?", "de": "Was ist deine erste Erinnerung daran, einen Computer, ein Telefon oder ein Auto gesehen zu haben?", "es": "\u00bfCu\u00e1l es tu primer recuerdo de ver una computadora, un tel\u00e9fono o un coche?", "pt": "Qual \u00e9 a tua primeira lembran\u00e7a de ver um computador, um telefone ou um carro?", "ro": "Care este prima ta amintire de c\u00e2nd ai v\u0103zut un computer, un telefon sau o ma\u0219in\u0103?", "fr": "Quel est ton premier souvenir d\u2019avoir vu un ordinateur, un t\u00e9l\u00e9phone ou une voiture ?", "it": "Qual \u00e8 stato il tuo primo ricordo di aver visto un computer, un telefono o un''auto?", "fi": "Mik\u00e4 oli ensimm\u00e4inen muistosi tietokoneen, puhelimen tai auton n\u00e4kemisest\u00e4?", "nl": "Wat is je eerste herinnering aan het zien van een computer, telefoon of auto?", "no": "Hva var ditt f\u00f8rste minne om \u00e5 se en datamaskin, telefon eller bil?", "sv": "Vad \u00e4r ditt f\u00f6rsta minne av att se en dator, telefon eller bil?", "pl": "Jakie jest twoje pierwsze wspomnienie zwi\u0105zane z widzeniem komputera, telefonu lub samochodu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What was your first memory of seeing a computer, phone, or car?';
UPDATE questions
SET translations = '{"en": "What\u2019s something that cost very little back then but is expensive now?", "da": "Hvad er noget, der kostede meget lidt dengang, men som er dyrt nu?", "de": "Was hat fr\u00fcher sehr wenig gekostet, ist aber heute teuer?", "es": "\u00bfQu\u00e9 cosa costaba muy poco antes pero ahora es cara?", "pt": "O que custava muito pouco antes, mas \u00e9 caro agora?", "ro": "Ce lucru costa foarte pu\u021bin atunci, dar e scump acum?", "fr": "Quelle chose co\u00fbtait tr\u00e8s peu autrefois mais est ch\u00e8re aujourd\u2019hui ?", "it": "Qualcosa che costava molto poco allora ma adesso \u00e8 costoso?", "fi": "Mik\u00e4 on jotain, mik\u00e4 maksoi ennen hyvin v\u00e4h\u00e4n, mutta on nyt kallista?", "nl": "Wat is iets dat vroeger heel weinig kostte maar nu duur is?", "no": "Hva er noe som kostet veldig lite den gangen, men som er dyrt n\u00e5?", "sv": "Vad \u00e4r n\u00e5got som kostade v\u00e4ldigt lite d\u00e5 men som \u00e4r dyrt nu?", "pl": "Co\u015b, co kiedy\u015b kosztowa\u0142o bardzo ma\u0142o, a teraz jest drogie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something that cost very little back then but is expensive now?';
UPDATE questions
SET translations = '{"en": "What\u2019s something people used to do more slowly \u2014 and that was a good thing?", "da": "Hvad er noget, folk plejede at g\u00f8re langsommere \u2014 og det var godt?", "de": "Was haben die Leute fr\u00fcher langsamer gemacht \u2013 und das war gut so?", "es": "\u00bfQu\u00e9 hac\u00edan las personas m\u00e1s despacio antes \u2014 y era algo bueno?", "pt": "O que as pessoas faziam mais devagar antigamente \u2014 e era bom?", "ro": "Ce f\u0103ceau oamenii mai \u00eencet \u00eenainte \u2014 \u0219i era un lucru bun?", "fr": "Quelle chose les gens faisaient-ils plus lentement avant \u2014 et c\u2019\u00e9tait bien ainsi ?", "it": "Qualcosa che le persone facevano pi\u00f9 lentamente \u2014 e che era una cosa positiva?", "fi": "Mik\u00e4 on jotain, mit\u00e4 ihmiset ennen tekiv\u00e4t hitaammin \u2014 ja se oli hyv\u00e4 asia?", "nl": "Wat is iets dat mensen vroeger langzamer deden \u2014 en dat een goede zaak was?", "no": "Hva er noe folk pleide \u00e5 gj\u00f8re saktere \u2014 og som var en god ting?", "sv": "Vad \u00e4r n\u00e5got som folk brukade g\u00f6ra l\u00e5ngsammare \u2014 och som var en bra sak?", "pl": "Co\u015b, co ludzie robili kiedy\u015b wolniej \u2014 i to by\u0142o dobre?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What’s something people used to do more slowly — and that was a good thing?';
UPDATE questions
SET translations = '{"en": "What kind of music did you listen to, and how did you play it?", "da": "Hvilken slags musik lyttede du til, og hvordan spillede du den?", "de": "Welche Musik hast du geh\u00f6rt, und wie hast du sie gespielt?", "es": "\u00bfQu\u00e9 tipo de m\u00fasica escuchabas y c\u00f3mo la reproduc\u00edas?", "pt": "Que tipo de m\u00fasica ouvias e como a tocavas?", "ro": "Ce fel de muzic\u0103 ascultai \u0219i cum o redai?", "fr": "Quel genre de musique \u00e9coutais-tu et comment la jouais-tu ?", "it": "Che tipo di musica ascoltavi e come la suonavi?", "fi": "Millaista musiikkia kuuntelit ja miten soitit sit\u00e4?", "nl": "Welke soort muziek luisterde je naar, en hoe speelde je het?", "no": "Hvilken type musikk h\u00f8rte du p\u00e5, og hvordan spilte du den?", "sv": "Vilken typ av musik lyssnade du p\u00e5, och hur spelade du den?", "pl": "Jakiej muzyki s\u0142ucha\u0142e\u015b i jak j\u0105 odtwarza\u0142e\u015b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'The Good Old Days Talks'
  AND translations->>'en' = 'What kind of music did you listen to, and how did you play it?';