UPDATE questions
SET translations = '{"en": "What parts of your independence are most important for me to respect?", "da": "Hvilke dele af din uafh\u00e6ngighed er vigtigst for mig at respektere?", "de": "Welche Teile deiner Unabh\u00e4ngigkeit sind f\u00fcr mich am wichtigsten zu respektieren?", "es": "\u00bfQu\u00e9 partes de tu independencia son m\u00e1s importantes para que yo respete?", "pt": "Quais partes da sua independ\u00eancia s\u00e3o mais importantes para eu respeitar?", "ro": "Ce p\u0103r\u021bi din independen\u021ba ta sunt cele mai importante pentru mine s\u0103 le respect?", "fr": "Quelles parties de ton ind\u00e9pendance sont les plus importantes pour moi \u00e0 respecter ?", "it": "Quali aspetti della tua indipendenza sono pi\u00f9 importanti per me da rispettare?", "fi": "Mitk\u00e4 osat itsen\u00e4isyydest\u00e4si ovat t\u00e4rkeimpi\u00e4, ett\u00e4 kunnioitan?", "nl": "Welke delen van jouw onafhankelijkheid zijn het belangrijkst voor mij om te respecteren?", "no": "Hvilke deler av din uavhengighet er viktigst for meg \u00e5 respektere?", "sv": "Vilka delar av din sj\u00e4lvst\u00e4ndighet \u00e4r viktigast f\u00f6r mig att respektera?", "pl": "Jakie aspekty twojej niezale\u017cno\u015bci s\u0105 dla ciebie najwa\u017cniejsze, aby je szanowa\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What parts of your independence are most important for me to respect?';
UPDATE questions
SET translations = '{"en": "What\u2019s the kindest thing someone did for you?", "da": "Hvad er det venligste, nogen nogensinde har gjort for dig?", "de": "Was ist das Netteste, das jemand je f\u00fcr dich getan hat?", "es": "\u00bfCu\u00e1l es la cosa m\u00e1s amable que alguien ha hecho por ti?", "pt": "Qual foi a coisa mais gentil que algu\u00e9m j\u00e1 fez por voc\u00ea?", "ro": "Care este cel mai frumos gest pe care cineva l-a f\u0103cut pentru tine?", "fr": "Quelle est la chose la plus gentille que quelqu\u2019un ait faite pour toi ?", "it": "Qual \u00e8 stata la cosa pi\u00f9 gentile che qualcuno ha fatto per te?", "fi": "Mik\u00e4 on yst\u00e4v\u00e4llisin asia, jonka joku on tehnyt puolestasi?", "nl": "Wat is het vriendelijkste dat iemand voor jou heeft gedaan?", "no": "Hva er den snilleste tingen noen har gjort for deg?", "sv": "Vad \u00e4r det sn\u00e4llaste n\u00e5gon har gjort f\u00f6r dig?", "pl": "Jak\u0105 naj\u017cyczliwsz\u0105 rzecz kto\u015b dla ciebie zrobi\u0142?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s the kindest thing someone did for you?';
UPDATE questions
SET translations = '{"en": "What do you do when your motivation goes missing?", "da": "Hvad g\u00f8r du, n\u00e5r din motivation forsvinder?", "de": "Was machst du, wenn deine Motivation verschwindet?", "es": "\u00bfQu\u00e9 haces cuando pierdes la motivaci\u00f3n?", "pt": "O que voc\u00ea faz quando perde a motiva\u00e7\u00e3o?", "ro": "Ce faci c\u00e2nd \u00ee\u021bi pierzi motiva\u021bia?", "fr": "Que fais-tu quand ta motivation dispara\u00eet ?", "it": "Cosa fai quando la tua motivazione scompare?", "fi": "Mit\u00e4 teet, kun motivaatiosi katoaa?", "nl": "Wat doe je als je motivatie weg is?", "no": "Hva gj\u00f8r du n\u00e5r motivasjonen forsvinner?", "sv": "Vad g\u00f6r du n\u00e4r din motivation f\u00f6rsvinner?", "pl": "Co robisz, gdy brakuje ci motywacji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you do when your motivation goes missing?';
UPDATE questions
SET translations = '{"en": "How do you define \u201csuccess\u201d in life (without numbers)?", "da": "Hvordan definerer du \u201csucces\u201d i livet (uden tal)?", "de": "Wie definierst du \u201eErfolg\u201c im Leben (ohne Zahlen)?", "es": "\u00bfC\u00f3mo defines el \u201c\u00e9xito\u201d en la vida (sin n\u00fameros)?", "pt": "Como voc\u00ea define \u201csucesso\u201d na vida (sem n\u00fameros)?", "ro": "Cum define\u0219ti \u201esuccesul\u201d \u00een via\u021b\u0103 (f\u0103r\u0103 cifre)?", "fr": "Comment d\u00e9finis-tu le \u00ab succ\u00e8s \u00bb dans la vie (sans chiffres) ?", "it": "Come definisci il \"successo\" nella vita (senza numeri)?", "fi": "Miten m\u00e4\u00e4rittelet \"menestyksen\" el\u00e4m\u00e4ss\u00e4 (ilman numeroita)?", "nl": "Hoe definieer je \u201csucces\u201d in het leven (zonder cijfers)?", "no": "Hvordan definerer du \"suksess\" i livet (uten tall)?", "sv": "Hur definierar du \"framg\u00e5ng\" i livet (utan siffror)?", "pl": "Jak definiujesz \u201esukces\u201d w \u017cyciu (bez liczb)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you define “success” in life (without numbers)?';
UPDATE questions
SET translations = '{"en": "How do you like to spend time alone, and what does that give you?", "da": "Hvordan kan du lide at tilbringe tid alene, og hvad giver det dig?", "de": "Wie verbringst du gerne Zeit allein, und was gibt dir das?", "es": "\u00bfC\u00f3mo te gusta pasar tiempo a solas, y qu\u00e9 te aporta eso?", "pt": "Como voc\u00ea gosta de passar o tempo sozinho(a), e o que isso te traz?", "ro": "Cum \u00ee\u021bi place s\u0103 petreci timpul singur(\u0103) \u0219i ce \u00ee\u021bi ofer\u0103 asta?", "fr": "Comment aimes-tu passer du temps seul(e), et qu\u2019est-ce que cela t\u2019apporte ?", "it": "Come ti piace trascorrere del tempo da solo e cosa ti d\u00e0 questo?", "fi": "Miten tykk\u00e4\u00e4t viett\u00e4\u00e4 aikaa yksin, ja mit\u00e4 se sinulle antaa?", "nl": "Hoe breng je graag tijd alleen door, en wat levert dat je op?", "no": "Hvordan liker du \u00e5 tilbringe tid alene, og hva gir det deg?", "sv": "Hur gillar du att tillbringa tid ensam, och vad ger det dig?", "pl": "Jak lubisz sp\u0119dza\u0107 czas samemu i co ci to daje?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you like to spend time alone, and what does that give you?';
UPDATE questions
SET translations = '{"en": "What\u2019s something new you\u2019ve learned about love from being with me?", "da": "Hvad er noget nyt, du har l\u00e6rt om k\u00e6rlighed ved at v\u00e6re sammen med mig?", "de": "Was hast du Neues \u00fcber die Liebe gelernt, seit du mit mir zusammen bist?", "es": "\u00bfQu\u00e9 has aprendido nuevo sobre el amor desde que est\u00e1s conmigo?", "pt": "O que voc\u00ea aprendeu de novo sobre o amor estando comigo?", "ro": "Ce ai \u00eenv\u0103\u021bat nou despre dragoste fiind cu mine?", "fr": "Qu\u2019as-tu appris de nouveau sur l\u2019amour en \u00e9tant avec moi ?", "it": "Qualcosa di nuovo che hai imparato sull''amore stando con me?", "fi": "Mik\u00e4 on jotain uutta, mit\u00e4 olet oppinut rakkaudesta ollessasi kanssani?", "nl": "Wat is iets nieuws dat je over liefde hebt geleerd door met mij samen te zijn?", "no": "Hva er noe nytt du har l\u00e6rt om kj\u00e6rlighet ved \u00e5 v\u00e6re sammen med meg?", "sv": "Vad \u00e4r n\u00e5got nytt du har l\u00e4rt dig om k\u00e4rlek fr\u00e5n att vara med mig?", "pl": "Czego nowego nauczy\u0142e\u015b si\u0119 o mi\u0142o\u015bci, b\u0119d\u0105c ze mn\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What’s something new you’ve learned about love from being with me?';
UPDATE questions
SET translations = '{"en": "Do you think we\u2019ve helped each other grow as people? How?", "da": "Tror du, vi har hjulpet hinanden med at vokse som mennesker? Hvordan?", "de": "Glaubst du, dass wir uns gegenseitig geholfen haben, als Menschen zu wachsen? Wie?", "es": "\u00bfCrees que nos hemos ayudado a crecer como personas? \u00bfC\u00f3mo?", "pt": "Voc\u00ea acha que ajudamos um ao outro a crescer como pessoas? Como?", "ro": "Crezi c\u0103 ne-am ajutat reciproc s\u0103 cre\u0219tem ca oameni? Cum?", "fr": "Penses-tu que nous nous sommes aid\u00e9s \u00e0 grandir comme personnes ? Comment ?", "it": "Pensi che ci siamo aiutati a crescere come persone? In che modo?", "fi": "Mielest\u00e4si olemme auttaneet toisiamme kasvamaan ihmisin\u00e4? Miten?", "nl": "Denk je dat we elkaar hebben geholpen om als mensen te groeien? Hoe?", "no": "Tror du vi har hjulpet hverandre med \u00e5 vokse som mennesker? Hvordan?", "sv": "Tror du att vi har hj\u00e4lpt varandra att v\u00e4xa som personer? Hur?", "pl": "Czy my\u015blisz, \u017ce pomogli\u015bmy sobie nawzajem w rozwoju jako ludzie? W jaki spos\u00f3b?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'Do you think we’ve helped each other grow as people? How?';
UPDATE questions
SET translations = '{"en": "How do you know it\u2019s time to let something end?", "da": "Hvordan ved du, at det er tid til at afslutte noget?", "de": "Woran erkennst du, dass es Zeit ist, etwas zu beenden?", "es": "\u00bfC\u00f3mo sabes que es momento de dejar algo ir?", "pt": "Como voc\u00ea sabe que \u00e9 hora de deixar algo acabar?", "ro": "Cum \u0219tii c\u0103 este timpul s\u0103 \u00eenchei ceva?", "fr": "Comment sais-tu qu\u2019il est temps de mettre fin \u00e0 quelque chose ?", "it": "Come fai a sapere che \u00e8 il momento di far finire qualcosa?", "fi": "Miten tied\u00e4t, ett\u00e4 on aika p\u00e4\u00e4st\u00e4\u00e4 jotain loppumaan?", "nl": "Hoe weet je wanneer het tijd is om iets te laten eindigen?", "no": "Hvordan vet du at det er p\u00e5 tide \u00e5 la noe ta slutt?", "sv": "Hur vet du n\u00e4r det \u00e4r dags att l\u00e5ta n\u00e5got ta slut?", "pl": "Jak wiesz, \u017ce nadszed\u0142 czas, aby co\u015b zako\u0144czy\u0107?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'How do you know it’s time to let something end?';
UPDATE questions
SET translations = '{"en": "What do you owe your future self?", "da": "Hvad skylder du dit fremtidige jeg?", "de": "Was schuldest du deinem zuk\u00fcnftigen Ich?", "es": "\u00bfQu\u00e9 le debes a tu yo del futuro?", "pt": "O que voc\u00ea deve ao seu eu do futuro?", "ro": "Ce datorezi sinelui t\u0103u din viitor?", "fr": "Que dois-tu \u00e0 ton toi futur ?", "it": "Cosa devi al tuo io futuro?", "fi": "Mit\u00e4 olet velkaa tulevalle itsellesi?", "nl": "Wat ben je je toekomstige zelf verschuldigd?", "no": "Hva skylder du din fremtidige selv?", "sv": "Vad \u00e4r du skyldig din framtida jag?", "pl": "Co jeste\u015b winien swojemu przysz\u0142emu ja?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'What do you owe your future self?';
UPDATE questions
SET translations = '{"en": "When do you feel most attractive?", "da": "Hvorn\u00e5r f\u00f8ler du dig mest attraktiv?", "de": "Wann f\u00fchlst du dich am attraktivsten?", "es": "\u00bfCu\u00e1ndo te sientes m\u00e1s atractivo(a)?", "pt": "Quando voc\u00ea se sente mais atraente?", "ro": "C\u00e2nd te sim\u021bi cel mai atr\u0103g\u0103tor(are)?", "fr": "Quand te sens-tu le/la plus attirant(e) ?", "it": "Quando ti senti pi\u00f9 attraente?", "fi": "Milloin tunnet itsesi kaikkein vieh\u00e4tt\u00e4vimm\u00e4ksi?", "nl": "Wanneer voel je je het meest aantrekkelijk?", "no": "N\u00e5r f\u00f8ler du deg mest attraktiv?", "sv": "N\u00e4r k\u00e4nner du dig mest attraktiv?", "pl": "Kiedy czujesz si\u0119 najbardziej atrakcyjny?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'Deep Talks'
  AND translations->>'en' = 'When do you feel most attractive?';