UPDATE questions
SET translations = '{"en": "Which of us is most likely to hide snacks from the others?", "da": "Hvem gemmer sandsynligvis snacks fra de andre?", "de": "Wer von uns versteckt wahrscheinlich Snacks vor den anderen?", "es": "\u00bfQui\u00e9n de nosotros es m\u00e1s probable que esconda los bocadillos de los dem\u00e1s?", "pt": "Quem de n\u00f3s \u00e9 mais prov\u00e1vel esconder lanches dos outros?", "ro": "Cine dintre noi ascunde gust\u0103ri de ceilal\u021bi?", "fr": "Qui parmi nous cache probablement des snacks aux autres ?", "it": "Quale di noi \u00e8 pi\u00f9 probabile che nasconda snack agli altri?", "fi": "Kumpi meist\u00e4 todenn\u00e4k\u00f6isimmin piilottaa herkkuja muilta?", "nl": "Wie van ons is het meest waarschijnlijk om snacks voor de anderen te verstoppen?", "no": "Hvem av oss er mest sannsynlig til \u00e5 skjule snacks for de andre?", "sv": "Vilken av oss \u00e4r mest ben\u00e4gen att g\u00f6mma snacks fr\u00e5n de andra?", "pl": "Kto z nas jest najbardziej sk\u0142onny chowa\u0107 przek\u0105ski przed innymi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Which of us is most likely to hide snacks from the others?';
UPDATE questions
SET translations = '{"en": "Who always forgets everyone\u2019s birthdays until the last minute?", "da": "Hvem glemmer altid alles f\u00f8dselsdage indtil sidste \u00f8jeblik?", "de": "Wer vergisst immer alle Geburtstage bis zur letzten Minute?", "es": "\u00bfQui\u00e9n siempre olvida los cumplea\u00f1os de todos hasta el \u00faltimo minuto?", "pt": "Quem sempre esquece os anivers\u00e1rios de todos at\u00e9 o \u00faltimo minuto?", "ro": "Cine uit\u0103 mereu zilele de na\u0219tere ale tuturor p\u00e2n\u0103 \u00een ultimul moment?", "fr": "Qui oublie toujours les anniversaires de tout le monde jusqu\u2019\u00e0 la derni\u00e8re minute ?", "it": "Chi dimentica sempre i compleanni di tutti fino all''ultimo minuto?", "fi": "Kuka unohtaa aina kaikkien syntym\u00e4p\u00e4iv\u00e4t viime hetkell\u00e4?", "nl": "Wie vergeet altijd ieders verjaardag tot het laatste moment?", "no": "Hvem glemmer alltid alles bursdager til siste liten?", "sv": "Vem gl\u00f6mmer alltid allas f\u00f6delsedagar tills i sista minuten?", "pl": "Kto zawsze zapomina o urodzinach wszystkich do ostatniej chwili?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who always forgets everyone’s birthdays until the last minute?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to start laughing when they shouldn\u2019t?", "da": "Hvem begynder sandsynligvis at grine, n\u00e5r de ikke burde?", "de": "Wer f\u00e4ngt wahrscheinlich an zu lachen, wenn er nicht sollte?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que empiece a re\u00edr cuando no deber\u00eda?", "pt": "Quem \u00e9 mais prov\u00e1vel de come\u00e7ar a rir quando n\u00e3o devia?", "ro": "Cine e cel mai probabil s\u0103 \u00eenceap\u0103 s\u0103 r\u00e2d\u0103 c\u00e2nd nu ar trebui?", "fr": "Qui est le plus susceptible de rire quand il ne faut pas ?", "it": "Chi \u00e8 pi\u00f9 probabile che inizi a ridere quando non dovrebbe?", "fi": "Kuka todenn\u00e4k\u00f6isesti alkaa nauraa, kun ei pit\u00e4isi?", "nl": "Wie is het meest waarschijnlijk om te beginnen met lachen wanneer dat niet gepast is?", "no": "Hvem er mest sannsynlig til \u00e5 begynne \u00e5 le n\u00e5r de ikke burde?", "sv": "Vem \u00e4r mest ben\u00e4gen att b\u00f6rja skratta n\u00e4r de inte borde?", "pl": "Kto najprawdopodobniej zacznie si\u0119 \u015bmia\u0107, kiedy nie powinien?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to start laughing when they shouldn’t?';UPDATE questions
SET translations = '{"en": "What\u2019s the funniest thing that\u2019s ever happened during dinner?", "da": "Hvad er det sjoveste, der nogensinde er sket under middagen?", "de": "Was ist das Lustigste, das jemals beim Abendessen passiert ist?", "es": "\u00bfCu\u00e1l es la cosa m\u00e1s divertida que ha pasado durante la cena?", "pt": "Qual \u00e9 a coisa mais engra\u00e7ada que j\u00e1 aconteceu durante o jantar?", "ro": "Care e cel mai amuzant lucru care s-a \u00eent\u00e2mplat vreodat\u0103 la cin\u0103?", "fr": "Quelle est la chose la plus dr\u00f4le qui soit arriv\u00e9e pendant le d\u00eener ?", "it": "Qual \u00e8 la cosa pi\u00f9 divertente che ti sia mai successa durante la cena?", "fi": "Mik\u00e4 on hauskin asia, joka on koskaan tapahtunut illallisen aikana?", "nl": "Wat is het grappigste dat ooit tijdens het diner is gebeurd?", "no": "Hva er det morsomste som noen gang har skjedd under middagen?", "sv": "Vad \u00e4r det roligaste som n\u00e5gonsin har h\u00e4nt under middagen?", "pl": "Co by\u0142o naj\u015bmieszniejszego, co kiedykolwiek si\u0119 zdarzy\u0142o podczas kolacji?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'What’s the funniest thing that’s ever happened during dinner?';
UPDATE questions
SET translations = '{"en": "Who\u2019s best at cheering people up?", "da": "Hvem er bedst til at opmuntre folk?", "de": "Wer kann am besten andere aufmuntern?", "es": "\u00bfQui\u00e9n es el mejor animando a los dem\u00e1s?", "pt": "Quem \u00e9 o melhor a animar as pessoas?", "ro": "Cine e cel mai bun la a \u00eenveseli oamenii?", "fr": "Qui est le meilleur pour remonter le moral des gens ?", "it": "Chi \u00e8 il migliore nel tirare su il morale alle persone?", "fi": "Kuka on paras pirist\u00e4m\u00e4\u00e4n ihmisi\u00e4?", "nl": "Wie is het beste in het opvrolijken van mensen?", "no": "Hvem er best til \u00e5 muntre folk opp?", "sv": "Vem \u00e4r b\u00e4st p\u00e5 att muntra upp folk?", "pl": "Kto jest najlepszy w pocieszaniu ludzi?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s best at cheering people up?';
UPDATE questions
SET translations = '{"en": "Who takes the longest to get ready for family outings?", "da": "Hvem bruger l\u00e6ngst tid p\u00e5 at g\u00f8re sig klar til familieudflugter?", "de": "Wer braucht am l\u00e4ngsten, um sich f\u00fcr Familienausfl\u00fcge fertigzumachen?", "es": "\u00bfQui\u00e9n tarda m\u00e1s en prepararse para las salidas familiares?", "pt": "Quem demora mais para se arrumar para os passeios em fam\u00edlia?", "ro": "Cine se preg\u0103te\u0219te cel mai mult pentru ie\u0219irile \u00een familie?", "fr": "Qui met le plus de temps \u00e0 se pr\u00e9parer pour les sorties en famille ?", "it": "Chi impiega pi\u00f9 tempo a prepararsi per le uscite di famiglia?", "fi": "Kuka vie eniten aikaa valmistautuakseen perheretkiin?", "nl": "Wie heeft de meeste tijd nodig om zich klaar te maken voor gezinsuitstapjes?", "no": "Hvem bruker lengst tid p\u00e5 \u00e5 gj\u00f8re seg klar til familieturer?", "sv": "Vem tar l\u00e4ngst tid p\u00e5 sig att g\u00f6ra sig redo f\u00f6r familjeutflykter?", "pl": "Kto potrzebuje najwi\u0119cej czasu, \u017ceby si\u0119 przygotowa\u0107 na rodzinne wyj\u015bcia?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who takes the longest to get ready for family outings?';
UPDATE questions
SET translations = '{"en": "Who in our family has the biggest collection of random stuff?", "da": "Hvem i vores familie har den st\u00f8rste samling af tilf\u00e6ldige ting?", "de": "Wer in unserer Familie hat die gr\u00f6\u00dfte Sammlung zuf\u00e4lliger Sachen?", "es": "\u00bfQui\u00e9n en nuestra familia tiene la colecci\u00f3n m\u00e1s grande de cosas al azar?", "pt": "Quem na nossa fam\u00edlia tem a maior cole\u00e7\u00e3o de coisas aleat\u00f3rias?", "ro": "Cine din familia noastr\u0103 are cea mai mare colec\u021bie de lucruri \u00eent\u00e2mpl\u0103toare?", "fr": "Qui dans notre famille a la plus grande collection d\u2019objets al\u00e9atoires ?", "it": "Chi nella nostra famiglia ha la collezione pi\u00f9 grande di cose strane?", "fi": "Kell\u00e4 perheess\u00e4mme on suurin kokoelma satunnaisia tavaroita?", "nl": "Wie in onze familie heeft de grootste verzameling van willekeurige spullen?", "no": "Hvem i familien v\u00e5r har den st\u00f8rste samlingen av tilfeldige ting?", "sv": "Vem i v\u00e5r familj har den st\u00f6rsta samlingen av slumpm\u00e4ssiga saker?", "pl": "Kto w naszej rodzinie ma najwi\u0119ksz\u0105 kolekcj\u0119 r\u00f3\u017cnych rzeczy?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who in our family has the biggest collection of random stuff?';
UPDATE questions
SET translations = '{"en": "Who\u2019s best at keeping secrets from Mom or Dad?", "da": "Hvem er bedst til at holde hemmeligheder for mor eller far?", "de": "Wer kann am besten Geheimnisse vor Mama oder Papa bewahren?", "es": "\u00bfQui\u00e9n es el mejor guardando secretos de mam\u00e1 o pap\u00e1?", "pt": "Quem \u00e9 o melhor a guardar segredos da m\u00e3e ou do pai?", "ro": "Cine e cel mai bun la a \u021bine secrete fa\u021b\u0103 de mama sau tata?", "fr": "Qui est le meilleur pour garder des secrets \u00e0 maman ou papa ?", "it": "Chi \u00e8 il migliore a tenere segreti, mamma o pap\u00e0?", "fi": "Kuka on paras pit\u00e4m\u00e4\u00e4n salaisuuksia \u00e4idilt\u00e4 tai is\u00e4lt\u00e4?", "nl": "Wie is het beste in het geheimhouden van geheimen voor Mama of Papa?", "no": "Hvem er best til \u00e5 holde hemmeligheter for mamma eller pappa?", "sv": "Vem \u00e4r b\u00e4st p\u00e5 att h\u00e5lla hemligheter fr\u00e5n mamma eller pappa?", "pl": "Kto lepiej potrafi trzyma\u0107 sekrety przed mam\u0105 lub tat\u0105?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s best at keeping secrets from Mom or Dad?';
UPDATE questions
SET translations = '{"en": "Who in our family is the best at fixing things (even if it\u2019s with duct tape)?", "da": "Hvem i vores familie er bedst til at fikse ting (selv med gaffatape)?", "de": "Wer in unserer Familie ist am besten im Reparieren (auch mit Klebeband)?", "es": "\u00bfQui\u00e9n en nuestra familia es el mejor arreglando cosas (aunque sea con cinta adhesiva)?", "pt": "Quem na nossa fam\u00edlia \u00e9 o melhor a consertar coisas (mesmo com fita adesiva)?", "ro": "Cine din familia noastr\u0103 e cel mai bun la reparat lucruri (chiar \u0219i cu band\u0103 adeziv\u0103)?", "fr": "Qui dans notre famille est le meilleur pour r\u00e9parer les choses (m\u00eame avec du ruban adh\u00e9sif) ?", "it": "Chi nella nostra famiglia \u00e8 il migliore a riparare le cose (anche se \u00e8 con il nastro adesivo)?", "fi": "Kuka perheess\u00e4mme on paras korjaamaan asioita (vaikka se olisi teipill\u00e4)?", "nl": "Wie in onze familie is het beste in het repareren van dingen (zelfs als het met ducttape is)?", "no": "Hvem i familien v\u00e5r er best til \u00e5 fikse ting (selv om det er med duct tape)?", "sv": "Vem i v\u00e5r familj \u00e4r b\u00e4st p\u00e5 att laga saker (\u00e4ven om det \u00e4r med silvertejp)?", "pl": "Kto w naszej rodzinie jest najlepszy w naprawianiu rzeczy (nawet je\u015bli to za pomoc\u0105 ta\u015bmy klej\u0105cej)?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who in our family is the best at fixing things (even if it’s with duct tape)?';
UPDATE questions
SET translations = '{"en": "Who\u2019s most likely to blink in every photo?", "da": "Hvem blinker mest p\u00e5 billeder?", "de": "Wer blinzelt auf jedem Foto?", "es": "\u00bfQui\u00e9n es m\u00e1s probable que parpadee en todas las fotos?", "pt": "Quem \u00e9 mais prov\u00e1vel piscar em todas as fotos?", "ro": "Cine clipe\u0219te cel mai des \u00een poze?", "fr": "Qui cligne toujours des yeux sur les photos ?", "it": "Chi \u00e8 pi\u00f9 probabile che sbatti le palpebre in ogni foto?", "fi": "Kuka todenn\u00e4k\u00f6isesti r\u00e4p\u00e4ytt\u00e4\u00e4 silmi\u00e4\u00e4n jokaisessa valokuvassa?", "nl": "Wie is het meest waarschijnlijk om in elke foto te knipperen?", "no": "Hvem er mest sannsynlig til \u00e5 blunke p\u00e5 hvert bilde?", "sv": "Vem \u00e4r mest sannolikt att blinka p\u00e5 varje foto?", "pl": "Kto najprawdopodobniej mruga na ka\u017cdym zdj\u0119ciu?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who’s most likely to blink in every photo?';
UPDATE questions
SET translations = '{"en": "Who in our family starts playing Christmas music way too early?", "da": "Hvem i vores familie begynder at spille julemusik alt for tidligt?", "de": "Wer in unserer Familie spielt viel zu fr\u00fch Weihnachtsmusik?", "es": "\u00bfQui\u00e9n en nuestra familia empieza a poner m\u00fasica navide\u00f1a demasiado pronto?", "pt": "Quem na nossa fam\u00edlia come\u00e7a a tocar m\u00fasica de Natal cedo demais?", "ro": "Cine din familia noastr\u0103 pune muzic\u0103 de Cr\u0103ciun prea devreme?", "fr": "Qui dans notre famille commence la musique de No\u00ebl beaucoup trop t\u00f4t ?", "it": "Chi nella nostra famiglia inizia a suonare la musica di Natale troppo presto?", "fi": "Kuka perheess\u00e4mme alkaa soittaa joulumusiikkia liian aikaisin?", "nl": "Wie in onze familie begint er veel te vroeg met het afspelen van kerstmuziek?", "no": "Hvem i familien v\u00e5r begynner \u00e5 spille julesanger altfor tidlig?", "sv": "Vem i v\u00e5r familj b\u00f6rjar spela julmusik alldeles f\u00f6r tidigt?", "pl": "Kto w naszej rodzinie zaczyna gra\u0107 muzyk\u0119 \u015bwi\u0105teczn\u0105 zdecydowanie za wcze\u015bnie?"}'::jsonb,
    updated_at = NOW()
WHERE category_name = 'History Talks'
  AND translations->>'en' = 'Who in our family starts playing Christmas music way too early?';